### ISSUE TITLE
DFF085D0-2D96-420F-91A2-A2650A815E6E/20210104143812

### ISSUE THREAD

**Issue by Harkuluz** [docker/for-win#10000]
dignostic id = DFF085D0-2D96-420F-91A2-A2650A815E6E/20210104143812
=====
logs
======

```
Version: 3.0.0 (50684)
Sha1: b7108cdfefccc66549bd6b9ee3373e8dd40b8ac1
Started on: 2021/01/04 20:05:54.513
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 1909
Build: 18363
BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
File: C:\Users\Asus\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[20:05:54.682][GUI               ][Info   ] Starting...
[20:05:54.837][ComponentVersions ][Info   ] Edition community
[20:05:54.846][ComponentVersions ][Info   ] Edition community
[20:05:54.998][LoggingMessageHandler][Info   ] [efd052eb] <GoBackendClient start> GET http://localhost/ping
[20:05:55.040][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[20:05:55.301][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[20:05:55.350][LoggingMessageHandler][Info   ] [a77e6b75] <GoBackendClient start> GET http://localhost/ping
[20:05:55.356][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[20:05:55.359][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[20:05:55.660][LoggingMessageHandler][Info   ] [11549d65] <GoBackendClient start> GET http://localhost/ping
[20:05:55.660][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[20:05:55.961][LoggingMessageHandler][Info   ] [496d3c7d] <GoBackendClient start> GET http://localhost/ping
[20:05:55.961][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[20:05:56.089][GoBackendProcess  ][Info   ] Started
[20:05:56.090][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[20:05:56.094][SegmentApi        ][Info   ] Usage statistic: Identify
[20:05:56.262][LoggingMessageHandler][Info   ] [f11e4f0e] <GoBackendClient start> GET http://localhost/ping
[20:05:56.797][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[20:05:57.098][LoggingMessageHandler][Info   ] [bd28a362] <GoBackendClient start> GET http://localhost/ping
[20:05:57.098][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[20:05:57.400][LoggingMessageHandler][Info   ] [1efaa576] <GoBackendClient start> GET http://localhost/ping
[20:05:57.400][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[20:05:57.701][LoggingMessageHandler][Info   ] [71d62c82] <GoBackendClient start> GET http://localhost/ping
[20:05:57.701][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[20:05:58.003][LoggingMessageHandler][Info   ] [9f1e08ef] <GoBackendClient start> GET http://localhost/ping
[20:05:58.063][LoggingMessageHandler][Info   ] [9f1e08ef] <GoBackendClient end> GET http://localhost/ping -> 200 OK (took 59ms)
[20:05:58.081][GoBackendClient   ][Info   ] backend API ready
[20:05:58.226][LoggingMessageHandler][Info   ] [57055f6d] <GoBackendClient start> GET http://localhost/features
[20:05:58.241][LoggingMessageHandler][Info   ] [57055f6d] <GoBackendClient end> GET http://localhost/features -> 200 OK (took 14ms)
[20:05:58.596][GoBackendProcess  ][Info   ] msg="starting backend server"
[20:05:58.597][GoBackendProcess  ][Info   ] msg="started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl"
[20:05:58.597][GoBackendProcess  ][Info   ] msg="listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection"
[20:05:58.597][GoBackendProcess  ][Error  ] msg="unable to query WslEngineEnabled state after 0s. Last error was Get \"http://unix/settings\": open \\\\.\\pipe\\dockerWebApiServer: The system cannot find the file specified."
[20:05:58.597][GoBackendProcess  ][Info   ] msg="adding routes for /docker.tar"
[20:05:58.597][GoBackendProcess  ][Info   ] msg="adding routes for /kube-images.tar"
[20:05:58.597][GoBackendProcess  ][Info   ] msg="adding routes for /services.tar -> C:\\Program Files\\Docker\\Docker\\resources\\services.tar"
[20:05:58.597][GoBackendProcess  ][Info   ] msg="adding routes for /docker.tar"
[20:05:58.597][GoBackendProcess  ][Info   ] msg="adding routes for /kube-images.tar"
[20:05:58.597][GoBackendProcess  ][Info   ] msg="adding routes for /services.tar -> C:\\Program Files\\Docker\\Docker\\resources\\services.tar"
[20:05:58.597][GoBackendProcess  ][Info   ] msg="external: GET /ping 200 \"DockerDesktopCSharp\" \"\""
[20:05:58.597][GoBackendProcess  ][Info   ] msg="external: GET /features 200 \"DockerDesktopCSharp\" \"\""
[20:05:58.668][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[20:05:58.668][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\docker_cli
[20:05:58.668][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[20:05:58.668][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[20:06:02.148][SegmentApi        ][Info   ] Usage statistic: appLaunched
[20:06:02.163][SegmentApi        ][Info   ] Usage statistic: heartbeat
[20:06:02.895][SegmentApi        ][Warning] Failed to Identify: An error occurred while sending the request.
[20:06:02.895][SegmentApi        ][Warning] Failed to track event appLaunched: An error occurred while sending the request.
[20:06:02.895][SegmentApi        ][Warning] Failed to track event heartbeat: An error occurred while sending the request.
[20:06:07.991][GoBackendProcess  ][Error  ] msg="unable to query WslEngineEnabled state after 10.0080815s. Last error was Get \"http://unix/settings\": open \\\\.\\pipe\\dockerWebApiServer: The system cannot find the file specified."
[20:06:25.955][LoggingMessageHandler][Info   ] [5d9c1d57] <Server start> GET http://unix/settings
[20:06:26.869][LoggingMessageHandler][Info   ] [5d9c1d57] <Server end> GET http://unix/settings -> 200 OK (took 914ms)
[20:06:27.613][GoBackendProcess  ][Info   ] msg="NewSharer: WSL2 engine is enabled so no file sharer is required."
[20:06:27.613][GoBackendProcess  ][Info   ] msg="enabling filesystem caching"
[20:06:27.626][GoBackendProcess  ][Info   ] msg="filesystem exports are:  (2)"
[20:06:27.738][GoBackendProcess  ][Info   ] msg="volume control server listening on \\\\.\\pipe\\dockerVolume"
[20:06:27.822][GoBackendProcess  ][Info   ] msg="filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3"
[20:06:27.847][GoBackendProcess  ][Info   ] msg="file ownership will be determined by the calling user (\"fake owner\" mode)"
[20:06:27.847][GoBackendProcess  ][Info   ] msg="using mfsymlinks"
[20:06:52.301][LoggingMessageHandler][Info   ] [a39b7192] <BackendAPIClient start> GET http://backend/version
[20:06:53.421][LoggingMessageHandler][Info   ] [a39b7192] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 1120ms)
[20:06:53.506][LoggingMessageHandler][Info   ] [65250278] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[20:06:53.817][LoggingMessageHandler][Info   ] [65250278] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 311ms)
[20:06:53.837][LoggingMessageHandler][Info   ] [3cdd7f39] <BackendAPIClient start> POST http://backend/migrate/app
[20:06:53.853][LoggingMessageHandler][Info   ] [3cdd7f39] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 16ms)
[20:07:02.708][Updater           ][Info   ] Launcher process exited with 4294967291
[20:07:02.720][Engines           ][Debug  ] Starting
[20:07:02.732][LoggingMessageHandler][Info   ] [9177ffe2] <BackendAPIClient start> POST http://backend/versionpack/enable
[20:07:03.141][LoggingMessageHandler][Info   ] [9177ffe2] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 409ms)
[20:07:03.146][LoggingMessageHandler][Info   ] [b8dcf5de] <BackendAPIClient start> POST http://backend/cloudcli/toggle
[20:07:03.226][LoggingMessageHandler][Info   ] [b8dcf5de] <BackendAPIClient end> POST http://backend/cloudcli/toggle -> 204 NoContent (took 80ms)
[20:07:03.242][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[20:07:03.243][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[20:07:03.249][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxWSL2
[20:07:03.273][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[20:07:03.275][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1609771023}
[20:07:03.276][SystrayNotifications][Info   ] Docker is starting
[20:07:03.281][LoggingMessageHandler][Info   ] [64ae25e5] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[20:07:03.929][WSL2Provisioning  ][Info   ] Checking docker-desktop
[20:07:03.935][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\Asus\AppData\Local\Docker\wsl\distro
[20:07:04.206][Updater           ][Info   ] Launcher process exited with 4294967291
[20:07:10.102][LoggingMessageHandler][Info   ] [64ae25e5] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 6821ms)
[20:07:37.036][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\Asus\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0x80041002


 stderr: 
[20:07:37.098][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[20:07:37.215][LinuxWSL2Engine   ][Info   ] Stopping engine
[20:07:37.313][LoggingMessageHandler][Info   ] [bf2f153c] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[20:07:38.406][LoggingMessageHandler][Info   ] [bf2f153c] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 1092ms)
[20:07:38.946][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[20:07:38.946][LoggingMessageHandler][Info   ] [27535809] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[20:07:39.101][WSL2Provisioning  ][Info   ] Checking docker-desktop
[20:07:39.101][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\Asus\AppData\Local\Docker\wsl\distro
[20:07:39.181][LoggingMessageHandler][Info   ] [27535809] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 235ms)
[20:08:05.625][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\Asus\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0x80041002


 stderr: 
[20:08:05.626][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[20:08:05.714][LinuxWSL2Engine   ][Info   ] Stopping engine
[20:08:05.791][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[20:08:05.791][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[20:08:05.791][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxWSL2
[20:08:05.792][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1609771085}
[20:08:05.984][SystrayNotifications][Error  ] System.InvalidOperationException: Failed to deploy distro docker-desktop to C:\Users\Asus\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0x80041002


 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
[20:08:06.058][GUI               ][Info   ] Sending Bugsnag report 81b89dd8-00a3-4d72-93b7-52de49b90dd4...
[20:08:06.407][GUI               ][Info   ] Bugsnag report 81b89dd8-00a3-4d72-93b7-52de49b90dd4 sent
[20:08:06.408][SegmentApi        ][Info   ] Usage statistic: eventCrash
[20:08:06.423][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[20:08:07.530][Engines           ][Error  ] Start failed with Failed to deploy distro docker-desktop to C:\Users\Asus\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0x80041002


 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__21.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 102)
[20:08:07.532][SegmentApi        ][Warning] Failed to track event eventCrash: An error occurred while sending the request.
[20:08:12.691][GoBackendProcess  ][Info   ] msg="external: GET /diagnostics/goroutines 200 \"Go-http-client/1.1\" \"\""
[20:08:12.691][GoBackendProcess  ][Info   ] msg="external: GET /ping 200 \"DockerDesktopGo\" \"\""
[20:08:12.739][GoBackendProcess  ][Info   ] msg="external: GET /events 200 \"DockerDesktopGo\" \"\""
[20:08:12.762][GoBackendProcess  ][Info   ] msg="external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\""
[20:10:55.618][Diagnostics       ][Info   ] Uploading diagnostics DFF085D0-2D96-420F-91A2-A2650A815E6E/20210104143812
[20:11:00.749][Diagnostics       ][Info   ] Uploaded succesfully diagnostics DFF085D0-2D96-420F-91A2-A2650A815E6E/20210104143812
[20:13:19.758][ErrorReportWindow ][Info   ] Open logs
=====================================
```

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  DFF085D0-2D96-420F-91A2-A2650A815E6E/20210104143812

### Expected behavior
after installing the docker desktop I try to start the docker desktop by running the docker desktop shortcut it should start the docker

### Actual behavior
but docker desktop not start and open a window that An error occurred
### Information

  - Windows Version: windows 10 pro
  - Docker Desktop Version: latest version
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: **NO**

### Steps to reproduce the behavior

  1. Install the docker desktop
  2. Start the docker decktop by double-clicking on docker desktop shortcut
  3. It will show an error occurred message

**Comment by stephen-turner** [comment]
It appears that WSL 2 is not set up correctly. Try these instructions from Microsoft: https://aka.ms/wsl2-install

**Comment by stephen-turner** [comment]
And congratulations on getting ticket number 10000. 😄
