### ISSUE TITLE
Docker crashing when auto starting on Windows 10 Professional

### ISSUE THREAD

**Issue by davoutuk** [docker/for-win#1002]
I have Docker (latest version) auto running on my Windows 10 PC.  It crashes and reports the following error:
Docker command did not complete within the allowed timeout. Output: 
   at Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 152
   at Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 49
   at Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 197
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 168
   at Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 65
   at Docker.Backend.BackendServer.<Run>b__5_11(Object[] args) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\BackendServer.cs:line 54
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

From the Docker 'Settings' UI 'Reset' menu, if I restart  Docker then everything works fine.

Any ideas on how to fix this?

The log file shows:

[05:52:51.691][SambaShare     ][Info   ] Unmount C
[05:52:51.741][ApiProxy       ][Info   ] proxy >> GET /_ping
[05:52:51.741][ApiProxy       ][Info   ] Dial Hyper-V socket 90fdc477-c5f6-4699-a215-ff3bd4ca90a6:23a432c2-537a-4291-bcb5-d62504644739
[05:52:51.741][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 90fdc477-c5f6-4699-a215-ff3bd4ca90a6:23a432c2-537a-4291-bcb5-d62504644739
[05:52:51.742][ApiProxy       ][Info   ] proxy << GET /_ping
[05:52:51.744][ApiProxy       ][Info   ] proxy >> POST /v1.30/images/load?quiet=1
[05:52:51.744][ApiProxy       ][Info   ] Dial Hyper-V socket 90fdc477-c5f6-4699-a215-ff3bd4ca90a6:23a432c2-537a-4291-bcb5-d62504644739
[05:52:51.745][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 90fdc477-c5f6-4699-a215-ff3bd4ca90a6:23a432c2-537a-4291-bcb5-d62504644739
[05:52:51.875][ApiProxy       ][Info   ] proxy << POST /v1.30/images/load?quiet=1
[05:52:51.925][ApiProxy       ][Info   ] proxy >> GET /_ping
[05:52:51.925][ApiProxy       ][Info   ] Dial Hyper-V socket 90fdc477-c5f6-4699-a215-ff3bd4ca90a6:23a432c2-537a-4291-bcb5-d62504644739
[05:52:51.925][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 90fdc477-c5f6-4699-a215-ff3bd4ca90a6:23a432c2-537a-4291-bcb5-d62504644739
[05:52:51.927][ApiProxy       ][Info   ] proxy << GET /_ping
[05:52:51.931][ApiProxy       ][Info   ] proxy >> POST /v1.30/containers/create [rewriteBinds]
[05:52:51.932][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.
[05:52:52.032][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.
[05:52:52.133][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.

**Comment by friism** [comment]
Are you auto-starting a container that has a bind-mounted volume? Bind-mounted volumes will only work a little while after Docker for Windows starts, because it has to setup up the host filesharing.

**Comment by jasonbivins** [comment]
Hi @davoutuk 
Does Docker work if you disable the Auto-start, and start it manually after Windows boots?

![image](https://user-images.githubusercontent.com/28021664/29278113-bd014a60-80e1-11e7-891b-0ecbc3d64248.png)

**Comment by rhogan73** [comment]
Experiencing the same issues.  If I kill the task (it won't stop) then stop the service and restart it, then it works as expected.
