### ISSUE TITLE
Error operation timed out when installing 

### ISSUE THREAD

**Issue by Preddyv** [docker/for-win#1003]
Hi I am getting an error when installing docker for windows server 2016

The operation has timed out.
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 246
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

**Comment by jasonbivins** [comment]
Hi @Preddyv   Are you using the installer located here?  : https://docs.docker.com/engine/installation/windows/docker-ee/

It looks like you might be trying to use the Windows 10 installer - can you post a screenshot of the error?

**Comment by Preddyv** [comment]
Hi yeah that works.

Was just wondering why the GUI element doesnt work

Does this mean i have to write the code to share volumes in the command
prompt?



*Vaughn Preddy*
*Software Developer | Travelit Division of Tourvest Travel Services*


12 Autumn Street, Rivonia, Sandton
*[c] 0722807700*
*[e] vaughnp@travelit.co.za <vaughnp@travelit.co.za>**@travelit.co.za
<http://travelit.co.za/>*




[image: travelit] <http://travelit.tvst.travel/>  [image: Service
Excellence Centre] <http://feedback.sec.travel/?cid=travelit>[image: Best
Company to work for]

**Comment by Preddyv** [comment]
How do I achieve the following using the command prompt
https://blogs.msdn.microsoft.com/stevelasker/2016/06/14/configuring-docker-for-windows-volumes/

Thanks

*Vaughn Preddy*
*Software Developer | Travelit Division of Tourvest Travel Services*


12 Autumn Street, Rivonia, Sandton
*[c] 0722807700*
*[e] vaughnp@travelit.co.za <vaughnp@travelit.co.za>**@travelit.co.za
<http://travelit.co.za/>*




[image: travelit] <http://travelit.tvst.travel/>  [image: Service
Excellence Centre] <http://feedback.sec.travel/?cid=travelit>[image: Best
Company to work for]

**Comment by Preddyv** [comment]
Hi actually when i run
the powershell just hangs

docker run hello-world:nanoserver


*Vaughn Preddy*
*Software Developer | Travelit Division of Tourvest Travel Services*


12 Autumn Street, Rivonia, Sandton
*[c] 0722807700*
*[e] vaughnp@travelit.co.za <vaughnp@travelit.co.za>**@travelit.co.za
<http://travelit.co.za/>*




[image: travelit] <http://travelit.tvst.travel/>  [image: Service
Excellence Centre] <http://feedback.sec.travel/?cid=travelit>[image: Best
Company to work for]

**Comment by Preddyv** [comment]
What do I do to get it to work?

*Vaughn Preddy*
*Software Developer | Travelit Division of Tourvest Travel Services*


12 Autumn Street, Rivonia, Sandton
*[c] 0722807700*
*[e] vaughnp@travelit.co.za <vaughnp@travelit.co.za>**@travelit.co.za
<http://travelit.co.za/>*




[image: travelit] <http://travelit.tvst.travel/>  [image: Service
Excellence Centre] <http://feedback.sec.travel/?cid=travelit>[image: Best
Company to work for]

**Comment by Preddyv** [comment]
Hi i see the error is actually

[10:25:33.017][DataKit        ][Error  ] com.docker.db.exe: Failed to set
up server socket listening on
hyperv-connect://b644bfb6-8b81-4b88-a0d0-2398abc8c1c7:
Unix.Unix_error(Unix.ENETDOWN, "socket", "")

[10:25:33.017][DataKit        ][Info   ] com.docker.db.exe: internal error,
uncaught exception:

[10:25:33.017][DataKit        ][Info   ]                    (Failure
accept_forever)

[10:25:33.017][DataKit        ][Info   ]

[10:25:33.022][DataKit        ][Error  ] Process died
[10:25:37.922][Linux          ][Error  ] Failed to start: The operation has
timed out.. Let's retry

any idea?

*Vaughn Preddy*
*Software Developer | Travelit Division of Tourvest Travel Services*


12 Autumn Street, Rivonia, Sandton
*[c] 0722807700*
*[e] vaughnp@travelit.co.za <vaughnp@travelit.co.za>**@travelit.co.za
<http://travelit.co.za/>*




[image: travelit] <http://travelit.tvst.travel/>  [image: Service
Excellence Centre] <http://feedback.sec.travel/?cid=travelit>[image: Best
Company to work for]

**Comment by abarke** [comment]
I got this error today:

The operation has timed out.
at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 245
at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

**Comment by Preddyv** [comment]
i found the issue the vm i wasnt set up to use docker....

*Vaughn Preddy*
*Software Developer | Travelit Division of Tourvest Travel Services*


12 Autumn Street, Rivonia, Sandton
*[c] 0722807700*
*[e] vaughnp@travelit.co.za <vaughnp@travelit.co.za>**@travelit.co.za
<http://travelit.co.za/>*




[image: travelit] <http://travelit.tvst.travel/>  [image: Service
Excellence Centre] <http://feedback.sec.travel/?cid=travelit>[image: Best
Company to work for]
