### ISSUE TITLE
Docker Desktop Startup Issues

### ISSUE THREAD

**Issue by compulshun** [docker/for-win#10082]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9A0AE96B-5114-4119-956E-951775215A64/20210113022445
  - [x] I am using the Docker WSL2 Backend
  - [x] I am using the Docker Hyper-V Backend

### Actual behavior
Docker Desktop won't start - I've followed all steps in the troubleshooting available here: https://docs.docker.com/docker-for-windows/troubleshoot/. Hyper-V is enabled as is WSL2 and Virtualization, and Windows is using WSL2. Hypervisor is set to launch at startup. I’ve uninstalled my AntiVirus software – I can’t see anything else I can do.
This is the error it throws:
System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
### Expected behavior
N/A

### Information

  - Windows Version: Windows 10 Pro (10.0.18363 Build 18363)
  - Docker Desktop Version: Latest
  - WSL2 or Hyper-V backend?  Both? Should I have one disabled?
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by stephen-turner** [comment]
It still looks like WSL 2 is not properly installed. What does `wsl -l -v` show?

**Comment by compulshun** [comment]
wsl -l -v was working, but showed that the docker environment was stopped.

I found a solution on the WSL2 github though, this is what worked for me if you're curious:
https://github.com/microsoft/WSL/issues/4177#issuecomment-597736482
