### ISSUE TITLE
Docker Desktop no longer starts

### ISSUE THREAD

**Issue by lesscodedotnet** [docker/for-win#10097]
- [X ] I have tried with the latest version of Docker Desktop
  - [X ] I have tried disabling enabled experimental features
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 1267FDB6-705B-45FD-816A-1E10D30CC6D6/20210114141837
  - [X ] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior
```
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\<me>\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: The RPC server is unavailable.


 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

### Expected behavior
Normal startup

### Information
<!--
Please, help us understand the problem.  For instance:
  - Is it reproducible? Every time
  - Is the problem new? Yes
  - Did the problem appear with an update? Perhaps
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
-->
  - Windows Version: 10 Pro 19041.746
  - Docker Desktop Version: 3.1.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior
<!--
A reproducible case, Dockerfiles with reproduction inside is best.
-->

  1. .start docker desktop
  2. ...

**Comment by DonLarry** [comment]
Verify if you have installed and activated the LxssManager service.

**Comment by lesscodedotnet** [comment]
I just went back to that machine to check and Docker now starts correctly. The LxssManager service is installed and running (but I don't think anything has changed in that respect since before last week when Docker was working fine).

**Comment by lesscodedotnet** [comment]
It looks like there was a Windows update last night and the machine restarted. I see the same Docker error on the screen, and every time I try to restart Docker manually. LxssManager service is running.

**Comment by lesscodedotnet** [comment]
Curiously, there's also now a service called `LxssManagerUser_17a195`. Any idea what that is?

**Comment by lesscodedotnet** [comment]
New diag id: 1267FDB6-705B-45FD-816A-1E10D30CC6D6/20210123142007

**Comment by lesscodedotnet** [comment]
... aaand now it's starting fine again. No idea what's going on here.

**Comment by lingjiamian** [comment]
Any solution? I have the same problem.

**Comment by lesscodedotnet** [comment]
Just happened again for me after an update

**Comment by lesscodedotnet** [comment]
I think I know why this is happening - it only seems to occur if a VPN is enabled at the time Docker Desktop starts.
