### ISSUE TITLE
Docker Unable To Start After Fresh Install - May be related to Certificate Issues

### ISSUE THREAD

**Issue by iUnknwn** [docker/for-win#10122]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features - Can't access settings, docker never finishes starting.
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D740EEEE-44C3-4B3D-8BB4-427CB75A5925/20210117082026
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior
Docker is unable to start after a fresh install. This system has never had docker installed before.

### Expected behavior
Docker starts.

### Information
  - Is it reproducible? Yes, 100% - the docker engine never has successfully started.
  - Is the problem new? Yes (after initial install).
  - Did the problem appear with an update? N/A
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best. N/A
  - Windows Version: 20H2 (19042.746)
  - Docker Desktop Version:  Last available from [here](https://hub.docker.com/editions/community/docker-ce-desktop-windows/), unable to query docker daemon because it does not start.
  - WSL2 or Hyper-V backend?  WSL2 (Linux distributions in WSL2 are working normally)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior
Start Docker Desktop.

Docker never is able to start, checking in the AppData/Roaming/Docker/log/vm/onboot.000-metadata, I see a single message repeated:

```
 Still unable to fetch metadata from Go backend after [increasing amounts of time]
```

From the log/host folder, there are several com.docker.backend.exe.log.[number] files, each with the same message repeated (though the goroutine number changes):
```
goroutine 237 [running]:
github.com/docker/pinata/common/cmd/com.docker.backend/internal/handlers.certificates(0xc000008000, 0xc00001c1e0, 0xa, 0x1, 0x0)
	C:/workspaces/master/src/github.com/docker/pinata/common/cmd/com.docker.backend/internal/handlers/vminit.go:110 +0x189
github.com/docker/pinata/common/cmd/com.docker.backend/internal/handlers.VMInit(0x1852640, 0xc00019e5b0, 0x35bced, 0x6003ede1)
	C:/workspaces/master/src/github.com/docker/pinata/common/cmd/com.docker.backend/internal/handlers/vminit.go:81 +0x408
github.com/labstack/echo.(*Echo).Add.func1(0x1852640, 0xc00019e5b0, 0x2266360, 0x70)
	C:/workspaces/master/src/github.com/docker/pinata/vendor/github.com/labstack/echo/echo.go:490 +0x91
github.com/labstack/echo/middleware.LoggerWithConfig.func2.1(0x1852640, 0xc00019e5b0, 0x0, 0x0)
	C:/workspaces/master/src/github.com/docker/pinata/vendor/github.com/labstack/echo/middleware/logger.go:118 +0x143
github.com/labstack/echo.(*Echo).ServeHTTP(0xc0000025a0, 0x182fa00, 0xc0004a6700, 0xc0005fc300)
	C:/workspaces/master/src/github.com/docker/pinata/vendor/github.com/labstack/echo/echo.go:593 +0x22f
net/http.serverHandler.ServeHTTP(0xc000214380, 0x182fa00, 0xc0004a6700, 0xc0005fc300)
	C:/Users/docker/.pinata/downloads/go/1.15.6/go/src/net/http/server.go:2843 +0xaa
net/http.(*conn).serve(0xc0001960a0, 0x1832a80, 0xc0002ee1c0)
	C:/Users/docker/.pinata/downloads/go/1.15.6/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	C:/Users/docker/.pinata/downloads/go/1.15.6/go/src/net/http/server.go:2969 +0x36d
time="2021-01-16T23:57:21-08:00" level=info msg="internal: GET /vm/init 500 \"DockerDesktopGo\" \"during /vm/init: cannot fetch Kubernetes certificates: cannot read \"sa.key\": open C:\\Users\\sz224.000\\AppData\\Local\\Docker\\pki\\sa.key: The system cannot find the file specified.\""
time="2021-01-16T23:57:21-08:00" level=error msg="cannot create kubernetes PKI: error creating PKI assets: failed to write or validate certificate \"etcd-server\": certificate etcd/server is not signed by corresponding CA. Cluster will need to be reset."
```

**Comment by iUnknwn** [comment]
After deleting the following folders:
  - AppData/Local/Docker
  - AppData/Roaming/Docker

And reinstalling Docker, the problem appears to have gone away and docker is able to start normally.
