### ISSUE TITLE
Unable to execute mount on Windows 10

### ISSUE THREAD

**Issue by miklavz24** [docker/for-win#1016]
### Expected behavior
Go to Settings | Shared Drives, click "C" and/or "D" in the list of drives
### Actual behavior
Shared Drives checkboxes go back to being empty
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
   DF261BD9-9A73-41A9-9116-0D226E96A4B8/2017-08-18_11-54-38
  - host distribution and version (Windows version, build number, etc)
   Version 17.07.0-ce-rc2-win22 (12979)
  windows 10 latest

**Comment by miklavz24** [comment]
log attached

[11:53:36.251][SambaShare     ][Info   ] Mount C
[11:53:36.354][Cmd            ][Info   ] Share name        C
[11:53:36.354][Cmd            ][Info   ] Path              C:\
[11:53:36.354][Cmd            ][Info   ] Remark            
[11:53:36.354][Cmd            ][Info   ] Maximum users     No limit
[11:53:36.354][Cmd            ][Info   ] Users             
[11:53:36.354][Cmd            ][Info   ] Caching           Caching disabled
[11:53:36.354][Cmd            ][Info   ] 
[11:53:36.354][Cmd            ][Info   ] The command completed successfully.
[11:53:36.354][Cmd            ][Info   ] 
[11:53:36.375][SambaShare     ][Info   ] "C" is shared
[11:53:36.612][SambaShare     ][Info   ] Cifs options: noperm,iocharset=utf8,nobrl,mfsymlinks,vers=3.02,domain=SOFTSERVE
[11:53:36.726][ApiProxy       ][Info   ] proxy >> GET /_ping
[11:53:36.726][ApiProxy       ][Info   ] Dial Hyper-V socket e37fa090-0129-4066-b890-fe3fcb479c8a:23a432c2-537a-4291-bcb5-d62504644739
[11:53:36.728][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket e37fa090-0129-4066-b890-fe3fcb479c8a:23a432c2-537a-4291-bcb5-d62504644739
[11:53:36.729][ApiProxy       ][Info   ] proxy << GET /_ping
[11:53:36.730][ApiProxy       ][Info   ] proxy >> POST /v1.31/images/load?quiet=1
[11:53:36.730][ApiProxy       ][Info   ] Dial Hyper-V socket e37fa090-0129-4066-b890-fe3fcb479c8a:23a432c2-537a-4291-bcb5-d62504644739
[11:53:36.737][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket e37fa090-0129-4066-b890-fe3fcb479c8a:23a432c2-537a-4291-bcb5-d62504644739
[11:53:36.851][ApiProxy       ][Info   ] proxy << POST /v1.31/images/load?quiet=1
[11:53:36.856][NamedPipeClient][Error  ] Unable to send Mount: Item has already been added. Key in dictionary: 'USER'  Key being added: 'USER'
[11:53:36.857][ShareHelper    ][Error  ] Failed to mount C: Item has already been added. Key in dictionary: 'USER'  Key being added: 'USER'
[11:53:36.856][NamedPipeServer][Error  ] Unable to execute Mount: Item has already been added. Key in dictionary: 'USER'  Key being added: 'USER'    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile)
   at Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs)
   at Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip)
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings)
   at Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings)
   at Docker.Backend.BackendServer.<Run>b__5_11(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[11:53:36.863][NamedPipeClient][Info   ] Sending GetDefaultVhdxPath()...
[11:53:36.863][NamedPipeServer][Info   ] GetDefaultVhdxPath()
[11:53:36.865][NamedPipeClient][Info   ] Received response for GetDefaultVhdxPath
[11:53:36.865][NamedPipeServer][Info   ] GetDefaultVhdxPath done in 00:00:00.0020188.

**Comment by cilerler** [comment]
Linking #995

**Comment by cilerler** [comment]
> A diagnostic was uploaded with id: 6CC99597-75C1-4C1E-95D3-F885674DC9ED/2017-09-24_07-40-50

I was using **Docker Community Edition 17.09.0-ce-rc3-win30 2017-09-22 [latest edge]** and downgraded to **Docker Community Edition 17.06.2-ce-win27 2017-09-06 [latest stable]** and it still wasn't working.  

Then I reset it to factory defaults _(Settings + Reset + Reset to factory defaults...)_ and looks like everything is working fine as of now.

**Comment by miklavz24** [comment]
any updates?
