### ISSUE TITLE
Unable to destroy: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class 

### ISSUE THREAD

**Issue by Sumitha-soman** [docker/for-win#10191]
### Information

Docker was running fine earlier. After starting the docker, getting the mentioned error.
Tried uninstalling and reinstalling. Also tried turning off and on Hyper-V feature

  - Windows Version:10
  - Docker Desktop Version:2.0.0.3 (31259)

log:

Version: 2.0.0.3 (31259)
Channel: stable
Started on: 2021/01/23 23:59:54.608
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1809
Build: 17763
BuildLabName: 17763.1.amd64fre.rs5_release.180914-1434
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[00:00:00.338][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[00:00:00.505][HyperV         ][Info   ] Script started at 00:00:00.492
[00:00:01.558][NPS            ][Error  ] Error in NPS process: Unable to create wootric user : http status : Unauthorized
[00:00:04.209][HyperV         ][Info   ] Modules loaded at 00:00:04.209
[00:00:04.730][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[00:00:04.730][HyperV         ][Debug  ] [stop] took 00:00:04.9572375 to run
[00:00:04.730][OptimizeDisk   ][Info   ] Optimize
[00:00:04.730][PowerShell     ][Info   ] Run script...
[00:00:06.786][Moby           ][Info   ] Stop
[00:00:06.802][HyperVGuids    ][Info   ] Installing GUIDs...
[00:00:06.802][PowerMode      ][Info   ] Start
[00:00:06.806][HyperVGuids    ][Info   ] GUIDs installed
[00:00:06.816][HyperV         ][Info   ] Create
[00:00:06.820][Firewall       ][Info   ] Removing all existing rules...
[00:00:06.876][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64000000000 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[00:00:06.922][HyperV         ][Info   ] Script started at 00:00:06.922
[00:00:06.946][HyperV         ][Info   ] Modules loaded at 00:00:06.946
[00:00:07.808][Firewall       ][Info   ] All existing rules are removed.
[00:00:07.808][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[00:00:07.826][Firewall       ][Info   ] Opening ports for SMB...
[00:00:07.849][Firewall       ][Info   ] Ports are opened
[00:00:08.284][HyperV         ][Info   ] Using existing Switch: DockerNAT
[00:00:08.446][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class 
. Let's retry
[00:00:08.605][HyperV         ][Info   ] Hyper-V is running
[00:00:08.605][PowerMode      ][Info   ] Stop
[00:00:08.605][HyperV         ][Info   ] Stop
[00:00:08.607][PowerShell     ][Info   ] Run script with parameters: -Stop True
[00:00:08.622][HyperV         ][Info   ] Script started at 00:00:08.622
[00:00:08.662][HyperV         ][Info   ] Modules loaded at 00:00:08.662
[00:00:08.702][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[00:00:08.702][HyperV         ][Debug  ] [stop] took 00:00:00.0973235 to run
[00:00:08.702][OptimizeDisk   ][Info   ] Optimize
[00:00:08.702][PowerShell     ][Info   ] Run script...
[00:00:09.823][Moby           ][Info   ] Stop
[00:00:09.838][HyperV         ][Info   ] Destroy
[00:00:09.838][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True
[00:00:09.850][HyperV         ][Info   ] Script started at 00:00:09.850
[00:00:09.871][HyperV         ][Info   ] Modules loaded at 00:00:09.871
[00:00:09.937][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[00:00:09.940][HyperV         ][Info   ] Destroying Switch DockerNAT...
[00:00:10.197][NamedPipeServer][Error  ] Unable to execute Start: Unable to destroy: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class 
    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 195
   at Docker.Backend.ContainerEngine.Linux.DoDestroy(Boolean keepVolume) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 364
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 116
[00:00:10.643][NamedPipeClient][Error  ] Unable to send Start: Unable to destroy: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class 

[00:00:10.645][Notifications  ][Error  ] Unable to destroy: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class 

[00:00:10.755][NamedPipeClient][Info   ] Sending Version()...
[00:00:10.757][NamedPipeClient][Info   ] Received response for Version
[00:00:10.757][NamedPipeClient][Info   ] Sending GatherDiagnostics(-path C:\Users\Sumitha.Soman\AppData\Local\Temp\ gather -id F31F01F1-C399-4264-A870-820595E9D38C/20210124000010, C:\Users\Sumitha.Soman\AppData\Local\Temp\F31F01F1-C399-4264-A870-820595E9D38C/20210124000010.zip)...
[00:00:10.757][NamedPipeServer][Info   ] Version()
[00:00:10.757][NamedPipeServer][Info   ] Version done in 00:00:00.
[00:00:10.763][NamedPipeServer][Info   ] GatherDiagnostics(-path C:\Users\Sumitha.Soman\AppData\Local\Temp\ gather -id F31F01F1-C399-4264-A870-820595E9D38C/20210124000010, C:\Users\Sumitha.Soman\AppData\Local\Temp\F31F01F1-C399-4264-A870-820595E9D38C/20210124000010.zip)
[00:03:25.394][NamedPipeClient][Info   ] Received response for GatherDiagnostics
[00:03:25.394][NamedPipeServer][Info   ] GatherDiagnostics done in 00:03:14.6307749.
[00:03:25.422][GUI            ][Info   ] Sending Bugsnag report 278b7c1f-4160-4fa6-ade2-c4e647ff1d8d...
[00:03:26.580][GUI            ][Info   ] Bugsnag report 278b7c1f-4160-4fa6-ade2-c4e647ff1d8d sent
[00:06:44.381][ErrorReportWindow][Info   ] Open logs

![image](https://user-images.githubusercontent.com/59161103/105610991-e0287900-5dd8-11eb-9f54-98ca033b7fd3.png)

**Comment by stephen-turner** [comment]
@Sumitha-soman Your version of Docker is nearly two years old. The current version is 3.1.0. I would recommend you upgrade.
