### ISSUE TITLE
Cannot reinstall Docker for Windows 3.1.0 on Win10 v2004.

### ISSUE THREAD

**Issue by romanrozinov** [docker/for-win#10202]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
  - [x] I am using the Docker WSL2 Backend
  - [ ] I am using the Docker Hyper-V Backend

### Actual behavior

Earlier i have used chocolatey to upgrade the version of Docker for Windows from 2.4 to 3.1.0 inside my Azure VM (D4-v3 with nested virtualization).  Since then, i see that c:\program files\docker\docker was empty but Windows thinks it was installed. There is no service entry in Service manager either.
I tried to force and reinstall and having an issue. Any time i try to use the installer, it reports that the existing installation is already present.  When, I attempt to uninstall I get a half-loaded GUI for uninstaller and no response.  When using the cli, I get the following:

```
C:\Users\roma> & 'C:\Program Files\Docker\Docker\Docker Desktop Installer.exe' uninstall force 
C:\Users\roma> [16:48:30.077] [ManifestAndExistingInstallationLoader] No install path specified, looking for default installation registry key
 [16:48:30.082] [Program] Existing installation found: version=51484, displayVersion=3.1.0, basePath=C:\Program Files\Docker\Docker, channelUrl=https://desktop.docker.com/win /stable/appcast.xml 
[16:48:30.087] [ProcessEnvironmentDetector] Relaunching from temp folder
 System.NullReferenceException: Object reference not set to an instance of an object.    at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__14.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
   at CommunityInstaller.Wizard.<StartStateMachine>d__8.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
   at CommunityInstaller.Wizard.<OnClosing>d__11.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) 
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj) 
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) 
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) 
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
    at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)    at System.Windows.Threading.DispatcherOperation.Invoke()    at System.Windows.Threading.Dispatcher.ProcessQueue() 
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) 
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) 
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame) 
   at System.Windows.Application.RunDispatcher(Object ignore)    at System.Windows.Application.RunInternal(Window window) 
   at CommunityInstaller.Wizard.Start()
    at CommunityInstaller.Cmd.UninstallHandler.Run(InstallerSettings installerSettings) 
   at CommunityInstaller.Program.Main(String[] args)Failed to track the fail to install event[16:48:35.472] [ManifestAndExistingInstallationLoader] No install path specified , looking for default installation registry key [16:48:35.477] [Program] Existing installation found: version=51484, displayVersion=3.1.0, basePath=C:\Program Files\Docker\Docker, channelUrl=https://desktop.docker.com/win /stable/appcast.xml Failed to track the uninstall started eventSystem.NullReferenceException: Object reference not set to an instance of an object.
    at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__14.MoveNext() 
--- End of stack trace from previous location where exception was thrown --- 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
   at CommunityInstaller.Wizard.<StartStateMachine>d__8.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) 
   at CommunityInstaller.Wizard.<OnClosing>d__11.MoveNext()
 --- End of stack trace from previous location where exception was thrown --- 
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() 
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
    at System.Windows.Threading.DispatcherOperation.InvokeImpl() 
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj) 
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) 
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)    at System.Windows.Threading.DispatcherOperation.Invoke()
    at System.Windows.Threading.Dispatcher.ProcessQueue() 
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) 
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) 
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg) 
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame) 
   at System.Windows.Application.RunDispatcher(Object ignore)    at System.Windows.Application.RunInternal(Window window)
    at CommunityInstaller.Wizard.Start()
    at CommunityInstaller.Cmd.UninstallHandler.Run(InstallerSettings installerSettings) 
   at CommunityInstaller.Program.Main(String[] args)Failed to track the fail to install event
```

### Expected behavior

My expectation that even if the upgrade was somehow unsuccessful i can still uninstall and then reinstall the build.

### Information

  - Windows Version:  Win 10 version 2004 (OS Build 20270.1)
  - Docker Desktop Version: v3.1.0
  - WSL2 or Hyper-V backend?  WSL 2 Backed
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:  I am running this in Azure VM D4_v3

### Steps to reproduce the behavior

  1. Start with Docker 2.4.X
  2. Use Chocolatey to upgrade to 3.1.0
  3. Attempt to uninstall the 3.1.0 through Add/Remove programs

**Comment by kyawzan3** [comment]
thank for information

**Comment by tlh2857** [comment]
Same thing happened to me. Any update?

**Comment by gaving** [comment]
Same hell here. Anybody get anywhere?

**Comment by gaving** [comment]
For any other poor sods, this is what worked for me:-

* Stop using chocolatey for Docker
* Deleted ```HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Docker```
* Downloaded latest from https://docs.docker.com/docker-for-windows/release-notes/

Also rebooted a bunch of times.

A colleague had to re-image his entire machine as none of this worked, so YMMV.
