### ISSUE TITLE
Bad response from Docker engine

### ISSUE THREAD

**Issue by hinell** [docker/for-win#1025]
### WORKAROUND
Start your docker as administrator (if it failed by service autostart or by shortcut otherwise). tl;dr

### Expected behavior
 Properly connecting to existing (previously installed) Moby machine
### Actual behavior
Getting error when trying to connect or reset docker

### Information
**Diagnostic ID**: ``F80B9291-0740-4640-830D-A9DE44281831/2017-08-22_00-21-57``
  - page URL if this is a docs issue or the name of a man page
- At first I run into issue when tried ``docker version`` after update then have reinstalled it and started again but got the error listed below. 
- **Platform:** Windows 10 x64 PRO Version 1607, build 14393.1358

Click details for more info.
<details>

```
Version: 17.07.0-ce-rc3-win23 (13024)
Channel: edge
Sha1: ead952bbb0995d3c78b824f1769827786e08f341
Started on: 2017/08/21 23:28:35.261
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.1358.amd64fre.rs1_release.170602-2252
File: C:\Users\Alex\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 


   in Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) в C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   in Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) в C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 252
   in Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) в C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   in Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) в C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   in Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) в C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[23:53:01.972][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\Alex\AppData\Local\Temp\qfwytq5p.php\pcap.tar)
[23:53:01.973][VpnKit         ][Warning] Unable to download logs: Pending time is expired.
[23:53:01.973][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0010003.
[23:53:02.018][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\Alex\AppData\Local\Temp\qfwytq5p.php\win_containers)...
[23:53:02.016][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\Alex\AppData\Local\Temp\qfwytq5p.php\mobyLogs.tar)
[23:53:02.016][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[23:53:02.024][CrashReport    ][Warning] Unable to collect features settings: Could not find file 'C:\Users\Alex\AppData\Roaming\Docker\features-overrides.json'.
[23:53:02.025][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\Alex\AppData\Local\Temp\qfwytq5p.php\win_containers)
[23:53:02.036][HyperV         ][Warning] Unable to download logs: 
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual machine with name "MobyLinuxVM".
[23:53:02.039][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[23:53:02.037][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.0209978.
[23:53:13.131][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[23:53:13.131][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:11.1054790.
[23:53:13.546][CrashReport    ][Info   ] Uploading diagnostics...
[23:53:14.997][NamedPipeClient][Info   ] Sending GetDefaultVhdxPath()...
[23:53:14.998][NamedPipeServer][Info   ] GetDefaultVhdxPath()
[23:53:15.000][NamedPipeClient][Info   ] Received response for GetDefaultVhdxPath
[23:53:14.999][NamedPipeServer][Info   ] GetDefaultVhdxPath done in 00:00:00.0014988.
[23:53:16.661][CrashReport    ][Info   ] Diagnostics successfully uploaded (F80B9291-0740-4640-830D-A9DE44281831/2017-08-21_23-53-01)
[23:53:16.661][GUI            ][Info   ] Sending Bugsnag report c4f27bdb-0a0b-49e3-8753-8ab695b7e860...
[23:53:18.274][GUI            ][Info   ] Bugsnag report c4f27bdb-0a0b-49e3-8753-8ab695b7e860 sent
[23:53:19.560][NamedPipeClient][Info   ] Sending GetDefaultVhdxPath()...
[23:53:19.561][NamedPipeServer][Info   ] GetDefaultVhdxPath()
[23:53:19.563][NamedPipeClient][Info   ] Received response for GetDefaultVhdxPath
[23:53:19.563][NamedPipeServer][Info   ] GetDefaultVhdxPath done in 00:00:00.0015004.
[23:53:21.683][FeedbackSettings][Info   ] Open logs

```

</details>

### Steps to reproduce the behavior

  1. Use Windows 10 with enabled and working Hyper-V machine
  2) Have running daemon (moby machine) with some images inside and latest Docker CE Edge client
  3) Update docker to 17.07.0-ce-rc3
  4. Start docker
  5. Try out to connect/reset docker
  ....
  6. <s>Profit!</s> Get the error.

**Comment by devangvt** [comment]
yes even i am getting the same error after the update. 👍

**Comment by hinell** [comment]
Getting the same error even after resetting docker to default. 
``F80B9291-0740-4640-830D-A9DE44281831/2017-08-22_11-35-00``

**Comment by chvndb** [comment]
I have the same issue on Windows Server with Docker CE Edge, no possibility to downgrade to a previous version to check if it still works.

**Comment by hinell** [comment]
Well, I have reinstalled the edge version by stable one and error is gone but docker version is still the same, lol: 
![screenshot_1](https://user-images.githubusercontent.com/8136158/29559802-bc26fe16-8738-11e7-9ade-5e28cbf023a0.png)
IDK how did this happen.

**Comment by chvndb** [comment]
Only edge supports Windows Server, so installing stable is not an option.

**Comment by chvndb** [comment]
Executing "Docker for Windows.exe" using "Run as administrator" gets it up and running again for me. To use docker, you have to then also run cmd or powershell as administrator.

**Comment by friism** [comment]
I think the new installer should work for stable on WS2016 too. Can you try this? https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe

I sent a PR to the docs: https://github.com/docker/docker.github.io/pull/4380

**Comment by hinell** [comment]
@friism 
Oh thanks. Is that latest updated version? 
Currently I'm on stable one and it works well though I'm gonna give a try to latest update (17.07.0-ce-rc4-win25 (13059)) to look if it works and report back if otherwise it don't.

**Comment by hinell** [comment]
@friism Surprisingly, docker works well if I start it as administrator and don't owtherwise. Pretty interesting...
@chvndb Thanks!

**Comment by hinell** [comment]
I think the problem is solved and I can close this issue.

**Comment by JohannesRudolph** [comment]
I don't think starting docker as an administrator "solves" this issue. It's a workaround, and not a good one at that. I'd much prefer docker get the old behavior working again (autostart without any sort of manual intervention required).

**Comment by hinell** [comment]
@JohannesRudolph Well I agree. Closing this issue was a premature decision. I'll keep it open unless the problem is addressed.

**Comment by chvndb** [comment]
@friism the stable release installer does not work for me on Windows Server 2016. It still gives me a warning to use Windows 10 and then exists.

**Comment by friism** [comment]
@ebriney can you confirm whether the stable installer checks supports this?

**Comment by hinell** [comment]
Anyone here still having the problem?
I think the issue could be closed cause after ``17.09.0-ce-rc3`` docker starts smoothly without administrator privileges.

**Comment by chvndb** [comment]
Can confirm, after upgrading to `17.09.0-ce-rc3`, everything starts up fine. Cheers !

**Comment by stepansib** [comment]
Nope, 17.09.0 still the same error ( 
Every Docker for windows update breaks docker (((

**Comment by friism** [comment]
@stepansib do you have more details - please upload a diagnostic id too. Are you trying to install Docker for Windows on Windows Server 2016 version 1709?

**Comment by stepansib** [comment]
Thank you, but forget. Already installing ubuntu right now. Tired of
permanent docjer for windows issues... )) ((

2 окт. 2017 г. 7:19 PM пользователь "Michael Friis" <
notifications@github.com> написал:

@stepansib <https://github.com/stepansib> do you have more details - please
upload a diagnostic id too. Are you trying to install Docker for Windows on
Windows Server 2016 version 1709?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/docker/for-win/issues/1025#issuecomment-333585368>, or mute
the thread

**Comment by danyg79** [comment]
Hi there!
I've just update my Docker for windows. I tried some windows restarts, reset to factory defaults, run as administrator but none of working :(

Error message:

Error response from daemon: Bad response from Docker engine

   a következő helyen: Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) hely: C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs, sor: 63
   a következő helyen: Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) hely: C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs, sor: 252
   a következő helyen: Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) hely: C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs, sor: 123
   a következő helyen: Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) hely: C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs, sor: 47
   a következő helyen: Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) hely: C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs, sor: 145

I have no "gopath" directory in C:\ root.

**Comment by Delavau** [comment]
@friism I think I have the same problem after updating to the latest version. I'm running on Windows 10 pro and I've tried the 'run as admin', 'reset to factory conditions', etc. I have also tried stable (13529) and edge (13514).  Same problem in either version.

Here is the diagnostic id: 67E35522-8620-4ED6-91DF-6C192F4179F9/2017-10-03_13-36-25

Error_ response from daemon: Bad response from Docker engine

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 252
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

**Comment by danyg79** [comment]
My final solution was uninstall latest stable and install the previous stable. (17.06.2-ce-win27 (13194))
And don't click on install update button :)
I hope it will be fixed in next release.

**Comment by stepansib** [comment]
@danyg79 good solution)) But i moved to Ubuntu. Now everything is perfect

**Comment by d-averkiev** [comment]
Facing same error today.
The "final solution" from @danyg79 works perfect. Thank you.
Previous 'stable' version docker for windows can be found here:
https://download.docker.com/win/stable/13194/Docker%20for%20Windows%20Installer.exe

**Comment by Delavau** [comment]
The latest version (13620) works for me.  No more problems on startup. Thank you.
