### ISSUE TITLE
Unable to install Docker Desktop

### ISSUE THREAD

**Issue by ramkiranhota** [docker/for-win#10251]
When I try to install docker desktop on my laptop using powershell, it is failing with below error. 
**Install Log attached**

[12:48:15.743][InstallWorkflow] Installation failed
Exception type: System.Exception, Exception message: Component CommunityInstaller.ExecAction failed: Process InstallerCli.exe exited with code -1073741819, StackTrace:
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[install-log.2.txt](https://github.com/docker/for-win/files/5895771/install-log.2.txt)

**Comment by Gearlong117** [comment]
My question is almost the same as yours. I opened the software today and found that it was necessary to update. After I clicked on the update, the software started to run the log, and the software disappeared when I ran. Reinstall again, the log reported is almost the same as yours.

**Comment by kny4** [comment]
I'm also having the same issue with installing
