### ISSUE TITLE
Latest update broken

### ISSUE THREAD

**Issue by animalmutch** [docker/for-win#10307]
The latest update to 3.1.0 has broken my installation. Docker no longer appears in the start menu, and running docker.exe results in the docker icon appearing in the system tray for a few seconds, then disappearing. Attempted uninstall/reinstall, and got the following error:

Failed to register product: The operation being requested was not performed because the user has not logged on to the network. The specified service does not exist. (Exception from HRESULT: 0x800704DD)
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

**Comment by rimi** [comment]
The same exception appeared for me when trying to install "Docker Desktop 3.2.1":

```
Failed to register product: The operation being requested was not performed because the user has not logged on to the network. The specified service does not exist. (Exception from HRESULT: 0x800704DD)
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

**Comment by animalmutch** [comment]
@rimi I fixed this by signing in to an admin account and installing from there. Give that a try :)

**Comment by rimi** [comment]
@animalmutch thanks, that worked for me!
