### ISSUE TITLE
Docker does not want to start after update to 17.07.0-ce-rc4 or 17.07.0-ce-rc3 (Windows Server 2016 and Windows 10)

### ISSUE THREAD

**Issue by marklechtermann** [docker/for-win#1040]
### Expected behavior

Docker should start

### Actual behavior

Error response from daemon: Bad response from Docker engine

### Information

82A98024-263F-449B-B178-312598389FAE/2017-08-25_09-54-43

Windows Server 2016 and Windows 10

After update to Version 17.07.0-ce-rc4-win25 (13059)
Same behavior with the previous version 17.07.0-ce-rc3

### Steps to reproduce the behavior

  1. Update to 17.07.0-ce-rc4 or reinstall 17.07.0-ce-rc4
  2. Try to start "C:\Program Files\Docker\Docker\Docker for Windows.exe"
  3. Error response from daemon: Bad response from Docker engine

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 252
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

Logfile:

...
[09:54:16.299][ApiProxy       ][Info   ] proxy >> GET /_ping
[09:54:16.299][ApiProxy       ][Info   ] Dial Hyper-V socket c858b456-31d2-4289-9a58-92af3fef1017:23a432c2-537a-4291-bcb5-d62504644739
[09:54:16.299][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket c858b456-31d2-4289-9a58-92af3fef1017:23a432c2-537a-4291-bcb5-d62504644739
[09:54:16.300][ApiProxy       ][Info   ] error reading response from Docker:  HvSocket has already been closed
...

On Windows 10:
After downgrade to 17.06.1-ce-win24 (stable) it runs!? 
But there is no stable release for Windows Server 2016. 
Any solutions?

**Comment by hinell** [comment]
Have you tried to start it as administrator?

**Comment by marklechtermann** [comment]
"Run as Administrator" ist the solution! Thx!
Unfortunately it's now necessary to execute the docker client as administrator.

**Comment by friism** [comment]
@ebriney do you know what's going on with this? Is this where you're supposed to log out of your Windows session and log back in?

**Comment by lucastheisen** [comment]
The recent updates cause failures for me as well:
```
[13:03:31.508][ApiProxy       ][Info   ] proxy >> GET /_ping^M
[13:03:31.508][ApiProxy       ][Info   ] Dial Hyper-V socket 728b8cc2-4c08-4024-9c21-23c917251e6b:23a432c2-537a-4291-bcb5-d62504644739^M
[13:03:31.508][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 728b8cc2-4c08-4024-9c21-23c917251e6b:23a432c2-537a-4291-bcb5-d62504644739^M
[13:03:31.509][ApiProxy       ][Info   ] error reading response from Docker:  HvSocket has already been closed^M
[13:03:31.509][ApiProxy       ][Info   ] proxy >> GET /v1.31/containers/json^M
[13:03:31.509][ApiProxy       ][Info   ] Dial Hyper-V socket 728b8cc2-4c08-4024-9c21-23c917251e6b:23a432c2-537a-4291-bcb5-d62504644739^M
[13:03:31.510][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 728b8cc2-4c08-4024-9c21-23c917251e6b:23a432c2-537a-4291-bcb5-d62504644739^M
[13:03:31.511][ApiProxy       ][Info   ] error reading response from Docker:  HvSocket has already been closed^M
[13:03:31.518][DockerDaemonChecker][Error  ] Docker daemon is not running^M
[13:03:31.519][NamedPipeServer][Error  ] Unable to execute Restart: Error response from daemon: Bad response from Docker engine^M
    at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63^M
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 252^M
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 182^M
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47^M
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145^M
[13:03:31.528][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\ltheisen\AppData\Local\Temp\rlyk4fck.cox\pcap.tar)^M
[13:03:31.532][VpnKit         ][Warning] Unable to download logs: The operation has timed out.^M
[13:03:31.532][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\ltheisen\AppData\Local\Temp\rlyk4fck.cox\win_containers)^M
[13:03:31.532][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0040003.^M
[13:03:31.532][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\ltheisen\AppData\Local\Temp\rlyk4fck.cox\mobyLogs.tar)^M
[13:03:31.538][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...^M
[13:03:36.622][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:05.0899694.^M
[13:03:47.294][NamedPipeServer][Info   ] GetDefaultVhdxPath()^M
[13:03:47.295][NamedPipeServer][Info   ] GetDefaultVhdxPath done in 00:00:00.0010014.^M
[13:03:47.726][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:16.1941121.^M
```
I attempted running the installer as administrator, but that didn't help.  However, after reverting to a prior version:
```
choco uninstall docker-for-windows
choco install docker-for-windows --pre --version=17.06.1.12818-edge
```
everything started working again.

**Comment by Scrxtchy** [comment]
Also ran into this problem on my Windows Server.
* Had a few issues quitting `Docker for Windows.exe` and gave it the taskkill so I could run it as admin
* jailed user I run my services on has it's own docker folder within the user directory, so configs aren't shared. Just a small thing since I have pretty massive memory limitations and shared drives.
* Have to run powershell as admin to be able to communicate to docker
* Containers still exist so at least that's less of a pain :+1:

**Comment by ebriney** [comment]
We just release a new version (17.09.0-ce-rc2-win29) that should fix the issue.
Can you test it and close the issue if it works?

**Comment by lucastheisen** [comment]
@ebriney , I can confirm that the latest release fixed this problem for me.  Though i use [chocolatey](https://chocolatey.org/packages/docker-for-windows/17.09.0.13333-edge) which shows the version as `17.09.0.13333-edge`, and when i check using docker itself:
```
PS C:\Users\ltheisen> docker --version
Docker version 17.09.0-ce-rc2, build 363a3e7
```
So not 100% positive that is the same as `-win29`...

**Comment by marklechtermann** [comment]
The bugfix works for me!
I was able to use Docker without administrator privileges ("Run as Adminstrator").

- Windows Server 2016
- Version 17.09.0-ce-rc2-win29 (13333)
- Start Daemon - Linux Container Mode (without "Run as administrator")
- Docker CLR (without "Run as administrator")
- it works!

**Comment by Scrxtchy** [comment]
Can confirm!
