### ISSUE TITLE
Docker Desktop with WSL2 integration installation fails

### ISSUE THREAD

**Issue by gunstonej** [docker/for-win#10443]
repeat of this: https://github.com/docker/for-win/issues/6928

trying to install Docker Desktop with WSL2 integration but installation fails:  https://docs.docker.com/docker-for-windows/wsl/
 
- [x] I have tried with the latest version of Docker Desktop
- [x] i have completed the wsl2 installation and installed ubuntu 2004 described here: https://docs.microsoft.com/en-us/windows/wsl/install-win10

### Actual behavior

The installer fails to complete. 

### Expected behavior

The installer to complete. 

### Information

details of my machine:
```
PS C:\engDev\git_mf\engDevSetup\dev\installers\wsl2_Ubuntu2004> systeminfo.exe

Host Name:                 PORT4028
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19042 N/A Build 19042
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Original Install Date:     02/10/2020, 09:31:05
System Boot Time:          22/02/2021, 11:55:04
System Manufacturer:       HP
System Model:              HP EliteBook 840 G7 Notebook PC
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 12 GenuineIntel ~1803 Mhz
BIOS Version:              HP S70 Ver. 01.03.02, 04/11/2020
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-gb;English (United Kingdom)
Input Locale:              en-gb;English (United Kingdom)
Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
Total Physical Memory:     16,157 MB
Available Physical Memory: 6,060 MB
Virtual Memory: Max Size:  22,813 MB
Virtual Memory: Available: 11,473 MB
Virtual Memory: In Use:    11,340 MB
Page File Location(s):     C:\pagefile.sys
Hotfix(s):                 9 Hotfix(s) Installed.
                           [01]: KB4601050
                           [02]: KB4561600
                           [03]: KB4562830
                           [04]: KB4577266
                           [05]: KB4577586
                           [06]: KB4580325
                           [07]: KB4586864
                           [08]: KB4598481
                           [09]: KB4601319
Network Card(s):           4 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: WiFi
                                 DHCP Enabled:    Yes
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [03]: SonicWall NetExtender Adapter
                                 Connection Name: Local Area Connection
                                 DHCP Enabled:    No
                                 IP address(es)
                           [04]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.17.208.1
                                 [02]: fe80::80b7:ec2c:9eb9:7809
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
```

configured to run wsl2 as default with ubuntu2004 successfully installed:
```
PS C:\Users\jg.installer> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         1
```

This is the error:
```
Component CommunityInstaller.AutoStartAction failed: Attempted to perform an unauthorized operation.
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

**Comment by Instagit** [comment]
Same error here. I was on 3.1.0 and tried to install 3.2.1. The only fix for now is installing 2.5.0. Any update or install after that crashes and leaves the installation broken.
