### ISSUE TITLE
System.InvalidOperationException: Failed to set version to docker-desktop: exit code: -1  stdout: The attempted operation is not supported for the type of object referenced.

### ISSUE THREAD

**Issue by gosaviprakash** [docker/for-win#10484]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: B99F3523-08AB-473F-A056-4DE2198ABD35/20210226100925

### Actual behavior
Docker-Desktop is not starting up and giving error
### Expected behavior
Docker-Desktop should start up normally
### Information

  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: 20.10.2, build 2291f61
  - WSL2 or Hyper-V backend?  WSL2 backend

Logs : 

System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.W SL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

**Comment by stephen-turner** [comment]
It appears that you haven't installed WSL 2 correctly, which Docker Desktop uses. Please follow Microsoft's instructions at https://aka.ms/wsl2-install. If it's set up correctly, then the command wsl -l -v should show a version 2 distro.

**Comment by gosaviprakash** [comment]
I have installed WSL 2 and while executing wsl -l -v command it is showing : 
  NAME              STATE           VERSION
* docker-desktop    Stopped         2

**Comment by gosaviprakash** [comment]
Hi,
Can you please suggest further actions as I have installed WSL2 correctly?
Thanks

**Comment by gosaviprakash** [comment]
Finally resolved issue with : 
- Unchecked WSL 2 installation while installing docker.
- Even Docker is failing to start with 'WSL 2 installation is incomplete' window then uncheck 'Use the WSL 2  based engine' from Docker->Settings->General : 
![DockerGeneralSettings](https://user-images.githubusercontent.com/47408548/109487199-e7af0200-7aa9-11eb-9a96-4b9442632fa9.jpg)
