### ISSUE TITLE
My (daily) morning crash. "Docker command did not complete within the allowed timeout."

### ISSUE THREAD

**Issue by lostllama** [docker/for-win#1049]
### Expected behavior

Docker starts with Windows.

### Actual behavior

An erorr occurred

Docker command did not complete within the allowed timeout. Output: 
   at Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 152
   at Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 49
   at Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 197
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 168
   at Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 65
   at Docker.Backend.BackendServer.<Run>b__5_11(Object[] args) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\BackendServer.cs:line 54
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

### Information

B258654D-04F9-494C-9F43-8B514E3411E0/2017-08-30_09-37-30

### Steps to reproduce the behavior

  1. Install Docker version 17.06.1-ce-win24 (13025)
  2. Restart Windows
  3. Crash

### Workaround

Close Docker from the system tray and start Docker manually.

**Comment by eriklundh** [comment]
Same crash log as above all of december 2017 with 17.09.1-ce-win42 on Windows 10 startup
Same workaround works.
Latest crash report B5C8CD00-3AE0-4995-B9DF-163AEC77336C/2017-12-30_21-12-23
