### ISSUE TITLE
Docker Desktop crashes with lifecycle-server error after changing WSL2 distro.

### ISSUE THREAD

**Issue by CasperTeirlinck** [docker/for-win#10530]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 19FEA144-529E-401E-8EDD-0E90CEE3DEBB/20210303112525

### Actual behavior
Docker Desktop starts up and stays in the starting phase for 5+ minutes after which it crashes with the following error:

```
System.TimeoutException:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
   at Docker.ApiServices.LifecycleClient.<WaitForServerUpAsync>d__8.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\LifecycleClient.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 153
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

This happens both when Docker Desktop automatically starts on startup, or when starting it manually.
During the startup process, the usage of the docker command in wsl results in:
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`
After the crash, the usage of the docker command results in:
`The command 'docker' could not be found in this WSL 2 distro.`

I am quite sure this problem started after I switched my default WLS2 distro.
I have been using Debian with docker desktop for a while and everything worked fine.
Recently I switched to Ubuntu 20.04 for compatibility reasons. I set it to default distro and after that I was able to use docker commands in Ubuntu, and not in Debian anymore. I then deregistered and uninstalled the Debian distro since I don't need it anymore. After that the docker desktop app fails to start and I have not been able to use docker in Ubuntu anymore.

I'm not sure what the issue is, docker worked fine in Ubuntu after making it the default distro, and I did not rely on the Debian distro anymore.

I have tried:
- Disabling the experimental features
- unregistering the docker-desktop and docker-desktop-data wsl instances
- stopping the docker desktop services
- completely uninstalling and reinstalling Docker Desktop and the wsl components, both with version 3.1 and 3.2

### Expected behavior
Docker Desktop starts within 10s and docker commands are available from within WSL2.

### Information

  - Windows Version: Windows 10 Pro version 2004 build 19041.804
  - Docker Desktop Version: 3.2.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Install WSL2 distro: Debian and set as default, use it with docker wsl2 backend
  2. Install WSL2 distro: Ubuntu 20.04, and set as default, use it with docker wsl2 backend
  3. Deregister the Debian distro and uninstall it
  4. Reboot and try to use docker in Ubuntu 20.04

**Comment by CasperTeirlinck** [comment]
I'll close the issue. I only got it working again after a full clean install of Windows.
I tried completely uninstalling and reinstalling multiple versions of WSL and Docker Desktop multiple times, with no success. Finally I also upgraded to the current Windows preview build, also with no success. Eventually I did a clean install of Windows, after which docker with WSL worked again as excepted.
