### ISSUE TITLE
Switch to Linux Containers times out - Path C:\gopath\... does not exist

### ISSUE THREAD

**Issue by wretiii** [docker/for-win#1059]
### Expected behavior
Open Docker for Windows, Switch to Linux Containers, run Linux images

### Actual behavior
Open Docker, receive error with option to set to factory defaults. It appears this may be occurring because there is no path to C:\gopath\... as seen in the output below.

### Information
Running Windows Server 2016, version 14393

My troubleshooting steps involve downloading and installing both the stable and edge versions a couple builds of each over the last week, though I don't recall the prior builds. Per #1025, I've attempted running all versions tried as administrator.

Diagnostic ID: 53C4B345-E76A-499B-9B82-00485FEBD4DD/2017-09-01_18-55-36
The operation has timed out.
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 246
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

PS C:\Windows\system32> docker version
Client:
 Version:      17.07.0-ce
 API version:  1.31
 Go version:   go1.8.3
 Git commit:   8784753
 Built:        Tue Aug 29 17:41:05 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.31/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to  connect. This error may also indicate that the docker daemon is not running.

PS C:\Windows\system32> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.07.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.1593.amd64fre.rs1_release.170731-1934)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4GiB
Name: jgr-p10-cap
ID: MDEV:CXDK:FRDL:XCL2:QONV:K44F:JAKO:AEMU:BFAZ:TWXE:BX4G:UGOH
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 22
 System Time: 2017-09-01T19:16:17.2955252-04:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

### Steps to reproduce the behavior

  1. Install stable or edge available from https://docs.docker.com/docker-for-windows/install/.
  2. Run As Administrator. Loads in Linux container mode by default
  3. Receive error message listed above.

**Comment by libai0915** [comment]
I have the exactly same issue.

**Comment by wretiii** [comment]
Does anyone know where to download older, working versions? If this is just a bug that is yet to be fixed, I'd like to see if I can get it working as needed with an older release.

**Comment by adragoset** [comment]
I managed to get stable 17.06.2-ce-win7 installed on windows server 2016 ver 14393. However  docker for windows must be started as administrator and any commands to docker must be issued via an elevated command prompt or powershell. If docker isnt started with administrator rights then after a few minutes docker crashes with errors reported in #1028 . Additionally any pull commands issued when running without administrator rights fail with segmentation fault errors which then cause the docker service to crash and give the  Bad response from Docker engine message and the service must be restarted. @wretiii  i have not been able to find where old stable versions can be downloaded either which means for the time being my dev environment is unusable.

**Comment by wretiii** [comment]
@adragoset, where did you find that version? I have 17.06.2-ce-win27, but not 17.06.2-ce-win7. Was that a typo possibly?

I've tried all the versions released since the end of August, stable and edge, and none work, even when running as administrator.

Not sure if it helps anyone who might be experiencing the same issues or looking into the issue, but I've attached the log file from the crashes I'm experiencing.

[log.txt](https://github.com/docker/for-win/files/1286220/log.txt)

**Comment by wretiii** [comment]
I'm not sure if this thread is even being monitored, but I've done some more troubleshooting and found that when installed on a physical box with Server 2016 and on a physical box with Windows 10, version 17.06.2-ce-win27 runs without issue.

Alternatively, I've installed the same version on two different virtual machines running Server 2016 and continue to receive the following error when starting in Linux container mode:

The operation has timed out.
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 247
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

At this time, the issue appears to be with running within a virtual environment.

I've ensured that Windows firewall is disabled, and no traffic coming from the IP address of my virtual Server 2016 server is being blocked on the firewall, however, in the log issued in the error window, it states the inability to connect to what appears to be an internal database, as the following output repeats itself for sometime in the log:

[15:06:45.439][DataKit        ][Info   ] Starting com.docker.db.exe 0.7.0-34-g6f04213 ...
[15:06:45.439][DataKit        ][Error  ] com.docker.db.exe: Failed to set up server socket listening on hyperv-connect://b21133c7-f06a-4a73-84a0-1c17b98fd79f: Unix.Unix_error(Unix.ENETDOWN, "socket", "")
[15:06:45.439][DataKit        ][Info   ] com.docker.db.exe: internal error, uncaught exception:
[15:06:45.439][DataKit        ][Info   ]                    (Failure accept_forever)
[15:06:45.439][DataKit        ][Info   ]                    
[15:06:45.454][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[15:06:45.454][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[15:06:45.454][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[15:06:45.454][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[15:06:45.454][Database       ][Info   ] Generating CA Cert Bundle
[15:06:45.454][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[15:06:45.454][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[], "debug":true, "experimental": true}
[15:06:45.454][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[15:06:45.454][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[15:06:45.454][Database       ][Info   ] CA Cert Bundle Generated
[15:06:46.490][Database       ][Error  ] 2017/09/08 15:06:45 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:45 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:45 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:45 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:45 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:45 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:46 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:46 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:46 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:46 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:46 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.
[15:06:46.490][Database       ][Error  ] Unable to modify database: Unable to write to the database. Exit code: 1. Let's retry in 1s
[15:06:47.505][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[15:06:47.505][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[15:06:47.505][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[15:06:47.505][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[15:06:47.505][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[15:06:47.505][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[], "debug":true, "experimental": true}
[15:06:47.505][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[15:06:47.505][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[15:06:48.556][Database       ][Error  ] 2017/09/08 15:06:47 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:47 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:47 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:47 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:47 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:48 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:48 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:48 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:48 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:48 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/09/08 15:06:48 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

Grasping at straws at this point.

**Comment by wretiii** [comment]
RTFM - I've found that Docker doesn't officially support running Docker for Windows on virtual hosts, and that the common errors I've experienced are a known issue on such an instance.

https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios

**Comment by lucarv** [comment]
i have the error on a physical machine, windows 10
