### ISSUE TITLE
Docker won't start anymore

### ISSUE THREAD

**Issue by metawave** [docker/for-win#10613]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID (WSL Backend): 9F7E443D-60D4-4A9A-B4B2-1D8C378A08B2/20210310191739
  - Diagnostics ID (Hyper-V Backend): 9F7E443D-60D4-4A9A-B4B2-1D8C378A08B2/20210310193514

### Actual behavior
- Install latest version 3.1.0 from download page
- update to 3.2.1 in docker-desktop
- 3.1.0 nor 3.2.1 will start, after a while everything runs into a timeout
- factory reset doesn't work either

### Expected behavior
- Install latest version 3.1.0 from download page
- update to 3.2.1 in docker-desktop
- Docker works as expected

### Information
  - Windows Version: 20H2 Build 19042.844
  - Docker Desktop Version: 3.1.0 and 3.2.1
  - WSL2 or Hyper-V backend?  both don't work. Running Ubuntu/Fedora in WSL1 does work by the way
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no
  - since 3.1.x updates, before it worked flawlessly for over a year
  - have hyper-v, container, WSL, wsl2 kernel update features disabled/enabled again a few times and few re-installs and even a network reset for winsock over commandline and reset feature in the windows settings did not fix the problem. I even deleted everything docker related in $USER/AppData/(Local|Roaming) and C:\ProgramData\Docker after each uninstall.

Errors appear everytime like:
```System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\Marcel\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0x80041002


 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

**Comment by daniel-butler** [comment]
This is the problem i've ran into too. Docker Autoupdated to 3.2.1 and since then it hasn't been working. I've restarted, uninstalled, reinstalled multiple times now. Originally I was using Hyper-V but switched to WSL engine. Neither works.

**Comment by stephen-turner** [comment]
The error "Failed to deploy distro docker-desktop" usually means that the WSL 2 installation is broken. Try installing/reinstalling WSL 2 from Microsoft's docs at http://aka.ms/wsl2-install

**Comment by solvingj** [comment]
Same, updated yesterday, now can't start. 
Docker Desktop.xe version 3.1.0.51484

```
Application: Docker Desktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Docker.Core.BackendAPI.ServiceNotInstalledException
   at Docker.Core.BackendAPI.BackendAPIPipeResolver+<ResolvePipeAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.BackendAPI.BackendAPIClient+<CreateSystemHttpClientAsync>d__3.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.BackendAPI.BackendAPIClient+<TryGetVhdxSize>d__16.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Engines.SettingsAdjuster+<CopyVhdxSizeAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.App+<Initialize>d__27.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

followed by:

```
Faulting application name: Docker Desktop.exe, version: 3.1.0.51484, time stamp: 0xd2a46f79
Faulting module name: KERNELBASE.dll, version: 10.0.19041.804, time stamp: 0x0e9c5eae
Exception code: 0xe0434352
Fault offset: 0x000000000002d759
Faulting process id: 0x2ddc
Faulting application start time: 0x01d71693d431756b
Faulting application path: C:\Program Files\Docker\Docker\Docker Desktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: d7215ef4-10e7-478f-8b4c-ff5c041000b2
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by solvingj** [comment]
Apparently, even though the Docker Desktop executable and other program files were present, it seems the upgrade failed, and Docker wasn't listed in my list of applications to uninstall.  I just downloaded/installed from here  https://hub.docker.com/editions/community/docker-ce-desktop-windows/ and it now seems fixed.

**Comment by wesleymusgrove** [comment]
I'm having the same issue.  Since the 3.2.1 update it's been super buggy on Windows 10.  It fails to start most of the time and when it does successfully start, the UI is very laggy and not interactive, like I can't click on anything.  I can't click on settings, the containers list, or even the red x to close it.  I have to go task manager to end the Docker Desktop task.  I went to control panel to add and remove programs and uninstalled Docker Desktop 3.2.1 then I re-installed the 3.1.0 version and it's working again.  When I restarted my computer, Docker Desktop prompted me for an update, so I let it do it's thing.  It worked for a few hours, but has now crashed and won't start again.  I'm going to try to uninstall and re-install 3.1.0 and try to avoid updating it until this gets resolved.

**Comment by 21region** [comment]
DiagnosticId: 54B37344-DD6D-4132-B39D-8960BCA6D0C9/20210312113724
```
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\e.okhterov\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: There was an operation attempted on a degraded object.


 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

```
