### ISSUE TITLE
Docker unable to start

### ISSUE THREAD

**Issue by xspbrx** [docker/for-win#1065]
### Expected behavior
Docker to open
### Actual behavior
Everytime Docker is opened, an error is occured with the following information

_Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 280
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145_

I've also included the log file that comes with the error.

Thank you

[log.txt](https://github.com/docker/for-win/files/1274910/log.txt)

**Comment by maxazan** [comment]
Do you use docker on Windows 10 Home? There is no support Windows 10 Home yet

The current version of Docker for Windows runs on 64bit Windows 10 Pro, Enterprise and Education (1511 November update, Build 10586 or later). In the future we will support more versions of Windows 10.

**Comment by jasonbivins** [comment]
Hi @xspbrx    
@maxazan  is correct - Docker for Windows is not supported on Windows Home versions.  
Please see here for a list of versions we support:  https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install
