### ISSUE TITLE
Kubernetes fails to start after upgrade (certificate not valid for 192.168.65.4)

### ISSUE THREAD

**Issue by bjornmagnusson** [docker/for-win#10674]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 08351941-7C21-4A66-A4EA-985578066E6B/20210316152828

### Actual behavior
Kubernetes fails to start.
kube-controller-manager-docker-desktop pods keep on failing due to certificate problems

### Expected behavior
Kubernetes starts

### Information
 ```
kubectl -n kube-system get pods -A
NAMESPACE     NAME                                     READY   STATUS             RESTARTS   AGE
kube-system   etcd-docker-desktop                      1/1     Running            2          5h28m
kube-system   kube-apiserver-docker-desktop            1/1     Running            2          5h28m
kube-system   kube-controller-manager-docker-desktop   0/1     CrashLoopBackOff   61         5h29m
kube-system   kube-scheduler-docker-desktop            1/1     Running            2          5h28m
```
```
kubectl -n kube-system logs kube-controller-manager-docker-desktop
Flag --port has been deprecated, see --secure-port instead.
I0316 15:22:37.536431       1 serving.go:331] Generated self-signed cert in-memory
I0316 15:22:38.308123       1 controllermanager.go:175] Version: v1.19.7
I0316 15:22:38.309484       1 dynamic_cafile_content.go:167] Starting request-header::/run/config/pki/front-proxy-ca.crt
I0316 15:22:38.309537       1 dynamic_cafile_content.go:167] Starting client-ca-bundle::/run/config/pki/ca.crt
I0316 15:22:38.310021       1 secure_serving.go:197] Serving securely on 127.0.0.1:10257
I0316 15:22:38.310411       1 tlsconfig.go:240] Starting DynamicServingCertificateController
W0316 15:22:38.313772       1 controllermanager.go:628] fetch api resource lists failed, use legacy client builder: Get "https://192.168.65.4:6443/api/v1?timeout=32s": x509: certificate is valid for 10.96.0.1, 0.0.0.0, 192.168.65.3, 127.0.0.1, not 192.168.65.4
F0316 15:22:48.334507       1 controllermanager.go:244] error building controller context: failed to wait for apiserver being healthy: timed out waiting for the condition: failed to get apiserver /healthz status: Get "https://192.168.65.4:6443/healthz?timeout=32s": x509: certificate is valid for 10.96.0.1, 0.0.0.0, 192.168.65.3, 127.0.0.1, not 192.168.65.4
goroutine 1 [running]:
k8s.io/kubernetes/vendor/k8s.io/klog/v2.stacks(0xc00000e001, 0xc0009a6000, 0x167, 0x1ae)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:996 +0xb9
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).output(0x6a47fa0, 0xc000000003, 0x0, 0x0, 0xc0005ae690, 0x68bfef4, 0x14, 0xf4, 0x0)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:945 +0x191
k8s.io/kubernetes/vendor/k8s.io/klog/v2.(*loggingT).printf(0x6a47fa0, 0x3, 0x0, 0x0, 0x449dd15, 0x25, 0xc000fa1348, 0x1, 0x1)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:733 +0x17a
k8s.io/kubernetes/vendor/k8s.io/klog/v2.Fatalf(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/klog/v2/klog.go:1456
k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func1(0x4a691a0, 0xc000054030)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:244 +0x54e
k8s.io/kubernetes/cmd/kube-controller-manager/app.Run(0xc000126278, 0xc0000920c0, 0xc0005ba450, 0xc0004aa480)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:260 +0x9b1
k8s.io/kubernetes/cmd/kube-controller-manager/app.NewControllerManagerCommand.func2(0xc0004ee840, 0xc000aef7c0, 0x0, 0x13)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:124 +0x2b7
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute(0xc0004ee840, 0xc00004c150, 0x13, 0x13, 0xc0004ee840, 0xc00004c150)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0004ee840, 0x166cdbe844b3e29c, 0x6a47c00, 0x406525)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:950 +0x375
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /workspace/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:887
main.main()
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kube-controller-manager/controller-manager.go:46 +0xe5
```

  - Windows Version: 10.0.18363.0
  - Docker Desktop Version: 3.2.2 (61853)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
Enable kubernetes and the wait for startup

**Comment by ukramer** [comment]
I could solve it by resetting the Kubernetes Cluster and deleting the pki folder in C:\Users\{user}\AppData\Local\Docker. Finally I just restarted Docker for Windows.
