### ISSUE TITLE
Cannot run Docker Compose Anymore from CLI

### ISSUE THREAD

**Issue by murpg** [docker/for-win#1072]
### Actual behavior  I get this error.    
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 64, in main
  File "compose\cli\main.py", line 113, in perform_command
  File "compose\cli\command.py", line 36, in project_from_options
  File "compose\cli\command.py", line 103, in get_project
  File "compose\config\config.py", line 316, in load
  File "compose\config\config.py", line 467, in process_config_file
  File "compose\config\validation.py", line 363, in validate_against_config_schema
  File "compose\config\validation.py", line 393, in load_jsonschema
IOError: [Errno 2] No such file or directory: u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\_MEI53~1\\compose\\config\\config_schema_v3.0.json'
docker-compose returned -1

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu. 124D2C91-7CD8-4FCE-B28C-88101D98153D/2017-09-06_12-39-57
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ... Update to latest version of Docker for Windows on Windows 2016 Server    
Docker version 17.03.0-ee-1, build 9094a76    
docker-compose version 1.9.0dev, build 466ebb6
  2. ...

**Comment by friism** [comment]
Can you try to update to a recent docker version (eg. 17.06)?

**Comment by murpg** [comment]
When I right mouse click it says I have the latest version

**Comment by murpg** [comment]
This is Docker for Windows that I am running not Docker CE

**Comment by jasonbivins** [comment]
Hi @murpg 
Can you double check this path to make sure it's there?

```C:\Users\ADMINI1\AppData\Local\Temp\2\_MEI531\compose\config\config_schema_v3.0.json```

**Comment by murpg** [comment]
That path is not there. I uninstalled and upgraded and things are back to normal now.
Docker version 17.05.0-ce-rc1, build 2878a85
docker-compose version 1.12.0, build ee0f34e1
