### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by ThePlenkov** [docker/for-win#10774]
Hi - when I try to install new version from here:

https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe

I have this:

`Process InstallerCli.exe exited with code 1
   at CommunityInstaller.ExecAction.<DoAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<UninstallAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()`

If I try to update existing version - it just does nothing - only closes itself.

I think the reason why - com.docker.serivce stays running even if  the app closes itself for new version installation

The solution right now is to make this call before: ` net stop com.docker.service`

However it would be really nice if installer can take care of it also.

Thanks!

**Comment by hantsy** [comment]
@ThePlenkov  
I got it worked. 

Try the following steps.
1. Stop docker.
2. Open the task manager window, make sure *com.docker.service* is terminated.
3. Then upgrade it .

Or  uninstall the old one( and check the *com.docker.service*), and install the new version.

**Comment by ThePlenkov** [comment]
@hantsy  this is correct! But the point is - can this new version upgrade itself? 

For all previous versions I never saw that installation worked. I always had to stop windows service manually and install the full version again downloaded from the docker hub.

I haven't checked yet if the most recent version has it fixed. I assume that not. Right now I'm on 3.3.3

**Comment by hantsy** [comment]
Since Docker 3.0, I also reinstalled from a fresh download several times.
Now I switched to use `chocolaty` to install from the command line.
Docker 3.x is slower than the former version, it frequently failed to start at the System startup, and even slower than the old Docker toolbox(Virtualbox versions).

And the worse is you can not stop the upgrade feature now.

**Comment by ThePlenkov** [comment]
3.6.0 problem still exists
![image](https://user-images.githubusercontent.com/6381507/129159813-6a0f0d08-1983-43de-bbf4-b193e66e5eb0.png)
