### ISSUE TITLE
Docker failed to initialize

### ISSUE THREAD

**Issue by Dan-Gahlinger** [docker/for-win#10771]
- [X ] I have tried with the latest version of Docker Desktop
  - [X ] I have tried disabling enabled experimental features
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: 7BB3ECD6-6F08-4F5D-A6EB-53CC2E8C2F60/20210329034242

### Actual behavior
System.IO.IOException
### Expected behavior
it should work
### Information

  - Windows Version: windows 10 Pro 20H2 version 10.0.19042.867
  - Docker Desktop Version: 3.2.2 (61853)
  - WSL2 or Hyper-V backend?  whatever docker installs (no other WSL/hyper-v installed)
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

all I need to do is start docker, then it sits at starting forever and eventually gives me the same error every time.
  1. ...
  2. ...

**Comment by Dan-Gahlinger** [comment]
Is there a fix for this?
I've tried everything I can find online.
another error result-

PS C:\Windows\system32> docker images
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.

**Comment by Dan-Gahlinger** [comment]
I setup a new computer, fresh install of windows 10, fresh install of Docker, got the same problem.
Are you guys going to work on this or what?

**Comment by Dan-Gahlinger** [comment]
System.TimeoutException:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
   at Docker.ApiServices.LifecycleClient.<WaitForServerUpAsync>d__8.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\LifecycleClient.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 153
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15387\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

**Comment by Dan-Gahlinger** [comment]
7BB3ECD6-6F08-4F5D-A6EB-53CC2E8C2F60/20210408223525
