### ISSUE TITLE
Windows 10 Docker daemon failed with message: Error starting daemon: Failed to load vmcompute.dll. Ensure that the Containers role is installed.

### ISSUE THREAD

**Issue by amousa1968** [docker/for-win#1082]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  Docker daemon failed with message:
Error starting daemon: Failed to load vmcompute.dll. Ensure that the Containers role is installed.

   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 198
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings) C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 78
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

Not sure what is the problem route cause, if you could assist to resolve.  thanks

**Comment by amousa1968** [comment]
Here is the error log:

Version: 17.06.2-ce-win27 (13194)
Channel: stable
Sha1: 428bd6ceae2994bd2fc2a72ec122507abe2cf526
Started on: 2017/09/10 22:20:36.100
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Home
Edition: Core
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834
File: C:\Users\Ayman\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[22:20:39.169][GUI            ][Info   ] Starting...
[22:21:25.572][Tracking       ][Info   ] Crash report and usage statistics are enabled
[22:21:25.638][SegmentApi     ][Info   ] Usage statistic: appLaunched
[22:21:26.913][NamedPipeClient][Info   ] Sending Version()...
[22:21:27.725][NamedPipeClient][Info   ] Received response for Version
[22:21:27.727][SegmentApi     ][Info   ] Usage statistic: heartbeat
[22:17:42.721][BackendServer  ][Info   ] Started
[22:21:27.545][NamedPipeServer][Info   ] Version()
[22:21:27.545][NamedPipeServer][Info   ] Version done in 00:00:00.
[22:21:35.580][PowerShell     ][Info   ] Run script '(Get-VMHost -ComputerName localhost).VirtualHardDiskPath'...
[22:21:38.040][PowerShell     ][Info   ] Creating a Runspace Pool...
[22:22:08.691][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[22:22:14.630][Notifications  ][Info   ] Docker is starting...
[22:22:14.739][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[22:22:14.755][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[22:22:14.864][PowerShell     ][Info   ] Run script...
[22:22:14.864][PowerShell     ][Info   ] Creating a Runspace Pool...
[22:22:15.210][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[22:24:43.275][PowerShell     ][Info   ] Run script...
[22:24:59.152][WindowsDockerDaemon][Info   ] Starting C:\Program Files\Docker\Docker\Resources\dockerd.exe -H npipe:////./pipe/docker_engine_windows -G "amousa\Ayman"
[22:25:03.764][WindowsDockerDaemon][Info   ] Started
[22:25:16.722][DockerDaemonChecker][Error  ] Docker daemon is not running
[22:25:17.993][DockerDaemonChecker][Error  ] Docker daemon is not running
[22:25:19.094][ApiProxy       ][Info   ] docker proxy: ready
[22:25:19.637][ApiProxy       ][Info   ] proxy >> GET /_ping
[22:25:19.637][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:19.706][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:19.707][ApiProxy       ][Info   ] proxy >> GET /v1.30/containers/json
[22:25:19.707][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:19.707][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:19.753][DockerDaemonChecker][Error  ] Docker daemon is not running
[22:25:21.178][ApiProxy       ][Info   ] proxy >> GET /_ping
[22:25:21.178][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:21.178][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:21.418][ApiProxy       ][Info   ] proxy >> GET /v1.30/containers/json
[22:25:21.418][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:21.418][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:21.604][DockerDaemonChecker][Error  ] Docker daemon is not running
[22:25:23.143][ApiProxy       ][Info   ] proxy >> GET /_ping
[22:25:23.143][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:23.143][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:23.273][ApiProxy       ][Info   ] proxy >> GET /v1.30/containers/json
[22:25:23.273][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:23.274][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:23.277][DockerDaemonChecker][Error  ] Docker daemon is not running
[22:25:24.515][ApiProxy       ][Info   ] proxy >> GET /_ping
[22:25:24.515][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:24.515][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:24.516][ApiProxy       ][Info   ] proxy >> GET /v1.30/containers/json
[22:25:24.516][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:24.516][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:24.519][DockerDaemonChecker][Error  ] Docker daemon is not running
[22:25:25.794][ApiProxy       ][Info   ] proxy >> GET /_ping
[22:25:25.794][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:25.794][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:25.795][ApiProxy       ][Info   ] proxy >> GET /v1.30/containers/json
[22:25:25.795][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:25.795][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:25.798][DockerDaemonChecker][Error  ] Docker daemon is not running
[22:25:27.424][ApiProxy       ][Info   ] proxy >> GET /_ping
[22:25:27.424][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:27.424][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:27.425][ApiProxy       ][Info   ] proxy >> GET /v1.30/containers/json
[22:25:27.425][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:27.425][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:27.428][DockerDaemonChecker][Error  ] Docker daemon is not running
[22:25:28.929][ApiProxy       ][Info   ] proxy >> GET /_ping
[22:25:28.930][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:28.930][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:28.931][ApiProxy       ][Info   ] proxy >> GET /v1.30/containers/json
[22:25:28.931][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:28.931][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:28.934][DockerDaemonChecker][Error  ] Docker daemon is not running
[22:25:30.109][ApiProxy       ][Info   ] proxy >> GET /_ping
[22:25:30.109][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:30.109][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:30.109][ApiProxy       ][Info   ] proxy >> GET /v1.30/containers/json
[22:25:30.109][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:30.109][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:30.112][DockerDaemonChecker][Error  ] Docker daemon is not running
[22:25:30.675][WindowsDockerDaemon][Warning] time="2017-09-10T22:25:30-07:00" msg="Running experimental build" 
[22:25:30.739][WindowsDockerDaemon][Debug  ] time="2017-09-10T22:25:30.739574600-07:00" msg="Listener created for HTTP on npipe (//./pipe/docker_engine_windows)" 
[22:25:30.791][WindowsDockerDaemon][Info   ] Error starting daemon: Failed to load vmcompute.dll. Ensure that the Containers role is installed.
[22:25:30.796][WindowsDockerDaemon][Error  ] Process died
[22:25:31.537][ApiProxy       ][Info   ] proxy >> GET /_ping
[22:25:31.538][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:31.538][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:31.538][ApiProxy       ][Info   ] proxy >> GET /v1.30/containers/json
[22:25:31.538][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:31.538][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:31.544][DockerDaemonChecker][Error  ] Docker daemon is not running
[22:25:32.563][WindowsDockerDaemon][Info   ] Starting C:\Program Files\Docker\Docker\Resources\dockerd.exe -H npipe:////./pipe/docker_engine_windows -G "amousa\Ayman"
[22:25:32.677][WindowsDockerDaemon][Info   ] Started
[22:25:32.680][ApiProxy       ][Info   ] Killing existing com.docker.proxy with PID 9212
[22:25:33.138][WindowsDockerDaemon][Warning] time="2017-09-10T22:25:33-07:00" msg="Running experimental build" 
[22:25:33.140][WindowsDockerDaemon][Debug  ] time="2017-09-10T22:25:33.140601300-07:00" msg="Listener created for HTTP on npipe (//./pipe/docker_engine_windows)" 
[22:25:33.140][WindowsDockerDaemon][Info   ] Error starting daemon: Failed to load vmcompute.dll. Ensure that the Containers role is installed.
[22:25:33.142][WindowsDockerDaemon][Error  ] Process died
[22:25:33.401][ApiProxy       ][Info   ] docker proxy: ready
[22:25:33.728][ApiProxy       ][Info   ] proxy >> GET /_ping
[22:25:33.728][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:33.729][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:33.729][ApiProxy       ][Info   ] proxy >> GET /v1.30/containers/json
[22:25:33.729][ApiProxy       ][Info   ] Dial name pipe  \\.\pipe\docker_engine_windows
[22:25:33.729][ApiProxy       ][Info   ] open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
[22:25:33.733][DockerDaemonChecker][Error  ] Docker daemon is not running
[22:25:33.736][ApiProxy       ][Info   ] Killing existing com.docker.proxy with PID 14836
[22:25:34.300][NamedPipeServer][Error  ] Unable to execute Start: Docker daemon failed with message:
Error starting daemon: Failed to load vmcompute.dll. Ensure that the Containers role is installed.

    at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 198
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 78
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[22:25:34.300][NamedPipeClient][Error  ] Unable to send Start: Docker daemon failed with message:
Error starting daemon: Failed to load vmcompute.dll. Ensure that the Containers role is installed.


[22:25:34.316][Notifications  ][Error  ] Docker daemon failed with message:
Error starting daemon: Failed to load vmcompute.dll. Ensure that the Containers role is installed.


[22:25:46.238][SegmentApi     ][Info   ] Usage statistic: actionMenuCloudLogin
[22:27:04.315][SegmentApi     ][Info   ] Usage statistic: actionLoginSucceded
[22:32:02.169][SegmentApi     ][Info   ] Usage statistic: actionMenuFeedback
[22:33:59.505][FeedbackSettings][Info   ] Open github issues
[22:40:17.419][BackendServer  ][Info   ] Stopping...
[22:40:17.448][BackendServer  ][Info   ] Stopped
[22:40:17.485][NamedPipeServer][Error  ] Pipe failure: Pipe hasn't been connected yet.    at System.IO.Pipes.PipeStream.CheckReadOperations()
   at System.IO.Pipes.PipeStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at Docker.Core.Pipe.NamedPipeServer.<HandleRequestAsync>d__12.MoveNext()
[22:40:24.886][BackendServer  ][Info   ] Started
[22:40:55.484][BackendServer  ][Info   ] Stopping...
[22:40:55.486][BackendServer  ][Info   ] Stopped
[22:40:55.495][NamedPipeServer][Error  ] Pipe failure: Pipe hasn't been connected yet.    at System.IO.Pipes.PipeStream.CheckReadOperations()
   at System.IO.Pipes.PipeStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at Docker.Core.Pipe.NamedPipeServer.<HandleRequestAsync>d__12.MoveNext()
[22:41:05.795][BackendServer  ][Info   ] Started
[22:42:50.293][BackendServer  ][Info   ] Stopping...
[22:42:50.294][BackendServer  ][Info   ] Stopped
[22:42:50.300][NamedPipeServer][Error  ] Pipe failure: Pipe hasn't been connected yet.    at System.IO.Pipes.PipeStream.CheckReadOperations()
   at System.IO.Pipes.PipeStream.BeginRead(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count)
   at Docker.Core.Pipe.NamedPipeServer.<HandleRequestAsync>d__12.MoveNext()
[22:43:12.897][BackendServer  ][Info   ] Started
[22:49:47.906][FeedbackSettings][Info   ] Upload diagnostic
[22:49:48.065][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[22:49:48.069][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\Ayman\AppData\Local\Temp\kqpiaisb.0mg\pcap.tar)...
[22:49:48.069][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\Ayman\AppData\Local\Temp\kqpiaisb.0mg\win_containers)...
[22:49:48.070][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\Ayman\AppData\Local\Temp\kqpiaisb.0mg\mobyLogs.tar)...
[22:49:48.072][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[22:49:48.095][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\Ayman\AppData\Local\Temp\kqpiaisb.0mg\pcap.tar)
[22:49:48.095][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\Ayman\AppData\Local\Temp\kqpiaisb.0mg\mobyLogs.tar)
[22:49:48.095][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\Ayman\AppData\Local\Temp\kqpiaisb.0mg\win_containers)
[22:49:48.095][NamedPipeServer][Info   ] GetDebugInfo()
[22:49:48.162][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[22:49:48.166][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[22:49:48.162][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[22:49:48.163][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0663453.
[22:49:48.167][PowerShell     ][Info   ] Creating a Runspace Pool...
[22:49:48.183][CrashReport    ][Warning] Unable to collect features settings: Could not find file 'C:\Users\Ayman\AppData\Roaming\Docker\features-overrides.json'.
[22:49:48.290][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[22:49:48.403][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[22:49:48.403][HyperV         ][Warning] Unable to download logs: Unrecognized Guid format.
[22:49:48.403][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.3073497.
[22:49:56.743][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[22:49:56.742][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:08.6464929.
[22:50:11.165][NamedPipeServer][Info   ] GetDebugInfo done in 00:00:23.0695712.
[22:50:11.167][NamedPipeClient][Info   ] Received response for GetDebugInfo
[22:50:11.442][CrashReport    ][Info   ] Uploading diagnostics...
[22:50:13.656][CrashReport    ][Info   ] Diagnostics successfully uploaded (0E5ABF8B-65F7-4379-AE94-0FFA2BF6A3F9/2017-09-10_22-49-47)
[22:52:59.272][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[22:52:59.273][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\Ayman\AppData\Local\Temp\tulirycq.3nk\pcap.tar)...
[22:52:59.273][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\Ayman\AppData\Local\Temp\tulirycq.3nk\mobyLogs.tar)...
[22:52:59.273][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\Ayman\AppData\Local\Temp\tulirycq.3nk\win_containers)...
[22:52:59.278][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[22:52:59.275][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\Ayman\AppData\Local\Temp\tulirycq.3nk\pcap.tar)
[22:52:59.276][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[22:52:59.282][CrashReport    ][Warning] Unable to collect features settings: Could not find file 'C:\Users\Ayman\AppData\Roaming\Docker\features-overrides.json'.
[22:52:59.276][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0010030.
[22:52:59.278][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\Ayman\AppData\Local\Temp\tulirycq.3nk\mobyLogs.tar)
[22:52:59.279][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\Ayman\AppData\Local\Temp\tulirycq.3nk\win_containers)
[22:52:59.279][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[22:52:59.337][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[22:52:59.337][HyperV         ][Warning] Unable to download logs: Unrecognized Guid format.
[22:52:59.337][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.0590383.
[22:53:03.005][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[22:53:03.005][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:03.7258197.
[22:53:03.156][CrashReport    ][Info   ] Uploading diagnostics...
[22:53:09.100][CrashReport    ][Info   ] Diagnostics successfully uploaded (0E5ABF8B-65F7-4379-AE94-0FFA2BF6A3F9/2017-09-10_22-52-59)
[22:53:09.221][GUI            ][Info   ] Sending Bugsnag report b5fee12c-7225-412d-8e7d-74ca692119de...
[22:53:11.487][GUI            ][Info   ] Bugsnag report b5fee12c-7225-412d-8e7d-74ca692119de sent
[22:53:17.035][ErrorReportWindow][Info   ] Open logs
[22:53:34.342][ErrorReportWindow][Info   ] Open logs

**Comment by jasonbivins** [comment]
Hi @amousa1968   It looks like you're running Windows 10 Home edition, which doesn't support Hyper-V   https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/hyper-v-requirements

Docker for Windows requires that you be on at least an education edition of Windows, but we prefer Pro or Enterprise   https://docs.docker.com/docker-for-windows/install/#download-docker-for-windows

**Comment by amousa1968** [comment]
Thank you!    Do you know if the beta would resolve the issue?  

Thanks 
Ayman Mousa

**Comment by jasonbivins** [comment]
Hi @amousa1968     I'm sorry but no - you'll have to upgrade your Windows version in order to be able to use Hyper-V
