### ISSUE TITLE
Docker Failing to Start after Install

### ISSUE THREAD

**Issue by geordielad** [docker/for-win#1085]
### Expected behavior

Docker Starts after logout and login (as per install post install steps) in after Windows 10 CE Install

### Actual behavior

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'XXXXXX' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

### Information

  - Diagnostic ID: 289095D1-5C3D-4B90-8A4F-1565358AAE7F/2017-09-12_17-03-39
  - host distribution and version (Windows version, build number, etc): Windows 10 Enterprise 

### Steps to reproduce the behavior

 Download Docker CE
Install
Follow Logout/Login Instructions

Docker does not start. Hyper-V Virtual Machine Management service is running

**Comment by jasonbivins** [comment]
Hi @geordielad 
Can you check to see if you're able to start and connect to any VMs in your Hyper-V manager?

**Comment by geordielad** [comment]
Thanks @jasonbivins I get exactly the same error in Hyper-V I will research internally and report back.

**Comment by Maikel-Nait** [comment]
This fixed the issue for me
[Fix error managing Hyper-V Server 2012 R2 from Windows 10](https://community.spiceworks.com/how_to/122307-fix-error-managing-hyper-v-server-2012-r2-from-windows-10)
