### ISSUE TITLE
Docker Desktop Access is denied error for Windos 10 HOME

### ISSUE THREAD

**Issue by haan78** [docker/for-win#10877]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windws 10 Home (2004)
  - Docker Desktop Version: Docker version 20.10.5, build 55c4c88
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

I couldn't change group settings because there is no group settings on windows HOME!

Error that I got when I started to Docker Desctop
System.ComponentModel.Win32Exception:
Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Docker.ManagedProcesses.ManagedProcess.StartProcess(String fileName, String arguments, String currentDirectory, IDictionary`2 envVariables, CancellationToken stopToken) in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.Desktop\ManagedProcesses\ManagedProcess.cs:line 122
   at Docker.ManagedProcesses.ManagedProcess.Start(String arguments, String currentDirectory, IDictionary`2 envVariables) in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.Desktop\ManagedProcesses\ManagedProcess.cs:line 50
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__21.MoveNext() in C:\workspaces\PR-15595\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 101

**Comment by emanual4real** [comment]
I'm having the same issue and now Docker won't even open without crashing.  Windows 10, Docker 3.3.0, WLS2 enabled.  Laptop and desktop both having similar issues.  We're newly behind ZScalar so wonder if that is causing an issue.

**Comment by simon-payne-informa** [comment]
In case it helps, I had this issue this morning and by running Docker Desktop as an administrator the error didn't occur and it started cleanly.  So that may give some hints, it is something to do with user permissions.

**Comment by lodellis** [comment]
Same issue, running as docker desktop as administrator did not fix this. My WSL2 ubuntu instance now doesn't believe docker is installed. Pushed a crash report

**Comment by estrehle** [comment]
Same issue.
How it went for me:
- Download Docker Desktop Installer and install. Run Docker Desktop. This works just fine. I can run it as user, it recognizes my WSL2 Ubuntu distro, I can use Docker in the distro.
- Reboot the computer.
- Run Docker Desktop again. This time, it asks for my admin credentials and install some update. Afterwards:
  - Running as user yields the error reported by @haan78 on startup. "Reset to factory defaults" does not help.
  - Running as admin works. But now Docker Desktop fails to recognize my WSL2 Ubuntu distro and I cannot use Docker in the distro.

I pushed the crash report. Quick help would be much appreciated.

**Comment by NeoMorfeo** [comment]
> Same issue on Windows 10 Pro, using a non-admin user account.
> How it went for me:
> 
> * Download [Docker Desktop Installer](https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe) and install.
> * Run Docker Desktop. This works just fine. I can run it as user, it recognizes my WSL2 Ubuntu distro, I can use Docker in the distro.
> * Reboot the computer.
> * Run Docker Desktop again. This time, it asks for my admin credentials and installs some update. Afterwards:
>   
>   * Running as user yields the error reported by @haan78 on startup. "Reset to factory defaults" does not help.
>   * Running as admin works. But now Docker Desktop fails to recognize my WSL2 Ubuntu distro and I cannot use Docker in the distro.
> 
> I pushed the crash report. Quick help would be much appreciated.

Same sceneario here...

**Comment by markus401** [comment]
> Same issue on Windows 10 Pro, using a non-admin user account.
> How it went for me:
> 
> * Download [Docker Desktop Installer](https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe) and install.
> * Run Docker Desktop. This works just fine. I can run it as user, it recognizes my WSL2 Ubuntu distro, I can use Docker in the distro.
> * Reboot the computer.
> * Run Docker Desktop again. This time, it asks for my admin credentials and installs some update. Afterwards:
>   
>   * Running as user yields the error reported by @haan78 on startup. "Reset to factory defaults" does not help.
>   * Running as admin works. But now Docker Desktop fails to recognize my WSL2 Ubuntu distro and I cannot use Docker in the distro.
> 
> I pushed the crash report. Quick help would be much appreciated.

The same for me... Thanks for the nice repro steps! They match exactly my situation.

**Comment by dkrowl** [comment]
> Same issue on Windows 10 Pro, using a non-admin user account.
> How it went for me:
> 
> * Download [Docker Desktop Installer](https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe) and install.
> * Run Docker Desktop. This works just fine. I can run it as user, it recognizes my WSL2 Ubuntu distro, I can use Docker in the distro.
> * Reboot the computer.
> * Run Docker Desktop again. This time, it asks for my admin credentials and installs some update. Afterwards:
>   
>   * Running as user yields the error reported by @haan78 on startup. "Reset to factory defaults" does not help.
>   * Running as admin works. But now Docker Desktop fails to recognize my WSL2 Ubuntu distro and I cannot use Docker in the distro.
> 
> I pushed the crash report. Quick help would be much appreciated.

Same here. This definitely smells like a permissions issue.

**Comment by FedericoYST** [comment]
Same issue for me. I can run it as Administrator but WSL Ubuntu distro cannot recognize Docker.

**Comment by nts-jkaufmann** [comment]
I had the same issue after the update. I removed Docker Desktop completely and installed version 3.3.0 (latest) again. Everything was fine afterwards, so it seems that only the automatic update is affected by the issue.

**Comment by arjasepp** [comment]
I have similar issue, not sure if or why it stopped responding. Docker was installed for quite some time. Then some laptop driver install came around and restarted my laptop and docker also installed something and after that it does not work. If I try my admin account it cannit find wsl folder for admin account, but it was all working fine before. I sent couple of crashreports too.

**Comment by barnebyte** [comment]
Updating to 3.3.1 solved the issue. If anyone have trouble with updating: leave the crash report window open, rightclick on docker icon in taskbar and select "download updates" (or check for updates if it's not there). Another window will pop up saying that Docker will download the updates in the background which will be installed at next time Docker restarts. Click Download, wait a bit until the update package is downloaded in the background while the crashreport window is still open. Once it's done, the rightclick-menu in taskbar will have an "update and restart" option. Click on that, and Docker should update itself on restart and the AccessDenied issue should be gone.

**Comment by mtahasahin** [comment]
Having the same issue. Docker crashes on start. Version is 3.3.1.

**Comment by yohancourbe** [comment]
Had same issue with 3.3.0, just upgraded to 3.3.1 and it works fine now.
