### ISSUE TITLE
Windows 10 docker start error - Windows containers mode

### ISSUE THREAD

**Issue by Amith211** [docker/for-win#1091]
### Expected behaviour
Docker daemon to start.
### Actual behaviour
![dockererror](https://user-images.githubusercontent.com/5212024/30400284-492623f4-98ce-11e7-9274-9e5eda0530e2.jpg)
### Information

  - Diagnostic ID: 934753C0-02FA-4930-8A7E-1E657B6BD56F/2017-09-13_21-09-14
          (Earlier ID: 934753C0-02FA-4930-8A7E-1E657B6BD56F/2017-09-13_15-18-11) 
  - host distribution and version: Windows Enterprise version 1703, build 15063.608 
  - Hyper-v installed and running VMs prior to docker installation.
  - 'Linux containers' mode starts without any problems.

### Steps to reproduce the behaviour
  1. Right click on docker in system tray
  2. Switch to Windows containers
  3. Daemon fails to start

**Comment by Amith211** [comment]
I removed some old vSwitches earlier, but that didn't seem to fix the issue as I kept getting the same error.

Having said that though, whilst writing this the daemon has suddenly started; I don't believe I have changed anything since the last error. I can pass my logs on to you, if you think they might be useful.

**Comment by toomyem** [comment]
The same is for Linux containers.

**Comment by manatax** [comment]
Similar issue on windows 10
Diagnostic id: 25D03CDC-A9C5-4DBB-AD32-1933C060CA0D/2017-09-15_12-03-37

Error:
`Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 280
   at Docker.Backend.ContainerEngine.Linux.Stop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 146
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145`

And I know Hyper-V is available in my machine:
`Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes`
