### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by joeldevries** [docker/for-win#1096]
### Expected behavior
Docker starts and works with Linux containers.

### Actual behavior
The Docker for Windows app starts and after a few minutes reports the following error:
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 267
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 251
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

### Information

Diagnostic ID 8D07753C-F2CC-47B6-9C9F-13F5D6D9F370/2017-09-14_10-54-08
Version 17.06.2-ce-win27 (13194)

Docker installer was run as Administrator.
Docker for Windows was run as Administrator.

I tried again with Experimental Features turned off  - same result.

### Steps to reproduce the behavior

  1. Install Docker for Windows
  2. Start Docker
  3. Wait

**Comment by awidjaja** [comment]
I have the same issue
https://github.com/docker/for-win/issues/1119

**Comment by flaksirus** [comment]
The same
387F6446-5B89-4E13-89AA-3128CA65EB82/2017-09-25_19-06-40

**Comment by TamByrd** [comment]
Same issue

82050DEF-F5EF-4E93-AB65-EC9542A4C7C2/2017-10-11_09-00-13

**Comment by rn** [comment]
@flaksirus Your issue is a kernel hang in a component maintained my Microsoft. I'll open an separate issue regarding it soon and will add your name to it.

@TamByrd Could you try the latest version (this issue is quite old) and create a new issue. Yours is different to the other two.

@joeldevries There is a Linux kernel crash in your logs (see below), actually there are several different ones, they all look related to the context switch code.

It looks like you have a skylake processor, which Linux detects and then tries to use the appropriate context switch code for that processor. Unfortunately, the version of Hyper-V does not correctly handle this processor. We had several issues like this in the past.

I'm afraid the only solution is a Windows update. I don't know if this was fixed with a regular patch to build 14393 or if this requires an update to a newer Windows version.

I'm closing this issue as Won't fix as this is not something we (Docker) can fix, but please report back if an update did fix it.

```
[07:41:58.883][Moby           ][Info   ] ------------[ cut here ]------------
[07:41:58.943][Moby           ][Info   ] WARNING: CPU: 0 PID: 0 at ./arch/x86/include/asm/fpu/internal.h:368 __switch_to+0x323/0x480
[07:41:58.949][Moby           ][Info   ] Modules linked in:
[07:41:58.976][Moby           ][Info   ] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G        W       4.9.41-moby #1
[07:41:59.027][Moby           ][Info   ] Hardware name: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS Hyper-V UEFI Release v1.0 11/26/2012
[07:41:59.059][Moby           ][Info   ]  0000000000000000 ffffffffad41b6d7 0000000000000000 0000000000000000
[07:41:59.075][Moby           ][Info   ]  ffffffffad0dcea9 ffff8f0fbb742380 ffffffffade10500 0000000000000000
[07:41:59.090][Moby           ][Info   ]  0000000000000000 0000000000000001 3d8dbe633249aaf0 ffffffffad01fe20
[07:41:59.093][Moby           ][Info   ] Call Trace:
[07:41:59.101][Moby           ][Info   ] ---[ end trace fd2061612229a8b2 ]---
[07:41:59.202][Moby           ][Info   ] Fixing recursive fault but reboot is needed!
```

and:
```
[07:43:35.644][Moby           ][Info   ] ------------[ cut here ]------------
[07:43:35.858][Moby           ][Info   ] WARNING: CPU: 0 PID: 0 at ./arch/x86/include/asm/fpu/internal.h:368 __switch_to+0x323/0x480
[07:43:35.865][Moby           ][Info   ] Modules linked in:
[07:43:35.884][Moby           ][Info   ] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G        W       4.9.41-moby #1
[07:43:35.921][Moby           ][Info   ] Hardware name: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS Hyper-V UEFI Release v1.0 11/26/2012
[07:43:35.942][Moby           ][Info   ]  0000000000000000 ffffffff9641b6d7 0000000000000000 0000000000000000
[07:43:35.959][Moby           ][Info   ]  ffffffff960dcea9 ffff8d00fb682240 ffffffff96e10500 0000000000000000
[07:43:35.979][Moby           ][Info   ]  0000000000000000 0000000000000001 cdcd31d052d13980 ffffffff9601fe20
[07:43:35.982][Moby           ][Info   ] Call Trace:
[07:43:35.992][Moby           ][Info   ] ---[ end trace 6ea786ab5568684f ]---
[07:43:36.089][Moby           ][Info   ]
[07:43:36.103][Moby           ][Info   ]    OpenRC 0.21.7.e3f10ac is starting up Linux 4.9.41-moby (x86_64)
[07:43:36.104][Moby           ][Info   ]
[07:43:36.110][Moby           ][Info   ]  * Mounting /proc ... [ ok ]
[07:43:36.131][Moby           ][Info   ]  * Mounting /run ... * /run/openrc: creating directory
[07:43:36.146][Moby           ][Info   ]  * /run/BlocUk: creaG: unable to handle kernel ting direNctory
[07:43:36.163][Moby           ][Info   ] ULL pointer dereference * a /run/lockt: co 0000000000000038
[07:43:36.167][Moby           ][Info   ] rrectingIP owne:r
[07:43:36.180][Moby           ][Info   ] [<ffffffff961090f1>] pick_next_task_fair+0x11d/0x349
[07:43:36.185][Moby           ][Info   ] PGD 640cc067 PUD 0
[07:43:36.186][Moby           ][Info   ]
[07:43:36.302][Moby           ][Info   ] BUG: unable to handle kernel NULL pointer dereference at           (null)
[07:43:36.326][Moby           ][Info   ] IP: [<ffffffff96044252>] no_context+0x2c8/0x3a4
[07:43:36.400][Moby           ][Info   ] PGD 640cc067 PUD 0
[07:43:36.401][Moby           ][Info   ]
[
```
