### ISSUE TITLE
Windows 10 - Error on client start - ErrorActionPreference

### ISSUE THREAD

**Issue by manatax** [docker/for-win#1098]
### Expected behavior

Docker client starts normally

### Actual behavior

Error:
> Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 280
   at Docker.Backend.ContainerEngine.Linux.Stop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 146
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

### Information

Diagnostic id:
> 25D03CDC-A9C5-4DBB-AD32-1933C060CA0D/2017-09-15_12-03-37

And I know Hyper-V is available in my machine:
> Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

### Steps to reproduce the behavior

1) Install DOCKER CE FOR WINDOWS
2) Restart

**Comment by alibix** [comment]
also getting this issue

**Comment by jasonbivins** [comment]
Hi @manatax 
It looks like you're running Windows 10 Home, which does not support full Hyper-V functionality. 
You'll need to upgrade your Windows version to Pro, Enterprise or Education editions.

**Comment by jesussandovalprieto** [comment]
I'm facing the same issue and I have installed Windows 10 Enterprise.

**Comment by GiampaoloFalqui** [comment]
I'm also having this issue on Windows 10 Pro.
