### ISSUE TITLE
always crashing when opening Docker

### ISSUE THREAD

**Issue by sosicaboodles** [docker/for-win#11004]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by minsis** [comment]
I am also getting this issue. After digging there is a .net runtime error. This only happened right after I upgraded to the latest version 3.3.1.63152. I saw some blog saying to delete the config.json file which I did - this did not fix the issue.

```
Application: Docker Desktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Docker.Core.Features.Features+<IsEnabled>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.ApiServices.Update.Updater+<CheckForUpdates>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.App+<Initialize>d__25.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

```
Faulting application name: Docker Desktop.exe, version: 3.3.1.63152, time stamp: 0xe4a15171
Faulting module name: KERNELBASE.dll, version: 10.0.18362.1411, time stamp: 0xeb8644a5
Exception code: 0xe0434352
Fault offset: 0x0000000000043b29
Faulting process id: 0x4704
Faulting application start time: 0x01d737918ed893c3
Faulting application path: C:\Program Files\Docker\Docker\Docker Desktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 8498e693-ebdc-4a4c-99e2-533a8cbcbdc6
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by minsis** [comment]
I did a reinstall of Docker Desktop 3.3.1 and that seems to cleared up the issue.

**Comment by scantron-jared-kremer** [comment]
We use Cisco AnyConnect at work. I was able to resolve this issue by making sure AnyConnect VPN was connected, then restarting docker.

**Comment by jonl-percsolutions-com** [comment]
I had the same issue, had to disconnect from our VPN in order to get it to start.

**Comment by juniormayhe** [comment]
for those using Oracle VirtualBox changed Network settings from _NAT_ to _Bridge Adapter_ did the trick
