### ISSUE TITLE
Docker Daemon is not running (Docker Desktop 2.3.03) Docker.Core.HttpBadResponseException: Unhandled exception: Sequence contains no elements

### ISSUE THREAD

**Issue by alpharameeztech** [docker/for-win#11089]
### Server:
ERROR: error during connect: This error may indicate that the docker daemon is not running.: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info: open //./pipe/docker_engine: The system cannot find the file specified.

### Error Trace

Docker.Core.HttpBadResponseException:
Unhandled exception: Sequence contains no elements
   at Docker.Core.Logging.ClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\ClientExceptionInterceptor.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<CreateHyperVVMAsync>d__10.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
Original stacktrace:
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Docker.Backend.HyperVInfrastructure.<CreateDefaultVMAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HyperVInfrastructure.<CreateOrConfigureDockerVMAsync>d__10.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HyperV.<CreateOrConfigureAsync>d__8.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperV.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HttpAPI.HyperVAPIController.<CreateVMAsync>d__7.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\HyperVAPIController.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

### Logs
Version: 2.3.0.3 (45519)
Channel: stable
Sha1: 0356a6f23f086a8134d83ee38d99ffe55a121f02
Started on: 2021/05/04 11:46:31.151
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 19042
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\rameez.israr\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:46:31.331][GUI               ][Info   ] Starting...
[11:46:31.392][ComponentVersions ][Info   ] Edition community
[11:46:31.401][ComponentVersions ][Info   ] Edition community
[11:46:32.001][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[11:46:32.071][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[11:46:32.081][SegmentApi        ][Info   ] Usage statistic: Identify
[11:46:32.469][SegmentApi        ][Info   ] Usage statistic: appLaunched
[11:46:35.416][ApplicationTemplatesTracking][Info   ] Cannot list templates
[11:46:35.421][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[11:46:35.431][SegmentApi        ][Info   ] Usage statistic: heartbeat
[11:46:35.762][LoggingMessageHandler][Info   ] [8aaee4a1] <BackendAPIClient start> GET http://backend/version
[11:46:35.856][LoggingMessageHandler][Info   ] [8aaee4a1] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 87ms)
[11:46:36.261][LoggingMessageHandler][Info   ] [76b3f967] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[11:46:36.281][LoggingMessageHandler][Info   ] [76b3f967] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 18ms)
[11:46:36.301][LoggingMessageHandler][Info   ] [b3affc13] <BackendAPIClient start> POST http://backend/migrate/app
[11:46:36.311][LoggingMessageHandler][Info   ] [b3affc13] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 7ms)
[11:46:36.321][Engines           ][Debug  ] Starting
[11:46:36.366][LoggingMessageHandler][Info   ] [fccc3a38] <BackendAPIClient start> POST http://backend/versionpack/enable
[11:46:36.471][LoggingMessageHandler][Info   ] [fccc3a38] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 107ms)
[11:46:36.711][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[11:46:36.731][GoBackendProcess  ][Info   ] Started
[11:46:36.736][MutagenProcess    ][Info   ] Starting C:\ProgramData\Docker\cli-plugins\docker-mutagen.exe mutagen daemon run
[11:46:36.761][MutagenProcess    ][Info   ] Started
[11:46:36.789][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[11:46:36.791][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[11:46:36.796][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxHyperV
[11:46:36.821][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1620110796}
[11:46:36.821][SystrayNotifications][Info   ] Docker is starting
[11:46:36.845][LoggingMessageHandler][Info   ] [0dcfe16b] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[11:46:37.124][LoggingMessageHandler][Info   ] [0dcfe16b] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 284ms)
[11:46:37.136][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[11:46:37.144][LoggingMessageHandler][Info   ] [c4e2c63f] <BackendAPIClient start> POST http://backend/hyperv/stop
[11:46:37.211][LoggingMessageHandler][Info   ] [c4e2c63f] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 68ms)
[11:46:37.256][VpnKitBridge      ][Info   ] Starting C:\Program Files\Docker\Docker\resources\vpnkit-bridge.exe --addr listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3 host
[11:46:37.286][VpnKitBridge      ][Info   ] Started
[11:46:37.324][MutagenProcess    ][Info   ] [forwarding] Looking for existing sessions
[11:46:37.324][MutagenProcess    ][Info   ] [forwarding] Session manager initialized
[11:46:37.324][MutagenProcess    ][Info   ] [sync] Looking for existing sessions
[11:46:37.324][MutagenProcess    ][Info   ] [sync] Session manager initialized
[11:46:37.331][IsoConfig         ][Info   ] Generating CA Cert Bundle
[11:46:37.452][IsoConfig         ][Info   ] CA Cert Bundle Generated
[11:46:37.465][VpnKitBridge      ][Info   ] listening on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[11:46:37.476][VpnKitBridge      ][Info   ] waiting for connection on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[11:46:38.912][LoggingMessageHandler][Info   ] [7f4f6238] <Server start> GET http://unix/versions
[11:46:39.076][LoggingMessageHandler][Info   ] [7f4f6238] <Server end> GET http://unix/versions -> 200 OK (took 165ms)
[11:46:39.436][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[11:46:39.437][GoBackendProcess  ][Info   ] started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl
[11:46:39.439][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[11:46:39.441][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[11:46:39.441][GoBackendProcess  ][Info   ] enabling filesystem caching
[11:46:39.441][GoBackendProcess  ][Info   ] filesystem exports are:  (2)
[11:46:39.441][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[11:46:39.442][GoBackendProcess  ][Info   ] volume control server listening on \\\\.\\pipe\\dockerVolume
[11:46:39.445][GoBackendProcess  ][Info   ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[11:46:39.445][GoBackendProcess  ][Info   ] file ownership will be determined by the calling user (\"fake owner\" mode)
[11:46:39.446][GoBackendProcess  ][Info   ] using mfsymlinks
[11:46:42.231][LoggingMessageHandler][Info   ] [b5e7794f] <BackendAPIClient start> POST http://backend/hyperv/create
[11:46:42.377][LoggingMessageHandler][Info   ] [b5e7794f] <BackendAPIClient end> POST http://backend/hyperv/create -> 500 InternalServerError (took 145ms)
[11:46:42.416][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[11:46:42.416][LoggingMessageHandler][Info   ] [fa41641f] <BackendAPIClient start> POST http://backend/hyperv/stop
[11:46:42.461][LoggingMessageHandler][Info   ] [fa41641f] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 49ms)
[11:46:42.487][VpnKitBridge      ][Info   ] Killing existing vpnkit-bridge with PID 4040
[11:46:42.519][LoggingMessageHandler][Info   ] [6c2826f8] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[11:46:43.879][LoggingMessageHandler][Info   ] [6c2826f8] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 1365ms)
[11:46:43.891][LoggingMessageHandler][Info   ] [2d3334b9] <BackendAPIClient start> GET http://backend/hyperv/check-virtualization
[11:46:44.161][LoggingMessageHandler][Info   ] [2d3334b9] <BackendAPIClient end> GET http://backend/hyperv/check-virtualization -> 204 NoContent (took 271ms)
[11:46:44.171][LoggingMessageHandler][Info   ] [5afcb015] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[11:46:44.422][LoggingMessageHandler][Info   ] [5afcb015] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 255ms)
[11:46:44.422][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[11:46:44.422][LoggingMessageHandler][Info   ] [852dabfd] <BackendAPIClient start> POST http://backend/hyperv/stop
[11:46:44.526][LoggingMessageHandler][Info   ] [852dabfd] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 102ms)
[11:46:44.581][VpnKitBridge      ][Info   ] Starting C:\Program Files\Docker\Docker\resources\vpnkit-bridge.exe --addr listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3 host
[11:46:44.606][VpnKitBridge      ][Info   ] Started
[11:46:44.606][IsoConfig         ][Info   ] Generating CA Cert Bundle
[11:46:44.723][IsoConfig         ][Info   ] CA Cert Bundle Generated
[11:46:44.771][VpnKitBridge      ][Info   ] listening on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[11:46:44.779][VpnKitBridge      ][Info   ] waiting for connection on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[11:46:45.436][LoggingMessageHandler][Info   ] [48f77c84] <BackendAPIClient start> POST http://backend/hyperv/create
[11:46:45.561][LoggingMessageHandler][Info   ] [48f77c84] <BackendAPIClient end> POST http://backend/hyperv/create -> 500 InternalServerError (took 133ms)
[11:46:45.571][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[11:46:45.571][LoggingMessageHandler][Info   ] [4182c7ee] <BackendAPIClient start> POST http://backend/hyperv/stop
[11:46:45.611][LoggingMessageHandler][Info   ] [4182c7ee] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 48ms)
[11:46:45.632][VpnKitBridge      ][Info   ] Killing existing vpnkit-bridge with PID 1216
[11:46:45.651][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[11:46:45.651][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[11:46:45.651][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxHyperV
[11:46:45.651][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1620110805}
[11:46:45.661][SystrayNotifications][Error  ] Unhandled exception: Sequence contains no elements
[11:46:45.721][GUI               ][Info   ] Sending Bugsnag report a62841f8-2897-4a94-bc56-6e698636aa72...
[11:46:45.921][GUI               ][Info   ] Bugsnag report a62841f8-2897-4a94-bc56-6e698636aa72 sent
[11:46:45.926][SegmentApi        ][Info   ] Usage statistic: eventCrash
[11:46:45.926][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[11:46:46.107][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[11:46:46.108][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[11:46:46.110][GoBackendProcess  ][Info   ] mutagen sync list --output json
[11:46:46.272][Engines           ][Error  ] Start failed with Unhandled exception: Sequence contains no elements
   at Docker.Core.Logging.ClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\ClientExceptionInterceptor.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<CreateHyperVVMAsync>d__10.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__24.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 109)
[11:46:46.775][GoBackendProcess  ][Info   ] mutagen C:\\ProgramData\\Docker\\cli-plugins\\docker-mutagen.exe mutagen sync list --output json: null\n
[11:46:46.775][GoBackendProcess  ][Info   ] external: GET /sync 200 \"Go-http-client/1.1\" \"\
[11:46:57.310][ErrorReportWindow ][Info   ] Open logs

However, the virtualization is working fine.
As I updated docker for windows from 2.0.2 to 3.3.1, I am getting this error.

The version 2.0.2 was working just fine with WSL option enabled.

Tried tons of things but nothing seems to work.

Any help would be much appreciated.

**Comment by alpharameeztech** [comment]
> I have the same problem. I tried reinstalling over versions, which I know used to work, but still have the problem. I've ended up uninstalling Docker for now as I can't get it to work.

It's driving me nuts, lol.

It actually stopped working right after the windows update which is really creepy. Now I cant find any other way to make it run. 

@mcacker which docker desktop version you have tried?

**Comment by mcacker** [comment]
@alpharameeztech I found that the latest version, 3.3.2, now works.  I installed it yesterday, and all is good.  They must have fixed it over the weekend

**Comment by alpharameeztech** [comment]
@macdja38 did you run it with the WSL2 option?

**Comment by macdja38** [comment]
> @macdja38 did you run it with the WSL2 option?

Wrong person

**Comment by alpharameeztech** [comment]
> @alpharameeztech yes, WSL 2

@mcacker nice, I will give it a try today and let you know then

**Comment by alpharameeztech** [comment]
@mcacker Unfortunately it isn't working for me. I am unable to switch to WSL2 even after following the guideline.
