### ISSUE TITLE
Unable to start, (re)install, or remove Docker Desktop for Windows.

### ISSUE THREAD

**Issue by cpswan** [docker/for-win#11101]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 71FB420F-DAAB-48DB-A39B-22A31C8685B4/20210501163516

  - [x] I did not have any experimental features enabled

### Actual behavior

Docker service fails to start

```
The com.docker.service service failed to start due to the following error: 
com.docker.service is not a valid Win32 application.
```

If I try to install Docker from a freshly downloaded Docker Desktop Installer I get the `Are you sure?` dialogue:

![image](https://user-images.githubusercontent.com/478926/116789345-4989e900-aaa6-11eb-9aa0-78bacd03b12f.png)

But on clicking Yes:

```
The file or directory is corrupted and unreadable
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at CommunityInstaller.ExecAction.<RunAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.ExecAction.<DoAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<UninstallAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

![image](https://user-images.githubusercontent.com/478926/116789407-8bb32a80-aaa6-11eb-8b9c-c7ae3eb114a1.png)

I have run `chkdsk /f /x` on my C: drive.

If I try to uninstall Docker (having renamed the original corrupted installer and copied in a new one) it hangs at `Removing VM and images`:

![image](https://user-images.githubusercontent.com/478926/116789302-1d6e6800-aaa6-11eb-8d51-634c33624687.png)

### Expected behavior

Docker service starts when PC boots up.

Running Docker Desktop Installer fixes or overwrites broken installation.

Add/Remove Programs allows me to uninstall Docker so that I can do a clean reinstall.

### Information

  - I don't use Docker every day, so I'm not sure when my installation broke, it just wasn't there when I needed it :(
  - I always accept new updates when they come along
  - I have tried renaming the C:\Program Files\Docker directory before running an install, but that makes no difference.
  - Windows Version: Windows 10 Pro 20H2 build 19042.964 experience 120.2212.2020.0
  - Docker Desktop Version: 3.2.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. I'm unable to start Docker, remove Docker or (re)install Docker, so not much more I can do here.

**Comment by cpswan** [comment]
I managed to fix this myself by tracking down all traces of Docker on the filesystem and in the registry and turning them into Docker_old so that the installer wouldn't fail at removing my old version - essentially a manual uninstall.

This included:

C:\Program Files\Docker
C:\Users\%USERNAME%\.docker
C:\Users\%USERNAME%\AppData\Local\Docker
C:\Users\%USERNAME%\AppData\Roaming\Docker
C:\Users\%USERNAME%\AppData\Roaming\Docker Desktop

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Docker Inc.
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Docker Desktop
