### ISSUE TITLE
Docker Desktop can't startup and keep spinning

### ISSUE THREAD

**Issue by icharge** [docker/for-win#11202]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9063A480-93D3-491E-A686-1173A31103A4/20210513134603

### Information

  - Windows Version: 10 (20H0  Build 19042.631) 
  - Docker Desktop Version: 3.3.3 (64133)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, Run on laptop

### Steps to reproduce the behavior

  1. Run Docker Desktop ( first time it say something failed to start and close by itself )
  2. Run again and keep spinning a long time and error

![image](https://user-images.githubusercontent.com/1619007/118146959-4e9d4f80-b439-11eb-8d7c-50e29bf33bd2.png)

Log file:
```
Version: 3.3.3 (64133)
Sha1: 68eba96de8051dcb12cf43b3a6955f1ee7156b4b
Started on: 2021/05/13 20:35:41.104
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 19042
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\norrapatnim\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[20:35:41.174][GUI               ][Info   ] Starting...
[20:35:41.272][LoggingMessageHandler][Info   ] [a563fa8c] <GoBackendClient start> GET http://localhost/ping
[20:35:41.289][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[20:35:41.375][AppMigrator       ][Info   ] Current version: 9. Latest version: 9
[20:35:41.401][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[20:35:41.410][GoBackendProcess  ][Info   ] Started
[20:35:41.410][TrackingSettings  ][Info   ] Crash report and usage statistics are disabled
[20:35:41.418][SegmentApi        ][Info   ] Usage statistic: heartbeat
[20:35:41.480][GoBackendProcess  ][Info   ] msg="starting backend server"
[20:35:41.481][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[20:35:41.481][GoBackendProcess  ][Info   ] msg="started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl"
[20:35:41.481][GoBackendProcess  ][Info   ] msg="listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection"
[20:35:41.481][GoBackendProcess  ][Info   ] msg="adding routes for /docker.tar"
[20:35:41.481][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\docker_cli
[20:35:41.481][GoBackendProcess  ][Info   ] msg="adding routes for /kube-images.tar"
[20:35:41.481][GoBackendProcess  ][Info   ] msg="adding routes for /docker.tar"
[20:35:41.481][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[20:35:41.481][GoBackendProcess  ][Info   ] msg="adding routes for /services.tar -> C:\\Program Files\\Docker\\Docker\\resources\\services.tar"
[20:35:41.481][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[20:35:41.481][GoBackendProcess  ][Info   ] msg="adding routes for /kube-images.tar"
[20:35:41.481][GoBackendProcess  ][Info   ] msg="adding routes for /services.tar -> C:\\Program Files\\Docker\\Docker\\resources\\services.tar"
[20:35:41.614][LoggingMessageHandler][Info   ] [ad59249f] <GoBackendClient start> GET http://localhost/ping
[20:35:41.633][GoBackendProcess  ][Info   ] msg="external: GET /ping 200 \"DockerDesktopCSharp\" \"\""
[20:35:41.642][LoggingMessageHandler][Info   ] [ad59249f] <GoBackendClient end> GET http://localhost/ping -> 200 OK (took 36ms)
[20:35:41.642][GoBackendClient   ][Info   ] backend API ready
[20:35:41.658][LoggingMessageHandler][Info   ] [e358170c] <GoBackendClient start> GET http://localhost/features
[20:35:41.658][GoBackendProcess  ][Info   ] msg="external: GET /features 200 \"DockerDesktopCSharp\" \"\""
[20:35:41.662][LoggingMessageHandler][Info   ] [e358170c] <GoBackendClient end> GET http://localhost/features -> 200 OK (took 4ms)
[20:35:41.715][Features          ][Info   ] User plan: free
[20:35:42.821][LoggingMessageHandler][Info   ] [bd8bc400] <Server start> GET http://unix/settings
[20:35:42.904][LoggingMessageHandler][Info   ] [bd8bc400] <Server end> GET http://unix/settings -> 200 OK (took 78ms)
[20:35:42.954][GoBackendProcess  ][Info   ] msg="NewSharer: WSL2 engine is enabled so no file sharer is required."
[20:35:42.954][GoBackendProcess  ][Info   ] msg="enabling filesystem caching"
[20:35:42.954][GoBackendProcess  ][Info   ] msg="filesystem exports are:  (2)"
[20:35:42.954][GoBackendProcess  ][Info   ] msg="volume control server listening on \\\\.\\pipe\\dockerVolume"
[20:35:42.954][GoBackendProcess  ][Info   ] msg="filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3"
[20:35:42.954][GoBackendProcess  ][Info   ] msg="filesystem server listening on \\\\.\\pipe\\dockerFilesystem"
[20:35:42.954][GoBackendProcess  ][Info   ] msg="file ownership will be determined by the calling user (\"fake owner\" mode)"
[20:35:42.954][GoBackendProcess  ][Info   ] msg="using mfsymlinks"
[20:35:42.964][LoggingMessageHandler][Info   ] [5381e76c] <Server start> GET http://unix/settings
[20:35:42.966][LoggingMessageHandler][Info   ] [5381e76c] <Server end> GET http://unix/settings -> 200 OK (took 2ms)
[20:35:42.967][GoBackendProcess  ][Info   ] msg="Static DNS lookup table: map[docker-desktop.:192.168.65.4 docker-for-desktop.:192.168.65.4 docker.for.mac.gateway.internal.:192.168.65.2 docker.for.mac.host.internal.:192.168.65.2 docker.for.mac.localhost.:192.168.65.2 gateway.docker.internal.:192.168.65.2 host.docker.internal.:192.168.65.2 http.docker.internal.:192.168.65.5 kubernetes.docker.internal.:192.168.65.4 vm.docker.internal.:192.168.65.4]"
[20:35:42.967][GoBackendProcess  ][Info   ] msg="DNS: TCP server listening on \\\\.\\pipe\\dockerDNSTCP"
[20:35:42.967][GoBackendProcess  ][Info   ] msg="DNS: UDP server listening on \\\\.\\pipe\\dockerDNSUDP"
[20:36:00.955][LoggingMessageHandler][Info   ] [aeb8a871] <BackendAPIClient start> GET http://backend/version
[20:36:01.379][LoggingMessageHandler][Info   ] [aeb8a871] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 424ms)
[20:36:01.379][LoggingMessageHandler][Info   ] [0f75ee32] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[20:36:01.443][LoggingMessageHandler][Info   ] [0f75ee32] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 56ms)
[20:36:01.444][LoggingMessageHandler][Info   ] [71dac228] <BackendAPIClient start> POST http://backend/migrate/app
[20:36:01.444][LoggingMessageHandler][Info   ] [71dac228] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 7ms)
[20:36:01.458][Updater           ][Debug  ] Starting check for updates
[20:36:02.587][CliInstaller      ][Info   ] Reading build information from appcast
[20:36:02.587][CliInstaller      ][Info   ] Launcher process exited with -1
[20:36:02.587][Updater           ][Debug  ] Finished check for updates
[20:36:02.587][Engines           ][Debug  ] Starting
[20:36:02.587][LoggingMessageHandler][Info   ] [c1dc0b4f] <BackendAPIClient start> POST http://backend/versionpack/enable
[20:36:02.601][UpdateCheckTimer  ][Debug  ] Check for updates
[20:36:02.601][Updater           ][Debug  ] Starting check for updates
[20:36:02.695][LoggingMessageHandler][Info   ] [c1dc0b4f] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 97ms)
[20:36:02.697][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[20:36:02.697][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[20:36:02.697][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxWSL2
[20:36:02.697][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1620912962}
[20:36:02.697][SystrayNotifications][Info   ] Docker is starting
[20:36:02.712][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[20:36:02.712][LoggingMessageHandler][Info   ] [b16c6ab9] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[20:36:02.935][WSL2Provisioning  ][Info   ] Checking docker-desktop
[20:36:02.939][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\norrapatnim\AppData\Local\Docker\wsl\distro
[20:36:02.994][LoggingMessageHandler][Info   ] [b16c6ab9] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 279ms)
[20:36:03.753][CliInstaller      ][Info   ] Reading build information from appcast
[20:36:03.763][Updater           ][Debug  ] Finished check for updates
[20:36:03.774][ElectronWindows   ][Info   ] Showing dashboard page
[20:36:04.661][LoggingMessageHandler][Info   ] [d172f95b] <Server start> POST http://localhost/notifications/subscriptions
[20:36:04.715][LoggingMessageHandler][Info   ] [15cd85b5] <NotificationsClient start> GET http://localhost/ping
[20:36:04.758][LoggingMessageHandler][Info   ] [15cd85b5] <NotificationsClient end> GET http://localhost/ping -> 200 OK (took 43ms)
[20:36:04.758][LoggingMessageHandler][Info   ] [d172f95b] <Server end> POST http://localhost/notifications/subscriptions -> 200 OK (took 98ms)
[20:36:05.167][LoggingMessageHandler][Info   ] [7a68d64d] <Server start> POST http://localhost/usage
[20:36:05.172][LoggingMessageHandler][Info   ] [7a68d64d] <Server end> POST http://localhost/usage -> 200 OK (took 4ms)
[20:36:05.223][GoBackendProcess  ][Info   ] msg="external: GET /features 200 \"axios/0.21.1\" \"\""
[20:36:05.224][LoggingMessageHandler][Info   ] [e6da593f] <Server start> GET http://localhost/kubernetes
[20:36:05.224][LoggingMessageHandler][Info   ] [60fbf554] <Server start> GET http://localhost/settings
[20:36:05.224][LoggingMessageHandler][Info   ] [75a9fb65] <Server start> GET http://localhost/registry/user
[20:36:05.226][LoggingMessageHandler][Info   ] [b839faf5] <Server start> GET http://localhost/versions
[20:36:05.227][LoggingMessageHandler][Info   ] [28d4cbeb] <Server start> GET http://localhost/update
[20:36:05.233][UpdateController  ][Info   ] Getting update available time: 0
[20:36:05.236][LoggingMessageHandler][Info   ] [75a9fb65] <Server end> GET http://localhost/registry/user -> 200 OK (took 11ms)
[20:36:05.236][LoggingMessageHandler][Info   ] [e6da593f] <Server end> GET http://localhost/kubernetes -> 200 OK (took 11ms)
[20:36:05.237][LoggingMessageHandler][Info   ] [60fbf554] <Server end> GET http://localhost/settings -> 200 OK (took 12ms)
[20:36:05.238][LoggingMessageHandler][Info   ] [28d4cbeb] <Server end> GET http://localhost/update -> 200 OK (took 11ms)
[20:36:05.242][LoggingMessageHandler][Info   ] [c6bdbd43] <Server start> GET http://localhost/docker
[20:36:05.246][LoggingMessageHandler][Info   ] [c6bdbd43] <Server end> GET http://localhost/docker -> 200 OK (took 4ms)
[20:36:05.268][GoBackendProcess  ][Info   ] msg="external: GET /system/editor 200 \"axios/0.21.1\" \"\""
[20:36:05.303][GoBackendProcess  ][Info   ] msg="external: GET /features 200 \"axios/0.21.1\" \"\""
[20:36:05.306][LoggingMessageHandler][Info   ] [9e4114fc] <Server start> GET http://localhost/system/disk-usage?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data
[20:36:05.343][LoggingMessageHandler][Info   ] [9e4114fc] <Server end> GET http://localhost/system/disk-usage?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data -> 200 OK (took 37ms)
[20:36:05.365][LoggingMessageHandler][Info   ] [b839faf5] <Server end> GET http://localhost/versions -> 200 OK (took 138ms)
[20:36:08.248][GoBackendProcess  ][Info   ] msg="external: GET /features 200 \"axios/0.21.1\" \"\""
[20:36:08.251][LoggingMessageHandler][Info   ] [2f6c5620] <Server start> GET http://localhost/settings
[20:36:08.254][LoggingMessageHandler][Info   ] [2f6c5620] <Server end> GET http://localhost/settings -> 200 OK (took 2ms)
[20:36:08.268][LoggingMessageHandler][Info   ] [78247734] <Server start> GET http://localhost/system/disk-usage?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data
[20:36:08.269][LoggingMessageHandler][Info   ] [78247734] <Server end> GET http://localhost/system/disk-usage?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data -> 200 OK (took 0ms)
[20:36:08.811][UpdatePopupTimer  ][Info   ] Starting timer
[20:36:08.813][UpdatePopupTimer  ][Info   ] Update available date: 1/1/1970 12:00:00 AM +00:00
[20:36:08.813][UpdatePopupTimer  ][Info   ] Update popup appearance date: 1/1/1970 12:00:00 AM +00:00
[20:46:03.169][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\norrapatnim\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: The operation could not be started because a required feature is not installed.


 stderr: 
[20:46:03.173][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[20:46:03.247][LinuxWSL2Engine   ][Info   ] Stopping engine
[20:46:03.311][LoggingMessageHandler][Info   ] [9680774c] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[20:46:03.312][BackendAPIClient  ][Warning] HttpOS Client: connection timed out.
[20:46:03.314][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[20:46:03.314][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[20:46:03.315][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxWSL2
[20:46:03.315][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1620913563}
[20:46:03.319][LoggingMessageHandler][Info   ] [085b7481] <NotificationsClient start> POST http://localhost/engine/state
[20:46:03.328][SystrayNotifications][Error  ] System.TimeoutException: The operation has timed out.
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.NamedPipe.NamedPipeDialer.<DialAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.Client.DialMessageHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<CheckFeaturesAsync>d__4.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoCheckPreconditionsAsync>d__31.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 280
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 62
[20:46:03.336][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[20:46:03.372][LoggingMessageHandler][Info   ] [085b7481] <NotificationsClient end> POST http://localhost/engine/state -> 200 OK (took 53ms)
[20:46:03.427][Engines           ][Error  ] Start failed with The operation has timed out.
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.NamedPipe.NamedPipeDialer.<DialAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.Client.DialMessageHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<CheckFeaturesAsync>d__4.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoCheckPreconditionsAsync>d__31.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 280
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__21.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 101)
[20:46:25.804][GoBackendProcess  ][Info   ] msg="external: GET /diagnostics/goroutines 200 \"Go-http-client/1.1\" \"\""
[20:46:25.804][GoBackendProcess  ][Info   ] msg="external: GET /events 200 \"DockerDesktopGo\" \"\""
[20:46:25.805][GoBackendProcess  ][Info   ] GET failed with Get "http://unix/forwards/list": open \\.\pipe\dockerWsl2BootstrapExposePorts: The system cannot find the file specified.
[20:46:25.805][GoBackendProcess  ][Info   ] msg="external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\""
[20:46:25.817][GoBackendProcess  ][Info   ] msg="external: GET /ping 200 \"DockerDesktopGo\" \"\""
[21:35:41.423][SegmentApi        ][Info   ] Usage statistic: heartbeat
[22:14:24.829][ErrorReportWindow ][Info   ] Open diagnostics

```

**Comment by icharge** [comment]
I just try to remove following folders and it worked !

%appdata%\Roaming\Docker
%appdata%\Roaming\Docker Desktop
