### ISSUE TITLE
Docker failed to intialize

### ISSUE THREAD

**Issue by saeedramzaan** [docker/for-win#11273]
System.ArgumentException:
Unable to create an instance of Docker.App: Unable to create an instance of Docker.ApiServices.Update.UpdateCheckTimer: Unable to create an instance of Docker.ApiServices.Update.Updater: Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
   at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
   at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
   at Docker.Core.Di.Singletons.Get[T]() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 28
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 281

  System.ArgumentException:
  Unable to create an instance of Docker.ApiServices.Update.UpdateCheckTimer: Unable to create an instance of Docker.ApiServices.Update.Updater: Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
     at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
     at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
     at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
  
     System.ArgumentException:
     Unable to create an instance of Docker.ApiServices.Update.Updater: Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
        at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
        at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
        at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
        at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
        at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
        at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
     
         System.ArgumentException:
         Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
            at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 93
            at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
            at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
            at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
            at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
            at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
         
              System.Reflection.TargetInvocationException:
              Exception has been thrown by the target of an invocation.
                 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
                 at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
                 at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
              
                    System.Runtime.InteropServices.COMException:
                    Retrieving the COM class factory for component with CLSID {1ECCA34C-E88A-44E3-8D6A-8921BDE9E452} failed due to the following error: 80070422 The service cannot be started, either because it is disabled or because it has no enabled devices associated with it. (Exception from HRESULT: 0x80070422).
                       at Docker.Notifications.BackgroundUpdateWatcher..ctor(ISystrayNotifications systray, IUpdateStateNotifier updateStateNotifier) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Desktop\Notifications\BackgroundUpdateWatcher.cs:line 12

Can anyone please support me to solve this issue?

![Capture](https://user-images.githubusercontent.com/84608545/119212425-0a2f3680-ba6d-11eb-81bd-e72aa0b42807.PNG)

**Comment by intile** [comment]
I am having this issue as well!

**Comment by zagnut999** [comment]
Me too.  v 3.3.3 and windows 10 pro.  Diagnostic id: E41BC9DD-55D0-4EDC-9BE4-3821E50836F8/20210609145924
I've uninstalled -> rebooted -> reinstalled twice and it keeps coming back.

**Comment by zagnut999** [comment]
> Me too. v 3.3.3 and windows 10 pro. Diagnostic id: E41BC9DD-55D0-4EDC-9BE4-3821E50836F8/20210609145924
> I've uninstalled -> rebooted -> reinstalled twice and it keeps coming back.

I think mine is because of a bad system update as I can't get in to network properties in windows.

**Comment by mat007** [comment]
Hi, can you check the status of the `Background Intelligent Transfer Service` in the services?
Is it running?

**Comment by mat007** [comment]
@zagnut999 your error looks different, from your logs:
> Retrieving the COM class factory for component with CLSID {1ECCA34C-E88A-44E3-8D6A-8921BDE9E452} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).

**Comment by Olubolar614** [comment]
> > Retrieving the COM class factory for component with CLSID {1ECCA34C-E88A-44E3-8D6A-8921BDE9E452} failed due to the following error: 80070422 The service cannot be started, either because it is disabled or because it has no enabled devices associated with it. (Exception from HRESULT: 0x80070422).
> 
> Hi, can you check the status of the `Background Intelligent Transfer Service` in the services?
> Is it running?

Background intelligent transfer service is currently not running on my local machine and when I tried to start, I got this error
![Background_Intelligent_Transfer_Start_Error](https://user-images.githubusercontent.com/26840342/121488742-477f4800-c9cb-11eb-8a3c-77a01a1b2151.JPG)

**Comment by mat007** [comment]
@Olubolar614 thanks, that looks like the same error you reported in #11404.
Obviously it shouldn’t prevent Docker Desktop to start (I’ll create an internal ticket to fix that), but it looks like there is something wrong with this service on your system.

**Comment by ziwer1** [comment]
@mat007 I have got this same issue. Diagnostic ID: A1A70C77-21C1-496F-93C2-8A3B778488AE/20210621130253

**Comment by cwatzl** [comment]
Me and several coworkers at my company were having the same problem. It turned out that the "Background Intelligent Transfer Service" was disabled on all company computers through a Group Policy. The solution was basically to ask our IT team to change that Group Policy. Cost us many hours overall to get to the bottom of this. 
I think it's rather weird that the Docker daemon would refuse to start altogether because a nonessential convenience feature (i.e. auto-update) doesn't work due to an external service dependency which isn't guaranteed to be available. I wish it would handle this gracefully.

**Comment by mat007** [comment]
> I wish it would handle this gracefully.

Yes, that’s the plan. It will be too short for the next release (3.5.0 later this week), but hopefully the next one after that will deal with it correctly.

**Comment by radRares1** [comment]
for anyone that has the problem.

I fixed it by
going to %ALLUSERSPROFILE%\Application Data\Microsoft\Network\Downloader\ (use the Win + R, paste and enter)
delete qmgr.dat file (which is probably corrupt)
open a PowerShell/cmd with admin rights
run ‘net start bits’ command
run docker and it should work.

At least this worked for me.
Consider that this is my personal system, not a company one. 
LE: in case your Background Intelligent Transfer Service is not starting, the above might fix your problem.

**Comment by longqua69** [comment]
Hi all,

According to the instruction in the link [Docker failed to initialize](https://forums.docker.com/t/docker-failed-to-initialize-operation-timed-out/111321/13), I resolved this issue by:
```
C:\Users[USER]\AppData\Local\Docker
C:\Users[USER]\AppData\Roaming\Docker
C:\Users[USER]\AppData\Roaming\Docker Desktop

Once deleted, I didn’t have to do anything else, Docker Desktop started booting up as normal.
```
This way worked for me and many people.
