### ISSUE TITLE
[Windows 10 Enterprise] Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by McFoggy** [docker/for-win#1131]
### Expected behavior
Docker for linux containers works

### Actual behavior
Docker for linux containers fails to start but Docker for Windows containers works correctly

### Information

- **Diagnostic ID : 16F345D6-6558-4EEE-BCAD-A029472799CB/2017-09-27_11-13-49**
- **Docker CE**:
```
Version: 17.06.2-ce-win27 (13194)
Channel: stable
Sha1: 428bd6ceae2994bd2fc2a72ec122507abe2cf526
Started on: 2017/09/27 11:06:03.671
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.0.amd64fre.rs1_release.160715-1616
```
- **Windows**
```
PS C:\windows\system32> Get-CimInstance Win32_OperatingSystem | FL *


Status                                    : OK
Name                                      : Microsoft Windows 10 Enterprise|C:\windows|\Device\Harddisk0\Partition3
FreePhysicalMemory                        : 29319596
FreeSpaceInPagingFiles                    : 5242880
FreeVirtualMemory                         : 34534104
Caption                                   : Microsoft Windows 10 Enterprise
Description                               :
InstallDate                               : 14/09/2017 16:15:28
CreationClassName                         : Win32_OperatingSystem
CSCreationClassName                       : Win32_ComputerSystem
CSName                                    : MORLK964
CurrentTimeZone                           : 120
Distributed                               : False
LastBootUpTime                            : 27/09/2017 11:03:08
LocalDateTime                             : 27/09/2017 11:16:51
MaxNumberOfProcesses                      : 4294967295
MaxProcessMemorySize                      : 137438953344
NumberOfLicensedUsers                     : 0
NumberOfProcesses                         : 119
NumberOfUsers                             : 11
OSType                                    : 18
OtherTypeDescription                      :
SizeStoredInPagingFiles                   : 5242880
TotalSwapSpaceSize                        :
TotalVirtualMemorySize                    : 38676044
TotalVisibleMemorySize                    : 33433164
Version                                   : 10.0.14393
BootDevice                                : \Device\HarddiskVolume1
BuildNumber                               : 14393
BuildType                                 : Multiprocessor Free
CodeSet                                   : 1252
CountryCode                               : 33
CSDVersion                                :
DataExecutionPrevention_32BitApplications : True
DataExecutionPrevention_Available         : True
DataExecutionPrevention_Drivers           : True
DataExecutionPrevention_SupportPolicy     : 2
Debug                                     : False
EncryptionLevel                           : 256
ForegroundApplicationBoost                : 2
LargeSystemCache                          :
Locale                                    : 040c
Manufacturer                              : Microsoft Corporation
MUILanguages                              : {en-US}
OperatingSystemSKU                        : 4
Organization                              : Agfa Healthcare
OSArchitecture                            : 64-bit
OSLanguage                                : 1033
OSProductSuite                            : 256
PAEEnabled                                :
PlusProductID                             :
PlusVersionNumber                         :
PortableOperatingSystem                   : False
Primary                                   : True
ProductType                               : 1
RegisteredUser                            : Agfa Healthcare
SerialNumber                              : XXXXX-XXXXX-XXXXX-XXXXX
ServicePackMajorVersion                   : 0
ServicePackMinorVersion                   : 0
SuiteMask                                 : 272
SystemDevice                              : \Device\HarddiskVolume3
SystemDirectory                           : C:\windows\system32
SystemDrive                               : C:
WindowsDirectory                          : C:\windows
PSComputerName                            :
CimClass                                  : root/cimv2:Win32_OperatingSystem
CimInstanceProperties                     : {Caption, Description, InstallDate, Name...}
CimSystemProperties                       : Microsoft.Management.Infrastructure.CimSystemProperties
```

Starting Docker For Windows fails in the end with the following error

```
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 267
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 251
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```
While starting, if I look at Hyper-V manager, I see the MobiLinuxVM being created/started/stopped/destroy several times until the error pops-up.

I have tried several things:
- delete MobiLinuxVM.vhdx file and let docker recreate it
- uninstall/reinstall docker-ce
- uninstall/reinstall docker-ce with hyper-V activated/deactivated (letting docker reactivating it)

I am out of trials & ideas. Thanks to anyone who can help.

**Comment by McFoggy** [comment]
I also tried with edge version [_Version 17.09.0-ce-rc3-win30 (13392), Channel: edge, 68d0b20_] but it failed with the same error than before.

**Diagnostic ID** : 16F345D6-6558-4EEE-BCAD-A029472799CB/2017-09-27_15-01-46

**Comment by AKravanja** [comment]
Same problem.
Version: 17.06.2-ce-win27 (13194)
**Diagnostic ID:** 1802B338-86B8-4292-B10F-2213DE2D7541/2017-09-29_15-00-12

**Comment by McFoggy** [comment]
Finally i got it working after:
- I have updated my windows version from OS.Build `14393.0` to `14393.1358`
- performed a reinstallation of docker for windows using the stable channel: [Version 17.09.0-ce-win32 (13529)]

Looks like the windows build was the culprit.

Now my system is
![image](https://user-images.githubusercontent.com/1119660/31189246-f10a65c0-a937-11e7-95dc-b3b1fd4beed2.png)
