### ISSUE TITLE
Installation failure on Windows 7

### ISSUE THREAD

**Issue by oldhen** [docker/for-win#1138]
### Expected behavior
Installer to execute

### Actual behavior
"LightweightInstaller has stopped working"

#### Application event log 1
Application: Docker for Windows Installer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   at System.Reflection.Assembly.Load(System.Reflection.AssemblyName)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveAssembly(BamlAssembly)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlTypeToType(BamlType)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType, Int16)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16)
   at System.Windows.Baml2006.Baml2006Reader.Process_ElementStart()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.ReadObject(System.Windows.Baml2006.KeyRecord)
   at System.Windows.ResourceDictionary.CreateObject(System.Windows.Baml2006.KeyRecord)
   at System.Windows.ResourceDictionary.OnGettingValue(System.Object, System.Object ByRef, Boolean ByRef)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(System.Object, System.Object ByRef, Boolean ByRef)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(System.Object, Boolean ByRef)
   at System.Windows.ResourceDictionary.GetValue(System.Object, Boolean ByRef)
   at System.Windows.DeferredResourceReference.GetValue(System.Windows.BaseValueSourceInternal)
   at System.Windows.DependencyPropertyChangedEventArgs.get_NewValue()
   at System.Windows.FrameworkElement.OnStyleChanged(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
   at System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, System.Windows.EffectiveValueEntry ByRef, Boolean, Boolean, System.Windows.OperationType)
   at System.Windows.DependencyObject.SetValueCommon(System.Windows.DependencyProperty, System.Object, System.Windows.PropertyMetadata, Boolean, Boolean, System.Windows.OperationType, Boolean)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(System.Object, System.Object)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(System.Object, System.Xaml.XamlMember, System.Object)

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at LightweightInstaller.Wizard..ctor(LightweightInstaller.IChannelHelper)
   at LightweightInstaller.Cmd.CommandResolver.Resolve(System.String[])
   at LightweightInstaller.Program.Main(System.String[])

#### Application event log 2
Faulting application name: Docker for Windows Installer.exe, version: 1.0.97.0, time stamp: 0x59afcd2c
Faulting module name: KERNELBASE.dll, version: 6.1.7601.23889, time stamp: 0x598d50ba
Exception code: 0xe0434352
Fault offset: 0x000000000001a06d
Faulting process id: 0x1020
Faulting application start time: 0x01d3386ed3eded52
Faulting application path: C:\Users\Glenn\Downloads\Docker for Windows Installer.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: 11a843ae-a462-11e7-b06c-d850e641cbd5

#### OS details
Windows 7 Professional 64-bit
.NET version 4.7.02053

### Steps to reproduce the behavior
Run Docker for Windows Installer.exe

**Comment by jasonbivins** [comment]
Hi @oldhen   Docker for Windows requires Win 10 or Server 2016 due to the Hyper-V requirements.
https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install

Have you tried Docker Toolbox?  It should work for you since it doesn't have the same Hyper-V requirements - https://docs.docker.com/toolbox/overview/

**Comment by oldhen** [comment]
Thanks for the info.  I'll try Docker Toolbox, as I'm just doing some evaluation before targeting a proper OS

**Comment by AyoubIDAOUBELLAL** [comment]
القحاب
