### ISSUE TITLE
Docker Desktop error: Failed to set version to docker-desktop: exit code: 1

### ISSUE THREAD

**Issue by splashsky** [docker/for-win#11384]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 

### Actual behavior
Starts Docker Desktop boot process. Notification appears stating "Attempting to start Docker with WSL 2 backend...", but icon in tray goes red and errors out with the error and stacktrace below.

### Expected behavior
Docker Desktop should boot and the Docker Daemon should be 100% functional.

### Information
This issue happens every time I attempt to start Docker/Docker Desktop. I am on Windows 10 Home, Build 21930.co_release.210521-1658, using Ubuntu 20.04 on WSL 2.

- I have followed the official Microsoft guide for installing WSL 2.
- I have attempted `netsh winsock reset` and rebooted my computer.
- I have attempted to press "Reset to Factory Default Settings" on the Docker Desktop error window.
- I have attempted the `NoLsp.exe` workaround outlined in another issue.

Here is the stacktrace and error.
```
System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: 1
 stdout: 
 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

**Comment by stephen-turner** [comment]
What does `wsl -l -v` show?

**Comment by splashsky** [comment]
```
PS C:\Users\skyle> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2
```

**Comment by stephen-turner** [comment]
Strange, you don't have the Docker distros at all. I'm not sure what to suggest other than uninstalling and reinstalling Docker Desktop.
