### ISSUE TITLE
docker for windows does not start on windows startup

### ISSUE THREAD

**Issue by enterprisebug** [docker/for-win#11410]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A2D2B013-F740-4FC8-B852-709BDFB56724/20210609062408 (uploaded)

### Actual behavior

- i have enabled `[x] Start Docker Desktop when you log in`
- tray icon displays ![image](https://user-images.githubusercontent.com/1539741/121307894-c3608e00-c900-11eb-9450-18f4ae4ed926.png)
- when i hover over the icon it disappears

### Expected behavior
- Docker starts without failure on windows start

### Information

  - Windows Version: **Windows 10 Enterprise**
  - Docker Desktop Version: **3.3.3 (64133)**
  - WSL2 or Hyper-V backend?  **WSL2**
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **local machine**

```
Version: 3.3.3 (64133)
Sha1: 68eba96de8051dcb12cf43b3a6955f1ee7156b4b
Started on: 2021/06/09 08:49:43.664
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1909
Build: 18363
BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
File: C:\Users\k579120\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" -Autostart
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[08:49:43.758][GUI               ][Info   ] Starting...
[08:49:43.883][LoggingMessageHandler][Info   ] [722e27be] <GoBackendClient start> GET http://localhost/ping
[08:49:43.945][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:49:44.255][LoggingMessageHandler][Info   ] [0545ebf8] <GoBackendClient start> GET http://localhost/ping
[08:49:44.255][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:49:44.380][AppMigrator       ][Info   ] Current version: 9. Latest version: 9
[08:49:44.380][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[08:49:44.568][LoggingMessageHandler][Info   ] [f35ab66e] <GoBackendClient start> GET http://localhost/ping
[08:49:44.568][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:49:44.630][GoBackendProcess  ][Info   ] Started
[08:49:44.630][TrackingSettings  ][Info   ] Crash report and usage statistics are disabled
[08:49:44.646][SegmentApi        ][Info   ] Usage statistic: heartbeat
[08:49:53.572][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:49:53.884][LoggingMessageHandler][Info   ] [4cd65547] <GoBackendClient start> GET http://localhost/ping
[08:49:53.884][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:49:53.884][LoggingMessageHandler][Info   ] [ab58a08f] <GoBackendClient start> GET http://localhost/ping
[08:49:53.884][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:49:53.915][GoBackendClient   ][Error  ] Error refreshing features: Docker.Core.DockerException: unable to ping backend API: The operation has timed out.
at Docker.Core.GoBackend.GoBackendClient.WaitUntilReady() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 88
at Docker.Core.GoBackend.GoBackendClient.<GetFeaturesAsync>d__8.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 143
[08:49:53.915][SegmentApi        ][Warning] Failed to track event heartbeat: Value cannot be null.
Parameter name: source
[08:49:53.915][Features          ][Info   ] User plan: free
[08:49:54.024][LoggingMessageHandler][Info   ] [ef4e43c6] <BackendAPIClient start> GET http://backend/version
[08:49:54.196][LoggingMessageHandler][Info   ] [9c353146] <GoBackendClient start> GET http://localhost/ping
[08:49:54.196][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:49:54.508][LoggingMessageHandler][Info   ] [761be833] <GoBackendClient start> GET http://localhost/ping
[08:49:54.508][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:49:54.665][LoggingMessageHandler][Info   ] [ef4e43c6] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 642ms)
[08:49:54.680][LoggingMessageHandler][Info   ] [55e8a29e] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[08:49:54.728][LoggingMessageHandler][Info   ] [55e8a29e] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 49ms)
[08:49:54.743][LoggingMessageHandler][Info   ] [dd0b7c5d] <BackendAPIClient start> POST http://backend/migrate/app
[08:49:54.743][LoggingMessageHandler][Info   ] [dd0b7c5d] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 7ms)
[08:49:54.743][Updater           ][Debug  ] Starting check for updates
[08:49:54.822][LoggingMessageHandler][Info   ] [c90fe03a] <GoBackendClient start> GET http://localhost/ping
[08:50:03.260][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:50:03.573][LoggingMessageHandler][Info   ] [51da6517] <GoBackendClient start> GET http://localhost/ping
[08:50:03.573][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:50:03.885][LoggingMessageHandler][Info   ] [88649fae] <GoBackendClient start> GET http://localhost/ping
[08:50:03.885][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:50:03.885][LoggingMessageHandler][Info   ] [e1e8e189] <GoBackendClient start> GET http://localhost/ping
[08:50:03.885][GoBackendClient   ][Error  ] Error refreshing features: Docker.Core.DockerException: unable to ping backend API: The operation has timed out.
at Docker.Core.GoBackend.GoBackendClient.WaitUntilReady() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 88
at Docker.Core.GoBackend.GoBackendClient.<GetFeaturesAsync>d__8.MoveNext() in C:\workspaces\PR-15766\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 143
[08:50:03.885][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[08:50:03.885][Updater           ][Debug  ] Finished check for updates

```

### Steps to reproduce the behavior

  1. reset to factory defaults

### Points of notice
after trying to start for at least 3 times, docker starts

**Comment by jslow421** [comment]
Experiencing this myself with essentially the same setup (WIN10 pro). So far, none of the suggested workarounds have helped. Also noticing as part of this when I manually start Docker it doesn't remember my preferences for showing the Docker window on launch, and shows me the tutorial each time regardless of if I've done it already.

**Comment by Karbust** [comment]
I've also been having the same issue for a while now.

I updated today to version 3.4.0 (65384) with hopes the issue would be solved, but no such luck.

**Comment by jslow421** [comment]
> I've also been having the same issue for a while now.
> 
> I updated today to version 3.4.0 (65384) with hopes the issue would be solved, but no such luck.

Same here on the update. It actually failed to automatically launch after the update as well.

**Comment by enterprisebug** [comment]
> I've also been having the same issue for a while now.
> 
> I updated today to version 3.4.0 (65384) with hopes the issue would be solved, but no such luck.

updating to 3.4.0 (65384) fixed it for me (restartet approx. 6 times to verify)

**Comment by Karbust** [comment]
> > I've also been having the same issue for a while now.
> > I updated today to version 3.4.0 (65384) with hopes the issue would be solved, but no such luck.
> 
> updating to 3.4.0 (65384) fixed it for me (restartet approx. 6 times to verify)

Still not working for me, on both computers. And even when I start it manually, the first time it crashes, only the second time it opens correctly.
