### ISSUE TITLE
MobyLinux don't start after upgrading to Docker 17.09 

### ISSUE THREAD

**Issue by gmsantos** [docker/for-win#1148]
### Expected behavior

After upgrade to 17.09 in Docker Edge, Linux containers is working normally.

### Actual behavior

MobyLinux can't start after upgrading. Windows containers are working fine.

### Information

  - Diagnostic ID: BFEB251B-C6B3-468C-8468-CCAF50FB591B/2017-10-01_10-17-27

### Steps to reproduce the behavior

  1. Start docker after upgrading
  2. Docker for Windows get a bad response from daemon

**Comment by DarkGhostHunter** [comment]
Found a patch: Install the v17.06.2.1319402 (almost-latest stable)

https://download.docker.com/win/stable/13194/Docker%20for%20Windows%20Installer.exe

**Comment by heaths** [comment]
How is installing an older build a fix for having installed a newer build (that, in our case, actually includes bug fixes we need)?

**Comment by DarkGhostHunter** [comment]
[It's a workaround, not a fix](http://www.paraesthesia.com/archive/2010/01/29/the-difference-between-a-workaround-and-a-fix.aspx/).

**Comment by AdarWesley** [comment]
I confirm, after installing the update that popped up today, Docker Version 17.09.0-ce-win32 for windows would not start.  I did verify that the Docker for Windows service is running.  However, the tray icon never shows up and client can't communicate with the daemon.

Reverting back to v17.06.2.1319402, as suggested above by DarkGhostHunter did work for me too.

**Comment by heaths** [comment]
FWIW, I uninstalled, removed any service traces, and reinstalled 17.09 and that worked for me. Seems it hasn't worked for everyone, but might be worth a shot.

**Comment by ps68060** [comment]
I have the same issue with 17.09.0-ce-win32(13529).

I tried uninstalling and installing the previous version 17.06 but that now hangs at the same point and just says Docker is starting...

`
Version: 17.09.0-ce-win32 (13529)
Channel: stable
Sha1: a94cf27a02ecf7ecb0c050ad44145c76efc2972d
Started on: 2017/10/03 11:03:13.397
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.693.amd64fre.rs1_release.161220-1747
File: C:\Users\pslegg\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:03:13.506][GUI            ][Info   ] Starting...
[11:03:14.038][SettingsLoader ][Error  ] Unable to read settings: Could not find a part of the path 'C:\ProgramData\docker\config\daemon.json'.
[11:03:14.069][Tracking       ][Info   ] Crash report and usage statistics are enabled
[11:03:14.085][SegmentApi     ][Info   ] Usage statistic: appLaunched
[11:03:18.131][NPS            ][Info   ] NPS user ceated on :10/3/2017 1:31:42 AM -07:00, last survey : 1/1/0001 12:00:00 AM +00:00
[11:03:18.131][SegmentApi     ][Info   ] Usage statistic: heartbeat
[11:03:18.131][SegmentApi     ][Info   ] Usage statistic: Identify
[11:03:18.194][Notifications  ][Info   ] Docker is starting...
[11:03:18.225][NamedPipeClient][Info   ] Sending Version()...
[11:03:18.241][NamedPipeClient][Info   ] Received response for Version
[11:03:18.241][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[11:02:54.961][BackendServer  ][Info   ] Started
[11:03:18.241][NamedPipeServer][Info   ] Version()
[11:03:18.241][NamedPipeServer][Info   ] Version done in 00:00:00.
[11:03:18.241][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
[11:03:18.241][PowerMode      ][Info   ] Stop
[11:03:18.256][HyperV         ][Info   ] Stop
[11:03:18.256][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:03:18.256][PowerShell     ][Info   ] Creating a Runspace Pool...
[11:03:18.449][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[11:03:18.533][HyperV         ][Info   ] Script started at 11:03:18.528
[11:03:19.977][HyperV         ][Info   ] Module loaded at 11:03:19.976
[11:03:20.117][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:03:20.118][HyperV         ][Debug  ] [stop] took 00:00:01.8612837 to run
[11:03:20.118][OptimizeDisk   ][Info   ] Optimize
[11:03:20.119][PowerShell     ][Info   ] Run script...
[11:03:20.130][Moby           ][Info   ] Stop
[11:03:20.139][PowerMode      ][Info   ] Start
[11:03:20.139][HyperVGuids    ][Info   ] Installing GUIDs...
[11:03:20.140][HyperV         ][Info   ] Create
[11:03:20.140][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[11:03:20.142][HyperVGuids    ][Info   ] GUIDs installed
[11:03:20.142][Firewall       ][Info   ] Removing all existing rules...
[11:03:20.148][HyperV         ][Info   ] Script started at 11:03:20.148
[11:03:20.167][HyperV         ][Info   ] Module loaded at 11:03:20.166
[11:03:20.287][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:03:20.516][Firewall       ][Info   ] All existing rules are removed.
[11:03:20.516][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[11:03:20.521][Firewall       ][Info   ] Opening ports for SMB...
[11:03:20.528][Firewall       ][Info   ] Ports are opened
[11:03:30.417][SegmentApi     ][Info   ] Usage statistic: actionMenuSettings
[11:04:18.058][FeedbackSettings][Info   ] Open logs
[11:07:56.909][SegmentApi     ][Info   ] Usage statistic: actionMenuAbout
[11:07:56.956][SegmentApi     ][Info   ] Usage statistic: eventElectedForFeature
[11:07:56.956][SegmentApi     ][Info   ] Usage statistic: stateFeatureEnabled
[11:08:26.545][FeedbackSettings][Info   ] Open logs
`

**Comment by amendezcabrera** [comment]
Same error here, the new version won't start MobyLinux VM, I tried almost everything without success. I uploaded some reports from the "Diagnose & feedback" menu option. 
Solved downloading and installing the previous version through the link provided by @DarkGhostHunter

**Comment by ps68060** [comment]
I tried 13194 but still always the same, it does not start.

**Comment by AdarWesley** [comment]
@heaths, can you elaborate what "removed any service traces" included?

**Comment by heaths** [comment]
I had both "docker" (process name: dockerd) and "com.docker.service" service names registered. Even after uninstall, I had to remove one, though I forget which or how it even got there.
```batch
sc.exe delete docker
sc.exe delete com.docker.service
```

**Comment by dbonnell** [comment]
The old version failed to start, complaining it couldn't find some network endpoint or something (diagnostic 999F89B2-9438-42DB-93BE-1F94353964F5/2017-10-04_16-04-33).  I moved C:\ProgramData\Docker to Docker.SAVE, started Docker again and this time it came up.  I quit Docker, moved Docker.SAVE\{image,volumes,windowsfilter| to Docker\, started Docker again and at least I have my images back and Docker working again.  Lost my containers (as issue was in networking, I decided it was safer to abandon them and re-create, which is all scripted so no biggy).

**Comment by ps68060** [comment]
I have tried disabling and re-enabling Hyper-V but 17.06 will not start.

When I stop the docker service I get this error, I don't know if this helps:

Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.WPF.BackendClient.Start() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 91
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by ps68060** [comment]
A diagnostic was uploaded with id: 79F8A385-8BB2-4919-804C-C7BAC34E5C9E/2017-10-04_12-10-39

**Comment by gtardif** [comment]
Hi @gmsantos, we're having a hard time reproducing this crash ; from your logs the vpnkit.exe process dies and is causing this crash.
Could you try the following builds and let us know if things are working better with one or both of them : 
https://download-stage.docker.com/win/pr/13599/Docker%20for%20Windows%20Installer.exe
https://download-stage.docker.com/win/pr/13601/Docker%20for%20Windows%20Installer.exe
(ignore updates that might get proposed)

*Warning: This version will not auto-update properly to newer versions. It's only meant for testing. 
You must uninstall the version you have currently installed before you install this test version. 
(You might want to backup your MobyLinuxVM from Hyper-V Manager)*

**Comment by aaronsturm** [comment]
@gtardif -
Didn't work:
https://download-stage.docker.com/win/pr/13599/Docker%20for%20Windows%20Installer.exe

Did work:
https://download-stage.docker.com/win/pr/13601/Docker%20for%20Windows%20Installer.exe

Didn't try:
https://download-stage.docker.com/win/pr/13603/Docker%20for%20Windows%20Installer.exe

**Note:** I didn't see that I was supposed to uninstall first. I'm hoping this does help in some small way.

**Comment by gmsantos** [comment]
@gtardif I had tried this 3 builds.

https://download-stage.docker.com/win/pr/13603/Docker%20for%20Windows%20Installer.exe
didn't worked: BFEB251B-C6B3-468C-8468-CCAF50FB591B/2017-10-04_21-47-33

https://download-stage.docker.com/win/pr/13601/Docker%20for%20Windows%20Installer.exe
Worked!

![image](https://user-images.githubusercontent.com/1991286/31206449-48999dae-a94e-11e7-8ebc-9d61f8718445.png)

https://download-stage.docker.com/win/pr/13599/Docker%20for%20Windows%20Installer.exe
didn't worked: BFEB251B-C6B3-468C-8468-CCAF50FB591B/2017-10-04_22-00-19

**Comment by gmsantos** [comment]
@gtardif  just for curiosity, build 13605 from autoupdate worked too

![image](https://user-images.githubusercontent.com/1991286/31206808-8914fd40-a950-11e7-82ac-1516af03c97e.png)

![image](https://user-images.githubusercontent.com/1991286/31206794-7786254a-a950-11e7-8746-b086797e7470.png)

**Comment by gtardif** [comment]
Thanks @aaronsturm & @gmsantos, your feedback helps a lot. 
We're working on a candidate build to release on the stable & edge channels very soon

**Comment by ps68060** [comment]
I tried 13601 (no go) and also tried the autoupdate to 13616.

I think the original failed install has broken it so badly that I will need to eradicate all traces of Docker. 

Are there any instructions on removing everything rather then just a basic windows uninstall ?

**Comment by gtardif** [comment]
Hi @aaronsturm  & @gmsantos, we are preparing a release with this build : 
https://download.docker.com/win/stable/13620/Docker%20for%20Windows%20Installer.exe
If you have a chance to test it, can you confirm it works for you ?

**Comment by gtardif** [comment]
@ps68060 indeed updates in this case will lead to random under-development builds, so 13616 does not correspond to this fix. 
I'll try to get more info about what you can clean on your machine appart from uninstall. At the moment you best shot is uninstall 13616, maybe install/uninstall 13601 from the previous link.
Sorry for all the inconvenience.

**Comment by perskinet** [comment]
@gtardif for me your solution works! Thanks a lot.

**Comment by aaronsturm** [comment]
@gtardif I had re-installed the previous version of Docker. I uninstalled it and installed the new build https://download.docker.com/win/stable/13620/Docker%20for%20Windows%20Installer.exe and it runs like expected. I'm assuming this is another test build and can't be auto-updated? Thanks for your prompt attention to this!

**Comment by luizcarlosfaria** [comment]
@gtardif I had re-installed the previous version of Docker. I uninstalled it and installed the new build https://download.docker.com/win/stable/13620/Docker%20for%20Windows%20Installer.exe and it runs like expected. [2]

**Comment by gmsantos** [comment]
@gtardif build 13620 (
https://download.docker.com/win/stable/13620/Docker%20for%20Windows%20Installer.exe) works too.

**Comment by gtardif** [comment]
@aaronsturm No need for reboot, you're all set. This build in this case was a candidate release, so no need to re-install anything, you will get updates for the next stable versions. (in the about box it should say "channel : stable").

**Comment by gtardif** [comment]
Thanks all for your feedback ; As explained just above, you're all set and will get next updates on the stable channel with this build.

**Comment by ps68060** [comment]
Still not working here.

I stopped the service, uninstalled, ran the clean-up script mentioned above and then installed 13620.

`Version: 17.09.0-ce-win33 (13620)
Channel: stable
Sha1: 8c56a3b0e1bf39569b048201110bf1005e4b3ac9
Started on: 2017/10/06 09:27:22.740
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.693.amd64fre.rs1_release.161220-1747
File: C:\Usersmyuser\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:27:22.858][GUI            ][Info   ] Starting...
[09:27:23.748][Tracking       ][Info   ] Crash report and usage statistics are enabled
[09:27:23.748][SegmentApi     ][Info   ] Usage statistic: appLaunched
[09:27:25.076][NPS            ][Info   ] NPS User id created
[09:27:25.279][NPS            ][Info   ] NPS user ceated on :10/6/2017 1:27:24 AM -07:00, last survey : 1/1/0001 12:00:00 AM +00:00
[09:27:25.279][SegmentApi     ][Info   ] Usage statistic: heartbeat
[09:27:25.294][SegmentApi     ][Info   ] Usage statistic: Identify
[09:27:25.373][Notifications  ][Info   ] Docker is starting...
[09:27:25.404][NamedPipeClient][Info   ] Sending Version()...
[09:27:25.419][NamedPipeClient][Info   ] Received response for Version
[09:27:25.419][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[09:27:19.544][BackendServer  ][Info   ] Started
[09:27:25.419][NamedPipeServer][Info   ] Version()
[09:27:25.419][NamedPipeServer][Info   ] Version done in 00:00:00.
[09:27:25.435][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
[09:27:25.435][PowerMode      ][Info   ] Stop
[09:27:25.435][HyperV         ][Info   ] Stop
[09:27:25.451][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[09:27:25.451][PowerShell     ][Info   ] Creating a Runspace Pool...
[09:27:25.646][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[09:27:25.714][HyperV         ][Info   ] Script started at 09:27:25.704
[09:27:27.256][HyperV         ][Info   ] Module loaded at 09:27:27.256
[09:27:27.391][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[09:27:27.391][HyperV         ][Debug  ] [stop] took 00:00:01.9561958 to run
[09:27:27.392][OptimizeDisk   ][Info   ] Optimize
[09:27:27.392][PowerShell     ][Info   ] Run script...
[09:27:27.408][Moby           ][Info   ] Stop
[09:27:27.417][PowerMode      ][Info   ] Start
[09:27:27.418][HyperVGuids    ][Info   ] Installing GUIDs...
[09:27:27.418][HyperV         ][Info   ] Create
[09:27:27.419][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[09:27:27.421][HyperVGuids    ][Info   ] GUIDs installed
[09:27:27.421][Firewall       ][Info   ] Removing all existing rules...
[09:27:27.435][HyperV         ][Info   ] Script started at 09:27:27.435
[09:27:27.457][HyperV         ][Info   ] Module loaded at 09:27:27.457
[09:27:27.584][HyperV         ][Info   ] Creating Switch: DockerNAT...
[09:27:27.834][Firewall       ][Info   ] All existing rules are removed.
[09:27:27.835][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[09:27:27.840][Firewall       ][Info   ] Opening ports for SMB...
[09:27:27.848][Firewall       ][Info   ] Ports are opened
[09:27:32.867][SegmentApi     ][Info   ] Usage statistic: eventElectedForFeature
[09:27:32.867][SegmentApi     ][Info   ] Usage statistic: stateFeatureEnabled
[09:27:34.632][SegmentApi     ][Info   ] Usage statistic: actionMenuSettings
[09:27:54.378][FeedbackSettings][Info   ] Open logs
`

**Comment by WEBOWNIA** [comment]
![2017-10-06 10_55_51-](https://user-images.githubusercontent.com/6145428/31270531-0b0c0e12-aa85-11e7-965a-1d6ee5a3912d.png)

**Comment by gtardif** [comment]
@ps68060 Sorry you seem to have a different issue on your machine. From the logs Hyper-V seem to hang very early when Docker starts, does not create the Hyper-V network adapter. Anything special in your network config ?

**Comment by ps68060** [comment]
I don't think there is anything unusual for a corporate environment. It worked up until I ran the update. 

I could try disabling and re-enabling Hyper-V again.

**Comment by DarkGhostHunter** [comment]
Upgraded from Docker for Windows v13194 to the latest v13620. No problems. Everything runs smoothly.

Please close.

**Comment by ps68060** [comment]
@gtardif  Would you like me to start another issue ?

**Comment by gtardif** [comment]
@ps68060 Yes please, that would be the best I think. Thanks
