### ISSUE TITLE
Docker for windows 10 not started

### ISSUE THREAD

**Issue by WEBOWNIA** [docker/for-win#1149]
Unable to start Docker for Windows service: 2
   w Docker.Program.Run(IReadOnlyCollection`1 args) w C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Program.cs:wiersz 171

Version: 17.06.2-ce-win27 (13194)
Channel: master
Sha1: 
Started on: 2017/10/02 13:55:56.831
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.1198.amd64fre.rs1_release_sec.170427-1353
File: C:\Users\******\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[13:55:57.605][GUI            ][Info   ] Starting...
[13:55:59.480][Tracking       ][Info   ] Crash report and usage statistics are enabled
[13:55:59.483][SegmentApi     ][Info   ] Usage statistic: appLaunched
[13:56:08.251][GUI            ][Error  ] Unable to start Docker for Windows service: 2
[13:56:24.312][ErrorReportWindow][Info   ] Open logs

**Comment by WEBOWNIA** [comment]
Backend service is not installed
   w Docker.WPF.BackendClient.CheckService() w C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:wiersz 289
   w Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) w C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:wiersz 150
   w Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) w C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:wiersz 91
   w Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() w C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:wiersz 77
   w Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() w C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:wiersz 59

Version: 17.09.0-ce-win32 (13529)
Channel: stable
Sha1: a94cf27a02ecf7ecb0c050ad44145c76efc2972d
Started on: 2017/10/02 15:00:29.566
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.1198.amd64fre.rs1_release_sec.170427-1353
File: C:\Users\*****\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[15:00:29.751][GUI            ][Info   ] Starting...
[15:00:31.062][SettingsLoader ][Error  ] Unable to read settings: Nie mozna odnalezc czesci sciezki „C:\Users\*******\.docker\daemon.json”.
[15:00:31.091][Tracking       ][Info   ] Crash report and usage statistics are enabled
[15:00:31.107][SegmentApi     ][Info   ] Usage statistic: appLaunched
[15:00:33.173][NPS            ][Info   ] NPS User id created
[15:00:33.725][NPS            ][Info   ] NPS user ceated on :10/2/2017 6:00:33 AM -07:00, last survey : 1/1/0001 12:00:00 AM +00:00
[15:00:33.726][SegmentApi     ][Info   ] Usage statistic: heartbeat
[15:00:33.729][SegmentApi     ][Info   ] Usage statistic: Identify
[15:00:33.942][Notifications  ][Info   ] Docker is starting...
[15:00:34.032][NamedPipeClient][Info   ] Sending Version()...
[15:00:39.067][Notifications  ][Error  ] Backend service is not installed
[15:00:43.661][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[15:00:43.663][NamedPipeClient][Info   ] Sending Version()...
[15:00:43.665][NamedPipeClient][Info   ] Sending Version()...
[15:00:43.739][CrashReport    ][Warning] Unable to collect features settings: Nie mozna odnalezc pliku 'C:\Users\abarczewski\AppData\Roaming\Docker\features-overrides.json'.
[15:00:43.739][NamedPipeClient][Info   ] Sending Version()...
[15:00:44.074][NamedPipeClient][Info   ] Sending Version()...
[15:00:52.702][ErrorReportWindow][Info   ] Open logs
[15:01:03.188][CrashReport    ][Warning] Unable to collect guest diagnostic: Backend service is not installed
[15:01:03.188][CrashReport    ][Warning] Unable to collect vpnkit diagnostic: Backend service is not installed
[15:01:03.188][CrashReport    ][Warning] Unable to collect win containers diagnostic: Backend service is not installed
[15:01:07.980][ErrorReportWindow][Info   ] Open logs

**Comment by impankratov** [comment]
Same here, tried to uninstall, reboot install, tried to delete hyper-v MobyLinuxVM hard drive - nothing helps.

Crash report:
`CE25C17D-4273-41FC-ADE7-E1371AD9C4F3/2017-10-02_19-46-20`

**Comment by heaths** [comment]
Seeing similar problems. I noticed after upgrading from the previous table release, there's now two docker services - one of which is still the old com.docker.service. Could this be a problem? I unregistered com.docker.service:

sc.exe delete com.docker.service

And re-registered dockerd.exe as a service:

dockerd.exe --unregister-service
dockerd.exe --register-service

Docker then starts; however, even after switching back to Windows containers I can no longer edit the daemon.json through the Settings control panel like I could before. Instead, I have to stop docker, run takeown.exe to take ownership of daemon.json (over-protected, if you ask me; not even key.json is that protected), re-ACL the file, then change the file manually before restarting the docker service.

**Comment by willsilvano** [comment]
Same here. Windows 10 Pro 64 bits don't start Docker.

**Comment by jukitor** [comment]
Same problem. And no way to downgrade...

**Comment by heaths** [comment]
I uninstalled and reinstalled and that seemed to help. Make sure services are all removed between steps. I also had to re-set up my daemon.json after reinstalling and switching back to Windows containers.

**Comment by impankratov** [comment]
>Same problem. And no way to downgrade...

@jukitor You can install previous stable version via chocolatey:
https://chocolatey.org/packages/docker-for-windows/17.06.2.1319402

@heaths Tried uninstalling, but with no luck. But I haven't checked the services, maybe 
>the old com.docker.service

is really the source of a problem.

**Comment by DarkGhostHunter** [comment]
Patch: https://github.com/docker/for-win/issues/1148#issuecomment-333677117

**Comment by jukitor** [comment]
Thanks @DarkGhostHunter (and @impankratov )

**Comment by JayGlass** [comment]
@DarkGhostHunter - thanks that worked for me as well

**Comment by JayGlass** [comment]
**Though gee, now I get:**
Object reference not set to an instance of an object.
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 247
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

**Comment by heaths** [comment]
/lifecycle frozen

If Docker, Inc. would open source this, as a long-time setup developer is be happy to solve this problem.

**Comment by kuntergunt** [comment]
I have installed Docker now at least a dozen times in the last year and it never managed to start without this error. Docker simply does not work for me.

**Comment by MehulKChaudhari** [comment]
Hey, are you still facing the issue?

**Comment by heaths** [comment]
At some point in the last year or two is started working, i.e. the service and systray application would restart so this can be closed.

/remove-lifecycle frozen
