### ISSUE TITLE
Docker update fails in 3.3.3 "Access is denied"

### ISSUE THREAD

**Issue by ThePlenkov** [docker/for-win#11496]
### Actual behavior

Docker Desktop for Windows suggests to install a new version. When I press Update and Restart from the tray icon context menu two things happen:

1. it asks me to prompt windows credentials with admin access
2.  Installation windows appears for less than a second. No actual installation happens
 
### Expected behavior
 It should update itself. This is unbelievable that such a basic feature of quite amazing product cannot be fixed for years. 

### Information
Please see the log:
```
Version: 3.3.3 (64133)
Sha1: 68eba96de8051dcb12cf43b3a6955f1ee7156b4b
Started on: 2021/06/21 09:04:54.278
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 2009
Build: 19043
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\pplenkov\AppData\Local\Docker\install-log.txt
CommandLine: "C:\Program Files\Docker\Docker\InstallerCli.exe" -k -p
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:04:54.378][Installer         ][Info   ] Killing processes...
[09:04:54.394][Installer         ][Info   ] Killing existing Docker Desktop process with PID 13768
[09:04:54.410][Installer         ][Info   ] Killing existing Docker Desktop process with PID 3360
[09:04:54.432][Installer         ][Info   ] Killing existing Docker Desktop process with PID 15884
[09:04:54.462][Installer         ][Info   ] Process Docker Desktop with PID 15832 has exited already
[09:04:54.462][Installer         ][Info   ] Killing existing Docker Desktop process with PID 7460
[09:04:54.478][Installer         ][Info   ] Process Docker Desktop with PID 7204 has exited already
[09:04:54.504][Installer         ][Error  ] Access is denied
[09:04:54.620][UninstallWorkflow] Action CommunityInstaller.ExecAction failed
Exception type: System.InvalidOperationException, Exception message: Process InstallerCli.exe exited with code 1, StackTrace:
   at CommunityInstaller.ExecAction.<DoAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__14.MoveNext()
[09:04:54.620][InstallWorkflow] Installation failed
Exception type: System.InvalidOperationException, Exception message: Process InstallerCli.exe exited with code 1, StackTrace:
   at CommunityInstaller.ExecAction.<DoAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<UninstallAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[09:04:54.620][InstallWorkflow] Rollbacking component CommunityInstaller.ExtractManifestStep
[09:04:54.636][InstallWorkflow] Rollbacking component CommunityInstaller.DownloadStep

```

**Comment by trungutt** [comment]
@ThePlenkov thanks for the report. Do you have the same issue by installing directly the latest release? (https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-340)

**Comment by ThePlenkov** [comment]
@trungutt well. It depends what we call normal behavior. If I just try to download and install i have this:

![image](https://user-images.githubusercontent.com/6381507/123601746-500fb500-d7f8-11eb-9a0b-f2573f121218.png)

```
Process InstallerCli.exe exited with code 1
   at CommunityInstaller.ExecAction.<DoAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<UninstallAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

The solution thought is quite straightforward
```
net stop com.docker.service
The Docker Desktop Service service is stopping.
The Docker Desktop Service service was stopped successfully.
```

I have reported this issue already:
https://github.com/docker/for-win/issues/10774

But it stays not fixed from version to version. 

I hope it helps.

Thanks!

**Comment by ThePlenkov** [comment]
@trungutt 3.6.0 problem is still there
![image](https://user-images.githubusercontent.com/6381507/129159694-bc60ec3f-e43c-46d2-a343-47c222cd1d8f.png)
