### ISSUE TITLE
Docker Desktop failed launch

### ISSUE THREAD

**Issue by zimmerkm** [docker/for-win#11523]
- [x ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 5B0A0CAE-7160-4E5A-9EFE-EE586D61F30C/20210624233438

### Actual behavior
When I attempt to launch:
System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: Unsupported console settings. In order to use this feature, the legacy console must be disabled.

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

### Information

  - Windows Version: Win10 Pro 10.0.19043 N/A Build 19043
  - Docker Desktop Version: 3.5.0
  - WSL2 or Hyper-V backend? WSL2 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...Launch app
  2. ...

**Comment by zimmerkm** [comment]
I also:
1. uninstalled docker desktop
2. deselected [hyper-v & windows subsystem for linux] from windows features.
3. restart & then installed the latest version of docker desktop
4. checked windows subsystem for Linux from windows features.
5. restarted & tried to start the docker, still, the same issue appeared.

**Comment by tebeco** [comment]
is that normal that the `docker-desktop` is gone ?

![image](https://user-images.githubusercontent.com/2266487/123377406-54379a80-d58c-11eb-9749-5b9244249267.png)

**Comment by tebeco** [comment]
Ok so I managed to fix it but i'm not sure exactly why so here is a list of the thing i did:

while the error is showing you have access to the Underlying UI ==> DO NOT CLICK QUIT

* On the error click `Reset to factory` (nop)
* `wsl -l -v` ==> missing the `docker-desktop` that runs `dockerd` so this was a lead
* on docker UI => uncheck `wsl2 backend` => apply and restart
(that will still fail but do it anyway)
* on the UI => if you had K8s => disable it until you fix the issue
* in the UI => Troubleshout button (the `bug` icon top bar) => RESET

So at that point I decided to WIPE wsl2 docker
* in a shell `wsl --unregister docker-desktop` <== will tell you it does not exists
* in a shell `wsl --unregister docker-desktop-data` <== should take time

NOTE: during startup Docker call `wsl` which managed to deadlock `wsl -l -v` so don't be surprised if you try to snoop on it but nothing happened

Restarting docker at this point ... for a reason I don't understand docker was still trying to use `wsl2 backend` and thus ... CRASH
so ... AGAIN
* on docker UI => uncheck `wsl2 backend` => apply and restart
* restart ... => IT WILL HANG / no error
* open an admin shell `Get-Process *docker*`
* `Stop-Process <PID>` <== some will ask validation .. YES
it will hard close/crash docker ... don't care
* restart docker ...
* it will tell you the services are not running ... YES START
* ... it's working again

I even did the tutorial to see that was working

![image](https://user-images.githubusercontent.com/2266487/123388370-01181480-d599-11eb-8ab0-7fbae78916f2.png)

and WSL2 is defaulted
![image](https://user-images.githubusercontent.com/2266487/123388419-112ff400-d599-11eb-88b6-2a3563f9db1d.png)


_Good luck, Exiles_

**Comment by stephen-turner** [comment]
@zimmerkm WSL 2 can't run if you have legacy console enabled. This is wholly a Windows thing, nothing to do with us, except that we use WSL 2 as a prerequisite. You need to turn off legacy console mode from the settings of any console window, then you should be OK.

**Comment by stephen-turner** [comment]
@tebeco Your issue is different, but it looks like you've solved it anyway.

**Comment by tebeco** [comment]
> @tebeco Your issue is different, but it looks like you've solved it anyway.

@stephen-turner different ?
That's look like the same stack trace, what did I missed ?

**Comment by stephen-turner** [comment]
@tebeco No worries.

**Comment by zimmerkm** [comment]
stephen-turner, thank you for your help.  What this boiled down to is simply that I had the legacy console enabled.  I'm able to launch without issue now.
