### ISSUE TITLE
Docker doesn't start

### ISSUE THREAD

**Issue by TamByrd** [docker/for-win#1152]
### Expected behavior
Docker starts 

### Actual behavior
12:57:48.968][NamedPipeServer][Error  ] Unable to execute Start: Docker hv-sock proxy (vsudd) is not reachable    at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 266
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 250
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[12:57:48.974][NamedPipeClient][Error  ] Unable to send Start: Docker hv-sock proxy (vsudd) is not reachable
[12:57:48.976][Notifications  ][Error  ] Docker hv-sock proxy (vsudd) is not reachable

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
82050DEF-F5EF-4E93-AB65-EC9542A4C7C2/2017-10-02_13-12-06

### Steps to reproduce the behavior
 Try to start docker

**Comment by DarkGhostHunter** [comment]
Same here. Cannot go back to earlier version. Dev machine unusable. Boss very pissed off.

**Comment by DarkGhostHunter** [comment]
Workaround: https://github.com/docker/for-win/issues/1148#issuecomment-333677117

**Comment by hellowin** [comment]
Thanks @DarkGhostHunter you saved my day
