### ISSUE TITLE
Version 3.5.1 will not start after upgrade or clean installation

### ISSUE THREAD

**Issue by mwm-twx** [docker/for-win#11557]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
* Docker does not start

```
[13:59:38.646][SystrayNotifications][Error  ] System.Threading.Tasks.TaskCanceledException: Cancellation token triggered before we finished reading from the stream.
   at HttpOverStream.ByLineReader.<ReadLineAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.Client.DialMessageHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.IPC.Client.<SendAsync>d__4.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.Core\IPC\Client.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.LifecycleClient.<DockerStartAsync>d__4.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.ApiServices\LifecycleClient.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.LinuxkitDaemonStartup.<StartAsync>d__5.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.Desktop\LinuxkitDaemonStartup.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<RestartAsync>d__26.MoveNext() in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 266
```

Root cause seems to be this:

```
[14:36:30.055][ApiProxy          ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.proxy.exe -windowsPipe=\\.\pipe\docker_engine_windows -wsl-distro docker-desktop  -dockerExe "C:\Program Files\Docker\Docker\resources\bin\docker.exe" -exposeTcp=127.0.0.1:2375,[::1]:2375 -inject-hosts=true
[14:36:30.060][ApiProxy          ][Info   ] Started
[14:36:30.135][ApiProxy          ][Info   ] msg="ipc.NewClient: e8fb0e9f-ProxyCMD -> \\\\.\\pipe\\dockerBackendApiServer [[STACK]]github.com/docker/pinata/common/pkg/backend.NewClientWithPath(...)\n\tC:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/backend/client.go:45\ngithub.com/docker/pinata/common/pkg/backend.NewClient(...)\n\tC:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/backend/client.go:51\nmain.main()\n\tC:/workspaces/master-merge/src/github.com/docker/pinata/win/backend/cmd/com.docker.proxy/main.go:57 +0x44b\n"
[14:36:32.140][ApiProxy          ][Fatal  ] msg="ensuring desktop context: querying desktop-linux docker context: open C:\\Users\\USERNAME\\.docker\\contexts\\meta\\fe9c6bd7a66301f49ca9b6a70b217107cd1284598bfc254700c989b916da791e\\meta.json: The file cannot be accessed by the system."
[14:36:32.152][ApiProxy          ][Error  ] Process died
[14:36:33.297][VpnKitBridge      ][Info   ] msg="guest: still waiting for docker-proxy after 1m0.0006852s"
```

If I watch the `.docker` directory while docker is staring, a `contexts/meta` directory hierarchy appears, but at some point during startup it is removed and leaves an empty _file_ `contexts`.  I've tried deleting that empty file, and the entire `.docker` directory, but it doesn't change the behavior.

### Expected behavior
* Docker starts

### Information

  - Windows Version: Windows 10 update 2004
  - Docker Desktop Version: 3.5.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
  1. Update from prior version to 3.5.1 or fresh install 3.5.1

**Comment by wszczepaniak** [comment]
Same for me. Windows 10 21H1 19043.1052

**Comment by KOGI** [comment]
Same here

**Comment by fahadDA** [comment]
Facing same issue. Legacy versions of docker installs and runs fine until the upgrade to v3.5.1, but v3.5.1 does not start. It always give the error "Docker failed to initialize . the operation has timed out"

**Comment by djs55** [comment]
@mwm-twx I think your analysis of the root cause is 100% correct. I've created a developer build which should allow the app to startup here: https://github.com/docker/for-win/issues/11601#issuecomment-877171395 Let me know if that helps or not.

Thanks for the observation about the `.docker` directory. Since both `.docker/contexts` and `.docker/contexts/meta` are supposed to be directories (as you highlight) perhaps a work-around would be to create these directories before starting the app. Perhaps there's a problem in the docker CLI code where it will do the equivalent of `cp foo .docker/contexts/meta` without first running `mkdir .docker/contexts/meta`.

**Comment by mwm-twx** [comment]
@djs55 I had also tried creating the directory beforehand, but just like the case with deleting the directory and letting docker create it, it ends up as a file and startup fails.

**Comment by jeritiana** [comment]
@djs55 I did some analysis and found out that `.docker/contexts` is not an empty file but a symlink to itself... see #11668
