### ISSUE TITLE
Initial launch of Docker fails - on startup or after update

### ISSUE THREAD

**Issue by jslow421** [docker/for-win#11572]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8B1F0678-C46A-4014-9DC4-CCC24BEC795F/20210701055555

### Actual behavior
On first launch, be it on system boot, or launch after an update, docker desktop crashes and must be manually re-launched.

### Expected behavior
Launch as normal

### Information
  - Occurs 100% of the time
  - Began happening after 3.3.3 update
  - After initial launch fails, second launch always succeeds.
  - WSL2
  - Have reinstalled docker, and WSL

  - Windows Version: 10 - 21H1 Build 19043.1081
  - Docker Desktop Version: 3.5.1
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Boot system or update docker

Additional event viewer logs possibly related:

.net runtime
```
Application: Docker Desktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.UnauthorizedAccessException

Exception Info: Docker.Core.HttpBadResponseException
   at Docker.Core.Logging.HttpClientExceptionInterceptor+<InterceptResponseAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.IPC.Client+<SendAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__58.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.BackendAPI.BackendAPIClient+<UpdateHostsAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.TaskExtension+<Forget>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Application error

```
Faulting application name: Docker Desktop.exe, version: 3.5.1.0, time stamp: 0x8c3f2661
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1081, time stamp: 0xde3fc775
Exception code: 0xe0434352
Fault offset: 0x0000000000034ed9
Faulting process id: 0x5f2c
Faulting application start time: 0x01d76e3ce568ab92
Faulting application path: C:\Program Files\Docker\Docker\Docker Desktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 25f84150-b79c-490e-b0c8-3d78744a9c1d
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by GuyPaddock** [comment]
I see this too. I often have to completely stop Docker, shutdown WSL, and restart the LxssManager process, before starting Docker again.
