### ISSUE TITLE
Frequent crashing of com.docker.backend.exe

### ISSUE THREAD

**Issue by lump** [docker/for-win#11589]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DD6D828D-0917-4899-92B2-4B7154FAB00F/20210703001044

### Actual behavior
The helper program, `com.docker.backend.exe` crashes repeatedly.  When it crashes, incoming connections to my containers stop working.  If I redeploy the container that opens the ports, it works for a few minutes, but then it crashes again and forgets the connections it is supposed to be relaying.

### Expected behavior
No crashing, always relay connections into containers.

### Information
I am running Docker Desktop with Swarm on WSL2.  The container is running HAProxy with a network in host mode, opening ports 80 and 443.  The com.docker.backend.exe only runs for a few minutes but then crashes and then the GoBackendProcess logs "Auto restarting process" and starts a new one, which has no knowledge of the ports it should be relaying.

- Is it reproducible?

I have seen this behavior on two different Windows 10 machines.  The first Windows machine I used was working fine several months ago.  The second Windows machine was a fresh install of windows, with all fresh installs of WSL2 and Docker Desktop.  I encountered this after coworkers came to me asking if I could help them because they couldn't get it to work.  They are experiencing the same thing.

- Is the problem new?

I don't know how new this problem is.  I haven't used Docker Desktop on Windows for several months.  I started using it again to try to help coworkers who use Windows 10 to get our docker stuff working on their platform, but they were encountering this issue.

- Did the problem appear with an update?

Probably, I can't confirm which update.

- A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.

I simply run `docker stack deploy` on a docker-compose file that starts a vanilla official HAProxy instance.  But it doesn't matter what it is.  The same thing happens to a MariaDB container that opens 3306.

```
---
version: '3.8'

networks:
  swarm:
    external: true

services:
  proxy:
    image: haproxy:2.3-alpine
    hostname: "{{.Service.Name}}.{{.Node.Hostname}}"
    networks:
    - swarm
    ports:
    - target: 80
      published: 80
      mode: host
      protocol: tcp
    - target: 443
      published: 443
      mode: host
      protocol: tcp
    configs:
    - source: haproxy.cfg
      target: "/usr/local/etc/haproxy/haproxy.cfg"
    deploy:
      mode: global
      placement:
        max_replicas_per_node: 1
        constraints:
        - node.role == manager
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
```

The error I see in the Docker logs when it crashes is this:
```
[17:31:49.945][GoBackendProcess  ][Info   ] panic: runtime error: slice bounds out of range [:46870] with capacity 512
[17:31:49.945][GoBackendProcess  ][Info   ] goroutine 75 [running]:
[17:31:49.945][GoBackendProcess  ][Info   ] github.com/docker/pinata/common/pkg/udp.(*datagram).unmarshal(0xc000535130, 0x1f9fe9f6e80, 0xc0006e0020, 0x1f9fe9f6e80, 0xc0006e0020, 0x3cd1405779)
[17:31:49.945][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/udp/encapsulation.go:160 +0x5a8
[17:31:49.945][GoBackendProcess  ][Info   ] github.com/docker/pinata/common/pkg/udp.(*encapsulator).ReadFromUDP(0xc0005d73c0, 0xc000bd4800, 0x200, 0x200, 0x0, 0x0, 0x0, 0x0)
[17:31:49.945][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/udp/encapsulation.go:33 +0x13d
[17:31:49.945][GoBackendProcess  ][Info   ] github.com/docker/pinata/common/pkg/udp.(*encapsulator).ReadFrom(0xc0005d73c0, 0xc000bd4800, 0x200, 0x200, 0x0, 0x0, 0x34cfb00, 0x2877b20, 0x3516ec0)
[17:31:49.945][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/udp/encapsulation.go:51 +0x54
[17:31:49.945][GoBackendProcess  ][Info   ] github.com/miekg/dns.(*Server).readPacketConn(0xc0000ff320, 0x28c00d8, 0xc0005d73c0, 0x77359400, 0x0, 0xc000303df8, 0xdac471, 0x243c1a0, 0x241e240, 0x2877b01, ...)
[17:31:49.945][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:704 +0xe2
[17:31:49.945][GoBackendProcess  ][Info   ] github.com/miekg/dns.defaultReader.ReadPacketConn(0xc0000ff320, 0x28c00d8, 0xc0005d73c0, 0x77359400, 0x3516ec0, 0x1, 0x0, 0x0, 0x0, 0x2877b20, ...)
[17:31:49.945][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:178 +0x57
[17:31:49.945][GoBackendProcess  ][Info   ] github.com/miekg/dns.(*Server).serveUDP(0xc0000ff320, 0x28c00d8, 0xc0005d73c0, 0x0, 0x0)
[17:31:49.945][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:502 +0x546
[17:31:49.945][GoBackendProcess  ][Info   ] github.com/miekg/dns.(*Server).ActivateAndServe(0xc0000ff320, 0x0, 0x0)
[17:31:49.945][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:357 +0x109
[17:31:49.945][GoBackendProcess  ][Info   ] github.com/docker/pinata/common/pkg/dns.(*Server).handleOneUDPConn(0xc0007ac1c0, 0x28c18f0, 0xc0006e0020)
[17:31:49.945][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/dns/server.go:131 +0x105
[17:31:49.945][GoBackendProcess  ][Info   ] created by github.com/docker/pinata/common/pkg/dns.(*Server).serveUDP
[17:31:49.945][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/dns/server.go:123 +0x56
[17:31:49.955][GoBackendProcess  ][Error  ] Process died
```

Then I see this ad nauseam (more than 10,000 lines, repeating every few milliseconds):
```
[17:31:49.947][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
```

Interspersed in the last few hundred lines, are these:
```
[17:31:54.960][GoBackendProcess  ][Error  ] Auto restarting process
[17:31:54.960][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer -native-api
[17:31:54.961][GoBackendProcess  ][Info   ] Started
[17:31:55.014][GoBackendProcess  ][Info   ] msg="starting backend server"
```

The new process doesn't know anything about the services it should be providing for the currently running containers.  So incoming connections are refused.

- Windows Version: 10 Pro 21H1 19043.1052
- Docker Desktop Version: 3.5.1 (66090)
- WSL2 or Hyper-V backend?  WSL2
- Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

Run any service that needs to open a port to the outside world.  It works for a few minutes and then dies.

**Comment by piotr-filipek-swi** [comment]
Hi,
I'm facing the same issue.

### System Information
* Windows 10 Enterprise, 21H1 19043.1052
* Docker Desktop 3.5.1 (66090)
* WSL2

### Information
I'm running Docker Desktop with Kubernetes. After upgrade to 3.5.1 (most likely from 3.3.3 but I'm not exactly sure) I started to loose connection to my local k8s api server. I turns out that the `com.docker.backend.exe` process randomly crashes which kills all the network communication with the containers. 

`~\AppData\Local\Docker\log.txt` contains the following error:
```
[13:25:05.226][GoBackendProcess  ][Info   ] panic: runtime error: slice bounds out of range [:55925] with capacity 512
[13:25:05.226][GoBackendProcess  ][Info   ] goroutine 179 [running]:
[13:25:05.226][GoBackendProcess  ][Info   ] github.com/docker/pinata/common/pkg/udp.(*datagram).unmarshal(0xc000079c70, 0x24d6f771900, 0xc000724100, 0x24d6f771900, 0xc000724100, 0x823a33d649)
[13:25:05.226][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/udp/encapsulation.go:160 +0x5a8
[13:25:05.226][GoBackendProcess  ][Info   ] github.com/docker/pinata/common/pkg/udp.(*encapsulator).ReadFromUDP(0xc00050e020, 0xc000637000, 0x200, 0x200, 0x0, 0x0, 0x0, 0x0)
[13:25:05.226][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/udp/encapsulation.go:33 +0x13d
[13:25:05.226][GoBackendProcess  ][Info   ] github.com/docker/pinata/common/pkg/udp.(*encapsulator).ReadFrom(0xc00050e020, 0xc000637000, 0x200, 0x200, 0x0, 0x0, 0x2a4fb00, 0x1df7b20, 0x2a96ec0)
[13:25:05.226][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/udp/encapsulation.go:51 +0x54
[13:25:05.226][GoBackendProcess  ][Info   ] github.com/miekg/dns.(*Server).readPacketConn(0xc0002dc240, 0x1e400d8, 0xc00050e020, 0x77359400, 0x0, 0xc000707df8, 0x32c471, 0x19bc1a0, 0x199e240, 0x1df7b01, ...)
[13:25:05.226][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:704 +0xe2
[13:25:05.226][GoBackendProcess  ][Info   ] github.com/miekg/dns.defaultReader.ReadPacketConn(0xc0002dc240, 0x1e400d8, 0xc00050e020, 0x77359400, 0x2a96ec0, 0x1, 0x0, 0x0, 0x0, 0x1df7b20, ...)
[13:25:05.226][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:178 +0x57
[13:25:05.226][GoBackendProcess  ][Info   ] github.com/miekg/dns.(*Server).serveUDP(0xc0002dc240, 0x1e400d8, 0xc00050e020, 0x0, 0x0)
[13:25:05.227][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:502 +0x546
[13:25:05.227][GoBackendProcess  ][Info   ] github.com/miekg/dns.(*Server).ActivateAndServe(0xc0002dc240, 0x0, 0x0)
[13:25:05.227][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:357 +0x109
[13:25:05.227][GoBackendProcess  ][Info   ] github.com/docker/pinata/common/pkg/dns.(*Server).handleOneUDPConn(0xc0000483c0, 0x1e418f0, 0xc000724100)
[13:25:05.227][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/dns/server.go:131 +0x105
[13:25:05.227][GoBackendProcess  ][Info   ] created by github.com/docker/pinata/common/pkg/dns.(*Server).serveUDP
[13:25:05.227][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/dns/server.go:123 +0x56
[13:25:05.231][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[13:25:05.232][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[13:25:05.233][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[13:25:05.234][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[13:25:05.235][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[13:25:05.236][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[13:25:05.237][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[13:25:05.239][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[13:25:05.240][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[13:25:05.241][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[13:25:05.242][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[13:25:05.243][GoBackendProcess  ][Error  ] Process died
```

**Comment by tg-hunter** [comment]
I am experiencing the same issue after upgrading to the latest Docker Desktop version 3.5.1 (66090) on Windows 10 Pro, 21h1 (19043.1083). I did not have this issue before upgrading.

`~\AppData\Local\Docker\log.txt` snippet:

```
[10:50:58.385][GoBackendProcess  ][Info   ] panic: runtime error: slice bounds out of range [:56727] with capacity 512
[10:50:58.385][GoBackendProcess  ][Info   ] goroutine 80 [running]:
[10:50:58.385][GoBackendProcess  ][Info   ] github.com/docker/pinata/common/pkg/udp.(*datagram).unmarshal(0xc00036adc0, 0x175284546e0, 0xc00066e480, 0x175284546e0, 0xc00066e480, 0xb4161553a5)
[10:50:58.385][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/udp/encapsulation.go:160 +0x5a8
[10:50:58.385][GoBackendProcess  ][Info   ] github.com/docker/pinata/common/pkg/udp.(*encapsulator).ReadFromUDP(0xc00066e4a0, 0xc000d4e400, 0x200, 0x200, 0x0, 0x0, 0x0, 0x0)
[10:50:58.385][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/udp/encapsulation.go:33 +0x13d
[10:50:58.385][GoBackendProcess  ][Info   ] github.com/docker/pinata/common/pkg/udp.(*encapsulator).ReadFrom(0xc00066e4a0, 0xc000d4e400, 0x200, 0x200, 0x0, 0x0, 0x36cfb00, 0x2a77b20, 0x3716ec0)
[10:50:58.385][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/udp/encapsulation.go:51 +0x54
[10:50:58.385][GoBackendProcess  ][Info   ] github.com/miekg/dns.(*Server).readPacketConn(0xc0001a4900, 0x2ac00d8, 0xc00066e4a0, 0x77359400, 0x0, 0xc000937df8, 0xfac471, 0x263c1a0, 0x261e240, 0x2a77b01, ...)
[10:50:58.385][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:704 +0xe2
[10:50:58.385][GoBackendProcess  ][Info   ] github.com/miekg/dns.defaultReader.ReadPacketConn(0xc0001a4900, 0x2ac00d8, 0xc00066e4a0, 0x77359400, 0x3716ec0, 0x1, 0x0, 0x0, 0x0, 0x2a77b20, ...)
[10:50:58.385][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:178 +0x57
[10:50:58.385][GoBackendProcess  ][Info   ] github.com/miekg/dns.(*Server).serveUDP(0xc0001a4900, 0x2ac00d8, 0xc00066e4a0, 0x0, 0x0)
[10:50:58.385][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:502 +0x546
[10:50:58.385][GoBackendProcess  ][Info   ] github.com/miekg/dns.(*Server).ActivateAndServe(0xc0001a4900, 0x0, 0x0)
[10:50:58.385][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/vendor/github.com/miekg/dns/server.go:357 +0x109
[10:50:58.385][GoBackendProcess  ][Info   ] github.com/docker/pinata/common/pkg/dns.(*Server).handleOneUDPConn(0xc000706400, 0x2ac18f0, 0xc00066e480)
[10:50:58.385][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/dns/server.go:131 +0x105
[10:50:58.385][GoBackendProcess  ][Info   ] created by github.com/docker/pinata/common/pkg/dns.(*Server).serveUDP
[10:50:58.385][GoBackendProcess  ][Info   ] 	C:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/dns/server.go:123 +0x56
[10:50:58.389][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.390][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.391][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.392][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.392][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.393][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.394][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.394][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.395][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.395][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.396][GoBackendProcess  ][Error  ] Process died
[10:50:58.396][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.397][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.398][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.398][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.399][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.400][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.400][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.401][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.401][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
[10:50:58.402][VpnKitBridge      ][Info   ] msg="windows: vpnkit-data: cannot dial open \\\\.\\pipe\\dockerVpnkitData: The system cannot find the file specified."
```
Many more `[VpnKitBridge      ][Info   ]` messages in the logs after the backend process dies.

**Comment by lump** [comment]
Automatically closing tickets is a little bit delusional, isn't it?  If you ignore your problems long enough, they might just go away, right?
