### ISSUE TITLE
Version: 17.09.0-ce cannot run any docker command throws connection error

### ISSUE THREAD

**Issue by udayansarma** [docker/for-win#1163]
### Expected behavior
Run docker  version 
### Actual behavior
get partial results and then get "error during connect: Get http://127.0.0.1:2377/v1.32/version: dial tcp 127.0.0.1:2377: connectex: No connection could be made because the target machine actively refused it."
![snip_20171003174850](https://user-images.githubusercontent.com/2105806/31155471-617fce56-a863-11e7-848b-16074842ab12.png)

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by GrahamGIGA** [comment]
Docker upgrade crashed after 'Upgrade Available' message.  

Previous release appears to have been uninstalled.  Tried installing download from store.

Got:

Access to the path 'C:\Program Files\Docker\Docker\resources\bin\docker-compose.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at LightweightInstaller.UnpackArtifactsStep.<DoAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__18.MoveNext()

**Comment by jasonbivins** [comment]
@udayansarma @GrahamGIGA 
Can you please try the latest stable version and let me know if you still see the same errors?

**Comment by GrahamGIGA** [comment]
Installed the full 17-09 and it is working fine.

Thanks

**Comment by udayansarma** [comment]
It still does not work for me. I installed  17.09.0-ce and still getting the error. Worst docker is crashing now.
![snip_20171010125407](https://user-images.githubusercontent.com/2105806/31407597-45a73636-adba-11e7-9e33-0d910de462bb.png)
![snip_20171010125427](https://user-images.githubusercontent.com/2105806/31407598-45c0bc28-adba-11e7-8cbc-28cdd8c711c3.png)

Thanks
Udy
