### ISSUE TITLE
Docker keeps crashing on startup

### ISSUE THREAD

**Issue by parasparmar** [docker/for-win#11637]
- [] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information
 20FF57CD-A3E4-4183-810A-4C3BDA149FAA/20210710142537
  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...
System.TimeoutException:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
   at Docker.ApiServices.LifecycleClient.<WaitForServerUpAsync>d__2.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\LifecycleClient.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 178
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

**Comment by JMS-1** [comment]
For us this happens after the installtion of KB5004945 and KB5003742 and the following reboot. The issue is really critical since running in a production environment.

**Comment by parasparmar** [comment]
Out of these I only have the KB5004945 update. However since it is a security update, for a CVE known as 'Print Nightmare' it can't be removed.
![image](https://user-images.githubusercontent.com/2953468/125205484-17fc7d80-e2a0-11eb-9c52-043bb82a3950.png)

**Comment by JMS-1** [comment]
Well ... I installed 3.3.3 on an update-to-date test system and eveything works fine. The only difference I can see is that the test system is running 21H1 instead of 20H2 and that the Docker Desktop hast been installed AFTER both Microsoft Fixes. 

Actually I hoped the problem would occur on the test system as well but no such "luck".

Perhaps you should enter your version stuff as well, may help the pros to reproduce.

Regards

Jochen

**Comment by parasparmar** [comment]
There have been 2 to 3 releases post the issue. The issue has now been resolved due to these upgrades. I can confirm that the issuse is no longer observed. Hence requesting for closure.
