### ISSUE TITLE
System.InvalidOperationException: job failed with message: 'DockerDesktopVM' failed to start. (Virtual machine ID C3A928D1-2C07-4491-840F-4317090678C9)  'DockerDesktopVM' failed to start worker process: The specified module could not be found. (0x8007007E). (Virtual machine ID C3A928D1-2C07-4491-840F-4317090678C9)

### ISSUE THREAD

**Issue by agrawal-anshul** [docker/for-win#11649]
Logs:
[log.txt](https://github.com/docker/for-win/files/6802461/log.txt)
===================================================
![Capture](https://user-images.githubusercontent.com/51377801/125312602-0e335280-e352-11eb-96c5-7ca74b4fe47c.PNG)

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: job failed with message: 'DockerDesktopVM' failed to start. (Virtual machine ID C3A928D1-2C07-4491-840F-4317090678C9)

'DockerDesktopVM' failed to start worker process: The specified module could not be found. (0x8007007E). (Virtual machine ID C3A928D1-2C07-4491-840F-4317090678C9)

'DockerDesktopVM' could not initialize. (Virtual machine ID C3A928D1-2C07-4491-840F-4317090678C9)

'DockerDesktopVM' Microsoft Input Management Device (Instance ID DE6CDC86-E1FB-4940-801B-C3C1A26C4DA4): Failed to create instance with error 'The specified module could not be found.' (0x8007007E). (Virtual machine ID C3A928D1-2C07-4491-840F-4317090678C9)
   at Docker.Backend.HyperVInfrastructure.HandleUpdatedJob(CIMConcreteJob updatedJob) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:line 770
   at Docker.Backend.HyperVInfrastructure.<HandleMaybeAsyncJob>d__39.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:line 704
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Backend.HyperVInfrastructure.<StartVMAsync>d__31.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:line 552
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HyperV.<StartAsync>d__6.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperV.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HttpAPI.HyperVController.<StartAsync>d__7.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\HyperVController.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

[log.txt](https://github.com/docker/for-win/files/6802403/log.txt)

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:Version 20H2(OS Build  19042.1083)
  - Docker Desktop Version: Docker Engine v20.10.7
  - WSL2 or Hyper-V backend? : Tried using both 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

**Comment by agrawal-anshul** [comment]
Diagonistic ID: 65C33E6B-B2C9-4CF6-A0EB-9CA502E01AD2/20210713140254
