### ISSUE TITLE
Docker engine is starting stuck 

### ISSUE THREAD

**Issue by bhende27** [docker/for-win#11661]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stakx** [comment]
I updated to Docker Desktop version 3.5.2 (66501) two days ago, and since then, Docker takes a very long time to start (up to 10 minutes). At first I thought it was stuck, but turns out it just takes a very, very long time.

### Expected behavior

When Docker starts, it usually takes about 30-60 seconds on my machine.

### Actual behavior

After the latest update, Docker takes up to 10 minutes to start.

### Information

* Windows Version: **Windows 10 Pro (10.0.19042 Build 19042)**
* Docker Desktop Version: **3.5.2 (66501)**
* WSL2 or Hyper-V backend? **Hyper-V**
* Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **no**

### Steps to reproduce the behavior

1. Boot your machine, or restart Docker

**Comment by fabiougolini** [comment]
Since I have upgraded to 3.5.2 I am not able to start Docker Desktop anymore. I couldn't even purge the data. So I had to uninstall it, losing my images, containers, etc.
Installed 3.3 and it was working fine, upgraded to 3.5.2, same issue...

**Comment by jbagnicki** [comment]
Downgrade to 3.3.3 also works for me. Back to 3.5.1 wasn't enough.

**Comment by stakx** [comment]
Downgrading worked for me, too. (Old releases can be downloaded on the [release notes](https://docs.docker.com/docker-for-windows/release-notes/) page btw.)

**Comment by PaulMorel** [comment]
I'm having similar issues, but for me its intermittent. Every other time I start Docker it gets stuck at *Docker engine is starting*.

----

Windows Version: **Windows 10 Pro (20H2 Build 19042)**
Docker Desktop Version: **3.5.2 (66501)**
WSL2 or Hyper-V backend? **Hyper-V**
Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **No**

----

Whenever it gets stuck, I get similar messages as @stakx in my logs:

```
[09:10:24.122][IPCClient         ][Info   ] (f1a7c41f) 683a1174-LifecycleClient-CSharp C->S GET /ping
[09:10:25.123][LifecycleClient   ][Warning] HttpOS Client: connection timed out.
[09:10:26.127][IPCClient         ][Info   ] (ac97cb9b) 683a1174-LifecycleClient-CSharp C->S GET /ping
[09:10:27.128][LifecycleClient   ][Warning] HttpOS Client: connection timed out.
[09:10:28.129][IPCClient         ][Info   ] (d514f2fa) 683a1174-LifecycleClient-CSharp C->S GET /ping
[09:10:29.128][LifecycleClient   ][Warning] HttpOS Client: connection timed out.
[09:10:30.146][IPCClient         ][Info   ] (4f8c9636) 683a1174-LifecycleClient-CSharp C->S GET /ping
[09:10:31.146][LifecycleClient   ][Warning] HttpOS Client: connection timed out.
[09:10:32.161][IPCClient         ][Info   ] (ec4f3690) 683a1174-LifecycleClient-CSharp C->S GET /ping
```

**Comment by nulled06** [comment]
Downgrade to 3.3.3 fix problem. 3.5.2 and 3.5.1 not work on Windows 21H1(19043 build)

**Comment by fabiougolini** [comment]
> Downgrade to 3.3.3 fix problem. 3.5.2 and 3.5.1 not work on Windows 21H1(19043 build)

Downgrading solves the issue but then Docker will autoupgrade itself on next reboot and the issue appears again...

**Comment by IosifZ** [comment]
I have the same issue. Docker used to start in 2 minutes on my machine, now it needs exactly 12 minutes to start.

- Windows Version: 10 Pro 21H1 (OS Build 19043.1110)
- Docker Desktop Version: 3.5.2 (66501)
- WSL2 or Hyper-V backend? Hyper-V
- Diagnostics ID: 2BE97D4B-BC5A-4ED0-9483-A57B73129F09/20210720102708
Here is the gap as it appears in the log:

`[11:48:40.870][HyperVGuids       ][Info   ] Installing GUIDs...
[11:48:40.870][HyperVGuids       ][Info   ] GUIDs installed
[11:48:40.872][HyperV            ][Info   ] Start
[11:48:42.818][IPCServer         ][Info   ] (105f864c) 592b4670-ServiceAPI S->C 44bc8ff2-BackendAPIClient-CSharp POST /hyperv/start (1951ms): OK
[11:58:43.482][IPCServer         ][Info   ] (f60a1cf8) 592b4670-ServiceAPI S<-C 67936a6f-BackendAPIClient-CSharp POST /hyperv/stop
   at Docker.Core.BackendAPI.BackendAPIClient.<StopHyperVVMAsync>d__12.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 0
   at Docker.Core.BackendAPI.BackendAPIClient.StopHyperVVMAsync(CancellationToken cancellationToken)
   at Docker.Engines.LinuxHyperVEngine.<DoStopAsync>d__17.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 101
   at Docker.Engines.LinuxHyperVEngine.DoStopAsync(CancellationToken cancellationToken)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 46
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 16
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__14.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 66
   at Docker.ApiServices.LifecycleClient.<WaitForServerUpAsync>d__2.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\LifecycleClient.cs:line 54
[11:58:52.333][IPCServer         ][Info   ] (f60a1cf8) 592b4670-ServiceAPI S->C 67936a6f-BackendAPIClient-CSharp POST /hyperv/stop (8851ms): OK`

**Comment by gschafra** [comment]
Got the same problem. But when I'm restarting the Docker-VM forcefully using the Hyper-V-Manager while the Docker-Window is indicating that it is still starting, it get's into functional state short after the VM has restarted.

**Comment by IosifZ** [comment]
Any news when this will be fixed?
Thanks.
