### ISSUE TITLE
Installer error: Component CommunityInstaller.ExecAction failed: The requested operation requires elevation

### ISSUE THREAD

**Issue by void-spark** [docker/for-win#11664]
- [ x] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics - Can't install not possible
  - Diagnostics ID:

### Actual behavior
Docker fails to install with error (even when the installer is given elevated rights):
[13:53:54.045][InstallWorkflow] Installation failed
Exception type: System.Exception, Exception message: Component CommunityInstaller.ExecAction failed: The requested operation requires elevation, StackTrace:
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

### Expected behavior
Docker installs correctly when given elevated rights.

### Information
We are trying to install Docker on Windows on new PC's.
In our environment there is management software which pops up a dialog to explicitly allow elevated rights.
When starting the Docker installer the dialog pops up, and elevated rights are given.
Yet later the installer fails regardless with the message 'The requested operation requires elevation'
My guess is that somewhere in the installer there is a invalid check for elevated rights.
Since it's closed source, I can't check that myself though.

  - Windows Version: 10.0.18363 Build 18363
  - Docker Desktop Version: 3.5.1 / 3.5.2
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, physical PC.

### Steps to reproduce the behavior

  1. Download lastest installer (Docker Desktop Installer.exe)
  2. Start installer, and give elevated rights (the software behind this is CyberArk Endpoint Privilege Manager)
  3. After a while the error is shown.

I understand you can't test this locally, since you most likely don't have the CyberArk software.
If we could know what check is performed in the code indicated by the stack trace that would help though possibly.
And maybe you can verify the check there is correct.

Thank you for your attention!

Installer log (3.5.1), all options selected:
```
Started on: 2021/07/13 13:46:57.462
File: C:\Users\void-spark\AppData\Local\Docker\install-log.txt
CommandLine: "C:\workspace\Downloads\Docker Desktop Installer.exe" "install" -package "res:DockerDesktop" --relaunch-as-admin
[13:46:57.472][ManifestAndExistingInstallationLoader] No install path specified, looking for default installation registry key
[13:46:57.473][Program] No installation found
[13:46:57.687][InstallWorkflow] Cancel pending background download
[13:46:57.703][InstallWorkflow] Using package: res:DockerDesktop
[13:46:57.707][InstallWorkflow] Downloading
[13:46:59.114][InstallWorkflow] Extracting manifest
[13:47:00.821][InstallWorkflow] Manifest found: version=66090, displayVersion=3.5.1, channelUrl=https://desktop.docker.com/win/stable/amd64/appcast.xml
[13:47:00.822][InstallWorkflow] Checking prerequisites
[13:47:01.888][InstallWorkflow] Prompting for optional features
[13:47:50.548][InstallWorkflow] Unpacking artifacts
[13:49:34.516][InstallWorkflow] Deploying component CommunityInstaller.CreateGroupAction
[13:49:39.139][InstallWorkflow] Deploying component CommunityInstaller.AddToGroupAction
[13:49:39.151][InstallWorkflow] Deploying component CommunityInstaller.EnableFeaturesAction
[13:49:40.708][InstallWorkflow-EnableFeaturesAction] Enable Windows Feature *Hyper-V*
[13:49:40.709][InstallWorkflow-EnableFeaturesAction] Enable Windows Feature Containers
[13:51:45.288][InstallWorkflow-EnableFeaturesAction] Class not registered

[13:53:49.098][InstallWorkflow-EnableFeaturesAction] Class not registered

[13:53:49.101][InstallWorkflow] Deploying component CommunityInstaller.EnableFeaturesAction
[13:53:50.664][InstallWorkflow] Deploying component CommunityInstaller.ServiceAction
[13:53:50.667][InstallWorkflow-ServiceAction] Removing service
[13:53:50.668][InstallWorkflow-ServiceAction] Creating service
[13:53:52.369][InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
[13:53:52.403][InstallWorkflow-ShortcutAction] Creating shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Docker Desktop.lnk/Docker Desktop
[13:53:52.451][InstallWorkflow] Deploying component CommunityInstaller.AutoStartAction
[13:53:52.452][InstallWorkflow] Deploying component CommunityInstaller.PathAction
[13:53:53.169][InstallWorkflow] Deploying component CommunityInstaller.PathAction
[13:53:53.996][InstallWorkflow] Deploying component CommunityInstaller.ExecAction
[13:53:54.045][InstallWorkflow] Installation failed
Exception type: System.Exception, Exception message: Component CommunityInstaller.ExecAction failed: The requested operation requires elevation, StackTrace:
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[13:53:54.047][InstallWorkflow] Rollbacking component CommunityInstaller.PathAction
[13:53:55.535][InstallWorkflow] Rollbacking component CommunityInstaller.PathAction
[13:53:56.978][InstallWorkflow] Rollbacking component CommunityInstaller.AutoStartAction
[13:53:56.979][InstallWorkflow] Rollbacking component CommunityInstaller.ShortcutAction
[13:53:56.981][InstallWorkflow] Rollbacking component CommunityInstaller.ServiceAction
[13:53:57.987][InstallWorkflow] Rollbacking component CommunityInstaller.EnableFeaturesAction
[13:53:57.989][InstallWorkflow] Rollbacking component CommunityInstaller.EnableFeaturesAction
[13:53:57.989][InstallWorkflow] Rollbacking component CommunityInstaller.AddToGroupAction
[13:53:57.990][InstallWorkflow] Rollbacking component CommunityInstaller.CreateGroupAction
[13:53:57.990][InstallWorkflow] Rollbacking component CommunityInstaller.UnpackArtifactsStep
[13:53:57.996][FileSystem] Deleting C:\Program Files\Docker\Docker
[13:54:01.238][FileSystem] Deleted C:\Program Files\Docker\Docker successfully
[13:54:01.239][InstallWorkflow] Rollbacking component CommunityInstaller.ExtractManifestStep
[13:54:01.239][InstallWorkflow] Rollbacking component CommunityInstaller.DownloadStep
```

Installer log (3.5.2), no options selected:
```
Started on: 2021/07/13 14:06:58.957
File: C:\Users\void-spark\AppData\Local\Docker\install-log.txt
CommandLine: "C:\workspace\Downloads\Docker Desktop Installer.exe" "install" -package "res:DockerDesktop" --relaunch-as-admin
[14:06:58.966][ManifestAndExistingInstallationLoader] No install path specified, looking for default installation registry key
[14:06:58.968][Program] No installation found
[14:06:59.207][InstallWorkflow] Cancel pending background download
[14:06:59.222][InstallWorkflow] Using package: res:DockerDesktop
[14:06:59.223][InstallWorkflow] Downloading
[14:07:00.601][InstallWorkflow] Extracting manifest
[14:07:02.259][InstallWorkflow] Manifest found: version=66501, displayVersion=3.5.2, channelUrl=https://desktop.docker.com/win/stable/amd64/appcast.xml
[14:07:02.259][InstallWorkflow] Checking prerequisites
[14:07:03.349][InstallWorkflow] Prompting for optional features
[14:14:30.677][InstallWorkflow] Unpacking artifacts
[14:16:07.350][InstallWorkflow] Deploying component CommunityInstaller.CreateGroupAction
[14:16:11.939][InstallWorkflow] Deploying component CommunityInstaller.AddToGroupAction
[14:16:11.947][InstallWorkflow] Deploying component CommunityInstaller.ServiceAction
[14:16:11.950][InstallWorkflow-ServiceAction] Removing service
[14:16:11.951][InstallWorkflow-ServiceAction] Creating service
[14:16:13.482][InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
[14:16:13.499][InstallWorkflow-ShortcutAction] Creating shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Docker Desktop.lnk/Docker Desktop
[14:16:13.509][InstallWorkflow] Deploying component CommunityInstaller.AutoStartAction
[14:16:13.511][InstallWorkflow] Deploying component CommunityInstaller.PathAction
[14:16:13.870][InstallWorkflow] Deploying component CommunityInstaller.PathAction
[14:16:14.152][InstallWorkflow] Deploying component CommunityInstaller.ExecAction
[14:16:14.212][InstallWorkflow] Installation failed
Exception type: System.Exception, Exception message: Component CommunityInstaller.ExecAction failed: The requested operation requires elevation, StackTrace:
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[14:16:14.214][InstallWorkflow] Rollbacking component CommunityInstaller.PathAction
[14:16:14.507][InstallWorkflow] Rollbacking component CommunityInstaller.PathAction
[14:16:14.824][InstallWorkflow] Rollbacking component CommunityInstaller.AutoStartAction
[14:16:14.826][InstallWorkflow] Rollbacking component CommunityInstaller.ShortcutAction
[14:16:14.827][InstallWorkflow] Rollbacking component CommunityInstaller.ServiceAction
[14:16:15.833][InstallWorkflow] Rollbacking component CommunityInstaller.AddToGroupAction
[14:16:15.833][InstallWorkflow] Rollbacking component CommunityInstaller.CreateGroupAction
[14:16:15.834][InstallWorkflow] Rollbacking component CommunityInstaller.UnpackArtifactsStep
[14:16:15.842][FileSystem] Deleting C:\Program Files\Docker\Docker
[14:16:22.506][FileSystem] Deleted C:\Program Files\Docker\Docker successfully
[14:16:22.506][InstallWorkflow] Rollbacking component CommunityInstaller.ExtractManifestStep
[14:16:22.507][InstallWorkflow] Rollbacking component CommunityInstaller.DownloadStep
```

**Comment by void-spark** [comment]
Our support team managed to resolve this, though I'm not sure what they changed, so closing the issue
