### ISSUE TITLE
Unable to start decker for desktop

### ISSUE THREAD

**Issue by sheosumit** [docker/for-win#11676]
Not able to start docker for desktop.

System.ArgumentException:
Unable to create an instance of Docker.App: Unable to create an instance of Docker.ApiServices.Update.UpdateCheckTimer: Unable to create an instance of Docker.ApiServices.Update.Updater: Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
   at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
   at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
   at Docker.Core.Di.Singletons.Get[T]() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 28
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 268

  System.ArgumentException:
  Unable to create an instance of Docker.ApiServices.Update.UpdateCheckTimer: Unable to create an instance of Docker.ApiServices.Update.Updater: Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
     at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
     at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
     at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
  
     System.ArgumentException:
     Unable to create an instance of Docker.ApiServices.Update.Updater: Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
        at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
        at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
        at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
        at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
        at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
        at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
     
         System.ArgumentException:
         Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
            at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 93
            at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
            at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
            at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
            at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
            at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
         
              System.Reflection.TargetInvocationException:
              Exception has been thrown by the target of an invocation.
                 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
                 at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
                 at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
              
                    System.Runtime.InteropServices.COMException:
                    Retrieving the COM class factory for component with CLSID {1ECCA34C-E88A-44E3-8D6A-8921BDE9E452} failed due to the following error: 80010111 OLE received a packet with an invalid header. (Exception from HRESULT: 0x80010111).
                       at Docker.Notifications.BackgroundUpdateWatcher..ctor(ISystrayNotifications systray, IUpdateStateNotifier updateStateNotifier) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\Notifications\BackgroundUpdateWatcher.cs:line 12

**Comment by gus-pdk** [comment]
Im experiencing the same issue. Upgrading, disabling/enabling windows features, complete uninstall and re-install have not worked.

**Comment by trungutt** [comment]
We're closing this issue because it doesn't contain enough information for us to investigate the problem. If you'd like us to investigate further, could you please open a fresh issue with a more detailed description of the problem and copy your diagnostic ID, following the steps at https://docs.docker.com/docker-for-win/troubleshoot?
