### ISSUE TITLE
"System.ArgumentException: Only TrueType fonts are supported" when isolation=process and calling Font.FromLogFont

### ISSUE THREAD

**Issue by AchimBursian** [docker/for-win#11688]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
    - Diagnostics ID: D32AB3F1-29A1-41C1-8E9A-F7B4B9DCBFB2/20210716092741

### Actual behavior
When building with `docker build --isolation=process` and running with `docker run --isolation=process`, my .NET based application crashes with an exception whenever I call `System.Drawing.Font.FromLogFont` (with a valid LOGFONT).

    Checking with Font.FromLogFont(): 'Arial'
    System.ArgumentException: Only TrueType fonts are supported. This is not a TrueType font.
       at System.Drawing.Font.FromLogFont(Object lf, IntPtr hdc)
       at System.Drawing.Font.FromLogFont(Object lf)
       at ContainerFontTest.FontCheck.CheckWithLogfont(String familyName)

When the **same** image is started with `docker run --isolation=hyperv`, the calls run fine and the application runs as expected.

Consistent setting for --isolation in build and run cause the problem. Only when the setting is inconsistent (process for building, but hyperv for execution) the problem is gone. Completely counterintuitive.

### Expected behavior
- The created image should be running fine with `--isolation=process` and `--isolation=hyperv`
- It shouldn't make any difference to use `--isolation=process` or `--isolation=hyperv` for `docker build`

### Information
It is completely unclear what the `--isolation` parameter affects during a `docker build`. We think that building an image should be an independent step, not taking into account the isolation method that will later be used for execution.

The problem is reproducible with the attached repro project. Don't know if that ever worked better with older versions, as I discovered it with newest Docker version.

  - Windows Version: Win 10 1909
  - Docker Desktop Version: 20.10.5
  - WSL2 or Hyper-V backend?  Windows Containers
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Steps to reproduce the behavior
- Switch Docker to Windows containers
- `cd ContainerFontTest`
- `msbuild ContainerFontTest.csproj -p:Configuration=Release;Platform=x64`
- `docker build --no-cache --isolation=hyperv  -t containerfonttest:hyperv  .`
- `docker build --no-cache --isolation=process -t containerfonttest:process .`

Run with different settings
- `docker run --isolation=process containerfonttest:hyperv`
- `docker run --isolation=process containerfonttest:process`
- `docker run --isolation=hyperv  containerfonttest:hyperv`
- `docker run --isolation=hyperv  containerfonttest:process`

![image](https://user-images.githubusercontent.com/75032748/125926992-bb06a648-31ef-4225-a0a0-e208fb1bcf88.png)

**Comment by AchimBursian** [comment]
[ContainerFontTest.zip](https://github.com/docker/for-win/files/6830172/ContainerFontTest.zip)
