### ISSUE TITLE
Error Launching on Windows 10

### ISSUE THREAD

**Issue by Bioblaze** [docker/for-win#11689]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
 Docker is unable to Start on Windows 10 utilizing Docker 3.5.2 

### Information

  - Windows Version: Windows 10 Pro 19043
  - Docker Desktop Version: 3.5.2 (66501)
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

From the Log.txt
```
Version: 3.5.2 (66501)
Sha1: 84e4b4334c1e4ea66e074cf2d17440e1f62ab201
Started on: 2021/07/16 09:08:25.709
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 19043
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\biobl\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:08:25.782][GUI               ][Info   ] Starting...
[09:08:25.967][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer -native-api
[09:08:26.029][GoBackendProcess  ][Info   ] Started
[09:08:26.033][DevEnvBackendProcess][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.dev-envs.exe 
[09:08:26.063][DevEnvBackendProcess][Info   ] Started
[09:08:26.095][GoBackendProcess  ][Error  ] msg="unable to parse C:\\Users\\biobl\\AppData\\Roaming\\Docker\\settings.json: open C:\\Users\\biobl\\AppData\\Roaming\\Docker\\settings.json: The system cannot find the file specified."
[09:08:26.099][DevEnvBackendProcess][Info   ] ⇨ http server started on \\.\pipe\dockerDevEnvApiServer
[09:08:26.100][GoBackendProcess  ][Fatal  ] msg="reading C:\\Users\\biobl\\AppData\\Roaming\\Docker\\locked-directories: while parsing JSON from C:\\Users\\biobl\\AppData\\Roaming\\Docker\\locked-directories: invalid character '\\x00' looking for beginning of value"
[09:08:26.101][IPCClient         ][Info   ] (2bcc061b) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:26.106][IPCClient         ][Info   ] (4d2d95bb) a51f9e30-GoBackendClient-CSharp C->S GET /settings
[09:08:26.106][GoBackendProcess  ][Error  ] Process died
[09:08:26.114][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:26.115][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:26.118][SettingsLoader    ][Warning] Failed to fetch settings from backend, retrying in 1 sec
[09:08:26.418][IPCClient         ][Info   ] (74220256) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:26.420][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:26.722][IPCClient         ][Info   ] (25ad7ec5) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:26.722][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:27.023][IPCClient         ][Info   ] (e0f152da) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:27.023][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:27.324][IPCClient         ][Info   ] (6ac92cd8) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:27.324][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:27.625][IPCClient         ][Info   ] (15a4cb84) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:27.625][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:27.926][IPCClient         ][Info   ] (07bb145b) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:27.926][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:28.227][IPCClient         ][Info   ] (00625b44) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:28.227][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:28.528][IPCClient         ][Info   ] (8c1b8d5b) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:28.528][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:28.829][IPCClient         ][Info   ] (b45c8ecd) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:28.829][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:29.130][IPCClient         ][Info   ] (5469a365) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:29.130][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:29.431][IPCClient         ][Info   ] (5871e5c7) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:29.431][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:29.732][IPCClient         ][Info   ] (b74ead62) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:29.732][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:30.033][IPCClient         ][Info   ] (e6d78d43) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:30.033][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:30.334][IPCClient         ][Info   ] (8c8591b1) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:30.334][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:30.635][IPCClient         ][Info   ] (e3e6e263) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:30.635][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:30.936][IPCClient         ][Info   ] (fc23b017) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:30.936][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:31.118][GoBackendProcess  ][Error  ] Auto restarting process
[09:08:31.118][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer -native-api
[09:08:31.178][GoBackendProcess  ][Info   ] Started
[09:08:31.236][GoBackendProcess  ][Error  ] msg="unable to parse C:\\Users\\biobl\\AppData\\Roaming\\Docker\\settings.json: open C:\\Users\\biobl\\AppData\\Roaming\\Docker\\settings.json: The system cannot find the file specified."
[09:08:31.237][IPCClient         ][Info   ] (770ca04f) a51f9e30-GoBackendClient-CSharp C->S GET /ping
[09:08:31.237][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:08:31.247][GoBackendProcess  ][Fatal  ] msg="reading C:\\Users\\biobl\\AppData\\Roaming\\Docker\\locked-directories: while parsing JSON from C:\\Users\\biobl\\AppData\\Roaming\\Docker\\locked-directories: invalid character '\\x00' looking for beginning of value"
[09:08:31.251][GoBackendProcess  ][Error  ] Process died
```

**Comment by Bioblaze** [comment]
the `locked-directories` file contains `   ` just 3 null values

**Comment by Bioblaze** [comment]
settings.json does not exist at all

**Comment by Bioblaze** [comment]
everything was working just 2 days ago, Windows updated or Docker updated and boom now everything is down. No idea why.

**Comment by Bioblaze** [comment]
```
Version: 3.5.2 (66501)
Sha1: 84e4b4334c1e4ea66e074cf2d17440e1f62ab201
Started on: 2021/07/16 09:46:45.044
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 19043
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\biobl\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:46:45.116][GUI               ][Info   ] Starting...
[09:46:45.227][IPCClient         ][Info   ] (1005f24c) 8c6a2144-GoBackendClient-CSharp C->S GET /ping
[09:46:45.227][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:46:45.295][GUI               ][Info   ] An instance is already running. Launching the container view.
[09:46:45.380][GUI               ][Error  ] System.TimeoutException:
The operation has timed out.
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.NamedPipe.NamedPipeDialer.<DialAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.Client.DialMessageHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 196
[09:46:45.528][IPCClient         ][Info   ] (8d5fe7d4) 8c6a2144-GoBackendClient-CSharp C->S GET /ping
[09:46:45.528][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:46:45.829][IPCClient         ][Info   ] (5d9ba75a) 8c6a2144-GoBackendClient-CSharp C->S GET /ping
[09:46:45.829][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:46:46.130][IPCClient         ][Info   ] (01c3348e) 8c6a2144-GoBackendClient-CSharp C->S GET /ping
[09:46:46.130][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:46:46.430][IPCClient         ][Info   ] (0aaf027c) 8c6a2144-GoBackendClient-CSharp C->S GET /ping
[09:46:46.430][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:46:46.731][IPCClient         ][Info   ] (e75c79e8) 8c6a2144-GoBackendClient-CSharp C->S GET /ping
[09:46:46.731][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:46:47.032][IPCClient         ][Info   ] (80d8bfdb) 8c6a2144-GoBackendClient-CSharp C->S GET /ping
[09:46:47.032][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:46:47.333][IPCClient         ][Info   ] (af998399) 8c6a2144-GoBackendClient-CSharp C->S GET /ping
[09:46:47.333][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[09:46:47.426][GoBackendProcess  ][Error  ] Auto restarting process
[09:46:47.426][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer -native-api
[09:46:47.486][GoBackendProcess  ][Info   ] Started
[09:46:47.542][GoBackendProcess  ][Error  ] msg="unable to parse C:\\Users\\biobl\\AppData\\Roaming\\Docker\\settings.json: open C:\\Users\\biobl\\AppData\\Roaming\\Docker\\settings.json: The system cannot find the file specified."
[09:46:47.554][GoBackendProcess  ][Fatal  ] msg="reading C:\\Users\\biobl\\AppData\\Roaming\\Docker\\locked-directories: while parsing JSON from C:\\Users\\biobl\\AppData\\Roaming\\Docker\\locked-directories: invalid character '\\x00' looking for beginning of value"
[09:46:47.557][GoBackendProcess  ][Error  ] Process died
```

Updated Windows, and ran it again tried to start Docker Desktop and this is the logs from the file.

**Comment by Bioblaze** [comment]
Updated too `Windows 10, version 21H2`

**Comment by Bioblaze** [comment]
I have uninstalled Docker, then restarted, then installed Docker, and restarted. And I still get the same issues.

**Comment by Bioblaze** [comment]
```
Version: 3.5.1 (66090)
Sha1: 758e6bb20c166a9e825d33ae94dee3c4787d6425
Started on: 2021/07/16 10:41:36.364
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 19043
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\biobl\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[10:41:36.436][GUI               ][Info   ] Starting...
[10:41:36.809][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer -native-api
[10:41:37.091][GoBackendProcess  ][Info   ] Started
[10:41:37.095][DevEnvBackendProcess][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.dev-envs.exe 
[10:41:37.162][GoBackendProcess  ][Error  ] msg="unable to parse C:\\Users\\biobl\\AppData\\Roaming\\Docker\\settings.json: open C:\\Users\\biobl\\AppData\\Roaming\\Docker\\settings.json: The system cannot find the file specified."
[10:41:37.170][GoBackendProcess  ][Fatal  ] msg="reading C:\\Users\\biobl\\AppData\\Roaming\\Docker\\locked-directories: while parsing JSON from C:\\Users\\biobl\\AppData\\Roaming\\Docker\\locked-directories: invalid character '\\x00' looking for beginning of value"
[10:41:37.175][GoBackendProcess  ][Error  ] Process died
```

So I down graded Docker same issue, maybe a windows problem? I'm updating windows again.

**Comment by Bioblaze** [comment]
```
Version: 3.5.1 (66090)
Sha1: 758e6bb20c166a9e825d33ae94dee3c4787d6425
Started on: 2021/07/16 10:47:37.887
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 19044
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\biobl\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[10:47:37.959][GUI               ][Info   ] Starting...
[10:47:38.038][IPCClient         ][Info   ] (00b51076) c38100f7-GoBackendClient-CSharp C->S GET /ping
[10:47:38.038][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:47:38.139][GUI               ][Info   ] An instance is already running. Launching the container view.
[10:47:38.181][GUI               ][Error  ] System.TimeoutException:
The operation has timed out.
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.NamedPipe.NamedPipeDialer.<DialAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.Client.DialMessageHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\PR-16024\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 196
[10:47:38.340][IPCClient         ][Info   ] (0bc513dc) c38100f7-GoBackendClient-CSharp C->S GET /ping
[10:47:38.340][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:47:38.641][IPCClient         ][Info   ] (c6a9d48f) c38100f7-GoBackendClient-CSharp C->S GET /ping
[10:47:38.641][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:47:38.942][IPCClient         ][Info   ] (506e2867) c38100f7-GoBackendClient-CSharp C->S GET /ping
[10:47:38.942][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:47:39.243][IPCClient         ][Info   ] (74fe1ed0) c38100f7-GoBackendClient-CSharp C->S GET /ping
[10:47:39.243][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:47:39.544][IPCClient         ][Info   ] (7f9ea902) c38100f7-GoBackendClient-CSharp C->S GET /ping
[10:47:39.544][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:47:39.845][IPCClient         ][Info   ] (487f49a2) c38100f7-GoBackendClient-CSharp C->S GET /ping
[10:47:39.845][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:47:40.146][IPCClient         ][Info   ] (fd80ad06) c38100f7-GoBackendClient-CSharp C->S GET /ping
[10:47:40.146][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:47:40.447][IPCClient         ][Info   ] (63e480ee) c38100f7-GoBackendClient-CSharp C->S GET /ping
[10:47:40.447][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:47:40.748][IPCClient         ][Info   ] (aced80aa) c38100f7-GoBackendClient-CSharp C->S GET /ping
[10:47:40.748][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:47:41.049][IPCClient         ][Info   ] (c1e3adc8) c38100f7-GoBackendClient-CSharp C->S GET /ping
[10:47:41.049][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:47:41.350][IPCClient         ][Info   ] (cc53a07c) c38100f7-GoBackendClient-CSharp C->S GET /ping
[10:47:41.350][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:47:41.651][IPCClient         ][Info   ] (c25ee045) c38100f7-GoBackendClient-CSharp C->S GET /ping
[10:47:41.651][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:47:41.952][IPCClient         ][Info   ] (3777342e) c38100f7-GoBackendClient-CSharp C->S GET /ping
[10:47:41.952][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:47:42.153][GoBackendProcess  ][Error  ] Auto restarting process
[10:47:42.153][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer -native-api
[10:47:42.211][GoBackendProcess  ][Info   ] Started
[10:47:42.253][IPCClient         ][Info   ] (33c611dd) c38100f7-GoBackendClient-CSharp C->S GET /ping
[10:47:42.253][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:47:42.271][GoBackendProcess  ][Error  ] msg="unable to parse C:\\Users\\biobl\\AppData\\Roaming\\Docker\\settings.json: open C:\\Users\\biobl\\AppData\\Roaming\\Docker\\settings.json: The system cannot find the file specified."
[10:47:42.282][GoBackendProcess  ][Fatal  ] msg="reading C:\\Users\\biobl\\AppData\\Roaming\\Docker\\locked-directories: while parsing JSON from C:\\Users\\biobl\\AppData\\Roaming\\Docker\\locked-directories: invalid character '\\x00' looking for beginning of value"
[10:47:42.285][GoBackendProcess  ][Error  ] Process died
```

**Comment by Bioblaze** [comment]
```
Windows 10 Pro
Version: 21H2
OS Build: 19044.1147
Experience: Windows Feature Experience Pack 120.2212.3920.0
```

**Comment by Bioblaze** [comment]
so after upgrading, downgrading, and testing every which way.

I got it too work by uninstalling docker, then restarting the PC, then going to %APPDATA% and deleting the Docker and Docker Desktop folders from Local and Roaming. Then I restarted again, and launched the installed as admin. Then once it was complete  I right clicked on the Docker Desktop Launcher and launch with admin. 

Currently I am now back up and running.

**Comment by Bioblaze** [comment]
So it seems like when you uninstall docker it fails to delete all the files from the local/roaming, after uninstalling the 3.5.1 version it seems to have a issue, i'll try 2-3 version back as well see if this was a bug introduced in a earlier version since I've never ran across this before.

**Comment by steffenb91** [comment]
deleting the AppData/Local/Docker|Docker Desktop Installer and AppData/Roaming/Docker|Docker Desktop Installer did the trick for me as well. my debug log showed the same output after upgrading.
Windows, Hyper-V, Docker Desktop 3.5.2

**Comment by Pramuspl** [comment]
> my debug log showed the same output after upgrading. deleting the AppData/Local/Docker|Docker Desktop Installer and AppData/Roaming/Docker|Docker Desktop Installer did the trick for me as well.
> 
> Windows, Hyper-V, Docker Desktop 3.5.2

These folder contain containers/images so it'd be better to narrow down what causes the issue and remove only that
