### ISSUE TITLE
unable to resolve docker endpoint: open C:\Users\username\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.

### ISSUE THREAD

**Issue by BaibhavVishal123** [docker/for-win#11709]
I had earlier installed Docker Toolbox in 2019. and today installed Docker Desktop.

  - [Y] I have tried with the latest version of Docker Desktop
  - [Y] I have tried disabling enabled experimental features
  - [N] I have uploaded Diagnostics
  - Diagnostics ID:

I am trying to run ```sam deploy``` on my windows local. This gives me the following error stack trace
```
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\cli_validation\image_repository_validation.py", line 76, in wrapped     
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 153, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\deploy\command.py", line 204, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\deploy\command.py", line 317, in do_cli
    package_context.run()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\package\package_context.py", line 107, in run
    docker_client = docker.from_env()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\client.py", line 85, in from_env
    timeout=timeout, version=version, **kwargs_from_env(**kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\utils\utils.py", line 361, in kwargs_from_env
    params['tls'] = tls.TLSConfig(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\tls.py", line 80, in __init__
    raise errors.TLSParameterError(
docker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docker CLI client configurations. See https://docs.docker.com/engine/articles/https/ for API details.
```

Upon Googling, I thought I needed to communicate securely on SSH via Docker; for which docker docs suggests this.
```https://docs.docker.com/engine/security/protect-access/```

However upon running this command from the above link 
```
docker context create --docker host=ssh://docker-user@host1.example.com --description="Remote engine" my-remote-engine
```

again points to the SSL error path mismatch
```
unable to resolve docker endpoint: open C:\Users\Administrator\.docker\machine\machines\default\ca.pem: The system cannot find the path specified.
```

This again upon Googling led me to 
```https://github.com/docker/for-win/issues/7629```

The common accepted solution there to overwrite path manually does not work for me. 
Please help, I got tired of this deep rabbit hole.

**Comment by stephen-turner** [comment]
Try removing all environment variables with starting with DOCKER_.

**Comment by BaibhavVishal123** [comment]
Quoting from my own [Q&A](https://stackoverflow.com/questions/68439430/sam-cli-cant-talk-to-ssl-on-docker-desktop-for-windows) 
So I did the following

- Installed latest stable Python -> Python3.9 . SAM CLI uses python, maybe docker updated SSL version, SAM uses different version
- Cleaned up Env. Variables of DOCKER_*
- Verified if any registry keys are left for Docker
- Reinstalled Docker Desktop full
- Login using Docker Hub. Someone suggested somewhere while Googling
- Didn't check the checkbox in Docker Desktop Settings "Expose Daemon on tcp://localhost:2375 without TLS"
