### ISSUE TITLE
Docker for Windows continue to crash at start

### ISSUE THREAD

**Issue by hoegge** [docker/for-win#1170]
### Expected behavior
Docker starting
### Actual behavior
Does not start but reports error

### Information
E9CBF190-66D5-420A-A5A8-9FA5D6D52443/2017-10-05_07-32-38
Windows 10 Pro, version 1703, OS build: 15063.540

### Steps to reproduce the behavior

  1. Start windows
  2. Start docker:
```
Docker command did not complete within the allowed timeout. Output: 
   at Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 152
   at Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 49
   at Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 197
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 168
   at Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 65
   at Docker.Backend.BackendServer.<Run>b__5_11(Object[] args) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\BackendServer.cs:line 54
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

If I reinstall with the MSI file, docker runs again. But after restart it breaks. I have suspected Avast Antivirus, that put powershell.exe in host (after docker starts), and therefore might interfere. Then I installed Avast and installed Avira instead. Does not interfere until you send crash information (via FIrefox.exe? Did you install c:\program files(x86)\Firefox ? Seems a bit messy. Does docker for windows have a virus issue or some malware slipped in?

Firefox_crashreporter.exe seems to contain virus TR/Dropper.rrmq

**Comment by hoegge** [comment]
after installing newest version "A new version of Docker is available" (I was running 17.06), Docker runs fine again, but after restart it again shows error messages and cannot start:
```
Docker command did not complete within the allowed timeout. Output: 
   at Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 152
   at Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 49
   at Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 197
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 168
   at Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 65
   at Docker.Backend.BackendServer.<Run>b__6_10(Object[] args) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\BackendServer.cs:line 52
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

and it wants to install a new version (same version again) that it just installed (17.09.0-ce-win33 (13620)). 

Crash report diagnostic ID: E9CBF190-66D5-420A-A5A8-9FA5D6D52443/2017-10-06_11-37-49

**Comment by hoegge** [comment]
Additionally, if you for some reason do not have network access for the installer (e.g. due to firewall) the installer quits immediately instead of reporting lack of connection:
```
An error occurred while sending the request.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.DownloadStep.<DoAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__18.MoveNext()
```

**Comment by hoegge** [comment]
After the latest update, Docker consitently fails starting up and consitently starts fine after doing a restart of docker (new option?).

I wonder why "Docker" do not bother to look into this (i.e., not a single response to this issue). Maybe because it is similar to: #27 #1075 ?
