### ISSUE TITLE
Another docker won't start anymore after last upate

### ISSUE THREAD

**Issue by makapaka23** [docker/for-win#1173]
### Information

  - 1367A974-CAB1-4CA3-989E-D8A8E9908255/2017-10-05_22-42-28
  - Win 10
  - Docker 17.09.0-ce-win32 (13529) stable

Log:

Error response from daemon: Bad response from Docker engine

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 252
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

I've had the problem for months, where on boot, docker won't start. However previously I would simply stop it and restart it, and everything works.  
But after the most recent update, it won't start anymore at all and I have tried to uninstall/reinstall, do factory reset, start docker as administrator and nothing seems to work.

I'd really appreciate help on this as i've become quite reliant on docker for my dev - in which case I havent been able to dev in a couple of weeks now !
  
### Steps to reproduce the behavior

  1. Tried uninstall/reinstall
  2. Tried factory reset/restart
  3. Tried starting as administrator

**Comment by gtardif** [comment]
Hi @makapaka23, we are having a hard time reproducing the issue but from the various logs it seems this is caused by libgmp that sometimes crashes the vpnkix.exe process. 
We have a candidate fix for the issue ; if you get a chance, could you test it and confirm if this fixes the problem on your machine ? 
https://download.docker.com/win/stable/13620/Docker%20for%20Windows%20Installer.exe

**Comment by makapaka23** [comment]
THANK you @gtardif that worked first time !

**Comment by stasburn** [comment]
Hi, @makapaka23 . Another way to fix that issue to change Docker for Windows service (the new service introduced with this update) credentials from LocalSystem to some admin user.
Works for me with Version 17.09.0-ce-win32 (13529)

**Comment by gtardif** [comment]
@makapaka23 Thanks ; this should be released anytime today ; you're all set on your side, you already have the release version, you will get the next stable updates
