### ISSUE TITLE
Error while Starting Docker Desktop on Windows 10 Education N

### ISSUE THREAD

**Issue by maheshsabnis** [docker/for-win#11777]
Hi All,

  I am using Docker Desktop from last 2 years. Suddenly on my Windows 10 Education 10, it is generating following exception

System.ArgumentException:
Unable to create an instance of Docker.App: Unable to create an instance of Docker.ApiServices.Update.UpdateCheckTimer: Unable to create an instance of Docker.ApiServices.Update.Updater: Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
   at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
   at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
   at Docker.Core.Di.Singletons.Get[T]() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 28
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 268

  System.ArgumentException:
  Unable to create an instance of Docker.ApiServices.Update.UpdateCheckTimer: Unable to create an instance of Docker.ApiServices.Update.Updater: Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
     at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
     at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
     at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
  
     System.ArgumentException:
     Unable to create an instance of Docker.ApiServices.Update.Updater: Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
        at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
        at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
        at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
        at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
        at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
        at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
     
         System.ArgumentException:
         Unable to create an instance of Docker.Notifications.BackgroundUpdateWatcher: Exception has been thrown by the target of an invocation.
            at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 93
            at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
            at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
            at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
            at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
            at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
         
              System.Reflection.TargetInvocationException:
              Exception has been thrown by the target of an invocation.
                 at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
                 at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
                 at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
              
                    System.Runtime.InteropServices.COMException:
                    Retrieving the COM class factory for component with CLSID {1ECCA34C-E88A-44E3-8D6A-8921BDE9E452} failed due to the following error: 80080005 Server execution failed (Exception from HRESULT: 0x80080005 (CO_E_SERVER_EXEC_FAILURE)).
                       at Docker.Notifications.BackgroundUpdateWatcher..ctor(ISystrayNotifications systray, IUpdateStateNotifier updateStateNotifier) in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\Notifications\BackgroundUpdateWatcher.cs:line 12
                    

I have uninstalled it and installed it twice with WSL 2 / without WSL 2 but the problem persists. Yesterday, I have renamed .kube folder to start the Kubernetes so it has started but today morning when I have restarted my laptop again the same issue. Is there some issue with latest Window 10 update? 

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by maheshsabnis** [comment]
Update,

 I have renamed the .kube folder and restarted the Docker and Kubernetes. I think I have to do this for each restart. Is there any other solution exist for the same.

Regards
Mahesh Sabnis
