### ISSUE TITLE
Docker fails to start in Windows 10

### ISSUE THREAD

**Issue by envyN** [docker/for-win#1181]
### Expected behavior
Docker should have started normally
### Actual behavior
Docker fails to start with below error:
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'NPETLA-W01' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.

log:
```Version: 17.09.0-ce-win33 (13620)
Channel: stable
Sha1: 8c56a3b0e1bf39569b048201110bf1005e4b3ac9
Started on: 2017/10/07 11:28:49.253
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.1480.amd64fre.rs1_release.170706-2004
File: C:\Users\npetla\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:28:50.795][GUI            ][Info   ] Starting...
[11:29:08.812][Tracking       ][Info   ] Crash report and usage statistics are enabled
[11:29:08.867][SegmentApi     ][Info   ] Usage statistic: appLaunched
[11:29:12.724][NPS            ][Info   ] NPS user ceated on :10/3/2017 8:32:35 AM -07:00, last survey : 1/1/0001 12:00:00 AM +00:00
[11:29:12.726][SegmentApi     ][Info   ] Usage statistic: heartbeat
[11:29:12.730][SegmentApi     ][Info   ] Usage statistic: Identify
[11:29:13.337][NamedPipeClient][Info   ] Sending Version()...
[11:29:13.566][NamedPipeClient][Info   ] Received response for Version
[11:29:13.597][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[11:27:11.974][BackendServer  ][Info   ] Started
[11:29:13.496][NamedPipeServer][Info   ] Version()
[11:29:13.497][NamedPipeServer][Info   ] Version done in 00:00:00.
[11:29:13.770][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
[11:29:13.776][PowerMode      ][Info   ] Stop
[11:29:14.362][HyperV         ][Info   ] Stop
[11:29:14.413][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:29:14.416][PowerShell     ][Info   ] Creating a Runspace Pool...
[11:29:19.299][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[11:29:19.682][HyperV         ][Info   ] Script started at 11:29:19.651
[11:29:29.929][HyperV         ][Info   ] Module loaded at 11:29:29.928
[11:29:30.401][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:29:30.402][HyperV         ][Debug  ] [stop] took 00:00:16.0380033 to run
[11:29:30.403][OptimizeDisk   ][Info   ] Optimize
[11:29:30.404][PowerShell     ][Info   ] Run script...
[11:29:30.558][Moby           ][Info   ] Stop
[11:29:30.573][PowerMode      ][Info   ] Start
[11:29:30.573][HyperVGuids    ][Info   ] Installing GUIDs...
[11:29:30.574][HyperV         ][Info   ] Create
[11:29:30.575][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[11:29:30.576][HyperVGuids    ][Info   ] GUIDs installed
[11:29:30.594][HyperV         ][Info   ] Script started at 11:29:30.594
[11:29:30.608][Firewall       ][Info   ] Removing all existing rules...
[11:29:30.623][HyperV         ][Info   ] Module loaded at 11:29:30.623
[11:29:30.812][Firewall       ][Info   ] All existing rules are removed.
[11:29:30.813][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[11:29:30.854][Firewall       ][Info   ] Opening ports for SMB...
[11:29:30.904][Firewall       ][Info   ] Ports are opened
[11:29:31.858][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:29:33.096][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'NPETLA-W01' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385. Let's retry
[11:29:33.098][PowerShell     ][Info   ] Run script...
[11:29:53.104][HyperV         ][Info   ] Hyper-V is running
[11:29:53.104][PowerMode      ][Info   ] Stop
[11:29:53.104][HyperV         ][Info   ] Stop
[11:29:53.105][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:29:53.115][HyperV         ][Info   ] Script started at 11:29:53.115
[11:29:53.137][HyperV         ][Info   ] Module loaded at 11:29:53.137
[11:29:54.013][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:29:54.013][HyperV         ][Debug  ] [stop] took 00:00:00.9094943 to run
[11:29:54.013][OptimizeDisk   ][Info   ] Optimize
[11:29:54.013][PowerShell     ][Info   ] Run script...
[11:29:54.327][Moby           ][Info   ] Stop
[11:29:54.343][HyperV         ][Info   ] Destroy
[11:29:54.344][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[11:29:54.355][HyperV         ][Info   ] Script started at 11:29:54.355
[11:29:54.378][HyperV         ][Info   ] Module loaded at 11:29:54.378
[11:29:54.589][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:29:54.592][HyperV         ][Info   ] Destroying Switch DockerNAT...
[11:29:54.851][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[11:29:54.992][HyperV         ][Debug  ] [destroy] took 00:00:00.6494918 to run
[11:29:54.993][Firewall       ][Info   ] Closing ports...
[11:29:54.993][Firewall       ][Info   ] Removing all existing rules...
[11:29:55.119][Firewall       ][Info   ] All existing rules are removed.
[11:29:55.119][Firewall       ][Info   ] Ports are closed
[11:29:55.120][HyperVGuids    ][Info   ] Removing GUIDs...
[11:29:55.122][HyperVGuids    ][Info   ] GUIDs removed
[11:29:55.122][HyperV         ][Info   ] Create
[11:29:55.123][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[11:29:55.132][HyperV         ][Info   ] Script started at 11:29:55.132
[11:29:55.165][HyperV         ][Info   ] Module loaded at 11:29:55.165
[11:29:56.363][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:29:56.999][PowerMode      ][Info   ] Stop
[11:29:57.000][HyperV         ][Info   ] Stop
[11:29:57.001][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:29:57.012][HyperV         ][Info   ] Script started at 11:29:57.012
[11:29:57.049][HyperV         ][Info   ] Module loaded at 11:29:57.049
[11:29:57.294][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:29:57.294][HyperV         ][Debug  ] [stop] took 00:00:00.2944994 to run
[11:29:57.294][OptimizeDisk   ][Info   ] Optimize
[11:29:57.294][PowerShell     ][Info   ] Run script...
[11:29:57.398][Moby           ][Info   ] Stop
[11:29:57.408][HyperV         ][Info   ] Destroy
[11:29:57.409][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[11:29:57.417][HyperV         ][Info   ] Script started at 11:29:57.417
[11:29:57.443][HyperV         ][Info   ] Module loaded at 11:29:57.442
[11:29:57.574][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:29:57.576][HyperV         ][Info   ] Destroying Switch DockerNAT...
[11:29:57.822][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[11:29:58.024][HyperV         ][Debug  ] [destroy] took 00:00:00.6155554 to run
[11:29:58.024][Firewall       ][Info   ] Closing ports...
[11:29:58.313][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'NPETLA-W01' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385
[11:29:58.315][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'NPETLA-W01' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385
[11:29:58.024][Firewall       ][Info   ] Removing all existing rules...
[11:29:58.072][Firewall       ][Info   ] All existing rules are removed.
[11:29:58.072][Firewall       ][Info   ] Ports are closed
[11:29:58.072][HyperVGuids    ][Info   ] Removing GUIDs...
[11:29:58.072][HyperVGuids    ][Info   ] GUIDs removed
[11:29:58.113][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'NPETLA-W01' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[12:29:12.366][SegmentApi     ][Info   ] Usage statistic: heartbeat
[13:29:12.342][SegmentApi     ][Info   ] Usage statistic: heartbeat
[14:03:02.634][SegmentApi     ][Info   ] Usage statistic: actionMenuSettings
[14:03:02.886][NamedPipeClient][Info   ] Sending Version()...
[14:03:02.892][NamedPipeClient][Info   ] Received response for Version
[14:03:02.893][NamedPipeClient][Info   ] Sending GetDefaultVhdxPath()...
[14:03:02.891][NamedPipeServer][Info   ] Version()
[14:03:02.892][NamedPipeServer][Info   ] Version done in 00:00:00.0005024.
[14:03:02.932][NamedPipeServer][Info   ] GetDefaultVhdxPath()
[14:03:03.214][NamedPipeClient][Error  ] Unable to send GetDefaultVhdxPath: Hyper-V encountered an error trying to access an object on computer 'NPETLA-W01' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
[14:03:03.212][NamedPipeServer][Error  ] Unable to execute GetDefaultVhdxPath: Hyper-V encountered an error trying to access an object on computer 'NPETLA-W01' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.    at Microsoft.Virtualization.Client.Management.Server.LoadOSInfo()
   at Microsoft.Virtualization.Client.Management.Server.get_VirtualizationNamespace()
   at Microsoft.Virtualization.Client.Management.ObjectKeyCreator.CreateServiceObjectKey(Server server, String serviceClassName, String serviceName, String systemCreationClassName)
   at Microsoft.Virtualization.Client.Management.ObjectLocator.GetVirtualizationService(Server server)
   at Docker.Core.Paths.get_DefaultHyperVVHDStorageFolder() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\Paths.cs:line 15
   at Docker.Core.Paths.get_DefaultMobyLinuxVhdFilePath() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\Paths.cs:line 36
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[14:03:13.382][FeedbackSettings][Info   ] Upload diagnostic
[14:03:13.394][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[14:03:13.399][NamedPipeClient][Info   ] Sending Version()...
[14:03:13.399][NamedPipeClient][Info   ] Sending Version()...
[14:03:13.425][NamedPipeClient][Info   ] Sending Version()...
[14:03:13.432][NamedPipeClient][Info   ] Received response for Version
[14:03:13.433][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[14:03:13.432][NamedPipeServer][Info   ] Version()
[14:03:13.432][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:03:13.433][NamedPipeServer][Info   ] Version()
[14:03:13.433][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:03:13.447][NamedPipeClient][Info   ] Received response for Version
[14:03:13.448][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\npetla\AppData\Local\Temp\1\nk5n13ck.ttj\pcap.tar)...
[14:03:13.449][NamedPipeServer][Info   ] GetDebugInfo()
[14:03:13.461][CrashReport    ][Warning] Unable to collect features settings: Could not find file 'C:\Users\npetla\AppData\Roaming\Docker\features-overrides.json'.
[14:03:13.461][NamedPipeClient][Info   ] Sending Version()...
[14:03:14.397][NamedPipeClient][Info   ] Received response for Version
[14:03:14.397][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\npetla\AppData\Local\Temp\1\nk5n13ck.ttj\mobyLogs.tar)...
[14:03:14.399][NamedPipeClient][Info   ] Received response for Version
[14:03:14.399][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\npetla\AppData\Local\Temp\1\nk5n13ck.ttj\win_containers)...
[14:03:14.396][NamedPipeServer][Info   ] Version()
[14:03:14.396][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:03:14.398][NamedPipeServer][Info   ] Version()
[14:03:14.398][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:03:14.401][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\npetla\AppData\Local\Temp\1\nk5n13ck.ttj\mobyLogs.tar)
[14:03:14.401][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\npetla\AppData\Local\Temp\1\nk5n13ck.ttj\pcap.tar)
[14:03:14.403][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\npetla\AppData\Local\Temp\1\nk5n13ck.ttj\win_containers)
[14:03:14.418][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[14:03:14.418][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[14:03:14.418][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0164986.
[14:03:14.485][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[14:03:18.122][HyperV         ][Warning] Unable to download logs: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'NPETLA-W01' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
[14:03:18.124][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[14:03:18.122][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:03.7209773.
[14:03:25.623][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[14:03:25.623][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:11.2204302.
[14:03:34.484][NamedPipeServer][Info   ] GetDebugInfo done in 00:00:21.0353676.
[14:03:34.488][NamedPipeClient][Info   ] Received response for GetDebugInfo
[14:03:36.122][CrashReport    ][Info   ] Uploading diagnostics...
[14:03:48.904][CrashReport    ][Info   ] Diagnostics successfully uploaded (459EA424-3400-4883-8F18-3DCD0C6EDBE1/2017-10-07_14-03-13)
[14:03:48.914][NamedPipeClient][Info   ] Sending Version()...
[14:03:48.916][NamedPipeClient][Info   ] Received response for Version
[14:03:48.917][NamedPipeClient][Info   ] Sending GetDefaultVhdxPath()...
[14:03:48.916][NamedPipeServer][Info   ] Version()
[14:03:48.916][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:03:48.920][NamedPipeServer][Info   ] GetDefaultVhdxPath()
[14:03:49.007][NamedPipeClient][Error  ] Unable to send GetDefaultVhdxPath: Hyper-V encountered an error trying to access an object on computer 'NPETLA-W01' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
[14:03:49.006][NamedPipeServer][Error  ] Unable to execute GetDefaultVhdxPath: Hyper-V encountered an error trying to access an object on computer 'NPETLA-W01' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.    at Microsoft.Virtualization.Client.Management.Server.LoadOSInfo()
   at Microsoft.Virtualization.Client.Management.Server.get_VirtualizationNamespace()
   at Microsoft.Virtualization.Client.Management.ObjectKeyCreator.CreateServiceObjectKey(Server server, String serviceClassName, String serviceName, String systemCreationClassName)
   at Microsoft.Virtualization.Client.Management.ObjectLocator.GetVirtualizationService(Server server)
   at Docker.Core.Paths.get_DefaultHyperVVHDStorageFolder() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\Paths.cs:line 15
   at Docker.Core.Paths.get_DefaultMobyLinuxVhdFilePath() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\Paths.cs:line 36
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[14:04:36.461][FeedbackSettings][Info   ] Open github issues
[14:05:56.358][SegmentApi     ][Info   ] Usage statistic: actionRestart
[14:05:56.361][Notifications  ][Info   ] Docker is restarting...
[14:05:56.388][NamedPipeClient][Info   ] Sending Version()...
[14:05:56.391][NamedPipeClient][Info   ] Received response for Version
[14:05:56.391][NamedPipeClient][Info   ] Sending Restart(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[14:05:56.391][NamedPipeServer][Info   ] Version()
[14:05:56.391][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:05:56.394][NamedPipeServer][Info   ] Restart(Docker.Core.Settings, Docker.Core.DaemonOptions)
[14:05:56.396][PowerMode      ][Info   ] Stop
[14:05:56.396][HyperV         ][Info   ] Stop
[14:05:56.401][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[14:05:56.410][HyperV         ][Info   ] Script started at 14:05:56.410
[14:05:56.441][HyperV         ][Info   ] Module loaded at 14:05:56.440
[14:05:56.661][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[14:05:56.662][HyperV         ][Debug  ] [stop] took 00:00:00.2649999 to run
[14:05:56.662][OptimizeDisk   ][Info   ] Optimize
[14:05:56.662][PowerShell     ][Info   ] Run script...
[14:05:56.757][Moby           ][Info   ] Stop
[14:05:56.771][PowerMode      ][Info   ] Stop
[14:05:56.771][HyperV         ][Info   ] Stop
[14:05:56.772][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[14:05:56.784][HyperV         ][Info   ] Script started at 14:05:56.784
[14:05:56.810][HyperV         ][Info   ] Module loaded at 14:05:56.810
[14:05:56.892][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[14:05:56.892][HyperV         ][Debug  ] [stop] took 00:00:00.1209964 to run
[14:05:56.892][OptimizeDisk   ][Info   ] Optimize
[14:05:56.892][PowerShell     ][Info   ] Run script...
[14:05:56.958][Moby           ][Info   ] Stop
[14:05:56.968][HyperV         ][Info   ] Create
[14:05:56.968][HyperVGuids    ][Info   ] Installing GUIDs...
[14:05:56.968][PowerMode      ][Info   ] Start
[14:05:56.969][Firewall       ][Info   ] Removing all existing rules...
[14:05:56.969][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[14:05:56.971][HyperVGuids    ][Info   ] GUIDs installed
[14:05:56.979][HyperV         ][Info   ] Script started at 14:05:56.979
[14:05:57.006][HyperV         ][Info   ] Module loaded at 14:05:57.005
[14:05:57.008][Firewall       ][Info   ] All existing rules are removed.
[14:05:57.008][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[14:05:57.015][Firewall       ][Info   ] Opening ports for SMB...
[14:05:57.069][Firewall       ][Info   ] Ports are opened
[14:05:57.260][HyperV         ][Info   ] Creating Switch: DockerNAT...
[14:05:57.443][NamedPipeServer][Error  ] Unable to execute Restart: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'NPETLA-W01' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 246
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 182
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[14:05:57.455][NamedPipeClient][Error  ] Unable to send Restart: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'NPETLA-W01' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385
[14:05:57.455][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'NPETLA-W01' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385
[14:05:59.341][ErrorReportWindow][Info   ] Open logs
```
### Information

  459EA424-3400-4883-8F18-3DCD0C6EDBE1/2017-10-07_14-03-13 - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by envyN** [comment]
After seeing other similar issues reported here and the long threads for possible solutions, i did an uninstall of docker, disabled Hyper-V from features and restarted and then reinstalled docker. But to no avail.

**Comment by jasonbivins** [comment]
Hi @envyN 
Let's recreate the MobyLinuxVM manually and hopefully get a more specific error

``` powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -destroy
```
```powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create ```

**Comment by Thonio** [comment]
I have the same issue and I try this command but nothing change
