### ISSUE TITLE
Docker Desktops crashes when Docker Desktop Service is disabled

### ISSUE THREAD

**Issue by erri120** [docker/for-win#11818]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9B5AEF17-97D8-4473-AEA4-8773E39EFE60/20210803165957

### System Information
  - Windows Version: Windows 10 Enterprise 21H1 (19043.1151)
  - Docker Desktop Version: 3.5.2 (66501)
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Information
I changed some hardware in my PC and on the next restart Docker Desktop complainted about the Docker Desktop Service not running and that I can start it. Clicking the start button will result in an unhandled .NET Framework exception posted at the end of this issue. Turns out that the service was set to "Disabled" in the Windows Service manager which leads to the following error when trying to manually start it using `net start com.docker.service`:

```
System error 1058 has occurred.

The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.
```

Furthermore if Docker Desktop fails to start the service and the unhandled exception occurs, selecting "Restart Docker" from the taskbar menu will completely crash Docker Desktop (and also my Firefox???).

I'm not sure what Docker Desktop uses to check if the Service is not running but it should also check if the Service is set to "Disabled" and then setting it start automatically.

### Unhandled Exception
```
************** Exception Text **************
Docker.Core.BackendAPI.ServiceNotRunningException: Unable to start Docker Desktops service: 2
   at Docker.Core.BackendAPI.BackendAPIPipeResolver.<ResolvePipeAsync>d__5.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIPipeResolver.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<CreateSystemHttpClientAsync>d__3.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<TryGetVhdxSize>d__16.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.SettingsAdjuster.<CopyVhdxSizeAsync>d__4.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\SettingsAdjuster.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.App.<Initialize>d__26.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\App.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by erri120** [comment]
cool
