### ISSUE TITLE
Docker does not start after failed update

### ISSUE THREAD

**Issue by ps68060** [docker/for-win#1189]
### Expected behavior
After upgrade to 17.09, Docker should start and allow Kitematic to connect etc.

### Actual behavior
Docker says it is starting but never does. Kitematic cannot connect. docker ps gives error.
Docker.service is running in task manager.

### Information
  - Diagnostic ID: EC79D346-839A-4EBF-926F-96DAC2E3CD6B/2017-10-09_09-34-03
  - Windows 10pro
  - Docker 17.09.0-ce-win33 (13620)

### Steps to reproduce the behavior

  1. start Docker
  2. open Settings window.

This was initially discussed under another issue https://github.com/docker/for-win/issues/1148

Several versions of Docker have been tried including Edge and none have started since the update from 17.06

**Comment by ps68060** [comment]
C:\WINDOWS\system32>docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by jasonbivins** [comment]
Hi @ps68060   
After looking through your logs, it looks like there's an issue with the Hyper-V VMMS service
```A timeout (30000 milliseconds) was reached while waiting for a transaction response from the vmms service.```

Can you double check Hyper-V to make sure you can not only start a VM - but also connect to it?

**Comment by ps68060** [comment]
I checked the BIOS and it shows VM is enabled.

In the Event Log it shows Hyper-V started:

'Hypervisor successfully started.'

I used Hyper-V Manager to create a new VM, I don't know if I did this correctly, I just used the wizard. 
It failed to start because "one of the Hyper-V components is not running".

**Comment by jasonbivins** [comment]
@ps68060   Let's make sure the Hyper-V VMM service is running

![image](https://user-images.githubusercontent.com/28021664/31348067-6c100894-acec-11e7-940d-dd5d42b6cf77.png)

**Comment by ps68060** [comment]
The service was running.

It tried a restart as suggested but it "did not respond in a timely fashion" and it was then left stuck in the Stopping  state. I had to reboot to get it started again.

**Comment by ps68060** [comment]
I just went back into Hyper-V Manager and today I am able to start the VM I created 
![2017-10-10 09_55 vm](https://user-images.githubusercontent.com/25297346/31377937-a32117dc-ada1-11e7-9c42-ecdf5887292c.png)

**Comment by ps68060** [comment]
Getting a bit desperate I tried to find a way to create a MobyLinux vm

C:\Program Files\Docker\Docker\resources> .\MobyLinux.ps1 -Create
Script started at 09:47:08.222
Module loaded at 09:47:09.724
Creating Switch: DockerNAT...


It just hangs there.

**Comment by dapalmi** [comment]
Any news on this? I still have the same problem. When starting Docker it never really starts. No error. No VM. I even deleted the MobyVM and did a clean install but still have the same problem.

**Comment by ps68060** [comment]
I tried netcfg -d  to see if it would delete the VM network connections but it deleted all the network config and I had to get it set-up again.

I thought docker then started a moby vm but it was the one I had created manually earlier.

I ran the autoupdate of Docker and there is no moby vm anymore.

No progress.

**Comment by ps68060** [comment]
Under Device Manager/ Network adapters I had several Hyper-V Virtual Switch Extension Adapter entries.

I removed all but the first of these, leaving just the one that was created 6/9/2017 when the original working version of Docker was installed.

**Comment by ps68060** [comment]
I also tried removing that one adapter so it would be re-created but no change.

**Comment by ps68060** [comment]
I am wondering if either a Windows policy change or a Windows update has prevented the installer from removing and creating the DockerNAT.

**Comment by adandris** [comment]
The following solved the problem in my case:

- Uninstalled Docker 17.09.0-ce-win33 (13620)
- Installed Docker 17.06.2-ce-win27 (13194)
- Restarted the computer

Before the restart, Docker still could not start. After the restart, Docker is running again. Hope this helps.

**Comment by ps68060** [comment]
Not for me, I tried that was one of the first things I tried #1148

**Comment by dapalmi** [comment]
How did you get the 17.06.2 version?

**Comment by ps68060** [comment]
Just to confirm with 13025 (my original working version)

[16:45:13.612][OptimizeDisk   ][Info   ] Optimize
[16:45:13.612][PowerShell     ][Info   ] Run script...
[16:45:13.692][Moby           ][Info   ] Stop
[16:45:13.704][HyperV         ][Info   ] Destroy
[16:45:13.704][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[16:45:13.713][HyperV         ][Info   ] Script started at 16:45:13.713
[16:45:13.731][HyperV         ][Info   ] Module loaded at 16:45:13.731
[16:45:13.793][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[16:45:13.796][HyperV         ][Info   ] Destroying Switch DockerNAT...
[16:45:13.963][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[16:45:14.231][HyperV         ][Debug  ] [destroy] took 00:00:00.5270026 to run
[16:45:14.231][Firewall       ][Info   ] Closing ports...
[16:45:14.231][Firewall       ][Info   ] Removing all existing rules...
[16:45:14.849][Firewall       ][Info   ] All existing rules are removed.
[16:45:14.849][Firewall       ][Info   ] Ports are closed
[16:45:14.849][HyperVGuids    ][Info   ] Removing GUIDs...
[16:45:14.851][HyperVGuids    ][Info   ] GUIDs removed
[16:45:14.851][HyperV         ][Info   ] Create
[16:45:14.852][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[16:45:14.861][HyperV         ][Info   ] Script started at 16:45:14.860
[16:45:14.875][HyperV         ][Info   ] Module loaded at 16:45:14.875
[16:45:14.951][HyperV         ][Info   ] Creating Switch: DockerNAT...
[16:45:33.770][SegmentApi     ][Info   ] Usage statistic: eventElectedForFeature
[16:45:33.770][SegmentApi     ][Info   ] Usage statistic: stateFeatureEnabled
[16:45:34.935][SegmentApi     ][Info   ] Usage statistic: actionMenuSettings
[16:45:39.435][FeedbackSettings][Info   ] Open logs

Docker is stuck at the Starting message.
In Hyper-V Manager there are no switches and no MobyLinux VM.

**Comment by ps68060** [comment]
@dapalmi   You can get 17.06.2 from a link in #1148

**Comment by dapalmi** [comment]
Thanks. Following steps worked for me. 
- Uninstalled Docker 17.09.0-ce-win33 
- Restarted PC
- Installed Docker 17.06.2-ce-win27 
- Restarted PC

**Comment by ps68060** [comment]
Repeated the steps above but still no luck:

[12:05:21.153][HyperVGuids    ][Info   ] GUIDs removed
[12:05:21.153][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[12:05:21.169][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385
[12:05:21.169][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385

**Comment by ps68060** [comment]
In the Win Device Manager I found a hyper-v device with no driver so I 
- uninstalled the device
- disabled hyper-v
- switch off and back on (restart seems to hang)
- enable hyper-v
- switch off and back on 

After a while Docker Settings says it is running but docker ps gives an error and I cannot open kitematic.

E4CC5ABD-2FC1-4851-8FE0-48FD97B6BC8E/2017-10-17_15-15-43

C:\WINDOWS\system32>docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by ps68060** [comment]
Something has definitely changed

E4CC5ABD-2FC1-4851-8FE0-48FD97B6BC8E/2017-10-17_15-24-44

It seems to be having a registry key issue, possibly a legacy of the failed install:

[15:22:57.493][ApiProxy       ][Info   ] Killing existing com.docker.proxy with PID 8588
[15:22:57.516][NamedPipeServer][Error  ] Unable to execute Start: Docker daemon failed with message:
Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Illegal operation attempted on a registry key that has been marked for deletion. 

    at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 198
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 78
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[15:22:57.516][NamedPipeClient][Error  ] Unable to send Start: Docker daemon failed with message:
Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Illegal operation attempted on a registry key that has been marked for deletion. 


[15:22:57.516][Notifications  ][Error  ] Docker daemon failed with message:
Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Illegal operation attempted on a registry key that has been marked for deletion.

**Comment by dapalmi** [comment]
I still get errors from daemon. But at least I can work a little bit until Docker releases a working bugfix version. They are taking their sweet time

**Comment by ps68060** [comment]
My hyper-V is broken. I can't even start the ubuntu vm I had created to check things worked.
