### ISSUE TITLE
Docker won't start after install of latest version

### ISSUE THREAD

**Issue by dawson1990** [docker/for-win#1190]
### Expected behavior
Docker to Start
### Actual behavior
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create the virtual hard disk.

The system failed to create 'C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx'.

Failed to create the virtual hard disk.

The system failed to create 'C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx': The file exists. (0x80070050).
at New-MobyLinuxVM, <No file>: line 222
at <ScriptBlock>, <No file>: line 385
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

### Information

  Diagnostic ID: B19F477B-2EA4-4237-935E-4CCAB5AC8FF8/2017-10-09_14-12-01

happens on first time use after clean install.  Have uninstalled and reinstalled to see if it was a once off error but no luck.
However runs when I 'Switch to Windows Containers', and crashes when I try switch back.

### Steps to reproduce the behavior

  1. Ran Docker for Windows installer
  2. Select Docker for Windows

**Comment by dawson1990** [comment]
Also if I delete the MobyLinuxVM it recreates it then says that it already exists

**Comment by dawson1990** [comment]
Fixed, had to uninstall Docker, disabled hyper v in features - reboot, enable hyper v in features - reboot then install Docker again and it worked
