### ISSUE TITLE
Docker not able to switch back to Hyper V, network issues when building and refusing to be stopped.

### ISSUE THREAD

**Issue by meiswjn** [docker/for-win#11923]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 745FF698-92A7-4CD9-9DDD-7E681017D7E0/20210820065904

### Actual behavior

Docker is having multiple issues for me (and plenty of other users in our company):
- When building an image from a Dockerfile the package registry cannot be reached.
- Docker occassionally freezes when building an image.
- Docker times out after disabling WSL2 and switching to Hyper V. If Docker crashed and tries to restart, the following error occurs (translated from German, as the .NET exception is in the system language):
```
System.IO.IOException: Tthe semaphore timeout period has expired

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.Threading.Tasks.Task.Execute()
--- End of stack monitoring from the previous location where the exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.NamedPipe.NamedPipeDialer.<DialAsync>d__8.MoveNext()
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.Client.DialMessageHandler.<SendAsync>d__9.MoveNext()
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.IPC.Client.<SendAsync>d__5.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Core\IPC\Client.cs:line 37.
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack monitoring from the previous location where the exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.GoBackend.GoBackendClient.<PostAsync>d__17`1.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 246.
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.GoBackend.GoBackendClient.<PushEvent>d__19.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 258.
--- End of stack monitoring from the previous location where the exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<SendState>d__22.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Engines\LinuxHyperVEngine.cs:line 154.
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStopAsync>d__19.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Engines\LinuxHyperVEngine.cs:line 118.
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__16.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Engines\LinuxHyperVEngine.cs:line 65.
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29.
--- End of stack monitoring from previous location where exception was thrown ---.
....
<20.000 more characters>
```
- When trying to get Docker Diagnostics via the UI, the following error is displayed:
`Cannot process diagnostics. Reason: Error invoking remote method 'desktop-go-backend': Error: connect ETIMEDOUT \\.\pipe\dockerBackendApiServer`
- If a freeze happens, Docker Desktop does not respect any stop commands (via the Windows icon) and keeps popping up when closed with Task Manager). 

### Expected behavior

- Before Docker started to behave like this, everything worked like a charm. 

### Information

  - Windows Version: Microsoft Windows 10 Enterprise 1909 (10.0.18363.1679)
  - Docker Desktop Version: 3.6.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No.

### Steps to reproduce the behavior

 Maybe it is the specific Windows version? This is hard to reproduce, I think. However, I am happy to test any suggestions or dev builds! Any help is greatly appreciated.

I have tried:
- Re-Installing Docker
- There is no file called panic.loc which is read-only (as written in other issues)

**Comment by meiswjn** [comment]
Another symptom: Docker does not always start up on the first try. As with the other issues, it times out:
```
For information about invoking JIT Debugging
instead of this dialog box, see the end of this message.

************** Exception text **************
System.TimeoutException: Timeout for the operation was exceeded.
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.Threading.Tasks.Task.Execute()
--- End of stack monitoring from the previous location where the exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.NamedPipe.NamedPipeDialer.<DialAsync>d__8.MoveNext()
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.Client.DialMessageHandler.<SendAsync>d__9.MoveNext()
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.IPC.Client.<SendAsync>d__5.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Core\IPC\Client.cs:line 37.
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 16.
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.LifecycleClient.<GetDockerStateAsync>d__4.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Engines\LifecycleClient.cs:line 49.
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Docker.Engines.LinuxkitDaemonStartup.<WaitAsync>d__5.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Engines\LinuxkitDaemonStartup.cs:line 60.
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__28.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 180.
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29.
--- End of stack monitoring from previous location where exception was thrown ---.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 29.
--- End of stack monitoring from the previous location where the exception was thrown ---.

<15,000 more>
```

**Comment by meiswjn** [comment]
Update: I managed to create and upload a diagnostics by downgrading to Docker 2.5.1. Docker still does not work, but I got the ID: 745FF698-92A7-4CD9-9DDD-7E681017D7E0/20210820065904

**Comment by meiswjn** [comment]
This issue was caused by McAfee.
