### ISSUE TITLE
Start up Docker desktop fail in an virtualized Windows10

### ISSUE THREAD

**Issue by tjqiulu** [docker/for-win#11941]
- [ ] I have tried with the latest version of Docker Desktop yes
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
An error occured

System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\Administrator\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

For information please visit https://aka.ms/wsl2-install

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 77
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__28.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 180
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

### Information

  - Windows Version: Windows10
  - Docker Desktop Version:3.6.0
  - WSL2 or Hyper-V backend?  yes
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:Yes, an Windows10 vm

### Steps to reproduce the behavior

  1. enable Hyper V in contro panel
  2. Install the Docker desktop
[Uploading service.txt…]()

  3. startup the Docker [desktop]()

**Comment by StefanScherer** [comment]
Thank you for the report. Unfortunately Docker Desktop is not supported in a virtualised environment (see https://docs.docker.com/desktop/windows/install/#whats-included-in-the-installer and https://docs.docker.com/desktop/windows/troubleshoot/#running-docker-desktop-in-nested-virtualization-scenarios). It's out of our control whether it works or not: it depends whether the outer hypervisor can fully run Hyper-V or WSL 2. Sometimes enabling nested virtualisation in the outer hypervisor makes it work, but there are no guarantees.

**Comment by aleksandaratanasov** [comment]
Just a comment for @StefanScherer;

I am running RHEL 8.4 with KVM and enabled nested virtualization and Win10 Pro VM on top. I was able to successfully install Ubuntu 20.04 as a WSL package and it works. However Docker does not even though it is instructed to use WSL2. I agree that to some extent the underlying hypervisor is responsible for what can be nested, however the fact that some thing work and Docker doesn't should perhaps also indicate an issue with Docker itself. The matter of fact is in my case I cannot enable Hyper-V platform (although services and tools can???) on my Win10 VM. However given that Docker is supposed to be accessible on Win10 **Home** (not **Pro**), where Hyper-V is not provided, this setup should work.
