### ISSUE TITLE
Docker desktop 3.6.0 crashes switching to windows containers

### ISSUE THREAD

**Issue by shaunmlowry** [docker/for-win#11954]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 02714274-6C30-4CA8-B88C-877E7CCB7357/20210820170611

### Actual behavior
"An error occurred" pop-up appears when attempting to switch to Windows containers from a fresh install with the following log:
```System.ServiceProcess.TimeoutException:
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\master-merge\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 208
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

### Expected behavior
Windows containers are available for execution after selecting "Switch to windows containers"

### Information
This is a new problem since upgrading to 3.6.0.  Uninstalling, rebooting and reinstalling does not solve the issue.

  - Windows Version: Windows 10 Pro 21H1 build 19043.1165
  - Docker Desktop Version: 3.6.0
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: on bare metal

### Steps to reproduce the behavior

  1. Install Docker Desktop 3.6.0 on windows 10
  2. Start Docker Desktop
  3. Select "Switch to windows containers" from the tray app

**Comment by EniShima** [comment]
The same issue also for me with the new version of docker . After it was updated , it crash when i swich to windows containers

**Comment by StefanScherer** [comment]
Thanks for the report. We‘re working on a fix. In the meantime have a look at  #11899 which has a workaround to make the panic.log file writable. I‘ll close this ticket as it‘s a duplicate.
