### ISSUE TITLE
Windows Docker failed after update

### ISSUE THREAD

**Issue by quick691fr** [docker/for-win#1196]
### Expected behavior

Docker starts as normal

### Actual behavior

Docker failed with error message :

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.
at New-MobyLinuxVM, <No file>: line 201
at <ScriptBlock>, <No file>: line 385
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

There is no more MobyLinux VM in Hyper-V, it just disapeared.

### Information

Diagnostic ID : 01375334-896D-43C3-8732-C967CE388B26/2017-10-10_12-04-10
Windows Edition : Windows 10 Pro
Windows Version : 1703
Windows OS Build : 15063.608

I tried to reset Docker but it didn't reinstall the MobyLinux VM into Hyper-V

### Steps to reproduce the behavior

Upgrade Docker for Windows to the lastest version after asking for update : 

Version 17.09.0-ce-win33 (13620)
Channel: stable
8c56a3b

**Comment by jasonbivins** [comment]
Hi @quick691fr 
Let's create it manually to see if you get a more specific error
```powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create```
