### ISSUE TITLE
Documentation or self diagnosis can't find 'check'

### ISSUE THREAD

**Issue by robtrooper** [docker/for-win#11971]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:70604451-AA4E-495C-9D49-62D228DB6704/20210823094248

### Actual behavior
Ran in-app Docker update and restarted then Docker-Desktop fails to run Engine. Reports 'Docker Engine stopped...'

### Expected behavior
For Docker-Desktop to run Engine and containers after an update.

### Information

  - Windows Version: Windows 10 Pro, 21H1, 19043.1165
  - Docker Desktop Version: Latest update. Unable 
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: Bare metal.

### Steps to reproduce the behavior
Unable to run Docker-Desktop engine.

  1. Update Docker-Desktop from Docker-Desktop
  2. run:$ docker container ls
  3. reports: 'error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.'

Not sure if re-installing Docker-Desktop will fix this?
  
Edited to add.
Also followed the https://docs.docker.com/desktop/windows/troubleshoot/ steps.
Got upto 
PS C:\> & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
Which reported 
'"check" is not valid command.'
Which was strange as i had just ran 
 & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" gather -upload
Without issue. I guess 'check' has been deprecated, although the troubleshooting steps still recommend it.

Also tried
$ detect-host-hypervisor
time="2021-08-23T11:09:44+01:00" level=info msg="Executing: [powershell -NoProfile -Command &{ $(Get-WmiObject Win32_ComputerSystem) | ConvertTo-json -Depth 1 }]"
time="2021-08-23T11:09:45+01:00" level=info msg="Executing: [powershell -NoProfile -Command &{ $(Get-WmiObject Win32_BaseBoard) | ConvertTo-json -Depth 1 }]"
unknown

Which suggests that Hyper-V is not running/working?

tested this with 
$ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
Path          :
Online        : True
RestartNeeded : False

When i try to restart Docker-Desktop or start Docker-Desktop i get an Error: Failed to start and a crash report.

Docker.Core.BackendAPI.ServiceNotInstalledException:
Docker Desktop service is not installed
   at Docker.Core.BackendAPI.BackendAPIPipeResolver.<ResolvePipeAsync>d__5.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIPipeResolver.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<CreateSystemHttpClientAsync>d__3.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<UpdateHostsAsync>d__5.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__14.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<RestartAsync>d__26.MoveNext() in C:\workspaces\PR-16070\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 266

**Comment by robtrooper** [comment]
I did reinstall Docker-Desktop 3.6 and all worked. The update was 3.6 too. I guess the update failed the first time.
There were some Docker related services still running that i had to end before being able to start the install.
