### ISSUE TITLE
System.NullReferenceException when right click on docker icon > About docker.

### ISSUE THREAD

**Issue by dungtri** [docker/for-win#1199]
I upgraded Docker for Windows to 17.09.0-ce-win33. And when do a right click on docker icon I only have one item "About docker" on the context menu. 

Beside, using command line on a windows bash console, I can manage my images and pull image without any problems.

When I click on it I got this exception : 

System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Docker.Core
  StackTrace:
       at Docker.Core.ExperimentalFeatures.Fixup(String name, String trackingId, ExperimentalFeature feature) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\ExperimentalFeatures.cs:line 252
       at Docker.Core.ExperimentalFeatures.Get(String name) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\ExperimentalFeatures.cs:line 234
       at Docker.WPF.AboutBox.OnActivated(EventArgs e) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\AboutBox.xaml.cs:line 41
       at System.Windows.Window.WmActivate(IntPtr wParam)
       at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
  InnerException:

**Comment by jasonbivins** [comment]
Hi @dungtri 
It looks like there might be a problem with one of the Experimental features - lets disable them manually to see if that helps.
Go to c:\programdata\docker\config and look for a Daemon.json file
edit the experimental entry to say false - like this ``` "experimental": false ```

**Comment by dungtri** [comment]
On my windows 10, Daemon.json is located on %USER_PROFILE%\.docker. I try to set "experimental": false but it doesn't change anything. The feature list injected on the About view seem to be empty.

**Comment by aburleigh94** [comment]
I'm seeing this issue on both stable and edge builds of Docker for Windows. Have edited the file in both locations but neither seemed to make any difference.

**Comment by DianneLovell456** [comment]
I'm getting the same issue.  I've tried installing different versions, but with no success.  I'm about to give up on Docker on windows - I've been fooling around with this for a few weeks.

**Comment by janakaeranda** [comment]
I faced the same issue and almost gave up docker on windows. But I manage to install latest edge version(18.03.0-ce-rc1-win54 (16164) and looks like it's fixed this issue.

**Comment by jllavin77** [comment]
Hello everybody,

My docker in windows installation has started failing due to the following error:

Unable to create an instance of Docker.App: Unable to create an instance of Docker.WPF.AboutBox
   at Docker.Core.di.Singletons.NewInstance(Type type, Int32 depth)
   at Docker.Core.di.Singletons.Get(Type type, Int32 depth)
   at Docker.Core.di.Singletons.Get[T]()
   at Docker.Program.Run(IReadOnlyCollection`1 args)

Taking a look at the logs, here is what I get:

Version: 18.03.1-ce-win65 (17513)
Channel: stable
Sha1: 
Started on: 2018/09/20 11:46:28.022
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro for Workstations
Edition: ProfessionalWorkstation
Id: 1709
Build: 16299
BuildLabName: 16299.637.amd64fre.rs3_release_svc.180808-1748
File: C:\Users\jllavin\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:46:28.272][GUI            ][Info   ] Starting...
[11:46:29.507][SegmentApi     ][Info   ] Not tracking: appLaunched
[11:46:30.507][SegmentApi     ][Info   ] Usage statistic: heartbeat
[11:46:30.538][SegmentApi     ][Info   ] Usage statistic: Identify
[11:46:30.616][GUI            ][Error  ] Unable to create an instance of Docker.App: Unable to create an instance of Docker.WPF.AboutBox
[11:58:25.067][ErrorReportWindow][Info   ] Open logs


Any help would be appreciated, I'd rather not go back to the old VBox days...so please, give me a hand.

Best 

JL

**Comment by helzgate** [comment]
Not that you guys probably didn't already try this but posting this just in case.  I had this same issue.  

To fix it I did the following:
* I disabled virus protection
* unintalled Docker
* restarted computer
* disabled virus protection
* reinstalled Docker.
