### ISSUE TITLE
MobyLinuxVM' failed to realize- Fails to find path specified configuration store and path specified

### ISSUE THREAD

**Issue by mchalep** [docker/for-win#1200]
### Expected behavior
Start Docker without error

### Actual behavior
MobyLinuxVM' failed to realize- Fails to find path specified configuration store and path specified.

### Information

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.

'MobyLinuxVM' failed to realize. (Virtual machine ID 2FDE4F33-8AA5-4D80-B359-A3EF6AA90F41)

Failed to access configuration store: The system cannot find the path specified. (0x80070003).
at New-MobyLinuxVM, <No file>: line 201
at <ScriptBlock>, <No file>: line 385
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(Strin

### Steps to reproduce the behavior
  1. ...Start Docker CE for Win
  2. ...

**Comment by mchalep** [comment]
This is a Windows 10 Enterprise edition machine running Docker CE for Windows with HypeV - cleanly installed. Cannot find a reason why this does not work. Would like to try an older version of Docker CE for Windows but that isn't possible, as not available anywhere. Mystery to me why this is not working. Should have just installed and run without a problem, which is what I had expected.

**Comment by mchalep** [comment]
Version: 17.09.0-ce-win34 (13622)
Channel: edge
Sha1: 9171a03f452387240b4484d394ee3f3f66f1e3f0
Started on: 2017/10/11 16:57:02.807
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.1593.amd64fre.rs1_release.170731-1934
File: C:\Users\patrick.mchale\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[16:57:02.932][GUI            ][Info   ] Starting...
[16:57:03.703][Tracking       ][Info   ] Crash report and usage statistics are enabled
[16:57:03.703][SegmentApi     ][Info   ] Usage statistic: appLaunched
[16:57:05.409][NPS            ][Info   ] NPS user ceated on :10/10/2017 12:41:04 PM -07:00, last survey : 1/1/0001 12:00:00 AM +00:00
[16:57:05.409][SegmentApi     ][Info   ] Usage statistic: heartbeat
[16:57:05.409][SegmentApi     ][Info   ] Usage statistic: Identify
[16:57:05.503][NamedPipeClient][Info   ] Sending Version()...
[16:57:05.518][NamedPipeClient][Info   ] Received response for Version
[16:57:05.518][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[16:57:05.518][NamedPipeServer][Info   ] Version done in 00:00:00.
[16:57:05.518][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
[16:57:05.518][PowerMode      ][Info   ] Stop
[16:57:05.518][HyperV         ][Info   ] Stop
[16:57:05.518][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[16:57:05.534][HyperV         ][Info   ] Script started at 16:57:05.534
[16:57:05.549][HyperV         ][Info   ] Module loaded at 16:57:05.549
[16:57:05.565][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[16:57:05.565][HyperV         ][Debug  ] [stop] took 00:00:00.0468778 to run
[16:57:05.565][OptimizeDisk   ][Info   ] Optimize
[16:57:05.565][PowerShell     ][Info   ] Run script...
[16:57:05.581][Moby           ][Info   ] Stop
[16:57:05.581][PowerMode      ][Info   ] Start
[16:57:05.581][HyperV         ][Info   ] Create
[16:57:05.581][HyperVGuids    ][Info   ] Installing GUIDs...
[16:57:05.581][Firewall       ][Info   ] Removing all existing rules...
[16:57:05.581][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride C:\Users\Public\HyperV\MobyLinuxVM.vhdx -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[16:57:05.581][HyperVGuids    ][Info   ] GUIDs installed
[16:57:05.596][HyperV         ][Info   ] Script started at 16:57:05.596
[16:57:05.612][HyperV         ][Info   ] Module loaded at 16:57:05.612
[16:57:05.690][HyperV         ][Info   ] Creating Switch: DockerNAT...
[16:57:05.893][Firewall       ][Info   ] All existing rules are removed.
[16:57:05.893][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[16:57:05.909][Firewall       ][Info   ] Opening ports for SMB...
[16:57:05.940][Firewall       ][Info   ] Ports are opened
[16:57:07.471][HyperV         ][Info   ] Switch created.
[16:57:10.289][HyperV         ][Info   ] Set IP address on switch
[16:57:10.304][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[16:57:10.476][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.

'MobyLinuxVM' failed to realize. (Virtual machine ID 1CD57E3A-E9B7-4349-BB04-8671EF0E6AE7)

Failed to access configuration store: The system cannot find the path specified. (0x80070003).
at New-MobyLinuxVM, <No file>: line 201
at <ScriptBlock>, <No file>: line 385. Let's retry

**Comment by mchalep** [comment]
Problem Sorted:    Registry item had incorrect path in:
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization].
To Fix: DefaultExternalDataRoot modified to point to C:\Users\Public\HyperV\
To Fix: DefaultVirtualHardDiskPath also modified to point to C:\Users\Public\HyperV\

**Comment by tsasioglu** [comment]
Thanks @mchalep, I had some old paths someone had configured in those 2 keys. I just deleted them and docker picked up the correct paths.

**Comment by ppotter100** [comment]
For me, the access settings for the c:\Users\Public\Public Documents\ folder, were somehow limited for Virtual machine. Probably due to my companies policy. Check it to "full control" for Virtual Machines and the problem was solved.

**Comment by TheBoneJarmer** [comment]
Problem solved thanks to both ppotter100 and mchalep. I gave the folder **C:\Users\Public\Documents\Hyper-V** full control rights for the user **Virtual Machines** and I changed my registry keys like this:
**DefaultExternalDataRoot**: C:\Users\Public\Documents\Hyper-V\Config\
**DefaultVirtualHardDiskPath**: C:\Users\Public\Documents\Hyper-V\Disks\
