### ISSUE TITLE
TimeoutException when Docker Engine starting after update to 4.0.0

### ISSUE THREAD

**Issue by nikinsider** [docker/for-win#12073]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F5D6A982-8F7B-455F-95E8-67EA57D982B2/20210903094543

### Actual behavior
TimeoutException when Docker Engine starting

### Information

  - Windows Version: Windows 10 Enterprise 10.0.18363 Build 18363
  - Docker Desktop Version: 4.0.0 (67817)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Start Docker Desktop
  2. Error:
  System.ServiceProcess.TimeoutException:
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 210
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

**Comment by nikinsider** [comment]
An additional note. I updated Docker Desktop to 4.0.0 on 2 machines.
During the update process the new terms were displayed with both a checkbox and an Agree button.
On the first (the machine that has the error) I didn't select the checkbox, just pressed the Agree button.
On the second machine, I noticed the checkbox and checked it before pressing the Agree button.
May not be relevant but there you go.

**Comment by stephen-turner** [comment]
Hmmm, the Agree button should be greyed out until you check the checkbox. I've just tested it again, and I can't click it until I've checked the checkbox.

**Comment by nikinsider** [comment]
Apologies, sounds like I am mistaken about the checkbox.
I just remember when I was updating the second machine, I couldn't recall seeing the checkbox.

**Comment by gitvadim** [comment]
I have the same problem. I need to zap the docker data-root folder then it works, but only until I restart the machine docker is running on.

**Comment by soroshsabz** [comment]
ITNOA

I have the same problem

related to #12066

**Comment by nikinsider** [comment]
> ITNOA
> 
> I have the same problem
> 
> related to #12066

Thanks for the link to the related issue.
The following suggestion fixed the issue for me (see here: https://github.com/docker/for-win/issues/12066#issuecomment-921170876)

Quoting it here:
"Just to let you know, that it seems like the "settings" file is corrupt. If you delete the %appdata%\Docker\settings.json and restart docker, then it work again."
