### ISSUE TITLE
Install of docker 4.0.0 fails on Windows 10, WSL 2

### ISSUE THREAD

**Issue by jlbradley1844** [docker/for-win#12080]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Uninstalled docker desktop some time ago (last year I believe).

Now installing docker desktop 4.0.0 and getting this error:

Component CommunityInstaller.EnableFeaturesAction failed: Not found 
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

this appears after running installer for 5+ minutes

### Expected behavior

Install it and work

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

Windows 10, WSL2, bare metal on surface 4.

I've attempted installed twice, same issue both times

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mrtolkien** [comment]
Same bug and error here

**Comment by tr3pan** [comment]
Here is my 5 cents:
I got the same error today. I tried 3.6.0 installation and the installation failed again. The curious part is I had docker installed and I didn't have problem with the installation. There are a lot of fixes for this error, but mine was broken WMI repository and I had to rebuild it. At least for me I tried to run `systeminfo` and I got error `Loading Operating System Information ...ERROR: Invalid class`. After I rebuild the WMI repository, `systemfinfo` worked and the docker installation finished successfully.

**Comment by jlbradley1844** [comment]
OK I did the following:
- cleaned out my old docker folders (c:\ProgramFiles\Docker, c:\app\UserData\Local\Docker, etc.)
- reinstalled. It finished reinstallation, but when I ran, nothing happened
- uninstalled
- reinstalled again.
Now it starts, but it crashes during startup. No errors. If .I launch from powershell, there is no output to standard output or error.

Windows event log reports a crash: I get the following two errors in the application logs every time I attempt to run

first error:

Log Name:      Application
Source:        .NET Runtime
Date:          9/6/2021 9:49:36 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      JOES-SURFACE4
Description:
Application: Docker Desktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Management.Infrastructure.CimException

Exception Info: Docker.Core.HttpBadResponseException
   at Docker.Core.Logging.HttpClientExceptionInterceptor+<InterceptResponseAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.IPC.Client+<SendAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__58.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.BackendAPI.ServiceAPIClient+<UpdateHostsAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.TaskExtension+<Forget>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-09-07T01:49:36.2213894Z" />
    <EventRecordID>48117</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>JOES-SURFACE4</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: Docker Desktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: Microsoft.Management.Infrastructure.CimException

Exception Info: Docker.Core.HttpBadResponseException
   at Docker.Core.Logging.HttpClientExceptionInterceptor+&lt;InterceptResponseAsync&gt;d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.IPC.Client+&lt;SendAsync&gt;d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Net.Http.HttpClient+&lt;FinishSendAsyncBuffered&gt;d__58.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.BackendAPI.ServiceAPIClient+&lt;UpdateHostsAsync&gt;d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.Core.TaskExtension+&lt;Forget&gt;d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

</Data>
  </EventData>
</Event>


second error:
Log Name:      Application
Source:        Application Error
Date:          9/6/2021 9:49:36 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      JOES-SURFACE4
Description:
Faulting application name: Docker Desktop.exe, version: 4.0.0.0, time stamp: 0x9462d2a8
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1202, time stamp: 0xc9db1934
Exception code: 0xe0434352
Fault offset: 0x0000000000034f99
Faulting process id: 0x3a6c
Faulting application start time: 0x01d7a38a987c1d23
Faulting application path: C:\Program Files\Docker\Docker\Docker Desktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 12bf786a-c335-410c-a8ef-3b2094e27155
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-09-07T01:49:36.4700032Z" />
    <EventRecordID>48118</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>JOES-SURFACE4</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Docker Desktop.exe</Data>
    <Data>4.0.0.0</Data>
    <Data>9462d2a8</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.1202</Data>
    <Data>c9db1934</Data>
    <Data>e0434352</Data>
    <Data>0000000000034f99</Data>
    <Data>3a6c</Data>
    <Data>01d7a38a987c1d23</Data>
    <Data>C:\Program Files\Docker\Docker\Docker Desktop.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>12bf786a-c335-410c-a8ef-3b2094e27155</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

I'll re-download and attempt again. I would -hope- that the installer for such a large program would have a checksum to prevent it from installing bad downloads, but not sure what else to try.

**Comment by jlbradley1844** [comment]
re-download does nothing, appears the image is good

**Comment by A13x3i** [comment]
Shout out to @tr3pan ! Spent a day trying to figure it out. Please check to see if your windows 
`systeminfo` can run and check if your wmi is ok by running: 
1. `wmimgmt` 
2. Click on WMI Control(Local) > Properties and check General Tab for any errors ( I had class errors but there could be problems with namespaces etc)
3. Depending on your problem google the solution

For me wmi repository wasn't corrupted so rebuilt wasn't necessary , you can check this by running `winmgmt /verifyrepository` and see if its consitent or not.

my problem was WMI: Invalid Class  so I had to reregister/recompile all mof classes.
`CD C:\Windows\System32\WBEM dir /b *.mof *.mfl | findstr /v /i uninstall > moflist.txt & for /F %s in (moflist.txt) do mofcomp %s` 

Docker 4.0.0 wls2 installed like a charm after this

**Comment by jlbradley1844** [comment]
well, I thought that would be the issue. Sure enough, my WMI was messed up, I followed these instructions (http://woshub.com/wmi-troubleshooting/). A big raspberry for Microsoft, which has pulled support for their WMI utility and has nothing but out-of-date help information on their normally useful technical website.

Unfortunately, fixing WMI had no effect. I still see the same thing
- if I install and select the installation for WSL2, it crashes on installation
- if I skip the WSL2 install (I already have a working WSL2) I install docker desktop, but it crashes on startup after accepting the licensing.

**Comment by A13x3i** [comment]
@jlbradley1844 so your WMI Control > Properties> General show valid system info and no errors? I had the same problem if i install it without WSL2..it would start up and then crush with same error as in your original post. Fixing WMI allowed me to install..had wsl2 setup and running prior to docker install, same as you did.

**Comment by jlbradley1844** [comment]
Hmm my bad. I did a repair per the addressed article, and after doing so things seemed to work ok, but now that I look more, I still have errors. Let me try your command line before I rebuild the whole thing (yuk).

**Comment by johanmattssonm** [comment]
Hi. I believe I ran into this problem as well when installing 4.0.1.

![image](https://user-images.githubusercontent.com/350392/133839607-a6ae1f59-026d-4c75-9204-7f2022513b1a.png)

```
PS C:\WINDOWS\system32> winmgmt /verifyrepository
WMI repository is consistent
```

I got this error when trying to run the suggested command above in a PowerShell:

At line:1 char:88
+ ...  dir /b *.mof *.mfl | findstr /v /i uninstall > moflist.txt & for /F  ...
+                                                                 ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quot
ation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed

Please clarify this if you know how to fix it.
Cheers

**Comment by A13x3i** [comment]
@johanmattssonm Hey, yep instead of dir part  try 
`CD C:\Windows\System32\WBEM; ls *.mof | findstr /v /i uninstall > moflist.txt & for /F %s in (moflist.txt) do mofcomp %s` I had exact same error

**Comment by johanmattssonm** [comment]
👍

**Comment by christopherbauer** [comment]
I was able to get the installer to run by unticking the WSL installer, however docker desktop is crashing still.

**Comment by halinwu** [comment]
I have a same problem, pls following the step fix them. 
1. Stop Docker service; 
2. delete the docker config file(config.json and daemon.json),  they are located c:\users\{Username}\.docker\
3. restart Docker services; 
4. re-lunch docker desktop.exe
