### ISSUE TITLE
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Modifying the properties of the device 'Memory' failed.

### ISSUE THREAD

**Issue by jecot** [docker/for-win#1209]
### Expected behavior
Docker starts normally

### Actual behavior
Docker throws an error and can't start

### Information
468650FA-BB4D-4F09-B388-D9D0D6DDC67C/2017-10-12_08-48-19

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Modifying the properties of the device 'Memory' failed.

The operation cannot be performed while the object is in its current state.
at New-MobyLinuxVM, <No file>: line 216
at <ScriptBlock>, <No file>: line 385
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

Windows version: Windows 10 Pro 1703 build 15063.608
Docker version: Docker CE 17.09.0-ce-win33 (13620) Channel: stable 8c56a3b

**Comment by jecot** [comment]
I did try a few vain solutions mentionned in 
https://github.com/docker/for-win/issues/27
https://github.com/docker/for-win/issues/390

**Comment by jasonbivins** [comment]
Hi @jecot 
It looks like the MobyLinuxVM is stuck.  According to the logs, it is still in use, but has the number zero for assigned memory.  Can you try deleting it using your Hyper-V manager?  
You can also try this in Powershell
``` powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -destroy ```

**Comment by jecot** [comment]
Thanks @jasonbivins for helping out.

I've already tried that, with no positive results. The same error is thrown back.
I ended up installing Docker tools instead of running Docker natively on my windows machine (and it worked right off the bat) but this issue still needs to be addressed.
