### ISSUE TITLE
Docker self-diagnose tool hangs after DD0012

### ISSUE THREAD

**Issue by BePo65** [docker/for-win#12108]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 374F0BEE-826D-41F5-B516-1F166C3ADD87/20210909045402

### Actual behavior
Running the self-diagnose tool as recommended to trace my issue #12026, the tool never returns to the command prompt after the step [DD012]

### Expected behavior
The documentation in 'https://docs.docker.com/desktop/windows/troubleshoot/#experimental-self-diagnose-tool' says 'If there are any failures, it highlights the most relevant at the end'. Therefore I expect that there is an end (for me this should be 'the command prompt reappears').

Ideally the tools would give me a hint, what `[FAIL] DD0028: is there available VM disk space? exit status 1` means.

### Information
  - Windows Version: Windows 10 Pro 21H1
  - Docker Desktop Version: 4.1.0
  - WSL2 or Hyper-V backend?   Hyper-V backend
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: plain Acer notebook

### Steps to reproduce the behavior
Running in powershell 5.1 (`& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`)
or
Running in windows terminal (`"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`)
in both cases with elevated rights, results in:
```
time="2021-09-09T06:50:41+02:00" level=info msg="ipc.NewClient: d72f91bf-com.docker.diagnose -> \\\\.\\pipe\\dockerBackendV2 com.docker.service.exe [[STACK]]goroutine 1 [running, locked to thread]:\ngithub.com/docker/pinata/win/backend/pkg/service.NewClientForPath(...)\n\tC:/workspaces/master-merge/src/github.com/docker/pinata/win/backend/pkg/service/service.go:26\ngithub.com/docker/pinata/win/backend/pkg/service.NewClient(...)\n\tC:/workspaces/master-merge/src/github.com/docker/pinata/win/backend/pkg/service/service.go:20\ngithub.com/docker/pinata/common/pkg/diagkit/gather/diagnose.init()\n\tC:/workspaces/master-merge/src/github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x175\n"
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[FAIL] DD0028: is there available VM disk space? exit status 1

[PASS] DD0003: is the Docker CLI working?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0020: is the Hyper-V Windows Feature enabled?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?     <------ nothing happens after here ------

```

**Comment by BePo65** [comment]
Just an additional information:
If i run the docker desktop for windows diagnose, then the generated data contains a file named 'self-diagnose.txt' and the content looks like a run of the self-diagnose-tool, but with the expected 'recommendation' at the end.
Is it possible that I have a problem with my windows environment?

**Comment by aiordache** [comment]
Hi @BePo65. Can you run this powershell command please? 
```
 Get-DiskImage C:\Users\<username>\AppData\Local\Docker\wsl\distro\ext4.vhdx | Select-Object -Property FileSize, Size | ft -hidetableheaders
```
It's the command run by the VM disk check.

**Comment by jrobbins-LiveData** [comment]
I'm experiencing a hang (also on Windows)

**Comment by BePo65** [comment]
The folder 'C:\Users\<username>\AppData\Local\Docker\wsl\distro\' on my system is empty.
Can it be, that this is because i switched my pc to wsl2?
