### ISSUE TITLE
Docker Engine failed to start is still in 4.0.1

### ISSUE THREAD

**Issue by soroshsabz** [docker/for-win#12158]
ITNOA

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5BCDC324-A8CA-44F2-9CDA-DE2A62E609EB/20210917073242

### Actual behavior

```
System.ServiceProcess.TimeoutException:
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\PR-16360\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 210
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

### Expected behavior

Work correctly with current specific `data-root` (that exist with Docker Desktop 3.6)

### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible? Yes
  - Is the problem new? No, from version 4.0.0 related to #12066
  - Did the problem appear with an update?  No (but this problem is occur when I install new [Windows Cumulative Update  2021/09](https://support.microsoft.com/en-us/topic/september-1-2021-kb5005101-os-builds-19041-1202-19042-1202-and-19043-1202-preview-82a50f27-a56f-4212-96ce-1554e8058dc1)

  - Windows Version: Windows 10 Version 21H1 (OS Build 19043.1237)
  - Windows Feature Experience Pack: 120.2212.3530.0
  - Docker Desktop Version: 4.0.1
  - WSL2 or Hyper-V backend?   I use Windows Container (but WSL 2 based engine is enable in setting)
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

My docker settings like below

```
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": false,
  "experimental": false,
  "data-root": "N:/Docker"
}
```

### Steps to reproduce the behavior

  1. Try to run Docker Desktop
  2. Docker Desktop try to start Docker Engine
  3. Docker Engine failed to start after couple of minutes
  4. I cannot do anything :(

**Comment by soroshsabz** [comment]
related to #12066

**Comment by soroshsabz** [comment]
@mat007 Did you need any more info to start resolving this issue?

**Comment by soroshsabz** [comment]
Any update or workaround?
