### ISSUE TITLE
Docker fails to start with WSL backend

### ISSUE THREAD

**Issue by joshschmitter** [docker/for-win#12165]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 44F0958C-F48E-428F-92D3-F970E85D926C/20210917215350

### Actual behavior
After a brand-new install of Docker Desktop, it fails to start when using the WSL backend.  "Docker Engine Failed to start...".
`Docker.Engines.WSL2.WSL2ErrorFoundInLogsException: Error found in logs indicating startup will most likely fail: Error creating 000-metadata: exit status 1`

<details>

```

Docker.Engines.WSL2.WSL2ErrorFoundInLogsException:
Error found in logs indicating startup will most likely fail: Error creating 000-metadata: exit status 1
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__28.MoveNext() in C:\workspaces\PR-16360\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 180
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-16360\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16360\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-16360\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

```
</details>

### Expected behavior
Docker starts up.

### Information

  - Windows Version: Windows 10 Enterprise (19043.1237)
  - Docker Desktop Version: 4.0.1.68347
  - WSL2 or Hyper-V backend? 
     - Only WSL2 is problematic.  Hyber-V works fine.
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Download Docker MSI
  2. Install with default settings (select WSL backend)
  3. Start Docker and wait for it to crash.

**Comment by joshschmitter** [comment]
For some reason this issue disappeared.  I had already tried reboots as part of my previous troubleshooting, so that in itself couldn't have been the solution.
