### ISSUE TITLE
Manifest extraction failed: Could not find Windows Runtime type 'Windows.Data.Json.JsonObject'

### ISSUE THREAD

**Issue by tapika** [docker/for-win#12178]
While attempting to install docker desktop on Windows 7 machine - installer reports following error:

```
Manifest extraction failed: Could not find Windows Runtime type 'Windows.Data.Json.JsonObject'.
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

Is it so that Windows 7 is not supported anymore by Docker desktop ?

Virtual box at least seems to support Windows 7 on some level:

https://www.virtualbox.org/manual/UserManual.html#table-limited-support

P.S. For making own installer it's possible to use `ReadyToRun` technology in case if you don't want to go deeper with C++.

**Comment by apgeo** [comment]
Docker for Windows is not supported on Windows 7, minimal requirement is Windows 10.
As per: https://forums.docker.com/t/docker-stable-installer-not-running-windows-7/38622/2

Or you can use older Docker Toolbox:
https://github.com/docker-archive/toolbox/releases

**Comment by xiejun946** [comment]
i get this issue  too at windows 7

**Comment by mattjaf** [comment]
got the same issue...

**Comment by theking2** [comment]
I get this issue on Windows 11 build 22621.1105

**Comment by sandeepkunkunuru** [comment]
I get this issue on Windows 11 Pro build 22000.1696

**Comment by NorbertSandor** [comment]
I have this issue on Windows 11 build 22621.1413 :(

**Comment by RussianDjoNIK** [comment]
I've just got the same error on Windows 10 build 19045.2788.
During installing Docker Desktop 4.17.1 (101757)

**Comment by morningscifi** [comment]
Docker Desktop installation fails on Windows 10 build 19045.2728 with message:



```
Manifest extraction failed: Operation did not complete successfully because the file contains a virus or potentially unwanted software.

   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```
