### ISSUE TITLE
Unable to change location of Docker images

### ISSUE THREAD

**Issue by nijel91** [docker/for-win#1223]
### Expected behavior
I should be able to switch default location for Docker images on my local host. For example, if my C: drive is getting full, I should be able to switch from C:/ProgramData/Docker to D:/Docker.
### Actual behavior
Reading thread #185 I edited daemon.json file. It now looks as follows:

{"registry-mirrors":[],"insecure-registries":[], "debug":true, "experimental": true}
{"graph": "D:\\Docker"}

However, Docker fails to restart after this change. I get the error message below:

### Information

  Additional text encountered after finished reading JSON content: {. Path '', line 2, position 0.
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Docker.Backend.Processes.WindowsDaemonJsonRewriter.RewriteOptions(String daemonOptions, String userName) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 27
   at Docker.Backend.Processes.WindowsDockerDaemon.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 109
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 200
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 78
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

### Steps to reproduce the behavior

  1. Edit daemon.json file with above mentioned change
  2. Quit and start Docker for Windows CE Version 17.09.0-ce-win33 (13620) Channel: stable 8c56a3b

Am I doing something wrong? Any help is greatly appreciated!
Thank you.

**Comment by Blueve** [comment]
Try this:
{"registry-mirrors":[],"insecure-registries":[], "debug":true, "experimental": true, "graph": "D:\\Docker" }

**Comment by nijel91** [comment]
Ah! Thank you! My mistake was to make it a separate line. I should have just added it to the original parameters.
Thank you for your help, @Blueve!

**Comment by kiahmed** [comment]
this still doesn't work on my machine...added as above but always fails. How could you get it to work guys?

**Comment by 8thHalfHour** [comment]
This is not working for me in Stable (v2.0.0.3). It is working in Edge (v2.0.5.0), though it keeps asking me to "Apply" my changes, so technically, that is not working as expected, either. Any work-around for Stable?

**Comment by 8thHalfHour** [comment]
Just got the same issue from Edge. 

`No activity detected on VM, aborting
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendServer.<Run>b__8_5(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)`

This occured when I applied the code `"graph": "G:\\AllContent\\VM\\DI"` to the daemon. Crash report ID: 8728FAE4-349C-40EB-A403-46CF2CBD6AD1/20190724020508.

Any thoughts on this issue?
