### ISSUE TITLE
Docker times out when multiple containers / networks are running during Windows boot, works fine when reset to factory defaults

### ISSUE THREAD

**Issue by arekkas** [docker/for-win#1225]
### Expected behavior

When booting Windows 10, Docker should boot up regularly.

### Actual behavior

When resetting Docker or running just a few containers, Docker boots up just fine when booting Windows. However, when I'm running a docker-compose environment that includes ~10 images and two networks, Docker times out during boot.

Quitting Docker and then restarting it helps, but I see some quirky errors after a while - for example issues with log output or network connectivity inside my containers.

### Information

This is the error message I see:

![image](https://user-images.githubusercontent.com/3372410/31783762-b5728ee2-b4ff-11e7-9966-649b1f348526.png)

```
Docker command did not complete within the allowed timeout. Output: 
   at Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 152
   at Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 49
   at Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 197
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 168
   at Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 65
   at Docker.Backend.BackendServer.<Run>b__6_10(Object[] args) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\BackendServer.cs:line 52
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

Docker logfile: https://gist.github.com/arekkas/dc899d32f120cd07747922f2eb93511d

Diagnostics ID: 5A9CCCEE-6F44-4976-BB34-0757BE42887C/2017-10-19_19-00-48

Windows:

![image](https://user-images.githubusercontent.com/3372410/31783904-2527ce28-b500-11e7-8568-7d1510f6c18c.png)

### Steps to reproduce the behavior

Unfortunately, the docker-compose set up is not public as it builds a lot of stuff from source...

**Comment by arekkas** [comment]
Here some info on my docker environment:

```
$ docker ps -a
CONTAINER ID        IMAGE                                            COMMAND                  CREATED             STATUS                          PORTS                    NAMES
6c3d8469725f        compose_management-consent-app                   "/bin/sh -c 'yarn ..."   28 hours ago        Up About a minute               3000/tcp                 compose_management-consent-app_1
4b76919130b9        oryd/oathkeeper:v0.0.2-proxy                     "/bin/sh -c '/go/b..."   28 hours ago        Restarting (1) 19 seconds ago                            compose_management-oathkeeper-proxy_1
9d28a9945da1        oryd/oathkeeper:v0.0.2-proxy                     "/bin/sh -c '/go/b..."   28 hours ago        Restarting (1) 3 seconds ago                             compose_example-tenant-oathkeeper-proxy_1
39b6bed1493a        oryd/hydra:v0.10.0-alpha.7-http                  "hydra host --dang..."   28 hours ago        Up About a minute               4444/tcp                 compose_management-hydra_1
2fa0d7ce94aa        kong:0.11-alpine                                 "/docker-entrypoin..."   28 hours ago        Restarting (1) 17 seconds ago                            compose_management-kong_1
f33f6e01125a        oryd/hydra:v0.10.0-alpha.7-http                  "hydra host --dang..."   28 hours ago        Up About a minute               0.0.0.0:8204->4444/tcp   compose_example-tenant-hydra_1
1a6875ce9a8c        kong:0.11-alpine                                 "kong migrations up"     28 hours ago        Exited (0) 28 hours ago                                  compose_management-kong-migrations_1
a784ea9fb5a8        oryd/hydra:v0.10.0-alpha.7-http                  "hydra migrate sql..."   28 hours ago        Exited (0) 28 hours ago                                  compose_management-hydra-migrations_1
05911501702e        oryd/oathkeeper:v0.0.2-proxy                     "oathkeeper migrat..."   28 hours ago        Exited (0) 28 hours ago                                  compose_management-oathkeeper-migrations_1
df226e07bc44        oryd/oathkeeper:v0.0.2-management                "/bin/sh -c '/go/b..."   28 hours ago        Up About a minute               0.0.0.0:8103->4456/tcp   compose_management-oathkeeper-management_1
91f79b137c89        oryd/oathkeeper:v0.0.2-management                "/bin/sh -c '/go/b..."   28 hours ago        Up About a minute               0.0.0.0:8201->4456/tcp   compose_example-tenant-oathkeeper-example-tenant_1
63c3d910ad02        oryd/oathkeeper:v0.0.2-proxy                     "oathkeeper migrat..."   28 hours ago        Exited (0) 28 hours ago                                  compose_example-tenant-oathkeeper-migrations_1
8845b2b6bc2a        oryd/hydra:v0.10.0-alpha.7-http                  "hydra migrate sql..."   28 hours ago        Exited (0) 28 hours ago                                  compose_example-tenant-hydra-migrations_1
c88acdac5619        postgres:9.4                                     "docker-entrypoint..."   28 hours ago        Exited (255) 10 hours ago       0.0.0.0:8102->5432/tcp   compose_management-postgres_1
192aa2922a5e        postgres:9.4                                     "docker-entrypoint..."   28 hours ago        Exited (255) 10 hours ago       0.0.0.0:8202->5432/tcp   compose_example-tenant-postgres_1
3c547c704b36        compose_management-ui-backend                    "/bin/sh -c '/go/b..."   28 hours ago        Up About a minute               6001/tcp                 compose_management-ui-backend_1
c01e270fcee6        oryd/hydra-consent-app-express:v0.10.0-alpha.8   "/bin/sh -c 'npm s..."   28 hours ago        Up About a minute               0.0.0.0:8203->3000/tcp   compose_example-tenant-consent_1
```

```
$ docker network ls
NETWORK ID          NAME                            DRIVER              SCOPE
a1184872de48        bridge                          bridge              local
d3e4da3c7a8a        compose_example-tenant-subnet   bridge              local
7e87f88cfd1b        compose_management-subnet       bridge              local
39eceb8db50d        host                            host                local
ba0a63f55518        none                            null                local
```

```
$ docker images -a
REPOSITORY                       TAG                    IMAGE ID            CREATED             SIZE
compose_management-consent-app   latest                 1b8f3dd83aee        28 hours ago        1.02GB
<none>                           <none>                 ee914620b201        28 hours ago        1.02GB
<none>                           <none>                 f322a5c99200        28 hours ago        1.02GB
<none>                           <none>                 d61f3f4e1052        28 hours ago        1.02GB
<none>                           <none>                 dff8fefda2fd        28 hours ago        1.02GB
<none>                           <none>                 0712ae88d620        28 hours ago        72.3MB
<none>                           <none>                 cd2fba07accc        28 hours ago        72.1MB
<none>                           <none>                 b8d64fdb9f96        28 hours ago        72.1MB
<none>                           <none>                 88b72598950b        28 hours ago        72.1MB
<none>                           <none>                 4df2d928eac3        28 hours ago        72.1MB
<none>                           <none>                 d90739106df7        28 hours ago        72.1MB
compose_management-ui-backend    latest                 f1b559538c95        28 hours ago        551MB
<none>                           <none>                 92b5833cf309        28 hours ago        551MB
<none>                           <none>                 04681b0ac81d        28 hours ago        551MB
<none>                           <none>                 7db047335312        28 hours ago        534MB
<none>                           <none>                 aa01d77e1c9d        28 hours ago        483MB
<none>                           <none>                 4970d813f8a3        28 hours ago        357MB
<none>                           <none>                 a9edd3587075        28 hours ago        357MB
<none>                           <none>                 fc053901de35        28 hours ago        357MB
<none>                           <none>                 5cac899b1163        28 hours ago        357MB
<none>                           <none>                 48eba7dcd58f        28 hours ago        339MB
postgres                         9.4                    13fff887b6fb        6 days ago          263MB
oryd/oathkeeper                  v0.0.2-management      e4f4388b2017        7 days ago          848MB
oryd/oathkeeper                  v0.0.2-proxy           f44ef0e45360        7 days ago          848MB
oryd/hydra-consent-app-express   v0.10.0-alpha.8        347b8115c314        11 days ago         1.07GB
oryd/hydra                       v0.10.0-alpha.7-http   27e8d153d4c7        13 days ago         884MB
golang                           1.9-alpine             107ed76bfbd2        2 weeks ago         270MB
node                             8.5-alpine             7a779c246a41        4 weeks ago         67MB
kong                             0.11-alpine            d53207c4f9f5        5 weeks ago         83.3MB
d4w/nsenter                      latest                 9e4f13a0901e        13 months ago       83.8kB
```

After restarting, my docker logfile looks like this: https://gist.github.com/arekkas/a6dcba34a782f72bd6381a5d060ee8e1

**Comment by BrizzleRocker** [comment]
https://github.com/docker/for-win/issues/1075
