### ISSUE TITLE
Docker fails to start on Windows 10. Works fine after several restarts.

### ISSUE THREAD

**Issue by GinoPane** [docker/for-win#1226]
### Expected behavior
Docker should start when needed with no issues.

### Actual behavior
When I run Docker the first time it always fails to start. After restarting Docker it would probably start fine (not always).

### Information

```
Docker command did not complete within the allowed timeout. Output: 
   at Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 152
   at Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 49
   at Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 197
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 168
   at Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 65
   at Docker.Backend.BackendServer.<Run>b__6_10(Object[] args) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\BackendServer.cs:line 52
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

Version 17.09.0-ce-win33 (13620)

[log.txt](https://github.com/docker/for-win/files/1399569/log.txt)

### Steps to reproduce the behavior

  1. Run Docker for the first time after Windows start.
  2. See how it fails.

**Comment by gjong** [comment]
I am experiencing the exact same behavior with Version 17.09.1-ce-win42 (14687). In hopes that the developers can track down the issue I've sent multiple bug reports using the docker ui. It crashes with this exception the first time I start docker after a reboot or logout / login.

Usually it starts fine the second attempt (but sometimes it requires multiple attempts or even un-mounting of the logical drives)

**Comment by GinoPane** [comment]
@gjong Try to update to 17.12 at least. The issue seems to be fixed.
