### ISSUE TITLE
Group policy for Server service prevents installation of docker desktop

### ISSUE THREAD

**Issue by BrianFreemanAtlanta** [docker/for-win#12291]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Get the following error:
 [ServicePreRequisite] Failed to run prerequisite service: System.AggregateException: One or more errors occurred. ---> CommunityInstaller.Win32ExceptionWithContext: Failed to start service: Access is denied
   at CommunityInstaller.Service.Manager.<StartServiceAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.ServicePreRequisite.<EnsureServiceRunningAsync>d__14.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at CommunityInstaller.ServicePreRequisite.get_IsFullFilled()
---> (Inner Exception #0) CommunityInstaller.Win32ExceptionWithContext (0x80004005): Failed to start service: Access is denied
   at CommunityInstaller.Service.Manager.<StartServiceAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.ServicePreRequisite.<EnsureServiceRunningAsync>d__14.MoveNext()<---
Microsoft.PowerShell.Commands.WriteErrorException
[09:30:18.893] [InstallWorkflow] Prerequisite failed: Docker Desktop requires the Server service to be enabled.
### Expected behavior
Installer would see service is running and continue to install

### Information
Corporate group policies sets "server" service to automatic start. General user cannot change status of the service.

  - Windows Version: Enterprise 10.0.18363 build 18363
  - Docker Desktop Version: 4.1.1
  - WSL2 or Hyper-V backend?  have WSL2 installed and Hyper-V enabled
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: N/A

### Steps to reproduce the behavior

  1. Have group policy set "Server" service to automatic. User has only "Read" access to policy/service
  2. Verify user, even user with admin rights cannot change Server service run status.
  3. Install Docker Desktop - will error out - prerequisite is not fulfilled "Docker Desktop requires the server service to be enabled"
  4. chocolatey install gives detailed message

**Comment by joe0BAB** [comment]
Please try version 4.2.0. The problem should be fixed. Feel free to reopen if you are having further issues.
