### ISSUE TITLE
Hyper-V Backend Docker Starts very slow

### ISSUE THREAD

**Issue by IosifZ** [docker/for-win#12356]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 747B8852-E0FB-41C3-A4E1-2376729B922D/20211109084635

### Actual behavior
Docker needs around 15 minutes to start
### Expected behavior
Docker should start immediately after a Windows boot/reboot (2-3 minutes max)
### Information

  - Windows Version: 10 Pro build 19043
  - Docker Desktop Version: 4.1.1 (69879)
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior
Reboot your computer

Log: https://pastebin.com/raw/kSN1YTUE

**Comment by IosifZ** [comment]
This is the long break where nothing happens:
`[10:27:37.005][IPCServer         ][Info   ] (67e8307c) 45caecd0-ServiceAPI S->C 4f7688ca-ServiceAPIClient-CSharp POST /hyperv/start (1891ms): OK
[10:37:42.552][IPCServer         ][Info   ] (c62d5f5b) 45caecd0-ServiceAPI S<-C fc6e5925-ServiceAPIClient-CSharp POST /hyperv/stop`

If I manually reboot the Docker Hyper-V VM during that time, Docker starts in 35 seconds since the VM is up.

**Comment by IosifZ** [comment]
I made the upgrade to 4.2.0, same issue.

The output from the new Diagnostic tool:
```
PS C:\WINDOWS\system32> & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
[313:14:18:01.385][I] ipc.NewClient: 27c29488-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:26
[win/backend/pkg/service.NewClient(...)
[       win/backend/pkg/service/service.go:20
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x13b
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0020: is the Hyper-V Windows Feature enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
segment 2021/11/09 14:18:09 ERROR: sending request - Post "https://api.segment.io/v1/batch": dial tcp: lookup api.segment.io: getaddrinfow: The requested name is valid, but no data of the requested type was found.
segment 2021/11/09 14:18:09 ERROR: 1 messages dropped because they failed to be sent and the client was closed
No failures detected.
PS C:\WINDOWS\system32>
```

Here is the new Diagnostic ID: 747B8852-E0FB-41C3-A4E1-2376729B922D/20211109121503

**Comment by IosifZ** [comment]
New problem: Docker closes by itself. Here is what I was able to find in my event viewer:

```
Log Name:      Application
Source:        Application Error
Date:          10-Nov-21 14:06:01
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      xxxxxxxxxxxxxxxx
Description:
Faulting application name: Docker Desktop.exe, version: 4.2.0.0, time stamp: 0xd4a649ee
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1320, time stamp: 0x00d7bca2
Exception code: 0xe0434352
Fault offset: 0x0000000000034f69
Faulting process id: 0x3730
Faulting application start time: 0x01d7d602714babf6
Faulting application path: C:\Program Files\Docker\Docker\Docker Desktop.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 199945aa-c68e-4216-a2cc-9771bf338668
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>100</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-11-10T12:06:01.9202363Z" />
    <EventRecordID>115884</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>IOSIF-BOX</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Docker Desktop.exe</Data>
    <Data>4.2.0.0</Data>
    <Data>d4a649ee</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.19041.1320</Data>
    <Data>00d7bca2</Data>
    <Data>e0434352</Data>
    <Data>0000000000034f69</Data>
    <Data>3730</Data>
    <Data>01d7d602714babf6</Data>
    <Data>C:\Program Files\Docker\Docker\Docker Desktop.exe</Data>
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data>
    <Data>199945aa-c68e-4216-a2cc-9771bf338668</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```
