### ISSUE TITLE
`docker-compose up` fails in WSL 2 environment

### ISSUE THREAD

**Issue by blake-mealey** [docker/for-win#12355]
## Description of the issue

Whenever I run `docker-compose up` in my WSL 2 environment, it fails with the error:

```
docker.credentials.errors.InitializationError: docker-credential-desktop.exe not installed or not available in PATH
[519] Failed to execute script docker-compose
```

It's complaining that docker-credential-desktop is not available, however in the same session I can run `docker-credential-desktop -h` and get the help text output.

I am also able to use `docker run` to build and run my container without any problems.

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Output of `docker version`**
```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:46 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  happy:
    build:
      context: /home/blake/repos/happy
      dockerfile: Dockerfile
    container_name: happy
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
    - published: 3001
      target: 3000
    volumes:
    - /home/blake/repos/happy:/app:rw
    - /app/node_modules
version: '3.7'
```

## Steps to reproduce the issue

1. Create a WSL 2 environment (I'm running Ubuntu 20.04)
2. Install Docker Desktop
3. Create a Dockerfile and attempt to run `docker-compose up` on it

### Observed result

The above error message

### Expected result

The container is built and run

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1077, in up
  File "compose/cli/main.py", line 1073, in up
  File "compose/project.py", line 548, in up
  File "compose/service.py", line 367, in ensure_image_exists
  File "compose/service.py", line 1106, in build
  File "site-packages/docker/api/build.py", line 261, in build
  File "site-packages/docker/api/build.py", line 308, in _set_auth_headers
  File "site-packages/docker/auth.py", line 301, in get_all_credentials
  File "site-packages/docker/auth.py", line 287, in _get_store_instance
  File "site-packages/docker/credentials/store.py", line 25, in __init__
docker.credentials.errors.InitializationError: docker-credential-desktop.exe not installed or not available in PATH
[519] Failed to execute script docker-compose
```

## Additional information

OS version: Windows 10 version 2004 build 19041.264
WSL 2 distro: Ubuntu 20.04

The way I got my setup was:

* Installed WSL 2 with latest Windows update
* Installed Docker Desktop and enabled the WSL features

**Comment by ealanisg** [comment]
> 1. rm ~/.docker/config.json

This worked for me, no need of using sudo after, just `docker-compise build`

**Comment by Andrew-Staves-Activ** [comment]
This is still happening for me - I'm having to run `rm ~/.docker/config.json` each time I start Docker.
/remove-lifecycle stale
