### ISSUE TITLE
Unable to create transparent network when using WiFi

### ISSUE THREAD

**Issue by thxkiwi** [docker/for-win#12440]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: diagnose fails

### Actual behavior
```
PS C:\Users\miken> docker network create -d transparent test
Error response from daemon: failed during hnsCallRawResponse: hnsCall failed in Win32: The parameter is incorrect. (0x57)
```

### Expected behavior
```
PS C:\Users\miken> docker network create -d transparent test
41be85dba0ae954029cb03d3bdb9504b7ac47deaa89945b46b56123e610010f6
```

### Information

  - Windows Version: Windows 10 Pro (21H1) OS Build: 19043.1348
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  WSL2 but Windows containers so hyper-V isolation
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No. Host is running on the metal.

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```
PS C:\Users\miken> & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
[346:17:22:47.078][I] ipc.NewClient: ff5c9e32-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:26
[win/backend/pkg/service.NewClient(...)
[       win/backend/pkg/service/service.go:20
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x13b
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[FAIL] DD0028: is there available VM disk space? failed to retrieve the size information from ''
[FAIL] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[346:17:22:49.114][I] ipc.NewClient: d08c61f4-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer LifecycleServer
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClientForPath(...)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:64
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClient(...)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:58
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:21 +0x5a
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x9b9d97, 0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x12373c0, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1237440, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xb29060, 0xc000731918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x12375c0, 0xc00003a300, {0xc000731b20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00007a3d0, 0xc00007a3d0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273
[346:17:22:49.114][I] (92fb2130) d08c61f4-com.docker.diagnose C->S LifecycleServer GET /docker
[346:17:22:49.115][E] (92fb2130) d08c61f4-com.docker.diagnose C<-S NoResponse GET /docker (498.2µs): Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc0007313f0)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:108 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x74
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x9b9d97, 0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x12373c0, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1237440, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xb29060, 0xc000731918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x12375c0, 0xc00003a300, {0xc000731b20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00007a3d0, 0xc00007a3d0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273
[346:17:22:49.115][I] (92fb2130-1) d08c61f4-com.docker.diagnose C->S LifecycleServer GET /ping
[346:17:22:49.116][E] (92fb2130-1) d08c61f4-com.docker.diagnose C<-S NoResponse GET /ping (469.7µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc0007313f0)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:108 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x74
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x9b9d97, 0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x12373c0, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1237440, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xb29060, 0xc000731918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x12375c0, 0xc00003a300, {0xc000731b20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00007a3d0, 0xc00007a3d0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273
[346:17:22:50.126][I] (92fb2130-2) d08c61f4-com.docker.diagnose C->S LifecycleServer GET /ping
[346:17:22:50.126][E] (92fb2130-2) d08c61f4-com.docker.diagnose C<-S NoResponse GET /ping (312.5µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc0007313f0)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:108 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x74
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x9b9d97, 0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x12373c0, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1237440, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xb29060, 0xc000731918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x12375c0, 0xc00003a300, {0xc000731b20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00007a3d0, 0xc00007a3d0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273
[346:17:22:51.137][I] (92fb2130-3) d08c61f4-com.docker.diagnose C->S LifecycleServer GET /ping
[346:17:22:51.137][E] (92fb2130-3) d08c61f4-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc0007313f0)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:108 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x74
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x9b9d97, 0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x12373c0, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1237440, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xb29060, 0xc000731918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x12375c0, 0xc00003a300, {0xc000731b20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00007a3d0, 0xc00007a3d0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273
[346:17:22:52.146][I] (92fb2130-4) d08c61f4-com.docker.diagnose C->S LifecycleServer GET /ping
[346:17:22:52.146][E] (92fb2130-4) d08c61f4-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc0007313f0)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:108 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x74
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x9b9d97, 0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x12373c0, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1237440, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xb29060, 0xc000731918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x12375c0, 0xc00003a300, {0xc000731b20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00007a3d0, 0xc00007a3d0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273
[346:17:22:53.149][I] (92fb2130-5) d08c61f4-com.docker.diagnose C->S LifecycleServer GET /ping
[346:17:22:53.150][E] (92fb2130-5) d08c61f4-com.docker.diagnose C<-S NoResponse GET /ping (435.3µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc0007313f0)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:108 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x74
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x9b9d97, 0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x12373c0, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1237440, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xb29060, 0xc000731918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x12375c0, 0xc00003a300, {0xc000731b20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00007a3d0, 0xc00007a3d0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273
[346:17:22:54.161][I] (92fb2130-6) d08c61f4-com.docker.diagnose C->S LifecycleServer GET /ping
[346:17:22:54.161][E] (92fb2130-6) d08c61f4-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc0007313f0)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:108 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x74
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x9b9d97, 0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x12373c0, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1237440, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xb29060, 0xc000731918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x12375c0, 0xc00003a300, {0xc000731b20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00007a3d0, 0xc00007a3d0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273
[346:17:22:55.168][I] (92fb2130-7) d08c61f4-com.docker.diagnose C->S LifecycleServer GET /ping
[346:17:22:55.168][E] (92fb2130-7) d08c61f4-com.docker.diagnose C<-S NoResponse GET /ping (510.3µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc0007313f0)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:108 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x74
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x9b9d97, 0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x12373c0, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1237440, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xb29060, 0xc000731918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x12375c0, 0xc00003a300, {0xc000731b20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00007a3d0, 0xc00007a3d0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273
[346:17:22:56.176][I] (92fb2130-8) d08c61f4-com.docker.diagnose C->S LifecycleServer GET /ping
[346:17:22:56.176][E] (92fb2130-8) d08c61f4-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc0007313f0)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:108 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x74
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x9b9d97, 0x12373c0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x12373c0, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1237440, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0007317d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xb29060, 0xc000731918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x12375c0, 0xc00003a300, {0xc000731b20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00007a3d0, 0xc00007a3d0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273

[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[346:17:22:58.694][I] ipc.NewClient: af47a3e4-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.glob..func13()
[       common/pkg/diagkit/gather/diagnose/linuxkit.go:18 +0x4b
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1237340)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1237340)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x9b9d97, 0x1237340)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x1237340, 0xc0004877d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x12373c0, 0xc0004877d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1237440, 0xc0004877d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0004877d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xb29060, 0xc000731918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x12375c0, 0xc00003a300, {0xc000731b20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00007a3d0, 0xc00007a3d0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273
[346:17:22:58.694][I] (caf91723) af47a3e4-diagnose C->S diagnosticsd GET /ping
[346:17:22:58.694][E] (caf91723) af47a3e4-diagnose C<-S NoResponse GET /ping (603.3µs): Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[common/pkg/diagkit/gather/diagnose.glob..func13()
[       common/pkg/diagkit/gather/diagnose/linuxkit.go:19 +0x54
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1237340)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1237340)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x9b9d97, 0x1237340)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x1237340, 0xc0004877d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x12373c0, 0xc0004877d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1237440, 0xc0004877d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0004877d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xb29060, 0xc000731918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x12375c0, 0xc00003a300, {0xc000731b20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc00007a3d0, 0xc00007a3d0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273

[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0023: is the Containers Windows Feature enabled?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
2021/12/12 17:23:00 exit status 0xffffffff
```
### Steps to reproduce the behavior

Issue the following command when using WiFi
  1. `docker network create -d transparent mytransparent`

**Comment by thxkiwi** [comment]
Originally created an issue in moby project since this was occurring during docker build phase. See activity above.

**Comment by stephen-turner** [comment]
Thanks for the report. I think moby/moby is the right place for it: all hns errors are from the upstream engine. So I'll close this copy and leave the other one open.
