### ISSUE TITLE
Docker CE stable installer is not starting on Windows 7

### ISSUE THREAD

**Issue by pidzama** [docker/for-win#1246]
### Expected behavior
Double click on _Docker for Windows Installer.exe_ starts the installator program
### Actual behavior
Installator is not started, there is error when started from a console:

```

C:\Users\Administrator\Downloads>
Unhandled Exception: System.Windows.Markup.XamlParseException: Set property 'Sys
tem.Windows.FrameworkElement.Style' threw an exception. ---> System.IO.FileNotFo
undException: Could not load file or assembly 'PresentationFramework.Aero2, Publ
icKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find
the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String cod
eBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&
stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntro
spection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName as
semblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMar
k& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIn
trospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveAssembly(BamlAssembly
 bamlAssembly)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlTypeToType(BamlTy
pe bamlType)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType bam
lType, Int16 typeId)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16 typeId)
   at System.Windows.Baml2006.Baml2006Reader.Process_ElementStart()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.ReadObject(KeyRecord record)
   at System.Windows.ResourceDictionary.CreateObject(KeyRecord key)
   at System.Windows.ResourceDictionary.OnGettingValue(Object key, Object& value
, Boolean& canCache)
   at System.Windows.ResourceDictionary.OnGettingValuePrivate(Object key, Object
& value, Boolean& canCache)
   at System.Windows.ResourceDictionary.GetValueWithoutLock(Object key, Boolean&
 canCache)
   at System.Windows.ResourceDictionary.GetValue(Object key, Boolean& canCache)
   at System.Windows.DeferredResourceReference.GetValue(BaseValueSourceInternal
valueSource)
   at System.Windows.DependencyPropertyChangedEventArgs.get_NewValue()
   at System.Windows.FrameworkElement.OnStyleChanged(DependencyObject d, Depende
ncyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChange
dEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChange
dEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyCha
ngedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex
, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry
, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean co
erceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Obje
ct value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolea
n coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Ob
ject value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember
 property, Object value)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInf
o lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjec
tWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject
, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolea
n skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri b
aseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext par
serContext, Object parent, Boolean closeStream)
   at LightweightInstaller.Wizard..ctor(IChannelHelper channelHelper)
   at LightweightInstaller.Cmd.CommandResolver.Resolve(String[] args)
   at LightweightInstaller.Program.Main(String[] args)
```

### Information

  - Windows 7 Professional Service Pack 1
  - installer downloaded from [https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe](url) on 25th October 2017 (not sure what internal vesion is that)
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Download mentioned installer
  2. Try to run in on mentioned Windows version

**Comment by friism** [comment]
@ebriney is there a problem with no showing error for incompatible Windows version?

@pidzama Windows 10 is required for Docker for Windows.

If you can't upgrade from Windows 7, please use Docker Toolbox: https://www.docker.com/products/docker-toolbox

**Comment by ebriney** [comment]
@friism : will check that.

**Comment by hrimhariinsecure** [comment]
This is worth an entry in the FAQ and/or a note on the main download page pointing <win10 people to docker-toolbox, don't you think?

**Comment by hrimhari** [comment]
I'd have liked to see an entry on the FAQ and/or a note on the main download page pointing <win10 people to docker-toolbox.

**Comment by pidzama** [comment]
> I'd have liked to see an entry on the FAQ and/or a note on the main download page pointing <win10 people to docker-toolbox.

That would be great.
