### ISSUE TITLE
Docker Desktop keeps shutting down randomly

### ISSUE THREAD

**Issue by wrhighfield** [docker/for-win#12464]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: A191FE89-EB6B-45D1-93C3-A155DFEB86C3/20211224011822

Docker Desktop keeps shutting down randomly, this is a new install.

### Information
  - Windows Version: Windows 11 Pro 21H2 22000.376 (fresh install not an upgrade)
  - Docker Desktop Version: 4.3.2 (72729)
  - WSL2 or Hyper-V backend?   WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Windows Event Log Information
Faulting application name: Docker Desktop.exe, version: 4.3.2.0, time stamp: 0xfdaaf44f
Faulting module name: KERNELBASE.dll, version: 10.0.22000.348, time stamp: 0x065c557a
Exception code: 0xe0434352
Fault offset: 0x000000000004478c
Faulting process id: 0x5f4c
Faulting application start time: 0x01d7f7991e4be452
Faulting application path: C:\Program Files\Docker\Docker\Docker Desktop.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 1802e3f2-4d32-46c7-b4f0-27580188f8cc
Faulting package full name: 
Faulting package-relative application ID: 

Application: Docker Desktop.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
   at System.Net.HttpWebRequest.EndGetRequestStream(System.IAsyncResult, System.Net.TransportContext ByRef)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(System.IAsyncResult)

Exception Info: System.Net.Http.HttpRequestException
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at System.Net.Http.HttpClient+<FinishSendAsyncBuffered>d__58.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.ApiServices.Analytics.SegmentApi+<DoIdentify>d__25.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Docker.ApiServices.Analytics.SegmentApi+<>c__DisplayClass24_0+<<IdentifyAsync>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by quakemaster** [comment]
> * [x]  I have tried with the latest version of Docker Desktop
> * [x]  I have tried disabling enabled experimental features
> * [x]  I have uploaded Diagnostics
> * Diagnostics ID: A191FE89-EB6B-45D1-93C3-A155DFEB86C3/20211224011822
> 
> Docker Desktop keeps shutting down randomly, this is a new install.
> 
> ### Actual behavior
> ### Expected behavior
> ### Information
> * Windows Version: Windows 11 Pro 21H2 22000.376 (fresh install not an upgrade)
> * Docker Desktop Version: 4.3.2 (72729)
> * WSL2 or Hyper-V backend?   WSL2
> * Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No
> 
> ### Windows Event Log Information
> Faulting application name: Docker Desktop.exe, version: 4.3.2.0, time stamp: 0xfdaaf44f Faulting module name: KERNELBASE.dll, version: 10.0.22000.348, time stamp: 0x065c557a Exception code: 0xe0434352 Fault offset: 0x000000000004478c Faulting process id: 0x5f4c Faulting application start time: 0x01d7f7991e4be452 Faulting application path: C:\Program Files\Docker\Docker\Docker Desktop.exe Faulting module path: C:\Windows\System32\KERNELBASE.dll Report Id: 1802e3f2-4d32-46c7-b4f0-27580188f8cc Faulting package full name: Faulting package-relative application ID:
> 
> Application: Docker Desktop.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.Net.WebException at System.Net.HttpWebRequest.EndGetRequestStream(System.IAsyncResult, System.Net.TransportContext ByRef) at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(System.IAsyncResult)
> 
> Exception Info: System.Net.Http.HttpRequestException at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) at System.Net.Http.HttpClient+d__58.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) at Docker.ApiServices.Analytics.SegmentApi+d__25.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task) at Docker.ApiServices.Analytics.SegmentApi+<>c__DisplayClass24_0+<b__0>d.MoveNext() at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() at System.Threading.ThreadPoolWorkQueue.Dispatch()

same issue
+1
