### ISSUE TITLE
Upgrade from 4.3.1 to 4.3.2: docker for desktop fails to start docker engine

### ISSUE THREAD

**Issue by ManfredLange** [docker/for-win#12463]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4F6A9A13-1BB7-4A58-BC1F-8C8643C39AA8/20211224003558

### Actual behavior

1. Uninstalled version 4.3.1
2. Installed version 4.3.2
3. docker app is showing "Docker Engine starting..."
4. after several minutes (5 to 10 minutes?) the docker app opens a dialog box with the following content:
```
System.InvalidOperationException:
distro stopped unexpectedly
   at Docker.Engines.LinuxkitDaemonStartup.<WaitAsync>d__5.MoveNext() in C:\workspaces\4.3.x\src\github.com\docker\pinata\win\src\Docker.Engines\LinuxkitDaemonStartup.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__28.MoveNext() in C:\workspaces\4.3.x\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 179
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\4.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\4.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\4.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

### Expected behavior

1. Uninstall version 4.3.1
2. Install version 4.3.2
3. starting docker app should complete startup to become usable

### Information

  - Windows Version: Windows 10 Pro, Version 10.0.19043 Build 19043
  - Docker Desktop Version: 4.3.2
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no
  - Is it reproducible? Yes, all updates of the last 6 to 12 months were stuffed up as well

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

see attached file [docker.diagnose.2021-12-24.txt](https://github.com/docker/for-win/files/7771967/docker.diagnose.2021-12-24.txt)

### Steps to reproduce the behavior

I only have one computer and already spend at least half hour with each update to resolve and make it working again, so I'm afraid I don't have further details about how to reproduce this issue.

  1. ...
  2. ...

**Comment by ManfredLange** [comment]
This time the following helped to resolve the issue:
1. uninstall docker 4.3.1
2. close all terminals into any linux distro you may have installed in WSL(2)
3. close all VS Code instances; it may have terminal windows open
4. install docker 4.3.2
5. in a powershell terminal run the command `wsl --shutdown`
6. in a powershell terminal run the command `wsl -l -v` to see if all distros have stopped; if a distro is still running, explicitly terminate it with command `wsl -t <distroname>`; if the distro is still running, some process is still using it and you need to find and stop that process; try terminating the distro again; repeat this process until all distros are stopped
7. start docker 4.3.2; this time this succeed in my environment

**Comment by Sourabh1107** [comment]
Hello @ManfredLange I have a similar issue with Docker Windows. I have a small doubt before doing the above mentioned steps. Does uninstalling existing docker and re-installing docker removes existing volumes and containers? I don't want to lose existing containers. I have not signed-in while working with docker. So will the containers be restored after installing 4.3.2?

Thanks in advance

**Comment by lermontex** [comment]
Every update to Docker for Windows crashes due to the need to completely reinstall the software. Moreover, the problem is not being solved in any way. Is there an alternative to Docker?

**Comment by Sourabh1107** [comment]
Hi @lermontex after re-installing, did the existing volumes and containers get restored? Because I have several containers and don't want to lose the data. BTW, I didn't create an account while working with docker.

**Comment by lermontex** [comment]
@Sourabh1107, I always uninstall anything related to Docker before installing a new version if there are any errors after upgrading. So I can't tell you exactly, but most likely the containers will be lost :(
