### ISSUE TITLE
Laptop Unable to Sleep and Hibernate After Installation

### ISSUE THREAD

**Issue by http403** [docker/for-win#12473]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 986D3D27-7B46-4914-BE1E-469FCF43DB2B/20211230092718

### Actual behavior
My laptop unable to sleep or hibernate, then eventually drain the battery.

### Expected behavior
Get into sleep or hibernate within 5 seconds.

### Information

  - Windows Version: Windows 10 Build 19043
  - Docker Desktop Version: 4.3.2
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

```
[364:09:35:51.805][I] ipc.NewClient: 73f15a81-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:26
[win/backend/pkg/service.NewClient(...)
[       win/backend/pkg/service/service.go:20
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x13b
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[FAIL] DD0012: is the VM networking working? network checks failed: Post "http://ipc/check-network-connectivity": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[364:09:36:02.832][I] ipc.NewClient: b6790140-diagnose-network -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[       common/pkg/diagkit/gather/diagnose/network.go:34 +0x99
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1907540)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1907540)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x1907540)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1907540, 0xc0000dd7d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0000dd7d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x11f9060, 0xc00061f918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x19075c0, 0xc0000742a0, {0xc00061fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc0000643d0, 0xc0000643d0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273
[364:09:36:02.833][I] (9fd50e4c) b6790140-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["172.24.128.1","172.29.128.1","192.168.255.209","172.22.32.1","172.24.192.1"]}
[364:09:36:07.849][E] (9fd50e4c) b6790140-diagnose-network C<-S NoResponse POST /check-network-connectivity (5.0165381s): Post "http://ipc/check-network-connectivity": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[       common/pkg/diagkit/gather/diagnose/network.go:35 +0x10a
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1907540)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1907540)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x1907540)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1907540, 0xc0000dd7d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0000dd7d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x11f9060, 0xc00061f918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x19075c0, 0xc0000742a0, {0xc00061fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc0000643d0, 0xc0000643d0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273
[364:09:36:07.854][I] (9fd50e4c-1) b6790140-diagnose-network C->S diagnosticsd GET /ping
[364:09:36:07.864][I] (9fd50e4c-1) b6790140-diagnose-network C<-S 505b21a2-diagnosticsd GET /ping (9.7648ms): {"serverTime":1640856967860852700}
[364:09:36:07.864][I] (9fd50e4c-2) b6790140-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["172.24.128.1","172.29.128.1","192.168.255.209","172.22.32.1","172.24.192.1"]}
[364:09:36:12.870][E] (9fd50e4c-2) b6790140-diagnose-network C<-S NoResponse POST /check-network-connectivity (5.0057876s): Post "http://ipc/check-network-connectivity": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[       common/pkg/diagkit/gather/diagnose/network.go:35 +0x10a
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1907540)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1907540)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x1907540)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1907540, 0xc00048b7d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc00048b7d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x11f9060, 0xc00061f918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x19075c0, 0xc0000742a0, {0xc00061fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc0000643d0, 0xc0000643d0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273

[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: is the VM networking working?
    Failed with: network checks failed: Post "http://ipc/check-network-connectivity": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.
```

### Steps to reproduce the behavior

  1. Install Docker Desktop
  2. Get into sleep or hibernate

### Temporary Solution
Quit Docker before sleep or hibernation.

#### Note
I don't know why the check reported I don't have internet where I'm using the same laptop to write this issue.

**Comment by http403** [comment]
Somehow the issue is gone by itself, and I can't repoduce it. I will close it for now.
