### ISSUE TITLE
Docker Desktop does not start, keeps crashing

### ISSUE THREAD

**Issue by MichelZ** [docker/for-win#12497]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics (NOTE: I have tried but it fails while gathering diagnostics, so I guess it has not uploaded correctly)
  - Diagnostics ID: 7F799AAA-911E-4310-B2BC-0ED2069DDF16 (I don't think it was uploaded, as gathering failed)

### Actual behavior
Docker not starting. GUI just dies, daemon not running.
### Expected behavior
Docker starting and working

### Information
  - Is it reproducible? Yes, I have tried re-installing docker desktop a couple of times
  - Is the problem new? Yes, I haven't used docker in a couple of weeks, and when I tried again it didn't work
  - Did the problem appear with an update? Not sure if an update caused it,
  - Windows Version: 10 21H2
  - Docker Desktop Version: 4.4.3
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, physical Windows

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[docker-check.txt](https://github.com/docker/for-win/files/7880157/docker-check.txt)

### Steps to reproduce the behavior
  1. Install docker desktop
  2. Start docker desktop

Here is the error from diagnostics gather:
```
time="2022-01-17T09:10:13+01:00" level=info msg="Gathering {\n  \"id\": \"7F799AAA-911E-4310-B2BC-0ED2069DDF16\",\n  \"date\": \"2022-01-17 08:09:07.4552335 +0000 UTC\"\n}\n" type=list
time="2022-01-17T09:10:14+01:00" level=warning msg="cannot unmarshal: unexpected end of JSON input" type=collectInfo
panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 67 [running]:
github.com/docker/pinata/common/pkg/diagkit/gather.(*DesktopDiagInfo).collectInfo(0xc0000e7d40)
        C:/workspaces/PR-17085/src/github.com/docker/pinata/common/pkg/diagkit/gather/docker_desktop_windows.go:39 +0x465
github.com/docker/pinata/common/pkg/diagkit/gather.DesktopDiagInfo.Gather({{0xc0006aac80, 0x24}, {0xc000149440, 0x25}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}, ...)
        C:/workspaces/PR-17085/src/github.com/docker/pinata/common/pkg/diagkit/gather/docker_desktop.go:78 +0xc5
github.com/docker/pinata/common/pkg/diagkit/gather.(*Gatherers).Gather.func1(0x0, {0x15c6238, 0xc0002012c0}, 0x0)
        C:/workspaces/PR-17085/src/github.com/docker/pinata/common/pkg/diagkit/gather/gather.go:90 +0x164
created by github.com/docker/pinata/common/pkg/diagkit/gather.(*Gatherers).Gather
        C:/workspaces/PR-17085/src/github.com/docker/pinata/common/pkg/diagkit/gather/gather.go:87 +0x25d
```

**Comment by MichelZ** [comment]
After further diagnosis, my "Windows Management Instrumentation" Service was disabled, and thus Docker was unable to query WMI. After re-enabling and starting the service, docker works now. Also, the diagnostics application works.
