### ISSUE TITLE
DockerService logging PowerEvent in Windows Logs every 5 seconds (+BSOD)

### ISSUE THREAD

**Issue by 39digits** [docker/for-win#12507]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Every 5 seconds DockerService is shown under Application logs in Event Viewer with the message `PowerEvent handled successfully by the service.`

I am running the latest version of Docker Desktop on the latest version of Windows 11 Pro.  Docker Desktop is not set to automatically start when logging into Windows.  It is using WSL2 as the Docker Engine on an Ubuntu 20.04 distro.

The PowerEvents are logged whether Docker Desktop is running or not.

The PowerEvent logs are associated with the PID for `com.docker.service`

There are now random blue screens of death which ceased after uninstalling Docker Desktop.  The BSOD returned when reinstalling Docker Desktop.

### Expected behavior
No BSOD and no constant logs from DockerService for PowerEvents in the Windows Log when Docker Desktop isn't actually running.

### Information
  - Windows Version: Windows 11 Pro 21H2 (22000.438)
  - Docker Desktop Version: 4.4.3 (73365)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

```
[021:21:32:48.769][I] ipc.NewClient: e376ca7a-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:31
[win/backend/pkg/service.NewClient({0x12cd772, 0x13})
[       win/backend/pkg/service/service.go:25 +0xc5
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x118
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

### Steps to reproduce the behavior
Logs occur whether I start DockerDesktop or not using latest version of DockerDesktop.

The BSOD and related logs only occurred after I updated in December 2021 - prior to that I had zero issues.

**Comment by 39digits** [comment]
To add to this, I just uninstalled 4.4.3 and installed 4.2.0 (the version I was on prior to updating in December) and everything is stable on that older version.
