### ISSUE TITLE
Docker Desktop Causes Flickering Throughout Windows

### ISSUE THREAD

**Issue by MitchTalmadge** [docker/for-win#12532]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `70862C5B-B9BA-4B8F-8B99-71C2A82664EA/20220205231535`

### Actual behavior
When Docker Desktop is running, various parts of Windows such as the tray icons, mouse cursor, and help menus will flicker. The flickering does not happen all the time, but it only happens when Docker Desktop is running. Closing Docker Desktop immediately causes the flickering to stop, whilst closing other apps does not have any effect.

See this gif which shows the flickering, and then shows the flickering stopping after closing Docker Desktop:

![Docker Desktop Flicker2](https://user-images.githubusercontent.com/8848080/152662188-95fcb0c8-944f-4914-af66-75e641114093.gif)

### Expected behavior
There should be no flickering.

### Information

  - Windows Version: Windows 11 Pro Version 21H2 Build 22000.466
  - Docker Desktop Version: 4.4.4 (73704)
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

```
(base) PS C:\Users\mitch> & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
[036:16:22:24.692][I] ipc.NewClient: ad9367b5-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:40
[win/backend/pkg/service.NewClient({0x132e8be, 0x13}, {0x0, 0x0, 0x0})
[       win/backend/pkg/service/service.go:29 +0xe8
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x11f
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[FAIL] DD0012: is the VM networking working? network checks failed: failed to ping host: exit status 1
[036:16:22:30.301][I] ipc.NewClient: 642570f1-diagnose-network -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[       common/pkg/diagkit/gather/diagnose/network.go:34 +0x107
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1982760)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1982760)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x1982760)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1982760, 0xc0002e17d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0002e17d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x125e960, 0xc000797918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x19827e0, 0xc00077e490, {0xc000797b20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc0001163b0, 0xc0001163b0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273
[036:16:22:30.301][I] (0b59f805) 642570f1-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["192.168.56.1","10.1.0.0","172.18.64.1","172.20.112.1","172.22.144.1","172.21.128.1","192.168.112.1","172.26.64.1","172.31.96.1"]}
[036:16:22:30.823][E] (0b59f805) 642570f1-diagnose-network C<-S bfbfbe8b-diagnosticsd POST /check-network-connectivity (522.876ms): failed to ping host: exit status 1
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[       common/pkg/diagkit/gather/diagnose/network.go:35 +0x182
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1982760)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1982760)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x1982760)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1982760, 0xc0002e17d8)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0002e17d8)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x125e960, 0xc000797918)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x19827e0, 0xc00077e490, {0xc000797b20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc0001163b0, 0xc0001163b0, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:130 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:96 +0x273

[FAIL] DD0032: do Docker networks overlap with host IPs? network redis-whiteboard_devcontainer_default has subnet 172.18.0.0/16 which overlaps with host IP 172.18.64.1
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 2 issues:

1 : The test: is the VM networking working?
    Failed with: network checks failed: failed to ping host: exit status 1

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.

2 : The test: do Docker networks overlap with host IPs?
    Failed with: network redis-whiteboard_devcontainer_default has subnet 172.18.0.0/16 which overlaps with host IP 172.18.64.1

If the subnet used by a Docker network overlaps with an IP used by the host, then containers
won't be able to contact the overlapping IP addresses.

Please try configuring the IP address range used by networks: in your docker-compose.yml.
See https://docs.docker.com/compose/compose-file/compose-file-v2/#ipv4_address-ipv6_address
```

My network connectivity is fine despite what it says; my containers work fine. I do not see how it could be related to this problem.

### Steps to reproduce the behavior

  1. Open Docker Desktop
  2. It usually starts flickering right away, but sometimes it does not do any flickering for a while. 
  3. Once the flickering starts, close Docker Desktop -- it will end immediately.
  4. Open Docker Desktop again -- the flickering will start immediately.

**Comment by aafloy** [comment]
For me it starts at random times, and when it does it steals focus as well, making my machine unusable.

Difference from the report above is Windows 11 Pro build 22000.434 and "No fatal errors detected" in my docker diagnose.

**Comment by ripvannwinkler** [comment]
Can confirm, same issue as @aafloy, running Windows 11 Pro 21H2 build 22000.493

**Comment by proligde** [comment]
I can confirm this exact behaviour, too. At the same time the CPU load goes up significantly. I can hear the fan spinning up, but nothing in WSL is hinting in any specific direction. But it stops immediately when I stop/restart docker desktop. In some cases docker desktop seems to hang and doesn't open. I can then just kill it using `wsl --shutdown` in windows' powershell which usually makes docker desktop respond/popup again. Then stop it -> everything goes back to normal.

Which might be important to point out: I don't have **any** docker workloads/containers running, though. It just happens randomly every couple of hours, even when I haven't even opened a WSL shell.

**Comment by ripvannwinkler** [comment]
> What might be important to point out: I don't have any docker workloads/containers running, though. It just happens randomly every couple of hours, even when I haven't even opened a WSL shell.

Same here. It seems completely random. One odd thing I noticed yesterday, but I have zero confirmation on, is that it only seems to happen when I have the Docker icon pinned to the system tray. Since I turned it off / leave it in the overflow menu, I haven't had the problem return. This doesn't mesh with original screenshot of this post, so it may just be a coincidence, but I thought maybe it's worth pointing out since it could be related to something that causes the icon repaint to happen.

**Comment by Sven-dfx** [comment]
Same issue here, I have only one Linux container running. Didn't have the issues with Win10, it started after installing Win11.

WSL2 is installed, don't have Hyper-V installed.
Win11 Version: 21H2 22000.556
Docker Desktop: 4.5.1 (74721)

**Comment by wcom939** [comment]
This happened to me too! it happens only when my laptop is connected to external monitors.

**Comment by ripvannwinkler** [comment]
> This happened to me too! it happens only when my laptop is connected to external monitors.

I only have one monitor, same issue.

**Comment by dbdness** [comment]
I am experiencing the same issue, and like mentioned earlier in the thread, it steals window focus, making it quite critical. 
My specs:

- Windows 11 V21H2, build 22000.556
- WSL2 (No Hyper-V)
- Docker Desktop 4.* and 3.*

My current workaround is downgrading Docker Desktop to [v. 2.5.0.1](https://docs.docker.com/desktop/windows/release-notes/2.x/#docker-desktop-community-2501) (!). This seems to run stable for now. 
All other tested builds between 3.* and 4.* produced this issue for me.

**Comment by capi** [comment]
The flickering starts in my case if I have Docker Desktop open _and_ copy a PNG with alpha-channel to the clipboard. (e.g. https://excalidraw.com and export to clipboard, or Greenshot with an annotation on the screenshot, ...).

Once I copy something else to the clipboard, the flickering stops. Or if I close Docker Desktop.

**Comment by ripvannwinkler** [comment]
@capi I don't use excalidraw but I do have greenshot. Can you elaborate on the greenshot with annotation bit? Steps to reproduce? I'd love to verify if that causes it on my end.

**Comment by MitchTalmadge** [comment]
I also use greenshot... good find. I'll try this out soon

**Comment by Pdijkgithub** [comment]
I’ve tried the Greenshot theory. And it is exactly as @capi mentioned. As soon as I copy a screenshot to the clipboard via Greenshot the flickering starts. When I copy a piece of text the flickering stops.

**Comment by ripvannwinkler** [comment]
Wow... just tried it and can confirm. 

1. Open Docker Desktop, wait for it to start up
2. Copy a screenshot from Greenshot to the clipboard
3. Flickering starts (Task Manager is the most obvious window to observe this on)
4. Highlight a piece of text anywhere in any program and press CTRL+C
5. Flickering stops.

Any ideas on what the clipboard would have to do with Docker Desktop flickering? Seems like a really weird interaction here...

**Comment by capi** [comment]
I'm quite sure it's related to the content of the clipboard, not to the application that produces it. As I said, I can also reproduce the whole issue using https://excalidraw.com (which is a website, in my case running in Edge), and if I export to clipboard there, I have the same phenomenon.

@ripvannwinkler Thanks for the link to the issue on Greenshot's side, which seems to confirm that it is related to the clipboard content. I learned more about the clipboard there than I'd have wanted to :-)

**Comment by pimvd** [comment]
After a little bit of testing with settings in Greenshot, this setting is fixing the problem for me:
![image](https://user-images.githubusercontent.com/1193635/162672540-bc9a4e2a-5690-4dc0-8b51-afe8538516ed.png)

**Comment by capi** [comment]
As the Greenshot issue outlines, it seems to be more a WSL than a Docker Desktop issue. I can now also reproduce the issue by having another WSL session running without having Docker Desktop open.

**Comment by MitchTalmadge** [comment]
I can confirm what others are seeing. After copying an image to my clipboard using Greenshot, the flickering started. Docker Desktop is running. I copy any text to my clipboard, and then the flickering stops. See below:

![Docker Desktop Flicker](https://user-images.githubusercontent.com/8848080/163771774-b52f9847-d98d-4ba5-b974-ea1d7d62fa17.gif)

**Comment by MitchTalmadge** [comment]
This issue looks related: https://github.com/microsoft/WSL/issues/8166

**Comment by proligde** [comment]
wow! I use greenshot, too and can confirm: copying sth. else into the clipboard resolves the issue. Great find @capi !

**Comment by MitchTalmadge** [comment]
The underlying cause was WSLg crashing and restarting in an endless loop: https://github.com/microsoft/wslg/issues/443

Updating to WSLg 1.0.34 has solved this problem for me. In an elevated prompt:

```
(base) PS C:\Users\mitch> wsl --update
Installing: Windows Subsystem for Linux
Windows Subsystem for Linux has been installed.

(base) PS C:\Users\mitch> wsl --version
WSL version: 0.60.0.0
Kernel version: 5.10.102.1
WSLg version: 1.0.34
MSRDC version: 1.2.2924
Direct3D version: 1.601.0
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.160
```
