### ISSUE TITLE
Multiple path related problems after starting a container with a volume

### ISSUE THREAD

**Issue by Rvb0rob0t** [docker/for-win#12541]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4C518D5A-B850-458C-A1F6-DCDF0E68AC8A/20220209213432

### Actual behavior
When using as a volume a host folder/file not used before, many path problems occur (realpath and readlink -f doesn't work properly, python imports fail...). In the following dump, I use the realpath command to detect when the problem occurs.
```
ruborobot@Ruben:/mnt/d
$ pwd
/mnt/d
ruborobot@Ruben:/mnt/d
$ realpath .
/mnt/d
ruborobot@Ruben:/mnt/d
$ docker run -v $(pwd)/test:/test hello-world > /dev/null
ruborobot@Ruben:/mnt/d
$ pwd
/mnt/d
ruborobot@Ruben:/mnt/d
$ realpath .
realpath: .: No such file or directory
ruborobot@Ruben:/mnt/d
$ cd .
ruborobot@Ruben:/mnt/d
$ realpath .
/mnt/d
ruborobot@Ruben:/mnt/d
$ docker run -v $(pwd)/test:/test hello-world > /dev/null
ruborobot@Ruben:/mnt/d
$ realpath .
/mnt/d
ruborobot@Ruben:/mnt/d
$ docker run -v $(pwd)/test1:/test hello-world > /dev/null
ruborobot@Ruben:/mnt/d
$ realpath .
realpath: .: No such file or directory
ruborobot@Ruben:/mnt/d
$ realpath /mnt/d
/mnt/d
ruborobot@Ruben:/mnt/d
$ realpath .
realpath: .: No such file or directory
ruborobot@Ruben:/mnt/d
$ cd /mnt/d
ruborobot@Ruben:/mnt/d
$ realpath .
/mnt/d
```

### Expected behavior
realpath (and other mentioned stuff) works properly after starting a container with a volume

### Information

  - Windows Version: 10.0.19044 compilación 19044
  - Docker Desktop Version: Docker Desktop 4.4.4 (73704)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```
[040:23:39:47.278][I] ipc.NewClient: 8d820bc2-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:40
[win/backend/pkg/service.NewClient({0x9ae8be, 0x13}, {0x0, 0x0, 0x0})
[       win/backend/pkg/service/service.go:29 +0xe8
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x11f
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[SKIP] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.
```

### Steps to reproduce the behavior

  1. With docker installed with WSL2, go to a windows file system path such as /mnt/d (or /mnt/c, it doesn't matter)
  2. In a Linux terminal, check if realpath works properly (`realpath .` should return the actual path, as `pwd` do)
  2. Run the command `docker run -v $(pwd)/test:/test hello-world`
  3. Enjoy realpath non-functioning and other bugs
  4. Run `cd .` (impressive, right?) to "solve" the problems
  5. Run the command `docker run -v $(pwd)/test:/test hello-world`
  6. Magically now there is no problem because we used the test dir before

**Comment by Rvb0rob0t** [comment]
It seems that the /mnt/d volume is remounted every time because that would explain (?) why some things doesn't work until you go to the new volume (`cd .`):
```
ruborobot@Ruben:/mnt/d
$ mount | wc -l
101
ruborobot@Ruben:/mnt/d
$ docker run -v $(pwd)/test_used:/test hello-world > /dev/null
ruborobot@Ruben:/mnt/d
$ mount | wc -l
101
ruborobot@Ruben:/mnt/d
$ docker run -v $(pwd)/test_not_used:/test hello-world > /dev/null
ruborobot@Ruben:/mnt/d
$ mount | wc -l
102
```
