### ISSUE TITLE
Unable to login because com.docker.backend.exe not utilizing root CA certificate store (nor system proxy settings)

### ISSUE THREAD

**Issue by patricknelson** [docker/for-win#12593]
Our company utilizes security software (Netskope) that intercepts and scans all TLS/SSL traffic going to and from employee machines. It appears that login to the Docker Desktop specifically fails to work. This is **presumably** because it isn't utilizing the system's root CA certificate store (and using HTTP proxy configuration in the system proxy settings doesn't alleviate the issue). This is required since the security software dynamically issues its own certificates to facilitate scanning HTTP traffic.  We came to this conclusion because we were able to add exceptions to Netskope scanning on a process-by-process basis and the login issue resolved itself once `com.docker.backend.exe` was added to the exclusion list (since our initial attempts of bypassing scanning of HTTP traffic to/from `Docker Desktop.exe` failed to resolve the problem).

Without this exception, a  "Login Failed!" error occurs with the details "unexpected EOF"  when attempting to sign in (see below). Ultimately after looking closer at our debug logs we found that the executable `com.docker.backend.exe` was also attempting to connect to `login.docker.com` during sign in. It started working _immediately_ as soon as we started bypassing HTTPS scanning for this specific process.

  - [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics (NOTE: **Not actually completed**, just flagging this as completed since it's not possible right now with Netskope, probably a separate problem out of scope of this particular ticket which is specific to login issues only)
  - Diagnostics ID: (Diagnostics cannot upload due to the nature of this error, but that's ok since it's been isolated anyway, see above.)

### Actual behavior

![image](https://user-images.githubusercontent.com/4269377/156269536-24339323-f3e4-4ecd-8ab7-75ae5c401b89.png)

### Expected behavior

That login would succeed and that the username would populate the area in the top right corner of the application.

### Information

  - Windows Version: Windows 10 (10.0.19042.1526)
  - Docker Desktop Version: Docker Desktop 4.5.1 (74721)
  - WSL2 or Hyper-V backend?   Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

<details>
<summary>
Expand to see the output I yanked from `com.docker.diagnose.exe.log` (since diagnostic uploads don't work).
</summary>

```
[060:16:01:43.320][I] ipc.NewClient: 2a9ccc79-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[	win/backend/pkg/service/service.go:42
[win/backend/pkg/service.NewClient({0x172f112, 0x13}, {0x0, 0x0, 0x0})
[	win/backend/pkg/service/service.go:31 +0xd0
[common/pkg/diagkit/gather/diagnose.init()
[	common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x11f
[060:16:01:43.377][I] ipc.NewClient: bc6e8736-com.docker.diagnose -> \\.\pipe\dockerDnsForwarder dns-forwarder
[main.gatherCmd({0xc0000420c0, 0x2, 0x4})
[	common/cmd/com.docker.diagnose/main.go:247 +0xac8
[main.main()
[	common/cmd/com.docker.diagnose/main.go:101 +0x2bb
[060:16:01:43.380][I] (a99fdee8) bc6e8736-com.docker.diagnose C->S dns-forwarder POST /diagnostics
[060:16:01:43.382][I] (a99fdee8) bc6e8736-com.docker.diagnose C<-S f36b6c67-dns-forwarder POST /diagnostics (1.9911ms): OK
[060:16:01:43.384][I] ipc.NewClient: 3d0800b2-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClientForPath(...)
[	linuxkit/pkg/desktop-host-tools/pkg/client/client.go:59
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClient({0x172f112, 0x13})
[	linuxkit/pkg/desktop-host-tools/pkg/client/client.go:53 +0xa5
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[	common/pkg/diagkit/gather/diagnose/dockerd.go:21 +0x29
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1cf2200)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1cf2200)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x1596677, 0x1cf2200)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1cf2200, 0xc000647bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1cf2280, 0xc000647bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc000647bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x1671e20, 0xc0004c3d00)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1cf2400, 0x0, {0x0, 0x0, 0x0})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[common/pkg/diagkit/gather.(*SelfDiagnose).Trigger(0x1cffac0)
[	common/pkg/diagkit/gather/diagnose.go:32 +0x6e
[created by main.gatherCmd
[	common/cmd/com.docker.diagnose/main.go:245 +0xa45
[060:16:01:43.385][I] (7c325a7b) 3d0800b2-com.docker.diagnose C->S VMDockerdAPI GET /docker
[060:16:01:43.385][I] ipc.NewClient: 44b467c8-DiagkitPKG -> \\.\pipe\dockerBackendApiServer BackendAPI
[common/pkg/backend.NewClientForPath(...)
[	common/pkg/backend/client.go:142
[common/pkg/backend.NewClient({0x1727264, 0xa})
[	common/pkg/backend/client.go:136 +0x74
[common/pkg/diagkit/gather.BackendGatherer.Gather({}, {0x1824518, 0xc000610720}, {0x182a1d8, 0xc000616120})
[	common/pkg/diagkit/gather/backend.go:32 +0x3d
[common/pkg/diagkit/gather.(*Gatherers).Gather.func1(0xc0004c7fd0, {0x1824518, 0xc000610720}, 0xc0005ac000)
[	common/pkg/diagkit/gather/gather.go:88 +0x164
[common/pkg/diagkit/gather.(*Gatherers).Gather
[	common/pkg/diagkit/gather/gather.go:85 +0x25d
[060:16:01:43.385][I] (aee70662) 44b467c8-DiagkitPKG C->S BackendAPI GET /goroutines/stacks
[060:16:01:43.386][I] (7c325a7b) 3d0800b2-com.docker.diagnose C<-S 44d9e785-VMDockerdAPI GET /docker (1.0028ms): {"current_action":"","current_action_start":"2022-03-01T23:25:25.9264711Z","engine":"running","error":""}
[060:16:01:43.386][I] ipc.NewClient: 95b16515-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.glob..func13()
[	common/pkg/diagkit/gather/diagnose/linuxkit.go:18 +0x92
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1cf2180)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1cf2180)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x1596677, 0x1cf2180)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x1cf2180, 0xc000647bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1cf2200, 0xc000647bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1cf2280, 0xc000647bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc000647bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x1671e20, 0xc0004c3d00)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1cf2400, 0x0, {0x0, 0x0, 0x0})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[common/pkg/diagkit/gather.(*SelfDiagnose).Trigger(0x1cffac0)
[	common/pkg/diagkit/gather/diagnose.go:32 +0x6e
[created by main.gatherCmd
[	common/cmd/com.docker.diagnose/main.go:245 +0xa45
[060:16:01:43.386][I] (cf5166c5) 95b16515-diagnose C->S diagnosticsd GET /ping
[060:16:01:43.388][I] (cf5166c5) 95b16515-diagnose C<-S 09bf65ac-diagnosticsd GET /ping (1.9989ms): {"serverTime":1646179303387738000}
[060:16:01:43.428][I] (aee70662) 44b467c8-DiagkitPKG C<-S d71e2870-BackendAPI GET /goroutines/stacks (43.0003ms): 0xc000612530
[060:16:01:43.430][I] (4ec9c074) 44b467c8-DiagkitPKG C->S BackendAPI GET /events
[060:16:01:43.431][I] (4ec9c074) 44b467c8-DiagkitPKG C<-S d71e2870-BackendAPI GET /events (0s): &[1646177114908040800 (from server) docker: stopping (LinuxHyperVEngine sent docker state stopping)  1646177116515944300 (from server) docker: stopped (LinuxHyperVEngine sent docker state stopped)  1646177118785474500 (from server) docker: starting (LinuxHyperVEngine sent docker state starting)  1646177125926479500 docker: running (lifecycle-server sent docker state running) ]
[060:16:01:43.433][I] ipc.NewClient: 140aa988-DiagkitPKG -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClientForPath(...)
[	linuxkit/pkg/desktop-host-tools/pkg/client/client.go:59
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClient({0x1727264, 0xa})
[	linuxkit/pkg/desktop-host-tools/pkg/client/client.go:53 +0xa5
[common/pkg/diagkit/gather.LifecycleServerGatherer.Gather({}, {0x1, 0x1}, {0x182a1d8, 0xc000616120})
[	common/pkg/diagkit/gather/lifecycleserver.go:24 +0x2f
[common/pkg/diagkit/gather.(*Gatherers).Gather.func1(0xc0004c7fd0, {0x1824518, 0xc000610720}, 0xc0005ac000)
[	common/pkg/diagkit/gather/gather.go:88 +0x164
[common/pkg/diagkit/gather.(*Gatherers).Gather
[	common/pkg/diagkit/gather/gather.go:85 +0x25d
[060:16:01:43.433][I] (ce51595a) 140aa988-DiagkitPKG C->S VMDockerdAPI GET /goroutines/stacks
[060:16:01:43.438][I] (ce51595a) 140aa988-DiagkitPKG C<-S 44d9e785-VMDockerdAPI GET /goroutines/stacks (4.9989ms): 0xc00040ecb0
[060:16:01:43.438][I] ipc.NewClient: d068f1fe-DiagkitPKG -> \\.\pipe\dockerAPIProxyControl ProxyControl
[common/pkg/diagkit/gather.ProxyAPIGatherer.Gather({}, {0x1, 0x1}, {0x182a1d8, 0xc000616120})
[	common/pkg/diagkit/gather/proxy.go:25 +0xa5
[common/pkg/diagkit/gather.(*Gatherers).Gather.func1(0xc0004c7fd0, {0x1824518, 0xc000610720}, 0xc0005ac000)
[	common/pkg/diagkit/gather/gather.go:88 +0x164
[common/pkg/diagkit/gather.(*Gatherers).Gather
[	common/pkg/diagkit/gather/gather.go:85 +0x25d
[060:16:01:43.438][I] (3bbff57d) d068f1fe-DiagkitPKG C->S ProxyControl GET /goroutines/stacks
[060:16:01:43.462][I] (3bbff57d) d068f1fe-DiagkitPKG C<-S bd16983b-proxyControl GET /goroutines/stacks (22.9994ms): 0xc000506270
[060:16:01:43.640][I] (485434bb) 2a9ccc79-com.docker.diagnose C->S com.docker.service.exe GET /hyperv/check-virtualization
[060:16:01:43.737][I] (485434bb) 2a9ccc79-com.docker.diagnose C<-S 7f6208ce-ServiceAPI GET /hyperv/check-virtualization (97.2145ms): {"HypervisorPresent":true,"VmmsServiceAlreadyRunning":true,"VmmsServiceAvailable":true,"VmmsServiceError":""}
[060:16:01:43.737][I] ipc.NewClient: e3f85659-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[win/backend/pkg/service.NewClientForPath(...)
[	win/backend/pkg/service/service.go:42
[win/backend/pkg/service.NewClient({0x172f112, 0x13}, {0x0, 0x0, 0x0})
[	win/backend/pkg/service/service.go:31 +0xd0
[common/pkg/diagkit/gather/diagnose.runBootloaderHasVirtualizationEnabled()
[	common/pkg/diagkit/gather/diagnose/bootloader_windows.go:15 +0x30
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1cf1d00)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1cf1d00)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x1596677, 0x1cf1d00)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x7, 0x1cf1d00, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x6, 0x1cf1e00, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x5, 0x1cf1e80, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x4, 0x1cf2000, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x1cf2180, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1cf2200, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1cf2280, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x1671e20, 0xc0004c3d00)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1cf2400, 0x0, {0x0, 0x0, 0x0})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[common/pkg/diagkit/gather.(*SelfDiagnose).Trigger(0x1cffac0)
[	common/pkg/diagkit/gather/diagnose.go:32 +0x6e
[created by main.gatherCmd
[	common/cmd/com.docker.diagnose/main.go:245 +0xa45
[060:16:01:43.737][I] (0443b7a9) e3f85659-com.docker.diagnose C->S com.docker.service.exe GET /hyperv/bootloader
[060:16:01:43.985][I] (0443b7a9) e3f85659-com.docker.diagnose C<-S 7f6208ce-ServiceAPI GET /hyperv/bootloader (247.8187ms): 0xc0005063c0
[060:16:01:43.985][I] (bb9c1f9e) 2a9ccc79-com.docker.diagnose C->S com.docker.service.exe POST /windowsfeatures/check: [{Name:*Hyper-V* Description:Hyper-V}]
[060:16:01:44.935][I] (bb9c1f9e) 2a9ccc79-com.docker.diagnose C<-S 7f6208ce-ServiceAPI POST /windowsfeatures/check (950.1026ms): {"NotAvailable":[],"NotEnabled":[]}
[060:16:01:45.347][I] ipc.NewClient: a9bfbfa2-diagnose -> \\.\pipe\dockerBackendApiServer BackendAPI
[common/pkg/backend.NewClientForPath(...)
[	common/pkg/backend/client.go:142
[common/pkg/backend.NewClient({0x1725c5e, 0x8})
[	common/pkg/backend/client.go:136 +0x74
[common/pkg/diagkit/gather/diagnose.glob..func8()
[	common/pkg/diagkit/gather/diagnose/ipc.go:25 +0x25
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1cf2580)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1cf2580)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x1cf2580)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1cf2580, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x1671e20, 0xc0004c3d00)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1cf2400, 0x0, {0x0, 0x0, 0x0})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[common/pkg/diagkit/gather.(*SelfDiagnose).Trigger(0x1cffac0)
[	common/pkg/diagkit/gather/diagnose.go:32 +0x6e
[created by main.gatherCmd
[	common/cmd/com.docker.diagnose/main.go:245 +0xa45
[060:16:01:45.347][I] (9e93a4f2) a9bfbfa2-diagnose C->S BackendAPI GET /ping
[060:16:01:45.348][I] (9e93a4f2) a9bfbfa2-diagnose C<-S d71e2870-BackendAPI GET /ping (522.4µs): OK
[060:16:01:48.225][I] ipc.NewClient: ad3e7ecf-diagnose -> \\.\pipe\dockerBackendNativeApiServer CSharpAPI
[common/pkg/gui.NewClientForPath({0x1725c5e, 0xc00028f5f0}, {0xc00028f620, 0x175d1b0})
[	common/pkg/gui/client.go:71 +0x3d
[common/pkg/gui.NewClient({0x1725c5e, 0x8})
[	common/pkg/gui/client.go:58 +0x5a
[common/pkg/diagkit/gather/diagnose.glob..func9()
[	common/pkg/diagkit/gather/diagnose/ipc.go:40 +0x25
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1cf1f00)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1cf1f00)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x1cf1f00)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1cf1f00, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x1671e20, 0xc0004c3d00)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1cf2400, 0x0, {0x0, 0x0, 0x0})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[common/pkg/diagkit/gather.(*SelfDiagnose).Trigger(0x1cffac0)
[	common/pkg/diagkit/gather/diagnose.go:32 +0x6e
[created by main.gatherCmd
[	common/cmd/com.docker.diagnose/main.go:245 +0xa45
[060:16:01:48.225][I] (771854b2) ad3e7ecf-diagnose C->S CSharpAPI GET /ping
[060:16:01:48.292][I] (771854b2) ad3e7ecf-diagnose C<-S 88e34c99-CSharpAPI GET /ping (66.9716ms): OK
[060:16:01:48.293][I] ipc.NewClient: baaee3fa-diagnose -> \\.\pipe\dockerDesktopLinuxEngine Proxy
[common/pkg/diagkit/gather/diagnose.glob..func11()
[	common/pkg/diagkit/gather/diagnose/ipc.go:94 +0x7e
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1cf2680)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1cf2680)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x1cf2680)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1cf2680, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x1671e20, 0xc0004c3d00)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1cf2400, 0x0, {0x0, 0x0, 0x0})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[common/pkg/diagkit/gather.(*SelfDiagnose).Trigger(0x1cffac0)
[	common/pkg/diagkit/gather/diagnose.go:32 +0x6e
[created by main.gatherCmd
[	common/cmd/com.docker.diagnose/main.go:245 +0xa45
[060:16:01:48.293][I] (f381dc61) baaee3fa-diagnose C->S Proxy GET /desktop-diagnostics/ping
[060:16:01:48.294][I] (f381dc61) baaee3fa-diagnose C<-S UnknownServer GET /desktop-diagnostics/ping (532.6µs): OK
[060:16:01:48.294][I] ipc.NewClient: 292a004a-diagnose -> \\.\pipe\dockerBackendV2 Service
[common/pkg/diagkit/gather/diagnose.glob..func12()
[	common/pkg/diagkit/gather/diagnose/ipc_windows.go:15 +0x92
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1cf2a80)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1cf2a80)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x1cf2a80)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1cf2a80, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc0003c1bc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x1671e20, 0xc0004c3d00)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1cf2400, 0x0, {0x0, 0x0, 0x0})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[common/pkg/diagkit/gather.(*SelfDiagnose).Trigger(0x1cffac0)
[	common/pkg/diagkit/gather/diagnose.go:32 +0x6e
[created by main.gatherCmd
[	common/cmd/com.docker.diagnose/main.go:245 +0xa45
[060:16:01:48.295][I] (7ee01ad7) 292a004a-diagnose C->S Service GET /ping
[060:16:01:48.350][I] (7ee01ad7) 292a004a-diagnose C<-S 7f6208ce-ServiceAPI GET /ping (54.7624ms): {"serverTime":1646179308345000000}
[060:16:01:48.372][I] ipc.NewClient: bf1e6af4-diagnose-network -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[	common/pkg/diagkit/gather/diagnose/network.go:34 +0xdd
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1cf2380)
[	common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1cf2380)
[	common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x1cf2380)
[	common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1cf2380, 0xc00070dbc0)
[	common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x100000000000000, 0xc00070dbc0)
[	common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x1671e20, 0xc0004c3d00)
[	common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1cf2400, 0x0, {0x0, 0x0, 0x0})
[	common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[common/pkg/diagkit/gather.(*SelfDiagnose).Trigger(0x1cffac0)
[	common/pkg/diagkit/gather/diagnose.go:32 +0x6e
[created by main.gatherCmd
[	common/cmd/com.docker.diagnose/main.go:245 +0xa45
[060:16:01:48.372][I] (2c1f83fc) bf1e6af4-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["172.28.144.1","10.0.0.10","10.0.0.27"]}
[060:16:01:48.464][I] (2c1f83fc) bf1e6af4-diagnose-network C<-S 09bf65ac-diagnosticsd POST /check-network-connectivity (92.1823ms): OK
```

</details>

### Steps to reproduce the behavior

1. Install/utilize Netskope or other TLS/SSL steering security software.
2. Ensure the security software's custom root CA certificate is installed on system (and that visiting a site like https://www.docker.com presents the working security software certificate instead of the real certificate)
3.  Click "Sign in"
4. Go through login steps in browser. 
5. Click button to proceed back in Docker Desktop (will receive "unexpected EOF" in screenshot above).

Wish I had a more intuitive way to reproduce. It's hard to reproduce without security software of some sort that intercepts TLS. Sorry about that 😞

**Comment by joe0BAB** [comment]
Hi @patricknelson! Thank's for reporting. I have created an internal ticket and we will investigate how to solve this. Hope to come back to you soon!

**Comment by joe0BAB** [comment]
Hi @patricknelson! The handling of proxy settings has been re-worked entirely. Could you re-test with latest version if this still is an issue for you?

**Comment by patricknelson** [comment]
Unfortunately, I can’t right now unless it’s in 4.7.1 since yet another bug is holding me back at the moment (#12721). However, if I can remember, I can try to give this a shot later once it is updated. 😕
