### ISSUE TITLE
Unable to write to the database. Exit code: 1

### ISSUE THREAD

**Issue by Farbed** [docker/for-win#1260]
### Expected behavior
Docker starts
### Actual behavior
An error occurred

Unable to write to the database. Exit code: 1
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 246
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

![image](https://user-images.githubusercontent.com/20759342/32135547-0e8e1264-bbcf-11e7-9cf4-1ccc4eabd0a7.png)

Attempted to fix by following these steps exactly:

https://github.com/docker/for-win/issues/1066

Tried twice to make sure the steps were followed properly, still not working. Also reinstalled Windows 10 Pro before doing any of these steps. (Reintsall was keep files and apps).
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
1A89E0B5-FCCC-46DA-B9AB-98422FEA12E3/2017-10-28_10-57-39
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Be me
  2. Start Docker

**Comment by pietgk** [comment]
I have the exact same issue on a newly installed Windows Server2016
