### ISSUE TITLE
Installation fails with System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by WUUUGI** [docker/for-win#12604]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

Installation does not succeed and I get no installation wizard.

```bash
Version: 4.6.0 (75818)
Sha1:
Started on: 2022/03/16 09:40:29.661
Resources: C:\Users\my-user\Downloads\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 19043
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\my-user\AppData\Local\Docker\install-log.txt
CommandLine: "C:\Users\my-user\Downloads\installer.exe"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2022-03-16T09:40:29.824319500Z][ManifestAndExistingInstallationLoader][Info   ] No install path specified, looking for default installation registry key
[2022-03-16T09:40:29.824319500Z][Installer         ][Info   ] No installation found
[2022-03-16T09:40:29.846496900Z][ManifestAndExistingInstallationLoader][Info   ] Not run as admin, relaunching with UAC prompt

Unhandled Exception: System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at System.Security.AccessControl.Win32.SetSecurityInfo(ResourceType type, String name, SafeHandle handle, SecurityInfos securityInformation, SecurityIdentifier owner, SecurityIdentifier group, GenericAcl sacl, GenericAcl dacl)
   at System.Security.AccessControl.NativeObjectSecurity.Persist(String name, SafeHandle handle, AccessControlSections includeSections, Object exceptionContext)
   at System.Security.AccessControl.NativeObjectSecurity.Persist(String name, AccessControlSections includeSections, Object exceptionContext)
   at System.Security.AccessControl.FileSystemSecurity.Persist(String fullPath)
   at Docker.Core.PermissionUtils.SetAdministratorLocalSystemOnly(ILogger logger, String path) in C:\workspaces\4.6.x\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 47
   at Docker.Core.PermissionUtils.RemoveGlobalWrite(ILogger logger, String path) in C:\workspaces\4.6.x\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 19
   at CommunityInstaller.Program.Main(String[] args)
```

### Expected behavior

Installation succeeeds and I see an installation wizard.

### Information

  - Windows Version:
  
  Windows 10 Pro, Build: 19043

  - Docker Desktop Version:

  Version: 4.6.0 (75818)

  - WSL2 or Hyper-V backend?  

   Enabled

  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

   No

### Steps to reproduce the behavior

  1. Download the installer from the docker desktop homepage
  2. Execute the installer (using shell or per double-click)
  3. Installation freezes, exception occurs in shell

**Comment by WUUUGI** [comment]
I just tried to use an older installer, v4.5.1 works for me.

**Comment by mat007** [comment]
Hi @WUUUGI and thanks for the report.
This is definitely a recent change to fix a security issue.
The log you’ve pasted, is it from the log files? Or from the standard output?

**Comment by kevin-wimmer** [comment]
Same problem. Affects all versions >= 4.6.0.

@mat007, the log provided by @WUUUGI comes from standard out.
