### ISSUE TITLE
No Local Images listed in Docker Desktop, however, docker image list lists 28 images. 

### ISSUE THREAD

**Issue by scraemon** [docker/for-win#12605]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 17EF859C-BAD0-48C9-B0DA-A19B56A93CF6/20220316132900

### Actual behavior
No Local images are listed in the 'Images' window.

### Expected behavior
28 Local images are listed in the 'Images' window.

This would be consistent with the output of running `docker image list` in WSL2 Ubuntu.

### Information

  - Windows Version: Windows 10 Pro 21H2 - OS build 19044.1586
  - Docker Desktop Version: 4.6.0 (75296)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[075:09:17:14.080][I] ipc.NewClient: 637cc5a3-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:42
[win/backend/pkg/service.NewClient({0x17600b4, 0x13}, {0x0, 0x0, 0x0})
[       win/backend/pkg/service/service.go:31 +0xd0
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x11f
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[FAIL] DD0028: is there available VM disk space? failed to retrieve the size information from ''
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[FAIL] DD0012: is the VM networking working? network checks failed: Post "http://ipc/check-network-connectivity": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[075:09:17:44.177][I] ipc.NewClient: 51b98cb1-diagnose-network -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[       common/pkg/diagkit/gather/diagnose/network.go:34 +0xdd
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1d23380)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1d23380)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x1d23380)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1d23380, 0xc0000cb830)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x10000000183a140, 0xc0000cb830)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x16a2e40, 0xc0002df970)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1d23400, 0xc0002dfb48, {0xc0002dfb00, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc000188030, 0xc000188030, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:97 +0x273
[075:09:17:44.177][I] (09ea8de3) 51b98cb1-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["172.28.16.1","192.168.1.3","192.168.0.123"]}
[075:09:17:49.195][E] (09ea8de3) 51b98cb1-diagnose-network C<-S NoResponse POST /check-network-connectivity (5.0181199s): Post "http://ipc/check-network-connectivity": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[       common/pkg/diagkit/gather/diagnose/network.go:35 +0x15b
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1d23380)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1d23380)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x1d23380)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1d23380, 0xc0000cb830)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x10000000183a140, 0xc0000cb830)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x16a2e40, 0xc0002df970)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1d23400, 0xc0002dfb48, {0xc0002dfb00, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc000188030, 0xc000188030, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:97 +0x273
[075:09:17:49.197][I] (09ea8de3-1) 51b98cb1-diagnose-network C->S diagnosticsd GET /ping
[075:09:17:49.201][I] (09ea8de3-1) 51b98cb1-diagnose-network C<-S 67559b4f-diagnosticsd GET /ping (4.1859ms): {"serverTime":1647436669059399000}
[075:09:17:49.202][I] (09ea8de3-2) 51b98cb1-diagnose-network C->S diagnosticsd POST /check-network-connectivity: {"ips":["172.28.16.1","192.168.1.3","192.168.0.123"]}
[075:09:17:54.213][E] (09ea8de3-2) 51b98cb1-diagnose-network C<-S NoResponse POST /check-network-connectivity (5.0111144s): Post "http://ipc/check-network-connectivity": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
[common/pkg/diagkit/gather/diagnose.runIsVMNetworkingOK()
[       common/pkg/diagkit/gather/diagnose/network.go:35 +0x15b
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1d23380)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1d23380)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2, 0x1d23380)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1d23380, 0xc0000cb830)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x10000000183a140, 0xc0000cb830)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x16a2e40, 0xc0002df970)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1d23400, 0xc0002dfb48, {0xc0002dfb00, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1ce
[main.checkCmd({0xc000188030, 0xc000188030, 0x4}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:97 +0x273

[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 2 issues:

1 : The test: is there available VM disk space?
    Failed with: failed to retrieve the size information from ''

Verify the available VM disk space. Try running `docker system prune` to clean up.

2 : The test: is the VM networking working?
    Failed with: network checks failed: Post "http://ipc/check-network-connectivity": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

VM seems to have a network connectivity issue. Please check your host firewall and anti-virus settings in case they are blocking the VM.

### Steps to reproduce the behavior

  1. Open Docker Deskop.
  2. Click on Images.

**Comment by scraemon** [comment]
After restarting Windows, the issue is no longer present - the Local images once again show up in the Images window.
