### ISSUE TITLE
VPN Passthrough not working

### ISSUE THREAD

**Issue by crowne** [docker/for-win#12636]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DA69F136-1880-46C7-88EB-80FAF110A06D/20220331082056

### Actual behavior
Cannot reach hosts on VPN from within container

### Expected behavior
VPN Host is reachable from windows outside of container e.g. powershell,
[Docs](https://docs.docker.com/desktop/windows/networking/) say that VPN traffic should passthrough to windows,
it seems like this is not happening 

### Information

  - Windows Version: Windows 10 Pro Version 21H2 (OS Build 19044.1586)
  - Docker Desktop Version: Docker Desktop 4.6.1 (76265)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[2022-03-31T07:48:38.509828600Z][com.docker.diagnose.exe][I] ipc.NewClient: d9b73639-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:42
[win/backend/pkg/service.NewClient({0x14714c4, 0x13}, {0x0, 0x0, 0x0})
[       win/backend/pkg/service/service.go:31 +0xd0
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x11f
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
No fatal errors detected.

### Steps to reproduce the behavior

  1. Reboot computer
  2. Connect to VPN using Cisco AnyConnect
  3. Open powershell
  ```shell
> ping 10.1.160.22
Pinging 10.1.160.22 with 32 bytes of data:
Reply from 10.1.160.22: bytes=32 time=189ms TTL=64
Reply from 10.1.160.22: bytes=32 time=192ms TTL=64

Ping statistics for 10.1.160.22:
    Packets: Sent = 2, Received = 2, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 189ms, Maximum = 192ms, Average = 190ms

> tracert 10.1.160.22

Tracing route to 10.1.160.22 over a maximum of 30 hops

  1   391 ms   303 ms   188 ms  10.1.160.22

Trace complete.
  ```
  4. Run busybox interactive shell
  ```shell
> docker run --rm -it busybox sh
>
> ping -w 3 10.1.160.22
PING 10.1.160.22 (10.1.160.22): 56 data bytes

--- 10.1.160.22 ping statistics ---
3 packets transmitted, 0 packets received, 100% packet loss
>
> traceroute 10.1.160.22
traceroute to 10.1.160.22 (10.1.160.22), 30 hops max, 46 byte packets
 1  172.240.0.1 (172.240.0.1)  0.004 ms  0.004 ms  0.002 ms
 2  10.1.0.1 (10.1.0.1)  3108.017 ms !H  3155.501 ms !H  3119.533 ms !H
  ```
  
I have tried setting "bip" and "default-address-pools" in daemon.json to various values ... but no success.

**Comment by crowne** [comment]
I think the problem here is that Cisco AnyConnect is configured to use split tunnels,
there are several secure routes defined for various subnets e.g. 10.1.160.0/24
and a single Non-secure route 0.0.0.0/0 for all other traffic.

Can docker be configured to route the traffic given this setup?
