### ISSUE TITLE
Docker run -v /c/path: creates odd directory

### ISSUE THREAD

**Issue by RandyAvis** [docker/for-win#12646]
We are using Docker Desktop on Windows for our development environment. The issue stated here did not appear until the last update - 4.6.1 (76265)

We run a git bash script to set up a number of variables based on the target environment. We load finished product into a partitioned network running linux desktops, so we want to use shell scripts for everything.

I am simplifying somewhat to illustrate the problem. Here is the command we run.

docker run -v /c/Users/ravis1/git/docker/logs/baseline:/tomcat/logs:z $dockerRepo/sxnimbus/baseline:local

$dockerRepo varies by environment

when I run this command from a git bash window, it creates a baseline;C directory in the logs folder. When I run it from a Windows command line window I do not get the error.

When I originally wrote this it worked fine on my machine. When my team started trying it they were seeing the directories, and log files were not appearing in either logs/baseline or logs/baseline:C

Since I upgraded to this version I see the same problem. Is there a workaround, or a fix in the works?

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
baseline;C directory created in the logs directory. Mapped tomcat log files do not appear either here or in baseline directory
### Expected behavior
Directory not created, logs appear in baseline directory as expected.
### Information
  - Windows Version: 10
  - Docker Desktop Version: 4.6.1 (76265)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
[2022-04-05T20:36:01.110943100Z][com.docker.diagnose.exe][I] ipc.NewClient: 441440e8-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:42
[win/backend/pkg/service.NewClient({0xbe14c4, 0x13}, {0x0, 0x0, 0x0})
[       win/backend/pkg/service/service.go:31 +0xd0
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x11f
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0031: does the Docker API work?
[PASS] DD0004: is the Docker engine running?
[PASS] DD0011: are the LinuxKit services running?
[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0015: are the binary symlinks installed?
[PASS] DD0003: is the Docker CLI working?
[PASS] DD0013: is the $PATH ok?
[FAIL] DD0005: is the user in the docker-users group? The specified domain either does not exist or could not be contacted.
[PASS] DD0007: is the backend responding?
[PASS] DD0014: are the backend processes running?
[PASS] DD0008: is the native API responding?
[PASS] DD0009: is the vpnkit API responding?
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[PASS] DD0012: is the VM networking working?
[PASS] DD0032: do Docker networks overlap with host IPs?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?

Please investigate the following 1 issue:

1 : The test: is the user in the docker-users group?
    Failed with: The specified domain either does not exist or could not be contacted.

The current user must be member of the docker-users group. Press the Win + R keys to open Run, type lusrmgr.msc into Run, followed by Enter to open Local Users and Groups.

****************** NOTE: I have a domain account DOMAIN/ravis1 and it IS in the docker-users group. Regardless the run -v mapping was working until this last update.

### Steps to reproduce the behavior

  1. ... See above
  2. ...

**Comment by RandyAvis** [comment]
Running the command from a windows command prompt works, but that is undesirable behavior as we need one script for our local development environment and another for the linux environment.
