### ISSUE TITLE
Windows 10 Startup Error - ErrorActionPreference - Stop: The object already exists.

### ISSUE THREAD

**Issue by JoshCode** [docker/for-win#1264]
### Expected behavior
Start of the program

### Actual behavior
Error

```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.


   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

### Information

Diagnostic ID: 7FFF6CFF-5CA3-4CB9-9D10-F53FF8683CDA/2017-10-30_04-30-51
Windows version: Windows 10 Education version 1709, build 16299
Log file: [log.txt](https://github.com/docker/for-win/files/1425889/log.txt)

### Steps to reproduce the behavior

1. Install Docker CE on Windows 10 Education 1709
2. Run

**Comment by JoshCode** [comment]
Any news on this issue?

**Comment by JoshCode** [comment]
I just installed the Edge version of Docker and that seems to fix it. Also switching to Windows containers on the stable version will fix it, but on Edge, Linux containers also work.
