### ISSUE TITLE
Docker Desktop 4.7.1 fails install 'unpacking failed: Data Error'

### ISSUE THREAD

**Issue by mattjwarren** [docker/for-win#12680]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Install fails with;

Unpacking failed: Data Error
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

### Expected behavior

Install completes

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

& : The term 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:3
+ & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe"  ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...er.diagnose.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
    
### Steps to reproduce the behavior

  1. download docker installer for windows
  2. run it

I have tried multiple times with a fresh download each time, same issue.

**Comment by Katylar** [comment]
Exact same issue on my end.

**Comment by buts101** [comment]
same issue with 4.9.1... unpacking is taking way too long time but extracting it via 7zip is quick.

**Comment by wmanka** [comment]
I also have this issue with version 4.9.1

**Comment by smartwombat** [comment]
Similar issue with 4.10.0 (82025)

[install-log-admin.txt](https://github.com/docker/for-win/files/9092720/install-log-admin.txt)

**Comment by drakor007** [comment]
Similar issue with 4.12.0 (85629)
Unpacking failed: File does not exist: C:\Users\dklem\AppData\Local\Temp\DockerDesktop\2zxk1ix4nxa
   v CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- Konec trasování zásobníku z předchozího místa, ze kterého byla vyvolána výjimka ---
   v System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   v System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   v CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

**Comment by Nimmo89** [comment]
Similar issue with 4.13.0 (89412)
Unpacking failed: Data Error
   в CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

**Comment by BlueAlder** [comment]
Getting the same issue with 4.16.1 (95567)

Unpacking failed: Data Error
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

**Comment by LucaMaurelliC** [comment]
Same issue on Windows 10 Pro, Docker 4.17.0

**Comment by mavega998** [comment]
I have the same issue with Windows 11 Pro. Docker 4.17.1
```
[2023-04-03T01:29:36.828448900Z][InstallWorkflow][E] Installation failed System.Exception: Unpacking failed: Data Error ---> SharpCompress.Compressors.LZMA.DataErrorException: Data Error
   at SharpCompress.Compressors.LZMA.Decoder.Code(Int32 dictionarySize, OutWindow outWindow, Decoder rangeDecoder)
   at SharpCompress.Compressors.LZMA.LzmaStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.ReadByte()
   at SharpCompress.Compressors.LZMA.Bcj2DecoderStream.<Run>d__20.MoveNext()
   at SharpCompress.Compressors.LZMA.Bcj2DecoderStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at SharpCompress.IO.ReadOnlySubStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at SharpCompress.Common.EntryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at SharpCompress.Utility.TransferTo(Stream source, Stream destination, Entry entry, IReaderExtractionListener readerExtractionListener)
   at SharpCompress.Readers.AbstractReader`2.Write(Stream writeStream)
   at SharpCompress.Readers.AbstractReader`2.WriteEntryTo(Stream writableStream)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.UnpackArtifactsStep.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[2023-04-03T01:29:36.830448300Z][InstallWorkflow][I] Rollbacking component CommunityInstaller.ExtractManifestStep
[2023-04-03T01:29:36.831448200Z][InstallWorkflow][I] Rollbacking component CommunityInstaller.DownloadStep
```

**Comment by AppleNorris** [comment]
I probably have found a fix.
Applicable only if you have this error: "CommunityInstaller.InstallWorkflow.d__30.MoveNext()"
Open admin PowerShell, run Get-ExecutionPolicy. If it returns Restricted, then run Set-ExecutionPolicy AllSigned.
It's the same policy that doesn't allow to install Chocolatey, really, though you probably don't need to bypass it.

**Comment by sharkymcdongles** [comment]
I fixed this by uninstalling docker desktop fully. 
Deleting all docker folders in program files / program data / appdata for all users.
Shutting down wsl via wsl --shutdown.
Installing latest version as admin.
Running this in powershell as admin:
```
wsl --unregister docker-desktop
wsl --unregister docker-desktop-data
```

Then starting docker desktop.

**Comment by Solotov** [comment]
> I probably have found a fix. Applicable only if you have this error: "CommunityInstaller.InstallWorkflow.d__30.MoveNext()" Open admin PowerShell, run Get-ExecutionPolicy. If it returns Restricted, then run Set-ExecutionPolicy AllSigned. It's the same policy that doesn't allow to install Chocolatey, really, though you probably don't need to bypass it.

### I was getting this error when installing or upgrading to new version

> Unpacking failed: Data Error
>   en Docker.Installer.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
> --- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
>   en System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>   en System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>   en Docker.Installer.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

### Error is solved after execution
`Set-ExecutionPolicy AllSigned`

_! Thank you @AppleNorris for the solution!!!_
