### ISSUE TITLE
Docker Desktop failed to stop

### ISSUE THREAD

**Issue by Antonytm** [docker/for-win#12688]
- [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

When I try to run Docker Desktop, I see message:
Docker Desktop failed to stop...

Builtin diagnostics tool fails with message:
`Cannot process diagnostics. Reason: Error invoking remote method 'desktop-go-backend': [object Object]`

### Information
I got this problem the second time.  
The first time, I uninstalled Docker, installed it again and it was fixed. (Repair without uninstallation didn't help)

  - Windows Version: Windows 10 Pro 21H1 19043.1645
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No
  AMD Ryzen 9 5900X 12-Core Processor               3.70 GHz

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

```
[2022-04-25T11:11:30.726946700Z][com.docker.diagnose.exe][I] ipc.NewClient: f9bffc71-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service.exe
[goroutine 1 [running, locked to thread]:
[win/backend/pkg/service.NewClientForPath(...)
[       win/backend/pkg/service/service.go:42
[win/backend/pkg/service.NewClient({0xcfdbdb, 0x13}, {0x0, 0x0, 0x0})
[       win/backend/pkg/service/service.go:31 +0xd0
[common/pkg/diagkit/gather/diagnose.init()
[       common/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x11f
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[SKIP] DD0028: is there available VM disk space?
[FAIL] DD0031: does the Docker API work? error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-04-25T11:11:30.778539100Z][com.docker.diagnose.exe][I] ipc.NewClient: b3dfd4f3-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClientForPath(...)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:59
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClient({0xcfdbdb, 0x13})
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:53 +0xa5
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:21 +0x29
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1275680)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0xb62437?, 0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1275680, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1275700?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xc3de00?, 0xc00035f898)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1275880, 0xc00011e001?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0001163b0?, 0xc0001163b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:97 +0x27f
[2022-04-25T11:11:30.778539100Z][com.docker.diagnose.exe][I] (3e38adb4) b3dfd4f3-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2022-04-25T11:11:30.778539100Z][com.docker.diagnose.exe][E] (3e38adb4) b3dfd4f3-com.docker.diagnose C<-S NoResponse GET /docker (0s): Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc000230530)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:105 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x32
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1275680)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0xb62437?, 0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1275680, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1275700?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xc3de00?, 0xc00035f898)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1275880, 0xc00011e001?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0001163b0?, 0xc0001163b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:97 +0x27f
[2022-04-25T11:11:30.779055100Z][com.docker.diagnose.exe][I] (3e38adb4-1) b3dfd4f3-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-04-25T11:11:30.779055100Z][com.docker.diagnose.exe][E] (3e38adb4-1) b3dfd4f3-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc000230530)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:105 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x32
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1275680)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0xb62437?, 0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1275680, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1275700?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xc3de00?, 0xc00035f898)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1275880, 0xc00011e001?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0001163b0?, 0xc0001163b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:97 +0x27f
[2022-04-25T11:11:31.781865200Z][com.docker.diagnose.exe][I] (3e38adb4-2) b3dfd4f3-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-04-25T11:11:31.781865200Z][com.docker.diagnose.exe][E] (3e38adb4-2) b3dfd4f3-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc000230530)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:105 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x32
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1275680)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0xb62437?, 0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1275680, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1275700?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xc3de00?, 0xc00035f898)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1275880, 0xc00011e001?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0001163b0?, 0xc0001163b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:97 +0x27f
[2022-04-25T11:11:32.792007200Z][com.docker.diagnose.exe][I] (3e38adb4-3) b3dfd4f3-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-04-25T11:11:32.792007200Z][com.docker.diagnose.exe][E] (3e38adb4-3) b3dfd4f3-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc000230530)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:105 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x32
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1275680)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0xb62437?, 0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1275680, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1275700?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xc3de00?, 0xc00035f898)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1275880, 0xc00011e001?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0001163b0?, 0xc0001163b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:97 +0x27f
[2022-04-25T11:11:33.798238500Z][com.docker.diagnose.exe][I] (3e38adb4-4) b3dfd4f3-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-04-25T11:11:33.798238500Z][com.docker.diagnose.exe][E] (3e38adb4-4) b3dfd4f3-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc000230530)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:105 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x32
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1275680)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0xb62437?, 0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1275680, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1275700?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xc3de00?, 0xc00035f898)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1275880, 0xc00011e001?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0001163b0?, 0xc0001163b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:97 +0x27f
[2022-04-25T11:11:34.806535200Z][com.docker.diagnose.exe][I] (3e38adb4-5) b3dfd4f3-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-04-25T11:11:34.806535200Z][com.docker.diagnose.exe][E] (3e38adb4-5) b3dfd4f3-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc000230530)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:105 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x32
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1275680)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0xb62437?, 0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1275680, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1275700?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xc3de00?, 0xc00035f898)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1275880, 0xc00011e001?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0001163b0?, 0xc0001163b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:97 +0x27f
[2022-04-25T11:11:35.809091300Z][com.docker.diagnose.exe][I] (3e38adb4-6) b3dfd4f3-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-04-25T11:11:35.809091300Z][com.docker.diagnose.exe][E] (3e38adb4-6) b3dfd4f3-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc000230530)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:105 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x32
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1275680)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0xb62437?, 0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1275680, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1275700?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xc3de00?, 0xc00035f898)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1275880, 0xc00011e001?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0001163b0?, 0xc0001163b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:97 +0x27f
[2022-04-25T11:11:36.810694900Z][com.docker.diagnose.exe][I] (3e38adb4-7) b3dfd4f3-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-04-25T11:11:36.810694900Z][com.docker.diagnose.exe][E] (3e38adb4-7) b3dfd4f3-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc000230530)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:105 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x32
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1275680)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0xb62437?, 0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1275680, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1275700?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xc3de00?, 0xc00035f898)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1275880, 0xc00011e001?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0001163b0?, 0xc0001163b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:97 +0x27f
[2022-04-25T11:11:37.821341400Z][com.docker.diagnose.exe][I] (3e38adb4-8) b3dfd4f3-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-04-25T11:11:37.821341400Z][com.docker.diagnose.exe][E] (3e38adb4-8) b3dfd4f3-com.docker.diagnose C<-S NoResponse GET /ping (59.7µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[linuxkit/pkg/desktop-host-tools/pkg/client.(*lifecycleClient).GetDockerState(0xc000230530)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:105 +0x5c
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:22 +0x32
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1275680)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0xb62437?, 0x1275680)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1275680, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1275700?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xc3de00?, 0xc00035f898)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1275880, 0xc00011e001?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0001163b0?, 0xc0001163b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:97 +0x27f

[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[2022-04-25T11:11:37.824494200Z][com.docker.diagnose.exe][I] ipc.NewClient: 33c19825-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.glob..func13()
[       common/pkg/diagkit/gather/diagnose/linuxkit.go:18 +0x92
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1275600)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1275600)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0xb62437?, 0x1275600)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x1275600, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1275680?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1275700?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xc3de00?, 0xc00035f898)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1275880, 0xc00011e001?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0001163b0?, 0xc0001163b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:97 +0x27f
[2022-04-25T11:11:37.824494200Z][com.docker.diagnose.exe][I] (7c2d7973) 33c19825-diagnose C->S diagnosticsd GET /ping
[2022-04-25T11:11:37.824494200Z][com.docker.diagnose.exe][E] (7c2d7973) 33c19825-diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[common/pkg/diagkit/gather/diagnose.glob..func13()
[       common/pkg/diagkit/gather/diagnose/linuxkit.go:19 +0x9e
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1275600)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x1275600)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0xb62437?, 0x1275600)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x1275600, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1275680?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1275700?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb00000012?, 0xc00061f738)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0xc3de00?, 0xc00035f898)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x1275880, 0xc00011e001?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1cb
[main.checkCmd({0xc0001163b0?, 0xc0001163b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:131 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:97 +0x27f

[PASS] DD0016: is the LinuxKit VM running?
[PASS] DD0001: is the application running?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[FAIL] DD0025: are WSL distros installed? WSL Distribution docker-desktop is missing
[PASS] DD0026: is the WSL LxssManager service running?
[FAIL] DD0029: is the WSL 2 Linux filesystem corrupt? exit status 0xffffffff
[PASS] DD0015: are the binary symlinks installed?
error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0013: is the $PATH ok?
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0007: is the backend responding?
2022/04/25 14:11:39 exit status 0xffffffff
```

**Comment by fredericdalleau** [comment]
Could you upload diagnostic informations? You can refer to https://docs.docker.com/desktop/windows/troubleshoot/#diagnose-and-feedback
There is also the possibility to diagnostic from the command line if the UI fails to start.
Thanks,

**Comment by StefanScherer** [comment]
The diagnostics shows some errors with the WSL 2 distro or filesystem. 🤔 
Could you run `wsl.exe -l -v` manually and show the results?
What could help is running these commands

```
wsl --shutdown
wsl -l -v
wsl --unregister docker-desktop
wsl -l -v
```
to remove only the docker-desktop distro. The data distro is kept untouched. The next start of Docker Desktop will create the docker-desktop distro again.
