### ISSUE TITLE
Can't install Docker 3.6.0 on windows 10 Pro with WSL 2 enabled- Unhandled exception

### ISSUE THREAD

**Issue by mikeazores** [docker/for-win#12697]
- [x ] I have tried with the latest version of Docker Desktop
  - [x ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

Can't install Docker on windows 10 Pro with WSL 2 enabled in Ubuntu distro. Get an error when installing.

I had a prior version (a version from 1 year ago) of Docker Desktop installed with WSL1. I enabled WSL2 and Docker Desktop was running fine. Then I tried to update docker using "find updates" option inside Docker, it started updating but then I got an error and the installation was aborted. Docker was uninstalled from my computer and NO new version was installed. So, I tried to install it again, manually downloading Docker installer and double clicking "Docker Desktop Installer.exe" but nothing happens.  Then followed the steps stated bellow (steps to reproduce the error) getting an exception error.

I tried also restarting my computer and again with the same error.

### Expected behavior

Install the program normally

### Information

  - Windows Version: 10 21H2 Build 1944.1645
  - Docker Desktop Version: Latest
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Steps to reproduce the behavior

  1. Download Docker Desktop for Windows
  2. Open powershell with admin rights
  3. Enter:  Start-Process '...pathto\Docker Desktop Installer.exe' -Wait install
  4. Got the error:

Unhandled Exception: System.ComponentModel.Win32Exception: The system cannot find the path specified
   at Docker.Core.CanonicalizePath.CheckSymlinkForSubPath(String path, String pathEnd) in C:\workspaces\PR-17739\src\github.com\docker\pinata\win\src\Docker.Core\CanonicalizePath.cs:line 133
   at Docker.Core.PermissionUtils.CheckPath(String path, Boolean allowDockerAppData) in C:\workspaces\PR-17739\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 233
   at Docker.Core.PermissionUtils.CheckACLBeforeRestrictAndCheckSymlink(ILogger logger, String path) in C:\workspaces\PR-17739\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 93
   at Docker.Core.PermissionUtils.ApplyACLOnChildren(ILogger logger, String path, Int32 recurse) in C:\workspaces\PR-17739\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 78
   at Docker.Core.PermissionUtils.ApplyACLOnChildren(ILogger logger, String path, Int32 recurse) in C:\workspaces\PR-17739\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 62
   at Docker.Core.PermissionUtils.RemoveGlobalWrite(ILogger logger, String path) in C:\workspaces\PR-17739\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 21
   at CommunityInstaller.Program.Main(String[] args)

**UPDATE:** I was able to install Docker Desktop 3.5.2.

**Comment by StefanScherer** [comment]
We don't have the capacity to investigate very old versions of Docker Desktop. Could you try with the latest 4.8.1?
If the problem still exists please open a new ticket.
