### ISSUE TITLE
WindowsContainersController.FixPermissions sets acls too deep

### ISSUE THREAD

**Issue by anderslaub** [docker/for-win#12701]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features

### Actual behavior

Entrypoints located in `C:\{folder}` is not allowed to run as `ContainerUser`. 

Any access control set on files or folders is overridden when docker is restarted and ContainerUser is removed as owner of files and folders created during build.

### Expected behavior

Access control lists within the container filesystem should not be modified by the docker service on startup.

### Information

  - Windows Version: 10 21H2
  - Docker Desktop Version: 4.7.1
  - WSL2 or Hyper-V backend?   hyperv
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

When upgrading from Docker Desktop 4.6.1 to 4.7.1 some containers failed to start due to missing file system permissions.

I noticed that setting acls explicitly to allow users during container build solved the issue. 

But only until docker service was restarted - then any acls set was gone and only local admin and system was allowed.

Adding an audit rule on changepermission to the folder within the data dir showed that it was com.docker.service that changed the permissions.

![image](https://user-images.githubusercontent.com/2105432/166842262-c84cfc0b-8245-451d-a2c0-98b8893c7098.png)

Further investigation led me to `WindowsContainersController.Start` > `FixPermissions `> `PermissionUtils.SetAdministratorLocalSystemOnly `> `ApplyACLOnChildren `where I noticed that acls are updated 4 levels down while 3 levels would have been sufficient.

It is a breaking change with significant impact that apps no longer can reside directly in a folder on the c drive. It is extremely common to deploy f. ex. netcore apps etc. to `C:\App` or similar which is not currently possible. Any apps would need to be deployed 2 levels deeper - or run as ContainerAdministrator which I fear some will see as a viable mitigation (don't).

The issue is easy to reproduce and others have confirmed experiencing the same issues following an upgrade.

### Steps to reproduce the behavior

  1.  Build below dockerfile
  ````
# escape=`

FROM mcr.microsoft.com/windows/nanoserver:1809

WORKDIR /app
RUN echo echo ¯\_(?)_/¯ > test.bat

ENTRYPOINT "C:\app\test.bat"
````
  3. Run it
![image](https://user-images.githubusercontent.com/2105432/166840313-a2d336d1-11e4-439c-9291-728727da2702.png)
  4. Restart Docker
  5. Run it again
  
![image](https://user-images.githubusercontent.com/2105432/166841358-a53027e6-2dff-45a5-aac2-1c53ee4b555f.png)

  6. Last; make a change to the RUN command in the Dockerfile and build the container again (using cache). 
 
![image](https://user-images.githubusercontent.com/2105432/166841609-b060042f-6500-4962-b13c-e404d653a25a.png)

ContainerUser no longer can access C:\App in the cache layer even though ContainerUser really should be the owner.

Please help solve this quickly or provide more information on these recent unannounced changes in behaviour. 

Thanks.

Related issue reported here: https://github.com/docker/for-win/issues/12684

**Comment by michaellwest** [comment]
I have experienced this issue over the last few days. Quite the pain.

**Comment by RAhnemann** [comment]
Seeing this as well. Reverting back to 4.6.1 resolves the issues.

**Comment by pbering** [comment]
seems to only happen using `mcr.microsoft.com/windows/nanoserver` ... works fine using `mcr.microsoft.com/windows/servercore`  both in `hyperv` and `process` isolation.

**Comment by anderslaub** [comment]
@pbering This is by "design" and due to mcr.microsoft.com/windows/servercore running as `ContainerAdministrator` by default (which really should be stopped since it enable easy container escapes if it is breached since ContainerAdministrator is local admin on the host too).

You can try this example Dockerfile to confirm that the same permission issues occur when using servercore as base:

```
# escape=`

FROM mcr.microsoft.com/windows/servercore:ltsc2019

USER ContainerUser

WORKDIR /app
RUN echo echo ¯\_(?)_/¯ > test.bat

ENTRYPOINT "C:\app\test.bat"
```

Inspecting the access control lists in the data dir also clearly shows that permissions in the fs are changed on restart - no matter the base image.

![image](https://user-images.githubusercontent.com/2105432/166896180-31aa5c8e-1462-454f-b417-0262d690a788.png)

**Comment by pbering** [comment]
yeah, something is broken with the ACL's when running as `ContainerUser`. Running with `--user ContainerAdministrator` works as a temporary workaround.

**Comment by steviemcg** [comment]
Same issue here. Tried playing around with ContainerUser and ContainerAdministrator but in the end I gave up and reverted to 4.6.1.

**Comment by ebriney** [comment]
Hello @anderslaub, can you try that build: https://desktop-stage.docker.com/win/main/amd64/79163/Docker%20Desktop%20Installer.exe
You will need to rebuild your image or reset to default.
But it seems to work on your simple example on my machine.

**Comment by michaellwest** [comment]
First attempt appears to have worked.

**Comment by anderslaub** [comment]
Thank you so much @ebriney I can confirm that it works too.

I can't help it but I had to peak on the changes made and I can see that you now skip the `windowsfilter` folder in `PermissionUtils.ApplyACLOnChildren(..)` 

Can you elaborate a bit on why the acls has to be ensured restricted to local admin & system only in the rest of the docker data root folder?

It runs on every `WindowsContainerController` `Start `which from the looks of it was something that was introduced in v4.8.0. 

From an outsiders perspective, just looking through the reflected code it could seem to have been rushed in, which makes me quite curious on why it's needed in the first place.

**Comment by jarllomax** [comment]
Just tried to install 4.9.0 but I get a message saying that docker-desktop is up to date, even though I'm currently on 4.8.2 :-( 

So no luck installing it and checking that this will fix the permission issues we currently have.
I will try to completely remove 4.8.2 and then install 4.9.0, just though you'd like to know

**Comment by djarvis** [comment]
@ebriney We are seeing this exact issue just recently, out of the blue, on Windows Server 2019 with DockerMsftProvider and the docker pacakge:

Install-Module -Name DockerMsftProvider -Repository PSGallery  -Force
Install-Package -Name docker -ProviderName DockerMsftProvider -Force

The docker version is:

Docker version 20.10.9, build 591094d

Previous docker version was 20.10.5.

Does this issue apply to this as well and is there a newer version with a fix?

**Comment by guyelight** [comment]
I'm running into a similar issue in 4.9.0. When Docker Desktop Starts it attempts to change ACLs and it is breaking.  It will never start again, until I manage to delete my Docker directory via cocker-ci-zap.exe.  It appears my image and others has a symlink in it, breaking the start of Docker:

System.Exception:
Path contains symlink: D:\ProgramData\Docker\windowsfilter\02334b1348055d79ea9243eb6385402429db79735f45d2fa94c7028981ec6487\Files\docker-entrypoint-initdb.d
at Docker.Core.PermissionUtils.CheckPath(String path, Boolean allowDockerAppData) in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 272
at Docker.Core.PermissionUtils.CheckACLBeforeRestrictAndCheckSymlink(ILogger logger, String path) in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 94
at Docker.Core.PermissionUtils.ApplyACLOnChildren(ILogger logger, String path, Int32 recurse) in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 47
at Docker.Core.PermissionUtils.ApplyACLOnChildren(ILogger logger, String path, Int32 recurse) in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 63
at Docker.Core.PermissionUtils.ApplyACLOnChildren(ILogger logger, String path, Int32 recurse) in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 63
at Docker.Core.PermissionUtils.ApplyACLOnChildren(ILogger logger, String path, Int32 recurse) in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 63
at Docker.Core.PermissionUtils.ApplyACLOnChildren(ILogger logger, String path, Int32 recurse) in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 63
at Docker.Backend.HttpAPI.WindowsContainersController.FixPermissions(String path) in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\WindowsContainersController.cs:line 72
at Docker.Backend.HttpAPI.WindowsContainersController.Start(WindowsContainerStartRequest request) in C:\workspaces\PR-18120\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\WindowsContainersController.cs:line 37
at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

So I can never run PostgreSql as a Windows Container.

I have found I need to go back to 4.5.1 to have a stable environment

**Comment by ebriney** [comment]
@djarvis It's not related to the issue in this ticket which only apply to Docker Desktop
Is someone can test this build https://desktop-stage.docker.com/win/main/amd64/81206/Docker%20Desktop%20Installer.exe
cc @pbering @guyelight

**Comment by zhaotq** [comment]
After installation, docker desktop not starting up.

**Comment by pbering** [comment]
@ebriney I've testet the 4.10.0 version and it seems to be working, I can:

1. build
2. up
3. restart and then up still works 

I've noticed that there are some debug info being printet during build: 

```
Building solr-init
[2022-06-16T08:25:20.177759700Z][docker-credential-desktop][I] set path configuration to OnHost
[2022-06-16T08:25:20.254496300Z][docker-credential-desktop][I] set path configuration to OnHost
[2022-06-16T08:25:20.331550300Z][docker-credential-desktop][I] set path configuration to OnHost
[2022-06-16T08:25:20.407578900Z][docker-credential-desktop][I] set path configuration to OnHost
[2022-06-16T08:25:20.484186500Z][docker-credential-desktop][I] set path configuration to OnHost
[2022-06-16T08:25:20.562237900Z][docker-credential-desktop][I] set path configuration to OnHost
[2022-06-16T08:25:20.639151500Z][docker-credential-desktop][I] set path configuration to OnHost
[2022-06-16T08:25:20.716856200Z][docker-credential-desktop][I] set path configuration to OnHost
Sending build context to Docker daemon  2.048kB
```

Guess it some debug stuff of yours?

**Comment by ebriney** [comment]
Sorry we had an issue on main and the build I have provided has a bug that's been fixed now, you can try this new build @zhaotq : https://desktop-stage.docker.com/win/main/amd64/81320/Docker%20Desktop%20Installer.exe
Thanks @pbering I will check that

**Comment by pbering** [comment]
The official 4.10.0 (82025) release it also working and there are no debug messages either! Thank you 🥇
