### ISSUE TITLE
Failed Docker Desktop 4.10.1 installation on Windows 10: Component CommunityInstaller.EnableFeaturesAction failed: Not found

### ISSUE THREAD

**Issue by woutkonings** [docker/for-win#12840]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: not available, as it's installation

### Actual behavior
I am having issues again since an overnight update of Windows. My Docker Desktop failed to startup, so I decided to reinstall. Now the reinstall is failing. I am on Microsoft Windows [Version 10.0.19044.1826] trying to install Docker Desktop 4.10.1 and getting the following error:

Component CommunityInstaller.EnableFeaturesAction failed: Not found with CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext() with System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() with System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) with CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

I have already tried:

    running the installation as admin
    unchecking the checkboxes at the start of installation
    enabling the Windows Management Instrumentation service as admin
    removing the docker folders on C: manually

### Expected behavior
The installation to work.

### Information

  - Windows Version: 10.0.19044.1826
  - Docker Desktop Version: 4.10.1
  - WSL2 or Hyper-V backend?  Attempted both.
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:  No.

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
Not available.

**Comment by HuynhHuuThang** [comment]
i am having a similar issue as you are, here is my error:

Component CommunityInstaller.EnableFeaturesAction failed: 
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

Have anyone know how to fix it?

**Comment by seaBFH** [comment]
probably not same issue..

Component CommunityInstaller.EnableFeaturesAction failed: 
   在 CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

**Comment by tinybigideas** [comment]
Same issue but with 4.12.0

**Comment by FaizeKhan12** [comment]
**Having the same issue:**
Component CommunityInstaller.EnableFeaturesAction failed: 
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()


**Here is the logs file for the installation:**
-------------------------------------------------------------------------------->8
Version: 4.13.0 (89412)
Sha1: 
Started on: 2022/10/25 18:54:16.320
Resources: C:\Users\alifa\Downloads\resources
OS: Windows 10 Home
Edition: Core
Id: 2009
Build: 22000
BuildLabName: 22000.1.amd64fre.co_release.210604-1628
File: C:\ProgramData\DockerDesktop\install-log-admin.txt
CommandLine: "C:\Users\alifa\Downloads\Docker Desktop Installer (3).exe" "install" -package "res:DockerDesktop" --relaunch-as-admin
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2022-10-25T18:54:16.431434200Z][ManifestAndExistingInstallationLoader][Info   ] No install path specified, looking for default installation registry key
[2022-10-25T18:54:16.442612300Z][Installer         ][Info   ] No installation found
[2022-10-25T18:54:16.547354400Z][InstallWorkflow   ][Info   ] Cancel pending background download
[2022-10-25T18:54:16.549472400Z][BackgroundTransfer][Info   ] Cancel current background transfer job
[2022-10-25T18:54:20.715804400Z][InstallWorkflow   ][Info   ] Using package: res:DockerDesktop
[2022-10-25T18:54:20.719242900Z][InstallWorkflow   ][Info   ] Downloading
[2022-10-25T18:54:21.923057800Z][InstallWorkflow   ][Info   ] Extracting manifest
[2022-10-25T18:54:22.193285700Z][InstallWorkflow   ][Info   ] Manifest found: version=89412, displayVersion=4.13.0, channelUrl=https://desktop.docker.com/win/main/amd64/appcast.xml
[2022-10-25T18:54:22.193285700Z][InstallWorkflow   ][Info   ] Checking prerequisites
[2022-10-25T18:54:22.279349100Z][InstallWorkflow   ][Info   ] Prompting for optional features
[2022-10-25T18:54:23.590023100Z][Installer         ][Warning] Failed to track the installer started event
[2022-10-25T18:54:24.376696500Z][InstallWorkflow   ][Info   ] Selected backend mode: wsl-2
[2022-10-25T18:54:24.377510800Z][InstallWorkflow   ][Info   ] Unpacking artifacts
[2022-10-25T18:55:56.579633700Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.CreateGroupAction
[2022-10-25T18:55:58.873810800Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.AddToGroupAction
[2022-10-25T18:56:01.154675300Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.EnableFeaturesAction
[2022-10-25T18:56:01.165181800Z][InstallWorkflow-EnableFeaturesAction][Info   ] Required features: VirtualMachinePlatform, Microsoft-Windows-Subsystem-Linux
[2022-10-25T18:56:01.239186500Z][InstallWorkflow   ][Error  ] Installation failed System.Exception: Component CommunityInstaller.EnableFeaturesAction failed:  ---> System.Runtime.InteropServices.COMException
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   at CommunityInstaller.EnableFeaturesAction.<DoAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[2022-10-25T18:56:01.240185600Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.AddToGroupAction
[2022-10-25T18:56:01.240185600Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.CreateGroupAction
[2022-10-25T18:56:01.241185500Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.UnpackArtifactsStep
[2022-10-25T18:56:01.245167100Z][FileSystem        ][Info   ] Deleting C:\Program Files\Docker\Docker
[2022-10-25T18:56:01.505208700Z][FileSystem        ][Info   ] Deleted C:\Program Files\Docker\Docker successfully
[2022-10-25T18:56:01.505208700Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.ExtractManifestStep
[2022-10-25T18:56:01.505208700Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.DownloadStep


Please provide any update. Thanks

**Comment by kavyadevd** [comment]
Running into the same issue for Docker Desktop 4.14.1

**Comment by hanaKadosh** [comment]
Can someone help me? 
I try to install docker and get an error:

Component CommunityInstaller.EnableFeaturesAction failed: Invalid namespace at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

**Comment by adnanmehedi2462** [comment]
First, open command prompt and run,

wsl --status

If you get something like "you have an update," you're at the right place. Then run,

wsl --install -d ubuntu

Let it finish and then run,

wsl --update

Then reboot your system and open the docker installer again. It should install fine now.

**Comment by david-engelmann** [comment]
Experiencing this issue with the latest docker desktop version install, I was able to resolve the issue following the steps I took for a different bug. [The comment](https://github.com/docker/for-win/issues/13020#issuecomment-1285447765) mentions some parts that I think might be overkill but I was able to reinstall after following those steps.

**Comment by ronnieroyston** [comment]
Uninstall as best you can. Uninstall WSL. Redownload the Docker Desktop for Windows. Reboot. Run the new .exe installer.

**Comment by ntalamdotcom** [comment]
2024 and I still get this message:

Component Docker.Installer.EnableFeaturesAction failed: 
   at Docker.Installer.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Installer.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

**Comment by UAli5** [comment]
I also got the same error
Component Docker.Installer.EnableFeaturesAction failed:
at Docker.Installer.InstallWorkflow.d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.Installer.InstallWorkflow.d__23.MoveNext()

**Comment by kushboojain-iplit** [comment]
I'm getting the same error. Could someone please provide a solution for this

**Comment by david-engelmann** [comment]
@kushboojain-iplit checkout this [comment](https://github.com/docker/for-win/issues/13020#issuecomment-1285447765).

**Comment by kushboojain-iplit** [comment]
> @kushboojain-iplit checkout this [comment](https://github.com/docker/for-win/issues/13020#issuecomment-1285447765).

@david-engelmann 
I tired this, but it did not work

**Comment by david-engelmann** [comment]
> > @kushboojain-iplit checkout this [comment](https://github.com/docker/for-win/issues/13020#issuecomment-1285447765).
> 
> @david-engelmann 
> I tired this, but it did not work

I'd consider a complete reinstall of Docker. Potentially, grab an older version

**Comment by kushboojain-iplit** [comment]
> > > @kushboojain-iplit checkout this [comment](https://github.com/docker/for-win/issues/13020#issuecomment-1285447765).
> > 
> > 
> > @david-engelmann
> > I tired this, but it did not work
> 
> I'd consider a complete reinstall of Docker. Potentially, grab an older version

What would you mean by complete reinstall? I have tried reinstalling docker with the latest version as well as with version 4.24. Should I try with even more older versions? I'm on Windows 11 Pro

**Comment by david-engelmann** [comment]
> > > > @kushboojain-iplit checkout this [comment](https://github.com/docker/for-win/issues/13020#issuecomment-1285447765).
> > > 
> > > 
> > > @david-engelmann
> > > I tired this, but it did not work
> > 
> > I'd consider a complete reinstall of Docker. Potentially, grab an older version
> 
> What would you mean by complete reinstall? I have tried reinstalling docker with the latest version as well as with version 4.24. Should I try with even more older versions? I'm on Windows 11 Pro

Uninstall docker desktop, delete all references to docker from your windows machine, including the cache folders. Restart your machine then try and reinstall an older version of docker desktop

**Comment by Lonjher** [comment]
I have tried many ways, but still I got the same error message.

Installation failed

Component Docker.Installer.EnableFeaturesAction failed: Invalid namespace at Docker.Installer.InstallWorkflow.<DoHandleD4WPackageAsync>d_30.MoveNext()
End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.Exception Dispatchinfo. Throw()
at System.Runtime.CompilerServices.TaskAwaiter. Handle NonSuccessAndDebuggerNotification (Task task)
atDocker.Installer.InstallWorkflow.<DoProcessAsync>d_23.MoveNext()

Does anyone have solved such this trouble?

**Comment by david-engelmann** [comment]
@Lonjher did you see this comment - https://github.com/docker/for-win/issues/12511#issuecomment-1335085137

**Comment by Lonjher** [comment]
> @Lonjher did you see this comment - https://github.com/docker/for-win/issues/12511#issuecomment-1335085137

Yes, I heve solved it and it runs as expected

**Comment by catchban** [comment]
I got a similar error and these lines in the log gave me a clue:

"2024-07-08T19:52:01.547462400Z][InstallWorkflow-EnableFeaturesAction][I] Required features: VirtualMachinePlatform, Microsoft-Windows-Subsystem-Linux
[2024-07-08T19:52:01.609499200Z][InstallWorkflow][E] Installation failed System.Exception: Component Docker.Installer.EnableFeaturesAction failed:  ---> System.Runtime.InteropServices.COMException"

Docker was trying to use those features and failing.
Tried to activate both features in "Windows Features" and saw that "Windows Features" was blank.
Followed [this guide](https://www.makeuseof.com/how-to-fix-windows-features-empty/) and found out that Windows Modules Installer Service was not running.
I started the service in Services and the issue got resolved.

**Comment by Vejvoda2023** [comment]
Maybe it's a lack of computer storage space.That's what caused my problem.

**Comment by ibaoger** [comment]
Component Docker.Installer.AddToGroupAction failed: 调用的目标发生了异常。
   在 Docker.Installer.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.Installer.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

**Comment by leobard** [comment]
> Tried to activate both features in "Windows Features" and saw that "Windows Features" was blank. Followed [this guide](https://www.makeuseof.com/how-to-fix-windows-features-empty/) and found out that Windows Modules Installer Service was not running. I started the service in Services and the issue got resolved.

Similar for me, a WMI problem, but some classes where missing. See longer explanation here: https://github.com/docker/for-win/issues/14412#issuecomment-2512868764

**Comment by Namankataria01** [comment]
Having the same issue . anyone know the fix for this?
<img width="792" height="522" alt="Image" src="https://github.com/user-attachments/assets/f0b09c21-61b0-46f9-af25-a036a8398265" />

**Comment by bambom** [comment]
Help ,SOS 


-------------------------------------------------------------------------------->8
Version: 4.45.0 (203075)
Sha1: 
Started on: 2025/09/02 15:56:35.575
Resources: E:\resources
OS: Windows 10 Pro China Only
Edition: ProfessionalCountrySpecific
Id: 2009
Build: 26100
BuildLabName: 26100.1.amd64fre.ge_release.240331-1435
File: C:\ProgramData\DockerDesktop\install-log-admin.txt
CommandLine: "E:\Docker Desktop Installer.exe" "install" -package "res:DockerDesktop" --relaunch-as-admin
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2025-09-02T15:56:35.641985600Z][Installer][I] No installation found
[2025-09-02T15:56:35.803497100Z][AdminInstallHandler][I] Running admin installation
[2025-09-02T15:56:35.947534400Z][InstallWorkflow][I] Using package: res:DockerDesktop
[2025-09-02T15:56:35.948535000Z][InstallWorkflow][I] Downloading
[2025-09-02T15:56:36.833003500Z][InstallWorkflow][I] Extracting manifest
[2025-09-02T15:56:37.115709100Z][Installer][W] Failed to track segment eventInstallingUpdate: System.Net.Http.HttpRequestException: 发送请求时出错。 ---> System.Net.WebException: 基础连接已经关闭: 发送时发生错误。 ---> System.IO.IOException: 由于意外的数据包格式，握手失败。
   在 System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   在 System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   在 System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.Installer.Analytics.SegmentApi.<TrackSegment>d__33.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.Installer.Analytics.SegmentApi.<Track>d__32.MoveNext()
[2025-09-02T15:56:37.470837300Z][InstallWorkflow][I] Manifest found: version=203075, displayVersion=4.45.0, channelUrl=https://desktop-stage.docker.com/win/main/amd64/appcast.xml
[2025-09-02T15:56:37.470837300Z][InstallWorkflow][I] Checking prerequisites
[2025-09-02T15:56:37.610039600Z][InstallWorkflow][I] settings from previous installation exist: match the backend mode to that
[2025-09-02T15:56:37.619041000Z][InstallWorkflow][I] backend mode will be set to: windows
[2025-09-02T15:56:37.619041000Z][InstallWorkflow][I] Selected backend mode: windows
[2025-09-02T15:56:37.619041000Z][InstallWorkflow][I] Unpacking artifacts
[2025-09-02T15:57:48.484392200Z][InstallWorkflow][I] Deploying component Docker.Installer.CreateGroupAction
[2025-09-02T15:57:48.540023800Z][InstallWorkflow][I] Deploying component Docker.Installer.AddToGroupAction
[2025-09-02T15:57:48.546022600Z][InstallWorkflow][I] Deploying component Docker.Installer.EnableFeaturesAction
[2025-09-02T15:57:48.610381000Z][InstallWorkflow-EnableFeaturesAction][I] Required features: VirtualMachinePlatform, Microsoft-Windows-Subsystem-Linux
[2025-09-02T15:57:48.757954500Z][InstallWorkflow][E] Installation failed System.Exception: Component Docker.Installer.EnableFeaturesAction failed:  ---> System.Runtime.InteropServices.COMException
   在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   在 System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   在 System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   在 System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   在 Docker.Installer.EnableFeaturesAction.GetFeaturesToEnable()
   在 Docker.Installer.EnableFeaturesAction.<DoAsync>d__45.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Docker.Installer.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
   在 Docker.Installer.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.Installer.InstallWorkflow.<ProcessAsync>d__25.MoveNext()
[2025-09-02T15:57:48.758955600Z][InstallWorkflow][I] Rollbacking component Docker.Installer.AddToGroupAction
[2025-09-02T15:57:48.758955600Z][InstallWorkflow][I] Rollbacking component Docker.Installer.CreateGroupAction
[2025-09-02T15:57:48.758955600Z][InstallWorkflow][I] Rollbacking component Docker.Installer.UnpackArtifactsStep
[2025-09-02T15:57:48.767956200Z][FileSystem][I] Deleting C:\Program Files\Docker\Docker
[2025-09-02T15:57:48.913954300Z][FileSystem][I] Deleted C:\Program Files\Docker\Docker successfully
[2025-09-02T15:57:48.913954300Z][InstallWorkflow][I] Rollbacking component Docker.Installer.ExtractManifestStep
[2025-09-02T15:57:48.913954300Z][InstallWorkflow][I] Rollbacking component Docker.Installer.DownloadStep

<img width="704" height="457" alt="Image" src="https://github.com/user-attachments/assets/b9236261-741d-46b9-acdf-ce1603ddada9" />
