### ISSUE TITLE
Elevation required when running Docker Desktop Installer as Admin

### ISSUE THREAD

**Issue by gzerocool** [docker/for-win#12929]
8
Version: 4.11.1 (84025)
Sha1: 
Started on: 2022/08/24 10:20:04.597
Resources: C:\Temp\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 2009
Build: 19044
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\ProgramData\DockerDesktop\install-log-admin.txt
CommandLine: "C:\Temp\Docker Desktop Installer.exe"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2022-08-24T10:20:04.734907000Z][ManifestAndExistingInstallationLoader][Info   ] No install path specified, looking for default installation registry key
[2022-08-24T10:20:04.743299000Z][Installer         ][Info   ] No installation found
[2022-08-24T10:20:04.885510200Z][InstallWorkflow   ][Info   ] Cancel pending background download
[2022-08-24T10:20:04.887525800Z][BackgroundTransfer][Info   ] Cancel current background transfer job
[2022-08-24T10:20:04.893956800Z][InstallWorkflow   ][Info   ] Using package: res:DockerDesktop
[2022-08-24T10:20:04.894955800Z][InstallWorkflow   ][Info   ] Downloading
[2022-08-24T10:20:05.963989700Z][InstallWorkflow   ][Info   ] Extracting manifest
[2022-08-24T10:20:06.722037800Z][InstallWorkflow   ][Info   ] Manifest found: version=84025, displayVersion=4.11.1, channelUrl=https://desktop.docker.com/win/main/amd64/appcast.xml
[2022-08-24T10:20:06.722037800Z][InstallWorkflow   ][Info   ] Checking prerequisites
[2022-08-24T10:20:07.077509600Z][InstallWorkflow   ][Info   ] Prompting for optional features
[2022-08-24T10:20:08.177740600Z][Installer         ][Warning] Failed to track the installer started event
[2022-08-24T10:20:09.444457700Z][InstallWorkflow   ][Info   ] Selected backend mode: wsl-2
[2022-08-24T10:20:09.445455300Z][InstallWorkflow   ][Info   ] Unpacking artifacts
[2022-08-24T10:21:51.782311900Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.CreateGroupAction
[2022-08-24T10:21:59.570017200Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.AddToGroupAction
[2022-08-24T10:21:59.587640300Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.EnableFeaturesAction
[2022-08-24T10:21:59.607662700Z][InstallWorkflow-EnableFeaturesAction][Info   ] Required features: VirtualMachinePlatform, Microsoft-Windows-Subsystem-Linux
[2022-08-24T10:22:00.177424400Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.ServiceAction
[2022-08-24T10:22:00.179873400Z][InstallWorkflow-ServiceAction][Info   ] Removing service
[2022-08-24T10:22:00.180948000Z][InstallWorkflow-ServiceAction][Info   ] Creating service
[2022-08-24T10:22:02.173866500Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.ShortcutAction
[2022-08-24T10:22:02.203540400Z][InstallWorkflow-ShortcutAction][Info   ] Creating shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Docker Desktop.lnk/Docker Desktop
[2022-08-24T10:22:02.213032600Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.ShortcutAction
[2022-08-24T10:22:02.215244500Z][InstallWorkflow-ShortcutAction][Info   ] Creating shortcut: C:\Users\ALDW\Desktop\Docker Desktop.lnk/Docker Desktop
[2022-08-24T10:22:02.222330000Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.AutoStartAction
[2022-08-24T10:22:02.224386600Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.PathAction
[2022-08-24T10:22:03.524224500Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.PathAction
[2022-08-24T10:22:04.181598800Z][InstallWorkflow   ][Info   ] Deploying component CommunityInstaller.ExecAction
[2022-08-24T10:22:04.477072800Z][InstallWorkflow   ][Error  ] Installation failed System.Exception: Component CommunityInstaller.ExecAction failed: The requested operation requires elevation ---> System.ComponentModel.Win32Exception: The requested operation requires elevation
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at CommunityInstaller.ExecAction.<RunAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.ExecAction.<DoAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[2022-08-24T10:22:04.481588500Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.PathAction
[2022-08-24T10:22:05.107003000Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.PathAction
[2022-08-24T10:22:05.910739600Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.AutoStartAction
[2022-08-24T10:22:05.913105800Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.ShortcutAction
[2022-08-24T10:22:05.914106800Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.ShortcutAction
[2022-08-24T10:22:05.919057500Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.ServiceAction
[2022-08-24T10:22:06.937998000Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.EnableFeaturesAction
[2022-08-24T10:22:06.939362400Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.AddToGroupAction
[2022-08-24T10:22:06.939362400Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.CreateGroupAction
[2022-08-24T10:22:06.940468100Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.UnpackArtifactsStep
[2022-08-24T10:22:06.953686400Z][FileSystem        ][Info   ] Deleting C:\Program Files\Docker\Docker
[2022-08-24T10:22:07.228501700Z][FileSystem        ][Info   ] Deleted C:\Program Files\Docker\Docker successfully
[2022-08-24T10:22:07.228501700Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.ExtractManifestStep
[2022-08-24T10:22:07.230533500Z][InstallWorkflow   ][Info   ] Rollbacking component CommunityInstaller.DownloadStep

************************************************************************************
*READ ME FIRST*

This repository is for reporting bugs with the Docker Desktop for Windows software,
which we respond to on a best-effort basis.

Do *not* paste logfiles into github issues: upload diagnostics instead, which are
only visible to Docker engineers.

Support requests in this repository (i.e., trouble installing or using the
software) will be ignored, but personalized support is available to Docker Pro and
Team customers at https://hub.docker.com/support/desktop/, and community support is
available from the Docker community Slack (https://www.docker.com/docker-community).

Issues without sufficient detail to debug them will be closed. They generally need
a clear title and description, steps to reproduce, and a diagnostics ID. See
https://docs.docker.com/docker-for-windows/troubleshoot/#diagnose-and-feedback for
how to generate a diagnostics ID either from inside the app or from the command line.
************************************************************************************

-->

  - [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by nicks** [comment]
Hi! Sorry to hear you're having trouble. We're not able to help debug installation issues without detailed repro steps.
https://github.com/docker/for-win#support
From the error message, my guess is that you need to make sure you're using an account with admin privileges.
