### ISSUE TITLE
Docker Failed to Initialize : Docker Desktop is Shutting Down

### ISSUE THREAD

**Issue by tvrajja** [docker/for-win#12949]
Hello,

I'm not able to start the docker desktop from windows 10 pro machine. 
I have selected "Use WSL 2 instead of Hyper-V (recommended) while installing docker desktop version 4.12.0 (85629).
Can you please check the below diagnose file and advice me how to resolve this issue.

Log file:
Version: 4.12.0 (85629)
Sha1: 38dadfbe15d75f37fe5285e8466328291ef133b9
Started on: 2022/09/05 15:51:06.729
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 19044
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\rajamanickamt\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2022-09-05T15:51:06.782421000Z][GUI               ][Info   ] Starting...
[2022-09-05T15:51:06.929709200Z][GUI               ][Info   ] An instance is already running. Launching the container view.
[2022-09-05T15:51:06.951349500Z][GUI               ][Warning] Launching the dashboard failed: The operation has timed out.
[2022-09-05T15:51:06.951349500Z][GUI               ][Error  ] System.Exception:
Docker Desktop is shutting down.
   at Docker.Program.LaunchFrontend(Logger logger) in C:\workspaces\4.12.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 285
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\4.12.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 192

& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe"
[2022-09-05T16:02:46.461137600Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Please specify a command.

USAGE: com.docker.diagnose.exe [options] COMMAND [options]

Gather and upload diagnostics bundles for Docker Desktop.
Commands:
  check
  gather
  upload
  check-hypervisor
  detect-host-hypervisor

Options:
  -json string
        Output check results to the given .json file
  -path string
        Local path prefix where to store the diagnostics bundle.

Run 'com.docker.diagnose.exe COMMAND help' for more information on the command

Common use cases:
- Generate a diagnostics check:
    com.docker.diagnose.exe check
  This will print a series of diagnostic and suggest a way to repair the failures.

- Generate a diagnostics bundle and upload:
    com.docker.diagnose.exe gather -upload
  This will print a diagnostics ID you can supply for further troubleshooting.

- Generate a local diagnostics bundle to upload later:
    com.docker.diagnose.exe gather
  This will print a diagnostics ID you can use to upload with.
    com.docker.diagnose.exe submit <ID>

- Generate a local diagnostics bundle:
    com.docker.diagnose.exe gather <file>
  This will generate a local bundle in <file>.zip.

If -path is specified, place the diagnostics bundle in that directory. Otherwise the sstem default temporary directory will be used.
PS C:\Users\rajamanickamt> & "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check
[2022-09-05T16:06:33.605657000Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[SKIP] DD0028: is there available VM disk space?
[FAIL] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-09-05T16:06:33.609341600Z][com.docker.diagnose.exe][I] ipc.NewClient: 27091793-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClientForPath(...)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:59
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClient({0x8d655d, 0x13})
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:53 +0x99
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:21 +0x29
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0xe830a0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0xe830a0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x72cb77?, 0xe830a0)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0xe830a0, 0xc00035f728)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0xe83120?, 0xc00035f728)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb?, 0xc00035f728)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x812340?, 0xc00035f890)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0xe838a0, 0xb75d624e00000010?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc00006e3d0?, 0xc00006e3d0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:133 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:99 +0x287
[2022-09-05T16:06:33.612388200Z][com.docker.diagnose.exe][I] (cc61e671) 27091793-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2022-09-05T16:06:33.612388200Z][com.docker.diagnose.exe][W] (cc61e671) 27091793-com.docker.diagnose C<-S NoResponse GET /docker (0s): Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-09-05T16:06:33.612388200Z][com.docker.diagnose.exe][I] (cc61e671-1) 27091793-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T16:06:33.612388200Z][com.docker.diagnose.exe][W] (cc61e671-1) 27091793-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-09-05T16:06:34.619365300Z][com.docker.diagnose.exe][I] (cc61e671-2) 27091793-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T16:06:34.619365300Z][com.docker.diagnose.exe][W] (cc61e671-2) 27091793-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-09-05T16:06:35.622187200Z][com.docker.diagnose.exe][I] (cc61e671-3) 27091793-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T16:06:35.622187200Z][com.docker.diagnose.exe][W] (cc61e671-3) 27091793-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-09-05T16:06:36.626615900Z][com.docker.diagnose.exe][I] (cc61e671-4) 27091793-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T16:06:36.626975400Z][com.docker.diagnose.exe][W] (cc61e671-4) 27091793-com.docker.diagnose C<-S NoResponse GET /ping (359.5µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-09-05T16:06:37.629530700Z][com.docker.diagnose.exe][I] (cc61e671-5) 27091793-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T16:06:37.629530700Z][com.docker.diagnose.exe][W] (cc61e671-5) 27091793-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-09-05T16:06:38.631962900Z][com.docker.diagnose.exe][I] (cc61e671-6) 27091793-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T16:06:38.631962900Z][com.docker.diagnose.exe][W] (cc61e671-6) 27091793-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-09-05T16:06:39.635057800Z][com.docker.diagnose.exe][I] (cc61e671-7) 27091793-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T16:06:39.635057800Z][com.docker.diagnose.exe][W] (cc61e671-7) 27091793-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-09-05T16:06:40.637337700Z][com.docker.diagnose.exe][I] (cc61e671-8) 27091793-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-09-05T16:06:40.637337700Z][com.docker.diagnose.exe][W] (cc61e671-8) 27091793-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[2022-09-05T16:06:40.637337700Z][com.docker.diagnose.exe][I] ipc.NewClient: 9828a65f-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.glob..func14()
[       common/pkg/diagkit/gather/diagnose/linuxkit.go:18 +0x8b
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0xe83020)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0xe83020)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x72cb77?, 0xe83020)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0xe83020, 0xc00059f728)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0xe830a0?, 0xc00059f728)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0xe83120?, 0xc00059f728)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb?, 0xc00059f728)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x812340?, 0xc00035f890)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0xe838a0, 0xb75d624e00000010?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc00006e3d0?, 0xc00006e3d0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:133 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:99 +0x287
[2022-09-05T16:06:40.647723100Z][com.docker.diagnose.exe][I] (431d13bd) 9828a65f-diagnose C->S diagnosticsd GET /ping
[2022-09-05T16:06:40.647723100Z][com.docker.diagnose.exe][W] (431d13bd) 9828a65f-diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0001: is the application running? Docker is not running
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0017: can a VM be started?
[PASS] DD0024: is WSL installed?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[FAIL] DD0025: are WSL distros installed? WSL Distribution docker-desktop is missing
[PASS] DD0026: is the WSL LxssManager service running?
[FAIL] DD0029: is the WSL 2 Linux filesystem corrupt? exit status 0xffffffff
[FAIL] DD0035: is the VM time synchronized? exit status 0xffffffff
[PASS] DD0015: are the binary symlinks installed?
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0013: is the $PATH ok?
[FAIL] DD0005: is the user in the docker-users group? The user name could not be found.
[FAIL] DD0007: is the backend responding? failed to ping com.docker.backend with error: Get "http://ipc/ping": open \\.\pipe\dockerBackendApiServer: The system cannot find the file specified.
[2022-09-05T16:06:44.570333400Z][com.docker.diagnose.exe][I] ipc.NewClient: 279f47b3-diagnose -> \\.\pipe\dockerBackendApiServer BackendAPI
[common/pkg/backend.NewClientForPath({0x8ccef1?, 0x7b6ee0?}, {0xc00008f3a0?, 0xc0001a8000?})
[       common/pkg/backend/client.go:170 +0x3d
[common/pkg/backend.NewClient({0x8ccef1, 0x8})
[       common/pkg/backend/client.go:165 +0x50
[common/pkg/diagkit/gather/diagnose.glob..func9()
[       common/pkg/diagkit/gather/diagnose/ipc.go:25 +0x25
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0xe83420)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0xe83420)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x2?, 0xe83420)
[       common/pkg/diagkit/gather/diagnose/run.go:140 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0xe83420, 0xc000387728)
[       common/pkg/diagkit/gather/diagnose/run.go:146 +0x36
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xcb?, 0xc000387728)
[       common/pkg/diagkit/gather/diagnose/run.go:149 +0x73
[common/pkg/diagkit/gather/diagnose.walkOnce(0x812340?, 0xc00035f890)
[       common/pkg/diagkit/gather/diagnose/run.go:135 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0xe838a0, 0xb75d624e00000010?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc00006e3d0?, 0xc00006e3d0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:133 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:99 +0x287

2022/09/05 12:06:51 exit status 0xffffffff

**Comment by tundewusi** [comment]
[ common/cmd/com.docker.diagnose/main.go:99 +0x287

**Comment by tvrajja** [comment]
Hi @tundewusi, Thank you for reaching out. 
I'm not understand your comments. can you tell me more details how to resolve this?
Thanks

**Comment by cliveapple** [comment]
hi @tvrajja I solved this by deleting wsl how?
go to setting apps search for linux
it should pop up if its installed
the click uninstall
going to start menu type windows features 
then click on the following 
containers,
hyper v,
virtual machine platform,
windows hypervisor platform,
it will ask you to restart once the above are checked
one more thing go setting apps startup apps find docker turn on on start up

**Comment by cliveapple** [comment]
> I solved this by deleting wsl how? go to setting apps search for linux it should pop up if its installed then click uninstall going to start menu type windows features then click on the following containers, hyper v, virtual machine platform, windows hypervisor platform, it will ask you to restart once the above are checked one more thing go setting apps startup apps find docker turn on on start up
> 
> let me know if this fixes the issue my specs = windows 10 pro on amd chip
