### ISSUE TITLE
Failed to start    at Docker.Engines.LinuxkitDaemonStartup.<WaitAsync>d__5.MoveNext() in C:\workspaces\4.12.x\src\github.com\docker\pinata\win\src\Docker.Engines\LinuxkitDaemonStartup.cs:line 54

### ISSUE THREAD

**Issue by donhuvy** [docker/for-win#12960]
log

```
Docker.Core.DockerException:
Failed to start
   at Docker.Engines.LinuxkitDaemonStartup.<WaitAsync>d__5.MoveNext() in C:\workspaces\4.12.x\src\github.com\docker\pinata\win\src\Docker.Engines\LinuxkitDaemonStartup.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\4.12.x\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 170
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\4.12.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\4.12.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\4.12.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\4.12.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__22.MoveNext() in C:\workspaces\4.12.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 107
```

![image](https://user-images.githubusercontent.com/1328316/189624087-42317878-40cd-45a3-a137-3090276ca7b0.png)

**Comment by 1itt1eB0y** [comment]
looks like I have a familiar issue
my Diagnositcs ID is `87570521-983B-487A-9286-059B2DF21B88/20220916104321`

**Comment by 1itt1eB0y** [comment]
@donhuvy I used `netsh winsock reset` to solve this issue. You can try it.

**Comment by AvelaSAN** [comment]
![image](https://user-images.githubusercontent.com/22552244/190843438-019317c9-58ce-495d-b670-5010eaa73620.png)
mismi problema

**Comment by rozaqabdul656** [comment]
netsh winsock reset using this worked

**Comment by crimcol** [comment]
> @donhuvy I used `netsh winsock reset` to solve this issue. You can try it.

It worked for me!

**Comment by saurabhsingla786** [comment]
Thanks it works :)
`netsh winsock reset`

**Comment by MichaelUray** [comment]
For me it helped just to restart Docker Desktop.

**Comment by KSroido** [comment]
thx a lot. `netsh winsock reset` worked for me. doing homework just before ddl. thx a lot!

**Comment by kpaaro** [comment]
> @donhuvy I used `netsh winsock reset` to solve this issue. You can try it.

thanks

**Comment by kevinyyyy** [comment]
> @donhuvy I used `netsh winsock reset` to solve this issue. You can try it.

thank you very mush, it works. But why it works?

**Comment by nitishdb** [comment]
This error occured after I installed WSL2 Ubuntu for Docker Desktop. Just simply restarting the machine worked for me.

**Comment by 1itt1eB0y** [comment]
> > @donhuvy I used `netsh winsock reset` to solve this issue. You can try it.
> 
> thank you very much, it works. But how it works?

@kevinyyyy it seems like something caused IPC misconfiguration, so that Docker can't connet to the socket. Use this cmd to reset IPC to make it running properly.

**Comment by yaniv-walker** [comment]
> @donhuvy I used `netsh winsock reset` to solve this issue. You can try it.

Thx a lot. It worked for me.

**Comment by ta-ke-inf** [comment]
> @donhuvy I used `netsh winsock reset` to solve this issue. You can try it.
thank you very match. It worked for me.

**Comment by ta-ke-inf** [comment]
> @donhuvy I used `netsh winsock reset` to solve this issue. You can try it.

thank you very match!! It worked for me.

**Comment by sg552** [comment]
In my case, the 360 software kills the relative file ( identify docker file as virus ) 

so `netsh winsock restart` not work for me.

my solution: 

1. open 360 guard. 
2. uninstall docker
3. re-install docker ( keep 360 opening, then it will complain that some virus found , then you mark the virus file as "safe")

after re-installation, docker successfully started!
