### ISSUE TITLE
Docker fails to start on Windows 10

### ISSUE THREAD

**Issue by Pepita73** [docker/for-win#1296]
### Expected behavior
When I reinstall Docker then I can using soon.

### Actual behavior
Docker can't startig, only see an error box:
![2017-11-07 18_20_38-hyper-v manager](https://user-images.githubusercontent.com/3989431/32507897-02325da0-c3e9-11e7-82e2-f6845bcd6017.png)

### Information

  - Version:
```bash
PS C:\Users\Pepita> docker --version
Docker version 17.09.0-ce, build afdb6d4
```
  - System:
![2017-11-07 18_27_50-system](https://user-images.githubusercontent.com/3989431/32508114-92109b4e-c3e9-11e7-9d66-91cc6ce8f2ce.png)

### Steps to reproduce the behavior

  1. After some Windows upgrade, the next Docker starting was unsuccesfull, I saw similar error.
  2. First I checked Hyper-v and didn't see MobyLinuxVM.
  3. Then uninstall Docker and Instal latest "stable". But I think it isn't stable.. :)
  4. Reboot PC.
  5. I see the error box, but I started with Hyper-V Manager is shown and I saw for some minutes the VM:
![2017-11-07 18_20_00-hyper-v manager](https://user-images.githubusercontent.com/3989431/32508444-a0c225ee-c3ea-11e7-8091-7ef0136413c9.png)
But it was off and when Error box showed, the VM has been removed.

  6. I checked [this page](https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled), but my virtualization is enabled.
![2017-11-07 18_21_41-task manager](https://user-images.githubusercontent.com/3989431/32508573-0da52882-c3eb-11e7-8ecb-aaf58c8a69db.png)

If need more information or testing I try to solve it. I hope you can resolve this problem soon.
Thx.

**Comment by Pepita73** [comment]
More info:
I tryed to start my containers in not runing Docker (Git bash):
```bash
$ docker-compose up -d
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 68, in main
  File "compose\cli\main.py", line 121, in perform_command
  File "compose\cli\main.py", line 938, in up
  File "compose\project.py", line 417, in up
  File "compose\project.py", line 646, in warn_for_swarm_mode
  File "site-packages\docker\api\daemon.py", line 90, in info
  File "site-packages\docker\utils\decorators.py", line 46, in inner
  File "site-packages\docker\api\client.py", line 189, in _get
  File "site-packages\requests\sessions.py", line 488, in get
  File "site-packages\requests\sessions.py", line 475, in request
  File "site-packages\requests\sessions.py", line 596, in send
  File "site-packages\requests\adapters.py", line 423, in send
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
  File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
  File "httplib.py", line 1042, in request
  File "httplib.py", line 1082, in _send_request
  File "httplib.py", line 1038, in endheaders
  File "httplib.py", line 882, in _send_output
  File "httplib.py", line 844, in send
  File "site-packages\docker\transport\npipeconn.py", line 31, in connect
  File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 50, in connect
pywintypes.error: (2, 'WaitNamedPipe', 'The system cannot find the file specified.')
Failed to execute script docker-compose
```
I don't know it's helpful or not.

**Comment by Pepita73** [comment]
Now I found the VM iso and tried to install it manually in Hyper-V. Installation is succesfull but can't starting:
![2017-11-07 19_08_08-hyper-v manager](https://user-images.githubusercontent.com/3989431/32509977-52b035d0-c3ef-11e7-8213-2e2cf550b579.png)
NOw I try to check BIOS settings but I think some upgrades can't modify it and morning and yeserday Docker worked...

**Comment by Pepita73** [comment]
Now I found the resolution:
https://ppolyzos.com/2017/06/10/hyper-v-error-virtual-machine-cound-not-bestarted-because-the-hypervisor-is-not-running/

It was **NOT** Docker bug but Windows. 
Any upgrade setted HypervisorLaunchType to off. 

This issue resolved.

**Comment by wilomgfx** [comment]
@Pepita73 im getting the same error from running ```docker-compose up --build``` :/. I tried your solution and i still get the same error.
