### ISSUE TITLE
'Unable to write to the database' on Windows 10 Enterprise

### ISSUE THREAD

**Issue by DeltaWhy** [docker/for-win#130]
### Expected behavior

Docker continues to work after upgrading to 1.12.1
### Actual behavior

```
Unable to write to the database. Exit code: 1
   at Docker.Backend.Database.WriteFile(String key, String file)
   at Docker.Backend.Database.Write(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

I have the Hyper-V manager open while starting/restarting Docker and it looks like the VM never starts. Starting it manually gives the same error.
### Information

Windows 10 Enterprise 1511
Diagnostic ID: C380F3E2-0971-484D-BDF3-D7A856B52C33/2016-10-05_09-04-45

**Comment by jplonghi** [comment]
Save problem for me

`2016/10/10 00:55:24 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

[00:55:24.185][NamedPipeServer][Error  ] Unable to execute Start: Unable to write to the database. Exit code: 1    at Docker.Backend.Database.WriteKeys(ICollection`1 keyValues)
   at Docker.Backend.Database.ModifyDatabase(ICollection`1 keyValuesToWrite, ICollection`1 keysToRemove)
   at Docker.Backend.Database.Write(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[00:55:24.192][NamedPipeClient][Error  ] Unable to send Start: Unable to write to the database. Exit code: 1
[00:55:24.203][Notifications  ][Error  ] Unable to write to the database. Exit code: 1
[00:56:30.670][ErrorReportWindow][Info   ] Open logs`

**Comment by dgageot** [comment]
@DeltaWhy @jplonghi Could you please give a try to Docker for Windows Beta28 and tell us if you still see the issue?

**Comment by DeltaWhy** [comment]
That works and appears to handle the custom CA certificates correctly.

**Comment by jplonghi** [comment]
@dgageot  didn't work for me, this is the crash report id:
7107CCD3-6829-42E3-BCC5-27BE9B671686/2016-10-19_13-58-01

**Comment by glucaci** [comment]
I have the same problem on Windows 10 Education 10.0.14393

I have tested with the following versions:

- 1.12.3-beta30.1 (8711)
Diagnostic ID: D9C7FA2E-3BDD-4D91-8F5A-6A2AB283ED3D/2016-11-21_17-17-11

- 1.12.3 (8488)
Diagnostic ID: 90D7B701-B06B-491F-A074-F4DA772E66A9/2016-11-21_17-29-35

**Comment by bcraun** [comment]
For what it's worth, I'm having the same issue on Windows 10 Pro. Only notable thing in my scenario is that I'm running Windows 10 in VMware Fusion on Mac Sierra.

- v1.12.3 (8488)

**Comment by rneugeba** [comment]
@glucaci you seem to be running Windows 10 on top of VirtualBox. Since Docker for Windows also uses virtualisation the underlying system needs to support nested virtualisation. We have no control nor visibility on how the Windows VM is configured nor how well the various hypervisors support nested virtualisation (it's very hard to get right) so we can't really support this scenario.

@jplonghi do you still have the DNS issue? Can you try Beta31 release this week? If you then still have a problem with DNS, could you file a separate issue.

Closing this issue as it looks like the original issues is resolved.

**Comment by geurtjens** [comment]
I have successfully run "Docker for Windows" on a Macbook pro with the latest version of MacOSX, parallels and Windows 10 Pro.

Specifically I am running OSX 10.12.1 (sierra) using "Parallels Desktop 12 Pro Edition" with docker for windows running on Windows 10 Pro version 10.0.14393.  

The reason it works is because I use Parallels Desktop 12 Pro Edition.  Pro edition allows nested virtualisation.  Pro edition costs an extra $AUD60 and you have to pay that yearly.

If you have the pro edition you still have to enable nested virtualisation  http://kb.parallels.com/en/116239.

Good Luck

mgeurtjens
