### ISSUE TITLE
Docker Installation issue after update crash

### ISSUE THREAD

**Issue by FaizeKhan12** [docker/for-win#13034]
I'm having this issue while installing Docker:
Component CommunityInstaller.EnableFeaturesAction failed:
at CommunityInstaller.InstallWorkflow.d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at CommunityInstaller.InstallWorkflow.d__23.MoveNext()

I have done:
- Fixing the WMI
- Downgrading the version of docker and installing
- Deleting the program data and program file docker files and then installing

Here is the logs file for the installation:
-------------------------------------------------------------------------------->8
Version: 4.13.0 (89412)
Sha1:
Started on: 2022/10/25 18:54:16.320
Resources: C:\Users\alifa\Downloads\resources
OS: Windows 10 Home
Edition: Core
Id: 2009
Build: 22000
BuildLabName: 22000.1.amd64fre.co_release.210604-1628
File: C:\ProgramData\DockerDesktop\install-log-admin.txt
CommandLine: "C:\Users\alifa\Downloads\Docker Desktop Installer (3).exe" "install" -package "res:DockerDesktop" --relaunch-as-admin
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2022-10-25T18:54:16.431434200Z][ManifestAndExistingInstallationLoader][Info ] No install path specified, looking for default installation registry key
[2022-10-25T18:54:16.442612300Z][Installer ][Info ] No installation found
[2022-10-25T18:54:16.547354400Z][InstallWorkflow ][Info ] Cancel pending background download
[2022-10-25T18:54:16.549472400Z][BackgroundTransfer][Info ] Cancel current background transfer job
[2022-10-25T18:54:20.715804400Z][InstallWorkflow ][Info ] Using package: res:DockerDesktop
[2022-10-25T18:54:20.719242900Z][InstallWorkflow ][Info ] Downloading
[2022-10-25T18:54:21.923057800Z][InstallWorkflow ][Info ] Extracting manifest
[2022-10-25T18:54:22.193285700Z][InstallWorkflow ][Info ] Manifest found: version=89412, displayVersion=4.13.0, channelUrl=https://desktop.docker.com/win/main/amd64/appcast.xml
[2022-10-25T18:54:22.193285700Z][InstallWorkflow ][Info ] Checking prerequisites
[2022-10-25T18:54:22.279349100Z][InstallWorkflow ][Info ] Prompting for optional features
[2022-10-25T18:54:23.590023100Z][Installer ][Warning] Failed to track the installer started event
[2022-10-25T18:54:24.376696500Z][InstallWorkflow ][Info ] Selected backend mode: wsl-2
[2022-10-25T18:54:24.377510800Z][InstallWorkflow ][Info ] Unpacking artifacts
[2022-10-25T18:55:56.579633700Z][InstallWorkflow ][Info ] Deploying component CommunityInstaller.CreateGroupAction
[2022-10-25T18:55:58.873810800Z][InstallWorkflow ][Info ] Deploying component CommunityInstaller.AddToGroupAction
[2022-10-25T18:56:01.154675300Z][InstallWorkflow ][Info ] Deploying component CommunityInstaller.EnableFeaturesAction
[2022-10-25T18:56:01.165181800Z][InstallWorkflow-EnableFeaturesAction][Info ] Required features: VirtualMachinePlatform, Microsoft-Windows-Subsystem-Linux
[2022-10-25T18:56:01.239186500Z][InstallWorkflow ][Error ] Installation failed System.Exception: Component CommunityInstaller.EnableFeaturesAction failed: ---> System.Runtime.InteropServices.COMException
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
at System.Linq.Enumerable.d__971.MoveNext() at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
at System.Linq.Enumerable.WhereEnumerableIterator1.MoveNext() at System.Linq.Enumerable.Any[TSource](IEnumerable1 source)
at CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
at CommunityInstaller.EnableFeaturesAction.d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at CommunityInstaller.InstallWorkflow.d__30.MoveNext()
--- End of inner exception stack trace ---
at CommunityInstaller.InstallWorkflow.d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at CommunityInstaller.InstallWorkflow.d__23.MoveNext()
[2022-10-25T18:56:01.240185600Z][InstallWorkflow ][Info ] Rollbacking component CommunityInstaller.AddToGroupAction
[2022-10-25T18:56:01.240185600Z][InstallWorkflow ][Info ] Rollbacking component CommunityInstaller.CreateGroupAction
[2022-10-25T18:56:01.241185500Z][InstallWorkflow ][Info ] Rollbacking component CommunityInstaller.UnpackArtifactsStep
[2022-10-25T18:56:01.245167100Z][FileSystem ][Info ] Deleting C:\Program Files\Docker\Docker
[2022-10-25T18:56:01.505208700Z][FileSystem ][Info ] Deleted C:\Program Files\Docker\Docker successfully
[2022-10-25T18:56:01.505208700Z][InstallWorkflow ][Info ] Rollbacking component CommunityInstaller.ExtractManifestStep
[2022-10-25T18:56:01.505208700Z][InstallWorkflow ][Info ] Rollbacking component CommunityInstaller.DownloadStep

Please provide any update. Thanks

**Comment by SindreOsnes** [comment]
I am having the same issue
