### ISSUE TITLE
Docker gone if problem during update occurs

### ISSUE THREAD

**Issue by nphmuller** [docker/for-win#1310]
Today Docker tried to install the latest version (17.11.0-ce-rc3), but during the update the installer notified me that `docker-for-win.iso` is in use, which made the installation fail.

No problem, I would just restart later that day and re-run the updater. The problem was however that the current Docker installation was gone. So I had to re-download the installer and reinstall docker manually after rebooting.

### Expected behavior
If the update fails, the current Docker installation should still work.

### Actual behavior
If the update fails, the current Docker installation is gone.

### Steps to reproduce the behavior

  1. Install outdated version of Docker.
  2. Make sure a file of the installer is in use (for example `docker-for-win.iso`.
  3. Let Docker install the update.

**Comment by sampeson** [comment]
I can see the same if I have `docker-compose exec <target service> bash` open in terminal during Docker for Windows update. It gives error message about not able to access files and Docker for Windows installation is gone. Need to separately install Docker for Windows (after stopping docker-compose exec).

**Comment by florenperetti** [comment]
This happened to me today after updating to 2.1.01

**Comment by JakubSzpejewski** [comment]
This happened to me after 2.1.01 update as well. The installer said docker's installed, but all files were missing. Removing docker from registry in `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall` and installing again fixed it.

**Comment by hussnainsheikh** [comment]
Facing the same issue while updating to the 2.1.0.2, docker crash and all gone.

**Comment by fiuzaB** [comment]
Same here.

**Comment by deshbandhu** [comment]
yes the same issue, docker icon is missing if docker update gets failed in midway.

**Comment by MikeWeller** [comment]
This just happend to me with a 2.2.0.X minor upgrade. The setup dialog died with some errors that I didn't save, and afterwards there is no trace of Docker Desktop installed on my system!

**Comment by Susanthab** [comment]
Docker is gone suddenly. It does not even install the latest Docker on Windows now.

**Comment by torbjornk** [comment]
+1

For me, I noticed Docker being gone. C:\Program Files\Docker\Docker was replace with just the Docker Desktop Installer.exe (and not a new file). Had a dialogue window about updating, cancelled to see what happened, Docker is still missing.

**Comment by 78Star** [comment]
Same here. Not sure if it helps but a parity check was happening also, and my app data is set to cache prefer.

**Comment by Yohandah** [comment]
Just happened to me today .......... this sucks. Made me lose a lot of time.

**Comment by some1won** [comment]
This happened to me this morning. Any hope of a resolution yet?

**Comment by wimhollebrandse** [comment]
Happened to me today to whilst I was connected to a Docker container from VS Code. That ended up crashing, whilst the update window/popup was active and the next thing, Docker service disappeared from systray and installation was gone and replaced by the installation bootstrapper.

Note that I had not opted to actually install the update, so I reckon this also happens whilst the background Docker update window pops up.

I can't believe this issue is still open after being initially reported back in 2017...

**Comment by jansenmccloud** [comment]
I had the same problem today. 
The update failed due to some directory permission problems (windows 10, docker update 2020-11-12)
Now the whole installation is gone. :(

**Comment by bmoyer240** [comment]
+1

**Comment by kmute90** [comment]
+1

**Comment by svensaku** [comment]
+1

**Comment by Delta456** [comment]
Same for me

**Comment by pranav-manik** [comment]
+1

**Comment by pranav-manik** [comment]
error fixed removing all Docker related files in system and reinstalling without selecting "install for wsl2"

**Comment by boy51** [comment]
Happened to me too, I start my system and for no apparent reason docker is not installed anymore.

**Comment by LaunaG** [comment]
+1 My Docker Desktop application apparently crashed today during an update and uninstalled itself (Windows 10).  I couldn't find the actual event in the Windows application logs and had to fix the problem by reinstalling the program manually.  Like jansenmccloud above, my prior settings were restored though.

**Comment by gulshanBakle** [comment]
> error fixed removing all Docker related files in system and reinstalling without selecting "install for wsl2"

I tried this setting, but after installation docker desktop takes forever to start. Also settings tab in dashboard freezes in animation. Did anyone came across any of this behavior ?

**Comment by Riotsmurf2** [comment]
Just got this issue again, it has happened to me 3 times. Its amazing that this issue has been on-going for almost 3 and a half years. I cannot find a solution.

**Comment by pranav-manik** [comment]
> > error fixed removing all Docker related files in system and reinstalling without selecting "install for wsl2"
> 
> I tried this setting, but after installation docker desktop takes forever to start. Also settings tab in dashboard freezes in animation. Did anyone came across any of this behavior ?
hmm no did you remove the "C:\Users\*****\AppData\Roaming\Docker" and  "C:\Users\*****\AppData\Roaming\Docker Desktop" folder before reinstalling?

**Comment by johnmreynolds** [comment]
Same thing happened to me just now when doing an automatic update of the windows docker desktop.

**Comment by nicofretti** [comment]
Same thing happened to me to fix it without loosing information i installed the previous version of Docker Desktop from https://docs.docker.com/docker-for-windows/release-notes/.

**Comment by oluwoleeo** [comment]
I just experienced this. On launching Docker Desktop on Windows, it tried to update. I leave it to do so. After some time, I realised, it had been totally uninstalled from my system. This sucks. It is surprising this has been ongoing for almost 4 years now without a fix.

**Comment by jsmolley** [comment]
Just experienced this as well (Windows). I clicked "apply and restart" when notified, but it was like the UI jammed and the button did nothing. After a reboot, docker desktop was completely gone. For me it may have been due to a lack of disk space.

**Comment by sunxyw** [comment]
Same issue here.
Docker has gone after the restart after update.

**Comment by DavidDRea** [comment]
The same just happened to me.
I now have half a day's worth of local setup, media imports and elasticpress indexing before work can start

**Comment by b-hayes** [comment]
I just went to launch docker desktop and it's gone!
Went to add/remove programs and it's no longer listed as installed.
Docker just randomly uninstalled itself yesterday!

**Comment by mfru** [comment]
Same with me, I just now realized that docker is gone. Apparently it nuked itself.

`docker` and `docker-compose` are not recognized in wsl anymore. Start menu does not show Docker as entry anymore.

Running `Docker Desktop Installer.exe` from `C:\Program Files\Docker\Docker` (4.0.0 67817) yields 

>Object reference not set to an instance of an object.
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Installer\InstallWorkflow.cs:line 94
   
  Running `Docker Desktop.exe` directly yields an unhandled exception in .NET:
  >See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

>************** Exception Text **************
Docker.Core.BackendAPI.ServiceNotInstalledException: Docker Desktop service is not installed
   at Docker.Core.BackendAPI.BackendAPIPipeResolver.<ResolvePipeAsync>d__5.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIPipeResolver.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.ServiceAPIClient.<CreateSystemHttpClientAsync>d__3.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.ServiceAPIClient.<TryGetVhdxSize>d__16.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 156
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.SettingsAdjuster.<CopyVhdxSizeAsync>d__4.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Desktop\SettingsAdjuster.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.App.<Initialize>d__27.MoveNext() in C:\workspaces\PR-16319\src\github.com\docker\pinata\win\src\Docker.Desktop\App.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

(...) Rest of the log omitted

**Comment by b-hayes** [comment]
got sick of this kind of thing wrecking my day and ditched the docker desktop. Im running docker daemon inside wsl directly now.

**Comment by hoffmeistert** [comment]
Same here. This has been open since 2017 and look to me like a serious time sink for developers ....

**Comment by mrpink76** [comment]
Just happened to me :(

**Comment by proimage** [comment]
Ditto, during an automatic update. :( Thankfully, all my containers are still intact. :)

**Comment by stgit123** [comment]
This happened to me today (again! It has happened before). 4 years since this issue was opened and still no resolution.

**Comment by shaieleigh** [comment]
Just happened to me too today. I am reading 4 years without a resolution? Crazy

**Comment by DementedPixel** [comment]
Also started happening for me a few weeks ago. I have downloaded the latest docker but it still tries to update and removed the old version. I have to reinstall docker daily now to keep working.

**Comment by stgit123** [comment]
Just happened to me AGAIN. I see I posted about this just 26 days ago. I've unticked 'Automatically check for updates' to save future me from having to reinstall for the 90th time.

**Comment by shaieleigh** [comment]
Happened to me again a few days ago. I wrote to Docker. They said that this issue does not exist and that my company must use device management software (which we do not) and then I sent him a link to this site. I haven't heard back. Guess we will see

**Comment by bosschaert** [comment]
It happened to me as well today (on Mac OSX Monterey 12.1). Reinstalling docker fixed it and thankfully all my settings and images were still there, but I would certainly call it unusual that when you select to 'upgrade' the installation you find that it's removed. Then you have to go and find the docker desktop download page, download it and reinstall it...

**Comment by stgit123** [comment]
Maybe it is something to do with this "Grace period ends January 31st. Important terms of service reminder for Docker Desktop use". I guess we will find out in 6 days

**Comment by shaieleigh** [comment]
This will be a third time within weeks. I have also decided to stop using docker desktop and just use docker through WSL.

**Comment by Saxman255** [comment]
Happening every few weeks at my company with tons of people.  Seriously, what gives??

**Comment by janssjo** [comment]
Happened to me today, has been happening every few weeks for a while now. So far, reinstalling docker restores images and containers.

**Comment by kapsner** [comment]
+1, happens every few weeks to me

**Comment by stgit123** [comment]
Despite updating my settings to turn off automatic updates, this still keeps happening to me. I contacted support. 

They said 

> Docker Desktop support is only available to Pro and Team customers. If you are a customer, please resubmit your ticket via https://hub.docker.com/support/desktop/, which will collect additional data we need to investigate it.
> 
> If you are not a customer, you could try the self-diagnose tool documented at https://docs.docker.com/desktop/windows/troubleshoot/#self-diagnose-tool or https://docs.docker.com/desktop/mac/troubleshoot/#self-diagnose-tool to see if it has any useful information.
> 

I'm not a paying customer (my company is too small) so I went the self-diagnosis route. After reinstalling (AGAIN) I ran the diagnostics and got this
> [FAIL] DD0005: is the user in the docker-users group? The specified domain either does not exist or could not be contacted."

However when I checked my Groups in Computer Management (Windows) and I am in the docker-users group. When Docker Desktop is running I am able to use it, so I don't think that is the issue with these repeated uninstalls. 

Are there any paying customers on this thread who could submit a ticket on https://hub.docker.com/support/desktop/?

**Comment by proimage** [comment]
Why the heck does someone need to be a paying customer to report a flippin' software bug?

**Comment by shaieleigh** [comment]
@stgit123 I submitted a ticket and so far no promising responses. I wound up using Docker without Docker Desktop. It's easy once you get used to it.

**Comment by fenchu** [comment]
Docker asks to upgrade to 4.5.1 and naive me says yes, then it is gone. We also bought licenses because the only thing we could see when we search for docker in windows was a image saying docker was no longer free. Windows10, docker desktop 4.5.0. 
I just go to docker and doanload the latest docker desktop installer and use that one.

**Comment by stgit123** [comment]
> @stgit123 I submitted a ticket and so far no promising responses. I wound up using Docker without Docker Desktop. It's easy once you get used to it.

Thanks, we will probably have to go the same route as they don't seem to want to do anything about this one

**Comment by Saxman255** [comment]
Interestingly, our IT dept, in their infinite wisdom started to automatically wipe out the log4j library from our local copy of our git repository.  I'm starting to suspect some stupid policy from them...

**Comment by mat007** [comment]
Hi!

In order for us to investigate we would need either [diagnostics](https://docs.docker.com/desktop/windows/troubleshoot/#diagnose-and-feedback) or at least log files (you can look in `%LOCALAPPDATA%\Docker` and `%PROGRAMDATA%\DockerDesktop` for any `install-log*.txt` files).

Also we would need to know if it happens during an update, or not.

We have had a couple of paid support tickets opened recently (with diagnostics) about Docker Desktop disappearing all of a sudden (i.e. not during an update).
But what is extremely suspicious is that when that happens, they are no un-installation logs, only installation logs.

There is just no code anywhere outside the uninstaller that deletes files or registry keys. Also doing this requires admin permissions, i.e. usually an UAC elevation prompt, so it’s not something that could really happen sneakily.

When it happens could you also check whether the following folders exist or not:
- `%PROGRAMDATA%\DockerDesktop`
- `%LOCALAPPDATA%\Docker`
- `%APPDATA%\Docker`
- `%APPDATA%\Docker Desktop`
- `%PROGRAMFILES%\Docker`
- `C:\Users\%USERNAME%\.docker`

Let’s try and get to the bottom of this!

**Comment by stgit123** [comment]
Hi @mat007 Thank you for looking into this!

Here are some of my logs from 24 Jan when this happened to me before

`%LOCALAPPDATA%\Docker`

install-log.10.txt 2022-01-24 09:02

`Started on: 2022-01-24 09:02:06.291
File: C:\Users\REDACTED\AppData\Local\Docker\install-log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop Installer.exe" check-for-update
[09:02:06.680][ManifestAndExistingInstallationLoader] No install path specified, looking for default installation registry key
[09:02:08.074][Program] Existing installation found: build=72729, version=4.3.2, basePath=C:\Program Files\Docker\Docker, channelUrl=https://desktop.docker.com/win/main/amd64/appcast.xml
[09:02:09.375][AppcastParser] Updater not in rollout group
[09:02:09.857][CheckForUpdateHandler] Appcast found: build=72729, version=4.3.2, date=2021-12-21T18:15:59Z, installerUrl=https://desktop.docker.com/win/main/amd64/72729/Docker%20Desktop%20Installer.exe, highlights=
[09:02:09.899][CheckForUpdateHandler] Up to date`

install-log.11.txt 2022-01-24 17:10

`Version: 4.4.4 (73704)
Sha1: 
Started on: 2022-01-24 17:10:28.150
Resources: C:\Installations\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 19044
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\REDACTED\AppData\Local\Docker\install-log.txt
CommandLine: "C:\Installations\Docker Desktop Installer.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[17:10:28.368][ManifestAndExistingInstallationLoader][Info   ] No install path specified, looking for default installation registry key
[17:10:28.379][Program           ][Info   ] No installation found
[17:10:28.393][ProcessEnvironmentDetector][Info   ] Not run as admin, relaunching with UAC prompt`

When this happens again I will check for the existence of the other folders you mentioned.

**Comment by mat007** [comment]
@stgit123 

Thanks!

The first log is a check for update which did not find a new update.
The second one is the start of an installation from scratch: it starts with regular permissions and then elevates with a UAC prompt. Don’t you have a `install-log.12.txt` that has the next piece of the installation?

So it looks like between the two, during that day, something deleted Docker Desktop…

We’ve had users reporting that some management tools (e.g. [Desktop Central](https://www.zoho.com/desktop-central-cloud/)) were responsible for doing exactly what you’re describing. Once they had their IT add Docker Desktop to the exclusion list of applications the tool was supposed to keep up to date automatically, they didn’t experience the issue anymore.

**Comment by stgit123** [comment]
Hi @mat007 

Thanks for the speedy response! 

I think `install-log.11.txt` was me manually installing from scratch once I realised it had uninstalled itself again. 

I do have `install-log.12.txt` but it is from 17 Feb (over 3 weeks later) so I didn't think it was relevant. But here it is anyway in case it is useful

`Version: 4.4.4 (73704)
Sha1: 
Started on: 2022-02-17 17:48:37.859
Resources: C:\Installations\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 19044
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\REDACTED\AppData\Local\Docker\install-log.txt
CommandLine: "C:\Installations\Docker Desktop Installer.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[17:48:38.078][ManifestAndExistingInstallationLoader][Info   ] No install path specified, looking for default installation registry key
[17:48:38.095][Program           ][Info   ] No installation found
[17:48:38.111][ProcessEnvironmentDetector][Info   ] Not run as admin, relaunching with UAC prompt`

I will give this info to our IT team, thank you for that.

**Comment by janssjo** [comment]
FWIW, I updated docker desktop today 4.5.1 -> 4.6.0.
Before the update, I stopped all containers and also did a Kubernetes reset (I didn't do this with previous updates).
Then proceeded with the update and it went well, no problems, no re-installation needed.

This is my first successful docker desktop update in several months. Maybe the cleanup before update helped (i.e. stopping containers, resetting kubernetes)?

**Comment by kapsner** [comment]
@janssjo I can confirm that. Update from 4.5.1 -> 4.6.0 was the first time since mid 2021 that docker desktop did not dissapear during the update. Worked for me even without stopping containers / doing the cleanup before the update.

**Comment by proimage** [comment]
I've only encountered this issue once, [back in December 2021](https://github.com/docker/for-win/issues/1310#issuecomment-991878893), and as a result I haven't updated Docker Desktop since. I'm on version 4.4.4 (in Windows 11), and it's saying the latest version is 4.5.1. I've been pushing off updating, for fear that what happened the first time will happen again.

@mat007 I'm willing to update now, but is there anything you'd like me to do or check or whatever before I start the process... anything to make it more likely I'd have the information or logs or whatever y'all need to figure this out?

**Comment by mat007** [comment]
Hi @proimage, sorry for the delay.

What you can do is quit Docker Desktop, then delete all log files (`%LOCALAPPDATA%\Docker\*.txt` and `%APPDATA%\Docker\log`), then re-open Docker Desktop and do the update.
If anything goes wrong, and you could [create a diagnostics bundle](https://docs.docker.com/desktop/windows/troubleshoot/#diagnose-and-feedback) and give us its ID once uploaded, we would be able to understand what happened.

Thanks!

**Comment by proimage** [comment]
Well, that update went smoothly. ¯\_(ツ)_/¯

**Comment by max1c** [comment]
Just happened to me when upgrading from 4.7.x to 4.8.1...

**Comment by VGit2008** [comment]
I know this thread is old but want to share my solution as someone may find it useful.

**Symptoms**
- Upgrading from 4.6.1 to 4.21.1 (lastest version as of today)
- Update to the latest version by clicking **Check for updates** in Docker Desktop settings menu
- The updater performs installation process until finish then old version has been removed, but new version didn't get installed. 
- Docker Desktop shortcut gone. Restart Windows does not help.

**My solution**
- Check the install log files in %PROGRAMDATA%\DockerDesktop\
- Look for the update command and run it manually. I my case it was
**`update-196675368.exe "install" --confirm --auto-close-and-start-app --relaunch-as-admin`**
- Open command prompt as admin and paste the command, that's it. All containers still remain and able to use as before update

**Comment by dieselrabbit** [comment]
Just happened to me upgrading from 4.21.1 to 4.22.1

**Comment by krhoybraten** [comment]
Happened to me yesterday.

**Comment by gossie** [comment]
Had the same issue when updating to v426.1.

**Comment by manuelricci** [comment]
Happened to me today when updating to v4.27.1

**Comment by bsousaa** [comment]
@gossie @manuelricci can you please share a Diagnostics ID to understand what's going on? You can generate one with the terminal https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal

**Comment by manuelricci** [comment]
@bsousaa Sorry for the late response. I resolved with a fresh installation and everything start working properly again. Next time I'll provided the Diagnostic ID as suggested.

**Comment by gossie** [comment]
Same here.

**Comment by manuelricci** [comment]
> Same here.

@gossie as suggested by @bsousaa to me can you please share a Diagnostics ID? Check the docs to understand how to do it  https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal

**Comment by gossie** [comment]
What I ment with `Same here` is, that I have already reinstalled Docker on my machine.

**Comment by manuelricci** [comment]
> @gossie @manuelricci can you please share a Diagnostics ID to understand what's going on? You can generate one with the terminal https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal

Hi @bsousaa happened again today. 

This is my Diagnostic ID: 8A272418-AC72-47D9-A60B-426E5BC53F84/20240215194340

**Comment by totszwai** [comment]
WTF, my docker is gone after today's updated!!!!!

**Comment by bsousaa** [comment]
@totszwai  - diagnostics id please

**Comment by fredricj** [comment]
It failed for me today with this error I could find in the log:
```
[2024-02-20T11:17:52.379685600Z][UninstallWorkflow][I] Unregistering product
[2024-02-20T11:17:52.380682900Z][RegisterProductStep][E] Failed to delete registry key: Cannot delete a subkey tree because the subkey does not exist.
[2024-02-20T11:17:52.512797100Z][UninstallWorkflow][I] Uninstalled finished
[2024-02-20T11:17:52.519926600Z][InstallWorkflow][I] settings from previous installation exist: match the backendmode to that
[2024-02-20T11:17:52.520925900Z][InstallWorkflow][I] existing setting useWindowsContainers = False
[2024-02-20T11:17:52.520925900Z][InstallWorkflow][I] existing setting wslEngineEnabled = True
[2024-02-20T11:17:52.520925900Z][InstallWorkflow][I] Selected backend mode: wsl-2
[2024-02-20T11:17:52.524925600Z][InstallWorkflow][I] Unpacking artifacts
[2024-02-20T11:17:52.541506000Z][InstallWorkflow][E] Installation failed System.Exception: Unpacking failed: This access control list is not in canonical form and therefore cannot be modified. ---> System.InvalidOperationException: This access control list is not in canonical form and therefore cannot be modified.
   at System.Security.AccessControl.CommonAcl.ThrowIfNotCanonical()
   at System.Security.AccessControl.CommonAcl.AddQualifiedAce(SecurityIdentifier sid, AceQualifier qualifier, Int32 accessMask, AceFlags flags, ObjectAceFlags objectFlags, Guid objectType, Guid inheritedObjectType)
   at System.Security.AccessControl.DiscretionaryAcl.AddAccess(AccessControlType accessType, SecurityIdentifier sid, Int32 accessMask, InheritanceFlags inheritanceFlags, PropagationFlags propagationFlags)
   at System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(AccessControlModification modification, AccessRule rule, Boolean& modified)
   at System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(AccessRule rule)
   at Docker.Core.PermissionUtils.RemoveGlobalWrite(ILogger logger, String path) in C:\workspaces\PR-26059\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 54
   at Docker.Installer.UnpackArtifactsStep.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Installer.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at Docker.Installer.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Installer.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[2024-02-20T11:17:52.543503700Z][InstallWorkflow][I] Rollbacking component Docker.Installer.ExtractManifestStep
[2024-02-20T11:17:52.544505700Z][InstallWorkflow][I] Rollbacking component Docker.Installer.DownloadStep
```

I'm guessing the installer/updater doesn't handle exceptions gracefully during updates. No error message is visible to the user. The installation window just disappear.

**Comment by vladkrasn** [comment]
Happened to me too

**Comment by Ray7788** [comment]
Happened to me on 2 March 2024!!!! All the docker-related things disappeared!

I downloaded the docker desktop installer from the official website and it executed an automatic recovering process, now all is back.

**Comment by dickyindra** [comment]
Happened to me on March 13, 2024 😅

**Comment by doughnut1332** [comment]
Still has the same issue.
Happend to me on June 15, 2024

**Comment by slash-h** [comment]
Happened to me as well on 15th June. The update version failed and my exisiting docker desktop setup disappeared from the system. 
However, reinstalling docker desktop brought my all images back... Happy now, but this issue is so scary and strange

**Comment by totszwai** [comment]
> WTF, my docker is gone after today's updated!!!!!

What the actual F man, 4 months later, I installed another update, and the damn thing uninstalled itself AGAIN!!!!!! 😡

**Comment by bsousaa** [comment]
@totszwai - please share a diagnostics id to investigate internally

**Comment by totszwai** [comment]
> @totszwai - please share a diagnostics id to investigate internally

Yeah, I am not sure how useful it is though, after the update, the Docker Desktop was basically gone from my system and I had to manually reinstall it... so this id is generated from the new installation...

04C3128C-7F3F-4004-958B-63CF2FAA04D2/20240621151821
