### ISSUE TITLE
open //./pipe/docker_engine: The system cannot find the file specified.

### ISSUE THREAD

**Issue by maulik-chavda** [docker/for-win#13137]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker Desktop is not starting 
### Expected behavior
Docker Desktop should be working
### Information

On starting system docker crashed and I had to hard restart system, which is happening to me frequently

I got this below error :
error during connect: in the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect:  Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dlocalplatform_suite%22%3Atrue%7D%7D":  open //./pipe/docker_engine: The system cannot find the file specified.

Mostly such errors are getting resolved after restarting Docker and/or Windows, but this time it didn't, so I updated docker, then reinstalled docker, then uninstalled and re-installed WSL as well, with all these operations I did cleaned temp folders. but error and issue is still same

Also, can't understand why its always showing state as Uninstalling on running wsl -l -v

PS C:\Users\{username}> wsl -l -v
  NAME                   STATE           VERSION
* Ubuntu                 Stopped         2
  docker-desktop         Uninstalling    2
  docker-desktop-data    Stopped         2

Also, with windows container Docker Desktop Containers UI is loading, but with Linux containers its not, irrespective of WSL or Hyper-V mode of docker.

after changing to Windows container by DockerCli.exe -SwitchDaemon, error is same but with lesser content as below, but its always talks about not able to find some file.

docker: Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
See 'docker run --help'.

  - Windows Version: 21H2 (OS Build 19044.2364)
  - Docker Desktop Version: 4.15.0 (93002) 
  - WSL2 or Hyper-V backend?  tried both
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
C:\Program Files\Docker\Docker\resources>com.docker.diagnose.exe check
[2022-12-19T11:32:52.874931500Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[FAIL] DD0001: is the application running? querying Docker Desktop.exe process: is it running as a different user?: Access is denied.
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[FAIL] DD0025: are WSL distros installed? WSL Distribution docker-desktop is missing
[PASS] DD0026: is the WSL LxssManager service running?
[FAIL] DD0029: is the WSL 2 Linux filesystem corrupt? exit status 0xffffffff
[FAIL] DD0035: is the VM time synchronized? exit status 0xffffffff
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[2022-12-19T11:32:59.286102000Z][com.docker.diagnose.exe][I] ipc.NewClient: cd98f417-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.glob..func14()
[       common/pkg/diagkit/gather/diagnose/linuxkit.go:18 +0x8b
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0xf840c0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0xf840c0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x4?, 0xf840c0)
[       common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0xf840c0, 0xc0003bb728)
[       common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0xf84140, 0xc0003bb728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0xf841c0, 0xc0003bb728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xf84940, 0xc0003bb728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkOnce(0x922c80?, 0xc00035f890)
[       common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0xf84940, 0xfa9342b200000010?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc0001123b0?, 0xc0001123b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:133 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:99 +0x287
[2022-12-19T11:32:59.286102000Z][com.docker.diagnose.exe][I] (288cd6be) cd98f417-diagnose C->S diagnosticsd GET /ping
[2022-12-19T11:32:59.286804300Z][com.docker.diagnose.exe][W] (288cd6be) cd98f417-diagnose C<-S NoResponse GET /ping (522.4µs): Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-12-19T11:32:59.289656500Z][com.docker.diagnose.exe][I] ipc.NewClient: ed0e65c6-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClientForPath(...)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:61
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClient({0x9e68bf, 0x13})
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:55 +0x99
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:21 +0x29
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0xf84140)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0xf84140)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x3?, 0xf84140)
[       common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0xf84140, 0xc0003bb728)
[       common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0xf841c0, 0xc0003bb728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xf84940, 0xc0003bb728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkOnce(0x922c80?, 0xc00035f890)
[       common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0xf84940, 0xfa9342b200000010?, {0xc00035fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc0001123b0?, 0xc0001123b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:133 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:99 +0x287
[2022-12-19T11:32:59.289656500Z][com.docker.diagnose.exe][I] (1e5fd96d) ed0e65c6-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2022-12-19T11:32:59.290770700Z][com.docker.diagnose.exe][W] (1e5fd96d) ed0e65c6-com.docker.diagnose C<-S NoResponse GET /docker (1.1142ms): Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-12-19T11:32:59.290770700Z][com.docker.diagnose.exe][I] (1e5fd96d-1) ed0e65c6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-19T11:32:59.291574700Z][com.docker.diagnose.exe][W] (1e5fd96d-1) ed0e65c6-com.docker.diagnose C<-S NoResponse GET /ping (804µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-12-19T11:33:00.314987600Z][com.docker.diagnose.exe][I] (1e5fd96d-2) ed0e65c6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-19T11:33:00.315791900Z][com.docker.diagnose.exe][W] (1e5fd96d-2) ed0e65c6-com.docker.diagnose C<-S NoResponse GET /ping (804.3µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-12-19T11:33:01.322301000Z][com.docker.diagnose.exe][I] (1e5fd96d-3) ed0e65c6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-19T11:33:01.324063400Z][com.docker.diagnose.exe][W] (1e5fd96d-3) ed0e65c6-com.docker.diagnose C<-S NoResponse GET /ping (1.8518ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-12-19T11:33:02.325781900Z][com.docker.diagnose.exe][I] (1e5fd96d-4) ed0e65c6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-19T11:33:02.328020500Z][com.docker.diagnose.exe][W] (1e5fd96d-4) ed0e65c6-com.docker.diagnose C<-S NoResponse GET /ping (2.2386ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-12-19T11:33:03.331993500Z][com.docker.diagnose.exe][I] (1e5fd96d-5) ed0e65c6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-19T11:33:03.332886400Z][com.docker.diagnose.exe][W] (1e5fd96d-5) ed0e65c6-com.docker.diagnose C<-S NoResponse GET /ping (892.9µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-12-19T11:33:04.335253400Z][com.docker.diagnose.exe][I] (1e5fd96d-6) ed0e65c6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-19T11:33:04.337356800Z][com.docker.diagnose.exe][W] (1e5fd96d-6) ed0e65c6-com.docker.diagnose C<-S NoResponse GET /ping (2.3617ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-12-19T11:33:05.338501500Z][com.docker.diagnose.exe][I] (1e5fd96d-7) ed0e65c6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-19T11:33:05.340291500Z][com.docker.diagnose.exe][W] (1e5fd96d-7) ed0e65c6-com.docker.diagnose C<-S NoResponse GET /ping (1.79ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2022-12-19T11:33:06.350381300Z][com.docker.diagnose.exe][I] (1e5fd96d-8) ed0e65c6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2022-12-19T11:33:06.351257900Z][com.docker.diagnose.exe][W] (1e5fd96d-8) ed0e65c6-com.docker.diagnose C<-S NoResponse GET /ping (876.6µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[PASS] DD0013: is the $PATH ok?
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
[FAIL] DD0003: is the Docker CLI working? exit status 1
[FAIL] DD0005: is the user in the docker-users group? The specified domain either does not exist or could not be contacted.
2022/12/19 17:03:06 exit status 0xffffffff

C:\Program Files\Docker\Docker\resources>
### Steps to reproduce the behavior

And on Clean/Purge Data, getting below error, and after that docker is getting quit.

System.InvalidOperationException:
Failed to terminate distro: exit code: -1
 stdout: There is no distribution with the supplied name.

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 160
   at Docker.Engines.WSL2.WSL2Provisioning.<TerminateDistroAsync>d__15.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<TerminateDistrosAsync>d__11.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<UnprovisionAsync>d__9.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoDestroyAsync>d__32.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 328
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.DestroyTransition.<DoRunAsync>d__7.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\DestroyTransition.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<DestroyAsync>d__17.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<RemoveDataAsync>d__26.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 214

**Comment by DamienGR** [comment]
I had the exact same issue and solved it with `wsl --unregister docker-desktop`
Before that I uninstalled docker desktop then installed it again but I'm not sure this step is necessary

**Comment by maulik-chavda** [comment]
Yes @DamienGR,
Even after uninstalling Docker, I was always getting its reference from this command `wsl -l -v`

  NAME                   STATE           VERSION
* Ubuntu                 Stopped         2
  docker-desktop         Uninstalling    2
  docker-desktop-data    Stopped         2
  
  So, I did un-installed both WSL and Docker and then did 
`wsl --unregister docker-desktop-data` and `wsl --unregister docker-desktop`

and then installed Docker again, now Docker is running fine with Linux containers, able to fix this issue after unregistering docker from wsl.

Thanks @DamienGR !

**Comment by Cristishor201** [comment]
I run into this error as well, on Win7.
