### ISSUE TITLE
Docker desktop not starting

### ISSUE THREAD

**Issue by vinod-artha** [docker/for-win#13146]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by vinod-artha** [comment]
`-------------------------------------------------------------------------------->8
Version: 4.15.0 (93002)
Sha1: edb830d237baed81db424449290ec28577916262
Started on: 2022/12/28 04:56:43.749
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro N
Edition: ProfessionalN
Id: 2009
Build: 19045
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\ProgramData\DockerDesktop\service.txt
CommandLine: "C:\Program Files\Docker\Docker\com.docker.service"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2022-12-28T04:56:43.967772200Z][DockerService][I] Starting service
[2022-12-28T04:57:03.280295400Z][IPCServer][I] (becf3514) daeadd82-ServiceAPI S<-C e1431bee-ServiceAPIClient-CSharp GET /version
   at Docker.Core.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 16
   at Docker.Core.HttpClientExtensions.GetJsonAsync[T](HttpClient httpClient, String uri, CancellationToken cancellationToken)
   at Docker.Core.BackendAPI.BackendAPIPipeResolver.<ResolvePipeAsync>d__5.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIPipeResolver.cs:line 103
   at Docker.Core.BackendAPI.BackendAPIPipeResolver.ResolvePipeAsync()
   at Docker.Core.BackendAPI.ServiceAPIClient.<CreateSystemHttpClientAsync>d__3.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 24
   at Docker.Core.BackendAPI.ServiceAPIClient.CreateSystemHttpClientAsync()
   at Docker.Core.BackendAPI.ServiceAPIClient.<TryGetVhdxSize>d__15.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 135
   at Docker.Core.BackendAPI.ServiceAPIClient.TryGetVhdxSize(String path)
   at Docker.Engines.SettingsAdjuster.<CopyVhdxSizeAsync>d__4.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Desktop\SettingsAdjuster.cs:line 23
   at Docker.Engines.SettingsAdjuster.CopyVhdxSizeAsync(Settings settings)
   at Docker.App.<InitializeAsync>d__12.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Desktop\App.cs:line 72
   at Docker.App.InitializeAsync(Singletons singletons)
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 222
   at Docker.Program.Main(String[] args) in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 118
[2022-12-28T04:57:03.655304400Z][IPCServer][I] (becf3514) daeadd82-ServiceAPI S->C e1431bee-ServiceAPIClient-CSharp GET /version (369ms): OK
[2022-12-28T04:57:05.452261300Z][IPCServer][I] (5ecfd8b7) daeadd82-ServiceAPI S<-C 632fb7d0-ServiceAPIClient-CSharp GET /hyperv/vhdx-size
   at Docker.Core.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 16
   at Docker.Core.HttpClientExtensions.GetJsonAsync[T](HttpClient httpClient, String uri, CancellationToken cancellationToken)
   at Docker.Core.BackendAPI.ServiceAPIClient.<TryGetVhdxSize>d__15.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 137
   at Docker.Core.BackendAPI.ServiceAPIClient.<CreateSystemHttpClientAsync>d__3.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 31
[2022-12-28T04:57:05.624077300Z][IPCServer][I] (5ecfd8b7) daeadd82-ServiceAPI S->C 632fb7d0-ServiceAPIClient-CSharp GET /hyperv/vhdx-size (175ms): OK
[2022-12-28T04:57:10.528963700Z][IPCServer][I] (98446d04) daeadd82-ServiceAPI S<-C 3b88e2e6-ServiceAPIClient-CSharp POST /dns/refresh-hosts
   at Docker.Core.BackendAPI.ServiceAPIClient.<UpdateHostsAsync>d__5.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 0
   at Docker.Core.BackendAPI.ServiceAPIClient.UpdateHostsAsync(CancellationToken cancellationToken)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 94
   at Docker.Engines.WSL2.LinuxWSL2Engine.DoStartAsync(CancellationToken cancellationToken)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 31
   at Docker.ApiServices.StateMachines.StartTransition.DoRunAsync(CancellationToken cancellationToken)
[2022-12-28T04:57:13.017358800Z][IPCServer][I] (98446d04) daeadd82-ServiceAPI S->C 3b88e2e6-ServiceAPIClient-CSharp POST /dns/refresh-hosts (2478ms): OK
[2022-12-28T04:57:28.180783500Z][IPCServer][I] (37116581) daeadd82-ServiceAPI S<-C 4f812e48-ServiceAPIClient-CSharp POST /windowsfeatures/check
   at Docker.Core.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 22
   at Docker.Core.HttpClientExtensions.PostJsonWithJsonResponseAsync[T](HttpClient httpClient, String uri, Object content, CancellationToken cancellationToken)
   at Docker.Core.BackendAPI.ServiceAPIClient.<CheckFeaturesAsync>d__4.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 35
   at Docker.Core.BackendAPI.ServiceAPIClient.CheckFeaturesAsync(CancellationToken cancellationToken, WindowsFeature[] windowsFeatures)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoCheckPreconditionsAsync>d__31.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 294
   at Docker.Engines.WSL2.LinuxWSL2Engine.DoCheckPreconditionsAsync(CancellationToken cancellationToken)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 61
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 31
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStopAsync>d__30.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 275
   at Docker.Engines.WSL2.WSL2Provisioning.<IsMainDistroDeployedAsync>d__10.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 107
   at Docker.Engines.WSL2.WSL2Provisioning.<ListDistrosAsync>d__7.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 41
   at Docker.ApiServices.WSL2.WslDistroInfoProvider.<GetAllWslDistrosAsync>d__3.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslDistroInfoProvider.cs:line 83
   at Docker.ApiServices.WSL2.WslCommand.<RunShortLivedAsync>d__1.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 103
[2022-12-28T04:57:28.335701400Z][Installer][I] Checking for features: VirtualMachinePlatform, Microsoft-Windows-Subsystem-Linux
[2022-12-28T04:57:29.927661500Z][IPCServer][I] (37116581) daeadd82-ServiceAPI S->C 4f812e48-ServiceAPIClient-CSharp POST /windowsfeatures/check (1746ms): OK
[2022-12-28T04:57:32.082268700Z][IPCServer][I] (fb742d5b) daeadd82-ServiceAPI S<-C c33ac5ee-ServiceAPIClient-CSharp POST /dns/refresh-hosts
   at Docker.Core.BackendAPI.ServiceAPIClient.<UpdateHostsAsync>d__5.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 0
   at Docker.Core.BackendAPI.ServiceAPIClient.UpdateHostsAsync(CancellationToken cancellationToken)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__26.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 94
   at Docker.Engines.WSL2.LinuxWSL2Engine.DoStartAsync(CancellationToken cancellationToken)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 72
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 31
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoCheckPreconditionsAsync>d__31.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 313
   at Docker.Engines.WSL2.WSL2Provisioning.<UnprovisionAsync>d__9.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 101
   at Docker.Engines.WSL2.WSL2Provisioning.<ListDistrosAsync>d__7.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\WSL2Provisioning.cs:line 41
   at Docker.ApiServices.WSL2.WslDistroInfoProvider.<GetAllWslDistrosAsync>d__3.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslDistroInfoProvider.cs:line 83
   at Docker.ApiServices.WSL2.WslCommand.<RunShortLivedAsync>d__1.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 103
[2022-12-28T04:57:32.179723700Z][IPCServer][I] (fb742d5b) daeadd82-ServiceAPI S->C c33ac5ee-ServiceAPIClient-CSharp POST /dns/refresh-hosts (102ms): OK
[2022-12-28T04:58:24.574432000Z][IPCServer][I] (b6f69be2) daeadd82-ServiceAPI S<-C ff393285-ServiceAPIClient-CSharp GET /version
   at Docker.Core.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 16
   at Docker.Core.HttpClientExtensions.GetJsonAsync[T](HttpClient httpClient, String uri, CancellationToken cancellationToken)
   at Docker.Core.BackendAPI.BackendAPIPipeResolver.<ResolvePipeAsync>d__5.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIPipeResolver.cs:line 103
   at Docker.Core.BackendAPI.BackendAPIPipeResolver.ResolvePipeAsync()
   at Docker.Core.BackendAPI.ServiceAPIClient.<CreateSystemHttpClientAsync>d__3.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 24
   at Docker.Core.BackendAPI.ServiceAPIClient.CreateSystemHttpClientAsync()
   at Docker.Core.BackendAPI.ServiceAPIClient.<TryGetVhdxSize>d__15.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 135
   at Docker.Core.BackendAPI.ServiceAPIClient.TryGetVhdxSize(String path)
   at Docker.Engines.SettingsAdjuster.<CopyVhdxSizeAsync>d__4.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Desktop\SettingsAdjuster.cs:line 23
   at Docker.Engines.SettingsAdjuster.CopyVhdxSizeAsync(Settings settings)
   at Docker.App.<InitializeAsync>d__12.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Desktop\App.cs:line 72
   at Docker.App.InitializeAsync(Singletons singletons)
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 222
   at Docker.Program.Main(String[] args) in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 118
[2022-12-28T04:58:24.574432000Z][IPCServer][I] (b6f69be2) daeadd82-ServiceAPI S->C ff393285-ServiceAPIClient-CSharp GET /version (0ms): OK
[2022-12-28T04:58:24.741929500Z][IPCServer][I] (ea979878) daeadd82-ServiceAPI S<-C 4a960ae3-ServiceAPIClient-CSharp GET /hyperv/vhdx-size
   at Docker.Core.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 16
   at Docker.Core.HttpClientExtensions.GetJsonAsync[T](HttpClient httpClient, String uri, CancellationToken cancellationToken)
   at Docker.Core.BackendAPI.ServiceAPIClient.<TryGetVhdxSize>d__15.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 137
   at Docker.Core.BackendAPI.ServiceAPIClient.<CreateSystemHttpClientAsync>d__3.MoveNext() in C:\workspaces\main-merge\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\ServiceAPIClient.cs:line 31
[2022-12-28T04:58:24.741929500Z][IPCServer][I] (ea979878) daeadd82-ServiceAPI S->C 4a960ae3-ServiceAPIClient-CSharp GET /hyperv/vhdx-size (1ms): OK
[2022-12-28T04:58:58.827130200Z][DockerService][I] Stopping service
`

**Comment by PatrykKuniczak** [comment]
Sill docker have many problems with starting engine on windows, I use Win 10, and i can't run this ...

@stephen-turner Anybody from your repo, relate users problems?
