### ISSUE TITLE
4.16.0 Installation failed due to BadImageFormatException

### ISSUE THREAD

**Issue by JohnCOsborne** [docker/for-win#13162]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Docker Desktop installation fails with both Hyper V and WSL configuration
### Expected behavior
Successfull installation
### Information
I have tried:

- Resetting WMI service
- Deleting Docker folders and trying again
- Trying install off and on vpn
- trying older versions (4.13.1,4.14.0,4.15.0)

  - Windows Version: 21H2 OS Build: 19044.2130
  - Docker Desktop Version: 4.16.0
  - WSL2 or Hyper-V backend?  **Both**
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: **No**

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

N/A

### Steps to reproduce the behavior

  1. ... Use my Laptop
  2. ... Try to install Docker Desktop

### Stack Trace
[2023-01-13T14:51:57.781865200Z][ManifestAndExistingInstallationLoader][I] No install path specified, looking for default installation registry key
[2023-01-13T14:51:57.791806500Z][Installer][I] No installation found
[2023-01-13T14:51:57.927443500Z][InstallWorkflow][I] Cancel pending background download
[2023-01-13T14:51:57.930436000Z][BackgroundTransfer][I] Cancel current background transfer job
[2023-01-13T14:51:57.943401400Z][InstallWorkflow][I] Using package: res:DockerDesktop
[2023-01-13T14:51:57.945395800Z][InstallWorkflow][I] Downloading
[2023-01-13T14:51:58.829448300Z][InstallWorkflow][I] Extracting manifest
[2023-01-13T14:51:59.417874900Z][InstallWorkflow][I] Manifest found: version=93002, displayVersion=4.15.0, channelUrl=https://desktop.docker.com/win/main/amd64/appcast.xml
[2023-01-13T14:51:59.417874900Z][InstallWorkflow][I] Checking prerequisites
[2023-01-13T14:51:59.445800300Z][InstallWorkflow][I] Prompting for optional features
[2023-01-13T14:51:59.445800300Z][Installer][W] Failed to track the installer started event
[2023-01-13T14:52:24.746092100Z][InstallWorkflow][I] Selected backend mode: hyper-v
[2023-01-13T14:52:24.747088300Z][InstallWorkflow][I] Unpacking artifacts
[2023-01-13T14:54:23.210355000Z][InstallWorkflow][I] Deploying component CommunityInstaller.CreateGroupAction
[2023-01-13T14:54:25.667469600Z][InstallWorkflow][I] Deploying component CommunityInstaller.AddToGroupAction
[2023-01-13T14:54:25.676445500Z][InstallWorkflow][I] Deploying component CommunityInstaller.EnableFeaturesAction
[2023-01-13T14:54:25.693400500Z][InstallWorkflow-EnableFeaturesAction][I] Required features: *Hyper-V*, Containers
[2023-01-13T14:54:25.996291800Z][InstallWorkflow][E] Installation failed System.Exception: Component CommunityInstaller.EnableFeaturesAction failed:  ---> System.BadImageFormatException
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   at CommunityInstaller.EnableFeaturesAction.<DoAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[2023-01-13T14:54:25.997324600Z][InstallWorkflow][I] Rollbacking component CommunityInstaller.AddToGroupAction
[2023-01-13T14:54:25.998319900Z][InstallWorkflow][I] Rollbacking component CommunityInstaller.CreateGroupAction
[2023-01-13T14:54:25.998319900Z][InstallWorkflow][I] Rollbacking component CommunityInstaller.UnpackArtifactsStep
[2023-01-13T14:54:26.005307800Z][FileSystem][I] Deleting C:\Program Files\Docker\Docker
[2023-01-13T14:54:26.481000100Z][FileSystem][I] Deleted C:\Program Files\Docker\Docker successfully
[2023-01-13T14:54:26.481000100Z][InstallWorkflow][I] Rollbacking component CommunityInstaller.ExtractManifestStep
[2023-01-13T14:54:26.481994300Z][InstallWorkflow][I] Rollbacking component CommunityInstaller.DownloadStep

**Comment by JJC-code** [comment]
@JohnCOsborne have you resolved the issue? If so, please tell me how?

**Comment by JohnCOsborne** [comment]
@JJC-code Turns out my laptop (work laptop) was corrupted and help desk could not update my PC. My employer had to ship me a new laptop

**Comment by JohnCOsborne** [comment]
Issue resolved.
