### ISSUE TITLE
Docker not starting in windows

### ISSUE THREAD

**Issue by murkishashank** [docker/for-win#13179]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [] I have uploaded Diagnostics
  - Diagnostics ID: 49B1E6EA-4AAA-450E-B14D-2F97CA90CFC0/20230119124612

### Actual behavior

Docker not starting in windows. Docker desktop only shows "docker desktop starting..." on screen.

### Expected behavior
Docker should start

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

```
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[SKIP] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[FAIL] DD0025: are WSL distros installed? WSL Distribution docker-desktop is missing
[PASS] DD0026: is the WSL LxssManager service running?
[FAIL] DD0029: is the WSL 2 Linux filesystem corrupt? exit status 0xffffffff
[FAIL] DD0035: is the VM time synchronized? exit status 0xffffffff
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[2023-01-19T12:34:38.933825400Z][com.docker.diagnose.exe][I] ipc.NewClient: cc37e241-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.glob..func14()
[       common/pkg/diagkit/gather/diagnose/linuxkit.go:18 +0x8b
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x16ca440)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x16ca440)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x4?, 0x16ca440)
[       common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x16ca440, 0xc0006ef728)
[       common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x16ca4c0, 0xc0006ef728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x16ca540, 0xc0006ef728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x16cacc0, 0xc0006ef728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkOnce(0x105e880?, 0xc00026f890)
[       common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x16cacc0, 0xb90b5700000010?, {0xc00026fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc0000460b0?, 0xc000046090?, 0x4?}, {0xc0000300e0, 0x7})
[       common/cmd/com.docker.diagnose/main.go:138 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:102 +0x27f
[2023-01-19T12:34:38.934327300Z][com.docker.diagnose.exe][I] (be09e3be) cc37e241-diagnose C->S diagnosticsd GET /ping
[2023-01-19T12:34:38.934828600Z][com.docker.diagnose.exe][W] (be09e3be) cc37e241-diagnose C<-S NoResponse GET /ping (501.3µs): Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-01-19T12:34:38.937289500Z][com.docker.diagnose.exe][I] ipc.NewClient: 30fd62a6-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClientForPath(...)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:63
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClient({0x1123b9c, 0x13})
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:57 +0x99
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:21 +0x29
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x16ca4c0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0x16ca4c0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x3?, 0x16ca4c0)
[       common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x16ca4c0, 0xc0006ef728)
[       common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x16ca540, 0xc0006ef728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x16cacc0, 0xc0006ef728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkOnce(0x105e880?, 0xc00026f890)
[       common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0x16cacc0, 0xb90b5700000010?, {0xc00026fb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc0000460b0?, 0xc000046090?, 0x4?}, {0xc0000300e0, 0x7})
[       common/cmd/com.docker.diagnose/main.go:138 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:102 +0x27f
[2023-01-19T12:34:38.937808900Z][com.docker.diagnose.exe][I] (8db37758) 30fd62a6-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2023-01-19T12:34:38.938298600Z][com.docker.diagnose.exe][W] (8db37758) 30fd62a6-com.docker.diagnose C<-S NoResponse GET /docker (489.7µs): Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-01-19T12:34:38.938298600Z][com.docker.diagnose.exe][I] (8db37758-1) 30fd62a6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-19T12:34:38.938797200Z][com.docker.diagnose.exe][W] (8db37758-1) 30fd62a6-com.docker.diagnose C<-S NoResponse GET /ping (498.6µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-01-19T12:34:39.955775800Z][com.docker.diagnose.exe][I] (8db37758-2) 30fd62a6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-19T12:34:39.956856900Z][com.docker.diagnose.exe][W] (8db37758-2) 30fd62a6-com.docker.diagnose C<-S NoResponse GET /ping (1.0811ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-01-19T12:34:40.970556400Z][com.docker.diagnose.exe][I] (8db37758-3) 30fd62a6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-19T12:34:40.972140700Z][com.docker.diagnose.exe][W] (8db37758-3) 30fd62a6-com.docker.diagnose C<-S NoResponse GET /ping (1.5355ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-01-19T12:34:41.984525300Z][com.docker.diagnose.exe][I] (8db37758-4) 30fd62a6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-19T12:34:41.985838200Z][com.docker.diagnose.exe][W] (8db37758-4) 30fd62a6-com.docker.diagnose C<-S NoResponse GET /ping (1.3129ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-01-19T12:34:42.986939800Z][com.docker.diagnose.exe][I] (8db37758-5) 30fd62a6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-19T12:34:42.989458700Z][com.docker.diagnose.exe][W] (8db37758-5) 30fd62a6-com.docker.diagnose C<-S NoResponse GET /ping (2.2743ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-01-19T12:34:43.999109900Z][com.docker.diagnose.exe][I] (8db37758-6) 30fd62a6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-19T12:34:43.999109900Z][com.docker.diagnose.exe][W] (8db37758-6) 30fd62a6-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-01-19T12:34:45.014793300Z][com.docker.diagnose.exe][I] (8db37758-7) 30fd62a6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-19T12:34:45.014793300Z][com.docker.diagnose.exe][W] (8db37758-7) 30fd62a6-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-01-19T12:34:46.020958500Z][com.docker.diagnose.exe][I] (8db37758-8) 30fd62a6-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-01-19T12:34:46.021236800Z][com.docker.diagnose.exe][W] (8db37758-8) 30fd62a6-com.docker.diagnose C<-S NoResponse GET /ping (278.3µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[PASS] DD0013: is the $PATH ok?
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
2023/01/19 18:04:47 exit status 0xffffffff
```

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by OzKron** [comment]
I have the same issue, using latest docker
anyone?

**Comment by Bibins00** [comment]
Me also having this same issue 😴

**Comment by orennu** [comment]
same here, seeing this in %localappdata%\Docker\log.txt

[2023-01-19T15:03:18.146003000Z][com.docker.backend.exe][I] WSLEngine: start handler error exit: 2 errors occurred:
[2023-01-19T15:03:18.146547000Z][GoBackendProcess][I] 	* provisioning docker WSL distros: deploying "docker-desktop": importing WSL distro "docker-desktop": deploying WSL distro "docker-desktop" ("C:\\Program Files\\Docker\\Docker\\resources\\wsl\\wsl-bootstrap.tar" -> "C:\\Users\\<USER>\\AppData\\Local\\Docker\\wsl\\distro"): exit status 0xffffffff
[2023-01-19T15:03:18.146547000Z][GoBackendProcess][I] 	* checking if isocache exists: CreateFile \\wsl$\docker-desktop-data\isocache\: The network name cannot be found.
[2023-01-19T15:03:18.146547000Z][com.docker.backend.exe][W] (1bbc865c) 64416b3c-BackendAPI S->C 1957be84-GoBackendClient-CSharp POST /wsl/engine/start (39.4280722s): 2 errors occurred:
[2023-01-19T15:03:18.147080400Z][GoBackendProcess][I] 	* provisioning docker WSL distros: deploying "docker-desktop": importing WSL distro "docker-desktop": deploying WSL distro "docker-desktop" ("C:\\Program Files\\Docker\\Docker\\resources\\wsl\\wsl-bootstrap.tar" -> "C:\\Users\\<USER>\\AppData\\Local\\Docker\\wsl\\distro"): exit status 0xffffffff
[2023-01-19T15:03:18.147080400Z][GoBackendProcess][I] 	* checking if isocache exists: CreateFile \\wsl$\docker-desktop-data\isocache\: The network name cannot be found.
[2023-01-19T15:03:18.147080400Z][GoBackendProcess][I] [common/cmd/com.docker.backend/internal/handlers/wsl_windows.go:30 github.com/docker/pinata/common/cmd/com.docker.backend/internal/handlers.(*WSLHandler).StartEngine()
[2023-01-19T15:03:18.147080400Z][GoBackendProcess][I] [common/pkg/ipc/server.go:185 github.com/docker/pinata/common/pkg/ipc.(*server).wrapHandlerFunc.func1()
[2023-01-19T15:03:18.147080400Z][GoBackendProcess][I] [github.com/labstack/echo/v4@v4.9.1/echo.go:536 github.com/labstack/echo/v4.(*Echo).add.func1()
[2023-01-19T15:03:18.147080400Z][GoBackendProcess][I] [github.com/labstack/echo/v4@v4.9.1/middleware/recover.go:119 github.com/labstack/echo/v4/middleware.RecoverWithConfig.func1.1()
[2023-01-19T15:03:18.147080400Z][GoBackendProcess][I] [github.com/labstack/echo/v4@v4.9.1/echo.go:646 github.com/labstack/echo/v4.(*Echo).ServeHTTP()
[2023-01-19T15:03:18.147080400Z][GoBackendProcess][I] [net/http/server.go:2947 net/http.serverHandler.ServeHTTP()
[2023-01-19T15:03:18.147080400Z][GoBackendProcess][I] [net/http/server.go:1991 net/http.(*conn).serve()
[2023-01-19T15:03:18.147080400Z][GoBackendProcess][I] [runtime/asm_amd64.s:1594 runtime.goexit()
[2023-01-19T15:03:18.154101100Z][GoBackendClient][E] Error sending starting WSL engine: Docker.Core.HttpBadResponseException: {"message":"2 errors occurred:\n\t* provisioning docker WSL distros: deploying \"docker-desktop\": importing WSL distro \"docker-desktop\": deploying WSL distro \"docker-desktop\" (\"C:\\\\Program Files\\\\Docker\\\\Docker\\\\resources\\\\wsl\\\\wsl-bootstrap.tar\" -\u003e \"C:\\\\Users\\\\orenn\\\\AppData\\\\Local\\\\Docker\\\\wsl\\\\distro\"): exit status 0xffffffff\n\t* checking if isocache exists: CreateFile \\\\wsl$\\docker-desktop-data\\isocache\\: The network name cannot be found.\n\n"}

   at Docker.Core.Logging.HttpClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() in C:\workspaces\PR-19937\src\github.com\docker\pinata\win\src\Docker.Core\Logging\HttpClientExceptionInterceptor.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.IPC.Client.<SendAsync>d__5.MoveNext() in C:\workspaces\PR-19937\src\github.com\docker\pinata\win\src\Docker.Core\IPC\Client.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.GoBackend.GoBackendClient.<PostNoBody>d__18.MoveNext() in C:\workspaces\PR-19937\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 204

**Comment by orennu** [comment]
> Me also having this same issue, But I solved now 😎
> 
> It happens because of there is no WSL (Windows Subsystem for Linux) on your system. So that you have to install or enable WSL on your system. Follow this link to install WSL 👉 https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package
> 
> After that restart your system, then open docker (It my take up to 10 secs to start)
> 
> Hope it may solve your issue✌️

wsl is installed on my system and still having this issue, i tried to install earlier versions but seeing same issue:
```
Failed to deploy distro docker-desktop to C:\Users\orenn\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: The system cannot find the file specified.
```

**Comment by Bibins00** [comment]
> > Me also having this same issue, But I solved now 😎
> > It happens because of there is no WSL (Windows Subsystem for Linux) on your system. So that you have to install or enable WSL on your system. Follow this link to install WSL 👉 https://learn.microsoft.com/en-us/windows/wsl/install-manual#step-4---download-the-linux-kernel-update-package
> > After that restart your system, then open docker (It my take up to 10 secs to start)
> > Hope it may solve your issue✌️
> 
> wsl is installed on my system and still having this issue, i tried to install earlier versions but seeing same issue:
> 
> ```
> Failed to deploy distro docker-desktop to C:\Users\orenn\AppData\Local\Docker\wsl\distro: exit code: -1
>  stdout: The system cannot find the file specified.
> ```

Can you pls confirm your OS type?

**Comment by Dargon789** [comment]
docker not'start run on windows 10 11 error run on wsl-1 wsl-2 
Diagnose Succeeded ID : 0C83EAD9-AD8B-4FC1-A37C-FDA6381EA7D7/20230119172312 
It's been like this since version 15. I've tried many times to solve the problem. update the driver and many things, but always says that it's wrong T_T

**Comment by neandrake** [comment]
Also ran into this on Windows 10 Pro 22H2, 10.0.19045, with WSL 2. I've been using this setup without issue for 1-2 years and this only started happening recently, possibly since the update to Docker Desktop 4.16.1.

I've tried
1. Uninstalling Docker Desktop and also deleting remnants in AppData and ProgramData locations. This required shutting down WSL to make sure a vxd file was deleted.
2. From system tray icon, Troubleshooting -> Clean / Purge Data and Reset to factory defaults.
3. Running `wsl --update` which did update things. I even tried re-installing after doing this.
4. Restarting the machine.
5. Uninstalling VirtualBox 7

Docker still gets hung when starting up. Even when trying to quit/stop/restart it's hung on "Docker Desktop stopping..."

**Comment by Macodom** [comment]
They're going to release new version since this one is bugged, https://github.com/docker/for-win/issues/13165

**Comment by ManOguaR** [comment]
This behavior is due windows securty settings:
Try "Switch to Windows Containers", docker must run ok.
Then if you switch to linux, it will be starting up forever.

Follow the steps (1-8) mentioned in the answer for [this question](https://stackoverflow.com/questions/50126279/cant-start-docker-on-windows).

Hope this helps!

**Comment by kevinferretti** [comment]
Installing the new update resolved the issue for me

**Comment by 5-Jeremy** [comment]
I was still having this issue after the latest update, but I fixed it by enabling Windows Hypervisor Platform in the "Turn Windows features on or off" menu.

**Comment by Rydgel** [comment]
New update doesn't fix it

**Comment by MatiasLGonzalez** [comment]
I've been having this issue since yesterday too, Windows 10 Home with WSL2 backend, today I gave up on using WSL and click the "Switch to Windows containers..." button, I got the pop up about changing to Windows containers, but I noticed that Docker Desktop finally started behind the pop up, I click on cancel on the pop up and now Docker is working as if nothing happened, as a sidenote I left it starting overnight with no luck, so it would be a extreme coincidence if just happened to finish its startup as I click the switch, in case anyone wants to give it a shot

**Comment by p1-0tr** [comment]
hi, for those still experiencing start up with WSL after 4.16.2 - I've created a dev build with possible fixes, if you are willing to give it a go, you can find it here - https://desktop-stage.docker.com/win/main/amd64/96109/Docker%20Desktop%20Installer.exe .

**Comment by neandrake** [comment]
I am continuing to see this issue after upgrading to 4.16.2 (using WSL).

**Comment by p1-0tr** [comment]
This issue is related to https://github.com/docker/for-win/issues/13184 , so I'm closing it as a duplicate.

**Comment by navaidali** [comment]
This worked for me: Go to "Turn Windows features on or off" and enable Containers, Virtual Machine Platform, Windows Hypervisor Platform and Hyper-V.
