### ISSUE TITLE
Update to version 4.16.3 (96739) bricks docker desktop w/ WSL

### ISSUE THREAD

**Issue by localpath** [docker/for-win#13207]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 281AAD03-FB38-4863-9D4A-04A2C31F240D/20230201010715

### Actual behavior
Docker desktop crashes. Will not start properly.
### Expected behavior
Docker desktop operates as previous version
### Information

  - Windows Version: Windows 11 Home 22H2 22621.1105
  - Docker Desktop Version: 4.16.3 (96739)
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```
Please investigate the following 1 issue:

1 : The test: is the WSL 2 Linux filesystem corrupt?
    Failed with: [    6.077447] EXT4-fs warning (device sdf): ext4_clear_journal_err:5640: Filesystem error recorded from previous mount: IO failure
```
### Steps to reproduce the behavior

  1. Update to newest version
  2. Bricks on start

**Comment by p1-0tr** [comment]
hi @localpath , thanks for reporting the issue and sorry for the inconvenience. It seems that DD is having trouble integrating with a distro running on your system. Could you try shutting WSL down (`wsl --shutdown` on the CLI) to make sure there are no lingering processes left running in that distro that could be causing the issue and try starting DD again? If that fails could you manually edit `%appdata%\Docker\settings.json` such that integrations are disabled

    "integratedWslDistros": [],
    "enableIntegrationWithDefaultWslDistro": false,
    
to see if DD starts with the integrations disabled?

**Comment by f2calv** [comment]
I rebooted, still broken.
I downgraded to 4.16.2 and now even that version is broken.

Where is this imaginary settings.json file? 

![image](https://user-images.githubusercontent.com/16097639/216016886-93168510-f78e-46d8-8387-8d8457c6e275.png)

**Comment by p1-0tr** [comment]
The settings file is in `%userprofile%\AppData\Roaming\Docker`

**Comment by Tanzy** [comment]
At the moment looks like I'm going to have to reinstall Windows. The uninstall option is greyed out, so I've manually had to remove all files etc, now when trying to install I get the following. (Note got this before I manually deleted all the files) I'm actually using Windows 11

```Version: 4.16.1 (95567)
Sha1:
Started on: 2023/02/01 11:03:02.786
Resources: C:\Users\xxxx\Downloads\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 22621
BuildLabName: 22621.1.amd64fre.ni_release.220506-1250
File: C:\Users\xxxx\AppData\Local\Docker\install-log.txt
CommandLine: "C:\Users\xxxx\Downloads\Docker Desktop Installer.exe" install
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2023-02-01T11:03:02.989801500Z][ManifestAndExistingInstallationLoader][I] No install path specified, looking for default installation registry key
[2023-02-01T11:03:03.005421400Z][Installer][E] System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Path.GetFullPathInternal(String path)
   at CommunityInstaller.ExistingInstallation.FromRegistry(InstallerSettings settings, String uninstallRegistryKey)
   at CommunityInstaller.ManifestAndExistingInstallationLoader.Load()
   at CommunityInstaller.Program.Resolve(InstallerSettings settings, ILogger log)
   at CommunityInstaller.Program.Run(String[] args)
```

**Comment by p1-0tr** [comment]
@Tanzy please try running the installer with from the CLI `--disable-version-check` (`.\<installer path>.exe install --disable-version-check`)

**Comment by Tanzy** [comment]
@p1-0tr just tried and got this

```
start /w "" "Docker Desktop Installer.exe" install --disable-version-check
-------------------------------------------------------------------------------->8
Version: 4.16.1 (95567)
Sha1:
Started on: 2023/02/01 11:28:21.854
Resources: C:\Users\xxx\Downloads\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 22621
BuildLabName: 22621.1.amd64fre.ni_release.220506-1250
File: C:\Users\xxx\AppData\Local\Docker\install-log.txt
CommandLine: "Docker Desktop Installer.exe"  install --disable-version-check
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2023-02-01T11:28:22.135455200Z][ManifestAndExistingInstallationLoader][I] No install path specified, looking for default installation registry key
[2023-02-01T11:28:22.151089700Z][Installer][E] System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Path.GetFullPathInternal(String path)
   at CommunityInstaller.ExistingInstallation.FromRegistry(InstallerSettings settings, String uninstallRegistryKey)
   at CommunityInstaller.ManifestAndExistingInstallationLoader.Load()
   at CommunityInstaller.Program.Resolve(InstallerSettings settings, ILogger log)
   at CommunityInstaller.Program.Run(String[] args)
```

**Comment by p1-0tr** [comment]
It looks like the installer succeeds at opening `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Docker Desktop`, but the sub keys it expects are missing. Either make sure `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Docker Desktop` is removed. Alternatively, I've attached a zipped `*.reg` file - [desktopinstallerkeys.reg.zip](https://github.com/docker/for-win/files/10556586/desktopinstallerkeys.reg.zip) - with the missing registry keys that are preventing the installer from making progress, so you can import that.

**Comment by Tanzy** [comment]
@p1-0tr that worked thanks 🕺 

I deleted the `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Docker Desktop` registry key, and reran the installer. I've installed version 4.16.1, not sure if I want to risk installing 4.16.3 again

**Comment by hughli-git** [comment]
> @Tanzy please try running the installer with from the CLI `--disable-version-check` (`.\<installer path>.exe install --disable-version-check`)

Thanks a lot, I success install version 4.16.1. hope not freeze any more.

**Comment by NiklasBr** [comment]
My installation also bricked WSL2 and got stuck here: 
![image](https://user-images.githubusercontent.com/279826/216702061-57905a13-da38-41ea-b591-a223bd2da245.png)

**Comment by BoYanZh** [comment]
> It looks like the installer succeeds at opening `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Docker Desktop`, but the sub keys it expects are missing. Please make sure `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Docker Desktop` is removed. Alternatively, I've attached a zipped `*.reg` file - [desktopinstallerkeys.reg.zip](https://github.com/docker/for-win/files/10556586/desktopinstallerkeys.reg.zip) - with the missing registry keys that are preventing the installer from making progress, so you can import that.

Thanks! It works!

**Comment by markalanevans** [comment]
Same here we are bricked

**Comment by NiklasBr** [comment]
/remove-lifecycle stale

There hasn't been any activity because we were waiting for Docker to respond.
