### ISSUE TITLE
Unable to update from 4.16.2 to 4.16.3

### ISSUE THREAD

**Issue by valiko-ua** [docker/for-win#13203]
Nothing happens when I click Download Update button.
Seems issue https://github.com/docker/for-win/issues/13023 came back.
Some error message would be helpful to understand what's going on.

**Comment by siimots** [comment]
Same here

DO NOT UPDATE TO 4.16.3

Everyting is corrupted for me.

Cannot uninstall, cannot update, cannot reinstall...

**Comment by iAmG-r00t** [comment]
Same here

**Comment by iAmG-r00t** [comment]
Now it affects WSL2

**Comment by p1-0tr** [comment]
hi @siimots , what do you mean by corrupted? Are you able to collect diagnostics (https://docs.docker.com/desktop/troubleshoot/overview/#diagnose-from-the-terminal) or provide the contents of `%LOCALAPPDATA%/Docker/log.txt`? Also could you try killing DD and shutting WSL down(you can do that by running `wsl --shutdown`), and starting DD again. If that does not help, manually remove the `docker-desktop` WSL distro `wsl --unregister docker-desktop` and make sure it is no longer in the distro list `wsl -l --all -v`.

**Comment by siimots** [comment]
I updated 3 PCs.

1. Updated fine.

2. Installed but failed to "Docker Desktop Failed to start"
```Docker.Core.HttpBadResponseException:
{"message":"1 error occurred:\n\t* starting WSL integration service: synchronising agents: starting added distros: 1 error occurred:\n\t* waiting for WSL integration for Ubuntu: timed out while polling for WSL distro integration to become ready in \"Ubuntu\"\n\n\n\n"}

   at Docker.Core.GoBackend.GoBackendClient.<PostNoBodyWithError>d__19.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 226
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__11.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__15.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__23.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 109
```
Also attached [log.txt](https://github.com/docker/for-win/files/10543811/log.txt)
Used gather upload diagnostic for PC nr 2.

3. Updater installer got stuck for 1 hour after Desktop shortcut creation. So I guess it was almost completed, but never finished. Had to reboot.
Then I was unable to reinstall from exe, no uninstaller/repair in Add/Remove programs. I had to use my backup system image to restore.

**Comment by p1-0tr** [comment]
@siimots , thanks for getting back to me. On PC nr 2 could you check if the problem persists through a `wsl --shutdown` and/or reboot (that should get rid of any lingering state that may have been leftover by the previous version)?

Case (3) sounds concerning, I'll flag it to someone who knows the installer better.

**Comment by HeXx123321** [comment]
@p1-0tr, I had a similar issue but your fix helped me;  `wsl --shutdown` worked for me thanks :)

FYI - DD v4.16.3, Ubuntu 20.04.4 LTS

I came from a community forum issue where the docker engine was failing to start for some weird unknown reason

**Comment by Abdesselem18275** [comment]
1. Update all packages `sudo apt update`
2. Upgrade all packages `sudo apt upgrade`
3. Restart WSL `wsl --shutdown` then `wsl -d <DistributionName>`

DISTRO : Ubuntu 20.04.4 LTS

**Comment by Franky1** [comment]
On one of my windows 10 machines, docker also did not work anymore after update to the version `4.16.3`
I tried a few things, which of them was ultimately the solution, I can't say for sure:

First, I uninstalled/removed the current Docker Desktop version.
I deleted all Docker* directories under `Program*` and `AppData/Local` and `AppData/Roaming`
Then I installed an older version 4.15.0 from the release page.
Still did not work.
Deleted again.
Then manually killed the WSL process because it was hanging
Then updated WSL with `wsl --update`
Then installed version 4.15.0 again.
The docker started again, but with an error message.
In Docker Desktop under Troubleshoot i selected the option `Reset to factory defaults`
Then Docker worked.

In between rebooted again and again of course....

**Comment by XedinUnknown** [comment]
I upgraded everything inside WSL, upgraded WSL itself, and it works now.

**Comment by saschanaz** [comment]
/remove-lifecycle stale

A workaround is to enable the background update. You still won't be able to hit the update button but at some point Docker will automatically update.
