### ISSUE TITLE
Docker hangs after starting and stopping a large number of containers in parallel

### ISSUE THREAD

**Issue by axelfontaine** [docker/for-win#13218]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior

Docker hangs after starting about 30-40 containers in rapid succession. The status in the GUI is still green, however when attempting a restart an error dialog is then presented:

```
Docker.Core.HttpBadResponseException:
{"message":"1 error occurred:\n\t* starting WSL integration service: integration service is already running\n\n"}

   at Docker.Core.GoBackend.GoBackendClient.<PostNoBodyWithError>d__19.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 226
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__11.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__15.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__23.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 109
```

### Expected behavior

Doesn't hang.

### Information
  - Windows Version: 11 22H2 x64
  - Docker Desktop Version: 4.16.3
  - WSL2 or Hyper-V backend?  WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

```
[2023-02-04T14:54:00.734669700Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[2023-02-04T14:54:04.459933700Z][com.docker.diagnose.exe][I] ipc.NewClient: 81349d53-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[common/pkg/diagkit/gather/diagnose.glob..func14()
[       common/pkg/diagkit/gather/diagnose/linuxkit.go:18 +0x8b
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0xeeb440)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0xeeb440)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x4?, 0xeeb440)
[       common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0xeeb440, 0xc00031d728)
[       common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0xeeb4c0, 0xc00031d728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0xeeb540, 0xc00031d728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xeebcc0, 0xc00031d728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkOnce(0x87e8a0?, 0xc0002df890)
[       common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0xeebcc0, 0xaa21811a00000010?, {0xc0002dfb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc0000963b0?, 0xc0000963b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:138 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:102 +0x27f
[2023-02-04T14:54:04.460456300Z][com.docker.diagnose.exe][I] (f03d6295) 81349d53-diagnose C->S diagnosticsd GET /ping
[2023-02-04T14:54:04.460980900Z][com.docker.diagnose.exe][W] (f03d6295) 81349d53-diagnose C<-S NoResponse GET /ping (524.6µs): Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-04T14:54:04.462013500Z][com.docker.diagnose.exe][I] ipc.NewClient: 77c7c6ac-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClientForPath(...)
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:63
[linuxkit/pkg/desktop-host-tools/pkg/client.NewClient({0x943bdc, 0x13})
[       linuxkit/pkg/desktop-host-tools/pkg/client/client.go:57 +0x99
[common/pkg/diagkit/gather/diagnose.isDockerEngineRunning()
[       common/pkg/diagkit/gather/diagnose/dockerd.go:21 +0x29
[common/pkg/diagkit/gather/diagnose.(*test).GetResult(0xeeb4c0)
[       common/pkg/diagkit/gather/diagnose/test.go:46 +0x43
[common/pkg/diagkit/gather/diagnose.Run.func1(0xeeb4c0)
[       common/pkg/diagkit/gather/diagnose/run.go:17 +0x5a
[common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x3?, 0xeeb4c0)
[       common/pkg/diagkit/gather/diagnose/run.go:142 +0x77
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0xeeb4c0, 0xc0005b7728)
[       common/pkg/diagkit/gather/diagnose/run.go:151 +0x87
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0xeeb540, 0xc0005b7728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0xeebcc0, 0xc0005b7728)
[       common/pkg/diagkit/gather/diagnose/run.go:148 +0x52
[common/pkg/diagkit/gather/diagnose.walkOnce(0x87e8a0?, 0xc0002df890)
[       common/pkg/diagkit/gather/diagnose/run.go:137 +0xcc
[common/pkg/diagkit/gather/diagnose.Run(0xeebcc0, 0xaa21811a00000010?, {0xc0002dfb20, 0x1, 0x1})
[       common/pkg/diagkit/gather/diagnose/run.go:16 +0x1d4
[main.checkCmd({0xc0000963b0?, 0xc0000963b0?, 0x4?}, {0x0, 0x0})
[       common/cmd/com.docker.diagnose/main.go:138 +0x105
[main.main()
[       common/cmd/com.docker.diagnose/main.go:102 +0x27f
[2023-02-04T14:54:04.462013500Z][com.docker.diagnose.exe][I] (d098b1e6) 77c7c6ac-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2023-02-04T14:54:04.462538600Z][com.docker.diagnose.exe][W] (d098b1e6) 77c7c6ac-com.docker.diagnose C<-S NoResponse GET /docker (525.1µs): Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-04T14:54:04.462538600Z][com.docker.diagnose.exe][I] (d098b1e6-1) 77c7c6ac-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-04T14:54:04.463064200Z][com.docker.diagnose.exe][W] (d098b1e6-1) 77c7c6ac-com.docker.diagnose C<-S NoResponse GET /ping (525.6µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-04T14:54:05.466795800Z][com.docker.diagnose.exe][I] (d098b1e6-2) 77c7c6ac-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-04T14:54:05.466795800Z][com.docker.diagnose.exe][W] (d098b1e6-2) 77c7c6ac-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-04T14:54:06.475748900Z][com.docker.diagnose.exe][I] (d098b1e6-3) 77c7c6ac-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-04T14:54:06.475748900Z][com.docker.diagnose.exe][W] (d098b1e6-3) 77c7c6ac-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-04T14:54:07.486948500Z][com.docker.diagnose.exe][I] (d098b1e6-4) 77c7c6ac-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-04T14:54:07.486948500Z][com.docker.diagnose.exe][W] (d098b1e6-4) 77c7c6ac-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-04T14:54:08.497198600Z][com.docker.diagnose.exe][I] (d098b1e6-5) 77c7c6ac-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-04T14:54:08.497198600Z][com.docker.diagnose.exe][W] (d098b1e6-5) 77c7c6ac-com.docker.diagnose C<-S NoResponse GET /ping (77.9µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-04T14:54:09.507066100Z][com.docker.diagnose.exe][I] (d098b1e6-6) 77c7c6ac-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-04T14:54:09.507613900Z][com.docker.diagnose.exe][W] (d098b1e6-6) 77c7c6ac-com.docker.diagnose C<-S NoResponse GET /ping (547.8µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-04T14:54:10.517779200Z][com.docker.diagnose.exe][I] (d098b1e6-7) 77c7c6ac-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-04T14:54:10.517779200Z][com.docker.diagnose.exe][W] (d098b1e6-7) 77c7c6ac-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-02-04T14:54:11.526360800Z][com.docker.diagnose.exe][I] (d098b1e6-8) 77c7c6ac-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-02-04T14:54:11.526456600Z][com.docker.diagnose.exe][W] (d098b1e6-8) 77c7c6ac-com.docker.diagnose C<-S NoResponse GET /ping (95.8µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[PASS] DD0013: is the $PATH ok?
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[FAIL] DD0014: are the backend processes running? 1 error occurred:
        * com.docker.wsl-distro-proxy.exe is not running


[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[FAIL] DD0009: is the vpnkit API responding? open \\.\pipe\dockerVpnKitDiagnostics: The system cannot find the file specified.
[PASS] DD0010: is the Docker API proxy responding?
[PASS] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[WARN] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[WARN] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[PASS] DD0015: are the binary symlinks installed?
[WARN] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[WARN] DD0032: do Docker networks overlap with host IPs? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/networks": open //./pipe/docker_engine_linux: The system cannot find the file specified.

Please note the following 4 warnings:

1 : The check: are the LinuxKit services running?
    Produced the following warning: failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

The Docker engine runs inside a Linux VM as a service. Therefore the services must have started.

2 : The check: is the Docker engine running?
    Produced the following warning: Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

The Docker engine manages all containers and images on the host. Check the dockerd.log to see why it failed to start.

3 : The check: does the Docker API work?
    Produced the following warning: error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.

If the Docker API is not available from the host then Docker Desktop will not work correctly.

4 : The check: do Docker networks overlap with host IPs?
    Produced the following warning: error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/networks": open //./pipe/docker_engine_linux: The system cannot find the file specified.

If the subnet used by a Docker network overlaps with an IP used by the host, then containers
won't be able to contact the overlapping IP addresses.

Try configuring the IP address range used by networks: in your docker-compose.yml.
See https://docs.docker.com/compose/compose-file/compose-file-v2/#ipv4_address-ipv6_address


Please investigate the following 2 issues:

1 : The test: are the LinuxKit services running?
    Failed with: failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

The Docker engine runs inside a Linux VM as a service. Therefore the services must have started.

2 : The test: are the backend processes running?
    Failed with: 1 error occurred:
        * com.docker.wsl-distro-proxy.exe is not running



Not all of the backend processes are running.
```

### Steps to reproduce the behavior

Start and stop a 100 containers in parallel.

**Comment by STaRDoGG** [comment]
After a reboot I was getting this as well:

```
Docker.Core.HttpBadResponseException:
{"message":"1 error occurred:\n\t* starting WSL integration service: integration service is already running\n\n"}

   at Docker.Core.GoBackend.GoBackendClient.<PostNoBodyWithError>d__19.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 226
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__11.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__15.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__23.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 109
```

After a search, this was the "[fix](https://stackoverflow.com/a/75444497/553663)" that worked for me.

**Comment by jonasraoni** [comment]
I've just deleted a bunch of images and got this error as well.
Restarting the computer/Docker didn't help, what solved for me was to shutdown WSL: `wsl --shutdown`.

**Comment by axelfontaine** [comment]
I decided the weeks of instability with Docker Desktop had finally been enough and moved to a bare WSL2 setup.

These are the steps I followed:
1. `wsl --import ubuntu 22.04`
2. [Enable WSL2 systemd support](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#systemd-support)
3. [Install Docker in the WSL2 distro](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository)
4. Set `DOCKER_HOST=tcp://localhost:2375`
5. `wsl socat TCP-LISTEN:2375,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock`

Voila!

Open a new terminal window and both the Windows Docker CLI and Testcontainers now work flawlessly!

For volumes make sure to use the WSL2 path (`/mnt/c/...`) instead of the Windows path (`C:\...`)

**Comment by STaRDoGG** [comment]
> I decided the weeks of instability with Docker Desktop had finally been enough and moved to a bare WSL2 setup.
> 
> These are the steps I followed:
> 
> 1. `wsl --import ubuntu 22.04`
> 2. [Enable WSL2 systemd support](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#systemd-support)
> 3. [Install Docker in the WSL2 distro](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository)
> 4. Set `DOCKER_HOST=tcp://localhost:2375`
> 5. `wsl socat TCP-LISTEN:2375,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock`
> 
> Voila!
> 
> Open a new terminal window and both the Windows Docker CLI and Testcontainers now work flawlessly!
> 
> For volumes make sure to use the WSL2 path (`/mnt/c/...`) instead of the Windows path (`C:\...`)

Been thinking about doing this myself. Docker Desktop seems like beta software at this point, and no apparent, solid, testing before getting released.

**Comment by jonasraoni** [comment]
I've noticed some random bad issues at the latest updates 🙂

After this one happened, whenever I start Docker it starts to eat my disk, and kills the whole system performance, I've got an instance installed inside the WSL distro, so I'll probably just use it. Also, keeping the shared folders on the Linux filesystem should probably give a nice bump to the performance.

**Comment by YouveGotMeowxy** [comment]
@axelfontaine 

I'm not the greatest with Linux, are these 2 steps both done within WSL/Ubuntu? Or do any of them need to be done in Windows?

> 4. Set `DOCKER_HOST=tcp://localhost:2375`
> 5. `wsl socat TCP-LISTEN:2375,reuseaddr,fork UNIX-CONNECT:/var/run/docker.sock`

(Thinking out loud here) It looks like #5 is done within WSL so it opens port 2375 on the WSL side, right? But #4 I'm not really sure if it's supposed to be done in Windows or WSL?
