### ISSUE TITLE
t* provisioning docker WSL distros: deploying \"docker-desktop\": importing WSL distro \"docker-desktop\": deploying WSL distro \"docker-desktop\" (\"C:\\\\Program Files\\\\Docker\\\\Docker\\\\resources\\\\wsl\\\\wsl-bootstrap.tar\" -\u003e \"C:\\\\Users\\\\USER\\\\AppData\\\\Local\\\\Docker\\\\wsl\\\\distro\"): exit status 0xffffffff\n\t* checking if isocache exists: CreateFile \\\\wsl$\\docker-desktop-data\\isocache\\: The network name cannot be found.\n\n"}

### ISSUE THREAD

**Issue by bowrey** [docker/for-win#13234]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by fspider** [comment]
I am having the same issue.

```
Docker.Core.HttpBadResponseException:
{"message":"2 errors occurred:\n\t* provisioning docker WSL distros: running wsl-bootstrap version set in main distro: exit status 0xffffffff\n\t* checking if isocache exists: CreateFile \\\\wsl$\\docker-desktop-data\\isocache\\: The network name cannot be found.\n\n"}

   at Docker.Core.GoBackend.GoBackendClient.<PostNoBodyWithError>d__19.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 226
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__11.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__15.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__23.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 109

```

**Comment by khaihoan123** [comment]
> I am having the same issue.
> 
> ```
> Docker.Core.HttpBadResponseException:
> {"message":"2 errors occurred:\n\t* provisioning docker WSL distros: running wsl-bootstrap version set in main distro: exit status 0xffffffff\n\t* checking if isocache exists: CreateFile \\\\wsl$\\docker-desktop-data\\isocache\\: The network name cannot be found.\n\n"}
> 
>    at Docker.Core.GoBackend.GoBackendClient.<PostNoBodyWithError>d__19.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 226
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__11.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 54
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 91
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 118
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__15.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Docker.Engines.Engines.<StartAsync>d__23.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 109
> ```

same issue, how to fix it

**Comment by p1-0tr** [comment]
hi @khaihoan123, could you try running `wsl --shutdown` and then starting DD and if that does not help, updating WSL (`wsl --update`)?

**Comment by khaihoan123** [comment]
> hi @khaihoan123, could you try running `wsl --shutdown` and then starting DD and if that does not help, updating WSL (`wsl --update`)?

it's not work, still failed

**Comment by sunyang93** [comment]
Docker.Core.HttpBadResponseException:
{"message":"2 errors occurred:\n\t* provisioning docker WSL distros: terminating WSL distro \"docker-desktop\": terminating WSL distro \"docker-desktop\": exit status 0xffffffff\n\t* checking if isocache exists: CreateFile \\\\wsl$\\docker-desktop-data\\isocache\\: The network name cannot be found.\n\n"}

   在 Docker.Core.GoBackend.GoBackendClient.<PostNoBodyWithError>d__19.MoveNext() 位置 C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:行号 226
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__11.MoveNext() 位置 C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:行号 54
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() 位置 C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:行号 29
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() 位置 C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:行号 91
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() 位置 C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:行号 118
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__15.MoveNext() 位置 C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:行号 72
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.Engines.Engines.<SwitchDaemonAsync>d__28.MoveNext() 位置 C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:行号 267
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Docker.Engines.Engines.<SwitchDaemonAsync>d__28.MoveNext() 位置 C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:行号 288
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Docker.ApiServices.Services.DesktopService.<SwitchDaemonAsync>d__4.MoveNext() 位置 C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\Services\DesktopService.cs:行号 39

**Comment by baal1986** [comment]
Блять сделайте уже обновление долбаебы

**Comment by demiluke** [comment]
This is also happening to me.

`Docker.Core.HttpBadResponseException:
{"message":"1 error occurred:\n\t* provisioning docker WSL distros: terminating WSL distro \"docker-desktop\": terminating WSL distro \"docker-desktop\": exit status 0xffffffff\n\n"}

   at Docker.Core.GoBackend.GoBackendClient.<PostNoBodyWithError>d__19.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 226
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__11.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__15.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__23.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 109
`

attempted the reset to factory defaults which failed with the same error

**Comment by zhouhu949** [comment]
same error is here 
`Error details:
2 errors occurred:
	* provisioning docker WSL distros: deploying "docker-desktop": importing WSL distro "\xe0e\xd5l\x10b\x9fR\x8c[\x10b\xcdd\\O\f\xff\xe0V:N\x87e\xf6N\x05S+T\xc5u\xd2k\x16b\\o(W\x84v\x83W>Wo\x8f\xf6N\x020 \x00\r\x00\n\x00E\x00r\x00r\x00o\x00r\x00 \x00c\x00o\x00d\x00e\x00:\x00 \x00W\x00s\x00l\x00/\x00S\x00e\x00r\x00v\x00i\x00c\x00e\x00/\x00C\x00r\x00e\x00a\x00t\x00e\x00V\x00m\x00/\x000\x00x\x008\x000\x000\x007\x000\x000\x00e\x001\x00\r\x00\n\x00" output="docker-desktop": running WSL command "wsl.exe --import docker-desktop C:\\Users\\hu.zhou\\AppData\\Local\\Docker\\wsl\\distro C:\\Program Files\\Docker\\Docker\\resources\\wsl\\wsl-bootstrap.tar --version 2" failed with output "\xe0e\xd5l\x10b\x9fR\x8c[\x10b\xcdd\\O\f\xff\xe0V:N\x87e\xf6N\x05S+T\xc5u\xd2k\x16b\\o(W\x84v\x83W>Wo\x8f\xf6N\x020 \x00\r\x00\n\x00E\x00r\x00r\x00o\x00r\x00 \x00c\x00o\x00d\x00e\x00:\x00 \x00W\x00s\x00l\x00/\x00S\x00e\x00r\x00v\x00i\x00c\x00e\x00/\x00C\x00r\x00e\x00a\x00t\x00e\x00V\x00m\x00/\x000\x00x\x008\x000\x000\x007\x000\x000\x00e\x001\x00\r\x00\n\x00": exit status 0xffffffff
	* checking if isocache exists: CreateFile \\wsl$\docker-desktop-data\isocache\: The network name cannot be found.`

**Comment by pieterocp** [comment]
Also have the same issue, cannot even run the diagnostics either @docker-robot that fails with 

```
Cannot process diagnostics. Reason: Error invoking remote method 'desktop-go-backend': Error: {"message":"[2023-03-20T12:06:05.676637100Z][com.docker.diagnose.exe][I] set path configuration to OnHost\nGathering diagnostics for ID C12233BA-8EE7-4BE8-BC2D-86BCDC94CEC8/20230320120538 into C:\\Users\\User\\AppData\\Local\\Temp\\C12233BA-8EE7-4BE8-BC2D-86BCDC94CEC8\\20230320120538.zip.\nThis may take up to 15 minutes.\ntime=\"2023-03-20T12:06:05Z\" level=info msg=\"Triggering Linux sysrq and log flushes via a unix socket: \\\\\\\\.\\\\pipe\\\\dockerDiagnosticd\" type=unixsock\ntime=\"2023-03-20T12:06:05Z\" level=warning msg=\"/flush failed: Post \\\"http://unix/flush\\\": open \\\\\\\\.\\\\pipe\\\\dockerDiagnosticd: The system cannot find the file specified.\" type=unixsock\nunable to trigger dns-forwarder diagnostics: Post \"http://ipc/diagnostics\": open \\\\.\\pipe\\dockerDnsForwarder: The system cannot find the file specified.\ntime=\"2023-03-20T12:06:12Z\" level=info msg=\"Start gathering list of 133 elements (timeout=15m0s)\" type=list\ntime=\"2023-03-20T12:06:12Z\" level=info msg=\"Gathering DiagKit\" type=list\ntime=\"2023-03-20T12:06:12Z\" level=info msg=\"Gathering LifecycleServerGatherer\" type=list\ntime=\"2023-03-20T12:06:12Z\" level=info msg=\"Gathering ProxyAPIGatherer\" type=list\ntime=\"2023-03-20T12:06:12Z\" level=info msg=\"Gathering BackendGatherer\" type=list\ntime=\"2023-03-20T12:06:12Z\" level=info msg=\"Gathering DiagKit took 1.1401ms\" type=list\ntime=\"2023-03-20T12:06:12Z\" level=info msg=\"Gathering system\" type=list\ntime=\"2023-03-20T12:06:12Z\" level=info msg=\"Executing: [powershell -NoProfile -Command &{ $(Get-WmiObject Win32_OperatingSystem) | ConvertTo-json -Depth 1 }]\"\ntime=\"2023-03-20T12:06:13Z\" level=info msg=\"Executing: [powershell -NoProfile -Command &{ $(Get-WmiObject Win32_ComputerSystem) | ConvertTo-json -Depth 1 }]\"\ntime=\"2023-03-20T12:06:13Z\" level=info msg=\"Executing: [powershell -NoProfile -Command &{ $(Get-WmiObject Win32_Processor) | ConvertTo-json -Depth 1 }]\"\ntime=\"2023-03-20T12:06:13Z\" level=info msg=\"Gathering BackendGatherer took 789.8328ms\" type=list\ntime=\"2023-03-20T12:06:13Z\" level=info msg=\"Gathering ProcessGatherer\" type=list\ntime=\"2023-03-20T12:06:13Z\" level=info msg=\"Gathering ProcessGatherer took 13.6172ms\" type=list\ntime=\"2023-03-20T12:06:13Z\" level=info msg=\"Gathering typeperf \\\\Process(*)\\\\% Processor Time (timeout 0s)-sc (timeout 0s)5 (timeout 0s)-y\" type=list\ntime=\"2023-03-20T12:06:13Z\" level=info msg=\"Executing: [typeperf \\\\Process(*)\\\\% Processor Time -sc 5 -y]\"\ntime=\"2023-03-20T12:06:14Z\" level=info msg=\"Executing: [powershell -NoProfile -Command &{ $(Get-WmiObject Win32_BaseBoard) | ConvertTo-json -Depth 1 }]\"\ntime=\"2023-03-20T12:06:15Z\" level=info msg=\"Executing: [powershell -NoProfile -Command &{ Get-Item 'Registry::HKEY_LOCAL_MACHINE\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion' }]\"\ntime=\"2023-03-20T12:06:15Z\" level=info msg=\"Executing: [powershell -NoProfile -Command &{ Get-MpComputerStatus }]\"\nerror during connect: This error may indicate that the docker daemon is not running.: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json\": open //./pipe/docker_engine: The system cannot find the file specified.\ntime=\"2023-03-20T12:06:16Z\" level=info msg=\"Executing: [powershell -NoProfile -Command &{ $PSVersionTable }]\"\ntime=\"2023-03-20T12:06:16Z\" level=info msg=\"Gathering system took 3.5468502s\" type=list\ntime=\"2023-03-20T12:06:16Z\" level=info msg=\"Gathering tasklist /V\" type=list\ntime=\"2023-03-20T12:06:16Z\" level=info msg=\"Executing: [tasklist /V]\"\n2023/03/20 12:06:16 exit status 0xffffffff\n: exit status 1"}
```

Error on starting up docker desktop.

```
Docker.Core.HttpBadResponseException:
{"message":"1 error occurred:\n\t* provisioning docker WSL distros: terminating WSL distro \"docker-desktop\": terminating WSL distro \"docker-desktop\": exit status 0xffffffff\n\n"}

   at Docker.Core.GoBackend.GoBackendClient.<PostNoBodyWithError>d__19.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 226
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__11.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__15.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__23.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 109

```
