### ISSUE TITLE
Installing Docker Desktop while setting installation directory fails

### ISSUE THREAD

**Issue by MichaelNZ85** [docker/for-win#13254]
### Actual behavior
Attempting to install Docker Desktop for Windows from the Windows Command Prompt fails with an UnauthorizedAccessException.
### Expected behavior
Docker Desktop installs to specified directory and runs.
### Information
Attempting to install Docker Desktop from an Administrator command prompt with the following command
```
"Docker Desktop Installer.exe" install --installation-dir=E:\Docker
```
fails with the following error message: 
```
 Installation failed System.Exception: Unpacking failed: Attempted to perform an unauthorized operation. ---> System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
```
**Full output:**
```
D:\Downloads>"Docker Desktop Installer.exe" install --installation-dir=E:\Docker

D:\Downloads>-------------------------------------------------------------------------------->8
Version: 4.16.3 (96739)
Sha1:
Started on: 2023/02/20 11:29:20.143
Resources: D:\Downloads\resources
OS: Windows 10 Home
Edition: Core
Id: 2009
Build: 19045
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\ProgramData\DockerDesktop\install-log-admin.txt
CommandLine: "Docker Desktop Installer.exe"  install --installation-dir=E:\Docker
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2023-02-20T11:29:20.380040300Z][ManifestAndExistingInstallationLoader][I] Install path is E:\Docker. Loading manifest first
[2023-02-20T11:29:20.391392900Z][ManifestAndExistingInstallationLoader][I] No manifest found, returning no existing install
[2023-02-20T11:29:20.392448900Z][Installer][I] No installation found
[2023-02-20T11:29:20.643298600Z][InstallWorkflow][I] Cancel pending background download
[2023-02-20T11:29:20.645293300Z][BackgroundTransfer][I] Cancel current background transfer job
[2023-02-20T11:29:24.928877400Z][InstallWorkflow][I] Using package: res:DockerDesktop
[2023-02-20T11:29:24.930879300Z][InstallWorkflow][I] Downloading
[2023-02-20T11:29:27.807495100Z][InstallWorkflow][I] Extracting manifest
[2023-02-20T11:29:28.708493700Z][InstallWorkflow][I] Manifest found: version=96739, displayVersion=4.16.3, channelUrl=https://desktop.docker.com/win/main/amd64/appcast.xml
[2023-02-20T11:29:28.708493700Z][InstallWorkflow][I] Checking prerequisites
[2023-02-20T11:29:29.183549200Z][InstallWorkflow][I] Prompting for optional features
[2023-02-20T11:29:31.093060300Z][Installer][W] Failed to track the installer started event
[2023-02-20T11:29:45.483314400Z][InstallWorkflow][I] Selected backend mode: wsl-2
[2023-02-20T11:29:45.484312400Z][InstallWorkflow][I] Unpacking artifacts
[2023-02-20T11:29:45.504313400Z][InstallWorkflow][E] Installation failed System.Exception: Unpacking failed: Attempted to perform an unauthorized operation. ---> System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at System.Security.AccessControl.Win32.GetSecurityInfo(ResourceType resourceType, String name, SafeHandle handle, AccessControlSections accessControlSections, RawSecurityDescriptor& resultSd)
   at System.Security.AccessControl.NativeObjectSecurity.CreateInternal(ResourceType resourceType, Boolean isContainer, String name, SafeHandle handle, AccessControlSections includeSections, Boolean createByName, ExceptionFromErrorCode exceptionFromErrorCode, Object exceptionContext)
   at System.Security.AccessControl.FileSystemSecurity..ctor(Boolean isContainer, String name, AccessControlSections includeSections, Boolean isDirectory)
   at System.Security.AccessControl.DirectorySecurity..ctor(String name, AccessControlSections includeSections)
   at System.IO.DirectoryInfo.GetAccessControl()
   at Docker.Core.PermissionUtils.RemoveGlobalWrite(ILogger logger, String path) in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Core\PermissionUtils.cs:line 22
   at CommunityInstaller.UnpackArtifactsStep.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[2023-02-20T11:29:45.506797900Z][InstallWorkflow][I] Rollbacking component CommunityInstaller.ExtractManifestStep
[2023-02-20T11:29:45.508729300Z][InstallWorkflow][I] Rollbacking component CommunityInstaller.DownloadStep
```

**Please, just add the ability to select an installation directory to the installer like most installers have!**

  - Windows Version: Windows 10 Home 22H2
  - Docker Desktop Version: None as not installed yet
  - WSL2 or Hyper-V backend?  Will use WSL but not installed yet
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
Not relevant as Docker is not installed

### Steps to reproduce the behavior

  1. Download the Docker Desktop installer
  2. Open up a Windows command prompt as an administrator
  3. Run the following command: `"Docker Desktop Installer.exe" install --installation-dir=E:\Docker`
  4. Docker Desktop installer will open, click "Ok"
  5. The following screen should appear:

![WindowsTerminal_piA6qSxu7q](https://user-images.githubusercontent.com/15241383/220095937-5559f4d2-e08d-4549-87a3-3233240b69a4.png)

**Comment by MichaelNZ85** [comment]
Turns out it was a permission issue with that particular folder. When I tried to open it, it popped up saying 'You don't currently have permission to access this folder' or the like. Deleted it and it installed fine
