### ISSUE TITLE
WSL already running exception

### ISSUE THREAD

**Issue by aguedeney** [docker/for-win#13263]
- [X] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:E44F1ACF-D53E-4B63-A263-42F02A550E0F/20230226202555

### Actual behavior
Start Docker Desktop after installation, then set WSL2 and it fails with WSL already running.

### Expected behavior
Start Docker Desktop without errors

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

An Error Occurred Dialog

 at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(
![Capture](https://user-images.githubusercontent.com/9642883/221437731-437b0d2f-4f06-4b96-af66-51277638dbb2.PNG)
)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__15.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__23.MoveNext() in C:\workspaces\4.16.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 109

**Comment by sam-thibault** [comment]
We have just release 4.17.0 that contains several fixes around the WSL integration.  Can you try the latest version?
Release notes (and links to installers) here: https://docs.docker.com/desktop/release-notes/
