### ISSUE TITLE
Docker Desktop 4.17.0 fails to start

### ISSUE THREAD

**Issue by LeviPesin** [docker/for-win#13310]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F7452781-0CA0-47E5-BDFA-EE163E156BA0/20230317085429

### Actual behavior
Docker Desktop throws the following error after about ~10 minutes trying to start:
```
Docker.Core.HttpBadResponseException:
{"message":"checking windows features: Post \"http://ipc/windowsfeatures/check\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"}

   at Docker.Core.Logging.HttpClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() in C:\workspaces\4.17.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\HttpClientExceptionInterceptor.cs:line 26
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.IPC.Client.<SendAsync>d__5.MoveNext() in C:\workspaces\4.17.x\src\github.com\docker\pinata\win\src\Docker.Core\IPC\Client.cs:line 42
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.GoBackend.GoBackendClient.<WSLEngineCheckPreconditions>d__42.MoveNext() in C:\workspaces\4.17.x\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 405
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoCheckPreconditionsAsync>d__19.MoveNext() in C:\workspaces\4.17.x\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 194
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\4.17.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__7.MoveNext() in C:\workspaces\4.17.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 74
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__15.MoveNext() in C:\workspaces\4.17.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__23.MoveNext() in C:\workspaces\4.17.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 109
```

### Expected behavior
Docker Desktop starts properly.

### Information
  - Windows Version: Windows 10 Home 22H2
  - Docker Desktop Version: 4.17.0
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

```
[2023-03-17T09:07:28.943116500Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[2023-03-17T09:08:02.561019800Z][com.docker.diagnose.exe][I] ipc.NewClient: 3b2d3c2b-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[2023-03-17T09:08:02.562250600Z][com.docker.diagnose.exe][I] (894bf9e6) 3b2d3c2b-diagnose C->S diagnosticsd GET /ping
[2023-03-17T09:08:02.563883600Z][com.docker.diagnose.exe][W] (894bf9e6) 3b2d3c2b-diagnose C<-S NoResponse GET /ping (1.1157ms): Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-17T09:08:02.578824800Z][com.docker.diagnose.exe][I] ipc.NewClient: 2674fd56-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[2023-03-17T09:08:02.580071800Z][com.docker.diagnose.exe][I] (ec493400) 2674fd56-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2023-03-17T09:08:02.582879000Z][com.docker.diagnose.exe][W] (ec493400) 2674fd56-com.docker.diagnose C<-S NoResponse GET /docker (2.8072ms): Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-17T09:08:02.583997100Z][com.docker.diagnose.exe][I] (ec493400-1) 2674fd56-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-17T09:08:02.585800900Z][com.docker.diagnose.exe][W] (ec493400-1) 2674fd56-com.docker.diagnose C<-S NoResponse GET /ping (1.8038ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-17T09:08:03.602050000Z][com.docker.diagnose.exe][I] (ec493400-2) 2674fd56-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-17T09:08:03.603207700Z][com.docker.diagnose.exe][W] (ec493400-2) 2674fd56-com.docker.diagnose C<-S NoResponse GET /ping (1.5242ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-17T09:08:04.609691700Z][com.docker.diagnose.exe][I] (ec493400-3) 2674fd56-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-17T09:08:04.611050900Z][com.docker.diagnose.exe][W] (ec493400-3) 2674fd56-com.docker.diagnose C<-S NoResponse GET /ping (1.3592ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-17T09:08:05.627417100Z][com.docker.diagnose.exe][I] (ec493400-4) 2674fd56-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-17T09:08:05.629144700Z][com.docker.diagnose.exe][W] (ec493400-4) 2674fd56-com.docker.diagnose C<-S NoResponse GET /ping (739.4µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-17T09:08:06.637600100Z][com.docker.diagnose.exe][I] (ec493400-5) 2674fd56-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-17T09:08:06.638601100Z][com.docker.diagnose.exe][W] (ec493400-5) 2674fd56-com.docker.diagnose C<-S NoResponse GET /ping (1.001ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-17T09:08:07.648298000Z][com.docker.diagnose.exe][I] (ec493400-6) 2674fd56-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-17T09:08:07.649137200Z][com.docker.diagnose.exe][W] (ec493400-6) 2674fd56-com.docker.diagnose C<-S NoResponse GET /ping (839.2µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-17T09:08:08.655813100Z][com.docker.diagnose.exe][I] (ec493400-7) 2674fd56-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-17T09:08:08.657803600Z][com.docker.diagnose.exe][W] (ec493400-7) 2674fd56-com.docker.diagnose C<-S NoResponse GET /ping (1.9905ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-17T09:08:09.660717900Z][com.docker.diagnose.exe][I] (ec493400-8) 2674fd56-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-17T09:08:09.661765200Z][com.docker.diagnose.exe][W] (ec493400-8) 2674fd56-com.docker.diagnose C<-S NoResponse GET /ping (1.0473ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[PASS] DD0013: is the $PATH ok?
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[FAIL] DD0014: are the backend processes running? 2 errors occurred:
        * com.docker.vpnkit.exe is not running
        * com.docker.proxy.exe is not running


[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[FAIL] DD0009: is the vpnkit API responding? open \\.\pipe\dockerVpnKitDiagnostics: The system cannot find the file specified.
[FAIL] DD0010: is the Docker API proxy responding? failed to ping Docker proxy API with error: Get "http://ipc/desktop-diagnostics/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-17T09:08:31.595123300Z][com.docker.diagnose.exe][I] ipc.NewClient: 2f97506e-diagnose -> \\.\pipe\dockerDesktopLinuxEngine Proxy
[2023-03-17T09:08:31.596158900Z][com.docker.diagnose.exe][I] (d1341ce7) 2f97506e-diagnose C->S Proxy GET /desktop-diagnostics/ping
[2023-03-17T09:08:31.597778300Z][com.docker.diagnose.exe][W] (d1341ce7) 2f97506e-diagnose C<-S NoResponse GET /desktop-diagnostics/ping (1.6194ms): Get "http://ipc/desktop-diagnostics/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-17T09:08:31.600294800Z][com.docker.diagnose.exe][I] (d1341ce7-1) 2f97506e-diagnose C->S Proxy GET /ping
[2023-03-17T09:08:31.601407900Z][com.docker.diagnose.exe][W] (d1341ce7-1) 2f97506e-diagnose C<-S NoResponse GET /ping (1.1131ms): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-17T09:08:32.610773500Z][com.docker.diagnose.exe][I] (d1341ce7-2) 2f97506e-diagnose C->S Proxy GET /ping
[2023-03-17T09:08:32.613492400Z][com.docker.diagnose.exe][W] (d1341ce7-2) 2f97506e-diagnose C<-S NoResponse GET /ping (2.7189ms): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-17T09:08:33.615974300Z][com.docker.diagnose.exe][I] (d1341ce7-3) 2f97506e-diagnose C->S Proxy GET /ping
[2023-03-17T09:08:33.618098700Z][com.docker.diagnose.exe][W] (d1341ce7-3) 2f97506e-diagnose C<-S NoResponse GET /ping (2.1244ms): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-17T09:08:34.634159400Z][com.docker.diagnose.exe][I] (d1341ce7-4) 2f97506e-diagnose C->S Proxy GET /ping
[2023-03-17T09:08:34.635879900Z][com.docker.diagnose.exe][W] (d1341ce7-4) 2f97506e-diagnose C<-S NoResponse GET /ping (1.7205ms): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-17T09:08:35.651795700Z][com.docker.diagnose.exe][I] (d1341ce7-5) 2f97506e-diagnose C->S Proxy GET /ping
[2023-03-17T09:08:35.653127200Z][com.docker.diagnose.exe][W] (d1341ce7-5) 2f97506e-diagnose C<-S NoResponse GET /ping (1.3315ms): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-17T09:08:36.663374200Z][com.docker.diagnose.exe][I] (d1341ce7-6) 2f97506e-diagnose C->S Proxy GET /ping
[2023-03-17T09:08:36.664727000Z][com.docker.diagnose.exe][W] (d1341ce7-6) 2f97506e-diagnose C<-S NoResponse GET /ping (1.3528ms): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-17T09:08:37.667983900Z][com.docker.diagnose.exe][I] (d1341ce7-7) 2f97506e-diagnose C->S Proxy GET /ping
[2023-03-17T09:08:37.669831900Z][com.docker.diagnose.exe][W] (d1341ce7-7) 2f97506e-diagnose C<-S NoResponse GET /ping (1.848ms): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-17T09:08:38.677452700Z][com.docker.diagnose.exe][I] (d1341ce7-8) 2f97506e-diagnose C->S Proxy GET /ping
[2023-03-17T09:08:38.679310700Z][com.docker.diagnose.exe][W] (d1341ce7-8) 2f97506e-diagnose C<-S NoResponse GET /ping (1.858ms): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.

[PASS] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0022: is the Virtual Machine Platform Windows Feature enabled?
[PASS] DD0021: is the WSL 2 Windows Feature enabled?
[PASS] DD0024: is WSL installed?
[PASS] DD0025: are WSL distros installed?
[PASS] DD0026: is the WSL LxssManager service running?
[PASS] DD0029: is the WSL 2 Linux filesystem corrupt?
[PASS] DD0035: is the VM time synchronized?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[WARN] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[WARN] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[PASS] DD0015: are the binary symlinks installed?
[WARN] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[WARN] DD0032: do Docker networks overlap with host IPs? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/networks": open //./pipe/docker_engine_linux: The system cannot find the file specified.

Please note the following 4 warnings:

1 : The check: are the LinuxKit services running?
    Produced the following warning: failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

The Docker engine runs inside a Linux VM as a service. Therefore the services must have started.

2 : The check: is the Docker engine running?
    Produced the following warning: Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

The Docker engine manages all containers and images on the host. Check the dockerd.log to see why it failed to start.

3 : The check: does the Docker API work?
    Produced the following warning: error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.

If the Docker API is not available from the host then Docker Desktop will not work correctly.

4 : The check: do Docker networks overlap with host IPs?
    Produced the following warning: error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/networks": open //./pipe/docker_engine_linux: The system cannot find the file specified.

If the subnet used by a Docker network overlaps with an IP used by the host, then containers
won't be able to contact the overlapping IP addresses.

Try configuring the IP address range used by networks: in your docker-compose.yml.
See https://docs.docker.com/compose/compose-file/compose-file-v2/#ipv4_address-ipv6_address


Please investigate the following 2 issues:

1 : The test: are the LinuxKit services running?
    Failed with: failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

The Docker engine runs inside a Linux VM as a service. Therefore the services must have started.

2 : The test: are the backend processes running?
    Failed with: 2 errors occurred:
        * com.docker.vpnkit.exe is not running
        * com.docker.proxy.exe is not running



Not all of the backend processes are running.
```

### Steps to reproduce the behavior

  1. Try to start Docker Desktop,
  2. Wait some time,
  3. Observe the error.

**Comment by LeviPesin** [comment]
Seems like outputs are similar to https://github.com/docker/for-win/issues/13025#issuecomment-1291240002 and https://github.com/docker/for-win/issues/13025#issuecomment-1295469001...

**Comment by LeviPesin** [comment]
Here is my settings.json file:
```json
{
  "swarmFederationExplicitlyLoggedOut": false,
  "wslEnableGrpcfuse": false,
  "integratedWslDistros": [
    "Ubuntu-18.04"
  ],
  "enableIntegrationWithDefaultWslDistro": true,
  "skipUpdateToWSLPrompt": true,
  "skipWSLMountPerfWarning": false,
  "displaySwitchWinLinContainers": false,
  "displayed18362Deprecation": false,
  "settingsVersion": 25,
  "autoStart": false,
  "activeOrganizationName": "",
  "useCredentialHelper": true,
  "credentialHelper": "docker-credential-wincred.exe",
  "disableTips": false,
  "tipLastViewedTime": 1677662800980,
  "tipLastId": 40,
  "updateAvailableTime": 0,
  "updateInstallTime": 0,
  "disableUpdate": true,
  "openUIOnStartupDisabled": false,
  "analyticsEnabled": false,
  "displayedTutorial": true,
  "displayedWelcomeSurvey": true,
  "disableHardwareAcceleration": false,
  "displayRestartDialog": true,
  "displayedElectronPopup": [],
  "latestBannerKey": "",
  "acceptCanaryUpdates": false,
  "useNightlyBuildUpdates": false,
  "autoDownloadUpdates": true,
  "lastLoginDate": 0,
  "themeSource": "system",
  "containerTerminal": "system",
  "allowExperimentalFeatures": true,
  "enableSegmentDebug": false,
  "dataFolder": "C:\\ProgramData\\DockerDesktop\\vm-data",
  "memoryMiB": 2048,
  "swapMiB": 1024,
  "cpus": 2,
  "diskSizeMiB": 65536,
  "diskTRIM": true,
  "vpnkitCIDR": "192.168.65.0/24",
  "socksProxyPort": 0,
  "proxyHttpMode": "system",
  "overrideProxyHttp": "",
  "overrideProxyHttps": "",
  "overrideProxyExclude": "",
  "filesharingDirectories": [],
  "kubernetesEnabled": true,
  "showKubernetesSystemContainers": false,
  "kubernetesInitialInstallPerformed": true,
  "useVirtualizationFramework": false,
  "useVirtualizationFrameworkVirtioFS": false,
  "useVirtualizationFrameworkRosetta": false,
  "useGrpcfuse": true,
  "useVpnkit": true,
  "vpnKitMaxPortIdleTime": 300,
  "vpnKitTransparentProxy": true,
  "useWindowsContainers": false,
  "noWindowsContainers": false,
  "requireVmnetd": false,
  "wslEngineEnabled": true,
  "customWslDistroDir": "",
  "licenseTermsVersion": 2,
  "deprecatedCgroupv1": false,
  "useContainerdSnapshotter": true,
  "lifecycleTimeoutSeconds": 600,
  "exposeDockerAPIOnTCP2375": false,
  "enhancedContainerIsolation": false,
  "extensionsEnabled": true,
  "onlyMarketplaceExtensions": false,
  "showExtensionsSystemContainers": false,
  "useBackgroundIndexing": true
}
```
