### ISSUE TITLE
'DockerDesktopVM' failed to start.

### ISSUE THREAD

**Issue by mavviiss** [docker/for-win#13341]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D2CBA4DE-FA7E-4B43-BC92-20592510721C/20230328121213

### Actual behavior
At the start time
### Information

  - Windows Version: 10 Pro
  - Docker Desktop Version: 4.17.1
  - WSL2 or Hyper-V backend?  Hyper-V
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No, I didn't

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

[2023-03-28T12:22:09.447472800Z][com.docker.diagnose.exe][W] Windows version might not be up-to-date: The system cannot find the file specified.
[2023-03-28T12:22:09.454716000Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[SKIP] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0020: is the Hyper-V Windows Feature enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[2023-03-28T12:22:10.022587900Z][com.docker.diagnose.exe][I] ipc.NewClient: 1f83eee2-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[2023-03-28T12:22:10.023136100Z][com.docker.diagnose.exe][I] (40d77b4b) 1f83eee2-diagnose C->S diagnosticsd GET /ping
[2023-03-28T12:22:10.023136100Z][com.docker.diagnose.exe][W] (40d77b4b) 1f83eee2-diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-28T12:22:10.024191000Z][com.docker.diagnose.exe][I] ipc.NewClient: 3a5fdc42-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[2023-03-28T12:22:10.024704700Z][com.docker.diagnose.exe][I] (0eccc0a0) 3a5fdc42-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2023-03-28T12:22:10.024704700Z][com.docker.diagnose.exe][W] (0eccc0a0) 3a5fdc42-com.docker.diagnose C<-S NoResponse GET /docker (0s): Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-28T12:22:10.024704700Z][com.docker.diagnose.exe][I] (0eccc0a0-1) 3a5fdc42-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-28T12:22:10.025215900Z][com.docker.diagnose.exe][W] (0eccc0a0-1) 3a5fdc42-com.docker.diagnose C<-S NoResponse GET /ping (511.2µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-28T12:22:11.026320700Z][com.docker.diagnose.exe][I] (0eccc0a0-2) 3a5fdc42-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-28T12:22:11.028174400Z][com.docker.diagnose.exe][W] (0eccc0a0-2) 3a5fdc42-com.docker.diagnose C<-S NoResponse GET /ping (1.8537ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-28T12:22:12.029236100Z][com.docker.diagnose.exe][I] (0eccc0a0-3) 3a5fdc42-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-28T12:22:12.029236100Z][com.docker.diagnose.exe][W] (0eccc0a0-3) 3a5fdc42-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-28T12:22:13.030737400Z][com.docker.diagnose.exe][I] (0eccc0a0-4) 3a5fdc42-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-28T12:22:13.032875900Z][com.docker.diagnose.exe][W] (0eccc0a0-4) 3a5fdc42-com.docker.diagnose C<-S NoResponse GET /ping (1.9588ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-28T12:22:14.035234200Z][com.docker.diagnose.exe][I] (0eccc0a0-5) 3a5fdc42-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-28T12:22:14.036297900Z][com.docker.diagnose.exe][W] (0eccc0a0-5) 3a5fdc42-com.docker.diagnose C<-S NoResponse GET /ping (1.0637ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-28T12:22:15.037336800Z][com.docker.diagnose.exe][I] (0eccc0a0-6) 3a5fdc42-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-28T12:22:15.037336800Z][com.docker.diagnose.exe][W] (0eccc0a0-6) 3a5fdc42-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-28T12:22:16.037559100Z][com.docker.diagnose.exe][I] (0eccc0a0-7) 3a5fdc42-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-28T12:22:16.037559100Z][com.docker.diagnose.exe][W] (0eccc0a0-7) 3a5fdc42-com.docker.diagnose C<-S NoResponse GET /ping (130µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-03-28T12:22:17.038188600Z][com.docker.diagnose.exe][I] (0eccc0a0-8) 3a5fdc42-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-03-28T12:22:17.038430700Z][com.docker.diagnose.exe][W] (0eccc0a0-8) 3a5fdc42-com.docker.diagnose C<-S NoResponse GET /ping (242.1µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[PASS] DD0013: is the $PATH ok?
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
[FAIL] DD0014: are the backend processes running? 2 errors occurred:
        * com.docker.vpnkit.exe is not running
        * com.docker.proxy.exe is not running

[PASS] DD0007: is the backend responding?
[PASS] DD0008: is the native API responding?
[FAIL] DD0009: is the vpnkit API responding? open \\.\pipe\dockerVpnKitDiagnostics: The system cannot find the file specified.
[FAIL] DD0010: is the Docker API proxy responding? failed to ping Docker proxy API with error: Get "http://ipc/desktop-diagnostics/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-28T12:22:37.707796000Z][com.docker.diagnose.exe][I] ipc.NewClient: 77a68b7f-diagnose -> \\.\pipe\dockerDesktopLinuxEngine Proxy
[2023-03-28T12:22:37.707796000Z][com.docker.diagnose.exe][I] (3dcfa5de) 77a68b7f-diagnose C->S Proxy GET /desktop-diagnostics/ping
[2023-03-28T12:22:37.708358600Z][com.docker.diagnose.exe][W] (3dcfa5de) 77a68b7f-diagnose C<-S NoResponse GET /desktop-diagnostics/ping (562.6µs): Get "http://ipc/desktop-diagnostics/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-28T12:22:37.708358600Z][com.docker.diagnose.exe][I] (3dcfa5de-1) 77a68b7f-diagnose C->S Proxy GET /ping
[2023-03-28T12:22:37.709417300Z][com.docker.diagnose.exe][W] (3dcfa5de-1) 77a68b7f-diagnose C<-S NoResponse GET /ping (1.0587ms): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-28T12:22:38.709949900Z][com.docker.diagnose.exe][I] (3dcfa5de-2) 77a68b7f-diagnose C->S Proxy GET /ping
[2023-03-28T12:22:38.709949900Z][com.docker.diagnose.exe][W] (3dcfa5de-2) 77a68b7f-diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-28T12:22:39.710998000Z][com.docker.diagnose.exe][I] (3dcfa5de-3) 77a68b7f-diagnose C->S Proxy GET /ping
[2023-03-28T12:22:39.712831300Z][com.docker.diagnose.exe][W] (3dcfa5de-3) 77a68b7f-diagnose C<-S NoResponse GET /ping (1.6866ms): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-28T12:22:40.715125300Z][com.docker.diagnose.exe][I] (3dcfa5de-4) 77a68b7f-diagnose C->S Proxy GET /ping
[2023-03-28T12:22:40.715355400Z][com.docker.diagnose.exe][W] (3dcfa5de-4) 77a68b7f-diagnose C<-S NoResponse GET /ping (230.1µs): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-28T12:22:41.716314200Z][com.docker.diagnose.exe][I] (3dcfa5de-5) 77a68b7f-diagnose C->S Proxy GET /ping
[2023-03-28T12:22:41.716314200Z][com.docker.diagnose.exe][W] (3dcfa5de-5) 77a68b7f-diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-28T12:22:42.717083500Z][com.docker.diagnose.exe][I] (3dcfa5de-6) 77a68b7f-diagnose C->S Proxy GET /ping
[2023-03-28T12:22:42.718664700Z][com.docker.diagnose.exe][W] (3dcfa5de-6) 77a68b7f-diagnose C<-S NoResponse GET /ping (1.5812ms): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-28T12:22:43.719181800Z][com.docker.diagnose.exe][I] (3dcfa5de-7) 77a68b7f-diagnose C->S Proxy GET /ping
[2023-03-28T12:22:43.721201900Z][com.docker.diagnose.exe][W] (3dcfa5de-7) 77a68b7f-diagnose C<-S NoResponse GET /ping (2.0201ms): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.
[2023-03-28T12:22:44.722165300Z][com.docker.diagnose.exe][I] (3dcfa5de-8) 77a68b7f-diagnose C->S Proxy GET /ping
[2023-03-28T12:22:44.722349400Z][com.docker.diagnose.exe][W] (3dcfa5de-8) 77a68b7f-diagnose C<-S NoResponse GET /ping (184.1µs): Get "http://ipc/ping": open \\.\pipe\dockerDesktopLinuxEngine: The system cannot find the file specified.

[PASS] DD0006: is the Docker Desktop Service responding?
[SKIP] DD0030: is the image access management authorized?
[PASS] DD0033: does the host have Internet access?
[PASS] DD0002: does the bootloader have virtualization enabled?
[PASS] DD0020: is the Hyper-V Windows Feature enabled?
[PASS] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[WARN] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[WARN] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[PASS] DD0015: are the binary symlinks installed?
[WARN] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[WARN] DD0032: do Docker networks overlap with host IPs? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/networks": open //./pipe/docker_engine_linux: The system cannot find the file specified.

Please note the following 4 warnings:

1 : The check: are the LinuxKit services running?
    Produced the following warning: failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

The Docker engine runs inside a Linux VM as a service. Therefore the services must have started.

2 : The check: is the Docker engine running?
    Produced the following warning: Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

The Docker engine manages all containers and images on the host. Check the dockerd.log to see why it failed to start.

3 : The check: does the Docker API work?
    Produced the following warning: error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.

If the Docker API is not available from the host then Docker Desktop will not work correctly.

4 : The check: do Docker networks overlap with host IPs?
    Produced the following warning: error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/networks": open //./pipe/docker_engine_linux: The system cannot find the file specified.

If the subnet used by a Docker network overlaps with an IP used by the host, then containers
won't be able to contact the overlapping IP addresses.

Try configuring the IP address range used by networks: in your docker-compose.yml.
See https://docs.docker.com/compose/compose-file/compose-file-v2/#ipv4_address-ipv6_address

Please investigate the following 2 issues:

1 : The test: are the LinuxKit services running?
    Failed with: failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

The Docker engine runs inside a Linux VM as a service. Therefore the services must have started.

2 : The test: are the backend processes running?
    Failed with: 2 errors occurred:
        * com.docker.vpnkit.exe is not running
        * com.docker.proxy.exe is not running

Not all of the backend processes are running.

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by corwestermaniddink** [comment]
If you uninstall now Docker, then the installer stops with a error?

**Comment by mavviiss** [comment]
> If you uninstall now Docker, then the installer stops with a error?

yes

**Comment by mavviiss** [comment]
ValidatorError: Query.prototype.countDocuments() no longer accepts a callback
        at validate (/home/mavis/projects/infrastructureServerNode/node_modules/mongoose/lib/schematype.js:1347:13)
        at /home/mavis/projects/infrastructureServerNode/node_modules/mongoose/lib/schematype.js:1328:11
        at processTicksAndRejections (node:internal/process/task_queues:95:5) {
      properties: [Object],
      kind: 'unique',
      path: 'serviceName',
      value: 'VPS[AAA]-1680608641830',
      reason: MongooseError: Query.prototype.countDocuments() no longer accepts a callback
          at model.Query.Query.countDocuments (/home/mavis/projects/infrastructureServerNode/node_modules/mongoose/lib/query.js:2752:11)
          at /home/mavis/projects/infrastructureServerNode/node_modules/mongoose-unique-validator/index.js:123:52
          at new Promise (<anonymous>)
          at model.<anonymous> (/home/mavis/projects/infrastructureServerNode/node_modules/mongoose-unique-validator/index.js:54:32)
          at SchemaString.SchemaType.doValidate (/home/mavis/projects/infrastructureServerNode/node_modules/mongoose/lib/schematype.js:1311:24)
          at /home/mavis/projects/infrastructureServerNode/node_modules/mongoose/lib/document.js:2872:18
          at processTicksAndRejections (node:internal/process/task_queues:77:11),
      [Symbol(mongoose:validatorError)]: true
    }
