### ISSUE TITLE
docker desktop error

### ISSUE THREAD

**Issue by amitylandmarks** [docker/for-win#13366]
- [ ] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - WSL2 or Hyper-V backend?  
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by amitylandmarks** [comment]
System.InvalidOperationException:
Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.WPF.BackendClient.Version()
   at Docker.WPF.BackendClient.CheckVersion()
   at Docker.WPF.BackendClient.CheckService(String action)
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters)
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

**Comment by BrandonWanHuanSheng** [comment]
Oops! Docker Engine Hang on start.

**Comment by landism** [comment]
Thanks for filing. Would it be possible to submit a [diagnostic report](https://docs.docker.com/desktop/troubleshoot/overview/#diagnose)?
