### ISSUE TITLE
VSTS build-agent, Installed docker-for-windows on host, docker-compose fails with pywintypes.error: (5, 'CreateFile', 'Access is denied.')

### ISSUE THREAD

**Issue by DutchITWorks** [docker/for-win#1337]
### Expected behavior
docker-compose build command working

### Actual behavior
docker-compose exits with error message pywintypes.error: (5, 'CreateFile', 'Access is denied.')

### Information
For a CI/CD pipeline I'm currently trying to get a **local** VSTS build-agent to run a docker command.
I have installed the VSTS build-agent and I see this agent available in the VSTS website. I have also installed docker for windows version 17.09.0-ce-win33 (13620) on the build-agent's host machine.
The sources get downloaded to the agent's _work folder, but when the docker-compose command is called, the following error is thrown:

2017-11-18T14:50:40.2980501Z ##[section]Starting: Build services
2017-11-18T14:50:40.3250479Z ==============================================================================
2017-11-18T14:50:40.3250479Z Task         : Docker Compose
2017-11-18T14:50:40.3250479Z Description  : Build, push or run multi-container Docker applications. Task can be used with Docker or Azure Container registry.
2017-11-18T14:50:40.3250479Z Version      : 0.4.7
2017-11-18T14:50:40.3250479Z Author       : Microsoft Corporation
2017-11-18T14:50:40.3250479Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=848006)
2017-11-18T14:50:40.3250479Z ==============================================================================
2017-11-18T14:50:44.5425702Z [command]"C:\Program Files\Docker\Docker\Resources\bin\docker-compose.exe" -f C:\Agent\_work\1\s\docker-compose.yml -f C:\Agent\.docker-compose.1511016644488.yml -p DockerHosting build
2017-11-18T14:50:45.2281567Z proxy uses an image, skipping
2017-11-18T14:50:45.2281567Z Building website
2017-11-18T14:50:45.8069536Z Traceback (most recent call last):
2017-11-18T14:50:45.8069536Z   File "docker-compose", line 6, in <module>
2017-11-18T14:50:45.8069536Z   File "compose\cli\main.py", line 68, in main
2017-11-18T14:50:45.8069536Z   File "compose\cli\main.py", line 121, in perform_command
2017-11-18T14:50:45.8069536Z   File "compose\cli\main.py", line 249, in build
2017-11-18T14:50:45.8069536Z   File "compose\project.py", line 343, in build
2017-11-18T14:50:45.8069536Z   File "compose\service.py", line 918, in build
2017-11-18T14:50:45.8079582Z   File "site-packages\docker\api\build.py", line 246, in build
2017-11-18T14:50:45.8079582Z   File "site-packages\docker\utils\decorators.py", line 46, in inner
2017-11-18T14:50:45.8079582Z   File "site-packages\docker\api\client.py", line 185, in _post
2017-11-18T14:50:45.8079582Z   File "site-packages\requests\sessions.py", line 522, in post
2017-11-18T14:50:45.8079582Z   File "site-packages\requests\sessions.py", line 475, in request
2017-11-18T14:50:45.8079582Z   File "site-packages\requests\sessions.py", line 596, in send
2017-11-18T14:50:45.8079582Z   File "site-packages\requests\adapters.py", line 423, in send
2017-11-18T14:50:45.8079582Z   File "site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
2017-11-18T14:50:45.8079582Z   File "site-packages\requests\packages\urllib3\connectionpool.py", line 363, in _make_request
2017-11-18T14:50:45.8079582Z   File "httplib.py", line 1042, in request
2017-11-18T14:50:45.8089562Z   File "httplib.py", line 1082, in _send_request
2017-11-18T14:50:45.8089562Z   File "httplib.py", line 1038, in endheaders
2017-11-18T14:50:45.8089562Z   File "httplib.py", line 882, in _send_output
2017-11-18T14:50:45.8089562Z   File "httplib.py", line 844, in send
2017-11-18T14:50:45.8089562Z   File "site-packages\docker\transport\npipeconn.py", line 31, in connect
2017-11-18T14:50:45.8089562Z   File "site-packages\docker\transport\npipesocket.py", line 22, in wrapped
2017-11-18T14:50:45.8089562Z   File "site-packages\docker\transport\npipesocket.py", line 70, in connect
2017-11-18T14:50:45.8089562Z pywintypes.error: (5, 'CreateFile', 'Access is denied.')
2017-11-18T14:50:45.8259547Z Failed to execute script docker-compose

When I try running the same command with powershell on the build-machine, then it works. It's got something to do with user-accounts.

I tried disabling UAC to no avail.

**Comment by DutchITWorks** [comment]
Figured it out... there are 2 services running: 
- The VSTS agent running under account 'Local service'.
- The Docker agent running under account 'Local system'

When I made the VSTS agent also use the 'Local system' account, the issue was solved. 
So keep in mind that these services must run the SAME account!!
