### ISSUE TITLE
Can't switch to Windows Containers on 4.18

### ISSUE THREAD

**Issue by Phelsong** [docker/for-win#13389]
- [x ] I have tried with the latest version of Docker Desktop
  - [ x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Actual behavior
Error and engine crash
### Expected behavior
being able to run a container
### Information

  - Windows Version: Win11 23430.1000
  - Docker Desktop Version: 4.18
  - WSL2 or Hyper-V backend?  WSL2 
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: no

Happens with WSL2 or hyperV backend, anytime I switch to windows containers. Wasn't happening on 4.17 or on 3.6 currently.
Errorlog:
[Docker.Core.HttpBadResponseExceptio.txt](https://github.com/docker/for-win/files/11214830/Docker.Core.HttpBadResponseExceptio.txt)

**Comment by Phelsong** [comment]
[2023-04-12T19:11:55.742253500Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[PASS] DD0002: does the bootloader have virtualization enabled?
[SKIP] DD0018: does the host support virtualization?
[PASS] DD0001: is the application running?
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[2023-04-12T19:11:57.043909200Z][com.docker.diagnose.exe][I] ipc.NewClient: b735135f-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[2023-04-12T19:11:57.043909200Z][com.docker.diagnose.exe][I] (79d5b062) b735135f-diagnose C->S diagnosticsd GET /ping
[2023-04-12T19:11:57.044428000Z][com.docker.diagnose.exe][W] (79d5b062) b735135f-diagnose C<-S NoResponse GET /ping (518.8µs): Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

[PASS] DD0023: is the Containers Windows Feature enabled?
[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-12T19:11:57.199933700Z][com.docker.diagnose.exe][I] ipc.NewClient: ead8764e-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[2023-04-12T19:11:57.199933700Z][com.docker.diagnose.exe][I] (cfb9bdc9) ead8764e-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2023-04-12T19:11:57.199933700Z][com.docker.diagnose.exe][W] (cfb9bdc9) ead8764e-com.docker.diagnose C<-S NoResponse GET /docker (0s): Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-12T19:11:57.199933700Z][com.docker.diagnose.exe][I] (cfb9bdc9-1) ead8764e-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-12T19:11:57.200444900Z][com.docker.diagnose.exe][W] (cfb9bdc9-1) ead8764e-com.docker.diagnose C<-S NoResponse GET /ping (511.2µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-12T19:11:58.205869400Z][com.docker.diagnose.exe][I] (cfb9bdc9-2) ead8764e-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-12T19:11:58.205869400Z][com.docker.diagnose.exe][W] (cfb9bdc9-2) ead8764e-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-12T19:11:59.220160500Z][com.docker.diagnose.exe][I] (cfb9bdc9-3) ead8764e-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-12T19:11:59.220422300Z][com.docker.diagnose.exe][W] (cfb9bdc9-3) ead8764e-com.docker.diagnose C<-S NoResponse GET /ping (261.8µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-12T19:12:00.235150700Z][com.docker.diagnose.exe][I] (cfb9bdc9-4) ead8764e-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-12T19:12:00.235699400Z][com.docker.diagnose.exe][W] (cfb9bdc9-4) ead8764e-com.docker.diagnose C<-S NoResponse GET /ping (548.7µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-12T19:12:01.248125900Z][com.docker.diagnose.exe][I] (cfb9bdc9-5) ead8764e-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-12T19:12:01.248444900Z][com.docker.diagnose.exe][W] (cfb9bdc9-5) ead8764e-com.docker.diagnose C<-S NoResponse GET /ping (319µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-12T19:12:02.263019500Z][com.docker.diagnose.exe][I] (cfb9bdc9-6) ead8764e-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-12T19:12:02.263019500Z][com.docker.diagnose.exe][W] (cfb9bdc9-6) ead8764e-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-12T19:12:03.275893100Z][com.docker.diagnose.exe][I] (cfb9bdc9-7) ead8764e-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-12T19:12:03.275893100Z][com.docker.diagnose.exe][W] (cfb9bdc9-7) ead8764e-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-12T19:12:04.278570700Z][com.docker.diagnose.exe][I] (cfb9bdc9-8) ead8764e-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-12T19:12:04.278827800Z][com.docker.diagnose.exe][W] (cfb9bdc9-8) ead8764e-com.docker.diagnose C<-S NoResponse GET /ping (257.1µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[PASS] DD0013: is the $PATH ok?
error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0005: is the user in the docker-users group?
[PASS] DD0038: is the connection to Docker working?
2023/04/12 14:12:05 error checking if default wsl distro is running: exit status 0xffffffff
NativeCommandExitException: Program "com.docker.diagnose.exe" ended with non-zero exit code: 1.

**Comment by hav4ik** [comment]
I have the same issue.

- OS: Windows 10 Enterprise (build 19044.2846)
- Docker Desktop: 4.18.0 (104112)
- Windows Containers

Full logs:
```
Docker.Core.HttpBadResponseException:
no response content
   at Docker.Core.GoBackend.GoBackendClient.<PostNoBodyWithError>d__21.MoveNext() in C:\workspaces\PR-21378\src\github.com\docker\pinata\win\src\Docker.Core\GoBackend\GoBackendClient.cs:line 228
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WindowsContainersEngine.<DoStartAsync>d__10.MoveNext() in C:\workspaces\PR-21378\src\github.com\docker\pinata\win\src\Docker.Engines\WindowsContainersEngine.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-21378\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__7.MoveNext() in C:\workspaces\PR-21378\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__7.MoveNext() in C:\workspaces\PR-21378\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__17.MoveNext() in C:\workspaces\PR-21378\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<SwitchDaemonAsync>d__29.MoveNext() in C:\workspaces\PR-21378\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 253
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Engines.Engines.<SwitchDaemonAsync>d__29.MoveNext() in C:\workspaces\PR-21378\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 272
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.Services.DesktopService.<SwitchDaemonAsync>d__3.MoveNext() in C:\workspaces\PR-21378\src\github.com\docker\pinata\win\src\Docker.ApiServices\Services\DesktopService.cs:line 36
   ```

**Comment by sam-thibault** [comment]
Likely duplicate of:
- https://github.com/docker/for-win/issues/13379

**Comment by Gekko0114** [comment]
I have a same issue

**Comment by antonfirsov** [comment]
> Likely duplicate of:

@sam-thibault are you sure? #13379 does not mention the crash log with `HttpBadResponseException` from https://github.com/docker/for-win/issues/13389#issuecomment-1506760425 which is what I'm experiencing. I can't get Windows containers running at all with 4.18.0.

This is also mentioned in https://forums.docker.com/t/docker-desktop-started-failing-to-start-for-windows-containers/135576, the only workaround seems to be to revert to 4.17.1.

**Comment by Phelsong** [comment]
> > Likely duplicate of:
> 
> @sam-thibault are you sure? #13379 does not mention the crash log with `HttpBadResponseException` from the OP and https://github.com/docker/for-win/issues/13389#issuecomment-1506760425. I can't get Windows containers running at all with 4.18.0. I'm getting `error during connect: This error may indicate that the docker daemon is not running` when I try to use them, so it doesn't look like a UI-only issue as mentioned in https://github.com/docker/for-win/issues/13379#issuecomment-1505303943.
> 
> This is being also discussed in https://forums.docker.com/t/docker-desktop-started-failing-to-start-for-windows-containers/135576, the only workaround seems to be to revert to 4.17.1.

The preview update for WSL fixed Docker for me. So I'm not even sure this is (directly) a Docker issue.

**Comment by crhistianramirez** [comment]
@Phelsong which version of WSL are you using that works?

**Comment by Phelsong** [comment]
> @Phelsong which version of WSL are you using that works?

WSL version: 1.3.15.0
Kernel version: 5.15.90.4-1
WSLg version: 1.0.55
MSRDC version: 1.2.4419
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.23521.1000

**Comment by Phelsong** [comment]
Stale
