### ISSUE TITLE
Unable to install Docker Desktop 4.18.0 (104112)

### ISSUE THREAD

**Issue by frkr** [docker/for-win#13387]
Windows 10 22H2 (19045.2846)

```
Cadeia de caracteres JSON inválida. (Exceção de HRESULT: 0x83750007)
   em Windows.Data.Json.JsonValue.Parse(String input)
   em CommunityInstaller.InstallWorkflow.SetupBackendModeAndFeatures(List`1 backendModeFeaturesSteps)
   em CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

Does not work trying this:
- netsh winsock reset 
- wsl --set-default-version 2

**Comment by gabu-lartiga** [comment]
I'm having the same issue. I got stuck at the same point everytime.

```
Version: 4.18.0 (104112)
Sha1:
Started on: 2023-04-18 23:01:01.651
OS: Windows 10 Home Single Language
Edition: CoreSingleLanguage
Id: 2009
Build: 19044
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\ProgramData\DockerDesktop\install-log-admin.txt
CommandLine: "Docker Desktop Installer.exe"  install
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2023-04-18T23:01:01.803652300Z][ManifestAndExistingInstallationLoader][I] No install path specified, looking for default installation registry key
[2023-04-18T23:01:01.813625600Z][Installer][I] No installation found
[2023-04-18T23:01:02.002998700Z][InstallWorkflow][I] Cancel pending background download
[2023-04-18T23:01:02.004993400Z][BackgroundTransfer][I] Cancel current background transfer job
[2023-04-18T23:01:06.189014200Z][InstallWorkflow][I] Using package: res:DockerDesktop
[2023-04-18T23:01:06.190043800Z][InstallWorkflow][I] Downloading
[2023-04-18T23:01:08.474376400Z][InstallWorkflow][I] Extracting manifest
```

**Comment by jleipus** [comment]
I recently got a similar issue. 
OS: Windows 10 Pro
Build: 19044

When running through powershell, during "Extracting manifest" step got 
`Process is terminated due to StackOverlowException`

Tried installers for 4.14 - 4.18, all had the same issue.

**Comment by frkr** [comment]
i tryed some new commands.

Trying to install with wsl-2

```
-------------------------------------------------------------------------------->8
Version: 4.18.0 (104112)
Sha1: 
Started on: 2023/04/22 02:10:21.738
Resources: C:\Users\admin\Downloads\resources
OS: Windows 10 Education
Edition: Education
Id: 2009
Build: 19045
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\ProgramData\DockerDesktop\install-log-admin.txt
CommandLine: "Docker Desktop Installer.exe"  install --no-windows-containers --backend=wsl-2 --admin-settings
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2023-04-22T02:10:22.065782400Z][ManifestAndExistingInstallationLoader][I] No install path specified, looking for default installation registry key
[2023-04-22T02:10:22.082724700Z][Installer][I] No installation found
[2023-04-22T02:10:22.238722000Z][InstallWorkflow][I] Cancel pending background download
[2023-04-22T02:10:22.241724400Z][BackgroundTransfer][I] Cancel current background transfer job
[2023-04-22T02:10:26.529755700Z][InstallWorkflow][I] Using package: res:DockerDesktop
[2023-04-22T02:10:26.531724300Z][InstallWorkflow][I] Downloading
[2023-04-22T02:10:30.711764800Z][InstallWorkflow][I] Extracting manifest
[2023-04-22T02:10:32.013722300Z][InstallWorkflow][I] Manifest found: version=104112, displayVersion=4.18.0, channelUrl=https://desktop.docker.com/win/main/amd64/appcast.xml
[2023-04-22T02:10:32.013722300Z][InstallWorkflow][I] Checking prerequisites
[2023-04-22T02:10:32.588724100Z][InstallWorkflow][I] settings from previous installation exist: match the backendmode to that
[2023-04-22T02:10:32.593726700Z][InstallWorkflow][E] Installation failed System.Exception: Cadeia de caracteres JSON inv�lida. (Exce��o de HRESULT: 0x83750007)
   em Windows.Data.Json.JsonValue.Parse(String input)
   em CommunityInstaller.InstallWorkflow.SetupBackendModeAndFeatures(List`1 backendModeFeaturesSteps)
   em CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exce��o foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[2023-04-22T02:10:32.597721900Z][InstallWorkflow][I] Rollbacking component CommunityInstaller.ExtractManifestStep
[2023-04-22T02:10:32.598723500Z][InstallWorkflow][I] Rollbacking component CommunityInstaller.DownloadStep
[2023-04-22T02:10:32.798762300Z][Installer][W] Failed to track the installer started event

```

Installing with windows:

```
-------------------------------------------------------------------------------->8
Version: 4.18.0 (104112)
Sha1: 
Started on: 2023/04/22 02:14:51.147
Resources: C:\Users\admin\Downloads\resources
OS: Windows 10 Education
Edition: Education
Id: 2009
Build: 19045
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\ProgramData\DockerDesktop\install-log-admin.txt
CommandLine: "Docker Desktop Installer.exe"  install --no-windows-containers --backend=windows --admin-settings
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2023-04-22T02:14:51.439722600Z][ManifestAndExistingInstallationLoader][I] No install path specified, looking for default installation registry key
[2023-04-22T02:14:51.456723500Z][Installer][I] No installation found
[2023-04-22T02:14:51.606722400Z][InstallWorkflow][I] Cancel pending background download
[2023-04-22T02:14:51.609725400Z][BackgroundTransfer][I] Cancel current background transfer job
[2023-04-22T02:14:51.626723800Z][InstallWorkflow][I] Using package: res:DockerDesktop
[2023-04-22T02:14:51.627724100Z][InstallWorkflow][I] Downloading
[2023-04-22T02:14:54.310753200Z][InstallWorkflow][I] Extracting manifest
[2023-04-22T02:14:55.216763900Z][InstallWorkflow][I] Manifest found: version=104112, displayVersion=4.18.0, channelUrl=https://desktop.docker.com/win/main/amd64/appcast.xml
[2023-04-22T02:14:55.217724300Z][InstallWorkflow][I] Checking prerequisites
[2023-04-22T02:14:55.703767300Z][InstallWorkflow][I] Selected backend mode: windows
[2023-04-22T02:14:55.704724500Z][InstallWorkflow][I] Unpacking artifacts
[2023-04-22T02:14:55.780738200Z][Installer][W] Failed to track the installer started event
[2023-04-22T02:17:57.916723700Z][InstallWorkflow][I] Deploying component CommunityInstaller.CreateGroupAction
[2023-04-22T02:18:07.283723500Z][InstallWorkflow][I] Deploying component CommunityInstaller.AddToGroupAction
[2023-04-22T02:18:16.334724300Z][InstallWorkflow][I] Deploying component CommunityInstaller.EnableFeaturesAction
[2023-04-22T02:18:16.361724600Z][InstallWorkflow-EnableFeaturesAction][I] Required features: *Hyper-V*, Containers
[2023-04-22T02:18:17.255740300Z][InstallWorkflow][I] Deploying component CommunityInstaller.ServiceAction
[2023-04-22T02:18:17.259723800Z][InstallWorkflow-ServiceAction][I] Removing service
[2023-04-22T02:18:17.261722200Z][InstallWorkflow-ServiceAction][I] Creating service
[2023-04-22T02:18:19.297766000Z][InstallWorkflow][I] Deploying component CommunityInstaller.ShortcutAction
[2023-04-22T02:18:19.324757500Z][InstallWorkflow-ShortcutAction][I] Creating shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Docker Desktop.lnk/Docker Desktop
[2023-04-22T02:18:19.415723900Z][InstallWorkflow][I] Deploying component CommunityInstaller.ShortcutAction
[2023-04-22T02:18:19.417724300Z][InstallWorkflow-ShortcutAction][I] Creating shortcut: C:\Users\admin\Desktop\Docker Desktop.lnk/Docker Desktop
[2023-04-22T02:18:19.419725200Z][InstallWorkflow][I] Deploying component CommunityInstaller.AutoStartAction
[2023-04-22T02:18:19.421725300Z][InstallWorkflow][I] Deploying component CommunityInstaller.PathAction
[2023-04-22T02:18:19.908723900Z][InstallWorkflow][I] Deploying component CommunityInstaller.ExecAction
[2023-04-22T02:18:19.915724000Z][InstallWorkflow-ExecAction][I] Running: C:\Program Files\Docker\Docker\InstallerCli.exe -i with timeout=-1
[2023-04-22T02:18:23.074728500Z][InstallWorkflow][I] Registering product
[2023-04-22T02:18:23.087728200Z][InstallWorkflow][I] Saving C:\ProgramData\DockerDesktop\install-settings.json
[2023-04-22T02:18:23.226725200Z][InstallWorkflow][I] Installation succeeded

```

After install, the following file could be modfied or not. But the result its the same.

install-settings.json

```
{
  "useWindowsContainers": true,
  "noWindowsContainers": true
}
```

Diagnose:
```
[2023-04-22T02:51:30.387464200Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Gathering diagnostics for ID 66E116E0-CC07-4C76-9D51-9496A0AA6037/20230422025130 into C:\Users\admin\AppData\Local\Temp\66E116E0-CC07-4C76-9D51-9496A0AA6037\20230422025130.zip.
This may take up to 15 minutes.
[2023-04-22T02:51:30.389072200Z][com.docker.diagnose.exe][I] ipc.NewClient: 997956f9-com.docker.diagnose -> \\.\pipe\dockerDnsForwarder dns-forwarder
[2023-04-22T02:51:30.389072200Z][com.docker.diagnose.exe][I] Triggering Linux sysrq and log flushes via a unix socket: \\.\pipe\dockerDiagnosticd
[2023-04-22T02:51:30.389883500Z][com.docker.diagnose.exe][I] (0653d435) 997956f9-com.docker.diagnose C->S dns-forwarder POST /diagnostics
[2023-04-22T02:51:30.389883500Z][com.docker.diagnose.exe][I] ipc.NewClient: ab82c48a-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service
[2023-04-22T02:51:30.391676900Z][com.docker.diagnose.exe][I] (8f337acd) ab82c48a-com.docker.diagnose C->S com.docker.service GET /hyperv/bootloader
[2023-04-22T02:51:30.392324000Z][com.docker.diagnose.exe][W] (0653d435) 997956f9-com.docker.diagnose C<-S NoResponse POST /diagnostics (1.6742ms): Post "http://ipc/diagnostics": open \\.\pipe\dockerDnsForwarder: O sistema não pode encontrar o arquivo especificado.
[2023-04-22T02:51:30.392852100Z][com.docker.diagnose.exe][I] (0653d435-1) 997956f9-com.docker.diagnose C->S dns-forwarder GET /ping
[2023-04-22T02:51:30.392324000Z][com.docker.diagnose.exe][W] /flush failed: Post "http://unix/flush": open \\.\pipe\dockerDiagnosticd: O sistema não pode encontrar o arquivo especificado.
[2023-04-22T02:51:30.394050300Z][com.docker.diagnose.exe][W] (0653d435-1) 997956f9-com.docker.diagnose C<-S NoResponse GET /ping (690.7µs): Get "http://ipc/ping": open \\.\pipe\dockerDnsForwarder: O sistema não pode encontrar o arquivo especificado.
[2023-04-22T02:51:30.555502400Z][com.docker.diagnose.exe][I] (8f337acd) ab82c48a-com.docker.diagnose C<-S 5e4cbeda-ServiceAPI GET /hyperv/bootloader (163.8255ms): 0xc000102470
[2023-04-22T02:51:30.556047600Z][com.docker.diagnose.exe][I] ipc.NewClient: 4795f545-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service
[2023-04-22T02:51:30.557141700Z][com.docker.diagnose.exe][I] (3951cad2) 4795f545-com.docker.diagnose C->S com.docker.service GET /hyperv/check-virtualization
[2023-04-22T02:51:30.747427600Z][com.docker.diagnose.exe][I] (3951cad2) 4795f545-com.docker.diagnose C<-S 5e4cbeda-ServiceAPI GET /hyperv/check-virtualization (189.7636ms): {"HypervisorPresent":true,"VmmsServiceAlreadyRunning":true,"VmmsServiceAvailable":true,"VmmsServiceError":""}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1a9 pc=0xda53d1]

goroutine 11 [running]:
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.findStringInKMSG({0x23?, 0x1096910?})
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/vm.go:55 +0x51
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.vmStartWorks({0x1?, 0x0?})
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/vm.go:41 +0x25
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1595ae0, {0x10a0f18?, 0xc00006ed80?})
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/test.go:47 +0x4f
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.Run.func1(0x1595ae0)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:21 +0x65
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x6?, 0x1595ae0)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:146 +0x77
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x5, 0x1595ae0, 0xc000121a68)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:155 +0x87
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x4, 0x1595b60, 0xc000121a68)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:152 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x1595c60, 0xc000121a68)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:152 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1595ce0, 0xc000121a68)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:152 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1595d60, 0xc000121a68)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:152 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x15964e0, 0xc000121a68)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:152 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkOnce(0x0?, 0xc000525c00)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:141 +0xcc
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.Run({0x10a0f18, 0xc00006ed80}, 0x15964e0, 0x0?, 0x0)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:20 +0x212
github.com/docker/pinata/common/pkg/diagkit/gather.(*SelfDiagnose).Trigger(0x15a3750, {0x10a0f18, 0xc00006ed80})
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.go:32 +0x86
created by main.gatherCmd
        github.com/docker/pinata/common/cmd/com.docker.diagnose/main.go:288 +0xa2a
```


and the folder: C:\Users\admin\AppData\Local\Temp\66E116E0-CC07-4C76-9D51-9496A0AA6037

its empty

**Comment by hseiyo** [comment]
@frkr 
I also experienced the same error, but I was able to install 4.19.0 using the following method. 
There was an old version of Docker installed in my environment, so it may not work for you.

Rename the folder names as follows:

C:\Users\your user name\AppData\Roaming\Docker to Docker_backup
C:\Users\your user name\AppData\Roaming\Docker Desktop to Docker Desktop_backup
C:\Users\your user name\AppData\Local\Docker to Docker_backup

Run the following command in an administrator command prompt:

`start /w "" "Docker Desktop Installer.exe" install --backend=wsl-2
`

Before running the above command, I deleted the Docker-related registry entries, so that may have affected the situation. However, I did not see any change until I renamed the folders as above. It may also be unnecessary to specify the backend during installation, but I am not certain.

**Comment by frkr** [comment]
Previously, I installed Windows Hyper-V and the installation worked. But it didn't run anymore.

So what I did.

I went to "Uninstall or Change Program" and followed the steps of our friend @hseiyo.

And it worked.


# the wsl2 command

> i tryed some new commands.
> 
> Trying to install with wsl-2
> 
> ```
> -------------------------------------------------------------------------------->8
> Version: 4.18.0 (104112)
> Sha1: 
> Started on: 2023/04/22 02:10:21.738
> Resources: C:\Users\admin\Downloads\resources
> OS: Windows 10 Education
> Edition: Education
> Id: 2009
> Build: 19045
> BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
> File: C:\ProgramData\DockerDesktop\install-log-admin.txt
> CommandLine: "Docker Desktop Installer.exe"  install --no-windows-containers --backend=wsl-2 --admin-settings

# the windows install

> ```
> 
> Installing with windows:
> 
> ```
> -------------------------------------------------------------------------------->8
> Version: 4.18.0 (104112)
> Sha1: 
> Started on: 2023/04/22 02:14:51.147
> Resources: C:\Users\admin\Downloads\resources
> OS: Windows 10 Education
> Edition: Education
> Id: 2009
> Build: 19045
> BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
> File: C:\ProgramData\DockerDesktop\install-log-admin.txt
> CommandLine: "Docker Desktop Installer.exe"  install --no-windows-containers --backend=windows --admin-settings
> You can send feedback, including this log file, at https://github.com/docker/for-win/issues

> [2023-04-22T02:18:23.226725200Z][InstallWorkflow][I] Installation succeeded
> ```
> 
> After install, the following file could be modfied or not. But the result its the same.
> 
> install-settings.json
> 
> ```
> {
>   "useWindowsContainers": true,
>   "noWindowsContainers": true
> }
> ```
> 
> Diagnose:
> 
> ```
> [2023-04-22T02:51:30.387464200Z][com.docker.diagnose.exe][I] set path configuration to OnHost
> Gathering diagnostics for ID 66E116E0-CC07-4C76-9D51-9496A0AA6037/20230422025130 into C:\Users\admin\AppData\Local\Temp\66E116E0-CC07-4C76-9D51-9496A0AA6037\20230422025130.zip.

> created by main.gatherCmd
>         github.com/docker/pinata/common/cmd/com.docker.diagnose/main.go:288 +0xa2a
> ```
> 
> and the folder: C:\Users\admin\AppData\Local\Temp\66E116E0-CC07-4C76-9D51-9496A0AA6037
> 
> its empty



# before... i uninstalled it. AND:


> @frkr I also experienced the same error, but I was able to install 4.19.0 using the following method. There was an old version of Docker installed in my environment, so it may not work for you.
> 
> Rename the folder names as follows:
> 
> C:\Users\your user name\AppData\Roaming\Docker to Docker_backup C:\Users\your user name\AppData\Roaming\Docker Desktop to Docker Desktop_backup C:\Users\your user name\AppData\Local\Docker to Docker_backup
> 
> Run the following command in an administrator command prompt:
> 
> `start /w "" "Docker Desktop Installer.exe" install --backend=wsl-2 `
> 
> Before running the above command, I deleted the Docker-related registry entries, so that may have affected the situation. However, I did not see any change until I renamed the folders as above. It may also be unnecessary to specify the backend during installation, but I am not certain.

# and now:

```
C:\Users\admin\Downloads>start /w "" "Docker Desktop Installer.exe" install --backend=wsl-2
-------------------------------------------------------------------------------->8
Version: 4.18.0 (104112)
Sha1:
Started on: 2023/05/03 13:26:36.530
Resources: C:\Users\admin\Downloads\resources
OS: Windows 10 Education
Edition: Education
Id: 2009
Build: 19045
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\ProgramData\DockerDesktop\install-log-admin.txt
CommandLine: "Docker Desktop Installer.exe"  install --backend=wsl-2
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2023-05-03T13:26:36.806796800Z][ManifestAndExistingInstallationLoader][I] No install path specified, looking for default installation registry key
[2023-05-03T13:26:36.820796500Z][Installer][I] No installation found
[2023-05-03T13:26:36.953796000Z][InstallWorkflow][I] Cancel pending background download
[2023-05-03T13:26:36.956796700Z][BackgroundTransfer][I] Cancel current background transfer job
[2023-05-03T13:26:41.185810900Z][InstallWorkflow][I] Using package: res:DockerDesktop
[2023-05-03T13:26:41.187807700Z][InstallWorkflow][I] Downloading
[2023-05-03T13:26:45.960797300Z][InstallWorkflow][I] Extracting manifest
[2023-05-03T13:26:47.292801200Z][InstallWorkflow][I] Manifest found: version=104112, displayVersion=4.18.0, channelUrl=https://desktop.docker.com/win/main/amd64/appcast.xml
[2023-05-03T13:26:47.292801200Z][InstallWorkflow][I] Checking prerequisites
[2023-05-03T13:26:47.760796300Z][InstallWorkflow][I] Prompting for optional features
[2023-05-03T13:26:47.762796000Z][Installer][W] Failed to track the installer started event
[2023-05-03T13:27:00.814794000Z][InstallWorkflow][I] Selected backend mode: wsl-2
[2023-05-03T13:27:00.815795500Z][InstallWorkflow][I] Unpacking artifacts
[2023-05-03T13:30:05.621800200Z][InstallWorkflow][I] Deploying component CommunityInstaller.CreateGroupAction
[2023-05-03T13:30:14.786799500Z][InstallWorkflow][I] Deploying component CommunityInstaller.AddToGroupAction
[2023-05-03T13:30:23.884802700Z][InstallWorkflow][I] Deploying component CommunityInstaller.EnableFeaturesAction
[2023-05-03T13:30:23.920797000Z][InstallWorkflow-EnableFeaturesAction][I] Required features: VirtualMachinePlatform, Microsoft-Windows-Subsystem-Linux
[2023-05-03T13:30:24.904795500Z][InstallWorkflow][I] Deploying component CommunityInstaller.ServiceAction
[2023-05-03T13:30:24.908797700Z][InstallWorkflow-ServiceAction][I] Removing service
[2023-05-03T13:30:24.911796800Z][InstallWorkflow-ServiceAction][I] Creating service
[2023-05-03T13:30:24.914796700Z][InstallWorkflow][I] Deploying component CommunityInstaller.ShortcutAction
[2023-05-03T13:30:24.938798200Z][InstallWorkflow-ShortcutAction][I] Creating shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Docker Desktop.lnk/Docker Desktop
[2023-05-03T13:30:25.035797100Z][InstallWorkflow][I] Deploying component CommunityInstaller.AutoStartAction
[2023-05-03T13:30:25.037796300Z][InstallWorkflow][I] Deploying component CommunityInstaller.PathAction
[2023-05-03T13:30:25.256794900Z][InstallWorkflow][I] Deploying component CommunityInstaller.ExecAction
[2023-05-03T13:30:25.263795300Z][InstallWorkflow-ExecAction][I] Running: C:\Program Files\Docker\Docker\InstallerCli.exe -i with timeout=-1
[2023-05-03T13:30:30.455796500Z][InstallWorkflow][I] Registering product
[2023-05-03T13:30:30.474799600Z][InstallWorkflow][I] Deleting C:\ProgramData\DockerDesktop\install-settings.json
[2023-05-03T13:30:30.479797400Z][InstallWorkflow][I] Installation succeeded
```

# testing

```
C:\WINDOWS\system32>docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
2db29710123e: Pull complete
Digest: sha256:4e83453afed1b4fa1a3500525091dbfca6ce1e66903fd4c01ff015dbcb1ba33e
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/


C:\WINDOWS\system32>
```

**Comment by dedi74132** [comment]
> @frkr I also experienced the same error, but I was able to install 4.19.0 using the following method. There was an old version of Docker installed in my environment, so it may not work for you.
> 
> Rename the folder names as follows:
> 
> C:\Users\your user name\AppData\Roaming\Docker to Docker_backup C:\Users\your user name\AppData\Roaming\Docker Desktop to Docker Desktop_backup C:\Users\your user name\AppData\Local\Docker to Docker_backup
> 
> Run the following command in an administrator command prompt:
> 
> `start /w "" "Docker Desktop Installer.exe" install --backend=wsl-2 `
> 
> Before running the above command, I deleted the Docker-related registry entries, so that may have affected the situation. However, I did not see any change until I renamed the folders as above. It may also be unnecessary to specify the backend during installation, but I am not certain.

awesome, you save my day...

**Comment by gabrielparanhosdev** [comment]
I have problem too
![image](https://github.com/docker/for-win/assets/76761558/f4cbc4a5-765a-4f64-890a-64d90025baf0)
