### ISSUE TITLE
Docker Desktop destroys `docker-desktop` WSL distro

### ISSUE THREAD

**Issue by LeviPesin** [docker/for-win#13418]
- [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F7452781-0CA0-47E5-BDFA-EE163E156BA0/20230422095827

### Actual behavior
Docker Desktop throws the following error after about ~20-30 minutes trying to start:
```
System.Exception:
1 error occurred:
	* waiting for docker daemon: context deadline exceeded


   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__10.MoveNext() in C:\workspaces\PR-21378\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-21378\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__7.MoveNext() in C:\workspaces\PR-21378\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__7.MoveNext() in C:\workspaces\PR-21378\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Engines.Engines.<WaitCurrentTransitionsAsync>d__30.MoveNext() in C:\workspaces\PR-21378\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 282
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__24.MoveNext() in C:\workspaces\PR-21378\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 114
```
The log file is attached: [log.txt](https://github.com/docker/for-win/files/11301040/log.txt)

### Expected behavior
Docker Desktop starts properly.

### Information
  - Windows Version: Windows 10 Home 22H2 Build 19045.2846 Windows Feature Experience Pack 120.2212.4190.0
  - Docker Desktop Version: 4.18.0
  - WSL2 or Hyper-V backend? WSL2
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`
```
[2023-04-22T10:12:24.260876500Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[PASS] DD0028: is there available VM disk space?
[FAIL] DD0002: does the bootloader have virtualization enabled? contacting Windows service: Get "http://ipc/hyperv/bootloader": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:30.937893000Z][com.docker.diagnose.exe][I] ipc.NewClient: 5fdd02df-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service
[2023-04-22T10:12:30.938870800Z][com.docker.diagnose.exe][I] (887a72fc) 5fdd02df-com.docker.diagnose C->S com.docker.service GET /hyperv/bootloader
[2023-04-22T10:12:30.940886200Z][com.docker.diagnose.exe][W] (887a72fc) 5fdd02df-com.docker.diagnose C<-S NoResponse GET /hyperv/bootloader (2.0154ms): Get "http://ipc/hyperv/bootloader": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:30.941888900Z][com.docker.diagnose.exe][I] (887a72fc-1) 5fdd02df-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:30.943887600Z][com.docker.diagnose.exe][W] (887a72fc-1) 5fdd02df-com.docker.diagnose C<-S NoResponse GET /ping (1.9987ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:31.957404900Z][com.docker.diagnose.exe][I] (887a72fc-2) 5fdd02df-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:31.959935200Z][com.docker.diagnose.exe][W] (887a72fc-2) 5fdd02df-com.docker.diagnose C<-S NoResponse GET /ping (2.5303ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:32.962470800Z][com.docker.diagnose.exe][I] (887a72fc-3) 5fdd02df-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:32.966625300Z][com.docker.diagnose.exe][W] (887a72fc-3) 5fdd02df-com.docker.diagnose C<-S NoResponse GET /ping (4.0712ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:33.971173400Z][com.docker.diagnose.exe][I] (887a72fc-4) 5fdd02df-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:33.974517500Z][com.docker.diagnose.exe][W] (887a72fc-4) 5fdd02df-com.docker.diagnose C<-S NoResponse GET /ping (3.3441ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:34.990161500Z][com.docker.diagnose.exe][I] (887a72fc-5) 5fdd02df-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:34.992030500Z][com.docker.diagnose.exe][W] (887a72fc-5) 5fdd02df-com.docker.diagnose C<-S NoResponse GET /ping (1.869ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:35.994488400Z][com.docker.diagnose.exe][I] (887a72fc-6) 5fdd02df-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:35.996543200Z][com.docker.diagnose.exe][W] (887a72fc-6) 5fdd02df-com.docker.diagnose C<-S NoResponse GET /ping (2.0548ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:37.000312200Z][com.docker.diagnose.exe][I] (887a72fc-7) 5fdd02df-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:37.004316500Z][com.docker.diagnose.exe][W] (887a72fc-7) 5fdd02df-com.docker.diagnose C<-S NoResponse GET /ping (4.4432ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:38.013597500Z][com.docker.diagnose.exe][I] (887a72fc-8) 5fdd02df-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:38.017585700Z][com.docker.diagnose.exe][W] (887a72fc-8) 5fdd02df-com.docker.diagnose C<-S NoResponse GET /ping (3.9882ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.

[SKIP] DD0018: does the host support virtualization?
[FAIL] DD0001: is the application running? Docker is not running
[FAIL] DD0022: is the Virtual Machine Platform Windows Feature enabled? querying windows features: Post "http://ipc/windowsfeatures/check": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:38.151349300Z][com.docker.diagnose.exe][I] ipc.NewClient: 058ef254-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service
[2023-04-22T10:12:38.152417500Z][com.docker.diagnose.exe][I] (5223dcd2) 058ef254-com.docker.diagnose C->S com.docker.service POST /windowsfeatures/check: [VirtualMachinePlatform (Virtual Machine Platform)]
[2023-04-22T10:12:38.154405400Z][com.docker.diagnose.exe][W] (5223dcd2) 058ef254-com.docker.diagnose C<-S NoResponse POST /windowsfeatures/check (1.9879ms): Post "http://ipc/windowsfeatures/check": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:38.155388300Z][com.docker.diagnose.exe][I] (5223dcd2-1) 058ef254-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:38.156396100Z][com.docker.diagnose.exe][W] (5223dcd2-1) 058ef254-com.docker.diagnose C<-S NoResponse GET /ping (1.0078ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:39.173492100Z][com.docker.diagnose.exe][I] (5223dcd2-2) 058ef254-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:39.176142200Z][com.docker.diagnose.exe][W] (5223dcd2-2) 058ef254-com.docker.diagnose C<-S NoResponse GET /ping (2.6501ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:40.178934200Z][com.docker.diagnose.exe][I] (5223dcd2-3) 058ef254-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:40.180410200Z][com.docker.diagnose.exe][W] (5223dcd2-3) 058ef254-com.docker.diagnose C<-S NoResponse GET /ping (1.476ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:41.184876100Z][com.docker.diagnose.exe][I] (5223dcd2-4) 058ef254-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:41.188873900Z][com.docker.diagnose.exe][W] (5223dcd2-4) 058ef254-com.docker.diagnose C<-S NoResponse GET /ping (3.9978ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:42.204094000Z][com.docker.diagnose.exe][I] (5223dcd2-5) 058ef254-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:42.208078600Z][com.docker.diagnose.exe][W] (5223dcd2-5) 058ef254-com.docker.diagnose C<-S NoResponse GET /ping (3.9846ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:43.220786900Z][com.docker.diagnose.exe][I] (5223dcd2-6) 058ef254-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:43.224432700Z][com.docker.diagnose.exe][W] (5223dcd2-6) 058ef254-com.docker.diagnose C<-S NoResponse GET /ping (2.6585ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:44.228684200Z][com.docker.diagnose.exe][I] (5223dcd2-7) 058ef254-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:44.232191600Z][com.docker.diagnose.exe][W] (5223dcd2-7) 058ef254-com.docker.diagnose C<-S NoResponse GET /ping (3.5074ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:45.246879400Z][com.docker.diagnose.exe][I] (5223dcd2-8) 058ef254-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:45.249417300Z][com.docker.diagnose.exe][W] (5223dcd2-8) 058ef254-com.docker.diagnose C<-S NoResponse GET /ping (2.5379ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.

[FAIL] DD0021: is the WSL 2 Windows Feature enabled? querying windows features: Post "http://ipc/windowsfeatures/check": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:45.309779600Z][com.docker.diagnose.exe][I] ipc.NewClient: e33d14bd-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service
[2023-04-22T10:12:45.315372600Z][com.docker.diagnose.exe][I] (3ff14aae) e33d14bd-com.docker.diagnose C->S com.docker.service POST /windowsfeatures/check: [Microsoft-Windows-Subsystem-Linux (Windows Subsystem for Linux)]
[2023-04-22T10:12:45.319403400Z][com.docker.diagnose.exe][W] (3ff14aae) e33d14bd-com.docker.diagnose C<-S NoResponse POST /windowsfeatures/check (6.8914ms): Post "http://ipc/windowsfeatures/check": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:45.321362200Z][com.docker.diagnose.exe][I] (3ff14aae-1) e33d14bd-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:45.325543900Z][com.docker.diagnose.exe][W] (3ff14aae-1) e33d14bd-com.docker.diagnose C<-S NoResponse GET /ping (4.1817ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:46.330329900Z][com.docker.diagnose.exe][I] (3ff14aae-2) e33d14bd-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:46.334100500Z][com.docker.diagnose.exe][W] (3ff14aae-2) e33d14bd-com.docker.diagnose C<-S NoResponse GET /ping (3.7706ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:47.349889900Z][com.docker.diagnose.exe][I] (3ff14aae-3) e33d14bd-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:47.355901900Z][com.docker.diagnose.exe][W] (3ff14aae-3) e33d14bd-com.docker.diagnose C<-S NoResponse GET /ping (6.012ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:48.365056700Z][com.docker.diagnose.exe][I] (3ff14aae-4) e33d14bd-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:48.371820000Z][com.docker.diagnose.exe][W] (3ff14aae-4) e33d14bd-com.docker.diagnose C<-S NoResponse GET /ping (6.2261ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:49.386589800Z][com.docker.diagnose.exe][I] (3ff14aae-5) e33d14bd-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:49.390602100Z][com.docker.diagnose.exe][W] (3ff14aae-5) e33d14bd-com.docker.diagnose C<-S NoResponse GET /ping (4.0123ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:50.406125400Z][com.docker.diagnose.exe][I] (3ff14aae-6) e33d14bd-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:50.410593400Z][com.docker.diagnose.exe][W] (3ff14aae-6) e33d14bd-com.docker.diagnose C<-S NoResponse GET /ping (4.468ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:51.427613800Z][com.docker.diagnose.exe][I] (3ff14aae-7) e33d14bd-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:51.432246900Z][com.docker.diagnose.exe][W] (3ff14aae-7) e33d14bd-com.docker.diagnose C<-S NoResponse GET /ping (4.6788ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-04-22T10:12:52.449788000Z][com.docker.diagnose.exe][I] (3ff14aae-8) e33d14bd-com.docker.diagnose C->S com.docker.service GET /ping
[2023-04-22T10:12:52.452947500Z][com.docker.diagnose.exe][W] (3ff14aae-8) e33d14bd-com.docker.diagnose C<-S NoResponse GET /ping (3.9856ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.

[PASS] DD0024: is WSL installed?
[FAIL] DD0025: are WSL distros installed? WSL Distribution docker-desktop is missing
[PASS] DD0026: is the WSL LxssManager service running?
[FAIL] DD0029: is the WSL 2 Linux filesystem corrupt? exit status 0xffffffff
[FAIL] DD0035: is the VM time synchronized? exit status 0xffffffff
[PASS] DD0017: can a VM be started?
[PASS] DD0016: is the LinuxKit VM running?
[FAIL] DD0011: are the LinuxKit services running? failed to ping VM diagnosticsd with error: Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[2023-04-22T10:12:55.724309600Z][com.docker.diagnose.exe][I] ipc.NewClient: 88f82096-diagnose -> \\.\pipe\dockerDiagnosticd diagnosticsd
[2023-04-22T10:12:55.725796100Z][com.docker.diagnose.exe][I] (3896f36d) 88f82096-diagnose C->S diagnosticsd GET /ping
[2023-04-22T10:12:55.727422100Z][com.docker.diagnose.exe][W] (3896f36d) 88f82096-diagnose C<-S NoResponse GET /ping (1.626ms): Get "http://ipc/ping": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.

[FAIL] DD0004: is the Docker engine running? Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-22T10:12:55.737259800Z][com.docker.diagnose.exe][I] ipc.NewClient: 0b655648-com.docker.diagnose -> \\.\pipe\dockerLifecycleServer VMDockerdAPI
[2023-04-22T10:12:55.738182900Z][com.docker.diagnose.exe][I] (2f79a886) 0b655648-com.docker.diagnose C->S VMDockerdAPI GET /docker
[2023-04-22T10:12:55.739995200Z][com.docker.diagnose.exe][W] (2f79a886) 0b655648-com.docker.diagnose C<-S NoResponse GET /docker (1.7511ms): Get "http://ipc/docker": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-22T10:12:55.739995200Z][com.docker.diagnose.exe][I] (2f79a886-1) 0b655648-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-22T10:12:55.741997100Z][com.docker.diagnose.exe][W] (2f79a886-1) 0b655648-com.docker.diagnose C<-S NoResponse GET /ping (2.0019ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-22T10:12:56.742594500Z][com.docker.diagnose.exe][I] (2f79a886-2) 0b655648-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-22T10:12:56.745587700Z][com.docker.diagnose.exe][W] (2f79a886-2) 0b655648-com.docker.diagnose C<-S NoResponse GET /ping (2.9932ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-22T10:12:57.753489900Z][com.docker.diagnose.exe][I] (2f79a886-3) 0b655648-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-22T10:12:57.755529300Z][com.docker.diagnose.exe][W] (2f79a886-3) 0b655648-com.docker.diagnose C<-S NoResponse GET /ping (2.0394ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-22T10:12:58.769169800Z][com.docker.diagnose.exe][I] (2f79a886-4) 0b655648-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-22T10:12:58.770734900Z][com.docker.diagnose.exe][W] (2f79a886-4) 0b655648-com.docker.diagnose C<-S NoResponse GET /ping (1.5651ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-22T10:12:59.782354400Z][com.docker.diagnose.exe][I] (2f79a886-5) 0b655648-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-22T10:12:59.787271500Z][com.docker.diagnose.exe][W] (2f79a886-5) 0b655648-com.docker.diagnose C<-S NoResponse GET /ping (4.2521ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-22T10:13:00.802961000Z][com.docker.diagnose.exe][I] (2f79a886-6) 0b655648-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-22T10:13:00.806223000Z][com.docker.diagnose.exe][W] (2f79a886-6) 0b655648-com.docker.diagnose C<-S NoResponse GET /ping (3.262ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-22T10:13:01.809241700Z][com.docker.diagnose.exe][I] (2f79a886-7) 0b655648-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-22T10:13:01.810677300Z][com.docker.diagnose.exe][W] (2f79a886-7) 0b655648-com.docker.diagnose C<-S NoResponse GET /ping (1.4356ms): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.
[2023-04-22T10:13:02.825643100Z][com.docker.diagnose.exe][I] (2f79a886-8) 0b655648-com.docker.diagnose C->S VMDockerdAPI GET /ping
[2023-04-22T10:13:02.826451900Z][com.docker.diagnose.exe][W] (2f79a886-8) 0b655648-com.docker.diagnose C<-S NoResponse GET /ping (808.8µs): Get "http://ipc/ping": open \\.\pipe\dockerLifecycleServer: The system cannot find the file specified.

[PASS] DD0015: are the binary symlinks installed?
[FAIL] DD0031: does the Docker API work? error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine_linux/v1.24/containers/json?limit=0": open //./pipe/docker_engine_linux: The system cannot find the file specified.
[PASS] DD0013: is the $PATH ok?
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json": open //./pipe/docker_engine: The system cannot find the file specified.
[FAIL] DD0003: is the Docker CLI working? exit status 1
[PASS] DD0005: is the user in the docker-users group?
[FAIL] DD0038: is the connection to Docker working? HTTP GET https://login.docker.com: Get "https://login.docker.com": proxyconnect tcp: open \\.\pipe\dockerHTTPProxy: The system cannot find the file specified.
[FAIL] DD0014: are the backend processes running? 3 errors occurred:
        * com.docker.backend.exe is not running
        * com.docker.vpnkit.exe is not running
        * com.docker.proxy.exe is not running


[FAIL] DD0007: is the backend responding? failed to ping com.docker.backend with error: Get "http://ipc/ping": open \\.\pipe\dockerBackendApiServer: The system cannot find the file specified.
[2023-04-22T10:13:04.061251900Z][com.docker.diagnose.exe][I] ipc.NewClient: 9d207ff7-diagnose -> \\.\pipe\dockerBackendApiServer BackendAPI
```
Seems like it becomes stuck then.

### Steps to reproduce the behavior
  1. Try to start Docker Desktop,
  2. Wait some time,
  3. Observe the error.

**Comment by LeviPesin** [comment]
> [FAIL] DD0025: are WSL distros installed? WSL Distribution docker-desktop is missing

I think that's strange... But this is just freshly updated to 4.18.0 Docker Desktop.

**Comment by LeviPesin** [comment]
`wsl -l -v` produces:
```
  NAME                   STATE           VERSION
* Ubuntu-18.04           Stopped         2
  docker-desktop-data    Running         2
```

**Comment by LeviPesin** [comment]
I think I will just back up extensions and settings and then reinstall.

**Comment by LeviPesin** [comment]
Seems like the issue didn't resolve (although `docker-desktop` distro appeared), will update the first post.

**Comment by LeviPesin** [comment]
It seems like one of the steps (trying to start Docker Desktop, running `com.docker.diagnose.exe gather -upload`, running `com.docker.diagnose.exe check`) destroys the `docker-desktop` distro???

**Comment by LeviPesin** [comment]
Seems like after another reinstall without copying settings it finally starts to work...

**Comment by LeviPesin** [comment]
Same issue again...
