### ISSUE TITLE
Unable to start Docker Desktop "Access denied" in logs

### ISSUE THREAD

**Issue by Remscar** [docker/for-win#13506]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: Unable to

### Actual behavior

When I try to start running Docker Desktop nothing happens. If I look in the logs I see:

```
-------------------------------------------------------------------------------->8
Version: 4.19.0 (106363)
Sha1: ea77a2abbb310ce3e094a79b6cb36e4de9d9f507
Started on: 2023/05/24 22:06:08.653
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 22621
BuildLabName: 22621.1.amd64fre.ni_release.220506-1250
File: C:\Users\remsc\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2023-05-24T22:06:08.701898800Z][GUI][I] Starting...
[2023-05-24T22:06:08.805407800Z][GUI][E] Access denied to Docker. Exiting.
```

### Expected behavior

Docker Desktop should start.

I have ensured that my user is a member of the docker user group.
I have tried running as administrator.

### Information

  - Windows Version: 11 Pro (10.0.22621)
  - Docker Desktop Version: 4.19.0
  - WSL2 or Hyper-V backend?  WSL
  - Are you running inside a virtualized Windows e.g. on a cloud server or a VM: No

### Output of `& "C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" check`

```
[2023-05-24T22:11:45.213760300Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Starting diagnostics

[PASS] DD0027: is there available disk space on the host?
[SKIP] DD0028: is there available VM disk space?
[SKIP] DD0002: does the bootloader have virtualization enabled?
[FAIL] DD0018: does the host support virtualization? checking virtualization support via Windows service: Get "http://ipc/hyperv/check-virtualization": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-05-24T22:11:45.224641400Z][com.docker.diagnose.exe][I] ipc.NewClient: fa634799-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service
[2023-05-24T22:11:45.224641400Z][com.docker.diagnose.exe][I] (e0b2143c) fa634799-com.docker.diagnose C->S com.docker.service GET /hyperv/check-virtualization
[2023-05-24T22:11:45.225163400Z][com.docker.diagnose.exe][W] (e0b2143c) fa634799-com.docker.diagnose C<-S NoResponse GET /hyperv/check-virtualization (0s): Get "http://ipc/hyperv/check-virtualization": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-05-24T22:11:45.225163400Z][com.docker.diagnose.exe][I] (e0b2143c-1) fa634799-com.docker.diagnose C->S com.docker.service GET /ping
[2023-05-24T22:11:45.225163400Z][com.docker.diagnose.exe][W] (e0b2143c-1) fa634799-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-05-24T22:11:46.234041700Z][com.docker.diagnose.exe][I] (e0b2143c-2) fa634799-com.docker.diagnose C->S com.docker.service GET /ping
[2023-05-24T22:11:46.234041700Z][com.docker.diagnose.exe][W] (e0b2143c-2) fa634799-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-05-24T22:11:47.249799200Z][com.docker.diagnose.exe][I] (e0b2143c-3) fa634799-com.docker.diagnose C->S com.docker.service GET /ping
[2023-05-24T22:11:47.249799200Z][com.docker.diagnose.exe][W] (e0b2143c-3) fa634799-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-05-24T22:11:48.251810500Z][com.docker.diagnose.exe][I] (e0b2143c-4) fa634799-com.docker.diagnose C->S com.docker.service GET /ping
[2023-05-24T22:11:48.251810500Z][com.docker.diagnose.exe][W] (e0b2143c-4) fa634799-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-05-24T22:11:49.258556600Z][com.docker.diagnose.exe][I] (e0b2143c-5) fa634799-com.docker.diagnose C->S com.docker.service GET /ping
[2023-05-24T22:11:49.258556600Z][com.docker.diagnose.exe][W] (e0b2143c-5) fa634799-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-05-24T22:11:50.266558000Z][com.docker.diagnose.exe][I] (e0b2143c-6) fa634799-com.docker.diagnose C->S com.docker.service GET /ping
[2023-05-24T22:11:50.266558000Z][com.docker.diagnose.exe][W] (e0b2143c-6) fa634799-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-05-24T22:11:51.270030200Z][com.docker.diagnose.exe][I] (e0b2143c-7) fa634799-com.docker.diagnose C->S com.docker.service GET /ping
[2023-05-24T22:11:51.270030200Z][com.docker.diagnose.exe][W] (e0b2143c-7) fa634799-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-05-24T22:11:52.279237400Z][com.docker.diagnose.exe][I] (e0b2143c-8) fa634799-com.docker.diagnose C->S com.docker.service GET /ping
[2023-05-24T22:11:52.279237400Z][com.docker.diagnose.exe][W] (e0b2143c-8) fa634799-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.

[FAIL] DD0001: is the application running? Docker is not running
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1c1 pc=0x16a99b1]

goroutine 1 [running]:
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.findStringInKMSG({0x198a6c0?, 0xc000008060?})
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/vm.go:55 +0x51
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.vmStartWorks({0xc000367e80?, 0xc000367ea0?})
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/vm.go:41 +0x25
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1e9ea80, {0x1991028?, 0xc000443da0?})
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/test.go:47 +0x4f
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.Run.func1(0x1e9ea80)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:21 +0x65
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x6?, 0x1e9ea80)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:146 +0x77
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x5, 0x1e9ea80, 0xc0005bd770)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:155 +0x87
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x4, 0x1e9eb00, 0xc0005bd770)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:152 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x1e9eb80, 0xc0005bd770)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:152 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1e9ec80, 0xc0005bd770)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:152 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1e9ed00, 0xc0005bd770)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:152 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x1e9f580, 0xc0005bd770)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:152 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkOnce(0xc00035f8c8?, 0xc00035f908)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:141 +0xcc
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.Run({0x1991028, 0xc000443da0}, 0x1e9f580, 0xc00007c000?, 0x1)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:20 +0x213
main.checkCmd({0xc00010e3b0?, 0xc00035ff50?, 0x2?}, {0x0, 0x0})
        github.com/docker/pinata/common/cmd/com.docker.diagnose/main.go:157 +0x129
main.main()
        github.com/docker/pinata/common/cmd/com.docker.diagnose/main.go:119 +0x329
```

**Comment by Darkbelg** [comment]
Can you check the Virtual hdd space?

**Comment by Remscar** [comment]
> Can you check the Virtual hdd space?

Not anymore. I did a complete uninstall / reinstall and it works again.
