### ISSUE TITLE
 starting keep alive in the data distro: waiting for wsl-keepalive to be ready:...

### ISSUE THREAD

**Issue by VandenplasTDY** [docker/for-win#13523]
Experiencing almost the same, Docker Desktop 4.17.0 was just installed fresh to Win10, but with error:

> 2 errors occurred:
>    * starting keep alive in the data distro: waiting for wsl-keepalive to be ready: running wsl-keepalive in "docker-desktop->data": exit status 0xffffffff
 >   * checking if isocache exists: CreateFile \\wsl$\docker-desktop-data\isocache\: The filename, directory name, or volume label syntax is incorrect.

Uninstall, reboot and reinstall didn't fix this.

_Originally posted by @tehautanop in https://github.com/docker/for-win/issues/13273#issuecomment-1453428485_

**Comment by bsousaa** [comment]
can you share the output of `docker version`? How does the error show up? What steps to reproduce?

**Comment by VandenplasTDY** [comment]
It is running the latest version

  NAME                   STATE           VERSION
* Ubuntu                 Running         2
  docker-desktop-data    Running         2
  docker-desktop         Stopped         2

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

System.Exception:

2 errors occurred:
                * starting keep alive in the data distro: waiting for wsl-keepalive to be ready: running wsl-keepalive in "docker-desktop-data": exit status 0xffffffff
                * checking if isocache exists: CreateFile [\\wsl$\docker-desktop-data\isocache\](file://wsl%24/docker-desktop-data/isocache/): The network name cannot be found.


   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__11.MoveNext() in C:\workspaces\4.17.x\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\4.17.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__7.MoveNext() in C:\workspaces\4.17.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__7.MoveNext() in C:\workspaces\4.17.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 108
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__15.MoveNext() in C:\workspaces\4.17.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__23.MoveNext() in C:\workspaces\4.17.x\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:line 109

**Comment by VandenplasTDY** [comment]
I can \\wsl.localhost\docker-desktop-data via windows when docker desktop is not running

Can not access it when docker starts and fails

**Comment by VandenplasTDY** [comment]
After it has failed, if I try and copy to the clipboard any information, a few minutes later I will get a blue screen of death.

**Comment by bsousaa** [comment]
Sounds like you have issues on your Windows setup and it's not Docker related

**Comment by VandenplasTDY** [comment]
What make you say that? I need some more details.  Is it something you have seen in the logs?

Had been working fine for months.

**Comment by bsousaa** [comment]
Simply based on your comment getting a BSOD after copying from clipboard. I would suggest re-installing Docker and possibly the machine.

If you have a specific issue you can reproduce, follow these steps and generate a Diagnostics ID: https://docs.docker.com/engine/install/troubleshoot/

**Comment by VandenplasTDY** [comment]
I expect the copying from clipboard is just a general docker desktop issue.

If I reinstall, will it find my containers or do I lose them?

**Comment by bsousaa** [comment]
It's not clear to me how copying to clipboard is related to Docker Desktop - but I'm probably missing context or information. Re-installing Docker Desktop will clean your image store.

You can find detailed hands-on guides in the docs website that may help you building and save images: https://docs.docker.com/get-started/hands-on-overview/

**Comment by VandenplasTDY** [comment]
Had to remove docker desktop and use normal docker instead.

**Comment by rafntor** [comment]
I have the same symptom (but no BSOD) : 
![image](https://github.com/docker/for-win/assets/44544090/04199005-5cdc-4070-9055-8c0a92342a06)

I have had it for a couple of weeks and it came after updating versions (docker/windows-updates). My machine had been working for years before that

**Comment by VandenplasTDY** [comment]
Yes, that's the same error I got after a windows update.

I lost all my containers and had to remove docker desk and use just docker instead. I had been warned that docker desktop is unstable.

With just docker, I still have integration with WSL2 and VCODE.

**Comment by rafntor** [comment]
Update DD and wsl as suggested [here ](https://github.com/docker/for-win/issues/13445#issuecomment-1548287455) does not help either

![image](https://github.com/docker/for-win/assets/44544090/66f92443-9f17-462d-ad59-9ff885833661)
![image](https://github.com/docker/for-win/assets/44544090/6c2da3e8-1c47-4a4b-a272-b89a444b7d04)

**Comment by VandenplasTDY** [comment]
Yes, I did all that all. (My system was already up to date).

When docker desktop goes wrong, you just lose everything.

From the internet:
Remove Docker Desktop 

Install just docker:
https://stackoverflow.com/a/70934691 and https://nickjanetakis.com/blog/install-docker-in-wsl-2-
without-docker-desktop

**Comment by bsousaa** [comment]
I'm raising priority internally and will investigate further

**Comment by kevgenyk** [comment]
> Yes, I did all that all. (My system was already up to date).
> 
> When docker desktop goes wrong, you just lose everything.
> 
> From the internet: Remove Docker Desktop
> 
> Install just docker: https://stackoverflow.com/a/70934691 and https://nickjanetakis.com/blog/install-docker-in-wsl-2- without-docker-desktop

Did you try wsl --update? It resolved the same issue from my end.

**Comment by VandenplasTDY** [comment]
yes, I did a wsl --update, but in my case it just said that I was already up to date.

**Comment by ovidiuc** [comment]
This has happened to me as well, after updating windows with updates KB5027231 and KB5027119. I've uninstalled KB5027119 and it didn't fix the issue, so I assume the culprit is something in KB5027231. Windows does not give me an option to uninstall it.

Was there any workaround found, aside from going plain docker? WSL and Windows 11 are up to date.

**Comment by VandenplasTDY** [comment]
If you are using VCODE, 

 https://stackoverflow.com/a/70934691 and https://nickjanetakis.com/blog/install-docker-in-wsl-2- without-docker-desktop

gives you same functionality as Docker Desktop.

**Comment by ovidiuc** [comment]
I had to loose all my images and containers and reinstall Docker Desktop. Now it's working.

It's not the first time updates mess up my environment, so I've made a habit of keeping the containers ephemeral.

One other thing I did before reinstalling, completely unrelated, was to enable systemd in `/etc/wsl.conf`. I don't think it mattered, but thought I should mention it.

**Comment by KillenX** [comment]
I fixed it in my case, doing `wsl --update`, and I waited for it to complete. Afterwards I ran `wsl`, it started and docker connected automatically. I would suggest restarting so you are not dependent on that command prompt but otherwise, everything works!

**Comment by gigoug** [comment]
I do "wsl --update" too, and it works for me!
