### ISSUE TITLE
issue downloading 4.20.1

### ISSUE THREAD

**Issue by GhostlyNite10** [docker/for-win#13558]
### Description

when I try to run Docker Desktop Installer.exe I get given a text that says ↓↓↓

Docker Desktop 4.20.1
installation failed

Invalid JSON string. (Exception from HRESULT: 0x83750007)
   at Windows.Data.Json.JsonValue.Parse(String input)
   at CommunityInstaller.InstallWorkflow.SetupBackendModeAndFeatures(List`1 backendModeFeaturesSteps)
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

### Reproduce

Run Docker Desktop Installer.exe

### docker version

```bash
Unkown
```

### docker info

```bash
Unkown
```

### Diagnostics ID

110738

**Comment by ebriney** [comment]
Hello @GhostlyNite10, can you delete `C:\ProgramData\DockerDesktop\install-settings.json`?
It seems to be corrupted.

**Comment by raja-anbazhagan** [comment]
I have tried deleting everthing named docker in my filesystem. No help. I keep getting this error.

```
c:\Users\userid\Downloads>start /w "" "Docker Desktop Installer.exe" install --backend=hyper-v
-------------------------------------------------------------------------------->8
Version: 4.22.1 (118664)
Sha1:
Started on: 2023/08/25 12:12:33.658
Resources: c:\Users\userid\Downloads\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 2009
Build: 19045
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\ProgramData\DockerDesktop\install-log-admin.txt
CommandLine: "Docker Desktop Installer.exe"  install --backend=hyper-v
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2023-08-25T12:12:33.941614900Z][ManifestAndExistingInstallationLoader][I] No install path specified, looking for default installation registry key
[2023-08-25T12:12:33.941614900Z][Installer][I] No installation found
[2023-08-25T12:12:34.191559200Z][InstallWorkflow][I] Cancel pending background download
[2023-08-25T12:12:34.191559200Z][BackgroundTransfer][I] Cancel current background transfer job
[2023-08-25T12:12:34.222842700Z][InstallWorkflow][I] Using package: res:DockerDesktop
[2023-08-25T12:12:34.238469600Z][InstallWorkflow][I] Downloading
[2023-08-25T12:12:39.401268700Z][InstallWorkflow][I] Extracting manifest
[2023-08-25T12:12:40.440324200Z][InstallWorkflow][I] Manifest found: version=118664, displayVersion=4.22.1, channelUrl=https://desktop-stage.docker.com/win/main/amd64/appcast.xml
[2023-08-25T12:12:40.441284700Z][InstallWorkflow][I] Checking prerequisites
[2023-08-25T12:12:41.315350200Z][InstallWorkflow][I] settings from previous installation exist: match the backendmode to that
[2023-08-25T12:12:41.325354100Z][InstallWorkflow][E] Installation failed System.Exception: Invalid JSON string. (Exception from HRESULT: 0x83750007)
   at Windows.Data.Json.JsonValue.Parse(String input)
   at CommunityInstaller.InstallWorkflow.SetupBackendModeAndFeatures(List`1 backendModeFeaturesSteps)
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[2023-08-25T12:12:41.337509800Z][InstallWorkflow][I] Rollbacking component CommunityInstaller.ExtractManifestStep
[2023-08-25T12:12:41.344482200Z][InstallWorkflow][I] Rollbacking component CommunityInstaller.DownloadStep
```

**Comment by raja-anbazhagan** [comment]
Okay. I was running the deployment from the administrator and that user had a different settings on their %appdata% .
Also in my case, the file was a proper JSON but having a comma at the end of last key value pair.

![image](https://github.com/docker/for-win/assets/8947215/22972814-402b-4b71-b3c0-ff8cddc998df)

**Comment by asimibnakhlaque** [comment]
It's been 3 days and I am having the same issue with docker desktop 4.30.0.0
