### ISSUE TITLE
Problems after Activation of Option "Add the *.docker.internal names to the host's etc/hosts file (Requires password)"

### ISSUE THREAD

**Issue by MBMD87** [docker/for-win#13567]
### Description

Hi,
we have problems since we have to use the Option "Add the *.docker.internal names to the host's etc/hosts file (Requires password)" (since 4.18/4.19). Some of our developers need the automated hosts entrys of that Option. Our Developers have no Admin Permissions and since that Option arrived, we had no Problems starting Docker and the Docker Desktop Service seamed to work fine. I think the start type of hat service was manual at that time. Here are the things that i could reproduce since Version 4.19 and Activation of the Option "Add the *.docker.internal names to the host's etc/hosts file (Requires password)".

**Version 4.19**
-	After the Activation the Docker Desktop Service start type seams to switch from manual to automatic
-	After a reboot and new start of Docker an UAC Prompt opens „Docker Desktop Privileged Helper“ Path: „C:\Program Files\Docker\Docker\resources\com.docker.admin.exe“ start-service
-	Since the start type of the Docker Desktop Service is automatic it is already started, so i don’t know what the Privilidged Helper wants to start
-	After clicking “No” Docker starts as expected
-	The prompt doesn't always seem to show up. There seams to be a difference between a connection inside and outside of our domain network

**Version 4.20.1**
-	After the Update to 4.20.1 Docker won’t start 
-	The Service has switched the start type to manual 
-	The UAC Prompt appears again 
-	After clicking „No“ a Message appears that the Docker Desktop Service isn’t running
-	The UAC Prompt appears again
-	After clicking „No“ again it shows the following Error Report:
`System.Exception:
setting up rootless: ensuring com.docker.service is running: starting windows service: user denied admin privileges
   bei Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__10.MoveNext() in C:\workspaces\PR-22253\src\github.com\docker\pinata\win\src\Docker.Engines\WSL2\LinuxWSL2Engine.cs:Zeile 93.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-22253\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:Zeile 29.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__7.MoveNext() in C:\workspaces\PR-22253\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:Zeile 79.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__7.MoveNext() in C:\workspaces\PR-22253\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:Zeile 108.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__17.MoveNext() in C:\workspaces\PR-22253\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:Zeile 97.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Docker.Engines.Engines.<StartAsync>d__24.MoveNext() in C:\workspaces\PR-22253\src\github.com\docker\pinata\win\src\Docker.Engines\Engines.cs:Zeile 124.
`
-	After clicking „Quit“ a .NET Error appears and Docker is closed 

### Reproduce

**Version 4.19**
- Activate Option "Add the *.docker.internal names to the host's etc/hosts file (Requires password)" in the General Settings
- Start Docker after a reboot

**Version 4.20.1**
- Start Docker after upgrade to 4.20.1 if the Option was activated before

### Expected behavior

Docker starts without needing Admin Rights at every startup as it was before. 

### docker version

```bash
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.5
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.19
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.4
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Command line tool for Docker Scout (Docker Inc.)
    Version:  v0.12.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
ERROR: error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info": open //./pipe/docker_engine: The system cannot find the file specified.
errors pretty printing info
```

### docker info

```bash
error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
Client:
 Cloud integration: v1.0.33
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default
```

### Diagnostics ID

-

### Additional Info

No Diagnostics ID because it crashes as admin and also as standard user:

`C:\WINDOWS\system32>"C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe" gather -upload
[2023-06-27T06:25:01.937126800Z][com.docker.diagnose.exe][I] set path configuration to OnHost
Gathering diagnostics for ID 5D1A0932-8BF5-4C2F-B92D-137B40162127/20230627062501 into C:\Users\ADM-MB~1\AppData\Local\Temp\5D1A0932-8BF5-4C2F-B92D-137B40162127\20230627062501.zip.
This may take up to 15 minutes.
[2023-06-27T06:25:01.953256800Z][com.docker.diagnose.exe][I] ipc.NewClient: 36810b16-com.docker.diagnose -> \\.\pipe\dockerDnsForwarder dns-forwarder
[2023-06-27T06:25:01.953826200Z][com.docker.diagnose.exe][I] (411b819f) 36810b16-com.docker.diagnose C->S dns-forwarder POST /diagnostics
[2023-06-27T06:25:01.953256800Z][com.docker.diagnose.exe][I] Triggering Linux sysrq and log flushes via a unix socket: \\.\pipe\dockerDiagnosticd
[2023-06-27T06:25:01.954310100Z][com.docker.diagnose.exe][I] ipc.NewClient: 4fdd842f-com.docker.diagnose -> \\.\pipe\dockerBackendV2 com.docker.service
[2023-06-27T06:25:01.955525600Z][com.docker.diagnose.exe][W] /flush failed: Post "http://unix/flush": open \\.\pipe\dockerDiagnosticd: The system cannot find the file specified.
[2023-06-27T06:25:01.955525600Z][com.docker.diagnose.exe][W] (411b819f) 36810b16-com.docker.diagnose C<-S NoResponse POST /diagnostics (1.6994ms): Post "http://ipc/diagnostics": open \\.\pipe\dockerDnsForwarder: The system cannot find the file specified.
[2023-06-27T06:25:01.956104000Z][com.docker.diagnose.exe][I] (411b819f-1) 36810b16-com.docker.diagnose C->S dns-forwarder GET /ping
[2023-06-27T06:25:01.955525600Z][com.docker.diagnose.exe][I] (4dea452d) 4fdd842f-com.docker.diagnose C->S com.docker.service GET /hyperv/check-virtualization
[2023-06-27T06:25:01.956104000Z][com.docker.diagnose.exe][W] (411b819f-1) 36810b16-com.docker.diagnose C<-S NoResponse GET /ping (0s): Get "http://ipc/ping": open \\.\pipe\dockerDnsForwarder: The system cannot find the file specified.
[2023-06-27T06:25:01.956623400Z][com.docker.diagnose.exe][W] (4dea452d) 4fdd842f-com.docker.diagnose C<-S NoResponse GET /hyperv/check-virtualization (1.0978ms): Get "http://ipc/hyperv/check-virtualization": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-06-27T06:25:01.956623400Z][com.docker.diagnose.exe][I] (4dea452d-1) 4fdd842f-com.docker.diagnose C->S com.docker.service GET /ping
[2023-06-27T06:25:01.957140900Z][com.docker.diagnose.exe][W] (4dea452d-1) 4fdd842f-com.docker.diagnose C<-S NoResponse GET /ping (517.5µs): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-06-27T06:25:02.968301000Z][com.docker.diagnose.exe][I] (4dea452d-2) 4fdd842f-com.docker.diagnose C->S com.docker.service GET /ping
[2023-06-27T06:25:02.968301000Z][com.docker.diagnose.exe][I] (411b819f-2) 36810b16-com.docker.diagnose C->S dns-forwarder GET /ping
[2023-06-27T06:25:02.969173400Z][com.docker.diagnose.exe][W] (4dea452d-2) 4fdd842f-com.docker.diagnose C<-S NoResponse GET /ping (802.3µs): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-06-27T06:25:02.970331000Z][com.docker.diagnose.exe][W] (411b819f-2) 36810b16-com.docker.diagnose C<-S NoResponse GET /ping (2.03ms): Get "http://ipc/ping": open \\.\pipe\dockerDnsForwarder: The system cannot find the file specified.
[2023-06-27T06:25:03.970594000Z][com.docker.diagnose.exe][I] (4dea452d-3) 4fdd842f-com.docker.diagnose C->S com.docker.service GET /ping
[2023-06-27T06:25:03.971249500Z][com.docker.diagnose.exe][W] (4dea452d-3) 4fdd842f-com.docker.diagnose C<-S NoResponse GET /ping (655.5µs): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-06-27T06:25:03.971799400Z][com.docker.diagnose.exe][I] (411b819f-3) 36810b16-com.docker.diagnose C->S dns-forwarder GET /ping
[2023-06-27T06:25:03.972338100Z][com.docker.diagnose.exe][W] (411b819f-3) 36810b16-com.docker.diagnose C<-S NoResponse GET /ping (538.7µs): Get "http://ipc/ping": open \\.\pipe\dockerDnsForwarder: The system cannot find the file specified.
[2023-06-27T06:25:04.972500100Z][com.docker.diagnose.exe][I] (411b819f-4) 36810b16-com.docker.diagnose C->S dns-forwarder GET /ping
[2023-06-27T06:25:04.972500100Z][com.docker.diagnose.exe][I] (4dea452d-4) 4fdd842f-com.docker.diagnose C->S com.docker.service GET /ping
[2023-06-27T06:25:04.973017200Z][com.docker.diagnose.exe][W] (411b819f-4) 36810b16-com.docker.diagnose C<-S NoResponse GET /ping (517.1µs): Get "http://ipc/ping": open \\.\pipe\dockerDnsForwarder: The system cannot find the file specified.
[2023-06-27T06:25:04.974731900Z][com.docker.diagnose.exe][W] (4dea452d-4) 4fdd842f-com.docker.diagnose C<-S NoResponse GET /ping (2.2318ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-06-27T06:25:05.975747500Z][com.docker.diagnose.exe][I] (411b819f-5) 36810b16-com.docker.diagnose C->S dns-forwarder GET /ping
[2023-06-27T06:25:05.977071500Z][com.docker.diagnose.exe][I] (4dea452d-5) 4fdd842f-com.docker.diagnose C->S com.docker.service GET /ping
[2023-06-27T06:25:05.977424600Z][com.docker.diagnose.exe][W] (411b819f-5) 36810b16-com.docker.diagnose C<-S NoResponse GET /ping (1.4794ms): Get "http://ipc/ping": open \\.\pipe\dockerDnsForwarder: The system cannot find the file specified.
[2023-06-27T06:25:05.979782800Z][com.docker.diagnose.exe][W] (4dea452d-5) 4fdd842f-com.docker.diagnose C<-S NoResponse GET /ping (2.7112ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-06-27T06:25:07.006280500Z][com.docker.diagnose.exe][I] (4dea452d-6) 4fdd842f-com.docker.diagnose C->S com.docker.service GET /ping
[2023-06-27T06:25:07.006280500Z][com.docker.diagnose.exe][I] (411b819f-6) 36810b16-com.docker.diagnose C->S dns-forwarder GET /ping
[2023-06-27T06:25:07.007611200Z][com.docker.diagnose.exe][W] (4dea452d-6) 4fdd842f-com.docker.diagnose C<-S NoResponse GET /ping (1.3307ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-06-27T06:25:07.009109800Z][com.docker.diagnose.exe][W] (411b819f-6) 36810b16-com.docker.diagnose C<-S NoResponse GET /ping (2.8293ms): Get "http://ipc/ping": open \\.\pipe\dockerDnsForwarder: The system cannot find the file specified.
[2023-06-27T06:25:08.013455800Z][com.docker.diagnose.exe][I] (411b819f-7) 36810b16-com.docker.diagnose C->S dns-forwarder GET /ping
[2023-06-27T06:25:08.013490800Z][com.docker.diagnose.exe][I] (4dea452d-7) 4fdd842f-com.docker.diagnose C->S com.docker.service GET /ping
[2023-06-27T06:25:08.013558100Z][com.docker.diagnose.exe][W] (411b819f-7) 36810b16-com.docker.diagnose C<-S NoResponse GET /ping (146.7µs): Get "http://ipc/ping": open \\.\pipe\dockerDnsForwarder: The system cannot find the file specified.
[2023-06-27T06:25:08.014518100Z][com.docker.diagnose.exe][W] (4dea452d-7) 4fdd842f-com.docker.diagnose C<-S NoResponse GET /ping (1.0623ms): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-06-27T06:25:09.016391600Z][com.docker.diagnose.exe][I] (4dea452d-8) 4fdd842f-com.docker.diagnose C->S com.docker.service GET /ping
[2023-06-27T06:25:09.016391600Z][com.docker.diagnose.exe][I] (411b819f-8) 36810b16-com.docker.diagnose C->S dns-forwarder GET /ping
[2023-06-27T06:25:09.017366100Z][com.docker.diagnose.exe][W] (4dea452d-8) 4fdd842f-com.docker.diagnose C<-S NoResponse GET /ping (974.5µs): Get "http://ipc/ping": open \\.\pipe\dockerBackendV2: The system cannot find the file specified.
[2023-06-27T06:25:09.019121000Z][com.docker.diagnose.exe][W] (411b819f-8) 36810b16-com.docker.diagnose C<-S NoResponse GET /ping (2.7293ms): Get "http://ipc/ping": open \\.\pipe\dockerDnsForwarder: The system cannot find the file specified.
unable to trigger dns-forwarder diagnostics: Post "http://ipc/diagnostics": open \\.\pipe\dockerDnsForwarder: The system cannot find the file specified.
[2023-06-27T06:25:09.021527200Z][com.docker.diagnose.exe][W] unable to read kubernetes state from settings.json: assuming it is enabled
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1c9 pc=0x87c931]

goroutine 35 [running]:
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.findStringInKMSG({0x23?, 0xb5a2e8?})
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/vm.go:55 +0x51
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.vmStartWorks({0x1?, 0x0?})
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/vm.go:41 +0x25
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.(*test).GetResult(0x1073cc0, {0xb649e8?, 0xc000512030?})
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/test.go:44 +0x4f
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.Run.func1(0x1073cc0)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:21 +0x65
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkOnce.func1(0x6?, 0x1073cc0)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:146 +0x77
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x5, 0x1073cc0, 0xc000151b28)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:155 +0x87
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x4, 0x1073d40, 0xc000151b28)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:152 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x3, 0x1073dc0, 0xc000151b28)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:152 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x2, 0x1073ec0, 0xc000151b28)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:152 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x1, 0x1073f40, 0xc000151b28)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:152 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkDepthFirst(0x0, 0x10747c0, 0xc000151b28)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:152 +0x52
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.walkOnce(0x0?, 0xc0001a3cc0)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:141 +0xcc
github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.Run({0xb649e8, 0xc000512030}, 0x10747c0, 0x0?, 0x0)
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose/run.go:20 +0x213
github.com/docker/pinata/common/pkg/diagkit/gather.(*SelfDiagnose).Trigger(0x1081c60, {0xb649e8, 0xc000512030})
        github.com/docker/pinata/common/pkg/diagkit/gather/diagnose.go:32 +0x86
created by main.gatherCmd
        github.com/docker/pinata/common/cmd/com.docker.diagnose/main.go:288 +0xa2a`

**Comment by MBMD87** [comment]
Is there anyone else having the same Problem? As expected, the Problem persists with the Update to 4.21.1.

**Comment by periscuelo** [comment]
Are you using HYPER-V or WSL2? Because with WSL2 the Option "Add the *.docker.internal names to the host's etc/hosts file (Requires password)" is not necessary according to [the docs](https://docs.docker.com/desktop/windows/permission-requirements/?uuid=4275FE9C-3616-4BF7-A1A7-E4081955DA02). Then if you are trying with WSL2 just not mark this option and it will be ok. This option exists to help someone who decides to use HYPER-V only.

![image](https://github.com/docker/for-win/assets/6675426/e7c52183-88ac-4c1d-9c77-56ec3fbe8998)
