### ISSUE TITLE
An unexpected errpr pccurred

### ISSUE THREAD

**Issue by goatintheshell** [docker/for-win#13573]
### Description

Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/desktop/windows/troubleshoot/#virtualization

### Reproduce

On start up

### Expected behavior

Not this

### docker version

```bash
error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
Client:
 Cloud integration: v1.0.22
 Version:           20.10.12
 API version:       1.41
 Go version:        go1.16.12
 Git commit:        e91ed57
 Built:             Mon Dec 13 11:44:07 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true
```

### docker info

```bash
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.7.1)
  compose: Docker Compose (Docker Inc., v2.2.3)
  scan: Docker Scan (Docker Inc., v0.16.0)

Server:
ERROR: error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info": open //./pipe/docker_engine: The system cannot find the file specified.
errors pretty printing info
```

### Diagnostics ID

Cannot process diagnostics. Reason: Error invoking remote method 'desktop-go-backend': Error: {"message":"[181:12:49:08.867][I] ipc.NewClient: 4b2fdf35-com.docker.diagnose -> \\\\.\\pipe\\dockerBackendV2 com.docker.service.exe\n[goroutine 1 [running, locked to thread]:\n[win/backend/pkg/service.NewClientForPath(...)\n[\twin/backend/pkg/service/service.go:40\n[win/backend/pkg/service.NewClient({0x103e8be, 0x13}, {0x0, 0x0, 0x0})\n[\twin/backend/pkg/service/service.go:29 +0xe8\n[common/pkg/diagkit/gather/diagnose.init()\n[\tcommon/pkg/diagkit/gather/diagnose/ipc_windows.go:23 +0x11f\nGathering diagnostics for ID 41DA4A31-1C4E-41F6-9D1D-F49732C62A2F/20230630164908 into C:\\Users\\Hilary\\AppData\\Local\\Temp\\41DA4A31-1C4E-41F6-9D1D-F49732C62A2F\\20230630164908.zip.\nThis may take up to 15 minutes.\ntime=\"2023-06-30T12:49:08-04:00\" level=info msg=\"Triggering Linux sysrq via a unix socket: \\\\\\\\.\\\\pipe\\\\dockerDiagnosticd\" type=unixsock\ntime=\"2023-06-30T12:49:08-04:00\" level=warning msg=\"/sysrq failed: Post \\\"http://unix/sysrq\\\": open \\\\\\\\.\\\\pipe\\\\dockerDiagnosticd: The system cannot find the file specified.\" type=unixsock\ntime=\"2023-06-30T12:49:08-04:00\" level=info msg=\"Start gathering list of 120 elements (timeout=15m0s)\" type=list\ntime=\"2023-06-30T12:49:08-04:00\" level=info msg=\"Gathering DiagKit\" type=list\ntime=\"2023-06-30T12:49:08-04:00\" level=info msg=\"Gathering BackendGatherer\" type=list\ntime=\"2023-06-30T12:49:08-04:00\" level=info msg=\"Gathering LifecycleServerGatherer\" type=list\ntime=\"2023-06-30T12:49:15-04:00\" level=info msg=\"Gathering ProxyAPIGatherer\" type=list\nerror during connect: This error may indicate that the docker daemon is not running.: Get \"http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json\": open //./pipe/docker_engine: The system cannot find the file specified.\n2023/06/30 12:49:19 exit status 0xffffffff\n: exit status 1"}

**Comment by bsousaa** [comment]
Your request is not clear to me. Can you be more specific on the issue and context this is happening?

**Comment by leonardoeliziario** [comment]
teste

**Comment by leonardoeliziario** [comment]
teste

**Comment by leonardoeliziario** [comment]
teste2
