### ISSUE TITLE
`tc` does not work on Docker for Windows

### ISSUE THREAD

**Issue by tcaiazzi** [docker/for-win#13882]
### Description

Currently, the usage of the `tc` command is not supported on Docker Desktop for Windows, both using hyper-v and WSL2 as engine. 

On hyper-v:
```bash
tc qdisc add dev eth0 root netem delay 10ms
RTNETLINK answers: Operation not supported
```

On WSL2: 
```bash
tc qdisc add dev eth0 root netem delay 10ms
RTNETLINK answers: No such file or directory
```

### Reproduce

1. Run a docker container:
```bash
docker network create --ipam-driver=null --driver=kathara/katharanp_vde:amd64 l2_net
docker run -ti --rm --net l2_net --name=test --privileged kathara/base 
```
2. Type a tc command in the container:
```bash
tc qdisc add dev eth0 root netem delay 10ms
```
On hyper-v, the command will return: 
```bash
RTNETLINK answers: Operation not supported
```

On WSL2, the command will return: 
```bash
RTNETLINK answers: No such file or directory
```

### Expected behavior

The `tc` command should run without error. 

### docker version

```bash
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.7
 API version:       1.43
 Go version:        go1.20.10
 Git commit:        afdd53b
 Built:             Thu Oct 26 09:08:44 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.26.1 (131620)
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### docker info

```bash
Client:
 Version:    24.0.7
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.0-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-buildx.exe
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3-desktop.2
    Path:     C:\Program Files\Docker\cli-plugins\docker-compose.exe
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-dev.exe
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     C:\Program Files\Docker\cli-plugins\docker-extension.exe
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  0.1
    Path:     C:\Program Files\Docker\cli-plugins\docker-feedback.exe
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.10
    Path:     C:\Program Files\Docker\cli-plugins\docker-init.exe
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-sbom.exe
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scan.exe
  scout: Docker Scout (Docker Inc.)
    Version:  v1.2.0
    Path:     C:\Program Files\Docker\cli-plugins\docker-scout.exe

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan kathara/katharanp_vde:amd64 macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.133.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 20
 Total Memory: 7.575GiB
 Name: docker-desktop
 ID: 14421397-d43c-475a-8e5b-1c6ed1ae8810
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### Diagnostics ID

D77FBDA5-8AD6-46D1-AFBC-FEAFE4584888/20240124153425

### Additional Info

Please let me know if you prefer two different issues, one for WSL2 and one for hyper-v.

Just for reference: same issue on Mac with Apple chip (docker/for-mac#7138)
Thanks!

**Comment by Abhijrathod** [comment]
-------------------------------------------------------------------------------->8
Version: 4.26.1 (131620)
Sha1: 
Started on: 2024-01-26 20:05:15.312
Resources: C:\Users\nueon\Downloads\Programs\resources
OS: Windows 10 Home Single Language
Edition: CoreSingleLanguage
Id: 2009
Build: 19045
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\ProgramData\DockerDesktop\install-log-admin.txt
CommandLine: "C:\Users\nueon\Downloads\Programs\Docker Desktop Installer.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2024-01-26T20:05:16.775122300Z][ManifestAndExistingInstallationLoader][I] No install path specified, looking for default installation registry key
[2024-01-26T20:05:16.784153600Z][Installer][E] System.ArgumentNullException: Value cannot be null.
Parameter name: path
   at System.IO.Path.GetFullPathInternal(String path)
   at Docker.Installer.ExistingInstallation.FromRegistry(InstallerSettings settings, String uninstallRegistryKey)
   at Docker.Installer.ManifestAndExistingInstallationLoader.Load()
   at Docker.Installer.Program.Resolve(InstallerSettings settings, ILogger log)
   at Docker.Installer.Program.Run(String[] args)

**Comment by djs55** [comment]
FYI @dgageot

**Comment by djs55** [comment]
Thanks for the report. Could you try again with Hyper-V on 4.27.1? It should now be working:
```
> docker run --privileged -it alpine
/ # apk add iproute2-tc
(1/6) Installing libcap2 (2.69-r1)
(2/6) Installing zstd-libs (1.5.5-r8)
(3/6) Installing libelf (0.190-r1)
(4/6) Installing libmnl (1.0.5-r2)
(5/6) Installing libxtables (1.8.10-r3)
(6/6) Installing iproute2-tc (6.6.0-r0)
Executing busybox-1.36.1-r15.trigger
OK: 9 MiB in 21 packages
/ # tc qdisc add dev eth0 root netem delay 10ms
/ #
```
Note that the WSL 2 case depends on the WSL 2 kernel configuration which is handled by Microsoft here: https://github.com/microsoft/WSL2-Linux-Kernel . I recommend making an issue and describing your use-case over there.

Thanks!

**Comment by Abhijrathod** [comment]
Ok Sir

**Comment by tcaiazzi** [comment]
Hi @djs55, 

It works on Hyper-v. Thanks!

For the WSL 2 case, I will open an issue in the WSL repository, as you suggested. 

Many thanks for the help!
