### ISSUE TITLE
Installation Failed Docker Version: 4.28.0

### ISSUE THREAD

**Issue by tuliocruz** [docker/for-win#14004]
### Description

When running the Docker installer with Administrator permission, an installation failure is reported with the following error message as shown in the screenshot below:
![image](https://github.com/docker/for-win/assets/47005441/d82cec67-889c-4dc4-9530-63c67764602e)
<br>
This is the configuration of my computer with Windows 10:
![image](https://github.com/docker/for-win/assets/47005441/111db2e9-fbb5-4f46-91f7-5e92499a1f17)

<br>
Hyper-V is enabled and wsl is also installed and configured on my Windows 10:

![image](https://github.com/docker/for-win/assets/47005441/738fc554-ac0d-4331-9ea6-21f5a75b75a2)
![image](https://github.com/docker/for-win/assets/47005441/e38d6881-a141-4ad6-b6a8-55287a53bd71)
![image](https://github.com/docker/for-win/assets/47005441/1c7f6ff5-d156-4bc4-b179-70c2fad72192)

### Reproduce

1- Baixe o docker do site official:
![image](https://github.com/docker/for-win/assets/47005441/6cf27950-b6a2-462c-84ad-b965f53b9e82)

2- Execute o arquivo baixado com acesso de Administrador:
![image](https://github.com/docker/for-win/assets/47005441/23b27523-1e10-4f9b-895d-fd1866eded2a)

### docker version

```bash
Component Docker.Installer.EnableFeaturesAction failed: Classe não registrada

   em Docker.Installer.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em Docker.Installer.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

### docker info

```bash
.
```

### Diagnostics ID

123456

**Comment by TheTerrasque** [comment]
Having a similar problem here, not sure if it's the exact same problem. v4.28.0 installer

Error message:

```
Component Docker.Installer.EnableFeaturesAction failed: Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. An attempt was made to load a program with an incorrect format.
   at Docker.Installer.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Installer.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

**Comment by ssalokhaGodel** [comment]
Hi!
Have the same issue with docker

**Comment by mtechnomaniac** [comment]
I also get the following error when trying to install Docker Desktop on Win10:

`Component Docker.Installer.EnableFeaturesAction failed: Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The module was expected to contain an assembly manifest.
   at Docker.Installer.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Installer.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()`


Tried the most recent and older Versions of Docker Desktop Installer: 4.30.0, 4.31.1 & 4.32.0 (157355) but the issue remains even after reinstalling Win 10 Pro 22H2 (19045.4651)

Hyper-V is enabled & WSL are configured. able to launch Ubuntu & also WSL prompts without any issues.

**Comment by elpanas** [comment]
Idem here.
I used the internal updater to update from 4.28 to 4.32 and Docker destroyed itself.
Then I tried to reinstall it from the installer and this error turns up.
I tried to to delete every remaining folder/files manually but nothing
I tried to disable WSL 2 and same error.

![image](https://github.com/user-attachments/assets/baf3fc98-094d-4c82-b90d-2c9f6b1b96af)

**Comment by ovavadim** [comment]
> Idem here. I used the internal updater to update from 4.28 to 4.32 and Docker destroyed itself. Then I tried to reinstall it from the installer and this error turns up. I tried to to delete every remaining folder/files manually but nothing I tried to disable WSL 2 and same error.
> 
> ![image](https://private-user-images.githubusercontent.com/49339752/353531292-baf3fc98-094d-4c82-b90d-2c9f6b1b96af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5ODI1MDksIm5iZiI6MTcyMzk4MjIwOSwicGF0aCI6Ii80OTMzOTc1Mi8zNTM1MzEyOTItYmFmM2ZjOTgtMDk0ZC00YzgyLWI5MGQtMmM5ZjZiMWI5NmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDExNTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3Y2E2ZDRhODY4OTBiNjEzZjNlMDY1YjhmYmUxZjAzZWQ0ODE3NWM0NzAyYWM1OGEwYThkOTJiMGQxN2Y5ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9PY60J8t-8-xd72up2KfS-b0VNycxWWsBr5_eLKRd8g)

I confirm the same issue, this also happened after the update:
https://github.com/docker/for-win/issues/14265

**Comment by mtechnomaniac** [comment]
I simply don't understand why the issue reminded after windows reinstall. finally gave up on Docker and installed Rancher instead :(
