### ISSUE TITLE
Docker on Win 10 Pro does not start

### ISSUE THREAD

**Issue by bugga** [docker/for-win#1402]
### Expected behavior
Docker should start normally
### Actual behavior
An error message that "Hyper-V feature is not enabled." Followed by "Docker failed to enable Hyper-V" (even though this is enabled)
### Information
**Attached** is the install.txt and log.text file
**Error messages from log.txt**
```
[Linux          ][Error  ] Failed to start: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79. Let's retry
[16:10:12.490][PowerShell     ][Info   ] Run script...
[16:10:12.505][Installer      ][Error  ] Unable to test feature Hyper-V: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Dism' was not loaded because no valid module file was found in any module directory.
[16:10:12.505][NamedPipeClient][Error  ] Unable to send Start: BackendInstallFeatureException
...
[16:10:28.466][NamedPipeClient][Info   ] Received response for InstallFeatures
[16:10:28.466][Installer      ][Error  ] Unable to enable feature Hyper-V: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Dism' was not loaded because no valid module file was found in any module directory.
...
[16:11:15.993][NamedPipeServer][Error  ] Unable to execute StopAll: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 279
   at Docker.Backend.ContainerEngine.Linux.Stop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 146
   at Docker.Backend.Backend.StopAll() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Backend.cs:line 80
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[16:11:16.009][NamedPipeClient][Error  ] Unable to send StopAll: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 79
```
**Host info from log.txt**
Version: 17.09.0-ce-win33 (13620)
Channel: stable
Sha1: 8c56a3b0e1bf39569b048201110bf1005e4b3ac9
Started on: 2017/12/09 16:10:10.301
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299
BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534

### Steps to reproduce the behavior

  1. Install Docker for Windows
  2. Run Docker as Administrator
[log.txt](https://github.com/docker/for-win/files/1545230/log.txt)

**Comment by jasonbivins** [comment]
Hi @bugga Do you get any errors in powershell when you run this ``` import-module hyper-v ```
Are you able to open Hyper-V manager and connect to any VM's?

**Comment by bugga** [comment]
@jasonbivins yes, I do get the following error when I run that command. I have not created any VMs in the Hyper-V manager. I'll do that and post the findings as well. Thanks for helping!

PS C:\WINDOWS\system32> import-module hyper-v
import-module : The specified module 'hyper-v' was not loaded because no valid module file was found in any module
directory.
At line:1 char:1
+ import-module hyper-v
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (hyper-v:String) [Import-Module], FileNotFoundException
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by bugga** [comment]
@jasonbivins I was able to create a VM using quick create option with Win 10 dev environment. Hope this helps. Please let me know if there's anything else I should try. Thanks!
