### ISSUE TITLE
Docker ce is not starting up in windows 64 2010 VM from vmware

### ISSUE THREAD

**Issue by rkjaiswal1** [docker/for-win#1407]
Here is the crash report number:
502ABB8B-8E8B-4643-9BBA-DFB08671D067/2017-12-11_17-44-47

Log:

Version: 17.09.0-ce-win33 (13620)
Channel: stable
Sha1: 8c56a3b0e1bf39569b048201110bf1005e4b3ac9
Started on: 2017/12/11 17:09:14.745
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.1794.amd64fre.rs1_release.171008-1615
File: C:\Users\Administrator\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[17:09:22.636][GUI            ][Info   ] Starting...
[17:09:29.433][Tracking       ][Info   ] Crash report and usage statistics are enabled
[17:09:29.433][SegmentApi     ][Info   ] Usage statistic: appLaunched
[17:09:32.276][NPS            ][Info   ] NPS user ceated on :12/11/2017 12:31:11 AM -08:00, last survey : 1/1/0001 12:00:00 AM +00:00
[17:09:32.276][SegmentApi     ][Info   ] Usage statistic: heartbeat
[17:09:32.276][SegmentApi     ][Info   ] Usage statistic: Identify
[17:09:33.683][NamedPipeClient][Info   ] Sending Version()...
[17:09:48.980][NamedPipeClient][Info   ] Sending Version()...
[17:09:49.058][NamedPipeClient][Info   ] Received response for Version
[17:09:49.058][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[17:09:47.276][BackendServer  ][Info   ] Started
[17:09:49.042][NamedPipeServer][Info   ] Version()
[17:09:49.058][NamedPipeServer][Info   ] Version done in 00:00:00.0156498.
[17:09:49.058][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
[17:09:49.089][PowerMode      ][Info   ] Stop
[17:09:49.151][HyperV         ][Info   ] Stop
[17:09:49.339][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[17:09:49.433][PowerShell     ][Info   ] Creating a Runspace Pool...
[17:09:53.776][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[17:09:54.761][HyperV         ][Info   ] Script started at 17:09:54.714
[17:10:00.339][HyperV         ][Info   ] Module loaded at 17:10:00.339
[17:10:02.042][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[17:10:02.042][HyperV         ][Debug  ] [stop] took 00:00:12.8124730 to run
[17:10:02.042][OptimizeDisk   ][Info   ] Optimize
[17:10:02.089][PowerShell     ][Info   ] Run script...
[17:10:04.261][Moby           ][Info   ] Stop
[17:10:04.276][HyperVGuids    ][Info   ] Installing GUIDs...
[17:10:04.276][PowerMode      ][Info   ] Start
[17:10:04.276][HyperV         ][Info   ] Create
[17:10:04.276][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[17:10:04.276][HyperVGuids    ][Info   ] GUIDs installed
[17:10:04.276][Firewall       ][Info   ] Removing all existing rules...
[17:10:04.292][HyperV         ][Info   ] Script started at 17:10:04.292
[17:10:04.308][HyperV         ][Info   ] Module loaded at 17:10:04.308
[17:10:04.339][Firewall       ][Info   ] All existing rules are removed.
[17:10:04.339][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[17:10:04.339][Firewall       ][Info   ] Opening ports for SMB...
[17:10:04.339][Firewall       ][Info   ] Ports are opened
[17:10:05.808][HyperV         ][Info   ] Using existing Switch: DockerNAT
[17:10:08.183][HyperV         ][Info   ] Using existing Switch IP address
[17:10:10.636][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[17:10:11.292][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[17:10:12.370][HyperV         ][Info   ] Disabled Guest Service Interface
[17:10:12.386][HyperV         ][Info   ] Enabled Heartbeat
[17:10:12.417][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[17:10:12.433][HyperV         ][Info   ] Enabled Shutdown
[17:10:12.464][HyperV         ][Info   ] Enabled Time Synchronization
[17:10:12.480][HyperV         ][Info   ] Disabled VSS
[17:10:12.651][HyperV         ][Info   ] VM created.
[17:10:12.651][HyperV         ][Debug  ] [create] took 00:00:08.3750172 to run
[17:10:12.651][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[17:10:12.901][Database       ][Info   ] Generating CA Cert Bundle
[17:10:12.995][DataKit        ][Info   ] Starting com.docker.db.exe 0.7.0-34-g6f04213 ...

[17:10:12.995][DataKit        ][Error  ] com.docker.db.exe: Failed to set up server socket listening on hyperv-connect://bba54225-49dc-4073-bde0-b9e0fd04146a: Unix.Unix_error(Unix.ENETDOWN, "socket", "")

[17:10:12.995][DataKit        ][Info   ] com.docker.db.exe: internal error, uncaught exception:

[17:10:12.995][DataKit        ][Info   ]                    (Failure accept_forever)

[17:10:12.995][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[17:10:12.995][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[17:10:12.995][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[17:10:12.995][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[17:10:12.995][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[17:10:12.995][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json=<REDACTED>
[17:10:12.995][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[17:10:12.995][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[17:10:12.995][DataKit        ][Error  ] Process died
[17:10:13.011][Database       ][Info   ] CA Cert Bundle Generated
[17:10:14.212][Database       ][Error  ] 2017/12/11 17:10:13 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:13 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:13 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:13 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:13 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:13 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:13 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:13 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:14 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:14 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:14 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

[17:10:14.212][Database       ][Error  ] Unable to modify database: Unable to write to the database. Exit code: 1. Let's retry in 1s
[17:10:15.228][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[17:10:15.228][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[17:10:15.228][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[17:10:15.228][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[17:10:15.228][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[17:10:15.228][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json=<REDACTED>
[17:10:15.228][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[17:10:15.228][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[17:10:16.263][Database       ][Error  ] 2017/12/11 17:10:15 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:15 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:15 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:15 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:15 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:15 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:15 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:15 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:16 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:16 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:16 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

[17:10:16.263][Database       ][Error  ] Unable to modify database: Unable to write to the database. Exit code: 1. Let's retry in 1s
[17:10:17.279][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[17:10:17.279][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[17:10:17.279][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[17:10:17.279][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[17:10:17.279][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[17:10:17.279][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json=<REDACTED>
[17:10:17.279][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[17:10:17.279][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[17:10:18.315][Database       ][Error  ] 2017/12/11 17:10:17 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:17 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:17 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:17 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:17 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:17 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:17 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:18 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:18 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:18 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:18 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

[17:10:18.315][Database       ][Error  ] Unable to modify database: Unable to write to the database. Exit code: 1. Let's retry in 1s
[17:10:19.330][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[17:10:19.330][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[17:10:19.330][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[17:10:19.330][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[17:10:19.330][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[17:10:19.330][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json=<REDACTED>
[17:10:19.330][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[17:10:19.330][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[17:10:20.365][Database       ][Error  ] 2017/12/11 17:10:19 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:19 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:19 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:19 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:19 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:19 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:19 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:20 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:20 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:20 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:20 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

[17:10:20.365][Database       ][Error  ] Unable to modify database: Unable to write to the database. Exit code: 1. Let's retry in 1s
[17:10:21.381][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[17:10:21.381][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[17:10:21.381][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[17:10:21.381][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[17:10:21.381][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[17:10:21.381][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json=<REDACTED>
[17:10:21.381][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[17:10:21.381][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[17:10:22.418][Database       ][Error  ] 2017/12/11 17:10:21 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:21 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:21 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:21 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:21 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:21 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:22 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:22 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:22 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:22 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/11 17:10:22 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

[17:10:22.418][Linux          ][Error  ] Failed to start: Unable to write to the database. Exit code: 1. Let's retry
[17:10:22.418][PowerShell     ][Info   ] Run script...
[17:10:30.418][HyperV         ][Info   ] Hyper-V is running
[17:10:30.418][PowerMode      ][Info   ] Stop
[17:10:30.418][HyperV         ][Info   ] Stop
[17:10:30.418][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[17:10:30.433][HyperV         ][Info   ] Script started at 17:10:30.433
[17:10:30.449][HyperV         ][Info   ] Module loaded at 17:10:30.449
[17:10:30.480][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[17:10:30.480][HyperV         ][Debug  ] [stop] took 00:00:00.0625173 to run
[17:10:30.480][OptimizeDisk   ][Info   ] Optimize
[17:10:30.480][PowerShell     ][Info   ] Run script...
[17:10:31.824][Moby           ][Info   ] Stop
[17:10:31.824][HyperV         ][Info   ] Destroy
[17:10:31.824][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[17:10:31.824][HyperV         ][Info   ] Script started at 17:10:31.824
[17:10:31.839][HyperV         ][Info   ] Module loaded at 17:10:31.839
[17:10:31.855][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[17:10:31.871][HyperV         ][Info   ] Destroying Switch DockerNAT...
[17:10:32.761][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[17:10:32.918][HyperV         ][Debug  ] [destroy] took 00:00:01.0937712 to run
[17:10:32.918][Firewall       ][Info   ] Closing ports...
[17:10:32.918][Firewall       ][Info   ] Removing all existing rules...
[17:10:32.980][Firewall       ][Info   ] All existing rules are removed.
[17:10:32.980][Firewall       ][Info   ] Ports are closed
[17:10:32.980][HyperVGuids    ][Info   ] Removing GUIDs...
[17:10:32.996][HyperVGuids    ][Info   ] GUIDs removed
[17:10:32.996][HyperV         ][Info   ] Create
[17:10:32.996][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[17:10:32.996][HyperV         ][Info   ] Script started at 17:10:32.996
[17:10:33.011][HyperV         ][Info   ] Module loaded at 17:10:33.011
[17:10:33.277][HyperV         ][Info   ] Creating Switch: DockerNAT...
[17:10:34.371][HyperV         ][Info   ] Switch created.
[17:10:34.933][HyperV         ][Info   ] Set IP address on switch
[17:10:34.949][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[17:10:35.886][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[17:10:36.074][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[17:10:36.683][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[17:10:36.824][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\mobylinux.iso
[17:10:37.371][HyperV         ][Info   ] Disabled Guest Service Interface
[17:10:37.386][HyperV         ][Info   ] Enabled Heartbeat
[17:10:37.402][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[17:10:37.418][HyperV         ][Info   ] Enabled Shutdown
[17:10:37.433][HyperV         ][Info   ] Enabled Time Synchronization
[17:10:37.464][HyperV         ][Info   ] Disabled VSS
[17:10:37.699][HyperV         ][Info   ] VM created.
[17:10:37.699][HyperV         ][Debug  ] [create] took 00:00:04.7031353 to run
[17:10:37.699][PowerMode      ][Info   ] Stop
[17:10:37.699][HyperV         ][Info   ] Stop
[17:10:37.699][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[17:10:37.714][HyperV         ][Info   ] Script started at 17:10:37.699
[17:10:37.714][HyperV         ][Info   ] Module loaded at 17:10:37.714
[17:10:37.746][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[17:10:37.746][HyperV         ][Debug  ] [stop] took 00:00:00.0468744 to run
[17:10:37.746][OptimizeDisk   ][Info   ] Optimize
[17:10:37.746][PowerShell     ][Info   ] Run script...
[17:10:39.121][Moby           ][Info   ] Stop
[17:10:39.121][HyperV         ][Info   ] Create
[17:10:39.121][PowerMode      ][Info   ] Start
[17:10:39.121][HyperVGuids    ][Info   ] Installing GUIDs...
[17:10:39.121][Firewall       ][Info   ] Removing all existing rules...
[17:10:39.121][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[17:10:39.121][HyperVGuids    ][Info   ] GUIDs installed
[17:10:39.121][HyperV         ][Info   ] Script started at 17:10:39.121
[17:10:39.136][HyperV         ][Info   ] Module loaded at 17:10:39.136
[17:10:39.136][Firewall       ][Info   ] All existing rules are removed.
[17:10:39.136][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[17:10:39.152][Firewall       ][Info   ] Opening ports for SMB...
[17:10:39.152][Firewall       ][Info   ] Ports are opened
[17:10:39.527][HyperV         ][Info   ] Using existing Switch: DockerNAT
[17:10:41.136][HyperV         ][Info   ] Using existing Switch IP address
[17:10:41.168][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[17:10:41.308][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[17:10:41.464][HyperV         ][Info   ] Disabled Guest Service Interface
[17:10:41.496][HyperV         ][Info   ] Enabled Heartbeat
[17:10:41.511][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[17:10:41.527][HyperV         ][Info   ] Enabled Shutdown
[17:10:41.543][HyperV         ][Info   ] Enabled Time Synchronization
[17:10:41.574][HyperV         ][Info   ] Disabled VSS
[17:10:41.714][HyperV         ][Info   ] VM created.
[17:10:41.714][HyperV         ][Debug  ] [create] took 00:00:02.5937016 to run
[17:10:41.714][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[17:10:41.730][Database       ][Info   ] Generating CA Cert Bundle
[17:10:41.746][Database       ][Info   ] CA Cert Bundle Generated
[17:10:41.761][DataKit        ][Info   ] Starting com.docker.db.exe 0.7.0-34-g6f04213 ...

[17:10:41.761][DataKit        ][Error  ] com.docker.db.exe: Failed to set up server socket listening on hyperv-connect://8b12749f-1d84-4165-a089-f560caef5f63: Unix.Unix_error(Unix.ENETDOWN, "socket", "")

[17:10:41.761][DataKit        ][Info   ] com.docker.db.exe: internal error, uncaught exception:

[17:10:41.761][DataKit        ][Info   ]                    (Failure accept_forever)

[17:10:41.777][DataKit        ][Error  ] Process died
[17:10:46.746][PowerMode      ][Info   ] Stop
[17:10:46.746][HyperV         ][Info   ] Stop
[17:10:46.746][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[17:10:46.746][HyperV         ][Info   ] Script started at 17:10:46.746
[17:10:46.761][HyperV         ][Info   ] Module loaded at 17:10:46.761
[17:10:46.793][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[17:10:46.793][HyperV         ][Debug  ] [stop] took 00:00:00.0468591 to run
[17:10:46.793][OptimizeDisk   ][Info   ] Optimize
[17:10:46.793][PowerShell     ][Info   ] Run script...
[17:10:48.136][Moby           ][Info   ] Stop
[17:10:48.136][HyperV         ][Info   ] Destroy
[17:10:48.136][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[17:10:48.136][HyperV         ][Info   ] Script started at 17:10:48.136
[17:10:48.152][HyperV         ][Info   ] Module loaded at 17:10:48.152
[17:10:48.168][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[17:10:48.168][HyperV         ][Info   ] Destroying Switch DockerNAT...
[17:10:48.777][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[17:10:48.824][HyperV         ][Debug  ] [destroy] took 00:00:00.6874879 to run
[17:10:48.824][Firewall       ][Info   ] Closing ports...
[17:10:48.824][Firewall       ][Info   ] Removing all existing rules...
[17:10:48.886][Firewall       ][Info   ] All existing rules are removed.
[17:10:48.886][Firewall       ][Info   ] Ports are closed
[17:10:48.886][HyperVGuids    ][Info   ] Removing GUIDs...
[17:10:48.886][HyperVGuids    ][Info   ] GUIDs removed
[17:10:49.105][NamedPipeServer][Error  ] Unable to execute Start: The operation has timed out.    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 246
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[17:10:49.121][NamedPipeClient][Error  ] Unable to send Start: The operation has timed out.
[17:10:49.121][Notifications  ][Error  ] The operation has timed out.
[17:12:28.918][ErrorReportWindow][Info   ] Open logs
[17:44:47.418][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[17:44:47.418][NamedPipeClient][Info   ] Sending Version()...
[17:44:47.418][NamedPipeClient][Info   ] Sending Version()...
[17:44:47.418][NamedPipeClient][Info   ] Sending Version()...
[17:44:47.418][NamedPipeClient][Info   ] Sending Version()...
[17:44:47.418][NamedPipeClient][Info   ] Received response for Version
[17:44:47.418][NamedPipeClient][Info   ] Received response for Version
[17:44:47.418][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\Administrator\AppData\Local\Temp\dpyl2jcz.34d\mobyLogs.tar)...
[17:44:47.418][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\Administrator\AppData\Local\Temp\dpyl2jcz.34d\win_containers)...
[17:44:47.418][NamedPipeClient][Info   ] Received response for Version
[17:44:47.418][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[17:44:47.418][NamedPipeClient][Info   ] Received response for Version
[17:44:47.418][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\Administrator\AppData\Local\Temp\dpyl2jcz.34d\pcap.tar)...
[17:44:47.418][CrashReport    ][Warning] Unable to collect features settings: Could not find file 'C:\Users\Administrator\AppData\Roaming\Docker\features-overrides.json'.
[17:44:47.418][NamedPipeServer][Info   ] Version()
[17:44:47.418][NamedPipeServer][Info   ] Version done in 00:00:00.
[17:44:47.433][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[17:44:47.418][NamedPipeServer][Info   ] Version()
[17:44:47.418][NamedPipeServer][Info   ] Version done in 00:00:00.
[17:44:47.418][NamedPipeServer][Info   ] Version()
[17:44:47.418][NamedPipeServer][Info   ] Version done in 00:00:00.
[17:44:47.418][NamedPipeServer][Info   ] Version()
[17:44:47.418][NamedPipeServer][Info   ] Version done in 00:00:00.
[17:44:47.418][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\Administrator\AppData\Local\Temp\dpyl2jcz.34d\mobyLogs.tar)
[17:44:47.418][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\Administrator\AppData\Local\Temp\dpyl2jcz.34d\win_containers)
[17:44:47.418][NamedPipeServer][Info   ] GetDebugInfo()
[17:44:47.418][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\Administrator\AppData\Local\Temp\dpyl2jcz.34d\pcap.tar)
[17:44:47.418][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[17:44:47.433][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[17:44:47.433][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0155967.
[17:44:47.918][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[17:44:47.918][HyperV         ][Warning] Unable to download logs: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual machine with name "MobyLinuxVM".
[17:44:47.918][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.4999766.
[17:44:59.418][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[17:44:59.418][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:11.9999959.
[17:45:10.136][NamedPipeClient][Info   ] Received response for GetDebugInfo
[17:45:10.121][NamedPipeServer][Info   ] GetDebugInfo done in 00:00:22.7031423.
[17:45:10.371][CrashReport    ][Info   ] Uploading diagnostics...
[17:45:16.730][CrashReport    ][Info   ] Diagnostics successfully uploaded (502ABB8B-8E8B-4643-9BBA-DFB08671D067/2017-12-11_17-44-47)
[17:45:16.793][GUI            ][Info   ] Sending Bugsnag report 0f674510-6b55-4f73-8f2a-710fc7c10fb8...
[17:45:18.699][GUI            ][Info   ] Bugsnag report 0f674510-6b55-4f73-8f2a-710fc7c10fb8 sent

**Comment by rn** [comment]
since we have no control over how you configure the windows VM in vmware, we can't support this confguration. see https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios
