### ISSUE TITLE
Docker is unable write to the database due to a n error in NamedPipeServer

### ISSUE THREAD

**Issue by deokl** [docker/for-win#1408]
### Expected behavior
Docker starts normally

### Actual behavior
Docker fails to start with error message

Unable to write to the database. Exit code: 1
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 245
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 181
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

In the log file there ist following:

[08:56:15.194][DataKit        ][Info   ] Starting com.docker.db.exe 0.7.0-34-g6f04213 ...
[08:56:15.210][DataKit        ][Info   ] com.docker.db.exe: internal error, uncaught exception:
[08:56:15.210][DataKit        ][Info   ]                    Unix.Unix_error(Unix.ENOTSOCK, "select", "")
[08:56:15.226][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[08:56:15.226][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[08:56:15.226][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[08:56:15.226][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[08:56:15.226][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[08:56:15.226][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json=<REDACTED>
[08:56:15.226][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[08:56:15.226][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[08:56:15.226][Database       ][Info   ] Generating CA Cert Bundle
[08:56:15.257][Database       ][Info   ] CA Cert Bundle Generated
[08:56:15.429][DataKit        ][Error  ] Process died
[08:56:16.706][Database       ][Error  ] 2017/12/12 08:56:15 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/12 08:56:15 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/12 08:56:15 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/12 08:56:15 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/12 08:56:15 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/12 08:56:16 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/12 08:56:16 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/12 08:56:16 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/12 08:56:16 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/12 08:56:16 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/12/12 08:56:16 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.
[08:56:16.706][Database       ][Error  ] Unable to modify database: Unable to write to the database. Exit code: 1. Let's retry in 1s

'Docker version' returns:

Client:
Version:      17.09.1-ce
API version:  1.32
Go version:   go1.8.3
Git commit:   19e2cf6
Built:        Thu Dec  7 22:22:26 2017
OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

### Information

  - Diagnostic ID: 94283CA3-F82C-403E-A504-ECDF9D298691/2017-12-11_17-22-46
  - Windows 10 Enterprise
  - Docker Version 17.09.1-ce-win42 (14687), Channel: stable, 3176a6a

### Steps to reproduce the behavior

  1. Install docker
  2. Start (automatically or manually) 
  3. optionally: run any docker command

**Comment by deokl** [comment]
One of the first lines says: CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
but the exception begins with Docker.Backend.ContainerEngine.Linux.DoStart(...). Is it normal?

**Comment by rn** [comment]
please try the latest versions. Both edge and stable do not use the database anymore
