### ISSUE TITLE
Cannot start Docker Desktop Installer

### ISSUE THREAD

**Issue by ltigas0423** [docker/for-win#14117]
### Description

Uninstalled docker, and now trying to re-install it back. But installer won't open.

`Version: 4.30.0 (149282)
Sha1:
Started on: 2024/06/06 03:06:35.194
Resources: C:\Users\Lexter\Downloads\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 2009
Build: 22631
BuildLabName: 22621.1.amd64fre.ni_release.220506-1250
File: C:\ProgramData\DockerDesktop\install-log-admin.txt
CommandLine: "Docker Desktop Installer (1).exe"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2024-06-06T03:06:35.270110300Z][Installer][E] System.TypeLoadException: Could not load type 'System.ICloneable' from assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Docker.Installer.Analytics.SegmentApi..ctor(ILogger log, InstallerSettings settings, TrackingSettings tracking, IVersion version)
   at Docker.Installer.Program.Resolve(InstallerSettings settings, ILogger log)
   at Docker.Installer.Program.Run(String[] args)
`

### Reproduce

DOWNLOAD Docker Desktop Installer from website
try to open it

### docker version

```bash
Can't install
```

### docker info

```bash
Can't install
```

### Diagnostics ID

Can't install

**Comment by ltigas0423** [comment]
installed 4.24.0 and it worked fine. Tried 4.30, 29, and even 28, not sure the in between versions til 24. But 24 worked

**Comment by raphael-sena** [comment]
Hey, I am having the same trouble here.. How did you find an downloader for an older version od Docker Desktop installer?
