### ISSUE TITLE
Intallation Failed on windows 10 pro

### ISSUE THREAD

**Issue by asimibnakhlaque** [docker/for-win#14134]
### Description

I am unable to install docker on windows 10 pro I have tried every method that I came to knew but still it's showing the same installation error

### Reproduce

```
[2024-06-13T17:22:22.429429900Z][ManifestAndExistingInstallationLoader][I] No install path specified, looking for default installation registry key
[2024-06-13T17:22:22.445061500Z][Installer][I] No installation found
[2024-06-13T17:22:22.643610400Z][InstallWorkflow][I] Using package: res:DockerDesktop
[2024-06-13T17:22:22.655607800Z][InstallWorkflow][I] Downloading
[2024-06-13T17:22:26.042786100Z][InstallWorkflow][I] Extracting manifest
[2024-06-13T17:22:26.862824400Z][InstallWorkflow][I] Manifest found: version=149282, displayVersion=4.30.0, channelUrl=https://desktop-stage.docker.com/win/main/amd64/appcast.xml
[2024-06-13T17:22:26.862824400Z][InstallWorkflow][I] Checking prerequisites
[2024-06-13T17:22:26.904416700Z][InstallWorkflow][I] Prompting for optional features
[2024-06-13T17:22:29.392871000Z][InstallWorkflow][I] Selected backend mode: wsl-2
[2024-06-13T17:22:29.394873100Z][InstallWorkflow][I] Unpacking artifacts
[2024-06-13T17:24:43.274489800Z][InstallWorkflow][I] Deploying component Docker.Installer.CreateGroupAction
[2024-06-13T17:24:43.443675000Z][InstallWorkflow][I] Deploying component Docker.Installer.AddToGroupAction
[2024-06-13T17:24:43.484009900Z][InstallWorkflow][I] Deploying component Docker.Installer.EnableFeaturesAction
[2024-06-13T17:24:44.258969500Z][InstallWorkflow-EnableFeaturesAction][I] Required features: VirtualMachinePlatform, Microsoft-Windows-Subsystem-Linux
[2024-06-13T17:24:44.339969600Z][InstallWorkflow][E] Installation failed System.Exception: Component Docker.Installer.EnableFeaturesAction failed: Provider load failure  ---> System.Management.ManagementException: Provider load failure
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Docker.Installer.EnableFeaturesAction.GetFeaturesToEnable()
   at Docker.Installer.EnableFeaturesAction.<DoAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Installer.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at Docker.Installer.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Installer.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[2024-06-13T17:24:44.349970000Z][InstallWorkflow][I] Rollbacking component Docker.Installer.AddToGroupAction
[2024-06-13T17:24:44.353966800Z][InstallWorkflow][I] Rollbacking component Docker.Installer.CreateGroupAction
[2024-06-13T17:24:44.353966800Z][InstallWorkflow][I] Rollbacking component Docker.Installer.UnpackArtifactsStep
[2024-06-13T17:24:44.367968300Z][FileSystem][I] Deleting C:\Program Files\Docker\Docker
[2024-06-13T17:24:44.667967000Z][FileSystem][I] Deleted C:\Program Files\Docker\Docker successfully
[2024-06-13T17:24:44.667967000Z][InstallWorkflow][I] Rollbacking component Docker.Installer.ExtractManifestStep
[2024-06-13T17:24:44.669968600Z][InstallWorkflow][I] Rollbacking component Docker.Installer.DownloadStep
```

### Expected behavior

Installed and running 

### docker version

```bash
latest version from the official web
```

### docker info

```bash
no info i am unable to install
```

### Diagnostics ID

no id

### Additional Info

I am almost trying from two weeks to install the docker but still no results.

**Comment by leobard** [comment]
I think I had the same problem and I found a solution. Long explanation in this long comment here: https://github.com/docker/for-win/issues/14412#issuecomment-2512868764
