### ISSUE TITLE
Uninstaller doesnt complete uninstallation - 4.30.0 (even after running it as admin)

### ISSUE THREAD

**Issue by aravindk777** [docker/for-win#14145]
### Description

I tried to uninstall the Docker-Desktop from the Programs and Features and also directly from command line also. But ends up getting stuck at the uninstaller trying to remove VMs and images step. Logs has some errors with respect to access denied error and that is the same even when i run the command as ADMINISTRATOR. 

**Error log:**
```
Version: 4.30.0 (149282)
Sha1: 
Started on: 2024/06/19 15:36:31.900
Resources: C:\Users\...\AppData\Local\Temp\DockerDesktop\ogfbk02m5z2\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 2009
Build: 19045
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\ProgramData\DockerDesktop\install-log-admin.txt
CommandLine: "C:\Users\...\AppData\Local\Temp\DockerDesktop\ogfbk02m5z2\Docker Desktop Installer.exe" "uninstall" --remove-self
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2024-06-19T15:36:32.328126200Z][ManifestAndExistingInstallationLoader][I] No install path specified, looking for default installation registry key
[2024-06-19T15:36:33.595387300Z][Installer][I] Existing installation found: build=149282, version=4.30.0, basePath=C:\Program Files\Docker\Docker, channelUrl=https://desktop-stage.docker.com/win/main/amd64/appcast.xml
[2024-06-19T15:36:34.140227000Z][UninstallWorkflow][I] Running before uninstall actions
[2024-06-19T15:36:34.141228000Z][UninstallWorkflow][I] Proceeding with Docker.Installer.ExecAction
[2024-06-19T15:36:34.149107200Z][UninstallWorkflow-ExecAction][I] Running: C:\Program Files\Docker\Docker\InstallerCli.exe -k -u with timeout=60000
[2024-06-19T15:36:37.297115400Z][UninstallWorkflow][I] Done with Docker.Installer.ExecAction
[2024-06-19T15:36:37.298115200Z][UninstallWorkflow][I] Proceeding with Docker.Installer.KillLockingProcessesAction
[2024-06-19T15:36:38.742466800Z][UninstallWorkflow][E] Action Docker.Installer.KillLockingProcessesAction failed: System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\DockerDesktop\tmp-d4w' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Docker.Installer.ResourceManager.AddOwnedFileSystemEntries(IEnumerable`1 paths)
   at Docker.Installer.KillLockingProcessesAction.<DoAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Installer.UninstallWorkflow.<ProcessAsync>d__14.MoveNext()
```

![docker-desktop-uninstaller](https://github.com/docker/for-win/assets/40478917/c1ff910e-4452-432b-974b-c2d900aa12f4)

### Reproduce

1. Install docker-desktop 4.30.0 or higher version in a windows 10 enterprise, with a non admin type account. 
2. Reboot and try to uninstall using the Programs and Features control panel or directly via command line. 
3. Uninstaller will open and gets stuck at this stage 

### Expected behavior

Uninstaller should remove Docker-Desktop completely from the machine. 

### docker version

```bash
Client:
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default
error during connect: in the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version": open //./pipe/docker_engine: The system cannot find the file specified.
```

### docker info

```bash
Client:
 Version:    24.0.2
 Context:    default
 Debug Mode: false

Server:
ERROR: error during connect: in the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/info": open //./pipe/docker_engine: The system cannot find the file specified.
errors pretty printing info
```

### Diagnostics ID

NA

### Additional Info

**Uninstaller log:**

```
Version: 4.30.0 (149282)
Sha1: 
Started on: 2024/06/19 15:36:31.900
Resources: C:\Users\a-aravind_k-t1\AppData\Local\Temp\DockerDesktop\ogfbk02m5z2\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 2009
Build: 19045
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\ProgramData\DockerDesktop\install-log-admin.txt
CommandLine: "C:\Users\a-aravind_k-t1\AppData\Local\Temp\DockerDesktop\ogfbk02m5z2\Docker Desktop Installer.exe" "uninstall" --remove-self
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2024-06-19T15:36:32.328126200Z][ManifestAndExistingInstallationLoader][I] No install path specified, looking for default installation registry key
[2024-06-19T15:36:33.595387300Z][Installer][I] Existing installation found: build=149282, version=4.30.0, basePath=C:\Program Files\Docker\Docker, channelUrl=https://desktop-stage.docker.com/win/main/amd64/appcast.xml
[2024-06-19T15:36:34.140227000Z][UninstallWorkflow][I] Running before uninstall actions
[2024-06-19T15:36:34.141228000Z][UninstallWorkflow][I] Proceeding with Docker.Installer.ExecAction
[2024-06-19T15:36:34.149107200Z][UninstallWorkflow-ExecAction][I] Running: C:\Program Files\Docker\Docker\InstallerCli.exe -k -u with timeout=60000
[2024-06-19T15:36:37.297115400Z][UninstallWorkflow][I] Done with Docker.Installer.ExecAction
[2024-06-19T15:36:37.298115200Z][UninstallWorkflow][I] Proceeding with Docker.Installer.KillLockingProcessesAction
[2024-06-19T15:36:38.742466800Z][UninstallWorkflow][E] Action Docker.Installer.KillLockingProcessesAction failed: System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\DockerDesktop\tmp-d4w' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.AddSearchableDirsToStack(SearchData localSearchData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Docker.Installer.ResourceManager.AddOwnedFileSystemEntries(IEnumerable`1 paths)
   at Docker.Installer.KillLockingProcessesAction.<DoAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Installer.UninstallWorkflow.<ProcessAsync>d__14.MoveNext()
```
![docker-desktop-uninstaller](https://github.com/docker/for-win/assets/40478917/c1ff910e-4452-432b-974b-c2d900aa12f4)

**Comment by byjrack** [comment]
Seeing this cascade with similar results into upgrades.  Playing with ownership and ACLs of `tmp-d4w` seems to get things going again, but it is a mess
