### ISSUE TITLE
Docker failing to start after installation on Win10 Pro

### ISSUE THREAD

**Issue by shan14** [docker/for-win#1419]
### Expected behavior
Docker should start normally
### Actual behavior
Docker fails to start

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
2324F0CE-E473-4497-9C59-E998E617265D/2017-12-12_09-42-42
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
**PS C:\WINDOWS\system32> docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:22:26 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/version: open //./pipe/docker_engine: The system c
annot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to
 connect. This error may also indicate that the docker daemon is not running.**
### Steps to reproduce the behavior

  1. Install latest stable version of Docker for Windows
  2. Start Docker from 'Start' Menu

**Comment by dermeister0** [comment]
Docker does not start after Windows 10 update to version 1709.

```
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(String args, Dictionary`2 env) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 138
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 200
   at Docker.Backend.ContainerEngine.Windows.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 135
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

Diagnostic ID:
F0A02330-1871-4BFD-83F8-86402B74876B/2017-12-13_11-40-16

**Reset to factory defaults** did not help.

**Comment by zzclynn** [comment]
exactly same issue, I reported in https://github.com/docker/for-win/issues/1451, no good answer

**Comment by CAH-FlyChen** [comment]
me too

**Comment by KwalityKoder** [comment]
I'm also on Win 10 (1709)  with Docker for Windows 18.02,0-ce-win52 (15732) [Edge] - exact same error.

**Comment by rn** [comment]
@dermeister0 @shan14 your logs are odd. They both contain a lot of "Problem Signature" messages like:
```
[13:02:09.893][WindowsDaemon  ][Info   ] Fault bucket , type 0
Event Name: OsMitigation
Response: Not available
Cab Id: 0

Problem signature:
P1: consent.exe
P2: 10.0.15063.0
P3: e0f856c4
P4: StackHash_0c4f
P5: 0.0.0.0
P6: 00000000
P7: PCH_EE_FROM_ntdll+0x00000000000A5EF4
P8: c0000409
P9: 000000000000002d
P10:

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERBF32.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_consent.exe_43b5926498d2ea7097d687195e746f37caadf1be_1d88d6cb_283d2b4f
```

I have never seen these, and don't know if they are a red herring. Are you running some AV software you could disable?

Also, might be worth installing all Windows updates and try again with the latest Stable/Edge releases of Docker for Windows

**Comment by sandeep1729** [comment]
try:

cd "C:\Program Files\Docker\Docker"
./DockerCli.exe -SwitchDaemon

https://github.com/docker/for-win/issues/1825#issuecomment-433719346
