### ISSUE TITLE
Unable to start: The VM couldn't get an IP address after 60 tries

### ISSUE THREAD

**Issue by iamffz** [docker/for-win#142]
[18:19:19.654][Notifications  ][Info   ] Docker is restarting...
[18:19:19.696][NamedPipeClient][Info   ] Sending Stop()...
[18:19:19.853][NamedPipeServer][Info   ] Stop()
[18:19:20.095][HyperV         ][Info   ] Stop
[18:19:20.268][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[18:19:23.155][HyperV         ][Info   ] Stopping VM MobyLinuxVM...
[18:19:29.019][HyperV         ][Info   ] Turn Off VM ...
[18:19:29.046][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[18:19:29.079][VpnKit         ][Info   ] Killing existing com.docker.slirp with PID 6624
[18:19:29.094][DataKit        ][Info   ] Killing existing com.docker.db with PID 11108
[18:19:29.141][NamedPipeClient][Info   ] Received response for Stop
[18:19:29.124][NamedPipeServer][Info   ] Stop done.
[18:19:29.152][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[18:19:29.173][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[18:19:29.185][HyperVGuids    ][Info   ] Installing GUIDs...
[18:19:29.206][HyperVGuids    ][Info   ] GUIDs installed
[18:19:29.219][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[18:19:32.429][Firewall       ][Info   ] Ports are opened
[18:19:32.450][HyperV         ][Info   ] Create
[18:19:32.475][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[18:19:33.275][HyperV         ][Info   ] Using existing Switch: DockerNAT
[18:19:33.759][HyperV         ][Info   ] Using existing Switch IP address
[18:19:35.201][HyperV         ][Info   ] Using existing: MobyLinuxVM (state = Off)
[18:19:35.734][HyperV         ][Info   ] Setting MobyLinuxVM vm CPUs to 2 and Memory to 2048 MB
[18:19:35.747][DataKit        ][Info   ] Starting...
[18:19:35.769][PowerShell     ][Info   ] Run script...
[18:19:35.813][DataKit        ][Info   ] Started
[18:19:35.836][VpnKit         ][Info   ] Starting...
[18:19:35.858][PowerShell     ][Info   ] Run script...
[18:19:35.906][DataKit        ][Info   ] 
[18:19:35.918][DataKit        ][Info   ] +22164us    Datakit  Starting com.docker.db.exe 09081b4 ...
[18:19:35.917][VpnKit         ][Info   ] Started
[18:19:35.963][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[18:19:35.976][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[18:19:35.994][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[18:19:35.992][VpnKit         ][Info   ] com.docker.slirp.exe: Logging to stdout (stdout:true DEBUG:false)
[18:19:36.019][VpnKit         ][Info   ] com.docker.slirp.exe: Setting handler to ignore all SIGPIPE signals
[18:19:36.045][VpnKit         ][Info   ] com.docker.slirp.exe: vpnkit version %VERSION% with hostnet version local %HOSTNET_PINNED% uwt version 0.0.3 hvsock version 0.10.0 %HVSOCK_PINNED%
[18:19:36.008][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[18:19:36.065][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[18:19:36.076][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[]}
[18:19:36.056][VpnKit         ][Info   ] com.docker.slirp.exe: starting port_forwarding port_control_url:hyperv-connect://e2e509a1-5eb8-48fd-8835-a2e303841b9b vsock_path:
[18:19:36.100][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to e2e509a1-5eb8-48fd-8835-a2e303841b9b:0B95756A-9985-48AD-9470-78E060895BE7
[18:19:36.087][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[18:19:36.117][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[18:19:36.107][VpnKit         ][Debug  ] com.docker.slirp.exe: Waiting for connections on socket hyperv-connect://e2e509a1-5eb8-48fd-8835-a2e303841b9b
[18:19:36.143][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to e2e509a1-5eb8-48fd-8835-a2e303841b9b:30D48B34-7D27-4B0B-AAAF-BBBED334DD59
[18:19:36.153][VpnKit         ][Debug  ] com.docker.slirp.exe: Waiting for connections on socket hyperv-connect://e2e509a1-5eb8-48fd-8835-a2e303841b9b
[18:19:36.166][VpnKit         ][Info   ] com.docker.slirp.exe: hosts file has bindings for localhost RedisiTopPlus nodeserver nodeserverv2
[18:19:36.965][DataKit        ][Info   ] 
[18:19:36.979][DataKit        ][Info   ] +1081535us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[18:19:36.971][Database       ][Info   ] Successfully wrote 8 value(s)
[18:19:37.018][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/exclude
[18:19:37.042][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/http
[18:19:37.067][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/https
[18:19:37.263][DataKit        ][Info   ] 
[18:19:37.271][DataKit        ][Info   ] +1379564us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[18:19:37.265][Database       ][Info   ] Successfully removed 3 value(s)
[18:19:37.349][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/ssl/certs/ca-certificates.crt=C:\WINDOWS\TEMP\tmpB8E2.tmp
[18:19:37.580][Database       ][Info   ] Successfully wrote value
[18:19:37.581][DataKit        ][Info   ] 
[18:19:37.595][DataKit        ][Info   ] +1697601us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[18:19:37.587][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[18:19:37.760][Database       ][Info   ] Writing com.docker.driver.amd64-linux/slirp/dns=nameserver 192.168.1.86
[18:19:37.976][DataKit        ][Info   ] 
[18:19:37.988][DataKit        ][Info   ] +2092212us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[18:19:37.981][Database       ][Info   ] Successfully wrote 1 value(s)
[18:19:38.020][HyperV         ][Info   ] Start
[18:19:38.047][PowerShell     ][Info   ] Run script with parameters: -Start True...
[18:19:38.106][HyperV         ][Info   ] Starting VM MobyLinuxVM...
[18:19:39.426][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:40.675][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:42.213][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:43.297][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:44.331][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:45.446][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:46.653][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:47.991][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:49.017][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:50.043][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:51.198][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:52.388][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:53.640][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:54.708][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:55.731][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:56.916][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:58.145][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:19:59.457][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:00.478][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:01.513][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:02.615][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:03.856][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:05.100][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:06.121][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:07.141][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:08.273][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:09.550][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:10.805][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:11.832][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:12.911][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:14.025][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:15.248][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:16.478][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:17.501][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:18.545][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:19.644][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:20.807][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:22.029][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:23.051][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:24.072][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:25.153][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:26.316][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:27.536][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:28.558][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:29.581][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:30.657][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:31.802][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:33.010][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:34.030][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:35.049][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:36.131][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:37.283][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:38.502][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:39.524][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:40.546][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:41.625][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:42.778][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:43.991][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:45.015][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:47.738][HyperV         ][Info   ] Hyper-V is running
[18:20:47.755][HyperV         ][Info   ] Create
[18:20:47.767][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[18:20:48.298][HyperV         ][Info   ] Using existing Switch: DockerNAT
[18:20:48.590][HyperV         ][Info   ] Using existing Switch IP address
[18:20:48.683][HyperV         ][Info   ] Using existing: MobyLinuxVM (state = Running)
[18:20:48.693][HyperV         ][Info   ] Stop
[18:20:48.703][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[18:20:48.789][HyperV         ][Info   ] Stopping VM MobyLinuxVM...
[18:20:50.690][HyperV         ][Info   ] Turn Off VM ...
[18:20:50.736][HyperV         ][Info   ] VM MobyLinuxVM killed. Waiting for state to change
[18:20:53.749][HyperV         ][Info   ] Killed VM MobyLinuxVM is off
[18:20:53.762][VpnKit         ][Info   ] Killing existing com.docker.slirp with PID 11884
[18:20:53.775][DataKit        ][Info   ] Killing existing com.docker.db with PID 9048
[18:20:53.785][HyperVGuids    ][Info   ] Installing GUIDs...
[18:20:53.793][HyperVGuids    ][Info   ] GUIDs installed
[18:20:53.799][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[18:20:55.638][Firewall       ][Info   ] Ports are opened
[18:20:55.646][HyperV         ][Info   ] Create
[18:20:55.653][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[18:20:56.065][HyperV         ][Info   ] Using existing Switch: DockerNAT
[18:20:56.154][HyperV         ][Info   ] Using existing Switch IP address
[18:20:56.188][HyperV         ][Info   ] Using existing: MobyLinuxVM (state = Off)
[18:20:56.550][HyperV         ][Info   ] Setting MobyLinuxVM vm CPUs to 2 and Memory to 2048 MB
[18:20:56.559][DataKit        ][Info   ] Starting...
[18:20:56.564][PowerShell     ][Info   ] Run script...
[18:20:56.596][DataKit        ][Info   ] Started
[18:20:56.621][VpnKit         ][Info   ] Starting...
[18:20:56.630][PowerShell     ][Info   ] Run script...
[18:20:56.633][DataKit        ][Info   ] 
[18:20:56.648][DataKit        ][Info   ] +7579us    Datakit  Starting com.docker.db.exe 09081b4 ...
[18:20:56.667][VpnKit         ][Info   ] Started
[18:20:56.677][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[18:20:56.684][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[18:20:56.691][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[18:20:56.699][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[18:20:56.709][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[18:20:56.702][VpnKit         ][Info   ] com.docker.slirp.exe: Logging to stdout (stdout:true DEBUG:false)
[18:20:56.724][VpnKit         ][Info   ] com.docker.slirp.exe: Setting handler to ignore all SIGPIPE signals
[18:20:56.730][VpnKit         ][Info   ] com.docker.slirp.exe: vpnkit version %VERSION% with hostnet version local %HOSTNET_PINNED% uwt version 0.0.3 hvsock version 0.10.0 %HVSOCK_PINNED%
[18:20:56.717][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[]}
[18:20:56.744][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[18:20:56.751][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[18:20:56.738][VpnKit         ][Info   ] com.docker.slirp.exe: starting port_forwarding port_control_url:hyperv-connect://e2e509a1-5eb8-48fd-8835-a2e303841b9b vsock_path:
[18:20:56.769][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to e2e509a1-5eb8-48fd-8835-a2e303841b9b:0B95756A-9985-48AD-9470-78E060895BE7
[18:20:56.776][VpnKit         ][Debug  ] com.docker.slirp.exe: Waiting for connections on socket hyperv-connect://e2e509a1-5eb8-48fd-8835-a2e303841b9b
[18:20:56.784][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to e2e509a1-5eb8-48fd-8835-a2e303841b9b:30D48B34-7D27-4B0B-AAAF-BBBED334DD59
[18:20:56.790][VpnKit         ][Debug  ] com.docker.slirp.exe: Waiting for connections on socket hyperv-connect://e2e509a1-5eb8-48fd-8835-a2e303841b9b
[18:20:56.798][VpnKit         ][Info   ] com.docker.slirp.exe: hosts file has bindings for localhost RedisiTopPlus nodeserver nodeserverv2
[18:20:57.304][Database       ][Info   ] Successfully wrote 8 value(s)
[18:20:57.305][DataKit        ][Info   ] 
[18:20:57.317][DataKit        ][Info   ] +679642us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[18:20:57.311][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/exclude
[18:20:57.335][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/http
[18:20:57.343][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/https
[18:20:57.464][DataKit        ][Info   ] 
[18:20:57.470][DataKit        ][Info   ] +838144us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[18:20:57.465][Database       ][Info   ] Successfully removed 3 value(s)
[18:20:57.544][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/ssl/certs/ca-certificates.crt=C:\WINDOWS\TEMP\tmpF21F.tmp
[18:20:57.716][Database       ][Info   ] Successfully wrote value
[18:20:57.718][DataKit        ][Info   ] 
[18:20:57.728][DataKit        ][Info   ] +1092170us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[18:20:57.723][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[18:20:57.854][Database       ][Info   ] Writing com.docker.driver.amd64-linux/slirp/dns=nameserver 192.168.1.86
[18:20:58.010][DataKit        ][Info   ] 
[18:20:58.017][DataKit        ][Info   ] +1384204us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[18:20:58.010][Database       ][Info   ] Successfully wrote 1 value(s)
[18:20:58.032][HyperV         ][Info   ] Start
[18:20:58.038][PowerShell     ][Info   ] Run script with parameters: -Start True...
[18:20:58.075][HyperV         ][Info   ] Starting VM MobyLinuxVM...
[18:20:58.748][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:20:59.771][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:00.791][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:02.262][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:03.287][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:04.386][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:05.409][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:06.432][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:07.950][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:08.976][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:10.068][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:11.094][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:12.118][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:13.568][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:14.592][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:15.669][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:16.691][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:17.712][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:19.079][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:20.101][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:21.177][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:22.199][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:23.222][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:24.583][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:25.604][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:26.685][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:27.704][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:28.726][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:30.078][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:31.100][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:32.184][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:33.205][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:34.225][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:35.713][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:36.739][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:37.828][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:38.849][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:39.878][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:41.238][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:42.258][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:43.335][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:44.364][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:45.395][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:46.750][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:47.768][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:48.848][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:49.868][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:50.888][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:52.252][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:53.271][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:54.361][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:55.387][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:56.408][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:57.761][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:58.797][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:21:59.967][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:01.009][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:02.042][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:04.187][HyperV         ][Info   ] Wait for the VM to get an IP address
[18:22:05.717][NamedPipeServer][Error  ] Unable to execute Start: Unable to start: The VM couldn't get an IP address after 60 tries
at <ScriptBlock>, <No file>: line 340    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[18:22:05.752][NamedPipeClient][Error  ] Unable to send Start: Unable to start: The VM couldn't get an IP address after 60 tries
at <ScriptBlock>, <No file>: line 340
[18:22:05.860][Notifications  ][Error  ] Unable to start: The VM couldn't get an IP address after 60 tries
at <ScriptBlock>, <No file>: line 340
[18:22:06.003][Program        ][Info   ] Sending Bugsnag report 40cc4992-0de9-4853-862a-c2304934aead...
[18:22:08.585][ErrorReportWindow][Info   ] Open logs
[18:22:08.782][Program        ][Info   ] Bugsnag report 40cc4992-0de9-4853-862a-c2304934aead sent

**Comment by rneugeba** [comment]
@iamffz: thanks for your report. Could you provide a diagnostics ID? it should be printed as part of the erro dialogue and should be of the form `<UUID>/<date>`. It allows us to take a closer look at what is happening.
thanks

**Comment by iamffz** [comment]
diagnostic id : 5D6A3F06-7427-4449-9C56-129893A7B8E6/2559-10-13_10-42-54

**Comment by rneugeba** [comment]
@iamffz thanks for the report. Unfortunately, from looking at the logs, you have the same issue as others users seem to experience. This is tracked under #54. I'll close this as a duplicate and add your details to #54
