### ISSUE TITLE
Hyper-V was unable to find a virtual switch with name "DockerNAT"

### ISSUE THREAD

**Issue by andreimaxim** [docker/for-win#1422]
### Expected behavior

Docker starts.

### Actual behavior

Docker fails to start with the following error:

```
[11:45:58.986][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[11:45:59.547][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385
[11:45:59.549][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 131
```

During the start-up I opened the Hyper-V manager and looked at the virtual switches and DockerNAT was there. When the script finished, the DockerNAT switch was gone.

### Information

A diagnostic was uploaded with id: B723CED3-2DDB-4A4B-A135-9F6963212FC6/2017-12-13_11-55-05.

Docker: 17.09.1-ce-win42
Windows: Windows 10 Pro version 1709, OS build 16299.125

**Comment by andreimaxim** [comment]
I am closing this issue as it seems to be caused by a third-party software, ZoneAlarm in my case. It seems that some antivirus/firewall/anti-malware software might block any attempts to create new virtual switches via scripts. While the behavior seems reasonable for most computer users, it would have been nice to see some alerts when this is going on. 

Uninstalling ZoneAlarm and Docker then reinstalling Docker fixed the problem for me.
