### ISSUE TITLE
Docker installer fails with  System.TypeLoadException

### ISSUE THREAD

**Issue by taquion87** [docker/for-win#14234]
### Description

I ensured my system meets all requirements. After running DockerInstaller I get the following error:

> -------------------------------------------------------------------------------->8
Version: 4.32.0 (157355)
Sha1: 
Started on: 2024/07/31 19:40:19.978
Resources: C:\Users\fcose\Downloads\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 22631
BuildLabName: 22621.1.amd64fre.ni_release.220506-1250
File: C:\Users\fcose\AppData\Local\Docker\install-log.txt
CommandLine: "Docker Desktop Installer.exe"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2024-07-31T19:40:20.040596600Z][Installer][E] System.TypeLoadException: Could not load type 'System.ICloneable' from assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Docker.Installer.Analytics.SegmentApi..ctor(ILogger log, InstallerSettings settings, TrackingSettings tracking, IVersion version)
   at Docker.Installer.Program.Resolve(InstallerSettings settings, ILogger log)
   at Docker.Installer.Program.Run(String[] args)

I am using the lastest installer:

![image](https://github.com/user-attachments/assets/59da680e-5cab-4de9-878b-74327c79d949)

### Reproduce

Just run the installer

### Expected behavior

Docker should be installed

### docker version

```bash
No version, this happens at the moment of the installation
```

### docker info

```bash
No info, this happens at the moment of the installation
```

### Diagnostics ID

No ID

**Comment by FoppeCrezee** [comment]
I am running into the same issue. I also tried an older version (4.29.0) of the same installer, but that doesn't work. I had docker installed previously, but wanted to reinstall. So that might be causing the issue. I tried to delete any files related to docker, which still existed after deinstalling.

**Comment by jkap** [comment]
I was experiencing this issue as well and was able to work around it by moving the installer exe to a different folder (in my case, a subfolder of Downloads was enough). No clue why this was enough, hopefully it helps someone else.

**Comment by FoppeCrezee** [comment]
I managed to get Docker Desktop installed with version 4.16.3 and then upgrade to 4.33.1. So apparently something changed between those versions which caused the issue.
The solution proposed by @jkap, also worked for me!

**Comment by mrpcss** [comment]
> I was experiencing this issue as well and was able to work around it by moving the installer exe to a different folder (in my case, a subfolder of Downloads was enough). No clue why this was enough, hopefully it helps someone else.

Thank you! Confirmed this solved the issue for my install using the latest version.

**Comment by JaronCascante** [comment]
> I was experiencing this issue as well and was able to work around it by moving the installer exe to a different folder (in my case, a subfolder of Downloads was enough). No clue why this was enough, hopefully it helps someone else.

Thank you, this resolved the issue.

**Comment by leocrabe225** [comment]
> I was experiencing this issue as well and was able to work around it by moving the installer exe to a different folder (in my case, a subfolder of Downloads was enough). No clue why this was enough, hopefully it helps someone else.

What? How? It works.

**Comment by james-gould** [comment]
> I was experiencing this issue as well and was able to work around it by moving the installer exe to a different folder (in my case, a subfolder of Downloads was enough). No clue why this was enough, hopefully it helps someone else.

Crazy this is still the solution, why does this work! Thanks.

**Comment by itselliee** [comment]
> I was experiencing this issue as well and was able to work around it by moving the installer exe to a different folder (in my case, a subfolder of Downloads was enough). No clue why this was enough, hopefully it helps someone else.

what. this worked, thank you
