### ISSUE TITLE
I'm Having issue installing Docker Desktop after Windows Update

### ISSUE THREAD

**Issue by simonsteyn** [docker/for-win#14375]
### Description

Here is the log file. This is what it shows after installation failed:
Component Docker.Installer.EnableFeaturesAction failed: Not found 
   at Docker.Installer.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Installer.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

[dism.log](https://github.com/user-attachments/files/17465821/dism.log)

Wsl is enabled, windows features aswell

### Reproduce

I don't know if it's a bug.

### docker version

Newest Version

### docker info

Docker Desktop Windows 10 Home

### Diagnostics ID

312121

**Comment by romanrozinov** [comment]
I have a same issue with v4.35.1 .. I am unsure how to proceed

[install-log-admin.txt](https://github.com/user-attachments/files/17626013/install-log-admin.txt)
