### ISSUE TITLE
Docker Desktop 4.34.3

### ISSUE THREAD

**Issue by ddracoo** [docker/for-win#14392]
### Description

After update, Docker Desktop disappeared. Re-Installation not working and showing this Error: 
`Unpacking failed: Access to the path 'C:\Program Files\Docker\Docker\com.docker.service.config' is denied.
   at Docker.Installer.InstallWorkflow.<DoHandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Installer.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()`

### Reproduce

Executing Docker Desktop Installer exe

### docker version

Docker Desktop 3.43.3 

### docker info

n/a

### Diagnostics ID

n/a

**Comment by D1usantha** [comment]
test

**Comment by hamedhafez1** [comment]
disable anti virus and firewall untill installation
