### ISSUE TITLE
Docker Desktop update loop

### ISSUE THREAD

**Issue by Tom01098** [docker/for-win#14404]
### Description

Docker Desktop has been stuck on 'Update and Restart' for several versions. If I select it, it goes to 'Installing' for a second and then back to 'Update and Restart'. This persists across a reboot of both Docker and the machine. Running the `4.35.1` installer does nothing, and running it from Powershell shows this log:

```
Version: 4.34.3 (170107)
Sha1:
Started on: 2024/11/04 21:27:18.850
Resources: C:\Users\Tom01\Downloads\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 22631
BuildLabName: 22621.1.amd64fre.ni_release.220506-1250
File: C:\Users\Tom01\AppData\Local\Docker\install-log.txt
CommandLine: "C:\Users\Tom01\Downloads\Docker Desktop Installer.exe"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[2024-11-04T21:27:18.978933200Z][ManifestAndExistingInstallationLoader][I] No install path specified, looking for default installation registry key
[2024-11-04T21:27:18.991860600Z][Installer][E] Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 1, position 3712.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Docker.Installer.Manifest.FromJson(String json, Boolean skipPrerequisites, InstallerSettings installerSettings)
   at Docker.Installer.ManifestAndExistingInstallationLoader.LoadManifestIfFileExist(String installDir)
   at Docker.Installer.ManifestAndExistingInstallationLoader.Load()
   at Docker.Installer.Program.Resolve(InstallerSettings settings, ILogger log)
   at Docker.Installer.Program.Run(String[] args)
```

### Reproduce

Have a broken local setup.

### Expected behavior

Docker Desktop should be able to update or at least have a clean install.

### docker version

Client:
 Version:           27.2.0
 API version:       1.47
 Go version:        go1.21.13
 Git commit:        3ab4256
 Built:             Tue Aug 27 14:14:20 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop  ()
 Engine:
  Version:          27.2.0
  API version:      1.47 (minimum version 1.24)
  Go version:       go1.21.13
  Git commit:       3ab5c7d
  Built:            Tue Aug 27 14:15:15 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.7.20
  GitCommit:        8fc6bcff51318944179630522a095cc9dbf9f353
 runc:
  Version:          1.1.13
  GitCommit:        v1.1.13-0-g58aa920
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### docker info

Client:
 Version:    27.2.0
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.16.2-desktop.1
    Path:     /usr/local/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.2-desktop.2
    Path:     /usr/local/lib/docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container (Docker Inc.)
    Version:  0.0.34
    Path:     /usr/local/lib/docker/cli-plugins/docker-debug
  desktop: Docker Desktop commands (Alpha) (Docker Inc.)
    Version:  v0.0.15
    Path:     /usr/local/lib/docker/cli-plugins/docker-desktop
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.2
    Path:     /usr/local/lib/docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.25
    Path:     /usr/local/lib/docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.5
    Path:     /usr/local/lib/docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.3.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.13.0
    Path:     /usr/local/lib/docker/cli-plugins/docker-scout
WARNING: Plugin "/usr/local/lib/docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /usr/local/lib/docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 13
 Server Version: 27.2.0
 Storage Driver: overlayfs
  driver-type: io.containerd.snapshotter.v1
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 nvidia runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fc6bcff51318944179630522a095cc9dbf9f353
 runc version: v1.1.13-0-g58aa920
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
 Kernel Version: 5.15.153.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 15.58GiB
 Name: docker-desktop
 ID: 0b8000f2-aa82-4609-a8b4-d615ee9be45f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Labels:
  com.docker.desktop.address=unix:///var/run/docker-cli.sock
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
WARNING: daemon is not using the default seccomp profile

### Diagnostics ID

4036A451-A9DE-4A6B-AB96-CBEB9580AC35/20241104213046

**Comment by Tom01098** [comment]
This issue still persists. Attempting to uninstall it gets the same error about reading JSON.

**Comment by Tom01098** [comment]
I gave up and deleted everything in `C:\Program Files\Docker`, and ran `wsl --unregister docker-desktop` and `wsl --unregister docker-desktop-data`. The installer worked after this for a fresh install, so I'll close this issue.
