### ISSUE TITLE
Bad response from Docker engine Version 17.09.1-ce-win42 (14687)

### ISSUE THREAD

**Issue by danielcooperxyz** [docker/for-win#1443]
### Expected behavior
Docker runs on startup
### Actual behavior
```
Error response from daemon: Bad response from Docker engine

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 251
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
4B4A59F5-A0FF-4F3A-BACD-17B1944A3F60/2017-12-18_16-34-26
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
```
Version: 17.09.1-ce-win42 (14687)
Channel: stable
Sha1: 3176a6af014bdb1346ed31371a717e87e656e2b7
Started on: 2017/12/18 16:29:39.116
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299
BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534
```
### Steps to reproduce the behavior

  1. Start docker
This is also the case if I try and run as administrator.

**Comment by danielcooperxyz** [comment]
Fixed this by reinstalling docker for windows.
