### ISSUE TITLE
I can't start docker on Windows 10

### ISSUE THREAD

**Issue by ferguardiola** [docker/for-win#1450]
Hello, 

After installing docker on windows 10, and try to start it i got the following error.

Can anybody help me ? Thank you

Version: 17.09.1-ce-win42 (14687)
Channel: stable
Sha1: 3176a6af014bdb1346ed31371a717e87e656e2b7
Started on: 2017/12/20 09:40:21.964
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.1944.amd64fre.rs1_release.171129-2100
File: C:\Users\fernando.guardiola\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at 
[09:40:22.073][GUI            ][Info   ] Starting...
[09:40:22.854][Tracking       ][Info   ] Crash report and usage statistics are enabled
[09:40:22.854][SegmentApi     ][Info   ] Usage statistic: appLaunched
[09:40:24.165][NPS            ][Info   ] NPS user ceated on :12/19/2017 3:23:28 AM -08:00, last survey : 1/1/0001 12:00:00 AM +00:00
[09:40:24.165][SegmentApi     ][Info   ] Usage statistic: heartbeat
[09:40:24.165][SegmentApi     ][Info   ] Usage statistic: Identify
[09:40:24.306][Notifications  ][Info   ] Docker is starting...
[09:40:24.306][NamedPipeClient][Info   ] Sending Version()...
[09:40:24.321][NamedPipeClient][Info   ] Received response for Version
[09:40:24.321][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[09:40:05.105][BackendServer  ][Info   ] Started
[09:40:24.321][NamedPipeServer][Info   ] Version()
[09:40:24.321][NamedPipeServer][Info   ] Version done in 00:00:00.
[09:40:24.337][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
[09:40:24.384][PowerMode      ][Info   ] Stop
[09:40:24.384][HyperV         ][Info   ] Stop
[09:40:24.462][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[09:40:24.540][PowerShell     ][Info   ] Creating a Runspace Pool...
[09:40:25.336][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[09:40:25.571][HyperV         ][Info   ] Script started at 09:40:25.524
[09:40:29.881][HyperV         ][Info   ] Module loaded at 09:40:29.881
[09:40:30.721][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[09:40:30.737][HyperV         ][Debug  ] [stop] took 00:00:06.3525776 to run
[09:40:30.737][OptimizeDisk   ][Info   ] Optimize
[09:40:30.737][PowerShell     ][Info   ] Run script...
[09:40:30.788][Moby           ][Info   ] Stop
[09:40:30.794][HyperVGuids    ][Info   ] Installing GUIDs...
[09:40:30.794][PowerMode      ][Info   ] Start
[09:40:30.796][HyperV         ][Info   ] Create
[09:40:30.796][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[09:40:30.796][HyperVGuids    ][Info   ] GUIDs installed
[09:40:30.796][Firewall       ][Info   ] Removing all existing rules...
[09:40:30.796][HyperV         ][Info   ] Script started at 09:40:30.796
[09:40:30.830][HyperV         ][Info   ] Module loaded at 09:40:30.830
[09:40:31.230][HyperV         ][Info   ] Creating Switch: DockerNAT...
[09:40:31.443][Firewall       ][Info   ] All existing rules are removed.
[09:40:31.444][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[09:40:31.451][Firewall       ][Info   ] Opening ports for SMB...
[09:40:31.491][Firewall       ][Info   ] Ports are opened
[09:40:33.923][HyperV         ][Info   ] Switch created.
[09:40:37.506][HyperV         ][Info   ] Set IP address on switch
[09:40:38.738][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[09:40:41.378][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[09:40:41.960][HyperV         ][Info   ] Creating dynamic VHD: C:\Users\Public\Documents\Hyper-V\Virtual hard disks\MobyLinuxVM.vhdx
[09:40:43.431][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual hard disks\MobyLinuxVM.vhdx
[09:40:44.230][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[09:40:45.487][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\mobylinux.iso
[09:40:46.704][HyperV         ][Info   ] Disabled Guest Service Interface
[09:40:46.738][HyperV         ][Info   ] Enabled Heartbeat
[09:40:46.805][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[09:40:46.842][HyperV         ][Info   ] Enabled Shutdown
[09:40:46.867][HyperV         ][Info   ] Enabled Time Synchronization
[09:40:46.954][HyperV         ][Info   ] Disabled VSS
[09:40:47.969][HyperV         ][Info   ] VM created.
[09:40:47.970][HyperV         ][Debug  ] [create] took 00:00:17.1739448 to run
[09:40:47.970][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[09:40:48.215][Database       ][Info   ] Generating CA Cert Bundle
[09:40:48.257][DataKit        ][Info   ] Starting com.docker.db.exe 0.7.0-34-g6f04213 ...

[09:40:48.272][DataKit        ][Error  ] com.docker.db.exe: Failed to set up server socket listening on hyperv-connect://421e72a5-da29-42bb-8558-3358f2129140: Unix.Unix_error(Unix.ENETDOWN, "socket", "")

[09:40:48.273][DataKit        ][Info   ] com.docker.db.exe: internal error, uncaught exception:

[09:40:48.273][DataKit        ][Info   ]                    (Failure accept_forever)

[09:40:48.279][DataKit        ][Error  ] Process died
[09:40:48.374][Database       ][Info   ] CA Cert Bundle Generated
[09:40:53.191][Linux          ][Error  ] Failed to start: The operation has timed out.. Let's retry
[09:40:53.193][PowerShell     ][Info   ] Run script...
[09:41:01.174][HyperV         ][Info   ] Hyper-V is running
[09:41:01.175][PowerMode      ][Info   ] Stop
[09:41:01.175][HyperV         ][Info   ] Stop
[09:41:01.175][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[09:41:01.188][HyperV         ][Info   ] Script started at 09:41:01.187
[09:41:01.201][HyperV         ][Info   ] Module loaded at 09:41:01.200
[09:41:01.232][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[09:41:01.232][HyperV         ][Debug  ] [stop] took 00:00:00.0573143 to run
[09:41:01.232][OptimizeDisk   ][Info   ] Optimize
[09:41:01.232][PowerShell     ][Info   ] Run script...
[09:41:02.593][Moby           ][Info   ] Stop
[09:41:02.616][HyperV         ][Info   ] Destroy
[09:41:02.616][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[09:41:02.616][HyperV         ][Info   ] Script started at 09:41:02.616
[09:41:02.632][HyperV         ][Info   ] Module loaded at 09:41:02.632
[09:41:02.646][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[09:41:02.647][HyperV         ][Info   ] Destroying Switch DockerNAT...
[09:41:03.314][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[09:41:03.517][HyperV         ][Debug  ] [destroy] took 00:00:00.9011738 to run
[09:41:03.518][Firewall       ][Info   ] Closing ports...
[09:41:03.518][Firewall       ][Info   ] Removing all existing rules...
[09:41:03.719][Firewall       ][Info   ] All existing rules are removed.
[09:41:03.719][Firewall       ][Info   ] Ports are closed
[09:41:03.719][HyperVGuids    ][Info   ] Removing GUIDs...
[09:41:03.719][HyperVGuids    ][Info   ] GUIDs removed
[09:41:03.719][HyperV         ][Info   ] Create
[09:41:03.719][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[09:41:03.734][HyperV         ][Info   ] Script started at 09:41:03.734
[09:41:03.750][HyperV         ][Info   ] Module loaded at 09:41:03.750
[09:41:03.781][HyperV         ][Info   ] Creating Switch: DockerNAT...
[09:41:05.165][HyperV         ][Info   ] Switch created.
[09:41:05.473][HyperV         ][Info   ] Set IP address on switch
[09:41:05.488][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[09:41:06.629][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[09:41:07.068][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual hard disks\MobyLinuxVM.vhdx
[09:41:07.482][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[09:41:07.654][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\mobylinux.iso
[09:41:08.305][HyperV         ][Info   ] Disabled Guest Service Interface
[09:41:08.317][HyperV         ][Info   ] Enabled Heartbeat
[09:41:08.404][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[09:41:08.416][HyperV         ][Info   ] Enabled Shutdown
[09:41:08.427][HyperV         ][Info   ] Enabled Time Synchronization
[09:41:08.480][HyperV         ][Info   ] Disabled VSS
[09:41:09.112][HyperV         ][Info   ] VM created.
[09:41:09.112][HyperV         ][Debug  ] [create] took 00:00:05.3932285 to run
[09:41:09.112][PowerMode      ][Info   ] Stop
[09:41:09.112][HyperV         ][Info   ] Stop
[09:41:09.113][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[09:41:09.122][HyperV         ][Info   ] Script started at 09:41:09.122
[09:41:09.131][HyperV         ][Info   ] Module loaded at 09:41:09.131
[09:41:09.154][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[09:41:09.154][HyperV         ][Debug  ] [stop] took 00:00:00.0419765 to run
[09:41:09.154][OptimizeDisk   ][Info   ] Optimize
[09:41:09.154][PowerShell     ][Info   ] Run script...
[09:41:10.550][Moby           ][Info   ] Stop
[09:41:10.554][HyperV         ][Info   ] Create
[09:41:10.554][HyperVGuids    ][Info   ] Installing GUIDs...
[09:41:10.554][PowerMode      ][Info   ] Start
[09:41:10.554][Firewall       ][Info   ] Removing all existing rules...
[09:41:10.555][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[09:41:10.563][HyperV         ][Info   ] Script started at 09:41:10.563
[09:41:10.568][HyperVGuids    ][Info   ] GUIDs installed
[09:41:10.576][HyperV         ][Info   ] Module loaded at 09:41:10.576
[09:41:10.847][Firewall       ][Info   ] All existing rules are removed.
[09:41:10.847][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[09:41:10.851][Firewall       ][Info   ] Opening ports for SMB...
[09:41:10.861][Firewall       ][Info   ] Ports are opened
[09:41:10.982][HyperV         ][Info   ] Using existing Switch: DockerNAT
[09:41:12.042][HyperV         ][Info   ] Using existing Switch IP address
[09:41:12.078][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[09:41:12.196][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[09:41:12.357][HyperV         ][Info   ] Disabled Guest Service Interface
[09:41:12.385][HyperV         ][Info   ] Enabled Heartbeat
[09:41:12.415][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[09:41:12.440][HyperV         ][Info   ] Enabled Shutdown
[09:41:12.467][HyperV         ][Info   ] Enabled Time Synchronization
[09:41:12.493][HyperV         ][Info   ] Disabled VSS
[09:41:12.623][HyperV         ][Info   ] VM created.
[09:41:12.623][HyperV         ][Debug  ] [create] took 00:00:02.0682614 to run
[09:41:12.623][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[09:41:12.644][Database       ][Info   ] Generating CA Cert Bundle
[09:41:12.672][Database       ][Info   ] CA Cert Bundle Generated
[09:41:12.692][DataKit        ][Info   ] Starting com.docker.db.exe 0.7.0-34-g6f04213 ...

[09:41:12.695][DataKit        ][Error  ] com.docker.db.exe: Failed to set up server socket listening on hyperv-connect://2e9f13ea-daa6-4c85-9e06-135e6bfc133e: Unix.Unix_error(Unix.ENETDOWN, "socket", "")

[09:41:12.695][DataKit        ][Info   ] com.docker.db.exe: internal error, uncaught exception:

[09:41:12.695][DataKit        ][Info   ]                    (Failure accept_forever)

[09:41:12.699][DataKit        ][Error  ] Process died
[09:41:17.647][PowerMode      ][Info   ] Stop
[09:41:17.647][HyperV         ][Info   ] Stop
[09:41:17.648][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[09:41:17.655][HyperV         ][Info   ] Script started at 09:41:17.655
[09:41:17.670][HyperV         ][Info   ] Module loaded at 09:41:17.670
[09:41:17.702][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[09:41:17.702][HyperV         ][Debug  ] [stop] took 00:00:00.0549831 to run
[09:41:17.702][OptimizeDisk   ][Info   ] Optimize
[09:41:17.702][PowerShell     ][Info   ] Run script...
[09:41:19.060][Moby           ][Info   ] Stop
[09:41:19.076][HyperV         ][Info   ] Destroy
[09:41:19.076][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[09:41:19.076][HyperV         ][Info   ] Script started at 09:41:19.076
[09:41:19.107][HyperV         ][Info   ] Module loaded at 09:41:19.107
[09:41:19.169][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[09:41:19.169][HyperV         ][Info   ] Destroying Switch DockerNAT...
[09:41:19.857][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[09:41:19.920][HyperV         ][Debug  ] [destroy] took 00:00:00.8439137 to run
[09:41:19.920][Firewall       ][Info   ] Closing ports...
[09:41:19.920][Firewall       ][Info   ] Removing all existing rules...
[09:41:20.141][Firewall       ][Info   ] All existing rules are removed.
[09:41:20.141][Firewall       ][Info   ] Ports are closed
[09:41:20.141][HyperVGuids    ][Info   ] Removing GUIDs...
[09:41:20.141][HyperVGuids    ][Info   ] GUIDs removed
[09:41:20.188][NamedPipeServer][Error  ] Unable to execute Start: The operation has timed out.    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 245
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[09:41:20.188][NamedPipeClient][Error  ] Unable to send Start: The operation has timed out.
[09:41:20.188][Notifications  ][Error  ] The operation has timed out.
[09:43:28.444][ErrorReportWindow][Info   ] Open logs
[09:46:52.618][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[09:46:52.618][NamedPipeClient][Info   ] Sending Version()...
[09:46:52.618][NamedPipeClient][Info   ] Sending Version()...
[09:46:52.618][NamedPipeClient][Info   ] Sending Version()...
[09:46:52.681][CrashReport    ][Warning] Unable to collect features settings: Could not find file 'C:\Users\fernando.guardiola\AppData\Roaming\Docker\features-overrides.json'.
[09:46:52.681][NamedPipeClient][Info   ] Sending Version()...
[09:46:53.611][NamedPipeClient][Info   ] Received response for Version
[09:46:53.611][NamedPipeClient][Info   ] Received response for Version
[09:46:53.611][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\fernando.guardiola\AppData\Local\Temp\uls2peru.equ\mobyLogs.tar)...
[09:46:53.611][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\fernando.guardiola\AppData\Local\Temp\uls2peru.equ\win_containers)...
[09:46:53.611][NamedPipeClient][Info   ] Received response for Version
[09:46:53.611][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[09:46:53.611][NamedPipeServer][Info   ] Version()
[09:46:53.611][NamedPipeClient][Info   ] Received response for Version
[09:46:53.611][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\fernando.guardiola\AppData\Local\Temp\uls2peru.equ\pcap.tar)...
[09:46:53.611][NamedPipeServer][Info   ] Version()
[09:46:53.611][NamedPipeServer][Info   ] Version done in 00:00:00.
[09:46:53.611][NamedPipeServer][Info   ] Version done in 00:00:00.
[09:46:53.611][NamedPipeServer][Info   ] Version()
[09:46:53.611][NamedPipeServer][Info   ] Version done in 00:00:00.
[09:46:53.611][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[09:46:53.611][NamedPipeServer][Info   ] Version()
[09:46:53.611][NamedPipeServer][Info   ] Version done in 00:00:00.
[09:46:53.611][NamedPipeServer][Info   ] GetDebugInfo()
[09:46:53.611][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\fernando.guardiola\AppData\Local\Temp\uls2peru.equ\win_containers)
[09:46:53.611][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\fernando.guardiola\AppData\Local\Temp\uls2peru.equ\pcap.tar)
[09:46:53.611][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[09:46:53.611][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.
[09:46:53.611][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\fernando.guardiola\AppData\Local\Temp\uls2peru.equ\mobyLogs.tar)
[09:46:53.611][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[09:46:53.768][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[09:46:53.768][HyperV         ][Warning] Unable to download logs: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual machine with name "MobyLinuxVM".
[09:46:53.768][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.1561916.
[09:46:58.620][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[09:46:58.619][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:05.0079187.
[09:47:07.871][NamedPipeServer][Info   ] GetDebugInfo done in 00:00:14.2593536.
[09:47:07.871][NamedPipeClient][Info   ] Received response for GetDebugInfo
[09:47:08.020][CrashReport    ][Info   ] Uploading diagnostics...
[09:47:10.886][CrashReport    ][Info   ] Diagnostics successfully uploaded (785297BA-5D89-4841-90B0-9052C1FE795C/2017-12-20_09-46-52)
[09:47:10.906][GUI            ][Info   ] Sending Bugsnag report a7187d00-81ad-4467-92c9-ef04127fad9b...
[09:47:12.017][GUI            ][Info   ] Bugsnag report a7187d00-81ad-4467-92c9-ef04127fad9b sent

**Comment by jasonbivins** [comment]
Hi @ferguardiola   Are you able to start the Docker for Windows service?

**Comment by ferguardiola** [comment]
Hello, yes the services for windows is up and runing..

I've tried with the edge version, the stable, from de poweshell manually..  and anything works

13:10:44.368][VpnKit         ][Info   ] vpnkit.exe: reconnected transport layer

[13:10:44.384][VpnKit         ][Info   ] vpnkit.exe: remove connection limit

[13:10:44.415][NamedPipeServer][Error  ] Unable to execute Restart: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID 52FE79B7-E4BA-4CC6-AEF3-5A8FB4119158)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID 52FE79B7-E4BA-4CC6-AEF3-5A8FB4119158).
at Start-MobyLinuxVM, <No file>: line 291
at <ScriptBlock>, <No file>: line 386    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 245
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 181
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[13:10:44.415][NamedPipeClient][Error  ] Unable to send Restart: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID 52FE79B7-E4BA-4CC6-AEF3-5A8FB4119158)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID 52FE79B7-E4BA-4CC6-AEF3-5A8FB4119158).
at Start-MobyLinuxVM, <No file>: line 291
at <ScriptBlock>, <No file>: line 386
[13:10:44.415][Notifications  ][Error  ] Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID 52FE79B7-E4BA-4CC6-AEF3-5A8FB4119158)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID 52FE79B7-E4BA-4CC6-AEF3-5A8FB4119158).
at Start-MobyLinuxVM, <No file>: line 291
at <ScriptBlock>, <No file>: line 386
[13:10:44.431][VpnKit         ][Info   ] vpnkit.exe: allowing binds to any IP addresses

**Comment by ferguardiola** [comment]
Manually from powershell:

C:\Windows\system32>powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create
Script started at 13:19:44.524
Module loaded at 13:19:45.837
Creating Switch: DockerNAT...
Switch created.
Set IP address on switch
ISO file at .\mobylinux.iso does not exist
At C:\Program Files\Docker\Docker\resources\MobyLinux.ps1:376 char:5
+     throw "$args"
+     ~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (ISO file at .\m... does not exist:String) [], RuntimeException
    + FullyQualifiedErrorId : ISO file at .\mobylinux.iso does not exist


C:\Windows\system32>

**Comment by duprefm** [comment]
PS C:\WINDOWS\system32> powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1
" -create
Script started at 22:57:07.559
Module loaded at 22:57:11.821
Creating Switch: DockerNAT...
Hyper-V\Get-VMNetworkAdapter : Hyper-V n'a trouvé aucun commutateur virtuel portant le nom « DockerNAT ».
Au caractère C:\Program Files\Docker\Docker\resources\MobyLinux.ps1:117 : 25
+ ... etAdapter = Hyper-V\Get-VMNetworkAdapter -ManagementOS -SwitchName $S ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (DockerNAT:String) [Get-VMNetworkAdapter], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVMNetworkAdapter
