### ISSUE TITLE
Installing update keeps hanging

### ISSUE THREAD

**Issue by AlfredSchreuder** [docker/for-win#1453]
Expected behavior
Install new version of docker

Actual behavior
Hangs when installing

Information
I am on Windows 10 Pro.
I have started to dread when I get the update window from docker.
Instead of updating via that I just download the installer but it seems even that hangs.

![docker](https://user-images.githubusercontent.com/16957584/34249773-33c03d0a-e63b-11e7-875d-6681cc0646b6.PNG)

It's been like that for the past 10m. 
I was able to cancel te installation, but cant uninstall via apps because docker doenst show there.

Steps to reproduce the behavior
Try to update a new version of docker on windows

**Comment by svassaux** [comment]
same for me !

**Comment by svassaux** [comment]
on windows 10 with last updates installed, when I run the last docker ce stable installer : 

Microsoft Windows [versão 10.0.16299.125]
(c) 2017 Microsoft Corporation. Todos os direitos reservados.

D:\Transit>"Docker for Windows Installer.exe"

D:\Transit>[17:56:36.510] [InstallHandler] No d4w installation found
[17:56:36.517] [InstallHandler] Using embedded package
[17:56:36.677] [InstallWorkflow] Using package: res:d4w
[17:56:36.679] [InstallWorkflow] Downloading
[17:56:36.985] [InstallWorkflow] Exracting manifest
[17:56:37.021] [InstallWorkflow] Checking prerequisites
[17:56:37.056] [InstallWorkflow] Unpacking artifacts
[17:56:47.306] [InstallWorkflow] Deploying component LightweightInstaller.CreateGroupAction
[17:56:47.387] [InstallWorkflow] Deploying component LightweightInstaller.AddToGroupAction
[17:56:47.471] [InstallWorkflow] Deploying component LightweightInstaller.ServiceAction
[17:56:47.896] [InstallWorkflow] Deploying component LightweightInstaller.ShortcutAction
[17:56:47.941] [InstallWorkflow] Deploying component LightweightInstaller.ShortcutAction
[17:56:47.958] [InstallWorkflow] Component LightweightInstaller.ShortcutAction failed
Exception type: System.IO.FileNotFoundException, Exception message: O sistema não pode encontrar o arquivo especificado. (Exceção de HRESULT: 0x80070002), StackTrace:
   em System.Runtime.InteropServices.ComTypes.IPersistFile.Save(String pszFileName, Boolean fRemember)
   em LightweightInstaller.ShortcutAction.DoAsync(CancellationToken cancelToken)
   em LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__19.MoveNext()
[17:56:47.960] [InstallWorkflow] Installation failed
Exception type: System.IO.FileNotFoundException, Exception message: O sistema não pode encontrar o arquivo especificado. (Exceção de HRESULT: 0x80070002), StackTrace:
   em System.Runtime.InteropServices.ComTypes.IPersistFile.Save(String pszFileName, Boolean fRemember)
   em LightweightInstaller.ShortcutAction.DoAsync(CancellationToken cancelToken)
   em LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__19.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em LightweightInstaller.InstallWorkflow.<ProcessAsync>d__18.MoveNext()

Exceção Sem Tratamento: System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em LightweightInstaller.UnpackArtifactsStep.<UndoAsync>d__24.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em LightweightInstaller.InstallWorkflow.<ProcessAsync>d__18.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em LightweightInstaller.Wizard.<StartStateMachine>d__10.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em LightweightInstaller.Wizard.<OnClosing>d__14.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   em System.Windows.Threading.DispatcherOperation.InvokeImpl()
   em MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Windows.Threading.DispatcherOperation.Invoke()
   em System.Windows.Threading.Dispatcher.ProcessQueue()
   em System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   em MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   em MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   em System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   em MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   em MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   em System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   em System.Windows.Application.RunDispatcher(Object ignore)
   em System.Windows.Application.RunInternal(Window window)
   em LightweightInstaller.Cmd.InstallHandler.Run(String[] args)
   em LightweightInstaller.Program.Main(String[] args)

**Comment by mutemule** [comment]
I'm running into the same problem with the Docker for Windows 17.09.1-ce-win42 installer:

```
C:\Users\foo\Downloads> '.\Docker for Windows Installer.exe'
[05:45:02.848] [InstallHandler] No d4w installation found
[05:45:02.851] [InstallHandler] Using embedded package
[05:45:02.971] [InstallWorkflow] Using package: res:d4w
[05:45:02.972] [InstallWorkflow] Downloading
[05:45:03.522] [InstallWorkflow] Exracting manifest
[05:45:03.631] [InstallWorkflow] Checking prerequisites
[05:45:03.662] [InstallWorkflow] Unpacking artifacts
[05:45:09.524] [InstallWorkflow] Deploying component LightweightInstaller.CreateGroupAction
[05:45:09.578] [InstallWorkflow] Deploying component LightweightInstaller.AddToGroupAction
[05:45:09.640] [InstallWorkflow] Deploying component LightweightInstaller.ServiceAction
[05:45:10.036] [InstallWorkflow] Deploying component LightweightInstaller.ShortcutAction
[05:45:10.135] [InstallWorkflow] Deploying component LightweightInstaller.ShortcutAction
[05:45:10.144] [InstallWorkflow] Component LightweightInstaller.ShortcutAction failed
Exception type: System.IO.FileNotFoundException, Exception message: The system cannot find the file specified. (Exception from HRESULT: 0x80070002), StackTrace:
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Save(String pszFileName, Boolean fRemember)
   at LightweightInstaller.ShortcutAction.DoAsync(CancellationToken cancelToken)
   at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__19.MoveNext()
[05:45:10.147] [InstallWorkflow] Installation failed
Exception type: System.IO.FileNotFoundException, Exception message: The system cannot find the file specified. (Exception from HRESULT: 0x80070002), StackTrace:
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Save(String pszFileName, Boolean fRemember)
   at LightweightInstaller.ShortcutAction.DoAsync(CancellationToken cancelToken)
   at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__18.MoveNext()
```

At this point, the installer looks like this:

![image](https://user-images.githubusercontent.com/305329/34379451-542a1dd0-eac9-11e7-9c74-194f0c68ed14.png)

Upon exiting the installer, I'm asked to confirm, and shortly afterwards, it crashes with, `LightweightInstaller has stopped working`:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at LightweightInstaller.UnpackArtifactsStep.<UndoAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.Wizard.<StartStateMachine>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.Wizard.<OnClosing>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at LightweightInstaller.Cmd.InstallHandler.Run(String[] args)
   at LightweightInstaller.Program.Main(String[] args)
```

I've tried:

* confirming I'm on a supported version of Windows (Windows 10 Pro, build 16299)
* disabling and re-enabling Hyper-V
* checking .Net to ensure it's installed properly (`sfc /scannow`, seems to be)
* using older installers (17.09.0-ce-win33 and 17.09.0-ce-win32)
* using [ProcessMonitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to try to figure out what file it is that doesn't exist, but there are too many entries right now

I'm at a bit of a loss, but I don't seem to be able to install Docker for Windows at all right now.

**Comment by svassaux** [comment]
I've tried many different things, updating registry keys, analyzing the process, removing everything and starting all over again...
Docker guys, please update the installer !

**Comment by Lucas-C** [comment]
Also reported here: https://github.com/docker/for-win/issues/1417

**Comment by Lucas-C** [comment]
Like @svassaux I also gave a try at ProcessMonitor to figure out what is happening.
The only thing I found is that before hanging, the last thing the installer process does is to create a new thread.

**Comment by AlfredSchreuder** [comment]
Disabling antivirus worked for me!

**Comment by denzuko** [comment]
> Disabling antivirus worked for me!

Sounds like there's a process lock involved like the one used by uac and one should use start to use the Microsoft Application Compatibility Toolkit. Since it enables one to directly disable UAC for any application that are decided to trust. The compatibility fix one needs to select is RunAsInvoker.

**Comment by MohMehrnia** [comment]
yes, Disabling Anti Virus Work For Me
