### ISSUE TITLE
Docker no longer starting after recent Win-10 update

### ISSUE THREAD

**Issue by mmisztal1980** [docker/for-win#1462]
Recently, I've had a Win-10 update. The current OS version is:
**Version	10.0.16299 Build 16299**

### Expected behavior

Docker should start.

### Actual behavior

Docker times out. An exception stack-trace is presented:
```
Docker command did not complete within the allowed timeout. Output: 
   at Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 152
   at Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\MobyCommand.cs:line 49
   at Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 197
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 168
   at Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\SambaShare.cs:line 65
   at Docker.Backend.BackendServer.<Run>b__6_10(Object[] args) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\BackendServer.cs:line 52
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

It is possible to reset docker afterwards, and it then starts normally.

### Information

DiagnosticId: `5239E3DB-D0D2-47AE-B158-5D03C5A0619A/2017-12-25_22-15-52`

**Comment by mmisztal1980** [comment]
I believe I've managed to resolve this using the following method:

##Solution:
- Uninstall Docker for Windows CE
- Remove the Hyper-V feature
- Reboot
- Install the Hyper-V feature
- Install Docker for Windows CE
- Let Docker copy settings from the old VM it has detected  (I believe this is optional).

Docker seems to be starting normally.
