### ISSUE TITLE
Unable to write to the database. Exit code: 1 On Win10 Pro x64

### ISSUE THREAD

**Issue by universeroc** [docker/for-win#1466]
### Expected behavior
Start normally
### Actual behavior
Unable to write to the database. Exit code: 1
### Information

  After installation, click docker for windows to start it.

### Steps to reproduce the behavior

  1. open start menu
  2. click docker for windows

Unable to write to the database. Exit code: 1
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 245
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

raw log in the attachment
[log.txt](https://github.com/docker/for-win/files/1589147/log.txt)

**Comment by universeroc** [comment]
After Resetting Win10, reinstall Docker, it works. Although I lost most apps, Docker is running. It's the best news to me.
