### ISSUE TITLE
Unable to create...The computer '...' could not be resolved

### ISSUE THREAD

**Issue by briwilcox** [docker/for-win#147]
### Expected behavior

Docker daemon with Hyper-V starts at startup
### Actual behavior

Docker fails to start
### Information

A diagnostic was uploaded with id: EA9197C6-EA7F-4D1B-B97A-9C7C8602B5FF/2016-10-14_14-15-00

Below I've replaced my actual computer name with (computer-name)

[14:07:10.373][Program        ][Info   ] Version: 1.12.1-stable
[14:07:10.457][Program        ][Info   ] Starting on: 10/14/2016 2:07:10 PM
[14:07:10.467][Program        ][Info   ] Resources: C:\Program Files\Docker\Docker\Resources
[14:07:10.477][Program        ][Info   ] OS: Windows 10 Enterprise
[14:07:10.495][Program        ][Info   ] Edition: Enterprise
[14:07:10.509][Program        ][Info   ] Id: 1607
[14:07:10.521][Program        ][Info   ] Build: 14393
[14:07:10.548][Program        ][Info   ] BuildLabName: 14393.321.amd64fre.rs1_release_inmarket.161004-2338
[14:07:10.589][Program        ][Info   ] Sha1: 995236d98308333f27e3a36505dd761ac9c843f3
[14:07:10.632][Program        ][Info   ] You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[14:07:11.597][TrackingStatus ][Info   ] Crash report and usage statistics are enabled
[14:07:11.629][Analytics      ][Info   ] Usage Statistic: appLaunched
[14:07:11.745][NamedPipeClient][Info   ] Sending Version()...
[14:07:11.772][NamedPipeClient][Info   ] Received response for Version
[14:07:11.779][Analytics      ][Info   ] Usage Statistic: heartbeat
[14:07:11.759][NamedPipeServer][Info   ] Version done.
[14:07:12.523][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[14:07:12.526][Updater        ][Info   ] Checking for updates on channel Stable...
[14:07:12.534][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[14:07:12.545][HyperV         ][Info   ] Stop
[14:07:12.567][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[14:07:12.731][Updater        ][Info   ] Local build 7135 is as good as the remote 7135 on channel Stable
[14:07:17.234][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[14:07:17.258][HyperVGuids    ][Info   ] Installing GUIDs...
[14:07:17.269][HyperVGuids    ][Info   ] GUIDs installed
[14:07:17.280][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[14:07:18.435][Firewall       ][Info   ] Ports are opened
[14:07:18.441][HyperV         ][Info   ] Create
[14:07:18.449][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[14:07:27.545][HyperV         ][Info   ] Creating Switch: DockerNAT...
[14:07:41.909][HyperV         ][Info   ] Hyper-V is running
[14:07:41.909][HyperV         ][Info   ] Create
[14:07:41.909][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[14:07:51.039][HyperV         ][Info   ] Creating Switch: DockerNAT...
**[14:08:04.556][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The computer '(computer-name)' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at <ScriptBlock>, <No file>: line 340    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[14:08:04.556][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The computer '(computer-name)' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at <ScriptBlock>, <No file>: line 340
[14:08:04.571][Notifications  ][Error  ] Unable to create: The computer '(computer-name)' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at <ScriptBlock>, <No file>: line 340**
[14:08:11.551][ErrorReportWindow][Info   ] Open logs
[14:12:20.347][FeedbackSettings][Info   ] Open logs
### Steps to reproduce the behavior
1. Boot Windows

**Comment by joshuaavalon** [comment]
Yes, I am facing the same problem. It works the time when I install it  several weeks ago. Today I want to start learning about Docker and I get the same error.

**Comment by simonferquel** [comment]
Can you upload a diagnostic so we can understand the state of your machine (Settings / Diagnose & Feedback / Upload a diagnostic) ?

**Comment by dgageot** [comment]
Hi @briwilcox You might want to try the Beta channel instead of the stable one because it contains more recent fixes: https://docs.docker.com/docker-for-windows/

**Comment by briwilcox** [comment]
@simonferquel A diagnostic was uploaded with id: EA9197C6-EA7F-4D1B-B97A-9C7C8602B5FF/2016-10-14_14-15-00

**Comment by briwilcox** [comment]
@dgageot I tried docker beta. Fails to start for a different reason:

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer '024156360653' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at New-Switch, <No file>: line 123
at <ScriptBlock>, <No file>: line 337
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

I've uploaded a separate crash report @ **EA9197C6-EA7F-4D1B-B97A-9C7C8602B5FF/2016-10-19_16-00-39** for the beta installation.

**Comment by casperdcl** [comment]
Similar issue here:

25749FEA-4204-443F-B987-F081E680E169/2016-10-22_13-25-05

My PC was win 8.1, upgraded to 10+hyper V and has zonealarm. I disabled zonealarm completely during installation and startup but docker still fails to start.

**Comment by briwilcox** [comment]
Just wanted to add this is still happening on Docker v 1.12.3-beta29.2 (8290)

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer (computer name) could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at New-Switch, <No file>: line 123
at <ScriptBlock>, <No file>: line 362
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

Crash report here:
EA9197C6-EA7F-4D1B-B97A-9C7C8602B5FF/2016-10-27_11-24-57

**Comment by briwilcox** [comment]
I can stop reporting these if you want but seeing this in the latest beta update: 1.12.3-beta29.3 (8418):

EA9197C6-EA7F-4D1B-B97A-9C7C8602B5FF/2016-11-02_14-26-39

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer '(Computer Name)' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at New-Switch, <No file>: line 123
at <ScriptBlock>, <No file>: line 362
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by tarunendra** [comment]
Hi, I'm also getting the same issues and below is crash report.

38527887-88C4-47EC-8D21-D98A92197C62/2016-11-08_12-53-42

**Comment by fishhead108** [comment]
Temporary fix: write to C:\Windows\System32\drivers\etc\hosts
ip address    computer name

**Comment by roolebo** [comment]
@fishhead108 thanks! the workaround works.

**Comment by daniel-onisoru** [comment]
The workaround with hosts didn't worked for me.
I noticed that I have a network adapter called Broken Docker Adapter (20161215T1111536705Z) (1) .. that for some reason exists.

Disabling that did the trick.

**Comment by Phoenyx33** [comment]
For me, no broken adapter, hosts didn't work, trying Beta/Experimental didn't work. <sigh>
Added a new Issue with Diagnostic as I found a new glitch to this. It seems to think the mobylinux.iso
is invalid and tells me to use a "valid Boot Media". Issue #402 with attached diagnostic number.

**Comment by wouterds** [comment]
Same issue. Tried uninstalling it, re-installing it, installing the beta version, .. Since the last update of Docker it doesn't start anymore for me.

Windows 10 Pro.

3E50F123-046F-4158-A67E-D4BCD708C35C/2017-01-21_19-25-41

**Comment by robcthegeek** [comment]
Same issue here - Docker fails to start and it reports that it can't my machine name can't be resolved.

:boom: **Crash Report:** `93F4B946-F34A-4EBF-AFC6-B3F6151F3464/2017-01-23_09-26-59`

Tried a complete re-install, no dice.

Let me know if there's anything you want me to try/guinea pig. I need to get this up and running ASAP! 😄

**Comment by casperdcl** [comment]
Personally there was no way for me to get around this other than leaving ZoneAlarm permanently uninstalled. If anyone has zonealarm + docker + win10 all working harmoniously do let me know.

**Comment by zezke** [comment]
I ran into the same issue after installing the latest update. However @fishhead108's suggestion to edit the hosts files fixed my issue.

**Comment by djmarland** [comment]
I also encountered the same problem after updating to 1.13. 
To find my loopback address I typed `Ping Loopback` into Powershell. It turns out my loopback address is in IPv6, so *that* was what I added to the hosts file.

`::1 COMPUTERNAME`

Seems to be working now

**Comment by rneugeba** [comment]
I've changed the title to better reflect the issue.

On our systems we do not have the computer name in `C:\Windows\System32\drivers\etc\hosts` and don't encounter the issue so I'm a little at a loss here why this fails for some users. However, the workaround seems easy and straight forward.

**Comment by nsgundy** [comment]
Ran into the same issue today. Had a different issue first after updating to the latest version 17.03.0-ce-win1 (10296) and followed a recommendation to reset the network adapters via `Settings->Network&Internet > Status > Network Reset`. After rebooting and trying to start Docker again, I am presented with the issue here: `Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer 'COMPUTERNAME' could not be resolved. Make sure you typed the machine name correctly and that you have network access.`

**Comment by dnunes** [comment]
I just ran into the same issue.

For me, simply **disabling the vmWare Network Adapters** (I had two) did the trick. Docker may have used the wrong one while trying to run or something?

**Comment by vitr** [comment]
I just had the same error, in my case, the solution was about renaming my computer
![image](https://cloud.githubusercontent.com/assets/2770290/24281467/a47b5290-10a4-11e7-8692-d57144778b87.png)
See my 'Full Computer Name' was a way longer than **16** chars and docker shorted it to just **16** chars.
After renaming my computer to a shorter name the issue has gone.

**Comment by nsgundy** [comment]
A fix would be appreciated... I for one have no ability to change my computer name (domain workstation).

**Comment by jasonbivins** [comment]
@briwilcox 

Do you any additional virtual switches in your Hyper-V or do yo only have the DockerNat  ?

**Comment by Phoenyx33** [comment]
Just the dockernat for me.



Sent from my Sprint Samsung Galaxy S® 6.


-------- Original message --------

**Comment by AdamTakeow** [comment]
@vitr 
The computer renaming method did the trick for me! Thanks!

**Comment by jasonbivins** [comment]
I tested this with 29 character computer name a few times in the latest Edge (17.06 rc5) build and haven't had any issues with startup or pulling images.  If anyone is still seeing this issue, please let us know.

**Comment by llaslo** [comment]
I had the same problem running on a Windows 10 Pro VM in VMWare Fusion Pro 8.  The issue was that it was truncating the computer name.  My computer name was: `IT100012-Win10VM` but Docker was giving an error resolving `IT100012-Win10V`.  I worked around this by adding the following line to my host file:
```::1    localhost IT100012-Win10V```

**Comment by jasonbivins** [comment]
closing - pinata issue was closed and I can no longer repro this as of 17.09 CE

**Comment by TijmenW** [comment]
@jasonbivins 
I have the same problem, should I open a new issue?

**Comment by ddwagner** [comment]
This is still happening to me as well. Updated to latest docker desktop (2.0.03) today and all of a sudden it couldn't resolve the computer name. Fixed by shortening the name. New issue time?

**Comment by robert-mccarter** [comment]
Like @vitr  renaming my computer worked for me (although I completely get that not everybody can do that).  I had a very long name and Docker was cutting off the name, so my guess it the truncated name didn't work.

**Comment by TijmenW** [comment]
Because of university policy, I'm not allowed to rename my computer. Is there another workaround?

**Comment by robert-mccarter** [comment]
I'm not sure @TijmenW, the only thing I can think of is that you could grab the truncated name Docker is trying to use, and then add that into your hosts file mapping it to the full name, or localhost.  No idea if that will work though.

**Comment by CaffeinatedAndroid** [comment]
Just to echo others here, I had this problem. Renaming my computer to 15 chars or less worked for me. Would be good to have this automatically detected and fixed, rather than requiring people to edit a hosts file.

**Comment by TijmenW** [comment]
@CaffeinatedAndroid It bothered me too, so I opened a issue. #4192

**Comment by JonnyD07** [comment]
I had this same issue. I had VirtualBox installed on my PC, which I believe was starting up at the same time as Docker. Uninstalling VirtualBox fixed the issue for me.
