### ISSUE TITLE
My docker failed to start with an error, after uploading the crash report I was given this diagnostic id  53AC4506-F901-4C36-A190-C0657966D849/2018-01-05_10-16-14

### ISSUE THREAD

**Issue by nospaniol** [docker/for-win#1491]
The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Docker.Core.Cmd.StartProcessAndCaptureOutput(Int32 timeout, Process process, String stdin) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\Cmd.cs:line 91
   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 45
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 201
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 79
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

diagnostic Id= 53AC4506-F901-4C36-A190-C0657966D849/2018-01-05_10-16-14

**Comment by rorygilfillan** [comment]
Diagnostic: 830D4A61-9626-4EFE-9ECE-CE56DFF542CE/20180807150433
I'm getting this error when I tried to restart:
The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Docker.Core.Cmd.StartProcessAndCaptureOutput(Int32 timeout, Process process, String stdin) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\Cmd.cs:line 91
   at Docker.Actions.WarnAufsDeprecatedIfAufsUsed() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 283
   at Docker.Actions.<>c__DisplayClass22_0.<RestartVm>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 210
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
