### ISSUE TITLE
docker for windows won't start in allotted time

### ISSUE THREAD

**Issue by ormico** [docker/for-win#1499]
I have a Windows 10 Pro workstation that acts as a Build Server agent. I have Docker for Windows latest version installed.

### Expected behavior
1) Docker build tasks succeed.
2) When logging on as teamcityagent, Docker for Windows will start without error.

### Actual behavior
It works fine if I log in as my domain administrator user but is currently not completing startup if I log in as the user the build agent runs under. This user, teamcityagent, is not an administrator but is in the power users and docker-users groups.

In addition to not starting when I log in as teamcityagent, the build tasks are also failing with the following error.

[ZurichSolution\docker-compose.dcproj] DockerCleanWorkspace (1s)
[12:17:57]	[DockerCleanWorkspace] CleanWorkspace (1s)
[12:17:57]	[CleanWorkspace] docker-compose  -f "C:\BuildAgent\work\8153772692f92b8\ZurichSolution\docker-compose.yml" -f "C:\BuildAgent\work\8153772692f92b8\ZurichSolution\docker-compose.override.yml" -f "C:\BuildAgent\work\8153772692f92b8\ZurichSolution\obj\Docker\docker-compose.vs.release.partial.g.yml" -p dockercompose16002480030657872379 kill
[12:17:59]	[CleanWorkspace] Windows named pipe error: The system cannot find the file specified. (code: 2)
[12:17:59]	[CleanWorkspace] C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(394, 5): Visual Studio Container Tools requires Docker to be running before building, debugging or running a containerized project.

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
12B93BBD-B5E3-428D-AFCE-6A3D51735907/2018-01-08_12-51-03

This Windows 10 Pro is a VM running under Hyper-V and is a member of our domain.

This was working fine and stopped. Previously I had a similar problem. That time, I worked with the workstation for a while and it started working. I thought at the time that the last change I made (turning off windows firewall) had fixed the issue but that change is still in place and it is broken again. 

I suspect that if I can get Docker to start that the issue will go away for a while, possibly until the workstation reboots, but I'm not sure.

Can you tell me what is preventing docker from starting and what I can do to fix it?

**Comment by ormico** [comment]
need to amend this.
its not starting when I log in as teamcityagent or myself. I thought it was starting when I logged in as myself, but it is not. Either I was mistaken or it stopped.

**Comment by ormico** [comment]
this error appears in the log a lot
[13:30:45.747][ApiProxy       ][Info   ] Failed to connect to the database open \\.\pipe\dockerDataBase: The system cannot find the file specified.

**Comment by ormico** [comment]
logged in as myself I
1) opened Services and restarted Docker for Windows Service.
2) opened Docker for Windows settings from System Tray, selected the Reset tab, and clicked Restart Docker.

The icon on the bottom left changed Green and said that docker was started.

However, when i re-ran the build from Team city, I got a different error in the build log:
```
[ZurichSolution\docker-compose.dcproj] DockerCleanWorkspace (1s)
[13:46:44]	[DockerCleanWorkspace] CleanWorkspace (1s)
[13:46:44]	[CleanWorkspace] docker-compose  -f "C:\BuildAgent\work\8153772692f92b8\ZurichSolution\docker-compose.yml" -f "C:\BuildAgent\work\8153772692f92b8\ZurichSolution\docker-compose.override.yml" -f "C:\BuildAgent\work\8153772692f92b8\ZurichSolution\obj\Docker\docker-compose.vs.release.partial.g.yml" -p dockercompose16002480030657872379 kill
[13:46:45]	[CleanWorkspace] Windows named pipe error: Access is denied. (code: 5)
[13:46:45]	[CleanWorkspace] C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(394, 5): error MSB4018: The "CleanWorkspace" task failed unexpectedly.
Microsoft.Docker.Utilities.CommandLineClientException: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/version: open //./pipe/docker_engine: Access is denied. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running..

For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting ---> Microsoft.Docker.Utilities.CommandLineClientException: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/version: open //./pipe/docker_engine: Access is denied. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Docker.DockerClient.<ExecuteAsync>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Docker.DockerClient.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Docker.DockerClientExtensions.<GetServerOperatingSystemAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Docker.Prerequisites.DockerTargetOSCheckPrerequisite.<EvaluateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Docker.Prerequisites.DockerCompositePrerequisite.<EvaluateAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Docker.BuildTasks.DockerBuildTask.<HandleExceptionAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Docker.BuildTasks.DockerBuildTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**Comment by ormico** [comment]
2nd build, error changed back to first error

**Comment by ormico** [comment]
ok, I had it working for a minute
Logged into windows over RDP as teamcityagent.
Waited for Docker to fail to start.
Opened Docker for Windows from system tray.
Waited for it to pop the Send Crash report window. Clicked OK to send on first one.
After it sent the first one it went to the 2nd one. Clicked Close (if you don't it will just keep sending crash reports forever).
Opened Reset Tab.
Clicked Restart Docker.
Waited for Docker to Restart.

on TeamCity dashboard, re-ran build.
At first it was working. It built the container image, then half way through pushing the container image to the registry it stopped working.
```
Step 10/10: Push Containers to Azure Registry (PowerShell) (46s)
[14:16:56]	[Step 10/10] PowerShell Executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
[14:16:56]	[Step 10/10] Working directory: C:\BuildAgent\work\8153772692f92b8
[14:16:56]	[Step 10/10] Command: C:\Windows\sysnative\WindowsPowerShell\v1.0\powershell.exe
[14:16:56]	[Step 10/10] PowerShell arguments: -NoProfile, -NonInteractive, -ExecutionPolicy, ByPass, -File, C:\BuildAgent\temp\buildTmp\powershell2545010920815193622.ps1
[14:16:57]	[Step 10/10] The push refers to a repository [lbaware.azurecr.io/lbaware.switzerland.zurich.authserver]
[14:16:57]	[Step 10/10] 935752c31511: Preparing
[14:16:57]	[Step 10/10] db8101313087: Preparing
[14:16:57]	[Step 10/10] a6f0db82af58: Preparing
[14:16:57]	[Step 10/10] 03a2d35de712: Preparing
[14:16:57]	[Step 10/10] 3abbdf53e460: Preparing
[14:16:57]	[Step 10/10] 7f091d9051a0: Preparing
[14:16:57]	[Step 10/10] e27a10675c56: Preparing
[14:16:57]	[Step 10/10] 7f091d9051a0: Waiting
[14:16:57]	[Step 10/10] e27a10675c56: Waiting
[14:17:00]	[Step 10/10] db8101313087: Pushed
[14:17:00]	[Step 10/10] 3abbdf53e460: Pushed
[14:17:02]	[Step 10/10] e27a10675c56: Layer already exists
[14:17:30]	[Step 10/10] 935752c31511: Pushed
[14:17:35]	[Step 10/10] 7f091d9051a0: Pushed
[14:17:41]	[Step 10/10] unexpected EOF
[14:17:41]	[Step 10/10] error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/images/lbaware.azurecr.io/lbaware.switzerland.zurich.authserver/push?tag=latest: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
[14:17:41]	[Step 10/10] error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/images/lbaware.switzerland.zurich.website/tag?repo=lbaware.azurecr.io%2Flbaware.switzerland.zurich.website&tag=1.0.0.194: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
[14:17:42]	[Step 10/10] error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/images/lbaware.switzerland.zurich.website/tag?repo=lbaware.azurecr.io%2Flbaware.switzerland.zurich.website&tag=latest: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
[14:17:42]	[Step 10/10] error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/images/lbaware.azurecr.io/lbaware.switzerland.zurich.website/push?tag=1.0.0.194: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
[14:17:42]	[Step 10/10] error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/images/lbaware.azurecr.io/lbaware.switzerland.zurich.website/push?tag=latest: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```
really frustrating.

**Comment by ormico** [comment]
re-ran build and it is back to erroring when building image.

uploaded a new crash report:
4B541CA8-9FD4-40FB-BB08-59962D50B12C/2018-01-08_14-28-45

Performed the Restart Docker step again.
Re-ran TeamCity Build.
Build succeeded in building image and pushing it to registry.

Logged out of Windows RDP and re-ran build again.
Build failed at building image. same error.

Logged back into Windows. Repeated Restart Docker steps.
Re-Ran TeamCity build.
I'm currently waiting for that to complete.

I don't really know why this started happening. It was working for quite a while.
I noticed on Thu, 4 Jan this workstation installed "January 3, 2018—KB4056892 (OS Build 16299.192)". I don't know if it was working on Friday or stopped working over the weekend or if this update is related or not.

I'm going to try and disconnect from the RDP without logging out and see if the builds keep working, but I could really use some help on this.

Also, is there any guidance on setting up a Windows build server using Docker for Windows building Linux containers for ASP.NET Core 2.0?

Things I'm considering:
1) uninstalling and re-installing Docker for Windows as teamcityagent instead of under my account initially.
2) making teamcityagent a local admin. In the past I had a policy to not do this because it can cause other issues but I'm really banging my head against the wall here.

**Comment by ormico** [comment]
Saw this in the output I pasted above: "In the default daemon configuration on Windows, the docker client must be run elevated to connect." 
This is confusing to me. I have never had to run the client in an elevated prompt before. I'm not sure I understand what this is telling me.
When searching for this error I found this
https://github.com/moby/moby/pull/27394
But after reading it, I still don't know what it is talking about. Going to find the Quick Start guide now.
I have not knowingly changed or customized the daemon and I do not know if docker is supposed to be using named pipes or not.

**Comment by JohPa8696** [comment]
I'm having the same issue. Have you managed to find a workaround for this, @ormico?

**Comment by rn** [comment]
@ormico we don't support running Docker for Windows inside Windows 10 VM. See https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios We used to use Windows 10 VMs in CI and had a lot of issues

Basically we have little visibility of how the VM is configured, what else is happening on the host etc. making it very hard triage. So I'm closing this issue.
