### ISSUE TITLE
Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.

### ISSUE THREAD

**Issue by sampathmende** [docker/for-win#1503]
Hello,
After installing docker on windows 10, and try to start it i got the following error.

### Expected behavior
Docker should run without any issues.

### Actual behavior
Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.
   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 201
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 79
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
           Diagnostic ID::   B999BE27-8101-474F-B488-CA8CC70894F1/2018-01-09_15-53-54
  - a reproducible case if this is a bug, Dockerfiles FTW
      Docker not strating up
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
            Windows 10 Pro
            version : 1709
            OS build :16299.125
Docker version ::
Version 17.09.1-ce-win42 (14687)
Channel: stable
3176a6a

### Steps to reproduce the behavior

  1. ...After installing docker on windows 10, and try to start it i got the following error.
  2. ...

**Comment by FRSgit** [comment]
Check out issue #1505 - for me changing system's PATH variable and restarting console (few times) fixed the problem.

**Comment by sampathmende** [comment]
i checked the path variable ,but everything looks fine. but the above issue there.

**Comment by sampathmende** [comment]
Now I installed oracle vm and docker toolbox and run the docker build for jackhammer
 Its giving error while installing jdk 8 
dpkg error processing  oracle-java8-installer  (--configure)
sub process installed post installation script returned error exit status 1
Error were encountered while processing oracle-java8-installer
sub process /usr/bin/dpkg  returned an error code 1
Error service web failed to build 
the command  bin/sh -c echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \rm -rf /var/cache/oracle-jdk8-installer returned non zero code 100

**Comment by sampathmende** [comment]
closed
