### ISSUE TITLE
anic: runtime error: invalid memory address or nil pointer dereference when any docker-machine command is run

### ISSUE THREAD

**Issue by echarrod** [docker/for-win#1504]
### Expected behavior
When running a docker-machine command, e.g. `docker-machine ls`, I expect them to work as expected
### Actual behavior
```
$ docker-machine ls
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x7adc03]

goroutine 1 [running]:
github.com/docker/machine/libmachine/host.MigrateHostV2ToHostV3(0xc0422265c0, 0xc04217a480, 0x2, 0x202, 0x1427af4, 0x1, 0x0)
        /go/src/github.com/docker/machine/libmachine/host/migrate_v2_v3.go:26 +0x1d3
github.com/docker/machine/libmachine/host.MigrateHost(0xc042178540, 0xc04217a480, 0x2, 0x202, 0x202, 0x0, 0x0, 0x2f)
        /go/src/github.com/docker/machine/libmachine/host/migrate.go:109 +0x85a
github.com/docker/machine/libmachine/persist.Filestore.loadConfig(0xc042171410, 0x26, 0xc0421715c0, 0x2c, 0xc0421715c0, 0x2c, 0xc042178540, 0x2f, 0x30)
        /go/src/github.com/docker/machine/libmachine/persist/filestore.go:120 +0x15f
github.com/docker/machine/libmachine/persist.Filestore.Load(0xc042171410, 0x26, 0xc0421715c0, 0x2c, 0xc0421715c0, 0x2c, 0xc042105fa0, 0x7, 0x407d9c, 0x3a20f85d, ...)
        /go/src/github.com/docker/machine/libmachine/persist/filestore.go:156 +0x174
github.com/docker/machine/libmachine.(*Client).Load(0xc0420ff450, 0xc042105fa0, 0x7, 0x0, 0xc0421716b0, 0x0)
        /go/src/github.com/docker/machine/libmachine/libmachine.go:92 +0x79
github.com/docker/machine/libmachine/persist.LoadHosts(0x58740b0, 0xc0420ff450, 0xc042105fd0, 0x1, 0x1, 0x0, 0x13931c0, 0x0, 0x58740b0)
        /go/src/github.com/docker/machine/libmachine/persist/store.go:29 +0x106
github.com/docker/machine/libmachine/persist.LoadAllHosts(0x58740b0, 0xc0420ff450, 0xc0420ff450, 0x58740b0, 0xc0420ff450, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/machine/libmachine/persist/store.go:45 +0xc2
github.com/docker/machine/commands.cmdLs(0x1d6c940, 0xc0421060b0, 0x1d6c240, 0xc0420ff450, 0x0, 0x0)
        /go/src/github.com/docker/machine/commands/ls.go:83 +0x132
github.com/docker/machine/commands.runCommand.func1(0xc042219d40)
        /go/src/github.com/docker/machine/commands/commands.go:163 +0x4bb
github.com/docker/machine/vendor/github.com/codegangsta/cli.Command.Run(0x1427cab, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1433518, 0xd, 0x0, ...)
        /go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/command.go:137 +0x891
github.com/docker/machine/vendor/github.com/codegangsta/cli.(*App).Run(0xc0422199e0, 0xc0420403e0, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/machine/vendor/github.com/codegangsta/cli/app.go:175 +0x8ef
main.main()
        /go/src/github.com/docker/machine/cmd/machine.go:163 +0xacb
```
### Information

  - Diagnostic ID - 87A10C5D-3B71-417B-8E01-67AA9B2FC81B/2018-01-09_11-03-32
  - Windows 10 Pro, Version 1709, OS Build 16299.192
```
$ docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:05:22 2017
 OS/Arch:       windows/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:12:29 2017
  OS/Arch:      linux/amd64
  Experimental: true
```
### Steps to reproduce the behavior

  1. Create machine with hyperv with a virtual switch: `docker-machine create --driver hyperv --hyperv-virtual-switch VirtualSwitch1 default`
  2. I have removed and re-added this a few times with `docker-machine rm default --force`
  3. My config.json is just set to {}, since it was lost somewhere
  4. I tried resetting docker to factory settings, and also trying the stable version, but the issue is still the same

**Comment by echarrod** [comment]
Updated specs, issue is still occurring:

```
Client:
 Version:       18.04.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    3d479c0
 Built: Tue Apr 10 18:13:15 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.04.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   3d479c0
  Built:        Tue Apr 10 18:23:05 2018
  OS/Arch:      linux/amd64
  Experimental: true
```
