### ISSUE TITLE
Cannot Start with Linux Containers

### ISSUE THREAD

**Issue by TaylorBarrick** [docker/for-win#1523]
### Expected behavior
Linux Containers should work

### Actual behavior
D4W fails to start with the message:

Unable to create File System Image
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass27_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 335
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

Choosing Windows containers allows D4W to load fully.  Switching back to Linux containers still fails.

### Information

  - Diagnostic ID : 3EFB0CF0-AC4F-441C-BA0A-11B9C9AE2263/2018-01-10_13-01-31
  - Windows 10 Build 17063.1000

### Steps to reproduce the behavior

  1. Start Docker for Windows with Linux Containers selected

**Comment by jasonbivins** [comment]
HI @TaylorBarrick 
The latest Windows insider build (17063) broke a few things for us, it should be fixed with the next insider release   https://blogs.windows.com/windowsexperience/2017/12/19/announcing-windows-10-insider-preview-build-17063-pc/#8u4SZFHchBmH2swz.97
