### ISSUE TITLE
Unable to create file system image

### ISSUE THREAD

**Issue by JakeHendy** [docker/for-win#1540]
### Expected behavior
Docker starts as expected
### Actual behavior
Docker fails to start consistently with "Unable to create file system image" 
### Information
Crash ID: 7CC3B046-BA2C-4D96-9D03-5392E7C2D87D/2018-01-12_17-23-22
Host: Windows 10 Insider 17063. (x2, my desktop and Surface Pro 4)

Updated to Docker this morning on my Surface to see this error. Came home and Docker on my desktop is also experiencing the same issue. 
Tried to change the location for docker images and vhd's are stored to a directory (C:\jake.hendy\Docker) but that seemingly had no effect.

Similar to #1514 
### Steps to reproduce the behavior
Update to latest docker on Windows 10.

**Comment by jonstanley** [comment]
"Me too"

Crashg ID: 4D785EEE-C529-4F8B-86AB-2E06804AD387/2018-01-13_13-15-02
Host: Windows 10 x64 Insider Build 10.0.17074.1000

Work-around, switch from Docker stable to Docker edge, version 17.12.0-ce-win45 works as expected.

**Comment by JakeHendy** [comment]
Just updated to 17074, same issue. I'm running Docker Edge... 
![image](https://user-images.githubusercontent.com/545914/34907469-c8292518-f876-11e7-96dc-e097ef95f159.png)

**Comment by sisu4u** [comment]
Same problem here. A58293E2-C81D-4053-89ED-BF48C10543CF/2018-01-14_14-21-47

Also, I don't understand the versioning:
stable == 17.12.0-ce-win47
edge == 17.12.0-ce-win45
nightly == 17.03...

I tried all of them, deleted .docker directory, reinstalled. Checked hyper-v. Nothing seems to fix it.
The only way to start docker is enabling LCOW but then I immediately run into this issue https://github.com/docker/compose/issues/5402

**Comment by suprsidr** [comment]
Same here, luckily I still had win27 installer in my downloads. Pays to be lazy cleaning up downloads ;)

**Comment by suprsidr** [comment]
sorry. cannot find build # its from 9/27/2017

**Comment by jonstanley** [comment]
@suprsidr okay thanks... wish @docker would keep/allow easy access to a build archive so we could at least easily roll back when a release implodes... ugh.

**Comment by rhinoceraptor** [comment]
There goes my whole day, debugging broken Windows and Docker stuff. Maybe tomorrow I'll be able to work again.

**Comment by jonstanley** [comment]
There went a whole weekend and some... nobody at @docker noticed the issues are on fire?

**Comment by rhinoceraptor** [comment]
I'm on 17063 btw. I tried uninstalling docker, switching to nightly, edge and stable and none of them work.

**Comment by bahaki386** [comment]
Me too.
I tried use 17.12.0-ce-win45 on Windows Insider Build 17074,then reproduce this error.

**Comment by seffyroff** [comment]
I'm experiencing the same issue on 17074 here.

**Comment by JakeHendy** [comment]
Tried replacing the binaries found in this [zip](https://download.docker.com/win/static/stable/x86_64/docker-17.09.0-ce.zip) with those in Program Files, alas no luck. Time to get diff'ing...

**Comment by kfsone** [comment]
Same issue immediately after 17074 upgrade.

Diagnostic: 6E2776E7-61BF-42E6-B31B-60527DE3DA3B/2018-01-20_14-32-33

**Comment by suprsidr** [comment]
is it me or is this 12 day old issue still an issue?

**Comment by pgrm** [comment]
@suprsidr I just got the issue yesterday - so probably still an issue - the worst thing about it is, that docker doesn't seem to offer downloading old setup files which used to work (at least I couldn't find it), and unless you have an old file in your download folder laying around you're pretty much out of luck.

**Comment by suprsidr** [comment]
not a fan of posting links here but this is the version I referenced above:
https://www.dropbox.com/s/5baw4lm0x3ansbp/Docker%20for%20Windows%20Installer%2017.06.2-ce.exe.zip?dl=0

Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:19 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by ckcampbell248** [comment]
I'm having the same problem with Docker 17.12.0-ce-win47 (15139) on Windows 10 Enterprise Build 17074. 

I tried resetting to factory defaults and also tried uninstalling and reinstalling. No joy.

**Comment by CWRau** [comment]
"Me too"

Crash ID: `33DDF081-2786-4764-BF0F-91730B519554/2018-01-25_07-48-42`

Log:
```
Version: 17.12.0-ce-win47 (15139)
Channel: stable
Sha1: 9c692cd5b38166289573183371647d915f300292
Started on: 2018/01/25 07:45:20.197
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise Insider Preview
Edition: Professional
Id: 1709
Build: 17074
BuildLabName: 17074.1002.amd64fre.rs_prerelease_flt.180116-1539
File: C:\Users\c.rau\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[07:45:20.437][GUI            ][Info   ] Starting...
[07:45:21.267][Tracking       ][Info   ] Crash report and usage statistics are enabled
[07:45:21.274][SegmentApi     ][Info   ] Usage statistic: appLaunched
[07:45:23.764][NPS            ][Info   ] NPS user ceated on :10/4/2017 10:15:50 AM -07:00, last survey : 11/4/2017 2:23:00 PM -07:00
[07:45:23.766][SegmentApi     ][Info   ] Usage statistic: heartbeat
[07:45:23.771][SegmentApi     ][Info   ] Usage statistic: Identify
[07:45:23.878][NamedPipeClient][Info   ] Sending Version()...
[07:45:23.885][NamedPipeClient][Info   ] Received response for Version
[07:45:23.886][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[07:45:23.885][NamedPipeServer][Info   ] Version done in 00:00:00.
[07:45:23.888][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
[07:45:23.888][PowerMode      ][Info   ] Stop
[07:45:23.888][HyperV         ][Info   ] Stop
[07:45:23.888][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[07:45:23.904][HyperV         ][Info   ] Script started at 07:45:23.903
[07:45:23.916][HyperV         ][Info   ] Module loaded at 07:45:23.915
[07:45:23.926][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[07:45:23.926][HyperV         ][Debug  ] [stop] took 00:00:00.0380002 to run
[07:45:23.926][OptimizeDisk   ][Info   ] Optimize
[07:45:23.926][PowerShell     ][Info   ] Run script...
[07:45:23.939][Moby           ][Info   ] Stop
[07:45:23.950][PowerMode      ][Info   ] Start
[07:45:23.950][HyperVGuids    ][Info   ] Installing GUIDs...
[07:45:23.950][HyperV         ][Info   ] Create
[07:45:23.950][Firewall       ][Info   ] Removing all existing rules...
[07:45:23.951][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[07:45:23.953][HyperVGuids    ][Info   ] GUIDs installed
[07:45:23.971][HyperV         ][Info   ] Script started at 07:45:23.971
[07:45:23.990][HyperV         ][Info   ] Module loaded at 07:45:23.990
[07:45:24.136][HyperV         ][Info   ] Creating Switch: DockerNAT...
[07:45:25.448][Firewall       ][Info   ] All existing rules are removed.
[07:45:25.450][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[07:45:25.483][Firewall       ][Info   ] Opening ports for SMB...
[07:45:25.505][Firewall       ][Info   ] Ports are opened
[07:45:36.022][HyperV         ][Info   ] Switch created.
[07:45:49.895][HyperV         ][Info   ] Set IP address on switch
[07:45:49.930][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[07:45:51.200][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[07:45:52.189][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[07:45:53.221][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[07:45:53.868][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[07:45:54.879][HyperV         ][Info   ] Disabled Guest Service Interface
[07:45:54.903][HyperV         ][Info   ] Enabled Heartbeat
[07:45:54.940][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[07:45:54.964][HyperV         ][Info   ] Enabled Shutdown
[07:45:54.981][HyperV         ][Info   ] Enabled Time Synchronization
[07:45:55.022][HyperV         ][Info   ] Disabled VSS
[07:45:55.670][HyperV         ][Info   ] VM created.
[07:45:55.672][HyperV         ][Debug  ] [create] took 00:00:31.7213127 to run
[07:45:55.672][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[07:45:55.730][Database       ][Info   ] Generating CA Cert Bundle
[07:45:55.814][Database       ][Info   ] CA Cert Bundle Generated
[07:45:55.837][Linux          ][Error  ] Failed to start: Unable to create File System Image. Let's retry
[07:45:55.906][HyperV         ][Info   ] Hyper-V is running
[07:45:55.906][PowerMode      ][Info   ] Stop
[07:45:55.907][HyperV         ][Info   ] Stop
[07:45:55.909][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[07:45:55.927][HyperV         ][Info   ] Script started at 07:45:55.927
[07:45:55.991][HyperV         ][Info   ] Module loaded at 07:45:55.991
[07:45:56.079][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[07:45:56.079][HyperV         ][Debug  ] [stop] took 00:00:00.1724963 to run
[07:45:56.079][OptimizeDisk   ][Info   ] Optimize
[07:45:56.079][PowerShell     ][Info   ] Run script...
[07:45:57.877][Moby           ][Info   ] Stop
[07:45:57.889][HyperV         ][Info   ] Destroy
[07:45:57.889][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[07:45:57.904][HyperV         ][Info   ] Script started at 07:45:57.904
[07:45:57.929][HyperV         ][Info   ] Module loaded at 07:45:57.929
[07:45:57.954][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[07:45:57.955][HyperV         ][Info   ] Destroying Switch DockerNAT...
[07:46:06.967][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[07:46:07.067][HyperV         ][Debug  ] [destroy] took 00:00:09.1780741 to run
[07:46:07.067][Firewall       ][Info   ] Closing ports...
[07:46:07.067][Firewall       ][Info   ] Removing all existing rules...
[07:46:08.070][Firewall       ][Info   ] All existing rules are removed.
[07:46:08.070][Firewall       ][Info   ] Ports are closed
[07:46:08.070][HyperVGuids    ][Info   ] Removing GUIDs...
[07:46:08.075][HyperVGuids    ][Info   ] GUIDs removed
[07:46:08.075][HyperV         ][Info   ] Create
[07:46:08.076][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[07:46:08.097][HyperV         ][Info   ] Script started at 07:46:08.096
[07:46:08.126][HyperV         ][Info   ] Module loaded at 07:46:08.126
[07:46:08.279][HyperV         ][Info   ] Creating Switch: DockerNAT...
[07:46:24.446][HyperV         ][Info   ] Switch created.
[07:46:35.192][HyperV         ][Info   ] Set IP address on switch
[07:46:35.425][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[07:46:39.578][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[07:46:40.574][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[07:46:41.425][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[07:46:42.946][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[07:46:43.669][HyperV         ][Info   ] Disabled Guest Service Interface
[07:46:43.698][HyperV         ][Info   ] Enabled Heartbeat
[07:46:43.731][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[07:46:43.751][HyperV         ][Info   ] Enabled Shutdown
[07:46:43.772][HyperV         ][Info   ] Enabled Time Synchronization
[07:46:43.798][HyperV         ][Info   ] Disabled VSS
[07:46:44.176][HyperV         ][Info   ] VM created.
[07:46:44.177][HyperV         ][Debug  ] [create] took 00:00:36.1014843 to run
[07:46:44.177][PowerMode      ][Info   ] Stop
[07:46:44.177][HyperV         ][Info   ] Stop
[07:46:44.177][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[07:46:44.194][HyperV         ][Info   ] Script started at 07:46:44.194
[07:46:44.208][HyperV         ][Info   ] Module loaded at 07:46:44.208
[07:46:44.243][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[07:46:44.243][HyperV         ][Debug  ] [stop] took 00:00:00.0665355 to run
[07:46:44.243][OptimizeDisk   ][Info   ] Optimize
[07:46:44.243][PowerShell     ][Info   ] Run script...
[07:46:45.860][Moby           ][Info   ] Stop
[07:46:45.873][PowerMode      ][Info   ] Start
[07:46:45.873][HyperV         ][Info   ] Create
[07:46:45.873][HyperVGuids    ][Info   ] Installing GUIDs...
[07:46:45.873][Firewall       ][Info   ] Removing all existing rules...
[07:46:45.873][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[07:46:45.880][HyperVGuids    ][Info   ] GUIDs installed
[07:46:45.896][HyperV         ][Info   ] Script started at 07:46:45.895
[07:46:45.924][HyperV         ][Info   ] Module loaded at 07:46:45.923
[07:46:46.302][HyperV         ][Info   ] Using existing Switch: DockerNAT
[07:46:46.707][Firewall       ][Info   ] All existing rules are removed.
[07:46:46.708][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[07:46:46.723][Firewall       ][Info   ] Opening ports for SMB...
[07:46:46.738][Firewall       ][Info   ] Ports are opened
[07:46:56.999][HyperV         ][Info   ] Using existing Switch IP address
[07:46:57.077][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[07:46:58.119][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[07:46:59.206][HyperV         ][Info   ] Remove existing DVDs
[07:46:59.929][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[07:47:01.174][HyperV         ][Info   ] Disabled Guest Service Interface
[07:47:01.227][HyperV         ][Info   ] Enabled Heartbeat
[07:47:01.265][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[07:47:01.307][HyperV         ][Info   ] Enabled Shutdown
[07:47:01.351][HyperV         ][Info   ] Enabled Time Synchronization
[07:47:01.419][HyperV         ][Info   ] Disabled VSS
[07:47:01.687][HyperV         ][Info   ] VM created.
[07:47:01.687][HyperV         ][Debug  ] [create] took 00:00:15.8146871 to run
[07:47:01.687][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[07:47:01.727][Database       ][Info   ] Generating CA Cert Bundle
[07:47:01.815][Database       ][Info   ] CA Cert Bundle Generated
[07:47:01.856][PowerMode      ][Info   ] Stop
[07:47:01.856][HyperV         ][Info   ] Stop
[07:47:01.858][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[07:47:01.894][HyperV         ][Info   ] Script started at 07:47:01.894
[07:47:01.937][HyperV         ][Info   ] Module loaded at 07:47:01.937
[07:47:01.975][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[07:47:01.976][HyperV         ][Debug  ] [stop] took 00:00:00.1194892 to run
[07:47:01.976][OptimizeDisk   ][Info   ] Optimize
[07:47:01.976][PowerShell     ][Info   ] Run script...
[07:47:03.207][Moby           ][Info   ] Stop
[07:47:03.237][HyperV         ][Info   ] Destroy
[07:47:03.239][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[07:47:03.253][HyperV         ][Info   ] Script started at 07:47:03.253
[07:47:03.293][HyperV         ][Info   ] Module loaded at 07:47:03.293
[07:47:03.336][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[07:47:03.338][HyperV         ][Info   ] Destroying Switch DockerNAT...
[07:47:09.337][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[07:47:09.687][HyperV         ][Debug  ] [destroy] took 00:00:06.4494690 to run
[07:47:09.687][Firewall       ][Info   ] Closing ports...
[07:47:09.687][Firewall       ][Info   ] Removing all existing rules...
[07:47:15.782][Firewall       ][Info   ] All existing rules are removed.
[07:47:15.808][NamedPipeClient][Error  ] Unable to send Start: Unable to create File System Image
[07:47:15.782][Firewall       ][Info   ] Ports are closed
[07:47:15.811][Notifications  ][Error  ] Unable to create File System Image
[07:47:15.782][HyperVGuids    ][Info   ] Removing GUIDs...
[07:47:15.789][HyperVGuids    ][Info   ] GUIDs removed
[07:47:15.793][NamedPipeServer][Error  ] Unable to execute Start: Unable to create File System Image    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 256
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[07:48:42.058][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[07:48:42.061][NamedPipeClient][Info   ] Sending Version()...
[07:48:42.061][NamedPipeClient][Info   ] Sending Version()...
[07:48:42.062][NamedPipeClient][Info   ] Sending Version()...
[07:48:42.064][NamedPipeClient][Info   ] Sending Version()...
[07:48:42.079][CrashReport    ][Warning] Unable to collect features settings: Could not find file 'C:\Users\c.rau\AppData\Roaming\Docker\features-overrides.json'.
[07:48:42.082][NamedPipeClient][Info   ] Received response for Version
[07:48:42.082][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[07:48:42.082][NamedPipeClient][Info   ] Received response for Version
[07:48:42.082][NamedPipeClient][Info   ] Received response for Version
[07:48:42.083][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\c.rau\AppData\Local\Temp\okm1p1aj.53s\pcap.tar)...
[07:48:42.083][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\c.rau\AppData\Local\Temp\okm1p1aj.53s\mobyLogs.tar)...
[07:48:42.083][NamedPipeClient][Info   ] Received response for Version
[07:48:42.083][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\c.rau\AppData\Local\Temp\okm1p1aj.53s\win_containers)...
[07:48:42.081][NamedPipeServer][Info   ] Version()
[07:48:42.081][NamedPipeServer][Info   ] Version done in 00:00:00.
[07:48:42.087][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[07:48:42.082][NamedPipeServer][Info   ] Version()
[07:48:42.082][NamedPipeServer][Info   ] Version()
[07:48:42.082][NamedPipeServer][Info   ] Version()
[07:48:42.082][NamedPipeServer][Info   ] Version done in 00:00:00.
[07:48:42.082][NamedPipeServer][Info   ] Version done in 00:00:00.
[07:48:42.082][NamedPipeServer][Info   ] Version done in 00:00:00.
[07:48:42.083][NamedPipeServer][Info   ] GetDebugInfo()
[07:48:42.084][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\c.rau\AppData\Local\Temp\okm1p1aj.53s\pcap.tar)
[07:48:42.084][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\c.rau\AppData\Local\Temp\okm1p1aj.53s\mobyLogs.tar)
[07:48:42.084][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\c.rau\AppData\Local\Temp\okm1p1aj.53s\win_containers)
[07:48:42.085][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[07:48:42.086][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[07:48:42.086][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0019990.
[07:48:42.113][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[07:48:42.112][HyperV         ][Warning] Unable to download logs: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual machine with name "MobyLinuxVM".
[07:48:42.113][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.0290011.
[07:49:19.895][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[07:49:19.895][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:37.8104307.
[07:49:34.573][NamedPipeServer][Info   ] GetDebugInfo done in 00:00:52.4894757.
[07:49:34.577][NamedPipeClient][Info   ] Received response for GetDebugInfo
[07:49:34.891][CrashReport    ][Info   ] Uploading diagnostics...
[07:49:37.104][CrashReport    ][Info   ] Diagnostics successfully uploaded (33DDF081-2786-4764-BF0F-91730B519554/2018-01-25_07-48-42)
[07:49:37.144][GUI            ][Info   ] Sending Bugsnag report 4a7d03a6-beb4-40cf-a1e3-92045071c09a...
[07:49:38.498][GUI            ][Info   ] Bugsnag report 4a7d03a6-beb4-40cf-a1e3-92045071c09a sent
```

**Comment by RexSkz** [comment]
Still have this problem.

Windows: **Insider Preview 17083**
Docker: **18.01.0-ce-win48 (15285)**

---

> We fixed an issue with Linux containers on Windows using Docker Community Edition for Windows (edge) on many machines. The docker pull or docker run commands will fail with an error “Not enough memory resources are available to complete this operation”.

Reference is [here](https://blogs.windows.com/windowsexperience/2018/01/24/announcing-windows-10-insider-preview-build-17083-for-pc/#Khy0wkkmIEKxo8yK.97). One problem solved, another one to go...

**Comment by aaronpowell** [comment]
Still an issue with Docker `18.02.0-ce-rc1-win50 (15489)`.

**Comment by spboyer** [comment]
Getting this same issue with Docker ce 
Version 17.12.0-ce-win47 (15139)
Channel: stable
9c692cd

@taylorb-microsoft

**Comment by taylorb-microsoft** [comment]
We have identified the bug (and fix) in Windows, we are validating the fix once I have a target build number I will update the various issues.

**Comment by los93sol** [comment]
How soon do you expect to have the update ready?

**Comment by taylorb-microsoft** [comment]
Likely next week

**Comment by nabsul** [comment]
Wow, this is really painful. This basically means I can't use docker until then. Fortunately for me, I don't use it every day, but for others I'm sure this is a bigger problem. 

Would I have avoided all this trouble if I was not using Windows Insider? I understand that preview builds have some risk associated, but I assumed that fixes would come out quicker as well.

**Comment by hach-que** [comment]
Latest edge release is still broken in 17083. Workaround is to use Docker Toolbox.

**Comment by jasonbivins** [comment]
It seems to be starting up if you switch to Windows container mode

**Comment by rhinoceraptor** [comment]
I would use docker toolbox, except my company's AV does questionable things to user processes, which VirtualBox (rightly) protests against.

I really miss using a real operating system where things work and it doesn't ~blue~ green screen once a week...

**Comment by suprsidr** [comment]
I linked to a previous working version above https://github.com/docker/for-win/issues/1540#issuecomment-360173768

**Comment by rhinoceraptor** [comment]
Thanks @suprsidr, that works for me on 17083!

**Comment by robotdad** [comment]
@jasonbivins the problem with switching to Windows containers is you can't use Linux containers too 👎

**Comment by aaronpowell** [comment]
@robotdad if you're using Edge then LCOW is enabled side-by-side with WCOW, so you can run Linux and Windows containers at the same time.

What you can't do is switch back to "just Linux containers" (which is what that change mode is for), which starts up a Hyper-V machine to run everything within.

So on Edge builds in Fast Ring you can run a Linux container when it's set to 'Run Windows Containers', you just specify a `--platform Linux` flag to your `docker run`.

Only down side is that you can't expand the amount of memory LCOW uses beyond 2GB, meaning that you can't run the MS SQL Server container.

**Comment by spboyer** [comment]
@aaronpowell - the flag is great for standard containers and workarounds for now. The bigger issue is being able to test the kubernetes features.

**Comment by RexSkz** [comment]
Still not working on Windows 10 17093.
Docker version 18.01.0-ce-win48 (15285).

**Comment by robotdad** [comment]
docker run still says I can't use Linux. This is on 17093. Personally I will leave fast ring if I can't get this working by the end of the week.

 docker run -d -p 12345:22 --security-opt seccomp:unconfined ducatel/visual-studio-linux-build-box --platform Linux
Unable to find image 'ducatel/visual-studio-linux-build-box:latest' locally
latest: Pulling from ducatel/visual-studio-linux-build-box
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: image operating system "linux" cannot be used on this platform.

**Comment by PatrickLang** [comment]
Sorry for the troubles here. I did get a Windows developer to dig into this, but don't know when the fix will be in the Windows Insider fast ring. To @robotdad - not by Friday since the Windows Insider team seems to release on Mondays.

I've also discussed another workaround with the d4w team to work around this Windows bug but don't have an ETA for that either.

**Comment by RexSkz** [comment]
Still not working on Windows 10 17101.
Docker version 18.02.0-ce-rc2-win51 (15631).

Can't use d4w for about a month...
I don't want to use docker toolbox...

**Comment by gbatalski** [comment]
I switched back to 17.07.0-ce-win26 (13125) via older installer and now linux containers work good at a first glance.

**Comment by los93sol** [comment]
@taylorb-microsoft Did you ever get a build number?  Looks like people are still having issues.  I’ve been holding off on all docker updates to stay productive, this issue has been drug out far too long for us fast ring folks.

**Comment by gbatalski** [comment]
Version 17.07.0-ce-win26 (13125)
Channel: edge
7c2cb37

Windows 1709 (Build 17074.1002)

**Comment by PatrickLang** [comment]
I'm looking at build 17104 which may have the fixes. I don't have a release ETA but am hoping to confirm at least a minimum build number to look for.

@ebriney - anything you can share on possible workarounds?

**Comment by ebriney** [comment]
We didn't use win api to create iso anymore.
It will be fixed in 18.03, next week for edge and stable in 2-3 weeks.

**Comment by PatrickLang** [comment]
Windows 10 Insider build 17104 with 17.12.0-ce-win47 doesn't hit the error but MobyLinuxVM seems to just spin the CPU without actually starting the Linux daemon. That's a separate issue - I can open the config.iso attached to the VM and the config.json in there is ok.

Trying 18.02.0-ce-win52 now on Windows 10 Insider build 17104 now.

**Comment by PatrickLang** [comment]
Hmm, getting hangs with 18.02 as well. I'm not sure if this is related to the different Windows build or something else. It's definitely not crashing creating the ISO any longer though.

I don't have an ETA on when 17104+ will be out so keep watching the Windows Insider blog for upcoming builds.

**Comment by PatrickLang** [comment]
Oh, I didn't reboot so the newer MobyLinuxVM from 18.02 wasn't running. Looks like 17104+ is good with 18.02

```
(gin).OsBuildNumber
17104
PS C:\Windows\system32> docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

PS C:\Windows\system32> docker version
Client:
 Version:       18.02.0-ce
 API version:   1.36
 Go version:    go1.9.3
 Git commit:    fc4de44
 Built: Wed Feb  7 21:12:53 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.02.0-ce
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.3
  Git commit:   fc4de44
  Built:        Wed Feb  7 21:20:15 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

**Comment by seffyroff** [comment]
Insider build 17604 with Docker CE 18.02.0 Still giving the binary issue here.

Diagnostic ID 40289C5D-0187-44C6-869E-75348E5AE660/2018-02-16_20-49-59.

OS Details:
Windows 10 Pro Insider Preview
Build 17604.rs_prerelease.180209-1422

Docker details:
Version 18.02.0-ce-win52 (15732)
Channel: edge
92c7ac6

**Comment by haroldvandekamp** [comment]
I am on Windows 10 Insider Slow version 1709 Build 17074.1002 and also had the error "Unable to create file system image" when I was using Docker Community Edition 17.12.0-ce-win47 2018-01-12 (Stable).
I uninstalled that version, downloaded and installed the Docker Community Edition 17.09.1-ce-win42 2017-12-11 (Stable) version (https://download.docker.com/win/stable/14687/Docker%20for%20Windows%20Installer.exe), after that Docker starts normally.

**Comment by IvanCl4udio** [comment]
Installing the version Docker version 17.09.1-ce, build 19e2cf6 works for me. Docker starts normally.

Thanks @haroldvandekamp for the tip!

**Comment by juliusbz** [comment]
@emperoar check this out.

**Comment by pranavb** [comment]
Just repeating what @haroldvandekamp said [above](https://github.com/docker/for-win/issues/1540#issuecomment-366697527):

* Windows Insiders in the **Slow ring** (17074.1002)
* Install Docker 17.12.0-ce 
 [Release notes](https://docs.docker.com/release-notes/docker-ce/#17120-ce-2017-12-27)
 [Download](https://download.docker.com/win/stable/14687/Docker%20for%20Windows%20Installer.exe)

**Comment by EmpeRoar** [comment]
Hi Guys,

I am already running
Windows 10: Build 17110
Docker:  18.03.0-ce-rc1

But still got this error:
Error response from daemon: driver failed programmi
ng external connectivity on endpoint eager_ardinghelli (7b2b773dc6c7fb151d5d92340eb686fa14b831d6cddcad4d1270
90528ce5c56d): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error Permission denied.

**Comment by xiaoppp** [comment]
![image](https://user-images.githubusercontent.com/1396802/37084143-b0ab6ef2-222c-11e8-8016-1f6d55f1a119.png)

this version woks fine on my side

**Comment by PatrickLang** [comment]
@JakeHendy - do you think we should close this issue? The original file system image creation problem is solved, so it might be easier to track other problems like the [proxy error](https://github.com/docker/for-win/issues/1540#issuecomment-369822822) as separate issues
