### ISSUE TITLE
Lastest stable release of Docker for Windows does not run with latest Windows Pro Release

### ISSUE THREAD

**Issue by koeppj** [docker/for-win#1543]
### Expected behavior
- Install Docker
- Run Docker
- Creates MobyLinuxVM

### Actual behavior
- Installs Docker
- Running Docker fails to create VM 

### Information
-  Diagnostic ID: 265B8555-0FFF-4768-8D33-8124E9CB5E75/2018-01-12_12-56-14
-  Windows Version 
OS: Windows 10 Pro
Edition: Professional
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834

### Steps to reproduce the behavior

  1. Install Docker for Windows

  2. Run Docker

--- Log Output Below --
Version: 17.12.0-ce-win47 (15139)
Channel: stable
Sha1: 9c692cd5b38166289573183371647d915f300292
Started on: 2018/01/12 12:44:04.140
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834
File: C:\Users\John\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[12:44:04.284][GUI            ][Info   ] Starting...
[12:44:04.732][Tracking       ][Info   ] Crash report and usage statistics are enabled
[12:44:04.735][SegmentApi     ][Info   ] Usage statistic: appLaunched
[12:44:05.597][NPS            ][Info   ] NPS user ceated on :12/6/2017 7:09:29 AM -08:00, last survey : 1/12/2018 8:12:26 AM -08:00
[12:44:05.598][SegmentApi     ][Info   ] Usage statistic: heartbeat
[12:44:05.601][SegmentApi     ][Info   ] Usage statistic: Identify
[12:44:05.716][NamedPipeClient][Info   ] Sending Version()...
[12:44:05.724][NamedPipeClient][Info   ] Received response for Version
[12:44:05.726][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[12:44:05.723][NamedPipeServer][Info   ] Version done in 00:00:00.
[12:44:05.728][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
[12:44:05.728][PowerMode      ][Info   ] Stop
[12:44:05.728][HyperV         ][Info   ] Stop
[12:44:05.728][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[12:44:05.743][HyperV         ][Info   ] Script started at 12:44:05.743
[12:44:05.764][HyperV         ][Info   ] Module loaded at 12:44:05.764
[12:44:05.776][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[12:44:05.776][HyperV         ][Debug  ] [stop] took 00:00:00.0479985 to run
[12:44:05.776][OptimizeDisk   ][Info   ] Optimize
[12:44:05.776][PowerShell     ][Info   ] Run script...
[12:44:05.790][Moby           ][Info   ] Stop
[12:44:05.796][HyperV         ][Info   ] Create
[12:44:05.796][PowerMode      ][Info   ] Start
[12:44:05.796][HyperVGuids    ][Info   ] Installing GUIDs...
[12:44:05.796][Firewall       ][Info   ] Removing all existing rules...
[12:44:05.796][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[12:44:05.799][HyperVGuids    ][Info   ] GUIDs installed
[12:44:05.813][HyperV         ][Info   ] Script started at 12:44:05.813
[12:44:05.845][HyperV         ][Info   ] Module loaded at 12:44:05.844
[12:44:05.849][Firewall       ][Info   ] All existing rules are removed.
[12:44:05.849][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[12:44:05.858][Firewall       ][Info   ] Opening ports for SMB...
[12:44:05.868][Firewall       ][Info   ] Ports are opened
[12:44:05.972][HyperV         ][Info   ] Creating Switch: DockerNAT...
[12:44:08.894][HyperV         ][Info   ] Switch created.
[12:44:10.984][HyperV         ][Info   ] Set IP address on switch
[12:44:11.001][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[12:44:11.105][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.

'MobyLinuxVM' failed to realize.
at New-MobyLinuxVM, <No file>: line 202
at <ScriptBlock>, <No file>: line 409. Let's retry
[12:44:11.117][HyperV         ][Info   ] Hyper-V is running
[12:44:11.117][PowerMode      ][Info   ] Stop
[12:44:11.117][HyperV         ][Info   ] Stop
[12:44:11.117][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[12:44:11.126][HyperV         ][Info   ] Script started at 12:44:11.126
[12:44:11.139][HyperV         ][Info   ] Module loaded at 12:44:11.139
[12:44:11.154][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[12:44:11.154][HyperV         ][Debug  ] [stop] took 00:00:00.0370078 to run
[12:44:11.154][OptimizeDisk   ][Info   ] Optimize
[12:44:11.154][PowerShell     ][Info   ] Run script...
[12:44:11.165][Moby           ][Info   ] Stop
[12:44:11.170][HyperV         ][Info   ] Destroy
[12:44:11.171][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[12:44:11.179][HyperV         ][Info   ] Script started at 12:44:11.179
[12:44:11.191][HyperV         ][Info   ] Module loaded at 12:44:11.191
[12:44:11.202][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[12:44:11.203][HyperV         ][Info   ] Destroying Switch DockerNAT...
[12:44:13.466][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[12:44:13.477][HyperV         ][Debug  ] [destroy] took 00:00:02.3066424 to run
[12:44:13.477][Firewall       ][Info   ] Closing ports...
[12:44:13.477][Firewall       ][Info   ] Removing all existing rules...
[12:44:13.567][Firewall       ][Info   ] All existing rules are removed.
[12:44:13.567][Firewall       ][Info   ] Ports are closed
[12:44:13.567][HyperVGuids    ][Info   ] Removing GUIDs...
[12:44:13.568][HyperVGuids    ][Info   ] GUIDs removed
[12:44:13.568][HyperV         ][Info   ] Create
[12:44:13.569][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[12:44:13.581][HyperV         ][Info   ] Script started at 12:44:13.581
[12:44:13.608][HyperV         ][Info   ] Module loaded at 12:44:13.608
[12:44:13.685][HyperV         ][Info   ] Creating Switch: DockerNAT...
[12:44:16.100][HyperV         ][Info   ] Switch created.
[12:44:18.175][HyperV         ][Info   ] Set IP address on switch
[12:44:18.192][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[12:44:18.310][PowerMode      ][Info   ] Stop
[12:44:18.310][HyperV         ][Info   ] Stop
[12:44:18.310][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[12:44:18.326][HyperV         ][Info   ] Script started at 12:44:18.325
[12:44:18.339][HyperV         ][Info   ] Module loaded at 12:44:18.339
[12:44:18.352][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[12:44:18.352][HyperV         ][Debug  ] [stop] took 00:00:00.0420141 to run
[12:44:18.352][OptimizeDisk   ][Info   ] Optimize
[12:44:18.352][PowerShell     ][Info   ] Run script...
[12:44:18.365][Moby           ][Info   ] Stop
[12:44:18.370][HyperV         ][Info   ] Destroy
[12:44:18.379][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[12:44:18.389][HyperV         ][Info   ] Script started at 12:44:18.389
[12:44:18.410][HyperV         ][Info   ] Module loaded at 12:44:18.410
[12:44:18.420][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[12:44:18.422][HyperV         ][Info   ] Destroying Switch DockerNAT...
[12:44:20.620][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[12:44:20.631][HyperV         ][Debug  ] [destroy] took 00:00:02.2608920 to run
[12:44:20.631][Firewall       ][Info   ] Closing ports...
[12:44:20.631][Firewall       ][Info   ] Removing all existing rules...
[12:44:20.658][Firewall       ][Info   ] All existing rules are removed.
[12:44:20.658][Firewall       ][Info   ] Ports are closed
[12:44:20.658][HyperVGuids    ][Info   ] Removing GUIDs...
[12:44:20.658][HyperVGuids    ][Info   ] GUIDs removed
[12:44:20.659][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.

'MobyLinuxVM' failed to realize.
at New-MobyLinuxVM, <No file>: line 202
at <ScriptBlock>, <No file>: line 409    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 181
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[12:44:20.691][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.

'MobyLinuxVM' failed to realize.
at New-MobyLinuxVM, <No file>: line 202
at <ScriptBlock>, <No file>: line 409
[12:44:20.692][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.

'MobyLinuxVM' failed to realize.
at New-MobyLinuxVM, <No file>: line 202
at <ScriptBlock>, <No file>: line 409
[12:44:30.559][ErrorReportWindow][Info   ] Open logs

**Comment by Maikel-Nait** [comment]
This fixed the issue for me
[Fix error managing Hyper-V Server 2012 R2 from Windows 10](https://community.spiceworks.com/how_to/122307-fix-error-managing-hyper-v-server-2012-r2-from-windows-10)
