### ISSUE TITLE
Error upgrading to 17.12.0-ce-win47 (15139)

### ISSUE THREAD

**Issue by ehazlett** [docker/for-win#1545]
### Expected behavior
Upgrade to work.

### Actual behavior
After latest upgrade (17.12.0-ce-win47 15139) it removed the Moby VM but didn't re-create.  Upon attempt to start this error is received:

```
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 293
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 260
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows 10 Pro
Version 1709
Build 16299.192

### Steps to reproduce the behavior

  1. Upgrade to version specified above.
  2. Start Docker for Windows

**Comment by rsgoheen** [comment]
I had the same problem.  A couple of "Reset to factory defaults", a reboot, and one more "Reset to factory defaults" seems to have solved things

**Comment by adamjbradley** [comment]
Same issue. Extremely poor behavior.

**Comment by shawmanz32na** [comment]
I have the same problem, but a couple of "Reset to factory defaults" and some reboots have NOT solved things for me.

**Comment by ehazlett** [comment]
It would be nice to have a response from the team instead of it being ignored and eventually closed by a bot.

**Comment by shawmanz32na** [comment]
@ehazlett I understand the feeling.

That said, the team is aware of this issue and actively tracking it where possible (see @rn 's comment in #1866), and have released two stable releases since this version. Have you tried installing/upgrading to a more current stable version, and are you still having this issue?

I eventually "solved" this issue by getting rid of my inception-esque Docker-inside-a-Windows-VM environment.

**Comment by ehazlett** [comment]
@shawmanz32na tbh after three data corruptions across two upgrades I stopped using it.  I'll try to get a chance to install the latest.  thx.
