### ISSUE TITLE
Move MobyLinuxVM.vhdx to another drive 

### ISSUE THREAD

**Issue by eliassal** [docker/for-win#1589]
### Expected behavior
In settings, it gives the impression that we can change the location of MobyLinux.vhdx , Docker for windows refuse to change "MobyLinux.vhdx" location
### Actual behavior
I clicked on settings > Advanced, changed to a new directory on a another drive, clicked apply, Docker for windows revert back to

> C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx

### Information

   - Yes reproducible
  - page URL if this is a docs issue or the name of a man page
  - Windows 10 Enterprise

### Steps to reproduce the behavior

1.Right Click the whale, chose advanced
2.browse to another directory, for example E:\docker
3.Hit apply
4. Docker for windows revert back to the 1st directory and starts

**Comment by Zabanya** [comment]
try moving it from hyper v, although i can move it from inside docker.

win 10 1709, Docker version 17.12.0-ce, build c97c6d6

hyper v shows this if i move disk from docker
![hv](https://user-images.githubusercontent.com/1352081/35205334-f84fff72-ff66-11e7-918e-88e330343a04.png)

**Comment by eliassal** [comment]
I managed to do it from inside docker also, thanks

**Comment by eliassal** [comment]
Zabanya, since I did the change, whenever I try toi switch to linux containers mode, it crashes with the following message 
Crash ID is 

> 54E91A22-1B28-4D5A-9325-27354CD3129B/2018-01-23_04-19-12

I looked at thread #271 but nothing useful

> Docker hv-sock proxy (vsudd) is not reachable
>    at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 293
>    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 260
>    at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
>    at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
>    at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
> 
>

**Comment by eliassal** [comment]
Here is the log file as well
[DockerCrashlog.txt](https://github.com/docker/for-win/files/1655945/DockerCrashlog.txt)

**Comment by tbsexton** [comment]
For what it's worth, I'm getting this same issue. It seemed like perhaps running the daemon as administrator might work, or removing Read-Only from the `Hyper-V` or `Virtual Hard Disks` directories, but neither changes the error message, and that directory reverts back to read-only immediately, even with admin privileges.

**Comment by nategraf** [comment]
I also needed to move my VHD to my other drive (My C: drive is a small SSD, my E: drive is a big HDD)

The settings menu did not work, but I found a workaround.
1. Shut down Docker
2. Move the  `C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx` to `E:\Foo\Bar\MobyLinuxVM.vhdx`
3. Edit `%APPDATA%\Docker\settings.json` to set `"MobyVhdPathOverride": "E:\\Foo\\Bar\\MobyLinuxVM.vhdx"`
4. Start Docker

So the setting works, but just not through the settings menu for some reason. ¯\_( ツ )_/¯

**Comment by TBBle** [comment]
I just tried this, and it seemed to work fine through the Docker for Windows UI. Docker restarted, and (since I had the HyperV Manager open) the HyperV Manager showed 'Moving storage' and moved the VHDX into the new path.

The `settings.json` file was also updated.

After restarting the daemon, the text box in the settings UI (which was locked for interaction) reverted to the old location, but once HyperV was finished moving the storage, it updated to the new location.

**Comment by walkerjian** [comment]
Shouldn't have closed this off so soon, and should have tested 'solution' better - using move in Hyper-V manager moves file systems to new location but does not update kitematic. Kitematic has no easy way of seeing the new location as far as I can tell. There is huge confusion as to where Linux containers are stored, where windows containers are stored, where overlays are stored, where configuration files are stored, and there are no examples in the configuration file (settings.json) of valid file paths, the examples above just use very simple paths. To state clearly: the process of moving docker containers, images, configuration files from one location to another is both valid, needed and extremely poorly documented, leading to a great deal of confusion and wasted effort, and really angering a lot of people who are are trying to assess docker containerisation as a valid solution to the devops problem. I am trying to use docker as a means of getting on with a job without worrying about configuration and reproducibility issues and it just frustrates every reasonable request put on it.

**Comment by TBBle** [comment]
@walkerjian I suspect that by doing the move in Hyper-V Manager rather than the Docker for Windows UI, you have suffered a different issue.

**Comment by fengyuentau** [comment]
I am having the same issue. Docker is in the Linux container mode. Steps to reproduce the behavior:
1. right click the whale and exit
2. move "MobyLinuxVM" from "Hyper V Manager", "Choose Move Type" -> "Move the virtual machine's storage", "Choose Move Option" -> "Move all of the virtual machine's data to a single location", than choose a folder in another drive like "D:\docker-storage\"
3. restart docker
In Docker's settings -> Advanced, "Disk Image Location" is still the old one:
```shell
C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
```
Enter the path above, a new `MobyLinuxVM.vhdx` is created.
And value of `"MobyVhdPathOverride"` in `settings.json` is `null`.
Following @nategraf 's solution solved my problem.

**Comment by TBBle** [comment]
@fengyuentau That's correct, if you do the move from Hyper-V Manager (rather than the Docker for Windows UI), then Docker needs to have its configuration updated to the new location. There don't appear to be any problem reports left in this ticket that don't relate to moving the image in Hyper-V Manager.

Perhaps someone needs to open a feature request for Docker for Windows to detect/handle that, since it's clearly a desired use-case.

**Comment by TBBle** [comment]
I tested this *again* last week (against 18.09) and it still works to change the location in the Docker 'Advanced Settings' page as described in the original problem report.

If you're doing things in Hyper-V manager, then you're making it harder for yourself, because Docker for Windows is trying to manage that Hyper-V machine for you.

Changing the default folder for Virtual Hard Disk locations in Hyper-V host-machine settings is generally a good idea, the default location is... odd. But you don't need to uninstall Docker to move the image its already created.

**Comment by airyboy** [comment]
My workaround using the directory junction feature:
1. Quit Docker so as to be able to manipulate with the virtual disk file
1.1 For safety back up your MobyLinuxVM.vhdx file to some different location
2. Create a folder on the other disk, for example D:\docker-disk
3. Move MobyLinuxVM.vhdx into this folder
4. Open cmd (not  powershell) as Administrator
5. Create the dir junction with the command: 
`mklink /J "c:\Users\Public\Documents\Hyper-V\Virtual hard disks" "D:\docker-disk"`
6. Start Docker

**Comment by powertoaster** [comment]
Just tried it today (against 2.0.0.2) it does not move the location using either method.
Always reverts to default after restart.
Windows 10 17134.

**Comment by powertoaster** [comment]
codymullins, I had to do the exact same thing.
Which means that this bug was closed too soon, and still very much exists.

**Comment by arvind-subramanian** [comment]
@fengyuentau  @eliassal @powertoaster  - I think we should reopen this issue. Or at the very least, we should have better documentation about expected behavior and caveats, in the Docker settings UI. 
 
I am facing this on Version 2.0.0.3 (31259).  

Another thing I am noticing is that %APPDATA%\Docker\settings.json does not have the field ""MobyVhdPathOverride"  at all, for it to be changed to a new directory. Adding that field to the json file has no impact, and on docker restart, in the settings UI, we can see that change of directory isn't reflected. 

Would appreciate if someone has a workaround that actually works.

**Comment by TBBle** [comment]
@arvind-subramanian Based on the steps and checks I posted above, *which* problem are you facing?

As far as `MobyVhdPathOverride`, my `%APPDATA%\Docker\settings.json` contains a `diskPath` setting which points to my `MobyLinuxVM.vhdx`, matching _Disk image location_ in the Docker UI. I suspect that setting has been renamed sometime since 2017.

**Comment by arvind-subramanian** [comment]
@TBBle  - Thanks for your response! 

> Which problem am I facing ?

-> Not being able to change image  directory setting  in Docker For Windows. 

> my %APPDATA%\Docker\settings.json contains a diskPath setting 

I don't see the  "diskPath" in the settings.json in Docker For Windows (Version 2.0.0.3 (31259) ) 

I achieved changing the image directory path by 

1) Moving image in Hyper-V
2)Reinstalling docker for windows
3) Started with a clean slate, with no existing images. 

In this experiment, I had docker crash, did a reset as well.

**Comment by TBBle** [comment]
Okay, so you *didn't* do it through the Docker UI? I think you need a different bug then, this one was opened about moving the image via the Docker settings window.

If you didn't have `diskPath` there already, possibly it's added when you first move the image through the UI. The config file is not documented anywhere I've seen.

**Comment by arvind-subramanian** [comment]
> Okay, so you didn't do it through the Docker UI? I think you need a different bug then, this one was opened about moving the image via the Docker settings window.

Thanks for response, I apologize if I was not clear in my earlier message.

 **I observed the identical behavior  what  the bug reporter had described in the bug description in Docker for Windows Version 2.0.0.3 (31259) .** 

  Hence, I really do not think we would need another issue to address the same.  We could create a new issue if you feel if it is necessary. 

The only workaround for this issue which worked for me was nuking all images, changing image location directory  in  Hyper-V, and uninstalling and reinstalling docker for windows.

**Comment by TBBle** [comment]
The behaviour described in "Actual Behaviour" in the original bug report doesn't show a failure. That's Step 8 in my list of steps, so it's working-as-expected as far as that bug report tested.

So, to diagnose this issue for you: after the Docker UI reverted to displaying the old Path (Step 8), check the state versus the dot-points under Step 8, and check if it reaches Step 9 correctly.

Particularly important is what Hyper-V Manager shows, because the 'Move Disk Image' operation is all done in Hyper-V: Docker is just making the request to Hyper-V, and then *when it completes*, updating its settings to match the new location. Hyper-V takes care of redirecting image access etc. during the move, so until completed, Docker still sees the image at the old location.

Once we know that, we know where it's failing. It's possible Hyper-V is aborting the move internally for some reason, but I don't know off-hand how to diagnose that.

**Comment by carehart** [comment]
@TBBle Paul, thanks so much for your patience in this thread, and your great explanation of how we could watch the process of the move in Hyper-v. I can confirm that on my 2.0.0.3 version of Docker for Windows/Docker Desktop, on Win 10 Pro, with about 30g of containers, I did in fact have the move go as smoothly as you'd described.

Indeed, not only did the hyper-v UI showed the move happening but better still, the Docker for Windows (DfW) UI gave clear indication that it was doing the move (as soon as I clicked apply on the settings page where we'd point to the new location). It indicated that it was shutting down, then that it was in the process of moving the vhd, then when it was done. It also greyed out the location selection feature until it was done (I failed to pay attention, but I do believe it showed the NEW location the whole time). 

Also, the Windows status bar popped up reported the 3 similar steps (that DfW was shutting down, the move was happening, and that it had then restarted), and with audible sounds--such that I could walk away while it ran (about 1-2 minutes) and knew when it was done

I then confirmed that all the vxd had moved from its default location (C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\) to my newly chosen one: D:\Hyper-V\Virtual Hard Disks. And in the settings.json (where I, too, had no override element), I found that the "diskPath" element had changed from null to the new path.

I suspect part of the problem here (with people trying it via "manual" ways even in 2019, like moving the VHD in the hyper-v, or trying to edit that json file) may be that when they google how to do this move of the vhdx, the first few results are from 2018 and older...as indeed is this very post, suggesting those. (And I am really glad I didn't stop at that, but read down to your replies.)

I suppose back then the DfW UI did NOT so carefully let folks know what was going on. It may help for those having problems to update their DfW, and/or report the exact version of DfW they're on if they are still having trouble.

Now if only it could be as easy to move the image location for Windows Containers. :-(

**Comment by harrisdt15f** [comment]
I will show you how i done it step by step easily.

**Comment by harrisdt15f** [comment]
> I just tried this, and it seemed to work fine through the Docker for Windows UI. Docker restarted, and (since I had the HyperV Manager open) the HyperV Manager showed 'Moving storage' and moved the VHDX into the new path.
> 
> The `settings.json` file was also updated.
> 
> After restarting the daemon, the text box in the settings UI (which was locked for interaction) reverted to the old location, but once HyperV was finished moving the storage, it updated to the new location.

https://github.com/docker/for-win/issues/1589#issuecomment-489499702

**Comment by TBBle** [comment]
@harrisdt15f That set of screenshots you linked is exactly what Docker for Windows UI does for you when you change the location in the UI and hit "Apply", except it doesn't also change your Default Hyper-V storage location, it just updates its own configuration to find its own VHD.

**Comment by strugglingwittheselines** [comment]
I've tried to modify the path through Docker settings but it reverts back after the restart, and I wonder if there is any way to "sync" my available virtual disk (i.e: reinstalling windows....). So I have a fast workaround:

- If need to move the disk, go to Hyper-V Manager, click MobylinuxVM -> Move -> Follow the Prompts -> Then click Hyper-V Settings -> Change the Virtual Hard Disks to the folder which contains MobyLinuxVM.vhdx

- If you already have the disk in another place and want to use it (instead of new disk which Docker created), just go Hyper-V Settings and change the Virtual Hard Disks to the folder which contains your disk, that's all ! 
You can set the Virtual Machines Configuration file below Virtual Hard Disks as well but right now I don't use it (default configuration has no problem :D )

**Comment by strugglingwittheselines** [comment]
I've tried to modify the path through Docker settings but it reverts back after the restart, and I wonder if there is any way to "sync" my available virtual disk (i.e: reinstalling windows....). So I have a fast workaround:
- If you already have the disk in another place and want to use it (instead of new disk which Docker created), just go Hyper-V Settings and change the Virtual Hard Disks to the folder which contains your disk.

- If need to move the disk, go to Hyper-V Manager, click MobylinuxVM -> Move -> Follow the Prompts -> And then Follow the step #1 above, that's all !

You can set the Virtual Machines Configuration file below Virtual Hard Disks as well but right now I don't use it (default configuration has no problem :D )

**Comment by strugglingwittheselines** [comment]
I've tried to modify the path through Docker settings but it reverts back after the restart, and I wonder if there is any way to "sync" my available virtual disk (i.e: reinstalling windows....). So I have a fast workaround:

If you already have the disk in another place and want to use it (instead of new disk which Docker created), just go Hyper-V Settings and change the Virtual Hard Disks to the folder which contains your MobyLinuxVM.vhdx disk.

If you need to move the disk, go to Hyper-V Manager, click MobylinuxVM -> Move -> Follow the Prompts -> And then Follow the step #1 above, that's all !

You can set the Virtual Machines Configuration file below Virtual Hard Disks as well but right now I don't use it (No problem with the default configuration till now :D )

**Comment by zedzhu** [comment]
> I will show you how i did it step by step easily.
> below here is with picture descriptions.
> http://note.youdao.com/noteshare?id=5b2322cc30d6a3537b02b87d3bd1da4a

Very clear and it works for me!

**Comment by mmatrosov** [comment]
Worked flawlessly in docker 2.2.0.3. I changed location from the docker UI, clicked Apply & Restart, it was restarting for a minute while moving the disk image under the hood. Then it just started to work.
