### ISSUE TITLE
DFW on LCOW stoped working on the latest update

### ISSUE THREAD

**Issue by awidjaja** [docker/for-win#1590]
### Expected behavior

> Docker is running

### Actual behavior

> Error:
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass28_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 304
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

> F2099E05-3DBA-47DC-974B-B993D6042D1E/2018-01-21_17-22-47 

 - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

> OS Name: 	Microsoft Windows 10 Pro
Version:	10.0.16299 Build 16299
Docker Version: 18.01.0-ce-win48 (15285)
Channel: edge
ee22821

### Steps to reproduce the behavior

  1. install docker for windows 
  2. enable LCOW

(note: Linux container on VM also doesn't work as reported in the past. only when switching to windows container docker is running.)

**Comment by awidjaja** [comment]
ok in latest version
