### ISSUE TITLE
Windows Docker suddenly stopped working for me...

### ISSUE THREAD

**Issue by nickweavers** [docker/for-win#1595]
Unable to execute Start: Unable to create File System Image    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 256
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[15:41:52.588][NamedPipeClient][Error  ] Unable to send Start: Unable to create File System Image
[15:41:52.589][Notifications  ][Error  ] Unable to create File System Image

Where does it try to create this? I've checked I'm not low on disk space and I have 156GB unused.

**Comment by taylorb-microsoft** [comment]
Seems to be a dup of #1514.

**Comment by nickweavers** [comment]
Thanks, the diagnostic is F9A929A3-F71D-4746-9449-10E14C1AFF91/2018-01-22_15-44-13

**Comment by rn** [comment]
this looks like a dup of #1540 which turned out to be a Windows bug. You either need to be on insider build 17104+ or try the latest edge release of Docker for Windows.
