### ISSUE TITLE
Failed to start Docker in windwos 10 entperprise version

### ISSUE THREAD

**Issue by pras79** [docker/for-win#1611]
### Expected behavior
Docker  should up and run in the windows 10
### Actual behavior
Docker is failing to start 
### Information

'MobyLinuxVM' failed to start. (Virtual machine ID BBA2568F-A042-450B-8027-873FF69F1CA3)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID BBA2568F-A042-450B-8027-873FF69F1CA3).
at Start-MobyLinuxVM, <No file>: line 315
at <ScriptBlock>, <No file>: line 410    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 256
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[10:18:41.133][NamedPipeClient][Error  ] Unable to send Start: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID BBA2568F-A042-450B-8027-873FF69F1CA3)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID BBA2568F-A042-450B-8027-873FF69F1CA3).
at Start-MobyLinuxVM, <No file>: line 315
at <ScriptBlock>, <No file>: line 410
[10:18:41.133][Notifications  ][Error  ] Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID BBA2568F-A042-450B-8027-873FF69F1CA3)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID BBA2568F-A042-450B-8027-873FF69F1CA3).
at Start-MobyLinuxVM, <No file>: line 315
at <ScriptBlock>, <No file>: line 410

### Steps to reproduce the behavior

  1. ... install the docker in windows  enterprise 10 
  2. ...start the docker  and then it will fail to start and show the error message

**Comment by rn** [comment]
Could you please try the latest Docker for Windows version and upload and provide the diagnostics?
Thanks
