### ISSUE TITLE
Unable to start Docker

### ISSUE THREAD

**Issue by duprefm** [docker/for-win#1621]
### Information
  - Diagnostic ID 0169E4B4-C185-4206-9557-BB549E391595/2018-01-27_16-09-33.

Unable to create: L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Hyper-V n'a trouvé aucun commutateur virtuel portant le nom « DockerNAT ».
à New-Switch, <Aucun fichier> : ligne 119
à <ScriptBlock>, <Aucun fichier> : ligne 396
   à Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:ligne 36
   à Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:ligne 95
   à Docker.Actions.<>c__DisplayClass18_0.<Start>b__0() dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:ligne 81
   à Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() dans C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:ligne 59
  
### Steps to reproduce the behavior

  1. Desinstall Docker F for Windows
  2. Desable Hyper-V
  3. Reboot.
  4. Enable Hyper-V
  5. Install Docker.
[Crasjh-log-docker.txt](https://github.com/docker/for-win/files/1670184/Crasjh-log-docker.txt)

**Comment by jasonbivins** [comment]
Hi @duprefm   check to see if you have a DockerNAT virtual switch, or any duplicate switches - especially NAT

**Comment by Kralizek** [comment]
Having the same issue
```
External component has thrown an exception.
   at HVFiles.Connect(SafeSocket* , _GUID* , _GUID* , Int32 )
   at HVFiles.Connect(SafeSocket* , _GUID* partition, _GUID* service) in c:\gopath\src\github.com\docker\pinata\win\src\vendor\hvsock_cpp\includes\transport\connect.h:line 23
   at Docker.Win32Helpers.HVSockConnectivity.CheckConnectivity(Guid vmId, Guid serviceId) in c:\gopath\src\github.com\docker\pinata\win\src\docker.win32helpers\hvsockconnectivity.cpp:line 21
   at Docker.Backend.HvSockChecker.WaitForConnectivity(Guid vmId, Guid serviceId, TimeSpan timeout) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HVSockChecker.cs:line 26
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 291
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 260
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

**Comment by duprefm** [comment]
I can't create a virtual switch by script on my labtop. I think is the root cause of this problem.

**Comment by duprefm** [comment]
PS C:\WINDOWS\system32> powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1
" -create
Script started at 22:37:29.424
Module loaded at 22:37:33.463
Creating Switch: DockerNAT...
Hyper-V\Get-VMNetworkAdapter : Hyper-V n'a trouvé aucun commutateur virtuel portant le nom « DockerNAT ».
Au caractère C:\Program Files\Docker\Docker\resources\MobyLinux.ps1:117 : 25
+ ... etAdapter = Hyper-V\Get-VMNetworkAdapter -ManagementOS -SwitchName $S ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (DockerNAT:String) [Get-VMNetworkAdapter], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVMNetworkAdapter

**Comment by vsky279** [comment]
Having the same issue. It may be somehow linked to KB4074588 which I had big troubles with but in the end installed successfully (but not able to start Docker).
```
External component has thrown an exception.
   at HVFiles.Connect(SafeSocket* , _GUID* , _GUID* , Int32 )
   at HVFiles.Connect(SafeSocket* , _GUID* partition, _GUID* service) in c:\gopath\src\github.com\docker\pinata\win\src\vendor\hvsock_cpp\includes\transport\connect.h:line 23
   at Docker.Win32Helpers.HVSockConnectivity.CheckConnectivity(Guid vmId, Guid serviceId) in c:\gopath\src\github.com\docker\pinata\win\src\docker.win32helpers\hvsockconnectivity.cpp:line 21
   at Docker.Backend.HvSockChecker.WaitForConnectivity(Guid vmId, Guid serviceId, TimeSpan timeout) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HVSockChecker.cs:line 26
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 291
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 260
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```
