### ISSUE TITLE
IO Error after Windows Update

### ISSUE THREAD

**Issue by abductedMind** [docker/for-win#1625]
### Expected behavior
Able to build containers on Windows using Docker for Windows.

### Actual behavior
Receive the following instead
```
Step 1/11 : FROM php:7.1.11-apache-jessie
7.1.11-apache-jessie: Pulling from library/php
85b1f47fba49: DTraceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\main.py", line 959, in up
  File "compose\project.py", line 452, in up
  File "compose\service.py", line 308, in ensure_image_exists
  File "compose\service.py", line 972, in build
  File "compose\progress_stream.py", line 44, in stream_output
  File "compose\progress_stream.py", line 80, in print_output_event
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 169, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
Failed to execute script docker-compose
```

### Information
Diagnostic ID - E483219F-6C27-4F90-B954-81BDC03784DC/2018-01-28_13-30-22

### Steps to reproduce the behavior

  1. build any service from a docker compose file

My Windows updated last night and since then I have been unable to build new containers due to this IO error. The project itself works fine. Its in production and continues to be updated by other developers - and myself on my Macbook, which I am forced to use now that my Windows box doesn't build docker images.

I have factory reset, rebooted and reinstalled Docker for Windows at this point. I have officially given up until I see an update to DFW or a work around.

**Comment by fma-unitb** [comment]
Same issue here, output of "docker-compose up"

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\main.py", line 575, in logs
  File "compose\cli\log_printer.py", line 105, in run
  File "compose\cli\log_printer.py", line 109, in write
  File "codecs.py", line 370, in write
  File "site-packages\colorama\ansitowin32.py", line 40, in write
  File "site-packages\colorama\ansitowin32.py", line 141, in write
  File "site-packages\colorama\ansitowin32.py", line 166, in write_and_convert
  File "site-packages\colorama\ansitowin32.py", line 174, in write_plain_text
IOError: [Errno 0] Error
Failed to execute script docker-compose

**Comment by Jules-Baratoux** [comment]
Similar issue here: https://github.com/docker/compose/issues/5263 I guess.

**Comment by DanyD** [comment]
We have the same issue. Neither Powershell nor CMD works. We do not use an integrated terminal but the standalone shells of Win 10. The error renders the docker-compose tool quite useless at the moment with Windows.

**Comment by Silic0nS0ldier** [comment]
As mentioned over at the VS Code issue, this is due to a [known issue](https://github.com/Microsoft/vscode/issues/36630#issuecomment-350387362) in Windows. The good news is a fix has been made, the bad news is it'll be coming in the next feature update (and Insider builds before that, possibly out in current builds).

Some people have been lucky with this issue, in that they can just use another terminal, others less so. A possible work around at least 1 person has had luck with is to [switch on the legacy console option](https://github.com/Microsoft/vscode/issues/36630#issuecomment-358894887).

**Comment by abductedMind** [comment]
Working within the legacy cmd terminal works for me. The problem is isolated to docker-compose build as far as I can tell, so my other bash scripts still run. 

Not happy though! Not pointing fingers, but even if its a windows problem, Docker should push a fix for this to the stable track ASAP instead of waiting for the next feature release.

**Comment by Silic0nS0ldier** [comment]
Fix I mentioned should be out in the latest Windows 10 release (April 2018 Update). Worth double checking of course.

**Comment by Silic0nS0ldier** [comment]
I was using Docker for Windows for 2 hours within VS Code integrated terminal (issue manifested itself with high frequency in it) without issue. Should be good to close this.

**Comment by abductedMind** [comment]
This has been fixed.
