### ISSUE TITLE
'MobyLinuxVM' failed to start worker process after Windows update 1709 Build: 16299

### ISSUE THREAD

**Issue by cspainhour** [docker/for-win#1636]
### Expected behavior
Switch to Linux Container
### Actual behavior
An Error occurred.

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 8B97A348-F091-491D-B3A7-AEEA4C463F98)

'MobyLinuxVM' failed to start worker process: %%3228369022 (0xC06D007E). (Virtual machine ID 8B97A348-F091-491D-B3A7-AEEA4C463F98)
at Start-MobyLinuxVM, <No file>: line 315
at <ScriptBlock>, <No file>: line 410
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 256
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

### Information

  -A crash report has been uploaded, with the diagnostic ID:   
   09230F48-F3DB-44D3-8605-DD17A302B9EB/2018-01-25_07-04-07

   Version: 17.12.0-ce-win47 (15139)
   Channel: stable
   Sha1: 9c692cd5b38166289573183371647d915f300292
   Started on: 2018/01/25 07:02:50.432
   Resources: C:\Program Files\Docker\Docker\Resources
   OS: Windows 10 Enterprise
   Edition: Enterprise
   Id: 1709
   Build: 16299
   BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534

### Steps to reproduce the behavior

1.  Right click on docker icon
2. "Switch to Linux containers..."

**Comment by neeniya** [comment]
Got exactly the same issue. Sent in a crash report with diagnostic id: **DCF454E9-6130-481C-809B-903D8BD66458/2018-01-31_12-03-30** .

**Comment by aflopes** [comment]
I'm having the same issue, but in my case I think that it is related with https://community.sophos.com/kb/en-us/127797. I do have Sophos running in my laptop and I'm also not able to start any VM in Hyper-V manager.

**Comment by cspainhour** [comment]
I don't think my issue is related to Sophos, as I have disabled all Sophos Services, restarted, and received the same results.

**Comment by neeniya** [comment]
I have Sophos installed too, but it's not an option to disable it. I've just resorted to running Docker from a Linux VM.
