### ISSUE TITLE
Clean install fails , docker doesn't start diagnostics id 9649CE34-DD95-4C8F-9F9D-FBF8391D7692/2018-02-01_12-11-47

### ISSUE THREAD

**Issue by techmike2kx** [docker/for-win#1641]
### Expected behavior
install docker (either edge or stable)
start docker
### Actual behavior
install docker (either edge or stable)
start docker
docker crashes 

### Information
propagated error :
`Unable to create File System Image
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 95
   at Docker.Actions.<>c__DisplayClass18_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 81
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59`

  - Diagnostic ID: 9649CE34-DD95-4C8F-9F9D-FBF8391D7692/2018-02-01_12-11-47
  - host distribution and version : docker for windows 18.02.0-ce-rc1-win50 (15489)

**Comment by strmpnk** [comment]
I've been seeing this same issue. Does Docker have any official statement on this? It's been broken for weeks now. It's a bit sad that the old Docker Toolkit is the only reliable way to get working linux containers on my machines. (I've also tried LCOW with the new experimental features in Edge and they hang indefinitely after pulling down an image, so I never successfully start anything).

**Comment by neowizmaster** [comment]
I seem to be having the same issue. Diagnostic IDs
B55E5166-3E9D-4E05-BA1E-8A9834C2A68E/2018-02-06_13-54-33
B55E5166-3E9D-4E05-BA1E-8A9834C2A68E/2018-02-06_14-57-40

Version 17.12.0-ce-win47 (15139)
Channel: stable
9c692cd

It seems to be a general issue.

**Comment by rn** [comment]
this looks like a dup of #1540 which turned out to be a Windows bug. You either need to be on insider build 17104+ or try the latest edge release of Docker for Windows.
