### ISSUE TITLE
Docker ran fine for 2 days then broke on reboot

### ISSUE THREAD

**Issue by cdeli** [docker/for-win#1645]
Formatted my computer and now Docker seems to not work at all. Following is the error

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID A3BDFCB6-2388-41FC-A090-CA88B6EA2CEC)

'MobyLinuxVM' failed to start worker process: %%3228369022 (0xC06D007E). (Virtual machine ID A3BDFCB6-2388-41FC-A090-CA88B6EA2CEC)
at Start-MobyLinuxVM, <No file>: line 315
at <ScriptBlock>, <No file>: line 410
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 256
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

Below is the log

Version: 17.12.0-ce-win47 (15139)
Channel: stable
Sha1: 9c692cd5b38166289573183371647d915f300292
Started on: 2018/02/01 11:57:42.269
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299
BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534
File: C:\Users\iwifi\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:57:42.593][GUI            ][Info   ] Starting...
[11:57:45.125][Tracking       ][Info   ] Crash report and usage statistics are enabled
[11:57:45.128][SegmentApi     ][Info   ] Usage statistic: appLaunched
[11:57:45.880][NPS            ][Info   ] NPS user ceated on :1/30/2018 2:34:49 PM -08:00, last survey : 1/1/0001 12:00:00 AM +00:00
[11:57:45.882][SegmentApi     ][Info   ] Usage statistic: heartbeat
[11:57:45.884][SegmentApi     ][Info   ] Usage statistic: Identify
[11:57:46.310][Notifications  ][Info   ] Docker is starting...
[11:57:46.332][NamedPipeClient][Info   ] Sending Version()...
[11:57:46.356][NamedPipeClient][Info   ] Received response for Version
[11:57:46.365][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[11:57:46.342][NamedPipeServer][Info   ] Version done in 00:00:00.
[11:57:46.369][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
[11:57:46.369][PowerMode      ][Info   ] Stop
[11:57:46.369][HyperV         ][Info   ] Stop
[11:57:46.370][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:57:46.374][HyperV         ][Info   ] Script started at 11:57:46.373
[11:57:46.386][HyperV         ][Info   ] Module loaded at 11:57:46.386
[11:57:46.401][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:57:46.402][HyperV         ][Debug  ] [stop] took 00:00:00.0330015 to run
[11:57:46.402][OptimizeDisk   ][Info   ] Optimize
[11:57:46.402][PowerShell     ][Info   ] Run script...
[11:57:46.413][Moby           ][Info   ] Stop
[11:57:46.416][HyperV         ][Info   ] Create
[11:57:46.417][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[11:57:46.419][HyperVGuids    ][Info   ] Installing GUIDs...
[11:57:46.422][HyperV         ][Info   ] Script started at 11:57:46.422
[11:57:46.426][HyperVGuids    ][Info   ] GUIDs installed
[11:57:46.426][PowerMode      ][Info   ] Start
[11:57:46.426][Firewall       ][Info   ] Removing all existing rules...
[11:57:46.432][HyperV         ][Info   ] Module loaded at 11:57:46.431
[11:57:46.448][Firewall       ][Info   ] All existing rules are removed.
[11:57:46.448][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[11:57:46.479][Firewall       ][Info   ] Opening ports for SMB...
[11:57:46.507][Firewall       ][Info   ] Ports are opened
[11:57:46.686][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:57:48.214][HyperV         ][Info   ] Switch created.
[11:57:49.452][HyperV         ][Info   ] Set IP address on switch
[11:57:49.468][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[11:57:50.218][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[11:57:50.387][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[11:57:50.671][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[11:57:50.760][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[11:57:51.065][HyperV         ][Info   ] Disabled Guest Service Interface
[11:57:51.075][HyperV         ][Info   ] Enabled Heartbeat
[11:57:51.091][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[11:57:51.102][HyperV         ][Info   ] Enabled Shutdown
[11:57:51.111][HyperV         ][Info   ] Enabled Time Synchronization
[11:57:51.126][HyperV         ][Info   ] Disabled VSS
[11:57:51.343][HyperV         ][Info   ] VM created.
[11:57:51.343][HyperV         ][Debug  ] [create] took 00:00:04.9266551 to run
[11:57:51.343][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[11:57:51.360][Database       ][Info   ] Generating CA Cert Bundle
[11:57:51.371][Database       ][Info   ] CA Cert Bundle Generated
[11:57:51.384][Moby           ][Info   ] Connecting...
[11:57:51.384][Moby           ][Error  ] Failed to read Moby's logs: The operation has timed out.
[11:57:51.385][HyperV         ][Info   ] Start
[11:57:51.385][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[11:57:51.385][PowerShell     ][Info   ] Run script with parameters: -Start True -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso -confIsoFile C:\ProgramData\Docker\tmp-d4w\config.iso...
[11:57:51.391][HyperV         ][Info   ] Script started at 11:57:51.390
[11:57:51.408][HyperV         ][Info   ] Module loaded at 11:57:51.408
[11:57:51.410][HyperV         ][Info   ] Starting VM MobyLinuxVM...
[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Setting handler to ignore all SIGPIPE signals

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Version %VERSION% from %VCS_COMMIT_ID%

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: System SOMAXCONN is 2147483647

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Will use a listen backlog of 32

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Starting port forwarding server on port_control_url:"hyperv-connect://9bc3c762-39af-4fdb-8f5e-1ab6b90ca14d" vsock_path:""

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Removed connection limit

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Connecting to 9bc3c762-39af-4fdb-8f5e-1ab6b90ca14d:0B95756A-9985-48AD-9470-78E060895BE7

[11:57:51.870][VpnKit         ][Warning] vpnkit.exe: There is no database: using hardcoded network configuration values

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: DNS server configured with no builtin DNS names; everything will be forwarded

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: 2 upstream DNS servers are configured

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Disabling transparent HTTP redirection

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Updating resolvers to use upstream DNS servers 

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Secure random number generator is available

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Add(3): DNS configuration changed to: use upstream DNS servers 

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: DNS server configured with builtin DNS names [ docker.for.win.gateway.internal -> 192.168.65.1, docker.for.win.http.internal -> 192.168.65.1, docker.for.win.localhost -> 192.168.65.2, docker.for.win.host.internal -> 192.168.65.2 ]

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: 0 upstream DNS servers are configured

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: DNS configuration file C:\Users\iwifi\AppData\Roaming\Docker\resolv.conf has changed

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Reading DNS configuration from C:\Users\iwifi\AppData\Roaming\Docker\resolv.conf

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Watching DNS configuration file C:\Users\iwifi\AppData\Roaming\Docker\resolv.conf for changes

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: DHCP configuration file C:\Users\iwifi\AppData\Roaming\Docker\dhcp.json has changed

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Reading DHCP configuration file from C:\Users\iwifi\AppData\Roaming\Docker\dhcp.json

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Watching DHCP configuration file C:\Users\iwifi\AppData\Roaming\Docker\dhcp.json for changes

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Configuration server_macaddr = f6:16:36:bc:f9:c6; max_connection = None; dns_path = C:\Users\iwifi\AppData\Roaming\Docker\resolv.conf; dns = ; resolver = Upstream; domain = None; allowed_bind_addresses = 0.0.0.0; gateway_ip = 192.168.65.1; host_ip = 192.168.65.2; lowest_ip = 192.168.65.3; highest_ip = 192.168.65.254; dhcp_json_path = C:\Users\iwifi\AppData\Roaming\Docker\dhcp.json; dhcp_configuration = None; mtu = 1500; http_intercept = None; http_intercept_path = None; port_max_idle_time = 30; host_names = docker.for.win.localhost, docker.for.win.host.internal; gateway_name = docker.for.win.gateway.internal, docker.for.win.http.internal

[11:57:51.870][VpnKit         ][Info   ] vpnkit.exe: Connecting to 9bc3c762-39af-4fdb-8f5e-1ab6b90ca14d:30D48B34-7D27-4B0B-AAAF-BBBED334DD59

[11:57:51.871][VpnKit         ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT

[11:57:51.872][VpnKit         ][Info   ] vpnkit.exe: C:\Windows\System32\drivers\etc\hosts file has bindings for 

[11:57:51.872][VpnKit         ][Info   ] vpnkit.exe: Updating DNS configuration to nameserver 192.168.1.1#53

[11:57:51.872][VpnKit         ][Info   ] order 0

[11:57:51.872][VpnKit         ][Info   ] vpnkit.exe: Updating resolvers to use upstream DNS servers nameserver 192.168.1.1#53

[11:57:51.872][VpnKit         ][Info   ] order 0

[11:57:51.872][VpnKit         ][Info   ] vpnkit.exe: Secure random number generator is available

[11:57:51.872][VpnKit         ][Info   ] vpnkit.exe: Remove(3): DNS configuration changed to: use upstream DNS servers nameserver 8.8.8.8#53

[11:57:51.872][VpnKit         ][Info   ] timeout 2000

[11:57:51.872][VpnKit         ][Info   ] order 0

[11:57:51.872][VpnKit         ][Info   ] nameserver 8.8.4.4#53

[11:57:51.872][VpnKit         ][Info   ] timeout 2000

[11:57:51.872][VpnKit         ][Info   ] order 0

[11:57:51.872][VpnKit         ][Info   ] vpnkit.exe: Add(3): DNS configuration changed to: use upstream DNS servers nameserver 192.168.1.1#53

[11:57:51.872][VpnKit         ][Info   ] order 0

[11:57:51.872][VpnKit         ][Info   ] vpnkit.exe: DNS server configured with builtin DNS names [ docker.for.win.gateway.internal -> 192.168.65.1, docker.for.win.http.internal -> 192.168.65.1, docker.for.win.localhost -> 192.168.65.2, docker.for.win.host.internal -> 192.168.65.2 ]

[11:57:51.872][VpnKit         ][Info   ] vpnkit.exe: 1 upstream DNS servers are configured

[11:57:51.872][VpnKit         ][Info   ] vpnkit.exe: Update DHCP configuration to { searchDomains = fios-router.home; domainName = fios-router.home }

[11:57:51.904][HyperV         ][Info   ] Remove existing DVDs
[11:57:52.134][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[11:57:52.218][HyperV         ][Info   ] Attach Config ISO C:\ProgramData\Docker\tmp-d4w\config.iso
[11:57:53.100][Linux          ][Error  ] Failed to start: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 9BC3C762-39AF-4FDB-8F5E-1AB6B90CA14D)

'MobyLinuxVM' failed to start worker process: %%3228369022 (0xC06D007E). (Virtual machine ID 9BC3C762-39AF-4FDB-8F5E-1AB6B90CA14D)
at Start-MobyLinuxVM, <No file>: line 315
at <ScriptBlock>, <No file>: line 410. Let's retry
[11:57:55.388][HyperV         ][Info   ] Hyper-V is running
[11:57:55.388][PowerMode      ][Info   ] Stop
[11:57:55.389][HyperV         ][Info   ] Stop
[11:57:55.389][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:57:55.393][HyperV         ][Info   ] Script started at 11:57:55.393
[11:57:55.414][HyperV         ][Info   ] Module loaded at 11:57:55.414
[11:57:55.438][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[11:57:55.438][HyperV         ][Debug  ] [stop] took 00:00:00.0495016 to run
[11:57:55.438][OptimizeDisk   ][Info   ] Optimize
[11:57:55.438][PowerShell     ][Info   ] Run script...
[11:57:56.542][Moby           ][Info   ] Stop
[11:57:56.548][VpnKit         ][Info   ] Killing existing vpnkit with PID 14360
[11:57:56.552][HyperV         ][Info   ] Destroy
[11:57:56.553][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[11:57:56.556][HyperV         ][Info   ] Script started at 11:57:56.556
[11:57:56.566][HyperV         ][Info   ] Module loaded at 11:57:56.566
[11:57:56.578][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[11:57:56.578][HyperV         ][Info   ] Destroying Switch DockerNAT...
[11:57:57.196][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[11:57:57.248][HyperV         ][Debug  ] [destroy] took 00:00:00.6955011 to run
[11:57:57.248][Firewall       ][Info   ] Closing ports...
[11:57:57.248][Firewall       ][Info   ] Removing all existing rules...
[11:57:57.306][Firewall       ][Info   ] All existing rules are removed.
[11:57:57.306][Firewall       ][Info   ] Ports are closed
[11:57:57.306][HyperVGuids    ][Info   ] Removing GUIDs...
[11:57:57.307][HyperVGuids    ][Info   ] GUIDs removed
[11:57:57.307][HyperV         ][Info   ] Create
[11:57:57.308][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[11:57:57.311][HyperV         ][Info   ] Script started at 11:57:57.311
[11:57:57.330][HyperV         ][Info   ] Module loaded at 11:57:57.330
[11:57:57.452][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:57:58.336][HyperV         ][Info   ] Switch created.
[11:57:58.930][HyperV         ][Info   ] Set IP address on switch
[11:57:58.940][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[11:57:59.527][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[11:57:59.701][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[11:57:59.985][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[11:58:00.080][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[11:58:00.404][HyperV         ][Info   ] Disabled Guest Service Interface
[11:58:00.414][HyperV         ][Info   ] Enabled Heartbeat
[11:58:00.432][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[11:58:00.444][HyperV         ][Info   ] Enabled Shutdown
[11:58:00.454][HyperV         ][Info   ] Enabled Time Synchronization
[11:58:00.468][HyperV         ][Info   ] Disabled VSS
[11:58:00.686][HyperV         ][Info   ] VM created.
[11:58:00.687][HyperV         ][Debug  ] [create] took 00:00:03.3792624 to run
[11:58:00.687][PowerMode      ][Info   ] Stop
[11:58:00.687][HyperV         ][Info   ] Stop
[11:58:00.688][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:58:00.693][HyperV         ][Info   ] Script started at 11:58:00.693
[11:58:00.703][HyperV         ][Info   ] Module loaded at 11:58:00.703
[11:58:00.720][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[11:58:00.720][HyperV         ][Debug  ] [stop] took 00:00:00.0329994 to run
[11:58:00.720][OptimizeDisk   ][Info   ] Optimize
[11:58:00.720][PowerShell     ][Info   ] Run script...
[11:58:01.950][Moby           ][Info   ] Stop
[11:58:01.956][HyperV         ][Info   ] Create
[11:58:01.956][HyperVGuids    ][Info   ] Installing GUIDs...
[11:58:01.957][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[11:58:01.958][HyperVGuids    ][Info   ] GUIDs installed
[11:58:01.958][PowerMode      ][Info   ] Start
[11:58:01.959][Firewall       ][Info   ] Removing all existing rules...
[11:58:01.960][HyperV         ][Info   ] Script started at 11:58:01.960
[11:58:01.973][HyperV         ][Info   ] Module loaded at 11:58:01.973
[11:58:01.983][Firewall       ][Info   ] All existing rules are removed.
[11:58:01.983][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[11:58:01.991][Firewall       ][Info   ] Opening ports for SMB...
[11:58:02.009][Firewall       ][Info   ] Ports are opened
[11:58:02.087][HyperV         ][Info   ] Using existing Switch: DockerNAT
[11:58:08.044][HyperV         ][Info   ] Using existing Switch IP address
[11:58:08.069][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[11:58:08.356][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[11:58:08.606][HyperV         ][Info   ] Remove existing DVDs
[11:58:08.818][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[11:58:09.151][HyperV         ][Info   ] Disabled Guest Service Interface
[11:58:09.164][HyperV         ][Info   ] Enabled Heartbeat
[11:58:09.174][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[11:58:09.187][HyperV         ][Info   ] Enabled Shutdown
[11:58:09.200][HyperV         ][Info   ] Enabled Time Synchronization
[11:58:09.212][HyperV         ][Info   ] Disabled VSS
[11:58:09.290][HyperV         ][Info   ] VM created.
[11:58:09.291][HyperV         ][Debug  ] [create] took 00:00:07.3344699 to run
[11:58:09.291][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[11:58:09.300][Database       ][Info   ] Generating CA Cert Bundle
[11:58:09.311][Database       ][Info   ] CA Cert Bundle Generated
[11:58:09.324][Moby           ][Info   ] Connecting...
[11:58:09.324][Moby           ][Error  ] Failed to read Moby's logs: The operation has timed out.
[11:58:09.324][HyperV         ][Info   ] Start
[11:58:09.325][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[11:58:09.325][PowerShell     ][Info   ] Run script with parameters: -Start True -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso -confIsoFile C:\ProgramData\Docker\tmp-d4w\config.iso...
[11:58:09.328][HyperV         ][Info   ] Script started at 11:58:09.328
[11:58:09.339][HyperV         ][Info   ] Module loaded at 11:58:09.339
[11:58:09.348][HyperV         ][Info   ] Starting VM MobyLinuxVM...
[11:58:09.419][HyperV         ][Info   ] Remove existing DVDs
[11:58:09.689][VpnKit         ][Info   ] vpnkit.exe: Setting handler to ignore all SIGPIPE signals

[11:58:09.689][VpnKit         ][Info   ] vpnkit.exe: Version %VERSION% from %VCS_COMMIT_ID%

[11:58:09.689][VpnKit         ][Info   ] vpnkit.exe: System SOMAXCONN is 2147483647

[11:58:09.689][VpnKit         ][Info   ] vpnkit.exe: Will use a listen backlog of 32

[11:58:09.689][VpnKit         ][Info   ] vpnkit.exe: Starting port forwarding server on port_control_url:"hyperv-connect://a3bdfcb6-2388-41fc-a090-ca88b6ea2cec" vsock_path:""

[11:58:09.689][VpnKit         ][Info   ] vpnkit.exe: Removed connection limit

[11:58:09.689][VpnKit         ][Info   ] vpnkit.exe: Connecting to a3bdfcb6-2388-41fc-a090-ca88b6ea2cec:0B95756A-9985-48AD-9470-78E060895BE7

[11:58:09.689][VpnKit         ][Warning] vpnkit.exe: There is no database: using hardcoded network configuration values

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: DNS server configured with no builtin DNS names; everything will be forwarded

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: 2 upstream DNS servers are configured

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: Disabling transparent HTTP redirection

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: Updating resolvers to use upstream DNS servers 

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: Secure random number generator is available

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: Add(3): DNS configuration changed to: use upstream DNS servers 

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: DNS server configured with builtin DNS names [ docker.for.win.gateway.internal -> 192.168.65.1, docker.for.win.http.internal -> 192.168.65.1, docker.for.win.localhost -> 192.168.65.2, docker.for.win.host.internal -> 192.168.65.2 ]

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: 0 upstream DNS servers are configured

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: DNS configuration file C:\Users\iwifi\AppData\Roaming\Docker\resolv.conf has changed

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: Reading DNS configuration from C:\Users\iwifi\AppData\Roaming\Docker\resolv.conf

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: Watching DNS configuration file C:\Users\iwifi\AppData\Roaming\Docker\resolv.conf for changes

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: DHCP configuration file C:\Users\iwifi\AppData\Roaming\Docker\dhcp.json has changed

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: Reading DHCP configuration file from C:\Users\iwifi\AppData\Roaming\Docker\dhcp.json

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: Watching DHCP configuration file C:\Users\iwifi\AppData\Roaming\Docker\dhcp.json for changes

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: Configuration server_macaddr = f6:16:36:bc:f9:c6; max_connection = None; dns_path = C:\Users\iwifi\AppData\Roaming\Docker\resolv.conf; dns = ; resolver = Upstream; domain = None; allowed_bind_addresses = 0.0.0.0; gateway_ip = 192.168.65.1; host_ip = 192.168.65.2; lowest_ip = 192.168.65.3; highest_ip = 192.168.65.254; dhcp_json_path = C:\Users\iwifi\AppData\Roaming\Docker\dhcp.json; dhcp_configuration = None; mtu = 1500; http_intercept = None; http_intercept_path = None; port_max_idle_time = 30; host_names = docker.for.win.localhost, docker.for.win.host.internal; gateway_name = docker.for.win.gateway.internal, docker.for.win.http.internal

[11:58:09.690][VpnKit         ][Info   ] vpnkit.exe: Connecting to a3bdfcb6-2388-41fc-a090-ca88b6ea2cec:30D48B34-7D27-4B0B-AAAF-BBBED334DD59

[11:58:09.695][VpnKit         ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT

[11:58:09.697][VpnKit         ][Info   ] vpnkit.exe: C:\Windows\System32\drivers\etc\hosts file has bindings for 

[11:58:09.697][VpnKit         ][Info   ] vpnkit.exe: Updating DNS configuration to nameserver 192.168.1.1#53

[11:58:09.697][VpnKit         ][Info   ] order 0

[11:58:09.697][VpnKit         ][Info   ] vpnkit.exe: Updating resolvers to use upstream DNS servers nameserver 192.168.1.1#53

[11:58:09.697][VpnKit         ][Info   ] order 0

[11:58:09.697][VpnKit         ][Info   ] vpnkit.exe: Secure random number generator is available

[11:58:09.697][VpnKit         ][Info   ] vpnkit.exe: Remove(3): DNS configuration changed to: use upstream DNS servers nameserver 8.8.8.8#53

[11:58:09.697][VpnKit         ][Info   ] timeout 2000

[11:58:09.697][VpnKit         ][Info   ] order 0

[11:58:09.697][VpnKit         ][Info   ] nameserver 8.8.4.4#53

[11:58:09.697][VpnKit         ][Info   ] timeout 2000

[11:58:09.697][VpnKit         ][Info   ] order 0

[11:58:09.697][VpnKit         ][Info   ] vpnkit.exe: Add(3): DNS configuration changed to: use upstream DNS servers nameserver 192.168.1.1#53

[11:58:09.697][VpnKit         ][Info   ] order 0

[11:58:09.697][VpnKit         ][Info   ] vpnkit.exe: DNS server configured with builtin DNS names [ docker.for.win.gateway.internal -> 192.168.65.1, docker.for.win.http.internal -> 192.168.65.1, docker.for.win.localhost -> 192.168.65.2, docker.for.win.host.internal -> 192.168.65.2 ]

[11:58:09.697][VpnKit         ][Info   ] vpnkit.exe: 1 upstream DNS servers are configured

[11:58:09.697][VpnKit         ][Info   ] vpnkit.exe: Update DHCP configuration to { searchDomains = fios-router.home; domainName = fios-router.home }

[11:58:09.765][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[11:58:09.852][HyperV         ][Info   ] Attach Config ISO C:\ProgramData\Docker\tmp-d4w\config.iso
[11:58:10.766][PowerMode      ][Info   ] Stop
[11:58:10.766][HyperV         ][Info   ] Stop
[11:58:10.766][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:58:10.776][HyperV         ][Info   ] Script started at 11:58:10.776
[11:58:10.792][HyperV         ][Info   ] Module loaded at 11:58:10.791
[11:58:10.807][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[11:58:10.807][HyperV         ][Debug  ] [stop] took 00:00:00.0410045 to run
[11:58:10.808][OptimizeDisk   ][Info   ] Optimize
[11:58:10.808][PowerShell     ][Info   ] Run script...
[11:58:11.907][Moby           ][Info   ] Stop
[11:58:11.911][VpnKit         ][Info   ] Killing existing vpnkit with PID 14748
[11:58:11.917][HyperV         ][Info   ] Destroy
[11:58:11.918][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[11:58:11.924][HyperV         ][Info   ] Script started at 11:58:11.924
[11:58:11.933][HyperV         ][Info   ] Module loaded at 11:58:11.933
[11:58:11.944][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[11:58:11.945][HyperV         ][Info   ] Destroying Switch DockerNAT...
[11:58:12.403][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[11:58:12.446][HyperV         ][Debug  ] [destroy] took 00:00:00.5285493 to run
[11:58:12.446][Firewall       ][Info   ] Closing ports...
[11:58:12.446][Firewall       ][Info   ] Removing all existing rules...
[11:58:12.501][Firewall       ][Info   ] All existing rules are removed.
[11:58:12.501][Firewall       ][Info   ] Ports are closed
[11:58:12.501][HyperVGuids    ][Info   ] Removing GUIDs...
[11:58:12.781][NamedPipeClient][Error  ] Unable to send Start: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID A3BDFCB6-2388-41FC-A090-CA88B6EA2CEC)

'MobyLinuxVM' failed to start worker process: %%3228369022 (0xC06D007E). (Virtual machine ID A3BDFCB6-2388-41FC-A090-CA88B6EA2CEC)
at Start-MobyLinuxVM, <No file>: line 315
at <ScriptBlock>, <No file>: line 410
[11:58:12.782][Notifications  ][Error  ] Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID A3BDFCB6-2388-41FC-A090-CA88B6EA2CEC)

'MobyLinuxVM' failed to start worker process: %%3228369022 (0xC06D007E). (Virtual machine ID A3BDFCB6-2388-41FC-A090-CA88B6EA2CEC)
at Start-MobyLinuxVM, <No file>: line 315
at <ScriptBlock>, <No file>: line 410
[11:58:12.502][HyperVGuids    ][Info   ] GUIDs removed
[11:58:12.502][NamedPipeServer][Error  ] Unable to execute Start: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID A3BDFCB6-2388-41FC-A090-CA88B6EA2CEC)

'MobyLinuxVM' failed to start worker process: %%3228369022 (0xC06D007E). (Virtual machine ID A3BDFCB6-2388-41FC-A090-CA88B6EA2CEC)
at Start-MobyLinuxVM, <No file>: line 315
at <ScriptBlock>, <No file>: line 410    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 256
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[11:58:22.129][ErrorReportWindow][Info   ] Open logs

Anyone have any idea's??

**Comment by jasonbivins** [comment]
Hi @cdeli   Check Hyper-V to make sure it's running.  Can you create and connect to any VM's there?
