### ISSUE TITLE
An error occured after installation - Unable to create File System Image

### ISSUE THREAD

**Issue by ocoyawale** [docker/for-win#1653]
I just installed Docker on my laptop but after installation, there is a display of an error message:

**Unable to create File System Image**
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 95
   at Docker.Actions.<>c__DisplayClass18_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 81
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Expected behavior

install docker (either edge or stable)
start docker

### Actual behavior

install docker 
start docker
docker crashes with error message

### Information
Diagnostic ID :41FB48A9-C844-43C8-8A51-B24D03970C5B/2018-02-03_17-36-59

OS: Windows 10 Pro Insider Preview
Edition: Professional
Id: 1709
Build: 17074
BuildLabName: 17074.1002.amd64fre.rs_prerelease_flt.180116-1539

Error Log Message:

Version: 17.12.0-ce-win47 (15139)
Channel: stable
Sha1: 9c692cd5b38166289573183371647d915f300292
Started on: 2018/02/03 17:24:42.355
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro Insider Preview
Edition: Professional
Id: 1709
Build: 17074
BuildLabName: 17074.1002.amd64fre.rs_prerelease_flt.180116-1539
File: C:\Users\PROF\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[17:24:58.640][GUI            ][Info   ] Starting...
[17:25:30.988][Tracking       ][Info   ] Crash report and usage statistics are enabled
[17:25:30.988][SegmentApi     ][Info   ] Usage statistic: appLaunched
[17:25:43.769][SegmentApi     ][Error  ] Failed to track event appLaunched: timeout after 10s
[17:25:44.535][GUI            ][Error  ] Error while trying to run NPS survey process.Unable to create an instance of Docker.WPF.Nps.NPS: Unable to create an instance of Docker.WPF.Nps.WootricService
[17:25:44.551][SegmentApi     ][Info   ] Usage statistic: heartbeat
[17:25:44.551][SegmentApi     ][Error  ] Failed to track event heartbeat: An error occurred while sending the request.
[17:25:44.566][SegmentApi     ][Info   ] Usage statistic: Identify
[17:25:44.629][SegmentApi     ][Error  ] Failed to Identify: An error occurred while sending the request.
[17:25:47.051][NamedPipeClient][Info   ] Sending Version()...
[17:26:15.038][NamedPipeClient][Info   ] Sending Version()...
[17:26:15.366][NamedPipeClient][Info   ] Received response for Version
[17:26:15.366][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[17:26:13.069][BackendServer  ][Info   ] Started
[17:26:15.272][NamedPipeServer][Info   ] Version()
[17:26:15.272][NamedPipeServer][Info   ] Version done in 00:00:00.
[17:26:15.397][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
[17:26:15.491][PowerMode      ][Info   ] Stop
[17:26:16.350][HyperV         ][Info   ] Stop
[17:26:17.460][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[17:26:19.304][PowerShell     ][Info   ] Creating a Runspace Pool...
[17:27:24.620][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[17:27:41.902][HyperV         ][Info   ] Script started at 17:27:41.792
[17:28:38.507][HyperV         ][Info   ] Module loaded at 17:28:38.507
[17:28:45.572][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[17:28:45.588][HyperV         ][Debug  ] [stop] took 00:02:28.6593718 to run
[17:28:45.588][OptimizeDisk   ][Info   ] Optimize
[17:28:45.588][PowerShell     ][Info   ] Run script...
[17:28:45.619][Moby           ][Info   ] Stop
[17:28:45.775][HyperVGuids    ][Info   ] Installing GUIDs...
[17:28:45.775][PowerMode      ][Info   ] Start
[17:28:45.775][HyperV         ][Info   ] Create
[17:28:45.775][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[17:28:45.775][HyperVGuids    ][Info   ] GUIDs installed
[17:28:45.791][Firewall       ][Info   ] Removing all existing rules...
[17:28:46.025][HyperV         ][Info   ] Script started at 17:28:46.025
[17:28:46.057][HyperV         ][Info   ] Module loaded at 17:28:46.057
[17:28:46.476][Firewall       ][Info   ] All existing rules are removed.
[17:28:46.476][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[17:28:46.492][Firewall       ][Info   ] Opening ports for SMB...
[17:28:46.507][Firewall       ][Info   ] Ports are opened
[17:28:49.824][HyperV         ][Info   ] Creating Switch: DockerNAT...
[17:28:54.885][HyperV         ][Info   ] Switch created.
[17:28:59.241][HyperV         ][Info   ] Set IP address on switch
[17:29:07.647][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[17:29:13.483][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[17:29:16.603][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[17:29:17.998][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[17:29:18.719][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[17:29:20.128][HyperV         ][Info   ] Disabled Guest Service Interface
[17:29:20.159][HyperV         ][Info   ] Enabled Heartbeat
[17:29:20.288][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[17:29:20.318][HyperV         ][Info   ] Enabled Shutdown
[17:29:20.338][HyperV         ][Info   ] Enabled Time Synchronization
[17:29:20.500][HyperV         ][Info   ] Disabled VSS
[17:29:21.854][HyperV         ][Info   ] VM created.
[17:29:21.855][HyperV         ][Debug  ] [create] took 00:00:36.0793696 to run
[17:29:21.856][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[17:29:22.034][Database       ][Info   ] Generating CA Cert Bundle
[17:29:22.112][Database       ][Info   ] CA Cert Bundle Generated
[17:29:22.235][Linux          ][Error  ] Failed to start: Unable to create File System Image. Let's retry
[17:29:22.323][HyperV         ][Info   ] Hyper-V is running
[17:29:22.323][PowerMode      ][Info   ] Stop
[17:29:22.323][HyperV         ][Info   ] Stop
[17:29:22.324][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[17:29:22.338][HyperV         ][Info   ] Script started at 17:29:22.338
[17:29:22.350][HyperV         ][Info   ] Module loaded at 17:29:22.350
[17:29:22.385][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[17:29:22.385][HyperV         ][Debug  ] [stop] took 00:00:00.0619976 to run
[17:29:22.385][OptimizeDisk   ][Info   ] Optimize
[17:29:22.385][PowerShell     ][Info   ] Run script...
[17:29:23.880][Moby           ][Info   ] Stop
[17:29:23.896][HyperV         ][Info   ] Destroy
[17:29:23.897][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[17:29:23.908][HyperV         ][Info   ] Script started at 17:29:23.908
[17:29:23.918][HyperV         ][Info   ] Module loaded at 17:29:23.918
[17:29:23.940][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[17:29:23.942][HyperV         ][Info   ] Destroying Switch DockerNAT...
[17:29:25.216][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[17:29:25.622][HyperV         ][Debug  ] [destroy] took 00:00:01.7251746 to run
[17:29:25.637][Firewall       ][Info   ] Closing ports...
[17:29:25.637][Firewall       ][Info   ] Removing all existing rules...
[17:29:25.746][Firewall       ][Info   ] All existing rules are removed.
[17:29:25.746][Firewall       ][Info   ] Ports are closed
[17:29:25.746][HyperVGuids    ][Info   ] Removing GUIDs...
[17:29:25.762][HyperVGuids    ][Info   ] GUIDs removed
[17:29:25.762][HyperV         ][Info   ] Create
[17:29:25.762][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[17:29:25.793][HyperV         ][Info   ] Script started at 17:29:25.793
[17:29:25.840][HyperV         ][Info   ] Module loaded at 17:29:25.840
[17:29:25.913][HyperV         ][Info   ] Creating Switch: DockerNAT...
[17:29:27.901][HyperV         ][Info   ] Switch created.
[17:29:29.059][HyperV         ][Info   ] Set IP address on switch
[17:29:29.075][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[17:29:31.753][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[17:29:32.406][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[17:29:33.337][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[17:29:34.209][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[17:29:35.130][HyperV         ][Info   ] Disabled Guest Service Interface
[17:29:35.145][HyperV         ][Info   ] Enabled Heartbeat
[17:29:35.251][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[17:29:35.289][HyperV         ][Info   ] Enabled Shutdown
[17:29:35.303][HyperV         ][Info   ] Enabled Time Synchronization
[17:29:35.384][HyperV         ][Info   ] Disabled VSS
[17:29:36.723][HyperV         ][Info   ] VM created.
[17:29:36.724][HyperV         ][Debug  ] [create] took 00:00:10.9622250 to run
[17:29:36.724][PowerMode      ][Info   ] Stop
[17:29:36.724][HyperV         ][Info   ] Stop
[17:29:36.725][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[17:29:36.757][HyperV         ][Info   ] Script started at 17:29:36.757
[17:29:36.766][HyperV         ][Info   ] Module loaded at 17:29:36.766
[17:29:36.801][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[17:29:36.802][HyperV         ][Debug  ] [stop] took 00:00:00.0779956 to run
[17:29:36.802][OptimizeDisk   ][Info   ] Optimize
[17:29:36.802][PowerShell     ][Info   ] Run script...
[17:29:38.180][Moby           ][Info   ] Stop
[17:29:38.197][HyperV         ][Info   ] Create
[17:29:38.197][PowerMode      ][Info   ] Start
[17:29:38.197][HyperVGuids    ][Info   ] Installing GUIDs...
[17:29:38.198][Firewall       ][Info   ] Removing all existing rules...
[17:29:38.198][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[17:29:38.199][HyperVGuids    ][Info   ] GUIDs installed
[17:29:38.215][HyperV         ][Info   ] Script started at 17:29:38.215
[17:29:38.236][HyperV         ][Info   ] Module loaded at 17:29:38.236
[17:29:38.253][Firewall       ][Info   ] All existing rules are removed.
[17:29:38.253][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[17:29:38.261][Firewall       ][Info   ] Opening ports for SMB...
[17:29:38.270][Firewall       ][Info   ] Ports are opened
[17:29:38.428][HyperV         ][Info   ] Using existing Switch: DockerNAT
[17:29:42.492][HyperV         ][Info   ] Using existing Switch IP address
[17:29:42.565][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[17:29:43.551][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[17:29:43.920][HyperV         ][Info   ] Remove existing DVDs
[17:29:44.545][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[17:29:45.603][HyperV         ][Info   ] Disabled Guest Service Interface
[17:29:45.623][HyperV         ][Info   ] Enabled Heartbeat
[17:29:45.642][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[17:29:45.664][HyperV         ][Info   ] Enabled Shutdown
[17:29:45.683][HyperV         ][Info   ] Enabled Time Synchronization
[17:29:45.703][HyperV         ][Info   ] Disabled VSS
[17:29:45.821][HyperV         ][Info   ] VM created.
[17:29:45.824][HyperV         ][Debug  ] [create] took 00:00:07.6270010 to run
[17:29:45.824][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[17:29:45.841][Database       ][Info   ] Generating CA Cert Bundle
[17:29:45.865][Database       ][Info   ] CA Cert Bundle Generated
[17:29:45.872][PowerMode      ][Info   ] Stop
[17:29:45.872][HyperV         ][Info   ] Stop
[17:29:45.872][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[17:29:45.884][HyperV         ][Info   ] Script started at 17:29:45.884
[17:29:45.893][HyperV         ][Info   ] Module loaded at 17:29:45.893
[17:29:45.917][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[17:29:45.918][HyperV         ][Debug  ] [stop] took 00:00:00.0459971 to run
[17:29:45.918][OptimizeDisk   ][Info   ] Optimize
[17:29:45.918][PowerShell     ][Info   ] Run script...
[17:29:47.176][Moby           ][Info   ] Stop
[17:29:47.192][HyperV         ][Info   ] Destroy
[17:29:47.193][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[17:29:47.207][HyperV         ][Info   ] Script started at 17:29:47.207
[17:29:47.244][HyperV         ][Info   ] Module loaded at 17:29:47.243
[17:29:47.266][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[17:29:47.267][HyperV         ][Info   ] Destroying Switch DockerNAT...
[17:29:48.112][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[17:29:48.771][HyperV         ][Debug  ] [destroy] took 00:00:01.5786327 to run
[17:29:48.771][Firewall       ][Info   ] Closing ports...
[17:29:48.771][Firewall       ][Info   ] Removing all existing rules...
[17:29:48.943][Firewall       ][Info   ] All existing rules are removed.
[17:29:48.943][Firewall       ][Info   ] Ports are closed
[17:29:48.943][HyperVGuids    ][Info   ] Removing GUIDs...
[17:29:48.944][HyperVGuids    ][Info   ] GUIDs removed
[17:29:49.196][NamedPipeServer][Error  ] Unable to execute Start: Unable to create File System Image    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 256
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[17:29:49.229][NamedPipeClient][Error  ] Unable to send Start: Unable to create File System Image
[17:29:49.230][Notifications  ][Error  ] Unable to create File System Image
[17:37:00.135][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[17:37:00.137][NamedPipeClient][Info   ] Sending Version()...
[17:37:00.139][NamedPipeClient][Info   ] Sending Version()...
[17:37:00.323][NamedPipeServer][Info   ] Version()
[17:37:00.329][CrashReport    ][Warning] Unable to collect features settings: Could not find file 'C:\Users\PROF\AppData\Roaming\Docker\features-cache.json'.
[17:37:00.324][NamedPipeServer][Info   ] Version done in 00:00:00.0009996.
[17:37:00.329][CrashReport    ][Warning] Unable to collect features settings: Could not find file 'C:\Users\PROF\AppData\Roaming\Docker\features-overrides.json'.
[17:37:00.330][NamedPipeClient][Info   ] Received response for Version
[17:37:00.330][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[17:37:00.331][NamedPipeClient][Info   ] Sending Version()...
[17:37:00.331][NamedPipeServer][Info   ] Version()
[17:37:00.338][NamedPipeClient][Info   ] Received response for Version
[17:37:00.338][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\PROF\AppData\Local\Temp\gmvnsr5e.w5t\pcap.tar)...
[17:37:00.339][NamedPipeClient][Info   ] Sending Version()...
[17:37:00.331][NamedPipeServer][Info   ] Version done in 00:00:00.
[17:37:00.989][NamedPipeClient][Info   ] Received response for Version
[17:37:00.989][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\PROF\AppData\Local\Temp\gmvnsr5e.w5t\mobyLogs.tar)...
[17:37:00.988][NamedPipeServer][Info   ] Version()
[17:37:00.988][NamedPipeServer][Info   ] Version done in 00:00:00.
[17:37:00.990][NamedPipeServer][Info   ] GetDebugInfo()
[17:37:01.004][NamedPipeClient][Info   ] Received response for Version
[17:37:01.004][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\PROF\AppData\Local\Temp\gmvnsr5e.w5t\win_containers)...
[17:37:01.004][NamedPipeServer][Info   ] Version()
[17:37:01.004][NamedPipeServer][Info   ] Version done in 00:00:00.
[17:37:01.038][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\PROF\AppData\Local\Temp\gmvnsr5e.w5t\mobyLogs.tar)
[17:37:01.038][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\PROF\AppData\Local\Temp\gmvnsr5e.w5t\win_containers)
[17:37:01.038][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\PROF\AppData\Local\Temp\gmvnsr5e.w5t\pcap.tar)
[17:37:01.114][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[17:37:01.113][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[17:37:01.114][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[17:37:01.114][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0758017.
[17:37:01.536][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[17:37:01.536][HyperV         ][Warning] Unable to download logs: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual machine with name "MobyLinuxVM".
[17:37:01.536][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.4974699.
[17:37:16.650][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[17:37:16.650][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:15.6115359.
[17:37:40.061][NamedPipeServer][Info   ] GetDebugInfo done in 00:00:39.0703478.
[17:37:40.064][NamedPipeClient][Info   ] Received response for GetDebugInfo
[17:37:40.309][CrashReport    ][Info   ] Uploading diagnostics...
[17:37:58.512][CrashReport    ][Info   ] Diagnostics successfully uploaded (41FB48A9-C844-43C8-8A51-B24D03970C5B/2018-02-03_17-36-59)
[17:37:58.602][GUI            ][Info   ] Sending Bugsnag report a1f684c5-23f8-4177-927f-2a674311d7d8...
[17:38:14.098][GUI            ][Info   ] Bugsnag report a1f684c5-23f8-4177-927f-2a674311d7d8 sent
[18:04:29.982][ErrorReportWindow][Info   ] Open logs
[18:25:01.219][ErrorReportWindow][Info   ] Open logs

**Comment by jasonbivins** [comment]
Hi @ocoyawale 

If you see the Docker whale icon in your systray, right click it and switch to Windows containers.

**Comment by ocoyawale** [comment]
Hi Jason, I followed your instruction and - Voila! Docker is up and running! Thanks so much.

**Comment by hascist** [comment]
I had the same issue and was pleasantly surprised to find a quick and easy fix. Thanks!

**Comment by mrdomiciano** [comment]
Hello guys!
I think this actually doesn't fix anything. Only switch to Windows Containers!... But, if is that do you really want to, OK!... But probably not! 
If so, you will be able to run Windows containers only, in other words, Windows applications.
Both versions should be working, as  they used to be before. We need the flexibility package Linux or Windows images!
Greetings!
