### ISSUE TITLE
Docker for Windows crashes after docker ps and cannot be started aftwards

### ISSUE THREAD

**Issue by jeremiahkjones** [docker/for-win#1654]
### Expected behavior
I should be able to run any docker commands.  Docker should start normally.
### Actual behavior
After successfully installing docker for windows I can build and run via docker-compose but after a while when I run `docker ps` docker crashes and I get an error in the console that says "permission denied" or something to that effect. After this point, any time I attempt to restart/start docker for windows I get the following error (the only way to resolve is to uninstall and re-install but then it just happens again after a while):
```
The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Docker.Core.Cmd.StartProcessAndCaptureOutput(Int32 timeout, Process process, String stdin) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\Cmd.cs:line 91
   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 45
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 262
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 189
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```
The only way I can find to fix the problem is to uninstall docker and then re-install... but then after an hour or so of usage it happens again.  I can't keep docker for windows working properly.
### Information

  - 48D9F8CD-7F8B-4E0C-8A37-D7D502A8B41E/2018-02-03_22-24-07
  - Docker for WIndows Version 17.12.0-ce-win47 (15139)
  - Windows 10 Pro
  - Using ConEmu to run commands, but same results using git bash or windows cmd

### Steps to reproduce the behavior

  1. Install docker for windows
  2. Build and start up something via docker-compose
  3. Use things for a while, running various docker commands
  4.  Eventually get an "access denied" error (for me it was after running `docker ps`)
  5.  Docker for windows has crashed and no longer works
  6.  attempts to run any `docker` commands in a shell now just result in "docker is not a recognized...etc"

**Comment by jeremiahkjones** [comment]
Later versions seem to have fixed this issue as this has not been a problem in a while.
