### ISSUE TITLE
Docker service fails to start in Windows 10 :  Unable to stop - Killed VM MobyLinuxVM error

### ISSUE THREAD

**Issue by aar-1** [docker/for-win#1656]
### Information

  - Diagnostic ID -FB440548-A0CA-457C-A920-998B55BFD67A/2018-02-04_23-56-28
  - Error says - Unable to stop - Killed VM MobyLinuxVM did not stop at Fatal...
  - Docker update for Version 17.12.0-ce-win47 (15139) installed
  - Windows 10 OS 64 bit host system

### Steps to reproduce the behavior

  1.  Installed docker update as mentioned above
  2.  At system boot notices this error

Attached please find detailed log report from Docker log files
[log.txt](https://github.com/docker/for-win/files/1693190/log.txt)

**Comment by jasonbivins** [comment]
Hi @aar-1 
It looks like the MobyLinuxVM is stuck, there are also errors about it being missing.

let's make sure it's cleared out - stop Docker - then run this from an elevated powershell prompt. Try to start Docker normally after that

`powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -destroy`

**Comment by mattsgreen** [comment]
@jasonbivins thanks that worked for me!

**Comment by shivakumarjava1** [comment]
Is this issue still open?

Unable to stop: Killed VM MobyLinuxVM did not stop
at Fatal, <No file>: line 400
at Stop-VM-Force, <No file>: line 388
at Stop-MobyLinuxVM, <No file>: line 326
at <ScriptBlock>, <No file>: line 407
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 181
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 306
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 129
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

**Comment by shivakumarjava1** [comment]
My college is use windows 10 pro but he is not getting any error.

**Comment by aar-1** [comment]
@jasonbivins - Thanks for your response.  I tried".\MobyLinux.ps1" -destroy from elevated powershell after shutting down Docker service.
On observing from Hyper -V Manager GUI, it did destroy the MobyLinuxVM. But on restartingDocker service I get a new error -
"**Docker hv-sock proxy (vsudd) is not reachable**" 
at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 293
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 260
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[Detailed log is attached.]
[log.txt](https://github.com/docker/for-win/files/1788489/log.txt)

I see this is a commonly encountered error like in - https://github.com/docker/for-win/issues/606
I tried updating docker, tried the edge version - but nothing so far has resolved the issue for me.
 Any clue ?

**Comment by pbbhopp** [comment]
SOLVED!
The same situation here( Win10( Version 10.0.17134) with Docker 2.0.0.3), after switch to Windows containers it was unable to return to Linux containers - an error occurred with the VM.
So, I stopped the Hyper-V process vmcompute.exe in the Task Manager. Then run it again as Admin, then switch Docker to Linux containers, it switched and runs well. Try this and return feedback.
