### ISSUE TITLE
Can't start Docker for Windows (stable) on Windows 10

### ISSUE THREAD

**Issue by rcolinray** [docker/for-win#1676]
### Expected behavior

Docker for Windows to start successfully.

### Actual behavior

Docker for Windows did not start successfully.

### Information

  - Diagnostic ID: 11A0D70C-EB93-48CA-A2B0-950B0CC9B0DE/2018-02-08_11-31-30
  - Windows 10 Pro, Version 1709, OS Build 16299.192

Error log:

```
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 293
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 260
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

### Steps to reproduce the behavior

1. Install Docker for Windows (stable) on Windows 10
2. Start Docker for Windows

**Comment by rcolinray** [comment]
The issue ended up being related to a BIOS issue with my computer.
