### ISSUE TITLE
Binary stream does not contain valid BinaryHeader; 18.02.0-ce-win52 (15732) on Win10 17093

### ISSUE THREAD

**Issue by jburnett** [docker/for-win#1677]
### Expected behavior
Docker should continue to run after upgrading 

### Actual behavior
Docker consistently fails to start with error message:
Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 75
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information
Diagnostic ID: 474E9017-199F-478F-81E4-5B51C3B4A4C1/2018-02-08_12-53-50
Docker for Windows, Edge channel, version 18.02.0-ce-win52 (15732)
Windows 10 Pro, build 17093.rs_prerelease.180202-1400

### Steps to reproduce the behavior

  1. Install specified Docker for Windows on specified Windows 10 build
  2. Start _Docker for Windows.exe_
[20180208 Docker crash.txt](https://github.com/docker/for-win/files/1708283/20180208.Docker.crash.txt)
[log.txt](https://github.com/docker/for-win/files/1708284/log.txt)

**Comment by dannyk81** [comment]
Same here

Crash report: `5459E06B-6398-479F-B0E7-08E317758B02/2018-02-08_13-25-49`

Failing back to 17.09.1 works just fine...

**Comment by jburnett** [comment]
Thanks @dannyk81.  I dropped back to current stable channel version, 17.12.0.15139 (17.12.0-ce-win47).  It crashes with the same error.  I'll try rolling back further as Danny suggests.

**Comment by hoopsomuah** [comment]
I experienced this issue on the stable channel as well.

**Comment by johnmiroki** [comment]
@dannyk81 could you please share how you found an older version of docker installation file? i'd really appreciate it

**Comment by mphacker** [comment]
Same issue here.  Running Windows 10 Insider Fast build 17101.   I have tried both stable and edge builds.

 C763F0ED-CD8F-4B90-A742-64C53FB67EC3/2018-02-19_10-49-03

**Comment by jburnett** [comment]
I've tried 3 Docker versions: 17.09, 17.12, and 18.02 (all community ed) on Window 10 1803 Build 17101.1000.  I get the same "Binary stream '0' does not contain a valid BinaryHeader" error in each case.  After installing 18.02, I rebooted (b/c maybe?), but not change.  Finally, I invoked "Reset to factory defaults," but still received the error.
Most recent Diagnostic ID: 474E9017-199F-478F-81E4-5B51C3B4A4C1/2018-02-19_17-37-01

A few recent log files which may be helpful:

[DockerLogs-2018-02-16_13-32-58.zip](https://github.com/docker/for-win/files/1738416/DockerLogs-2018-02-16_13-32-58.zip)
[DockerLogs-2018-02-19_17-34-27.zip](https://github.com/docker/for-win/files/1738417/DockerLogs-2018-02-19_17-34-27.zip)

**Comment by jburnett** [comment]
@johnmiroki, you can find some previous Windows builds on https://download.docker.com/win/static/  and select Edge or Stable.  HTH

**Comment by sgtoj** [comment]
I have the same issue. Here the log...

```
Version: 18.02.0-ce-win52 (15732)
Channel: edge
Sha1: 92c7ac6fd6d2f3876329f394b1482a0d89211762
Started on: 2018/02/20 18:59:09.945
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise Insider Preview
Edition: Professional
Id: 1709
Build: 17604
BuildLabName: 17604.1000.amd64fre.rs_prerelease.180209-1422
File: C:\Users\brian\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[18:59:10.027][GUI            ][Info   ] Starting...
[18:59:10.586][Tracking       ][Info   ] Crash report and usage statistics are enabled
[18:59:10.586][SegmentApi     ][Info   ] Usage statistic: appLaunched
[18:59:11.490][NPS            ][Info   ] NPS user ceated on :11/12/2017 9:16:57 AM -08:00, last survey : 12/13/2017 3:19:38 PM -08:00
[18:59:11.490][SegmentApi     ][Info   ] Usage statistic: heartbeat
[18:59:11.492][SegmentApi     ][Info   ] Usage statistic: Identify
[18:59:11.552][NamedPipeClient][Info   ] Sending Version()...
[18:59:21.327][NamedPipeClient][Info   ] Sending Version()...
[18:59:21.375][NamedPipeClient][Info   ] Received response for Version
[18:59:21.376][NamedPipeClient][Info   ] Sending Start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions)...
[18:59:19.344][BackendServer  ][Info   ] Started
[18:59:21.372][NamedPipeServer][Info   ] Version()
[18:59:21.373][NamedPipeServer][Info   ] Version done in 00:00:00.0009987.
[18:59:21.391][NamedPipeServer][Info   ] Start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions)
[18:59:21.391][PowerMode      ][Info   ] Stop
[18:59:21.391][HyperV         ][Info   ] Stop
[18:59:21.391][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[18:59:21.391][PowerShell     ][Info   ] Creating a Runspace Pool...
[18:59:21.469][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[18:59:21.501][HyperV         ][Info   ] Script started at 18:59:21.501
[18:59:22.990][HyperV         ][Info   ] Module loaded at 18:59:22.990
[18:59:23.268][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[18:59:23.268][HyperV         ][Debug  ] [stop] took 00:00:01.8764750 to run
[18:59:23.268][OptimizeDisk   ][Info   ] Optimize
[18:59:23.269][PowerShell     ][Info   ] Run script...
[18:59:24.452][Moby           ][Info   ] Stop
[18:59:24.463][HyperVGuids    ][Info   ] Installing GUIDs...
[18:59:24.463][PowerMode      ][Info   ] Start
[18:59:24.466][HyperV         ][Info   ] Create
[18:59:24.466][HyperVGuids    ][Info   ] GUIDs installed
[18:59:24.466][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64424509440 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[18:59:24.492][Firewall       ][Info   ] Removing all existing rules...
[18:59:24.500][HyperV         ][Info   ] Script started at 18:59:24.500
[18:59:24.508][HyperV         ][Info   ] Module loaded at 18:59:24.507
[18:59:24.547][Firewall       ][Info   ] All existing rules are removed.
[18:59:24.559][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[18:59:24.564][Firewall       ][Info   ] Opening ports for SMB...
[18:59:24.569][Firewall       ][Info   ] Ports are opened
[18:59:24.767][HyperV         ][Info   ] Using existing Switch: DockerNAT
[18:59:28.326][HyperV         ][Info   ] Using existing Switch IP address
[18:59:29.677][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[18:59:29.943][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[18:59:30.117][HyperV         ][Info   ] Remove existing DVDs
[18:59:30.242][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[18:59:30.650][HyperV         ][Info   ] Disabled Guest Service Interface
[18:59:30.664][HyperV         ][Info   ] Enabled Heartbeat
[18:59:30.675][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[18:59:30.688][HyperV         ][Info   ] Enabled Shutdown
[18:59:30.699][HyperV         ][Info   ] Enabled Time Synchronization
[18:59:30.709][HyperV         ][Info   ] Disabled VSS
[18:59:30.786][HyperV         ][Info   ] VM created.
[18:59:30.787][HyperV         ][Debug  ] [create] took 00:00:06.3211206 to run
[18:59:30.787][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[18:59:30.813][Database       ][Info   ] Generating CA Cert Bundle
[18:59:30.831][Database       ][Info   ] CA Cert Bundle Generated
[18:59:33.121][Notifications  ][Error  ] Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
[18:59:33.136][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[18:59:33.136][NamedPipeClient][Info   ] Sending Version()...
[18:59:33.136][NamedPipeClient][Info   ] Sending Version()...
[18:59:33.136][NamedPipeClient][Info   ] Sending Version()...
[18:59:33.136][NamedPipeClient][Info   ] Sending Version()...
[18:59:33.136][CrashReport    ][Warning] Unable to collect features settings: Could not find file 'C:\Users\brian\AppData\Roaming\Docker\features-overrides.json'.
[18:59:38.148][CrashReport    ][Warning] Unable to collect vpnkit diagnostic: The calling thread must be STA, because many UI components require this.
[18:59:38.148][CrashReport    ][Warning] Unable to collect guest diagnostic: The calling thread must be STA, because many UI components require this.
[18:59:38.148][CrashReport    ][Warning] Unable to collect win containers diagnostic: The calling thread must be STA, because many UI components require this.
[18:59:59.699][CrashReport    ][Info   ] Uploading diagnostics...
[19:00:00.399][CrashReport    ][Info   ] Diagnostics successfully uploaded (06CF462C-568C-4E92-BF0E-D36D548133B1/2018-02-20_18-59-33)
[19:00:00.427][GUI            ][Info   ] Sending Bugsnag report 688ca6ee-f389-4a64-9f84-34797900f253...
[19:00:01.288][GUI            ][Info   ] Bugsnag report 688ca6ee-f389-4a64-9f84-34797900f253 sent
[19:02:45.258][ErrorReportWindow][Info   ] Open logs
```

**Comment by sgtoj** [comment]
Finally found a workaround! After reading this [recent blog](https://blog.docker.com/2018/02/docker-for-windows-18-02-with-windows-10-fall-creators-update/), I set `LCOW_API_PLATFORM_IF_OMITTED` system-level environment variable to `linux` and restarted docker service. 

```powershell
[Environment]::SetEnvironmentVariable("LCOW_API_PLATFORM_IF_OMITTED", "linux", "Machine")
```

**Comment by mi-hol** [comment]
bug fixed in Windows build 17107.1000

**Comment by arjenpdevries** [comment]
Confirmed - can be closed.

**Comment by danquist** [comment]
I started encountering this error after installing the latest dotnet core 2.1.105. Reinstalling both Docker and Hyper-V has no effect, neither does uninstalling the dotnet SDK.

OS Build is 16299.371. How do I upgrade to 17107?

**Comment by danquist** [comment]
See #1232 for a fix.
