### ISSUE TITLE
Docker for Windows. Failed to access configuration store: A virtual disk support provider for the specified file was not found. (0xC03A0014)

### ISSUE THREAD

**Issue by danousman** [docker/for-win#1689]
### Expected behavior

Start docker

### Actual behavior

Docker doesn't start with next error.
Reinstall of docker doesn't help.

### Information

[11:56:16.688][PowerMode      ][Info   ] Start
[11:56:16.688][Firewall       ][Info   ] Removing all existing rules...
[11:56:16.688][HyperVGuids    ][Info   ] GUIDs installed
[11:56:16.688][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[11:56:16.693][HyperV         ][Info   ] Script started at 11:56:16.693
[11:56:16.701][HyperV         ][Info   ] Module loaded at 11:56:16.701
[11:56:16.769][Firewall       ][Info   ] All existing rules are removed.
[11:56:16.769][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[11:56:16.776][Firewall       ][Info   ] Opening ports for SMB...
[11:56:16.781][Firewall       ][Info   ] Ports are opened
[11:56:17.060][HyperV         ][Info   ] Using existing Switch: DockerNAT
[11:56:20.613][HyperV         ][Info   ] Using existing Switch IP address
[11:56:20.621][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[11:56:20.816][NamedPipeServer][Error  ] Unable to execute Restart: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.

'MobyLinuxVM' failed to realize. (Virtual machine ID CC8AAD4B-D83C-483B-AE61-6F4F702AA0FF)

Failed to access configuration store: A virtual disk support provider for the specified file was not found. (0xC03A0014).
at New-MobyLinuxVM, <No file>: line 202
at <ScriptBlock>, <No file>: line 409    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 256
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 189
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[11:56:20.829][NamedPipeClient][Error  ] Unable to send Restart: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.

'MobyLinuxVM' failed to realize. (Virtual machine ID CC8AAD4B-D83C-483B-AE61-6F4F702AA0FF)

Failed to access configuration store: A virtual disk support provider for the specified file was not found. (0xC03A0014).
at New-MobyLinuxVM, <No file>: line 202
at <ScriptBlock>, <No file>: line 409
[11:56:20.829][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.

'MobyLinuxVM' failed to realize. (Virtual machine ID CC8AAD4B-D83C-483B-AE61-6F4F702AA0FF)

Failed to access configuration store: A virtual disk support provider for the specified file was not found. (0xC03A0014).
at New-MobyLinuxVM, <No file>: line 202
at <ScriptBlock>, <No file>: line 409

### Steps to reproduce the behavior

  1. Start or restart docker

**Comment by ctartamella** [comment]
Also seeing this.  Is there a known solution?  I think it is more of a Hyper-V issue as I can not even create VMs.

**Comment by pepet339** [comment]
I'm getting the same error...

**Comment by frg** [comment]
Also having the same issue. Any ideas?

**Comment by frg** [comment]
Seems like the "Share drive" was unselected for some reason. Selected a shared drive again. Restarted Docker and everything started working as expected.

**Comment by tbarlow12** [comment]
+1

**Comment by zhangzyg** [comment]
I have the same issue like this, is there any solution on this?

**Comment by bradamelton** [comment]
> 
> 
> I have the same issue like this, is there any solution on this?

Check your Hyper-V Shared drive in Hyper-V Settings, as recommended by JNaeemGitonga. Mine was also reassinged to F: and causing this problem. Changed it back, and all was again well.
