### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by tannerchung** [docker/for-win#1691]
### Expected behavior

Startup like normal

### Actual behavior

```
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 293
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 260
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
0601BC2D-8792-47D9-9FC7-2307862FD9D5/2018-02-12_12-20-04
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. Open Docker

OR

  1. Open Docker
  2. Reset to Factory Defaults

Resetting to Factory Defaults still produced the same error.

**Comment by rcolinray** [comment]
I encountered the same error, and it turned out to be related to an issue with my BIOS. My CPU was stuck at 0.79GHz for some reason. Once I got that sorted out, Docker started working again.

**Comment by drazisil** [comment]
Actually, in my case (thought about this because of @rcolinray 's comment) It seems to be because I had the coinhive miner eating all my cpu.

**Comment by ctmcisco** [comment]
For anyone following this ticket:

Try the following:

1. Switch or stay on Windows Containers.
2. Disable the "Start when Windows starts" setting.


![image](https://user-images.githubusercontent.com/14852041/37053107-e9a96bd8-2140-11e8-9bdf-b264980b6127.png)

3. Exit Docker application
4. restart docker services via PowerShell

get-service *docker* | Restart-Service -Force -Verbose

5. Launch Docker , Run as Admin
6. Swtich to Linux Containers.

TEST:

Reboot Windows 10
Launch Docker 
Does it work?

You can also parse the docker log in PowerShell for troubleshooting:

cat C:\Users\USERPROFILE\AppData\Local\Docker\log.txt -tail 10 -wait

**Comment by develtn** [comment]
i faced this problem earlier today and solved it like this:
change the VHD location to an empty folder
throw some cpu and memory power and that should work for you as well.

**Comment by rn** [comment]
@tannerchung I don't seem to be able to access your diagnostics? Maybe the upload was blocked by a firewall. Could you attached Log.txt here?

**Comment by tannerchung** [comment]
@rn sorry about that, I've been having some noob issues with Github's notification system. I haven't been facing this issue since the newer Docker for windows releases so didn't check up on this until now.
