### ISSUE TITLE
The VM couldn't get an IP address after 60 tries

### ISSUE THREAD

**Issue by maxday** [docker/for-win#17]
Hi,
First, thanks for your work, I've seen a great demo at DevoxxFR and I can't wait to use it :)

I'm running Docker for Windows Version: 1.12.0-beta21 on a WIN10 VM.
Hyper-V is activated and Windows services are OK.
The MobyLinuxVM is well created but Docker fails to start because it cannot get an IP for the VM.

The DNS server radio button configuration is set to "automatic".
I've tried to reboot, reset to factory, uninstall/reinstall,
I've also tried to set the a fixed DNS.

Error : 
Failed to start VM "MobyLinuxVM": The VM couldn't get an IP address after 60 tries
   at Docker.Core.Pipe.NamedPipeClient.TrySend(String action, Object[] parameters)
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Core.Backend.BackendClient.Start(Settings settings)
   at Docker.Actions.DoStart(Settings settings, Boolean showWelcomeWindow)
   at Docker.Core.TaskQueue.<.ctor>b__16_0()

Diagnostic id : 
5C73F6A7-06A7-40B5-A2F9-9EF5214B83F2/2016-08-02_09-22-49

**Comment by dgageot** [comment]
Hi @maxday, thank you very much for taking the time to share your feedback. I'm afraid running Docker for Windows inside a VM is not something that we officially support. Some many things can break.
However, we can try to help you.

+ Can you tell us which Hypervisor you are using to run the VM (Vbox, vmware...)?
+ Is it configured for nested virtualisation?

ping @rneugeba Can you provide insights?

**Comment by maxday** [comment]
Hi @dgageot ,
Thanks for your quick answer.
It's running with VMWare and the nested virtualisation is enabled.
Feel free to ask if you need any further info

**Comment by cuikangyi** [comment]
I have the same problem on Windows 10,version1607,OS build 14393.
docker version 1.12.0-stable(build:5968)

**Comment by dgageot** [comment]
@cuikangyi Do you have a log or diagnostic id to share?

**Comment by TaylorBarrick** [comment]
I have the problem describe above and here is a log file and diagnostic ID

A diagnostic was uploaded with id: F92E5AB4-A9AA-4269-A7D6-8FEB6F6E3D34/2016-08-01_22-30-16
Windows 10.0.14393

[22:26:32.349][ApiProxy ][Info ] dns server: ready
[22:26:32.353][ApiProxy ][Info ] docker proxy: ready
[22:26:32.356][ApiProxy ][Info ] listen tcp 10.0.75.1:53: bind: The requested address is not valid in its context.
[22:26:32.359][ApiProxy ][Info ] listen udp 10.0.75.1:53: bind: The requested address is not valid in its context.
[22:26:32.363][ApiProxy ][Info ] Waiting for the port/IP to become available
[22:26:32.367][ApiProxy ][Info ] Waiting for the port/IP to become available
[22:26:32.551][Database ][Info ] Successfully removed 3 value(s)
[22:26:32.555][Database ][Info ] Writing com.docker.driver.amd64-linux/net/config=static
[22:26:32.553][DataKit ][Info ] 
[22:26:32.562][DataKit ][Info ] +524521us fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[22:26:32.559][Database ][Info ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[22:26:32.570][Database ][Info ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[22:26:32.574][Database ][Info ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[22:26:32.579][Database ][Info ] Writing com.docker.driver.amd64-linux/etc/resolv.conf=nameserver 10.0.75.1
[22:26:32.583][Database ][Info ] Writing com.docker.driver.amd64-linux/network=hybrid
[22:26:32.586][Database ][Info ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[],"debug":false}
[22:26:32.591][Database ][Info ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[22:26:32.595][Database ][Info ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[22:26:33.537][Database ][Info ] Successfully wrote 9 value(s)
[22:26:33.541][HyperV ][Info ] Start
[22:26:33.547][PowerShell ][Info ] Run script with parameters: -Start True...
[22:26:33.537][DataKit ][Info ] 
[22:26:33.561][DataKit ][Info ] +1508337us fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[22:26:33.631][HyperV ][Info ] Starting VM MobyLinuxVM...
[22:26:34.140][HyperV ][Info ] Wait for the VM to get an IP address
[22:26:35.155][HyperV ][Info ] Wait for the VM to get an IP address
[22:26:36.174][HyperV ][Info ] Wait for the VM to get an IP address
[22:26:37.434][HyperV ][Info ] Wait for the VM to get an IP address
...
..
[22:27:37.803][NamedPipeServer][Error ] Unable to execute Start: Failed to start VM "MobyLinuxVM": The VM couldn't get an IP address after 60 tries at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
at Docker.Core.PowerShell.Run(String script, Dictionary2 parameters, Action1 lineReceived)
at Docker.Backend.Backend.Start(Settings settings)
at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass7_0.b__0(Object[] parameters)
at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by cuikangyi** [comment]
@dgageot Sorry,I forget to see. 
Then I reset to factory defaults, and it can be work.
Thank you for your reply.

**Comment by kukjevov** [comment]
I have same problem. 

It looks like problem of Windows 10 Redstone 1 update (build 14393) with combination of latest stable docker version. 

I have enabled windows features like "Containers", "Hyper-V" and "Windows subsystem for linux (beta)".
I have restarted computer. I tried to reinstall docker, reset to factory defaults.

Nothing helped.

And according this it looks like problem of Redstone 1. https://forums.docker.com/t/failed-to-start-vm-mobylinuxvm-the-vm-couldnt-get-an-ip-address-after-60-tries/19551/7 

Have you solved this somehow ?
Thank you

**Comment by rneugeba** [comment]
@kukjevov @maxday @TaylorBarrick I'm closing this issue as a duplicated of #54. While #54 is newer it has more comments on it. I've copied and pasted your reports in #54 so that they don't fall through the cracks.

**Comment by rsaliy** [comment]
It isn't working for me too
Crash report BF641EE2-6BEE-405C-B6DD-E5489E163E2C/2016-12-14_06-46-25

**Comment by rneugeba** [comment]
@rsaliy the fix is only on the Beta channel, not on the stable channel. Could you try the latest Beta?

**Comment by d3x0r** [comment]
I've been searching all over for 'beta channel' and have failed.
I have this issue still...  so maybe in a month beta isn't relesaed?
```
[02:50:02.348][Moby           ][Info   ] 00:01: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[02:50:02.418][Moby           ][Info   ] 00:02: ttyS1 at I/O 0x2f8 (irq = 3, base_baud = 115200) is a 16550A
[02:50:02.425][Moby           ][Info   ] Initializing Nozomi driver 2.1d
[02:50:02.432][Moby           ][Info   ] Non-volatile memory driver v1.3
[02:50:02.450][Moby           ][Info   ] Hangcheck: starting hangcheck timer 0.9.1 (tick is 180 seconds, margin is 60 seconds).
[02:50:02.459][Moby           ][Info   ] [drm] Initialized drm 1.1.0 20060810
[02:50:02.466][Moby           ][Info   ] loop: module loaded
[02:50:02.475][Moby           ][Info   ] VMware PVSCSI driver - version 1.0.5.0-k
[02:50:02.484][Moby           ][Info   ] hv_vmbus: registering driver hv_storvsc
[02:50:02.880][HyperV         ][Info   ] Wait for the VM to get an IP address
[02:50:04.028][HyperV         ][Info   ] Wait for the VM to get an IP address
```
<cut>
```
[02:50:59.235][HyperV         ][Info   ] Wait for the VM to get an IP address
[02:51:00.245][HyperV         ][Info   ] Wait for the VM to get an IP address
[02:51:01.390][NamedPipeServer][Error  ] Unable to execute Start: Unable to start: The VM couldn't get an IP address after 60 tries
at Fatal, <No file>: line 353
at Start-MobyLinuxVM, <No file>: line 267
at <ScriptBlock>, <No file>: line 363    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[02:51:01.391][NamedPipeClient][Error  ] Unable to send Start: Unable to start: The VM couldn't get an IP address after 60 tries
at Fatal, <No file>: line 353
at Start-MobyLinuxVM, <No file>: line 267
at <ScriptBlock>, <No file>: line 363
[02:51:01.392][Notifications  ][Error  ] Unable to start: The VM couldn't get an IP address after 60 tries
at Fatal, <No file>: line 353
at Start-MobyLinuxVM, <No file>: line 267
at <ScriptBlock>, <No file>: line 363
[02:56:57.039][FeedbackSettings][Info   ] Open logs
```

I don't see it attempting to get anything.....

**Comment by rneugeba** [comment]
@d3x0r we release betas almost weekly. The latest is available for download from the main Docker for Windows page: https://docs.docker.com/docker-for-windows/

**Comment by d3x0r** [comment]
Okay beta does get an address and runs; but a couple nodeos images I tried don't work(?)  I don't know how to know if it(docket) works..... sorry first day new tool
