### ISSUE TITLE
Docker won't start on Windows 10 - Provider is not capable of the attempted operation

### ISSUE THREAD

**Issue by ddyson** [docker/for-win#1717]
### Expected behavior
Docker has just stopped loading on my Windows 10 developer machine

### Actual behavior
The following error appears on start up.

### Information
An error occurred

The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The operation on computer 'DAN-ELITEBOOK' failed: Provider is not capable of the attempted operation 
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 256
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

[log.txt](https://github.com/docker/for-win/files/1732729/log.txt)

**Comment by rn** [comment]
Do you run any AV software? If so could you try disabling it? We had a lot of issues (some similar to yours) caused by a variety of AV/Security software.
