### ISSUE TITLE
Docker wont start on windows 10 build 17101 - Failed to initalize

### ISSUE THREAD

**Issue by jakevis** [docker/for-win#1718]
### Expected behavior
It initalizes

### Actual behavior
it fails

### Information

A16C0F38-FF48-4B24-A6E9-EA185923F23E/2018-02-16_18-41-48

Winver - 1803 (OS Build 17101.1000)

### Steps to reproduce the behavior

Install docker edge on this version of windows

The calling thread must be STA, because many UI components require this.
   at System.Windows.Input.InputManager..ctor()
   at System.Windows.Input.InputManager.GetCurrentInputManagerImpl()
   at System.Windows.Input.KeyboardNavigation..ctor()
   at System.Windows.FrameworkElement.FrameworkServices..ctor()
   at System.Windows.FrameworkElement.EnsureFrameworkServices()
   at System.Windows.FrameworkElement..ctor()
   at System.Windows.Controls.Control..ctor()
   at System.Windows.Window..ctor()
   at Docker.WPF.DialogBox..ctor() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\DialogBox.xaml.cs:line 230
   at Docker.WPF.ServiceNotRunningBox.ShowConfirm() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\DialogBox.xaml.cs:line 116
   at Docker.WPF.BackendClient.CheckService() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 283
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 151
   at Docker.WPF.BackendClient.TryGetVhdxSize(String physicalPath) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 125
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.WPF.AdvancedSettings.<GetDiskImageMaxSize>d__11.MoveNext() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\Settings\AdvancedSettings.xaml.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.WPF.AdvancedSettings.<InitDiskFields>d__8.MoveNext() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\Settings\AdvancedSettings.xaml.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Program.cs:line 185

**Comment by jasonbivins** [comment]
Hi @jakevis   Will it start in Windows container mode?

**Comment by jakevis** [comment]
Hi again,

Yes it will (although I havnt tried running a windows container yet).

Thanks

Jake

**Comment by moondev** [comment]
I'm on 17101 as well and was having the same issue with Docker starting. However I was able to launch it successfully (Linux container mode) by running `\Docker for Windows.exe` as an Administrator.

For what it's worth, Hyper-V Quick Create also will also error out unless its launched as an admin.
