### ISSUE TITLE
Couldn't start Docker in Windows 10 with error - Couldn't stop VM MobyLinuxVM

### ISSUE THREAD

**Issue by grushler** [docker/for-win#176]
Docker was working fine when I first installed it. Now when I try to start it again after 2 days of installation, I get below error -

```
[09:16:40.685][Program        ][Info   ] Version: 1.12.1-stable
[09:16:40.730][Program        ][Info   ] Starting on: 10/28/2016 9:16:40 AM
[09:16:40.732][Program        ][Info   ] Resources: C:\Program Files\Docker\Docker\Resources
[09:16:40.733][Program        ][Info   ] OS: Windows 10 Enterprise
[09:16:40.734][Program        ][Info   ] Edition: Enterprise
[09:16:40.735][Program        ][Info   ] Id: 1511
[09:16:40.736][Program        ][Info   ] Build: 10586
[09:16:40.736][Program        ][Info   ] BuildLabName: 10586.633.amd64fre.th2_release.161004-1602
[09:16:40.738][Program        ][Info   ] Sha1: 995236d98308333f27e3a36505dd761ac9c843f3
[09:16:40.738][Program        ][Info   ] You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:16:40.791][Program        ][Error  ] An instance is already running. Exiting.
[09:16:55.530][GeneralSettings][Info   ] Saving settings
[09:17:34.183][Notifications  ][Info   ] Docker is resetting to default...
[09:17:34.206][NamedPipeClient][Info   ] Sending Stop()...
[09:17:34.208][NamedPipeServer][Info   ] Stop()
[09:17:34.210][HyperV         ][Info   ] Stop
[09:17:34.212][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[09:17:34.397][HyperV         ][Info   ] Stopping VM MobyLinuxVM...
[09:17:36.517][HyperV         ][Info   ] Turn Off VM ...
[09:17:36.537][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[09:17:37.558][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[09:17:38.578][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[09:17:39.623][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[09:17:40.648][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[09:17:41.684][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[09:17:42.723][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[09:17:43.753][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[09:17:44.781][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[09:17:45.810][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[09:17:46.826][DataKit        ][Info   ] Killing existing com.docker.db with PID 9076
[09:17:46.827][NamedPipeServer][Error  ] Unable to execute Stop: Unable to stop: Couldn't stop VM MobyLinuxVM
at <ScriptBlock>, <No file>: line 340    at Docker.Backend.ContainerEngine.Linux.Stop()
   at Docker.Backend.Backend.Stop()
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[09:17:46.830][NamedPipeClient][Error  ] Unable to send Stop: Unable to stop: Couldn't stop VM MobyLinuxVM
at <ScriptBlock>, <No file>: line 340
[09:17:46.831][Notifications  ][Error  ] Unable to stop: Couldn't stop VM MobyLinuxVM
at <ScriptBlock>, <No file>: line 340
```

A diagnostic was uploaded with id: 
`3A1A49EC-521B-4D5C-896B-925BD25A6953/2016-10-28_09-20-36`

Windows version - Windows 10 Enterprise

**Comment by dgageot** [comment]
Hi @grushler Could you try a more recent version of Docker for Windows? Beta 30.1 is the latest beta.

**Comment by grushler** [comment]
The latest version works fine. Closing the issue. Thanks @dgageot
