### ISSUE TITLE
Docker fail to start - problem with virtual network switch

### ISSUE THREAD

**Issue by haakoo** [docker/for-win#1767]
### Docker should start
Docker fails to start because of a problem with virtual network switch.

### Information

  - Diagnostic ID: 12AB57E5-86DC-4E7A-BDF1-9D3C6AC91D00/2018-03-01_14-18-01
  - Windows 10 Pro 1709 with all updates

#### Error message

> Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 132
at <ScriptBlock>, <No file>: line 409
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 181
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

#### Log file:
[Docker-log.txt](https://github.com/docker/for-win/files/1771448/Docker-log.txt)

### Steps to reproduce the behavior

  1. Install docker
  2. Start docker

**Comment by angdanni** [comment]
Hi,

I have the same problem

**Information**

Diagnostic id: 27D52D0B-D61A-4B4C-BE47-D6CFB1BB3382/2018-05-24_09-30-48
Log file: [log.txt](https://github.com/docker/for-win/files/2034262/log.txt)

**Comment by haakoo** [comment]
I think the issue is related to the real-time-scan of Trend Micro. It managed to install Docker-for-windows when I killed that.

Not sure why it triggered.
