### ISSUE TITLE
Unable to stop: Killed VM MobyLinuxVM did not stop

### ISSUE THREAD

**Issue by shawnlee5482** [docker/for-win#1773]
### Expected behavior
Can start/stop Docker

### Actual behavior
Unable to stop: Killed VM MobyLinuxVM did not stop
at Fatal, <No file>: line 400
at Stop-VM-Force, <No file>: line 388
at Stop-MobyLinuxVM, <No file>: line 326
at <ScriptBlock>, <No file>: line 407
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 181
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 306
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

### Information

  Diagnostic ID: 70AEDCF8-ED6D-43E6-BEAD-75A4B97225A9/2018-03-01_11-46-19
  
  Host: Windows 10 Enterprise version 1607 Build 14393.1198 , Intel Core i7-5600U CPU 64bit 16GB

### Steps to reproduce the behavior

  1. Try to start Docker for Windows
  2. Fail due to the error reported

**Comment by exrich** [comment]
+1 same issue

Diagnostic ID: FCE41835-7983-4F1A-A5E4-EE6E4B338306/2018-03-05_21-43-53

**Comment by Bleaid** [comment]
Trying to switch to Linux containers in a windows 10 results on this same error.
_(To  reproduce: Right -click on the docker icon, select switch to Linux containers)_

**Comment by nancykaystudios** [comment]
Same issue:
Unable to stop: Killed VM MobyLinuxVM did not stop
at Fatal, <No file>: line 385
at Stop-VM-Force, <No file>: line 373
at Stop-MobyLinuxVM, <No file>: line 311
at <ScriptBlock>, <No file>: line 392
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass23_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 264
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by sergray** [comment]
Same problem with Docker Desktop 2.0.0.3 in VMWare Windows 10 VM
