### ISSUE TITLE
Docker not running when enabling 'Expose Daemon without TLS' option

### ISSUE THREAD

**Issue by parenas127** [docker/for-win#1775]
### Information
  - 9086DDFF-010C-4FC3-9D41-CE8CC0BA0C7E/2018-03-02_13-48-22
  - Docker settings > tick the 'Expose daemon on tcp://localhost:2375 without TLS
  - Docker version: Docker version 17.12.0-ce, build c97c6d6

### Steps to reproduce the behavior

  1. Docker settings
  2. tick the 'Expose daemon on tcp://localhost:2375 without TLS
  3. Will prompt an error : 

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.35/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 262
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 189
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

**Comment by edd1212** [comment]
Yes, I too have the same issue.. Please help

**Comment by tonymet** [comment]
i had this issue after modifying the `127.0.0.1 localhost` line.  Comment that out and see if it works. 

this Powershell cmd shows listening ports.
```
 netstat -a -o|Select-String -Pattern 2375

  TCP    127.0.0.1:2375         DESKTOP-H2JARAN:0      LISTENING       12075
```
