### ISSUE TITLE
Docker Hyper-V & Containers not available even tough it is active

### ISSUE THREAD

**Issue by simonstappen** [docker/for-win#1786]
### Expected behavior
Docker starts properly.
### Actual behavior
Docker crashes upon start and exits with `An error occured - Docker doesn't support your Windows version. Check documentation for minimum requirements`
### Information
My log reads:
```
Version: 17.12.0-ce-win47 (15139)
Channel: stable
Sha1: 9c692cd5b38166289573183371647d915f300292
Started on: 2018/03/05 15:40:21.999
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299
BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534
File: C:\Users\simon\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[15:40:22.152][GUI            ][Info   ] Starting...
[15:40:22.794][Tracking       ][Info   ] Crash report and usage statistics are enabled
[15:40:22.798][SegmentApi     ][Info   ] Usage statistic: appLaunched
[15:40:24.139][NPS            ][Info   ] NPS user ceated on :3/5/2018 5:35:43 AM -08:00, last survey : 1/1/0001 12:00:00 AM +00:00
[15:40:24.140][SegmentApi     ][Info   ] Usage statistic: heartbeat
[15:40:24.144][SegmentApi     ][Info   ] Usage statistic: Identify
[15:40:24.257][NamedPipeClient][Info   ] Sending Version()...
[15:40:24.265][NamedPipeClient][Info   ] Received response for Version
[15:40:24.267][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings, Docker.Core.DaemonOptions)...
[15:40:24.264][NamedPipeServer][Info   ] Version()
[15:40:24.264][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:40:24.270][NamedPipeServer][Info   ] Start(Docker.Core.Settings, Docker.Core.DaemonOptions)
[15:40:24.270][PowerMode      ][Info   ] Stop
[15:40:24.270][HyperV         ][Info   ] Stop
[15:40:24.271][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[15:40:24.286][HyperV         ][Info   ] Script started at 15:40:24.286
[15:40:24.292][Moby           ][Info   ] Stop
[15:40:24.303][Linux          ][Error  ] Failed to start: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 80. Let's retry
[15:40:24.304][Installer      ][Info   ] Checking for features: Hyper-V, Containers
[15:40:24.304][PowerShell     ][Info   ] Run script...
[15:40:24.309][Installer      ][Error  ] Unable to check for available feature Hyper-V: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Dism' was not loaded because no valid module file was found in any module directory.
[15:40:24.316][NamedPipeClient][Error  ] Unable to send Start: Docker doesn't support your Windows version. Check documentation for minimum requirements
[15:40:24.309][PowerShell     ][Info   ] Run script...
[15:40:24.314][Installer      ][Error  ] Unable to check for available feature Containers: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Dism' was not loaded because no valid module file was found in any module directory.
[15:40:24.314][Installer      ][Error  ] Feature(s) not available: Hyper-V, Containers
[15:40:27.929][SystrayRemote  ][Info   ] Systray listener shutdown (cancelled)
[15:40:27.929][SystrayRemote  ][Info   ] Systray listener shutdown (cancelled)
[15:40:27.930][SystrayRemote  ][Info   ] Systray listener shutdown (cancelled)
[15:40:27.930][SystrayRemote  ][Info   ] Systray listener shutdown (cancelled)
[15:40:27.930][SystrayRemote  ][Info   ] Systray listener shutdown (cancelled)
[15:40:27.942][NamedPipeClient][Info   ] Sending Version()...
[15:40:27.943][NamedPipeClient][Info   ] Received response for Version
[15:40:27.944][NamedPipeClient][Info   ] Sending StopAll()...
[15:40:27.943][NamedPipeServer][Info   ] Version()
[15:40:27.943][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:40:27.949][NamedPipeServer][Info   ] StopAll()
[15:40:27.949][PowerMode      ][Info   ] Stop
[15:40:27.949][HyperV         ][Info   ] Stop
[15:40:27.951][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[15:40:27.965][HyperV         ][Info   ] Script started at 15:40:27.965
[15:40:27.972][Moby           ][Info   ] Stop
[15:40:27.978][NamedPipeServer][Error  ] Unable to execute StopAll: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 80    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 181
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 306
   at Docker.Backend.ContainerEngine.Linux.Stop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 153
   at Docker.Backend.Backend.StopAll() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Backend.cs:line 95
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[15:40:28.005][NamedPipeClient][Error  ] Unable to send StopAll: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
at <ScriptBlock>, <No file>: line 80
```
Hyper-V and containers seem to be enabled. Virtualization is also enabled in bios settings and spinning up regular hyper-v machines works as well.
![hyperv](https://user-images.githubusercontent.com/11631175/36981064-6a7992d4-208c-11e8-9c5c-23641cf992e1.JPG)
![cpu](https://user-images.githubusercontent.com/11631175/36981122-96af7d6e-208c-11e8-9931-4470adc890d1.JPG)

### Steps to reproduce the behavior

1.   Install Hyper-V, Containers feature on windows 10 pro.
2.   Restart
3.   Install docker
4.   Docker doesnt start

It would be great if anyone of you could help me if you ever encountered this behavior. I've already tried all solutions provides on github/stackoverflow/google but cannot get it working. Looking forward to your responses!

Kind regards
Simon

**Comment by jasonbivins** [comment]
The specified module 'Hyper-V' was not loaded - try this in powershell to see if it helps or gives a mores specific error:
`import-module Hyper-V`

**Comment by clmcgrath** [comment]
i am currently experiencing same issue on windows-server 1803 
the hyper-v is not enabled pop-up keeps coming up whenever i try to start Docker For Windows.exe
and at login

**Comment by clmcgrath** [comment]
i tried the import-module  hyper-v  and it seems to be loading the command set 
![image](https://user-images.githubusercontent.com/452012/40250781-63123a5c-5aa5-11e8-8510-b991b475a8e6.png)

**Comment by guhuajun** [comment]
Greetings,

Would you mind run bcdedit /enum and check following setting?

hypervisorlaunchtype

**Comment by balintbako** [comment]
I have the exact same issue using Docker CE 18.03 on Windows 10

The output of BCEdit is:
.hypervisorlaunchtype    Auto
