### ISSUE TITLE
Not able to run Docker

### ISSUE THREAD

**Issue by shivakumarjava1** [docker/for-win#1802]
I just installed docker on my windows 10 enterprise edition. I am getting below error when i tried ti start the docker. I tried by rebooted many time but still no luck. can anyone help me --thanks

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.
at New-MobyLinuxVM, <No file>: line 202
at <ScriptBlock>, <No file>: line 409
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 181
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[log.txt](https://github.com/docker/for-win/files/1790016/log.txt)

**Comment by jasonbivins** [comment]
Hi @shivakumarjava1 
Make sure you can open up Hyper-V manager - then run this in powershell
`powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create`

**Comment by shivakumarjava1** [comment]
I just did restore factory couple time and reboot the system. now it's fine. thanks for response.

**Comment by shivakumarjava1** [comment]
I just did restore factory couple time and reboot the system. now it's fine. thanks for response.
