### ISSUE TITLE
IOError: Can not access file in context

### ISSUE THREAD

**Issue by seanbmiller** [docker/for-win#1813]
### Expected behavior
docker-compose for windows builds

### Actual behavior
IOError during docker-compose up

### Information
  - Diagnostic ID 4AC255CF-3F3A-4317-BA32-0BDB65F61923/2018-03-09_10-04-27
  - "Enable Win32 long paths" is enabled in my Local Group Policy Editor.

### Steps to reproduce the behavior
docker-compose fails:
PS C:\...\...\...> docker-compose -f docker-compose.yml up -d --build
Building web
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\main.py", line 1001, in up
  File "compose\cli\main.py", line 997, in up
  File "compose\project.py", line 463, in up
  File "compose\service.py", line 310, in ensure_image_exists
  File "compose\service.py", line 989, in build
  File "site-packages\docker\api\build.py", line 150, in build
  File "site-packages\docker\utils\build.py", line 14, in tar
  File "site-packages\docker\utils\utils.py", line 103, in create_archive
IOError: Can not access file in context: C:\...\...\...\src\app\accountSettings\account-settings-main\components\account-settings-catalog\components\account-settings-catalog-addenda\components\account-settings-catalog-addenda-filter\account-settings-catalog-addenda-filter.component.html
Failed to execute script docker-compose
PS C:\...\...\...> docker-compose -v
docker-compose version 1.19.0, build 9e633ef3

docker build fails also during file copy to the container:
Step 15/16 : COPY ${source:-/dist} .
COPY failed: CreateFile \\?\C:\ProgramData\Docker\tmp\docker-builder144846892\dist: The system cannot find the file specified.
> docker -v
Docker version 18.03.0-ce-rc1, build c160c73

**Comment by provAlexSage** [comment]
I am seeing this on my mac as well...
```Building testserver
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/main.py", line 1001, in up
  File "compose/cli/main.py", line 997, in up
  File "compose/project.py", line 463, in up
  File "compose/service.py", line 326, in ensure_image_exists
  File "compose/service.py", line 989, in build
  File "site-packages/docker/api/build.py", line 150, in build
  File "site-packages/docker/utils/build.py", line 14, in tar
  File "site-packages/docker/utils/utils.py", line 103, in create_archive
IOError: Can not access file in context: /Users/saucey/projects/test-server/node_modules/.bin/window-size```

**Comment by rn** [comment]
This looks like a `docker-compose` issue. Could you please file an issue at https://github.com/docker/compose
