### ISSUE TITLE
Docker fails to start on Windows 10 Showing below error

### ISSUE THREAD

**Issue by raj2804** [docker/for-win#1814]
Version: 17.12.0-ce-win47 (15139)
Channel: stable
Started on: 2018/03/10 20:10:22.835
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834
An Error Occured:
Unable to create File System Image
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 95
   at Docker.Actions.<>c__DisplayClass20_0.<ResetToDefault>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 154
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by rn** [comment]
Can you upload diagnostics? We had a similar issue https://github.com/docker/for-win/issues/1540 but that was a bug in Windows on some insider builds. Alternatively can you try the latest edge release where we changed the mechanism for creating the image (which should also make it into the next stable release)
