### ISSUE TITLE
storage-driver aufs crash

### ISSUE THREAD

**Issue by daimor** [docker/for-win#1831]
### Expected behavior
docker should not crash
### Actual behavior
docker daemon crashed
```
Error response from daemon: Bad response from Docker engine

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 253
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 184
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

Crash report:
B34DA94D-7EBC-4BBB-B868-12929E1FEB43/2018-03-14_08-57-52

Version: 18.03.0-ce-rc3-win56 (16433)
Channel: edge
Sha1: b6990be78d497b77b655de2e294da59e9d182baf
Started on: 2018/03/14 08:32:34.642
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1709
Build: 16299
BuildLabName: 16299.15.amd64fre.rs3_release.170928-1534

Linux containers

### Steps to reproduce the behavior

  1. Docker Updated from the previous version, with `"storage-driver": "aufs"`
  2. Crashed after start new version
  3. Reset to factory defaults
  4. Started correctly
  5. change settings again to `"storage-driver": "aufs"`, and apply
  6. crash

**Comment by guillaumerose** [comment]
Thanks for the report. I can reproduce it. We updated the kernel and aufs didn't get properly activated. 
For the moment, I will recommend you to stay with the rc2. A rc4 will follow next week.
