### ISSUE TITLE
v18.03-rc3 Can't Run docker-compose ?

### ISSUE THREAD

**Issue by khs1994** [docker/for-win#1833]
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

```bash
PS C:\Users\90621\lnmp> docker-compose config
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 121, in perform_command
  File "compose\cli\main.py", line 329, in config
  File "compose\cli\command.py", line 67, in get_config_from_options
  File "compose\config\config.py", line 283, in find
  File "compose\config\config.py", line 283, in <listcomp>
  File "compose\config\config.py", line 183, in from_filename
  File "compose\config\config.py", line 1434, in load_yaml
  File "site-packages\yaml\__init__.py", line 94, in safe_load
  File "site-packages\yaml\__init__.py", line 70, in load
  File "site-packages\yaml\loader.py", line 24, in __init__
  File "site-packages\yaml\reader.py", line 85, in __init__
  File "site-packages\yaml\reader.py", line 124, in determine_encoding
  File "site-packages\yaml\reader.py", line 178, in update_raw
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 65: illegal multibyte sequence
[12020] Failed to execute script docker-compose
```
But v1.19.0 work
```bash
PS C:\Users\90621\lnmp> C:\bin\docker-compose.exe config
networks:
  backend:
    labels:
      com.khs1994.lnmp: "true"
      com.khs1994.lnmp.app.env: development
      com.khs1994.lnmp.backend: "true"
  frontend:
    labels:
      com.khs1994.lnmp: "true"
      com.khs1994.lnmp.app.env: development
      com.khs1994.lnmp.frontend: "true"
secrets:
...
```

**Comment by khs1994** [comment]
I download `docker-compose` v1.19.0 from github, and replace it in `C:\Program Files\Docker\Docker\resources\bin` it work !

**Comment by khs1994** [comment]
@shin-
