### ISSUE TITLE
Not able to start Docker

### ISSUE THREAD

**Issue by sudipto92** [docker/for-win#1842]
### Actual behavior
Version: 17.12.0-ce-win47 (15139)
Channel: stable
Sha1: 9c692cd5b38166289573183371647d915f300292
Started on: 2018/03/16 13:28:39.881
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834

at <ScriptBlock>, <No file>: line 407    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 181
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 306
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 129
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[13:59:05.409][NamedPipeClient][Error  ] Unable to send Start: Unable to stop: Killed VM MobyLinuxVM did not stop
at Fatal, <No file>: line 400
at Stop-VM-Force, <No file>: line 388
at Stop-MobyLinuxVM, <No file>: line 326
at <ScriptBlock>, <No file>: line 407
[13:59:05.413][Notifications  ][Error  ] Unable to stop: Killed VM MobyLinuxVM did not stop
at Fatal, <No file>: line 400
at Stop-VM-Force, <No file>: line 388
at Stop-MobyLinuxVM, <No file>: line 326
at <ScriptBlock>, <No file>: line 407

### Steps to reproduce the behavior
  1. Start Docker For Windows

Please check above log.

**Comment by LoganFraser** [comment]
I have this exact error on Windows 10 Pro.  Fresh install of Docker.

**Comment by LeslieMurphy** [comment]
I have a different startup failure.  Docker did not start after reboot. Icon remained in the animated "Docker is starting" state for many minutes after by OS reboot.  Uploaded diagnostic E0D1C2FD-9EA0-4839-ADC2-D0AEEC8DA49C/2018-03-18_14-30-07

My MobyLinuxVM was hung up at 23% CPU (100% one core) in Hyper-V Manager.  I reset the VM and then restarted Docker For Windows.  Came back up then.



14:28:13.453][ApiProxy       ][Info   ] time="2018-03-18T14:28:13-06:00" msg="proxy >> GET /_ping\n"
[14:28:13.453][ApiProxy       ][Info   ] time="2018-03-18T14:28:13-06:00" msg="Dial Hyper-V socket aa185a96-780f-4986-9cf2-141689c963f1:23a432c2-537a-4291-bcb5-d62504644739"
[14:28:43.454][ApiProxy       ][Info   ] time="2018-03-18T14:28:43-06:00" msg="A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
[14:28:43.458][ApiProxy       ][Info   ] time="2018-03-18T14:28:43-06:00" msg="proxy >> GET /v1.35/version\n"
[14:28:43.458][ApiProxy       ][Info   ] time="2018-03-18T14:28:43-06:00" msg="Dial Hyper-V socket aa185a96-780f-4986-9cf2-141689c963f1:23a432c2-537a-4291-bcb5-d62504644739"
[14:29:13.459][ApiProxy       ][Info   ] time="2018-03-18T14:29:13-06:00" msg="A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

**Comment by mdwhitis** [comment]
I have the samw issue on Windows 10 Pro version 1709  OS build 162999.309
Hyper V is enabled.
Virtualization is enabled.

**Comment by berkum** [comment]
Same problem here

**Comment by sudipto92** [comment]
Issue get resolved... Run Docker for windows as a ADMIN

**Comment by sudipto92** [comment]
Issue get resolved... Run Docker for windows as a ADMIN
