### ISSUE TITLE
Docker control application freezes  on volume sharing and needs to be killed

### ISSUE THREAD

**Issue by 1605200517** [docker/for-win#1853]
### Expected behavior
I can add a volume to shared as suggested in the Docker settings

### Actual behavior

- go to Settings/Shared Drives
- select any writable drive, e.g. C or D
- click apply
- Docker control application freezes until you quit Docker (the client/daemon can be still used in background however so the freeze is jut about the control app)

### Information

  - Diagnostic ID 99071758-71EE-4434-938A-45DEF36AD8C5/2018-03-19_09-50-58

Tested both with latest stable (17.x) and edge (18.x).

**Comment by jasonbivins** [comment]
Hi @1605200517   It looks like your firewall is blocking SMB - I also saw a few SM errors in the event viewer logs
https://success.docker.com/article/error-a-firewall-is-blocking-file-sharing-between-windows-and-the-containers

**Comment by LeslieMurphy** [comment]
I uploaded diagnostic E0D1C2FD-9EA0-4839-ADC2-D0AEEC8DA49C/2018-03-22_13-20-24

Volume sharing was working, then all of a sudden it stopped in the middle of my day.  I used reset credentials and re-enabled the drives.  The Docker client prompted me for my local credentials and accepted them.  But then right afterwards it unchecked the shared volumes!

Quitting docker and then restarting it usually fixes my sporadic volume sharing issue.  But why is this happening?  It is very annoying as Visual Studio debugging requires volume sharing to work (debugging .Net Core apps).  Today doing a stop/restart did not help.  When Docker came back up the shared drives were unchecked.  I checked them, and interestingly it did not prompt for auth credentials!  But even after selecting it still did not work.  I tried one more stop/restart cycle. Docker came back up with the drives selected.   That time it worked!

**Comment by ChrisOrton** [comment]
### Same issue

Docker version
~~~
Version 18.06.0-ce-win72 (19098)
Channel: stable
5513f91
~~~

Restarting Docker leads to Error
~~~
Unable to stop: Killed VM MobyLinuxVM did not stop
at Fatal, <No file>: line 385
at Stop-VM-Force, <No file>: line 373
at Stop-MobyLinuxVM, <No file>: line 311
at <ScriptBlock>, <No file>: line 392
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 183
   at Docker.Backend.ContainerEngine.Linux.DoStop() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 350
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 176
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180
~~~

~~~
A crash report has been uploaded with diagnostic id:
E72772DB-936E-42F9-A26B-CED981B10C16/20180807083336
~~~

**Comment by gcollombet** [comment]
Same issue

/remove-lifecycle stale

Windows 10 Entreprise, Version 1703, OS Version 15063.1446
