### ISSUE TITLE
Docker fails to start

### ISSUE THREAD

**Issue by somayedkh** [docker/for-win#1857]
### Expected behavior
Docker to start 

### Actual behavior
Docker fails to start , error occures 

### Information
  - A diagnostic was uploaded with id: DE2241D6-20F6-4D31-BFFC-AA975199C600/2018-03-19_17-38-29 

Docker fails to start in my machine. Here is the error I got everytime trying to start it: 

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid namespace 

   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 256
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 189
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

I also add the log file for more information. 

Thanks in advance!

[docker-log.txt](https://github.com/docker/for-win/files/1825924/docker-log.txt)

**Comment by jasonbivins** [comment]
Hi @somayedkh 
Can you check to see if this runs in Powershell or if you get the same error? 
`Get-NetIPInterface`

**Comment by somayedkh** [comment]
Hi @jasonbivins 
Yes, I got the same error... and I couldn't solve it.

**Comment by somayedkh** [comment]
I solved this issue. WMI repository was corrupted and I fixed it.

**Comment by rn** [comment]
thanks for getting back. Could you post here how you fixed the WMI corruption? I think other users may also have similar issues. In the meantime I'm closing this issue
