### ISSUE TITLE
Docker fails to start on Win 10 Enterprise

### ISSUE THREAD

**Issue by Stoffe** [docker/for-win#1860]
### Actual behavior
Docker fails to start, Vt-X enabled in bios, and Hyper-V installed.
Hyper-v tested and works...

### Information

  - Diagnostic ID: 85D94797-8E24-474A-8C10-14D7EE00C3ED/2018-03-20_10-19-52

[09:46:33.176][NamedPipeServer][Error  ] Unable to execute Start: Docker hv-sock proxy (vsudd) is not reachable    at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 293
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 260
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

**Comment by dgeissl** [comment]
I've had the same problem after a firmware update. 
Going to the Daemon settings and hitting "Apply" again did restart the daemon and it was working fine after that again.

**Comment by Stoffe** [comment]
Hmm, nope, tried both apply, tried advanced, tried with experimental features both on and off...
Nada, still fails to start :/

**Comment by mdwhitis** [comment]
Opening an Admin Powershell and doing:
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V –All
Worked for me an Windows 10 Pro when having the same issue.

**Comment by rn** [comment]
I've looked at all supplied diagnostics in this issue and other "Docker hv-sock proxy (vsudd) is not reachable" and they seem to fall into three categories:

- Running Docker for Windows inside a Windows 10 VM. This is problematic as we have no visibility of your Windows VM configuration and activity on the host. Because of that we can't support this configuration. See also https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios
- The Linux VM is very slow booting. Please take a look at: https://github.com/docker/for-win/issues/1995
- There was a linux kernel crash of some sort. Please take a look at: https://github.com/docker/for-win/issues/1994

If you have provided a diagnostics ID, I've added you to the relevant issue, so I'm closing this issue.
