### ISSUE TITLE
Docker does not start.

### ISSUE THREAD

**Issue by craigemery** [docker/for-win#1864]
### Expected behavior
Docker Version 18.03.0-ce-rc4-win57 (16511) starts
### Actual behavior
Docker does not.
### Information
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create the virtual hard disk.

The system failed to create 'C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx'.
at New-MobyLinuxVM, <No file>: line 208
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 51
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
DCE1442C-3E06-41C2-B0EC-45810F011F06/2018-03-21_08-34-20

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ... Install Docker Edge
  2. ...Wait for it to crash

**Comment by craigemery** [comment]
Log:
Version: 18.03.0-ce-rc4-win57 (16511)
Channel: edge
Sha1: f280152707201941918732694bf07f5ecaf4fa24
Started on: 2018/03/20 17:25:41.210
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.2125.amd64fre.rs1_release.180301-2139
File: C:\Users\c_emery\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[00:25:43.926][SegmentApi     ][Info   ] Usage statistic: heartbeat
[01:25:43.837][SegmentApi     ][Info   ] Usage statistic: heartbeat
[02:25:43.759][SegmentApi     ][Info   ] Usage statistic: heartbeat
[03:25:43.667][SegmentApi     ][Info   ] Usage statistic: heartbeat
[04:25:43.562][SegmentApi     ][Info   ] Usage statistic: heartbeat
[05:25:43.448][SegmentApi     ][Info   ] Usage statistic: heartbeat
[06:25:43.362][SegmentApi     ][Info   ] Usage statistic: heartbeat
[07:25:43.285][SegmentApi     ][Info   ] Usage statistic: heartbeat
[08:25:01.525][SegmentApi     ][Info   ] Usage statistic: eventElectedForFeature
[08:25:01.526][SegmentApi     ][Info   ] Usage statistic: stateFeatureEnabled
[08:25:01.566][SegmentApi     ][Info   ] Usage statistic: eventElectedForFeature
[08:25:01.567][SegmentApi     ][Info   ] Usage statistic: stateFeatureEnabled
[08:25:03.699][SegmentApi     ][Info   ] Usage statistic: actionMenuFeedback
[08:25:03.909][NamedPipeClient][Info   ] Sending Version()...
[08:25:03.909][NamedPipeClient][Info   ] Sending Version()...
[08:25:03.909][NamedPipeClient][Info   ] Received response for Version
[08:25:03.909][NamedPipeClient][Info   ] Sending TryGetVhdxSize()...
[08:25:03.909][NamedPipeClient][Info   ] Received response for Version
[08:25:03.909][NamedPipeClient][Info   ] Sending TryGetVhdxSize()...
[08:25:03.909][NamedPipeServer][Info   ] Version()
[08:25:03.909][NamedPipeClient][Info   ] Sending Version()...
[08:25:03.909][NamedPipeClient][Info   ] Sending Version()...
[08:25:03.909][NamedPipeServer][Info   ] Version done in 00:00:00.
[08:25:03.909][NamedPipeServer][Info   ] Version()
[08:25:03.909][NamedPipeServer][Info   ] Version done in 00:00:00.
[08:25:03.909][NamedPipeServer][Info   ] TryGetVhdxSize()
[08:25:03.909][PowerShell     ][Info   ] Run script 'Get-VHD –Path "" | select -ExpandProperty Size'...
[08:25:03.909][NamedPipeServer][Info   ] TryGetVhdxSize()
[08:25:03.909][PowerShell     ][Info   ] Run script 'Get-VHD –Path "" | select -ExpandProperty Size'...
[08:25:04.705][NamedPipeClient][Info   ] Received response for Version
[08:25:04.705][NamedPipeClient][Info   ] Received response for Version
[08:25:04.705][NamedPipeClient][Info   ] Sending TryGetVhdxSize()...
[08:25:04.705][NamedPipeClient][Info   ] Sending TryGetVhdxSize()...
[08:25:04.705][NamedPipeServer][Info   ] Version()
[08:25:04.705][NamedPipeServer][Info   ] Version done in 00:00:00.
[08:25:04.705][NamedPipeServer][Info   ] Version()
[08:25:04.705][NamedPipeServer][Info   ] Version done in 00:00:00.
[08:25:04.705][NamedPipeServer][Info   ] TryGetVhdxSize()
[08:25:04.705][PowerShell     ][Info   ] Run script 'Get-VHD –Path "" | select -ExpandProperty Size'...
[08:25:04.705][NamedPipeServer][Info   ] TryGetVhdxSize()
[08:25:04.705][PowerShell     ][Info   ] Run script 'Get-VHD –Path "" | select -ExpandProperty Size'...
[08:25:05.142][NamedPipeClient][Info   ] Received response for TryGetVhdxSize
[08:25:05.142][NamedPipeServer][Info   ] TryGetVhdxSize done in 00:00:01.2335874.
[08:25:05.142][NamedPipeClient][Info   ] Received response for TryGetVhdxSize
[08:25:05.142][NamedPipeServer][Info   ] TryGetVhdxSize done in 00:00:00.4374863.
[08:25:05.158][NamedPipeClient][Info   ] Received response for TryGetVhdxSize
[08:25:05.158][NamedPipeClient][Info   ] Sending Version()...
[08:25:05.158][NamedPipeServer][Info   ] TryGetVhdxSize done in 00:00:00.4531124.
[08:25:05.158][NamedPipeClient][Info   ] Received response for Version
[08:25:05.158][NamedPipeClient][Info   ] Sending TryGetVhdxSize()...
[08:25:05.158][NamedPipeServer][Info   ] Version()
[08:25:05.158][NamedPipeServer][Info   ] Version done in 00:00:00.
[08:25:05.158][NamedPipeServer][Info   ] TryGetVhdxSize()
[08:25:05.158][PowerShell     ][Info   ] Run script 'Get-VHD –Path "" | select -ExpandProperty Size'...
[08:25:05.173][NamedPipeClient][Info   ] Received response for TryGetVhdxSize
[08:25:05.173][NamedPipeServer][Info   ] TryGetVhdxSize done in 00:00:00.0156299.
[08:25:05.220][NamedPipeClient][Info   ] Received response for TryGetVhdxSize
[08:25:05.220][NamedPipeServer][Info   ] TryGetVhdxSize done in 00:00:01.3117187.
[08:25:43.181][SegmentApi     ][Info   ] Usage statistic: heartbeat
[08:34:20.079][FeedbackSettings][Info   ] Upload diagnostic
[08:34:20.079][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[08:34:20.079][NamedPipeClient][Info   ] Sending Version()...
[08:34:20.110][NamedPipeClient][Info   ] Sending Version()...
[08:34:20.110][NamedPipeClient][Info   ] Sending Version()...
[08:34:20.125][CrashReport    ][Warning] Unable to collect features settings: Could not find file 'C:\Users\c_emery\AppData\Roaming\Docker\features-overrides.json'.
[08:34:20.141][NamedPipeClient][Info   ] Received response for Version
[08:34:20.141][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\c_emery\AppData\Local\Temp\liqw5feh.hp3\mobyLogs.tar)...
[08:34:20.125][NamedPipeServer][Info   ] Version()
[08:34:20.125][NamedPipeServer][Info   ] Version done in 00:00:00.
[08:34:20.141][NamedPipeClient][Info   ] Received response for Version
[08:34:20.141][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\c_emery\AppData\Local\Temp\liqw5feh.hp3\win_containers)...
[08:34:20.125][NamedPipeServer][Info   ] Version()
[08:34:20.141][NamedPipeClient][Info   ] Received response for Version
[08:34:20.141][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\c_emery\AppData\Local\Temp\liqw5feh.hp3\pcap.tar)...
[08:34:20.125][NamedPipeServer][Info   ] Version done in 00:00:00.
[08:34:20.141][NamedPipeServer][Info   ] Version()
[08:34:20.141][NamedPipeServer][Info   ] Version done in 00:00:00.
[08:34:20.141][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\c_emery\AppData\Local\Temp\liqw5feh.hp3\win_containers)
[08:34:20.141][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\c_emery\AppData\Local\Temp\liqw5feh.hp3\mobyLogs.tar)
[08:34:20.157][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\c_emery\AppData\Local\Temp\liqw5feh.hp3\pcap.tar)
[08:34:20.157][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[08:34:20.157][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[08:34:20.157][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.
[08:34:20.172][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[08:34:20.306][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[08:34:20.297][HyperV         ][Warning] Unable to download logs: Connection failed
[08:34:20.306][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.1645975.
[08:34:31.064][FeedbackSettings][Info   ] Open logs
