### ISSUE TITLE
Docker client fails to start on windows 10 Pro

### ISSUE THREAD

**Issue by kvickyk** [docker/for-win#1873]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - Windows Version: windows 10 Pro
  - Docker for Windows Version: 

### Information
Diagnostic ID: 
[docker-log.txt](https://github.com/docker/for-win/files/1843511/docker-log.txt)
2A618FBF-21C3-4367-9E79-7749178DB805/2018-03-23_14-11-22

### Steps to reproduce the behavior

  1. Install Docker client on windows
  2. Allow docker to Enable Hyper-V and restart
 3. Fails on restart.

`Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'VKADARU-PC' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 132
at <ScriptBlock>, <No file>: line 409
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 181
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145`

**Comment by daanl** [comment]
Same problem here any luck?

**Comment by kvickyk** [comment]
Yes. I noticed that the "Hyper-V Virtual Machine Management" services crashes after about 5 min or so. Check your Event viewer to see if it crashed for you.

After some googling and [turning on CFG](https://social.technet.microsoft.com/Forums/en-US/5baf98f4-d96b-4fc7-8a02-6781304cf6c5/hyper-v-problem-with-installing-and-launching-on-windows-10-1709?forum=win10itprovirt) (Control Flow Guard), I got a different error this time.

```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled


   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass16_0.<ResetToDefault>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 124
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

**Comment by kvickyk** [comment]
After performing some restarts on docker I see a new error

```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID EB564031-8F7C-4DF4-BE20-CD8BE865AE45)

'MobyLinuxVM' failed to start worker process: Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source. (0xC0000428). (Virtual machine ID EB564031-8F7C-4DF4-BE20-CD8BE865AE45)
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass16_0.<ResetToDefault>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 124
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

**Comment by kvickyk** [comment]
Finally got it working. I ran the following commands from [here] (https://github.com/docker/for-win/issues/794#issuecomment-308436032).

1. Open powershell in administrator mode
2. Navigate to directory `C:\Program Files\Docker\Docker\resources`
3. Run the following commands

```
powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -destroy
```

```
powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create
```


Output:
```
PS C:\Program Files\Docker\Docker\resources> powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -destroy
Script started at 16:14:00.324
Module loaded at 16:14:01.877
VM MobyLinuxVM does not exist
Destroying Switch DockerNAT...
Removing VM MobyLinuxVM...
Delete VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
PS C:\Program Files\Docker\Docker\resources> powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create
Script started at 16:14:06.179
Module loaded at 16:14:07.806
Creating Switch: DockerNAT...
Switch created.
Set IP address on switch
Creating VM MobyLinuxVM...
Setting CPUs to 2 and Memory to 2048 MB
Creating dynamic VHD: C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
Connect Internal Switch DockerNAT
Attach DVD .\docker-for-win.iso
Disabled Guest Service Interface
Enabled Heartbeat
Disabled Key-Value Pair Exchange
Enabled Shutdown
Enabled Time Synchronization
Disabled VSS
VM created.
```

**Comment by mikebz** [comment]
I am having the same issue.  Can't run Linux containers on my Win 10 Pro VM.

**Comment by coatsnmore** [comment]
Same issue on Version 18.03.1-ce-win65 (17513).

**Comment by Cesar-Ofi** [comment]
Same issue here

**Comment by adamcoulombe** [comment]
Same issue here. Cannot get docker to work for me :(

**Comment by rifaterdemsahin** [comment]
I am running it on parallels and memory is left like 1.37 GB. Is this an excuse for me to buy the nex mac book pros with 32 GB of RAM and spend 4k to run Docker in mac using Parallels.

Error

Unable to launch process: 1314
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass23_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 262
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by danilobreda** [comment]
Worked for me the command to remove the VM:
powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -destroy

When I use the command to created the vm, i got a error.

I tried to remove the adapters from the hyper-v, because the nature of the error, the only way is something like this: [Remove Network Adpater MSDN](https://blogs.msdn.microsoft.com/jjameson/2011/03/14/removing-stale-network-adapters-in-hyper-v-vm/)

After removed the adapter i reseted by factory the docker.

Worked 👍

**Comment by mjames7777** [comment]
This worked fine for me you must run PowerShell in Admin mode -- then restart docker

**Comment by pharophy** [comment]
Maybe this will help someone else.  I followed @kvickyk 's powershell commands, but the second command threw an error that the object already exists.  I went into Control Panel > Network and Internet > Network Connections and found that I had a network connection called "Broken Docker Adapter."  I disabled that in addition to the "vEthernet (DockerNAT) 2" connection, then re-enabled "vEthernet (DockerNAT) 2."  

<img width="590" alt="network connetions" src="https://user-images.githubusercontent.com/921945/51410496-cc374600-1b32-11e9-9d02-aa69f898ed89.png">

After that, I re-ran this command:
`powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create`
Then, I started Docker and it seems to be working fine now.

**Comment by sergeykad** [comment]
I got a similar issue.
Diagnostic ID: AB998F36-DB20-41D1-9892-04A33188F928/20190207221259

```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to change state.
at Start-MobyLinuxVM, <No file>: line 296
at <ScriptBlock>, <No file>: line 412
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

**Comment by techsavvypp** [comment]
I got this issue. Any solution?



Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 155
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by ludogithub** [comment]
Same here since last Docker update :

Unable to create: L’exécution de la commande s’est arrêtée, car la variable de préférence « ErrorActionPreference » ou le paramètre courant a la valeur Stop : Hyper-V a rencontré une erreur lors d’une tentative d’accès à un objet sur l’ordinateur « LAPTOP-0MEKR2TS », car l’objet est introuvable. L’objet a peut-être été supprimé. Vérifiez que le service de gestion d’ordinateurs virtuels est en cours d’exécution sur l’ordinateur.
à New-Switch, <Aucun fichier> : ligne 121
à <ScriptBlock>, <Aucun fichier> : ligne 411
   à Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) dans C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:ligne 36
   à Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) dans C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:ligne 92
   à Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() dans C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:ligne 155
   à Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() dans C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:ligne 59

**Comment by techsavvypp** [comment]
![image](https://user-images.githubusercontent.com/42607623/55472131-f58f4a80-5628-11e9-9b4d-e47fe2443748.png)


I am getting this error while running ' powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create '

**Comment by danilobreda** [comment]
@techsavvypp see my steps on above,  the problema is that you are creating the vm with a adapter that is bugged, you need to delete the newtwork adapter.

**Comment by qfdk** [comment]
Same issue here. Cannot get docker to work for me :(

Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3
