### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by bernardpumped** [docker/for-win#1886]
Help I just updated my docker CE for windows to 18.03.0-ce-win59 (16762) stable Channel d70d80d
and it fails to start with  "An item with the same key has already been added". I've submitted a diagnostics log. Have tried all reinstalling disable/re-enable Hyper-V but makes no difference, 
Please help as i'm now dead in the water

Error as follows

An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Docker.Backend.Processes.ApiProxy.GetEnvVars() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\ApiProxy.cs:line 55
   at Docker.Backend.Processes.ApiProxy.StartWinNamedPipe(Settings settings, String daemonNamedPipe) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\ApiProxy.cs:line 72
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 218
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 93
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144

**Comment by abcNocturn** [comment]
+1
Just updated Docker today after the message dialog.
Tried Linux/Windows Containers, reboot and Edge-Version.
Both crash.

**Comment by bernardpumped** [comment]
Hi Daniel,
I'm on Windows 10, how do i switch back to 17.12.0-ce-win47

regards

**Comment by abcNocturn** [comment]
Hey Bernard,
had to search a littlebit:
https://docs.docker.com/docker-for-windows/release-notes/#docker-community-edition-17120-ce-win47-2018-01-12

regards

**Comment by NicoKno** [comment]
+1

Same problem. I also removed all docker correlated directories from my system and reinstalled. Problem persists.

Switching back to 17.12.0 worked for me either.

**Comment by bernardpumped** [comment]
thanks Daniel  that did the trick.
Can you believe docker releasing without basic installation system testing, shocking

**Comment by abcNocturn** [comment]
Your welcome Bernard, 
guess the guys behind docker are only humans too ;)

**Comment by bernardpumped** [comment]
yeah fair enough 8-)
