### ISSUE TITLE
"Timeout has expired" when switching to Windows containers

### ISSUE THREAD

**Issue by clabough** [docker/for-win#1898]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 Enterprise 1709 build 16299.334
  - Docker for Windows Version: 18.03.0-ce-win59 (16762)

### Expected behavior
Successful switch to Windows containers

### Actual behavior
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(String args, Dictionary`2 env) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 152
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 218
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 93
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144

### Information
Diagnostics ID
480BEAD7-4CB7-4585-90E7-781D712A18C1/2018-03-29_11-59-26

### Steps to reproduce the behavior

  1. Click "Switch to Windows containers..."

**Comment by clabough** [comment]
So I thought I'd try to uninstall/reinstall (selecting Windows Containers in the setup) and now get this.

> Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(String args, Dictionary`2 env) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 152
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 218
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 93
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144

Diagnostic ID 480BEAD7-4CB7-4585-90E7-781D712A18C1/2018-03-30_10-14-35

**Comment by clabough** [comment]
I had to go back to 17.09.1-ce-win42 (14687) to be able to switch to Windows containers.

**Comment by clabough** [comment]
This error is still happening in Version 18.03.1-ce-win64 (17438)

ID: 480BEAD7-4CB7-4585-90E7-781D712A18C1/2018-04-26_10-13-30

**Comment by clabough** [comment]
Just tried Version 18.03.1-ce-win65 (17513) after applying WU 1803 yesterday and installation went fine without the timeout issue

**Comment by necroTaxonomist** [comment]
bump

I'm on Version 18.03.1-ce-win65 (17513) and getting this error

> Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(String args, Dictionary`2 env) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 152
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 218
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 93
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144

I also need to use Windows and Linux containers at the same time, which as far as I can tell only works past ce-win56, so I can't go back to an earlier version

**Comment by necroTaxonomist** [comment]
Okay, it works with 18.03.0-ce-win59 for some reason. /shrug

**Comment by Ranger1230** [comment]
I'm getting this same error in 18.06.0-cs-win72.
Diagnostic id:
0AE42C4B-ECE2-4D0D-B98D-AC1FC5CAD236/20180730095629

**Comment by Rich-Ott** [comment]
I was getting this same error and upon investigation saw that "Windows Hypervisor Platform" was disabled in _Windows Features_, even though the Containers and Hyper-V options were enabled. After enabling the **Windows Hypervisor Platform** feature and rebooting, Docker was able to start with Windows containers (and switch back and forth between linux and windows containers without error).

**Comment by Aprosystem** [comment]
Version 18.06.1-ce-win73 (19507)

Limit czasu upłynął i operacja nie została ukończona.
   w System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   w Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(String args, Dictionary`2 env) w C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:wiersz 176
   w Docker.Backend.Processes.WindowsDockerDaemon.Start(Settings settings, String daemonOptions) w C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:wiersz 136
   w Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) w C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:wiersz 222
   w Docker.Backend.ContainerEngine.Windows.Restart(Settings settings, String daemonOptions) w C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:wiersz 153
   w Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) w C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:wiersz 48
   w Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) w C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:wiersz 180

**Comment by TheBlueSky** [comment]
I've been facing this issue for a while now and still cannot switch to Windows Containers. Currently I'm on version 18.06.1-ce-win73 (19507) and Windows 10 version 1809. I also reported the issue multiple times through the crash screen.

Can we have someone from Docker for Windows team to comment on this issue?

**Comment by TheBlueSky** [comment]
This one is from just now:

    Timed out while waiting for Docker daemon to be ready
       at Docker.Backend.Processes.WindowsDockerDaemon.WaitForDaemonToBeReady() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 147
       at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 222
       at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 96
       at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
       at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180

Hyper-V is installed (I successfully run VMs and Linux Containers) and I tried to switch to Windows Container with Windows Hypervisor Platform enabled and disabled.

@mat007, can we have someone to comment on this one. I don't know who are the people in charge of this repo, just saw you active in closing/triaging issues.

**Comment by Monte-Christo** [comment]
[Look at this suggestion.](https://github.com/docker/for-win/issues/2697#issuecomment-427197825)

**Comment by zhangxin511** [comment]
Had a recent windows update and stop working. Using this approach helped me. THX @Rich-Ott 

> I was getting this same error and upon investigation saw that "Windows Hypervisor Platform" was disabled in _Windows Features_, even though the Containers and Hyper-V options were enabled. After enabling the **Windows Hypervisor Platform** feature and rebooting, Docker was able to start with Windows containers (and switch back and forth between linux and windows containers without error).
