### ISSUE TITLE
Docker is not installing on windows 8.1

### ISSUE THREAD

**Issue by flik** [docker/for-win#1908]
I have downloaded the docker for windows from https://store.docker.com/editions/community/docker-ce-desktop-windows
and when I tried to install, it is giving me errors:```

Method not found: 'Windows.Data.Json.JsonArray Windows.Data.Json.JsonObject.GetNamedArray(System.String, Windows.Data.Json.JsonArray)'.
at LightweightInstaller.Manifest.FromJson(String json)
at LightweightInstaller.ExtractManifestStep.d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at LightweightInstaller.InstallWorkflow.d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at LightweightInstaller.InstallWorkflow.d__23.MoveNext()
```

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version: 8.1
  - Docker for Windows Version:

### Expected behavior
install to windows
### Actual behavior
given errors


### Information
<!--
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
-->

### Steps to reproduce the behavior


   1.  Download from https://store.docker.com/editions/community/docker-ce-desktop-windows
    2. Install it on widows 8.1
    You will get errors.

**Comment by jasonbivins** [comment]
Hi @flik   Due to Hyper-V requirements Docker for WIndows requires Windows 10
https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install

You can use our legacy app Docker toolbox if you can't upgrade to Win 10 for some reason though
https://docs.docker.com/toolbox/overview/
