### ISSUE TITLE
Docker 18.03 not start on windows containers mode, "The file size exceeds the limit allowed and cannot be saved"

### ISSUE THREAD

**Issue by interpeix** [docker/for-win#1918]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have submitted Diagnostics
  - [x ] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 Enterprise 1709 16299.248
  - Docker for Windows Version: 18.03.0-ce-win59 (16762)

### Expected behavior
Work with windows containers like previous version.
### Actual behavior
Software crash at startup.
### Information
DEB03AED-4FC5-4C2B-AD08-56FD7BFADC9A/2018-04-05_08-54-37

The file size exceeds the limit allowed and cannot be saved
   at System.Diagnostics.EventLogInternal.get_EntryCount()
   at System.Diagnostics.EventLogInternal.StartListening(String currentMachineName, String currentLogName)
   at System.Diagnostics.EventLogInternal.StartRaisingEvents(String currentMachineName, String currentLogName)
   at System.Diagnostics.EventLogInternal.set_EnableRaisingEvents(Boolean value)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(String args, Dictionary`2 env) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 152
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 218
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 93
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src

### Steps to reproduce the behavior

  1. Try to install with the option "Use windows containers..." or Install without that option and switch later to windows containers.

**Comment by interpeix** [comment]
After further investigation and a lot of guessing xD I have be able to solve the issue clearing the Windows Application Log whose size was 20MB.
