### ISSUE TITLE
Cannot start docker in windows 10 version 1709.

### ISSUE THREAD

**Issue by aevers1967** [docker/for-win#1921]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have submitted Diagnostics
  - [ X] I have included the Diagnostics ID in this Issue 
  - Windows Version:  Windows 10 version 1709
  - Docker for Windows Version:   18.03.0-ce

### Steps to reproduce the behavior

  1. ... Just trying to start docker
  2. ...

**Comment by stephen-turner** [comment]
There is not much to go on here. Could you describe the symptoms?

**Comment by aevers1967** [comment]
I installed the docker and startr docker then i get the following error message: 

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID B3334DDA-723E-4344-88E2-30F26E01F6AF)

'MobyLinuxVM' failed to start worker process: The specified module could not be found. (0x8007007E). (Virtual machine ID B3334DDA-723E-4344-88E2-30F26E01F6AF)

'MobyLinuxVM' could not initialize. (Virtual machine ID B3334DDA-723E-4344-88E2-30F26E01F6AF)

'MobyLinuxVM' Microsoft Emulated IoAPIC (Instance ID 72682FC4-040A-430A-BE0B-224574B953FE): Failed to create instance with error 'The specified module could not be found.' (0x8007007E). (Virtual machine ID B3334DDA-723E-4344-88E2-30F26E01F6AF)
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass23_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 264
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by jasonbivins** [comment]
Hi @aevers1967 
Can you provide a diagnostic ID as well?
It looks like there might be a missing Powershell module - try this 
```import-module hyper-v```

**Comment by jasonbivins** [comment]
@aevers1967   
It sounds like you're having a problem with PS itself that you'll need to troubleshoot, 
 what error did you get?
From the logs, its  failing in the middle of importing these Modules - 

`Import-Module Microsoft.PowerShell.Utility
Import-Module Microsoft.PowerShell.Management
Import-Module Hyper-V
Import-Module NetAdapter
Import-Module NetTCPIP`

**Comment by jasonbivins** [comment]
From your event viewer logs in the diagnostics - it looks like the problem is with Hyper-V itself instead of PS
`The Microsoft Hyper-V Guest Infrastructure Driver service failed to start due to the following error: 
A device attached to the system is not functioning.`
