### ISSUE TITLE
Docker Crashes on Start   - Docker for Windows Version:  18.03.0-ce-win59 (16762)

### ISSUE THREAD

**Issue by mdwhitis** [docker/for-win#1923]
Crash Report:
CBAB554F-D929-47D0-9451-7C603BD5463F/2018-04-06_09-30-17

  - [ X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have submitted Diagnostics
  - [X] I have included the Diagnostics ID in this Issue
  - Windows Version:  10 pro version 1803 build 17133.1
  - Docker for Windows Version:  18.03.0-ce-win59 (16762)

### Expected behavior
docker starts.

### Actual behavior
docker crashes

### Information
  - Diagnostic ID CBAB554F-D929-47D0-9451-7C603BD5463F/2018-04-06_09-30-17
 
### Steps to reproduce the behavior

  1.  Start docker for windows

**Comment by mdwhitis** [comment]
The Error says to check the virtual machine manager is running 
![virtual-machinr managemeny](https://user-images.githubusercontent.com/182369/38467551-fac19f68-3aee-11e8-8949-6cdc9c28a38b.PNG)

**Comment by zersiax** [comment]
I have a similar issue. VMM is definitely running

**Comment by mdwhitis** [comment]
Docker Edge Build crashes as well: 
Version 18.03.0-ce-win58 (16761)
Channel: edge
8c7c9dc

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'EVIL-E' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 51
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

[log.txt](https://github.com/docker/for-win/files/1889270/log.txt)

**Comment by mdwhitis** [comment]
It works if you use Windows containers instead of Linux Containers
[log-works.txt](https://github.com/docker/for-win/files/1889372/log-works.txt)

**Comment by mdwhitis** [comment]
I got it working again by following these instructions:
https://github.com/linuxkit/lcow

now I can do stuff like:
docker run --platform linux --rm -ti centos:latest
Unable to find image 'centos:latest' locally
latest: Pulling from library/centos
469cfcc7a4b3: Pull complete
Digest: sha256:bc494daa9d9ad7e37f93236fbd2c3f372739997c6336ef3c321e227f336e73d3
Status: Downloaded newer image for centos:latest

**Comment by mdwhitis** [comment]
Fails with newest release as well...

Version 18.04.0-ce-rc2-win61 (17070)
Channel: edge
f3c9ab6

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'EVIL-E' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass23_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 261
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by mdwhitis** [comment]
Fixed this by doing a windows 10 "refresh" and reinstall of docker.
Works now.

**Comment by srimajji** [comment]
@mdwhitis did you by any chance try it with the latest windows insider release?

**Comment by mdwhitis** [comment]
Yes I did.

**Comment by rn** [comment]
This this seems to be fixed for the original poster, closing this issue
