### ISSUE TITLE
Docker won't start (Win10 15063, Windows containers)

### ISSUE THREAD

**Issue by yurieastwood** [docker/for-win#1941]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [ X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X ] I have submitted Diagnostics
  - [ X ] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10.0 Pro Build 15063 Rev 0
  - Docker for Windows Version: 18.03.0-ce-win59 (16762)

### Expected behavior
After installing Docker with Windows Containers as default program should start normally.

### Actual behavior
Program is failling to start with "An error ocurred" and the following stack trace:

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 218
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 93
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144

### Information
7FEC80B1-D01A-4EB6-BC95-85C64428BED6/2018-04-11_18-04-53

### Steps to reproduce the behavior

  1. Install latest version
  2. Check the "Use windows containers" option
  3. Finish the installation

**Comment by jasonbivins** [comment]
@yurieastwood It looks like you might have a duplicate or stuck network

If you look at your network adapters - do you see a NAT, or DockerNAT already there?

![image](https://user-images.githubusercontent.com/28021664/38749480-be899dcc-3f1f-11e8-88a3-9e3234b308d4.png)

**Comment by bertye** [comment]
I have the same issue as @yurieastwood and I do not see the `vEthernet (DockerNAT)` nor the `vEthernet (External for VM)` adapter. `vEthernet (nat)` and `vEthernet (Default Swtich)` are present.

**Comment by yurieastwood** [comment]
@jasonbivins sorry for the late reply but no, there are no duplicate networks. actually there are no networks since apparently docker can't even create it's usual network

**Comment by jasonbivins** [comment]
Try to create a new Virtual switch in external mode - 
https://docs.docker.com/machine/drivers/hyper-v/#2-set-up-a-new-external-network-switch-optional

If that fails - then it might be best to wipe out all network settings. Download the cleanup script from Microsoft Here: https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/live/windows-server-container-tools/CleanupContainerHostNetworking

`PS C:\> .\WindowsContainerNetworking-LoggingAndCleanupAide.ps1 -Cleanup -ForceDeleteAllSwitches`
