### ISSUE TITLE
Docker doesn't start on Windows 10, eventually fails with "Docker hv-sock proxy (vsudd) is not reachable"

### ISSUE THREAD

**Issue by dmjones500** [docker/for-win#1957]
- Windows Version: Windows 10 Enterprise
  - Docker for Windows Version: 18.03.0-ce-win59 (16762)

### Expected behavior

Docker will start when "Docker for Windows" is run from Start Menu.

### Actual behavior

Docker doesn't start; "Docker is starting..." shown as the tooltip in the tray for 10 minutes or so. Eventually an error is shown:

> [NamedPipeServer][Error  ] Unable to execute Start: Docker hv-sock proxy (vsudd) is not reachable    at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 284
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 251
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 112

### Information

Diagnostic ID: E6912385-BFDF-4685-AACD-2280FC6B2844/2018-04-17_10-51-50
Windows 10 Enterprise, build number 14393. 14393.0.amd64fre.rs1_release.160715-1616

### Steps to reproduce the behavior

Couple of notes: my machine is connected to my work active directory. My local user does not have local admin rights, instead I have a separate set of credentials I need to use when elevated rights are needed.

This is a relatively fresh laptop. Prior to installing Docker, I enabled Windows Subsystem for Linux. (Just in case that's relevant).

  1. Installed Docker for Windows CE. I selected to use Linux containers
  2. (Was prompted to enable Hyper-V, which I accepted). Machine rebooted a couple of times.
  3. Docker failed to start with a permissions error (I wasn't in docker-users). I added myself to this group. I also added myself to the Hyper-V management group.
  4. Tried to start Docker again.

**Comment by dmjones500** [comment]
Note: when I switched to Windows Containers, Docker started successfully.

**Comment by rn** [comment]
There is a Linux kernel crash in your logs (see below), actually there are several different ones, they all look related to the context switch code.

It looks like you have a skylake processor, which Linux detects and then tries to use the appropriate context switch code for that processor. Unfortunately, the version of Hyper-V does not correctly handle this processor. We had several issues like this in the past.

I'm afraid the only solution is a Windows update. I don't know if this was fixed with a regular patch to build 14393 or if this requires an update to a newer Windows version.

I'm closing this issue as Won't fix as this is not something we (Docker) can fix, but please report back if an update did fix it.

Thanks

```
[09:38:45.433][Moby           ][Info   ] [   13.979617] ------------[ cut here ]------------
[09:38:45.480][Moby           ][Info   ] [   13.989608] WARNING: CPU: 0 PID: 0 at ./arch/x86/include/asm/fpu/internal.h:368 __switch_to+0x347/0x49d
[09:38:45.549][Moby           ][Info   ] [   13.989608] Modules linked in:
[09:38:45.618][Moby           ][Info   ] [   13.989608] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G        W       4.9.87-linuxkit-aufs #1
[09:38:45.718][Moby           ][Info   ] [   13.989608] Hardware name: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS Hyper-V UEFI Release v1.0 11/26/2012
[09:38:45.819][Moby           ][Info   ] [   13.989608]  0000000000000000 ffffffff8e438de6 0000000000000000 0000000000000000
[09:38:45.850][Moby           ][Info   ] [   13.989608]  ffffffff8e0dead0 ffff8cedf9222b00 ffffffff8ee13500 0000000000000001
[09:38:46.066][Moby           ][Info   ] [   13.989608]  0000000000000000 0000000000000000 01d25a1bd3913515 ffffffff8e0200ba
[09:38:46.097][Moby           ][Info   ] [   13.989608] Call Trace:
[09:38:46.682][Moby           ][Info   ] [   13.989608] ---[ end trace 1c47b109ffec3a89 ]---
[09:38:47.874][Moby           ][Info   ] [   15.307127] BUG: unable to handle kernel NULL pointer dereference at 0000000000000038
[09:38:48.003][Moby           ][Info   ] [   15.317096] IP: [<ffffffff8e109539>] enqueue_entity+0x32/0x42b
[09:38:48.204][Moby           ][Info   ] [   15.317096] PGD 0 [   15.317096]
[09:38:48.289][Moby           ][Info   ] [   15.317096] Oops: 0000 [#1] SMP
[09:38:48.580][Moby           ][Info   ] [   15.317096] Modules linked in:
[09:38:48.897][Moby           ][Info   ] [   15.317096] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G        W       4.9.87-linuxkit-aufs #1
[09:38:50.256][Moby           ][Info   ] [   15.317096] Hardware name: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS Hyper-V UEFI Release v1.0 11/26/2012
[09:38:50.472][Moby           ][Info   ] [   15.317096] task: ffffffff8ee13500 task.stack: ffffffff8ee00000
[09:38:50.746][Moby           ][Info   ] [   15.317096] RIP: 0010:[<ffffffff8e109539>]  [<ffffffff8e109539>] enqueue_entity+0x32/0x42b
[09:38:51.808][Moby           ][Info   ] [   15.317096] RSP: 0018:ffff8cedfae03c80  EFLAGS: 00010046
[09:38:52.252][Moby           ][Info   ] [   15.317096] RAX: 0000000000000000 RBX: ffff8cedf9223500 RCX: 0000000000002a01
[09:38:52.281][Moby           ][Info   ] [   15.317096] RDX: 0000000000000001 RSI: ffff8cedf9223500 RDI: 0000000000000000
[09:38:53.140][Moby           ][Info   ] [   15.317096] RBP: ffff8cedfae03ce0 R08: ffff8cedfa72a3c0 R09: 0000000000000100
[09:38:53.406][Moby           ][Info   ] [   15.317096] R10: ffff8cedfae03e60 R11: ffff8cedfae03e98 R12: 0000000000000000
[09:38:53.594][Moby           ][Info   ] [   15.317096] R13: ffff8cedfae03d08 R14: 0000000000000000 R15: ffff8cedf9223480
[09:38:53.750][Moby           ][Info   ] [   15.317096] FS:  0000000000000000(0000) GS:ffff8cedfae00000(0000) knlGS:0000000000000000
[09:38:53.797][Moby           ][Info   ] [   15.317096] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[09:38:53.829][Moby           ][Info   ] [   15.317096] CR2: 0000000000000038 CR3: 0000000075ea2000 CR4: 0000000000340630
[09:38:53.860][Moby           ][Info   ] [   15.317096] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[09:38:53.907][Moby           ][Info   ] [   15.317096] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[09:38:53.923][Moby           ][Info   ] [   15.317096] Stack:
[09:38:53.954][Moby           ][Info   ] [   15.317096]  0000000000000001 0000000000019080 ffffffff8e10a248 ffffffff8e1078ea
[09:38:54.016][Moby           ][Info   ] [   15.317096]  ffff8cedf9223480 0000000000000000 ffff8ced00000010 ffff8cedf9223500
[09:38:54.063][Moby           ][Info   ] [   15.317096]  0000000000000000 ffff8cedfae03d08 0000000000000000 ffff8cedf9223480
[09:38:54.079][Moby           ][Info   ] [   15.317096] Call Trace:
[09:38:54.204][Moby           ][Info   ] [   15.317096]  <IRQ> [   15.317096]  [<ffffffff8e10a248>] ? find_busiest_group+0x10d/0x601
[09:38:54.267][Moby           ][Info   ] [   15.317096]  [<ffffffff8e1078ea>] ? select_task_rq_fair+0x1a5/0x6c4
[09:38:54.314][Moby           ][Info   ] [   15.317096]  [<ffffffff8e109987>] ? enqueue_task_fair+0x55/0xcf
[09:38:54.408][Moby           ][Info   ] [   15.317096]  [<ffffffff8e109987>] ? enqueue_task_fair+0x55/0xcf
[09:38:54.439][Moby           ][Info   ] [   15.317096]  [<ffffffff8e1003f5>] ? ttwu_do_activate+0x3e/0x6b
[09:38:54.470][Moby           ][Info   ] [   15.317096]  [<ffffffff8e10114b>] ? try_to_wake_up+0x1cf/0x210
[09:38:54.549][Moby           ][Info   ] [   15.317096]  [<ffffffff8e10fedb>] ? autoremove_wake_function+0x11/0x35
[09:38:54.580][Moby           ][Info   ] [   15.317096]  [<ffffffff8e10fb25>] ? __wake_up_common+0x4c/0x78
[09:38:54.611][Moby           ][Info   ] [   15.317096]  [<ffffffff8e10fb89>] ? __wake_up+0x38/0x49
[09:38:54.642][Moby           ][Info   ] [   15.317096]  [<ffffffff8e10fc36>] ? __wake_up_bit+0x50/0x6a
[09:38:54.752][Moby           ][Info   ] [   15.317096]  [<ffffffff8e22308c>] ? end_buffer_read_sync+0xe/0x17
[09:38:54.924][Moby           ][Info   ] [   15.317096]  [<ffffffff8e22340e>] ? end_bio_bh_io_sync+0x28/0x31
[09:38:54.987][Moby           ][Info   ] [   15.317096]  [<ffffffff8e4182d6>] ? blk_update_request+0x183/0x239
[09:38:55.002][Moby           ][Info   ] [   15.317096]  [<ffffffff8e5475f5>] ? scsi_end_request+0x2c/0x174
[09:38:55.065][Moby           ][Info   ] [   15.317096]  [<ffffffff8e54897d>] ? scsi_io_completion+0x1ad/0x48c
[09:38:55.143][Moby           ][Info   ] [   15.317096]  [<ffffffff8e41e037>] ? blk_done_softirq+0x84/0xa4
[09:38:55.222][Moby           ][Info   ] [   15.317096]  [<ffffffff8e7fbd80>] ? __do_softirq+0xf0/0x248
[09:38:55.253][Moby           ][Info   ] [   15.317096]  [<ffffffff8e0e35c6>] ? irq_exit+0x52/0x91
[09:38:55.284][Moby           ][Info   ] [   15.317096]  [<ffffffff8e034acd>] ? hyperv_vector_handler+0x3a/0x44
[09:38:55.347][Moby           ][Info   ] [   15.317096]  [<ffffffff8e7f9f16>] ? hyperv_callback_vector+0x96/0xa0
[09:38:55.409][Moby           ][Info   ] [   15.317096]  <EOI> [   15.317096]  [<ffffffff8e7f8954>] ? native_safe_halt+0x2/0x3
[09:38:55.456][Moby           ][Info   ] [   15.317096]  [<ffffffff8e7f8803>] ? default_idle+0x1b/0x2c
[09:38:55.628][Moby           ][Info   ] [   15.317096]  [<ffffffff8e1106b8>] ? cpu_startup_entry+0x12e/0x1e4
[09:38:55.660][Moby           ][Info   ] [   15.317096]  [<ffffffff8ef79f0b>] ? start_kernel+0x42f/0x44f
[09:38:55.691][Moby           ][Info   ] [   15.317096]  [<ffffffff8ef79120>] ? early_idt_handler_array+0x120/0x120
[09:38:55.738][Moby           ][Info   ] [   15.317096]  [<ffffffff8ef793fd>] ? x86_64_start_kernel+0x141/0x165
[09:38:55.957][Moby           ][Info   ] [   15.317096] Code: 89 d0 83 e0 21 4c 8d 6c 24 10 48 83 e4 f0 41 ff 75 f8 55 48 89 e5 41 57 41 56 41 55 41 54 49 89 fc 53 48 89 f3 48 83 ec 38 ff c8 <48> 8b 47 38 41 0f 95 c5 89 55 c4 48 39 f0 48 89 45 c8 75 0d 45
[09:38:56.051][Moby           ][Info   ] [   15.317096] RIP  [<ffffffff8e109539>] enqueue_entity+0x32/0x42b
[09:38:56.114][Moby           ][Info   ] [   15.317096]  RSP <ffff8cedfae03c80>
[09:38:56.129][Moby           ][Info   ] [   15.317096] CR2: 0000000000000038
[09:38:56.176][Moby           ][Info   ] [   15.317096] ---[ end trace 1c47b109ffec3a8a ]---
```
