### ISSUE TITLE
unable to start Docker using Windows Containers

### ISSUE THREAD

**Issue by jlouros** [docker/for-win#1974]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [x] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10.0 Pro 1709 build 1699 402
  - Docker for Windows Version: Version 18.03.0-ce-win59 (16762)

### Expected behavior

Docker successfully starts for Windows Containers

### Actual behavior

Docker fails to start

### Information

Diagnostic id: 96929818-95DF-41E1-8638-E4BDB4F35AEE/2018-04-25_23-32-23

```
Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 218
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 93
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144
```

### Steps to reproduce the behavior

  1. click Switch to Windows Containers

### Additional comments

odd network adapters 
![image](https://user-images.githubusercontent.com/587250/39276655-fa3ab628-48e1-11e8-8900-47155b8152a3.png)

**Comment by jlouros** [comment]
After a clean install of Windows 10, this issue didn't show up.
"Killing a fly with a flamethrower".
Hopefully the uploaded logs can provide some useful information.
