### ISSUE TITLE
Docker failed to initialize, No Diagnose & Feedback in menu, About Docker hangs

### ISSUE THREAD

**Issue by balbertho** [docker/for-win#1985]
Please, check https://docs.docker.com/docker-for-win/troubleshoot/.
Issues without logs and details cannot be debugged, and will be closed.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version: 17134.1.amd64fre.rs4_release.180410-1804
  - Docker for Windows Version: 18.05.0-ce-rc1-win63 (17439)

### Expected behavior
Initialize

### Actual behavior
Error Message shown and the screen has never updated.

![docker](https://user-images.githubusercontent.com/12370920/39400097-5465dba6-4b5c-11e8-8673-37c6976a56e1.PNG)

Object reference not set to an instance of an object.
   at Docker.Core.ExperimentalFeatures.Fixup(String name, String trackingId, ExperimentalFeature feature) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\ExperimentalFeatures.cs:line 270
   at Docker.Core.ExperimentalFeatures.Get(String name) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\ExperimentalFeatures.cs:line 249
   at Docker.Actions.Start() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 47
   at Docker.App.Initialize() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\App.cs:line 96
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Program.cs:line 166

### Information

No "Diagnose & Feedback" in the menu.

![docker menu](https://user-images.githubusercontent.com/12370920/39400124-0e1ef41a-4b5d-11e8-8430-72b65aa7942e.png)

Clicking "About Docker" hangs and auto close Docker after some seconds.

![docker about](https://user-images.githubusercontent.com/12370920/39400185-11c62c36-4b5e-11e8-82ad-15cd53a39676.PNG)

log.txt:
Version: 18.05.0-ce-rc1-win63 (17439)
Channel: edge
Sha1: 3b5a9a44cd9af5d358a1c63baea9c5c61b16e4da
Started on: 2018/04/29 03:31:11.385
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1803
Build: 17134
BuildLabName: 17134.1.amd64fre.rs4_release.180410-1804
File: C:\Users\BAlbert\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[03:31:11.498][GUI            ][Info   ] Starting...
[03:31:12.140][Tracking       ][Info   ] Crash report and usage statistics are enabled
[03:31:12.143][SegmentApi     ][Info   ] Usage statistic: appLaunched
[03:31:12.196][SegmentApi     ][Info   ] Usage statistic: heartbeat
[03:31:12.198][SegmentApi     ][Info   ] Usage statistic: Identify
[03:31:13.770][GUI            ][Error  ] Object reference not set to an instance of an object.
[03:31:13.799][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[03:31:13.808][CrashReport    ][Warning] Unable to collect features settings: Could not find file 'C:\Users\BAlbert\AppData\Roaming\Docker\features-overrides.json'.
[03:31:13.815][NamedPipeClient][Info   ] Sending Version()...
[03:31:13.818][NamedPipeClient][Info   ] Sending Version()...
[03:31:13.818][NamedPipeClient][Info   ] Sending Version()...
[03:31:13.818][NamedPipeClient][Info   ] Sending Version()...
[03:31:13.827][NamedPipeClient][Info   ] Received response for Version
[03:31:13.827][NamedPipeClient][Info   ] Received response for Version
[03:31:13.827][NamedPipeClient][Info   ] Received response for Version
[03:31:13.827][NamedPipeClient][Info   ] Received response for Version
[03:31:13.828][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[03:31:13.828][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\BAlbert\AppData\Local\Temp\3zowiuwv.cmj\pcap.tar)...
[03:31:13.828][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\BAlbert\AppData\Local\Temp\3zowiuwv.cmj\mobyLogs.tar)...
[03:31:13.828][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\BAlbert\AppData\Local\Temp\3zowiuwv.cmj\win_containers)...
[03:31:13.830][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[03:31:13.825][NamedPipeServer][Info   ] Version done in 00:00:00.0010025.
[03:31:13.825][NamedPipeServer][Info   ] Version()
[03:31:13.825][NamedPipeServer][Info   ] Version done in 00:00:00.
[03:31:13.825][NamedPipeServer][Info   ] Version()
[03:31:13.825][NamedPipeServer][Info   ] Version done in 00:00:00.
[03:31:13.825][NamedPipeServer][Info   ] Version()
[03:31:13.825][NamedPipeServer][Info   ] Version done in 00:00:00.
[03:31:13.829][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\BAlbert\AppData\Local\Temp\3zowiuwv.cmj\pcap.tar)
[03:31:13.829][NamedPipeServer][Info   ] GetDebugInfo()
[03:31:13.829][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\BAlbert\AppData\Local\Temp\3zowiuwv.cmj\win_containers)
[03:31:13.850][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[03:31:13.829][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\BAlbert\AppData\Local\Temp\3zowiuwv.cmj\mobyLogs.tar)
[03:31:13.830][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[03:31:13.830][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0010012.
[03:31:13.830][PowerShell     ][Info   ] Run script '(Hyper-V\Get-VM MobyLinuxVM).Id.Guid'...
[03:31:13.850][HyperV         ][Warning] Unable to download logs: Unrecognized Guid format.
[03:31:13.850][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.0210004.
[03:31:16.836][Systray        ][Error  ] Failed opening Docker menu: Object reference not set to an instance of an object.
[03:31:18.972][Systray        ][Error  ] Failed opening Docker menu: Object reference not set to an instance of an object.
[03:31:20.251][SegmentApi     ][Info   ] Usage statistic: actionMenuAbout

### Steps to reproduce the behavior

  1. Install
  2. Start

**Comment by stephen-turner** [comment]
Thanks for the report, @balbertho. I have found one way to reproduce this, if the file `C:\Users\<your name>\AppData\Roaming\Docker\already-enabled-features.json` is present but empty. Could you try deleting that file and starting again?

**Comment by stephen-turner** [comment]
This issue got automatically closed because I fixed it in our internal repo. But please reopen if the above diagnosis doesn't explain the problem.

**Comment by balbertho** [comment]
@stephen-turner Yes, it works, thank you. By the way, the json file is not empty but with the hex code:
`00 00 00 00 00 00 00 00 00 00 00 00 00 00 00` where appears to be empty. Thank you anyway.
