### ISSUE TITLE
Docker does not start - Windows 10

### ISSUE THREAD

**Issue by amitla** [docker/for-win#2008]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have submitted Diagnostics
  - [x ] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 Ent. Version 1709 Build 16299.371
  - Docker for Windows Version: 18.03.1-ce-win65 (17513) (Stable Channel)

### Expected behavior
Docker should start upon windows start
### Actual behavior
Docker deamon is not responsing
``` powershell
PS C:\Program Files\Docker\Docker\resources> docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```
### Information
####Diagnostics ID
``` 
503E3F4C-9F00-4FB6-8016-BEF3D5B0BCAD/2018-05-07_09-51-05
```

### Steps to reproduce the behavior

  1. restart windows

**Comment by cmosguy** [comment]
I am getting a similar error and I do not understand how or why this is happening.  I noticed in my log files I have:

````
[07:08:03.607][Linux          ][Info   ] Vsudd is reachable!
[07:08:05.618][ApiProxy       ][Info   ] time="2018-05-14T07:08:05-07:00" msg="docker proxy: ready"
[07:08:05.724][ApiProxy       ][Info   ] time="2018-05-14T07:08:05-07:00" msg="proxy >> GET /_ping\n"
[07:08:05.724][ApiProxy       ][Info   ] time="2018-05-14T07:08:05-07:00" msg="Dial Hyper-V socket 8d84fbdf-17e3-43cc-b440-c41f23c1d31d:23a432c2-537a-4291-bcb5-d62504644739"
[07:08:05.734][ApiProxy       ][Info   ] time="2018-05-14T07:08:05-07:00" msg="Successfully dialed Hyper-V socket 8d84fbdf-17e3-43cc-b440-c41f23c1d31d:23a432c2-537a-4291-bcb5-d62504644739"
[07:08:05.734][ApiProxy       ][Info   ] Exception 0xc0000005 0x0 0x0 0x571732e1
[07:08:05.734][ApiProxy       ][Info   ] PC=0x571732e1
[07:08:05.734][ApiProxy       ][Info   ] syscall.Syscall9(0x7ff8fc359900, 0x7, 0x854, 0xc0421b1458, 0x1, 0xc0421b144c, 0xc0421b1448, 0xc042132ba0, 0x0, 0x0, ...)
[07:08:05.734][ApiProxy       ][Info   ] 	C:/go19/src/runtime/syscall_windows.go:185 +0x69
[07:08:05.734][ApiProxy       ][Info   ] syscall.WSARecv(0x854, 0xc0421b1458, 0x1, 0xc0421b144c, 0xc0421b1448, 0xc042132ba0, 0x0, 0xc04203a000, 0x2fd13f8)
[07:08:05.734][ApiProxy       ][Info   ] 	C:/go19/src/syscall/zsyscall_windows.go:1545 +0x115
[07:08:05.734][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.(*HVsockConn).read(0xc0422d00f0, 0xc04245e240, 0x4, 0x4, 0x4, 0x4, 0xc0421b1500)
[07:08:05.734][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_windows.go:158 +0xf9
[07:08:05.734][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.(*HVsockConn).Read(0xc0422d00f0, 0xc04223b000, 0x1000, 0x1000, 0xc0421b15a0, 0x448c59, 0x4592a0)
[07:08:05.734][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock.go:305 +0xbd
[07:08:05.734][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*withLogging).Read(0xc042448320, 0xc04223b000, 0x1000, 0x1000, 0xc042358000, 0xc0421b1688, 0xc0421b1688)
[07:08:05.734][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:257 +0x77
[07:08:05.734][ApiProxy       ][Info   ] bufio.(*Reader).fill(0xc04208eb40)
[07:08:05.734][ApiProxy       ][Info   ] 	C:/go19/src/bufio/bufio.go:97 +0x121
[07:08:05.734][ApiProxy       ][Info   ] bufio.(*Reader).ReadSlice(0xc04208eb40, 0xa, 0xc0421b1758, 0x42ba0f, 0x1dae700, 0xc04206e520, 0x1d3c100)
[07:08:05.734][ApiProxy       ][Info   ] 	C:/go19/src/bufio/bufio.go:338 +0x33
[07:08:05.734][ApiProxy       ][Info   ] bufio.(*Reader).ReadLine(0xc04208eb40, 0x90, 0x90, 0x1400fc0, 0xc042358001, 0x140000000000, 0x90)
[07:08:05.734][ApiProxy       ][Info   ] 	C:/go19/src/bufio/bufio.go:367 +0x3b
[07:08:05.734][ApiProxy       ][Info   ] net/textproto.(*Reader).readLineSlice(0xc0421b1898, 0x1150a1e, 0xc0421b17f0, 0x41164f, 0x90, 0x1400fc0)
[07:08:05.734][ApiProxy       ][Info   ] 	C:/go19/src/net/textproto/reader.go:55 +0x77
[07:08:05.734][ApiProxy       ][Info   ] net/textproto.(*Reader).ReadLine(0xc0421b1898, 0xc0423001b0, 0x13b30a0, 0x1db06a0, 0x100570106ad0270)
[07:08:05.734][ApiProxy       ][Info   ] 	C:/go19/src/net/textproto/reader.go:36 +0x32
[07:08:05.735][ApiProxy       ][Info   ] net/http.ReadResponse(0xc04208eb40, 0xc042524600, 0x1000, 0xc04223b000, 0x1000)
[07:08:05.735][ApiProxy       ][Info   ] 	C:/go19/src/net/http/response.go:149 +0xd1
[07:08:05.735][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*passthru).doHandleHTTP(0xc0423b23f0, 0x6ad0230, 0xc0422d00f0, 0x1d2e8a0, 0xc0420b4000, 0xc042524600, 0x41164f, 0x80)
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:101 +0x186
[07:08:05.735][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*passthru).HandleHTTP(0xc0423b23f0, 0x1d2e8a0, 0xc0420b4000, 0xc042524600, 0x0, 0x0)
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:87 +0x1fa
[07:08:05.735][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.withError.func1(0x1d2e8a0, 0xc0420b4000, 0xc042524600)
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/common/backend/proxy/routes.go:19 +0x6c
[07:08:05.735][ApiProxy       ][Info   ] net/http.HandlerFunc.ServeHTTP(0xc0423b2420, 0x1d2e8a0, 0xc0420b4000, 0xc042524600)
[07:08:05.735][ApiProxy       ][Info   ] 	C:/go19/src/net/http/server.go:1918 +0x4b
[07:08:05.735][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc042291ab0, 0x1d2e8a0, 0xc0420b4000, 0xc042524600)
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/gorilla/mux/mux.go:159 +0xf4
[07:08:05.735][ApiProxy       ][Info   ] github.com/docker/pinata/win/backend/apiproxy.(*delegatingHandler).ServeHTTP(0xc0423571a0, 0x1d2e8a0, 0xc0420b4000, 0xc042524000)
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/win/backend/apiproxy/apiproxy.go:17 +0x67
[07:08:05.735][ApiProxy       ][Info   ] net/http.serverHandler.ServeHTTP(0xc0424e2340, 0x1d2e8a0, 0xc0420b4000, 0xc042524000)
[07:08:05.735][ApiProxy       ][Info   ] 	C:/go19/src/net/http/server.go:2619 +0xbb
[07:08:05.735][ApiProxy       ][Info   ] net/http.(*conn).serve(0xc042305400, 0x1d2f7a0, 0xc0423fa000)
[07:08:05.735][ApiProxy       ][Info   ] 	C:/go19/src/net/http/server.go:1801 +0x724
[07:08:05.735][ApiProxy       ][Info   ] created by net/http.(*Server).Serve
[07:08:05.735][ApiProxy       ][Info   ] 	C:/go19/src/net/http/server.go:2720 +0x28f
[07:08:05.735][ApiProxy       ][Info   ] goroutine 1 [chan receive]:
[07:08:05.735][ApiProxy       ][Info   ] main.main()
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/win/backend/cmd/com.docker.proxy/main.go:70 +0x515
[07:08:05.735][ApiProxy       ][Info   ] goroutine 18 [syscall]:
[07:08:05.735][ApiProxy       ][Info   ] os/signal.signal_recv(0x0)
[07:08:05.735][ApiProxy       ][Info   ] 	C:/go19/src/runtime/sigqueue.go:131 +0xad
[07:08:05.735][ApiProxy       ][Info   ] os/signal.loop()
[07:08:05.735][ApiProxy       ][Info   ] 	C:/go19/src/os/signal/signal_unix.go:22 +0x29
[07:08:05.735][ApiProxy       ][Info   ] created by os/signal.init.0
[07:08:05.735][ApiProxy       ][Info   ] 	C:/go19/src/os/signal/signal_unix.go:28 +0x48
[07:08:05.735][ApiProxy       ][Info   ] goroutine 20 [chan receive]:
[07:08:05.735][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1d900e0)
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/golang/glog/glog.go:882 +0xa6
[07:08:05.735][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/golang/glog.init.0
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/golang/glog/glog.go:410 +0x20a
[07:08:05.735][ApiProxy       ][Info   ] goroutine 21 [select]:
[07:08:05.735][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe(0xc042291a40, 0x1, 0xc042457f18, 0x0)
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:270 +0x169
[07:08:05.735][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).listenerRoutine(0xc042291a40)
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:300 +0x139
[07:08:05.735][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.ListenPipe
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:374 +0x2b8
[07:08:05.735][ApiProxy       ][Info   ] goroutine 5 [chan receive]:
[07:08:05.735][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).Accept(0xc042291a40, 0x14c2960, 0xc042305400, 0x1d2f860, 0xc0424f6090)
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:397 +0x199
[07:08:05.735][ApiProxy       ][Info   ] net/http.(*Server).Serve(0xc0424e2340, 0x1d238a0, 0xc042291a40, 0x0, 0x0)
[07:08:05.735][ApiProxy       ][Info   ] 	C:/go19/src/net/http/server.go:2695 +0x1b9
[07:08:05.735][ApiProxy       ][Info   ] github.com/docker/pinata/win/backend/apiproxy.(*apiProxy).start.func1(0xc0423b2e40)
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/win/backend/apiproxy/apiproxy.go:62 +0x4c
[07:08:05.735][ApiProxy       ][Info   ] created by github.com/docker/pinata/win/backend/apiproxy.(*apiProxy).start
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/win/backend/apiproxy/apiproxy.go:61 +0xa1
[07:08:05.735][ApiProxy       ][Info   ] goroutine 6 [chan receive]:
[07:08:05.735][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).Accept(0xc0423d1810, 0x1a, 0xc042463f78, 0x1d238a0, 0xc0423d1810)
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:397 +0x199
[07:08:05.735][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/gui/server.(*guiAPIServer).Start(0xc0421f6460, 0x16, 0x0)
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/common/backend/gui/server/server_windows.go:44 +0xe7
[07:08:05.735][ApiProxy       ][Info   ] created by main.main
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/win/backend/cmd/com.docker.proxy/main.go:63 +0x744
[07:08:05.735][ApiProxy       ][Info   ] goroutine 22 [syscall, locked to thread]:
[07:08:05.735][ApiProxy       ][Info   ] syscall.Syscall6(0x7ff8fe7b5540, 0x5, 0x838, 0xc0421edf9c, 0xc0421edfa0, 0xc0421edfa8, 0xffffffff, 0x0, 0xc0421edf50, 0x4037e3, ...)
[07:08:05.735][ApiProxy       ][Info   ] 	C:/go19/src/runtime/syscall_windows.go:174 +0x69
[07:08:05.735][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x838, 0xc0421edf9c, 0xc0421edfa0, 0xc0421edfa8, 0xffffffff, 0x0, 0x0)
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:100 +0xbb
[07:08:05.735][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x838)
[07:08:05.735][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:159 +0xc0
[07:08:05.736][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.initIo
[07:08:05.736][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:72 +0x87
[07:08:05.736][ApiProxy       ][Info   ] goroutine 7 [select]:
[07:08:05.736][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe(0xc0423d1810, 0x1, 0xc0422a1f18, 0x0)
[07:08:05.736][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:270 +0x169
[07:08:05.736][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).listenerRoutine(0xc0423d1810)
[07:08:05.736][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:300 +0x139
[07:08:05.736][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.ListenPipe
[07:08:05.736][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:374 +0x2b8
[07:08:05.736][ApiProxy       ][Info   ] goroutine 8 [select]:
[07:08:05.740][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc04223e000, 0xc0423b2ea0, 0x0, 0x0, 0x1d18760, 0x1d0f450, 0x0, 0x0, 0x0)
[07:08:05.740][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:186 +0x193
[07:08:05.740][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.connectPipe(0xc04223e000, 0x0, 0x0)
[07:08:05.740][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:386 +0xef
[07:08:05.740][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe.func1(0xc042010d20, 0xc04223e000)
[07:08:05.740][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:267 +0x32
[07:08:05.740][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe
[07:08:05.740][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:266 +0xa9
[07:08:05.740][ApiProxy       ][Info   ] goroutine 10 [select]:
[07:08:05.740][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc04223e0b0, 0xc0423b2f00, 0x0, 0x0, 0x1d18760, 0x1d0f450, 0x0, 0x0, 0x0)
[07:08:05.740][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:186 +0x193
[07:08:05.740][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.connectPipe(0xc04223e0b0, 0x0, 0x0)
[07:08:05.740][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:386 +0xef
[07:08:05.740][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe.func1(0xc042010f00, 0xc04223e0b0)
[07:08:05.740][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:267 +0x32
[07:08:05.740][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe
[07:08:05.740][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:266 +0xa9
[07:08:05.740][ApiProxy       ][Info   ] goroutine 49 [select]:
[07:08:05.740][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc0420e82c0, 0xc0423b2f30, 0xc0420e82f8, 0x0, 0x1d18760, 0x1d0f600, 0x1d18760, 0x1d0f600, 0xea1904f900000000)
[07:08:05.740][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:186 +0x193
[07:08:05.740][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32File).Read(0xc0420e82c0, 0xc0421321f1, 0x1, 0x1, 0x0, 0x0, 0x0)
[07:08:05.740][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:224 +0x151
[07:08:05.740][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32MessageBytePipe).Read(0xc04227cec0, 0xc0421321f1, 0x1, 0x1, 0xb4c5253600000000, 0xc04229eea0, 0x0)
[07:08:05.740][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:116 +0x63
[07:08:05.740][ApiProxy       ][Info   ] net/http.(*connReader).backgroundRead(0xc0421321e0)
[07:08:05.740][ApiProxy       ][Info   ] 	C:/go19/src/net/http/server.go:660 +0x69
[07:08:05.740][ApiProxy       ][Info   ] created by net/http.(*connReader).startBackgroundRead
[07:08:05.740][ApiProxy       ][Info   ] 	C:/go19/src/net/http/server.go:656 +0xdf
[07:08:05.740][ApiProxy       ][Info   ] goroutine 50 [syscall, locked to thread]:
[07:08:05.740][ApiProxy       ][Info   ] syscall.Syscall6(0x7ff8fe7b5540, 0x5, 0x86c, 0xc0421eff9c, 0xc0421effa0, 0xc0421effa8, 0xffffffff, 0x0, 0x1, 0x1, ...)
[07:08:05.740][ApiProxy       ][Info   ] 	C:/go19/src/runtime/syscall_windows.go:174 +0x69
[07:08:05.740][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.getQueuedCompletionStatus(0x86c, 0xc0421eff9c, 0xc0421effa0, 0xc0421effa8, 0xc0ffffffff, 0xc0421effc0, 0x6119ee)
[07:08:05.740][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/zsyscall_windows.go:125 +0xbb
[07:08:05.740][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.ioCompletionProcessor(0x86c)
[07:08:05.741][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_windows.go:293 +0xcc
[07:08:05.741][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.initIo
[07:08:05.741][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_windows.go:259 +0x87
[07:08:05.741][ApiProxy       ][Info   ] goroutine 51 [chan send]:
[07:08:05.741][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*passthru).doHandleHTTP.func1(0xc042494960, 0xc042524600, 0x1d2faa0, 0xc042448320)
[07:08:05.741][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:96 +0x9a
[07:08:05.741][ApiProxy       ][Info   ] created by github.com/docker/pinata/common/backend/proxy.(*passthru).doHandleHTTP
[07:08:05.741][ApiProxy       ][Info   ] 	c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:95 +0x101
[07:08:05.741][ApiProxy       ][Info   ] rax     0x3187900
[07:08:05.741][ApiProxy       ][Info   ] rbx     0x0
[07:08:05.741][ApiProxy       ][Info   ] rcx     0x7ff8fed257a4
[07:08:05.741][ApiProxy       ][Info   ] rdi     0x854
[07:08:05.741][ApiProxy       ][Info   ] rsi     0x57368d20
[07:08:05.741][ApiProxy       ][Info   ] rbp     0x0
[07:08:05.741][ApiProxy       ][Info   ] rsp     0x5d4f9d0
[07:08:05.741][ApiProxy       ][Info   ] r8      0x5d4f958
[07:08:05.741][ApiProxy       ][Info   ] r9      0x0
[07:08:05.741][ApiProxy       ][Info   ] r10     0x0
[07:08:05.741][ApiProxy       ][Info   ] r11     0x246
[07:08:05.741][ApiProxy       ][Info   ] r12     0xc0421b144c
[07:08:05.741][ApiProxy       ][Info   ] r13     0x3110840
[07:08:05.741][ApiProxy       ][Info   ] r14     0xc042132ba0
[07:08:05.741][ApiProxy       ][Info   ] r15     0xc0421b1448
[07:08:05.741][ApiProxy       ][Info   ] rip     0x571732e1
[07:08:05.741][ApiProxy       ][Info   ] rflags  0x10206
[07:08:05.741][ApiProxy       ][Info   ] cs      0x33
[07:08:05.741][ApiProxy       ][Info   ] fs      0x53
[07:08:05.741][ApiProxy       ][Info   ] gs      0x2b
[07:08:05.788][ApiProxy       ][Error  ] Process died
[07:08:05.824][DockerDaemonChecker][Error  ] Docker daemon is not running
[07:08:07.183][DockerDaemonChecker][Error  ] Docker daemon is not running
[07:08:08.538][DockerDaemonChecker][Error  ] Docker daemon is not running
[07:08:09.932][DockerDaemonChecker][Error  ] Docker daemon is not running
[07:08:11.352][DockerDaemonChecker][Error  ] Docker daemon is not running
[07:08:11.750][ApiProxy       ][Info   ] time="2018-05-14T07:08:11-07:00" msg="docker proxy: ready"
[07:08:12.759][ApiProxy       ][Info   ] time=

**Comment by rn** [comment]
@cmosguy do you ahppen to run LavaSoft companion or other AV software? The stack trace looks pretty similar to  https://github.com/moby/moby/issues/27423

@amitla there is a variant of https://github.com/docker/for-win/issues/1994 in your logs, unfortunately of the hung task variety. I've added your ID to that ticket.

I'm closing this issue as the original issue has been triaged and @cmosguy your issue is different. If the link I sent you is not related please open a new issue.
