### ISSUE TITLE
fatal: Error starting daemon: failed to load vmcompute.dll

### ISSUE THREAD

**Issue by max-favilli** [docker/for-win#2020]
I have Windows 10 pro 1709 16299.431
Hyper-V is installed and turned on in Windows features
Visual Studio 2017 v15.7.1

Installed latest Docker For Windows.

But Docker doesn't start, the log shows the following error:
```
[12:10:15.653][WindowsDaemon  ][Error  ] fatal: Error starting daemon: failed to load vmcompute.dll, ensure that the Containers feature is installed
[12:10:17.238][NamedPipeServer][Error  ] Unable to execute Start: Time out has expired and the operation has not been completed.    at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(String args, Dictionary`2 env) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 152
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 218
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 93
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144

```

What should I do?

**Comment by rn** [comment]
Do you have a diagnostics ID?

Have you ever had VirtualBox, HAXM (Android emulator), or VMWare installed on the system?  If so, try to uninstall them first

**Comment by rn** [comment]
alternatively, try to un-install Docker for windows. Disable the Hyper-V and Windows container feature, reboot, and re-install Docker for Windows (which should re-enable Hyper-V and Windows Container features, which requires another reboot). We had cases where sometimes the Hyper-V feature and/or Windows container feature is not installed cleanly (for unknown reasons)

**Comment by max-favilli** [comment]
@rn Thanks a lot. Following your suggestion fixed the problem.

**Comment by rn** [comment]
thanks for getting back. The wonders of Windows....some users seem to have these issues with Hyper-V not quite being enabled, and we have no idea why. We use to do this on our systems in CI 50+ times a day without failure...

glad it's working for you now. Sometimes turning it off and on again seems to be the right solution

**Comment by andreasblueher** [comment]
I'm facing the same issue and deactivating and activating the feature did not help for us. It appears with Azure VMs this might be related to the template you're using. But I haven't figured out what the solution is yet. Any help on what the minimum requirements are is appreciated.

**Comment by Oxymoron290** [comment]
same issue on brand new install of windows server 2019
Installed windows container feature
downloaded docker & dockerd
added them to by path
called dockerd --register-service
Then called Start-Service docker with a failed to start error

**Comment by erikest** [comment]
Had the same problem and I _think_ also enabling the windows feature "Windows Hypervisor Platform" was the missing piece.  

This [superuser answer](https://superuser.com/questions/1510172/hyper-v-vs-virtual-machine-platform-vs-windows-hypervisor-platform-settings-in-p) seems to indicate as much
