### ISSUE TITLE
Unable to start docker daemon

### ISSUE THREAD

**Issue by vishalm** [docker/for-win#2023]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have submitted Diagnostics
  - [ ] I have included the Diagnostics ID in this Issue
  - Windows Version:
  - Docker for Windows Version:

### Information
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 218
   at Docker.Backend.ContainerEngine.Windows.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 150
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144

### Steps to reproduce the behavior

Install docker Latest 18.5CE
Unable to start

**Comment by rn** [comment]
Could you supply a diagnostics ID. without we are unable to help

**Comment by jhansen9657** [comment]
i seem to be having the same issue

**Comment by ArunimaSharma19** [comment]
I am facing the same issue.
Windows : 10
Docker Version: 18.03.1-ce-win65 (17513)
Diagnostics Id : B16ECB89-F5C7-42FC-85E4-D2FBAD0DFB1F/2018-05-14_18-22-42

**Comment by jasonbivins** [comment]
@ArunimaSharma19 
Can you try the edge channel?  Your hostname has a `-`  in it and  the edge channel seems to be handling that better on startup right now.

**Comment by ArunimaSharma19** [comment]
@jasonbivins Tried that. That doesn't seem to work too.
The issue in my case, seems to be an update in the version of a software called Digital Guardian. The version it got updated to is 7.4.1.0161.
If we revert back the version of Digital Guardian to 7.4.0.0031, all the versions of docker seem to run fine.

**Comment by vishalm** [comment]
Yesterday there was a big update push from MS suddenly docker started
working the only thing remaining unable to share.c drive

**Comment by rn** [comment]
I'm closing this as no diagnostics ID was supplied and @vishalm seems to have made some progress

@ArunimaSharma19 there are `go` back traces in your logs like the one below. We had some issue with some AV software in the past causing this sort of crash. Looks like this was also the case for you

```
[17:10:21.274][ApiProxy       ][Info   ] Exception 0xc0000005 0x0 0x0 0x745032e1
[17:10:21.274][ApiProxy       ][Info   ] PC=0x745032e1
[17:10:21.274][ApiProxy       ][Info   ] syscall.Syscall9(0x7ff9a9ca9900, 0x7, 0x868, 0xc04249f458, 0x1, 0xc04249f44c, 0xc04249f448, 0xc042132e70, 0x0, 0x0, ...)
[17:10:21.274][ApiProxy       ][Info   ]        C:/go19/src/runtime/syscall_windows.go:185 +0x69
[17:10:21.274][ApiProxy       ][Info   ] syscall.WSARecv(0x868, 0xc04249f458, 0x1, 0xc04249f44c, 0xc04249f448, 0xc042132e70, 0x0, 0xc04217a000, 0x3160d50)
[17:10:21.274][ApiProxy       ][Info   ]        C:/go19/src/syscall/zsyscall_windows.go:1545 +0x115
[17:10:21.274][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.(*HVsockConn).read(0xc0422d00f0, 0xc0424ac110, 0x4, 0x4, 0x4, 0x4, 0xc04249f500)
[17:10:21.274][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_windows.go:158 +0xf9
[17:10:21.274][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.(*HVsockConn).Read(0xc0422d00f0, 0xc0424f9000, 0x1000, 0x1000, 0xc04249f5a0, 0x448c59, 0x4592a0)
[17:10:21.274][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock.go:305 +0xbd
[17:10:21.274][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*withLogging).Read(0xc04252c2c0, 0xc0424f9000, 0x1000, 0x1000, 0xc0420101a0, 0xc04249f688, 0xc04249f688)
[17:10:21.274][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:257 +0x77
[17:10:21.274][ApiProxy       ][Info   ] bufio.(*Reader).fill(0xc04208eba0)
[17:10:21.274][ApiProxy       ][Info   ]        C:/go19/src/bufio/bufio.go:97 +0x121
[17:10:21.274][ApiProxy       ][Info   ] bufio.(*Reader).ReadSlice(0xc04208eba0, 0xa, 0xc04249f758, 0x42ba0f, 0x1dae700, 0xc04206e520, 0x1d3c100)
[17:10:21.274][ApiProxy       ][Info   ]        C:/go19/src/bufio/bufio.go:338 +0x33
[17:10:21.274][ApiProxy       ][Info   ] bufio.(*Reader).ReadLine(0xc04208eba0, 0x90, 0x90, 0x1400fc0, 0xc042010101, 0x140000000000, 0x90)
[17:10:21.274][ApiProxy       ][Info   ]        C:/go19/src/bufio/bufio.go:367 +0x3b
[17:10:21.274][ApiProxy       ][Info   ] net/textproto.(*Reader).readLineSlice(0xc04249f898, 0x1150a1e, 0xc04249f7f0, 0x41164f, 0x90, 0x1400fc0)
[17:10:21.274][ApiProxy       ][Info   ]        C:/go19/src/net/textproto/reader.go:55 +0x77
[17:10:21.274][ApiProxy       ][Info   ] net/textproto.(*Reader).ReadLine(0xc04249f898, 0xc0422d2480, 0x13b30a0, 0x1db06a0, 0x100570104f51698)
[17:10:21.274][ApiProxy       ][Info   ]        C:/go19/src/net/textproto/reader.go:36 +0x32
[17:10:21.274][ApiProxy       ][Info   ] net/http.ReadResponse(0xc04208eba0, 0xc042512e00, 0x1000, 0xc0424f9000, 0x1000)
[17:10:21.275][ApiProxy       ][Info   ]        C:/go19/src/net/http/response.go:149 +0xd1
[17:10:21.275][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*passthru).doHandleHTTP(0xc0422fed20, 0x4f51658, 0xc0422d00f0, 0x1d2e8a0, 0xc04220e0e0, 0xc042512e00, 0x41164f, 0x80)
[17:10:21.275][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:101 +0x186
[17:10:21.275][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*passthru).HandleHTTP(0xc0422fed20, 0x1d2e8a0, 0xc04220e0e0, 0xc042512e00, 0x0, 0x0)
[17:10:21.275][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:87 +0x1fa
[17:10:21.275][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.withError.func1(0x1d2e8a0, 0xc04220e0e0, 0xc042512e00)
[17:10:21.275][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/routes.go:19 +0x6c
[17:10:21.275][ApiProxy       ][Info   ] net/http.HandlerFunc.ServeHTTP(0xc0422fed50, 0x1d2e8a0, 0xc04220e0e0, 0xc042512e00)
[17:10:21.275][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:1918 +0x4b
[17:10:21.275][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0422919d0, 0x1d2e8a0, 0xc04220e0e0, 0xc042512e00)
[17:10:21.275][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/gorilla/mux/mux.go:159 +0xf4
[17:10:21.275][ApiProxy       ][Info   ] github.com/docker/pinata/win/backend/apiproxy.(*delegatingHandler).ServeHTTP(0xc04231e7a0, 0x1d2e8a0, 0xc04220e0e0, 0xc042512400)
[17:10:21.275][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/win/backend/apiproxy/apiproxy.go:17 +0x67
[17:10:21.275][ApiProxy       ][Info   ] net/http.serverHandler.ServeHTTP(0xc04226a000, 0x1d2e8a0, 0xc04220e0e0, 0xc042512400)
[17:10:21.275][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:2619 +0xbb
[17:10:21.275][ApiProxy       ][Info   ] net/http.(*conn).serve(0xc042046280, 0x1d2f7a0, 0xc042034040)
[17:10:21.275][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:1801 +0x724
[17:10:21.275][ApiProxy       ][Info   ] created by net/http.(*Server).Serve
[17:10:21.275][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:2720 +0x28f
[17:10:21.275][ApiProxy       ][Info   ] goroutine 1 [chan receive]:
[17:10:21.275][ApiProxy       ][Info   ] main.main()
[17:10:21.275][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/win/backend/cmd/com.docker.proxy/main.go:70 +0x515
[17:10:21.275][ApiProxy       ][Info   ] goroutine 18 [syscall]:
[17:10:21.275][ApiProxy       ][Info   ] os/signal.signal_recv(0x0)
[17:10:21.275][ApiProxy       ][Info   ]        C:/go19/src/runtime/sigqueue.go:131 +0xad
[17:10:21.275][ApiProxy       ][Info   ] os/signal.loop()
[17:10:21.275][ApiProxy       ][Info   ]        C:/go19/src/os/signal/signal_unix.go:22 +0x29
[17:10:21.275][ApiProxy       ][Info   ] created by os/signal.init.0
[17:10:21.275][ApiProxy       ][Info   ]        C:/go19/src/os/signal/signal_unix.go:28 +0x48
[17:10:21.275][ApiProxy       ][Info   ] goroutine 6 [chan receive]:
[...]
[17:10:21.285][ApiProxy       ][Info   ] goroutine 35 [chan send]:
[17:10:21.285][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*passthru).doHandleHTTP.func1(0xc04200b200, 0xc042512e00, 0x1d2faa0, 0xc04252c2c0)
[17:10:21.285][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:96 +0x9a
[17:10:21.285][ApiProxy       ][Info   ] created by github.com/docker/pinata/common/backend/proxy.(*passthru).doHandleHTTP
[17:10:21.285][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:95 +0x101
[17:10:21.285][ApiProxy       ][Info   ] rax     0x31e3810
[17:10:21.285][ApiProxy       ][Info   ] rbx     0x0
[17:10:21.285][ApiProxy       ][Info   ] rcx     0x7ff9aad757a4
[17:10:21.285][ApiProxy       ][Info   ] rdi     0x868
[17:10:21.285][ApiProxy       ][Info   ] rsi     0x746f8d20
[17:10:21.285][ApiProxy       ][Info   ] rbp     0x0
[17:10:21.285][ApiProxy       ][Info   ] rsp     0x6c1f9d0
[17:10:21.285][ApiProxy       ][Info   ] r8      0x6c1f958
[17:10:21.285][ApiProxy       ][Info   ] r9      0x0
[17:10:21.285][ApiProxy       ][Info   ] r10     0x0
[17:10:21.285][ApiProxy       ][Info   ] r11     0x246
[17:10:21.285][ApiProxy       ][Info   ] r12     0xc04249f44c
[17:10:21.285][ApiProxy       ][Info   ] r13     0x4f90840
[17:10:21.285][ApiProxy       ][Info   ] r14     0xc042132e70
[17:10:21.285][ApiProxy       ][Info   ] r15     0xc04249f448
[17:10:21.285][ApiProxy       ][Info   ] rip     0x745032e1
[17:10:21.285][ApiProxy       ][Info   ] rflags  0x10202
[17:10:21.285][ApiProxy       ][Info   ] cs      0x33
[17:10:21.285][ApiProxy       ][Info   ] fs      0x53
[17:10:21.285][ApiProxy       ][Info   ] gs      0x2b

```

**Comment by urscion** [comment]
FYI, upgrading to Digital Guardian 7.5 worked for me for LCOW.
