### ISSUE TITLE
Docker for Windows Failed to start - error during connect -- //./pipe/docker_engine: The system cannot find the file specified.

### ISSUE THREAD

**Issue by cmosguy** [docker/for-win#2028]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have submitted Diagnostics
  - [X ] I have included the Diagnostics ID in this Issue
  - Windows Version: Windows 10 Enterprise 1703 
  - OS Build: 15063.1029
  - Docker for Windows Version: 18.03.1-ce-win65 (17513)
 
### Expected behavior
Docker for windows should just load and start.

### Actual behavior
I get the infamous error:

```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 51
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```
### Information
 - Diagnostic id: 9E583796-ABBA-42D0-97AA-AF93BA1BB4FC/2018-05-14_07-13-13

### Steps to reproduce the behavior

1.  I do not know how to reproduce error, all the sudden after a an IT wide windows update everything started failing here.

**Comment by jasonbivins** [comment]
@cmosguy 
Does it start if you right click the docker icon, and switch modes to Windows containers?

**Comment by rn** [comment]
@cmosguy there seem to be two issues in your logs:

First, the LinuxVM boots really slow:
```
[05:19:57.872][Moby           ][Info   ] [   60.133717] Write protecting the kernel read-only data: 14336k
[05:19:57.890][Moby           ][Info   ] [   60.179359] Freeing unused kernel memory: 2040K
[05:19:57.928][Moby           ][Info   ] [   60.201998] Freeing unused kernel memory: 1368K
[05:19:57.968][Moby           ][Info   ] [   60.246650] random: crng init done
```
Typically a normal system would get to this stage in like 2-5 seconds. On your system it takes 60s. See also https://github.com/docker/for-win/issues/1995

Then it boots but there is a go backtrace in the logs (see below). The backtrace looks very similar to https://github.com/moby/moby/issues/27423 which was cause by Lavasoft web companion. Are you running it (or other AV software)?

Here is the backtrace
```
[05:20:47.414][ApiProxy       ][Info   ] Exception 0xc0000005 0x0 0x0 0x5e2f32e1
[05:20:47.414][ApiProxy       ][Info   ] PC=0x5e2f32e1
[05:20:47.414][ApiProxy       ][Info   ] syscall.Syscall9(0x7ffa414b9900, 0x7, 0x884, 0xc04221f458, 0x1, 0xc04221f44c, 0xc04221f448, 0xc0424a2900, 0x0, 0x0, ...)
[05:20:47.414][ApiProxy       ][Info   ]        C:/go19/src/runtime/syscall_windows.go:185 +0x69
[05:20:47.414][ApiProxy       ][Info   ] syscall.WSARecv(0x884, 0xc04221f458, 0x1, 0xc04221f44c, 0xc04221f448, 0xc0424a2900, 0x0, 0xc042029180, 0x2fd13f8)
[05:20:47.414][ApiProxy       ][Info   ]        C:/go19/src/syscall/zsyscall_windows.go:1545 +0x115
[05:20:47.414][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.(*HVsockConn).read(0xc042440000, 0xc0420d6c00, 0x4, 0x4, 0x4, 0x4, 0xc04221f500)
[05:20:47.414][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_windows.go:158 +0xf9
[05:20:47.414][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.(*HVsockConn).Read(0xc042440000, 0xc04236a000, 0x1000, 0x1000, 0xc04221f5a0, 0x448c59, 0x4592a0)
[05:20:47.414][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock.go:305 +0xbd
[05:20:47.415][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*withLogging).Read(0xc0424da2c0, 0xc04236a000, 0x1000, 0x1000, 0xc042368000, 0xc04221f688, 0xc04221f688)
[05:20:47.415][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:257 +0x77
[05:20:47.415][ApiProxy       ][Info   ] bufio.(*Reader).fill(0xc04232b140)
[05:20:47.415][ApiProxy       ][Info   ]        C:/go19/src/bufio/bufio.go:97 +0x121
[05:20:47.415][ApiProxy       ][Info   ] bufio.(*Reader).ReadSlice(0xc04232b140, 0xa, 0xc04221f758, 0x42ba0f, 0x1dae700, 0xc04206e520, 0x1d3c100)
[05:20:47.415][ApiProxy       ][Info   ]        C:/go19/src/bufio/bufio.go:338 +0x33
[05:20:47.415][ApiProxy       ][Info   ] bufio.(*Reader).ReadLine(0xc04232b140, 0x90, 0x90, 0x1400fc0, 0xc042368001, 0x140000000000, 0x90)
[05:20:47.415][ApiProxy       ][Info   ]        C:/go19/src/bufio/bufio.go:367 +0x3b
[05:20:47.415][ApiProxy       ][Info   ] net/textproto.(*Reader).readLineSlice(0xc04221f898, 0x1150a1e, 0xc04221f7f0, 0x41164f, 0x90, 0x1400fc0)
[05:20:47.415][ApiProxy       ][Info   ]        C:/go19/src/net/textproto/reader.go:55 +0x77
[05:20:47.415][ApiProxy       ][Info   ] net/textproto.(*Reader).ReadLine(0xc04221f898, 0xc04222a1b0, 0x2fd4980, 0x1db0601, 0x1015701037f0158)
[05:20:47.415][ApiProxy       ][Info   ]        C:/go19/src/net/textproto/reader.go:36 +0x32
[05:20:47.416][ApiProxy       ][Info   ] net/http.ReadResponse(0xc04232b140, 0xc0423a2500, 0x1000, 0xc04236a000, 0x1000)
[05:20:47.416][ApiProxy       ][Info   ]        C:/go19/src/net/http/response.go:149 +0xd1
[05:20:47.416][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*passthru).doHandleHTTP(0xc04229e7b0, 0x37f0118, 0xc042440000, 0x1d2e8a0, 0xc0421e8000, 0xc0423a2500, 0x41164f, 0x80)
[05:20:47.416][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:101 +0x186
[05:20:47.416][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*passthru).HandleHTTP(0xc04229e7b0, 0x1d2e8a0, 0xc0421e8000, 0xc0423a2500, 0x0, 0x0)
[05:20:47.416][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:87 +0x1fa
[05:20:47.416][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.withError.func1(0x1d2e8a0, 0xc0421e8000, 0xc0423a2500)
[05:20:47.416][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/routes.go:19 +0x6c
[05:20:47.416][ApiProxy       ][Info   ] net/http.HandlerFunc.ServeHTTP(0xc04229e7e0, 0x1d2e8a0, 0xc0421e8000, 0xc0423a2500)
[05:20:47.416][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:1918 +0x4b
[05:20:47.416][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0422939d0, 0x1d2e8a0, 0xc0421e8000, 0xc0423a2500)
[05:20:47.416][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/gorilla/mux/mux.go:159 +0xf4
[05:20:47.416][ApiProxy       ][Info   ] github.com/docker/pinata/win/backend/apiproxy.(*delegatingHandler).ServeHTTP(0xc0423564b0, 0x1d2e8a0, 0xc0421e8000, 0xc042192100)
[05:20:47.416][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/win/backend/apiproxy/apiproxy.go:17 +0x67
[05:20:47.416][ApiProxy       ][Info   ] net/http.serverHandler.ServeHTTP(0xc04252e0d0, 0x1d2e8a0, 0xc0421e8000, 0xc042192100)
[05:20:47.416][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:2619 +0xbb
[05:20:47.416][ApiProxy       ][Info   ] net/http.(*conn).serve(0xc042446000, 0x1d2f7a0, 0xc0423fb340)
[05:20:47.416][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:1801 +0x724
[05:20:47.416][ApiProxy       ][Info   ] created by net/http.(*Server).Serve
[05:20:47.416][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:2720 +0x28f
[05:20:47.416][ApiProxy       ][Info   ] goroutine 1 [chan receive]:
[05:20:47.416][ApiProxy       ][Info   ] main.main()
[05:20:47.416][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/win/backend/cmd/com.docker.proxy/main.go:70 +0x515
[05:20:47.416][ApiProxy       ][Info   ] goroutine 18 [syscall]:
[05:20:47.416][ApiProxy       ][Info   ] os/signal.signal_recv(0x0)
[05:20:47.416][ApiProxy       ][Info   ]        C:/go19/src/runtime/sigqueue.go:131 +0xad
[05:20:47.416][ApiProxy       ][Info   ] os/signal.loop()
[05:20:47.416][ApiProxy       ][Info   ]        C:/go19/src/os/signal/signal_unix.go:22 +0x29
[05:20:47.416][ApiProxy       ][Info   ] created by os/signal.init.0
[05:20:47.416][ApiProxy       ][Info   ]        C:/go19/src/os/signal/signal_unix.go:28 +0x48
[05:20:47.416][ApiProxy       ][Info   ] goroutine 21 [chan receive]:
[05:20:47.417][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1d900e0)
[05:20:47.417][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/golang/glog/glog.go:882 +0xa6
[05:20:47.417][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/golang/glog.init.0
[05:20:47.417][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/golang/glog/glog.go:410 +0x20a
[05:20:47.417][ApiProxy       ][Info   ] goroutine 22 [select]:
[05:20:47.417][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe(0xc042293960, 0x1, 0xc042453f18, 0x0)
[05:20:47.417][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:270 +0x169
[05:20:47.417][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).listenerRoutine(0xc042293960)
[05:20:47.417][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:300 +0x139
[05:20:47.417][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.ListenPipe
[05:20:47.417][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:374 +0x2b8
[05:20:47.417][ApiProxy       ][Info   ] goroutine 5 [chan receive]:
[05:20:47.417][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).Accept(0xc042293960, 0x14c2960, 0xc042446000, 0x1d2f860, 0xc0421561e0)
[05:20:47.417][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:397 +0x199
[05:20:47.417][ApiProxy       ][Info   ] net/http.(*Server).Serve(0xc04252e0d0, 0x1d238a0, 0xc042293960, 0x0, 0x0)
[05:20:47.417][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:2695 +0x1b9
[05:20:47.417][ApiProxy       ][Info   ] github.com/docker/pinata/win/backend/apiproxy.(*apiProxy).start.func1(0xc04229e990)
[05:20:47.417][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/win/backend/apiproxy/apiproxy.go:62 +0x4c
[05:20:47.417][ApiProxy       ][Info   ] created by github.com/docker/pinata/win/backend/apiproxy.(*apiProxy).start
[05:20:47.417][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/win/backend/apiproxy/apiproxy.go:61 +0xa1
[05:20:47.417][ApiProxy       ][Info   ] goroutine 8 [IO wait]:
[05:20:47.417][ApiProxy       ][Info   ] internal/poll.runtime_pollWait(0x37a1f40, 0x72, 0xc04218b218)
[05:20:47.417][ApiProxy       ][Info   ]        C:/go19/src/runtime/netpoll.go:173 +0x5e
[05:20:47.417][ApiProxy       ][Info   ] internal/poll.(*pollDesc).wait(0xc04218b358, 0x72, 0x1d0f600, 0x0, 0x0)
[05:20:47.417][ApiProxy       ][Info   ]        C:/go19/src/internal/poll/fd_poll_runtime.go:85 +0xb5
[05:20:47.417][ApiProxy       ][Info   ] internal/poll.(*ioSrv).ExecIO(0x1d8bb80, 0xc04218b218, 0xc042032000, 0x2, 0x1, 0x0)
[05:20:47.417][ApiProxy       ][Info   ]        C:/go19/src/internal/poll/fd_windows.go:205 +0x13a
[05:20:47.417][ApiProxy       ][Info   ] internal/poll.(*FD).acceptOne(0xc04218b200, 0x864, 0xc04211a2a0, 0x2, 0x2, 0xc04218b218, 0x2fd0d50, 0xc042461d10, 0x41164f, 0x10)
[05:20:47.417][ApiProxy       ][Info   ]        C:/go19/src/internal/poll/fd_windows.go:767 +0xae
[05:20:47.418][ApiProxy       ][Info   ] internal/poll.(*FD).Accept(0xc04218b200, 0xc0423f0040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
[05:20:47.418][ApiProxy       ][Info   ]        C:/go19/src/internal/poll/fd_windows.go:801 +0x171
[05:20:47.418][ApiProxy       ][Info   ] net.(*netFD).accept(0xc04218b200, 0x41164f, 0x30, 0x137fdc0)
[05:20:47.418][ApiProxy       ][Info   ]        C:/go19/src/net/fd_windows.go:192 +0x88
[05:20:47.418][ApiProxy       ][Info   ] net.(*TCPListener).accept(0xc04206c078, 0x4eefa1, 0x137fdc0, 0xc0423e8ab0)
[05:20:47.418][ApiProxy       ][Info   ]        C:/go19/src/net/tcpsock_posix.go:136 +0x35
[05:20:47.418][ApiProxy       ][Info   ] net.(*TCPListener).Accept(0xc04206c078, 0xc04204e098, 0x1290e80, 0x1d7a4f0, 0x1407440)
[05:20:47.418][ApiProxy       ][Info   ]        C:/go19/src/net/tcpsock.go:247 +0x50
[05:20:47.418][ApiProxy       ][Info   ] net/http.(*Server).Serve(0xc04252e340, 0x1d2e6e0, 0xc04206c078, 0x0, 0x0)
[05:20:47.418][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:2695 +0x1b9
[05:20:47.418][ApiProxy       ][Info   ] github.com/docker/pinata/win/backend/apiproxy.(*apiProxy).start.func1(0xc0423b1710)
[05:20:47.418][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/win/backend/apiproxy/apiproxy.go:62 +0x4c
[05:20:47.418][ApiProxy       ][Info   ] created by github.com/docker/pinata/win/backend/apiproxy.(*apiProxy).start
[05:20:47.418][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/win/backend/apiproxy/apiproxy.go:61 +0xa1
[05:20:47.418][ApiProxy       ][Info   ] goroutine 9 [chan receive]:
[05:20:47.422][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).Accept(0xc0422c2700, 0x1a, 0xc0421eff78, 0x1d238a0, 0xc0422c2700)
[05:20:47.422][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:397 +0x199
[05:20:47.422][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/gui/server.(*guiAPIServer).Start(0xc0424da280, 0x16, 0xc04204c10b)
[05:20:47.422][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/gui/server/server_windows.go:44 +0xe7
[05:20:47.422][ApiProxy       ][Info   ] created by main.main
[05:20:47.422][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/win/backend/cmd/com.docker.proxy/main.go:63 +0x744
[05:20:47.422][ApiProxy       ][Info   ] goroutine 23 [syscall, locked to thread]:
[05:20:47.422][ApiProxy       ][Info   ] syscall.Syscall6(0x7ffa42d55540, 0x5, 0x848, 0xc042303f9c, 0xc042303fa0, 0xc042303fa8, 0xffffffff, 0x0, 0xc042303f50, 0x4037e3, ...)
[05:20:47.422][ApiProxy       ][Info   ]        C:/go19/src/runtime/syscall_windows.go:174 +0x69
[05:20:47.422][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x848, 0xc042303f9c, 0xc042303fa0, 0xc042303fa8, 0x20202020ffffffff, 0x0, 0x0)
[05:20:47.422][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:100 +0xbb
[05:20:47.422][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x848)
[05:20:47.422][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:159 +0xc0
[05:20:47.422][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.initIo
[05:20:47.422][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:72 +0x87
[05:20:47.422][ApiProxy       ][Info   ] goroutine 10 [select]:
[05:20:47.422][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe(0xc0422c2700, 0x1, 0xc0421f1f18, 0x0)
[05:20:47.422][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:270 +0x169
[05:20:47.422][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).listenerRoutine(0xc0422c2700)
[05:20:47.422][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:300 +0x139
[05:20:47.422][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.ListenPipe
[05:20:47.422][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:374 +0x2b8
[05:20:47.422][ApiProxy       ][Info   ] goroutine 11 [select]:
[05:20:47.422][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc042436000, 0xc0423b1770, 0x0, 0x0, 0x1d18760, 0x1d0f450, 0x6e6f697470697263, 0x6574654422203a22, 0x742073656e696d72)
[05:20:47.422][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:186 +0x193
[05:20:47.422][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.connectPipe(0xc042436000, 0x0, 0x0)
[05:20:47.422][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:386 +0xef
[05:20:47.422][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe.func1(0xc042011320, 0xc042436000)
[05:20:47.422][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:267 +0x32
[05:20:47.422][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe
[05:20:47.422][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:266 +0xa9
[05:20:47.422][ApiProxy       ][Info   ] goroutine 36 [select]:
[05:20:47.423][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc0423d8000, 0xc0423e8b10, 0x0, 0x0, 0x1d18760, 0x1d0f450, 0x0, 0x0, 0x0)
[05:20:47.423][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:186 +0x193
[05:20:47.423][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.connectPipe(0xc0423d8000, 0x0, 0x0)
[05:20:47.423][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:386 +0xef
[05:20:47.423][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe.func1(0xc042348120, 0xc0423d8000)
[05:20:47.423][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:267 +0x32
[05:20:47.423][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe
[05:20:47.423][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:266 +0xa9
[05:20:47.423][ApiProxy       ][Info   ] goroutine 49 [select]:
[05:20:47.423][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc0420ea2c0, 0xc0423b1860, 0xc0420ea2f8, 0x0, 0x1d18760, 0x1d0f600, 0x1d18760, 0x1d0f600, 0x0)
[05:20:47.423][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:186 +0x193
[05:20:47.423][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32File).Read(0xc0420ea2c0, 0xc0423b17e1, 0x1, 0x1, 0x0, 0x0, 0x0)
[05:20:47.423][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:224 +0x151
[05:20:47.423][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32MessageBytePipe).Read(0xc042032060, 0xc0423b17e1, 0x1, 0x1, 0x0, 0x0, 0x0)
[05:20:47.423][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:116 +0x63
[05:20:47.423][ApiProxy       ][Info   ] net/http.(*connReader).backgroundRead(0xc0423b17d0)
[05:20:47.423][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:660 +0x69
[05:20:47.423][ApiProxy       ][Info   ] created by net/http.(*connReader).startBackgroundRead
[05:20:47.423][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:656 +0xdf
[05:20:47.423][ApiProxy       ][Info   ] goroutine 50 [syscall, locked to thread]:
[05:20:47.423][ApiProxy       ][Info   ] syscall.Syscall6(0x7ffa42d55540, 0x5, 0x894, 0xc042309f9c, 0xc042309fa0, 0xc042309fa8, 0xffffffff, 0x0, 0x1, 0x1, ...)
[05:20:47.423][ApiProxy       ][Info   ]        C:/go19/src/runtime/syscall_windows.go:174 +0x69
[05:20:47.423][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.getQueuedCompletionStatus(0x894, 0xc042309f9c, 0xc042309fa0, 0xc042309fa8, 0xffffffff, 0x0, 0x0)
[05:20:47.423][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/zsyscall_windows.go:125 +0xbb
[05:20:47.423][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.ioCompletionProcessor(0x894)
[05:20:47.423][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_windows.go:293 +0xcc
[05:20:47.423][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.initIo
[05:20:47.423][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_windows.go:259 +0x87
[05:20:47.423][ApiProxy       ][Info   ] goroutine 51 [chan send]:
[05:20:47.423][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*passthru).doHandleHTTP.func1(0xc042210900, 0xc0423a2500, 0x1d2faa0, 0xc0424da2c0)
[05:20:47.423][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:96 +0x9a
[05:20:47.423][ApiProxy       ][Info   ] created by github.com/docker/pinata/common/backend/proxy.(*passthru).doHandleHTTP
[05:20:47.423][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:95 +0x101
[05:20:47.423][ApiProxy       ][Info   ] rax     0x3086e30
[05:20:47.423][ApiProxy       ][Info   ] rbx     0x0
[05:20:47.423][ApiProxy       ][Info   ] rcx     0x7ffa43f957a4
[05:20:47.423][ApiProxy       ][Info   ] rdi     0x884
[05:20:47.423][ApiProxy       ][Info   ] rsi     0x5e4e8d20
[05:20:47.423][ApiProxy       ][Info   ] rbp     0x0
[05:20:47.423][ApiProxy       ][Info   ] rsp     0x710f9d0
[05:20:47.423][ApiProxy       ][Info   ] r8      0x710f958
[05:20:47.423][ApiProxy       ][Info   ] r9      0x0
[05:20:47.423][ApiProxy       ][Info   ] r10     0x0
[05:20:47.423][ApiProxy       ][Info   ] r11     0x246
[05:20:47.423][ApiProxy       ][Info   ] r12     0xc04221f44c
[05:20:47.423][ApiProxy       ][Info   ] r13     0x51e0840
[05:20:47.423][ApiProxy       ][Info   ] r14     0xc0424a2900
[05:20:47.423][ApiProxy       ][Info   ] r15     0xc04221f448
[05:20:47.423][ApiProxy       ][Info   ] rip     0x5e2f32e1
[05:20:47.423][ApiProxy       ][Info   ] rflags  0x10206
[05:20:47.423][ApiProxy       ][Info   ] cs      0x33
[05:20:47.423][ApiProxy       ][Info   ] fs      0x53
[05:20:47.423][ApiProxy       ][Info   ] gs      0x2b
[05:20:47.462][ApiProxy       ][Error  ] Process died
```

**Comment by cmosguy** [comment]
Hello @jasonbivins and @rn 

Thanks for your help.  I did the following with the combination of your advice:

1. I disabled my AV software (Symanec Endpoint Protection).  *This did not work*
2. I installed the latest Edge release `18.05.0-ce-rc1-win63 (17439)`. *This did not work*
3. I then switched over to the "Windows Containers" as @jasonbivins recommended.  *This worked*
[log.txt](https://github.com/docker/for-win/files/2005053/log.txt)

In summary, I do not know for sure what the difference between windows vs non-windows containers yet when i am running in this mode or what the drawbacks are but it seems to get me going for now.  

Also, I do not understand what was updated by my IT on my system, that created a change to break the docker application.  I think there is something going on with the go `syscall.Syscall9` function being called that is hitting a barrier.  Perhaps I need to run Docker for Windows in Administrator mode?

Thanks!

**Comment by rn** [comment]
Hmm, this is the first time I'm seeing this error. What happens is that there is a process which opens a socket and then connect to it. That works fine, but the call to `WSARecv()` to receive something form the socket after it was connected causes a go run time crash...The arguments to `WSARecv()` look reasonably sane, and in any case it would return an error if there was something wrong. But instead of the error it creates a panic/backtrace. Very weird

I don't think it is related to permission as that ought to return "Permission denied" type errors.

We have quite a few users on the same Windows build as you and this is the first time I see this type of crash. So for now I'm inclined to think it is something local to your system.

I think there is an *experimental* feature, called LCOW (Linux Containers on Windows) which is enabled when you switch to Window Containers. When in Windows container mode, could you try:
```
docker run --platform linux busybox uname -a
```
and see if this works?
