### ISSUE TITLE
Lightweight installer fails AND ends when outgoing connection is blocked by firewall

### ISSUE THREAD

**Issue by hoegge** [docker/for-win#2039]
- [ n.a.] I have tried with the latest version of my channel (Stable or Edge). No - you cannot test this on latest version since it will not trigger the update.
  - [ n.a.] I have submitted Diagnostics
  - [n.a. ] I have included the Diagnostics ID in this Issue
  - Windows Version: 10 pro 1709
  - Docker for Windows Version: Version 18.05.0-ce-rc1-win63 (17439)

### Expected behavior
The installer should say it could not connect and ask - Retry or Cancel so user have the option to open firewall before trying again.

### Actual behavior
If the firewall blocks new outgoing requests the lightweight installer says:
Installation failed

`
An error occurred while sending the request.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.DownloadStep.<DoAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
`

and you can only exit it. 
Next time you update the lightweight is another exe file in another folder, so you cannot give it access beforehand - you can only open your firewall totally, which in many cases are not desired.
The installer should make it possible to retry after the exe has been granted permissions to access the internet.

Version 18.05.0-ce-rc1-win63 (17439)
### Information
Since it is not a Docker error but an installer error the diagnostic info is n.a.

### Steps to reproduce the behavior

  1. Use a firewall that blocks unapproved outgoing connections
  2. Update docker

**Comment by hoegge** [comment]
Hi @jasonbivins 

I’m using a 3rd party firewall controller called “Windows 10 Firewall Control”. It also prevents outgoing connections from any program not explicitely approved - to prevent malicious / or ill-behaving programs from leaking info. Similar to Zonealarm (popular many years ago :-) )
