### ISSUE TITLE
Failed to install update

### ISSUE THREAD

**Issue by pellea** [docker/for-win#2043]
### Expected behavior
Docker updates itself successfully.

### Actual behavior
The docker update dialog crashed with this error:
```
Access to the path 'docker-compose.exe' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at LightweightInstaller.UninstallWorkflow.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<PerformUninstall>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
```
And docker is not isntalled anymore!

### Information
  - Windows Version: Windows 10 Enterprise 1803
  - Docker for Windows Version: latest-1 on edge

I log into Windows using my enterprise account (the account is an administrator). Docker has a lot of trouble with that. 
BTW, the share folders don't work either with this account. I need to use the local administrator.

**Comment by pellea** [comment]
It's already in the group.

**Comment by pellea** [comment]
After further investigation, Visual Studio seems to have locked the docker-compose executable. I close VS2017 and it didn't close the process. I killed it and the install succeeded.

Usually, I don't have any problem upgrading docker while VS is still running.

![docker-vs](https://user-images.githubusercontent.com/395982/40221249-32fc8a30-5a7c-11e8-86ab-44e430540aab.png)
