### ISSUE TITLE
No activity detected on VM, aborting

### ISSUE THREAD

**Issue by AoschkA** [docker/for-win#2061]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 1A5F780B-9641-4288-ABDE-A0E6DD16D44A/2018-05-24_09-29-54

### Expected behavior
Docker starts with linux containers

### Actual behavior
Crash log:
```
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass24_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 272
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

### Information

  - Windows Version: 10
  - Docker for Windows Version: Edge - 18.05.0-ce-win66 (17760)

### Steps to reproduce the behavior

  1. start docker
  2. switch to linux containers

**Comment by krzysztofantczak** [comment]
What about this did: 69C5304E-ECA7-4948-B0E4-46E99B8A99A6/2018-05-31_11-51-43  ?

I'm experiencing the same error on native windows 10 and Docker For Win 18.05.0-ce-win66 (17760).

The only thing i can do to proceed is to "reset to factory defaults", after that, it works for some time and here it is again ...

**Comment by MatthiasF999** [comment]
Same here, Windows Build 17677, Docker 18.05.0-ce-win66 (17760).

Diagnostic ID: 1B282871-896E-4CFB-9BEB-34A59CA4F976/2018-06-01_00-40-20

**Comment by dolifer** [comment]
Same here, Windows Windows 10 Build 16299, Docker 18.05.0-ce-win67 (18263)
Diagnostic ID: 4775B175-98DD-4BA9-9158-9033B97A05B8/2018-06-09_09-02-46

**Comment by khs1994** [comment]
```bash
No activity detected on VM, aborting
   在 Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:行号 36
   在 Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 75
   在 Docker.Actions.<>c__DisplayClass15_0.<Start>b__0() 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:行号 59
   在 Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:行号 59
```

Diagnostic ID: DF51DC4C-CD26-4013-BEE5-2241A7F8D337/2018-06-15_15-42-49

**Comment by Kew** [comment]
I am getting this as well. 

```
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 75
   at Docker.Actions.<>c__DisplayClass15_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 59
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

**Comment by krzysztofantczak** [comment]
This is endless cycle :(

1. reset to factory defaults
2. all good
3. restart docker or the whole system
4. "No activity detected on VM, aborting"
5. goto 1

**Comment by doumlap** [comment]
any update here?

**Comment by khs1994** [comment]
```bash
start->
  not work->quit
->start->not work->quit
->start->it's work
```

**Comment by AoschkA** [comment]
Nested virtualization is enabled. And you have close the issue based upon false information

**Comment by krzysztofantczak** [comment]
@AoschkA can You elaborate? The issue is affecting people that are not using nested virtualization as well.

**Comment by AoschkA** [comment]
No this is a nested virtualization issue

**Comment by krzysztofantczak** [comment]
I'm speechless ;-D You just accused people on providing false information - when they actually did provide correct feedback under issue reported in a way (by YOU btw.) that never indicated Your specific problem was related to nested virtualization - that was a resolution of it - provided by @jasonbivins. However, the same exactly result and issue still affects people WITHOUT nested virtualization. What's the purpose of Your comment here exactly? It solves nothing and its misleading.

**Comment by AoschkA** [comment]
Because he is closing the issue saying that nested virtualization is disabled on my parallels stop, which it is not. I am pointing out a flaw in the logs. What's the purpose of your comment?

**Comment by nlmalc** [comment]
This happening for me too: 45A4EE05-74BB-4C02-940D-38C2A5848622/20180726120102

No problems until I updated to 18.06.0-ce-win70 (19075).  After booting, Docker works for a bit.  This error crops up after a while, and then it doesn't seem to restart Docker when I tell it to.  I can see MobyLinuxVM isn't running, until I switch to Windows containers and then back to Linux containers.  At this point Docker is working again.

Why was ticket closed?  Has the issue that everybody including myself resolved and can be expected in a future stable release?

**Comment by masi** [comment]
Why closed? Happens to me right now:

```
LogFile: C:\Users\Masi\AppData\Local\Docker\log.92.txt
Version: 18.03.1-ce-win65 (17513)
Channel: stable
Sha1: 93354b38bd7210badafff8e0ce1f0be9a465be83
Started on: 2018/07/23 14:31:47.210
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1803
Build: 17134
BuildLabName: 17134.1.amd64fre.rs4_release.180410-1804
File: C:\Users\Masi\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe"
```

Crash report has been uploaded.

> 
> No activity detected on VM, aborting
>    bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:Zeile 36.
>    bei Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 77.
>    bei Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 61.
>    bei Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:Zeile 59.

**Comment by QuintinRudman** [comment]
same issue

![2018-07-30 18_31_50-no activity detected on vm aborting issue 2214 docker_for-win](https://user-images.githubusercontent.com/23453952/43415262-63f169d8-9435-11e8-8d8c-ed6b10a650ec.png)

**Comment by alphonse92** [comment]
Same error here

**Comment by IMmmKI** [comment]
Same error here as well. Docker version 18.06.0-ce, build 0ffa825

**Comment by JNaeemGitonga** [comment]
Experienced this with v18.06.0
fix: 
rollback to v18.03.0 until community fixes v180.6.0 for Windows

**Comment by eltiare** [comment]
How does one go about rolling back if you're starting out on this version? Docker doesn't provide older versions.

I seem to have gotten past it by running Docker in administrator mode, but that's a big pain if you ever restart.

**Comment by alexvy86** [comment]
@eltiare they do, see [here](https://docs.docker.com/docker-for-windows/release-notes/).

As for the issue in general, I also experienced it several days ago when I first upgraded to 18.06 and had to roll back to 18.03. Then after a couple of days of doing nothing special, I just tried reinstalling 18.06 and the problem didn't show up again. Not sure if it was a different build of 18.06? This is what I see in "About Docker":
```
Version 18.06.0-ce-win72 (19098)
Channel: stable
5513f91
```

**Comment by alphonse92** [comment]
Solution to Docker problems after updating. Rollbacking to my last instalation:

Version 17.09.1-ce-win42 (14687)
Channel: stable
3176a6a

**Comment by bhimraj-ghadge** [comment]
I faced same issue after upgrading to version 18.06.0.   Reset to factory settings worked for me, but as mentioned it can not be a solution for all.

**Comment by talgat-ruby** [comment]
I have the same issue. Why not reopen the issue? If so many people still have the problems.

**Comment by liujianm** [comment]
I faced same issue https://github.com/docker/for-win/issues/2489

**Comment by ochavezhacsys** [comment]
### What's up? ... :( ... similar problems ... :(

Unable to create: Se detuvo el comando en ejecución porque la variable de preferencia "ErrorActionPreference" o un parámetro común se han establecido en Stop: Hyper-V no encontró ningún conmutador virtual con el nombre "DockerNAT".
en New-Switch, <sin archivo>: línea 121
en <ScriptBlock>, <sin archivo>: línea 411
   en Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) en C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:línea 36
   en Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) en C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:línea 92
   en Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() en C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:línea 155
   en Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() en C:\workspaces\stable-18.09.x\src\github
