### ISSUE TITLE
Docker won't start or run any command

### ISSUE THREAD

**Issue by mmuarc** [docker/for-win#2079]
- [ X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 5EB13AF8-8578-4CEB-8B5B-0B47D2C9D35E/2018-05-31_13-01-07

### Expected behavior
Docker starts and I can run commands

### Actual behavior
Docker doesn't start throwing this error in the app:

error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 51
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information
This issue just happened without me doing any changes that I know. I installed docker this week and it was working just fine. Now it won't work. I have been searching for different issues related to the error I am getting and most of them point that the daemon might not be running (as stated in the log) or it isn't running with admin rights. I have tried every option I've seen. Since stopping the service from a command window and starting it with admin privileges or even uninstalling docker, disabling Hyper V, restart, Enable Hyper V and install docker again. Nothing seems to work.

The log keeps saying in the daemon checker that the daemon it is not running but windows says it is.

After failing to start, If I click the restart option in docker it instantly shows as running. But still no command will work with the following output message:

docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.

The result is I can't use docker any more in this machine.

  - Windows Version: Windows 10 Enterprise
  - Docker for Windows Version:  18.03.1-ce, build 9ee9f40

**Updated information:** It works fine if I switch it to Windows Container. So the issue only happens in Linux containers mode.

### Steps to reproduce the behavior
  
Just try to start docker.
[docker_log_error.txt](https://github.com/docker/for-win/files/2058124/docker_log_error.txt)

**Comment by markandersonus** [comment]
I have same issue. Worked fine last week when I installed. Today got same error as this. Restarting doesn't help

**Comment by mmuarc** [comment]
@markandersonus As a workwaround it worked for me to switch for windows containers. Of course that doesn't help you running containers but at least you can build.

**Comment by toarnold** [comment]
I have the same issue. Same docker version. Docker was working properly until I installed the Windows 10 April update.

After starting the computer a messagebox appears:

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.


   bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:Zeile 36.
   bei Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 67.
   bei Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 51.
   bei Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:Zeile 59.

But the service console tells me that the docker daemon has been startet and is up and running.

**Comment by rn** [comment]
@mmuarc do you by any chance run any AV software? In the logs I see a crash in a go program (see below) and we had similar issue with some AV from different vendors.

```
[12:56:05.934][ApiProxy       ][Info   ] Exception 0xc0000005 0x0 0x0 0x750b4396
[12:56:05.934][ApiProxy       ][Info   ] PC=0x750b4396
[12:56:05.934][ApiProxy       ][Info   ] syscall.Syscall9(0x7ffe9eabbdb0, 0x7, 0x810, 0xc042571458, 0x1, 0xc04257144c, 0xc042571448, 0xc0424b0240, 0x0, 0x0, ...)
[12:56:05.934][ApiProxy       ][Info   ]        C:/go19/src/runtime/syscall_windows.go:185 +0x69
[12:56:05.934][ApiProxy       ][Info   ] syscall.WSARecv(0x810, 0xc042571458, 0x1, 0xc04257144c, 0xc042571448, 0xc0424b0240, 0x0, 0xc04249e700, 0x3050d50)
[12:56:05.935][ApiProxy       ][Info   ]        C:/go19/src/syscall/zsyscall_windows.go:1545 +0x115
[12:56:05.935][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.(*HVsockConn).read(0xc0421a0000, 0xc04231c220, 0x4, 0x4, 0x4, 0x4, 0xc042571500)
[12:56:05.935][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_windows.go:158 +0xf9
[12:56:05.935][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.(*HVsockConn).Read(0xc0421a0000, 0xc0422fb000, 0x1000, 0x1000, 0xc0425715a0, 0x448c59, 0x4592a0)
[12:56:05.935][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock.go:305 +0xbd
[12:56:05.935][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*withLogging).Read(0xc042002220, 0xc0422fb000, 0x1000, 0x1000, 0xc04248c000, 0xc042571688, 0xc042571688)
[12:56:05.935][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:257 +0x77
[12:56:05.935][ApiProxy       ][Info   ] bufio.(*Reader).fill(0xc0422725a0)
[12:56:05.935][ApiProxy       ][Info   ]        C:/go19/src/bufio/bufio.go:97 +0x121
[12:56:05.935][ApiProxy       ][Info   ] bufio.(*Reader).ReadSlice(0xc0422725a0, 0xa, 0xc042571758, 0x42ba0f, 0x1dae700, 0xc042074520, 0x1d3c100)
[12:56:05.935][ApiProxy       ][Info   ]        C:/go19/src/bufio/bufio.go:338 +0x33
[12:56:05.935][ApiProxy       ][Info   ] bufio.(*Reader).ReadLine(0xc0422725a0, 0x90, 0x90, 0x1400fc0, 0xc04248c001, 0x140000000000, 0x90)
[12:56:05.935][ApiProxy       ][Info   ]        C:/go19/src/bufio/bufio.go:367 +0x3b
[12:56:05.935][ApiProxy       ][Info   ] net/textproto.(*Reader).readLineSlice(0xc042571898, 0x1150a1e, 0xc0425717f0, 0x41164f, 0x90, 0x1400fc0)
[12:56:05.935][ApiProxy       ][Info   ]        C:/go19/src/net/textproto/reader.go:55 +0x77
[12:56:05.935][ApiProxy       ][Info   ] net/textproto.(*Reader).ReadLine(0xc042571898, 0xc0422681b0, 0x13b30a0, 0x1db06a0, 0x1005701054b5ed8)
[12:56:05.935][ApiProxy       ][Info   ]        C:/go19/src/net/textproto/reader.go:36 +0x32
[12:56:05.935][ApiProxy       ][Info   ] net/http.ReadResponse(0xc0422725a0, 0xc0421d0600, 0x1000, 0xc0422fb000, 0x1000)
[12:56:05.935][ApiProxy       ][Info   ]        C:/go19/src/net/http/response.go:149 +0xd1
[12:56:05.935][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*passthru).doHandleHTTP(0xc0423ec330, 0x54b5e98, 0xc0421a0000, 0x1d2e8a0, 0xc0421f2000, 0xc0421d0600, 0x41164f, 0x80)
[12:56:05.935][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:101 +0x186
[12:56:05.935][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*passthru).HandleHTTP(0xc0423ec330, 0x1d2e8a0, 0xc0421f2000, 0xc0421d0600, 0x0, 0x0)
[12:56:05.935][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:87 +0x1fa
[12:56:05.935][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.withError.func1(0x1d2e8a0, 0xc0421f2000, 0xc0421d0600)
[12:56:05.935][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/routes.go:19 +0x6c
[12:56:05.935][ApiProxy       ][Info   ] net/http.HandlerFunc.ServeHTTP(0xc0423ec3c0, 0x1d2e8a0, 0xc0421f2000, 0xc0421d0600)
[12:56:05.935][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:1918 +0x4b
[12:56:05.935][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0421340e0, 0x1d2e8a0, 0xc0421f2000, 0xc0421d0600)
[12:56:05.935][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/gorilla/mux/mux.go:159 +0xf4
[12:56:05.935][ApiProxy       ][Info   ] github.com/docker/pinata/win/backend/apiproxy.(*delegatingHandler).ServeHTTP(0xc0423864d0, 0x1d2e8a0, 0xc0421f2000, 0xc0421d0000)
[12:56:05.935][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/win/backend/apiproxy/apiproxy.go:17 +0x67
[12:56:05.935][ApiProxy       ][Info   ] net/http.serverHandler.ServeHTTP(0xc0424d6270, 0x1d2e8a0, 0xc0421f2000, 0xc0421d0000)
[12:56:05.935][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:2619 +0xbb
[12:56:05.935][ApiProxy       ][Info   ] net/http.(*conn).serve(0xc0420c4500, 0x1d2f7a0, 0xc0420500c0)
[12:56:05.935][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:1801 +0x724
[12:56:05.936][ApiProxy       ][Info   ] created by net/http.(*Server).Serve
[12:56:05.936][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:2720 +0x28f
[12:56:05.936][ApiProxy       ][Info   ] goroutine 1 [chan receive]:
[12:56:05.936][ApiProxy       ][Info   ] main.main()
[12:56:05.936][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/win/backend/cmd/com.docker.proxy/main.go:70 +0x515
[12:56:05.936][ApiProxy       ][Info   ] goroutine 18 [syscall]:
[12:56:05.936][ApiProxy       ][Info   ] os/signal.signal_recv(0x0)
[12:56:05.936][ApiProxy       ][Info   ]        C:/go19/src/runtime/sigqueue.go:131 +0xad
[12:56:05.936][ApiProxy       ][Info   ] os/signal.loop()
[12:56:05.936][ApiProxy       ][Info   ]        C:/go19/src/os/signal/signal_unix.go:22 +0x29
[12:56:05.936][ApiProxy       ][Info   ] created by os/signal.init.0
[12:56:05.936][ApiProxy       ][Info   ]        C:/go19/src/os/signal/signal_unix.go:28 +0x48
[12:56:05.936][ApiProxy       ][Info   ] goroutine 36 [chan receive]:
[12:56:05.936][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x1d900e0)
[12:56:05.936][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/golang/glog/glog.go:882 +0xa6
[12:56:05.936][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/golang/glog.init.0
[12:56:05.936][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/golang/glog/glog.go:410 +0x20a
[12:56:05.936][ApiProxy       ][Info   ] goroutine 5 [select]:
[12:56:05.936][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe(0xc042134070, 0x1, 0xc04246bf18, 0x0)
[12:56:05.936][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:270 +0x169
[12:56:05.936][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).listenerRoutine(0xc042134070)
[12:56:05.936][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:300 +0x139
[12:56:05.936][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.ListenPipe
[12:56:05.936][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:374 +0x2b8
[12:56:05.936][ApiProxy       ][Info   ] goroutine 6 [chan receive]:
[12:56:05.936][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).Accept(0xc042134070, 0x14c2960, 0xc0420c4500, 0x1d2f860, 0xc042428090)
[12:56:05.936][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:397 +0x199
[12:56:05.936][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/gui/server.(*guiAPIServer).Start(0xc04227eea0, 0x16, 0x0)
[12:56:05.936][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/gui/server/server_windows.go:44 +0xe7
[12:56:05.936][ApiProxy       ][Info   ] created by main.main
[12:56:05.936][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/win/backend/cmd/com.docker.proxy/main.go:63 +0x744
[12:56:05.936][ApiProxy       ][Info   ] goroutine 49 [syscall, locked to thread]:
[12:56:05.936][ApiProxy       ][Info   ] syscall.Syscall6(0x7ffe9d746c00, 0x5, 0x7fc, 0xc04257bf9c, 0xc04257bfa0, 0xc04257bfa8, 0xffffffff, 0x0, 0xc04257bf50, 0x4037e3, ...)
[12:56:05.936][ApiProxy       ][Info   ]        C:/go19/src/runtime/syscall_windows.go:174 +0x69
[12:56:05.936][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x7fc, 0xc04257bf9c, 0xc04257bfa0, 0xc04257bfa8, 0xffffffff, 0x0, 0x0)
[12:56:05.936][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:100 +0xbb
[12:56:05.936][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x7fc)
[12:56:05.936][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:159 +0xc0
[12:56:05.936][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.initIo
[12:56:05.936][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:72 +0x87
[12:56:05.936][ApiProxy       ][Info   ] goroutine 8 [select]:
[12:56:05.936][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe(0xc0422961c0, 0x1, 0xc042581f18, 0x0)
[12:56:05.936][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:270 +0x169
[12:56:05.936][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).listenerRoutine(0xc0422961c0)
[12:56:05.936][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:300 +0x139
[12:56:05.936][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.ListenPipe
[12:56:05.936][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:374 +0x2b8
[12:56:05.936][ApiProxy       ][Info   ] goroutine 9 [select]:
[12:56:05.949][ApiProxy       ][Error  ] Process died
[12:56:05.949][DockerDaemonChecker][Error  ] Docker daemon is not running
[12:56:06.038][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc042262000, 0xc0423ed6e0, 0x0, 0x0, 0x1d18760, 0x1d0f450, 0x0, 0x0, 0x0)
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:186 +0x193
[12:56:06.038][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.connectPipe(0xc042262000, 0x0, 0x0)
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:386 +0xef
[12:56:06.038][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe.func1(0xc042047560, 0xc042262000)
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:267 +0x32
[12:56:06.038][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:266 +0xa9
[12:56:06.038][ApiProxy       ][Info   ] goroutine 11 [select]:
[12:56:06.038][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc0422620b0, 0xc0423ed830, 0x0, 0x0, 0x1d18760, 0x1d0f450, 0x0, 0x0, 0x0)
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:186 +0x193
[12:56:06.038][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.connectPipe(0xc0422620b0, 0x0, 0x0)
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:386 +0xef
[12:56:06.038][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe.func1(0xc042047740, 0xc0422620b0)
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:267 +0x32
[12:56:06.038][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32PipeListener).makeConnectedServerPipe
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:266 +0xa9
[12:56:06.038][ApiProxy       ][Info   ] goroutine 37 [select]:
[12:56:06.038][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32File).asyncIo(0xc0420ee2c0, 0xc0424280f0, 0xc0420ee2f8, 0x0, 0x1d18760, 0x1d0f600, 0x1d18760, 0x1d0f600, 0x0)
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:186 +0x193
[12:56:06.038][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32File).Read(0xc0420ee2c0, 0xc0424b0041, 0x1, 0x1, 0x0, 0x0, 0x0)
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/file.go:224 +0x151
[12:56:06.038][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/Microsoft/go-winio.(*win32MessageBytePipe).Read(0xc042384b20, 0xc0424b0041, 0x1, 0x1, 0x0, 0x0, 0x0)
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/Microsoft/go-winio/pipe.go:116 +0x63
[12:56:06.038][ApiProxy       ][Info   ] net/http.(*connReader).backgroundRead(0xc0424b0030)
[12:56:06.038][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:660 +0x69
[12:56:06.038][ApiProxy       ][Info   ] created by net/http.(*connReader).startBackgroundRead
[12:56:06.038][ApiProxy       ][Info   ]        C:/go19/src/net/http/server.go:656 +0xdf
[12:56:06.038][ApiProxy       ][Info   ] goroutine 38 [syscall, locked to thread]:
[12:56:06.038][ApiProxy       ][Info   ] syscall.Syscall6(0x7ffe9d746c00, 0x5, 0x820, 0xc0425abf9c, 0xc0425abfa0, 0xc0425abfa8, 0xffffffff, 0x0, 0x1, 0x1, ...)
[12:56:06.038][ApiProxy       ][Info   ]        C:/go19/src/runtime/syscall_windows.go:174 +0x69
[12:56:06.038][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.getQueuedCompletionStatus(0x820, 0xc0425abf9c, 0xc0425abfa0, 0xc0425abfa8, 0xffffffff, 0x0, 0x0)
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/zsyscall_windows.go:125 +0xbb
[12:56:06.038][ApiProxy       ][Info   ] github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.ioCompletionProcessor(0x820)
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_windows.go:293 +0xcc
[12:56:06.038][ApiProxy       ][Info   ] created by github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock.initIo
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/vendor/github.com/linuxkit/virtsock/pkg/hvsock/hvsock_windows.go:259 +0x87
[12:56:06.038][ApiProxy       ][Info   ] goroutine 39 [chan send]:
[12:56:06.038][ApiProxy       ][Info   ] github.com/docker/pinata/common/backend/proxy.(*passthru).doHandleHTTP.func1(0xc042214960, 0xc0421d0600, 0x1d2faa0, 0xc042002220)
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:96 +0x9a
[12:56:06.038][ApiProxy       ][Info   ] created by github.com/docker/pinata/common/backend/proxy.(*passthru).doHandleHTTP
[12:56:06.038][ApiProxy       ][Info   ]        c:/gopath/src/github.com/docker/pinata/common/backend/proxy/passthru.go:95 +0x101
[12:56:06.038][ApiProxy       ][Info   ] rax     0x314c2d0
[12:56:06.038][ApiProxy       ][Info   ] rbx     0x314c2d0
[12:56:06.038][ApiProxy       ][Info   ] rcx     0x7ffea01364d4
[12:56:06.038][ApiProxy       ][Info   ] rdi     0x0
[12:56:06.038][ApiProxy       ][Info   ] rsi     0x752ad280
[12:56:06.038][ApiProxy       ][Info   ] rbp     0x0
[12:56:06.038][ApiProxy       ][Info   ] rsp     0x72bf9d0
[12:56:06.038][ApiProxy       ][Info   ] r8      0x72bf958
[12:56:06.038][ApiProxy       ][Info   ] r9      0x0
[12:56:06.038][ApiProxy       ][Info   ] r10     0x0
[12:56:06.038][ApiProxy       ][Info   ] r11     0x246
[12:56:06.038][ApiProxy       ][Info   ] r12     0xc04257144c
[12:56:06.038][ApiProxy       ][Info   ] r13     0x30c0840
[12:56:06.038][ApiProxy       ][Info   ] r14     0xc042571458
[12:56:06.038][ApiProxy       ][Info   ] r15     0xc042571448
[12:56:06.038][ApiProxy       ][Info   ] rip     0x750b4396
[12:56:06.038][ApiProxy       ][Info   ] rflags  0x10202
[12:56:06.038][ApiProxy       ][Info   ] cs      0x33
[12:56:06.038][ApiProxy       ][Info   ] fs      0x53
[12:56:06.038][ApiProxy       ][Info   ] gs      0x2b
```

**Comment by mmuarc** [comment]
@rn  Thanks for your answer. I'm almost sure I am running AV and other firewalls and protections enforced by company policy. I'm trying to run Docker in a corporative laptop with a Windows 10 image customized by the IT department. 

On the other hand I have colleagues that are running it without problems in their laptops with potentially the same policies.

Since on the first install it worked for about 1 week or so and then suddenly stopped working. I was hoping for some sort of orientation about where the problem can be coming from so I can contact IT and try to get the problem solved. 

Kind regards,

Miguel

**Comment by rn** [comment]
@mmuarc maybe some AV signatures/files got updated. Below is my list of AV related issues and links to comments on this tracker. Some of them were intermittent, ie stuff started working again after another update etc. there were certainly some cases which caused a very similar crash in Go programs, but I can't remember which one.

- Unisys Stealth client (V3.3.011.0) see https://github.com/docker/for-win/issues/1933
- McAfee Endpoint Protection (10.5.1) https://github.com/docker/for-win/issues/292#issuecomment-380077617 also https://github.com/docker/for-win/issues/1961
- Symantec Endpoint Protection Firewall https://github.com/docker/for-win/issues/1961#issuecomment-382428717
- Trend Micro OfficeScan 12 https://github.com/docker/for-win/issues/324#issuecomment-364410062
- Sophos Avecto Defendpoint: https://github.com/docker/for-win/issues/1780#issuecomment-377610810
- Sophos HitmanPro.alert service: https://github.com/docker/for-win/issues/1221#issuecomment-362818300
- LavaSoft WebCompanion: https://github.com/moby/moby/issues/27423
- Digital Guardian: https://github.com/docker/for-win/issues/2023#issuecomment-388807440 and https://github.com/docker/for-win/issues/2023#issuecomment-389845643

**Comment by allgao** [comment]
Are you using docker for windows on windows 10?  Try this:  Right click docker icon -> switch to windows containers...
Tell me if it works.

**Comment by Filipedguy** [comment]
See https://github.com/docker/for-win/issues/2453#issuecomment-415023200 for more info

**Comment by mmuarc** [comment]
It finally was, as suggested by @rn, a problem related to an update of Digital Guardian. So please feel free to close this.

**Comment by hargrave81** [comment]
@mmuarc what was the solution/work around to the Digital Guardian blocking.  I have a similar issue where Docker will start but within 5 minutes docker will no longer respond on any ports for any containers or docker commands.  I cannot uninstall this application, so help configuring it for Docker-Friendly mode would be nice.

**Comment by mmuarc** [comment]
@hargrave81  I can't help you there. It was solved by the IT department and I have no clue how they did it.

**Comment by urscion** [comment]
FYI, upgrading to Digital Guardian 7.5 worked for LCOW on Win10 for me.
