### ISSUE TITLE
Unable to create docker when install

### ISSUE THREAD

**Issue by lysnow** [docker/for-win#2091]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: DF33A1E8-A68F-459F-A317-9665C0AB9B90/2018-06-08_14-38-29

### Actual behavior
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 75
   at Docker.Actions.<>c__DisplayClass15_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 59
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
### Information

  - Windows Version:  windows 10 enterprise  version 1703
  - Docker for Windows Version:  Docker Community Edition 18.05.0-ce-win67 2018-06-07

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rn** [comment]
Hmm it looks like the Hyper-V powershell integration is not availabed:
```
Failed to start: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
```

Can you open an elevated powershell and type something like `get-vm` and see if that works?

If not can you stop Docker for Windows, open  "Windows features" (aka "Turn Windows features on and off") and expand the Hyper-V menu. Try disabling it, reboot and then enabling it again (may need another reboot).

![screen shot 2018-06-13 at 11 51 02](https://user-images.githubusercontent.com/3338098/41346959-2670d116-6f00-11e8-8087-59cd51076e7f.png)
