### ISSUE TITLE
While upgrading the docker setup got corrupted,cannot uninstall or install the docker again

### ISSUE THREAD

**Issue by ssatijani** [docker/for-win#2093]
Docker installation giving error after trying to re-install again after setup got corrupted/

Backend service is not installed
   at Docker.WPF.BackendClient.CheckService() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 354
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 167
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 75
   at Docker.Actions.<>c__DisplayClass15_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 59
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by Kew** [comment]
Same issue here.

**Comment by YooYeah** [comment]
Same issue here ...
