### ISSUE TITLE
Docker for Windows fails to start: Unable to launch process 1260

### ISSUE THREAD

**Issue by jsonGiles** [docker/for-win#2094]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 487D0FDE-9064-4F4B-8DF9-8A30FC7101CD/2018-06-08_11-02-37

### Expected behavior
Docker for Windows should load without errors

### Actual behavior
When Windows boots up and Docker begins the startup process an error box appears stating:
Unable to launch process: 1260
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass23_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 262
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information
This occurs on my main development machine with Visual Studio, Hyper-V etc installed and running correctly. 
This occurs, every time I start Windows.
This problem occurred in both the 1709 version of Windows and the newer 1803 version.

After this error occurs the little whale turns and stays red and if you hover over it the tooltip says, "Unable to launch process 1260"

If I issue a simple docker version command (from an elevated Powershell) I get the version info just fine for the client but for the docker engine I get:
:\WINDOWS\system32> docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

Windows 10 version 1803
Docker for Windows: Version 18.03.1-ce-win65 (17513)

### Steps to reproduce the behavior
Boot windows and wait for Docker to load.

Thanks in advance for any help and if I did not supply enough information please let me know.

[log.txt](https://github.com/docker/for-win/files/2084947/log.txt)

**Comment by jasonbivins** [comment]
Hi @jsonGiles   It looks like you're being blocked by group policy - Visual studio tries to impersonate the docker process and is getting blocked. 

```10:56:46.326][Notifications  ][Error  ] Unable to launch process: 1260
[10:56:46.324][NamedPipeServer][Error  ] Unable to execute Start: Unable to launch process: 1260    at Docker.Win32Helpers.NativeImpersonatedProcess.Start(NativeImpersonatedProcess* , basic_string<wchar_t\,std::char_traits<wchar_t>\,std::allocator<wchar_t> >* watchguardPath) in c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.13.26128\include\xstring:line 1802
   at Docker.Win32Helpers.ImpersonatedProcess.Start(String watchguardPath) in c:\gopath\src\github.com\docker\pinata\win\src\docker.win32helpers\impersonatedprocess.cpp:line 250
   at Docker.Backend.Processes.ExternalProcess.StartImpersonatedProcess(String fileName, String arguments, String currentDirectory, IDictionary`2 envVariables, WindowsIdentityRecorder identity, CancellationToken stopToken)  
```

```
[10:56:47.325][WindowsDaemon  ][Warning] The description for Event ID '866' in Source 'Microsoft-Windows-SoftwareRestrictionPolicies' cannot be found.  The local computer may not have the necessary registry information or message DLL files to display the message, or you may not have permission to access them.  The following information is part of the event:'C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe', '{EDCB1E66-364D-40CA-B1C6-7202802F8E2B}', '*.doc*.exe' ```

**Comment by jsonGiles** [comment]
That makes sense, I have had other issues with group policy on that machine as it is joined to active directory domain. I'll start looking in that direction for a solution.
Thank you.

**Comment by jsonGiles** [comment]
I was finally able to resolve this. Apparently a while back I had installed a program to protect against cryptolocker malware and this put in a search filter for executable files with *doc*.* in it and that was blocking the Docker core services from running. Removed that from the registry and Docker runs fine now. Thank you @jasonbivins for putting me on the right trail.
