### ISSUE TITLE
Unable to start Docker: Creating Switch: DockerNAT...

### ISSUE THREAD

**Issue by antonsimola** [docker/for-win#2128]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: DBD33F26-5C16-4735-AFBB-3C9866231B6A/2018-06-20_09-43-43

### Expected behavior
Docker should start after installing

### Actual behavior
Crash on startup

### Information

  - Windows Version: Windows 10 Pro 10.0.17134
  - Docker for Windows Version: 18.05.0-ce-win67 (18263)

```
[09:43:43.291][HyperV         ][Info   ] Creating Switch: DockerNAT...
[09:43:43.538][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 183
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 117
[09:43:43.584][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
[09:43:43.585][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
```

[docker-crash-logs.txt.txt](https://github.com/docker/for-win/files/2118169/docker-crash-logs.txt.txt)
<img width="582" alt="hyperv-create-virtual-switch-crash" src="https://user-images.githubusercontent.com/8913934/41642271-858b8a04-7470-11e8-9648-1dd66d96854f.PNG">

<img width="716" alt="hyperv-create-virtual-machine-crash" src="https://user-images.githubusercontent.com/8913934/41642284-8cfbb318-7470-11e8-9c4d-4fcce2c2152b.PNG">

### Steps to reproduce the behavior
Install docker

Let docker initialize hyper-v and restart.

Something about Docker installation (?) has corrupted my Hyper-V setup since I get errors also when trying to access certain views in Hyper-V Manager (as shown in screenshots)

I have tried reinstalling Docker, reinstalling Hyper-V, removed all VPN programs, factory reset, restarted many many times. I have  successfully been able to run Docker couple weeks ago, perhaps something about the new versions recently is involved in the issue. I tried also installing back older version of Docker, without results.

**Comment by rn** [comment]
There is an odd message in the logs:
```
6/20/2018 9:43:37 AM         26138 Error            Failed while creating virtual Ethernet switch.
6/20/2018 9:43:37 AM         26050 Error            Switch create failed, name =
                                                    'B23325F3-D4F2-4E56-86DD-026B73B92565', friendly name =
                                                    'DockerNAT': Incorrect function. (0x80070001).
```
but also in the logs, when you use Windows containers:
```
[11:44:14.309][WindowsDaemon  ][Error  ] fatal: Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Incorrect function.
[11:44:14.309][WindowsDaemon  ][Error  ] fatal: Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Incorrect function.
```


Stab in the dark, but are you running any AV software which may have been updated?

**Comment by antonsimola** [comment]
Thanks for suggestion. I tried without F-Secure on, same error. Perhaps I will try removing it altogether.

**Comment by antonsimola** [comment]
I had to soft reinstall windows for this, now it is working. In the end I have no clue what caused the hyper-v to get so messed up. I'm closing the issue.

**Comment by chengxuncc** [comment]
[This worked for me](https://github.com/docker/for-win/issues/1221#issuecomment-349321329)
