### ISSUE TITLE
Docker crashes after Windows update

### ISSUE THREAD

**Issue by pohy** [docker/for-win#2134]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 55BA249E-3AFA-4128-87AF-7516E9E94C68/2018-06-21_10-17-25

### Expected behavior
Docker should start

### Actual behavior
Docker crashes at startup
Crash log:
```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.


   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 75
   at Docker.Actions.<>c__DisplayClass15_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 59
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

### Information
After installing the April Windows update, Docker stopped working.
  - Windows Version: Windows 10 Pro, Version 1803, OS Build 17134.112
  - Docker for Windows Version: 18.05.0-ce-win67 (18263)

**Comment by pohy** [comment]
Alright, [this solution](https://github.com/docker/for-win/issues/599#issuecomment-328917434), fixed it for me, after all.
