### ISSUE TITLE
After installing the docker version 18.05.0-ce I am getting the below error : 

### ISSUE THREAD

**Issue by abhi47roy** [docker/for-win#2156]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Windows 10 Pro
  - Docker for Windows Version: 18.05.0-ce

### Steps to reproduce the behavior

  1.Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass24_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 272
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by ebriney** [comment]
Hi @abhi47roy, without any uploaded diagnostics I must close the issue because we cannot do anything, feel free to re-open it if you add your diagnostic to the issue.
I don't have any data in your vm I suggest you to reset to default in the settings.
