### ISSUE TITLE
Startup Error of ObjectNotFound in Set-VMFirmware

### ISSUE THREAD

**Issue by ctaggart** [docker/for-win#216]
### Expected behavior
Docker starts

### Actual behavior
Docker fails to start with error

```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'S7' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
at New-MobyLinuxVM, <No file>: line 242
at <ScriptBlock>, <No file>: line 362
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
80141303-BF5F-4C57-9490-A9BDE913F481/2016-11-09_15-27-11

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

Following the steps to troubleshoot in #67, I get this error:

```
PS C:\WINDOWS\system32> cd 'C:\Program Files\Docker\Docker\resources'
PS C:\Program Files\Docker\Docker\resources> .\MobyLinux.ps1 -Destroy
VM MobyLinuxVM is stopped
Destroying Switch DockerNAT...
Removing VM MobyLinuxVM...
Delete VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
PS C:\Program Files\Docker\Docker\resources> .\MobyLinux.ps1 -Create
Creating Switch: DockerNAT...
Switch created.
Set IP address on switch
Creating VM MobyLinuxVM...
Setting CPUs to 2 and Memory to 2048 MB
Creating dynamic VHD: C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
Connect Internal Switch DockerNAT
Attach DVD .\mobylinux.iso
Set-VMFirmware : Hyper-V encountered an error trying to access an object on computer 'S7' because the object was not
found. The object might have been deleted, or you might not have permission to perform the task. Verify that the
Virtual Machine Management service on the computer is running. If the service is running, try to perform the task
again by using Run as Administrator.
At C:\Program Files\Docker\Docker\resources\MobyLinux.ps1:242 char:11
+     $vm | Set-VMFirmware -EnableSecureBoot Off -BootOrder $vm.DVDDriv ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Set-VMFirmware], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.SetVMFirmware

PS C:\Program Files\Docker\Docker\resources> docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      windows/amd64
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engin
e: The system cannot find the file specified.
```

I am running as admin.

**Comment by ctaggart** [comment]
I'm not sure what is wrong with Set-VMFirmware
```
PS C:\Program Files\Docker\Docker\resources> $vm = Get-VM -Name MobyLinuxVM
PS C:\Program Files\Docker\Docker\resources> $vm | Set-VMFirmware -EnableSecureBoot Off -BootOrder $vm.DVDDrives
Set-VMFirmware : Hyper-V encountered an error trying to access an object on computer 'S7' because the object was not
found. The object might have been deleted, or you might not have permission to perform the task. Verify that the
Virtual Machine Management service on the computer is running. If the service is running, try to perform the task
again by using Run as Administrator.
At line:1 char:7
+ $vm | Set-VMFirmware -EnableSecureBoot Off -BootOrder $vm.DVDDrives
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Set-VMFirmware], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.SetVMFirmware


PS C:\Program Files\Docker\Docker\resources> $vm.DVDDrives | fl


DvdMediaType       : ISO
Path               : C:\Program Files\Docker\Docker\resources\mobylinux.iso
ControllerLocation : 1
ControllerNumber   : 0
ControllerType     : SCSI
Name               : DVD Drive on SCSI controller number 0 at location 1
PoolName           : Primordial
Id                 : Microsoft:D43D866E-763A-4DD4-BD3A-7412364EBC4A\B061AB3E-2706-4D0C-AEC3-9F9A02F757C5\0\1\D
VMId               : d43d866e-763a-4dd4-bd3a-7412364ebc4a
VMName             : MobyLinuxVM
VMSnapshotId       : 00000000-0000-0000-0000-000000000000
VMSnapshotName     :
CimSession         : CimSession: .
ComputerName       : S7
IsDeleted          : False
VMCheckpointId     : 00000000-0000-0000-0000-000000000000
VMCheckpointName   :

```

**Comment by rneugeba** [comment]
@ctaggart thanks for your report. Could you try, in an elevated powershell, something like:
```
$vm = Get-VM MobyLinuxVM
$vm | Set-VMFirmware -EnableSecureBoot Off -BootOrder $vm.DVDDrives
```

**Comment by ctaggart** [comment]
Hi @rneugeba, I got that far last night. I reproduces the error. Since then, I've uninstalled Docker  for Windows and I'm troubleshooting Hyper-V. I'm able to reproduce the same error with a basic VM.
```
PS C:\WINDOWS\system32> $vm | Set-VMFirmware -EnableSecureBoot Off -BootOrder $vm.DVDDrives
Set-VMFirmware : Hyper-V encountered an error trying to access an object on computer 'S7' because the object was not
found. The object might have been deleted, or you might not have permission to perform the task. Verify that the
Virtual Machine Management service on the computer is running. If the service is running, try to perform the task
again by using Run as Administrator.
At line:1 char:7
+ $vm | Set-VMFirmware -EnableSecureBoot Off -BootOrder $vm.DVDDrives
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Set-VMFirmware], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.SetVMFirmware
```

I get this error in the Event Viewer when I try to create a VM with an ISO:
Event Viewer > Application and Services Logs > Microsoft > Windows > Hyper-V-VMMS

```
The description for Event ID 14026 from source Microsoft-Windows-Hyper-V-VMMS cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

New Virtual Machine4
23CBD329-CF0F-4107-AB74-5F5BBD2B4058
C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\New Virtual Machine4.vhdx
%%2147942402
0x80070002

The locale specific resource for the desired message is not present
```

Anyway, this appears to be a Hyper-V issue. I'll try to figure out where to get help.

**Comment by rneugeba** [comment]
@ctaggart thanks for the update. if you figure out where this error is coming from it would be greate if you could update this issue, especially if this is something we could improve in our setup script.

Have you tried disabling the Hyper-V feature, reboot and re-enable it again? There may have been some potential issues during OS upgrade...

**Comment by ctaggart** [comment]
I troubleshot it some more, but I'm quite confused why I can't create an Generation 2 VM with an ISO image attached. I asked about it on StackOverflow.

Can't create Hyper-V Gen 2 because of Event ID 14026
http://stackoverflow.com/questions/40537164/cant-create-hyper-v-gen-2-because-of-event-id-14026

**Comment by ctaggart** [comment]
@rneugeba I finally figured out how to make it work on my system. I'm able to change the boot device like so:

```
    # $vm | Set-VMFirmware -EnableSecureBoot Off -BootOrder $vm.DVDDrives
    $iso = $vm | Get-VMFirmware | select -ExpandProperty BootOrder | where {$_.FirmwarePath.EndsWith("Scsi(0,1)")}
    $vm | Set-VMFirmware -EnableSecureBoot Off -FirstBootDevice $iso
```

**Comment by rneugeba** [comment]
Thanks for the update. @dgageot have you come across this error before? I have not seen it....

**Comment by bunengdenglu** [comment]
@ctaggart I 'm encountering this **problem** right now, and could you please tell me how you got it solved detailedly ?

**Comment by ctaggart** [comment]
@bunengdenglu See the steps above. Essentially, I ended up troubleshooting and patching `C:\Program Files\Docker\Docker\resources\MobyLinux.ps1`.

You can try it out by running powershell as admin:
``` powershell
cd C:\Program Files\Docker\Docker\resources
.\MobyLinux.ps1 -Destroy
.\MobyLinux.ps1 -Create
```
If you are able to reproduce the problem, then may be try the patch I did:
``` powershel
    # $vm | Set-VMFirmware -EnableSecureBoot Off -BootOrder $vm.DVDDrives
    $iso = $vm | Get-VMFirmware | select -ExpandProperty BootOrder | where {$_.FirmwarePath.EndsWith("Scsi(0,1)")}
    $vm | Set-VMFirmware -EnableSecureBoot Off -FirstBootDevice $iso
```

**Comment by Slamper** [comment]
Is there a plan to apply this fix to the Docker for Windows release version ?

**Comment by gerritjanf** [comment]
This fixed the issue for me 💃

**Comment by briandmaher** [comment]
Brilliant, thanks so much! I was going a bit nvts trying to troubleshoot Hyper-V. You prob saved me many hours; much appreciated!
