### ISSUE TITLE
Issue Switching to Linux Containers

### ISSUE THREAD

**Issue by pws2018** [docker/for-win#2177]
- [x] I have uploaded Diagnostics
  - Diagnostics ID: B2C7253B-8339-4D74-8D51-1890742FEADD/2018-07-04_11-11-08

### Expected behavior
Be able to switch to Linux Containers (trying to setup Xibo)

### Actual behavior
'MobyLinuxVM' failed to start. (Virtual machine ID 7E42D00F-1285-41E9-BD77-2D853A0C706D)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID 7E42D00F-1285-41E9-BD77-2D853A0C706D).
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass23_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 264
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information
This is a Virtual Machine on an ESXI host, VMWare.  I tried the same install on a physical machine running the same OS and it worked fine, so I presume it's an issue with the virtual machine - is there a workaround for this?
  - Windows Version: Windows 10 Education vers 1803 x64
  - Docker for Windows Version: Version 18.03.1-ce-win65 (17513)

### Steps to reproduce the behavior
  1. Click switch to Linux Containers

**Comment by coolzsatyen** [comment]
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'SLB-HPH7XT2' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 111
at <ScriptBlock>, <No file>: line 409
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.<>c__DisplayClass30_0.<SwitchDaemon>b__0()
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1()
