### ISSUE TITLE
Crash during start, after adding "hosts" to deamon.json

### ISSUE THREAD

**Issue by artur-ch-PL** [docker/for-win#2178]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E92A5776-7EFC-4762-A98E-22D09A48D521/2018-07-04_12-47-28

### Expected behavior
Enable docker remote API on IP address instead of 'localhost' only.

### Actual behavior
Crash during docker restart.

### Information
I updated deamon.json file to:
`{  "registry-mirrors": [],  "insecure-registries": [    "10.70.57.171:5001"  ], "debug": true, "hosts":["tcp://10.70.57.174:2375"], "experimental": false}`

After that, during restart docker crash. I tried also:

- add a just empty array to "hosts" element - an issue is the same
- add hosts value without \" signs

I followed information included on the page:
https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file

  - Windows Version: Windows 10 Enterprise 64-bit version: 1803, osBuild: 17134.1
  - Docker for Windows Version: 18.03.01-ce

### Steps to reproduce the behavior

  1. Add to deamon.json hosts element
  2. Click: Docker -> Restart
  3. Notice pop-up with error:
```
Error response from daemon: Bad response from Docker engine

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 253
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 184
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144
```

### Question
I did something wrong/miss steps? Any suggestions on how to enable remote docker API from windows host on IPv4? 

Similar to:
https://github.com/docker/for-win/issues/225#issuecomment-266576967

**Comment by artur-ch-PL** [comment]
as a workaround I added on windows TCP port redirection by command:
`netsh interface portproxy add v4tov4 listenport=2385 listenaddress=10.70.57.174 connectport=2375 connectaddress=127.0.0.1`

**Comment by jasonbivins** [comment]
@artur-ch-PL   It looks like hosts is not a valid option for Docker for Windows, but I was able to use it on the EE version

<img width="656" alt="screen shot 2018-07-05 at 4 29 13 pm" src="https://user-images.githubusercontent.com/28021664/42346426-9d764b02-8070-11e8-894e-ab571cd7884e.png">

**Comment by artur-ch-PL** [comment]
So I will close that ticket and stick to workaround. Maybe in the future it will works. :)

Thanks for checking this!
