### ISSUE TITLE
Docker refuses to start with a "large" number of HyperV switches

### ISSUE THREAD

**Issue by Rainmaker52** [docker/for-win#2186]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker should start, independent of Hyper-V network configuration

### Actual behavior
When a large number of Hyper-V switches is present, Docker refuses to start when set to "Windows containers". When using "Linux containers" startup is succesful.

You do not actually need _that_ large of a number of switches. On my system, Docker refuses to start when there are more than ~10 internal switches present. I generally use internal switches. I am unsure whether the problem persists when using External or Private switches.

The error message displayed during startup is:

> Error response from daemon: i/o timeout
> 
>    at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
>    at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 222
>    at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 96
>    at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
>    at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144

The log.txt displays 1000s of lines with these messages:

> [23:49:18.486][ApiProxy       ][Info   ] time="2018-07-06T23:49:18+02:00" msg="proxy >> GET /v1.37/events\n"
> [23:49:18.552][ApiProxy       ][Info   ] time="2018-07-06T23:49:18+02:00" msg="i/o timeout"
> [23:49:18.553][ApiProxy       ][Error  ] time="2018-07-06T23:49:18+02:00" msg="Error watch events stream: Error response from daemon: i/o timeout"
> [23:49:18.553][ApiProxy       ][Info   ] time="2018-07-06T23:49:18+02:00" msg="proxy >> GET /v1.37/events\n"
> [23:49:18.555][WindowsDaemon  ][Warning] Unable to locate plugin: internal, retrying in 4s
> [23:49:18.557][WindowsDaemon  ][Warning] Unable to locate plugin: internal, retrying in 4s
> [23:49:18.619][ApiProxy       ][Info   ] time="2018-07-06T23:49:18+02:00" msg="i/o timeout"
> [23:49:18.619][ApiProxy       ][Error  ] time="2018-07-06T23:49:18+02:00" msg="Error watch events stream: Error response from daemon: i/o timeout"
> [23:49:18.619][ApiProxy       ][Info   ] time="2018-07-06T23:49:18+02:00" msg="proxy >> GET /v1.37/events\n"
> [23:49:18.671][ApiProxy       ][Info   ] time="2018-07-06T23:49:18+02:00" msg="i/o timeout"

The log file also displays:

> [23:49:19.144][ApiProxy       ][Error  ] time="2018-07-06T23:49:19+02:00" msg="Error watch events stream: Error response from daemon: i/o timeout"
> [23:49:19.145][ApiProxy       ][Info   ] time="2018-07-06T23:49:19+02:00" msg="proxy >> GET /v1.37/events\n"
> [23:49:19.164][ApiProxy       ][Info   ] time="2018-07-06T23:49:19+02:00" msg="i/o timeout"
> [23:49:19.175][DockerDaemonChecker][Error  ] **Docker daemon is not running**
> [23:49:19.197][ApiProxy       ][Info   ] time="2018-07-06T23:49:19+02:00" msg="i/o timeout"
> [23:49:19.197][ApiProxy       ][Error  ] time="2018-07-06T23:49:19+02:00" msg="Error watch events stream: Error response from daemon: i/o timeout"
> [23:49:19.197][ApiProxy       ][Info   ] time="2018-07-06T23:49:19+02:00" msg="proxy >> GET /v1.37/events\n"
> [23:49:19.251][ApiProxy       ][Info   ] time="2018-07-06T23:49:19+02:00" msg="i/o timeout"

Obviously, I've checked that the Docker Windows services are actually running.

Removing the Hyper-V switches makes Docker start again.

### Information
  - Windows Version: 10.0.17692.1004. Was also present in previous Windows version
  - Docker for Windows Version: 18.05.0-ce-win67 (edge). Also present in current stable release.

### Steps to reproduce the behavior
1. Switch to "Windows containers". Wait for the switch to complete
2. Stop Docker by choosing "Quit Docker in the context menu
3. Run this PowerShell script:
```
PS C:\> for($i=0; $i -le 20; $i++){
>> New-VMSwitch -Name "Switch$($i)" -SwitchType Internal
>> }
```
4. Start Docker
5. Wait for a few minutes. A timeout will occur.

**Comment by Rainmaker52** [comment]
Running version 2.0.1.0 (30090) from Edge, I've not been able to reproduce this bug.
