### ISSUE TITLE
No activity detected on VM, aborting

### ISSUE THREAD

**Issue by robrich** [docker/for-win#2214]
**Diagnostics ID:** 448D1A06-BF15-4908-834D-EB41D6F32ECC/2018-07-15_21-49-29 and 448D1A06-BF15-4908-834D-EB41D6F32ECC/2018-07-15_22-15-43 and a few more

Machine: Intel Core i9, Windows 10 Pro (1803), 64 gigs ram
Docker: 18.05.0-ce Edge

Start Docker for Windows as Admin, get "No activity detected on VM, aborting"

Tried reset to factory defaults

Tried https://github.com/docker/for-win/issues/1221#issuecomment-359218276 (`netcfg -d` then reboot)

Tried https://github.com/docker/for-win/issues/1221#issuecomment-365187459 (uninstall Docker, uninstall Hyper-V, delete everything, reinstall Hyper-V, reinstall Docker)

Still can't get Docker for Windows to start in Linux mode, Windows mode works just fine.

Unrelated?  In Event Viewer:
- Error occurred when creating network could not find plugin internal in v1 plugin registry: plugin not found
- Unable to locate plugin: internal, retrying in 8s (and 4s and 2s and 1s)

Moved the drive from this machine where it was working:
Machine: Intel Core i7 - 3rd gen, Windows 10 Pro (1803), 32 gigs ram
Maybe Hyper-V doesn't understand new hardware?

**Comment by robrich** [comment]
Same results when using `dockercli -SwitchLinuxEngine`

minikube starts up just fine.

**Comment by robrich** [comment]
Formatted machine, fresh Windows 10 Pro install from July updated MSDN disk, same behavior.

Diagnostics ID: **DD4576AF-ACA8-4B38-B116-8C9384FE468E/20180720162602**

Windows Version: Microsoft Windows [Version 10.0.17134.112]
Docker Version: Docker version 18.06.0-ce-rc3, build cbfa3d9

**Comment by robrich** [comment]
On the i7 machine, Docker starts correctly when I have `KB4284835` installed, but fails to start correctly when Windows 10 auto-updates and installs `KB4338819`.  On the i9 machine, Docker consistently fails to start whether `KB4338819` is installed or not.  Is i9 not compatible with D4W?

**Comment by rheid** [comment]
@robrich Do you any new about that issue. I have same problem.

**Comment by robrich** [comment]
@rheid: Nope, I'm pretty stuck.  I'm going to give 18.06.0-win69 a try, and I know there were some bad Windows Updates this last go-round, so I'm going to give Windows Update a month.  But pretty much I'm stuck.

**Comment by QuintinRudman** [comment]
Well my entire CI Pipeline is dead as a result of this.

![2018-07-30 18_18_07-196 29 129 195 - remote desktop connection](https://user-images.githubusercontent.com/23453952/43409726-fd1dafe2-9424-11e8-96bc-1661e6fedd7f.png)

**Comment by QuintinRudman** [comment]
If their is anything anyone can suggest that I perhaps did not try I'd really appreciate some help.

I have rebuilt Hyper-V, Containers, Docker, I have gone back everal versions of Docker, Disabled Nexus and bamboo to free up about 8GB of RAM for the MobyLinuxVM, Removed/Deleted and Recreated NAT,  VMSwitch, Netcfg -D, HNS.dat, daemon.json files under AppData, ProgramData, ../Docker/Resources/., Check Reg Entries, Windows Updates - Latest, Nested Virtualization, VT-x Support MMU HW enabled, Docker Daemon Service Elevated Access Rights,...not sure if I missed anything.

**Comment by robrich** [comment]
Diagnostics ID: **448D1A06-BF15-4908-834D-EB41D6F32ECC/20180801124844**  Most recent updates, Docker 18.06.0-ce-win71, same result.  On the up-side, I'm getting good at MiniKube.

**Comment by chrisofire** [comment]
Have we got an update on this issue as currently facing the exact same.

**Comment by robrich** [comment]
Docker version: Version 18.06.0-ce-win71 (19101)
Diagnostics ID: 448D1A06-BF15-4908-834D-EB41D6F32ECC/20180814114221
Same results.

**Comment by carlead** [comment]
On windows 10, if we uninstall windows docker, does it delete containers ?

Thanks,

**Comment by serialbandicoot** [comment]
I'm seeing the same issue with 18.06.0-ce-win72 (19098)

**Comment by superzadeh** [comment]
Yeah, I've noticed as well @talgat-ruby, trying multiple times to restart/quit and launch again seems more or less work, but it still takes a lot of time.

It also seems to be happening after my laptop becomes locked/sleep (using a Surface Pro and very often on the move, to it goes to sleep quite often). That would make me think that it's more related to some recent changes in Hyper-V/Windows, maybe related to battery optimizations that could change the way Hyper-V behaves when resuming from sleep, which could break Docker for some reason, but this is a very wild guess.

If there's anything I can do to help investigate, let me know.

**Comment by robrich** [comment]
on https://github.com/docker/for-win/issues/2253 and https://github.com/docker/for-win/issues/2404 they're suggesting to try [this](https://download.docker.com/win/stable/19470/Docker%20for%20Windows%20Installer.exe) build. So far the consensus is it doesn't resolve it.

**Comment by liujianm** [comment]
I faced same issue https://github.com/docker/for-win/issues/2489

**Comment by syedhassaanahmed** [comment]
Same issue on Stable 18.06.1-ce-win73 (19507)
Diagnostic ID: 9E546F03-92E7-4328-A05E-C51EAAD30B9A/20181024022318

**Comment by marioanz** [comment]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID:  22ED990D-4E0D-4381-9AEB-F430CAE1AFD3/20181130103807

### Expected behavior
Docker Start

### Actual behavior
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information

  - Windows Version: 
Edition:	Windows 10 Pro
Version:	1809
Installed on 	11/29/2018
OS build:	17763.134

  - Docker for Windows Version:  18.09.0

### Steps to reproduce the behavior


  1. Build Windows 10 VM.  Install Updates.
  2. Enable nested virtualization
  3. Turn on Features:  Containers, Hyper-V
  4. Download/Install Docker Desktop
