### ISSUE TITLE
Docker for Windows fails to start correctly

### ISSUE THREAD

**Issue by michaelieti** [docker/for-win#2220]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8C3408F9-E58A-4C06-8953-B8D8C22D0AAC/2018-07-18_15-51-32

### Expected behavior

Installing Docker and running it results in the daemon running and no problems

### Actual behavior

An error is thrown and the daemon fails to run.

### Information

I installed Docker for Windows on my machine. I have hyper-v and virtualization on. However it seems like its failing to start for some reason. The message I get is similar to others, although none of their fixes appear to have worked for me.

The message I get is as follows:  

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID C002FF8C-DCE7-401C-A127-3AD2F4CEA745)

'MobyLinuxVM' failed to start worker process: The specified module could not be found. (0x8007007E). (Virtual machine ID C002FF8C-DCE7-401C-A127-3AD2F4CEA745)

'MobyLinuxVM' could not initialize. (Virtual machine ID C002FF8C-DCE7-401C-A127-3AD2F4CEA745)

'MobyLinuxVM' Microsoft Emulated IoAPIC (Instance ID 72682FC4-040A-430A-BE0B-224574B953FE): Failed to create instance with error 'The specified module could not be found.' (0x8007007E). (Virtual machine ID C002FF8C-DCE7-401C-A127-3AD2F4CEA745)
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 67
   at Docker.Actions.<>c__DisplayClass14_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 51
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

  - Windows Version: win 10 enterprise 64-bit (10.0, Build 15063)
  - Docker for Windows Version: Docker version 18.03.1-ce, build 9ee9f40

### Steps to reproduce the behavior

  1. Install Docker on machine
  2. Attempt to run Docker on machine
  3.

**Comment by michaelieti** [comment]
Further information: I have attempted to use hyper-v to create a debian vm from scratch. However I now receive a similar error: Microsoft Emulated IoAPIC (Instance ID ... ): Failed to create instance with error 'The specified module could not be found.' (0x8007007E).  

I will investigate further.

**Comment by michaelieti** [comment]
Windows was corrupted, I got IT to rebuild and it now installs correctly. Leaving this here for posterity <3
