### ISSUE TITLE
Docker cannot start NoFile in gopath

### ISSUE THREAD

**Issue by stokkumrmv** [docker/for-win#2250]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 815DD9A1-9190-488F-8530-F8EB6C9B48F4/20180725144655

### Expected behavior
Starting Docker

### Actual behavior
"An error Occured

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'PC-17615' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass18_0.<ResetToDefault>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 137
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59"
 
previous version was working fine.

**Comment by gtardif** [comment]
Pleas provide the diagnsotic ID in the issue (you can re-run diagnostics if you don't have your previous diagnosticID, and copy/paste it here once diagnostics are uploaded)

**Comment by stokkumrmv** [comment]
@gtardif Excuse me, done. I think the error is due Hyper-V somehow denying access to the VM.

**Comment by stokkumrmv** [comment]
Problem solved : removing MobyVM, re-enabling Hyper-V and reinstalling Docker did the trick, followed instructions [here](https://stackoverflow.com/questions/42500353/docker-on-windows-10-cant-startup-after-deleting-mobylinuxvm-in-hyper-v-manuall)

**Comment by gtardif** [comment]
Indeed from your logs it seems the Hyper-V was not set properly. Thx for the feedback
