### ISSUE TITLE
No activity detected on VM, aborting

### ISSUE THREAD

**Issue by AdamMarton** [docker/for-win#2253]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A9D40723-139E-4D11-B980-5B6CF922785E/20180725150540

### Expected behavior

Docker should work after the 18.06 update.

### Actual behavior

Docker cannot start, and gives me this:

```
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

### Information

  - Windows Version: Windows 10
  - Docker for Windows Version: Version 18.06.0-ce-win70 (19075) Channel: stable 501df65

Also tried to reset Shared Drives' credentials, which won't save as well (could be related or an entirely different issue). Yes, I've restarted my host OS too.

### Steps to reproduce the behavior

  1. Update Docker to 18.06.0-ce-win70
  2. Docker fails to start

**Comment by dpgover** [comment]
I have the exact same issue, same version of everything. Even tried the credentials reset... and they don't seem to be saved. The checks get unchecked...

Diagnostics ID: 72CE2702-9EA7-4778-9954-ABA297A75D0D/20180725110614

**Comment by Planswalker** [comment]
Had the same issue here. Was able to fix it by resetting to factory default settings... Was not exactly obvious that that would be the fix though.

**Comment by adammarton** [comment]
@Planswalker I'd like to avoid this, if possible.

**Comment by ianwdunlop** [comment]
Got exactly the same after docker updated itself


No activity detected on VM, aborting 
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36  
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77  
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61  
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59


There are a few mentions of `kubectl not found` in the diagnostics. Is that important? Does "reset to factory defaults" blitz all the existing containers? Don't want to click it just in case.

**Comment by dpgover** [comment]
@ianwdunlop It does. Its safe to click... it has a warning ans confirmation request, saying just that. It would nuke all the images, containers, etc.
I suppose `kubectl` is from Kubernetes, one of the new things in the update...

**Comment by dpgover** [comment]
Is there a way to downgrade to the previous version/build? I don't know where to find the installers 😭

**Comment by ianwdunlop** [comment]
I've gone for the factory reset. Luckily I had the data I needed backed up so it wasn't too much of a problem to get the containers running again but not a great advert for docker that an update has caused so much pain.

**Comment by adammarton** [comment]
@dpgover tried downgrade, unfortunately Docker doesn't let you.

**Comment by awuit9090** [comment]
Exact same issue after updated to Version 18.06.0
Diagnostics ID: FCB9DA6D-E9B6-47BD-A254-DD26AB2CF0D8/20180725125435

No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by dpgover** [comment]
I couldn't wait any longer... I have to work... So I finally opted for the factory reset. Seems to be working.

**Comment by adammarton** [comment]
Factory Reset resolves the issue, but this could be not an option for all of us.

**Comment by cybertk** [comment]
Same issue here, cannot afford Factory Reset, waiting other solutions.

**Comment by nphmuller** [comment]
Same issue here after updating to 18.06.0-ce stable.
Had to use Factory Reset to get Docker working again.

Goodbye cache :(

**Comment by Planswalker** [comment]
Okay, so after factory resetting yesterday, I turned on my computer this morning only to run into the same error. Factory resetting again is apparently only a temporary solution, at least for me.

**Comment by adammarton** [comment]
@Planswalker that's huge! Hey @docker, do you plan to fix this?

**Comment by Planswalker** [comment]
Looks like they did - I just got an update notification, and after installing it Docker rebooted with no problems. Hooray!

**Comment by cybertk** [comment]
@Planswalker How do you get the update, no updates on my side.

![image](https://user-images.githubusercontent.com/455809/43303968-af093c0e-91a4-11e8-98a1-e48ddda91313.png)

**Comment by adammarton** [comment]
Can confirm, update resolved the issue.

@cybertk update arrived automatically this morning. If that's not the case for you, hit 'Check for Updates' in Docker's context menu.

**Comment by cybertk** [comment]
@adammarton Could you please share your current Docker-For-Win version, as I was told already on latest version after hitting 'Check for Update'. But this issue is still there.

**Comment by adammarton** [comment]
Hey @cybertk, here it is:
![image](https://user-images.githubusercontent.com/5418343/43309554-5f2e0170-9185-11e8-9a7d-2cda01132a33.png)

**Comment by ianwdunlop** [comment]
@cybertk Version Version 18.06.0-ce-win72 (19098) came in this morning. Seems to work so far. The issues listed as fixed seemed pretty much the same as previous version but so far it appears to work.

**Comment by cybertk** [comment]
Thanks for the information. But it's strange I cannot get the update, do you know if there is a way to upgrade manually?

**Comment by pahjuve89** [comment]
Using build 19098, I still am facing the same issue.
I don't plan to use the factory reset settings, so if there are any other things that I should do after the update, please do inform.

**Comment by cybertk** [comment]
Upgraded to 19098 by downloading the installer from Docker Store. But the issue is still there.

**Comment by adammarton** [comment]
@cybertk did you do a factory reset?

**Comment by cybertk** [comment]
Nope, I have important data in containers .

**Comment by QuintinRudman** [comment]
Issue is not resolved, still getting:

No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass18_0.<ResetToDefault>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 137
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

![2018-07-27 23_31_54-196 29 129 195 - remote desktop connection](https://user-images.githubusercontent.com/23453952/43347408-6968f652-91f5-11e8-921a-a6ed37b01783.png)

**Comment by enxhidervishi** [comment]
I am having the same issue, even after updating it and restarting my laptop. This is the error message I get: 

No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by cybertk** [comment]
Still fighting with this issue, here are some findings.

1. Windows Container works fine. (Settings -> Switch to Windows containers)
2. Sometimes it works after repeatedly quit and re-start Docker

if the 'Factory Reset' can fix this issue, it should be caused by some config.

**Comment by QuintinRudman** [comment]
This is such a stuff up, docker cannot be a single point of failure, my entire CI pipeline has been killed.

**Comment by dprothero** [comment]
Upgraded to `Version 18.06.0-ce-win72 (19098)` this morning - Have the same issue. Restarting Docker appears to work immediately, but docker commands exit with `ERROR: Windows named pipe error: The system cannot find the file specified. (code: 2)`

Rebooting doesn't help. Wish more QA had gone into this release. Going to do the factory reset. 😢

**Comment by efjacobson** [comment]
Same, using fully updated Windows and Docker, factory reset doesn't seem to help at all.

Windows 10 Pro `Version 1803 OS build 17134.191`
Docker `Version 18.06.0-ce-win72 (19098)`

```
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass25_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 275
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

**Comment by QuintinRudman** [comment]
Just an update from my side, I also reverted back to Ver 18.03.0, additional step i took was to c:\program files\docker\docker\resources\dockerd.exe --register-service and copy daemon.json filwith {"bridge" : "none"} into c:\programdata\docker\config\. the start the docker service using net start docker, this time the service stayed up, i then ran "c:\program files\docker\docker\resources\dockerd.exe -D" to see what the daemon does, this seems to get the "\..\pipe\docker_engine" issue and i could do a "docker.exe version" to see desktop and server apps running, however this was with windows containers it wouldn't switch to linux containers, so i had the data center virtualization engineer restart the VM from the host side and this seems to have fixed it.

Key here i think is "config files / network / docker service running" and testing using "dockerd.exe -D" helped a lot

Also when rebuilding uninstall docker restart containers restart hyper-v restart install latest windows updates, restart, then start installing each on its own followed by a restart.

I'm still poking at it, I must admit I understand docker mechanics now much better than before and strangely appreciate it, however, the 3 days we lost on productivity is scary to say the least, but I'm sure next crash I'll be much better equipped to fix any future issues.

**Comment by QuintinRudman** [comment]
Honestly, for now I'd say revert back to Version 18.03.0-ce-win59 (16762) to be safe.

Setup a nested VM on Virtual Box or Hyper-V, play with the latest version if it doesn't break upgrade, I'll wait till middle Aug for all the bugs to be flushed out.

Major requirement change is more RAM required, not sure if the MobyLInux VM uses more than 2GB by the looks of it even if you set the slider to 8GB it doesn't, perhaps updating the ps1 script that creates it will work.

**Comment by robrich** [comment]
I'm having similar issues as discussed on #2214. I'm blocked.

**Comment by ergaziz** [comment]
Same issue on Windows 10 Pro 1803 - Docker CE Version 18.06.0-ce-win72 (19098)

**Comment by PrasadDeloitte** [comment]
I am having a similar issue as well. I am not sure as to how I can go about it. This is needed for https://trailhead.salesforce.com/trails/force_com_dev_intermediate/modules/user-interface-api/units/install-sample-app and I am on corporate laptop.

**Comment by carlead** [comment]
@QuintinRudman When you revert back to older version of docker and you uninstalled Docker for Windows, did you loose your containers ?

Thanks,

**Comment by aboe026** [comment]
Just ran into the same issue this morning.
* `Win 10 Enterprise 17134`
* `Docker CE 18.0.6-ce-win72 (19098)`

**Comment by bhimraj-ghadge** [comment]
I faced same issue after upgrading to version 18.06.0.   Reset to factory settings worked for me, but as mentioned it can not be a solution for all.

**Comment by ThetaSinner** [comment]
Seeing this as well. For a while I was able to fix it by stopping and starting Docker but that's no longer working. Just fails to start with this error every time.

Not resetting because I have containers which take over 6 hours to build on my laptop!

Diagnostic Id: 3A2EF94E-8F87-46FF-9595-E7045B1DE1D0/20180823225612

**Comment by gtardif** [comment]
Hi @adammarton @robrich @ianwdunlop @awuit9090, we have a potential fix for this issue (that we don't reproduce), could you confirm if this [build](https://download.docker.com/win/stable/19470/Docker%20for%20Windows%20Installer.exe) fixes the `No activity detected on VM, aborting` issue ?

**Comment by robrich** [comment]
@gtardif: It didn't fix it, but it did try longer before it failed.  New diagnostics id: 448D1A06-BF15-4908-834D-EB41D6F32ECC/20180824111220

**Comment by ZeroOracle** [comment]
@gtardif you supported this version can fix it ,but i must run it with admin.at the moment,i find other bug in the new version:when i open the "About Docker"and Copy (ctrl+c) the version or Channel,the Docker will be destroyed,you can look pictures.
![tim20180825084405](https://user-images.githubusercontent.com/28525278/44613211-1c8bcf80-a843-11e8-80ea-4f2d25a857c5.jpg)

**Comment by jidemobell** [comment]
had to settle for reset

**Comment by SvenLauterbach** [comment]
I have the same issue, I also updated to version 19470, but the error remains. Even the factory reset does not help

**Comment by ZeroOracle** [comment]
@SvenLauterbach you can try to run it with admin.

**Comment by SvenLauterbach** [comment]
@ZeroOracle doesn't work either. Still same issue:

No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

I uploaded the crash report: 6116B219-DD6B-454D-8BA7-49682418C5D7/20180826174708.

![image](https://user-images.githubusercontent.com/1760777/44630139-5ea73500-a959-11e8-9597-df476e9b7eb7.png)

**Comment by gtardif** [comment]
@robrich Thanks for your feedback. Unfortunately we can't get your diagnostics. Could you attach you log.txt file (located in `c:/Users/xxx/AppData/Local/Docker/` ?

**Comment by robrich** [comment]
@gtardif : Here's the [log.txt](https://github.com/docker/for-win/files/2324825/log.txt)

**Comment by liujianm** [comment]
I faced same issue https://github.com/docker/for-win/issues/2489

**Comment by neoKushan** [comment]
I just encountered the same issue on a Server 2016 VM. Docker previously worked, then after an update it stopped with the above error. Factory resetting did not help.

However, I noticed that there was no Virtual switch being created. I created a new default one and suddenly Docker sprang into life. Could be useful for someone.

**Comment by JohanSellberg** [comment]
Thank you for the information. I checked and for me it creates and sets DockerNAT (don't remember if that is the correct name) as vSwitch. I tried when it is starting up to fast switch to a newly created vSwitch that has external connection. (also resetting it after the VM restarts). But I still get the error "No activity detected on Vm, aborting as above"

**Comment by IonKiwi** [comment]
Same problem here (on windows server 2016) :(
Diagnostics ID: BFFFD5F1-9FAA-481D-AC02-4740420DFF9D/20181018132702

**Comment by ryankmcintyre** [comment]
Same issue here, although a factory reset didn't help. Diagnostic ID 420F158D-839F-4B2F-80FE-E103265D6C9A/20181018095552 uploaded.

**Comment by syedhassaanahmed** [comment]
I'm not running Docker inside a VM, yet still facing the same issue on W10 1809. Any updates on this?

**Comment by cateruels** [comment]
Same issue here, factory reset didn't help at all.
Diag ID : 202B3280-D59F-4063-9A33-8AFC3516C96E/20181025111302

Version: 18.06.1-ce-win73 (19507)
Channel: stable
Sha1: b0f14f1dac391615de29280eb46a7d65c33e9e83
Started on: 2018/10/25 10:58:48.721
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834

**Comment by embusalacchi** [comment]
Same issue - thought my VM had some incompatible software.  I did a fresh windows 10 install, all updates, installed Firefox, downloaded docker, and it hangs like everyone else.  Interestingly enough it does seem to work if you switch to a Windows containers.

**Comment by mrhoga** [comment]
Same issue with Windows Server 2016 Datacenter and Linux containers. When switching to Windows Containers Docker can start without errors.

**Comment by omerciftcibasi** [comment]
Same issue here, 
[#2872](https://github.com/docker/for-win/issues/2872)

**Comment by omerciftcibasi** [comment]
uninstall and removing docker registries on windows 
than install back docker worked for me.

**Comment by David-Renz** [comment]
Same issue:
Version: 2.0.0.0-win78 (28905)
Channel: stable
Sha1: c404a62c3fed918897334638c2dd2a368c115b76
Started on: 2018/11/19 15:38:00.892
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1803
Build: 17134
BuildLabName: 17134.1.amd64fre.rs4_release.180410-1804

**Comment by IngMoscato** [comment]
I wanted to modify data-root path in config file and with Linux Containers I can't do it, but with Windows Containers I can.
I suppose that there is a problem to pass "windows-style" paths to linux containers through windows powershell.
I noticed that because, with linux containers, I always receive a "can't find path" error with an elementary command like for example:
docker run --name mongo1 -d mongo --config C:\\data1\config\mongod.cfg

**Comment by chlumper** [comment]
Possible duplicate of #2404

**Comment by SvenLauterbach** [comment]
Just an update from my side.

On my current setup docker does work. I'm running docker inside a Hyper-V VM (Version 9.0) where both, the host and guest is running the latest Windows 10 version 1809 (17763.195). Using the edge channel version does work.

![image](https://user-images.githubusercontent.com/1760777/50574152-e2c76880-0de2-11e9-8ab0-b9da22662c73.png)

**Comment by Bidthedog** [comment]
Running Docker For Windows 2.0.0.0-win81 (29211) in a Win 10 Hyper-V VM, getting the same error:
```
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```
Excerpt from the logs (diagnostic ID = C08ADECF-548F-4CC3-8737-BD8A79BC8EF0/20190104144108):
```
[14:39:09.204][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[14:39:09.329][HyperV         ][Info   ] Attach Config ISO C:\ProgramData\DockerDesktop\tmp-d4w\config.iso
[14:39:09.954][HyperV         ][Info   ] Attach Docker ISO C:\Program Files\Docker\Docker\Resources\docker.iso
[14:39:11.594][HyperV         ][Debug  ] [start] took 00:00:02.9531216 to run
[14:39:12.665][Moby           ][Info   ] Connected
[14:41:08.669][NamedPipeClient][Error  ] Unable to send Start: No activity detected on VM, aborting
[14:41:08.669][Notifications  ][Error  ] No activity detected on VM, aborting
[14:41:08.664][NamedPipeServer][Error  ] Unable to execute Start: No activity detected on VM, aborting    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 268
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 117
[14:41:08.688][NamedPipeClient][Info   ] Sending Version()...
[14:41:08.688][NamedPipeClient][Info   ] Received response for Version
[14:41:08.688][NamedPipeClient][Info   ] Sending GatherDiagnostics(-path C:\Users\User\AppData\Local\Temp\ gather -id C08ADECF-548F-4CC3-8737-BD8A79BC8EF0/20190104144108, C:\Users\User\AppData\Local\Temp\C08ADECF-548F-4CC3-8737-BD8A79BC8EF0/20190104144108.zip)...
[14:41:08.688][NamedPipeServer][Info   ] Version()
[14:41:08.688][NamedPipeServer][Info   ] Version done in 00:00:00.
```

Steps to reproduce:

* Created a fresh Hyper-V VM from the download here: https://developer.microsoft.com/en-us/windows/downloads/virtual-machines
* Enabled nested virtualization on the host using powershell as per https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/nested-virtualization
* Install docker
* Start docker

Have tried all manner of settings in host's BIOS, and the VM docker and Hyper-V installations. I've also tried a clean reinstall of both docker and Hyper-V in the VM. I've received plenty of other errors but I've worked through them to this point.

FYI Docker runs fine on the host machine, but that's one of the things I'm hoping to offload to my development VM.

**Comment by embusalacchi** [comment]
Yeah, it's unable to figure out a timer setting (if memory serves be correctly, I've given up on nested docker unfortunately).  If you start the VM directly and watch the boot it hangs.

**Comment by sschaerli** [comment]
Running Docker For Windows 2.0.0.0-win81 (29211) in a Win 10 (Version 1709) VMware VM, getting the same error:
```

[12:39:29.592][NamedPipeClient][Error  ] Unable to send Restart: No activity detected on VM, aborting
[12:39:29.592][Notifications  ][Error  ] No activity detected on VM, aborting
[12:39:29.589][NamedPipeServer][Error  ] Unable to execute Restart: No activity detected on VM, aborting    bei Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:Zeile 268.
   bei Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:Zeile 189.
   bei Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 48.
   bei Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 180.

```

**Comment by walked** [comment]
> Running Docker For Windows 2.0.0.0-win82 (29268) in a Win 10 (Version 1709) VMware VM, getting the same error:
> 
> ```
> 
> [12:39:29.592][NamedPipeClient][Error  ] Unable to send Restart: No activity detected on VM, aborting
> [12:39:29.592][Notifications  ][Error  ] No activity detected on VM, aborting
> [12:39:29.589][NamedPipeServer][Error  ] Unable to execute Restart: No activity detected on VM, aborting    bei Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:Zeile 268.
>    bei Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:Zeile 189.
>    bei Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 48.
>    bei Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:Zeile 180.
> ```

Same exact here inside a VMWare VM. Tried factory reset to no success. Unfortuante as I require VMWare on my workstation; so I figured running in VMWare is the next best solution; but no dice. :(

**Comment by vitalybibikov** [comment]
After 2 days of trying
0. Disable H-V and Containers in Features
1. Restart.
2. Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All  from elevated PS
3. Enable Containers.
4. Services => Start docker not under local account => admin will do
5. Restart
6. Profit

**Comment by alex-dylda** [comment]
Same issue with Win 10 Enterprise 1809 and docker 2.0.03 (31259) 
@vitalybibikov , tried your solution but it didn't help.
```
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass28_0.<SwitchDaemon>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 305
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

**Comment by OrangutanGaming** [comment]
Windows 10 Pro 1809 Build 17763.437
Docker Desktop Community 2.0.0.3 (31259) Build 8858db3
```
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59```

**Comment by alex-dylda** [comment]
@OrangutanGaming , of course I tried to restart, then tried to factory reset, than tried to reinstall, than tried to go through steps that @vitalybibikov provided.
But still no success.

**Comment by OrangutanGaming** [comment]
Every time you start you get that error? I wasn't really providing a fix, I just wanted to provide my log incase docker want more info

**Comment by alex-dylda** [comment]
After restarting it looks like docker work. But I see that it doesn't apply any changes that I make. 
For example I defined proxy and docker is restarting successfully, but I see that no proxy is used. So docker still can't do anything because we are working under proxy.
P.S. If i switch to windows containers and define proxy it works correct.

**Comment by alex-dylda** [comment]
And If I quit from docker and open it again it will open in Windows mode.

**Comment by sschaerli** [comment]
I fixed it manually like the following steps and I don't use Docker Desktop anymore. This helped me ([see also](https://stackoverflow.com/questions/36885985/cannot-start-docker-after-installation-on-windows)).

- Create a virtual switch, refer to this [article](https://blogs.technet.microsoft.com/canitpro/2014/03/10/step-by-step-enabling-hyper-v-for-use-on-windows-8-1/ ) on how to do that
- Create a docker machine using that network switch and hyper-V driver.

`docker-machine create -d hyperv --hyperv-virtual-switch "name of the virtual switch created above" default`

**Comment by RedReaperKun** [comment]
@sschaerli Sir, you saved my day =)

**Comment by ShannonMcCoy** [comment]
OK Found this fix on another site, tried it and it worked. Everything else failed. Wait til docker fails to the error. Hit the close button on the error message and go to Docker Settings. On the Advanced tab change the processors to 1. I had 4 in there. When you hit apply it restarts docker and runs like a top. I even pushed the processors back up to  4 and it keeps restarting and running with each change. Screwy but it worked for me after 5 hours of trying everything else. Good Luck.

**Comment by joshua-barber** [comment]
Ran into this issue starting about a week ago.

Crash report submitted: 6B9C68D0-5F1E-40D8-BDED-A8A6B0C71182/20190618211019
Content:
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by dspathak** [comment]
> Win 1803, latest docker, running in VM, was not working for Linux Containers.
> 
> After 2 days of trying:
> 
> 1. Disable H-V and Containers in Features
> 2. Restart.
> 3. Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All  from elevated PS
> 4. Enable Containers.
> 5. Services => Start docker not under local account => admin will do
> 6. Restart
> 7. Profit

This worked for me. First disabling and then re-enabling hyper-V and then reinstalling docker for desktop.
