### ISSUE TITLE
Running Docker on Windows 10 after installation fails.

### ISSUE THREAD

**Issue by david-intersys** [docker/for-win#2271]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: C4A7E27D-0B57-4E0C-90C8-F0710F642F59/20180725164230

### Expected behavior
Start Docker for first time. Ask to enable Hyper-V and Container features. Enable features
### Actual behavior
Get a error message
### Information
Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.WPF.BackendClient.InstallFeatures(Feature[] features) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 111
   at Docker.Notifications.BackendInstallFeatureExceptionReplier.<>c__DisplayClass10_0.<AskToUser>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Notifications\BackendInstallFeatureExceptionReplier.cs:line 103
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

 - Windows Version: 10 Pro
 - Docker for Windows Version: 18.06.0-ce-win70 (19075)

### Steps to reproduce the behavior
  1. Install Docker for windows
  2. After default instalation following the wizard, a new window is displayed asking you to enable Hyper-V and Container features
  3. Error is shown.

**Comment by ebriney** [comment]
Hi @david-intersys, this is a known issue due to a security fix, we did an hotfix yesterday, either you install the new version, either you can install containers feature manually. Sorry for the convenience.
