### ISSUE TITLE
Error after installation (pipe failure)

### ISSUE THREAD

**Issue by vollpe** [docker/for-win#2277]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CA2D72C7-9539-4396-B619-FE9DAA791522/20180726091045

### Expected behavior
Docker will be up and running
### Actual behavior
Cannot start work with Docker
### Information

  - Windows Version: OS: Windows 10 Pro, Id: 1803, Build: 17134
  - Docker for Windows Version: 18.06.0-ce-win70

### Steps to reproduce the behavior

  1. Install 
  2. Re-login to Windows after installation
  3. See error message

**Comment by rkamath3** [comment]
I confirm this error `Binary stream '0' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.WPF.BackendClient.InstallFeatures(Feature[] features) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 111
   at Docker.Notifications.BackendInstallFeatureExceptionReplier.<>c__DisplayClass10_0.<AskToUser>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Notifications\BackendInstallFeatureExceptionReplier.cs:line 103
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59`
