### ISSUE TITLE
Update: Access to the path 'Docker for windows Installer.exe' is denied.

### ISSUE THREAD

**Issue by kenorb** [docker/for-win#2291]
I had popup to upgrade Docker for Windows to 18.06.0-ce-win72 (19098), I've accepted. After downloading, the installation failed due to errors.

----

  - [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics? No, because installer stopped the Docker service.

### Actual behavior

```
Access to the path 'Docker for windows Installer.exe' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at LightweightInstaller.UninstallWorkflow.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<PerformUninstall>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
```
### Information

  - Windows Version: Windows 10 (1703)
  - Docker for Windows Version: 18.06.0-ce-win72

### Steps to reproduce the behavior

  1. Run installer for 18.06.0-ce-win72
  2. Wait till it downloads the package.
  3. It should fail.

**Comment by kenorb** [comment]
I've run update the second time, it got stuck on_Removing files..._ for over 20 minutes.

![image](https://user-images.githubusercontent.com/266306/43278902-45f8c89c-9104-11e8-8c50-f685ebea3335.png)

**Comment by kenorb** [comment]
Second time the installer finished the installation.

**Comment by luvvishu23** [comment]
I had the same issue found out that update notification window was open and docker installer was not able to delete the files. Close all docker related windows and retry

**Comment by AshishShukla16** [comment]
I have had same issue while updating the docker version on Windows 10
![docker error](https://user-images.githubusercontent.com/6327239/51434276-129bba80-1c83-11e9-862c-549b278957b4.JPG)
