### ISSUE TITLE
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled

### ISSUE THREAD

**Issue by ozitraveller** [docker/for-win#2296]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by ozitraveller** [comment]
[14:47:53.748][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled

    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 183
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 117
[14:47:53.851][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled


[14:47:53.853][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled


[14:47:53.884][NamedPipeClient][Info   ] Sending Version()...
[14:47:53.885][NamedPipeClient][Info   ] Received response for Version
[14:47:53.885][NamedPipeClient][Info   ] Sending GatherDiagnostics(-path C:\Users\ozi\AppData\Local\Temp\ gather -id F62E5D6C-B64F-4482-B383-86A1C4C734F5/20180727144753, C:\Users\ozi\AppData\Local\Temp\F62E5D6C-B64F-4482-B383-86A1C4C734F5/20180727144753.zip)...
[14:47:53.885][NamedPipeServer][Info   ] Version()
[14:47:53.885][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:47:53.885][NamedPipeServer][Info   ] GatherDiagnostics(-path C:\Users\ozi\AppData\Local\Temp\ gather -id F62E5D6C-B64F-4482-B383-86A1C4C734F5/20180727144753, C:\Users\gillsi\AppData\Local\Temp\F62E5D6C-B64F-4482-B383
[log.txt](https://github.com/docker/for-win/files/2234483/log.txt)
-86A1C4C734F5/20180727144753.zip)
