### ISSUE TITLE
Docker Daemon gets timed out

### ISSUE THREAD

**Issue by bhavya1212** [docker/for-win#2298]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 2338A418-048E-42CA-A7EE-99394AB42504/20180727113051

### Expected behavior
Normal Working of Docker
### Actual behavior
Timed out while waiting for Docker daemon to be ready
   at Docker.Backend.Processes.WindowsDockerDaemon.WaitForDaemonToBeReady() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 147
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 222
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 96
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180
### Information

  - Windows Version:
  - Docker for Windows Version: latest

### Steps to reproduce the behavior
<!--
A reproducible case, Dockerfiles FTW.
-

**Comment by dazinator** [comment]
same as #2302

**Comment by dazinator** [comment]
This has completely halted by ability to do any docker work on windows. How do I roll back to the previous stable version that worked - is the old installer still available somewhere?

**Comment by dazinator** [comment]
I have also tried `Edge` channel - same error.

**Comment by vikygeek** [comment]
@dazinator The same problem exits even after i rolled back to Version 18.03.1-ce-win65. I couldn't start docker now :( . My whole work totally stopped :/

**Comment by vikygeek** [comment]
Try to roll back the Windows update. That solved this issue for me..

**Comment by bhavya1212** [comment]
I tried each and every thing available , tried different versions of docker , tried enabling/disabling Hyper-V but at the end I had to reinstall Windows and that solved the issue for me
