### ISSUE TITLE
Docker cannot start. Uninstall & Reinstall does not help

### ISSUE THREAD

**Issue by geedsen** [docker/for-win#2311]
### Expected behavior

Dockers starts 

### Actual behavior

It comes up with the Error dialog
with this information:

Timed out while waiting for Docker daemon to be ready
   at Docker.Backend.Processes.WindowsDockerDaemon.WaitForDaemonToBeReady() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 147
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 222
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 96
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180

### Information

  - Windows Version: 10 Pro build 17134
  - Docker for Windows Version:

This problem was intermittent, and also sometimes came with a different error.

Error response from daemon: open \.\pipe\docker_engine_windows: The system cannot find the file specified.
at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DockerDaemonChecker.cs:line 63
at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 144
In the log:
Failed to start COMProvider while calling CheckWorkstationCache.
[07:49:59.503][NamedPipeClient][Error ] Unable to send Start: Error response from daemon: open \.\pipe\docker_engine_windows: The system cannot find the file specified.

In both cases you will find this error in the eventlog:

Error occurred when creating network could not find plugin internal in v1 plugin registry: plugin not found

This link provides another user having the same problem:
https://github.com/Microsoft/DockerTools/issues/126

**Comment by a2glukhov** [comment]
Exact the same problem.

**Comment by 165plo** [comment]
I was able to get passed this issue by: 

1. Uninstalling Docker
2. Using CCleaner to clean the registry 
3. I uninstalled all VM software (I had VMWare, VBox, and Hyper V
4. I cleaned up all the unused network interfaces (I had a lot)
5. Reinstalled Docker (Let docker reinstall hyper v)

Not sure if it made a difference but I had also done a reset to factory settings prior to this.

**Comment by danwkennedy** [comment]
Had this error and uploaded the diagnostics with ID:
54320DE0-EE03-405F-A658-0FE330E1FDED/20180905093045
