### ISSUE TITLE
Docker fails to start. Uninstall and reinstall does not resolve this issue

### ISSUE THREAD

**Issue by moonsw1** [docker/for-win#2314]
### Expected behavior
Docker should be able to start
### Actual behavior
Docker fails to start
### Information
The exact error messages are:

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 4FE7F7EA-18A5-433F-856B-BEC9660485A0)

'MobyLinuxVM' Synthetic Ethernet Port (Instance ID 67CF0F66-3F05-4534-AED8-1BE8E1109051): Failed to Power on with Error 'Attempt to access invalid address.' (0x800701E7). (Virtual machine ID 4FE7F7EA-18A5-433F-856B-BEC9660485A0)

'MobyLinuxVM' No available MAC address for "Network Adapter".
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. Start docker

**Comment by geedsen** [comment]
Go back to an older version:
Install Chocolatey if you don't have it yet ( https://chocolatey.org/) and then in an elevated powershell prompt run "Choco list docker-for-windows --all" to see all versions available and run for example "Choco install docker-for-windows -version 18.03.1.17513" to install the mentioned version, make sure you uninstall the version you don't want first.

**Comment by moonsw1** [comment]
Thank you for your response. However, uninstalling the version I have and installing the mentioned version with chocolatey still does not fix the problem.
