### ISSUE TITLE
Unable to reinstall docker 

### ISSUE THREAD

**Issue by PunnooseJoseph** [docker/for-win#2348]
DOcker for Windows 18.06.0-ce-win72

Installation failed

The process cannot access the file 'C:\Program Files\Docker\Docker\resources\docker-for-win.iso' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at LightweightInstaller.UnpackArtifactsStep.<DoAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()

Information
Windows Version:10
Docker for Windows Version:18.06.0-ce-win72

**Comment by PunnooseJoseph** [comment]
Information
Windows Version:10
Docker for Windows Version:18.06.0-ce-win72

**Comment by ntaranov** [comment]
Same here with 18.06.1-ce-win73

**Comment by boev** [comment]
Same for 18.06.1-ce-win73 on windows version: Windows 10 Enterprise 64-bit (10.0, Build 15063)

**Comment by Nordle** [comment]
Same for 2.0.0.2-ce on windows version: Windows 10 Enterprise 64-bit

**Comment by lidiam** [comment]
Same here for Docker 2.0.0.2 on windows 10 Pro 64 bit.

**Comment by HelioVaGator** [comment]
Same here while updating to Docker 2.0.0.2 on windows 10 Ent 64 bit. Now even installing the older version gives the same error.

**Comment by mat007** [comment]
Can you open the «Hyper-V Manager», remove the Docker Desktop VM and try again the installer?

The exact name of the VM can vary a bit depending on your version of Docker Desktop but it should look like:
![image](https://user-images.githubusercontent.com/2386884/69165868-8c464400-0af2-11ea-8f10-1cf20c390489.png)

**Comment by vrana116** [comment]
fixed my issue. thanks

**Comment by konstantinblaesi** [comment]
Stopping the VM was enough for me

**Comment by micheleissa** [comment]
> Can you open the «Hyper-V Manager», remove the Docker Desktop VM and try again the installer?
> 
> The exact name of the VM can vary a bit depending on your version of Docker Desktop but it should look like:
> ![image](https://user-images.githubusercontent.com/2386884/69165868-8c464400-0af2-11ea-8f10-1cf20c390489.png)

That got it working for me, thanks a bunch.
