### ISSUE TITLE
Docker for Windows fails to start

### ISSUE THREAD

**Issue by sschimmel** [docker/for-win#2349]
- [ X ] I have tried with the latest version of my channel (Stable)
  - [ X ] I have uploaded Diagnostics
  - Diagnostics ID: 2B3C6A2E-9D8C-4317-972F-2353BFC98970/20180801092345

### Expected behavior

Docker for windows starts

### Actual behavior

Docker for Windows crashes immediately on start.

### Information

Docker for Windows is not started on my system and the docker service is not running. I go to the start  menu and start docker for Windows. A dialog appears stating the docker service is not running and asking me if I want to start it. I click start.

An elevated access dialog appears and I grant the elevated access. A command prompt window appears and disappears immediately. After that the error dialog below appears. The docker icon in the systray is red.

I am currently unable to start Docker for Windows. Any attempt to start results in the same crash.

The full error from the dialog:
```
Unable to start Docker for Windows service: 2
   at Docker.WPF.BackendClient.CheckService() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 351
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 157
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

  - Windows Version: Windows 10
  - Docker for Windows Version: 18.06.0-ce-win72 (19098) (Stable)

![image](https://user-images.githubusercontent.com/459456/43507397-4dd40122-956d-11e8-8be6-3e64b427bfa7.png)

### Steps to reproduce the behavior

Start Docker for Windows.

**Comment by sschimmel** [comment]
A downgrade to the previous version resolved the issue. Docker is running fine with version: 18.03.1-ce-win65 (17513)

Seeing I'm not the first nor only one who has reported this issue over the last several days I would have expected that the update to 18.06 had been revoked. Instead I received a prompt to upgrade to 18.06 when I started Docker after the downgrade. 

![image](https://user-images.githubusercontent.com/459456/43507947-cd860c98-956e-11e8-90ec-cbb8f61dac1e.png)

**Comment by starwarsfan** [comment]
Running into the same issue. Any news or a workaround available?

`Unable to start Docker Desktops service: 2
   at Docker.WPF.BackendClient.CheckService(String action) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 305
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 167
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59`

The path "C:\workspaces\" is not existing on my machine. Where does it come from?

**Comment by sahinyanlik** [comment]
I solved this problem by removing %APPDATA%/Docker folder and start docker for windows with admin rights.

**Comment by feng-t** [comment]
我也出现了这个问题，不过我重新安装就没问题了

**Comment by failamir** [comment]
folder C:\workspace is the hidden folder

**Comment by AurelioOliver** [comment]
Passei por esse problema e facilmente foi resolvido quando percebi que dois serviços estavam parados, são eles: 

Docker Desktop Service
Docker Enkgine
