### ISSUE TITLE
docker for windows fails on start 

### ISSUE THREAD

**Issue by john-rene-madsen** [docker/for-win#2351]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4A9B12EB-7B30-4AEE-9A69-B949CDB39FC8/20180801093149

### Expected behavior
docker for windows should start the docker environment
### Actual behavior
  the VM MobyLinuxVM is startet and running in the Hyper-V manager
 but docker for windows reports "No activity detected on VM, aborting"
### Information

  - Windows Version:
OS-navn	Microsoft Windows 10 Enterprise
Version	10.0.17134 Build 17134
  - Docker for Windows Version:
Version: 18.06.0-ce-win72 (19098)
Channel: stable
Sha1: 5513f91045dac2b8d51420014ee9176d24791d7d
Started on: 2018/08/01 09:28:15.212

### Steps to reproduce the behavior

  1. start Docker for Windows on a rebooted machine

Is it possible to reset setting to new MobyLinuxVM image and the import/transfer the docker images from the old VM image ?

**Comment by ucavalcante** [comment]
im have same problem when i turn off kubernetes docker comes up again in reboot.

**Comment by rock-it-rob** [comment]
I'm experiencing the same issue and I don't have Kubernetes enabled.

**Comment by jamieshiz** [comment]
I have "Quit Docker" and relaunched it 3 times in a row and gotten the same error.

>No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59


Docker for Windows
Version 18.06.0-ce-win72 (19098)
Channel: stable
5513f91

Docker Compose
Version 1.22.0, build f46880fe

Kubernetes: Off

**Comment by john-rene-madsen** [comment]
I also have  Kubernetes: Off
It is a plain Docker for Windows installation just with a lot of images
that I will hate to loose. (I only have a backup of the Moby VM image)
Is there a way to ssh or the like into the MobyLinuxVM and extract the
images ?

Den tor. 2. aug. 2018 kl. 18.42 skrev Jamie Schiesel <
notifications@github.com>:

**Comment by chrisofire** [comment]
facing the same anyone resolved?

**Comment by robrich** [comment]
I'm having similar issues as discussed on #2214. I'm blocked.

**Comment by gtardif** [comment]
Hi @john-rene-madsen, @jamieshiz , we have a potential fix for this issue (that we don't reproduce), could you confirm if this [build](https://download.docker.com/win/stable/19470/Docker%20for%20Windows%20Installer.exe) fixes the No activity detected on VM, aborting issue ?

**Comment by robertgoljat** [comment]
gtardif 

> could you confirm if this build fixes the No activity detected on VM, aborting issue ?

No, it's not working!

![image](https://user-images.githubusercontent.com/14954136/44585666-5e6a3680-a7ad-11e8-985e-7aa6b16c2b3e.png)

**Comment by robertgoljat** [comment]
Hi Guillaume,

Check the attached diagnostics zip generated by Docker.


>> Thx to confirm this fixes the linux startup sequence

Actually, I have never had any problems with Linux startup sequence (it always worked). Switching to Windows containers causes problems…


Lep pozdrav / Best regards,

                             Robert Goljat


[smenstorsys_signature_2]

**Comment by john-rene-madsen** [comment]
The latest version fixed my problem

**Comment by syedhassaanahmed** [comment]
Same issue on Stable 18.06.1-ce-win73 (19507)
Diagnostic ID: 9E546F03-92E7-4328-A05E-C51EAAD30B9A/20181024022318

**Comment by leejosh** [comment]
i too am having the same issue. 
fresh install of server 2016.
fresh install of docker 18.06.1-ce

No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass18_0.<ResetToDefault>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 137
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
