### ISSUE TITLE
Timeout when switching to windows container engine

### ISSUE THREAD

**Issue by Hansa064** [docker/for-win#2363]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 2D8B5AE2-8904-44B0-BB77-446BF1363810/20180803110729

### Expected behavior
If I click on the "Switch to Windows Containers" Button, I'm able to switch between Linux contains and windows contains without problems.

### Actual behavior
The Docker-Daemon is trying to restart and after a long time I receive the following error:
`Timed out while waiting for Docker daemon to be ready
   at Docker.Backend.Processes.WindowsDockerDaemon.WaitForDaemonToBeReady() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 147
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 222
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 96
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180`

### Information

  - Windows Version:
  - Docker for Windows Version:
The issue occurrs independent of a Docker Version, and does not occurr every time. If I restart my Computer, the problem will most likely go away (for some time). But if the error occurrs, it is reproducable as long as the system is running.

### Steps to reproduce the behavior
Not reliable reproducable, but this is, what I'm doing:

1. Right click on the Docker-Daemon try icon
2. Select "Switch to Windows containers..."
3. Wait

**Comment by liguori** [comment]
Are there some news about this error? I got the same message as well.

**Comment by ericcox** [comment]
Workaround (for dev machines, obviously): uninstall Docker, reboot (important!), then reinstall, selecting Windows containers during install.

**Comment by liguori** [comment]
Hello @ericcox, the solution you gave to me it worked very good. I hope they are going to fix this "bug" soon. Thank you :)
