### ISSUE TITLE
Crash on start for docker windows latest edge

### ISSUE THREAD

**Issue by williamzhao87** [docker/for-win#2388]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BF269171-BD17-4A33-9EF7-31D9FC8838BC/20180807154926

### Expected behavior
Docker to start on Windows

### Actual behavior
Docker fails to start with:
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass18_0.<ResetToDefault>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 137
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information

  - Windows Version: Windows 10 Enterprise 10.0.15063 Build 15063
  - Docker for Windows Version: Version 18.06.0-ce-win71 (19101)
Channel: edge
1563e1a

### Steps to reproduce the behavior

  1. Start docker
This worked fine before updating to latest version.

**Comment by wvanvlaenderen** [comment]
I am having the same problem since the update to Version 18.06.0. Tried both the stable and edge releases. Downgrading to 18.03 does not solve the issue. Also tried to re-enable Hyper-V but no success.

**Comment by williamzhao87** [comment]
Latest Windows update seems to have fixed this for me.

**Comment by ilevina** [comment]
Having same issue ;(  tried to un-install Docker, then disable Hyper-V and Containers, after rebooting system enable Hyper-V , Containers and restart. Then trying to install Docker for Windows , still seeing same problem
