### ISSUE TITLE
Can't execute anything on shared folder (missing executable bit and can't change it)

### ISSUE THREAD

**Issue by withinboredom** [docker/for-win#243]
### Expected behavior
```
docker run -v C:\Users\withi\code\wp-calypso\bin\pre-push:/pre-push ubuntu:16.04 /pre-push
 // output
```

### Actual behavior
```
docker run -v C:\Users\withi\code\wp-calypso\bin\pre-push:/pre-push ubuntu:16.04 /pre-push
panic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]
        panic: standard_init_linux.go:175: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x88f8a0, 0xc82013bd50)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8201072e8)
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x88f8a0, 0xc82013bd50)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc820106bf8, 0xc82001a070, 0xc820106d08)
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820059310, 0x7fa0f642a5c0, 0xc82013bd50)
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc820076a00, 0x0, 0x0)
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x7f45a0, 0x9a4d88, 0x13, 0x8ebac8, 0x4, 0xc820107268, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x7f45a0, 0x9a4d88, 0x13, 0xc820107268, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x7f45a0, 0x9a4d88, 0xc820076a00, 0x0, 0x0)
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x8ee970, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x984240, 0x51, 0x0, ...)
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001800, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/main.go:137 +0xe24
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
`C0934A31-EC38-434B-A3A9-9360FBB7B85E/2016-11-20_09-50-56`
  - a reproducible case if this is a bug, Dockerfiles FTW
Try running any bash script
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Win 10 (build 14393.447)
Docker beta 1.12.3-beta30.1

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rneugeba** [comment]
@withinboredom thanks for your report. There is a common issue with line endings being different between windows and Linux. I can reproduce the error you are seeing with a small test shell script:
```
PS C:\Users\rneugeba\foo> notepad hello.sh
PS C:\Users\rneugeba\foo> cat .\hello.sh
#!/bin/sh
echo "Hello"
PS C:\Users\rneugeba\foo> docker run --rm -v C:\Users\rneugeba\foo:/foo alpine /foo/hello.sh
panic: standard_init_linux.go:175: exec user process caused "no such file or directory" [recovered]
        panic: standard_init_linux.go:175: exec user process caused "no such file or directory"

goroutine 1 [running, locked to thread]:
panic(0x88f8a0, 0xc82012d650)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8200f92e8)
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0
x38e
panic(0x88f8a0, 0xc82012d650)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200f8bf8, 0xc82001a098, 0xc820
0f8d08)
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libc
ontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820059450, 0x7f55dec725c0, 0xc82012d6
50)
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libc
ontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc820076a00, 0x0, 0x0)
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x7f45a0, 0x9a4d88, 0x13, 0x8ebac8, 0x4, 0xc8200f9268, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x7f45a0, 0x9a4d88, 0x13, 0xc8200f9268, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x7f45a0, 0x9a4d88, 0xc820076a00, 0x0, 0x0)
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0
x2ee
github.com/urfave/cli.Command.Run(0x8ee970, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x984240, 0x51, 0x0, ...)
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:19
1 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001800, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0
xaa4
main.main()
        /tmp/tmp.n151sEscRu/src/github.com/opencontainers/runc/main.go:137 +0xe24
```
If I create the file with Unix style line ending it works:
```
PS C:\Users\rneugeba\foo> cat .\hello.sh
#!/bin/sh
echo "Hello"
PS C:\Users\rneugeba\foo> docker run --rm -v C:\Users\rneugeba\foo:/foo alpine /foo/hello.sh
Hello
```
This is also documented in the troubleshoot section:
https://docs.docker.com/docker-for-windows/troubleshoot/#avoid-unexpected-syntax-errors-use-unix-style-line-endings-for-files-in-containers

Could you double check the line endings on your files?

**Comment by withinboredom** [comment]
👊 git ... something set `autocrlf` back to `true` from `input`! I knew I wasn't crazy when it was working the other day! The only thing I could think of was that I updated docker...
