### ISSUE TITLE
Docker for Windows 10 Pro 1709, MobyLinuxVM failed to start

### ISSUE THREAD

**Issue by rakeshpandey19** [docker/for-win#2454]
I have installed docker on Window 10 Pro 1709, I am getting below error, this seems to known issues, I tried the solutions provided on docker forums, but it did not help. Below is error I am getting
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 46688EF4-7329-4982-87B9-94B677F045B1)
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

  - [x] I have tried with the latest version of my channel (Stable Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 9AC3A831-B8A3-4419-8B44-B5833579B849/20180818114444

### Expected behavior
After install docker, MobyLinuxVM should be running

### Actual behavior
-[x] - During docker install when i opt for windows container, it works, but i see the same above error mentioned about MobyLinuxVM when i try to switch to linux container.

### Information

  - Windows Version: Windows 10 Pro 1709
  - Docker for Windows Version:
PS C:\WINDOWS\system32> docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
PS C:\WINDOWS\system32>

### Steps to reproduce the behavior

  1. ...Download and Run 'Docker for Windows Installer.exe', do default installation,  I mean don't check for Windows container. I will get installed successfully.
  2. ...Launch Docker for Windows App, You will get the same error
  3. If you see Hyper-V Manager, there is MobyLinuxVM, it tries to start, but fails, state showing off, screenshot 
![image](https://user-images.githubusercontent.com/14543276/44296533-78ec6d80-a2de-11e8-8a8c-90c08ba9f181.png)
[20180818113234.zip](https://github.com/docker/for-win/files/2299200/20180818113234.zip)

**Comment by rakeshpandey19** [comment]
++ During docker for windows install if you select option -> Windows container, then there seems not to be an issue, but if you try to switch to Linux Containers -> same error
PS C:\WINDOWS\system32> docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:05:28 2018
 OS/Arch:           windows/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.24)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:23:19 2018
  OS/Arch:          windows/amd64
  Experimental:     false
#####
--> Error i get when i switch to Linux Containers -
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID EED71E7D-E211-44D2-B6C2-A835E13B0155)
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass25_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 275
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by boboyada** [comment]
me too

**Comment by swatishrivastava** [comment]
Please answer someone on above issue. I am also facing same issue.
