### ISSUE TITLE
Docker for Windows service is not running

### ISSUE THREAD

**Issue by ekalaya** [docker/for-win#2459]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 57A53F0F-EF86-4DD1-853F-62D8D8C788BF/20180820130352

### Information

  - Windows Version: 10
  - Docker for Windows Version: 18.06.0-ce-win72 (19098)

###  Docker for Windows service is not running

   at Docker.WPF.BackendClient.CheckService() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 351
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 157
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by gtardif** [comment]
Hi @ekalaya, unfortunately we can't access the mentioned diagnostics for some reason. Could you provide your `log.txt` file that should be in your `c:/Users/xxx/AppData/Local/Docker` folder ? That might help us investigate why the Docker for Windows service is not started.

**Comment by gtardif** [comment]
@ekalaya Can you try if this [build](https://download.docker.com/win/stable/19470/Docker%20for%20Windows%20Installer.exe) is solving your problem ? (and upload diagnostics if not). Thanks for your help
