### ISSUE TITLE
Docker failed to start

### ISSUE THREAD

**Issue by deanskibum** [docker/for-win#2464]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID:
6740485B-E9C6-44FE-AE48-2F9700243AED/20180820072119
### Expected behavior
Docker to start
### Actual behavior
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID ECE93DEA-EE3F-4EA0-A97D-73DAD04D80EC)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID ECE93DEA-EE3F-4EA0-A97D-73DAD04D80EC).
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
### Information

[log.txt](https://github.com/docker/for-win/files/2302731/log.txt)

**Comment by gtardif** [comment]
This issue tracker is for the Docker for Windows application, which runs on Windows 10. 
From the attached logs, you're running Windows Server 2016 Datacenter. 
To get help with Docker on Windows Server please see http://success.docker.com/article/where-to-get-help-with-windows.
Thanks
