### ISSUE TITLE
Can't Start Docker.

### ISSUE THREAD

**Issue by UdayaBhandaru** [docker/for-win#2493]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker has to start and running
### Actual behavior
Docker not starting
failing with the below error

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

The log says

Version: 18.06.0-ce-win72 (19098)
Channel: stable
Sha1: 5513f91045dac2b8d51420014ee9176d24791d7d
Started on: 2018/08/27 11:16:33.173
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1803
Build: 17134
BuildLabName: 17134.1.amd64fre.rs4_release.180410-1804
File: C:\Users\ubhandaru\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:16:33.266][GUI            ][Info   ] Starting...
[11:16:34.650][Tracking       ][Info   ] Crash report and usage statistics are enabled
[11:16:34.650][SegmentApi     ][Info   ] Usage statistic: appLaunched
[11:16:34.696][SegmentApi     ][Info   ] Usage statistic: heartbeat
[11:16:34.696][SegmentApi     ][Info   ] Usage statistic: Identify
[11:16:36.780][Notifications  ][Info   ] Docker is starting...
[11:16:36.826][NamedPipeClient][Info   ] Sending Version()...
[11:16:36.842][NamedPipeClient][Info   ] Received response for Version
[11:16:36.842][NamedPipeClient][Info   ] Sending Start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions)...
[11:16:36.842][NamedPipeServer][Info   ] Version done in 00:00:00.
[11:16:36.842][NamedPipeServer][Info   ] Start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions)
[11:16:36.842][PowerMode      ][Info   ] Stop
[11:16:36.842][HyperV         ][Info   ] Stop
[11:16:36.842][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:16:36.857][HyperV         ][Info   ] Script started at 11:16:36.857
[11:16:36.873][HyperV         ][Info   ] Module loaded at 11:16:36.873
[11:16:37.584][NPS            ][Info   ] NPS user ceated on: 8/23/2018 11:06:12 PM -07:00, last survey:  1/1/0001 12:00:00 AM +00:00
[11:16:37.899][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:16:37.899][HyperV         ][Debug  ] [stop] took 00:00:01.0570866 to run
[11:16:37.899][OptimizeDisk   ][Info   ] Optimize
[11:16:37.899][PowerShell     ][Info   ] Run script...
[11:16:38.934][Moby           ][Info   ] Stop
[11:16:38.944][HyperVGuids    ][Info   ] Installing GUIDs...
[11:16:38.944][HyperV         ][Info   ] Create
[11:16:38.944][PowerMode      ][Info   ] Start
[11:16:38.944][Firewall       ][Info   ] Removing all existing rules...
[11:16:38.944][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64424509440 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[11:16:38.946][HyperVGuids    ][Info   ] GUIDs installed
[11:16:38.957][HyperV         ][Info   ] Script started at 11:16:38.957
[11:16:38.977][HyperV         ][Info   ] Module loaded at 11:16:38.977
[11:16:38.983][Firewall       ][Info   ] All existing rules are removed.
[11:16:38.983][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[11:16:38.998][Firewall       ][Info   ] Opening ports for SMB...
[11:16:39.004][Firewall       ][Info   ] Ports are opened
[11:16:41.044][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:17:18.540][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394. Let's retry
[11:17:18.603][HyperV         ][Info   ] Hyper-V is running
[11:17:18.603][PowerMode      ][Info   ] Stop
[11:17:18.603][HyperV         ][Info   ] Stop
[11:17:18.603][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:17:18.603][HyperV         ][Info   ] Script started at 11:17:18.603
[11:17:18.618][HyperV         ][Info   ] Module loaded at 11:17:18.618
[11:17:19.656][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:17:19.656][HyperV         ][Debug  ] [stop] took 00:00:01.0537370 to run
[11:17:19.656][OptimizeDisk   ][Info   ] Optimize
[11:17:19.656][PowerShell     ][Info   ] Run script...
[11:17:20.697][Moby           ][Info   ] Stop
[11:17:20.712][HyperV         ][Info   ] Destroy
[11:17:20.712][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[11:17:20.728][HyperV         ][Info   ] Script started at 11:17:20.728
[11:17:20.743][HyperV         ][Info   ] Module loaded at 11:17:20.743
[11:17:21.748][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:17:21.748][HyperV         ][Info   ] Destroying Switch DockerNAT...
[11:17:23.818][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[11:17:24.853][HyperV         ][Debug  ] [destroy] took 00:00:04.1412900 to run
[11:17:24.853][Firewall       ][Info   ] Closing ports...
[11:17:24.853][Firewall       ][Info   ] Removing all existing rules...
[11:17:24.947][Firewall       ][Info   ] All existing rules are removed.
[11:17:24.947][Firewall       ][Info   ] Ports are closed
[11:17:24.947][HyperVGuids    ][Info   ] Removing GUIDs...
[11:17:24.947][HyperVGuids    ][Info   ] GUIDs removed
[11:17:24.947][HyperV         ][Info   ] Create
[11:17:24.947][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64424509440 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[11:17:24.947][HyperV         ][Info   ] Script started at 11:17:24.947
[11:17:24.963][HyperV         ][Info   ] Module loaded at 11:17:24.963
[11:17:27.010][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:18:03.479][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 183
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 117
[11:18:03.526][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
[11:18:03.526][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394

**Comment by Get-Kraken** [comment]
Same here: fresh install on Windows 10 with latest updates.

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 49F7C6A7-6E57-4980-915F-11B0A6F5EB5F)
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
