### ISSUE TITLE
Docker fail to run in windows 10 pro

### ISSUE THREAD

**Issue by wei-zhou-gea** [docker/for-win#2560]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: windows 10 pro
  - Docker for Windows Version: 

### Steps to reproduce the behavior

  1. Install either edge or stable version
  2. Reboot computer
  3. Load docker program, it will run, for about 6 minutes   
  4. Then the diagnostics windows will pop up and show the error message.  I will post the error msg below.
  5. If switch to windows container, it appears to load fine within 10 seconds.
The uploaded DIAGNOSTIC ID:
E2594A26-1758-424F-AABE-195F073FAD5A/20180906113048

**Comment by wei-zhou-gea** [comment]
Here is the error msg  shown:
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

  at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
  at Docker.Actions.<>c__DisplayClass25_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 275
  at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by wei-zhou-gea** [comment]
Diagnostic ID:
E2594A26-1758-424F-AABE-195F073FAD5A/20180906113048
