### ISSUE TITLE
Docker daemon not starting 

### ISSUE THREAD

**Issue by dporunne** [docker/for-win#2566]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FC14396C-8B43-4539-8842-3CBF10C423AA/20180907093426

### Expected behavior
Docker for Windows should be started after docker is installed and started
 
### Actual behavior
Timed out while waiting for Docker daemon to be ready
   at Docker.Backend.Processes.WindowsDockerDaemon.WaitForDaemonToBeReady() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 147
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 222
   at Docker.Backend.ContainerEngine.Windows.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 153
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180

I uninstalled and installed Docker for Windows again but I keep getting the same error again

### Information

  - Windows Version: Windows 10 Enterprise Version 1803 (OS Build 17134.228 )
  - Docker for Windows Version: 18.06.1-ce

### Steps to reproduce the behavior

  1. I ran cleanup script given by Windows on the page: https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/live/windows-server-container-tools/CleanupContainerHostNetworking
  2. I got the below error while running "docker info" command:
 error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by dporunne** [comment]
[diagnostics.log](https://github.com/docker/for-win/files/2361629/diagnostics.log)

Attached Diagonistics

**Comment by dporunne** [comment]
Finally solved after hours of digging into the logs and troubleshooting:

There was a NAT network that was left hanging which I could not delete because WinNAT service was not getting started.
 
Firstly, took a backup the following registry key:

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nsi
Then I deleted the items with the key:

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nsi\{eb004a03-9b1a-11d4-9123-0050047759bc}.
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nsi\{eb004a04-9b1a-11d4-9123-0050047759bc}.
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Nsi\{eb004a05-9b1a-11d4-9123-0050047759bc}.

In powershell, then performed: 
start-service WinNat

Then I deleted the stale NAT network
Remove-NetNAT -Name "NATNetwork"

Then I removed removed all network adapters , removed Hyper V, and restarted the machine and then installed fresh Docker for Windows followed by letting Docker enable Hyper V by itself and then restarting the machine. Docker Working !!
