### ISSUE TITLE
Docker is not initializing on Windows Server 2016

### ISSUE THREAD

**Issue by andreluistosato** [docker/for-win#2579]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: C8535040-C234-423D-8233-736275D5EB34/20180910170243

### Expected behavior
-Docker should start normally

### Actual behavior
-Its generating an error ""

### Information

  - Windows Version: Windows Server 2016
  - Docker for Windows Version: 18.06.0-ce-win72
  -Hyper-v is installed
  -The current user is Administrator, its in the Docker user group, admin group and hyper v group.

### **Error in log:**
`[17:02:42.937][HyperV][Info   ] Starting VM MobyLinuxVM...
[17:02:42.981][NamedPipeServer][Error  ] Unable to execute Start: Unable to launch process: 1314    at Docker.Win32Helpers.NativeImpersonatedProcess.Start(NativeImpersonatedProcess* , basic_string<wchar_t\,std::char_traits<wchar_t>\,std::allocator<wchar_t> >* watchguardPath) in c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\xstring:line 1808
   at Docker.Win32Helpers.ImpersonatedProcess.Start(String watchguardPath) in c:\gopath\src\github.com\docker\pinata\win\src\docker.win32helpers\impersonatedprocess.cpp:line 250
   at Docker.Backend.Processes.ExternalProcess.StartImpersonatedProcess(String fileName, String arguments, String currentDirectory, IDictionary`2 envVariables, WindowsIdentityRecorder identity, CancellationToken stopToken) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\ExternalProcess.cs:line 66
   at Docker.Backend.Processes.ExternalProcess.Start(String arguments, String currentDirectory, IDictionary`2 envVariables, WindowsIdentityRecorder identity) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\ExternalProcess.cs:line 52
   at Docker.Backend.Processes.VpnKit.Start(Settings settings, String vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\VpnKit.cs:line 40
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 247
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 117
[17:02:42.992][NamedPipeClient][Error  ] Unable to send Start: Unable to launch process: 1314`

### **Docker Version command:** 
`C:\Users\Administrator> docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:34 2018
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.38/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.`

**Comment by jasonbivins** [comment]
Hi @andreluistosato 
We actually don't support Docker for Windows running on Server, you'll need to switch over to our EE edition that's included with Windows.  https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install
