### ISSUE TITLE
docker in windows fails: Unable to create an instance of Docker.WPF.AboutBox

### ISSUE THREAD

**Issue by jllavin77** [docker/for-win#2631]
Hello everybody,

My docker in windows installation has started failing due to the following error:

Unable to create an instance of Docker.App: Unable to create an instance of Docker.WPF.AboutBox
at Docker.Core.di.Singletons.NewInstance(Type type, Int32 depth)
at Docker.Core.di.Singletons.Get(Type type, Int32 depth)
at Docker.Core.di.Singletons.GetT
at Docker.Program.Run(IReadOnlyCollection`1 args)

Taking a look at the logs, here is what I get:

Version: 18.03.1-ce-win65 (17513)
Channel: stable
Sha1:
Started on: 2018/09/20 11:46:28.022
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro for Workstations
Edition: ProfessionalWorkstation
Id: 1709
Build: 16299
BuildLabName: 16299.637.amd64fre.rs3_release_svc.180808-1748
File: C:\Users\jllavin\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:46:28.272][GUI ][Info ] Starting...
[11:46:29.507][SegmentApi ][Info ] Not tracking: appLaunched
[11:46:30.507][SegmentApi ][Info ] Usage statistic: heartbeat
[11:46:30.538][SegmentApi ][Info ] Usage statistic: Identify
[11:46:30.616][GUI ][Error ] Unable to create an instance of Docker.App: Unable to create an instance of Docker.WPF.AboutBox
[11:58:25.067][ErrorReportWindow][Info ] Open logs

Any help would be appreciated, I'd rather not go back to the old VBox days...so please, give me a hand.

Best

JL

**Comment by jllavin77** [comment]
Fixed doing this:
https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10

and this:
https://success.docker.com/article/dockerforwin-install-fails-on-installationmanifestjson

and then reinstalling.

;)
