### ISSUE TITLE
Hyper-V was unable to find a virtual switch with name "DockerNAT".

### ISSUE THREAD

**Issue by rschuetzler** [docker/for-win#2660]
Same issue as #324, but I don't have any VPN software installed. I did at one point, but I've removed all of it, rebooted my computer several times, completely removed docker, disabled Hyper-V and started from scratch, and yet the issue persists.

  - [✔] I have tried with the latest version of my channel (Stable or Edge)
  - [✔] I have uploaded Diagnostics
  - Diagnostics ID: 8C37752B-4F0D-4F22-8C6E-A294E8BDFAB5/20180927191306

### Expected behavior
Docker starts
### Actual behavior
Error message:

```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

### Information

  - Windows Version: Version	10.0.17134 Build 17134
  - Docker for Windows Version:18.06.1-ce-win73 (19507)

### Steps to reproduce the behavior

  1. Try to start Docker from start menu

**Comment by Casraw** [comment]
Create a Network and connect to the container by Hand dosent help? But you need to use the right driver. I think "-d nat"
And only when you give it a name with the -o flag you will se the switch in hyperv manager. And define a subnet and the gateway (is the ip from the vswitch).

**Comment by rschuetzler** [comment]
@Casraw can you give me an example of what the command might look like? I've never created a virtual switch by hand.

**Comment by jsam2412** [comment]
Try running these commands and restart docker. This worked for me.

```
# Done from an admin shell 
net stop vmms
net start vmms
```
