### ISSUE TITLE
Docker for windows doesn't work

### ISSUE THREAD

**Issue by vivekdhami** [docker/for-win#2673]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker for windows should start and work as expected.

This issue has been quite common in windows machine for a long time and it really questions the level of support provided by Docker team.
Its very hard to understand why this particular issue is not being resolved. Also it really creates a doubt for choosing docker as a platform for all our future developments.

### Actual behavior
Docker doesn't start and fails with the following message:
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID E3FB2322-58EA-4150-B32B-122BE0318200)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID E3FB2322-58EA-4150-B32B-122BE0318200).
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information

  - Windows Version: 10.0.17134
  - Docker for Windows Version: 18.06.1-ce-win73 (19507)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by vivekdhami** [comment]
Apparently this was not an issue with either docker (both edge/stable versions) and neither with windows 10 updates either.
Somehow because of parallels upgrade the nested virtualization option was unselected that caused hyper-v issues.
