### ISSUE TITLE
Timed out while waiting for Docker daemon to be ready - Happens after Windows Update

### ISSUE THREAD

**Issue by TheDoubleH** [docker/for-win#2681]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 255C90F8-D52F-4D95-B29E-C97F8D8448AF/20181001230014
  - Diagnostics ID: 255C90F8-D52F-4D95-B29E-C97F8D8448AF/20181004234317

### Expected behavior
Docker Service Starts
### Actual behavior
Docker opens with error:
Timed out while waiting for Docker daemon to be ready
   at Docker.Backend.Processes.WindowsDockerDaemon.WaitForDaemonToBeReady() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 147
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 222
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 96
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180
### Information

  - Windows Version: Windows 10 PRO 
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. … Complete Windows Update, while having two containers active (Microsoft/dynamics-nav)
  2. ...

**Comment by a1russell** [comment]
There are several issues being opened related to this right now, so I'm not sure the best one to comment on, but this is happening to me, as well. After installing the Windows 10 October 2018 update, docker no longer starts. Furthermore, it breaks my network connection.

One thing I noticed is that, looking at the Network Connections, there are *two* vEthernet connections in play. One of them exists, and seems fine, maybe. The second one, however, will only appear for a split second, and then disappear for several seconds, again and again. If you open the Device Manager, you can see constant refreshing due to this device as well.

Browsing the web, I'll constantly see error messages that my network connection was interrupted.

I've had to uninstall Docker and disable Hyper-V in order to fix the network issue for now, but it'd be nice to be able to use Docker somehow!
