### ISSUE TITLE
Installation fails on Windows 10

### ISSUE THREAD

**Issue by averri** [docker/for-win#2714]
This is the error when trying to install Docker on Windows 10:

```
The process cannot access the file 'C:\Program Files\Docker\Docker\resources\dockerd.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at LightweightInstaller.UnpackArtifactsStep.<DoAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
```

  - [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Installation should occur without any issues!

### Actual behavior
Cannot install Docker on Windows 10.

### Information
  - Windows Version: 10
  - Docker for Windows Version: 2.0.0.0-beta1-win75 2018-09-14

### Steps to reproduce the behavior
Difficult to reproduce. I have just uninstalled and installed again as suggested in another forum, in order to solve another issue. The uninstall process had an error, and now it does not install again due to the error above.

I have never had a good experience with Docker on Windows.

**Comment by azizabdul** [comment]
What is solution for this issue

**Comment by professorhaseeb** [comment]
The solution is
Task Manager > Services, find the running docker processor, stop it and then reinstall the docker package.

**Comment by Varin6** [comment]
In my case, I had Windows Event Log open which was preventing access to the file. When I closed the Event Viewer, it reinstalled fine. It actually botched the update of docker as it couldn't remove the file, I had to manually remove the files and reinstall.
