### ISSUE TITLE
Can't start Docker for Windows on Windows 10 machine (October Update)

### ISSUE THREAD

**Issue by huytnd** [docker/for-win#2727]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5146133B-FDE3-4018-9DED-03B394A3D48C/20181011030305

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. Open Docker for Windows Installer
  2. Installed successfully
  3. Starting Docker, and the issue occurred

OS:  Windows 10 Pro x64 (build 17763)

**Comment by huytnd** [comment]
Version: 18.06.1-ce-win73 (19507)
Channel: stable
Sha1: b0f14f1dac391615de29280eb46a7d65c33e9e83
Started on: 2018/10/11 03:02:22.989
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1809
Build: 17763
BuildLabName: 17763.1.amd64fre.rs5_release.180914-1434
File: C:\Users\huytr\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[03:02:23.199][GUI            ][Info   ] Starting...
[03:02:24.445][Tracking       ][Info   ] Crash report and usage statistics are enabled
[03:02:24.449][SegmentApi     ][Info   ] Usage statistic: appLaunched
[03:02:24.517][SegmentApi     ][Info   ] Usage statistic: heartbeat
[03:02:24.520][SegmentApi     ][Info   ] Usage statistic: Identify
[03:02:26.428][Notifications  ][Info   ] Docker is starting...
[03:02:26.478][NamedPipeClient][Info   ] Sending Version()...
[03:02:26.504][NamedPipeClient][Info   ] Received response for Version
[03:02:26.506][NamedPipeClient][Info   ] Sending Start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions)...
[03:02:11.813][BackendServer  ][Info   ] Started
[03:02:26.501][NamedPipeServer][Info   ] Version()
[03:02:26.502][NamedPipeServer][Info   ] Version done in 00:00:00.0004958.
[03:02:26.512][NamedPipeServer][Info   ] Start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions)
[03:02:26.522][PowerMode      ][Info   ] Stop
[03:02:26.534][HyperV         ][Info   ] Stop
[03:02:26.599][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[03:02:26.618][PowerShell     ][Info   ] Creating a Runspace Pool...
[03:02:27.107][NPS            ][Info   ] NPS user ceated on: 10/10/2018 12:14:27 PM -07:00, last survey:  01/01/0001 12:00:00 AM +00:00
[03:02:27.126][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[03:02:27.319][HyperV         ][Info   ] Script started at 03:02:27.313
[03:02:29.946][HyperV         ][Info   ] Module loaded at 03:02:29.946
[03:02:31.360][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[03:02:31.360][HyperV         ][Debug  ] [stop] took 00:00:04.8152482 to run
[03:02:31.361][OptimizeDisk   ][Info   ] Optimize
[03:02:31.362][PowerShell     ][Info   ] Run script...
[03:02:32.399][Moby           ][Info   ] Stop
[03:02:32.405][PowerMode      ][Info   ] Start
[03:02:32.405][HyperVGuids    ][Info   ] Installing GUIDs...
[03:02:32.407][HyperV         ][Info   ] Create
[03:02:32.408][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64424509440 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[03:02:32.418][HyperVGuids    ][Info   ] GUIDs installed
[03:02:32.419][Firewall       ][Info   ] Removing all existing rules...
[03:02:32.451][HyperV         ][Info   ] Script started at 03:02:32.450
[03:02:32.460][Firewall       ][Info   ] All existing rules are removed.
[03:02:32.461][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[03:02:32.468][HyperV         ][Info   ] Module loaded at 03:02:32.468
[03:02:32.474][Firewall       ][Info   ] Opening ports for SMB...
[03:02:32.489][Firewall       ][Info   ] Ports are opened
[03:02:34.605][HyperV         ][Info   ] Creating Switch: DockerNAT...
[03:02:39.361][HyperV         ][Info   ] Switch created.
[03:02:41.347][HyperV         ][Info   ] Set IP address on switch
[03:02:41.481][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'localhost' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-MobyLinuxVM, <No file>: line 178
at <ScriptBlock>, <No file>: line 394. Let's retry
[03:02:41.673][Installer      ][Info   ] Checking for features: *Hyper-V*, Containers
[03:02:41.674][PowerShell     ][Info   ] Run script...
[03:02:44.255][PowerShell     ][Info   ] Run script...
[03:02:45.991][PowerShell     ][Info   ] Run script...
[03:02:47.983][PowerShell     ][Info   ] Run script...
[03:02:49.848][Installer      ][Info   ] Features installed
[03:02:49.900][HyperV         ][Info   ] Hyper-V is running
[03:02:49.900][PowerMode      ][Info   ] Stop
[03:02:49.901][HyperV         ][Info   ] Stop
[03:02:49.901][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[03:02:49.931][HyperV         ][Info   ] Script started at 03:02:49.931
[03:02:49.943][HyperV         ][Info   ] Module loaded at 03:02:49.943
[03:02:50.978][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[03:02:50.978][HyperV         ][Debug  ] [stop] took 00:00:01.0774966 to run
[03:02:50.978][OptimizeDisk   ][Info   ] Optimize
[03:02:50.978][PowerShell     ][Info   ] Run script...
[03:02:51.995][Moby           ][Info   ] Stop
[03:02:52.020][HyperV         ][Info   ] Destroy
[03:02:52.020][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[03:02:52.048][HyperV         ][Info   ] Script started at 03:02:52.048
[03:02:52.060][HyperV         ][Info   ] Module loaded at 03:02:52.060
[03:02:53.082][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[03:02:53.083][HyperV         ][Info   ] Destroying Switch DockerNAT...
[03:02:55.997][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[03:02:57.030][HyperV         ][Debug  ] [destroy] took 00:00:05.0099930 to run
[03:02:57.031][Firewall       ][Info   ] Closing ports...
[03:02:57.031][Firewall       ][Info   ] Removing all existing rules...
[03:02:57.134][Firewall       ][Info   ] All existing rules are removed.
[03:02:57.134][Firewall       ][Info   ] Ports are closed
[03:02:57.135][HyperVGuids    ][Info   ] Removing GUIDs...
[03:02:57.138][HyperVGuids    ][Info   ] GUIDs removed
[03:02:57.138][HyperV         ][Info   ] Create
[03:02:57.139][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64424509440 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[03:02:57.184][HyperV         ][Info   ] Script started at 03:02:57.184
[03:02:57.202][HyperV         ][Info   ] Module loaded at 03:02:57.202
[03:02:59.246][HyperV         ][Info   ] Creating Switch: DockerNAT...
[03:03:03.734][HyperV         ][Info   ] Switch created.
[03:03:04.967][HyperV         ][Info   ] Set IP address on switch
[03:03:05.076][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'localhost' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-MobyLinuxVM, <No file>: line 178
at <ScriptBlock>, <No file>: line 394    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 183
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 117
[03:03:05.146][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'localhost' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-MobyLinuxVM, <No file>: line 178
at <ScriptBlock>, <No file>: line 394
[03:03:05.149][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'localhost' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-MobyLinuxVM, <No file>: line 178
at <ScriptBlock>, <No file>: line 394
[03:03:05.179][NamedPipeClient][Info   ] Sending Version()...
[03:03:05.181][NamedPipeClient][Info   ] Received response for Version
[03:03:05.181][NamedPipeClient][Info   ] Sending GatherDiagnostics(-path C:\Users\huytr\AppData\Local\Temp\ gather -id 5146133B-FDE3-4018-9DED-03B394A3D48C/20181011030305, C:\Users\huytr\AppData\Local\Temp\5146133B-FDE3-4018-9DED-03B394A3D48C/20181011030305.zip)...
[03:03:05.180][NamedPipeServer][Info   ] Version()
[03:03:05.180][NamedPipeServer][Info   ] Version done in 00:00:00.
[03:03:05.182][NamedPipeServer][Info   ] GatherDiagnostics(-path C:\Users\huytr\AppData\Local\Temp\ gather -id 5146133B-FDE3-4018-9DED-03B394A3D48C/20181011030305, C:\Users\huytr\AppData\Local\Temp\5146133B-FDE3-4018-9DED-03B394A3D48C/20181011030305.zip)
[03:03:28.361][ErrorReportWindow][Info   ] Open logs

**Comment by huytnd** [comment]
I ended up to reset my PC, and it worked.
Conclusion: DO NOT update to the latest Windows 10 if your workstation is still running well.
