### ISSUE TITLE
No activity detected on VM, aborting

### ISSUE THREAD

**Issue by ktwade** [docker/for-win#2728]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
CD0111DF-E9FD-42B2-AFAF-34B0C5B23718/20181010145401

### Expected behavior
Docker switches to Linux containers
### Actual behavior
Crashes:
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass25_0.<SwitchDaemon>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 275
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information

This is a fresh install as I'm just trying to get introduced to docker. I am unable to get the "hello-world" image to run in Windows containers, so I was going to see if it would run in Linux containers and I got this.

  - Windows Version: Windows 10 version 1607 (OS Build 14393.0)
  - Docker for Windows Version: 18.06.1-ce-win73 (19507)

### Steps to reproduce the behavior

  1. Right-click on system tray icon and select switch to Linux containers.

**Comment by embusalacchi** [comment]
This is happening on Docker for Windows Version: 2.0.0.0-beta1-win75 as well.  Fresh install of Windows 10 Enterprise.  Diagnostics ID: E7E7C4CC-E67C-4A9A-A3BB-661725EEE312/20181031113836

**Comment by chlumper** [comment]
Possible duplicate of #2404
