### ISSUE TITLE
how can i resolve this issue when i run docker

### ISSUE THREAD

**Issue by willingtone** [docker/for-win#2732]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

Access to the path 'C:\WINDOWS\System32\drivers\etc\hosts' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at Docker.Backend.DnsUpdater.PatchSystemHosts(String mainIpAddress) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DnsUpdater.cs:line 269
   at Docker.Backend.DnsUpdater.UpdateHosts() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\DnsUpdater.cs:line 257
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 222
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 96
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180

**Comment by armandocastillo559** [comment]
same issue here.  
I got the latest off www.docker.com today [18.06.1-ce-win73 (19507) Stable] and installed it on my x64 Win10 Pro [ 10.0.17134 Build 17134] running on Lenovo P51s

**Comment by Rainmaker52** [comment]
Is it possible that some process is denying access to \etc\hosts? I'm thinking anti-virus software, anti-malware, protected folders etc.

Do you have any such software installed?
