### ISSUE TITLE
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.  'MobyLinuxVM' failed to realize.

### ISSUE THREAD

**Issue by Aventes** [docker/for-win#2739]
**Found a few appropriate issues #846 and #1821 but the provided solution wasn't helped.**

  - Diagnostics ID: 76D89A62-6F21-454E-8FD7-0FC823BA8923/20181012125136

### Expected behavior
Docker starts on Linux containers

### Actual behavior
Docker crashes with an error: 

```
Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64424509440 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso...
[12:40:17.097][HyperV         ][Info   ] Script started at 12:40:17.097
[12:40:17.110][HyperV         ][Info   ] Module loaded at 12:40:17.110
[12:40:17.130][HyperV         ][Info   ] Creating Switch: DockerNAT...
[12:40:19.062][HyperV         ][Info   ] Switch created.
[12:40:20.240][HyperV         ][Info   ] Set IP address on switch
[12:40:20.252][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[12:40:20.632][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.

'MobyLinuxVM' failed to realize.
at New-MobyLinuxVM, <No file>: line 187
at <ScriptBlock>, <No file>: line 394    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 183
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 117
[12:40:21.411][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.

MobyLinuxVM' failed to realize.
at New-MobyLinuxVM, <No file>: line 187
at <ScriptBlock>, <No file>: line 394
[12:40:21.413][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create a new virtual machine.

'MobyLinuxVM' failed to realize.
at New-MobyLinuxVM, <No file>: line 187
at <ScriptBlock>, <No file>: line 394
```

### Information
  - Windows Version: 10.0.15063
     OS Name: Microsoft Windows 10 Pro
     OS Build: 15063
  - Docker for Windows Version: Stable 18.06.1-ce-win73 (19507)
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
    76D89A62-6F21-454E-8FD7-0FC823BA8923/20181012125136
  - a reproducible case
    

### Steps to reproduce the behavior
  1. Enable HyperV
      **_Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All_**
      Reboot
  2. Enable Containerization
      _**Enable-WindowsOptionalFeature -Online -FeatureName Containers -All**_
  3. Ensure that HyperV is active: 
![image](https://user-images.githubusercontent.com/4823396/46862644-fe435880-ce1d-11e8-93fc-3871bb11f651.png)
  4. Install Docker Stable 
  5. Started Docker - allow system to reboot
  6. Error occurs - reinstallation HyperV and containerization wasn't hepled.

**Comment by Aventes** [comment]
Not relevant any more

**Comment by graphdb2** [comment]
I am the same issue can you explain why it is not relevant anymore ?

`Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.
at New-MobyLinuxVM, <No file>: line 187
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 75
   at Docker.Actions.<>c__DisplayClass15_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 59
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59`
