### ISSUE TITLE
Docker unable to start after settings change.

### ISSUE THREAD

**Issue by Kuinox** [docker/for-win#2804]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3B0AA1B7-DE49-4BA9-BEDB-2A763D00FACF/20181025125642

### Expected behavior
Docker start successfully with the new settings.
### Actual behavior
Docker fail to start with this error: 
```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to change state.

The operation failed with error code '32788'.
at Start-MobyLinuxVM, <No file>: line 300
at <ScriptBlock>, <No file>: line 395
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 254
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 189
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180
```
### Information
I can reproduce it on my laptop, but it never happened on my dekstop windows.
Resetting to factory default make Docker working again.

  - Windows Version: Windows 10 version 1803
  - Docker for Windows Version: 18.06.1-ce-win73 (19507)

### Steps to reproduce the behavior
  1. Change RAM "limit" in Advanced Settings
  2. Apply changes
  3. Restart Docker

**Comment by Kuinox** [comment]
Actually by reproducing this error again i'm not able to "factory default" because of the same error.

**Comment by hrbu** [comment]
Facing the same problem.

**Comment by Kuinox** [comment]
I have 16 Go of RAM and had more than 8Go available and tried to increase the limit under 4Go when it occurred.
