### ISSUE TITLE
Unhandled exception installing Docker for Windows 10

### ISSUE THREAD

**Issue by jslucas** [docker/for-win#2816]
- [x ] I have tried with the latest version of my channel (Stable or Edge)

### Expected behavior
Installation should succeed

### Actual behavior
When launching Docker for Windows Installer (stable), after "Downloading package" an exception is thrown and the install fails. 

Exception:
`End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at LightweightInstaller.ExtractManifestStep.<DoAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()`

  - Windows Version: Win10 Pro Version 1809
  - Docker for Windows Version: Current Stable

### Steps to reproduce the behavior
See above.

**Comment by Lucas-C** [comment]
I had a slightly different one:
```
docker for windows installation failed
    à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    à LightweightInstaller.DownloadStep.<DoAsync>d__35.MoveNext()
```
Relaunching the installer seemingly solved it.
