### ISSUE TITLE
Unable to start Docker for Windows

### ISSUE THREAD

**Issue by cfiller123** [docker/for-win#2835]
I have tried installing and reinstalling multiple times but myself (and my colleague) have been unable to get Docker for Windows running. Error message is below but unable to find a working solution.

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 269E3418-054E-4F89-8146-9EA92D684E07/20181031154155

### Expected behavior
Docker runs.

### Actual behavior
Does not run and says "an error occurred" and gives following error message:

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information
<!--
Every attempt to download and install Docker for Windows on my laptop and colleagues has the same failure. We are both using Lenovo laptops, T580 and T560. My laptop (which diagnostic ID corresponds to) is the T580.
  - Windows Version 10 OS Build 17134.376
  - Docker for Windows Version: Version 18.06.1-ce-win73 (19507)

### Steps to reproduce the behavior
1. Download most recent stable release.
2. Install
3. Try to run docker.
4. See above error message.

**Comment by cfiller123** [comment]
One additional item: compared it to a colleague who has recently installed Docker for Windows - he has a virtual machine added to Hyper-V manager from the install (or perhaps first run?) and I do not. Not sure if it's related but its the only difference we could see between my install and his.
