### ISSUE TITLE
After windows start up, I get error window

### ISSUE THREAD

**Issue by minoseah629** [docker/for-win#2836]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
5D590F3D-1301-4465-B950-8F4C8A8D173C/20181031195920

### Expected behavior
Docker should launch service successfully with no error

### Actual behavior
Docker threw error window
Timed out while waiting for Docker daemon to be ready
   at Docker.Backend.Processes.WindowsDockerDaemon.WaitForDaemonToBeReady() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 147
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 222
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 96
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180
### Information

  - Windows Version: 1809
  - Docker for Windows Version: 18.06.ce.win73 (19507) stable
  - VMware Fusion v 11.0.0 (10120384)

  1. VMware Fusion bootup Windows
  2. Docker Service starts up

**Comment by jonasro** [comment]
Is there no official response to any of these failures on latest version? There seems to be a lot of people with this issue (me included)
