### ISSUE TITLE
Failed to start Docker beta31 after Windows 10 latest update (to build 14965)

### ISSUE THREAD

**Issue by ramiwi** [docker/for-win#285]
### Expected behavior
Start Docker as windows 10 starts
### Actual behavior
Fail to start, gives this error:
[NamedPipeServer][Error  ] Unable to execute Start: Unable to stop: Couldn't stop VM MobyLinuxVM
at Fatal, <No file>: line 358
at Stop-VM-Force, <No file>: line 354
at Stop-MobyLinuxVM, <No file>: line 287
at <ScriptBlock>, <No file>: line 365    at Docker.Backend.ContainerEngine.Linux.Stop()
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[dockerlog.txt](https://github.com/docker/for-win/files/629559/dockerlog.txt)

### Information
  - Diagnostic ID: 76203926-E85E-4E11-9ED5-FE0A56B41D73/2016-12-04_15-47-54
  - Windows 10 Pro Insider Preview, Build: 14965
[dockerlog.txt](https://github.com/docker/for-win/files/629557/dockerlog.txt)

### Steps to reproduce the behavior
Start windows, wait for docker to try autostart or try starting it manually after it failed on startup.

**Comment by dgageot** [comment]
@ramiwi Can you update to Beta 31 and tell if the issue is still there?

**Comment by ramiwi** [comment]
I think its already beta 31, see this screenshot:
![docker-info-2016-12-04](https://cloud.githubusercontent.com/assets/1592063/20868772/30c02512-ba6c-11e6-8e61-c08fc0787732.png)

**Comment by ramiwi** [comment]
I think its already beta 31, see this screenshot:
![docker-info-2016-12-04](https://cloud.githubusercontent.com/assets/1592063/20868772/30c02512-ba6c-11e6-8e61-c08fc0787732.png)

**Comment by ramiwi** [comment]
Now it started successfully with windows.
(It failed 3 times - on startup, then when manually started and on another windows startup).

**Comment by dgageot** [comment]
@ramiwi Feel free to close the issue if you see it working more reliably

**Comment by ramiwi** [comment]
Failed today on windows startup with the following error:
```
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```
[log20161206.txt](https://github.com/docker/for-win/files/633832/log20161206.txt)

A crash report was uploaded with the following id:
76203926-E85E-4E11-9ED5-FE0A56B41D73/2016-12-06_13-13-35

**Comment by ramiwi** [comment]
Successfully started manually later.

**Comment by ramiwi** [comment]
Beta32.1 works fine.
