### ISSUE TITLE
Can't launch Docker in Win10

### ISSUE THREAD

**Issue by Pxtl** [docker/for-win#2887]
Just installed Docker into my laptop - runs windows 10 pro.  Initially used stable, got this error.  Uninstalled stable, uninstalled Hyper-V, then reinstalle dHyper-V and edge to see if that's better.

No dice.

diagnostic ID: 66D5D273-DB71-4F30-BE10-1CC6FBD6D0F2/20181114134310

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 66D5D273-DB71-4F30-BE10-1CC6FBD6D0F2/20181114134310

### Expected behavior
Docker starts up

### Actual behavior
Docker gives this error:

```
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

### Information

  - Windows Version: Windows 10 Pro
  - Docker for Windows Version: Docker 2.0.0 win77, I think

### Steps to reproduce the behavior

  1. Install docker on my machine
  2. There is no 2.

Also, attempting "docker info" from Powershell admin console gives this:

```
PS C:\WINDOWS\system32> docker info
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/info: open //./pipe/docker_engine: The system cann
ot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to co
nnect. This error may also indicate that the docker daemon is not running.
```

**Comment by choux130** [comment]
Same issue! Diagnostics ID : 28DDE6BD-2C9B-48C8-BC86-1A8FA23EDD14/20181120132032

**Comment by chlumper** [comment]
Possible duplicate of #2404
