### ISSUE TITLE
After an automatic docker update, it crashes on startup - The file exists

### ISSUE THREAD

**Issue by johanvdb** [docker/for-win#2916]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E3BEED69-AB8F-4B1F-8E76-4CCD4F38F22B/20181120083217

### Expected behavior

Docker should just start up

### Actual behavior

Docker crashes with "An error occurred" dialog.

### Information

Restarting does not seem to resolve the issue. I just got a popup yesterday after docker was working for months, saying that there was an update and whether I would like to apply it. I chose yes. This morning, when I restart the machine, the below happens.

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Failed to create the virtual hard disk.

The system failed to create 'C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx'.

Failed to create the virtual hard disk.

The system failed to create 'C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx': The file exists. (0x80070050).
at Ensure-VHD-Path, <No file>: line 306
at New-MobyLinuxVM, <No file>: line 208
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by johanvdb** [comment]
Diagnostic uploaded and original bug report edited. 
Diagnostic ID: E3BEED69-AB8F-4B1F-8E76-4CCD4F38F22B/20181120083217

**Comment by jarederaj** [comment]
I have the same error.

If I restart docker form the console I can see MobyLinuxVM is removed and added back in an Off state. Docker immediatly throws an error after MobyLinuxVM is added back into the list of Hyper-V managed VMs.

**Comment by amirsamary** [comment]
I have a friend with the same problem here. Tried everything I could find on this forum and on your troubleshooting documents. Any news on this?

**Comment by cowwoc** [comment]
How do we fix this?

**Comment by johanvdb** [comment]
You won't like my solution... I threw my MS notebook in the dustbin and got a mac. Being quite serious...
