### ISSUE TITLE
OSError: [Errno 22] Invalid argument in docker-compose in v2.0.0

### ISSUE THREAD

**Issue by peterjaric** [docker/for-win#2918]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 1E6E2498-3C44-42F1-AC6E-7C66643F6F92/20181120131213

### Expected behavior
Docker-compose starts my environment.

### Actual behavior
Docker-compose errors out and exits. See "Steps to reproduce the behavior" below.

### Information

  - Windows Version: 10.0.17134 Build 17134
  - Docker for Windows Version:
Version 2.0.0.0-win78 (28905)
Channel: stable
Build: c404a62

This worked yesterday for me, not for my co-worker. Then I updated Docker for Windows, and it stopped working for me too. This leads me to believe it has to do with the update and the new version.

It is reproducible by following the steps below.

### Steps to reproduce the behavior
1. Unpack testcase.zip.
2. Go to docker/env.
3. Run `docker-compose up --build`.

For me, on Windows, this is the output:

```../env docker-compose up --build
Building package-backend
[3944] Failed to execute script docker-compose
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1080, in up
  File "compose\cli\main.py", line 1076, in up
  File "compose\project.py", line 475, in up
  File "compose\service.py", line 340, in ensure_image_exists
  File "compose\service.py", line 1080, in build
  File "site-packages\docker\api\build.py", line 152, in build
  File "site-packages\docker\api\build.py", line 346, in process_dockerfile
OSError: [Errno 22] Invalid argument: '\\\\?\\C:\\Users\\[redacted username]\\code\\testcase\\docker\\env\\../backend/package.Dockerfile'
```

On OSX, this is the output:

```env$ docker-compose up --build
Building package-backend
Step 1/1 : FROM alpine
latest: Pulling from library/alpine
4fe2ade4980c: Already exists
Digest: sha256:621c2f39f8133acb8e64023a94dbdf0d5ca81896102b9e57c0dc184cadaf5528
Status: Downloaded newer image for alpine:latest
 ---> 196d12cf6ab1
Successfully built 196d12cf6ab1
Successfully tagged env_package-backend:latest
Recreating env_package-backend_1 ... done
Attaching to env_package-backend_1
env_package-backend_1 exited with code 0 
```

**Comment by peterjaric** [comment]
Turns out that by replacing the relative path with an absolute path, the problem can be worked around:

```dockerfile: c:/Users/[redacted username]/code/testcase/docker/backend/package.Dockerfile```

Not very portable, but until the issue is sorted, it is usable.

**Comment by christianacca** [comment]
Exact same problem for me

**Comment by kripergvg** [comment]
For me too. Fix this pls. 
![image](https://user-images.githubusercontent.com/7288803/48950362-efd37b00-ef4b-11e8-8916-62407ad03047.png)

**Comment by stephen-turner** [comment]
This turns out to be caused by https://github.com/docker/compose/issues/6356. We will have a fix soon.

**Comment by ebriney** [comment]
FYI, a compose release has been pushed: https://github.com/docker/compose/releases/tag/1.23.2
We'll do an update for Docker Desktop as soon as it's ready.

**Comment by ebriney** [comment]
It's fixed on stable, we will do an edge release today

**Comment by XedinUnknown** [comment]
Same problem on Docker Compose `1.24.1`.

```
PS I:\projects\multilingualpress> docker-compose up
Building codecept
Traceback (most recent call last):
  File "site-packages\docker\utils\build.py", line 96, in create_archive
OSError: [Errno 22] Invalid argument: '\\\\?\\I:\\projects\\multilingualpress\\vendor\\bin\\export-plural-rules'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1085, in up
  File "compose\cli\main.py", line 1081, in up
  File "compose\project.py", line 527, in up
  File "compose\service.py", line 360, in ensure_image_exists
  File "compose\service.py", line 1084, in build
  File "site-package
```

**Comment by ilmimris** [comment]
> Same problem on Docker Compose `1.24.1`.
> 
> ```
> PS I:\projects\multilingualpress> docker-compose up
> Building codecept
> Traceback (most recent call last):
>   File "site-packages\docker\utils\build.py", line 96, in create_archive
> OSError: [Errno 22] Invalid argument: '\\\\?\\I:\\projects\\multilingualpress\\vendor\\bin\\export-plural-rules'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "docker-compose", line 6, in <module>
>   File "compose\cli\main.py", line 71, in main
>   File "compose\cli\main.py", line 127, in perform_command
>   File "compose\cli\main.py", line 1085, in up
>   File "compose\cli\main.py", line 1081, in up
>   File "compose\project.py", line 527, in up
>   File "compose\service.py", line 360, in ensure_image_exists
>   File "compose\service.py", line 1084, in build
>   File "site-package
> ```

Same here, Docker Compose `1.24.1`.
```
Traceback (most recent call last):
  File "site-packages\docker\utils\build.py", line 96, in create_archive
OSError: [Errno 22] Invalid argument: '\\\\?\\E:\\project\\some_project\\modules\\main\\.pipenv\\bin\\python'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1085, in up
  File "compose\cli\main.py", line 1081, in up
  File "compose\project.py", line 527, in up
  File "compose\service.py", line 344, in ensure_image_exists
  File "compose\service.py", line 1084, in build
  File "site-packages\docker\api\build.py", line 159, in build
  File "site-packages\docker\utils\build.py", line 31, in tar
  File "site-packages\docker\utils\build.py", line 100, in create_archive
OSError: Can not read file in context: \\?\E:\project\some_project\modules\main\.pipenv\bin\python
[3844] Failed to execute script docker-compose
```

**Comment by flexchar** [comment]
Same issue on Windows 
![image](https://user-images.githubusercontent.com/9198896/67851789-76ed8380-fb0b-11e9-81a6-07effbbd64c5.png)

However it works if the first time start with docker-compose from WSL. All subsequent spin ups also work from windows.

**Comment by stephen-turner** [comment]
If it's still broken in compose, please report it in the docker/compose repo.

**Comment by spmartin** [comment]
Same problem in 1.25.5.

Please fix it, first reported issue was 2 years ago

**Comment by dmnkfl** [comment]
same here, also v 1.25.5

**Comment by stephen-turner** [comment]
This ticket is closed, so no-one will work on it. As I said before, if it's still broken, please open a new ticket in the docker/compose repo.

**Comment by maacpiash** [comment]
I'm also suffering from this two-year-old bug 😢

**Comment by maacpiash** [comment]
I'm also suffering from this one-and-a-half-year-old bug 😢 

```shell
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```
