### ISSUE TITLE
No activity detected on VM, aborting when switching to Linux containers

### ISSUE THREAD

**Issue by itservicesix** [docker/for-win#2971]
We are having issues switching to Linux containers. 
Docker start with no issues, however when switching to Linux containers the following error pops up after about 3 minutes:

No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass28_0.<SwitchDaemon>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 305
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

When I open Hyper V I can see the Moby Linux VM running, network status is not connecting and heartbeat is showing no contact.  Please see the following images. 
![capture2](https://user-images.githubusercontent.com/45363706/49024851-b6dd1580-f19a-11e8-8afc-14b08db7ce7d.PNG)
![capture1](https://user-images.githubusercontent.com/45363706/49024858-ba709c80-f19a-11e8-9e56-e4793207546e.PNG)
![capture](https://user-images.githubusercontent.com/45363706/49024862-bcd2f680-f19a-11e8-8ade-c33c40e02dbe.PNG)

**Comment by chlumper** [comment]
Possible duplicate of #2404

**Comment by jgraygi** [comment]
+1
