### ISSUE TITLE
Error switching to Linux containers on Windows Insider build 14986

### ISSUE THREAD

**Issue by PatrickLang** [docker/for-win#299]
### Expected behavior
No errors switching to Linux containers

### Actual behavior
MobyLinuxVM seems to start, cpu usage looks good (unlike Windows build 14971)

```none
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

Diagnostic ID:
Upload seems to keep hanging and spinning docker.service at nearly 100% CPU. I don't have an ID :(

Versions:
```none
Version: 1.13.0-rc3-beta32 (9266)
Channel: Beta
Sha1: 3990397e132a10772955c122b0ca9258fdaf84ce
Started on: 2016/12/07 20:20:05.078
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise Insider Preview
Edition: Enterprise
Id: 1607
Build: 14986
BuildLabName: 14986.1000.amd64fre.rs_prerelease.161202-1928
```

### Steps to reproduce the behavior

  1. Update to Windows Insider fast build 14986
  2. Run Docker for windows
  3. Right click Docker icon and choose "Switch to Linux"

**Comment by PatrickLang** [comment]
Well, a reboot later it started working. I'll close this out.

```none
PS C:\Users\Patrick\Desktop> docker run busybox uname -a
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
56bec22e3559: Pull complete
Digest: sha256:29f5d56d12684887bdfa50dcd29fc31eea4aaf4ad3bec43daf19026a7ce69912
Status: Downloaded newer image for busybox:latest
Linux edb18d6cf9ef 4.8.12-moby #1 SMP Tue Dec 6 05:03:18 UTC 2016 x86_64 GNU/Linux
```
