### ISSUE TITLE
Docker simply doesn't start after installation

### ISSUE THREAD

**Issue by brighthero** [docker/for-win#30]
### Expected behavior
Docker starts after installation normally

### Actual behavior
Docker is stuck at "Docker is starting..."

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu is not possible, button doesn't seem to be working.

  - Log file excerpt: 
```
[21:15:13.801][DataKit        ][Info   ] +399626us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[21:15:13.800][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[21:15:14.777][DataKit        ][Info   ] 
[21:15:14.777][DataKit        ][Info   ] +1377411us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[21:15:14.778][Database       ][Info   ] Successfully wrote 9 value(s)
[21:15:14.779][HyperV         ][Info   ] Start
[21:15:14.780][PowerShell     ][Info   ] Run script with parameters: -Start True...
[21:15:14.841][HyperV         ][Info   ] Starting VM MobyLinuxVM...
``` 
The program then gets stuck after that and nothing happens (waited for 30 mins)

[log-2016-08-08_21-15-05.txt](https://github.com/docker/for-win/files/407569/log-2016-08-08_21-15-05.txt)

### Steps to reproduce the behavior

  1. Install Docker on windows (Version: 1.12.0-stable)
  2. Wait for Docker to start (tray icon: "Docker is starting..."

**Comment by rneugeba** [comment]
Thanks for your your report. I see the following in the logs:
```
[21:13:38.162][HyperV         ][Info   ] Starting VM MobyLinuxVM...
[21:13:38.295][NamedPipeServer][Error  ] Unable to execute Start: Failed to start VM "MobyLinuxVM": Hyper-V was unable to find a virtual machine with
name "MobyLinuxVM".    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.Run(String script, Dictionary`2 parameters, Action`1 lineReceived)
   at Docker.Backend.Backend.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass7_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[21:13:38.308][NamedPipeServer][Error  ] Pipe failure: Pipe is broken.    at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.WriteCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.Write(__BinaryWriter sout)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteSerializedStreamHeader(Int64 topId, Int64 headerId)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck
)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Run>b__0()
```
which does not look good. I also noticed that you are on Windows build 14393 which, while it work ok for us, some other users reported issues, in particular on #27 it was reported that potentially VMs created on the previous released build (10586) may not work. 

Could you try and install and install the application again. 
Thanks

**Comment by stephan7878** [comment]
Encountering this issue on both Windows 10 Version 1511 and Anniversary Edition.
Used both Docker Stable and Beta (22/23)

<pre><code>
Failed to start VM "MobyLinuxVM": 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID D8D9797C-4500-48F7-A128-940D8AB93E9B)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID D8D9797C-4500-48F7-A128-940D8AB93E9B).
   at Docker.Core.Pipe.NamedPipeClient.TrySend(String action, Object[] parameters)
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Core.Backend.BackendClient.Start(Settings settings)
   at Docker.Actions.DoStart(Settings settings, Boolean showWelcomeWindow)
   at Docker.Core.TaskQueue.<.ctor>b__16_0()
</code></pre>

docker version
<pre><code>
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      windows/amd64
Error response from daemon: An invalid argument was supplied.`
</code></pre>

Log
<pre><code>
[21:18:03.678][Program        ][Info   ] Version: 1.12.0-stable
[21:18:03.678][Program        ][Info   ] Starting on: 8/19/2016 9:18:03 PM
[21:18:03.678][Program        ][Info   ] Resources: C:\Program Files\Docker\Docker\Resources
[21:18:03.692][Program        ][Info   ] OS: Windows 10 Enterprise
[21:18:03.692][Program        ][Info   ] Edition: Enterprise
[21:18:03.692][Program        ][Info   ] Id: 1511
[21:18:03.692][Program        ][Info   ] Build: 10586
[21:18:03.692][Program        ][Info   ] BuildLabName: 10586.0.amd64fre.th2_release.151029-1700
[21:18:03.708][Program        ][Info   ] Sha1: 9cd1dc28d3ac81cb5177ff9728f65200304b36f6
[21:18:03.708][Program        ][Info   ] You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[21:18:04.489][TrackingStatus ][Info   ] Crash report and usage statistics are enabled
[21:18:04.520][Mixpanel       ][Info   ] Id: 2806CE0F-73D8-486A-9277-E5E82219E4A6
[21:18:04.630][Mixpanel       ][Info   ] Failed to upload an event and will retry later
[21:18:04.630][Mixpanel       ][Info   ] Usage Statistic: appLaunched
[21:18:04.692][Mixpanel       ][Info   ] Failed to upload an event and will retry later
[21:18:04.713][NamedPipeClient][Info   ] Sending Version()...
[21:18:04.723][NamedPipeClient][Info   ] Received response for Version
[21:18:04.723][Mixpanel       ][Info   ] Usage Statistic: heartbeat
[21:17:16.680][BackendServer  ][Info   ] Started
[21:18:04.723][NamedPipeServer][Info   ] Version()
[21:18:04.740][Mixpanel       ][Info   ] Failed to upload an event and will retry later
[21:18:04.723][NamedPipeServer][Info   ] Version done.
[21:18:05.114][NamedPipeClient][Info   ] Sending Stop()...
[21:18:05.114][Updater        ][Info   ] Checking for updates on channel Stable...
[21:18:05.114][NamedPipeServer][Info   ] Stop()
[21:18:05.114][HyperV         ][Info   ] Stop
[21:18:05.145][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[21:18:05.161][UpdateFeedDownloader][Error  ] The remote name could not be resolved: 'download.docker.com'
[21:18:05.161][Updater        ][Info   ] No update available
[21:18:09.817][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[21:18:09.833][NamedPipeClient][Info   ] Received response for Stop
[21:18:09.833][NamedPipeServer][Info   ] Stop done.
[21:18:09.833][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[21:18:09.833][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[21:18:09.848][HyperVGuids    ][Info   ] Installing GUIDs...
[21:18:09.848][HyperVGuids    ][Info   ] GUIDs installed
[21:18:09.864][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[21:18:10.583][Firewall       ][Info   ] Ports are opened
[21:18:10.583][HyperV         ][Info   ] Create
[21:18:10.583][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[21:18:11.348][HyperV         ][Info   ] Using existing Switch: DockerNAT
[21:18:11.817][HyperV         ][Info   ] Using existing Switch IP address
[21:18:11.958][HyperV         ][Info   ] Using existing: MobyLinuxVM
[21:18:12.083][HyperV         ][Info   ] Setting MobyLinuxVM vm CPUs to 2 and Memory to 2048 MB
[21:18:12.083][DataKit        ][Info   ] Starting...
[21:18:12.083][PowerShell     ][Info   ] Run script...
[21:18:12.270][DataKit        ][Info   ] Started
[21:18:12.288][VpnKit         ][Info   ] Starting...
[21:18:12.288][PowerShell     ][Info   ] Run script...
[21:18:12.678][DataKit        ][Info   ] 
[21:18:12.678][DataKit        ][Info   ] +8184us    Datakit  Starting com.docker.db.exe 16bb469 ...
[21:18:14.864][VpnKit         ][Info   ] Started
[21:18:14.864][ApiProxy       ][Info   ] Starting...
[21:18:14.864][PowerShell     ][Info   ] Run script...
[21:18:15.598][VpnKit         ][Info   ] com.docker.slirp.exe: Logging to stdout (stdout:true DEBUG:false)
[21:18:15.598][VpnKit         ][Info   ] com.docker.slirp.exe: Setting handler to ignore all SIGPIPE signals
[21:18:15.598][VpnKit         ][Info   ] com.docker.slirp.exe: vpnkit version %VERSION% with hostnet version local %HOSTNET_PINNED% uwt version 0.0.3 hvsock version 0.10.0 %HVSOCK_PINNED%
[21:18:15.614][VpnKit         ][Info   ] com.docker.slirp.exe: starting port_forwarding port_control_url:hyperv-connect://d8d9797c-4500-48f7-a128-940d8ab93e9b max_connections:None vsock_path:
[21:18:15.614][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to d8d9797c-4500-48f7-a128-940d8ab93e9b:0B95756A-9985-48AD-9470-78E060895BE7
[21:18:15.614][VpnKit         ][Debug  ] com.docker.slirp.exe: Waiting for connections on socket hyperv-connect://d8d9797c-4500-48f7-a128-940d8ab93e9b
[21:18:15.614][VpnKit         ][Warning] com.docker.slirp.exe: no database: using hardcoded network configuration values
[21:18:15.614][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to d8d9797c-4500-48f7-a128-940d8ab93e9b:30D48B34-7D27-4B0B-AAAF-BBBED334DD59
[21:18:15.630][VpnKit         ][Debug  ] com.docker.slirp.exe: Waiting for connections on socket hyperv-connect://d8d9797c-4500-48f7-a128-940d8ab93e9b
[21:18:16.755][ApiProxy       ][Info   ] Started
[21:18:16.770][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/exclude
[21:18:16.770][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/http
[21:18:16.770][Database       ][Info   ] Removing com.docker.driver.amd64-linux/proxy/https
[21:18:17.286][ApiProxy       ][Info   ] docker proxy (on deprecated port): ready
[21:18:17.302][ApiProxy       ][Info   ] dns server: ready
[21:18:17.302][ApiProxy       ][Info   ] docker proxy: ready
[21:18:17.695][DataKit        ][Info   ] 
[21:18:17.697][DataKit        ][Info   ] +5022282us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[21:18:19.602][Database       ][Info   ] Successfully removed 3 value(s)
[21:18:19.605][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[21:18:19.614][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[21:18:19.620][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[21:18:19.625][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[21:18:19.636][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/resolv.conf=nameserver 10.0.75.1
[21:18:19.639][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[21:18:19.641][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[],"debug":false}
[21:18:19.644][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[21:18:19.647][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[21:18:20.798][Database       ][Info   ] Successfully wrote 9 value(s)
[21:18:20.800][DataKit        ][Info   ] 
[21:18:20.803][DataKit        ][Info   ] +8127016us       fs9p [ERROR] dispatcher caught Unix.Unix_error(Unix.EPIPE, "bytes_read", ""): no more requests will be handled
[21:18:20.801][HyperV         ][Info   ] Start
[21:18:20.814][PowerShell     ][Info   ] Run script with parameters: -Start True...
[21:18:21.415][HyperV         ][Info   ] Starting VM MobyLinuxVM...
[21:18:26.533][NamedPipeServer][Error  ] Unable to execute Start: Failed to start VM "MobyLinuxVM": 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID D8D9797C-4500-48F7-A128-940D8AB93E9B)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID D8D9797C-4500-48F7-A128-940D8AB93E9B).    at System.Management.Automation.Interpreter.ThrowInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
[21:18:26.608][NamedPipeClient][Error  ] Unable to send Start: Failed to start VM "MobyLinuxVM": 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID D8D9797C-4500-48F7-A128-940D8AB93E9B)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID D8D9797C-4500-48F7-A128-940D8AB93E9B).
[21:18:26.612][NamedPipeClient][Info   ] Sending CheckInstallation()...
[21:18:26.618][NamedPipeServer][Info   ] CheckInstallation()
[21:18:26.624][HyperV         ][Info   ] Check Hyper-V Windows optional feature
[21:18:26.628][PowerShell     ][Info   ] Run script...
[21:18:30.158][HyperV         ][Info   ] Hyper-V Windows feature is enabled
[21:18:30.167][NamedPipeClient][Info   ] Received response for CheckInstallation
[21:18:30.172][NamedPipeClient][Info   ] Sending CheckHyperVState()...
[21:18:30.162][NamedPipeServer][Info   ] CheckInstallation done.
[21:18:30.176][NamedPipeServer][Info   ] CheckHyperVState()
[21:18:30.180][HyperV         ][Info   ] Check Hyper-V State
[21:18:30.185][PowerShell     ][Info   ] Run script with parameters: -Check True...
[21:18:31.199][HyperV         ][Info   ] Hyper-V is running
[21:18:31.210][NamedPipeClient][Info   ] Received response for CheckHyperVState
[21:18:31.204][NamedPipeServer][Info   ] CheckHyperVState done.
[21:18:31.217][Notifications  ][Error  ] Failed to start VM "MobyLinuxVM": 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID D8D9797C-4500-48F7-A128-940D8AB93E9B)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID D8D9797C-4500-48F7-A128-940D8AB93E9B).
[21:19:13.314][ErrorReportWindow][Info   ] Open logs
</code></pre>

The Microsoft-Windows-Hyper-V-VMMS/Admin Event Logs:
<pre><code>
The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID D8D9797C-4500-48F7-A128-940D8AB93E9B).
</code></pre>

As well as:
<pre><code>
The virtual machine bus is not running.
</code></pre>

Tried <code>sc config vmbus start= system</code> and <code>sc config vmbus start= demand</code> but it did not resolve the issue.

**Comment by rneugeba** [comment]
@stephan7878 thanks for the updates. 

So you were running Docker for Windows in a Window 10 Pro VM on top of Hyper-V with nested virt? I've seen reports that window's nested virt might not be quite ready for prime time yet.

From your updates, it looks like you are now all up and running, so I close this issue for now. Feel free to re-open (or open another issue) should you have more issues.

**Comment by stephan7878** [comment]
@rneugeba - yes that is correct and I did manage to get it working 100% with Beta 23.

1. Install Windows 10 in a Hyper-V VM
2. Disable dynamic memory and enable nested virtualization:
`Set-VMProcessor -VMName <VMName> -ExposeVirtualizationExtensions $true`
`Set-VMMemory -VMName <VMName> -DynamicMemoryEnabled $false`
3. Install Docker for Windows Beta 23

**Comment by rneugeba** [comment]
Thanks for the confirmation. In general we don't recommend using nested virt as the support with most hypervisors is not mature enough

**Comment by ARKAFAJ** [comment]
I have docker for windows beta, installed using the msi package from the docker-for-windows page.
However it is not starting and is showing an error insufficient memory. I have reduced the virtual machine memory to 512 mb. still it is not working. i am a very beginner in using these tools. it will be a grat help if someone could help me in this. Thanks in advance

**Comment by jgahlawat** [comment]
Have you enabled NUMA spanning in your HyperV settings?  if not enable it i bet that will solve your issue.

  By default, Windows Server enables NUMA spanning, which provides the most flexibility as virtual machines (VMs) can access and use memory in any NUMA node. But it may result in lower performance compared to forcing VMs to use memory on the same NUMA node as the processor cores. 

By disabling NUMA spanning, you ensure that VMs use memory and processor cores in the same NUMA node, giving the best performance. 
 This should only be changed once, if, as an administrator, you feel comfortable with NUMA and the implications of disabling and also if you have some additional management suite that can help ensure best configuration.

 To configure NUMA spanning, open the Hyper-V Settings and select the NUMA Spanning option and disable it, I am sure, it will get solved; I struggled with the issue for a week and resolved it by disabling NUMA.

I am sure this would be marked as resolved by disabling NUMA in Hyper-V Manager.
