### ISSUE TITLE
Docker is not able to start after update to the Latest Stable Win64

### ISSUE THREAD

**Issue by JimmyWarHammer** [docker/for-win#3021]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
3C148D25-722E-4EAA-9E4B-82F64F313C63/20181203114254

### Expected behavior
After update Docker starts in regular manner

### Actual behavior
Docker is not able to start
Backend service is not installed
   at Docker.WPF.BackendClient.CheckService(String action) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 291
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 167
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 90
   at Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 155
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information
  - Windows Version:
Microsoft Windows [Version 10.0.17134.407]
x64 

  - Docker for Windows Version:
Version 2.0.0.0-win81 (29211)
Channel: stable
Build: 4271b9e

### Steps to reproduce the behavior

  1. Update Docker to the latest Stable
  2. Restart the PC
  3. Get an error while trying to start Docker

**Comment by chrisjasp** [comment]
I'm able to reproduce this issue. Also seeing it on Docker for Windows Version 2.0.0.0-win82. It appears that in my case the HyperV machine is removed and never recreated along with the virtual switch.

**Comment by rtice-csod** [comment]
I had the same issue (diagnostic ID DDDDE2BE-5E0B-4F5B-B9BA-DCACECCF94AB/20181204173243 ) but I was able to resolve the issue by doing the following:
1) uninstall docker
2) stop/start the HyperV service
3) creating an Ubuntu 18.04 VM via quick create successfully
4) reinstalling docker, now the Moby VM showed up correctly.

What led me down this path was that I noticed that creating a VM directly in HyperV was also failing.
