### ISSUE TITLE
New Version docker always crash

### ISSUE THREAD

**Issue by sximenes** [docker/for-win#3022]
E8E9F68D-AEB8-4DC6-8234-34E860CA13B5/20181203174530
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/json?all=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.
at New-MobyLinuxVM, : line 191
at , : line 411
at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
at Docker.Actions.<>c__DisplayClass19_0.b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by sximenes** [comment]
E8E9F68D-AEB8-4DC6-8234-34E860CA13B5/20181203174530
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/json?all=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by sximenes** [comment]
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.
at New-MobyLinuxVM, <No file>: line 191
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by elizeugba** [comment]
I'm having the same problem.

**Comment by AlanRNZ** [comment]
Ditto. 58AEED1E-C88C-41A4-BCA7-BFF2006BAA40/20181207100828

**Comment by ssameerr** [comment]
I am in the same Titanic : 
Diagnostic ID : 560CAFA3-8A61-4711-B257-44351897F393/20181207194813

**Comment by savbace** [comment]
Workaround: **stop/start Hyper-V service** helped me - after doing this Docker has started successfully.

![Image of Yaktocat](https://cdn.pbrd.co/images/HTF6XSj.png)

**Comment by kjeldflarup** [comment]
I experienced this today first time I started docker desktop ever.
After yet a restart the error was gone.

**Comment by kaisellgren** [comment]
I resolved this by opening Hyper-V Manager, pressing "Stop service" and "Restart" then I tried to switch to Linux Containers and it worked.
