### ISSUE TITLE
Docker not starting after update to 2.0.0

### ISSUE THREAD

**Issue by CodeMaven** [docker/for-win#3042]
- [ X] I have tried with the latest version of my channel (Stable or Edge)
  - [ X] I have uploaded Diagnostics
  - Diagnostics ID: 2405D3FD-B2D6-4855-A45A-C586353625AB/20181206133906
  - also: 2405D3FD-B2D6-4855-A45A-C586353625AB/20181206131422

### Expected behavior
Docker should start

### Actual behavior
Docker crashes when starting

### Information
Was previously on docker CE 18.06.1-ce-win73. Upon updating to 2.0.0 Docker no longer starts. The icon is red and there is an exception in the logs. Tried both stable and edge channels. Restarted computer multiple times.

 at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\edge-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59 

  - Windows Version 10:
  - Docker for Windows Version: 2.0.0.0-win78

### Steps to reproduce the behavior
Just start docker.

**Comment by narigon** [comment]
Hi, I have the same issue and now I'm unable to continue working on my machine.

Is there an ETA for a fix for this?

**Comment by CodeMaven** [comment]
I was able to get it working again by doing a factory reset on docker, but I lost all of my containers which was rather a bothersome setback... At least it works now and I was able to rebuild the oracle database that I had in my container from backkups.

**Comment by jhubsharp** [comment]
I've had this same problem. Various rounds of restarts and occasionally factory resetting Docker makes it go away, but it returns after a few days. Currently finding myself having to factory reset every few days.
