### ISSUE TITLE
Docker for Windows daemon cannot start

### ISSUE THREAD

**Issue by jordannielson** [docker/for-win#3043]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 31F1DCC9-9015-4D3D-A22F-5A18E97F5C3E/20181206150544

### Expected behavior
Docker daemon is able to start successfully and respond to commands like 'docker ps' or 'docker run hello-world'

### Actual behavior
Docker daemon fails to start and gives an error.  Docker commands requiring the daemon also fail and give and error.

### Information

The problem is reproducible every time.  Including after re-installing.  The problem appeared right after first install.

  - Windows Version: 10.0.17134 Build 17134
  - Docker for Windows Version: 2.0.0.0-win81 (29211), Channel: stable, Build: 4271b9e

Error given by starting docker:
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 48639AE0-A04E-47F9-9405-7CAB70690235)

'MobyLinuxVM' failed to start worker process: Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source. (0xC0000428). (Virtual machine ID 48639AE0-A04E-47F9-9405-7CAB70690235)
at Start-MobyLinuxVM, <No file>: line 296
at <ScriptBlock>, <No file>: line 412
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Steps to reproduce the behavior

  1. Quit Docker Desktop
  2. Run Docker For Windows (Desktop)

**Comment by ngie-eign** [comment]
Might be related to #1348.
