### ISSUE TITLE
BugSnag appears to not be working.

### ISSUE THREAD

**Issue by jtnord** [docker/for-win#305]
### Expected behavior

On a crash a bugsnap bundle is uploaded and ther eare not errors about uploading in the log file

### Actual behavior

Errors related to bugsnag are in the log file which to me implies the bugsnag report was not uploaded.

```
[13:57:35.461][GUI            ][Info   ] Sending Bugsnag report 87c7e5d8-5c02-4808-b02b-2fb70a44226b...
[13:57:35.462][GUI            ][Error  ] The type initializer for 'Bugsnag.Notifier' threw an exception.
[13:57:35.462][GUI            ][Error  ]    at Bugsnag.NotificationFactory.CreateNotificationBase()
   at Bugsnag.NotificationFactory.CreateFromError(Event error)
   at Bugsnag.Notifier.Send(Event errorEvent)
   at Docker.WPF.Crash.BugSnag.Notify(Exception exception)
[13:57:35.462][GUI            ][Error  ] Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
[13:57:35.462][GUI            ][Error  ]    at Bugsnag.Notifier..cctor()
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu. `4C36067F-0848-4ECE-B0F4-887DD80EA81B/2016-12-09_14-00-42`
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

```
Version: 1.13.0-rc3-beta32 (9266)
Channel: Beta
Sha1: 3990397e132a10772955c122b0ca9258fdaf84ce
Started on: 2016/12/09 13:41:21.726
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
```
### Steps to reproduce the behavior

  1. Do something that docker is unhappy about (see #304)
  2. in the crash report check the "log" link and look at the last output.

**Comment by rneugeba** [comment]
@dgageot @jeanlaurent can you take a look at what's happening here?

**Comment by dgageot** [comment]
@simonferquel ^^

**Comment by simonferquel** [comment]
Hmm acknowledged, i'll hotfix on monday :(

**Comment by dgageot** [comment]
@jtnord This should be fixed in Beta33 released today. PTAL

**Comment by rneugeba** [comment]
closing since I haven't seen any issues with this in any diagnostics I looked at since. @jtnord please re-open if you still see the issue

**Comment by jtnord** [comment]
@dgageot not sure how I can test without crashing Docker - and upgrading fixed the crash I reported in #304 - will re-open if I see it again.
