### ISSUE TITLE
Docker stable on Windows 10 inside VMWare fails to start

### ISSUE THREAD

**Issue by sutrap** [docker/for-win#3057]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 13E44FED-88A9-4982-8D44-E37D4BD12EB8/20181208005600

### Expected behavior
Docker should start on Bootup.
It fails to start Linux Containers.

### Actual behavior
Error:
No activity detected on VM, aborting
   bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:Zeile 36.
   bei Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 92.
   bei Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:Zeile 74.
   bei Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:Zeile 59.
### Information
Tried to run it on stable and Edge, Always the same Problem.

  - Windows Version: Windows 10 Version 1809 ( Build 17763.134)
  - Docker for Windows Version:  Version 2.0.0.0-win81 (29211)

### Steps to reproduce the behavior
Standard install

**Comment by Dexu5** [comment]
I'm facing similar issue while running docker in windows VM. For me, it throws the following error.

`   
   Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Modifying the properties of the device 'Memory' failed.

The operation cannot be performed while the object is in its current state.
at New-MobyLinuxVM, <No file>: line 206
at <ScriptBlock>, <No file>: line 411
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 255
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 189
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180`
