### ISSUE TITLE
Unable to send Start: No activity detected on VM, aborting

### ISSUE THREAD

**Issue by naymore** [docker/for-win#3060]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7D03127D-261D-4C80-B12D-A9FDFEC98518/20181208130213

### Expected behavior
Docker for Windows with working Linux containers

### Actual behavior
No Linux containers

### Information
Windows Version: Windows Server 2016, Version 1607 (OS Build 14393.2639)
Docker for Windows Version: Version 2.0.0.0-win81 (29211), Channel: stable, Build: 4271b9e
First and fresh installation of docker for windows. Reproducable error.
Factory reset doesn't help.

### Steps to reproduce the behavior
Download, Install -> voilà.
At some point an error message pops up:

`
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 155
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
`

## Important to know.. ##
This is a nested virtualization setup (see https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-for-windows-in-nested-virtualization-scenarios)

Physical Host is running Windows 10 (1803) + Xeon E3 v3 + H87 chipset (VT-d is supported)
Hyper-V VM (Gen. 1) is running Windows Server 2016 (1607)
I did enable Virtualization Features for the nested VM `Set-VMProcessor -VMName Name-ExposeVirtualizationExtensions $true`

The documentation says nested virtualization is NOT supported - it may work or not.
Is the error I am facing related to nested virtualization? Is there any hope for my setup? :)

**Comment by mattftw** [comment]
I was able to get around this issue by creating an instance with docker-machine (by following the steps linked here) https://docs.docker.com/machine/drivers/hyper-v/
then running `docker-machine env vm | Invoke-Expression`

Not a real solution by any means, but at least i can use docker within windows now.

Other things to note however probably unrelated is that my hypervisor is esxi 6.7
