### ISSUE TITLE
The VM couldn't get an IP address after 60 tries 

### ISSUE THREAD

**Issue by icezimo** [docker/for-win#307]
Hi, I have some problems about docker. I have read the issue about this problem but i can't fix it. I have reinstalled docker and hyper-v but it doesn't work.

**Expected behavior**

To get docker to start, after upgrade to 1.12.3 from 1.12.1.

**Actual behavior**
Unable to start: The VM couldn't get an IP address after 60 tries
at Fatal, <No file>: line 353
at Start-MobyLinuxVM, <No file>: line 267
at <ScriptBlock>, <No file>: line 363
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

Information

Diagnostic ID : 1F35C5D6-8C3D-4A9A-A630-941D9D9E0841/2016-12-09_23-39-04

Docker Version: Docker version 1.12.3, build d63ec34 (stable)

Windows version, build number: Windows 10 Pro

**Steps to reproduce the behavior**

1. Start up windows and docker but docker take more time than usual to start  .
2. docker send error message .

**Comment by justincormack** [comment]
Have you tried the beta channel? This has some fixes that may help, and will be promoted to stable later.

**Comment by icezimo** [comment]
@justincormack thanks, i will try it. =))
