### ISSUE TITLE
Docker for windows is not running - showing Unknown error (0xffffffff)

### ISSUE THREAD

**Issue by Rudra815** [docker/for-win#3084]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 28FE1938-DE07-4B49-8AEE-6ECC86459E3A/20181212204550

### Expected behavior
successful running
### Actual behaviour -- giving below error
Unknown error (0xffffffff)
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at Docker.Core.Cmd.AskForElevated(String filename, String arguments) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\Cmd.cs:line 83
   at Docker.WPF.BackendClient.CheckService(String action) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 302
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 167
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 90
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
### Information

  - Windows Version: Windows OS 10 Pro
  - Docker for Windows Version: Windows OS 10 Pro

### Steps to reproduce the behaviour
Click on start button on Docker for windows desktop icon

  1. ...
  2. ...

**Comment by Rudra815** [comment]
can anyone help me on this please...
