### ISSUE TITLE
Docker fails to start with an error after message 'Connect Internal Switch DockerNAT'

### ISSUE THREAD

**Issue by jasonwzs** [docker/for-win#315]
### Expected behavior
Docker start successfully

### Actual behavior
Docker fails to start

### Information
This is the snippet of log file containing the error message:
[16:31:02.204][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[16:31:03.950][HyperV         ][Info   ] Using existing Switch: DockerNAT
[16:31:04.237][HyperV         ][Info   ] Using existing Switch IP address
[16:31:04.292][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[16:31:04.928][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[16:31:05.186][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'AM-ZHWEN-W1' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
at New-MobyLinuxVM, <No file>: line 242
at <ScriptBlock>, <No file>: line 362    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[16:31:05.314][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'AM-ZHWEN-W1' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
at New-MobyLinuxVM, <No file>: line 242
at <ScriptBlock>, <No file>: line 362
[16:31:05.325][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'AM-ZHWEN-W1' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
at New-MobyLinuxVM, <No file>: line 242
at <ScriptBlock>, <No file>: line 362

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
E6976385-6FEA-462C-A74A-7C6A430A9D35/2016-12-12_16-36-11
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
N/A
  - host distribution and version (Windows version, build number, etc)
Edition: Windows 10 Enterprise
Version: 1511
OS Build: 10586.545

### Steps to reproduce the behavior
It was working fine before I tried to run minikube with hyper-v driver on same machine
  1. Install Docker for windows
  2. Start Docker
  3. Install minikube
  4. Start minikube with hyperv driver but without creating an external virtual switch
  5. Docker is stopped with an error
After that, Docker always fails to start. I tried to reinstall hyper-v and Docker but it still does not work.

**Comment by friism** [comment]
@jasonwzs can you try a factory reset?

**Comment by wentaozhu** [comment]
Yes. Factory reset is okay. But I need to revise the daemon configuration to use, such as 
 "storage-opt": "d:\\docker",
  "graph": "d:\\docker",
"storage-opt": [
    {
      "DM.basesize": "50G"
    }
.
Then the docker will restart and face the same issue.

**Comment by wentaozhu** [comment]
My configure file is wrong. Sorry.

**Comment by dgageot** [comment]
@jasonwzs @wentaozhu Can we close the issue then?

**Comment by jasonwzs** [comment]
I tried factory reset, but it didn't work.

**Comment by friism** [comment]
What happens if you try to start the Moby VM manually using Hyper-V manager?

**Comment by jasonwzs** [comment]
It can be started manually using hyperv manager but no ip address is assigned

**Comment by sendit2me** [comment]
Was getting a similar error, basically deleted the Docker NAT in the switches, 
there was no MobyLinuxVM created, but this was created, and the NAT, when I reset to factory defaults.

see also https://github.com/docker/for-win/issues/331

**Comment by jasonwzs** [comment]
I finally get it working by using the following workaround:
In resources\MobyLinux.ps1, comment the line $vm | Set-VMFirmware -EnableSecureBoot Off -BootOrder $vm.DVDDrives, replace it with following two lines:
$iso = $vm | Get-VMFirmware | select -ExpandProperty BootOrder | where {$_.FirmwarePath.EndsWith("Scsi(0,1)")}
$vm | Set-VMFirmware -EnableSecureBoot Off -FirstBootDevice $iso

It's still unclear why it was working before and suddenly couldn't be restarted after I tried to run minikube using docker NAT

**Comment by rneugeba** [comment]
@jasonwzs glad it worked for you. Looks like another case where #216 would have helped...

@dgageot maybe we should change the script. WDYT?

**Comment by rneugeba** [comment]
Closing. Seems to be fixed. Please re-open if the issue persists.

**Comment by jasonwzs** [comment]
How can I reopen this issue? The workaround works but I have to apply this workaround every time when docker is upgraded to a new version. We need an official fix for this issue (same as #216)

**Comment by rneugeba** [comment]
@jasonwzs Thanks for the feedback. I've created an internal tracking issue for this.

**Comment by rneugeba** [comment]
Closing this in favour of #400 which also has an internal tracking issue. @jasonwzs I've tagged you on that issue, so that you should get updates
