### ISSUE TITLE
Docker not starting (no activity on VM)

### ISSUE THREAD

**Issue by toelke** [docker/for-win#3210]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C8AF8EAA-1EF1-45D1-AEBA-1E620545881A/20190111085044

### Expected behavior

I expect docker to start after rebooting the computer.

### Actual behavior

The vm starts, in the log I can see that the linux-machine boots completely, docker waits for a few minutes and then stops the machine.

```
[09:43:28.629][Moby           ][Info   ] Welcome to LinuxKit
[09:43:28.631][Moby           ][Info   ]                         ##         .
[09:43:28.633][Moby           ][Info   ]                   ## ## ##        ==
[09:43:28.635][Moby           ][Info   ]                ## ## ## ## ##    ===
[09:43:28.637][Moby           ][Info   ]            /"""""""""""""""""\___/ ===
[09:43:28.639][Moby           ][Info   ]           {                       /  ===-
[09:43:28.641][Moby           ][Info   ]            \______ O           __/
[09:43:28.643][Moby           ][Info   ]              \    \         __/
[09:43:28.645][Moby           ][Info   ]               \____\_______/
[09:43:28.667][Moby           ][Info   ] Welcome to LinuxKit
[09:43:28.688][Moby           ][Info   ]                         ##         .
[09:43:28.707][Moby           ][Info   ]                   ## ## ##        ==
[09:43:28.726][Moby           ][Info   ]                ## ## ## ## ##    ===
[09:43:28.746][Moby           ][Info   ]            /"""""""""""""""""___/ ===
[09:43:28.768][Moby           ][Info   ]           {                       /  ===-
[09:43:28.786][Moby           ][Info   ]            ______ O           __/
[09:43:28.802][Moby           ][Info   ]                           __/
[09:43:28.818][Moby           ][Info   ]               ___________/
[09:43:28.822][Moby           ][Info   ] linuxkit-00155d670bc9 login: root (automatic login)
[09:43:28.826][Moby           ][Info   ] Welcome to LinuxKit!
[09:43:28.828][Moby           ][Info   ] NOTE: This system is namespaced.
[09:43:28.832][Moby           ][Info   ] The namespace you are currently in may not be the root.
[09:43:28.835][Moby           ][Info   ] System services are namespaced; to access, use `ctr -n services.linuxkit ...`
[09:43:28.837][Moby           ][Info   ] login[759]: root login on 'ttyS0'
[09:43:29.129][Moby           ][Info   ] linuxkit-00155d670bc9:~# 2019-01-11T09:43:28Z,onboot.000-metadata;2019/01/11 09:43:28 Trying CDROM /dev/sr0
[09:43:29.133][Moby           ][Info   ] 2019-01-11T09:43:28Z,onboot.000-metadata;2019/01/11 09:43:28 Trying CDROM /dev/sr1
[09:43:29.138][Moby           ][Info   ] 2019-01-11T09:43:28Z,onboot.000-metadata;2019/01/11 09:43:28 CDROM /dev/sr1: Probe succeeded
[09:43:29.164][Moby           ][Info   ] [    4.787465] IPVS: Creating netns size=2104 id=1
[09:43:29.169][Moby           ][Info   ] [    4.791652] IPVS: ftp: loaded support on port[0] = 21
[09:43:29.333][Moby           ][Info   ] [    4.955992] random: crng init done
[09:43:29.970][Moby           ][Info   ] [    5.592554] IPVS: Creating netns size=2104 id=2
[09:43:29.975][Moby           ][Info   ] [    5.597562] IPVS: ftp: loaded support on port[0] = 21
[09:43:30.970][Moby           ][Info   ] [    6.593554] IPVS: Creating netns size=2104 id=3
[09:43:30.975][Moby           ][Info   ] [    6.597703] IPVS: ftp: loaded support on port[0] = 21
[09:43:31.660][Moby           ][Info   ] 2019-01-11T09:43:30Z,onboot.004-format;2019/01/11 09:43:30 /dev/sda has content. blkid returned: /dev/sda: PTUUID="4f66d6e3" PTTYPE="dos"
[09:43:31.666][Moby           ][Info   ] 2019-01-11T09:43:30Z,onboot.004-format;2019/01/11 09:43:30 No eligible disks found
[09:43:32.223][Moby           ][Info   ] [    7.843488] IPVS: Creating netns size=2104 id=4
[09:43:32.228][Moby           ][Info   ] [    7.850991] IPVS: ftp: loaded support on port[0] = 21
[09:44:15.538][Moby           ][Info   ] [   51.159942] hv_balloon: Received INFO_TYPE_MAX_PAGE_CNT
[09:44:15.542][Moby           ][Info   ] [   51.164788] hv_balloon: Data Size is 8
[09:46:15.573][Linux          ][Error  ] Failed to start: No activity detected on VM, aborting. Let's retry
[09:46:15.629][HyperV         ][Info   ] Hyper-V is running
[09:46:15.629][PowerMode      ][Info   ] Stop
[09:46:15.630][HyperV         ][Info   ] Stop
[09:46:15.630][PowerShell     ][Info   ] Run script with parameters: -Stop True
[09:46:15.652][HyperV         ][Info   ] Script started at 09:46:15.652
[09:46:15.661][HyperV         ][Info   ] Modules loaded at 09:46:15.661
[09:46:15.712][HyperV         ][Info   ] Stopping VM MobyLinuxVM...
[09:46:18.721][Moby           ][Info   ] [  174.337232] hv_utils: Shutdown request received - graceful shutdown initiated
```

And get this error message:

```
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

### Information

The last version of docker I could use stably was 18.03.1-ce-win65 (17513); that however stopped working this week, I assume due to a Windows-Update.

My problem is with all later versions, if I move the disk of the linux-vm to a different drive (a HDD to not fill my SSD) and resize it.

I can reproduce this behavior on at least three machines.

### Steps to reproduce the behavior

1. Install Docker for Windows.
2. Change the location of the vhdx to d:\MobyLinuxVM.vhdx and resize to 240GB
3. Do something in a container that uses ~100GB of space in a named volume (I build a linux-distribution)
4. Reboot windows

**Comment by Ravenwater** [comment]
I got an update notification this morning to build 30090 and that completely hosed the system. Same type of behavior of Kubernetes never getting out of the 'starting' phase. Followed the suggestions of blowing away .kube directory in $USER, opening firewall to vpnnet and setting a fixed DNS address to no avail. 

I ended up uninstalling and reinstalling Docker Desktop. Version 2.0.0.0-win81 (29211) Build 4271b9e came up successfully.

**Comment by toelke** [comment]
The first boot after re-installation is almost always successfully; as is any boot after deleting the vhdx.

**Comment by toelke** [comment]
I tried build 30090 and it also just sits at

```
[08:42:36.788][Moby           ][Info   ] Welcome to LinuxKit
[08:42:36.792][Moby           ][Info   ]                         ##         .
[08:42:36.794][Moby           ][Info   ]                   ## ## ##        ==
[08:42:36.797][Moby           ][Info   ]                ## ## ## ## ##    ===
[08:42:36.799][Moby           ][Info   ]            /"""""""""""""""""\___/ ===
[08:42:36.803][Moby           ][Info   ]           {                       /  ===-
[08:42:36.806][Moby           ][Info   ]            \______ O           __/
[08:42:36.808][Moby           ][Info   ]              \    \         __/
[08:42:36.811][Moby           ][Info   ]               \____\_______/
[08:42:36.837][Moby           ][Info   ] Welcome to LinuxKit
[08:42:36.866][Moby           ][Info   ]                         ##         .
[08:42:36.894][Moby           ][Info   ]                   ## ## ##        ==
[08:42:36.922][Moby           ][Info   ]                ## ## ## ## ##    ===
[08:42:36.950][Moby           ][Info   ]            /"""""""""""""""""___/ ===
[08:42:36.983][Moby           ][Info   ]           {                       /  ===-
[08:42:37.012][Moby           ][Info   ]            ______ O           __/
[08:42:37.035][Moby           ][Info   ]                           __/
[08:42:37.055][Moby           ][Info   ]               ___________/
[08:42:37.061][Moby           ][Info   ] docker-desktop login: root (automatic login)
[08:42:37.066][Moby           ][Info   ] Welcome to LinuxKit!
[08:42:37.070][Moby           ][Info   ] NOTE: This system is namespaced.
[08:42:37.075][Moby           ][Info   ] The namespace you are currently in may not be the root.
[08:42:37.081][Moby           ][Info   ] System services are namespaced; to access, use `ctr -n services.linuxkit ...`
[08:42:37.086][Moby           ][Info   ] login[759]: root login on 'ttyS0'
[08:42:37.149][Moby           ][Info   ] docker-desktop:~# [    6.214381] random: crng init done
[08:42:37.468][Moby           ][Info   ] 2019-01-14T08:42:36Z,onboot.000-metadata;2019/01/14 08:42:36 Trying CDROM /dev/sr0
[08:42:37.473][Moby           ][Info   ] 2019-01-14T08:42:36Z,onboot.000-metadata;2019/01/14 08:42:36 Trying CDROM /dev/sr1
[08:42:37.480][Moby           ][Info   ] 2019-01-14T08:42:36Z,onboot.000-metadata;2019/01/14 08:42:36 CDROM /dev/sr1: Probe succeeded
[08:42:37.515][Moby           ][Info   ] [    6.579567] IPVS: Creating netns size=2104 id=1
[08:42:37.523][Moby           ][Info   ] [    6.584773] IPVS: ftp: loaded support on port[0] = 21
[08:42:38.528][Moby           ][Info   ] [    7.592205] IPVS: Creating netns size=2104 id=2
[08:42:38.535][Moby           ][Info   ] [    7.598029] IPVS: ftp: loaded support on port[0] = 21
[08:42:39.499][Moby           ][Info   ] [    8.563028] IPVS: Creating netns size=2104 id=3
[08:42:39.509][Moby           ][Info   ] [    8.569674] IPVS: ftp: loaded support on port[0] = 21
[08:42:39.805][Moby           ][Info   ] 2019-01-14T07:42:39Z,onboot.004-format;2019/01/14 07:42:39 /dev/sda has content. blkid returned: /dev/sda: PTUUID="0dbcffc7" PTTYPE="dos"
[08:42:39.811][Moby           ][Info   ] 2019-01-14T07:42:39Z,onboot.004-format;2019/01/14 07:42:39 No eligible disks found
[08:42:40.407][Moby           ][Info   ] [    9.471998] IPVS: Creating netns size=2104 id=4
[08:42:40.413][Moby           ][Info   ] [    9.477502] IPVS: ftp: loaded support on port[0] = 21
[08:43:22.496][Moby           ][Info   ] [   51.560490] hv_balloon: Received INFO_TYPE_MAX_PAGE_CNT
[08:43:22.500][Moby           ][Info   ] [   51.565726] hv_balloon: Data Size is 8
```

for a few minutes before timing out:

```
[08:45:22.506][Linux          ][Error  ] Failed to start: No activity detected on VM, aborting. Let's retry
[08:45:22.535][Installer      ][Info   ] Checking for features: *Hyper-V*, Containers
```

**Comment by Ravenwater** [comment]
On my system, build 30090 did not work. I went back and got the stable release version as of Jan 11:

Version 2.0.0.0-win81 (29211)
Channel: stable
Build: 4271b9e

The fact that this failure occurs frequently and resolutions vary is super-frustrating. Wish some of the Docker design engineers weighted in with some real insights and resolutions in this matter.

**Comment by toelke** [comment]
For me this failure has been introduced in the version after 18.03.1-ce-win65 (17513) and has persited ever since. I found no way of resolve it, yet (apart from using 18.03.1-ce-win65 (17513))

**Comment by toelke** [comment]
I opened #3260 with further information that could be more helpful in tracking my issue down.
