### ISSUE TITLE
Hyper-V was unable to find a virtual switch with name "DockerNAT".

### ISSUE THREAD

**Issue by bbodenmiller** [docker/for-win#324]
### Expected behavior

For Docker to actually start

### Actual behavior

Error

```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 123
at <ScriptBlock>, <No file>: line 362
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

Crash ID C48B068A-5C27-4F79-AF10-F7EB3615E5EF/2016-12-15_11-10-48

### Steps to reproduce the behavior

  1. Install Docker
  1. Docker fails

Worth noting I previously had the issues at https://github.com/docker/for-win/issues/260 which I fixed and it worked for a few days then this issue started.

**Comment by bbodenmiller** [comment]
Indeed it looks like the switch is not being created properly by Docker?

```
PS C:\WINDOWS\system32> Get-NetAdapter

Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Ethernet                  Intel(R) Ethernet Connection I218-LM          7 Disconnected EC-F4-BB-45-94-CE          0 bps
Local Area Connection* 6  Juniper Networks Virtual Adapter              4 Up           02-05-85-7F-EB-80         2 Gbps
Wi-Fi                     Intel(R) Dual Band Wireless-AC 7260           5 Up           A0-A8-CD-5D-D0-FE     144.4 Mbps
```

**Comment by bbodenmiller** [comment]
```powershell
PS C:\WINDOWS\system32> powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -destroy
VM MobyLinuxVM does not exist
Destroying Switch DockerNAT...
Removing VM MobyLinuxVM...
Delete VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
PS C:\WINDOWS\system32> powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create
Enabled workaround for Build 10586 VMSwitch issue
Creating Switch: DockerNAT...
Get-VMNetworkAdapter : Hyper-V was unable to find a virtual switch with name "DockerNAT".
At C:\Program Files\Docker\Docker\resources\MobyLinux.ps1:123 char:25
+ ... etAdapter = Get-VMNetworkAdapter -ManagementOS -SwitchName $SwitchNam ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (DockerNAT:String) [Get-VMNetworkAdapter], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVMNetworkAdapter
```

**Comment by bbodenmiller** [comment]
In `MobyLinux.ps1` I changed `New-VMSwitch $SwitchName -SwitchType Internal -ea SilentlyContinue | Out-Null` to `New-VMSwitch $SwitchName -SwitchType Internal` and now failing with:

```powershell
PS C:\WINDOWS\system32> powershell -ExecutionPolicy ByPass -File "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1" -create
Enabled workaround for Build 10586 VMSwitch issue
Creating Switch: DockerNAT...
New-VMSwitch : Failed while creating virtual Ethernet switch.
Switch create failed, name = '0787EEC4-9439-43F0-8F1D-3C26BD87F7CB', friendly name = 'DockerNAT': Invalid handle (0x80070006).
At C:\Program Files\Docker\Docker\resources\MobyLinux.ps1:122 char:9
+         New-VMSwitch $SwitchName -SwitchType Internal
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-VMSwitch], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.NewVMSwitch
```

**Comment by wentaozhu** [comment]
I faced the same issue.

**Comment by wentaozhu** [comment]
Factory rest will be ok.

**Comment by wentaozhu** [comment]
Maybe the daemon configure is wrong.

**Comment by bbodenmiller** [comment]
I tried factory reset, no luck.

**Comment by dgageot** [comment]
Hi @bbodenmiller  could you please try Docker for Windows Beta 33 and tell us if it works better?

**Comment by bbodenmiller** [comment]
Still broken

```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 374
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

**Comment by bbodenmiller** [comment]
I'm trying to get a crash ID but unfortunately it just hangs forever.

**Comment by dmeenan** [comment]
Have the same problem.  And now Hyper-V is corrupted too - can't remove/reinstall - it just fails, rolls back.  Leaving the broken vestiges of a Hyper-V switch (doesn't show up in the gui) named DockerNAT wandering the halls of my registry haunting every attempt to get Docker running.  Oh how I wish I hadn't clicked "upgrade" this morning.

**Comment by JackieJ** [comment]
Experienced the same problem after this morning's update to 1.13.0. Here my powershell output for adapters.

```
PS C:\> Get-NetAdapter
Name                      InterfaceDescription                    ifIndex Status       MacAddress             LinkSpeed
----                      --------------------                    ------- ------       ----------             ---------
Ethernet                  Intel(R) Ethernet Connection (2) I21...       5 Up           18-66-DA-37-70-30         1 Gbps
PS C:\>
```

I have Windows 10 Enterprise build 10586.713. Tried reinstall with elevated rights but no luck.

**Comment by tatmanblue** [comment]
What is the solution to this problem?

**Comment by HeavyStorm** [comment]
I'm having the same problem.

This seems to be an issue with Hyper-V itself. When using Hyper-V manager to create the Virtual Switch manually I get an error as well: 

![image](https://user-images.githubusercontent.com/1890900/28754883-0a5d03da-7525-11e7-9d01-8c43862c1b81.png)

I get the error even if I name the switch something else.

**Comment by HeavyStorm** [comment]
After messing about with system configuration and uninstalling and reinstalling stuff, I found the culprit (in my case): Check Point VPN. 

Just removing the VPN solved the issue. However, that's a new behavior since the Creator's update. I've had zero issues before with both softwares installed.

**Comment by friism** [comment]
Cc @jmesser81
-- 
http://friism.com/
(650) 318-1051
Sapere aude

**Comment by zmzmdr** [comment]
I faced the same issue.

**Comment by pbking** [comment]
Same issue for me.  Seems related to Cisco's AnyConnect VPN (which itself also had issues when upgrading to creators update).  Unfortunately I've got to be on the VPN to connect to our private registry... so damned if I do and damned if I don't.

**Comment by HeavyStorm** [comment]
@pbking it's the same for me... I'm lucky because my work machine isn't upgraded yet, but my home desktop (which I prefer to work on) can no longer be used - unless I downgrade Windows.

**Comment by clayshek** [comment]
Experiencing same issue, have Cisco AnyConnect VPN software for corporate VPN access, which I cannot remove.

**Comment by jasonbivins** [comment]
Hi @HeavyStorm @pbking 

Have you tried upgrading your Hyper-V configuration to 8.1?  The Creators update did make a few direct changes to Hyper-V and NAT networking

![image](https://user-images.githubusercontent.com/28021664/30487281-00a20b6e-9a01-11e7-812c-5f89bf3029de.png)

**Comment by shatl** [comment]
Having the same issue. @jasonbivins my Hyper-V configuration is 8.1

**Comment by edaemon** [comment]
I was experiencing the same issue except when I changed line 130 in MobyLinux.ps1 to `New-VMSwitch $SwitchName -SwitchType Internal` I got this error:

    Switch create failed, name = '0787EEC4-9439-43F0-8F1D-3C26BD87F7CB', friendly name = 'DockerNAT': Not found (0x80041002).

This was not Docker-specific, though; trying to create any type of switch in the Hyper-V Manager GUI failed with the same error. I eventually fixed this by uninstalling and reinstalling Hyper-V, restarting each time. After that I was able to manually create the switch in Hyper-V Manager and Docker started cleanly. It likely would have succeeded had I not created the switch manually and just let Docker create it -- I think the Manager just runs the same PowerShell command that Docker's MobyLinux.ps1 script uses.

I had already uninstalled Cisco AnyConnect as well as the Cisco Umbrella Roaming Client. They were uninstalled when I got Docker to start properly so that may have something to do with it. Both of them interfere with networking, and the Umbrella client may even create its own VMSwitch. I'll post another comment if re-installing those causes Docker to fail again.

FYI this was on Windows 10 Version 1703.

**Comment by shatl** [comment]
@edaemon This worked for me:
* disconnect from wired network
* connect to wifi and update Docker
* If Docker fails on startup connect to wired network and restart

**Comment by edaemon** [comment]
@shatl I tried that but the only thing that eventually worked was uninstalling and reinstalling Hyper-V. It's worked fine since I did that yesterday (even after reinstalling the Cisco software).

**Comment by beefo** [comment]
Same issue after creators update installed. Windows version: 10.0.16299 Docker version: 17.09.0-ce-win33 (13620)

A diagnostic was uploaded with id: 6ABFB0CF-8772-407D-B3AA-AE03A4A27D35/2017-11-16_11-55-19

- Disable and re-enable Hyper-V had no effect
- Uninstall and re-install of docker had no effect

> Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

**Comment by mrsalty** [comment]
Had the same issue, I managed to fix it by removing Hyper-V network adapters and reinstall Docker

**Comment by kleskowy** [comment]
Same here as in @beefo case.

Fiddling aroung with uninstalling Docker, disabling and re-enabling Hyper-V (both the service and in BIOS) did not help.
I also can't create a virtual switch manually in Hyper-V, I have no idea why.

```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common 
parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 385
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
```

**Comment by mrsalty** [comment]
What I did is not disable Hyper-V but went to Device Manager -> Network Adapters -> Uninstall Hyper-V Ethernet Adapter. Then reinstalled Docker and got it up and running

**Comment by kleskowy** [comment]
@mrsalty trouble is - I uninstalled the adapter and tried to restart Docker - did not help. And after disabling and reenabling Hyper-V I don't even have any Hyper-V network adapter in device manager... 

I have reported a crash report with a following diagnostic id: 
4A7FB306-AF44-4B6C-ADA8-D261ACEEE5CE/2017-11-17_17-35-36

**Comment by beefo** [comment]
> What I did is not disable Hyper-V but went to Device Manager -> Network Adapters -> Uninstall Hyper-V Ethernet Adapter. Then reinstalled Docker and got it up and running

@mrsalty tried this as well, no luck

**Comment by kleskowy** [comment]
What seems strange to me is that after over a day of fiddling around (flushing network config `($ netcfg -d)`, reinstalling network card drivers, re-enabling Hyper-V, multiple reinstalls of Docker etc), I tried installing Docker Toolbox (which installed VirtualBox I think, and required disabling Hyper-V for running).

Unfortunately it didn't help at all - it managed to create a virtual machine, but couldn't set up networking...

So please anyone help us with the Docker failing to start on windows 10 (DockerNAT virtual switch couldn't be found)...

**Comment by beefo** [comment]
@dgageot Do you know if anyone on the Docker team is looking at this issue? Severely effecting my day-to-day workflow, we rely on Docker quite heavily.

**Comment by antoine-morisseau** [comment]
I still have the issue.
Very annoying since i can't use docker anymore on my machine :|

**Comment by krushmike** [comment]
I am having the same issue.  Completely un-installed both Docker and Hyper-V and re-installed.  I did switch from the Stable channel to the Edge channel (17.11.0-ce-win40 14328)

Something odd though.  When Docker was starting after install, I noticed the DockerNAT vSwitch pop in to Hyper-V and then go away.  Shortly thereafter, I get the error and I can no longer create vSwitch's of any type via PS or through the management console.  If I reboot, I can create switches, but Docker still will not start.

**Comment by krushmike** [comment]
I noticed @pbking mentioned the Cisco AnyConnect VPN client above, so I removed the software and rebooted.  Everything in terms of Docker and Hyper-V is now working and stable with no further error messages in the logs.  Going to try re-installing the Cisco VPN client...

**Comment by pbking** [comment]
I was able to roll back to pre-creators update and haven't taken that or
the more recent update so that my machine stays out-of-date but use-able.
Once the holidays are upon us and I can be afford to be down for a while
I'll uninstall AnyConnect and Docker prior to taking any of the Windows
Updates.  If I can put AnyConnect and Docker both back on (some reading
tells me it may work) then I'll be back in the running and will update this
thread.

**Comment by kevin-wang-cy** [comment]
Exactly issue here, who can help? anyone from M$?

**Comment by jasonbivins** [comment]
@kevin-wang-cy 

There is a network cleanup tool available from [Microsoft](https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/live/windows-server-container-tools/CleanupContainerHostNetworking) - but please keep in mind that this will remove ALL switches, not just Docker ones.   ```
PS C:\> .\WindowsContainerNetworking-LoggingAndCleanupAide.ps1 -Cleanup -ForceDeleteAllSwitches ```

**Comment by NoamB** [comment]
Uninstalled "Check Point VPN" client, docker started fine. Re-installed VPN client, now both seem to work.

**Comment by treiboll** [comment]
CheckPoint VPN do not work correct on Windows 10 with creators update. I tried both versions E80.70 and E80.71. With installed CheckPoint it is no more possible to create virtual switches in Hyper-V. But docker needs to do that. CheckPoint is aware of this problems and is working on it.

**Comment by wwk3j** [comment]
ended up running the netfg -d on commandprompt elevated as admin and then hitting window key + x and going to program and features. Then turn on/off features. Then I disabled Hyper-V and rebooted. Then I re-enabled Hyper-V and rebooted. Mind you, this is after troubleshooting for a couple hours with MobyLinux.ps1 and a variety of powershell commands to no avail. My errors during that time varied quite a bit, but I have a feeling the disable and then re-enable which took 20-30 minutes for windows to reboot each time saved me.

**Comment by vlad-zhukov** [comment]
If you use Check Point VPN you can a [Windows 10 app](https://www.microsoft.com/en-us/store/p/check-point-capsule-vpn/9wzdncrdjxtj). Works like a charm!

**Comment by tsergey-tm** [comment]
I solved the problem by downgrade CheckPoint client to E80.60

**Comment by guichafy** [comment]
I solved this problem by uninstalling VPN Checkpoint software.

@tsergey-tm  I'll try to use this version E8060

**Comment by treiboll** [comment]
Check Point with version E80.73 works again with Docker on Windows 10

**Comment by NoamB** [comment]
@treiboll do you have a link for E80.73? I can't find it on Google or Checkpoint website.

**Comment by treiboll** [comment]
@NoamB based on a support ticket my company received the E80.73 installer directly. I think it will be released later but at the moment there is another problem with this version. Thus I think it will take some more time to the official release.

**Comment by zacaj** [comment]
Uninstalled Docker (stable or edge), ran netcfg -d, disabled Hyper-V, restarted, enabled Hyper-V, restarted, re-installed Docker, still doesn't work.

Tried to manually create a switch in the Hyper-V Manager and it fails too, "Failed while adding virtual Ethernet switch connections", "General access is denied error" despite being run as Administrator

Windows 10, no VPN software, etc.

**Comment by dmitry-cherkas** [comment]
Same here, my freshly updated docker for windows (Edge) does not start. Removing the Check Point E80.71 helped.

**Comment by ntravis** [comment]
This fix from Windows got me working again:
https://support.microsoft.com/en-us/help/3101106/you-cannot-create-a-hyper-v-virtual-switch-on-64-bit-versions-of-windo

**Comment by antoine-morisseau** [comment]
@ntravis i tried the fix from Windows and still the issue.

I believe the issue for me come from the vpn client installed on it but i don't have the right on it to uninstall it.

**Comment by juzam** [comment]
[E80.80 Remote Access Clients for Windows](https://supportcenter.checkpoint.com/supportcenter/portal/role/supportcenterUser/page/default.psml/media-type/html?action=portlets.DCFileAction&eventSubmit_doGetdcdetails=&fileid=60924) fixes this. (again?)

**Comment by HeavyStorm** [comment]
I can try it at home, it's very easy to reproduce it now.

**Comment by NoamB** [comment]
E80.80 does not work for me - Docker won't start. After uninstall -> Docker starts.

**Comment by dobriseb** [comment]
Hi,

I've got the same problem and, according to [Can't create any Virtual Switch in Hyper-V, Failed while creating virtual Ethernet switch 0x800401F3](https://social.technet.microsoft.com/Forums/en-US/f7e4af56-900e-4879-ab34-9d50f4e345a9/cant-create-any-virtual-switch-in-hyperv-failed-while-creating-virtual-ethernet-switch-0x800401f3?forum=win10itprovirt), I execute twice as administrator (and two reboot) this command line :
`netcfg -d`
The DockerNat was created by docker at the second reboot and docker run like a charm.

Hope this help.

**Comment by abstrask** [comment]
For what it's worth, Trend Micro OfficeScan 12 was the culprit in my case. Disabling the "Unauthorized Change Prevention Service" fixes the problem with creating the vSwitch.

Several protection features of OfficeScan is depending on this service however. It might be possible to narrow it down to a single sub-component, but for now this is my workaround.

**Comment by yodamad** [comment]
@abstrask Can you explain where to disable this feature, it seems that i'm facing the same problem actually

**Comment by kenpavia** [comment]
After running some Windows 10 updates, my Docker For Windows would not switch to Linux Containers.  The error message said it could not find the virtual switch named "DockerNAT".  When I tried to create this switch using Hyper-V, it would not create, saying just that it failed, but would not give a reason.

Thanks to suggestions in previous posts on this thread, I was able to fix it by disabling Hyper-V, then re-enabling it.  When switching to Linux Containers, Docker started up the MobyLinux VM.  I did not actually have to create the virtual switch.  Either Docker took care of it, or it was always there.  Here are the specific steps I followed:

1.  Disable Hyper-V through the Windows Features Turn On/Off Dialog.
2.  Reboot machine.
3.  Enable Hyper-V through the Windows Features Turn On/Off Dialog.
4. Reboot machine.
5. Start Docker For Windows.
6.  Switch to Linux Containers.

When running step 6, I saw the MobyLinux VM show up in Hyper-V Manager.

I'm running Windows 10 Enterprise x64 Version 1607.

**Comment by yvesdm** [comment]
The fix suggested by @ntravis 
https://support.microsoft.com/en-us/help/3101106/you-cannot-create-a-hyper-v-virtual-switch-on-64-bit-versions-of-windo
Solved the problem for me.

**Comment by NoamB** [comment]
Checkpoint VPN E80.81 works for me:

https://supportcenter.checkpoint.com/supportcenter/portal/user/anon/page/default.psml/media-type/html?action=portlets.DCFileAction&eventSubmit_doGetdcdetails=&fileid=61505

Reading the release notes of E80.80 (one version before) it looks like they fixed it then:

http://dl3.checkpoint.com/paid/58/58d46844dc7e4bebaf0df1d1f52c4b56/CP_E80.80_Win_ReleaseNotes.pdf?HashKey=1520631431_45286486f3bdc1ac84c58f6c3317b323&xtn=.pdf

**Comment by JianhuanZhuo** [comment]
switch to windows containers works for me

**Comment by kfparri** [comment]
I've had the same issue and I believe that CheckPoint VPN is to blame.  I had to uninstall and reinstall HyperV on my machine (I also reinstalled docker but I don't believe that was necessary)

**Comment by yvesdm** [comment]
I confirm what @abstrask said, Trend Micro 12 is also responsible of troubles when trying to start docker, 
We applied the proposed solution : Disabling the "Unauthorized Change Prevention Service" from Trend Micro to fix the problem with creating the vSwitch.

Here is the command line solution to stop this service : 
Launch a command prompt as administrator and run those commands :
- sc queryex TMBMServer
- taskkill /F /PID <PID found with previous command>

Note : It was working without problems with Trend Micro 11
Thanks : @abstrask for having shared this information who helped us a lot.

**Comment by HeavyStorm** [comment]
E80.80 solved issues for me. As per @NoamB comment, I'd recommend going full to E80.81.

**Comment by drsasankh** [comment]
In my case Trend Micro was the culprit. Docker is working after uninstalling TM.

**Comment by ilizane** [comment]
in my case i uninstalled Cisco anyConnect and docker could then start up.

**Comment by anguspalmer** [comment]
I had the same issue, Docker would not start, reporting that it could not find the virtual switch, DockerNAT. Attempting to create a virtual switch in Hyper-v also failed and I could see in the device manager logs that a new virtual network adapter was being created but then shortly after it is deleted.

After confirming that group policy was not an issue we found that disabling **Trend Officescan** allowed Docker to run. Our admin has disabled the two settings highlighted by @abstrask and now Docker runs with Trend Micro enabled.

**Comment by kilroy05** [comment]
I had the same issue but I use SoftEther VPN. Disabling the virtual adapter fixes it

**Comment by jorgenfroland** [comment]
Had the same issue. Made it work by disabling Trend OfficeScan and the Docker started perfectly. Its seems that Trend keeps me from creating virtual switches in Hyper-V in general.

**Comment by YoungjaeKim** [comment]
If you are using Windows 10 `1809`, please check below link. I spent 4 hours to fix it.
https://social.technet.microsoft.com/Forums/en-US/ee5b1d6b-09e2-49f3-a52c-820aafc316f9/hyperv-doesnt-work-after-upgrade-to-windows-10-1809?forum=win10itprovirt

**Comment by jsam2412** [comment]
Try running these commands and restart docker. This worked for me.

```
# Done from an admin shell 
net stop vmms
net start vmms
```

**Comment by SuneethaYamani** [comment]
> After messing about with system configuration and uninstalling and reinstalling stuff, I found the culprit (in my case): Check Point VPN.
> 
> Just removing the VPN solved the issue. However, that's a new behavior since the Creator's update. I've had zero issues before with both softwares installed.

this helped for me
