### ISSUE TITLE
Docker will Not Start in Windows 10 Environment

### ISSUE THREAD

**Issue by johngnazzo** [docker/for-win#3241]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A9897F24-6E42-4EF5-936B-90642823BEB6/20190116145940

### Expected behavior
Docker will not start in Windows 10 Desktop Environment

### Actual behavior
Get Error Message (See attached logs)
Docker was working until I upgraded to version 2.0.0.2
I tried uninstalling and re-installing my previously working version

### Information

  - Windows Version: Windows 10
  - Docker for Windows Version: 2.0.0.2

### Steps to reproduce the behavior
Start Docker Desktop
Get Error Message

Version: 18.06.0-ce-win72 (19098)
Channel: stable
Sha1: 5513f91045dac2b8d51420014ee9176d24791d7d
Started on: 2019/01/16 10:21:26.870
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1809
Build: 17763
BuildLabName: 17763.1.amd64fre.rs5_release.180914-1434
File: C:\Users\GNAZJOH\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[10:21:27.010][GUI            ][Info   ] Starting...
[10:21:27.042][GUI            ][Error  ] An instance is already running. Exiting.
[10:21:27.104][Installer      ][Info   ] Checking for features: Hyper-V, Containers
[10:21:27.104][PowerShell     ][Info   ] Run script...
[10:21:27.120][PowerShell     ][Info   ] Creating a Runspace Pool...
[10:21:28.108][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[10:21:34.691][PowerShell     ][Info   ] Run script...
[10:21:36.181][PowerShell     ][Info   ] Run script...
[10:21:37.534][PowerShell     ][Info   ] Run script...
[10:21:39.172][Installer      ][Info   ] Features installed
[10:21:39.677][WindowsDaemon  ][Info   ] debug: Listener created for HTTP on npipe (//./pipe/docker_engine_windows)
[10:21:39.678][WindowsDaemon  ][Info   ] debug: Service running
[10:21:39.682][WindowsDaemon  ][Info   ] Windows default isolation mode: hyperv
[10:21:39.682][WindowsDaemon  ][Info   ] debug: Stackdump - waiting signal at Global\docker-daemon-15712
[10:21:39.686][WindowsDaemon  ][Info   ] debug: Using default logging driver json-file
[10:21:39.686][WindowsDaemon  ][Info   ] debug: [graphdriver] trying provided driver: windowsfilter
[10:21:39.686][WindowsDaemon  ][Info   ] debug: WindowsGraphDriver InitFilter at C:\ProgramData\Docker\windowsfilter
[10:21:39.687][WindowsDaemon  ][Info   ] debug: Initialized graph driver windowsfilter
[10:21:39.733][WindowsDaemon  ][Info   ] debug: Max Concurrent Downloads: 3
[10:21:39.733][WindowsDaemon  ][Info   ] debug: Max Concurrent Uploads: 5
[10:21:39.734][WindowsDaemon  ][Info   ] Loading containers: start.
[10:21:39.734][WindowsDaemon  ][Info   ] debug: Option Experimental: false
[10:21:39.734][WindowsDaemon  ][Info   ] debug: Option DefaultDriver: nat
[10:21:39.734][WindowsDaemon  ][Info   ] debug: Option DefaultNetwork: nat
[10:21:39.734][WindowsDaemon  ][Info   ] debug: Network Control Plane MTU: 1500
[10:21:39.735][WindowsDaemon  ][Info   ] Restoring existing overlay networks from HNS into docker
[10:21:39.735][WindowsDaemon  ][Info   ] debug: [GET]=>[/networks/] Request : 
[10:21:39.747][WindowsDaemon  ][Info   ] debug: Network Response : []
[10:21:39.783][WindowsDaemon  ][Info   ] debug: [GET]=>[/networks/] Request : 
[10:21:39.785][WindowsDaemon  ][Info   ] debug: Network Response : []
[10:21:39.787][WindowsDaemon  ][Info   ] debug: Launching DNS server for network "none"
[10:21:39.792][WindowsDaemon  ][Info   ] debug: Allocating IPv4 pools for network nat (394a95a5618e3163bd06e12af5075af0bf86a59c3d4e4225754135eb9d1c7c20)
[10:21:39.792][WindowsDaemon  ][Info   ] debug: RequestPool(LocalDefault, , , map[], false)
[10:21:39.792][WindowsDaemon  ][Info   ] debug: RequestAddress(0.0.0.0/0, <nil>, map[RequestAddressType:com.docker.network.gateway])
[10:21:39.793][WindowsDaemon  ][Info   ] debug: HNSNetwork Request ={"Name":"nat","Type":"nat","Subnets":[{"AddressPrefix":"0.0.0.0/0"}]} Address Space=[{0.0.0.0/0  []}]
[10:21:39.793][WindowsDaemon  ][Info   ] debug: [POST]=>[/networks/] Request : {"Name":"nat","Type":"nat","Subnets":[{"AddressPrefix":"0.0.0.0/0"}]}
[10:21:55.991][WindowsDaemon  ][Info   ] debug: releasing IPv4 pools from network nat (394a95a5618e3163bd06e12af5075af0bf86a59c3d4e4225754135eb9d1c7c20)
[10:21:55.991][WindowsDaemon  ][Info   ] debug: ReleasePool(0.0.0.0/0)
[10:21:55.991][WindowsDaemon  ][Info   ] debug: daemon configured with a 15 seconds minimum shutdown timeout
[10:21:55.991][WindowsDaemon  ][Info   ] debug: start clean shutdown of all containers with a 15 seconds timeout...
[10:21:55.996][WindowsDaemon  ][Error  ] fatal: Error starting daemon: Error initializing network controller: Error creating default network: hnsCall failed in Win32: The system cannot find the file specified. (0x2)
[10:22:11.561][Cmd            ][Info   ] time="2019-01-16T10:22:11-06:00" level=fatal msg="The specified service already exists."
[10:22:11.623][WindowsDaemon  ][Info   ] debug: Listener created for HTTP on npipe (//./pipe/docker_engine_windows)
[10:22:11.624][WindowsDaemon  ][Info   ] debug: Service running
[10:22:11.624][WindowsDaemon  ][Info   ] debug: Listener created for HTTP on npipe (//./pipe/docker_engine_windows)
[10:22:11.626][WindowsDaemon  ][Info   ] debug: Service running
[10:22:11.629][WindowsDaemon  ][Info   ] Windows default isolation mode: hyperv
[10:22:11.629][WindowsDaemon  ][Info   ] Windows default isolation mode: hyperv
[10:22:11.629][WindowsDaemon  ][Info   ] debug: Stackdump - waiting signal at Global\docker-daemon-10884
[10:22:11.629][WindowsDaemon  ][Info   ] debug: Stackdump - waiting signal at Global\docker-daemon-10884
[10:22:11.629][WindowsDaemon  ][Info   ] debug: Using default logging driver json-file
[10:22:11.629][WindowsDaemon  ][Info   ] debug: Using default logging driver json-file
[10:22:11.630][WindowsDaemon  ][Info   ] debug: [graphdriver] trying provided driver: windowsfilter
[10:22:11.630][WindowsDaemon  ][Info   ] debug: [graphdriver] trying provided driver: windowsfilter
[10:22:11.630][WindowsDaemon  ][Info   ] debug: WindowsGraphDriver InitFilter at C:\ProgramData\Docker\windowsfilter
[10:22:11.630][WindowsDaemon  ][Info   ] debug: WindowsGraphDriver InitFilter at C:\ProgramData\Docker\windowsfilter
[10:22:11.630][WindowsDaemon  ][Info   ] debug: Initialized graph driver windowsfilter
[10:22:11.630][WindowsDaemon  ][Info   ] debug: Initialized graph driver windowsfilter
[10:22:11.637][WindowsDaemon  ][Info   ] debug: Max Concurrent Downloads: 3
[10:22:11.637][WindowsDaemon  ][Info   ] debug: Max Concurrent Uploads: 5
[10:22:11.637][WindowsDaemon  ][Info   ] debug: Max Concurrent Downloads: 3
[10:22:11.637][WindowsDaemon  ][Info   ] Loading containers: start.
[10:22:11.637][WindowsDaemon  ][Info   ] debug: Max Concurrent Uploads: 5
[10:22:11.637][WindowsDaemon  ][Info   ] Loading containers: start.
[10:22:11.637][WindowsDaemon  ][Info   ] debug: Option Experimental: false
[10:22:11.637][WindowsDaemon  ][Info   ] debug: Option Experimental: false
[10:22:11.637][WindowsDaemon  ][Info   ] debug: Option DefaultDriver: nat
[10:22:11.638][WindowsDaemon  ][Info   ] debug: Option DefaultNetwork: nat
[10:22:11.638][WindowsDaemon  ][Info   ] debug: Network Control Plane MTU: 1500
[10:22:11.638][WindowsDaemon  ][Info   ] debug: Option DefaultDriver: nat
[10:22:11.638][WindowsDaemon  ][Info   ] debug: Option DefaultNetwork: nat
[10:22:11.638][WindowsDaemon  ][Info   ] debug: Network Control Plane MTU: 1500
[10:22:11.638][WindowsDaemon  ][Info   ] Restoring existing overlay networks from HNS into docker
[10:22:11.638][WindowsDaemon  ][Info   ] debug: [GET]=>[/networks/] Request : 
[10:22:11.638][WindowsDaemon  ][Info   ] Restoring existing overlay networks from HNS into docker
[10:22:11.638][WindowsDaemon  ][Info   ] debug: [GET]=>[/networks/] Request : 
[10:22:11.644][WindowsDaemon  ][Info   ] debug: Network Response : []
[10:22:11.645][WindowsDaemon  ][Info   ] debug: Network Response : []
[10:22:11.667][WindowsDaemon  ][Info   ] debug: [GET]=>[/networks/] Request : 
[10:22:11.668][WindowsDaemon  ][Info   ] debug: [GET]=>[/networks/] Request : 
[10:22:11.670][WindowsDaemon  ][Info   ] debug: Network Response : []
[10:22:11.672][WindowsDaemon  ][Info   ] debug: Network Response : []
[10:22:11.672][WindowsDaemon  ][Info   ] debug: Launching DNS server for network "none"
[10:22:11.673][WindowsDaemon  ][Info   ] debug: Launching DNS server for network "none"
[10:22:11.677][WindowsDaemon  ][Info   ] debug: Allocating IPv4 pools for network nat (e271fa484146284bfaf01d89a81e54f1b09320b2b4e2ba6e3bb8fdce4e411aac)
[10:22:11.677][WindowsDaemon  ][Info   ] debug: RequestPool(LocalDefault, , , map[], false)
[10:22:11.677][WindowsDaemon  ][Info   ] debug: Allocating IPv4 pools for network nat (e271fa484146284bfaf01d89a81e54f1b09320b2b4e2ba6e3bb8fdce4e411aac)
[10:22:11.677][WindowsDaemon  ][Info   ] debug: RequestAddress(0.0.0.0/0, <nil>, map[RequestAddressType:com.docker.network.gateway])
[10:22:11.677][WindowsDaemon  ][Info   ] debug: RequestPool(LocalDefault, , , map[], false)
[10:22:11.677][WindowsDaemon  ][Info   ] debug: RequestAddress(0.0.0.0/0, <nil>, map[RequestAddressType:com.docker.network.gateway])
[10:22:11.678][WindowsDaemon  ][Info   ] debug: HNSNetwork Request ={"Name":"nat","Type":"nat","Subnets":[{"AddressPrefix":"0.0.0.0/0"}]} Address Space=[{0.0.0.0/0  []}]
[10:22:11.678][WindowsDaemon  ][Info   ] debug: [POST]=>[/networks/] Request : {"Name":"nat","Type":"nat","Subnets":[{"AddressPrefix":"0.0.0.0/0"}]}
[10:22:11.678][WindowsDaemon  ][Info   ] debug: HNSNetwork Request ={"Name":"nat","Type":"nat","Subnets":[{"AddressPrefix":"0.0.0.0/0"}]} Address Space=[{0.0.0.0/0  []}]
[10:22:11.678][WindowsDaemon  ][Info   ] debug: [POST]=>[/networks/] Request : {"Name":"nat","Type":"nat","Subnets":[{"AddressPrefix":"0.0.0.0/0"}]}
[10:22:27.726][WindowsDaemon  ][Info   ] debug: releasing IPv4 pools from network nat (e271fa484146284bfaf01d89a81e54f1b09320b2b4e2ba6e3bb8fdce4e411aac)
[10:22:27.726][WindowsDaemon  ][Info   ] debug: ReleasePool(0.0.0.0/0)
[10:22:27.726][WindowsDaemon  ][Info   ] debug: releasing IPv4 pools from network nat (e271fa484146284bfaf01d89a81e54f1b09320b2b4e2ba6e3bb8fdce4e411aac)
[10:22:27.727][WindowsDaemon  ][Info   ] debug: daemon configured with a 15 seconds minimum shutdown timeout
[10:22:27.727][WindowsDaemon  ][Info   ] debug: ReleasePool(0.0.0.0/0)
[10:22:27.727][WindowsDaemon  ][Info   ] debug: daemon configured with a 15 seconds minimum shutdown timeout
[10:22:27.727][WindowsDaemon  ][Info   ] debug: start clean shutdown of all containers with a 15 seconds timeout...
[10:22:27.727][WindowsDaemon  ][Info   ] debug: start clean shutdown of all containers with a 15 seconds timeout...
[10:22:27.731][WindowsDaemon  ][Error  ] fatal: Error starting daemon: Error initializing network controller: Error creating default network: hnsCall failed in Win32: The system cannot find the file specified. (0x2)
[10:22:27.732][WindowsDaemon  ][Error  ] fatal: Error starting daemon: Error initializing network controller: Error creating default network: hnsCall failed in Win32: The system cannot find the file specified. (0x2)
[10:22:29.338][WindowsDaemon  ][Info   ] Successfully scheduled Software Protection service for re-start at 2019-01-21T21:52:29Z. Reason: RulesEngine.
[10:22:29.338][WindowsDaemon  ][Info   ] Successfully scheduled Software Protection service for re-start at 2019-01-21T21:52:29Z. Reason: RulesEngine.
[10:22:29.354][WindowsDaemon  ][Info   ] The Software Protection service has stopped.

[10:22:29.354][WindowsDaemon  ][Info   ] The Software Protection service has stopped.

[10:22:36.166][WindowsDaemon  ][Info   ] Self-service Plug-in exited.
[10:22:36.166][WindowsDaemon  ][Info   ] Self-service Plug-in exited.
[10:22:42.389][NamedPipeClient][Error  ] Unable to send Start: Timed out while waiting for Docker daemon to be ready
[10:22:42.389][NamedPipeServer][Error  ] Unable to execute Start: Timed out while waiting for Docker daemon to be ready    at Docker.Backend.Processes.WindowsDockerDaemon.WaitForDaemonToBeReady() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 147
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 222
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 96
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180
[10:22:42.389][Notifications  ][Error  ] Timed out while waiting for Docker daemon to be ready
[10:22:42.405][NamedPipeClient][Info   ] Sending Version()...
[10:22:42.405][NamedPipeClient][Info   ] Received response for Version
[10:22:42.405][NamedPipeClient][Info   ] Sending GatherDiagnostics(-path C:\Users\GNAZJOH\AppData\Local\Temp\ gather -id A9897F24-6E42-4EF5-936B-90642823BEB6/20190116102242, C:\Users\GNAZJOH\AppData\Local\Temp\A9897F24-6E42-4EF5-936B-90642823BEB6/20190116102242.zip)...
[10:22:42.405][NamedPipeServer][Info   ] Version()
[10:22:42.405][NamedPipeServer][Info   ] Version done in 00:00:00.
[10:22:42.405][NamedPipeServer][Info   ] GatherDiagnostics(-path C:\Users\GNAZJOH\AppData\Local\Temp\ gather -id A9897F24-6E42-4EF5-936B-90642823BEB6/20190116102242, C:\Users\GNAZJOH\AppData\Local\Temp\A9897F24-6E42-4EF5-936B-90642823BEB6/20190116102242.zip)
[10:22:54.885][ErrorReportWindow][Info   ] Open logs
[10:23:49.494][NamedPipeClient][Info   ] Sending Version()...
[10:23:49.510][NamedPipeClient][Info   ] Received response for Version
[10:23:49.510][NamedPipeClient][Info   ] Sending StopGatherDiagnostics()...
[10:23:49.510][NamedPipeServer][Info   ] Version()
[10:23:49.510][NamedPipeClient][Info   ] Received response for StopGatherDiagnostics
[10:23:49.510][NamedPipeServer][Info   ] Version done in 00:00:00.
[10:23:49.510][NamedPipeServer][Info   ] StopGatherDiagnostics()
[10:23:49.510][NamedPipeServer][Info   ] StopGatherDiagnostics done in 00:00:00.
[10:23:49.572][NamedPipeClient][Info   ] Received response for GatherDiagnostics
[10:23:49.572][NamedPipeServer][Info   ] GatherDiagnostics done in 00:01:07.1674965.
[10:23:49.604][GUI            ][Info   ] Sending Bugsnag report 5bb09faf-c361-4317-bde2-f138f2068940...
[10:23:49.947][GUI            ][Info   ] Bugsnag report 5bb09faf-c361-4317-bde2-f138f2068940 sent

**Comment by moikot** [comment]
This is a very annoying issue. 
And it seems like it happens every time when Docker doesn't have enough time to cleanup some networking data associated with containers when they are terminated. 
I'm trying to use Docker with Service Fabric on my local machine and I see this issue constantly. The only fix now is to try to reset the Docker networking by running [CleanupContainerHostNetworking script](https://github.com/MicrosoftDocs/Virtualization-Documentation/tree/live/windows-server-container-tools/CleanupContainerHostNetworking). But read the documentation before running it.
