### ISSUE TITLE
Unable to start docker for windows 2.0.0.0-win81 (29211) (windows 10 17763)

### ISSUE THREAD

**Issue by auvinenak** [docker/for-win#3245]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: 4CC2FF15-A15E-4BEB-80BF-43CAE2B7CACA/20190117113342

### Expected behavior
Docker will start
### Actual behavior
Docker does not start
### Information

  - Windows Version: Windows 10 Enterprise 10.0.17763 
  - Docker for Windows Version: 2.0.0.0-win81 (29211)

### Steps to reproduce the behavior

I have a new computer with fresh install of windows.

  1. Install docker for windows
  2. Run docker as administrator

time="2019-01-17T11:33:39+02:00" level=error msg="cannot get pki directory: cannot read \"front-proxy-ca.crt\": open C:\\ProgramData\\DockerDesktop\\pki\\front-proxy-ca.crt: The system cannot find the file specified."

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by auvinenak** [comment]
Tried older version and it works: Edition 18.06.1-ce-win73 2018-08-29
