### ISSUE TITLE
Docker won't start

### ISSUE THREAD

**Issue by yamikuronue** [docker/for-win#3249]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6CDDF4CE-5490-420C-B513-FAEB6359B2B9/20190117084944

### Expected behavior
Docker starts

### Actual behavior
Crash window with this error:
```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to change state.

The operation failed with error code '32788'.
at Start-MobyLinuxVM, <No file>: line 296
at <ScriptBlock>, <No file>: line 412
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

### Information

  - Windows Version: 10.0.17134
  - Docker for Windows Version: 2.0.0.2

### Steps to reproduce the behavior

  1. Start Docker for Windows

**Comment by colossus21** [comment]
Facing the same problem!!
