### ISSUE TITLE
Race condition in MobyLinux.ps1

### ISSUE THREAD

**Issue by MicahZoltu** [docker/for-win#3252]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: (Diagnostics uploading not working)

### Expected behavior
Installs and runs successfully.

### Actual behavior
```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer 'LONG-COMPUTER-N' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at New-MobyLinuxVM, <No file>: line 191
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

### Information
  - Windows Version: Windows 10 Pro Build 1809
  - Docker for Windows Version: Version 2.0.0.2 (30215)

### Steps to reproduce the behavior
  1. Install Docker for Windows
  2. When prompted, let it add the Hyper-V components and restart.
  3. Launch Docker for Windows
  4. Wait for error.

I can reliably reproduce the bug by running the `MobyLinux.ps1` script with `-Destroy` and then with `-Create -IsoFile 'C:\Program Files\Docker\Docker\Resources\docker-for-win.iso'` instead of doing step 3 (this is how I was able to troubleshoot further).

----

I originally thought this was an issue with NetBios name truncation, but upon digging in for a while I actually found that it is a race condition in the script that I am running into.  If I run the `New-Switch` function in the `MobyLinux.ps1` script in isolation, and then I run the `New-MobyLinuxVM` function it works.  Also, if I run the script twice in a row with same parameters it will fail the first time and succeed the second time.  Finally, and most importantly, **if I put a `Start-Sleep -s 30` at the top of the `New-MobyLinuxVM` script everything works!**

All of my troubleshooting suggests that the issue is that the `New-MobyLinuxVM` function is being executed before Windows has finished initializing the new network interface, and when the script gets to the point where it tries to create the VM, it doesn't have connectivity so it fails to connect to the HyperVisor and thus fails to create the VM.

I didn't spend any time troubleshooting how long of a sleep is necessary to get things working, but 30 seconds seems to be enough (maybe it just needs a couple seconds).

**Comment by MicahZoltu** [comment]
/remove-lifecycle stale
/lifecycle frozen

This is not the type of issue that magically goes away on its own, nor is it a support request so I don't think it should auto-close due to staleness.
