### ISSUE TITLE
ErrorActionPreference

### ISSUE THREAD

**Issue by ChakritRakuang** [docker/for-win#3264]
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer 'CHAKRIT-RAKHUAN' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at New-MobyLinuxVM, <No file>: line 191
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 155
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by ggolub** [comment]
I had this same issue after upgrading Windows Enterprise to version 1809.  Now am unable to start Docker, even after complete uninstall/reinstall.  Completely blocked - an answer to this issue would be greatly appreciated.
