### ISSUE TITLE
Docker won't boot on clean install

### ISSUE THREAD

**Issue by samuelleeuwenburg** [docker/for-win#3288]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A9783F05-4E4E-4D24-A86A-98F5B78B0981/20190126134455

### Expected behavior
Docker for windows runs on a clean install

### Actual behavior
Docker won't start up

### Information
I have tried uninstalling and reinstalling Hyper-V, I also tried installing both stable and edge versions of Docker. I have gone through the debugging guide. I cannot use the cleanup script because docker can't run.

The error I get is:
```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

  - Windows Version: Windows 10 Professional
  - Docker for Windows Version: 2.0.0.2 (30215)

### Steps to reproduce the behavior
Install Docker,
Run docker

**Comment by mikeparker** [comment]
see https://github.com/docker/for-win/issues/3442
Can you check if it was because the IP address 10.0.75.1 was in use?
