### ISSUE TITLE
Docker for Windows not starting

### ISSUE THREAD

**Issue by davidobrien1985** [docker/for-win#329]
After booting Windows I am greeted with this error message:

```
Docker daemon failed with message:
time="2016-12-17T14:21:46.408909800+11:00" level=info msg="Windows default isolation mode: hyperv" 
time="2016-12-17T14:21:46.413407500+11:00" level=info msg="[graphdriver] using prior storage driver: windowsfilter" 
time="2016-12-17T14:21:46.578433700+11:00" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2016-12-17T14:21:46.580430800+11:00" level=info msg="Loading containers: start." 
Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : The parameter is incorrect. 


   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

Docker version 1.13.0-rc3, build 4d92237

**Comment by friism** [comment]
@davidobrien1985 thanks for reporting. Can you:

 * run the diagnostics (if that's available)
 * try factory reset
 * Try the MS debug script: https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-tools/Debug-ContainerHost (possibly even the new version that has more networking tests: https://github.com/Microsoft/Virtualization-Documentation/pull/513)

**Comment by davidobrien1985** [comment]
Diagnostics: 7FF335B8-A6FB-4C48-BC1E-B9F79F69CB3A/2016-12-21_23-53-35
Already done factory reset.

```
Checking for common problems
Describing Windows Version and Prerequisites
 [+] Is Windows 10 Anniversary Update or Windows Server 2016 546ms
 [+] Has KB3192366, KB3194496, or later installed if running Windows build 14393 17ms
 [+] Is not a build with blocking issues 18ms
Describing Docker is installed
 [+] A Docker service is installed - 'Docker' or 'com.Docker.Service'  69ms
 [+] Service is running 19ms
 [+] Docker.exe is in path 2.17s
Describing User has permissions to use Docker daemon
 [+] docker.exe should not return access denied 58ms
Describing Windows container settings are correct
 [+] Do not have DisableVSmbOplock set to 1 81ms
 [+] Do not have zz values set 30ms
Describing The right container base images are installed
docker.exe : error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/images/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon 
configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
At line:82 char:24
+     $imageListOutput = docker.exe images
+                        ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (error during co...is not running.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
 [-] At least one of 'microsoft/windowsservercore' or 'microsoft/nanoserver' should be installed 712ms
   ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Property'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   at <ScriptBlock>, <No file>: line 96
Describing Container network is created
 [+] At least one local container network is available 1.15s
 [-] At least one NAT, Transparent, or L2Bridge Network exists 29ms
   Expected {0} to be greater than {0}
   187:       $totalnets | Should BeGreaterThan 0
   at <ScriptBlock>, <No file>: line 187
 [-] NAT Network's vSwitch is internal 81ms
   Expected: {Internal}
   But was:  {}
   192:       $switchType | Should Be "Internal"      
   at <ScriptBlock>, <No file>: line 192
 [-] Specified Network Gateway IP for NAT network is assigned to Host vNIC 70ms
   Expected: value to not be empty
   196:       $natGatewayIP | Should Not BeNullOrEmpty
   at <ScriptBlock>, <No file>: line 196
 [-] NAT Network's internal prefix does not overlap with external IP' 70ms
   Expected {0} to be greater than {0}
   223:         $hostips.Count | Should BeGreaterThan 0
   at <ScriptBlock>, <No file>: line 223
Showing output from: docker info

Showing output from: docker version
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      windows/amd64

Showing output from: docker network ls

Warnings & errors from the last 24 hours
Logs saved to C:\dev\logs_20161221-235533.csv
```

@friism

**Comment by friism** [comment]
pinging @JMesser81.

@davidobrien1985 can you try the clean-up script too? Note that it can be a bit [heavy-handed](https://github.com/Microsoft/Virtualization-Documentation/pull/513#issuecomment-266611693).

**Comment by davidobrien1985** [comment]
Got back to testing this (on vacation in Thailand right now).
I ran the clean up script again (I ran it before getting on the plane) and now it works.

**Comment by friism** [comment]
Awesome, thanks for following up.
