### ISSUE TITLE
Docker For Windows Error Linux VM booting up slow

### ISSUE THREAD

**Issue by tonkajuris** [docker/for-win#330]
### Expected behavior
Docker Starts
### Actual behavior
Docker Error with the message:
```
  Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```
### Information
- Diagnostic ID: 3C0AAF9D-0582-43A4-A472-048E72FAC683
- The upload diagnostic process was in an endless loop and had cpu at 100%
 
- Posted log file to issue #274 
- Windows 10.0.14393 Build 14393 
### Steps to reproduce the behavior

  1. New Install
  2. Error happens from fresh install.

**Comment by tonkajuris** [comment]
I switched to the stable version of Docker and it works although strangely the About Docker says 1.13.0-rc3-beta33 (9442).
