### ISSUE TITLE
Unable to start docker on Windows 10: Generic failure

### ISSUE THREAD

**Issue by jamestharpe** [docker/for-win#331]
### Expected behavior

Docker starts

### Actual behavior

Docker crashes with the following message: Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure

### Information

  - Diagnostic ID: 499B149D-C318-4872-95A9-400222AE7F06/2016-12-17_12-05-49
  - Windows 10 Professional version 1607 (OS Build 14393.576)

### Steps to reproduce the behavior

  1. Install using InstallDocker.msi
  2. Try to start docker - error is shown, the whale in the system trey is red.

### Log
```
Version: 1.12.3 (8488)
Channel: Stable
Sha1: d63ec34a49019d2e0b29d7706e57ccfc721ddb8f
Started on: 2016/12/17 12:00:05.607
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.576.amd64fre.rs1_release_inmarket.161208-2252
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[12:00:05.560][Tracking       ][Info   ] Crash report and usage statistics are enabled
[12:00:05.631][SegmentApi     ][Info   ] Usage statistic: appLaunched
[12:00:05.692][NamedPipeClient][Info   ] Sending Version()...
[12:00:05.715][NamedPipeClient][Info   ] Received response for Version
[12:00:05.721][SegmentApi     ][Info   ] Usage statistic: heartbeat
[12:00:01.054][BackendServer  ][Info   ] Started
[12:00:01.054][Moby           ][Info   ] Connecting...
[12:00:05.703][NamedPipeServer][Info   ] Version()
[12:00:05.708][NamedPipeServer][Info   ] Version done.
[12:00:05.951][Notifications  ][Info   ] Docker is starting...
[12:00:05.951][Updater        ][Info   ] Checking for updates on channel Stable...
[12:00:05.969][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[12:00:05.975][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[12:00:05.983][HyperVGuids    ][Info   ] Installing GUIDs...
[12:00:05.989][HyperVGuids    ][Info   ] GUIDs installed
[12:00:05.997][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[12:00:06.459][Updater        ][Info   ] Local build 8488 is as good as the remote 8488 on channel Stable
[12:00:10.096][Firewall       ][Info   ] Ports are opened
[12:00:10.106][HyperV         ][Info   ] Create
[12:00:10.117][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[12:00:12.834][HyperV         ][Info   ] Creating Switch: DockerNAT...
[12:00:13.775][PowerShell     ][Info   ] Run script 'Import-Module Dism; Get-WindowsOptionalFeature -Online | where FeatureName -like "*Hyper-V*" | where State -ne Enabled'...
[12:00:15.912][HyperV         ][Info   ] Hyper-V is running
[12:00:15.917][HyperV         ][Info   ] Create
[12:00:15.924][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[12:00:16.065][HyperV         ][Info   ] Creating Switch: DockerNAT...
[12:00:16.399][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 123
at <ScriptBlock>, <No file>: line 362    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[12:00:16.468][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 123
at <ScriptBlock>, <No file>: line 362
[12:00:16.485][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 123
at <ScriptBlock>, <No file>: line 362
[12:01:39.586][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[12:01:39.599][NamedPipeServer][Info   ] GetDebugInfo()
[12:01:41.456][ErrorReportWindow][Info   ] Open logs
```

**Comment by rneugeba** [comment]
@jamestharpe thanks for the report. There seems to be something broken with your Hyper-V installation. I see errors in the `Microsoft-Windows-Hyper-V-VMMS` event log like:
```
12/17/2016 11:40:29 AM       32609 Error            The Virtual Machine Management Service could not send messages with the Synth3D VSP driver. This server cannot run as a RemoteFX host. You may need to restart the server.
[...]
12/17/2016 11:35:29 AM       15340 Error            The virtual machine bus is not running.
[...]
12/17/2016 12:00:16 PM       26138 Error            Failed while creating virtual Ethernet switch.
```

A few questions/suggestions:
- Could you try to manually create a empty Hyper-V VM and start it and see if that works? You can just go to Hyper-V manager and create a new VM and click through the steps. Then double click on the VM and power up, eventually it should show an error saying "Boot failure. Reboot and select proper Boot device".  If you get there Hyper V should work fine.
- Are you running any AntiVirus/Security software? We had some issues reported with Some security software being the culprit.

**Comment by sendit2me** [comment]
Was getting a similar error, basically deleted the Docker NAT in the switches, 
there was no MobyLinuxVM created, but this was created, and the NAT, when I reset to factory defaults.

**Comment by rneugeba** [comment]
Closing this issue due to lack of activity. Please re-open if the issue persists with the information requested.
thanks

**Comment by shimizukawa** [comment]
I had same issue, however it was resolved.
It can be done by removing `MobyLinuxVM` instance on Hyper-V manager and restarting docker.
http://stackoverflow.com/questions/41182714/unable-to-start-docker-in-windows-10-hyper-v-error-is-thrown

**Comment by kanthi84** [comment]
I am facing same issue. I installed Hyper V manually. Not able to start docker even after Reset to factory defaults.

Error Report says:
nable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'CL-KGANAPATHI' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 132
at <ScriptBlock>, <No file>: line 409
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 181
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 130
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

I have sent the crash report: 56CBBE29-2B63-4E0D-8074-2DB18FD41339/2018-02-06_16-06-15

**Comment by igmwandama** [comment]
It might help someone, I experience the same issue and no solution could work.
Then I thought of adding my user account and that of local administrator to **Hyper-V Administrator**, after that docker is now working.

though not sure if its really a solution

**Comment by shimizukawa** [comment]
Adding current user to **Hyper-V Administrators** group works fine to me! Thanks!

**Comment by fakabbir** [comment]
Tried uncheck and check back after restart worked for me:
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
