### ISSUE TITLE
Cannot start service docker on computer '.'. - when trying to switch to windows containers

### ISSUE THREAD

**Issue by chetanku** [docker/for-win#3317]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: 40E293D8-AC8F-45B9-937F-0F7264117CD1/20190130122410

### Expected behavior

It should switch to windows container

### Actual behavior

```
Cannot start service docker on computer '.'.
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 232
   at Docker.Backend.Processes.WindowsDockerDaemon.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 165
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 225
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 98
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180
```

### Information

  - Windows Version: Windows 10 Enterprise(1803)
  - Docker for Windows Version: ~18.09.1

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by chetanku** [comment]
After hours of troubleshooting, The issue was my office's security policies.  we added docker and hyper-v to exclusion policies and docker is working like a charm.
