### ISSUE TITLE
Docker not starting on Windows 10

### ISSUE THREAD

**Issue by jfallik** [docker/for-win#3328]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C63F46BE-4EF8-4A7B-A55A-A569340C3C75/20190201153123
[20190201153123.zip](https://github.com/docker/for-win/files/2823266/20190201153123.zip)

### Information

  - Windows Version: Windows 10 Enterprise
  - Docker for Windows Version: 2.0.0.30215

### Steps to reproduce the behavior

  1. Start Docker
  2. Docker doesn't start...
  3. Repeat process... I have tried rebooting, I have tried uninstalling and reinstalling, I made sure to have the Windows checkbox checked... Nothing makes a difference... I am running on a Physical machine

**Comment by mikeparker** [comment]
Relevant log entry:
```
[14:40:14.352][NamedPipeServer][Error  ] Unable to execute Start: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.
at Start-MobyLinuxVM, <No file>: line 296
at <ScriptBlock>, <No file>: line 412    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 255
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 117
```
