### ISSUE TITLE
Docker desktop crashes instantly when switching to windows containers

### ISSUE THREAD

**Issue by JerkerPihl** [docker/for-win#3340]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C0EA2572-5C59-4E23-BA7F-1E8215DC01EA/20190204230934

### Expected behavior
Switching to windows container 
### Actual behavior
Object reference not set to an instance of an object.
   at Docker.Backend.Features.Installer.CheckInstalledFeatures(Feature[] features) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\Features\Installer.cs:line 34
   at Docker.Backend.ContainerEngine.Windows.CheckInstallation() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 251
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 197
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 98
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180

### Information

  - Windows Version: Windows 10 Pro version 1809
  - Docker for Windows Version:
Version 2.0.0.2 (30215)
Channel: stable
Build: 0b030e1

### Steps to reproduce the behavior

  1. ... Start docker
  2. ... Switch to windows containers in icon menu

**Comment by JerkerPihl** [comment]
I have also uninstalled and then reinstalled again with no luck

**Comment by rexunderlinehxiao** [comment]
+1

**Comment by mikeparker** [comment]
We've found a possible bug if you have a corrupt `%ProgramData%/DockerDesktop/tmp-d4w/backend-info.json` file. Could you paste the contents of this file please?

Also, as a workaround, you can delete the file. Please let us know if this works or doesn't work.

**Comment by sawyer0413** [comment]
I deleted the %ProgramData%/DockerDesktop/tmp-d4w/backend-info.json file, and it still crashes.

**Comment by JerkerPihl** [comment]
Copied it
[backend-info.zip](https://github.com/docker/for-win/files/3281916/backend-info.zip)

**Comment by mikeparker** [comment]
Ok, good news - the file you linked @JerkerPihl is an invalid json file, and thats what we were expecting. We have fixed the code to deal with corrupt json files, so at least in future it won't crash. 

That said, i'd still like to figure out what causes the corrupt file in the first place.
