### ISSUE TITLE
An error occurred when selecting "Switch to Windows containers

### ISSUE THREAD

**Issue by dratnkantingavale** [docker/for-win#3342]
Could not save daemon configuration to C:\ProgramData\Docker\config\daemon.json: Access to the path 'C:\ProgramData\Docker\config' is denied.
   at Docker.WPF.DaemonOptionsLoader.Get(ContainerEngineMode mode) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\DaemonOptionsLoader.cs:line 85
   at Docker.WPF.BackendClient.Start(ContainerEngineMode mode) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 61
   at Docker.Actions.<>c__DisplayClass28_0.<SwitchDaemon>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 305
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by tonyaveniros** [comment]
Of course, I am seeing this, too, and no one one has responded. Because Docker on Windows.

**Comment by KhrystynaPopadyuk** [comment]
I had it too. Try to run docker as Administrator. This helped me.

**Comment by goyzhang** [comment]
I have the same issue in

> Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3

Looks like no one cares... @KhrystynaPopadyuk 's method helps

**Comment by raulAtNines** [comment]
Same issue as of July 18, 2019. Running as admin worked, but it will fail on Windows restart due to running as not-admin by default.
