### ISSUE TITLE
Fresh Install - Dock Failed to Initialize (May be related to my complicated setup)

### ISSUE THREAD

**Issue by dashtesla** [docker/for-win#3350]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

I did submit a crash report.
DF1C5894-747C-4191-9D5C-3C292D707973/20190207053135

### Expected behavior
I would like to be able to start docker for the first time.

### Actual behavior
Doesn't start for the first time after I input my credentials.

### Information

  - Windows Version: Windows Server 2019 Datacenter Build 17763.292
  - Docker for Windows Version: Latest, "Docker version 18.09.1, build 4c52b90"

### Steps to reproduce the behavior

  1. Download
  2. Install (why is this funny? XD)

I don't have any more files other than the crash report, also have no idea how docker works i'm trying it out for the first time.

This is my main server it runs Hyper-V VMs already I have Linux and Windows VMs running, it's also where I run my AD Domain Controller as a VM which autostarts when the server boots which brings my entire network to life even though this is a home network I have a server room and a lot of equipment so it's like a nerdy home.

I'm also not a programmer I deal with hardware and infrastructure a lot more, I'm also not familiar with github all that much so keep that in mind as i submit all this. 

All I want to accomplish is to run the container for Cryptomator Server without having to deploy a dedicated server just for that (I might in the future but I want a very specific server for that).

Any help is appreciated thanks.

Edit: I just realised that it did create a VM called MobyLinuxVM oddly enough didn't ask me for any permission, didn't ask where i wanted the VM the resources I would like to assign to it and it started on it's own apparently.

===========================================================
Additional Info from the failed to initialize window:
```

 at Docker.WPF.ClientConfig.DockerLogin.SetCredentialInStore(DockerLoginCredential cred) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\ClientConfig\DockerLogin.cs:line 158
   at Docker.WPF.ClientConfig.DockerLogin.OnCredentialChanges(Auth cred) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\ClientConfig\DockerLogin.cs:line 112
   at Docker.Core.Mediator`1.Raise(T ev) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\Mediator.cs:line 50
   at Docker.WPF.DockerHub.CredentialManager.Store(Credential cred, Credential oAuthCred) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\DockerHub\CredentialManager.cs:line 134
   at Docker.WPF.DockerHub.CredentialManager.<ValidateBasicCredentialsAsync>d__21.MoveNext() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\DockerHub\CredentialManager.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.WPF.WelcomeWindow.<LogIn>d__10.MoveNext() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\WelcomeWindow.xaml.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Program.cs:line 216
```
===========================================================

**Comment by mikeparker** [comment]
Possible duplicate of https://github.com/docker/for-win/issues/3326

**Comment by mikeparker** [comment]
Hi, I've identified a potential cause due to the way our different APIs handle special characters in passwords.

If you have special characters in your password you may find that changing your password fixes this issue.

If you do resolve this I would be interested in any findings, but obviously please don't post details of your passwords here :) For anything confidential you can reach me on the public community slack and leave me a message there.

**Comment by vfrz** [comment]
I was having the same exception when trying to log in, and that was because of my password.
I've changed it since, there was these special characters in the old one: $#;_%'"~*{
Hope it can help :)

**Comment by mikeparker** [comment]
Great to hear, thanks! This bug is fixed next release.

**Comment by sidc883** [comment]
I dont think it still works, since I had changed by password to remove a special character @ which i was using earlier. Now my password has Upper case character, lower case characters and numbers, eg. Abcd1234.
