### ISSUE TITLE
D29A7EB9-C168-4766-8170-EE2EFFFA1188/20190207001037

### ISSUE THREAD

**Issue by timtim00** [docker/for-win#3351]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: D29A7EB9-C168-4766-8170-EE2EFFFA1188/20190207001037

### Actual behavior
Crashes on startup...  Will not switch to Windows Containers or Shutdown without freezing.
### Information
Receiving error when doing pretty much anything.  I'm not entirely sure what all is happening, very new to this!  
Upon install I receive this:
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

 I also receive this when trying to do ``docker run hello-world`` in powershell:

C:\Program Files\Docker\Docker\Resources\bin\docker.exe: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

 

  - Windows Version: windows 10/amd64
  - Docker for Windows Version: 18.09.1

### Steps to reproduce the behavior

  1. ... Install Docker.
  2. ...

**Comment by mikeparker** [comment]
Duplicate of https://github.com/docker/for-win/issues/1221
* Windows updates may have broken some Hyper-V components. See https://github.com/docker/for-win/issues/1221#issuecomment-493118403 for the 'control flow guard' fix
