### ISSUE TITLE
Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

### ISSUE THREAD

**Issue by amastrobera** [docker/for-win#3358]
I have a windows 10 Pro virtual machine, hosted on Ubuntu 18.04.  I activated Hyper-V in the windows features, then installed docker. As I start docker over there I get this error: 

--- diagnostic ID : 14C8EEFB-6F85-4261-AF7D-D0DA66004DE8/20190207144901 ----

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID 80A425AD-E805-4858-BA62-0076058EA51F)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID 80A425AD-E805-4858-BA62-0076058EA51F).
at Start-MobyLinuxVM, <No file>: line 296
at <ScriptBlock>, <No file>: line 412
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 155
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by Outek** [comment]
I had the same issue until i realized, i did not activate "nested virtualization" on my workstation, maybe it's the same issue?

**Comment by smallswan399** [comment]
For those who are running azure virtual machines, your machines must be v3 virtual machines or you will get the issue
[https://docs.microsoft.com/en-us/azure/virtual-machines/windows/nested-virtualization](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/nested-virtualization)
