### ISSUE TITLE
Upload diagnostics hanging indefinetely

### ISSUE THREAD

**Issue by artisticcheese** [docker/for-win#337]
### Expected behavior
Diagnostics uploaded
### Actual behavior
Hanging indefintely
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
See description

```
[12:38:21.411][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[12:38:21.414][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\admin\AppData\Local\Temp\j52iyklo.04q\mobyLogs.tar)...
[12:38:21.414][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\admin\AppData\Local\Temp\j52iyklo.04q\pcap.tar)...
[12:38:21.415][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[12:38:21.423][NamedPipeClient][Error  ] Unable to send DownloadVmLogs: Could not load type 'Docker.Win32Helpers.MobyLogs' from assembly 'Docker.Win32Helpers, Version=1.0.6155.23386, Culture=neutral, PublicKeyToken=null'.
[12:38:21.416][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\admin\AppData\Local\Temp\j52iyklo.04q\pcap.tar)
[12:38:21.423][CrashReport    ][Warning] Unable to collect guest diagnostic: Could not load type 'Docker.Win32Helpers.MobyLogs' from assembly 'Docker.Win32Helpers, Version=1.0.6155.23386, Culture=neutral, PublicKeyToken=null'.
[12:38:21.418][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\admin\AppData\Local\Temp\j52iyklo.04q\mobyLogs.tar)
[12:38:21.418][NamedPipeServer][Info   ] GetDebugInfo()
[12:38:21.418][NamedPipeServer][Error  ] Unable to execute DownloadVmLogs: Could not load type 'Docker.Win32Helpers.MobyLogs' from assembly 'Docker.Win32Helpers, Version=1.0.6155.23386, Culture=neutral, PublicKeyToken=null'.    at Docker.Backend.HyperV.DownloadLogs(String destinationTarFile)
   at Docker.Backend.Backend.DownloadVmLogs(String destinationTarFile)
   at Docker.Backend.BackendServer.<Run>b__5_15(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[12:38:47.629][NamedPipeServer][Info   ] GetDebugInfo done in 00:00:26.2114768.
[12:38:47.632][NamedPipeClient][Info   ] Received response for GetDebugInfo
[12:40:03.581][FeedbackSettings][Info   ] Open logs
```
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Version 1.13.0-rc3-beta33 (9422)
### Steps to reproduce the behavior

  1. Choose "Upload diagnostic"

**Comment by rneugeba** [comment]
@artisticcheese this looks like a dup of #332 so I'm closing it. Beta34 should have a fix.
thanks
