### ISSUE TITLE
Docker Not Starting Successfully Windows 10 under VMWare Fusion

### ISSUE THREAD

**Issue by drmacro** [docker/for-win#3390]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker Desktop starts

### Actual behavior

Docker startup eventually fails with this failure:

No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 155
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

This is consistent.

Did a Windows reset to try to get a fresh and clean install, reinstalled Docker Desktop. 

Followed instructions here in the message from vitaliybibikov:

https://github.com/docker/for-win/issues/2253

Win 1803, latest docker, running in VM, was not working for Linux Containers.

After 2 days of trying:

1. Disable H-V and Containers in Features
2. Restart.
3. Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All  from elevated PS
4. Enable Containers.
5. Services => Start docker not under local account => admin will do
6. Restart
7. Profit

Also tried resetting to defaults, which had no apparent effect.

### Information
  - Is it reproducible? Yes
  - Is the problem new? Been happening for at least 3 months
  - Did the problem appear with an update? Yes, but not sure what update
  - Windows Version:

Windows 10 Pro, 1809, installed 2/13/2019, OS Build 17763.316

  - Docker for Windows Version:

Version 2.0.0.2 (30215)

### Steps to reproduce the behavior

Attempt to start Docker Desktop

**Comment by drmacro** [comment]
Diagnostics ID: 82B45F84-CED9-4F94-8322-286BEECD3EB0/20190214094608

**Comment by robthejedi** [comment]
I was having this same issue, I found the resolution in this post: https://www.trustedsec.com/2013/11/running-hyper-v-inside-vmware-fusion/

I made the change in the vm settings in VMWare under processors and memory to enable hypervisor applications in the VM. After that it started running without issue. 

My Env: 
Windows 10 Enterprise  (10.0.17763) Build 17763, installed 4/4/2019
Docker for Windows Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3
