### ISSUE TITLE
No activity detected on VM, aborting

### ISSUE THREAD

**Issue by thisisbrianm** [docker/for-win#3467]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 67F69B6B-0C2F-4B3A-9806-36F2F3D1AC26/20190226133055

### Expected behavior
Docker starts

### Actual behavior
Docker does not start, get an error popup with the following text:
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information
 I'm looking for a way to fix this error. I have looked at the other threads on this issue and don't see any solutions besides reseting to factory defaults. I would prefer not to do that. Any help would be appreciated. Thanks.

  - Windows Version: Windows 10 Pro Build 17134
  - Docker for Windows Version: 
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3

### Steps to reproduce the behavior

  1. ... 
  2. ...

**Comment by DongXu1234** [comment]
update win 10 to version 1607, it works for me.
setting -> windows update, good luck,bro
