### ISSUE TITLE
Docker service fails to start (new install)

### ISSUE THREAD

**Issue by Javerre** [docker/for-win#3468]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: 2F9FB3E0-44E1-4FD7-BE2F-29D914FBC095/20190226202010

### Expected behavior
Docker service starts

### Actual behavior
Docker service fails to start. The following error is reported:

```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID C9D026C2-38A1-473C-A7DD-1FFED0F55F39)
at Start-MobyLinuxVM, <No file>: line 296
at <ScriptBlock>, <No file>: line 412
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

### Information

  - Windows Version: Windows 10 Pro 1803 17134.590
  - Docker for Windows Version: 18.09.2, build 6247962

First attempt to install docker, failed right out of the box. Only non-default action was to check the "Use Windows containers" in the installer.

### Steps to reproduce the behavior

  1. Download latest docker for windows and install. 
  2. Select option to use Windows containers by default. 
  3. Logout and login to complete install as prompted
  4. Dialog box appears asking to enable HyperV. Select option to enable with restart.
  5. Following restart, Dialog box appears offering to start docker service. Accept
  6. Service fails to start and error box is displayed.
  7. Try option to "Reset to factory defaults"
  8. Service fails to start with same error as before

**Comment by Javerre** [comment]
Having read #1073 I went and checked via windows Control Panel to see if Hyper-V and Containers were enabled as per the documentation. They were. However, since @jasonbivins kindly provided some powershell commands to try I thought I would give them a go (albeit in a slightly shorthand form). Note that I did not uninstall Hyper-V, Containers or Docker to do this.

Additional steps were
  9. Open a powershell with elevated privileges
  10. Enter the command "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All"
  11. Install completes with restart required = FALSE
  12. Enter the command "Enable-WindowsOptionalFeature -Online -FeatureName Containers -All"
  13. Install completes with restart required = FALSE. 
  14. Right click on the red Docker icon in the tray and select Restart...
  15. Confirm the restart at the dialog box that appears and...
  16. Presto! **Docker is now running!**

**Comment by Javerre** [comment]
Having also read #1066 I would like to comment that like @sinlov the operating system involved was a Windows 10 Pro upgrade from Windows 10 Home. For me, It was fortunately **not** necessary to reinstall Windows 10 Pro to get this to work.
