### ISSUE TITLE
Docker gets stuck after crashing due to power cut.

### ISSUE THREAD

**Issue by rebussharma** [docker/for-win#3478]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:
B545B650-8C32-419F-BA2F-A689BC1D0B91/20190227143529

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. ... While docker is running, unplug computer from power source
  2. ...

### logs:
Version: 2.0.0.3 (31259)
Channel: stable
Sha1: 8858db33c8692b69de9987a5d672798d778735b2
Started on: 2019/02/27 15:34:24.014
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1803
Build: 17134
BuildLabName: 17134.1.amd64fre.rs4_release.180410-1804
File: C:\Users\rebus\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[15:34:24.092][GUI            ][Info   ] Starting...
[15:34:24.154][ComponentVersions][Info   ] Edition community
[15:34:25.092][GUI            ][Error  ] Object reference not set to an instance of an object.
[15:34:25.123][NamedPipeClient][Info   ] Sending Version()...
[15:34:25.123][NamedPipeClient][Info   ] Received response for Version
[15:34:25.123][NamedPipeClient][Info   ] Sending GatherDiagnostics(-path C:\Users\rebus\AppData\Local\Temp\ gather -id B545B650-8C32-419F-BA2F-A689BC1D0B91/20190227153425, C:\Users\rebus\AppData\Local\Temp\B545B650-8C32-419F-BA2F-A689BC1D0B91/20190227153425.zip)...
[14:57:21.872][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[14:57:21.872][HyperV         ][Info   ] Destroying Switch DockerNAT...
[14:57:21.887][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[14:57:21.981][HyperV         ][Info   ] Delete VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[14:57:21.981][HyperV         ][Debug  ] [destroy] took 00:00:01.8307598 to run
[14:57:21.981][Firewall       ][Info   ] Closing ports...
[14:57:21.981][Firewall       ][Info   ] Removing all existing rules...
[14:57:21.997][Firewall       ][Info   ] All existing rules are removed.
[14:57:21.997][Firewall       ][Info   ] Ports are closed
[14:57:21.997][HyperVGuids    ][Info   ] Removing GUIDs...
[14:57:21.997][HyperVGuids    ][Info   ] GUIDs removed
[14:57:22.012][Linux          ][Warning] The directory is not empty.

[14:57:22.012][PowerShell     ][Info   ] Run script with parameters: -RemoveNetworks True
[14:57:22.356][NamedPipeServer][Error  ] Unable to execute Destroy: Object reference not set to an instance of an object.    at Docker.Backend.ContainerEngine.Windows.CleanUpData(Settings settings) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 289
   at Docker.Backend.ContainerEngine.Windows.DoDestroy(Settings settings, Boolean keepVolume) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 283
   at Docker.Backend.ContainerEngine.Windows.Destroy(Settings settings, Boolean keepVolume) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 175
   at Docker.Backend.Backend.Destroy(Settings settings, ContainerEngineMode mode, Boolean keepVolume) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\Backend.cs:line 149
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180
[14:57:22.356][NamedPipeServer][Error  ] Pipe failure: Pipe is broken.    at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at Docker.Core.Pipe.NamedPipeServer.<HandleRequestAsync>d__13.MoveNext() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 152
[15:34:07.832][TimeIntegrationService][Info   ] Reset
[15:34:07.848][PowerShell     ][Info   ] Run script...
[15:34:08.163][PowerShell     ][Info   ] Run script...
[15:34:12.804][BootHelper     ][Info   ] Cold boot from full shutdown
[15:34:25.123][NamedPipeServer][Info   ] Version()
[15:34:25.123][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:34:25.123][NamedPipeServer][Info   ] GatherDiagnostics(-path C:\Users\rebus\AppData\Local\Temp\ gather -id B545B650-8C32-419F-BA2F-A689BC1D0B91/20190227153425, C:\Users\rebus\AppData\Local\Temp\B545B650-8C32-419F-BA2F-A689BC1D0B91/20190227153425.zip)
[15:35:14.706][NamedPipeClient][Info   ] Received response for GatherDiagnostics
[15:35:14.706][NamedPipeServer][Info   ] GatherDiagnostics done in 00:00:49.5834530.
[15:35:14.722][GUI            ][Info   ] Sending Bugsnag report 98bc8fa4-8f5d-46c1-af11-29b040ceaeb5...
[15:35:15.128][GUI            ][Info   ] Bugsnag report 98bc8fa4-8f5d-46c1-af11-29b040ceaeb5 sent
[15:37:07.979][CrashReport    ][Info   ] Uploading diagnostics B545B650-8C32-419F-BA2F-A689BC1D0B91/20190227153425
[15:37:15.088][CrashReport    ][Info   ] Uploaded succesfully diagnostics B545B650-8C32-419F-BA2F-A689BC1D0B91/20190227153425
[15:39:49.590][ErrorReportWindow][Info   ] Open logs

[logs.txt](https://github.com/docker/for-win/files/2912444/logs.txt)

**Comment by rebussharma** [comment]
Solved:
1. run cmd as admin
2. cd %appdata%
3. remove/force remove Docker from appdata/roaming
        rd /s /q "Docker"
4. start docker
