### ISSUE TITLE
Docker for Windows does not start

### ISSUE THREAD

**Issue by lestremo** [docker/for-win#3553]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:
DF8D3889-228D-4611-848B-AABEAFA9BB7F/20190312134432
### Expected behavior
Docker for Windows launches successfully
### Actual behavior
The following error occurs:

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'IBMPC4ERRI' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information

  - Windows Version:  Windows 10 Enterprise, Version 1809, OS Build 17763.316
  - Docker for Windows Version:  2.0.0.3

### Steps to reproduce the behavior

  1. Install Docker for Windows 2.0.0.3.
  2. Reboot PC
  3. Launcher Docker

**Comment by lestremo** [comment]
The issue was that I was using Linux containers.  When I switched to Windows containers, everything worked.  Ugh.
