### ISSUE TITLE
Startup on Windows 10 after upgrade to docker 2.0.0.3 fails with 'The parameter is incorrect'

### ISSUE THREAD

**Issue by schifferle** [docker/for-win#3560]
Startup on Windows 10 after upgrade to docker 2.0.0.3 fails with 'The parameter is incorrect':

The parameter is incorrect.

   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at Docker.WPF.Credentials.CredentialAsker.DecryptPassword(Byte[] encrypted) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\Credentials\CredentialAsker.cs:line 98
   at Docker.WPF.Credentials.CredentialAsker.RetrieveCredential(String target) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\Credentials\CredentialAsker.cs:line 116
   at Docker.WPF.ShareHelper.UpdateMounts() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\ShareHelper.cs:line 87
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 101
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by schifferle** [comment]
Hi togehter, if I start it with an admin account it works :) Please fix for non-admin modes and adapt the errormessage :-)

**Comment by juniormayhe** [comment]
Completely remove docker, restarted and installed the latest 2.0.0.31259, then Reset docker to defaults and now it is starting.

**Comment by ASk1** [comment]
Solved the problem removing Docker Host Filesystem Access record in Credential Manager

**Comment by jawadSharif** [comment]
In my case i had imported credentials from a backup of another disk, removing entries from credentials manager worked,
PS: Run As Admin or Re-install did not work for me.Thanks @ASk1 

> Solved the problem removing Docker Host Filesystem Access record in Credential Manager

**Comment by NicolasDorier** [comment]
This issue is not fixed, https://github.com/docker/for-win/issues/3560#issuecomment-537067861 solved it.
