### ISSUE TITLE
Unable to switch to window container from tray icon

### ISSUE THREAD

**Issue by shamsheerd** [docker/for-win#3608]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 85BE926D-95EF-408A-80A0-4880192FAD25/20190322001749

### Expected behavior
Should be able to switch to Window container successfully.

### Actual behavior
Time out has expired and the operation has not been completed.
Unable to switch to window container.

### Information

  - Windows Version: Win 10 Enterprise
  - Processor: Intel Core i7 - 8850H CPU 
  - Docker for Windows Version: 2.0.0.3 (31259)

I have uninstalled and selected 'Use Window containers..' option while installing it again (restarted where ever requred)

### Steps to reproduce the behavior
1. From the tray icon, right click on Docker.
2. Select 'Switch to Window containers..." and observe

**Error Message:**
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 232
   at Docker.Backend.Processes.WindowsDockerDaemon.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 165
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 225
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 98
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180

![image](https://user-images.githubusercontent.com/12619811/54778278-415def00-4c3a-11e9-9245-b7a5fe49322b.png)

**Comment by shamsheerd** [comment]
Anyone looking at this issue?
