### ISSUE TITLE
Can't switch to Linux Container

### ISSUE THREAD

**Issue by jahanzeb-j** [docker/for-win#3628]
This Error occured while i'm switching to linux container. I am using docker desktop for windows, using win 10. Running on Windows container is working fine. 

**An Error Occurred** 
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass28_0.<SwitchDaemon>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 305
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by mikeparker** [comment]
Are you using Cisco AnyConnect?
Possible dupe of https://github.com/docker/for-win/issues/2050
- stop Cisco agent, restart docker, start Cisco agent.
