### ISSUE TITLE
Docker Error while doing factory reset on windows 10.

### ISSUE THREAD

**Issue by techsavvypp** [docker/for-win#3675]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics: Yes
  - Diagnostics ID: 40B272FC-CF1C-4BCD-8292-D87ADDD4FF6E/20190402163901

### Expected behavior
Docker should Run Properly and should get factory reset without any error.

### Actual behavior
![image](https://user-images.githubusercontent.com/42607623/55399303-602c8180-5568-11e9-93a6-2220ae2c069b.png)

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 155
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

### Information

  - Windows Version: 10
  - Docker for Windows Version: 
![image](https://user-images.githubusercontent.com/42607623/55399324-6cb0da00-5568-11e9-891e-8aa91eaf2daa.png)

### Steps to reproduce the behavior

1) When Docker started for first time
2) When doing Factory Reset.

**Comment by techsavvypp** [comment]
When I install and start the Docker it throws above error.
