### ISSUE TITLE
docker desktop windows cannot start up

### ISSUE THREAD

**Issue by ikelca** [docker/for-win#3706]
`time="2019-04-07T10:07:40-04:00" level=error msg="cannot create kubernetes PKI: the certificate is not valid yet"

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0()
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1()`

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: win10
  - Docker for Windows Version: latest

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mikeparker** [comment]
Hi, can you add your diagnostics ID please?

**Comment by mikeparker** [comment]
Can you confirm if your system clock is correct? See also https://github.com/docker/for-win/issues/2913
