### ISSUE TITLE
"Error response from daemon: Bad Response from Docker engine" 18.09.2

### ISSUE THREAD

**Issue by afiorillo** [docker/for-win#3707]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 06FCA96B-E80C-4CD3-AD97-EEA0C1902AB5/20190407130755

### Expected behavior

A few minutes after starting the Docker daemon `docker info` returns info about the docker environment

### Actual behavior

A few minutes after starting the daemon (as Admin and a regular user) `docker info` returns an error message stating

> Error response from daemon: Bad Response from Docker engine

### Information

  - Windows Version: Windows 10 Pro, Version 1803
  - Docker for Windows Version: Docker version 18.09.2, build 6247962

The machine is in swarm mode as a worker. I noticed the issue when the manager reported all of the workers (5 roughly identical machines) as down.

This appears to be similar to #1028 and #2073 but both were closed due to inactivity. 

Checking the logs makes me think this may be a networking error. Just before the docker daemon becomes unresponsive, this error message appeared in the log

> [13:01:31.833][Moby           ][Info   ] [  182.067943] nf_conntrack: default automatic helper assignment has been turned off for security reasons and CT-based  firewall rule not found. Use the iptables CT target to attach helpers instead.
> [13:02:26.414][Moby           ][Info   ] <--DOCKER-->{"command":"dockerstate","severity":"fatal","diagnose":"2019-04-07T17:02:26Z docker github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).rejoinClusterBootStrap(0xc4213d5c20)\n2019-04-07T17:02:26Z docker \t/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:305 +0x2d0\n2019-04-07T17:02:26Z docker github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).(github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.rejoinClusterBootStrap)-fm()\n2019-04-07T17:02:26Z docker \t/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:175 +0x2c\n2019-04-07T17:02:26Z docker github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).triggerFunc(0xc4213d5c20, 0xdf8475800, 0xc4216fec60, 0xc42152eaf0)\n2019-04-07T17:02:26Z docker \t/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:256 +0x134\n2019-04-07T17:02:26Z docker created by github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).clusterInit\n2019-04-07T17:02:26Z docker \t/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:178 +0x8e9\n2019-04-07T17:02:26Z docker + failed_to_start\n2019-04-07T17:02:26Z docker + tail /var/log/docker.log","setstate":"failed to start"}
> [13:03:53.950][ApiProxy       ][Info   ] time="2019-04-07T13:03:53-04:00" msg="proxy >> GET /_ping\n"
> [13:03:53.952][ApiProxy       ][Info   ] time="2019-04-07T13:03:53-04:00" msg="error reading response from Docker:  HvSocket has already been closed"
> [13:03:53.954][ApiProxy       ][Info   ] time="2019-04-07T13:03:53-04:00" msg="proxy >> GET /v1.39/info\n"
> [13:03:53.957][ApiProxy       ][Info   ] time="2019-04-07T13:03:53-04:00" msg="error reading response from Docker:  HvSocket has already been closed"

### Steps to reproduce the behavior

  1. Install Docker on Windows 10 machine
  2. Configure as a swarm worker, i.e. `docker swarm join ...`
  3. Wait about 10 minutes
  4. `docker info`

**Comment by mikeparker** [comment]
Looks like an issue for moby/moby, include this:

Relevant part of log (vm/var/log/docker.log)
```
2019-04-07T17:02:24Z docker time="2019-04-07T17:02:24.528221200Z" level=error msg="node: 4d4e5a83df11 is unknown to memberlist"
2019-04-07T17:02:25Z docker time="2019-04-07T17:02:25.327818800Z" level=debug msg="memberlist: Initiating push/pull sync with: 192.168.65.3:7946"
2019-04-07T17:02:25Z docker time="2019-04-07T17:02:25.328140900Z" level=debug msg="memberlist: Stream connection from=192.168.65.3:36030"
2019-04-07T17:02:25Z docker time="2019-04-07T17:02:25.328893400Z" level=error msg="node: 4d4e5a83df11 is unknown to memberlist"
2019-04-07T17:02:25Z docker time="2019-04-07T17:02:25.329219000Z" level=error msg="node: 4d4e5a83df11 is unknown to memberlist"
2019-04-07T17:02:25Z docker time="2019-04-07T17:02:25.329389500Z" level=debug msg="Initiating bulk sync with node b8fd69d75585 after reconnect"
2019-04-07T17:02:25Z docker time="2019-04-07T17:02:25.329513700Z" level=debug msg="linuxkit-00155d28d601(4d4e5a83df11): Initiating bulk sync with node b8fd69d75585"
2019-04-07T17:02:25Z docker time="2019-04-07T17:02:25.329608000Z" level=debug msg="linuxkit-00155d28d601(4d4e5a83df11): Initiating unsolicited bulk sync for networks [] with node b8fd69d75585"
2019-04-07T17:02:25Z docker time="2019-04-07T17:02:25.527996200Z" level=error msg="node: 4d4e5a83df11 is unknown to memberlist"
2019-04-07T17:02:26Z docker panic: runtime error: invalid memory address or nil pointer dereference
2019-04-07T17:02:26Z docker [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x10927d0]
2019-04-07T17:02:26Z docker 
2019-04-07T17:02:26Z docker goroutine 627 [running]:
2019-04-07T17:02:26Z docker github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).rejoinClusterBootStrap(0xc4213d5c20)
2019-04-07T17:02:26Z docker 	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:305 +0x2d0
2019-04-07T17:02:26Z docker github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).(github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.rejoinClusterBootStrap)-fm()
2019-04-07T17:02:26Z docker 	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:175 +0x2c
2019-04-07T17:02:26Z docker github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).triggerFunc(0xc4213d5c20, 0xdf8475800, 0xc4216fec60, 0xc42152eaf0)
2019-04-07T17:02:26Z docker 	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:256 +0x134
2019-04-07T17:02:26Z docker created by github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb.(*NetworkDB).clusterInit
2019-04-07T17:02:26Z docker 	/go/src/github.com/docker/docker/vendor/github.com/docker/libnetwork/networkdb/cluster.go:178 +0x8e9
```

**Comment by giggio** [comment]
@andrewmfiorillo 	I saw your reference in the issue I opened, and I found a solution to my problem. Maybe it relates to yours:

https://github.com/docker/for-win/issues/2073#issuecomment-518444898

**Comment by andrewmfiorillo** [comment]
@giggio Good catch! I've actually moved on to a different project and have given up on this issue.

I suspect the solutions may be different as I saw the issue specifically within a Windows environment. I do remember trying to debug with application permissions (e.g. running as Administrator in Windows) without luck. :man_shrugging:
