### ISSUE TITLE
unable to start docker on Windows 10

### ISSUE THREAD

**Issue by accgaurn** [docker/for-win#3716]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8DFDDFD7-C940-403D-8DE3-C7065D2B9CD8/20190408210559

### Information

  - Windows Version: 10
  - Docker for Windows Version: 2.0.0.3

### Steps to reproduce the behavior

  1. install docker with the docker instaler for windows
  2. run the docker desktop

**ERROR:**
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 155
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Also from powershell when i try any docker command apart from docker --version i get this error:**
PS C:\Users\accgaurn> docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by timolahlou** [comment]
i have the same problem!

**Comment by anantshankar17** [comment]
Can you please post this to the docker repo as its a docker issue. There are multiple instances of this error, e.g: https://github.com/docker/for-win/issues/3744. Rebooting the machine normally fixes this. We are also looking if there is something at our end

**Comment by mikeparker** [comment]
Are you using Cisco AnyConnect?
Possible dupe of https://github.com/docker/for-win/issues/2050
- stop Cisco agent, restart docker, start Cisco agent.
