### ISSUE TITLE
Docker unable to start

### ISSUE THREAD

**Issue by smnason** [docker/for-win#3733]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Docker would start

### Actual behavior

Docker did not start

### Information

  - Windows Version: MS Windows Server 2016 Datacenter running on AWS
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. Try to start Docker

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID D9F784BB-DC9A-4EA3-A21C-55279072E613)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID D9F784BB-DC9A-4EA3-A21C-55279072E613).
at Start-MobyLinuxVM, <No file>: line 296
at <ScriptBlock>, <No file>: line 412
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 155
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by mikeparker** [comment]
Hi, can you check Hyper-V is enabled and check all the components / services are running?

Also out of curiosity it looks like you're running Docker Desktop on a Windows Server, rather than using the supported Docker Enterprise which is shipped with the Windows Server license, or simply using Linux machines in AWS to run docker directly. I just want to check you're aware of those more straightforward alternatives?
