### ISSUE TITLE
Docker crash when starting on Windows 10

### ISSUE THREAD

**Issue by pmerlin** [docker/for-win#3737]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

At Docker Start:
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'DESKTOP-CJNAVP5' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
  1. ...
  2. ...

**Comment by mikeparker** [comment]
Hi, can you check that the Virtual Machine Management service is running?

**Comment by JaneRizzo** [comment]
Hi Mike, 

I have the same error message, and have verified that Virtual Machine Mgmt is running, and that Hyper-V is active.  Assuming the original poster comes back and tells you the same thing, could you provide a solution?  I'd really appreciate knowing how to fix this issue; it's really a blocker for my work.

Thanks!

Jane
