### ISSUE TITLE
Switch to Linex container failed

### ISSUE THREAD

**Issue by xuanrenchen** [docker/for-win#3747]
I encountered an issue when I switch the windows container to Linux container? So anybody can give some advices? Below is issue description.
[log.txt](https://github.com/docker/for-win/files/3075902/log.txt)

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID 74DC921C-726C-471F-8E5E-5FA05F4872E5)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID 74DC921C-726C-471F-8E5E-5FA05F4872E5).
```
at Start-MobyLinuxVM, <No file>: line 296
at <ScriptBlock>, <No file>: line 412
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass28_0.<SwitchDaemon>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 305
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

**Comment by xuanrenchen** [comment]
@docker-desktop-robot

**Comment by mikeparker** [comment]
Could you check if the following Hyper-V components are running?

- Hyper-V Host Compute Service
- Hyper-V Virtual Machine Management

**Comment by mikeparker** [comment]
Closing due to lack of response. Please open a new ticket with the above information if the issue persists.
