### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by JLospinoso** [docker/for-win#375]
### Expected behavior
Docker should startup after installation

### Actual behavior
Docker crashes with an error reporting dialogue

### Information

```
Version: 1.12.5 (9503)
Channel: Stable
Sha1: 3e6f00c1dcd935ed4d9507b72693b9ae0359ca50
Started on: 2017/01/08 20:25:09.967
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.576.amd64fre.rs1_release_inmarket.161208-2252
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[20:25:09.927][Tracking       ][Info   ] Crash report and usage statistics are enabled
[20:25:09.994][SegmentApi     ][Info   ] Usage statistic: appLaunched
[20:25:10.070][NamedPipeClient][Info   ] Sending Version()...
[20:25:10.103][NamedPipeClient][Info   ] Received response for Version
[20:25:10.110][SegmentApi     ][Info   ] Usage statistic: heartbeat
[20:25:00.306][BackendServer  ][Info   ] Started
[20:25:00.308][Moby           ][Info   ] Connecting...
[20:25:10.087][NamedPipeServer][Info   ] Version()
[20:25:10.095][NamedPipeServer][Info   ] Version done.
[20:25:10.379][Updater        ][Info   ] Checking for updates on channel Stable...
[20:25:10.383][Notifications  ][Info   ] Docker is starting...
[20:25:10.413][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[20:25:10.423][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[20:25:10.436][HyperVGuids    ][Info   ] Installing GUIDs...
[20:25:10.444][HyperVGuids    ][Info   ] GUIDs installed
[20:25:10.456][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[20:25:10.595][Updater        ][Info   ] Local build 9503 is as good as the remote 9503 on channel Stable
[20:25:12.117][Firewall       ][Info   ] Ports are opened
[20:25:12.123][HyperV         ][Info   ] Create
[20:25:12.142][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[20:25:15.501][HyperV         ][Info   ] Creating Switch: DockerNAT...
[20:25:17.160][HyperV         ][Info   ] Switch created.
[20:25:17.823][PowerShell     ][Info   ] Run script 'Import-Module Dism; Get-WindowsOptionalFeature -Online | where FeatureName -like "*Hyper-V*" | where State -ne Enabled'...
[20:25:20.868][HyperV         ][Info   ] Hyper-V is running
[20:25:20.876][HyperV         ][Info   ] Create
[20:25:20.881][PowerShell     ][Info   ] Run script with parameters: -Create True -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[20:25:21.057][HyperV         ][Info   ] Using existing Switch: DockerNAT
[20:25:21.172][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[20:25:21.264][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.


[20:25:21.272][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.


[20:29:51.892][ErrorReportWindow][Info   ] Open logs
```

### Steps to reproduce the behavior

  1. Install docker on Windows 10 x64
  2. Click through prompts, see error reporting dialogue when Docker tries to run.

### Note

I had previously installed (and removed) Docker Toolbox. Not sure if this is causing issues.

**Comment by JLospinoso** [comment]
Same problem with beta:

```
Version: 1.13.0-rc5-beta35 (9606)
Channel: Beta
Sha1: d603c07c049bd3ef899e3ac09ead2a5db339679d
Started on: 2017/01/08 20:37:16.820
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.576.amd64fre.rs1_release_inmarket.161208-2252
File: C:\Users\jalospinoso\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[20:37:16.950][GUI            ][Info   ] Starting...
[20:37:17.254][Tracking       ][Info   ] Crash report and usage statistics are enabled
[20:37:17.260][SegmentApi     ][Info   ] Usage statistic: appLaunched
[20:37:17.335][NamedPipeClient][Info   ] Sending Version()...
[20:37:17.360][NamedPipeClient][Info   ] Received response for Version
[20:37:17.360][SegmentApi     ][Info   ] Usage statistic: heartbeat
[20:37:10.254][BackendServer  ][Info   ] Started
[20:37:17.357][NamedPipeServer][Info   ] Version()
[20:37:17.357][NamedPipeServer][Info   ] Version done in 00:00:00.0004992.
[20:37:17.467][Updater        ][Info   ] Checking for updates on channel Beta...
[20:37:17.471][Notifications  ][Info   ] Docker is starting...
[20:37:17.486][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[20:37:17.489][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[20:37:17.497][PowerMode      ][Info   ] Stop
[20:37:17.501][HyperV         ][Info   ] Stop
[20:37:17.517][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[20:37:17.520][PowerShell     ][Info   ] Creating a Runspace Pool...
[20:37:17.692][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[20:37:17.735][Updater        ][Info   ] Local build 9606 is as good as the remote 9606 on channel Beta
[20:37:17.762][HyperV         ][Info   ] Script started at 20:37:17.757
[20:37:19.222][HyperV         ][Info   ] Module loaded at 20:37:19.221
[20:37:19.432][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[20:37:19.432][HyperV         ][Debug  ] [stop] took 00:00:01.9290423 to run
[20:37:19.433][OptimizeDisk   ][Info   ] Optimize
[20:37:19.434][PowerShell     ][Info   ] Run script...
[20:37:19.455][Moby           ][Info   ] Stop
[20:37:19.467][HyperVGuids    ][Info   ] Installing GUIDs...
[20:37:19.467][PowerMode      ][Info   ] Start
[20:37:19.469][HyperV         ][Info   ] Create
[20:37:19.469][HyperVGuids    ][Info   ] GUIDs installed
[20:37:19.469][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[20:37:19.471][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[20:37:19.497][HyperV         ][Info   ] Script started at 20:37:19.497
[20:37:19.504][HyperV         ][Info   ] Module loaded at 20:37:19.504
[20:37:19.815][HyperV         ][Info   ] Creating Switch: DockerNAT...
[20:37:20.915][HyperV         ][Info   ] Switch created.
[20:37:21.378][Firewall       ][Info   ] Ports are opened
[20:37:21.379][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

. Let's retry
[20:37:21.380][PowerShell     ][Info   ] Run script...
[20:37:24.001][HyperV         ][Info   ] Hyper-V is running
[20:37:24.001][PowerMode      ][Info   ] Stop
[20:37:24.001][HyperV         ][Info   ] Stop
[20:37:24.001][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[20:37:24.009][HyperV         ][Info   ] Script started at 20:37:24.009
[20:37:24.017][HyperV         ][Info   ] Module loaded at 20:37:24.017
[20:37:24.029][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[20:37:24.029][HyperV         ][Debug  ] [stop] took 00:00:00.0274979 to run
[20:37:24.029][OptimizeDisk   ][Info   ] Optimize
[20:37:24.029][PowerShell     ][Info   ] Run script...
[20:37:24.038][Moby           ][Info   ] Stop
[20:37:24.052][HyperV         ][Info   ] Destroy
[20:37:24.052][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[20:37:24.059][HyperV         ][Info   ] Script started at 20:37:24.059
[20:37:24.066][HyperV         ][Info   ] Module loaded at 20:37:24.066
[20:37:24.078][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[20:37:24.079][HyperV         ][Info   ] Destroying Switch DockerNAT...
[20:37:24.527][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[20:37:24.540][HyperV         ][Debug  ] [destroy] took 00:00:00.4874931 to run
[20:37:24.540][Firewall       ][Info   ] Closing ports...
[20:37:26.083][Firewall       ][Info   ] Ports are closed
[20:37:26.083][HyperVGuids    ][Info   ] Removing GUIDs...
[20:37:26.085][HyperVGuids    ][Info   ] GUIDs removed
[20:37:26.085][HyperV         ][Info   ] Create
[20:37:26.085][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[20:37:26.100][HyperV         ][Info   ] Script started at 20:37:26.099
[20:37:26.112][HyperV         ][Info   ] Module loaded at 20:37:26.112
[20:37:26.192][HyperV         ][Info   ] Creating Switch: DockerNAT...
[20:37:27.213][HyperV         ][Info   ] Switch created.
[20:37:27.333][PowerMode      ][Info   ] Stop
[20:37:27.333][HyperV         ][Info   ] Stop
[20:37:27.333][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[20:37:27.342][HyperV         ][Info   ] Script started at 20:37:27.342
[20:37:27.353][HyperV         ][Info   ] Module loaded at 20:37:27.353
[20:37:27.363][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[20:37:27.363][HyperV         ][Debug  ] [stop] took 00:00:00.0299900 to run
[20:37:27.363][OptimizeDisk   ][Info   ] Optimize
[20:37:27.363][PowerShell     ][Info   ] Run script...
[20:37:27.372][Moby           ][Info   ] Stop
[20:37:27.382][HyperV         ][Info   ] Destroy
[20:37:27.382][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[20:37:27.388][HyperV         ][Info   ] Script started at 20:37:27.388
[20:37:27.396][HyperV         ][Info   ] Module loaded at 20:37:27.396
[20:37:27.406][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[20:37:27.406][HyperV         ][Info   ] Destroying Switch DockerNAT...
[20:37:27.865][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[20:37:27.874][HyperV         ][Debug  ] [destroy] took 00:00:00.4919752 to run
[20:37:27.874][Firewall       ][Info   ] Closing ports...
[20:37:28.014][SegmentApi     ][Info   ] Usage statistic: actionMenuCheckForUpdate
[20:37:28.015][Updater        ][Info   ] Checking for updates on channel Beta...
[20:37:28.029][Updater        ][Info   ] Local build 9606 is as good as the remote 9606 on channel Beta
[20:37:28.029][Notifications  ][Info   ] Docker is up-to-date
[20:37:28.215][Firewall       ][Info   ] Ports are closed
[20:37:28.215][HyperVGuids    ][Info   ] Removing GUIDs...
[20:37:28.215][HyperVGuids    ][Info   ] GUIDs removed
[20:37:28.217][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[20:37:28.293][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.


[20:37:28.294][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.


[20:37:28.321][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[20:37:28.324][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\jalospinoso\AppData\Local\Temp\j4pa23rb.km3\pcap.tar)...
[20:37:28.324][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[20:37:28.326][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\jalospinoso\AppData\Local\Temp\j4pa23rb.km3\win_containers)...
[20:37:28.326][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\jalospinoso\AppData\Local\Temp\j4pa23rb.km3\mobyLogs.tar)...
[20:37:28.327][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\jalospinoso\AppData\Local\Temp\j4pa23rb.km3\mobyLogs.tar)
[20:37:28.325][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\jalospinoso\AppData\Local\Temp\j4pa23rb.km3\pcap.tar)
[20:37:28.342][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[20:37:28.326][NamedPipeServer][Info   ] GetDebugInfo()
[20:37:28.327][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\jalospinoso\AppData\Local\Temp\j4pa23rb.km3\win_containers)
[20:37:28.341][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[20:37:28.341][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0165001.
[20:37:28.364][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[20:37:28.384][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[20:37:28.383][HyperV         ][Warning] Unable to download logs: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual machine with name "MobyLinuxVM".
[20:37:28.383][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.0564975.
[20:37:34.671][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[20:37:34.671][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:06.3439521.
[20:37:38.377][ErrorReportWindow][Info   ] Open logs
```

**Comment by JLospinoso** [comment]
Diagnostic ID: 5AF29D2F-F801-4F62-BF57-1973F5D62A4D/2017-01-08_20-37-28

**Comment by rneugeba** [comment]
@JLospinoso thanks for your report. It looks like you already have another Hyper-V VM installed. I assume it is working, so Hyper-V is working in general on your system, right?

Note, it's not a a problem having another VM, actually quite good to verify that Hyper-V is working fine.

The error seems to be that the application fails to create the VM, which is odd...

I didn't see anything obvious in the diagnostics, except that there are a number of broken network adapters lingering. Could you try removing them? They are prefixed with `Broken Docker Adapter`. They should not matter, but you never know...Quit the Docker for Windows application, then try to remove/delete/disable the adapters via the `Network Connections` control panel.

Try then again to start the Docker for Windows app and see if that works.

If that still fails, could you quit the app, and, from an elevated powershell (Run as Administrator):
```
& 'C:\Program Files\Docker\Docker\resources\MobyLinux.ps1' -destroy
& 'C:\Program Files\Docker\Docker\resources\MobyLinux.ps1' -create
```
I'd be interested to see if that works, and if not, what errors it throws. If this does not throw an error, you should be able to run the app and see if that works...

Thanks

**Comment by JLospinoso** [comment]
@rneugeba Thanks for the prompt response! 

Disabling the "Broken Docker Adapter" did the trick. I can't delete it, though.

Any idea what might have caused the issue?

**Comment by rneugeba** [comment]
Thanks for getting back. We basically rename adapters we can't remove/delete to `Broken Docker Adapter`. We try reasonably hard to delete them but on some small number of system there seem to be cases where we can't remove them and we don't know why and we don't know how these systems get into the state...

I think there might be some inconsistencies between registry entries etc...

**Comment by JLospinoso** [comment]
Makes sense. What are you using to try to remove? WMI? Is the source available?

**Comment by rneugeba** [comment]
The source is mostly in `C:\Program
Files\Docker\Docker\resources\MobyLinux.ps1`

**Comment by liayn** [comment]
Since have such an adapter too now, I can confirm the relevant code is in the ps1 file and that is

```

    # Make sure there are no lingering net adapter
    $netAdapters = Get-NetAdapter | ? { $_.Name.StartsWith("vEthernet ($SwitchName)") }
    if (($netAdapters).Length -gt 1) {
        Write-Output "Disable and rename invalid NetAdapters"

        $now = (Get-Date -Format FileDateTimeUniversal)
        $index = 1
        $invalidNetAdapters =  $netAdapters | ? { $_.DeviceID -ne $vmNetAdapter.DeviceId }

        foreach ($netAdapter in $invalidNetAdapters) {
            $netAdapter `
                | Disable-NetAdapter -Confirm:$false -PassThru `
                | Rename-NetAdapter -NewName "Broken Docker Adapter ($now) ($index)" `
                | Out-Null

            $index++
        }
    }
```

I guess for me this happened right with/after the windws 1809 update.
