### ISSUE TITLE
docker crashed at first sight

### ISSUE THREAD

**Issue by nilesim** [docker/for-win#3768]
Docker crashed after installation. I simply downloaded docker installer for Windows from: https://hub.docker.com/editions/community/docker-ce-desktop-windows

Than, I clicked Docker for Windows Installer to run the installer. After installation, it required a restart and after restart I tried to open docker desktop, i gave me this error:

> Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
> at New-Switch, <No file>: line 121
> at <ScriptBlock>, <No file>: line 411
>    at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
>    at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
>    at Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 155
>    at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

 Diagnostics ID: 90125684-D4AC-46A8-B347-57F6FE53717C/20190418113029
  - Windows Version: 10
  - Docker for Windows Version: 18.09.2

**Comment by nilesim** [comment]
Running the MOFCOMP command and a reboot fixed this problem for me.

1 . Running this command: (Command Prompt as administrator) MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof

2 . Then restart

(https://community.spiceworks.com/how_to/122307-fix-error-managing-hyper-v-server-2012-r2-from-windows-10)
