### ISSUE TITLE
ailed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

### ISSUE THREAD

**Issue by AN368844** [docker/for-win#3778]
Getting the below error:

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID 49DF28B3-DF6A-47AE-B22D-12D9D7EE81B6)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID 49DF28B3-DF6A-47AE-B22D-12D9D7EE81B6).
at Start-MobyLinuxVM, <No file>: line 296
at <ScriptBlock>, <No file>: line 412
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

Find the id:

Diagnostics Bundle: C:\Users\S-WIPR~2\AppData\Local\Temp\9A4A08B3-7DB1-4003-90A9-3AFAA84AB31B\20190419134303.zip
Diagnostics ID:     9A4A08B3-7DB1-4003-90A9-3AFAA84AB31B/20190419134303 (uploaded)

**Comment by AN368844** [comment]
[Docker logs.txt](https://github.com/docker/for-win/files/3098304/Docker.logs.txt)

**Comment by AN368844** [comment]
Please help me in trouble shooting this issue.
