### ISSUE TITLE
Docker startup failure

### ISSUE THREAD

**Issue by port43** [docker/for-win#3802]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  B2A2A768-5CA1-4B5E-89AE-839E2A9011EB/20190423155550

### Expected behavior 
Docker starts normally and setting the local shared drive of "C" stays checked

### Actual behavior
An error occurred:

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer '<my laptop name>' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-1

### Information

  - Windows Version:  Microsoft Windows 10 Enterprise 64-bit  (10.0.17763)
  - Docker for Windows Version:  2.0.0.3 (31259) stable build: 8858db3 and whatever the previous version was

### Steps to reproduce the behavior

  1. Start Docker as Administrator
  2. Admire popup window that says, "Docker Desktop is starting"
  3. Cross fingers
  4. See popup error as listed above in "Actual behavior"
  5. Scratch head repeatedly
  6. Close error
  7. Right click on red docker icon and select "Restart"
  8. Admire popup window that says, "Docker Desktop is restarting"
  9. Attempt to "Apply" "Shared Drives" with checkbox next to "C" active
10. Input correct credentials into credential dialog
11. Watch checkbox next to "C" drive go inactive
12. Click on "Advanced" and note that all inputs are inaccessible
13. Click on any heading under "Settings" in the Docker window
14. Get an "Apply changes" popup that says, "You have unapplied changes, would you like to apply them?"
15. Select "Apply" and get a new "Docker failed to initialize error" with the text:
Cannot validate argument on parameter 'Path'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Docker.Core.PowerShell.Output(String script, Boolean verbose) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\PowerShell.cs:line 110
   at Docker.Backend.ContainerEngine.Linux.TryResizeMobyVhdx(String physicalPath, Int64 newSize) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 488
   at Docker.Backend.BackendServer.<Run>b__6_14(Object[] args) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\BackendServer.cs:line 56
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180

NOTE:  ALL OF THIS IS WHILE USING LINUX CONTAINERS.  SWITCHING TO WINDOWS WILL ALLOW DOCKER TO START BUT ATTEMPTING TO SWITCH BACK TO LINUX CAUSES THE INITIAL FAILURE AGAIN

**Comment by MythreyaK** [comment]
Could you add the output of `bcdedit`, `docker version` and a screenshot of `Turn Windows Features on or off`

**Comment by port43** [comment]
My sincere apologies but this can be closed.  I have had to move on without using Docker because my development was falling behind.
