### ISSUE TITLE
Docker for Windows does not start (MobyLinuxVM out of Disk Space)

### ISSUE THREAD

**Issue by haraldreingruber** [docker/for-win#3830]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 7C6177A3-25BB-456B-9735-D54893911623/20190430093625

### Expected behavior
Docker for Windows starts as usual.

### Actual behavior
Docker for Windows does not start/starts with an error:

```text
2019-04-29T14:37:40Z docker + jq -e '."storage-driver"' /run/config/docker/daemon.json
2019-04-29T14:37:40Z docker + wait_docker_api
2019-04-29T14:37:40Z docker + :
2019-04-29T14:37:40Z docker + sleep 1
2019-04-29T14:37:40Z docker 2019/04/29 14:37:40 Listening on AF_HVSOCK service id 0000f3a3-FACB-11E6-BD58-64006A7986D3
2019-04-29T14:37:40Z docker 2019/04/29 14:37:40 Failed to listen on AF_VSOCK Kernel is too old and still uses the AF_HVSOCK patches
2019-04-29T14:37:40Z docker + '[' -d /var/lib/docker/aufs ]
2019-04-29T14:37:40Z docker + '[' -f /run/config/docker/redirect-logs ]
2019-04-29T14:37:40Z docker + /usr/local/bin/dockerd -H unix:///var/run/docker.sock --config-file /run/config/docker/daemon.json '--swarm-default-advertise-addr=eth0' --userland-proxy-path /usr/bin/vpnkit-expose-port
2019-04-29T14:37:41Z docker time="2019-04-29T14:37:
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

When running `docker ps` I get the following output:
```text
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
``` 

### Information

  - Windows Version: Windows Server 2016 (Version 1607)
  - Docker for Windows Version: Docker version 18.09.2, build 6247962 (Docker Desktop 2.0.0.3 stable)

### Steps to reproduce the behavior
Unfortunately, I can not offer a reproducible test case. It would be great to help me to get more insights from the logs and the diagnostic report.

**Comment by haraldreingruber** [comment]
It turned out that one of the container used up all the disk space from the quota assinged to the VM. Would be really cool if this root cause would be identifyable from the error report as well. Do you wanna keep this issue open for a log improvement task?
