### ISSUE TITLE
Docker stopped running after update 

### ISSUE THREAD

**Issue by msuqi** [docker/for-win#3844]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E572DB39-7671-4D7C-9AE9-CA1E0CDEDD44/20190502083726
[20190502083726.zip](https://github.com/docker/for-win/files/3138881/20190502083726.zip)

### Expected behavior
Docker to start and be running in the system tray
### Actual behavior
System tray Icon red and crashes even after I get prompted to use defaults.
### Information

  - Windows Version:
      - Windows 10 Professional 1809
  - Docker for Windows Version: 
      - Version 2.0.0.3 (31259)
      - Channel: stable
      - Build: 8858db3

### Steps to reproduce the behavior

  1. Double Click on Docker Desktop icon

### Steps tried to fix the problem
   1. Removed docker and reinstalled
       - Uninstalled from Programs and features
       - Ran the attached scripts in power shell with elevated permissions           
          [uninstallDocker.txt](https://github.com/docker/for-win/files/3138898/uninstallDocker.txt)

**Comment by msuqi** [comment]
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by msuqi** [comment]
Uninstalled trend micro Apex one and Docker starts.  When I look in Hyper-V Manager I do see Docker Nat under Virtual Switch Manager.  I look in network settings network adapters I do See Broken Docker Adapter.  Startup of Docker takes about 10 minutes to start. 

System Configuration:
Processor  i7-7600U @2.8GHz
Memory    16GB Ram
Storage      Samsung MZVLB512HAJQ 

Is there something else I should be looking at?

**Comment by msuqi** [comment]
Excluded all .exe files solved the problem
