### ISSUE TITLE
docker startup issue in windows

### ISSUE THREAD

**Issue by XeL077** [docker/for-win#3857]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C8AB2CFD-237C-473B-ADB2-1C236B9A893D/20190504203332

A task was canceled.
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.WPF.BackendClient.Version() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 46
   at Docker.WPF.BackendClient.CheckVersion() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 199
   at Docker.WPF.BackendClient.CheckService(String action) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 314
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 167
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

  - Windows Version: windows 10 pro
  - Docker for Windows Version: Version 2.0.0.3 (31259)

### Steps to reproduce the behavior
1. Install Docker.
2. I install Android Studio, and get fail Intel HAXM.
Android ADV - Emulator: ERROR: x86 emulation currently requires hardware acceleration.
3. Do it: https://www.youtube.com/watch?v=rg0TMy1G67U
and now I have error docker;
4. Reset PC.

**Comment by XeL077** [comment]
Ok, forget.
