### ISSUE TITLE
docker-compose and env_file in cp1251

### ISSUE THREAD

**Issue by scmrus** [docker/for-win#387]
### Information
Version: 1.13.0-rc6-beta36 (9696)
Channel: Beta
Sha1: 64a715b54327a0ec8f28076d1a343f4c811856fb
Started on: 2017/01/13 19:29:14.277
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1511
Build: 10586
BuildLabName: 10586.672.amd64fre.th2_release_sec.161024-1825

### Steps to reproduce the behavior

1. docker-compose.yml
```
version: '2'
services:
  test:
    build: .
    env_file:
      - .env
```

2. .env (cp1251)
```
# вы там держитесь
NOMONEY=1
```

3. docker-compose up -d
```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose\cli\main.py", line 64, in main
  File "compose\cli\main.py", line 113, in perform_command
  File "compose\cli\command.py", line 36, in project_from_options
  File "compose\cli\command.py", line 103, in get_project
  File "compose\config\config.py", line 331, in load
  File "compose\config\config.py", line 432, in load_services
  File "compose\config\config.py", line 411, in build_services
  File "compose\config\config.py", line 404, in build_service
  File "compose\config\config.py", line 703, in finalize_service
  File "compose\config\config.py", line 568, in resolve_environment
  File "compose\config\environment.py", line 34, in env_vars_from_file
  File "codecs.py", line 699, in next
  File "codecs.py", line 630, in next
  File "codecs.py", line 545, in readline
  File "codecs.py", line 492, in read
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc2 in position 0: invalid continuation byte
docker-compose returned -1
{ api } master » docker-compose -v                                                                                                                             /c/docker/... 127
docker-compose version 1.10.0-rc2, build 5b471e8c
```

**Comment by scmrus** [comment]
env_file can be converted to UTF-8 to fix it.

**Comment by justincormack** [comment]
Yaml only supports UTF-8 and UTF-16 so this is all you can use.

**Comment by scmrus** [comment]
yep, stupid mistake, but I hope this information can save some time for smb

**Comment by rneugeba** [comment]
I'm closing this issue as it seems like a compose issue not an issue with the Docker for Windows application. If this is still an issue, please open one on https://github.com/docker/compose
thanks for reporting
