### ISSUE TITLE
No activity detected on VM, aborting

### ISSUE THREAD

**Issue by zalym** [docker/for-win#3875]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics 
  - Diagnostics ID: C3D79879-4458-4147-AF58-FB3751C0B1D5/20190507183711

### Expected behavior
Docker to startup
### Actual behavior
Docker crashes with following error
No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
### Information

  - Windows Version:  
  - Docker for Windows Version:  Docker version 18.09.1, build 4c52b90

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by joevans-cchs** [comment]
My whole team is receiving this error when trying to run Linux containers on Docker Desktop on a win10 VM on a macbook pro.

The error started when we recently switched from Macbook Pro 2015's to Macbook Pro 2019's.  We used the mac migration assistant which brought over all settings and VMs.  I still have the Macbook Pro 2015 to verify it is still working.

This is the same across both old and new macbooks:
- Both are running macOS Mojave 10.14.5
- Running VMware Fusion 11.1.0
- Running Windows 10 VM 
   - Hyper-V is enabled on VM
   - Running Docker Desktop v2.0.0.3 (31259) Channel: stable Build:8858db3

 I see that MobyLinuxVM says it is running in the Hyper-V manager.  It eventually errors out with this msg:

No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass28_0.<SwitchDaemon>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 305
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by mikeparker** [comment]
@joevans-cchs Unfortunately you're running a nested virtualization setup, which Docker does not officially support, see https://docs.docker.com/docker-for-windows/troubleshoot/#running-docker-desktop-for-windows-in-nested-virtualization-scenarios for details.

@zalym I would be interested to know if you are also running your OS in a VM?

**Comment by zalym** [comment]
Yes, its a virtualized desktop
