### ISSUE TITLE
An error occurred when selecting "Switch to Windows containers..."

### ISSUE THREAD

**Issue by braveness23** [docker/for-win#388]
### Expected behavior

docker switches to windows containers

### Actual behavior

An error occured

Docker daemon failed with message:
time="2017-01-13T17:20:40-05:00" level=warning msg="Running experimental build" 
time="2017-01-13T17:20:40.221825700-05:00" level=debug msg="Listener created for HTTP on npipe (//./pipe/docker_engine_windows)" 
time="2017-01-13T17:20:40.226826100-05:00" level=info msg="Windows default isolation mode: hyperv" 
time="2017-01-13T17:20:40.226826100-05:00" level=debug msg="Using default logging driver json-file" 
time="2017-01-13T17:20:40.227825800-05:00" level=debug msg="WindowsGraphDriver InitFilter at C:\\ProgramData\\Docker\\windowsfilter" 
time="2017-01-13T17:20:40.227825800-05:00" level=debug msg="Using graph driver windowsfilter" 
time="2017-01-13T17:20:40.228326000-05:00" level=debug msg="Max Concurrent Downloads: 3" 
time="2017-01-13T17:20:40.228326000-05:00" level=debug msg="Max Concurrent Uploads: 5" 
time="2017-01-13T17:20:40.233825800-05:00" level=info msg="Graph migration to content-addressability took 0.00 seconds" 
time="2017-01-13T17:20:40.233825800-05:00" level=info msg="Loading containers: start." 
time="2017-01-13T17:20:40.234326700-05:00" level=debug msg="Option Experimental: true" 
time="2017-01-13T17:20:40.234326700-05:00" level=debug msg="Option DefaultDriver: nat" 
time="2017-01-13T17:20:40.234326700-05:00" level=debug msg="Option DefaultNetwork: nat" 
time="2017-01-13T17:20:40.289826600-05:00" level=debug msg="Network Response : [ { \"CurrentEndpointCount\" : 0, \"ID\" : \"a8e64b1a-5928-4849-b45e-12ae4c1bb257\", \"MacPools\" : [ { \"EndMacAddress\" : \"00-15-5D-F6-AF-FF\", \"StartMacAddress\" : \"00-15-5D-F6-A0-00\" } ], \"MaxConcurrentEndpoints\" : 0, \"Name\" : \"External\", \"Policies\" : [  ], \"TotalEndpoints\" : 0, \"Type\" : \"Transparent\", \"Version\" : 4294967297 } ]" 
time="2017-01-13T17:20:40.290326200-05:00" level=debug msg="Launching DNS server for network%!(EXTRA string=none)" 
time="2017-01-13T17:20:40.304827000-05:00" level=debug msg="releasing IPv4 pools from network External (c121ce664ae069e67ddfd42cf9c67efac433eae9f65cd907b64a57cddf58a20c)" 
time="2017-01-13T17:20:40.304827000-05:00" level=debug msg="ReleaseAddress(0.0.0.0/0, 0.0.0.0)" 
time="2017-01-13T17:20:40.304827000-05:00" level=debug msg="ReleasePool(0.0.0.0/0)" 
time="2017-01-13T17:20:40.325325600-05:00" level=debug msg="Allocating IPv4 pools for network External (5554ae4cccf4bc2c8b84ba7d18433e935037b0b656d2df7ef01010140fcab4b6)" 
time="2017-01-13T17:20:40.325826400-05:00" level=debug msg="RequestPool(LocalDefault, , , map[], false)" 
time="2017-01-13T17:20:40.325826400-05:00" level=debug msg="RequestAddress(0.0.0.0/0, <nil>, map[RequestAddressType:com.docker.network.gateway])" 
time="2017-01-13T17:20:40.325826400-05:00" level=debug msg="Launching DNS server for network%!(EXTRA string=External)" 
time="2017-01-13T17:20:40.331827000-05:00" level=debug msg="Network Response : { \"CurrentEndpointCount\" : 0, \"ID\" : \"a8e64b1a-5928-4849-b45e-12ae4c1bb257\", \"MacPools\" : [ { \"EndMacAddress\" : \"00-15-5D-F6-AF-FF\", \"StartMacAddress\" : \"00-15-5D-F6-A0-00\" } ], \"MaxConcurrentEndpoints\" : 0, \"Name\" : \"External\", \"Policies\" : [  ], \"TotalEndpoints\" : 0, \"Type\" : \"Transparent\", \"Version\" : 4294967297 }" 
time="2017-01-13T17:20:40.351825600-05:00" level=debug msg="Allocating IPv4 pools for network nat (0260f67f4262a6bfb1366ce50998bbcd84ef82833e38c5f0d796d45198d00621)" 
time="2017-01-13T17:20:40.351825600-05:00" level=debug msg="RequestPool(LocalDefault, , , map[], false)" 
time="2017-01-13T17:20:40.351825600-05:00" level=debug msg="RequestAddress(0.0.0.0/0, <nil>, map[RequestAddressType:com.docker.network.gateway])" 
time="2017-01-13T17:20:40.351825600-05:00" level=debug msg="HNSNetwork Request ={\"Name\":\"nat\",\"Type\":\"nat\",\"Subnets\":[{\"AddressPrefix\":\"0.0.0.0/0\",\"GatewayAddress\":\"0.0.0.0\"}]} Address Space=[{0.0.0.0/0 0.0.0.0 []}]" 
time="2017-01-13T17:20:40.378824500-05:00" level=debug msg="releasing IPv4 pools from network nat (0260f67f4262a6bfb1366ce50998bbcd84ef82833e38c5f0d796d45198d00621)" 
time="2017-01-13T17:20:40.378824500-05:00" level=debug msg="ReleaseAddress(0.0.0.0/0, 0.0.0.0)" 
time="2017-01-13T17:20:40.378824500-05:00" level=debug msg="ReleasePool(0.0.0.0/0)" 
time="2017-01-13T17:20:40.378824500-05:00" level=debug msg="start clean shutdown of all containers with a 15 seconds timeout..." 
Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : The parameter is incorrect. 

   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.

21422329-D27C-4E5D-ACA8-FC37FF2B4DA4/2017-01-13_17-28-28

  - host distribution and version (Windows version, build number, etc)

C:\Users\xxxx>docker version
Client:
 Version:      1.13.0-rc6
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   2f2d055
 Built:        Wed Jan 11 21:47:55 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc6
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   2f2d055
 Built:        Wed Jan 11 21:47:55 2017
 OS/Arch:      linux/amd64
 Experimental: true

### Steps to reproduce the behavior

  1. Select 'Switch to Windows containers...'
  2. Watch it burn

**Comment by rneugeba** [comment]
Thanks for the report. Could you try:
https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/Debug-ContainerHost

This script looks for common issues with Windows containers. And if it suggest there is a networking issue could you also try:
https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/CleanupContainerHostNetworking

thanks

**Comment by braveness23** [comment]
.\Debug-ContainerHost.ps1
Checking for common problems
Describing Windows Version and Prerequisites
 [+] Is Windows 10 Anniversary Update or Windows Server 2016 506ms
 [+] Has KB3192366, KB3194496, or later installed if running Windows build 14393 118ms
 [+] Is not a build with blocking issues 20ms
 [+] Has 'Containers' feature installed 5.65s
Describing Docker is installed
 [+] A Docker service is installed - 'Docker' or 'com.Docker.Service'  54ms
 [+] Service is running 16ms
 [+] Docker.exe is in path 4.15s
 [+] Docker is registered in the EventLog service 42ms
Describing User has permissions to use Docker daemon
 [+] docker.exe should not return access denied 47ms
Describing Windows container settings are correct
 [+] Do not have DisableVSmbOplock set to 1 27ms
 [+] Do not have zz values set 23ms
Describing The right container base images are installed
 [-] At least one of 'microsoft/windowsservercore' or 'microsoft/nanoserver' should be installed 165ms
   ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Property'. The argument is null or empty. Provide an argument that is not null or empty
, and then try the command again.
   at <ScriptBlock>, F:\Users\Xxxx\Desktop\Docker for Win\Debug-ContainerHost.ps1: line 109
Describing Container network is created
 [+] At least one local container network is available 3.09s
 [-] At least one NAT, Transparent, or L2Bridge Network exists 52ms
   Expected {0} to be greater than {0}
   200:       $totalnets | Should BeGreaterThan 0
   at <ScriptBlock>, F:\Users\Xxxx\Desktop\Docker for Win\Debug-ContainerHost.ps1: line 200
 [-] NAT Network's vSwitch is internal 29ms
   Expected: {Internal}
   But was:  {}
   205:       $switchType | Should Be "Internal"      
   at <ScriptBlock>, F:\Users\Xxxx\Desktop\Docker for Win\Debug-ContainerHost.ps1: line 205
 [-] Specified Network Gateway IP for NAT network is assigned to Host vNIC 27ms
   Expected: value to not be empty
   209:       $natGatewayIP | Should Not BeNullOrEmpty
   at <ScriptBlock>, F:\Users\Xxxx\Desktop\Docker for Win\Debug-ContainerHost.ps1: line 209
 [-] NAT Network's internal prefix does not overlap with external IP' 42ms
   Expected {0} to be greater than {0}
   236:         $hostips.Count | Should BeGreaterThan 0
   at <ScriptBlock>, F:\Users\Xxxx\Desktop\Docker for Win\Debug-ContainerHost.ps1: line 236
Showing output from: docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.0-rc6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.2-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: T3UB:IHNA:5ZZN:X3UD:Z3Y2:FQGH:FHYU:FF7S:R6BR:4DPZ:73LB:WDCY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 21
 System Time: 2017-01-14T21:26:19.460718Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

Showing output from: docker version
Client:
 Version:      1.13.0-rc6
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   2f2d055
 Built:        Wed Jan 11 21:47:55 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc6
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   2f2d055
 Built:        Wed Jan 11 21:47:55 2017
 OS/Arch:      linux/amd64
 Experimental: true

Showing output from: docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
5be0330e3ba3        bridge              bridge              local
58574d51fc6f        host                host                local
f43f8c53ac86        none                null                local

Warnings & errors from the last 24 hours
Logs saved to F:\Users\Xxxx\Desktop\Docker for Win\logs_20170114-162627.csv

PS F:\Users\Xxxx\Desktop\Docker for Win> 


Note; the saved log file 'logs_20170114-162627.csv' was a zero byte file.

Hope this helps!

**Comment by braveness23** [comment]
Running CleanupContainerHostNetworking.ps1 resulted with 'Complete!!!' but I was still unable to switch to Windows containers.  Received same error

**Comment by simonferquel** [comment]
@braveness23 Can you try with -Cleanup and -ForceDeleteAllSwitches ? You'll have to reboot after that.

**Comment by dgageot** [comment]
@braveness23 any chance you could try these?

**Comment by rneugeba** [comment]
Closing due to inactivity. Please re-open if the issue persists with the latest Beta and you have tried the above suggestion
Thanks

**Comment by braveness23** [comment]
Sorry about the long delay.  Life happened.  I have been keeping up with Beta upgrades so I am current.  Here is the output

PS F:\Users\Xxx\Desktop\Docker for Win> .\CleanupContainerHostNetworking.ps1 -Cleanup -ForceDeleteAllSwitches
docker : Error response from daemon: bridge is a pre-defined network and 
cannot be removed
At F:\Users\Xxx\Desktop\Docker for Win\CleanupContainerHostNetworking.ps1:145 
char:9
+         docker network rm $network
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ...nnot be removed 
   :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
docker : Error response from daemon: host is a pre-defined network and cannot 
be removed
At F:\Users\Xxx\Desktop\Docker for Win\CleanupContainerHostNetworking.ps1:145 
char:9
+         docker network rm $network
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ...nnot be removed 
   :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
docker : Error response from daemon: none is a pre-defined network and cannot 
be removed
At F:\Users\Xxx\Desktop\Docker for Win\CleanupContainerHostNetworking.ps1:145 
char:9
+         docker network rm $network
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ...nnot be removed 
   :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
Remove-NetNat : The requested operation is not supported.
At F:\Users\Xxx\Desktop\Docker for Win\CleanupContainerHostNetworking.ps1:192 
char:22
+         Get-NetNat | Remove-NetNat -Confirm:$false
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (MSFT_NetNat (In...d0ec93f6f;0 
   ...):root/StandardCimv2/MSFT_NetNat) [Remove-NetNat], CimException
    + FullyQualifiedErrorId : Windows System Error 50,Remove-NetNat
 
PLEASE RESTART THE SYSTEM TO COMPLETE CLEANUP
Complete!!!
