### ISSUE TITLE
Docker hangs after hours of working perfectly

### ISSUE THREAD

**Issue by nphmuller** [docker/for-win#3892]
- [ X ] I have tried with the latest version of my channel (Stable __and__ Edge)
  - [ X ] I have uploaded Diagnostics
  - Diagnostics ID: `60B42B01-C664-4F95-B310-C5802E3DC567/20190510155652`

### Detected behavior
After a while Docker CLI commands start to either timeout (connect connect to pipe) or complete after minutes.

When checking the Task Manager the CPU percentage seems to be high constantly (~35%. Normally it's < 5%) for ``Vmmem``. And Disk IO is very high (100% -> 120MB/s) for `System`.
I've tested this on the latest Stable (`2.0.0.3`) and Edge (`2.0.4.0` + `2.0.4.1`). I've reset Docker for Win to its default settings after switching to Edge.

I can only recover by using the `Restart Docker Desktop` options (only in Edge, in Stable I can't open the Docker for Win settings when the hang happens). Or by manually restarting the VM.
`Restart Docker Desktop` seems to delete and recreate the VM. The hard disk is not deleted.

Sadly I can't find a repro that works. But on my system this happens basically every day, after running Docker for hours. 

I hope the diagnostics contain enough information. Else I'm happy to try things out and provide other details.

### Information
  - Windows Version: 10 (1903, build 18362.86)
  - Docker for Windows Version: 2.0.4.1

**Comment by MythreyaK** [comment]
What anti-virus/security software are you using, if any?

**Comment by nphmuller** [comment]
Just the build in Windows Defender. I can try to disable real time scanning the next time it happens, but I don't see any additional cpu usage of Defender when the issue occurs.

**Comment by MythreyaK** [comment]
Could you check under `Defender > Virus & Threat Protection > Ransomware Protection > Allow an app through Controlled folder` if the following are present?

![image](https://user-images.githubusercontent.com/26112391/57624310-4d698b80-75af-11e9-8583-8893a63ef150.png)

Also, ensure you are using powershell/cmd admin privileges to call docker, just in case you forgot (I sure did!)

**Comment by nphmuller** [comment]
I don't have Ransomware Protection enabled, so those settings shouldn't matter.

And can you be a bit more specific what you mean with admin privileges? I've been using Docker Desktop for Windows now for years (in Linux mode), but never had to click an UAC prompt during normal usage (`docker run` `docker exec`, `docker pull`, etc). So I'm not sure what you mean.

**Comment by nphmuller** [comment]
Also, it seems the issue occurs more often if I import big chunks of data. For example, if I import a big SQL database (dacpac) file, the issue occurs about 15~20% of the time.

**Comment by MythreyaK** [comment]
> And can you be a bit more specific what you mean with admin privileges? 

I meant start powershell or cmd as an admin. But since you mention that the issue appears later, while docker was working fine till then, this shouldn't be the cause of the issue. 
I had a similar issue, with docker being unresponsive; so was wondering if the fixes I tried could help you. I'll let you know if I dig up something!

**Comment by mikeparker** [comment]
Are you running any containers? If so which images are they using?

**Comment by nphmuller** [comment]
I think the problem was caused by high memory usage. At first I didn't suspect this, because Task Manager showed a memory usage between 80-85% (or at least under 90), but I guess something under the hood still started swapping.

Once I've changed Docker desktop to allocate 3GB instead of 4GB the problem went away.

Will reopen the issue if this didn't solve it.

@mikeparker Thanks for responding! Sorry for your wasted time!

**Comment by mikeparker** [comment]
I've chatted through this issue with some others here. We think the issue is probably the memory usage inside the VM rather than on the host. If thats the case, we suspect the issue probably won't be solved long term by reducing the memory of the VM, but it's great thats working for you at the moment. 

To check if its the VM swap or the Host swap, you can examine the host swap usage by following this:
https://www.m-files.com/user-guide/latest/eng/inspecting_page_file_usage_in_performance_monitor.html

The way to check the internals is to run:
`docker run -it --privileged --pid=host justincormack/nsenter1`
Then once inside:
`free` shows the memory usage including swap file
`top` shows the processes 

Unfortunately once your machine is bust, the internal commands may stop working, but give it a go if you see this slowdown again, and even maybe after a few hours (i.e. before it slows to a crawl). We'd be interested in the results.

Out of curiosity, do you have a spinning hard drive or an SSD? A fragmented swap file or repeated swap file usage would be more crippling on a spinning drive.

**Comment by nphmuller** [comment]
Ok, I'll reopen the issue and try to check the internals via the steps you mentioned.

Once the swappage occurs the VM becomes _very_ slow, but commands will most of the time still run (couple of minutes before any result is written to the output, occasionally timing out).

I'll let you know when I know more.  Will revert the memory setting back to 4GB and wait until the issue reoccurs.

> Out of curiosity, do you have a spinning hard drive or an SSD? A fragmented swap file or repeated swap file usage would be more crippling on a spinning drive.

I have an SSD. But the swap file usage is still pretty crippling.

**Comment by HenriKoelewijn** [comment]
I am seeing the same results here. Windows 10, docker 2.0.0.3.
Host memory swappage is not the issue (0%)
Moby has 8Gb of memory, I am running about 60 containers. Is that too much? I remember having these issues before and moving from 4Gb to 8Gb solved the issue then.  

After a while, I get the following error dialog:


> No activity detected on VM, aborting
>    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 268
>    at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 189
>    at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
>    at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180
> 
Looks like the VM has swapping issues indeed. HyperV says memory demand is 18G. 
That will probably be the cause.

**Comment by mikeparker** [comment]
It's hard to say whether 60 containers is too much for 8G memory, it really depends what exactly the containers are doing. If they are tiny stateless services maybe thats fine, if they are running large databases then maybe not.

It would really help us if you could screenshot the output of the internals after doing `top`, both CPU and memory screens so we can see exactly what the state of the system resources are.

**Comment by HenriKoelewijn** [comment]
Small update: after giving Moby 20G, the memory demand shoots up to 30G. Yesterday, the same amount of containers were fine with 8Gb.

**Comment by HenriKoelewijn** [comment]
the docker engine does not respond, so it's difficult to get anything from inside the VM/container

**Comment by HenriKoelewijn** [comment]
The thing is, the containers were fine yesterday. Running happily with 8Gb of memory. Today it started to show these issues.

**Comment by HenriKoelewijn** [comment]
Latest update: It looks like one of the containers was misbehaving. This caused it to eat up a lot of memory suddenly. So the only thing that's left for my case is that the fact that docker becomes unavailable when we are encountering memory issues on the virtual machine.

**Comment by mikeparker** [comment]
I agree it'd be nice if we could ringfence the resources required to keep the lights on and protect ourselves against containers that try to grab too many resources.

**Comment by MythreyaK** [comment]
That can be done with the `--memory="xMB"` command line switch. More info [here].(https://docs.docker.com/config/containers/resource_constraints/)

**Comment by uc18** [comment]
Hello! I encountered a similar problem, is your workstation in a domain? Try to intercept the processes of the docker through procmon and after that publish here
[https://docs.microsoft.com/en-us/sysinternals/downloads/procmon]() - link
