### ISSUE TITLE
Unable to Share C (Windows 10 Enterprise)

### ISSUE THREAD

**Issue by gimlichael** [docker/for-win#3908]
- [X ] I have tried with the latest version of my channel (Stable or **Edge**)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: EAB8C0B4-EB77-48A1-BDB0-028F7DB673FD/20190514134637

### Expected behavior

Share drive C so that I can work with Docker images on Linux

### Actual behavior

Unable to share drive C

### Information
I have tried almost everything that i was able to Google .. the thing that looks must plausible is this article: https://github.com/docker/for-win/issues/355

Here is my log information: 

[16:01:16.580][SambaShare     ][Info   ] Mount C
[16:01:16.820][Cmd            ][Info   ] This shared resource does not exist.
[16:01:16.820][Cmd            ][Info   ] More help is available by typing NET HELPMSG 2310.
[16:01:16.825][SambaShare     ][Info   ] "C" is not shared
[16:01:16.825][SambaShare     ][Info   ] Creating share "C:" as "C" with Full Control to "AD-USER"
[16:01:17.018][Cmd            ][Info   ] C was shared successfully.
[16:01:17.180][Cmd            ][Info   ] Share name        C
[16:01:17.180][Cmd            ][Info   ] Path              C:\
[16:01:17.180][Cmd            ][Info   ] Remark            
[16:01:17.180][Cmd            ][Info   ] Maximum users     No limit
[16:01:17.181][Cmd            ][Info   ] Users             
[16:01:17.181][Cmd            ][Info   ] Caching           Caching disabled
[16:01:17.182][Cmd            ][Info   ] Permission        AD-USER, FULL
[16:01:17.182][Cmd            ][Info   ] The command completed successfully.
[16:01:17.188][SambaShare     ][Info   ] "C" is shared
[16:01:17.276][SambaShare     ][Info   ] Username: AD-USER
[16:01:17.276][SambaShare     ][Info   ] Host IP: 10.0.75.1
[16:01:17.276][SambaShare     ][Info   ] Cifs options: noperm,iocharset=utf8,dir_mode=0777,nobrl,mfsymlinks,vers=3.02,domain=DE-PROD,sec=ntlmsspi
[16:01:18.335][SambaShare     ][Error  ] Unable to mount C drive: unexpected error: System.Exception: dial tcp 10.0.75.1:445: i/o timeout
   at Docker.Backend.LifecycleClient.Mount(MountRequest req)
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential cred, UserNameAndDomain info, String options, String ip)
[16:01:18.335][SambaShare     ][Info   ] Removing share "C"
[16:01:18.497][NamedPipeClient][Info   ] Received response for filesharing/mount
[16:01:18.496][NamedPipeServer][Info   ] filesharing/mount done in 00:00:03.8245769.
[16:01:18.512][TrackingSettings][Info   ] Crash report and usage statistics are enabled
[16:01:18.525][NamedPipeClient][Info   ] Sending app/version()...
[16:01:18.527][NamedPipeClient][Info   ] Received response for app/version
[16:01:18.527][NamedPipeClient][Info   ] Sending disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)...
[16:01:18.526][NamedPipeServer][Info   ] app/version()
[16:01:18.526][NamedPipeServer][Info   ] app/version done in 00:00:00.
[16:01:18.528][NamedPipeServer][Info   ] disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)
[16:01:18.528][PowerShell     ][Info   ] Run script...
[16:01:18.671][NamedPipeClient][Info   ] Received response for disk/get-size
[16:01:18.675][NamedPipeClient][Info   ] Sending app/version()...
[16:01:18.676][NamedPipeClient][Info   ] Received response for app/version
[16:01:18.677][NamedPipeClient][Info   ] Sending disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)...
[16:01:18.671][NamedPipeServer][Info   ] disk/get-size done in 00:00:00.1426019.
[16:01:18.676][NamedPipeServer][Info   ] app/version()
[16:01:18.676][NamedPipeServer][Info   ] app/version done in 00:00:00.
[16:01:18.677][NamedPipeServer][Info   ] disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)
[16:01:18.678][PowerShell     ][Info   ] Run script...
[16:01:18.830][NamedPipeClient][Info   ] Received response for disk/get-size
[16:01:18.830][NamedPipeServer][Info   ] disk/get-size done in 00:00:00.1522455.

**Comment by jorrit** [comment]
Reset to factory defaults worked here.

**Comment by jorrit** [comment]
I also had to disconnect from Cisco AnyConnect.

**Comment by gimlichael** [comment]
Reset to factory default did not work and no VPN is installed on the workstation.

However, and this is weird, after several hours of trial-n-error, I finally changed the Subnet Mask from 255.255.255.240 to 255.255.255.0 (which should have no effect).

Then it worked.

I switched the Subnet back, and it still works.

I admit, it makes no sense .. but it might be related to an internal state only being triggered by the network change .. but that is just a theory.

Docker Desktop edge, 2.0.4.1 (34207)

**Comment by mikeparker** [comment]
Looks like there was an IP address clash or a firewall issue and changing the subnet mask changed your IP address and that somehow fixed the address clash / firewall issue.
```
[16:01:18.335][SambaShare ][Error ] Unable to mount C drive: unexpected error: System.Exception: dial tcp 10.0.75.1:445: i/o timeout
```
This is the VM attempting to contact the host and not getting a response.

We're also working on expanding our detection of problems like this and automating the IP address fixes.

Do you have any more reproduction instructions? Is this the first time you've installed Docker Desktop on this machine or is it possible some left over pieces from previous installs were lurking?

**Comment by DashAce10** [comment]
Disabling this setting worked for me.

![2019-07-02 20_34_59-Windows Defender Firewall with Advanced Security](https://user-images.githubusercontent.com/11287147/60561780-a5985080-9d09-11e9-8cd8-14277920f63a.png)

**Comment by bdwyertech** [comment]
@mikeparker could we make the address to reach the host configurable?  Maybe an advanced option under the sharing menu?
I can connect to via docker.for.win.localhost on port 445 or via my actual VPN adapter IP, however not the IP address on the "internal virtual switch".
