### ISSUE TITLE
Installation on windows 10 error

### ISSUE THREAD

**Issue by MuhammadAdeelRehman** [docker/for-win#3919]
I am trying to install Dockers for Windows on my windows 10 64bit but getting below error 

The process cannot access the file 'C:\Program Files\Docker\Docker\com.docker.service' because it is being used by another process.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at LightweightInstaller.UnpackArtifactsStep.<DoAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()

**Comment by mikeparker** [comment]
1. Have you installed Docker Desktop on this machine before?
2. Is that process running already before you install? Have you tried force closing the process?
3. Do you have a 3rd party antivirus software that could be locking files?

**Comment by MuhammadAdeelRehman** [comment]
Hi  Mike, 
Issue has been resolved. 
I did not enabled Virtualization on Win 10 OS before running docker exe.
Thanks
