### ISSUE TITLE
Unable to share drive

### ISSUE THREAD

**Issue by jsucupira** [docker/for-win#3937]
- [X] I have tried with the latest version of my channel (Stable and Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: BA53A3E7-E53C-4DA1-936F-89CC07C6468A/20190520190654

### Expected behavior
I would like to be able to share a drive within Docker Desktop

### Actual behavior
After selecting the drive and clicking Apply, I am prompted to enter my credentials.  Once the credentials are entered and I click okay, the screen flashes and the drive I had selected gets unselected.

### Information
I have never been able to share.  I have tried on both of my computers.
This issue happens on both version of Docker available to me (stable and edge), although the logs shows a different error for each.

  - Windows Version: Win 10 version 1809
  - Docker for Windows Version: 2.0.4.1 (34207)

### Steps to reproduce the behavior
  1. Open Settings
  2. Click Shared Drives
  3. Check one or more drive than apply

This is the error message I see in the logs:
[15:06:46.387][SambaShare     ][Info   ] Removing share "C"
[15:06:46.424][SambaShare     ][Info   ] Mount C
[15:06:46.510][Cmd            ][Info   ] This shared resource does not exist.
[15:06:46.510][Cmd            ][Info   ] More help is available by typing NET HELPMSG 2310.
[15:06:46.512][SambaShare     ][Info   ] "C" is not shared
[15:06:46.512][SambaShare     ][Info   ] Creating share "C:" as "C" with Full Control to "jonat"
[15:06:46.597][Cmd            ][Info   ] C was shared successfully.
[15:06:46.633][Cmd            ][Info   ] Share name        C
[15:06:46.633][Cmd            ][Info   ] Path              C:\
[15:06:46.633][Cmd            ][Info   ] Remark            
[15:06:46.633][Cmd            ][Info   ] Maximum users     No limit
[15:06:46.633][Cmd            ][Info   ] Users             
[15:06:46.633][Cmd            ][Info   ] Caching           Caching disabled
[15:06:46.633][Cmd            ][Info   ] Permission        JS-DESKTOP\jonat, FULL
[15:06:46.634][Cmd            ][Info   ] The command completed successfully.
[15:06:46.635][SambaShare     ][Info   ] "C" is shared
[15:06:46.638][SambaShare     ][Info   ] Username: jonat
[15:06:46.638][SambaShare     ][Info   ] Host IP: 10.0.75.1
[15:06:46.638][SambaShare     ][Info   ] Cifs options: noperm,iocharset=utf8,dir_mode=0777,nobrl,mfsymlinks,vers=3.02,domain=JS-DESKTOP,sec=ntlmsspi
[15:06:46.640][SambaShare     ][Error  ] Unable to mount C drive: unexpected error: System.AggregateException: One or more errors occurred. ---> System.TimeoutException: The operation has timed out.
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.HttpOverStream.NamedPipeDialer.<DialAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.HttpOverStream.Core.DialMessageHandler.<SendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.HttpOverStream.HttpClientExtensions.<Post>d__3`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Docker.Backend.LifecycleClient.Mount(MountRequest req)
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential cred, UserNameAndDomain info, String options, String ip)
---> (Inner Exception #0) System.TimeoutException: The operation has timed out.
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.HttpOverStream.NamedPipeDialer.<DialAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.HttpOverStream.Core.DialMessageHandler.<SendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.HttpOverStream.HttpClientExtensions.<Post>d__3`1.MoveNext()<---

[15:06:46.640][SambaShare     ][Info   ] Removing share "C"
[15:06:46.676][NamedPipeClient][Info   ] Received response for filesharing/mount
[15:06:46.676][NamedPipeServer][Info   ] filesharing/mount done in 00:00:00.5739997.

**Comment by mikeparker** [comment]
Lifecycle server log 
`2019-05-20T18:57:26Z lifecycle-server time="2019-05-20T18:57:26Z" level=info msg="/mount -> {\"status\":\"error\",\"message\":\"dial tcp 10.0.75.1:445: i/o timeout\"}"`
This suggests either an IP address clash or a firewall issue.
Try changing your subnet or subnet mask to force an IP address refresh.

Do you have any special firewall configuration or any devices that might be taking up `10.0.75.1`?

**Comment by jsucupira** [comment]
I was having this issue when running Docker within a Hyper-V VM.  I decided to just run on my main computer. @mikeparker
