### ISSUE TITLE
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 

### ISSUE THREAD

**Issue by BombStudioThai** [docker/for-win#3985]
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass21_0.<ResetToDefault>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 155
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by OlegSolonko** [comment]
I have the same problem

**Comment by adalgleish** [comment]
I am having the same issue.

**Comment by mikeparker** [comment]
Hyper-V install is corrupted, possibly because of a windows update.

See https://github.com/docker/for-win/issues/1221 for wider discussion.
* See https://github.com/docker/for-win/issues/1221#issuecomment-493118403 for the 'control flow guard' fix

Let me know if this solves your problem.

**Comment by PremRaju** [comment]
i am also having same issue.
i have tried all commented possibilities, i am unable to resolve it.
please help me out..

Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by Jrmromao** [comment]
I,m having the same issue.

**Comment by SSingh883710** [comment]
You guys can't solve. if you can, please let me know. So i could proceed with my installation.

**Comment by matthewdolman** [comment]
I'm having the same issue on a clean win 10 machine.  HyperV is turned on.

**Comment by BlumCore** [comment]
I am also having the same issue. HyperV is turned on. Also tried the 'control flow guard' fix but sadly didn't work.

**Comment by matthewdolman** [comment]
For me it turned out to be that I had a VPN installed before I installed Docker.  Turns out you can't do this.  I uninstalled the VPN, and the adaptor, removed docker and started again doing Docker first.  It worked.

**Comment by fakabbir** [comment]
Tried uncheck and check back after restart worked for me:
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
