### ISSUE TITLE
Docker for windows backend service is not installed

### ISSUE THREAD

**Issue by schneiderl** [docker/for-win#3990]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker is initialized properly and no error occurs. 
### Actual behavior
Docker crashes and does can't be initialized.
### Information

  - Windows Version:
  - Docker for Windows Version:

### Steps to reproduce the behavior

  1. I have installed docker for windows and tried to run it
  2. A error message appears with the following stack trace:

` Backend service is not installed
   at Docker.WPF.BackendClient.CheckService(String action) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 291
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 167
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 90
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59 `

also the log can be found below: 

```Version: 2.0.0.3 (31259)
Channel: stable
Sha1: 8858db33c8692b69de9987a5d672798d778735b2
Started on: 2019/05/27 14:51:45.674
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1809
Build: 17763
BuildLabName: 17763.1.amd64fre.rs5_release.180914-1434
File: C:\Users\**********\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[14:51:46.097][GUI            ][Info   ] Starting...
[14:51:46.449][ComponentVersions][Info   ] Edition community
[14:51:49.464][Tracking       ][Info   ] Crash report and usage statistics are enabled
[14:51:49.467][SegmentApi     ][Info   ] Usage statistic: appLaunched
[14:51:49.555][SegmentApi     ][Info   ] Usage statistic: heartbeat
[14:51:49.559][SegmentApi     ][Info   ] Usage statistic: Identify
[14:51:51.612][NamedPipeClient][Info   ] Sending Version()...
[14:51:52.219][NPS            ][Info   ] NPS user ceated on: 5/27/2019 9:57:51 AM -07:00, last survey:  1/1/0001 12:00:00 AM +00:00
[14:51:56.670][Notifications  ][Error  ] Backend service is not installed
[14:51:56.704][NamedPipeClient][Info   ] Sending Version()...
[14:52:01.710][CrashReport    ][Warning] Unable to gather diagnostics in Windows Service : (Backend service is not installed)
[14:52:01.711][CrashReport    ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\Resources\com.docker.diagnose.exe -path C:\Users\*******\AppData\Local\Temp\ gather -id 57B76A4C-7CB5-495C-A3A0-5C4856312752/20190527145156'
[14:52:19.139][SegmentApi     ][Info   ] Usage statistic: actionResetToDefault
[14:52:19.140][Notifications  ][Info   ] Docker Desktop will reset to default...
[14:52:19.908][CrashReport    ][Info   ] Diagnostics cancelled by user
[14:52:19.910][NamedPipeClient][Info   ] Sending Version()...
[14:52:19.922][Notifications  ][Info   ] Docker Desktop is starting...
[14:52:19.994][NamedPipeClient][Info   ] Sending Version()...
[14:52:20.006][CrashReport    ][Error  ] Empty diagnostic file C:\Users\********\AppData\Local\Temp\57B76A4C-7CB5-495C-A3A0-5C4856312752/20190527145156.zip after running : 'C:\Program Files\Docker\Docker\Resources\com.docker.diagnose.exe -path C:\Users\********\AppData\Local\Temp\ gather -id 57B76A4C-7CB5-495C-A3A0-5C4856312752/20190527145156'.
[14:52:20.007][ErrorReportWindow][Error  ] Could not gather diagnostics : Empty diagnostic file C:\Users\*******\AppData\Local\Temp\57B76A4C-7CB5-495C-A3A0-5C4856312752/20190527145156.zip.
[14:52:25.000][Notifications  ][Error  ] Backend service is not installed
[14:52:25.048][NamedPipeClient][Info   ] Sending Version()...
[14:52:30.060][CrashReport    ][Warning] Unable to gather diagnostics in Windows Service : (Backend service is not installed)
[14:52:30.060][CrashReport    ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\Resources\com.docker.diagnose.exe -path C:\Users\******\AppData\Local\Temp\ gather -id 57B76A4C-7CB5-495C-A3A0-5C4856312752/20190527145225'
[14:55:42.760][ErrorReportWindow][Info   ] Open logs
```

**Comment by schneiderl** [comment]
This was solved by reinstalling docker for windows twice (???). 
Closing the issue.
