### ISSUE TITLE
PolicyStore PersistentStore and Dhcp Enabled exception

### ISSUE THREAD

**Issue by nirodg** [docker/for-win#4003]
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled

   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

Diagnostic id 8EE08DD5-0140-49A9-827E-FAFA37F6A3DF/20190529190555

**Comment by mikeparker** [comment]
Are you using Cisco AnyConnect?
- stop Cisco agent, restart docker, start Cisco agent.

**Comment by nirodg** [comment]
> Are you using Cisco AnyConnect?
> 
> * stop Cisco agent, restart docker, start Cisco agent.
> 
> Dupe of #2050

Indeed, stoping Cisco VPN services fixes the problem.
