### ISSUE TITLE
fresh install, Docker 2.0.0.3 on Server 2019 Desktop

### ISSUE THREAD

**Issue by SergiuEnachi** [docker/for-win#4009]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 85F6ACAD-0479-43D7-910B-B03C7BEB2D6D/20190530045821

### Expected behavior
Successful first time startup !

### Actual behavior
Crash on startup

### Information

  - Windows Version: Server 2019 v18009 (Build 17763.529)
  - Docker for Windows Version: CE 2.0.0.3 (31259). Channel Stable

### Steps to reproduce the behavior

  1. Fresh Windows Server 2019 install, fully updated. Add Hyper-V and Containers features
  2. Download latest available Docker for Desktop version, and complete Installation
  3. Start if from Desktop Shortcut or Start menu - Error,
An error occurred
```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID A4DE3A6E-77F7-4A4D-AA68-60C4D09FC254)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID A4DE3A6E-77F7-4A4D-AA68-60C4D09FC254).
at Start-MobyLinuxVM, <No file>: line 296
at <ScriptBlock>, <No file>: line 412
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```

PS: docker version
```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

```

**Comment by SergiuEnachi** [comment]
For some reason, under default Administrator, it's working, after couple of restarts, and re-installation of Docker..
