### ISSUE TITLE
Backend service is not installed

### ISSUE THREAD

**Issue by Zoey233** [docker/for-win#4013]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:
50A0299D-D639-4ACF-8139-F4F127D9B724/20190531091802
### Expected behavior
install the docker
### Actual behavior
backend service is not installed
### Information

  - Windows Version:windows 10
  - Docker for Windows Version:latest

### Steps to reproduce the behavior

  1. installed minikube in my windows, and i can ues helm and kubectl
  2. download the docker for windows from the https://www.docker.com/get-started
  3.I got an error: 
Backend service is not installed
   at Docker.WPF.BackendClient.CheckService(String action) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 291
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\BackendClient.cs:line 167
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by R-Adrian** [comment]
you need at least Windows 10 Professional to run Docker, since it depends on the Hyper-V features that are only available in Pro.

Windows 10 Home (also known as "Windows 10" without anything added after the name) is not compatible with Docker because it has no support for Hyper-V virtualization.

The system requirements for Docker mention Windows 10 "Pro" or "Enterprise" / "Education" for this reason. https://docs.docker.com/docker-for-windows/install/
