### ISSUE TITLE
Docker Crash on Fresh Install Win1809

### ISSUE THREAD

**Issue by eanbowman** [docker/for-win#4135]
### Expected behavior
Docker running on first fresh install startup. Possibly same as #1640 ?

### Actual behavior
Docker crashed
![image](https://user-images.githubusercontent.com/1637212/60100110-07afef00-9727-11e9-9e9c-e1131961fcc3.png)

### Information

   at Docker.WPF.ClientConfig.DockerLogin.SetCredentialInStore(DockerLoginCredential cred) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\ClientConfig\DockerLogin.cs:line 158
   at Docker.WPF.ClientConfig.DockerLogin.OnCredentialChanges(Auth cred) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\ClientConfig\DockerLogin.cs:line 112
   at Docker.Core.Mediator`1.Raise(T ev) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\Mediator.cs:line 50
   at Docker.WPF.DockerHub.CredentialManager.Store(Credential cred, Credential oAuthCred) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\DockerHub\CredentialManager.cs:line 134
   at Docker.WPF.DockerHub.CredentialManager.<ValidateBasicCredentialsAsync>d__21.MoveNext() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\DockerHub\CredentialManager.cs:line 165
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.WPF.WelcomeWindow.<LogIn>d__10.MoveNext() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\WelcomeWindow.xaml.cs:line 144
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Program.cs:line 216
  - Windows Version: Windows 10 1809 Build 17763.503
  - Docker Desktop Version:
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:31 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false

### Steps to reproduce the behavior

1. Brand new Windows 10 install
2. Brand new Docker Install
3. Start Docker up the first time
4. (See crash report) 4BD24137-71AA-4F5D-8569-99D76AF33AE1/20190625084814

**Comment by eanbowman** [comment]
After running Docker as Administrator once, I was able to share the C drive and get on with working. That doesn't seem like it should be required.

**Comment by eanbowman** [comment]
Did ya ever fix it? :P
