### ISSUE TITLE
Docker is getting crashed again and again

### ISSUE THREAD

**Issue by mallesh-kumr** [docker/for-win#4166]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by mallesh-kumr** [comment]
Diagnostic ID: D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143743
Version: 2.0.0.3 (31259)
Channel: stable
Sha1: 8858db33c8692b69de9987a5d672798d778735b2
Started on: 2019/07/02 14:37:11.177
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1803
Build: 17134
BuildLabName: 17134.1.amd64fre.rs4_release.180410-1804
File: C:\Users\maneelak\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[14:37:11.300][GUI            ][Info   ] Starting...
[14:37:11.379][ComponentVersions][Info   ] Edition community
[14:37:12.076][Tracking       ][Info   ] Crash report and usage statistics are enabled
[14:37:12.079][SegmentApi     ][Info   ] Usage statistic: appLaunched
[14:37:12.161][SegmentApi     ][Info   ] Usage statistic: heartbeat
[14:37:12.166][SegmentApi     ][Info   ] Usage statistic: Identify
[14:37:14.312][NamedPipeClient][Info   ] Sending Version()...
[14:37:14.321][NamedPipeClient][Info   ] Received response for Version
[14:37:14.322][NamedPipeClient][Info   ] Sending MigrateApp()...
[14:37:14.325][NamedPipeClient][Info   ] Received response for MigrateApp
[14:37:14.320][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:37:14.324][NamedPipeServer][Info   ] MigrateApp()
[14:37:14.327][Notifications  ][Info   ] Docker Desktop is starting...
[14:37:14.325][NamedPipeServer][Info   ] MigrateApp done in 00:00:00.0009974.
[14:37:14.346][NamedPipeClient][Info   ] Sending Version()...
[14:37:14.348][NamedPipeServer][Info   ] Version()
[14:37:14.348][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:37:14.353][NamedPipeClient][Info   ] Received response for Version
[14:37:14.354][NamedPipeClient][Info   ] Sending RegisterFileAssociations(C:\Program Files\Docker\Docker\Docker for Windows.exe)...
[14:37:14.356][NamedPipeServer][Info   ] RegisterFileAssociations(C:\Program Files\Docker\Docker\Docker for Windows.exe)
[14:37:14.358][FileTypeRegistrar][Info   ] Registering file association for extension .ddvp
[14:37:14.362][NamedPipeClient][Info   ] Received response for RegisterFileAssociations
[14:37:14.364][NamedPipeClient][Info   ] Sending Version()...
[14:37:14.361][NamedPipeServer][Info   ] RegisterFileAssociations done in 00:00:00.0048060.
[14:37:14.366][NamedPipeClient][Info   ] Received response for Version
[14:37:14.366][NamedPipeClient][Info   ] Sending EnableVersionPack(default, Docker.Core.Settings)...
[14:37:14.366][NamedPipeServer][Info   ] Version()
[14:37:14.366][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:37:14.372][NamedPipeClient][Info   ] Received response for EnableVersionPack
[14:37:14.370][NamedPipeServer][Info   ] EnableVersionPack(default, Docker.Core.Settings)
[14:37:14.372][NamedPipeServer][Info   ] EnableVersionPack done in 00:00:00.0020471.
[14:37:14.377][NamedPipeClient][Info   ] Sending Version()...
[14:37:14.381][NamedPipeClient][Info   ] Received response for Version
[14:37:14.381][NamedPipeClient][Info   ] Sending Start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions)...
[14:37:14.380][NamedPipeServer][Info   ] Version()
[14:37:14.380][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:37:14.387][NamedPipeServer][Info   ] Start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions)
[14:37:14.387][PowerMode      ][Info   ] Stop
[14:37:14.387][HyperV         ][Info   ] Stop
[14:37:14.388][PowerShell     ][Info   ] Run script with parameters: -Stop True
[14:37:14.445][HyperV         ][Info   ] Script started at 14:37:14.445
[14:37:14.459][HyperV         ][Info   ] Modules loaded at 14:37:14.459
[14:37:14.483][NPS            ][Info   ] NPS last local survey date: 7/1/2019 8:44:05 AM +00:00
[14:37:14.557][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[14:37:14.557][HyperV         ][Debug  ] [stop] took 00:00:00.1702755 to run
[14:37:14.557][OptimizeDisk   ][Info   ] Optimize
[14:37:14.557][PowerShell     ][Info   ] Run script...
[14:37:14.708][Moby           ][Info   ] Stop
[14:37:14.729][HyperV         ][Info   ] Create
[14:37:14.731][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64000000000 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[14:37:14.735][HyperVGuids    ][Info   ] Installing GUIDs...
[14:37:14.735][PowerMode      ][Info   ] Start
[14:37:14.736][Firewall       ][Info   ] Removing all existing rules...
[14:37:14.745][HyperVGuids    ][Info   ] GUIDs installed
[14:37:14.790][Firewall       ][Info   ] All existing rules are removed.
[14:37:14.790][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[14:37:14.791][HyperV         ][Info   ] Script started at 14:37:14.791
[14:37:14.800][Firewall       ][Info   ] Opening ports for SMB...
[14:37:14.805][HyperV         ][Info   ] Modules loaded at 14:37:14.805
[14:37:14.814][Firewall       ][Info   ] Ports are opened
[14:37:14.964][HyperV         ][Info   ] Creating Switch: DockerNAT...
[14:37:18.336][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411. Let's retry
[14:37:18.366][HyperV         ][Info   ] Hyper-V is running
[14:37:18.366][PowerMode      ][Info   ] Stop
[14:37:18.366][HyperV         ][Info   ] Stop
[14:37:18.367][PowerShell     ][Info   ] Run script with parameters: -Stop True
[14:37:18.424][HyperV         ][Info   ] Script started at 14:37:18.424
[14:37:18.440][HyperV         ][Info   ] Modules loaded at 14:37:18.440
[14:37:18.486][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[14:37:18.486][HyperV         ][Debug  ] [stop] took 00:00:00.1196535 to run
[14:37:18.486][OptimizeDisk   ][Info   ] Optimize
[14:37:18.486][PowerShell     ][Info   ] Run script...
[14:37:18.542][Moby           ][Info   ] Stop
[14:37:18.550][HyperV         ][Info   ] Destroy
[14:37:18.551][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True
[14:37:18.603][HyperV         ][Info   ] Script started at 14:37:18.602
[14:37:18.624][HyperV         ][Info   ] Modules loaded at 14:37:18.624
[14:37:18.665][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[14:37:18.666][HyperV         ][Info   ] Destroying Switch DockerNAT...
[14:37:18.720][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[14:37:18.733][HyperV         ][Debug  ] [destroy] took 00:00:00.1835026 to run
[14:37:18.733][Firewall       ][Info   ] Closing ports...
[14:37:18.733][Firewall       ][Info   ] Removing all existing rules...
[14:37:18.863][Firewall       ][Info   ] All existing rules are removed.
[14:37:18.863][Firewall       ][Info   ] Ports are closed
[14:37:18.863][HyperVGuids    ][Info   ] Removing GUIDs...
[14:37:18.866][HyperVGuids    ][Info   ] GUIDs removed
[14:37:18.866][HyperV         ][Info   ] Create
[14:37:18.866][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64000000000 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[14:37:18.914][HyperV         ][Info   ] Script started at 14:37:18.914
[14:37:18.934][HyperV         ][Info   ] Modules loaded at 14:37:18.934
[14:37:19.013][HyperV         ][Info   ] Creating Switch: DockerNAT...
[14:37:21.265][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 195
   at Docker.Backend.HyperV.Create(Settings settings) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 125
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 117
[14:37:21.529][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
[14:37:21.531][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
[14:37:21.611][NamedPipeClient][Info   ] Sending Version()...
[14:37:21.618][NamedPipeClient][Info   ] Received response for Version
[14:37:21.618][NamedPipeClient][Info   ] Sending GatherDiagnostics(-path C:\Users\maneelak\AppData\Local\Temp\ gather -id D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143721, C:\Users\maneelak\AppData\Local\Temp\D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143721.zip)...
[14:37:21.618][NamedPipeServer][Info   ] Version()
[14:37:21.618][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:37:21.628][NamedPipeServer][Info   ] GatherDiagnostics(-path C:\Users\maneelak\AppData\Local\Temp\ gather -id D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143721, C:\Users\maneelak\AppData\Local\Temp\D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143721.zip)
[14:37:33.446][CrashReport    ][Info   ] Diagnostics cancelled by user
[14:37:33.446][NamedPipeClient][Info   ] Sending Version()...
[14:37:33.450][NamedPipeClient][Info   ] Sending Version()...
[14:37:33.467][NamedPipeServer][Info   ] Version()
[14:37:33.470][NamedPipeClient][Info   ] Received response for Version
[14:37:33.472][NamedPipeClient][Info   ] Sending StopGatherDiagnostics()...
[14:37:33.470][NamedPipeServer][Info   ] Version done in 00:00:00.0035321.
[14:37:33.473][NamedPipeClient][Info   ] Received response for Version
[14:37:33.473][NamedPipeClient][Info   ] Sending Stop(Linux, Docker.Core.Settings)...
[14:37:33.473][NamedPipeServer][Info   ] Version()
[14:37:33.473][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:37:33.479][NamedPipeClient][Info   ] Received response for StopGatherDiagnostics
[14:37:33.478][NamedPipeServer][Info   ] StopGatherDiagnostics()
[14:37:33.479][NamedPipeServer][Info   ] StopGatherDiagnostics done in 00:00:00.0009641.
[14:37:33.482][NamedPipeServer][Info   ] Stop(Linux, Docker.Core.Settings)
[14:37:33.482][PowerMode      ][Info   ] Stop
[14:37:33.482][HyperV         ][Info   ] Stop
[14:37:33.486][PowerShell     ][Info   ] Run script with parameters: -Stop True
[14:37:33.526][NamedPipeClient][Error  ] Unable to send GatherDiagnostics: Empty diagnostic file C:\Users\maneelak\AppData\Local\Temp\D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143721.zip
[14:37:33.527][CrashReport    ][Warning] Unable to gather diagnostics in Windows Service : (Empty diagnostic file C:\Users\maneelak\AppData\Local\Temp\D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143721.zip)
[14:37:33.528][CrashReport    ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\Resources\com.docker.diagnose.exe -path C:\Users\maneelak\AppData\Local\Temp\ gather -id D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143721'
[14:37:33.520][Backend        ][Error  ] Empty diagnostic file C:\Users\maneelak\AppData\Local\Temp\D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143721.zip after running : 'C:\Program Files\Docker\Docker\Resources\com.docker.diagnose.exe -path C:\Users\maneelak\AppData\Local\Temp\ gather -id D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143721', deleting it.
[14:37:33.683][NamedPipeClient][Info   ] Received response for Stop
[14:37:33.687][NamedPipeClient][Info   ] Sending Version()...
[14:37:33.523][NamedPipeServer][Error  ] Unable to execute GatherDiagnostics: Empty diagnostic file C:\Users\maneelak\AppData\Local\Temp\D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143721.zip    at Docker.Backend.Backend.GatherDiagnostics(String args, String file) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\Backend.cs:line 309
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180
[14:37:33.537][HyperV         ][Info   ] Script started at 14:37:33.537
[14:37:33.558][HyperV         ][Info   ] Modules loaded at 14:37:33.558
[14:37:33.605][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[14:37:33.605][HyperV         ][Debug  ] [stop] took 00:00:00.1229246 to run
[14:37:33.701][NamedPipeClient][Info   ] Received response for Version
[14:37:33.701][NamedPipeClient][Info   ] Sending Destroy(Docker.Core.Settings, Linux, True)...
[14:37:33.605][OptimizeDisk   ][Info   ] Optimize
[14:37:33.605][PowerShell     ][Info   ] Run script...
[14:37:33.665][Moby           ][Info   ] Stop
[14:37:33.679][NamedPipeServer][Info   ] Stop done in 00:00:00.1969105.
[14:37:33.701][NamedPipeServer][Info   ] Version()
[14:37:33.701][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:37:33.707][NamedPipeServer][Info   ] Destroy(Docker.Core.Settings, Linux, True)
[14:37:33.707][HyperV         ][Info   ] Destroy
[14:37:33.710][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True
[14:37:33.765][HyperV         ][Info   ] Script started at 14:37:33.765
[14:37:33.787][HyperV         ][Info   ] Modules loaded at 14:37:33.787
[14:37:33.862][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[14:37:33.864][HyperV         ][Info   ] Destroying Switch DockerNAT...
[14:37:33.936][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[14:37:33.950][HyperV         ][Debug  ] [destroy] took 00:00:00.2424162 to run
[14:37:33.950][Firewall       ][Info   ] Closing ports...
[14:37:33.992][NamedPipeClient][Info   ] Received response for Destroy
[14:37:33.950][Firewall       ][Info   ] Removing all existing rules...
[14:37:33.990][Firewall       ][Info   ] All existing rules are removed.
[14:37:33.990][Firewall       ][Info   ] Ports are closed
[14:37:33.990][HyperVGuids    ][Info   ] Removing GUIDs...
[14:37:33.990][HyperVGuids    ][Info   ] GUIDs removed
[14:37:33.992][Backend        ][Warning] The directory is not empty.

[14:37:33.992][NamedPipeServer][Info   ] Destroy done in 00:00:00.2844768.
[14:37:43.445][SegmentApi     ][Info   ] Usage statistic: actionMenuFeedback
[14:37:43.528][NamedPipeClient][Info   ] Sending Version()...
[14:37:43.531][NamedPipeServer][Info   ] Version()
[14:37:43.531][NamedPipeServer][Info   ] Version done in 00:00:00.
[14:37:43.548][NamedPipeClient][Info   ] Received response for Version
[14:37:43.561][NamedPipeClient][Info   ] Sending GatherDiagnostics(-path C:\Users\maneelak\AppData\Local\Temp\ gather -id D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143743, C:\Users\maneelak\AppData\Local\Temp\D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143743.zip)...
[14:37:43.574][NamedPipeServer][Info   ] GatherDiagnostics(-path C:\Users\maneelak\AppData\Local\Temp\ gather -id D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143743, C:\Users\maneelak\AppData\Local\Temp\D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143743.zip)
[14:38:28.442][FeedbackWindow ][Info   ] Open troubleshoot
[14:42:56.803][GUI            ][Info   ] Sending Bugsnag report 1b68a48e-d008-41d1-bf70-e9a2aa2d3f0c...
[14:42:58.298][GUI            ][Info   ] Bugsnag report 1b68a48e-d008-41d1-bf70-e9a2aa2d3f0c sent
[14:43:05.323][NamedPipeClient][Info   ] Received response for GatherDiagnostics
[14:43:05.322][NamedPipeServer][Info   ] GatherDiagnostics done in 00:05:21.7475272.
[14:48:01.494][FeedbackWindow ][Info   ] Uploading diagnostics...
[14:48:01.496][CrashReport    ][Info   ] Uploading diagnostics D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143743
[14:48:05.717][CrashReport    ][Info   ] Uploaded succesfully diagnostics D5D80BED-7AA7-4C15-968E-6EA106BC6D86/20190702143743
[15:37:12.208][SegmentApi     ][Info   ] Usage statistic: heartbeat
[15:43:41.985][SegmentApi     ][Info   ] Usage statistic: actionMenuSettings
[15:43:42.155][NamedPipeClient][Info   ] Sending Version()...
[15:43:42.157][NamedPipeClient][Info   ] Sending Version()...
[15:43:42.159][NamedPipeClient][Info   ] Received response for Version
[15:43:42.159][NamedPipeClient][Info   ] Sending TryGetVhdxSize()...
[15:43:42.159][NamedPipeClient][Info   ] Received response for Version
[15:43:42.160][NamedPipeClient][Info   ] Sending TryGetVhdxSize()...
[15:43:42.166][NamedPipeClient][Info   ] Sending Version()...
[15:43:42.166][NamedPipeClient][Info   ] Sending Version()...
[15:43:42.158][NamedPipeServer][Info   ] Version()
[15:43:42.158][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:43:42.159][NamedPipeServer][Info   ] Version()
[15:43:42.159][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:43:42.160][NamedPipeServer][Info   ] TryGetVhdxSize()
[15:43:42.161][PowerShell     ][Info   ] Run script 'Get-VHD –Path "" | select -ExpandProperty Size'...
[15:43:42.161][NamedPipeServer][Info   ] TryGetVhdxSize()
[15:43:42.161][PowerShell     ][Info   ] Run script 'Get-VHD –Path "" | select -ExpandProperty Size'...
[15:43:42.753][NamedPipeClient][Info   ] Received response for TryGetVhdxSize
[15:43:42.754][NamedPipeClient][Info   ] Sending Version()...
[15:43:42.756][NamedPipeClient][Info   ] Received response for Version
[15:43:42.756][NamedPipeClient][Info   ] Sending GetDefaultVhdxPath()...
[15:43:42.752][NamedPipeServer][Info   ] TryGetVhdxSize done in 00:00:00.5920195.
[15:43:42.757][NamedPipeClient][Info   ] Received response for Version
[15:43:42.757][NamedPipeClient][Info   ] Sending TryGetVhdxSize()...
[15:43:42.756][NamedPipeServer][Info   ] Version()
[15:43:42.760][NamedPipeClient][Info   ] Received response for Version
[15:43:42.760][NamedPipeClient][Info   ] Sending TryGetVhdxSize()...
[15:43:42.762][NamedPipeClient][Info   ] Received response for GetDefaultVhdxPath
[15:43:42.756][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:43:42.757][NamedPipeServer][Info   ] Version()
[15:43:42.767][NamedPipeClient][Info   ] Sending Version()...
[15:43:42.767][NamedPipeClient][Info   ] Sending Version()...
[15:43:42.757][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:43:42.758][NamedPipeServer][Info   ] Version()
[15:43:42.758][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:43:42.760][NamedPipeServer][Info   ] GetDefaultVhdxPath()
[15:43:42.762][NamedPipeServer][Info   ] GetDefaultVhdxPath done in 00:00:00.0020059.
[15:43:42.762][NamedPipeServer][Info   ] TryGetVhdxSize()
[15:43:42.762][PowerShell     ][Info   ] Run script 'Get-VHD –Path "" | select -ExpandProperty Size'...
[15:43:42.768][NamedPipeServer][Info   ] TryGetVhdxSize()
[15:43:42.768][PowerShell     ][Info   ] Run script 'Get-VHD –Path "" | select -ExpandProperty Size'...
[15:43:42.798][NamedPipeClient][Info   ] Received response for TryGetVhdxSize
[15:43:42.802][NamedPipeClient][Info   ] Sending Version()...
[15:43:42.798][NamedPipeServer][Info   ] TryGetVhdxSize done in 00:00:00.0359988.
[15:43:42.801][NamedPipeServer][Info   ] Version()
[15:43:42.804][NamedPipeClient][Info   ] Received response for Version
[15:43:42.804][NamedPipeClient][Info   ] Sending TryGetVhdxSize(C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx)...
[15:43:42.801][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:43:42.804][NamedPipeServer][Info   ] Version()
[15:43:42.804][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:43:42.818][NamedPipeClient][Info   ] Received response for TryGetVhdxSize
[15:43:42.818][NamedPipeClient][Info   ] Received response for Version
[15:43:42.819][NamedPipeClient][Info   ] Sending TryGetVhdxSize(C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx)...
[15:43:42.820][NamedPipeClient][Info   ] Received response for Version
[15:43:42.820][NamedPipeClient][Info   ] Sending TryGetVhdxSize(C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx)...
[15:43:42.818][NamedPipeServer][Info   ] TryGetVhdxSize done in 00:00:00.0500346.
[15:43:42.820][NamedPipeServer][Info   ] Version()
[15:43:42.820][NamedPipeServer][Info   ] TryGetVhdxSize(C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx)
[15:43:42.820][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:43:42.820][PowerShell     ][Info   ] Run script...
[15:43:42.821][NamedPipeServer][Info   ] TryGetVhdxSize(C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx)
[15:43:42.821][PowerShell     ][Info   ] Run script...
[15:43:42.822][NamedPipeServer][Info   ] TryGetVhdxSize(C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx)
[15:43:42.822][PowerShell     ][Info   ] Run script...
[15:43:42.870][NamedPipeClient][Info   ] Received response for TryGetVhdxSize
[15:43:42.870][NamedPipeServer][Info   ] TryGetVhdxSize done in 00:00:00.7090289.
[15:43:42.904][NamedPipeClient][Info   ] Received response for TryGetVhdxSize
[15:43:42.906][NamedPipeClient][Info   ] Sending Version()...
[15:43:42.904][NamedPipeServer][Info   ] TryGetVhdxSize done in 00:00:00.0840045.
[15:43:42.907][NamedPipeClient][Info   ] Received response for Version
[15:43:42.907][NamedPipeClient][Info   ] Sending TryGetVhdxSize(C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx)...
[15:43:42.907][NamedPipeServer][Info   ] Version()
[15:43:42.907][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:43:42.910][NamedPipeServer][Info   ] TryGetVhdxSize(C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx)
[15:43:42.911][PowerShell     ][Info   ] Run script...
[15:43:42.922][NamedPipeClient][Info   ] Received response for TryGetVhdxSize
[15:43:42.922][NamedPipeServer][Info   ] TryGetVhdxSize done in 00:00:00.1010029.
[15:43:42.956][NamedPipeClient][Info   ] Received response for TryGetVhdxSize
[15:43:42.956][NamedPipeServer][Info   ] TryGetVhdxSize done in 00:00:00.1340033.
[15:43:42.968][NamedPipeClient][Info   ] Received response for TryGetVhdxSize
[15:43:42.967][NamedPipeServer][Info   ] TryGetVhdxSize done in 00:00:00.0570002.
[15:52:56.401][FeedbackWindow ][Info   ] Open logs
