### ISSUE TITLE
Docker timeout crash on switching to windows containers

### ISSUE THREAD

**Issue by cchuter** [docker/for-win#4174]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:
8492F6F5-3664-481C-9904-0AE0F240B487/20190703183937
### Expected behavior
After a clean install of windows docker for desktop, I attempted a switch from Linux containers to windows containers. I expected it to switch.

### Actual behavior
It crashed:

```
Time out has expired and the operation has not been completed.
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env)
   at Docker.Backend.Processes.WindowsDockerDaemon.Start(Settings settings, String daemonOptions, Boolean useProtectedNamedPipe)
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendServer.<Run>b__8_4(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

  - Windows Version: Version	10.0.17763 Build 17763, Windows 10 Pro, 1809
  - Docker Desktop Version: 2.0.0.3

This is a work computer, that is running Carbon Black virus and endpoint protection. It is possible that that is preventing hyper-V from running some of its commands and thus causing this timeout. However, if that is the case, I wouldn't expect docker to crash. Once in this state docker is completely hosed and has to be reinstalled. Restarting or attempting to reset to factory defaults results in an endless loop of timeouts.  Initial installation of linux containers works (even though windows containers is selected as the starting container). This timeout crash occurs on switching.

### Steps to reproduce the behavior

  1. Install latest docker
  2. Switch to Windows containers.

**Comment by cchuter** [comment]
I have confirmed that Carbon Black is the issue. When it is off, I can switch containers. It appears that it is blocking hyper-v commands.

**Comment by ismaelthesilva** [comment]
Where is Carbon Black in the system? Thanks :)
