### ISSUE TITLE
Docker doesn't display a clear warning when using a computer with a unsupported name

### ISSUE THREAD

**Issue by TijmenW** [docker/for-win#4192]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 10951C40-27B9-4869-9E72-C6F02B661033/20190707163617

### Expected behavior

Either Docker should work, or the installation program should warn you in a clear way that the name is unsupported. 

### Actual behavior

Docker crashes with: `Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer `_…_` could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59`

As described in e.g. #147.

### Information

  - Windows Version: Windows 10 Enterprise 1903 (&1803)
  - Docker Desktop Version: Version 2.0.0.3 (31259)

Docker for Windows has A.F.A.I.K. never worked on computers whose names are weird, e.g. consisting only out of numbers.  
However, the error message users get to see is very confusing, leading user to open issues here, e.g.: #147, #3696, #3389, and #4055. (Probably)

While it would be nice to have Docker work with those names, since it's not always practical for users to rename their computer, it should at least display a clearer warning that the user should rename their computer and not a stack trace instead.

### Steps to reproduce the behavior

1. Have a computer with an unsupported name, like one consisting only of numbers, one looking like an IP-address or one consisting of more than 16 characters.
2. Install Docker for Windows.

**Comment by TijmenW** [comment]
@docker-desktop-robot 

/remove-lifecycle stale

**Comment by TijmenW** [comment]
Seems to be working now with the new WSL update.
