### ISSUE TITLE
Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running

### ISSUE THREAD

**Issue by anle20** [docker/for-win#4197]
Hi all,

I have the trouble when install docker on windows server. 

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID DF4E014A-351E-450C-B502-2DCE492101EC)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID DF4E014A-351E-450C-B502-2DCE492101EC).
at Start-MobyLinuxVM, <No file>: line 296
at <ScriptBlock>, <No file>: line 412
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by jjaiganesh** [comment]
Hi,

I too am facing this issue, but it happens for me  while switching the VM from windows to Linux. I noticed the windows creates a vm in Hyper-v Manager but fails to start it.

**Comment by mikeparker** [comment]
Are you running Docker Desktop from inside a Virtualized Server, or bare metal?

**Comment by jjaiganesh** [comment]
I installed on windows laptop, i guess bare metal it is.

**Comment by mikeparker** [comment]
@jjaiganesh can you post a diagnostic ID please?

**Comment by anle20** [comment]
Thank you for your help.

When I tried to install docker on PC, it worked. I think windows server cannot support to docker desktop.
