### ISSUE TITLE
Unable to start Docker Desktop in Windows 10 VM

### ISSUE THREAD

**Issue by avinash-premanath** [docker/for-win#4209]
I am using a Windows 10 Enterprise machine, Hyper-V is enabled in the VM but still couldn't get Docker running.

This is the error that I am getting 
_Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

Failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running.

'MobyLinuxVM' failed to start. (Virtual machine ID 143A83D1-5582-4859-BC9C-95A6BC9B38DB)

The Virtual Machine Management Service failed to start the virtual machine 'MobyLinuxVM' because one of the Hyper-V components is not running (Virtual machine ID 143A83D1-5582-4859-BC9C-95A6BC9B38DB).
at Start-MobyLinuxVM, <No file>: line 296
at <ScriptBlock>, <No file>: line 412
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59_

I have uploaded Diagnostics
  - **Diagnostics ID: FE13AFA1-03E2-4207-AC2B-456A8115D8B7/20190710153906**

**Comment by srinuiam** [comment]
I am experiencing same issue, do you have any solution for this issue.
