### ISSUE TITLE
Docker does not Start on Windows 10 Enterprise VM build 1903

### ISSUE THREAD

**Issue by samitcauseway** [docker/for-win#4262]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 929956BE-F1A0-44BC-9C62-D9930F11F321/20190718130209

### Expected behavior
Docker for windows should start

### Actual behavior
Docker for windows does not start

### Information

  - Windows Version: Windows 10 Enterprise build 1903 VM off VSpshere
  - Docker Desktop Version: 2.0.0.3

### Steps to reproduce the behavior

  1. ... Install Docker for desktop (Containers for windows unchecked) - Successful
  2. ... Launch Docker Desktop (as admin or standard)
  3. ... Waits a long time and then shows this
  4. ...  Hyper-V working fine (checked on ubuntu VM)
  5. ... MobyLinuxVm appears to run on Hyper-V manager (although Heartbeat = No Contact)
  6. ... Virtualisation enabled on VM

No activity detected on VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
[log.txt](https://github.com/docker/for-win/files/3406635/log.txt)

**Comment by stephen-turner** [comment]
Docker Desktop is not supported within a VM.
