### ISSUE TITLE
Cannot change image location

### ISSUE THREAD

**Issue by 8thHalfHour** [docker/for-win#4269]
- [x] I have tried with the latest version of my channel (Stable and Edge, to compare)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: There is no diagnostic log for this issue, as it appears to be missing functionality between Stable and Edge.

### Expected behavior

In Stable, you can change the disk location for Docker. I expected to find this option in Edge, as well. (I had to move to Edge because Stable will not allow me to change the storage location of images without crashing. I have that issue [here](https://github.com/docker/for-win/issues/1223#issuecomment-513294359).)

### Actual behavior

There does not appear to be a method to change the disk location for Docker Desktop Edge v2.0.5.0 (bld 35318).

### Information
  - Is it reproducible: Is it 100% reproducible, as the option does not exist. There is no Settings option, at all, that I can find, to perform this activity.
  - Is it new: I do not know if  the issue existed in previous versions of Edge, so I cannot comment if it is new. However, it has probably existed since the version I have installed was released.
  - Did it appear after an update: It did not appear with an update, for me, but with the actual installer.
 
  - Windows Version: Win 10 Pro v1903 (May 2019 Update)
  - Docker Desktop Version: Docker Desktop Edge v2.0.5.0 (bld 35318)

### Steps to reproduce the behavior
1. Look in settings to find a location to change the disk image location; it is not there.

**Comment by stephen-turner** [comment]
@8thHalfHour Are you using Linux containers or Windows containers? This option is only applicable for Linux containers.

**Comment by 8thHalfHour** [comment]
Aha! I am using Windows containers. Oddly enough, it works for Windows in Edge, though, so maybe this should be made a real feature in Windows, as well?

**Comment by 8thHalfHour** [comment]
Also, when I switched to Linux containers, I got the following errors:

```No activity detected on VM, aborting
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendServer.<Run>b__8_5(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)```

This occured when I applied the code `"graph": "G:\\AllContent\\VM\\DI"` to the daemon. Crash report ID: 8728FAE4-349C-40EB-A403-46CF2CBD6AD1/20190724020508.

**Comment by 8thHalfHour** [comment]
Has there been any update on this becoming a supported mechanism in Windows builds? It still works in Edge.

**Comment by stephen-turner** [comment]
No, the option doesn't make sense on Windows, as it's where the VM's disk is stored, and there is no VM for Windows containers.

I don't see this on Edge, but even if it shows up on some Edge versions, I'm pretty sure it can't do anything.

**Comment by 8thHalfHour** [comment]
Stephen, what I am saying is that when I change the VM location, I can get Docker yo recognize the new location with Edge; it will not do so with the stable release. And yes, this is still an issue with Windows because we, too, don’t necessarily want our images on our C:\ drive. Clearly, since I opened this and have forced Docker to use a different home for its images on Windows. Also, this question is all over the Web. This is a legit thing. I just wanted to know why I can get the daemon commands to work in Edge, but not the stable release.
