### ISSUE TITLE
Cannot Change Storage Location of Pulled Images

### ISSUE THREAD

**Issue by 8thHalfHour** [docker/for-win#4290]
- [x] I have tried with the latest version of my channel (Stable and Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
5A13236C-A79D-4616-BA2E-116DDA5D4E17/20190718093020 (from Stable using Windows containers)
8728FAE4-349C-40EB-A403-46CF2CBD6AD1/20190724020508 (from Edge, using Linux containers)
[ NOTE: There is no crash for changing the storage location on Edge for Windows; it just keeps asking me to "Apply" the changes ]

### Expected behavior

When I add `"graph": "G:\\AllContent\\VM\\DI"` to the `Settings > Daemon > Advanced switch >` window, the location where Docker for Windows' storage location changes to the location I've specified.

### Actual behavior

Crashes in Stable for Windows containers and Crashes for Stable and Edge for Linux containers. Edge for Windows containers doesn't crash, it just restarts fine and just keeps asking me to "Apply" my changes. It also moves the image storage location, as expected.

Edge (with containers for Linux), also produces this error:
`No activity detected on VM, aborting at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential) at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions, Credential credential) at Docker.Backend.BackendServer.<Run>b__8_5(Object[] args) at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)`

### Information

  - Is it reproducible? Yes. Every time.
  - Is the problem new? I am new to Docker, so I do not know.
  - Did the problem appear with an update? I also wouldn't know the answer to that. 
  - Windows Version: Win 10 Pro v1903
  - Docker Desktop Version: Edge v2.0.5.35318

### Steps to reproduce the behavior

Already described in Expected Behavior section.

**Comment by 8thHalfHour** [comment]
I've also tried using this JSON that Microsoft recommends: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon

`{
    "authorization-plugins": [],
    "dns": [],
    "dns-opts": [],
    "dns-search": [],
    "exec-opts": [],
    "storage-driver": "",
    "storage-opts": [],
    "labels": [],
    "log-driver": "", 
    "mtu": 0,
    "pidfile": "",
    "data-root": "",
    "cluster-store": "",
    "cluster-advertise": "",
    "debug": true,
    "hosts": [],
    "log-level": "",
    "tlsverify": true,
    "tlscacert": "",
    "tlscert": "",
    "tlskey": "",
    "group": "",
    "default-ulimits": {},
    "bridge": "",
    "fixed-cidr": "",
    "raw-logs": false,
    "registry-mirrors": [],
    "insecure-registries": [],
    "disable-legacy-registry": false
}`

And when I place a value for `data-root`, as they also explain in this article, like `"data-root" : "G:\\AllContent\\VM\\DI"`, this fails with the following errors:

```
After parsing a value an unexpected character was encountered: ". Path 'graph', line 7, position 2.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Docker.Backend.Processes.WindowsDaemonJsonRewriter.RewriteOptions(String daemonOptions, Settings settings, String userName, Boolean useProtectedNamedPipe)
   at Docker.Backend.Processes.WindowsDockerDaemon.Start(Settings settings, String daemonOptions, Boolean useProtectedNamedPipe)
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendServer.<Run>b__8_4(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

Diagnostics ID:  8728FAE4-349C-40EB-A403-46CF2CBD6AD1/20190725162332

. . . And now I am unable to reset to factory settings because it's stuck at "restarting" (even though I selected "reset to factory settings" after I submitted the Diagnostic report from the Error window). See here:

![2019-07-25_9-47-52](https://user-images.githubusercontent.com/44852729/61892964-ca738400-aec1-11e9-8dee-5fd54d9f3db0.png)
