### ISSUE TITLE
unable to share windows drive : docker for linux

### ISSUE THREAD

**Issue by sashwin** [docker/for-win#4312]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

### Actual behavior
Sharing windows C: drive or any other drive from docker setting GUI.

### Information
Reproduceable  
  - Windows Version: Windows 10 Enterprise 1803
  - Docker Desktop Version: 2.0.5.0

### Steps to reproduce the behavior

  1. Go to docker settings.
  2. Click on "shared drives"
  3. Select the drive to share. In my case "D"
  4. Click Apply

Nothing happens. Log file throws an exception...shown as attached.

[11:51:49.927][SambaShare        ][Info   ] "D" is not shared
[11:51:49.927][SambaShare        ][Info   ] Creating share "D:" as "D" with Full Control to "docker_user"
[11:51:50.041][Cmd               ][Info   ] D was shared successfully.
[11:51:50.110][Cmd               ][Info   ] Share name        D
[11:51:50.110][Cmd               ][Info   ] Path              D:\
[11:51:50.110][Cmd               ][Info   ] Remark            
[11:51:50.110][Cmd               ][Info   ] Maximum users     No limit
[11:51:50.111][Cmd               ][Info   ] Users             
[11:51:50.111][Cmd               ][Info   ] Caching           Caching disabled
[11:51:50.111][Cmd               ][Info   ] Permission        docker_host\docker_user, FULL
[11:51:50.111][Cmd               ][Info   ] The command completed successfully.
[11:51:50.116][SambaShare        ][Info   ] "D" is shared
[11:51:50.134][SambaShare        ][Info   ] Username: docker_user
[11:51:50.134][SambaShare        ][Info   ] Host IP: 10.0.75.1
[11:51:50.134][SambaShare        ][Info   ] Cifs options: noperm,iocharset=utf8,dir_mode=0777,nobrl,mfsymlinks,vers=3.02,domain=docker_host,sec=ntlmsspi
[11:51:50.204][Moby              ][Info   ] [ 7828.489722] CIFS VFS: SMB3 encryption not supported yet
[11:51:50.241][Moby              ][Info   ] [ 7828.551819] CIFS VFS: SMB3 encryption not supported yet
[11:51:50.286][Moby              ][Info   ] [ 7828.588293] CIFS VFS: SMB signature verification returned error = -13
[11:51:50.329][Moby              ][Info   ] [ 7828.632385] CIFS VFS: SMB signature verification returned error = -13
[11:51:50.372][Moby              ][Info   ] [ 7828.675584] CIFS VFS: cifs_put_smb_ses: Session Logoff failure rc=-13
[11:51:50.414][Moby              ][Info   ] [ 7828.719207] CIFS VFS: cifs_mount failed w/return code = -13
[11:51:50.421][SambaShare        ][Error  ] Unable to mount D drive: unexpected error: System.AggregateException: One or more errors occurred. ---> Docker.Backend.HttpBadResponseException: Exception of type 'Docker.Backend.HttpBadResponseException' was thrown.
   at Docker.Backend.HttpClientExtensions.<ParseResponseBodyAsJsonAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Docker.Backend.LifecycleClient.Mount(MountRequest req)
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential cred, UserNameAndDomain info, String options, String ip)
---> (Inner Exception #0) Docker.Backend.HttpBadResponseException: Exception of type 'Docker.Backend.HttpBadResponseException' was thrown.
   at Docker.Backend.HttpClientExtensions.<ParseResponseBodyAsJsonAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext()<---

[log.txt](https://github.com/docker/for-win/files/3440596/log.txt)

**Comment by diesalher** [comment]
same here +1

**Comment by slen99** [comment]
same here +1

**Comment by noumanberlas** [comment]
same with me as well +1

**Comment by mandybailey** [comment]
same here +1

**Comment by Longder** [comment]
same here +1

**Comment by lyon913** [comment]
Open gpedit and change "Computer Configuration\Windows Settings\Security Settings\Local Policies\Security Options\Network access: Sharing and security model for local accounts" value to Classic - Local users authenticate as themselves
solved for me.

**Comment by blacksider** [comment]
> Open gpedit and change "Computer Configuration\Windows Settings\Security Settings\Local Policies\Security Options\Network access: Sharing and security model for local accounts" value to Classic - Local users authenticate as themselves
> solved for me.

You just save my day!

**Comment by atodkar** [comment]
> Open gpedit and change "Computer Configuration\Windows Settings\Security Settings\Local Policies\Security Options\Network access: Sharing and security model for local accounts" value to Classic - Local users authenticate as themselves


I see this setting is already as mentioned but still I am getting this issue. Not sure what else could be the issue?
