### ISSUE TITLE
Docker Desktop Community Version 2.0.0.3 (31259) fail to start on Windows 10 Enterprise

### ISSUE THREAD

**Issue by macknight** [docker/for-win#4327]
- [y ] I have tried with the latest version of my channel (Stable or Edge)
  - [y ] I have uploaded Diagnostics
  - Diagnostics ID: 1FAF625C-185E-4C13-BC71-A828B31FF0E5/20190731104027

### Expected behavior
Docker should start, the icon should be white on desk tool bar.
### Actual behavior
Docker can not be started, the icon is red on desk tool bar.
### Information

  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: Docker Desktop Community Version 2.0.0.3 (31259)

### Steps to reproduce the behavior

  1. installer Docker Desktop Community Version 2.0.0.3 (31259) on Windows 10 Enterprise.
  2. From start menu, start Dock, the icon at last become red.
  Crash Reports:
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID BA081B1B-9665-4F56-8E83-4261A5092A04)
at Start-MobyLinuxVM, <No file>: line 296
at <ScriptBlock>, <No file>: line 412
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 92
   at Docker.Actions.<>c__DisplayClass19_0.<Start>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 74
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by macknight** [comment]
I found that even if I created a new VM in Hyper-V manager, it can not start too.
Every time ,it hangs at 10% of the process, and then it shows error. But no detail reson for the failure.
And I checked event viewer for Hyper-V-VMMS, it shows  just like below, and no usefull information.

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Microsoft-Windows-Hyper-V-VMMS" Guid="{6066f867-7ca1-4418-85fd-36e3f9c0600c}" /> 
  <EventID>15130</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2019-07-31T08:15:07.884966000Z" /> 
  <EventRecordID>769</EventRecordID> 
  <Correlation ActivityID="{3e205943-0904-40fe-8ccd-6d032a4ca3ac}" /> 
  <Execution ProcessID="5508" ThreadID="11496" /> 
  <Channel>Microsoft-Windows-Hyper-V-VMMS-Admin</Channel> 
  <Computer>PVGN56603291A.apj.global.corp.sap</Computer> 
  <Security UserID="S-1-5-18" /> 
  </System>
- <UserData>
- <VmlEventLog xmlns="http://www.microsoft.com/Windows/Virtualization/Events">
  <VmName>cat</VmName> 
  <VmId>2D519358-FC2D-46C3-980B-7A6906CE4A5D</VmId> 
  </VmlEventLog>
  </UserData>
  </Event>
