### ISSUE TITLE
Out of memory - docker crashes on first startup after updating docker.

### ISSUE THREAD

**Issue by AartBluestoke** [docker/for-win#4362]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID:
9CC60561-BA14-4D3F-84FC-80160F404430/20190801063149
### Expected behavior
Docker starts after upgrade without needing a reboot
### Actual behavior
Docker closed, installed the upgrade, then went 'oops' when trying to start with the attached diagnostic. No attempt to start any containers involved, just starting docker itself crashed.
### Information
  - Is it reproducible?
    As i have only seen this when starting the service some time after windows had been running, my guess is it might be due to <8gb of ram free on the machine (i have docker using 6)
  - Is the problem new?
This is not the first time i have seen this failure mechanism.
  - Did the problem appear with an update?
  - Windows Version:
windows 10.
  - Docker Desktop Version:
latest stable as of Today (i triggered this with the request to update)

### Steps to reproduce the behavior
Click on "yes i want to update", wait for install, try to start docker.

(the funny wording for the title is to try to differentiate what is crashing, and when it is crashing - there are other people talking about persistent crashes, or crashes after installing a windows update)

**Comment by mikeparker** [comment]
```
[16:31:47.716][HyperV            ][Error  ] Unable to start: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'DockerDesktopVM' failed to start.
Unable to allocate 6144 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA).
'DockerDesktopVM' failed to start. (Virtual machine ID CEDE51F7-A009-4D62-B849-53348F56C331)
'DockerDesktopVM' is unable to allocate 6144 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA). (Virtual machine ID CEDE51F7-A009-4D62-B849-53348F56C331)
```

**Comment by mikeparker** [comment]
Can you confirm if you have used WSL 2 at all?

**Comment by AartBluestoke** [comment]
(after googling for how to check this:) WSL isn't enabled
> docker context ls
NAME                DESCRIPTION                               DOCKER ENDPOINT                  ...
default *           Current DOCKER_HOST based configuration   npipe:////./pipe/docker_engine

**Comment by mikeparker** [comment]
Ok, thanks. I think this is purely just not having enough memory. Like you said:

> my guess is it might be due to <8gb of ram free on the machine (i have docker using 6)
> This is not the first time i have seen this failure mechanism.

We are releasing a patch very soon which will make the Out of Memory error much clearer to users so at least it will be obvious what the problem is.

My theory is that when you closed Docker Desktop to install the new version, either:
(a) other programs started allocating memory and then there was not the required 6GB free to run Docker Desktop again
(b) The new version of Docker Desktop requires slightly more memory which pushed your computer over the limit

Either way there are really only 2 options:
1. Free up more memory
2. Reduce the amount of memory allocated to the Docker Desktop VM

I will continue to monitor the bug reports about out of memory errors after the next patch.

**Comment by richdevboston** [comment]
This is NOT a stale issue.  This happens to me every time I try to start Docker now.  

"Resetting" DockerDesktop to Factory Settings does not help (see error messages below)

I have 32 GB RAM installed in a Windows 10 (Build v10.0.18363 Build 18363) on Dell Precision 7530 laptop hardware.   I am NOT using Windows 10 WSL.  

This is what I get when trying to run Docker Desktop with the latest available download kit:  

Docker.Core.DockerException:
Docker.Core.Backend.BackendDestroyException:
Unable to start Hyper-V VM: 'DockerDesktopVM' failed to start.

Unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA).

'DockerDesktopVM' failed to start. (Virtual machine ID 6C60E2ED-5F89-433A-B932-32D715F52FDA)

'DockerDesktopVM' is unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA). (Virtual machine ID 6C60E2ED-5F89-433A-B932-32D715F52FDA)
at Start-MobyLinuxVM, <No file>: line 688
at <ScriptBlock>, <No file>: line 811
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  System.Management.Automation.RuntimeException:
  Unable to start Hyper-V VM: 'DockerDesktopVM' failed to start.

Unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA).
  
  'DockerDesktopVM' failed to start. (Virtual machine ID 6C60E2ED-5F89-433A-B932-32D715F52FDA)

'DockerDesktopVM' is unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA). (Virtual machine ID 6C60E2ED-5F89-433A-B932-32D715F52FDA)
  at Start-MobyLinuxVM, <No file>: line 688
  at <ScriptBlock>, <No file>: line 811
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     'DockerDesktopVM' failed to start.

Unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA).
     
     'DockerDesktopVM' failed to start. (Virtual machine ID 6C60E2ED-5F89-433A-B932-32D715F52FDA)

'DockerDesktopVM' is unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA). (Virtual machine ID 6C60E2ED-5F89-433A-B932-32D715F52FDA)
     
         Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException:
         'DockerDesktopVM' failed to start.

Unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA).
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
            at Microsoft.Virtualization.Client.Management.VMComputerSystemBaseView.EndSetState(IVMTask setStateTask)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.<>c__DisplayClass4_0`1.<ConvertActionToFunction>b__0(T x)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
            at Microsoft.HyperV.PowerShell.VirtualMachine.ChangeState(VirtualMachineAction action, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.StartVM.ProcessOneOperand(VirtualMachine vm, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.VirtualizationCmdlet`1.ProcessOperands(IList`1 operands, IOperationWatcher operationWatcher)
         
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass30_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

#########################################################################

This is not a Hyper-V issue either because when I try to start DockerDesktopVM after starting Hyper-V in Windows 10, I get the following error from DockerDesktopVM:  

Hyper-V Manager 
An error occurred while attempting to start the 
selected virtual machine(s). 
'DockerDesktopVM' failed to start. 
Unable to allocate 2C48 MB of RAM: Insufficient system 
resources exist to complete the requested service. (Dx8D0705AA). 
'DockerDesktopVM' failed to start. (Virtual machine ID 
6C60E2ED-5F8-g 433A 8932 32D715F52FDA) 
'DockerDesktopVM' is unable to allocate 2C48 MB of RAM: 
Insufficient system resources exist to complete the requested 
service. (Dx8D0705AA). (Virtual machine ID 
6C60E2ED-5F8-g 433A 8932 32D715F52FDA)

########################################################
After the "Resetting DockerDesktop" operation I get the following error, basically the same result. 
########################################################

Docker.Core.DockerException:
Docker.Core.Backend.BackendException:
Unable to start Hyper-V VM: 'DockerDesktopVM' failed to start.

Unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA).

'DockerDesktopVM' failed to start. (Virtual machine ID 6C60E2ED-5F89-433A-B932-32D715F52FDA)

'DockerDesktopVM' is unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA). (Virtual machine ID 6C60E2ED-5F89-433A-B932-32D715F52FDA)
at Start-MobyLinuxVM, <No file>: line 688
at <ScriptBlock>, <No file>: line 811

  System.Management.Automation.RuntimeException:
  Unable to start Hyper-V VM: 'DockerDesktopVM' failed to start.

Unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA).
  
  'DockerDesktopVM' failed to start. (Virtual machine ID 6C60E2ED-5F89-433A-B932-32D715F52FDA)

'DockerDesktopVM' is unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA). (Virtual machine ID 6C60E2ED-5F89-433A-B932-32D715F52FDA)
  at Start-MobyLinuxVM, <No file>: line 688
  at <ScriptBlock>, <No file>: line 811
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.BackendNamedPipeServer.<Run>b__8_3(Object[] args)
     at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
     at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     'DockerDesktopVM' failed to start.

Unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA).
     
     'DockerDesktopVM' failed to start. (Virtual machine ID 6C60E2ED-5F89-433A-B932-32D715F52FDA)

'DockerDesktopVM' is unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA). (Virtual machine ID 6C60E2ED-5F89-433A-B932-32D715F52FDA)
     
         Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException:
         'DockerDesktopVM' failed to start.

Unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA).
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
            at Microsoft.Virtualization.Client.Management.VMComputerSystemBaseView.EndSetState(IVMTask setStateTask)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.<>c__DisplayClass4_0`1.<ConvertActionToFunction>b__0(T x)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
            at Microsoft.HyperV.PowerShell.VirtualMachine.ChangeState(VirtualMachineAction action, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.StartVM.ProcessOneOperand(VirtualMachine vm, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.VirtualizationCmdlet`1.ProcessOperands(IList`1 operands, IOperationWatcher operationWatcher)
         
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoRestartVM(Settings previousSettings)
   at Docker.Actions.<>c__DisplayClass34_0.<RestartVM>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

**Comment by AartBluestoke** [comment]
"Unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service." - try rebooting your computer and starting docker straight away. with only 2gb requested, it should be fine. If you're within 2gb of out-of-ram on startup, then you're going to be running into issues if you then start eg: visual studio.

Yes, this is something that can sometimes only be fixed with a reboot, as you need XGB of ram available as a continuous block.

Once you've seen this error once, trying again typically won't make a difference unless you've closed a bunch of programs inbetween.

You should watch out for how much ram sql server can claim for its own use.
