### ISSUE TITLE
Docker-Desktop fails to install on corrupted previous version

### ISSUE THREAD

**Issue by Sieboldianus** [docker/for-win#4373]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have not uploaded Diagnostics because install fails before

### Expected behavior
Docker Installation works

### Actual behavior
When installing Docker-Desktop, I first get:

![image](https://user-images.githubusercontent.com/13646666/62287374-07a7bb00-b45a-11e9-8c9a-fd73b813e7ab.png)

.. after hitting yes, I get the following error message:

```output
Could not find a part of the path 'C:\Program Files\Docker\Docker\installationmanifest.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
```

### Information

- Is it reproducible?

I am not sure how I got to this state. This morning I got notified that Docker-Desktop has a new version, I agreed to upgrade but the process stuck for 5 hours. I then tried to uninstall docker, but it also got stuck. I searched for ways to clean up my Docker-Desktop and completely start from scratch, I found this [post](https://forums.docker.com/t/cannot-uninstall-docker-for-windows/15661/11) and used the script to clean up. Now the install gets one step further, but stops with the error message above.

- Is the problem new?

Experienced it today the first time.

- Did the problem appear with an update?

Yes

  - Windows Version: Windows 10 Education latest
  - Docker Desktop Version: 2.1.0.0

**Comment by Sieboldianus** [comment]
I solved my issue with installation by following [this official advice](https://success.docker.com/article/dockerforwin-install-fails-on-installationmanifestjson)

However, the original issue that Docker gets stuck on update still remains - but I guess due to the limited information I have it cannot easily be reproduced. Therefore, please feel free to close this.

**Comment by mikeparker** [comment]
This may be an issue with an old installer and hence we're unable to fix it. I suspect our latest uninstaller won't know how to uninstall every single previous version and we rely on your current uninstaller to do the job, and if that has a bug there's not much we can do. I'll find out if we can solve this by triggering the latest uninstaller on upgrade rather than the old one

**Comment by FranklinYu** [comment]
My issue looks identical to this. It was caused by #1172. Solution is in [this article](https://success.docker.com/article/dockerforwin-install-fails-on-installationmanifestjson):

> There is a leftover registry key from an old uninstall pointing to a folder that for whatever reason no longer exists. It needs to be removed before the installer can proceed.
>
> 1. Kill the installer process if it's still running.
> 1. Run Regedit.
> 1. Run a quick backup of the registry by selecting File > Export (It is recommended that you set the export range to All.)
> 1. Navigate to `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall`
> 1. If there is a `Docker for Windows` entry, delete key and all subkeys.
> 1. Relaunch the installer, and you should no longer be prompted to update. The installer should proceed as a fresh install from this point.

**Comment by rtaylor72** [comment]
I have same problem.  The key mentioned does not exist.  Cannot install,

**Comment by rtaylor72** [comment]
The fix for me was to kill the "LightweightInstaller" process that was hung and run a cleanup script I found for the previous old Docker install.

**Comment by waseemMbutt** [comment]
> The fix for me was to kill the "LightweightInstaller" process that was hung and run a cleanup script I found for the previous old Docker install.

Running into a similar issue currently, where is this cleanup script? @rtaylor72
