### ISSUE TITLE
Proxy / Pipe error on the very first activation of WSL2 / docker

### ISSUE THREAD

**Issue by tebeco** [docker/for-win#4375]
- [x] I have tried with the latest version of my channel Edge / WSL2
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3E162870-D128-4BE3-B2E0-051948CE01E8/20190801110817

### Expected behavior
Expected to start on first run.

### Actual behavior
It happened approximatly a bit before 12h07 (i have a Message logged in WhatsApp at 12h07 right after it happenned, if it helps)

I did the diagnostic at ~13h15
here is whats the `LifeCycle Server Logs` looked like :
![image](https://user-images.githubusercontent.com/2266487/62289490-2a889e00-b45f-11e9-93c3-c388446ca9ce.png)

in the log file i can spot this (No idea if related to the error):

```
[12:03:53.828][APIRequestLogger  ][Info   ] [143342c8-fc0a-4d89-bbeb-aaeffadf3f89] GET http://localhost/docker -> 200 OK took 0ms
[12:03:53.829][APIRequestLogger  ][Info   ] [9f5bc29c-a88a-4423-b18f-927350bbcd5b] GET http://localhost/kubernetes
[12:03:53.830][APIRequestLogger  ][Info   ] [9f5bc29c-a88a-4423-b18f-927350bbcd5b] GET http://localhost/kubernetes -> 200 OK took 0ms
[12:03:54.652][APIRequestLogger  ][Info   ] [84379282-8602-4a76-8582-3a4b28368e3b] DELETE http://localhost/notifications/subscriptions
[12:03:54.652][APIRequestLogger  ][Info   ] [84379282-8602-4a76-8582-3a4b28368e3b] DELETE http://localhost/notifications/subscriptions -> 200 OK took 0ms
[12:04:01.582][SegmentApi        ][Info   ] Usage statistic: actionWSL2UILaunch
[12:04:02.012][APIRequestLogger  ][Info   ] [e49bd49f-dbf3-46c1-9349-b8bff882cf60] POST http://localhost/notifications/subscriptions
[12:04:02.012][NotificationsClient][Error  ] Client: EXCEPTION:System.TimeoutException: The operation has timed out.
   at System.IO.Pipes.NamedPipeClientStream.ConnectInternal(Int32 timeout, CancellationToken cancellationToken, Int32 startTime)
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.NamedPipe.NamedPipeDialer.<DialAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.Client.DialMessageHandler.<SendAsync>d__5.MoveNext()
[12:04:02.013][NotificationsRegistrationController][Error  ] Could not connect to requested named pipe: \\.\pipe\dockerFrontendApiServer. Is the server listening? System.TimeoutException: The operation has timed out.
[12:04:02.013][APIRequestLogger  ][Info   ] [e49bd49f-dbf3-46c1-9349-b8bff882cf60] POST http://localhost/notifications/subscriptions -> 400 BadRequest took 1ms
```

The very first activation of the `docker context` to activate and set it as `wsl` failed with an error about `proxy` and `pipe` being (all ?) busy.
That appeared only in the `Win10` Toast as an error and could not remember it
  - Windows Version: `Win10 insider fast build 18932`
  - Docker Desktop Version: `Edge Technical preview Wsl2` `2.1.0.0 (36883)`

### Steps to reproduce the behavior
It works when i clicked again `Start` ...
I have no idea how to reproduce this one, maybe on next reboot or restart ... can't tell

**Comment by tebeco** [comment]
WSL architecture changed a lot, closing 
will re-open if needed
