### ISSUE TITLE
AuthorizationManager check failed. PowerShell execution policy prevents Docker Desktop 2.1 starting

### ISSUE THREAD

**Issue by petedzappulla** [docker/for-win#4376]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 524EC744-367D-41DD-AA66-FD224CF54609/20190801114152

### Expected behavior
Upgrade should work

### Actual behavior
Docker desktop won't start anymore. Receive an error that says:
Unable to stop
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

Received a notification of an update and accepted the dialog. Update installed, and docker desktop no longer starts. I uninstalled docker desktop completely and reinstalled, but still get the same error:

Unable to stop
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by synergensoftware** [comment]
I am seeing something very similar...Docker Desktop was working beautifully yesterday morning, then I accepted the upgrade and I've been dead in the water ever since.  The upgrade installed (so it said), but starting Docker Desktop gives the error below.  I've tried the 'reset to factory defaults' and uploaded the crash report.  I've attached diagnostics zip file here as well.

[20190801141353.zip](https://github.com/docker/for-win/files/3457215/20190801141353.zip)

Unable to create
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by mikeparker** [comment]
Relevant logs
```
[07:41:48.233][HyperV            ][Error  ] Unable to stop: System.Management.Automation.CommandNotFoundException: The term 'Stop-MobyLinuxVM' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
```

**Comment by mikeparker** [comment]
@synergensoftware can you upload a diagnostic ID / logs? Its not clear that `Unable to stop` and `Unable to start` are necessarily the same bug and I want to be sure.

**Comment by mikeparker** [comment]
@petedzappulla do you have a restricted execution policy, perhaps enforced by your IT department? (You can check with running `Get-ExecutionPolicy -List` in powershell)

**Comment by petedzappulla** [comment]
In fact, I do... Looks like I've got a MachinePolicy of "AllSigned"

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       AllSigned
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine    Unrestricted

I tried the following command:
Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope MachinePolicy

but received an error (as I completely expected):
Cannot set execution policy. Execution policies at the MachinePolicy or UserPolicy scopes must
be set through Group Policy

This level of access didn't seem to be necessary with the last version of Docker Desktop I had (2.0.0.3). Is there a way to get the newest version running without having to jump through hoops with my IT department to change my MachinePolicy?

**Comment by synergensoftware** [comment]
Hi, Mike,

I ended up uninstalling and working with our infosec team to re-install.  Docker runs afoul of the security policies, so it is a pain, but I had no choice.

All is well on the older version.

Thanks

Paul


Paul Scivetti
Chief IDEA Officer, Synergen, Inc.
22334 E Via Del Verde, Queen Creek, AZ 85142
Direct: 480-999-0158

"We are constantly surrounded by incredible opportunities,
brilliantly disguised as impossible problems."

________________________________

**Comment by mikeparker** [comment]
> Looks like I've got a MachinePolicy of "AllSigned"

Ok, at least we know what the issue is, so that's the good news.

> This level of access didn't seem to be necessary with the last version of Docker Desktop I had (2.0.0.3). Is there a way to get the newest version running without having to jump through hoops with my IT department to change my MachinePolicy?

This is because our latest version we are executing the PowerShell VM modules "properly" through the execution engine rather than piping commands through from C#. Unfortunately this means we are now being checked with the execution policy. We have a script signing process which I'm investigating, so either we'll fix that so all scripts are properly signed or we'll have to roll back to our previous method. 

For now I can't think of a way to get the latest version working under a restricted execution policy. My advice would be to roll back to the last stable version -> https://download.docker.com/win/stable/31259/Docker%20for%20Windows%20Installer.exe

**Comment by souledge0** [comment]
@mikeparker I rolled back to last stable version but it still crashed, and I found policy errors in the log.

EA582271-57C7-428E-B9D2-0B9C904EBB1B/20190802110011

[log.txt](https://github.com/docker/for-win/files/3461831/log.txt)

**Comment by mikeparker** [comment]
@souledge0 there are no policy errors in your log after you rolled back, those are from the previous version. Your new error is 
```
[11:00:11.134][NamedPipeServer][Error  ] Unable to execute Start: Value cannot be null.
Parameter name: network    at System.Net.IPNetwork.InternalParse(Boolean tryParse, String network, IPNetwork& ipnetwork)
   at Docker.Core.IpHelper.ConvertCIDR(String cidr) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\IpHelper.cs:line 33
   at Docker.Backend.HyperV.Create(Settings settings) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 109
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 117
[11:00:11.142][NamedPipeClient][Error  ] Unable to send Start: Value cannot be null.
```
Can you check your settings.json for the `hypervCIDR` value please?

**Comment by sean-gay-work** [comment]
I ran into this same issue and was able to get Docker running again. Open your Services manager and restart the Hyper-V Virtual Machine Management service, then restart the Docker service and then start Docker desktop.

**Comment by mikeparker** [comment]
@souledge0 we've found a better workaround: 
> Open PowerShell and run Import-Module "C:\Program Files\Docker\Docker\resources\MobyLinux" then when prompted enter A this will install the docker cert locally.

This should allow you to use 2.1.0.0.

**Comment by souledge0** [comment]
@mikeparker great, will try this right now.

**Comment by souledge0** [comment]
@mikeparker I didn't find MobyLinux within "C:\Program Files\Docker\Docker\resources\"  of 2.0.0.3
I assume I need to run it after upgrading to 2.1.0.0?

**Comment by mikeparker** [comment]
@souledge0 yes thats the workaround to get 2.1 working.

**Comment by petedzappulla** [comment]
Release 2.1.0.1 works beautifully! Awesome turn-around time guys; thanks!
