### ISSUE TITLE
Docker fails on startup with WSL2 - Out of Memory

### ISSUE THREAD

**Issue by planetf1** [docker/for-win#4406]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker desktop starts normally

### Actual behavior
Docker desktop throws an error after startup on WSL2:

Unable to start
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

Diagnostics id is B9AB2DE9-84C6-4BB6-8906-153AB9809656/20190803155740

**Comment by planetf1** [comment]
Windows version: 10 Build 18950 (insider fast)
docker desktop version: 2.1.0.0 (36883)

Error happens every time. Note computer is MS surface - only 4GB ram

**Comment by stephen-turner** [comment]
Any idea, @simonferquel?

**Comment by simonferquel** [comment]
This is a stacktrace from the classic VM startup, not the swl2 UI.

**Comment by johnsnowderomania** [comment]
Version: 2.1.0.0 (36874)
Channel: stable
Sha1: 4afc8ac703034fbe00b41efad6c1b77cf2335ee0
Started on: 2019/08/05 18:19:47.784
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1809
Build: 17763
BuildLabName: 17763.1.amd64fre.rs5_release.180914-1434
File: C:\Users\mihai.leu\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[18:19:47.955][GUI               ][Info   ] Starting...
[18:19:47.984][ComponentVersions ][Info   ] Edition community
[18:19:48.085][ComponentVersions ][Info   ] Edition community
[18:19:48.687][AppMigrator       ][Info   ] Current version: 5. Latest version: 5
[18:19:48.839][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[18:19:48.843][SegmentApi        ][Info   ] Usage statistic: Identify
[18:19:48.954][SegmentApi        ][Info   ] Usage statistic: appLaunched
[18:19:49.442][ApplicationTemplatesTracking][Info   ] Cannot list templates
[18:19:49.444][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[18:19:49.446][SegmentApi        ][Info   ] Usage statistic: heartbeat
[18:19:49.591][NamedPipeClient   ][Info   ] Sending app/version()...
[18:19:49.599][NamedPipeClient   ][Info   ] Received response for app/version
[18:19:49.600][NamedPipeClient   ][Info   ] Sending app/migrate()...
[18:19:49.602][NamedPipeClient   ][Info   ] Received response for app/migrate
[18:19:49.598][NamedPipeServer   ][Info   ] app/version done in 00:00:00.0009971.
[18:19:49.601][NamedPipeServer   ][Info   ] app/migrate()
[18:19:49.601][NamedPipeServer   ][Info   ] app/migrate done in 00:00:00.
[18:19:49.620][NamedPipeClient   ][Info   ] Sending app/version()...
[18:19:49.622][NamedPipeClient   ][Info   ] Received response for app/version
[18:19:49.621][NamedPipeServer   ][Info   ] app/version()
[18:19:49.624][NamedPipeClient   ][Info   ] Sending version-packs/enable(community, Docker.Core.Settings)...
[18:19:49.621][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[18:19:49.629][NamedPipeClient   ][Info   ] Received response for version-packs/enable
[18:19:49.628][NamedPipeServer   ][Info   ] version-packs/enable(community, Docker.Core.Settings)
[18:19:49.629][NamedPipeServer   ][Info   ] version-packs/enable done in 00:00:00.0010033.
[18:19:49.644][NamedPipeClient   ][Info   ] Sending app/version()...
[18:19:49.645][NamedPipeClient   ][Info   ] Received response for app/version
[18:19:49.645][NamedPipeClient   ][Info   ] Sending engine/start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions, )...
[18:19:49.644][NamedPipeServer   ][Info   ] app/version()
[18:19:49.644][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[18:19:49.651][NamedPipeServer   ][Info   ] engine/start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions, )
[18:19:49.653][Linux             ][Info   ] Setting container engine status to Starting
[18:19:49.743][PowerMode         ][Info   ] Stop
[18:19:49.743][HyperV            ][Info   ] Stop
[18:19:49.743][PowerShell        ][Info   ] Run script with parameters: -Verbose True -ErrorAction Stop
[18:19:49.761][PowerShell        ][Error  ] Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of AllSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
[18:19:49.782][PowerShell        ][Error  ] Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of AllSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
[18:19:49.839][PowerShell        ][Error  ] AuthorizationManager check failed.
[18:19:49.882][HyperV            ][Error  ] Unable to stop: System.Management.Automation.CommandNotFoundException: The term 'Stop-MobyLinuxVM' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunCommandAsync>d__11.MoveNext()
[18:19:49.882][Moby              ][Info   ] Stop
[18:19:49.890][Linux             ][Error  ] Failed to start: Unable to stop. Let's retry
[18:19:49.890][Linux             ][Info   ] Setting container engine status to Starting
[18:19:49.914][HyperV            ][Info   ] Hyper-V is running
[18:19:49.914][PowerMode         ][Info   ] Stop
[18:19:49.914][HyperV            ][Info   ] Stop
[18:19:49.914][PowerShell        ][Info   ] Run script with parameters: -Verbose True -ErrorAction Stop
[18:19:49.933][PowerShell        ][Error  ] Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of AllSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
[18:19:49.950][PowerShell        ][Error  ] Windows PowerShell updated your execution policy successfully, but the setting is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its current effective execution policy of AllSigned. Type "Get-ExecutionPolicy -List" to view your execution policy settings. For more information please see "Get-Help Set-ExecutionPolicy".
[18:19:49.997][PowerShell        ][Error  ] AuthorizationManager check failed.
[18:19:50.028][HyperV            ][Error  ] Unable to stop: System.Management.Automation.CommandNotFoundException: The term 'Stop-MobyLinuxVM' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunCommandAsync>d__11.MoveNext()
[18:19:50.042][NamedPipeClient   ][Error  ] Unable to send engine/start: Unable to stop
[18:19:50.029][Moby              ][Info   ] Stop
[18:19:50.045][Notifications     ][Error  ] Unable to stop
[18:19:50.035][Linux             ][Info   ] Setting container engine status to FailedToStart
[18:19:50.036][NamedPipeServer   ][Error  ] Unable to execute engine/start: Unable to stop    at Docker.Backend.HyperV.HandleException(String action, Exception ex)
   at Docker.Backend.HyperV.RunScript(String action, String command, Dictionary`2 parameters, PowerShellConfiguration config)
   at Docker.Backend.HyperV.Stop()
   at Docker.Backend.ContainerEngine.Linux.DoStop()
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
[18:19:53.873][NamedPipeClient   ][Info   ] Sending app/version()...
[18:19:53.893][NamedPipeClient   ][Info   ] Received response for app/version
[18:19:53.893][NamedPipeClient   ][Info   ] Sending diagnostics/gather()...
[18:19:53.891][NamedPipeServer   ][Info   ] app/version()
[18:19:53.891][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[18:19:53.898][NamedPipeServer   ][Info   ] diagnostics/gather()
[18:20:00.527][SegmentApi        ][Info   ] Usage statistic: actionMenuSettings
[18:20:00.698][NamedPipeClient   ][Info   ] Sending app/version()...
[18:20:00.699][NamedPipeClient   ][Info   ] Received response for app/version
[18:20:00.699][NamedPipeClient   ][Info   ] Sending disk/get-size()...
[18:20:00.701][NamedPipeClient   ][Info   ] Sending app/version()...
[18:20:00.699][NamedPipeServer   ][Info   ] app/version()
[18:20:00.704][NamedPipeClient   ][Info   ] Received response for disk/get-size
[18:20:00.705][NamedPipeClient   ][Info   ] Received response for app/version
[18:20:00.706][NamedPipeClient   ][Info   ] Sending disk/get-size()...
[18:20:00.699][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[18:20:00.700][NamedPipeServer   ][Info   ] disk/get-size()
[18:20:00.709][NamedPipeClient   ][Info   ] Received response for disk/get-size
[18:20:00.710][NamedPipeClient   ][Info   ] Sending app/version()...
[18:20:00.710][NamedPipeClient   ][Info   ] Sending app/version()...
[18:20:00.703][NamedPipeServer   ][Info   ] disk/get-size done in 00:00:00.0030032.
[18:20:00.705][NamedPipeServer   ][Info   ] app/version()
[18:20:00.705][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[18:20:00.708][NamedPipeServer   ][Info   ] disk/get-size()
[18:20:00.708][NamedPipeServer   ][Info   ] disk/get-size done in 00:00:00.
[18:20:01.533][NamedPipeClient   ][Info   ] Received response for app/version
[18:20:01.534][NamedPipeClient   ][Info   ] Sending disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)...
[18:20:01.536][NamedPipeClient   ][Info   ] Received response for app/version
[18:20:01.536][NamedPipeClient   ][Info   ] Sending disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)...
[18:20:01.536][NamedPipeClient   ][Info   ] Received response for disk/get-size
[18:20:01.533][NamedPipeServer   ][Info   ] app/version()
[18:20:01.538][NamedPipeClient   ][Info   ] Sending app/version()...
[18:20:01.538][NamedPipeClient   ][Info   ] Received response for disk/get-size
[18:20:01.539][NamedPipeClient   ][Info   ] Received response for app/version
[18:20:01.539][NamedPipeClient   ][Info   ] Sending disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)...
[18:20:01.533][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[18:20:01.541][NamedPipeClient   ][Info   ] Received response for disk/get-size
[18:20:01.535][NamedPipeServer   ][Info   ] disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)
[18:20:01.536][NamedPipeServer   ][Info   ] app/version()
[18:20:01.536][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[18:20:01.536][NamedPipeServer   ][Info   ] disk/get-size done in 00:00:00.0009971.
[18:20:01.537][NamedPipeServer   ][Info   ] disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)
[18:20:01.538][NamedPipeServer   ][Info   ] disk/get-size done in 00:00:00.0010007.
[18:20:01.539][NamedPipeServer   ][Info   ] app/version()
[18:20:01.539][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[18:20:01.540][NamedPipeServer   ][Info   ] disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)
[18:20:01.540][NamedPipeServer   ][Info   ] disk/get-size done in 00:00:00.
[18:20:29.105][ErrorReportWindow ][Info   ] Open logs

**Comment by simonferquel** [comment]
@mikeparker this is not related to the WSL2 code. The trace indicates a startup failure of the Linuxkit VM.

@planetf1 @johnsnowderomania can you try to open the Tech Preview menu entry, even if docker says it can't start ?

**Comment by mikeparker** [comment]
OP logs: 
```
Not enough memory in the system to start the virtual machine DockerDesktopVM.

Could not initialize memory: Not enough memory resources are available to complete this operation. (0x8007000E).

'DockerDesktopVM' failed to start. (Virtual machine ID 8F71DA49-D046-4637-81EC-0DCFF1B4879C)

Not enough memory in the system to start the virtual machine DockerDesktopVM with ram size 2048 megabytes. (Virtual machine ID 8F71DA49-D046-4637-81EC-0DCFF1B4879C)

'DockerDesktopVM' could not initialize memory: Not enough memory resources are available to complete this operation. (0x8007000E). (Virtual machine ID 8F71DA49-D046-4637-81EC-0DCFF1B4879C)
```

**Comment by mikeparker** [comment]
Probably same issue as https://github.com/docker/for-win/issues/4348, https://github.com/docker/for-win/issues/4362, https://github.com/docker/for-win/issues/4368

**Comment by planetf1** [comment]
With the latest update, I no longer see this crash, instead I get a proper dialog reporting 'Not enough memory to start Docker Desktop'

The system in question is no doubt constrained - a 4GB surface (travel companion). 

The standard docker config is set for 2GB memory and cannot be reduced (via the UI)

After the  start fails I can click on the wsl2 tech preview, and start the docker daemon, which appears to work correctly. This is good news - I was hoping this new approach would work better on a constrained system

It begs the question as to whether it's possible to configure the client to ONLY start the preview, and NOT the regular docker desktop. Also whether k8s is deployable (automatically) into the wsl2 environment (though this could be a challenge in a constrained environment)

**Comment by stephen-turner** [comment]
Right now in the preview, we launch both approaches side by side so that you can switch in and out of it. However, our current plan is that once it reaches production, you won't get the old-style VM if your system can do WSL 2. That will only change if we find some unexpected reason why the old approach would be preferable for a chunk of users.
