### ISSUE TITLE
Docker 'Switch to Linux container fails to start 

### ISSUE THREAD

**Issue by telalwar** [docker/for-win#4452]
- [x] I have tried with the latest version of my channel (Stable or Edge)
- [x] I have uploaded Diagnostics
- Diagnostics ID: FCB29FE6-A7B0-494E-BA6F-0B8064DC84B6/20190806151334

- Os Name: Windows 10 pro
- Windows Version: 10.0.18362

- Docker Desktop Version: 2.1.0.0(36874) Community

### Expected behavior
Docker latest version should work on windows 10 pro

### Actual behavior
Happening when trying to `Switch to Linux containers`

Unable to stop
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.<>c__DisplayClass36_0.<SwitchDaemon>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Error message in logfile:**
[11:13:13.121][PowerShell ][Error  ] The required module 'Hyper-V' is not loaded. Load the module or remove the module from 'RequiredModules' in the file 'C:\Program Files\Docker\Docker\Resources\MobyLinux\MobyLinux.psd1'.
11:13:13.196][HyperV            ][Error  ] Unable to destroy: System.Management.Automation.CommandNotFoundException: The term 'Remove-MobyLinux' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunCommandAsync>d__11.MoveNext()

### Steps to reproduce the behavior
  1. Install the latest version(2.1.0.0) of docker 
  2. Start the Docker for windows desktop
  3. Switch to Linux Containers 

I previously had Docker installed via Docker toolbox. I uninstalled it, removed related Environment variables. 

 Made sure Hyper-v is enabled and restarted the system

**Comment by plantusd** [comment]
Similar issue

<pre>OS: Windows 10 Pro
Edition: Professional
Id: 1903
Build: 18362
BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
File: C:\Users\dplantus\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[19:02:22.055][GUI               ][Info   ] Starting...
[19:02:22.062][ComponentVersions ][Info   ] Edition community
[19:02:22.109][ComponentVersions ][Info   ] Edition community
[19:02:22.240][PowerShell        ][Info   ] Runspace Pool created (Min=1, Max=2)
[19:02:22.394][AppMigrator       ][Info   ] Current version: 5. Latest version: 5
[19:02:22.394][GUI               ][Error  ] An instance is already running. Exiting.
[19:02:22.855][PowerMode         ][Info   ] Stop
[19:02:22.857][HyperV            ][Info   ] Stop
[19:02:22.857][PowerShell        ][Info   ] Run script with parameters: -Verbose True -ErrorAction Stop
[19:02:24.993][HyperV            ][Error  ] Unable to stop: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunCommandAsync>d__11.MoveNext()
[19:02:24.993][Moby              ][Info   ] Stop
[19:02:25.000][Linux             ][Error  ] Failed to start: Unable to stop. Let's retry
[19:02:25.000][Linux             ][Info   ] Setting container engine status to Starting
[19:02:25.031][Installer         ][Info   ] Checking for features: *Hyper-V*, Containers
[19:02:25.031][PowerShell        ][Info   ] Run script...
[19:02:26.335][PowerShell        ][Info   ] Run script...
[19:02:27.306][PowerShell        ][Info   ] Run script...
[19:02:28.265][PowerShell        ][Info   ] Run script...
[19:02:29.216][Installer         ][Info   ] Features installed
[19:02:29.226][HyperV            ][Info   ] Hyper-V is running
[19:02:29.226][PowerMode         ][Info   ] Stop
[19:02:29.226][HyperV            ][Info   ] Stop
[19:02:29.226][PowerShell        ][Info   ] Run script with parameters: -Verbose True -ErrorAction Stop
[19:02:29.246][HyperV            ][Error  ] Unable to stop: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunCommandAsync>d__11.MoveNext()
[19:02:29.246][Moby              ][Info   ] Stop
[19:02:29.246][Linux             ][Info   ] Setting container engine status to FailedToStart
[19:02:29.254][NamedPipeServer   ][Error  ] Unable to execute engine/start: Unable to stop    at Docker.Backend.HyperV.HandleException(String action, Exception ex)
   at Docker.Backend.HyperV.RunScript(String action, String command, Dictionary`2 parameters, PowerShellConfiguration config)
   at Docker.Backend.HyperV.Stop()
   at Docker.Backend.ContainerEngine.Linux.DoStop()
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
[19:02:29.459][NamedPipeClient   ][Error  ] Unable to send engine/start: Unable to stop
[19:02:29.459][Notifications     ][Error  ] Unable to stop
[19:02:44.465][NamedPipeClient   ][Info   ] Sending app/version()...
[19:02:44.465][NamedPipeClient   ][Info   ] Received response for app/version
[19:02:44.465][NamedPipeClient   ][Info   ] Sending diagnostics/gather()...
[19:02:44.465][NamedPipeServer   ][Info   ] app/version()
[19:02:44.465][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[19:02:44.465][NamedPipeServer   ][Info   ] diagnostics/gather()
[19:03:52.483][ErrorReportWindow ][Info   ] Open logs</pre>

**Comment by mikeparker** [comment]
```
Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.
```
I guess you already know this but your Hyper-V install is broken.

**Comment by telalwar** [comment]
@mikeparker Yes , but I did not touch my Hyper-V  installation when I

**Comment by mikeparker** [comment]
Sorry, my previous comment was for plantusd. I'm still looking at yours. It looks like the Hyper-V powershell module is not installed in windows features but looking at your diagnostic it says that it is installed... 
Will continue to look.

**Comment by telalwar** [comment]
@mikeparker ah ok, I missed the tag. Ok here is how we solved it.

1. I updated my system variable `PsModulePath` with the correct Hyper-V path. In my case, the Hyper-V module was present at `C:\Windows\System32\WindowsPowerShell\v1.0\Modules`

2. Restarted the machine

and the issue was fixed. 

Thank you for looking into this issue!

**Comment by mikeparker** [comment]
Great! I'll note that fix for future.

**Comment by malkia** [comment]
FYI - I've found that my PsModulePath was broken too: ```C:\Windows\System32>echo %PsModulePath%                                                                                                                                                                                                                                        ;C:\Users\dstanev\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\PowerShell      ```

**Comment by malkia** [comment]
More Details: I've found that I had both PsModulePath as system var, and Env var.

The System Variable was correct, it was: ```%ProgramFiles%\WindowsPowerShell\Modules; %SystemRoot%\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\;C:\Program Files\Microsoft Message Analyzer\PowerShell\```

but then had one User Variable from Google which was the value I posted above^^^

**Comment by mikeparker** [comment]
Interesting - did installing the google cloud sdk create that environment variable? It'd be good to know if installing their SDK breaks docker desktop.

**Comment by malkia** [comment]
Seems like it - https://github.com/GoogleCloudPlatform/google-cloud-powershell/issues/611

**Comment by mikeparker** [comment]
@plantusd any chance you can upload a diagnostic for your error? I am tracking some similar errors and want to check what happened on your end.

**Comment by ndaadaa** [comment]
Hi, can you post procedure to edit PsModulePath ?
