### ISSUE TITLE
Docker 1.13 breaks docker permanently for all versions?

### ISSUE THREAD

**Issue by mmaguigan** [docker/for-win#446]
### Expected behavior
Docker should start.
### Actual behavior
Docker fails to create and start MobyLinuxVM.
### Information
I was operating on the Windows beta channel and received an update to 1.13 today. After the update I was repeatedly greeted with this message:

```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to change state.
at Start-MobyLinuxVM, <No file>: line 280
at <ScriptBlock>, <No file>: line 375
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

I have since tried uninstalling docker, installing the stable channel (which did not help), and then switching back to the beta channel (which still did not help). I am currently unable to use Docker for Windows.

Diagnostic code: F349369D-7646-4A5F-A691-0445B1F6C4B2/2017-01-30_11-44-59

### Steps to reproduce the behavior

  1. Update docker?

**Comment by trimox** [comment]
+1 - This needs to get resolved

**Comment by rneugeba** [comment]
@trimox could you provide a diagnostics ID?

@mmaguigan there is an error in the logs saying that the Hyper-V VM could not be started:
```
'MobyLinuxVM' failed to start.
```
not very helpful...
But I also see remnants of a VMware installation in the diagnostics. Did you have VMware installed? Could you try completely un-installing it? Hyper-V and VMware can't be used together on the same host and we have seen many issues where Hyper-V VMs can't be started when parts of VMware (or VirtualBox are still running).
It would also be useful to get the output of `get-computerinfo` executed in an elevated powershell.

**Comment by mmaguigan** [comment]
@rneugeba, I have not ever had VMWare installed on this computer. Perhaps it is detecting VMWare Horizons Client which is used to connect to VDI instances in our ESXi cluster - it should not be interfering with virtualization as I have Hyper-V enabled and no other hypervisor should be able to operate.

I agree that the logs were not helpful. I am afraid I must censor some of my computer information for security reasons, rest assured my censorship has been limited.

```
[20170130 15:36:14.816] [...\system32]> Get-ComputerInfo


WindowsBuildLabEx                                       : 14393.693.amd64fre.rs1_release.161220-1747
WindowsCurrentVersion                                   : 6.3
WindowsEditionId                                        : Enterprise
WindowsInstallationType                                 : Client
WindowsInstallDateFromRegistry                          : 9/27/2016 3:24:16 PM
WindowsProductId                                        : PRODUCTIDCENSORED
WindowsProductName                                      : Windows 10 Enterprise
WindowsRegisteredOrganization                           :
WindowsRegisteredOwner                                  : Windows User
WindowsSystemRoot                                       : C:\Windows
BiosCharacteristics                                     :
BiosBIOSVersion                                         :
BiosBuildNumber                                         :
BiosCaption                                             :
BiosCodeSet                                             :
BiosCurrentLanguage                                     :
BiosDescription                                         :
BiosEmbeddedControllerMajorVersion                      :
BiosEmbeddedControllerMinorVersion                      :
BiosFirmwareType                                        :
BiosIdentificationCode                                  :
BiosInstallableLanguages                                :
BiosInstallDate                                         :
BiosLanguageEdition                                     :
BiosListOfLanguages                                     :
BiosManufacturer                                        :
BiosName                                                :
BiosOtherTargetOS                                       :
BiosPrimaryBIOS                                         :
BiosReleaseDate                                         :
BiosSeralNumber                                         :
BiosSMBIOSBIOSVersion                                   :
BiosSMBIOSMajorVersion                                  :
BiosSMBIOSMinorVersion                                  :
BiosSMBIOSPresent                                       :
BiosSoftwareElementState                                :
BiosStatus                                              :
BiosSystemBiosMajorVersion                              :
BiosSystemBiosMinorVersion                              :
BiosTargetOperatingSystem                               :
BiosVersion                                             :
CsAdminPasswordStatus                                   :
CsAutomaticManagedPagefile                              :
CsAutomaticResetBootOption                              :
CsAutomaticResetCapability                              :
CsBootOptionOnLimit                                     :
CsBootOptionOnWatchDog                                  :
CsBootROMSupported                                      :
CsBootStatus                                            :
CsBootupState                                           :
CsCaption                                               :
CsChassisBootupState                                    :
CsChassisSKUNumber                                      :
CsCurrentTimeZone                                       :
CsDaylightInEffect                                      :
CsDescription                                           :
CsDNSHostName                                           :
CsDomain                                                :
CsDomainRole                                            :
CsEnableDaylightSavingsTime                             :
CsFrontPanelResetStatus                                 :
CsHypervisorPresent                                     :
CsInfraredSupported                                     :
CsInitialLoadInfo                                       :
CsInstallDate                                           :
CsKeyboardPasswordStatus                                :
CsLastLoadInfo                                          :
CsManufacturer                                          :
CsModel                                                 :
CsName                                                  :
CsNetworkAdapters                                       :
CsNetworkServerModeEnabled                              :
CsNumberOfLogicalProcessors                             :
CsNumberOfProcessors                                    :
CsProcessors                                            :
CsOEMStringArray                                        :
CsPartOfDomain                                          :
CsPauseAfterReset                                       :
CsPCSystemType                                          :
CsPCSystemTypeEx                                        :
CsPowerManagementCapabilities                           :
CsPowerManagementSupported                              :
CsPowerOnPasswordStatus                                 :
CsPowerState                                            :
CsPowerSupplyState                                      :
CsPrimaryOwnerContact                                   :
CsPrimaryOwnerName                                      :
CsResetCapability                                       :
CsResetCount                                            :
CsResetLimit                                            :
CsRoles                                                 :
CsStatus                                                :
CsSupportContactDescription                             :
CsSystemFamily                                          :
CsSystemSKUNumber                                       :
CsSystemType                                            :
CsThermalState                                          :
CsTotalPhysicalMemory                                   :
CsPhyicallyInstalledMemory                              :
CsUserName                                              :
CsWakeUpType                                            :
CsWorkgroup                                             :
OsName                                                  :
OsType                                                  :
OsOperatingSystemSKU                                    :
OsVersion                                               :
OsCSDVersion                                            :
OsBuildNumber                                           :
OsHotFixes                                              :
OsBootDevice                                            :
OsSystemDevice                                          :
OsSystemDirectory                                       :
OsSystemDrive                                           :
OsWindowsDirectory                                      :
OsCountryCode                                           :
OsCurrentTimeZone                                       :
OsLocaleID                                              :
OsLocale                                                :
OsLocalDateTime                                         :
OsLastBootUpTime                                        :
OsUptime                                                :
OsBuildType                                             :
OsCodeSet                                               :
OsDataExecutionPreventionAvailable                      :
OsDataExecutionPrevention32BitApplications              :
OsDataExecutionPreventionDrivers                        :
OsDataExecutionPreventionSupportPolicy                  :
OsDebug                                                 :
OsDistributed                                           :
OsEncryptionLevel                                       :
OsForegroundApplicationBoost                            :
OsTotalVisibleMemorySize                                :
OsFreePhysicalMemory                                    :
OsTotalVirtualMemorySize                                :
OsFreeVirtualMemory                                     :
OsInUseVirtualMemory                                    :
OsTotalSwapSpaceSize                                    :
OsSizeStoredInPagingFiles                               :
OsFreeSpaceInPagingFiles                                :
OsPagingFiles                                           :
OsHardwareAbstractionLayer                              :
OsInstallDate                                           :
OsManufacturer                                          :
OsMaxNumberOfProcesses                                  :
OsMaxProcessMemorySize                                  :
OsMuiLanguages                                          :
OsNumberOfLicensedUsers                                 :
OsNumberOfProcesses                                     :
OsNumberOfUsers                                         :
OsOrganization                                          :
OsArchitecture                                          :
OsLanguage                                              :
OsProductSuites                                         :
OsOtherTypeDescription                                  :
OsPAEEnabled                                            :
OsPortableOperatingSystem                               :
OsPrimary                                               :
OsProductType                                           :
OsRegisteredUser                                        :
OsSerialNumber                                          :
OsServicePackMajorVersion                               :
OsServicePackMinorVersion                               :
OsStatus                                                :
OsSuites                                                :
OsServerLevel                                           :
KeyboardLayout                                          :
TimeZone                                                : (UTC-05:00) Eastern Time (US & Canada)
LogonServer                                             : \\HOSTNAMECENSORED
PowerPlatformRole                                       : Desktop
HyperVisorPresent                                       :
HyperVRequirementDataExecutionPreventionAvailable       :
HyperVRequirementSecondLevelAddressTranslation          :
HyperVRequirementVirtualizationFirmwareEnabled          :
HyperVRequirementVMMonitorModeExtensions                :
DeviceGuardSmartStatus                                  : Off
DeviceGuardRequiredSecurityProperties                   :
DeviceGuardAvailableSecurityProperties                  :
DeviceGuardSecurityServicesConfigured                   :
DeviceGuardSecurityServicesRunning                      :
DeviceGuardCodeIntegrityPolicyEnforcementStatus         :
DeviceGuardUserModeCodeIntegrityPolicyEnforcementStatus :
```

I will go ahead and remove Horizon from my system and see if it did indeed affect it.

**Comment by mmaguigan** [comment]
No change with Horizon Viewer removed.

```
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to change state.
at Start-MobyLinuxVM, <No file>: line 280
at <ScriptBlock>, <No file>: line 375
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

Diagnostic Code: **F349369D-7646-4A5F-A691-0445B1F6C4B2/2017-01-30_15-46-27**
[log2.txt](https://github.com/docker/for-win/files/740251/log2.txt)

**Comment by mmaguigan** [comment]
can we remove the needs more information label?

**Comment by akadrac** [comment]
Remove the DockerNAT virtual switch from hyper-v and then try the re-installation.  Looks very similar to an issue I had when upgrading on the last stable version.

**Comment by DannyAllegrezza** [comment]
Having the same problem on my machine. Ironically, I have used Docker Toolbox on my machine but cannot seem to get the new version of Docker to work. Same errors. I'm well aware that all hints of Virtual Box need to be removed, so I have taken the necessary steps to do so (minus formatting the drive and reinstalling Win 10).

Hoping some useful info will come out of this thread.

I've tried:

* Removing Docker
* Disabling Hyper-V (via Powershell and the Windows UI)
* Manually removing old .docker folder files
* Manually enable Hyper-V
* Re-install Docker

**Comment by msadikkose** [comment]
I have exactly same problem. I just tried to install my new windows 10 pc.

**Comment by rneugeba** [comment]
@msadikkose @DannyAllegrezza could you please upload diagnostics and share the ID here.
thanks

**Comment by msadikkose** [comment]
This is diagnostic Id of my log  D1225885-D86F-40A3-8E8A-AA6357C4B1CB/2017-02-05_18-14-23

**Comment by mmaguigan** [comment]
@akadrac, I do not have a DockerNAT in Hyper-V.

**Comment by DannyAllegrezza** [comment]
@msadikkose it appears my issue is also Hyper-V related. Would you happen to have found a fix for your issue yet?

P.S: Swapped in a new HDD with Windows 10 and things work fine. Rather unfortunate I can't figure out how to fix it on my original drive.

**Comment by rneugeba** [comment]
might be similar to what folks are seeing on #482

**Comment by msadikkose** [comment]
@DannyAllegrezza Actually not yet. I searched about issue, my problem is installing windows 10 from image which is generated from a computer wihtout virtulization capability. I think clean windows 10 installation can be helpful.

**Comment by mmaguigan** [comment]
I just want to emphasize that this issue occurred on a Windows 10 Enterprise instance that was running docker successfully until the aforementioned update. Reinstalling Windows is not in any way an option as docker is a small part of my already very busy schedule - the issue is not related to #482. Let me know what you need to move this issue along and I will do my best, but please let's keep momentum here as this is a fatal defect if I cannot rely on Docker in a production Windows CI environment.

**Comment by rneugeba** [comment]
@mmaguigan thanks for the comment. I don't think this is an issue with Docker for Windows per se as the command/powershell cmdlet which fails is `Start-VM`. Prior to that everything looks to be set up fine. There is also an un-helpful message in the Hyper-V event log saying that it failed to start the VM without any details...

- can you try, quitting the app, and then from an elevated powershell in `C:\Program Files\Docker\Docker\resources\` execute `.\MobyLinux.ps1 -destroy`, followed by `.\MobyLinux.ps1 -create`. The execute `Start-VM MobyLinuxVM` directly.
- If this doesn't work, could you open Hyper-V Manager and try starting the VM from there?
- If that doesn't work could you try creating an empty VM in Hyper-V Manager? Just click on new VM and then just go through all the defaults. Once done start the VM. You should get a console window saying it couldn't find a boot medium or some such.

This is just to verify that Hyper-V is working on your system

thanks

**Comment by mmaguigan** [comment]
@rneugeba, thanks that was very helpful. Sure enough, I created an empty VM with no attached network interface (just to rule out DockerNAT from any relation to the issue) and sure enough, I cannot start any virtual machines anymore. The user interface and the PowerShell command fail with the same error.

Below are the events from ```Hyper-V-Worker\Admin``` in the event viewer in chronological order. They are from my attempt to start an empty VM with no NIC, but the same errors seem to occur for MobyLinuxVM.

```
Event 1 (12564):
'Test' No available MAC address for "Network Adapter".

Event 2 (12598):
'Test' Network Adapter (59e38e89-e695-47b3-b924-8189f99ae209--ec2d673c-bb4f-4a01-8cee-c7cbd8c79601) Disconnected from virtual network. (Virtual Machine ID 59E38E89-E695-47B3-B924-8189F99AE209)

Event 3 (12010):
The description for Event ID 12010 from source Microsoft-Windows-Hyper-V-Worker cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Test
59E38E89-E695-47B3-B924-8189F99AE209
Synthetic Ethernet Port
%%2147942887
0x800701E7
EC2D673C-BB4F-4A01-8CEE-C7CBD8C79601

The locale specific resource for the desired message is not present

Event 4 (12030):
'Test' failed to start. (Virtual machine ID 59E38E89-E695-47B3-B924-8189F99AE209)
```

**Comment by rneugeba** [comment]
Thanks for checking...just love the usefulness of error messages (not). Could you try disabling the Hyper-V feature, reboot, re-enable the Hyper-V feature reboot and see if that fixes it?

Also, do you have any third security (AV or firewall) software installed. We have seen some unhealthy interactions with some of them.

**Comment by rneugeba** [comment]
closing this issue due to inactivity. Please re-open if you have the additional information requested.
thanks for your report
