### ISSUE TITLE
Docker Desktop 2.1.0.0 crashes on start - Hyper-V was unable to find a virtual switch with name "DockerNAT"

### ISSUE THREAD

**Issue by erkist** [docker/for-win#4462]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E2BEE738-4A7F-4DE7-AE76-A05E92EB6621/20190807121617

### Expected behavior
Fresh installation of Docker Desktop starts successfully.

Virtual switches and virtual machines are created in Hyper-V.
### Actual behavior
Docker Desktop crashes on start-up every time, even after reboot.

Unable to create
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

Nothing is created in Hyper-V. The following error is seen in the log:

[14:31:12.573][HyperV            ][Info   ] Creating Switch: DockerNAT...
[14:31:13.252][HyperV            ][Error  ] Unable to create: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunCommandAsync>d__11.MoveNext()
[14:31:13.252][Linux             ][Error  ] Failed to start: Unable to create. Let's retry

### Information

  - Windows Version: 1809 (build 10.0.17763.615)
  - Docker Desktop Version: 2.1.0.0, fresh install.
  - RAM: 16GB, 9GB available
  - Reproducibility: Always, even after reboot and factory reset of Docker Desktop.

### Steps to reproduce the behavior

1. Start Docker Desktop after a fresh install and a reboot

**Comment by erkist** [comment]
I tried with Docker 2.0.0.3 and got a very similar result.

```
[10:38:57.466][HyperV         ][Info   ] Creating Switch: DockerNAT...
[10:38:58.442][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411. Let's retry
[10:38:58.478][Installer      ][Info   ] Checking for features: *Hyper-V*, Containers
[10:38:58.479][PowerShell     ][Info   ] Run script...
[10:39:01.106][PowerShell     ][Info   ] Run script...
[10:39:02.549][PowerShell     ][Info   ] Run script...
[10:39:04.237][PowerShell     ][Info   ] Run script...
[10:39:05.158][SegmentApi     ][Info   ] Usage statistic: actionCancelUpdate
[10:39:05.900][Installer      ][Info   ] Features installed
[10:39:05.945][HyperV         ][Info   ] Hyper-V is running
[10:39:05.945][PowerMode      ][Info   ] Stop
[10:39:05.945][HyperV         ][Info   ] Stop
[10:39:05.945][PowerShell     ][Info   ] Run script with parameters: -Stop True
[10:39:05.992][HyperV         ][Info   ] Script started at 10:39:05.991
[10:39:05.999][HyperV         ][Info   ] Modules loaded at 10:39:05.999
[10:39:06.009][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[10:39:06.010][HyperV         ][Debug  ] [stop] took 00:00:00.0649655 to run
[10:39:06.010][OptimizeDisk   ][Info   ] Optimize
[10:39:06.010][PowerShell     ][Info   ] Run script...
[10:39:06.020][Moby           ][Info   ] Stop
[10:39:06.030][HyperV         ][Info   ] Destroy
[10:39:06.030][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True
[10:39:06.080][HyperV         ][Info   ] Script started at 10:39:06.080
[10:39:06.089][HyperV         ][Info   ] Modules loaded at 10:39:06.089
[10:39:06.099][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[10:39:06.102][HyperV         ][Info   ] Destroying Switch DockerNAT...
[10:39:06.129][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[10:39:06.139][HyperV         ][Debug  ] [destroy] took 00:00:00.1095243 to run
[10:39:06.140][Firewall       ][Info   ] Closing ports...
[10:39:06.140][Firewall       ][Info   ] Removing all existing rules...
[10:39:06.239][Firewall       ][Info   ] All existing rules are removed.
[10:39:06.239][Firewall       ][Info   ] Ports are closed
[10:39:06.239][HyperVGuids    ][Info   ] Removing GUIDs...
[10:39:06.240][HyperVGuids    ][Info   ] GUIDs removed
[10:39:06.240][HyperV         ][Info   ] Create
[10:39:06.241][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64000000000 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[10:39:06.290][HyperV         ][Info   ] Script started at 10:39:06.289
[10:39:06.302][HyperV         ][Info   ] Modules loaded at 10:39:06.302
[10:39:06.324][HyperV         ][Info   ] Creating Switch: DockerNAT...
[10:39:06.971][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 195
   at Docker.Backend.HyperV.Create(Settings settings) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 125
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 117
[10:39:07.040][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
[10:39:07.042][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 121
at <ScriptBlock>, <No file>: line 411
[10:39:07.080][NamedPipeClient][Info   ] Sending Version()...
[10:39:07.081][NamedPipeClient][Info   ] Received response for Version
[10:39:07.081][NamedPipeClient][Info   ] Sending GatherDiagnostics(-path C:\Users\ErikSternerson\AppData\Local\Temp\ gather -id E2BEE738-4A7F-4DE7-AE76-A05E92EB6621/20190808103907, C:\Users\ErikSternerson\AppData\Local\Temp\E2BEE738-4A7F-4DE7-AE76-A05E92EB6621/20190808103907.zip)...
[10:39:07.081][NamedPipeServer][Info   ] Version()
[10:39:07.081][NamedPipeServer][Info   ] Version done in 00:00:00.
[10:39:07.082][NamedPipeServer][Info   ] GatherDiagnostics(-path C:\Users\ErikSternerson\AppData\Local\Temp\ gather -id E2BEE738-4A7F-4DE7-AE76-A05E92EB6621/20190808103907, C:\Users\ErikSternerson\AppData\Local\Temp\E2BEE738-4A7F-4DE7-AE76-A05E92EB6621/20190808103907.zip)
```

**Comment by da9l** [comment]
In 2.1.0.0 I got this error:

```
Unable to create
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

Looking deeper into log.txt I got this:
`[09:06:43.881][HyperV            ][Error  ] Unable to create: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".`

Could it be related to [issue 324](https://github.com/docker/for-win/issues/324)?

Yesterday (2019-08-08) I updated to 2.1.0.1 and I get the same error but a little bit more verbose:
D89B102F-8759-4D6E-B323-A69B530DA6A8/20190809061036
```
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

I've tried to clear up the Network adapters with `netcfg -d` but that does not help.

**Comment by Lambda-android** [comment]
If one have problems with this there might be reasons to explore https://support.microsoft.com/en-us/help/3105657/recommended-antivirus-exclusions-for-hyper-v-hosts

**Comment by mikeparker** [comment]
Tried this? https://github.com/docker/for-win/issues/3597#issuecomment-474949164

**Comment by djs55** [comment]
@erkist there is a completely new drive-sharing implementation in the latest edge release which doesn't use `DockerNAT` any more and which therefore may fix your problem.

In case it's useful I've written instructions for setting up and testing the new file sharing implementation here: https://github.com/docker/for-win/issues/5139#issuecomment-559700215
