### ISSUE TITLE
Windows Docker failed to start. 

### ISSUE THREAD

**Issue by speed2048** [docker/for-win#4465]
I installed Docker Desktop WSL 2 Tech Preview on Windows 10 Insider  Build 18950 and get the following stack trace when I start docker:

Unable to start
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

The diagnostic id is: 783526ED-108B-466D-AD8E-6C53118AB759/20190807163556

Note I am running WIndows 10 using VM Workstation 15 Pro. Version: 15.1.0 build-13591040

**Comment by StefanScherer** [comment]
Oh, this looks like the DockerDesktopVM could not be started. We don't support nested hypervisor. But what you can do is switch to Windows Containers mode, you can specify this during installation. This doesn't start the Hyper-V VM, but only the Windows Docker Engine.
Then you can click on WSL 2 Tech Preview from the menu and start it from the dialog.

**Comment by speed2048** [comment]
Thanks for the update, I would recommend that a message be presented that indicated that Docker does not support nested hypervistors.
