### ISSUE TITLE
Installation fails for version 2.1.0.1 - Access to the path '..\resources\inspector\..' is denied.

### ISSUE THREAD

**Issue by jmartens** [docker/for-win#4472]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Flawless upgrade to the latest stable release of Docker for Windows

### Actual behavior
Two pop-ups with the mesage that the installation of Docker for Windows v 2.1.0.1 failed with the following exceptions:

Window1:
```
Access to the path 'C:\Program Files\Docker\Docker\frontend\resources\inspector\cpu_profiler_test_runner' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
```

Window 2:
```
Access to the path 'C:\Program Files\Docker\Docker\frontend\resources\inspector\audits2_worker' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
```

### Information

  - Windows Version: Windows 10, versoin 1803 (OS build 17134.885)
  - Docker Desktop Version: 2.1.0.1

### Steps to reproduce the behavior

Not tried again yet

**Comment by jmartens** [comment]
Not sure if helps, but below a screenshot of both windows

![docker-installation-fail](https://user-images.githubusercontent.com/593327/62701805-77332280-b9e5-11e9-8483-eca08117a894.png)

**Comment by jmartens** [comment]
It seems the previous version of Docker for Windows is already installed as I can not find the Docker for Windows executable anymore. :-(

**Comment by jmartens** [comment]
This is the contents of my Docker folder, effectively only empty directories:

```
C:\Program Files\Docker\Docker>dir /s
 Volume in drive C is Windows
 Volume Serial Number is 5243-1209

 Directory of C:\Program Files\Docker\Docker

08-08-2019  13:56    <DIR>          .
08-08-2019  13:56    <DIR>          ..
08-08-2019  13:56    <DIR>          frontend
08-08-2019  13:56    <DIR>          resources
               0 File(s)              0 bytes

 Directory of C:\Program Files\Docker\Docker\frontend

08-08-2019  13:56    <DIR>          .
08-08-2019  13:56    <DIR>          ..
08-08-2019  13:56    <DIR>          resources
               0 File(s)              0 bytes

 Directory of C:\Program Files\Docker\Docker\frontend\resources

08-08-2019  13:56    <DIR>          .
08-08-2019  13:56    <DIR>          ..
08-08-2019  13:56    <DIR>          inspector
               0 File(s)              0 bytes

 Directory of C:\Program Files\Docker\Docker\frontend\resources\inspector

08-08-2019  13:56    <DIR>          .
08-08-2019  13:56    <DIR>          ..
08-08-2019  13:56    <DIR>          Images
               0 File(s)              0 bytes

 Directory of C:\Program Files\Docker\Docker\frontend\resources\inspector\Images

08-08-2019  13:56    <DIR>          .
08-08-2019  13:56    <DIR>          ..
               0 File(s)              0 bytes

 Directory of C:\Program Files\Docker\Docker\resources

08-08-2019  13:56    <DIR>          .
08-08-2019  13:56    <DIR>          ..
               0 File(s)              0 bytes

     Total Files Listed:
               0 File(s)              0 bytes
              17 Dir(s)  29.238.468.608 bytes free

C:\Program Files\Docker\Docker>
```

**Comment by jmartens** [comment]
A new install seems to have worked after donwloading from https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe

Not so happy with the flow of events. Now to check if my containers will still start...

**Comment by jmartens** [comment]
Containers seem to be up again.

**Comment by mikeparker** [comment]
Can you confirm which version you were updating from? 2.1.0.0? And you went through the normal update process?

**Comment by EugeneMsv** [comment]
Same behavior, after updating 2.1.0.0 errors appears and docker completely removed from pc

**Comment by jmartens** [comment]
Yes. On Aug 8, 2019 15:21, Mike Parker <notifications@github.com> wrote:Can you confirm which version you were updating from? 2.1.0.0? And you went through the normal update process?

**Comment by prudhvi-newell** [comment]
I'm also having a similar type of problem while upgrading Docker for windows from 2.1.0.0 to 2.1.0.1

Here's the pictu
<img width="499" alt="Docker Desktop" src="https://user-images.githubusercontent.com/46351883/62749416-5e009500-ba2a-11e9-9ae8-abf0e8854de8.PNG">

**Comment by prudhvi199302** [comment]
I'm also having a similar type of problem while upgrading Docker for windows from 2.1.0.0 to 2.1.0.1

Here's the picture
<img width="499" alt="Docker Desktop" src="https://user-images.githubusercontent.com/20563393/62749665-34943900-ba2b-11e9-87b7-1b301ad184aa.PNG">

**Comment by sukhmel** [comment]
Had an installer infinitely unpacking resources, no error have ever been shown. Retried several times to no avail, but have succeded after trying from [stable link ](https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe) jmartens's post.

**Comment by jmartens** [comment]
> Had an installer infinitely unpacking resources, no error have ever been shown. Retried several times to no avail, 

Please do not hi-jack issues as this seems to be a different symptom.

> but have succeded after trying from [stable link ](https://download.docker.com/win/stable/Docker%20for%20Windows%20Installer.exe) in jmartens's post.

Great, you're welcome.

**Comment by aldobongio** [comment]
Same exact behavior,:after updating 2.1.0.0 to 2.1.0.1 errors appeared (Access to the path ... is denied) and Docker was completely removed from pc.
Downloading and installing 2.1.0.1 from scratch fixed everything. Moreover, containers running before the "upgrade" are correctly restarted without manual intervention.

**Comment by brentarias** [comment]
Similar problem for me.  I had just rebooted my computer and right away I was asked if I would like to install 2.1.0.1.  I accepted and got this result:

    Access to the path 'Docker.ApiServices.dll' is denied.
        at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
        at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
        at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__11.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__25.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()

When I run `docker ps` at a cmd prompt I'm told `error during connect...the system cannot find the file specified...this error may also indicate that the docker daemon is not running.`

So now I'm attempting to fix it.  I had originally installed docker via Chocolatey:

    choco install -y docker-desktop

Now I'm trying to re-install using the same approach:

    choco install -y --force docker-desktop

The above command claims to be installing docker-desktop version 2.0.0.3.  Unfortunately, running `docker ps` gives the same error as before.  So now I do not have docker at all.

**Comment by ebertti** [comment]
I got related error, I think:

![image](https://user-images.githubusercontent.com/140394/64915630-c76a7680-d741-11e9-9170-b72d81bafd3d.png)
