### ISSUE TITLE
Message "Docker for Windows doesn't Support your Windows version" but it did yesterday and nothing changed

### ISSUE THREAD

**Issue by ShawnDigital** [docker/for-win#4482]
- [X] I have tried with the latest version of my channel (Stable)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 389E3BC9-6436-48E8-9DCB-95F18514C8BB/20190809193113  (**New**)
  - Diagnostics ID: 389E3BC9-6436-48E8-9DCB-95F18514C8BB/20190809155912 (Original)

### Expected behavior
Docker for Windows Starts 

### Actual behavior
Docker for windows says my OS isn't supported

![image](https://user-images.githubusercontent.com/8883525/62792586-3abeff80-ba95-11e9-92c1-30d5d5161522.png)

### Information

1. Allowed it to do an update maybe Wednesday, but have been using it constantly without issue. 
2. Came into work this morning and received this error.
3. Reinstalled Docker 4win
4. Removed and added back Hyper-V. Do not see dockerNAT but cannot remember if its always there or added by daemon which won't start.

  - Windows Version: 10.0.17763 Build 17763
  - Docker Desktop Version: Version: 2.1.0.1 (37199)

**From log see two things of note...**
> '[Error  ] Unable to send engine/start: Docker doesn't support your Windows version. Check documentation for minimum requirements
> [11:02:03.670][Installer         ][Error  ] Feature(s) not available: *Hyper-V*, Containers

Which it is and I reinstalled it even... but then I see...
> The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.. 

In the  diagnostics I saw...
> time="2019-08-09T10:59:42-05:00" level=warning msg="exec: \"powershell\": executable file not found in %PATH%" type=directorylist

Which I don't use powershell.exe and "Powershell for Windows 2.0" is not enabled in "windows features" dialog for apps & programs. I do use PowershellCore (pwsh.exe) but this is not new or has changed as far as I know. Automatic Windows Updates are disabled at work so it shouldn't have updated anything. I did run them just now to see if it would help and it did not. 

I.T. could have pushed something but I see no evidence they did. 

Is Powershell required for docker? It doesn't mention it anywhere I saw`

```
Version: 2.1.0.1 (37199)
Channel: stable
Sha1: 0a6675341101baa9fd3e4ee7c6606d832bc54abd
Started on: 2019/08/09 11:02:02.339
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1809
Build: 17763
BuildLabName: 17763.1.amd64fre.rs5_release.180914-1434
File: C:\Users\sdenton\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:02:02.430][GUI               ][Info   ] Starting...
[11:02:02.461][ComponentVersions ][Info   ] Edition community
[11:02:02.508][ComponentVersions ][Info   ] Edition community
[11:02:02.961][AppMigrator       ][Info   ] Current version: 5. Latest version: 5
[11:02:03.055][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[11:02:03.055][SegmentApi        ][Info   ] Usage statistic: Identify
[11:02:03.133][SegmentApi        ][Info   ] Usage statistic: appLaunched
[11:02:03.483][ApplicationTemplatesTracking][Info   ] Cannot list templates
[11:02:03.483][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[11:02:03.483][SegmentApi        ][Info   ] Usage statistic: heartbeat
[11:02:03.545][NamedPipeClient   ][Info   ] Sending app/version()...
[11:02:03.561][NamedPipeClient   ][Info   ] Received response for app/version
[11:02:03.561][NamedPipeClient   ][Info   ] Sending app/migrate()...
[11:02:03.561][NamedPipeClient   ][Info   ] Received response for app/migrate
[11:02:03.561][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[11:02:03.561][NamedPipeServer   ][Info   ] app/migrate()
[11:02:03.561][NamedPipeServer   ][Info   ] app/migrate done in 00:00:00.
[11:02:03.576][NamedPipeClient   ][Info   ] Sending app/version()...
[11:02:03.576][NamedPipeClient   ][Info   ] Received response for app/version
[11:02:03.576][NamedPipeClient   ][Info   ] Sending version-packs/enable(community, Docker.Core.Settings)...
[11:02:03.576][NamedPipeClient   ][Info   ] Received response for version-packs/enable
[11:02:03.576][NamedPipeServer   ][Info   ] app/version()
[11:02:03.576][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[11:02:03.576][NamedPipeServer   ][Info   ] version-packs/enable(community, Docker.Core.Settings)
[11:02:03.576][NamedPipeServer   ][Info   ] version-packs/enable done in 00:00:00.
[11:02:03.576][NamedPipeClient   ][Info   ] Sending app/version()...
[11:02:03.576][NamedPipeClient   ][Info   ] Received response for app/version
[11:02:03.576][NamedPipeClient   ][Info   ] Sending engine/start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions, AUDUBON\sdenton:**********)...
[11:02:03.576][NamedPipeServer   ][Info   ] app/version()
[11:02:03.576][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[11:02:03.576][NamedPipeServer   ][Info   ] engine/start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions, AUDUBON\sdenton:**********)
[11:02:03.592][Linux             ][Info   ] Setting container engine status to Starting
[11:02:03.639][PowerMode         ][Info   ] Stop
[11:02:03.639][HyperV            ][Info   ] Stop
[11:02:03.639][PowerShell        ][Info   ] Run script with parameters: -Stop True -Verbose True -ErrorAction Stop
[11:02:03.655][HyperV            ][Error  ] Unable to stop: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunAsync>d__6.MoveNext()
[11:02:03.655][Moby              ][Info   ] Stop
[11:02:03.655][Linux             ][Error  ] Failed to start: Unable to stop - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.. Let's retry
[11:02:03.655][Linux             ][Info   ] Setting container engine status to Starting
[11:02:03.655][Installer         ][Info   ] Checking for features: *Hyper-V*, Containers
[11:02:03.655][PowerShell        ][Info   ] Run script...
[11:02:03.670][PowerShell        ][Info   ] Run script...
[11:02:03.670][NamedPipeClient   ][Error  ] Unable to send engine/start: Docker doesn't support your Windows version. Check documentation for minimum requirements
[11:02:03.670][Installer         ][Error  ] Feature(s) not available: *Hyper-V*, Containers
[11:02:03.670][Linux             ][Info   ] Setting container engine status to Quitting
[11:05:35.412][DockerAnalytics   ][Error  ] Error getting engine info: Object reference not set to an instance of an object.
[11:05:35.534][DockerAnalytics   ][Error  ] Error getting engine info: Cannot access child value on Newtonsoft.Json.Linq.JValue.
[11:05:35.534][SegmentApi        ][Info   ] Usage statistic: dailyHeartbeat
[11:05:35.534][SystrayRemote     ][Info   ] Systray listener shutdown (cancelled)
[11:05:35.534][SystrayRemote     ][Info   ] Systray listener shutdown (cancelled)
[11:05:35.534][SystrayRemote     ][Info   ] Systray listener shutdown (cancelled)
[11:05:35.534][SystrayRemote     ][Info   ] Systray listener shutdown (cancelled)
[11:05:35.534][SystrayRemote     ][Info   ] Systray listener shutdown (cancelled)
[11:05:35.534][CrashReport       ][Info   ] Diagnostics cancelled by user
[11:05:35.534][NamedPipeClient   ][Info   ] Sending app/version()...
[11:05:35.549][CrashReport       ][Info   ] Diagnostics cancelled by user
[11:05:35.549][NamedPipeClient   ][Info   ] Sending app/version()...
[11:05:35.549][NamedPipeClient   ][Info   ] Received response for app/version
[11:05:35.549][NamedPipeClient   ][Info   ] Received response for app/version
[11:05:35.549][NamedPipeClient   ][Info   ] Sending diagnostics/stop-gather()...
[11:05:35.549][NamedPipeClient   ][Info   ] Sending diagnostics/stop-gather()...
[11:05:35.549][NamedPipeClient   ][Info   ] Received response for diagnostics/stop-gather
[11:05:35.549][NamedPipeClient   ][Info   ] Received response for diagnostics/stop-gather
[11:05:35.549][NamedPipeClient   ][Info   ] Sending app/version()...
[11:05:35.549][NamedPipeClient   ][Info   ] Received response for app/version
[11:05:35.549][NamedPipeClient   ][Info   ] Sending engine/stop(All, Docker.Core.Settings)...
[11:05:35.549][NamedPipeServer   ][Info   ] app/version()
[11:05:35.549][NamedPipeServer   ][Info   ] app/version()
[11:05:35.549][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[11:05:35.549][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[11:05:35.549][NamedPipeServer   ][Info   ] diagnostics/stop-gather()
[11:05:35.549][NamedPipeServer   ][Info   ] diagnostics/stop-gather done in 00:00:00.
[11:05:35.549][NamedPipeServer   ][Info   ] diagnostics/stop-gather()
[11:05:35.549][NamedPipeServer   ][Info   ] diagnostics/stop-gather done in 00:00:00.
[11:05:35.549][NamedPipeServer   ][Info   ] app/version()
[11:05:35.549][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[11:05:35.549][NamedPipeServer   ][Info   ] engine/stop(All, Docker.Core.Settings)
[11:05:35.549][Linux             ][Info   ] Setting container engine status to Stopping
[11:05:35.549][PowerMode         ][Info   ] Stop
[11:05:35.549][HyperV            ][Info   ] Stop
[11:05:35.565][NamedPipeClient   ][Error  ] Unable to send engine/stop: Unable to stop - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
[11:05:35.549][PowerShell        ][Info   ] Run script with parameters: -Stop True -Verbose True -ErrorAction Stop
[11:05:35.549][HyperV            ][Error  ] Unable to stop: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunAsync>d__6.MoveNext()
[11:05:35.549][Moby              ][Info   ] Stop
[11:05:35.565][Linux             ][Info   ] Setting container engine status to FailedToStop
[11:05:35.565][NamedPipeServer   ][Error  ] Unable to execute engine/stop: Unable to stop - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.    at Docker.Backend.HyperV.HandleException(String action, Exception ex)
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
   at Docker.Backend.ContainerEngine.Linux.DoStop()
   at Docker.Backend.ContainerEngine.Linux.Stop()
   at Docker.Backend.BackendService.Stop(ContainerEngineMode mode)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

**Comment by ShawnDigital** [comment]
After looking through the diagnostics and seeing so many powershell errors I tried installing _Powershell for Windows_, added it to the path var and restarted, same issue. I reran the diagnostics though and didn't see those errors so possibly results are more usable so adding it above.

**Comment by StefanScherer** [comment]
Thanks, yes Docker Desktop needs Powershell. Thanks that you tried to reinstall it again. I'll check the new diagnostics.

**Comment by ShawnDigital** [comment]
Ok so I was able to install the edge version and the daemon started up. I now have 

Docker version 19.03.1, build 74b1e89

Hopefully everything works as expected in edge *fingers crossed*

**Comment by ShawnDigital** [comment]
It looks like everything came up ok. Not sure if its a known issue but Edge fixed it.

**Comment by StefanScherer** [comment]
I‘m glad you have it running again 👍

**Comment by wskarziw** [comment]
Replacing "stable" version with "edge" is considered solving a problem. Really?

**Comment by mikumakues** [comment]
Had the same issue on 2 machines after updating to Docker Desktop 2.1.0.5. In my case the entry for "C:\Windows\System32\WindowsPowerShell\v1.0\Modules\" was replaced with the text "System.String[]" on both machines. Replacing the incorrect text with the correct path fixed the issue.

**Comment by dimon222** [comment]
@wskarziw i've just noticed this problem now, its Feb 2020 but issue is still present.

**Comment by wskarziw** [comment]
I'm sorry to hear that, @dimon222
