### ISSUE TITLE
Docker Is Not Running in Windows 10 build 1903

### ISSUE THREAD

**Issue by rajb865** [docker/for-win#4486]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker Desktop for windows should start successfully. 

### Actual behavior
[Diagnostic Logs](https://drive.google.com/file/d/1sUyD8JN9NqvhsKEJdF6bVE4aI6PFzaD4/view?usp=sharing), Giving below error repeatedly 

```
Timed out while waiting for Docker daemon to be ready

   at Docker.Backend.Processes.WindowsDockerDaemon.WaitForDaemonToBeReady()
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_4(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

  - Windows Version: 1903 OS Build 18362.239
  - Docker Desktop Version: 2.1.0.1(37199)

![image](https://user-images.githubusercontent.com/3242274/62819681-ed668f00-bb75-11e9-9be0-07722b42c42f.png)

![image](https://user-images.githubusercontent.com/3242274/62819667-b3958880-bb75-11e9-8a7d-1c0a55a6a4ce.png)
### Steps to reproduce the behavior

  1. Run Docker Desktop for Windows
  2. ...

**Comment by jpl-jengelke** [comment]
Try the solution here: https://github.com/docker/for-win/issues/3597
