### ISSUE TITLE
Docker Desktop fails to start with `Unable to launch process: 1260`

### ISSUE THREAD

**Issue by getrostt** [docker/for-win#4493]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4AE96A07-0DC9-4882-979C-0401B8ED3EA8/20190812075319

### Expected behavior
Docker Desktop starts without error.

### Actual behavior
Docker desktop shows the following error message:
```
Unable to launch process: 1260

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

### Information

  - Windows Version: Windows 10 Enterprise 1803
  - Docker Desktop Version: Docker version 19.03.1, build 74b1e89

### Steps to reproduce the behavior

  1. Start "Docker Desktop"

**Comment by getrostt** [comment]
I also tried to enable `Windows Hypervisor Platform` as suggested in #4111. It did not help either.
