### ISSUE TITLE
Docker-compose up not working on windows

### ISSUE THREAD

**Issue by ameeno** [docker/for-win#4494]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: BCD1E3B2-8DF6-4141-90C6-9B23CB230E78/20190812090956

### Expected behavior
Docker-compose up works
### Actual behavior
I get this error:

```
Traceback (most recent call last):
  File "site-packages\jsonschema\validators.py", line 380, in resolve_from_url
  File "site-packages\jsonschema\_utils.py", line 23, in __getitem__
KeyError: 'file:///D:/ProgramData/config_schema_v3.1.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "urllib\request.py", line 1474, in open_local_file
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'D:\\ProgramData\\config_schema_v3.1.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\jsonschema\validators.py", line 383, in resolve_from_url
  File "site-packages\jsonschema\validators.py", line 474, in resolve_remote
  File "urllib\request.py", line 223, in urlopen
  File "urllib\request.py", line 526, in open
  File "urllib\request.py", line 544, in _open
  File "urllib\request.py", line 504, in _call_chain
  File "urllib\request.py", line 1452, in file_open
  File "urllib\request.py", line 1491, in open_local_file
urllib.error.URLError: <urlopen error [WinError 2] The system cannot find the file specified: 'D:\\ProgramData\\config_schema_v3.1.json'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\command.py", line 42, in project_from_options
  File "compose\cli\command.py", line 115, in get_project
  File "compose\config\config.py", line 387, in load
  File "compose\config\config.py", line 387, in <listcomp>
  File "compose\config\config.py", line 554, in process_config_file
  File "compose\config\validation.py", line 452, in validate_against_config_schema
  File "compose\config\validation.py", line 509, in handle_errors
  File "site-packages\jsonschema\validators.py", line 105, in iter_errors
  File "site-packages\jsonschema\_validators.py", line 304, in properties_draft4
  File "site-packages\jsonschema\validators.py", line 121, in descend
  File "site-packages\jsonschema\validators.py", line 105, in iter_errors
  File "site-packages\jsonschema\_validators.py", line 16, in patternProperties
  File "site-packages\jsonschema\validators.py", line 121, in descend
  File "site-packages\jsonschema\validators.py", line 105, in iter_errors
  File "site-packages\jsonschema\_validators.py", line 212, in ref
  File "site-packages\jsonschema\validators.py", line 375, in resolve
  File "site-packages\jsonschema\validators.py", line 385, in resolve_from_url
jsonschema.exceptions.RefResolutionError: <urlopen error [WinError 2] The system cannot find the file specified: 'D:\\ProgramData\\config_schema_v3.1.json'>
[7620] Failed to execute script docker-compose

```

### Information

  - Windows Version: 1903
  - Docker Desktop Version: 2.1.0.1 

### Steps to reproduce the behavior

  1. try and use *ANY* docker compose file such as
```
version: "3"
services:
  product-service:
    build: ./product
    ports:
      - "5001:80"
    volumes:
      - "./product:/usr/src/app"

```

with the docker file:

```
FROM python:3-onbuild
COPY . /usr/src/app
CMD ["python", "api.py"]
```

my api.py is:

```
from flask import Flask
from flask_restful import Resource, Api

app = Flask(__name__)
api = API(app)

class Product(Resource):
    def get(self):
        return {
            'product': ['Ice cream',
                        'Chocolate',
                        'Fruit']
        }

api.add_resource(Product, '/')
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=80, debug=True)

```
  2. does not work man. dont know if its python or what. or urllib. just does not work, and i dont know why.

HELPPPPP

(PS, works under wsl linux with docker installed and connecting to the same docker damon via localhost port 2375)

**Comment by ameeno** [comment]
update.

so it seems to be working now.

I nuked my windows python3 / python 2 install

and also removed from path.


SO i believe docker-compose is reverting to its own built in python with json checking and is working fine.

It is a shame i need to lose my own python install/python path to get docker-compose to work,

is there any way to tell docker-compose to always use its OWN python and not check my path and revert to the system installed version?
