### ISSUE TITLE
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer 'CHAKRIT-RAKHUAN' could not be resolved. Make sure you typed the machine name correctly and that you have network access.

### ISSUE THREAD

**Issue by ChakritRakuang** [docker/for-win#4505]
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer 'CHAKRIT-RAKHUAN' could not be resolved. Make sure you typed the machine name correctly and that you have network access.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by jpl-jengelke** [comment]
Make sure your machine has a NetBIOS name defined. Wash, rinse, repeat.
