### ISSUE TITLE
Docker refuses to start since this morning.

### ISSUE THREAD

**Issue by IosifZ** [docker/for-win#4528]
Hi all,

Docker desktop refuses to start since this morning. Already tried a full uninstall and a fresh re-install without luck. Any ideas?
... 
2019-08-15T07:03:18Z docker time="2019-08-15T07:03:18.739695200Z" level=warning msg="got error while decoding json" error="unexpected EOF" retries=3443
2019-08-15T07:03:18Z docker time="2019-08-15T07:03:18.739708900Z" level=warning msg="got error while decoding json" error="unexpected EOF" retries=3444
2019-08-15T07:03:18Z docker time="2019-08-15T07:03:18.739721900Z" level=warning msg="got error while decoding json" error="unexpected EOF" retries=3445
2019-08-15T07:03:18Z docker time="2019-08-15T07:03:18.739737700Z" level=warning msg="got error while decoding json" error="unexpected EOF" retries=3446
2019-08-15T07:03:18Z docker time="2019-08-15T07:03:18.739752600Z" level=warning msg="got error while decoding json" error="unexpected EOF" retries=3447
2019-08-15T07:03:18Z docker time="2019-08-15T07:03:18.739770900Z" level=warning msg="got error while decoding json" error="unexpected EOF" retries=3448
2019-08-15T07:03:18Z docker time="2019-08-15T07:03:18.739784900Z" level=warning msg="got error while decoding json" error="unexpected EOF" retries=3449
2019-08-15T07:03:18Z docker time="2019-08-15T07:03:18.739797700Z" level=warning msg="got error while decoding json" error="unexpected EOF" retries=3450
2019-08-15T07:03:18Z docker time="2019-08-15T07:03:18.739810500Z" level=warning msg="got error while decoding json" error="unexpected EOF" retries=3451
2019-08-15T07:03:18Z docker time="2019-08-15T07:03:18.739824600Z" level=warning msg="got error while decoding json" error="unexpected EOF" retri

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
... 

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
02C9FD8A-2A01-4ED5-82BD-F2C799FE609F/20190815092338
### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

Windows 10 Pro Version 1903 (OS Build 18875.1000)
Docker desktop
Engine 19.03.1
Compose 1.24.1
Kubernetes v1.14.3
Notary 0.6.1
Credential Helpers 0.6.3
Machine 0.16.1

![Screenshot_20190815-124810](https://user-images.githubusercontent.com/53576878/63087525-16fb2e00-bf5b-11e9-9b8e-3cdbbad6c436.jpg)

**Comment by IosifZ** [comment]
And the log file.

[log.txt](https://github.com/docker/for-win/files/3506425/log.txt)

**Comment by jpl-jengelke** [comment]
Not sure about the error posted above, but this looks a *lot* like the issue with the W10E 1903 update. See https://github.com/docker/for-win/issues/3597 …
