### ISSUE TITLE
Cannot start Linux containers due to message about my OS not supported because it can't see hyper-v

### ISSUE THREAD

**Issue by ShawnDigital** [docker/for-win#4538]
I had this problem with stable last week and only got it working after a day or debugging by switching to Edge. Now its started on Edge. I've tried uninstalling all hyper v and reinstalling, I tried the newer release on stable and then back to edge. I removed PowerShellCore and made sure Powershell for Windows was installed based discussions last week after diagnostics had some Powershell errors. I don't know what else to try and cannot do my job right now. I switched to Windows containers and it started up,, switched back to Linux and it failed still, but can't use windows containers and am out of ideas.  Did factory reset. 

  - [X] I have tried with the latest version of my channel **Stable and Edge** both
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 2E7AEBC1-EA21-4C28-97D1-B4406698A861/20190816181414

### Expected behavior
Docker for Desktop starts

### Actual behavior
Unable to stop - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The specified module 'Hyper-V' was not loaded because no valid module file was found in any module directory.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.<>c__DisplayClass36_0.<SwitchDaemon>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

### Information
  - Is it reproducible? _For me don't know about anyone else_
  - Is the problem new? _Saw this last week and switched to edge but now its in edge_
  - Did the problem appear with an update? _Maybe a day or two after a update last week_
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
  - Windows Version: Version 10.0.17763 Build 17763
  - Docker Desktop Version: Docker version 19.03.1, build 74b1e89

This seems possibly related to Visual Studio 2019 granted its a tenuous connection, but I get a similar error that sounds like it involves Powershell modules when I open the PS as admin since a VS2019 update a few updates ago, but can't find anything to attempt troubleshooting.

_Import-Module : The specified module '.\Common7\Tools\vsdevshell\Microsoft.VisualStudio.DevShell.dll' was not loaded
because no valid module file was found in any module directory._

I'm going to try and make sure its up to date then start uninstalling extensions or whatever I can find until something happens.

**Comment by ShawnDigital** [comment]
So it appears that root of the issue was addition of the PS DevCmd prompt in a VS2019 update. If I have time I may look into it to figure what exactly what it did, but I am way behind at work now. This was traced back to issues I've seen since the VS update and the fix or more accurately workaround fixed this and other issues I've been experiencing, which was to add every module path on my PC (6 I think it was) to a system wide environmental variable **PSModulesPath** so that anything anywhere using any Powershell in any way shape or form on my system would see all modules. Once I did this docker4win started and errors I had seen in various consoles all went away. Hopefully this will help someone else if they see similar behavior. Not sure if docker 4 win modifications could avoid it or what. If I can catch up and find time I will try to get to the root of the issue.
