### ISSUE TITLE
Docker on Windows 10 Ent VM The operation has timed out com.docker.db.exe: Failed to set up server socket listening on hyperv-connect .... Unix.Unix_error(Unix.ENETDOWN, "socket", "")

### ISSUE THREAD

**Issue by dockergirl** [docker/for-win#454]
### Expected behavior
Docker shall start-up first time (beta docker)
Hyper V enabled & ok.
But it is a VM and i dont have much info about VM System because it is operated by other department.
 I think its VMWare, could you suggest VMWare neccessary setting for running docker ?
### Actual behavior
Error : Operation has timed out.
at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
### Information
**[11:20:35.219][DataKit        ][Info   ] Starting com.docker.db.exe 0.7.0-34-g6f04213 ...
[11:20:35.219][DataKit        ][Error  ] com.docker.db.exe: Failed to set up server socket listening on hyperv-connect://b5a5ef22-eaa9-4234-8fe5-4b724dcf40dd: Unix.Unix_error(Unix.ENETDOWN, "socket", "")
[11:20:35.219][DataKit        ][Info   ] com.docker.db.exe: internal error, uncaught exception:
[11:20:35.219][DataKit        ][Info   ]                    (Failure accept_forever)**

ID :1316F8B9-8B74-4655-B512-53C3544D41B8/2017-02-01_11-21-05
 
Version: 1.13.1-rc1-beta40 (9961)
Channel: beta
Sha1: 0d026e19d7e7bf206cfca68289de99dd4cb56b38
Started on: 2017/02/01 11:20:20.804
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.693.amd64fre.rs1_release.161220-1747
File: C:\Users\Admin\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:20:20.960][GUI            ][Info   ] Starting...
[11:20:21.335][Tracking       ][Info   ] Crash report and usage statistics are enabled
[11:20:21.335][SegmentApi     ][Info   ] Usage statistic: appLaunched
[11:20:21.507][NamedPipeClient][Info   ] Sending Version()...
[11:20:21.523][NamedPipeClient][Info   ] Received response for Version
[11:20:21.523][SegmentApi     ][Info   ] Usage statistic: heartbeat
[11:20:15.960][BackendServer  ][Info   ] Started
[11:20:21.523][NamedPipeServer][Info   ] Version()
[11:20:21.523][NamedPipeServer][Info   ] Version done in 00:00:00.
[11:20:21.679][Updater        ][Info   ] Checking for updates on channel beta...
[11:20:21.679][Notifications  ][Info   ] Docker is starting...
[11:20:21.710][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[11:20:21.710][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[11:20:21.710][PowerMode      ][Info   ] Stop
[11:20:21.710][HyperV         ][Info   ] Stop
[11:20:21.726][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:20:21.726][PowerShell     ][Info   ] Creating a Runspace Pool...
[11:20:21.929][Updater        ][Info   ] Local build 9961 is as good as the remote 9961 on channel beta
[11:20:21.929][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[11:20:22.085][HyperV         ][Info   ] Script started at 11:20:22.069
[11:20:24.312][HyperV         ][Info   ] Module loaded at 11:20:24.312
[11:20:24.513][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:20:24.514][HyperV         ][Debug  ] [stop] took 00:00:02.8038952 to run
[11:20:24.514][OptimizeDisk   ][Info   ] Optimize
[11:20:24.515][PowerShell     ][Info   ] Run script...
[11:20:24.541][Moby           ][Info   ] Stop
[11:20:24.549][HyperV         ][Info   ] Create
[11:20:24.549][HyperVGuids    ][Info   ] Installing GUIDs...
[11:20:24.549][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[11:20:24.552][HyperVGuids    ][Info   ] GUIDs installed
[11:20:24.553][PowerMode      ][Info   ] Start
[11:20:24.562][HyperV         ][Info   ] Script started at 11:20:24.562
[11:20:24.583][Firewall       ][Info   ] Removing all existing rules...
[11:20:24.591][HyperV         ][Info   ] Module loaded at 11:20:24.591
[11:20:24.866][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:20:24.928][Firewall       ][Info   ] All existing rules are removed.
[11:20:24.930][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[11:20:25.608][Firewall       ][Info   ] Opening ports for SMB...
[11:20:26.319][Firewall       ][Info   ] Ports are opened
[11:20:27.425][HyperV         ][Info   ] Switch created.
[11:20:28.579][HyperV         ][Info   ] Set IP address on switch
[11:20:29.969][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[11:20:31.141][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[11:20:31.313][HyperV         ][Info   ] Creating dynamic VHD: C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[11:20:32.454][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[11:20:33.126][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[11:20:33.626][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\mobylinux.iso
[11:20:35.094][HyperV         ][Info   ] VM created.
[11:20:35.094][HyperV         ][Debug  ] [create] took 00:00:10.5450028 to run
[11:20:35.094][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[11:20:35.173][DataKit        ][Info   ] Starting C:\Program Files\Docker\Docker\Resources\com.docker.db.exe --url hyperv-connect://b5a5ef22-eaa9-4234-8fe5-4b724dcf40dd,\\.\pipe\dockerDataBase --color never
[11:20:35.173][DataKit        ][Info   ] Started
[11:20:35.219][DataKit        ][Info   ] Starting com.docker.db.exe 0.7.0-34-g6f04213 ...
[11:20:35.219][DataKit        ][Error  ] com.docker.db.exe: Failed to set up server socket listening on hyperv-connect://b5a5ef22-eaa9-4234-8fe5-4b724dcf40dd: Unix.Unix_error(Unix.ENETDOWN, "socket", "")
[11:20:35.219][DataKit        ][Info   ] com.docker.db.exe: internal error, uncaught exception:
[11:20:35.219][DataKit        ][Info   ]                    (Failure accept_forever)
[11:20:35.219][DataKit        ][Info   ]                    
[11:20:35.235][Database       ][Info   ] Generating CA Cert Bundle
[11:20:35.251][DataKit        ][Error  ] Process died
[11:20:35.251][Database       ][Info   ] CA Cert Bundle Generated
[11:20:40.220][Linux          ][Error  ] Failed to start: The operation has timed out.. Let's retry
[11:20:40.220][PowerShell     ][Info   ] Run script...
[11:20:43.095][HyperV         ][Info   ] Hyper-V is running
[11:20:43.095][PowerMode      ][Info   ] Stop
[11:20:43.095][HyperV         ][Info   ] Stop
[11:20:43.095][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:20:43.110][HyperV         ][Info   ] Script started at 11:20:43.110
[11:20:43.126][HyperV         ][Info   ] Module loaded at 11:20:43.126
[11:20:43.173][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[11:20:43.173][HyperV         ][Debug  ] [stop] took 00:00:00.0781240 to run
[11:20:43.173][OptimizeDisk   ][Info   ] Optimize
[11:20:43.173][PowerShell     ][Info   ] Run script...
[11:20:44.704][Moby           ][Info   ] Stop
[11:20:44.704][HyperV         ][Info   ] Destroy
[11:20:44.704][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[11:20:44.720][HyperV         ][Info   ] Script started at 11:20:44.720
[11:20:44.735][HyperV         ][Info   ] Module loaded at 11:20:44.735
[11:20:44.766][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[11:20:44.766][HyperV         ][Info   ] Destroying Switch DockerNAT...
[11:20:45.891][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[11:20:45.985][HyperV         ][Debug  ] [destroy] took 00:00:01.2812361 to run
[11:20:45.985][Firewall       ][Info   ] Closing ports...
[11:20:45.985][Firewall       ][Info   ] Removing all existing rules...
[11:20:46.220][Firewall       ][Info   ] Removing DockerProxy...
[11:20:46.454][Firewall       ][Info   ] Removed DockerProxy.
[11:20:46.688][Firewall       ][Info   ] Removing DockerSmbMount...
[11:20:46.923][Firewall       ][Info   ] Removed DockerSmbMount.
[11:20:47.141][Firewall       ][Info   ] All existing rules are removed.
[11:20:47.141][Firewall       ][Info   ] Ports are closed
[11:20:47.141][HyperVGuids    ][Info   ] Removing GUIDs...
[11:20:47.141][HyperVGuids    ][Info   ] GUIDs removed
[11:20:47.141][HyperV         ][Info   ] Create
[11:20:47.141][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[11:20:47.157][HyperV         ][Info   ] Script started at 11:20:47.157
[11:20:47.173][HyperV         ][Info   ] Module loaded at 11:20:47.173
[11:20:47.235][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:20:48.829][HyperV         ][Info   ] Switch created.
[11:20:49.126][HyperV         ][Info   ] Set IP address on switch
[11:20:49.173][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[11:20:50.204][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[11:20:50.470][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[11:20:50.954][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[11:20:51.141][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\mobylinux.iso
[11:20:52.501][HyperV         ][Info   ] VM created.
[11:20:52.501][HyperV         ][Debug  ] [create] took 00:00:05.3593846 to run
[11:20:52.501][PowerMode      ][Info   ] Stop
[11:20:52.501][HyperV         ][Info   ] Stop
[11:20:52.501][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:20:52.516][HyperV         ][Info   ] Script started at 11:20:52.516
[11:20:52.548][HyperV         ][Info   ] Module loaded at 11:20:52.548
[11:20:52.579][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[11:20:52.579][HyperV         ][Debug  ] [stop] took 00:00:00.0781240 to run
[11:20:52.579][OptimizeDisk   ][Info   ] Optimize
[11:20:52.579][PowerShell     ][Info   ] Run script...
[11:20:54.110][Moby           ][Info   ] Stop
[11:20:54.110][HyperV         ][Info   ] Create
[11:20:54.110][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[11:20:54.110][HyperVGuids    ][Info   ] Installing GUIDs...
[11:20:54.110][HyperVGuids    ][Info   ] GUIDs installed
[11:20:54.110][PowerMode      ][Info   ] Start
[11:20:54.110][Firewall       ][Info   ] Removing all existing rules...
[11:20:54.157][HyperV         ][Info   ] Script started at 11:20:54.157
[11:20:54.188][HyperV         ][Info   ] Module loaded at 11:20:54.188
[11:20:54.360][Firewall       ][Info   ] All existing rules are removed.
[11:20:54.360][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[11:20:54.782][HyperV         ][Info   ] Using existing Switch: DockerNAT
[11:20:54.860][HyperV         ][Info   ] Using existing Switch IP address
[11:20:54.876][Firewall       ][Info   ] Opening ports for SMB...
[11:20:54.938][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[11:20:55.095][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[11:20:55.454][Firewall       ][Info   ] Ports are opened
[11:20:55.829][HyperV         ][Info   ] VM created.
[11:20:55.829][HyperV         ][Debug  ] [create] took 00:00:01.7187482 to run
[11:20:55.829][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[11:20:55.860][DataKit        ][Info   ] Starting C:\Program Files\Docker\Docker\Resources\com.docker.db.exe --url hyperv-connect://9244fae1-b0ba-438e-b028-eeaf67dd2b89,\\.\pipe\dockerDataBase --color never
[11:20:55.860][DataKit        ][Info   ] Started
[11:20:55.891][DataKit        ][Info   ] Starting com.docker.db.exe 0.7.0-34-g6f04213 ...
[11:20:55.891][DataKit        ][Error  ] com.docker.db.exe: Failed to set up server socket listening on hyperv-connect://9244fae1-b0ba-438e-b028-eeaf67dd2b89: Unix.Unix_error(Unix.ENETDOWN, "socket", "")
[11:20:55.891][DataKit        ][Info   ] com.docker.db.exe: internal error, uncaught exception:
[11:20:55.891][DataKit        ][Info   ]                    (Failure accept_forever)
[11:20:55.891][DataKit        ][Info   ]                    
[11:20:55.891][Database       ][Info   ] Generating CA Cert Bundle
[11:20:55.907][DataKit        ][Error  ] Process died
[11:20:55.923][Database       ][Info   ] CA Cert Bundle Generated
[11:21:00.891][PowerMode      ][Info   ] Stop
[11:21:00.891][HyperV         ][Info   ] Stop
[11:21:00.891][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:21:00.907][HyperV         ][Info   ] Script started at 11:21:00.907
[11:21:00.923][HyperV         ][Info   ] Module loaded at 11:21:00.923
[11:21:00.970][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[11:21:00.970][HyperV         ][Debug  ] [stop] took 00:00:00.0781206 to run
[11:21:00.970][OptimizeDisk   ][Info   ] Optimize
[11:21:00.970][PowerShell     ][Info   ] Run script...
[11:21:02.470][Moby           ][Info   ] Stop
[11:21:02.470][HyperV         ][Info   ] Destroy
[11:21:02.470][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[11:21:02.485][HyperV         ][Info   ] Script started at 11:21:02.485
[11:21:02.501][HyperV         ][Info   ] Module loaded at 11:21:02.501
[11:21:02.532][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[11:21:02.532][HyperV         ][Info   ] Destroying Switch DockerNAT...
[11:21:03.860][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[11:21:03.954][HyperV         ][Debug  ] [destroy] took 00:00:01.4843742 to run
[11:21:03.954][Firewall       ][Info   ] Closing ports...
[11:21:03.954][Firewall       ][Info   ] Removing all existing rules...
[11:21:04.204][Firewall       ][Info   ] Removing DockerProxy...
[11:21:04.438][Firewall       ][Info   ] Removed DockerProxy.
[11:21:04.657][Firewall       ][Info   ] Removing DockerSmbMount...
[11:21:04.891][Firewall       ][Info   ] Removed DockerSmbMount.
[11:21:05.110][NamedPipeClient][Error  ] Unable to send Start: The operation has timed out.
[11:21:05.110][Notifications  ][Error  ] The operation has timed out.
[11:21:05.141][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[11:21:05.157][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[11:21:05.173][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\Admin\AppData\Local\Temp\kkxdfimt.xep\pcap.tar)...
[11:21:05.110][Firewall       ][Info   ] All existing rules are removed.
[11:21:05.110][Firewall       ][Info   ] Ports are closed
[11:21:05.110][HyperVGuids    ][Info   ] Removing GUIDs...
[11:21:05.110][HyperVGuids    ][Info   ] GUIDs removed
[11:21:05.110][NamedPipeServer][Error  ] Unable to execute Start: The operation has timed out.    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[11:21:05.188][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\Admin\AppData\Local\Temp\kkxdfimt.xep\win_containers)...
[11:21:05.173][NamedPipeServer][Info   ] GetDebugInfo()
[11:21:06.618][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\Admin\AppData\Local\Temp\kkxdfimt.xep\mobyLogs.tar)...
[11:21:09.105][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\Admin\AppData\Local\Temp\kkxdfimt.xep\pcap.tar)
[11:21:09.110][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[11:21:09.109][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[11:21:09.109][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0039998.
[11:21:09.110][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\Admin\AppData\Local\Temp\kkxdfimt.xep\win_containers)
[11:21:11.925][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[11:21:11.871][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\Admin\AppData\Local\Temp\kkxdfimt.xep\mobyLogs.tar)
[11:21:11.895][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[11:21:11.925][HyperV         ][Warning] Unable to download logs: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual machine with name "MobyLinuxVM".
[11:21:11.925][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.0540025.
[11:21:12.998][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[11:21:12.997][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:03.8872273.
[11:21:23.382][NamedPipeServer][Info   ] GetDebugInfo done in 00:00:18.2098042.
[11:21:23.385][NamedPipeClient][Info   ] Received response for GetDebugInfo
[11:21:23.796][CrashReport    ][Info   ] Uploading diagnostics...
[11:21:27.017][CrashReport    ][Info   ] Diagnostics successfully uploaded
[11:21:27.031][GUI            ][Info   ] Sending Bugsnag report 31340f7c-019e-4bab-8653-567d4706868e...
[11:21:28.451][GUI            ][Info   ] Bugsnag report 31340f7c-019e-4bab-8653-567d4706868e sent
[11:23:41.463][ErrorReportWindow][Info   ] Open logs

### Steps to reproduce the behavior

  1. Install docker
  2. Docker starting up...

**Comment by rneugeba** [comment]
Thanks for your report. Please see: https://docs.docker.com/docker-for-windows/troubleshoot/#/running-docker-for-windows-in-nested-virtualization-scenarios
for some details. The link also lists some reasons why we can't really support Docker for Windows inside a Windows VM, so I'm closing this issue. If you have further questions please comment, and I see if I can help.

**Comment by dockergirl** [comment]
I understood your point. I have only the problem when you work in development it is easy to "purchase" another VM while it is not easy to "purchase" another HW PC. In my situation, it seems impossible...at least takes months until everybody confirms & order & finally get delivered & all the licenses & all the papers signed...:-)so i have to find some solution for the moment. It is bad that you can not support VMs.

**Comment by rneugeba** [comment]
How are your VMs provisioned? Are these VMs in the cloud or on-prem?
If on-prem it might be worth talking to your administrators...

Do you want to run windows containers or Linux containers?

**Comment by dockergirl** [comment]
Im talking to my admins, answer : only next week they can look at the VM system settings. I dont think it is cloud in that meaning though. But what is cloud anyway...I have a .net c# App & want to build a container for linux. I want to take the click once runtime (operated by IIS of Win server at the moment) & build it for apache in a linux container cloud (how to call it hmmm...).With that, i could switch off my own IIS & join to the cloud of the other department & use their system for free :-). Later, i want to take the complete App to their linux based container cloud & use for example theri authetication services & other services...

**Comment by dockergirl** [comment]
Thought i add that finally i got one Win10 PC & docker latets is working fine for build containers.

**Comment by rneugeba** [comment]
great. Glad that it is working for you
