### ISSUE TITLE
Docker fails to start when using Linux Containers when computer is on a domain

### ISSUE THREAD

**Issue by tomudding** [docker/for-win#4542]
- [x] I have tried with the latest version of my channel (**Stable**)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: **063A2FB2-4CB1-491E-A05E-B402FDE874AC/20190818093442**

### Expected behavior
Docker starts when using Linux Containers.

### Actual behavior
Docker fails to start when using Linux Containers and throws the following error:

> Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer '[REDACTED]' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
> 
>    at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
>    at Docker.Actions.<>c__DisplayClass36_0.<SwitchDaemon>b__0()
>    at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

### Information

  - Windows Version: 10.0.18362 Build 18362.295 (1903 Windows Enterprise Edition)
  - Docker Desktop Version: 2.1.0.1 (37199)

### Steps to reproduce the behavior

  1. Install Docker Desktop for Windows using the 'Use Linux Containers' option _or_ switch to Linux Containers.
  2. Wait for Docker Desktop to start
  3. It fails to start due to the the error.

Please note that this happens when the local computer is part of an enterprise domain. This causes the hostname of the computer to be unreachable, resulting in the error that crashes Docker.

**Comment by tomudding** [comment]
/remove-lifecycle stale

This still happens on the stable channel version 2.2.0.3 (42716). The error has changed:

> Docker.Core.DockerException:
> Docker.Core.Backend.BackendDestroyException:
> Unable to create Hyper-V VM: The computer '.' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
> at New-MobyLinuxVM, \<No file\>: line 388
> at New-MobyLinux, \<No file\>: line 182
> at \<ScriptBlock\>, \<No file\>: line 810
>    at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
>    at Docker.Backend.BackendNamedPipeServer.\<Run\>b__8_2(Object[] args)
>    at Docker.Core.Pipe.NamedPipeServer.\<\>c__DisplayClass9_0.\<Register\>b__0(Object[] parameters)
>    at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
> 
>   System.Management.Automation.RuntimeException:
>   Unable to create Hyper-V VM: The computer '.' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
>   at New-MobyLinuxVM, \<No file\>: line 388
>   at New-MobyLinux, \<No file\>: line 182
>   at \<ScriptBlock\>, \<No file\>: line 810
>      at Docker.Backend.HyperV.HandleException(String action, Exception ex)
>      at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
>      at Docker.Backend.HyperV.Create(Settings settings)
>      at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
>   
>   Microsoft.HyperV.PowerShell.VirtualizationException:
>   The computer '.' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
>      
>   Microsoft.Virtualization.Client.Management.ServerConnectionException:
>   The computer '.' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
>      at Microsoft.Virtualization.Client.Management.ServerNames.Resolve(String nameToResolve, IUserPassCredential credential)
>      at Microsoft.Virtualization.Client.Management.Server.GetServer(String name, IUserPassCredential credential)
>      at Microsoft.HyperV.PowerShell.VirtualizationObjectLocator.GetServer(String computerName)
>      at Microsoft.HyperV.PowerShell.ExceptionHelper.TryWithLogging[TInput,TOutput](Func`2 function, TInput input, IOperationWatcher operationWatcher)
>          
>    at Docker.Core.Pipe.NamedPipeClient.\<TrySendAsync\>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
>    at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
>    at Docker.Actions.\<\>c__DisplayClass26_0.\<StartAsync\>b__0()
>    at Docker.ApiServices.TaskQueuing.TaskQueue.\<\>c__DisplayClass18_0.\<.ctor\>b__1()

**Comment by tomudding** [comment]
This issue is no longer present in Docker Desktop for Windows, as the MobyLinux files have been removed in v2.3.
