### ISSUE TITLE
Windows Docker Issue 

### ISSUE THREAD

**Issue by sbollu** [docker/for-win#4574]
Version: 17.03.1-ce-rc1-win3 (10625)
Channel: edge
Sha1: 1795b358d57a91b5de5abac91fe6360420deb704
Started on: 2019/08/22 11:01:30.516
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1809
Build: 17763
BuildLabName: 17763.1.amd64fre.rs5_release.180914-1434
File: C:\Users\sbollu\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:01:30.764][GUI            ][Info   ] Starting...
[11:01:31.184][Tracking       ][Info   ] Crash report and usage statistics are enabled
[11:01:31.200][SegmentApi     ][Info   ] Usage statistic: appLaunched
[11:01:31.371][NamedPipeClient][Info   ] Sending Version()...
[11:01:31.386][NamedPipeClient][Info   ] Received response for Version
[11:01:31.386][SegmentApi     ][Info   ] Usage statistic: heartbeat
[10:59:36.332][BackendServer  ][Info   ] Started
[11:01:31.371][NamedPipeServer][Info   ] Version()
[11:01:31.371][NamedPipeServer][Info   ] Version done in 00:00:00.
[11:01:31.955][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[11:01:31.955][Updater        ][Info   ] Checking for updates on channel edge...
[11:01:31.955][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[11:01:31.971][PowerMode      ][Info   ] Stop
[11:01:31.971][HyperV         ][Info   ] Stop
[11:01:32.002][Updater        ][Info   ] We got a new version 37260 which is newer than 10625, asking user.
[11:01:32.002][SegmentApi     ][Info   ] Usage statistic: eventShowUpdateWindow
[11:01:32.002][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:01:32.018][PowerShell     ][Info   ] Creating a Runspace Pool...
[11:01:32.453][Updater        ][Info   ] Check for updates done.
[11:01:32.477][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[11:01:32.626][HyperV         ][Info   ] Script started at 11:01:32.620
[11:01:35.531][HyperV         ][Info   ] Module loaded at 11:01:35.531
[11:01:35.731][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:01:35.732][HyperV         ][Debug  ] [stop] took 00:00:03.7458030 to run
[11:01:35.732][OptimizeDisk   ][Info   ] Optimize
[11:01:35.733][PowerShell     ][Info   ] Run script...
[11:01:35.779][Moby           ][Info   ] Stop
[11:01:35.788][HyperVGuids    ][Info   ] Installing GUIDs...
[11:01:35.788][PowerMode      ][Info   ] Start
[11:01:35.788][HyperV         ][Info   ] Create
[11:01:35.789][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[11:01:35.793][HyperVGuids    ][Info   ] GUIDs installed
[11:01:35.797][Firewall       ][Info   ] Removing all existing rules...
[11:01:35.799][HyperV         ][Info   ] Script started at 11:01:35.799
[11:01:35.821][HyperV         ][Info   ] Module loaded at 11:01:35.821
[11:01:35.829][Firewall       ][Info   ] All existing rules are removed.
[11:01:35.829][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[11:01:35.839][Firewall       ][Info   ] Opening ports for SMB...
[11:01:35.849][Firewall       ][Info   ] Ports are opened
[11:01:36.062][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:01:36.221][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'PC' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 381. Let's retry
[11:01:36.223][PowerShell     ][Info   ] Run script...
[11:01:36.487][SegmentApi     ][Info   ] Usage statistic: actionAcceptUpdate
[11:01:36.495][InstallUpdateWindow][Info   ] Download msi to C:\Users\sbollu\AppData\Local\Temp\tmp1524.msi
[11:01:36.536][SegmentApi     ][Info   ] Usage statistic: actionCancelUpdate
[11:01:41.541][HyperV         ][Info   ] Hyper-V is running
[11:01:41.541][PowerMode      ][Info   ] Stop
[11:01:41.541][HyperV         ][Info   ] Stop
[11:01:41.546][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:01:41.551][HyperV         ][Info   ] Script started at 11:01:41.550
[11:01:41.562][HyperV         ][Info   ] Module loaded at 11:01:41.562
[11:01:41.619][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:01:41.619][HyperV         ][Debug  ] [stop] took 00:00:00.0776487 to run
[11:01:41.619][OptimizeDisk   ][Info   ] Optimize
[11:01:41.619][PowerShell     ][Info   ] Run script...
[11:01:41.671][Moby           ][Info   ] Stop
[11:01:41.680][HyperV         ][Info   ] Destroy
[11:01:41.680][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[11:01:41.685][HyperV         ][Info   ] Script started at 11:01:41.685
[11:01:41.694][HyperV         ][Info   ] Module loaded at 11:01:41.694
[11:01:41.748][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:01:41.750][HyperV         ][Info   ] Destroying Switch DockerNAT...
[11:01:41.850][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[11:01:41.900][HyperV         ][Debug  ] [destroy] took 00:00:00.2200101 to run
[11:01:41.900][Firewall       ][Info   ] Closing ports...
[11:01:41.900][Firewall       ][Info   ] Removing all existing rules...
[11:01:41.973][Firewall       ][Info   ] All existing rules are removed.
[11:01:41.973][Firewall       ][Info   ] Ports are closed
[11:01:41.973][HyperVGuids    ][Info   ] Removing GUIDs...
[11:01:41.976][HyperVGuids    ][Info   ] GUIDs removed
[11:01:41.976][HyperV         ][Info   ] Create
[11:01:41.977][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[11:01:41.983][HyperV         ][Info   ] Script started at 11:01:41.983
[11:01:42.006][HyperV         ][Info   ] Module loaded at 11:01:42.006
[11:01:42.160][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:01:42.309][PowerMode      ][Info   ] Stop
[11:01:42.309][HyperV         ][Info   ] Stop
[11:01:42.309][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:01:42.313][HyperV         ][Info   ] Script started at 11:01:42.313
[11:01:42.326][HyperV         ][Info   ] Module loaded at 11:01:42.326
[11:01:42.383][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:01:42.383][HyperV         ][Debug  ] [stop] took 00:00:00.0746677 to run
[11:01:42.383][OptimizeDisk   ][Info   ] Optimize
[11:01:42.383][PowerShell     ][Info   ] Run script...
[11:01:42.435][Moby           ][Info   ] Stop
[11:01:42.441][HyperV         ][Info   ] Destroy
[11:01:42.441][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[11:01:42.446][HyperV         ][Info   ] Script started at 11:01:42.446
[11:01:42.459][HyperV         ][Info   ] Module loaded at 11:01:42.459
[11:01:42.517][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:01:42.519][HyperV         ][Info   ] Destroying Switch DockerNAT...
[11:01:42.611][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[11:01:42.667][HyperV         ][Debug  ] [destroy] took 00:00:00.2259821 to run
[11:01:42.667][Firewall       ][Info   ] Closing ports...
[11:01:42.667][Firewall       ][Info   ] Removing all existing rules...
[11:01:42.687][Firewall       ][Info   ] All existing rules are removed.
[11:01:42.687][Firewall       ][Info   ] Ports are closed
[11:01:42.687][HyperVGuids    ][Info   ] Removing GUIDs...
[11:01:42.687][HyperVGuids    ][Info   ] GUIDs removed
[11:01:42.691][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'MM251528-PC' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 381    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[11:01:42.758][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'MM251528-PC' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 381
[11:01:42.759][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'MM251528-PC' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-Switch, <No file>: line 131
at <ScriptBlock>, <No file>: line 381
[11:01:42.776][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[11:01:42.780][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\sbollu\AppData\Local\Temp\zft55ryh.l1g\pcap.tar)...
[11:01:42.780][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\sbollu\AppData\Local\Temp\zft55ryh.l1g\mobyLogs.tar)...
[11:01:42.780][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\sbollu\AppData\Local\Temp\zft55ryh.l1g\win_containers)...
[11:01:42.781][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[11:01:42.790][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[11:01:42.780][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\sbollu\AppData\Local\Temp\zft55ryh.l1g\pcap.tar)
[11:01:42.780][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\sbollu\AppData\Local\Temp\zft55ryh.l1g\mobyLogs.tar)
[11:01:42.781][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\sbollu\AppData\Local\Temp\zft55ryh.l1g\win_containers)
[11:01:42.783][NamedPipeServer][Info   ] GetDebugInfo()
[11:01:42.787][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[11:01:42.787][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0069677.
[11:01:42.867][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[11:01:42.959][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[11:01:42.959][HyperV         ][Warning] Unable to download logs: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'MM251528-PC' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
[11:01:42.959][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.1791905.
[11:01:54.510][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[11:01:54.509][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:11.7283584.
[11:02:01.250][NamedPipeServer][Info   ] GetDebugInfo done in 00:00:18.4673299.
[11:02:01.254][NamedPipeClient][Info   ] Received response for GetDebugInfo
[11:02:01.635][CrashReport    ][Info   ] Uploading diagnostics...
[11:02:04.640][CrashReport    ][Info   ] Diagnostics successfully uploaded (02F2D31B-D3CE-442E-85A7-01267B6C572E/2019-08-22_11-01-42)
[11:02:04.657][GUI            ][Info   ] Sending Bugsnag report 5f9794f6-cac1-4ae9-b030-0d30c0f3df83...
[11:02:05.166][GUI            ][Info   ] Bugsnag report 5f9794f6-cac1-4ae9-b030-0d30c0f3df83 sent
[11:02:08.679][ErrorReportWindow][Info   ] Open logs

**Comment by sbollu** [comment]
It use to work 3 weeks back I am getting this error from one week.

**Comment by jpl-jengelke** [comment]
Here's the key to the problem: 'Variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer. ...'

Look into this -- https://github.com/docker/for-win/issues/3597
