### ISSUE TITLE
installing release 2.1.1.0 fails Insufficient disk space...  but there is 30+GB free space 

### ISSUE THREAD

**Issue by techboy1969** [docker/for-win#4577]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by techboy1969** [comment]
install fails  Desktop 2.1.1.0  

There is insufficient disk space to complete operation. (Exception from HRESULT: 0x80030070 (STG_E_MEDIUMFULL))
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Save(String pszFileName, Boolean fRemember)
   at CommunityInstaller.ShortcutAction.DoAsync(CancellationToken cancelToken)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()


I have over 30gb space free

**Comment by techboy1969** [comment]
turn off defender and malware protection and close processes to free ram

**Comment by spyd3rw3b** [comment]
when I turned off Defender and malware it got past the disk space error and stated it was being used by another process. Only one process was running. I have 100GB disk space free.

log:
Version: 2.1.0.1 (37199)
Channel: stable
Sha1: 0a6675341101baa9fd3e4ee7c6606d832bc54abd
Started on: 2019/09/04 19:47:06.463
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1903
Build: 18362
BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
File: C:\Users\dj_sa\AppData\Local\Docker\install-log.txt
CommandLine: "C:\Program Files\Docker\Docker\InstallerCli.exe" -i
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[19:47:06.781][ComponentVersions ][Info   ] Edition community
[19:47:06.835][ComponentVersions ][Info   ] Edition community
[19:47:06.901][Linux             ][Info   ] Setting container engine status to Stopped
[19:47:06.908][Installer         ][Info   ] Fixing permissions...
[19:47:06.910][Installer         ][Info   ] Deleting directory C:\ProgramData\DockerDesktop\version-bin
[19:47:06.911][Installer         ][Info   ] Deleting directory C:\ProgramData\Docker\cli-plugins
[19:47:06.967][Installer         ][Info   ] Permissions should be fixed.

error after defender off and running as and with admin permission:
The process cannot access the file 'C:\Program Files\Docker\Docker\Docker Desktop Installer.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at CommunityInstaller.RegisterProductStep.Register(String basePath, Manifest manifest, String manifestJson)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()

**Comment by mickare** [comment]
Turning off Windows Defender and Malware Protection temporary did help.

**Comment by spyd3rw3b** [comment]
updates fail even after turning off Defender and Malware protections. I eventually got it to install by re-downloading the binary, turning off Defender and Malware Protections and removing the previously installed version information, I had to do that for each upgrade since 2.1.0.1, otherwise it is working without issue, if an update pop-up occurs, I select the not now button, and just download the new version and re-run the install above. I run registry local (https://hub.docker.com/_/registry) so it pulls back in all my images
