### ISSUE TITLE
Cannot mount shared drive

### ISSUE THREAD

**Issue by trixobird** [docker/for-win#4587]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:
4EAF2228-432A-4DE3-A798-BDF257FAFCE2/20190824182750
### Expected behavior
Any shared drive is checked
### Actual behavior
No shared drive is checked
### Information

  - Windows Version:
  - Docker Desktop Version:

### Steps to reproduce the behavior

  1. Settings>Shared Drives
  2. Click a drive
  3. Enter the credentials
  4. Press Enter

After a a couple of seconds the checkbox is unchecked and the logs show this exception:
[21:36:32.972][MountCredentialAsker][Info   ] Storing credentials: MAIN\DockerHost:***********
[21:36:32.988][NamedPipeClient   ][Info   ] Sending app/version()...
[21:36:32.990][NamedPipeServer   ][Info   ] app/version()
[21:36:32.990][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[21:36:32.994][NamedPipeClient   ][Info   ] Received response for app/version
[21:36:32.994][NamedPipeClient   ][Info   ] Sending filesharing/mount(All, C, MAIN\DockerHost:**********, Docker.Core.Settings)...
[21:36:32.995][NamedPipeServer   ][Info   ] filesharing/mount(All, C, MAIN\DockerHost:**********, Docker.Core.Settings)
[21:36:32.995][SambaShare        ][Info   ] Mount C
[21:36:33.198][Cmd               ][Info   ] This shared resource does not exist.
[21:36:33.198][Cmd               ][Info   ] More help is available by typing NET HELPMSG 2310.
[21:36:33.201][SambaShare        ][Info   ] "C" is not shared
[21:36:33.201][SambaShare        ][Info   ] Creating share "C:" as "C" with Full Control to "MAIN\DockerHost"
[21:36:33.351][Cmd               ][Info   ] C was shared successfully.
[21:36:33.425][Cmd               ][Info   ] Share name        C
[21:36:33.425][Cmd               ][Info   ] Path              C:\
[21:36:33.425][Cmd               ][Info   ] Remark            
[21:36:33.425][Cmd               ][Info   ] Maximum users     No limit
[21:36:33.426][Cmd               ][Info   ] Users             
[21:36:33.426][Cmd               ][Info   ] Caching           Caching disabled
[21:36:33.427][Cmd               ][Info   ] Permission        MAIN\DockerHost, FULL
[21:36:33.427][Cmd               ][Info   ] The command completed successfully.
[21:36:33.433][SambaShare        ][Info   ] "C" is shared
[21:36:33.438][SambaShare        ][Info   ] Username: DockerHost
[21:36:33.438][SambaShare        ][Info   ] Host IP: 10.0.75.1
[21:36:33.438][SambaShare        ][Info   ] Cifs options: noperm,iocharset=utf8,dir_mode=0777,nobrl,mfsymlinks,vers=3.02,domain=MAIN,sec=ntlmsspi
[21:36:33.455][Moby              ][Info   ] [ 1286.071208] CIFS VFS: cifs_mount failed w/return code = -112
[21:36:33.461][GoBackendProcess  ][Info   ] error CloseWrite to: The pipe is being closed.
[21:36:33.461][SambaShare        ][Error  ] Unable to mount C drive: unexpected error: System.AggregateException: One or more errors occurred. ---> Docker.Backend.HttpBadResponseException: Exception of type 'Docker.Backend.HttpBadResponseException' was thrown.
   at Docker.Backend.HttpClientExtensions.<ParseResponseBodyAsJsonAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Docker.Backend.LifecycleClient.Mount(MountRequest req)
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential cred, UserNameAndDomain info, String options, String ip)
---> (Inner Exception #0) Docker.Backend.HttpBadResponseException: Exception of type 'Docker.Backend.HttpBadResponseException' was thrown.
   at Docker.Backend.HttpClientExtensions.<ParseResponseBodyAsJsonAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext()<---

[21:36:33.461][SambaShare        ][Info   ] Removing share "C"

I have followed the suggestion of the community regarding creating another user https://github.com/docker/for-win/issues/2719

**Comment by roobit** [comment]
how to fix this problem? I would like to know the detail information.

**Comment by trixobird** [comment]
> fixed the problem by resetting docker for windows

this didn't work for me :(

**Comment by roobit** [comment]
this didn't work for me either.

**Comment by trixobird** [comment]
as mentioned before I have tried the communities suggestions (including the aforementioned) and it didn't work. I'd like someone to look at the logs and pinpoint the problem

**Comment by roobit** [comment]
docker version is up to date, and using a local administrator to share drive. But still not work.

**Comment by njmalafa** [comment]
post the logs

**Comment by trixobird** [comment]
hi, I have posted the exception in the body of this bug. If you need the full logs, please let me know and I will provide them at the earliest convenience

**Comment by Jacob-Tate** [comment]
Check #690 for potential fix

**Comment by corradocavalli** [comment]
I'm having the exact same issue, tried everything but can't figure how to make sharing working.
Inside Docker log i see:

[17:09:27.562][SambaShare        ][Info   ] "C" is not shared
[17:09:27.562][SambaShare        ][Info   ] Creating share "C:" as "C" with Full Control to "BOSTON\corrado.cavalli"
[17:09:27.621][Cmd               ][Info   ] C was shared successfully.
[17:09:27.655][Cmd               ][Info   ] Share name        C
[17:09:27.655][Cmd               ][Info   ] Path              C:\
[17:09:27.655][Cmd               ][Info   ] Remark            
[17:09:27.655][Cmd               ][Info   ] Maximum users     No limit
[17:09:27.655][Cmd               ][Info   ] Users             
[17:09:27.655][Cmd               ][Info   ] Caching           Caching disabled
[17:09:27.656][Cmd               ][Info   ] Permission        BOSTON\corrado.cavalli, FULL
[17:09:27.656][Cmd               ][Info   ] The command completed successfully.
[17:09:27.658][SambaShare        ][Info   ] "C" is shared
[17:09:27.691][SambaShare        ][Info   ] Username: corrado.cavalli
[17:09:27.691][SambaShare        ][Info   ] Host IP: 10.0.75.1
[17:09:27.691][SambaShare        ][Info   ] Cifs options: noperm,iocharset=utf8,dir_mode=0777,nobrl,mfsymlinks,vers=3.02,domain=BOSTON,sec=ntlmsspi
[17:09:27.706][Moby              ][Info   ] [  110.606129] Status code returned 0xc000006d STATUS_LOGON_FAILURE
[17:09:27.708][Moby              ][Info   ] [  110.608282] CIFS VFS: Send error in SessSetup = -13
[17:09:27.710][Moby              ][Info   ] [  110.609979] CIFS VFS: cifs_mount failed w/return code = -13
[17:09:27.713][GoBackendProcess  ][Info   ] error CloseWrite to: The pipe is being closed.
[17:09:27.713][SambaShare        ][Error  ] Unable to mount C drive: unexpected error: System.AggregateException: One or more errors occurred. ---> Docker.Backend.HttpBadResponseException: Exception of type 'Docker.Backend.HttpBadResponseException' was thrown.
   at Docker.Backend.HttpClientExtensions.<ParseResponseBodyAsJsonAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Docker.Backend.LifecycleClient.Mount(MountRequest req)
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential cred, UserNameAndDomain info, String options, String ip)
---> (Inner Exception #0) Docker.Backend.HttpBadResponseException: Exception of type 'Docker.Backend.HttpBadResponseException' was thrown.
   at Docker.Backend.HttpClientExtensions.<ParseResponseBodyAsJsonAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext()<---

[17:09:27.713][SambaShare        ][Info   ] Removing share "C"
[17:09:27.744][SambaShare        ][Info   ] Mount C
[17:09:27.849][Cmd               ][Info   ] This shared resource does not exist.
[17:09:27.849][Cmd               ][Info   ] More help is available by typing NET HELPMSG 2310.
[17:09:27.851][SambaShare        ][Info   ] "C" is not shared
[17:09:27.851][SambaShare        ][Info   ] Creating share "C:" as "C" with Full Control to "corrado.cavalli"
[17:09:27.883][Cmd               ][Info   ] System error 1332 has occurred.
[17:09:27.883][Cmd               ][Info   ] No mapping between account names and security IDs was done.
[17:09:27.885][SambaShare        ][Error  ] Failed to create share "C:" as "C" with Full Control to "corrado.cavalli" with code: 2
[17:09:27.913][Cmd               ][Info   ] This shared resource does not exist.
[17:09:27.915][NamedPipeClient   ][Info   ] Received response for filesharing/mount
[17:09:27.913][Cmd               ][Info   ] More help is available by typing NET HELPMSG 2310.
[17:09:27.915][SambaShare        ][Info   ] "C" is not shared
[17:09:27.915][NamedPipeServer   ][Info   ] filesharing/mount done in 00:00:00.4590917.

tried all suggestions available, think is some SAMBA sharing issue, but SMB is installed (v3 too) but inside event viewer i see

SMB Session Authentication Failure

Client Name: \\10.0.75.2
Client Address: 10.0.75.2:58240
User Name: 
Session ID: 0x580004000025
Status: The attempted logon is invalid. This is either due to a bad username or authentication information. (0xC000006D)
SPN: session setup failed before the SPN could be queried
SPN Validation Policy: SPN optional / no validation

Group policy for Deny is not set while allow access via network is set to Everyone.

Ideas?

**Comment by atodkar** [comment]
I got below error while enabling C Drive on Windows 

`CIFS VFS: cifs_mount failed w/return code = -112`

And solved after below command in powershell-

`Set-SmbServerConfiguration -EnableSMB2Protocol $true`

Before this problem, I also faced issue related to encryption being enabled on Windows and that was resolved after disabling EncryptData on Smb Server configuration with below command.

`Set-SmbServerConfiguration -EncryptData $false`

Please note that there could be other security related implications due to softening the Smb Share security. But with above commands, issue got resolved for me.

**Comment by Ather23** [comment]
For some reason docker doesnt recognize AD account. 
I found that by checking the docker logs.

After reading various answers this worked for me:
1- Create a new user on your machine and grant it admin rights
2- Go to docker settings and share the drive
3- A window ask for user and password. Make sure you use the creds for the new user you created.

Hope this helps.

**Comment by strarsis** [comment]
I had a similar issue, restarting the "Server" service fixed it.
