### ISSUE TITLE
Docker is not starting

### ISSUE THREAD

**Issue by Prakash325** [docker/for-win#4595]
- [x] I have tried with the latest version of my channel (Stable or Edge)-- Stable
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3832B494-F1E5-4750-A6CE-3F8EC7DEA9B0/20190826174726

### Expected behavior
Docker should start when System starts

### Actual behavior
Docker is not starting and giving following error.
Error:
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass27_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
### Information

  - Windows Version: Windows 10 Pro, 1903 Id, 18362 Build 
  - Docker Desktop Version: 2.1.0.1 (37199)

### Steps to reproduce the behavior

  1. ...
  2. ...
I have tried disabling Hyper-V, enabling Hyper-V, re-installing Docker, change Control Flow Guard options. Nothing helped. Still facing same issue.

Logs:

Version: 2.1.0.1 (37199)
Channel: stable
Sha1: 0a6675341101baa9fd3e4ee7c6606d832bc54abd
Started on: 2019/08/26 23:15:50.696
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1903
Build: 18362
BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
File: C:\Users\USER.DESKTOP-EB3AANB\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[23:15:50.884][GUI               ][Info   ] Starting...
[23:15:50.915][ComponentVersions ][Info   ] Edition community
[23:15:51.009][ComponentVersions ][Info   ] Edition community
[23:15:51.492][AppMigrator       ][Info   ] Current version: 5. Latest version: 5
[23:15:51.663][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[23:15:51.663][SegmentApi        ][Info   ] Usage statistic: Identify
[23:15:51.773][SegmentApi        ][Info   ] Usage statistic: appLaunched
[23:15:54.500][ApplicationTemplatesTracking][Info   ] Cannot list templates
[23:15:54.500][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[23:15:54.516][SegmentApi        ][Info   ] Usage statistic: heartbeat
[23:15:54.703][NamedPipeClient   ][Info   ] Sending app/version()...
[23:15:54.719][NamedPipeClient   ][Info   ] Received response for app/version
[23:15:54.719][NamedPipeClient   ][Info   ] Sending app/migrate()...
[23:15:54.719][NamedPipeClient   ][Info   ] Received response for app/migrate
[23:15:54.703][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[23:15:54.719][NamedPipeServer   ][Info   ] app/migrate()
[23:15:54.719][NamedPipeServer   ][Info   ] app/migrate done in 00:00:00.
[23:15:54.735][NamedPipeClient   ][Info   ] Sending app/version()...
[23:15:54.735][NamedPipeServer   ][Info   ] app/version()
[23:15:54.750][NamedPipeClient   ][Info   ] Received response for app/version
[23:15:54.750][NamedPipeClient   ][Info   ] Sending version-packs/enable(community, Docker.Core.Settings)...
[23:15:54.735][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[23:15:54.750][NamedPipeClient   ][Info   ] Received response for version-packs/enable
[23:15:54.750][NamedPipeServer   ][Info   ] version-packs/enable(community, Docker.Core.Settings)
[23:15:54.750][NamedPipeServer   ][Info   ] version-packs/enable done in 00:00:00.
[23:15:54.766][NamedPipeClient   ][Info   ] Sending app/version()...
[23:15:54.766][NamedPipeClient   ][Info   ] Received response for app/version
[23:15:54.766][NamedPipeClient   ][Info   ] Sending engine/start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions, )...
[23:15:54.766][NamedPipeServer   ][Info   ] app/version()
[23:15:54.766][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[23:15:54.766][NamedPipeServer   ][Info   ] engine/start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions, )
[23:15:54.766][Linux             ][Info   ] Setting container engine status to Starting
[23:15:55.274][PowerMode         ][Info   ] Stop
[23:15:55.274][HyperV            ][Info   ] Stop
[23:15:55.353][PowerShell        ][Info   ] Run script with parameters: -Stop True -Verbose True -ErrorAction Stop
[23:15:55.540][HyperV            ][Info   ] VM DockerDesktopVM does not exist
[23:15:55.540][HyperV            ][Debug  ] [stop] took 00:00:00.2662769 to run
[23:15:55.540][OptimizeDisk      ][Info   ] Optimize
[23:15:55.540][PowerShell        ][Info   ] Run script...
[23:15:55.572][Moby              ][Info   ] Stop
[23:15:55.572][HyperVGuids       ][Info   ] Installing GUIDs...
[23:15:55.572][HyperV            ][Info   ] Create
[23:15:55.572][PowerMode         ][Info   ] Start
[23:15:55.572][PowerShell        ][Info   ] Run script with parameters: -Create True -VhdPathOverride C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx -VhdSize 68719476736 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 28 -PreferredIPAddress  -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-desktop.iso -Verbose True -ErrorAction Stop
[23:15:55.572][Firewall          ][Info   ] Removing all existing rules...
[23:15:55.650][HyperVGuids       ][Info   ] GUIDs installed
[23:15:55.650][Firewall          ][Info   ] All existing rules are removed.
[23:15:55.650][Firewall          ][Info   ] Opening ports for SMB...
[23:15:55.665][Firewall          ][Info   ] Ports are opened
[23:15:55.962][HyperV            ][Info   ] Creating Switch: DockerNAT...
[23:16:11.277][HyperV            ][Error  ] Unable to create: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunAsync>d__6.MoveNext()
[23:16:11.277][Linux             ][Error  ] Failed to start: Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure . Let's retry
[23:16:11.277][Linux             ][Info   ] Setting container engine status to Starting
[23:16:11.314][HyperV            ][Info   ] Hyper-V is running
[23:16:11.314][PowerMode         ][Info   ] Stop
[23:16:11.314][HyperV            ][Info   ] Stop
[23:16:11.314][PowerShell        ][Info   ] Run script with parameters: -Stop True -Verbose True -ErrorAction Stop
[23:16:11.356][HyperV            ][Info   ] VM DockerDesktopVM does not exist
[23:16:11.356][HyperV            ][Debug  ] [stop] took 00:00:00.0419640 to run
[23:16:11.356][OptimizeDisk      ][Info   ] Optimize
[23:16:11.356][PowerShell        ][Info   ] Run script...
[23:16:11.371][Moby              ][Info   ] Stop
[23:16:11.387][HyperV            ][Info   ] Destroy
[23:16:11.387][PowerShell        ][Info   ] Run script with parameters: -KeepVolume True -Destroy True -Verbose True -ErrorAction Stop
[23:16:11.434][HyperV            ][Info   ] VM DockerDesktopVM does not exist
[23:16:11.434][HyperV            ][Info   ] Destroying Switch DockerNAT...
[23:16:11.481][HyperV            ][Info   ] Removing VM DockerDesktopVM...
[23:16:11.496][HyperV            ][Debug  ] [destroy] took 00:00:00.1093721 to run
[23:16:11.496][Firewall          ][Info   ] Closing ports...
[23:16:11.496][Firewall          ][Info   ] Removing all existing rules...
[23:16:11.543][Firewall          ][Info   ] All existing rules are removed.
[23:16:11.543][Firewall          ][Info   ] Ports are closed
[23:16:11.543][HyperVGuids       ][Info   ] Removing GUIDs...
[23:16:11.543][HyperVGuids       ][Info   ] GUIDs removed
[23:16:11.543][HyperV            ][Info   ] Create
[23:16:11.543][PowerShell        ][Info   ] Run script with parameters: -Create True -VhdPathOverride C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx -VhdSize 68719476736 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 28 -PreferredIPAddress  -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-desktop.iso -Verbose True -ErrorAction Stop
[23:16:11.700][HyperV            ][Info   ] Creating Switch: DockerNAT...
[23:16:11.817][HyperV            ][Error  ] Unable to create: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunAsync>d__6.MoveNext()
[23:16:11.818][Linux             ][Info   ] Setting container engine status to FailedToStart
[23:16:11.818][NamedPipeServer   ][Error  ] Unable to execute engine/start: Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
   at Docker.Backend.HyperV.Create(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
[23:16:11.839][NamedPipeClient   ][Error  ] Unable to send engine/start: Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
[23:16:11.855][Notifications     ][Error  ] Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
[23:16:11.886][NamedPipeClient   ][Info   ] Sending app/version()...
[23:16:11.886][NamedPipeClient   ][Info   ] Received response for app/version
[23:16:11.886][NamedPipeClient   ][Info   ] Sending diagnostics/gather()...
[23:16:11.886][NamedPipeServer   ][Info   ] app/version()
[23:16:11.886][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[23:16:11.902][NamedPipeServer   ][Info   ] diagnostics/gather()
[23:17:24.912][SegmentApi        ][Info   ] Usage statistic: actionResetToDefault
[23:17:24.974][Notifications     ][Info   ] Docker Desktop will reset to default...
[23:17:25.058][CrashReport       ][Info   ] Diagnostics cancelled by user
[23:17:25.059][NamedPipeClient   ][Info   ] Sending app/version()...
[23:17:25.063][NamedPipeClient   ][Info   ] Received response for app/version
[23:17:25.063][NamedPipeClient   ][Info   ] Sending diagnostics/stop-gather()...
[23:17:25.079][NamedPipeClient   ][Info   ] Received response for diagnostics/stop-gather
[23:17:25.062][NamedPipeServer   ][Info   ] app/version()
[23:17:25.063][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[23:17:25.151][NamedPipeClient   ][Error  ] Unable to send diagnostics/gather: Object reference not set to an instance of an object.
[23:17:25.151][CrashReport       ][Warning] Unable to gather diagnostics in Windows Service : (Object reference not set to an instance of an object.)
[23:17:25.078][NamedPipeServer   ][Info   ] diagnostics/stop-gather()
[23:17:25.151][CrashReport       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\Resources\com.docker.diagnose.exe' gather.
[23:17:25.079][NamedPipeServer   ][Info   ] diagnostics/stop-gather done in 00:00:00.0009984.
[23:17:25.092][NamedPipeServer   ][Error  ] Unable to execute diagnostics/gather: Object reference not set to an instance of an object.    at Docker.Backend.BackendService.GatherDiagnostics()
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[23:17:29.462][DockerAnalytics   ][Error  ] Error getting engine info: Object reference not set to an instance of an object.
[23:17:30.181][DockerAnalytics   ][Error  ] Error getting engine info: Cannot access child value on Newtonsoft.Json.Linq.JValue.
[23:17:30.247][SegmentApi        ][Info   ] Usage statistic: dailyHeartbeat
[23:17:30.247][Notifications     ][Info   ] Docker Desktop is resetting to default...
[23:17:30.328][NamedPipeClient   ][Info   ] Sending app/version()...
[23:17:30.330][NamedPipeServer   ][Info   ] app/version()
[23:17:30.331][NamedPipeServer   ][Info   ] app/version done in 00:00:00.0010004.
[23:17:30.336][NamedPipeClient   ][Info   ] Received response for app/version
[23:17:30.337][NamedPipeClient   ][Info   ] Sending engine/stop(All, Docker.Core.Settings)...
[23:17:30.340][NamedPipeServer   ][Info   ] engine/stop(All, Docker.Core.Settings)
[23:17:30.342][Linux             ][Info   ] Setting container engine status to Stopping
[23:17:30.342][PowerMode         ][Info   ] Stop
[23:17:30.342][HyperV            ][Info   ] Stop
[23:17:30.343][PowerShell        ][Info   ] Run script with parameters: -Stop True -Verbose True -ErrorAction Stop
[23:17:30.418][HyperV            ][Info   ] VM DockerDesktopVM does not exist
[23:17:30.418][HyperV            ][Debug  ] [stop] took 00:00:00.0760020 to run
[23:17:30.418][OptimizeDisk      ][Info   ] Optimize
[23:17:30.418][PowerShell        ][Info   ] Run script...
[23:17:30.435][Moby              ][Info   ] Stop
[23:17:30.447][NamedPipeClient   ][Info   ] Received response for engine/stop
[23:17:30.449][NamedPipeClient   ][Info   ] Sending app/version()...
[23:17:30.451][NamedPipeClient   ][Info   ] Received response for app/version
[23:17:30.451][NamedPipeClient   ][Info   ] Sending engine/destroy(Docker.Core.Settings, All, False)...
[23:17:30.446][Linux             ][Info   ] Setting container engine status to Stopped
[23:17:30.447][NamedPipeServer   ][Info   ] engine/stop done in 00:00:00.1069989.
[23:17:30.450][NamedPipeServer   ][Info   ] app/version()
[23:17:30.450][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[23:17:30.453][NamedPipeServer   ][Info   ] engine/destroy(Docker.Core.Settings, All, False)
[23:17:30.460][GoBackendProcess  ][Info   ] Killing existing com.docker.backend with PID 11308
[23:17:30.470][Linux             ][Info   ] Setting container engine status to Destroying
[23:17:30.470][HyperV            ][Info   ] Destroy
[23:17:30.470][PowerShell        ][Info   ] Run script with parameters: -VhdPathOverride C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx -Destroy True -Verbose True -ErrorAction Stop
[23:17:30.532][HyperV            ][Info   ] VM DockerDesktopVM does not exist
[23:17:30.549][HyperV            ][Info   ] Destroying Switch DockerNAT...
[23:17:30.721][HyperV            ][Info   ] Removing VM DockerDesktopVM...
[23:17:30.735][HyperV            ][Info   ] Delete VHD C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx
[23:17:30.750][HyperV            ][Debug  ] [destroy] took 00:00:00.2806151 to run
[23:17:30.750][Firewall          ][Info   ] Closing ports...
[23:17:30.750][Firewall          ][Info   ] Removing all existing rules...
[23:17:30.776][Firewall          ][Info   ] All existing rules are removed.
[23:17:30.776][Firewall          ][Info   ] Ports are closed
[23:17:30.776][HyperVGuids       ][Info   ] Removing GUIDs...
[23:17:30.776][HyperVGuids       ][Info   ] GUIDs removed
[23:17:30.776][Linux             ][Info   ] Setting container engine status to Destroyed
[23:17:30.836][PowerShell        ][Info   ] Run script with parameters: -RemoveNetworks True
[23:17:32.601][NamedPipeClient   ][Info   ] Received response for engine/destroy
[23:17:32.601][NamedPipeServer   ][Info   ] engine/destroy done in 00:00:02.1473415.
[23:17:32.656][NamedPipeClient   ][Info   ] Sending app/version()...
[23:17:32.656][NamedPipeClient   ][Info   ] Received response for app/version
[23:17:32.656][NamedPipeClient   ][Info   ] Sending version-packs/enable(community, Docker.Core.Settings)...
[23:17:32.666][NamedPipeClient   ][Info   ] Received response for version-packs/enable
[23:17:32.656][NamedPipeServer   ][Info   ] app/version()
[23:17:32.656][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[23:17:32.666][NamedPipeServer   ][Info   ] version-packs/enable(community, Docker.Core.Settings)
[23:17:32.666][NamedPipeServer   ][Info   ] version-packs/enable done in 00:00:00.
[23:17:32.681][NamedPipeClient   ][Info   ] Sending app/version()...
[23:17:32.681][NamedPipeClient   ][Info   ] Received response for app/version
[23:17:32.681][NamedPipeClient   ][Info   ] Sending engine/start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions, )...
[23:17:32.681][NamedPipeServer   ][Info   ] app/version()
[23:17:32.681][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[23:17:32.686][NamedPipeServer   ][Info   ] engine/start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions, )
[23:17:32.696][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\Resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[23:17:32.736][GoBackendProcess  ][Info   ] Started
[23:17:32.736][Linux             ][Info   ] Setting container engine status to Starting
[23:17:32.828][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[23:17:32.831][GoBackendProcess  ][Info   ] time="2019-08-26T23:17:32+05:30" msg="started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl"
[23:17:32.831][GoBackendProcess  ][Debug  ] time="2019-08-26T23:17:32+05:30" msg="socket.ListenVsock: 4098"
[23:17:32.836][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[23:17:32.840][GoBackendProcess  ][Info   ] ⇨ http server started on 00000000-0000-0000-0000-000000000000:00001002-facb-11e6-bd58-64006a7986d3
[23:17:32.860][GoBackendProcess  ][Info   ] listening on 62372 for data connection
[23:17:33.076][PowerMode         ][Info   ] Stop
[23:17:33.076][HyperV            ][Info   ] Stop
[23:17:33.076][PowerShell        ][Info   ] Run script with parameters: -Stop True -Verbose True -ErrorAction Stop
[23:17:33.116][HyperV            ][Info   ] VM DockerDesktopVM does not exist
[23:17:33.116][HyperV            ][Debug  ] [stop] took 00:00:00.0402940 to run
[23:17:33.116][OptimizeDisk      ][Info   ] Optimize
[23:17:33.116][PowerShell        ][Info   ] Run script...
[23:17:33.131][Moby              ][Info   ] Stop
[23:17:33.141][HyperV            ][Info   ] Create
[23:17:33.141][PowerMode         ][Info   ] Start
[23:17:33.141][HyperVGuids       ][Info   ] Installing GUIDs...
[23:17:33.141][Firewall          ][Info   ] Removing all existing rules...
[23:17:33.146][PowerShell        ][Info   ] Run script with parameters: -Create True -VhdPathOverride C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx -VhdSize 68719476736 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 28 -PreferredIPAddress  -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-desktop.iso -Verbose True -ErrorAction Stop
[23:17:33.146][HyperVGuids       ][Info   ] GUIDs installed
[23:17:33.176][Firewall          ][Info   ] All existing rules are removed.
[23:17:33.176][Firewall          ][Info   ] Opening ports for SMB...
[23:17:33.186][Firewall          ][Info   ] Ports are opened
[23:17:33.252][HyperV            ][Info   ] Creating Switch: DockerNAT...
[23:17:33.350][HyperV            ][Error  ] Unable to create: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunAsync>d__6.MoveNext()
[23:17:33.350][Linux             ][Error  ] Failed to start: Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure . Let's retry
[23:17:33.350][Linux             ][Info   ] Setting container engine status to Starting
[23:17:33.450][Installer         ][Info   ] Checking for features: *Hyper-V*, Containers
[23:17:33.451][PowerShell        ][Info   ] Run script...
[23:17:37.499][PowerShell        ][Info   ] Run script...
[23:17:40.882][PowerShell        ][Info   ] Run script...
[23:17:43.509][PowerShell        ][Info   ] Run script...
[23:17:46.483][Installer         ][Info   ] Features installed
[23:17:46.500][HyperV            ][Info   ] Hyper-V is running
[23:17:46.500][PowerMode         ][Info   ] Stop
[23:17:46.500][HyperV            ][Info   ] Stop
[23:17:46.500][PowerShell        ][Info   ] Run script with parameters: -Stop True -Verbose True -ErrorAction Stop
[23:17:46.547][HyperV            ][Info   ] VM DockerDesktopVM does not exist
[23:17:46.547][HyperV            ][Debug  ] [stop] took 00:00:00.0469937 to run
[23:17:46.548][OptimizeDisk      ][Info   ] Optimize
[23:17:46.548][PowerShell        ][Info   ] Run script...
[23:17:46.567][Moby              ][Info   ] Stop
[23:17:46.574][HyperV            ][Info   ] Destroy
[23:17:46.575][PowerShell        ][Info   ] Run script with parameters: -KeepVolume True -Destroy True -Verbose True -ErrorAction Stop
[23:17:46.629][HyperV            ][Info   ] VM DockerDesktopVM does not exist
[23:17:46.631][HyperV            ][Info   ] Destroying Switch DockerNAT...
[23:17:46.666][HyperV            ][Info   ] Removing VM DockerDesktopVM...
[23:17:46.682][HyperV            ][Debug  ] [destroy] took 00:00:00.1083223 to run
[23:17:46.682][Firewall          ][Info   ] Closing ports...
[23:17:46.682][Firewall          ][Info   ] Removing all existing rules...
[23:17:46.732][Firewall          ][Info   ] All existing rules are removed.
[23:17:46.732][Firewall          ][Info   ] Ports are closed
[23:17:46.732][HyperVGuids       ][Info   ] Removing GUIDs...
[23:17:46.734][HyperVGuids       ][Info   ] GUIDs removed
[23:17:46.734][HyperV            ][Info   ] Create
[23:17:46.735][PowerShell        ][Info   ] Run script with parameters: -Create True -VhdPathOverride C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx -VhdSize 68719476736 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 28 -PreferredIPAddress  -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-desktop.iso -Verbose True -ErrorAction Stop
[23:17:46.833][HyperV            ][Info   ] Creating Switch: DockerNAT...
[23:17:46.928][HyperV            ][Error  ] Unable to create: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunAsync>d__6.MoveNext()
[23:17:46.928][Linux             ][Info   ] Setting container engine status to FailedToStart
[23:17:46.929][NamedPipeServer   ][Error  ] Unable to execute engine/start: Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
   at Docker.Backend.HyperV.Create(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
[23:17:46.950][NamedPipeClient   ][Error  ] Unable to send engine/start: Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
[23:17:46.950][Notifications     ][Error  ] Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
[23:17:46.950][NamedPipeClient   ][Info   ] Sending app/version()...
[23:17:46.950][NamedPipeClient   ][Info   ] Received response for app/version
[23:17:46.950][NamedPipeClient   ][Info   ] Sending diagnostics/gather()...
[23:17:46.950][NamedPipeServer   ][Info   ] app/version()
[23:17:46.950][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[23:17:46.950][NamedPipeServer   ][Info   ] diagnostics/gather()
[23:19:28.905][NamedPipeClient   ][Info   ] Received response for diagnostics/gather
[23:19:28.905][NamedPipeServer   ][Info   ] diagnostics/gather done in 00:01:41.9551916.
[23:20:15.776][GUI               ][Info   ] Sending Bugsnag report 2fe2d9d2-6427-490c-9fc9-cf6d7eeab14a...
[23:20:17.896][GUI               ][Info   ] Bugsnag report 2fe2d9d2-6427-490c-9fc9-cf6d7eeab14a sent
[23:20:17.912][CrashReport       ][Info   ] Uploading diagnostics 3832B494-F1E5-4750-A6CE-3F8EC7DEA9B0/20190826174726
[23:20:46.755][CrashReport       ][Info   ] Uploaded succesfully diagnostics 3832B494-F1E5-4750-A6CE-3F8EC7DEA9B0/20190826174726
[23:22:45.067][ErrorReportWindow ][Info   ] Open logs

**Comment by darrenkidd** [comment]
I've got the exact same issue. Version 2.1.0.1, Windows 10 Pro v1903.
Diagnostics ID: `5DB6BA1D-0FF8-416B-AD09-3D381D9CEFC6/20190829101903`.
Have tried all the same "control flow guard" tweaks floating about the Internet but nothing has helped.
