### ISSUE TITLE
Docker - The file size exceeds the limit allowed and cannot be saved.

### ISSUE THREAD

**Issue by dgosche** [docker/for-win#4612]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A5759151-3E31-4270-996C-65E778AF2734/20190829142709

### Expected behavior
Switch to windows containers

### Actual behavior
Docker crashes about The file size exceeds the limit allowed and cannot be saved

### Information

  - Windows Version: Windows 10 Enterprise LTSC 10.0.17763 Build 17763
  - Docker Desktop Version: 2.0.0.3 and 2.1.0.1

### Steps to reproduce the behavior

  1. …  Unfortunately, I haven't been able to create or pull down images to use in docker.  I kept getting an access denied when trying to rename after extracting.
  2. …  This error then started showing up after restarted windows.
  3. …  I've tried updating to latest.  I've used a powershell script that should completely remove Docker, installed the version 2.0.0.3 that I was told works for our environment, try to switch to windows containers and get the error.
  4. …  Resetting to factory defaults doesn't help either.

The file size exceeds the limit allowed and cannot be saved
   at System.Diagnostics.EventLogInternal.get_EntryCount()
   at System.Diagnostics.EventLogInternal.StartListening(String currentMachineName, String currentLogName)
   at System.Diagnostics.EventLogInternal.StartRaisingEvents(String currentMachineName, String currentLogName)
   at System.Diagnostics.EventLogInternal.set_EnableRaisingEvents(Boolean value)
   at Docker.Backend.Processes.WindowsDockerDaemon.StartLogging() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 115
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 232
   at Docker.Backend.Processes.WindowsDockerDaemon.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 165
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 225
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 98
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180

**Comment by dgosche** [comment]
Cleared Event Log for Applications under Windows Logs.  It was upwards of 16M in size.  I found a similar error on this site about this being done to resolve the issue.  I was then able to switch to Windows containers and finally able to download an image to use.
