### ISSUE TITLE
Running Django in a Docker container produces invalid, unremovable files

### ISSUE THREAD

**Issue by ca1ek** [docker/for-win#4621]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: E3123084-09F6-4168-AE6D-A2E0464E08AF/20190901103746

### Expected behavior
No unremovable files are created, containers can be built
### Actual behavior
A file, without the ability to check it's permissions or the owner, even as Administrator is created. It is unopenable, unmovable, can't be deleted, and blocks containers from starting up
### Information

  - Windows Version: Microsoft Windows [Version 10.0.17763.678]
  - Docker Desktop Version: 2.1.0.0 (36874)

### Steps to reproduce the behavior

  1. Create a Django project with default configuration
  2. Start up with dockerfile:
```dockerfile
FROM python:3.7.3

ENV PYTHONUNBUFFERED 1

RUN useradd -ms /bin/bash docker-user

RUN mkdir /static
RUN chown docker-user:docker-user /static
RUN mkdir /up_media
RUN chown docker-user:docker-user /up_media

RUN mkdir /code

WORKDIR /code

COPY ./code/requirements.txt /code/
RUN pip install --no-cache-dir -r requirements.txt

COPY ./code /code
RUN chown -R docker-user:docker-user /code

RUN chmod +x entrypoint.sh

USER docker-user
```
and compose:
```yaml
backend:
    build: .
    command: ./entrypoint.sh
    volumes:
      - ./code:/code
      - static_volume:/static
      - media_volume:/up_media
    ports:
      - 8000:8000
```
and entrypoint.sh:
```bash
#!/usr/bin/env bash
set -e

echo "Cleaning"
find . -name "*.pyc" -exec rm -f {} \;

echo "Migrating"
python manage.py migrate --noinput

echo "Collecting static files"
python manage.py collectstatic --noinput

gunicorn tbn.wsgi:application --reload --bind 0.0.0.0:8000 -w 2

"$@"
```
3. The container builds, but fails to start at the migrations
```
Attaching to tbn_main-db_1, tbn_backend_1, tbn_nginx_1
backend_1  | Cleaning
backend_1  | Migrating
backend_1  | Operations to perform:
backend_1  |   Apply all migrations: admin, auth, contenttypes, sessions
backend_1  | Running migrations:
backend_1  |   Applying contenttypes.0001_initial...Traceback (most recent call last):
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
backend_1  |     return self.cursor.execute(sql)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 381, in execute
backend_1  |     return Database.Cursor.execute(self, query)
backend_1  | sqlite3.OperationalError: unable to open database file
backend_1  |
backend_1  | The above exception was the direct cause of the following exception:
backend_1  |
backend_1  | Traceback (most recent call last):
backend_1  |   File "manage.py", line 21, in <module>
backend_1  |     main()
backend_1  |   File "manage.py", line 17, in main
backend_1  |     execute_from_command_line(sys.argv)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
backend_1  |     utility.execute()
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
backend_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
backend_1  |     self.execute(*args, **cmd_options)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
backend_1  |     output = self.handle(*args, **options)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 83, in wrapped
backend_1  |     res = handle_func(*args, **kwargs)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/core/management/commands/migrate.py", line 234, in handle
backend_1  |     fake_initial=fake_initial,
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 117, in migrate
backend_1  |     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
backend_1  |     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
backend_1  |     state = migration.apply(state, schema_editor)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/migration.py", line 124, in apply
backend_1  |     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/migrations/operations/models.py", line 92, in database_forwards
backend_1  |     schema_editor.create_model(model)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 307, in create_model
backend_1  |     self.execute(sql, params or None)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/base/schema.py", line 137, in execute
backend_1  |     cursor.execute(sql, params)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
backend_1  |     return super().execute(sql, params)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
backend_1  |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
backend_1  |     return executor(sql, params, many, context)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
backend_1  |     return self.cursor.execute(sql, params)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
backend_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 82, in _execute
backend_1  |     return self.cursor.execute(sql)
backend_1  |   File "/usr/local/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 381, in execute
backend_1  |     return Database.Cursor.execute(self, query)
backend_1  | django.db.utils.OperationalError: unable to open database file
```
4. Stop with `^C`
5. A file with the name `db.sqlite3-journal` exists, is rather weird, it's not possible to check it's permissions, the permission window shows that I'm not allowed to check the permissions even as an Administrator

![image](https://user-images.githubusercontent.com/1311686/64075326-37dfb500-ccb7-11e9-9d6a-64cd4049310a.png)

attempting to rename the file:
![image](https://user-images.githubusercontent.com/1311686/64075338-5ba2fb00-ccb7-11e9-8cb8-4f6e8cb1c23f.png)

When attempting to remove the file, I'm told to ask an administrator for permission, even as an administrator
![image](https://user-images.githubusercontent.com/1311686/64075355-8c833000-ccb7-11e9-84d1-ef89fef396b4.png)

6. Attempt to build the container again with `docker-compose up --build`
```
Building backend
Traceback (most recent call last):
  File "site-packages\docker\utils\build.py", line 96, in create_archive
PermissionError: [Errno 13] Permission denied: '\\\\?\\D:\\programowanie\\tbn\\code\\db.sqlite3-journal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1085, in up
  File "compose\cli\main.py", line 1081, in up
  File "compose\project.py", line 527, in up
  File "compose\service.py", line 344, in ensure_image_exists
  File "compose\service.py", line 1084, in build
  File "site-packages\docker\api\build.py", line 159, in build
  File "site-packages\docker\utils\build.py", line 31, in tar
  File "site-packages\docker\utils\build.py", line 100, in create_archive
OSError: Can not read file in context: \\?\D:\programowanie\tbn\code\db.sqlite3-journal
[12696] Failed to execute script docker-compose
```

**Comment by ca1ek** [comment]
A reboot resolves the issue, the file vanished.

**Comment by ca1ek** [comment]
Running the project again, then stopping it and rebuilding, it created an invalid file again and is tripping over it when building again

```
PS D:\programowanie\tbn> docker-compose up --build
Building backend
Traceback (most recent call last):
  File "site-packages\docker\utils\build.py", line 96, in create_archive
PermissionError: [Errno 13] Permission denied: '\\\\?\\D:\\programowanie\\tbn\\code\\tbn\\__pycache__\\__init__.cpython-37.pyc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1085, in up
  File "compose\cli\main.py", line 1081, in up
  File "compose\project.py", line 527, in up
  File "compose\service.py", line 344, in ensure_image_exists
  File "compose\service.py", line 1084, in build
  File "site-packages\docker\api\build.py", line 159, in build
  File "site-packages\docker\utils\build.py", line 31, in tar
  File "site-packages\docker\utils\build.py", line 100, in create_archive
OSError: Can not read file in context: \\?\D:\programowanie\tbn\code\tbn\__pycache__\__init__.cpython-37.pyc
[8536] Failed to execute script docker-compose
```

**Comment by MythreyaK** [comment]
I think this is because the invalid file is being added to docker's build context and since it can't read it, build fails. Try adding a `.dockerignore` file to your project's root folder with the following contents.
```
**/__pycache__
# Add the db file too temporarily, to let the build work
**/*db*
``` 
More info [here](https://docs.docker.com/engine/reference/builder/#dockerignore-file).

**Comment by ca1ek** [comment]
I added the `__pycache__` directory to `.dockerignore`, and it temporarily helped, but it broke moments later, this time the permissions on a webfont file broke
```
PS D:\programowanie\tbn> docker-compose up --build
Building backend
Traceback (most recent call last):
  File "site-packages\docker\utils\build.py", line 96, in create_archive
PermissionError: [Errno 13] Permission denied: '\\\\?\\D:\\programowanie\\tbn\\code\\static\\admin\\fonts\\Roboto-Light-webfont.woff'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1085, in up
  File "compose\cli\main.py", line 1081, in up
  File "compose\project.py", line 527, in up
  File "compose\service.py", line 344, in ensure_image_exists
  File "compose\service.py", line 1084, in build
  File "site-packages\docker\api\build.py", line 159, in build
  File "site-packages\docker\utils\build.py", line 31, in tar
  File "site-packages\docker\utils\build.py", line 100, in create_archive
OSError: Can not read file in context: \\?\D:\programowanie\tbn\code\static\admin\fonts\Roboto-Light-webfont.woff
[9540] Failed to execute script docker-compose
```
I'm not feeling like restarting my PC to get docker back into a usable state, but I think these lines in my Dockerfile might be at fault
```
RUN mkdir /static
RUN chown docker-user:docker-user /static
RUN mkdir /up_media
RUN chown docker-user:docker-user /up_media
```
since the permissions are breaking, and this is the only thing that touches permissions.
