### ISSUE TITLE
Docker desktop crashes

### ISSUE THREAD

**Issue by juanledesma84** [docker/for-win#4650]
It was working properly, but not anymore after 1903 update.

Windows 10 PRO ,1903

Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'XXX' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by juanledesma84** [comment]
I have fixed it following this:

https://shauncassells.wordpress.com/2018/05/24/fix-hyper-v-encountered-an-error-trying-to-access-an-object-on-computer-localhost-because-the-object-was-not-found-the-object-might-have-been-deleted-verify-that-the-virtual-machine-managemen/
