### ISSUE TITLE
Docker uninstalled after update

### ISSUE THREAD

**Issue by mshahzaibwiztech** [docker/for-win#4656]
I just got update notification from docker on 4th Sept 2019, and docker auto uninstalled after installing the new update!

**Comment by iwpnd** [comment]
Can confirm.

It ran through the process of uninstalling the old, but failed upon installing the new version with an error:

`Access to the path 'C:\Program Files\Docker\Docker\resources\CHANGELOG.md' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at CommunityInstaller.UnpackArtifactsStep.<DoAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()`

Now reinstalling with (Docker for Windows Installer.exe) throws the same error, even tho I ran as administrator. It boilds down to being locked out of Docker\resources\ without the possibility  to reclaim access to it for some weird reason.

**Comment by mshahzaibwiztech** [comment]
> Can confirm.
> 
> It ran through the process of uninstalling the old, but failed upon installing the new version with an error:
> 
> `Access to the path 'C:\Program Files\Docker\Docker\resources\CHANGELOG.md' is denied. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize) at CommunityInstaller.UnpackArtifactsStep.<DoAsync>d__31.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()`
> 
> Now reinstalling with (Docker for Windows Installer.exe) throws the same error, even tho I ran as administrator. It boilds down to being locked out of Docker\resources\ without the possibility to reclaim access to it for some weird reason.
> 
> edit: restart released the "lock" from the folder and let me install docker for windows again.
