### ISSUE TITLE
After failed upgrade and re-install, Cannot run program "docker-credential-desktop"

### ISSUE THREAD

**Issue by ericjturley** [docker/for-win#4666]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: `645333BA-CEE5-460D-8533-52F65BEFFD75/20190905194742`

### Information

  - Windows Version: Version	10.0.17763 Build 17763
  - Docker Desktop Version: Varies. See description
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. As of Sept 4th, had latest version. 
  2. New update was offered, accepted, install failed (see below for error).
  3. Went to uninstall, but Docker was not listed as an installed program.
  4. Reinstalled from latest as of Aug 9. `2.1.0.1`
  5. Now, I get:
```
2019-09-05 14:44:57.682  INFO 16120 --- [           main] org.testcontainers.DockerClientFactory   : Connected to docker: 
  Server Version: 19.03.1
  API Version: 1.40
  Operating System: Docker Desktop
  Total Memory: 1980 MB
2019-09-05 14:44:57.736 ERROR 16120 --- [           main] o.t.s.o.z.exec.ProcessExecutor           : Could not start process:

java.io.IOException: Cannot run program "docker-credential-desktop": CreateProcess error=2, The system cannot find the file specified
```

Error during upgrade:
```
Docker update installation failed
The directory is not empty.


   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
```

**Comment by ericjturley** [comment]
Even after installing the latest it fails.
Even after resetting to factory defaults, it fails.

**Comment by ericjturley** [comment]
Removing `"credsStore":"desktop"` from `config.json` caused the error logging to stop.

Looks like it was functional either way.

Looks like it was related to a [testcontainers issue](https://github.com/testcontainers/testcontainers-java/issues/921) that had been logged previously
