### ISSUE TITLE
Unable to successfully change bridge network address

### ISSUE THREAD

**Issue by iancward** [docker/for-win#4668]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: BE9B731E-9165-4813-A688-3697BCB5FD24/20190906022037

### Expected behavior
Docker should be able to successfully reconfigure bridge network and also be able to re-establish docker VM when it goes away

### Actual behavior
```
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

### Information

  - Windows Version: Windows 10 Enterprise, Version 1809, Build 17763.557
  - Docker Desktop Version: 2.0.1.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Directly on Windows

### Steps to reproduce the behavior

  1. Install Docker Desktop
  2. Attempt to reconfigure subnet to 
  3. Receive failure notification above

I tried the "Reset to Factory Defaults" to no avail. The only way I could get it to work again was to uninstall Docker Desktop for Windows, Remove all AppData directories, remove the DockerNAT Hyper-V network switch, and disable and re-enable Enhanced Session Mode Policy. I was then able to re-install Docker Desktop for Windows and successfully reconfigured bridge network. Things were running fine until all of a sudden several days (and several computer restarts) later, docker desktop failed to start and I'm back where I started.

### Logs and Analysis
In the logs, I see this:
```
[22:20:29.839][PowerShell        ][Info   ] Run script with parameters: -Create True -VhdPathOverride C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx -VhdSize 68719476736 -SwitchSubnetAddress 172.23.0.0 -SwitchSubnetMaskSize 24 -PreferredIPAddress  -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-desktop.iso -Verbose True -ErrorAction Stop
[22:20:29.976][HyperV            ][Info   ] Creating Switch: DockerNAT...
[22:20:33.129][HyperV            ][Info   ] Switch created.
[22:20:33.391][HyperV            ][Info   ] Setting docker switch IP address to 172.23.0.1
[22:20:33.429][HyperV            ][Info   ] Removing any other IP addresses from DockerNAT switch
[22:20:37.068][HyperV            ][Info   ] Creating VM DockerDesktopVM...
[22:20:37.360][HyperV            ][Error  ] Unable to create: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.
```
When I attempt to run the powershell script in question, `MobyLinux.ps1`, with the specified options, I get the following output:
```
PS C:\Program Files\Docker\Docker\resources> .\MobyLinux.ps1 -Create True -VhdPathOverride C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx -VhdSize 68719476736 -SwitchSubnetAddress 172.23.0.0 -SwitchSubnetMaskSize 24 -PreferredIPAddress  -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-desktop.iso -Verbose True -ErrorAction Stop
C:\Program Files\Docker\Docker\resources\MobyLinux.ps1 : Missing an argument for parameter 'PreferredIPAddress'.
Specify a parameter of type 'System.String' and try again.
At line:1 char:181
+ ... dress 172.23.0.0 -SwitchSubnetMaskSize 24 -PreferredIPAddress  -CPUs  ...
+                                               ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [MobyLinux.ps1], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,MobyLinux.ps1
```
It appears that something that is determining the powershell script needs to run is not properly able to determine what the `PreferredIpAddress` value should be and therefore leaves it blank.

**Comment by iancward** [comment]
After futzing with this, I decided to futz with another VM that also started to act weird made me realize that the other VM had been unable to mount a disc ISO and that it had probably become "stuck" with a windows file lock (yay windows). I restarted the Hyper-V Virtual Machine management service (which I now remember I did to get Docker working the first time) and now both my VM and the Moby VM are working.

**Comment by iancward** [comment]
Docker updated itself the other day, right before I shut down at the end of the day. When I came back in the following day, I ran into the same issue where Docker failed to start. I restarted the same "Hyper-V Virtual Machine Management" service and restarted Docker and things seemed to work again.

My assumption at this point is that it has something to do with the file handle on the Moby iso not being released. Restarting the management service forcibly releases the handle, which allows the subsequent run of Docker Desktop to create a VM, attach the iso, and boot it.

**Comment by iancward** [comment]
This just happened to me again today; can this issue be re-opened?

**Comment by iancward** [comment]
This is now happening every time I start my computer and it starts Docker for Windows. It looks like the Moby VM has been destroyed and Docker for Windows has been unable to re-create it, even after I restart the Hyper-V Virtual Machine Manager service. 

The logs show that creation of the VM failed, but don't exactly explain why
```
[09:47:50.021][PowerShell        ][Info   ] Run script with parameters: -Create True -VmName DockerDesktopVM -VhdPathOverride C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx -VhdSize 68719476736 -SwitchSubnetAddress 172.23.0.0 -SwitchSubnetMaskSize 24 -PreferredIPAddress  -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\resources\docker-desktop.iso -SwitchName  -Verbose True -ErrorAction Stop
[09:47:50.096][HyperV            ][Info   ] Creating VM DockerDesktopVM...
[09:47:50.189][NamedPipeClient   ][Error  ] Unable to send engine/start: Docker.Core.Backend.BackendDestroyException:
Unable to create Hyper-V VM: Creating the virtual machine failed.
at New-MobyLinuxVM, <No file>: line 397
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  System.Management.Automation.RuntimeException:
  Unable to create Hyper-V VM: Creating the virtual machine failed.
  at New-MobyLinuxVM, <No file>: line 397
  at New-MobyLinux, <No file>: line 182
  at <ScriptBlock>, <No file>: line 810
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.HyperV.Create(Settings settings)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     Creating the virtual machine failed.
     
         Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException:
         Creating the virtual machine failed.
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation, Boolean throwIfAffectedElementNotFound)
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation)
            at Microsoft.Virtualization.Client.Management.VMServiceView.EndCreateVirtualSystem[T](IVMTask task)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
            at Microsoft.HyperV.PowerShell.VirtualMachine.Create(Server server, String name, String location, Int32 generation, Version version, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateVirtualMachine(Server server, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateObjects(IOperationWatcher operationWatcher)
         
[09:47:50.192][Notifications     ][Error  ] Docker.Core.Backend.BackendDestroyException:
Unable to create Hyper-V VM: Creating the virtual machine failed.
at New-MobyLinuxVM, <No file>: line 397
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  System.Management.Automation.RuntimeException:
  Unable to create Hyper-V VM: Creating the virtual machine failed.
  at New-MobyLinuxVM, <No file>: line 397
  at New-MobyLinux, <No file>: line 182
  at <ScriptBlock>, <No file>: line 810
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.HyperV.Create(Settings settings)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     Creating the virtual machine failed.
     
         Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException:
         Creating the virtual machine failed.
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation, Boolean throwIfAffectedElementNotFound)
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation)
            at Microsoft.Virtualization.Client.Management.VMServiceView.EndCreateVirtualSystem[T](IVMTask task)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
            at Microsoft.HyperV.PowerShell.VirtualMachine.Create(Server server, String name, String location, Int32 generation, Version version, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateVirtualMachine(Server server, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateObjects(IOperationWatcher operationWatcher)
         
[09:47:50.188][HyperV            ][Error  ] Unable to create Hyper-V VM: Microsoft.HyperV.PowerShell.VirtualizationException: Creating the virtual machine failed. ---> Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException: Creating the virtual machine failed.
   at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
   at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation, Boolean throwIfAffectedElementNotFound)
   at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation)
   at Microsoft.Virtualization.Client.Management.VMServiceView.EndCreateVirtualSystem[T](IVMTask task)
   at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
   at Microsoft.HyperV.PowerShell.VirtualMachine.Create(Server server, String name, String location, Int32 generation, Version version, IOperationWatcher operationWatcher)
   at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateVirtualMachine(Server server, IOperationWatcher operationWatcher)
   at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateObjects(IOperationWatcher operationWatcher)
   --- End of inner exception stack trace ---
at New-MobyLinuxVM, <No file>: line 397
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810
[09:47:50.188][Linux             ][Info   ] Setting container engine status to FailedToStart
[09:47:50.188][NamedPipeServer   ][Error  ] Unable to execute engine/start:
Docker.Core.Backend.BackendDestroyException:
Unable to create Hyper-V VM: Creating the virtual machine failed.
at New-MobyLinuxVM, <No file>: line 397
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  System.Management.Automation.RuntimeException:
  Unable to create Hyper-V VM: Creating the virtual machine failed.
  at New-MobyLinuxVM, <No file>: line 397
  at New-MobyLinux, <No file>: line 182
  at <ScriptBlock>, <No file>: line 810
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.HyperV.Create(Settings settings)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     Creating the virtual machine failed.
     
         Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException:
         Creating the virtual machine failed.
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation, Boolean throwIfAffectedElementNotFound)
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation)
            at Microsoft.Virtualization.Client.Management.VMServiceView.EndCreateVirtualSystem[T](IVMTask task)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
            at Microsoft.HyperV.PowerShell.VirtualMachine.Create(Server server, String name, String location, Int32 generation, Version version, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateVirtualMachine(Server server, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateObjects(IOperationWatcher operationWatcher)
         
[09:47:50.222][GUI               ][Info   ] Sending Bugsnag report b3dfa815-42d2-4f9e-9566-8c67b4f75fed...
[09:47:50.439][GUI               ][Info   ] Bugsnag report b3dfa815-42d2-4f9e-9566-8c67b4f75fed sent
[09:47:50.441][SegmentApi        ][Info   ] Usage statistic: eventCrash
[09:47:50.452][NamedPipeClient   ][Info   ] Sending app/version()...
[09:47:50.453][NamedPipeClient   ][Info   ] Received response for app/version
[09:47:50.453][NamedPipeClient   ][Info   ] Sending diagnostics/gather()...
[09:47:50.453][NamedPipeServer   ][Info   ] app/version()
[09:47:50.453][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[09:47:50.454][NamedPipeServer   ][Info   ] diagnostics/gather()
[09:48:24.194][ErrorReportWindow ][Info   ] Open logs
[09:50:41.989][NamedPipeClient   ][Info   ] Received response for diagnostics/gather
[09:50:41.989][NamedPipeServer   ][Info   ] diagnostics/gather done in 00:02:51.5342075.
[09:53:02.031][Diagnostics       ][Info   ] Diagnostics cancelled by user
[09:53:02.032][NamedPipeClient   ][Info   ] Sending app/version()...
[09:53:02.034][NamedPipeClient   ][Info   ] Received response for app/version
[09:53:02.034][NamedPipeClient   ][Info   ] Sending diagnostics/stop-gather()...
[09:53:02.035][NamedPipeClient   ][Info   ] Received response for diagnostics/stop-gather
[09:53:02.033][NamedPipeServer   ][Info   ] app/version()
[09:53:02.033][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[09:53:02.035][NamedPipeServer   ][Info   ] diagnostics/stop-gather()
[09:53:02.035][NamedPipeServer   ][Info   ] diagnostics/stop-gather done in 00:00:00.
```
