### ISSUE TITLE
Time out has expired and the operation has not been completed."

### ISSUE THREAD

**Issue by sinisa-susnjar** [docker/for-win#4684]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3591657D-C368-4F9C-BB8A-543B971B4C9C/20190909091852

### Expected behavior

Docker Desktop starts.

### Actual behavior

Docker Desktop does not start.
Error Message shown:

```
Time out has expired and the operation has not been completed.

   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env)
   at Docker.Backend.Processes.WindowsDockerDaemon.Start(Settings settings, String daemonOptions, Boolean useProtectedNamedPipe)
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_4(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

```

### Information

  - Windows Version: Windows 10 Enterprise v1809 build 17763.720 64bit
  - Docker Desktop Version: 2.1.0.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install stable Docker Desktop on a Windows 10 machine
  2. Make sure to tick "Use Windows containers instead of Linux containers"
  3. Installation works fine, but Docker Desktop won't start afterwards
  4. "Reset to factory defaults" did not help, neither did reinstalling

Probably related to https://github.com/docker/for-win/issues/1419

**Comment by RobertDiebels** [comment]
Encountering this as well.
