### ISSUE TITLE
Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: [localhost] The 

### ISSUE THREAD

**Issue by RA40011109** [docker/for-win#4711]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: [localhost] The background process reported an error with the following message: .
at Stop-VM-Force, <No file>: line 347
at Stop-MobyLinuxVM, <No file>: line 311
at <ScriptBlock>, <No file>: line 392
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

**Comment by RA40011109** [comment]
Please help us anyone who knows to resolve this issue.  ASAP

**Comment by darrenkidd** [comment]
You can downgrade to **2.0.0.3** (Stable).

See [this comment](https://github.com/docker/for-win/issues/4685#issuecomment-530288265) in my related issue.
