### ISSUE TITLE
Docker for Desktop edge/beta fails to install

### ISSUE THREAD

**Issue by trondhindenes** [docker/for-win#4714]
This happened both for an upgrade and for a clean install:
This binary: `https://download.docker.com/win/edge/38030/Docker%20Desktop%20Installer.exe`
```
[15:08:51.144] [InstallWorkflow] Failed to register product
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
Exception type: System.IO.IOException, Exception message: The process cannot access the file 'C:\Program Files\Docker\Docker\Docker Desktop Installer.exe' because it is being used by another process., StackTrace:
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at CommunityInstaller.RegisterProductStep.Register(String basePath, Manifest manifest, String manifestJson)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
[15:08:51.145] [InstallWorkflow] Installation failed
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
Exception type: System.IO.IOException, Exception message: The process cannot access the file 'C:\Program Files\Docker\Docker\Docker Desktop Installer.exe' because it is being used by another process., StackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
   at CommunityInstaller.RegisterProductStep.Register(String basePath, Manifest manifest, String manifestJson)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
[15:08:52.446] [InstallWorkflow] Undo action failed
Exception type: System.UnauthorizedAccessException, Exception message: Access to the path 'Docker Desktop Installer.exe' is denied., StackTrace:
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at CommunityInstaller.UnpackArtifactsStep.<UndoAsync>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<Rollback>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
```

**Comment by trondhindenes** [comment]
as far as I can see from the chocolatey log, when this happens the installer does _not_ produce a non-zero error code, so the system believes everything is fine. Which it is not.

**Comment by trondhindenes** [comment]
a reboot helped, btw. Tho I couldn't find the process it complained about running before rebooting either.

**Comment by StefanScherer** [comment]
So, the clean install had something left from the previous update that may caused the error.? 🤔

What‘s the current state? Docker Desktop is installed and running after the reboot?

Would love to learn more to have a similar environment to reproduce the problem.

**Comment by trondhindenes** [comment]
After reboot I could install it without problems.
Probably a tricky one to repro, but it was essentially an upgrade from an older docker beta to the latest. I'm afraid I don't have more info
