### ISSUE TITLE
Can't start... even with factory-reset.

### ISSUE THREAD

**Issue by mrPsycho** [docker/for-win#4742]
- [*] I have tried with the latest version of my channel (Stable or Edge)
  - [*] I have uploaded Diagnostics
  - Diagnostics ID: 22018EEA-90EB-4560-BC13-82B8F0BC71CC/20190917140725

### Expected behavior
it starts and works

### Actual behavior
```
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Creating the virtual machine failed.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass27_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

### Steps to reproduce the behavior
  1. I don't know, but may be related to the error while it was upgraded.

**Comment by mrPsycho** [comment]
ok. fixed it with reinstalling and rebooting.
