### ISSUE TITLE
Hyper-V was unable to find a virtual switch with name "DockerNAT"

### ISSUE THREAD

**Issue by AliagaMusayev** [docker/for-win#4751]
Hi
I can not start Docker Desktop for Windows. Before there was not any problem, but it is already 2 days I can not start docker. Docker gives me an error message like:

Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".
at New-Switch, <No file>: line 117
at <ScriptBlock>, <No file>: line 394
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 77
   at Docker.Actions.<>c__DisplayClass16_0.<Start>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 61
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59

OS: Windows 10 Enterprise
I attach log file also
[log.txt](https://github.com/docker/for-win/files/3625148/log.txt)

**Comment by AliagaMusayev** [comment]
Docker version 18.06.1-ce-win73

**Comment by JohnCrist1988** [comment]
Docker for Windows creates a virtual switch within Hyper-V called DockerNAT. Was this virtual switch by chance accidentally deleted? Can you confirm that the switch doesn't exist?

**Comment by AliagaMusayev** [comment]
@JohnCrist1988 , before starting docker, in Hyper-V Manager there is no any DockerNAT virtual switch. 
But after starting docker we can se DockerNat virtual switch. I put screenshots before and after starting docker

Before docker start
![image](https://user-images.githubusercontent.com/32015719/65302442-44577f00-db8c-11e9-9c56-81ba25f8dc7a.png)


During docker start DockerNAT creates automatically
![image](https://user-images.githubusercontent.com/32015719/65302622-ca73c580-db8c-11e9-88be-786db6b7f158.png)

Although DockerNAT created during docker start, but docker raises error message:
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by AliagaMusayev** [comment]
Please help to fix the issue. It is already 5 days I can not use docker desktop
