### ISSUE TITLE
Timed out waiting for the lifecycle-server  to start

### ISSUE THREAD

**Issue by Quophi74** [docker/for-win#4774]
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by punkouter2018** [comment]
I get this every day I boot up and leave machine on

**Comment by pleonex** [comment]
I get this error all the time after the update 2.2.0.3 (42716). I am running on a physical machine (no VM). Report ID: 4A77728F-60A3-4A6D-B1E6-2D259B18B737/20200214070951

**Comment by kcragin** [comment]
I too get this on 2.2.0.3.

**Comment by user-ZJ** [comment]
I also meet the problem at windows platform. Is there any solutions?
