### ISSUE TITLE
Docker Desktop VM failed to start

### ISSUE THREAD

**Issue by sandeepgupta721** [docker/for-win#4793]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: Window 10 Pro
  - Docker Desktop Version: 2.1
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Citrix Machine

Unable to start - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'DockerDesktopVM' failed to start.

Failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running.

'DockerDesktopVM' failed to start. (Virtual machine ID 5A343F79-7B1F-4DCF-8949-45736C9DD066)

The Virtual Machine Management Service failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running (Virtual machine ID 5A343F79-7B1F-4DCF-8949-45736C9DD066).

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by crimdon** [comment]
#metoo
