### ISSUE TITLE
Crash on Docker start - Access to .userprofiles is denied

### ISSUE THREAD

**Issue by Unknow0059** [docker/for-win#4814]
- [x] **I have tried with the latest version of my channel (Stable or Edge)**
Not sure what that means. Just the program version? I got it from the hub/onboarding page so it's probably the stable one.
  - [x] **I have uploaded Diagnostics**
  - **Diagnostics ID:**
F71449AF-5BFA-4AAB-9759-EDDA1B15D91B/20190927001323
### Expected behavior
I expected to be able to use Docker for Windows Desktop upon launching it.
### Actual behavior
Error/crash:
```
Access to the path 'C:\ProgramData\DockerDesktop\.userprofiles' is denied.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at Docker.Backend.BackendService.Start(ContainerEngineMode mode, Settings settings, DaemonOptions daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_4(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information
Please, help us understand the problem.  For instance:
  - **Is it reproducible?**
I don't know.
  - **Is the problem new?**
It seems to be. I didn't find any info about it on the web nor on the issues repo. I found similar `access to path denied` errors but none regarding the `.userprofiles` file.
  - **Did the problem appear with an update?**
No. This is the first time I've installed Docker - it happened before I was prompted to update the program after installing, but it also happened even after I updated.  The update I'm referring to here is the `Kitematic 0.17.8` upgrade.
I tried reinstalling Docker to see if it would fix the problem, it didn't.
  - **Windows Version:**
```
ProductName    - Windows 10 Pro
WindowsVersion - 1903
WindowsBuild   - 10.0.18362.239
```
  - **Docker Desktop Version:** 2.1.0.1
Not sure why I have to put the app version here since it's in the logfile.
  - **Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:**
I'm not running inside a virtualized Windows.
### Steps to reproduce the behavior

  1. Install Docker for Windows Desktop (Stable channel) .
  2. Start the program.

**Comment by mat007** [comment]
You can delete this file safely, it will be re-created.
Does the error persist after doing this?

**Comment by Unknow0059** [comment]
I uninstalled Docker soon after the error, so I won't be able to test that.
But I accept that as the solution, so this can now be closed.
