### ISSUE TITLE
 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'

### ISSUE THREAD

**Issue by NitinM3** [docker/for-win#4817]
I'm getting below error while starting docker for desktop on my new windows 10 laptop.  A crash report has been uploaded with diagnostic id:**9787EA25-B1A0-4E9E-B411-E86656F5C7D8/20190927093819**

```
Unable to stop - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

**Comment by wpulsifer** [comment]
After upgrading to Windows version 1903 and to Docker for Desktop 2.1.0.3 (stable) I encountered the same error.  I found the following solution, which worked for me:

https://github.com/docker/for-win/issues/3597#issuecomment-474949164

**Comment by NitinM3** [comment]
I dont find `C:\WINDOWS\System32\vmcompute.exe` settings in my machine.
