### ISSUE TITLE
Timed out waiting for the lifecycle-server to start.

### ISSUE THREAD

**Issue by syed1605** [docker/for-win#4853]
3200A0CB-2EEC-4DF3-BF0E-E59FE46DEB84/20191001200020
[log.txt](https://github.com/docker/for-win/files/3678395/log.txt)

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by syed1605** [comment]
Every time I restart my laptop I get this error message
Timed out waiting for the lifecycle-server to start.
The id of my debug log is: 3200A0CB-2EEC-4DF3-BF0E-E59FE46DEB84/20191001200020
Kindly help!
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
