### ISSUE TITLE
Docker CE for Windows - SSL connection could not be established. remote certificate is invalid according to the validation procedure.

### ISSUE THREAD

**Issue by gireeshspr** [docker/for-win#4858]
I am having an SSL issue when calling https url (like https://sample/demoapi/api/item/ or https://msn.com etc.) from a containerized .net core 2.2 API.  The API works fine when run outside of container. 

Note: The container works perfect when mounting the ssl folder from the Docker thin Linux VM to the container.
docker run -itd -p 5011:80 -v /etc/ssl/certs:/etc/ssl/certs 

### Information
  - Windows Version: Win 10
  - Docker for windows CE Version: Docker CE 2.0.0.3 (not the latest. I have DNS name resolution issue when calling a URL from a container with the latest docker CE. Docker 2.0.0.3 is the one found working without issues)
  - Docker is running on windows 10 machine not on VM. Running Linux host and containers. 

I have followed the following resolutions to copy and update the ssl certificate onto the container but didn't work.
https://stackoverflow.com/questions/52261388/linux-docker-system-security-authentication-authenticationexception-the-remote?rq=1
https://stackoverflow.com/questions/42292444/how-do-i-add-a-ca-root-certificate-inside-a-docker-image

### details
  - [x ] I have tried with the following version of my channel (Stable or Edge)                        
          - Version 2.0.0.3 (31259), Channel: stable, Build: 8858db3
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 61FE5A46-0A29-4800-B5C1-4BC49D22DC56/20191002122430

### Expected behavior
    Containerized application should be able to connect to SSL and return expected result

### Actual behavior
Error received: 
at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at demoapiapp1.Controllers.ValuesController.Get(Int32 id) in C:\dev\Controllers\ItemsController.cs:line 41 ----- The SSL connection could not be established, see inner exception. <--------------------> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)

### Steps to reproduce the behavior
1. Create a sample .net core api and call an https service as follows. 
 try
            {
                var client = new HttpClient();
                var resp = await client.GetAsync("https://msn.com");
                data = await resp.Content.ReadAsStringAsync();
            }
            catch(Exception e)
            {
                data = e.StackTrace + "- " + e.Message + "  - " + e.InnerException;
            }
}
2. Publish the application as specified above 
   Application type: .net core 2.2 api
   Publish configuration: 
    Target framework: .netcoreapp2.2
    Deployment method: self-contained 
    Target run time: linux-x64
3. Build image using the docker file
   FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
   COPY Publish/ app/
   COPY ./certf.crt /usr/local/share/ca-certificates/certf.crt
   RUN chmod 644 /usr/local/share/ca-certificates/certf.crt && update-ca-certificates
   ENTRYPOINT ["dotnet", "app/testapp1.dll"]
4. Run docker command - docker run -itd -p 5011:80 --name demoapi demoapi
5. Browse the url http://localhost:5011/api/vales/ and see the error

**Comment by rensa** [comment]
Not sure if this is the same thing, but I was having a [similar issue ](https://github.com/r-lib/gargle/issues/111) authenticating to an API inside a container (totally different stack, mind—it was reaching out to Google Drive API from R), and it turned out to be a slow system clock, likely because of https://github.com/docker/for-win/issues/72. In my case the API returned 400 with a time-related error message, but I get the feeling that if current time is used to sign all sorts of requests, it could be the sort of bug that manifests in a variety of ways.

Just as a sanity check, you might wanna see if `date` reports something accurate. Mine was two days slow, and my auth problems vanished as soon as I manually changed it @_@

**Comment by gireeshspr** [comment]
Found the problem and resolved it. Posting this to help anyone who experience the same problem.

I used wrong certificate. The certificate to be used is the certificate authority certificate (root certificate) but I used the certificate issued to the system. I generated the root certificate from the chain and imported to container using the 'stakoverlow' resolution referenced above.

Resolution: The ca certificate is named as ca-cert.crt. Added the following lines the Dockerfile.

COPY ca-cert.crt /usr/local/share/ca-certificates/ca-cert.crt RUN chmod 644 /usr/local/share/ca-certificates/ca-cert.crt && update-ca-certificates

**Comment by parmindersinghkpt** [comment]
Hi gireeshspr
Thanks for the direction!!

Would you please give steps how you generate certificate.
And at which place in docker file we need to add the following lines:

COPY ca-cert.crt /usr/local/share/ca-certificates/ca-cert.crt RUN chmod 644 /usr/local/share/ca-certificates/ca-cert.crt && update-ca-certificates
