### ISSUE TITLE
Hyper-V was unable to find a virtual switch with name "DockerNAT"

### ISSUE THREAD

**Issue by AliagaMusayev** [docker/for-win#4869]
Hi, 
I can not start docker desktop on my Windows 10 laptop. It gives me an error message below:

Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual switch with name "DockerNAT".

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

I add log file here
[log.txt](https://github.com/docker/for-win/files/3689091/log.txt)

### Information

  - Windows Version: Windows 10 Enterprise
  - Docker Desktop Version: 2.1.0.3 (38240)
  - Diagnostics ID: 1D198B28-6359-4065-9176-93292616C58A/20191004050320

  1. Just try to start docker desktop

**Comment by AliagaMusayev** [comment]
Problem solved. 
To fix the issue follow the instructions which write in the document below 
https://support.microsoft.com/en-us/help/3101106/you-cannot-create-a-hyper-v-virtual-switch-on-64-bit-versions-of-windo

Then restart the PC, and open Hyper-V Manager. Then open Virtual Switch manager. Then create new  virtual switch with name DockerNAT

![image](https://user-images.githubusercontent.com/32015719/66187078-00d53880-e695-11e9-85e0-c83e74070ef6.png)
