### ISSUE TITLE
Docker Desktop service is not installed

### ISSUE THREAD

**Issue by TatyanaProkhoryatova** [docker/for-win#4871]
I got this error when running Docker Desktop on win 10 Pro

Docker Desktop service is not installed
   at Docker.WPF.BackendClient.CheckService(String action)
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters)
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

5F22E8C6-E84D-42F4-AF13-B9841AED020D/20191004114308

**Comment by TatyanaProkhoryatova** [comment]
Issue was fixed after updating Docker Desktop to a new version.
