### ISSUE TITLE
Docker Desktop 2.1.0.1 installation falied

### ISSUE THREAD

**Issue by harshalsojitra** [docker/for-win#4873]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by harshalsojitra** [comment]
The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Runtime.InteropServices.ComTypes.IPersistFile.Save(String pszFileName, Boolean fRemember)
   at CommunityInstaller.ShortcutAction.DoAsync(CancellationToken cancelToken)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackage>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
