### ISSUE TITLE
Docker fails to start: 'MobyLinuxVM' failed to start worker process: An invalid HANDLE was specified.

### ISSUE THREAD

**Issue by mjquigley** [docker/for-win#503]
### Expected behavior
Docker starts succesfully 
### Actual behavior
Docker fails to start and displays the following error
```
[16:02:41.508][NamedPipeServer][Error  ] Unable to execute Restart: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID A4A9BEC6-25D8-42E7-86D9-3549215451CF)

'MobyLinuxVM' failed to start worker process: An invalid HANDLE was specified. (0xC0000008). (Virtual machine ID A4A9BEC6-25D8-42E7-86D9-3549215451CF)
at Start-MobyLinuxVM, <No file>: line 281
at <ScriptBlock>, <No file>: line 376    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[16:02:41.518][NamedPipeClient][Error  ] Unable to send Restart: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID A4A9BEC6-25D8-42E7-86D9-3549215451CF)

'MobyLinuxVM' failed to start worker process: An invalid HANDLE was specified. (0xC0000008). (Virtual machine ID A4A9BEC6-25D8-42E7-86D9-3549215451CF)
at Start-MobyLinuxVM, <No file>: line 281
at <ScriptBlock>, <No file>: line 376
[16:02:41.518][Notifications  ][Error  ] Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID A4A9BEC6-25D8-42E7-86D9-3549215451CF)

'MobyLinuxVM' failed to start worker process: An invalid HANDLE was specified. (0xC0000008). (Virtual machine ID A4A9BEC6-25D8-42E7-86D9-3549215451CF)
at Start-MobyLinuxVM, <No file>: line 281
at <ScriptBlock>, <No file>: line 376
```
### Information
Diagnostic ID:  FB75CB56-6738-46B8-A624-6311000D4192/2017-02-15_16-33-54

System information:
Windows 10 Enterprise
Version 1607
Build 14393.693

Docker Version: 1.13.1-beta42 (10069)

### Steps to reproduce the behavior

  1. Start docker 
  2. Docker fails to start and displays an error message

I also tested by reinstalling the latest stable build and got the same issue and attempted disabling and reenabling Hyper-V.

**Comment by wh1t3rabbit** [comment]
Experiencing the same. Made sure virtualisation enabled in BIOS and HyperV running. Same error with the same line numbers. 

```
[22:21:01.133][NamedPipeServer][Error  ] Unable to execute Start: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 7CB52D37-B7E6-4CBA-8A8B-BE1678F142D0)

'MobyLinuxVM' failed to start worker process: The process terminated unexpectedly. (0x8007042B). (Virtual machine ID 7CB52D37-B7E6-4CBA-8A8B-BE1678F142D0)
at Start-MobyLinuxVM, <No file>: line 281
at <ScriptBlock>, <No file>: line 376    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[22:21:01.392][NamedPipeClient][Error  ] Unable to send Start: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 7CB52D37-B7E6-4CBA-8A8B-BE1678F142D0)

'MobyLinuxVM' failed to start worker process: The process terminated unexpectedly. (0x8007042B). (Virtual machine ID 7CB52D37-B7E6-4CBA-8A8B-BE1678F142D0)
at Start-MobyLinuxVM, <No file>: line 281
at <ScriptBlock>, <No file>: line 376
```

**Comment by rneugeba** [comment]
Thanks for the reports. The logs sadly don't contain much more information. The error is from the powershell cmdlet `Start-VM`. I gather that Docker for Windows used to work (1.13.0) but doesn't anymore. Did this happen during the upgrade to 1.13.1 or after? The Logs are a bit inconclusive here. We didn't really change much in the application between 1.13.0 and 1.13.1. I also saw no Windows updates etc which may have changed the system, so this is a bit weird.

@wh1t3rabbit could you supply a diagnostics ID? While you seem to have the same error, it may help us to find commonalities between the systems.

A few questions/suggestions:
- Are you running any third party security/antivirus/firewall software?
- can you try, quitting the app, and then from an elevated powershell in `C:\Program Files\Docker\Docker\resources\` execute `.\MobyLinux.ps1 -destroy`, followed by `.\MobyLinux.ps1 -create`. The execute `Start-VM MobyLinuxVM` directly.
- If this doesn't work, could you open Hyper-V Manager and try starting the VM from there?
- If that doesn't work could you try creating an empty VM in Hyper-V Manager? Just click on new VM and then just go through all the defaults. Once done start the VM. You should get a concole window saying it couldn't find a boot medium or somesuch.

Thanks

**Comment by mjquigley** [comment]
Docker worked on 1.13.0.  After upgrading to 1.13.1 it continued to work until I rebooted my machine.  

I am running some McAfee security suite (unfortunately I don't have permissions to disable this to see if it's the source of the problem)

I tried the recommend steps, I couldn't get any VMs to start in Hyper-V.

**Comment by rneugeba** [comment]
@mjquigley Thanks for the quick response. This then does not seem to be a issue specific to Docker for Windows but somethings seems to stop Hyper-V from working...sigh

Could you try disabling the Hyper-V feature from the UI (`Apps and Features`) and then reboot. Enable it again and then reboot?

Alternatively (or in parallel) can you ask your IT department, if you have such a thing, if they changed any security policies etc which could prevent Hyper-V VMs to be started?

**Comment by mjquigley** [comment]
I tried disabling and re-enabling Hyper-V, didn't seem to have any affect.

I tried reaching out to our IT department but they weren't very helpful with providing the information I asked for.  I'll try again this afternoon and see if I can get some more information out of them.

**Comment by urbanhusky** [comment]
I'm having similar issues.

```
[10:15:37.432][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer 'SF-THOMAS-MUEHL' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at New-MobyLinuxVM, <No file>: line 218
at <ScriptBlock>, <No file>: line 375    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[10:15:37.485][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer 'SF-THOMAS-MUEHL' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at New-MobyLinuxVM, <No file>: line 218
at <ScriptBlock>, <No file>: line 375
[10:15:37.487][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer 'SF-THOMAS-MUEHL' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at New-MobyLinuxVM, <No file>: line 218
at <ScriptBlock>, <No file>: line 375
```

Diagnostics ID 6B2300CA-5EC9-4040-A206-229AA6867BA9/2017-02-28_10-17-28

This is happening since a very recent update.
I'm running ESET Internet Security (but the license expired so Windows Defender took over).

**Comment by mjquigley** [comment]
I tried removing my antivirus software but the issue persists.

**Comment by blop** [comment]
Tested latest version of docker for windows (both stable and edge) on a fresh windows 10 install.
Got the same error message, it's not even starting !

Is someone actually using this ?

**Comment by mjquigley** [comment]
I found the cause of the issue for me at least. I uninstalled the Intel Unite Client that my office uses to connect to projectors, and the issue went away.  It seems there is some issue where it interferes with Hyper-V

**Comment by amellnik** [comment]
@mjquigley -- Nice catch, would you mind sharing how you figured this out?

**Comment by mjquigley** [comment]
One of the other engineers I work with who experienced the issue uninstalled things that were installed recently until the issue went away.  

If anyone else runs into this issue, there is a [driver update](https://downloadcenter.intel.com/download/26791/Intel-Unite-App-Extended-Display-Driver?product=89294) available from Intel that appears to resolve the issue.

**Comment by zachberger** [comment]
> If anyone else runs into this issue, there is a driver update available from Intel that appears to resolve the issue.

This worked for me

**Comment by josiah14** [comment]
I don't have the Intel Unite Client and yet I'm experiencing this issue.

**Comment by rn** [comment]
closing old issues
