### ISSUE TITLE
Failed to start Docker Desktop

### ISSUE THREAD

**Issue by petercmho** [docker/for-win#5041]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A860EBC9-753F-4797-A510-6972683F7FE5/20191031160121

### Expected behavior
Docker Desktop should start successfully.
### Actual behavior
An error message pop up with the following information.

Time out has expired and the operation has not been completed.

   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env)
   at Docker.Backend.Processes.WindowsDockerDaemon.Start(Settings settings, String daemonOptions, Boolean useProtectedNamedPipe)
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions)
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_4(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information

  - Windows Version: Windows 10 Pro 1809
  - Docker Desktop Version: 2.1.0.4(39773)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. … Restart computer or restart docker desktop
  2. ...

**Comment by minoseah629** [comment]
this issue seems related to what i experienced: 

Diagnostics ID:     4C0153D0-6C4B-4847-BBFE-9AC8AB814B10/20191104194434 
4C0153D0-6C4B-4847-BBFE-9AC8AB814B10/20191104192954
