### ISSUE TITLE
Docker is failing with error, The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop:

### ISSUE THREAD

**Issue by bhaskarshankarling** [docker/for-win#5062]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: Could not able to upload diagnostics as in the log

### Expected behavior
Should start without any error / issues
### Actual behavior
Throwing the below error shown in the log during start up 
### Information
Docker is failing with below error on a normal start / restart. Also could not stop the docker desktop as it just keeps showing `Docker Desktop will shut down` but it never stops. Please help me out.

```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The operation on computer 'DESKTOP-IH9EFN5' failed: Provider load failure 
at New-MobyLinuxVM, <No file>: line 182
at <ScriptBlock>, <No file>: line 411
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 36
   at Docker.Actions.<>c__DisplayClass28_0.<SwitchDaemon>b__0() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 305
   at Docker.WPF.TaskQueue.<>c__DisplayClass19_0.<.ctor>b__1() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\TaskQueue.cs:line 59
```
```
Version: 2.0.0.3 (31259)
Channel: stable
Sha1: 8858db33c8692b69de9987a5d672798d778735b2
Started on: 2019/11/05 15:30:03.684
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1903
Build: 18362
BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
File: C:\Users\Bhaskar Shankarling\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[15:30:03.774][GUI            ][Info   ] Starting...
[15:30:03.824][ComponentVersions][Info   ] Edition community
[15:30:03.824][GUI            ][Error  ] An instance is already running. Exiting.
[15:30:04.158][Tracking       ][Info   ] Crash report and usage statistics are enabled
[15:30:04.158][SegmentApi     ][Info   ] Usage statistic: appLaunched
[15:30:04.217][SegmentApi     ][Info   ] Usage statistic: heartbeat
[15:30:04.217][SegmentApi     ][Info   ] Usage statistic: Identify
[15:30:05.968][WootricService ][Warning] Could not get NPS authentication token, JSON value not found. (Exception from HRESULT: 0x83750009)
[15:30:06.108][NamedPipeClient][Info   ] Sending Version()...
[15:30:06.117][NamedPipeClient][Info   ] Received response for Version
[15:30:06.117][NamedPipeClient][Info   ] Sending MigrateApp()...
[15:30:06.117][NamedPipeClient][Info   ] Received response for MigrateApp
[15:30:06.117][NamedPipeClient][Info   ] Sending Version()...
[15:30:06.117][NamedPipeClient][Info   ] Received response for Version
[15:30:06.117][NamedPipeClient][Info   ] Sending RegisterFileAssociations(C:\Program Files\Docker\Docker\Docker for Windows.exe)...
[15:29:35.169][PowerShell     ][Info   ] Run script...
[15:30:06.117][NamedPipeClient][Info   ] Received response for RegisterFileAssociations
[15:30:06.117][NamedPipeClient][Info   ] Sending Version()...
[15:29:35.200][PowerShell     ][Info   ] Run script...
[15:30:06.117][NamedPipeClient][Info   ] Received response for Version
[15:30:06.117][NamedPipeClient][Info   ] Sending EnableVersionPack(default, Docker.Core.Settings)...
[15:30:06.133][NamedPipeClient][Info   ] Received response for EnableVersionPack
[15:29:35.299][BootHelper     ][Info   ] Resume from hibernation
[15:30:06.133][NamedPipeClient][Info   ] Sending Version()...
[15:30:06.133][NamedPipeClient][Info   ] Received response for Version
[15:30:06.117][NamedPipeServer][Info   ] Version()
[15:30:06.133][NamedPipeClient][Info   ] Sending Start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions)...
[15:30:06.117][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:30:06.117][NamedPipeServer][Info   ] MigrateApp()
[15:30:06.117][NamedPipeServer][Info   ] MigrateApp done in 00:00:00.
[15:30:06.117][NamedPipeServer][Info   ] Version()
[15:30:06.117][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:30:06.117][NamedPipeServer][Info   ] RegisterFileAssociations(C:\Program Files\Docker\Docker\Docker for Windows.exe)
[15:30:06.117][FileTypeRegistrar][Info   ] Registering file association for extension .ddvp
[15:30:06.117][NamedPipeServer][Info   ] RegisterFileAssociations done in 00:00:00.
[15:30:06.117][NamedPipeServer][Info   ] Version()
[15:30:06.117][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:30:06.133][NamedPipeServer][Info   ] EnableVersionPack(default, Docker.Core.Settings)
[15:30:06.133][NamedPipeServer][Info   ] EnableVersionPack done in 00:00:00.
[15:30:06.133][NamedPipeServer][Info   ] Version()
[15:30:06.133][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:30:06.184][NPS            ][Info   ] NPS last local survey date: 5/25/2019 7:54:09 PM +00:00
[15:30:06.133][NamedPipeServer][Info   ] Start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions)
[15:30:06.133][PowerMode      ][Info   ] Stop
[15:30:06.133][HyperV         ][Info   ] Stop
[15:30:06.133][PowerShell     ][Info   ] Run script with parameters: -Stop True
[15:30:06.133][HyperV         ][Info   ] Script started at 15:30:06.133
[15:30:06.148][HyperV         ][Info   ] Modules loaded at 15:30:06.148
[15:30:06.168][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[15:30:06.168][HyperV         ][Debug  ] [stop] took 00:00:00.0357732 to run
[15:30:06.168][OptimizeDisk   ][Info   ] Optimize
[15:30:06.168][PowerShell     ][Info   ] Run script...
[15:30:06.193][Moby           ][Info   ] Stop
[15:30:06.193][HyperV         ][Info   ] Create
[15:30:06.193][PowerMode      ][Info   ] Start
[15:30:06.193][HyperVGuids    ][Info   ] Installing GUIDs...
[15:30:06.193][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64000000000 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[15:30:06.193][Firewall       ][Info   ] Removing all existing rules...
[15:30:06.193][HyperVGuids    ][Info   ] GUIDs installed
[15:30:06.208][HyperV         ][Info   ] Script started at 15:30:06.208
[15:30:06.224][HyperV         ][Info   ] Modules loaded at 15:30:06.224
[15:30:06.269][Firewall       ][Info   ] All existing rules are removed.
[15:30:06.269][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[15:30:06.269][Firewall       ][Info   ] Opening ports for SMB...
[15:30:06.269][Firewall       ][Info   ] Ports are opened
[15:30:06.518][NPS            ][Error  ] Error in NPS process: Nullable object must have a value.
[15:30:06.594][HyperV         ][Info   ] Using existing Switch: DockerNAT
[15:30:10.478][HyperV         ][Info   ] Using existing Switch IP address
[15:32:10.520][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The operation on computer 'DESKTOP-IH9EFN5' failed: Provider load failure 
at New-MobyLinuxVM, <No file>: line 182
at <ScriptBlock>, <No file>: line 411. Let's retry
[15:32:22.682][SegmentApi     ][Info   ] Usage statistic: actionCancelUpdate
[15:36:10.599][HyperV         ][Info   ] Hyper-V is running
[15:36:10.599][PowerMode      ][Info   ] Stop
[15:36:10.599][HyperV         ][Info   ] Stop
[15:36:10.599][PowerShell     ][Info   ] Run script with parameters: -Stop True
[15:36:10.614][HyperV         ][Info   ] Script started at 15:36:10.614
[15:36:10.623][HyperV         ][Info   ] Modules loaded at 15:36:10.623
[15:36:10.636][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[15:36:10.636][HyperV         ][Debug  ] [stop] took 00:00:00.0363512 to run
[15:36:10.636][OptimizeDisk   ][Info   ] Optimize
[15:36:10.636][PowerShell     ][Info   ] Run script...
[15:36:10.655][Moby           ][Info   ] Stop
[15:36:10.667][HyperV         ][Info   ] Destroy
[15:36:10.667][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True
[15:36:10.680][HyperV         ][Info   ] Script started at 15:36:10.680
[15:36:10.686][HyperV         ][Info   ] Modules loaded at 15:36:10.686
[15:36:10.703][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[15:36:10.703][HyperV         ][Info   ] Destroying Switch DockerNAT...
[15:36:12.770][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[15:36:12.788][HyperV         ][Debug  ] [destroy] took 00:00:02.1210148 to run
[15:36:12.788][Firewall       ][Info   ] Closing ports...
[15:36:12.788][Firewall       ][Info   ] Removing all existing rules...
[15:36:12.913][Firewall       ][Info   ] All existing rules are removed.
[15:36:12.914][Firewall       ][Info   ] Ports are closed
[15:36:12.914][HyperVGuids    ][Info   ] Removing GUIDs...
[15:36:12.918][HyperVGuids    ][Info   ] GUIDs removed
[15:36:12.918][HyperV         ][Info   ] Create
[15:36:12.919][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -VhdSize 64000000000 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-for-win.iso
[15:36:12.927][HyperV         ][Info   ] Script started at 15:36:12.926
[15:36:12.936][HyperV         ][Info   ] Modules loaded at 15:36:12.936
[15:36:12.955][HyperV         ][Info   ] Creating Switch: DockerNAT...
[15:36:14.624][HyperV         ][Info   ] Switch created.
[15:36:22.203][HyperV         ][Info   ] Set IP address on switch
[15:38:22.227][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The operation on computer 'DESKTOP-IH9EFN5' failed: Provider load failure 
at New-MobyLinuxVM, <No file>: line 182
at <ScriptBlock>, <No file>: line 411    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 195
   at Docker.Backend.HyperV.Create(Settings settings) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 125
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 117
[15:38:22.536][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The operation on computer 'DESKTOP-IH9EFN5' failed: Provider load failure 
at New-MobyLinuxVM, <No file>: line 182
at <ScriptBlock>, <No file>: line 411
[15:38:22.541][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The operation on computer 'DESKTOP-IH9EFN5' failed: Provider load failure 
at New-MobyLinuxVM, <No file>: line 182
at <ScriptBlock>, <No file>: line 411
[15:38:22.619][NamedPipeClient][Info   ] Sending Version()...
[15:38:22.623][NamedPipeClient][Info   ] Received response for Version
[15:38:22.623][NamedPipeClient][Info   ] Sending GatherDiagnostics(-path C:\Users\Bhaskar Shankarling\AppData\Local\Temp\ gather -id 69ECDF7C-4221-4181-A0B6-A4E7CA9460C4/20191105153822, C:\Users\Bhaskar Shankarling\AppData\Local\Temp\69ECDF7C-4221-4181-A0B6-A4E7CA9460C4/20191105153822.zip)...
[15:38:22.622][NamedPipeServer][Info   ] Version()
[15:38:22.622][NamedPipeServer][Info   ] Version done in 00:00:00.
[15:38:22.625][NamedPipeServer][Info   ] GatherDiagnostics(-path C:\Users\Bhaskar Shankarling\AppData\Local\Temp\ gather -id 69ECDF7C-4221-4181-A0B6-A4E7CA9460C4/20191105153822, C:\Users\Bhaskar Shankarling\AppData\Local\Temp\69ECDF7C-4221-4181-A0B6-A4E7CA9460C4/20191105153822.zip)
[15:38:22.745][NamedPipeClient][Error  ] Unable to send GatherDiagnostics: No diagnostic output at C:\Users\Bhaskar Shankarling\AppData\Local\Temp\69ECDF7C-4221-4181-A0B6-A4E7CA9460C4/20191105153822.zip
[15:38:22.749][CrashReport    ][Warning] Unable to gather diagnostics in Windows Service : (No diagnostic output at C:\Users\Bhaskar Shankarling\AppData\Local\Temp\69ECDF7C-4221-4181-A0B6-A4E7CA9460C4/20191105153822.zip)
[15:38:22.749][CrashReport    ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\Resources\com.docker.diagnose.exe -path C:\Users\Bhaskar Shankarling\AppData\Local\Temp\ gather -id 69ECDF7C-4221-4181-A0B6-A4E7CA9460C4/20191105153822'
[15:38:22.737][Backend        ][Error  ] No diagnostic output available at C:\Users\Bhaskar Shankarling\AppData\Local\Temp\69ECDF7C-4221-4181-A0B6-A4E7CA9460C4/20191105153822.zip after running : 'C:\Program Files\Docker\Docker\Resources\com.docker.diagnose.exe -path C:\Users\Bhaskar Shankarling\AppData\Local\Temp\ gather -id 69ECDF7C-4221-4181-A0B6-A4E7CA9460C4/20191105153822'
[15:38:22.737][NamedPipeServer][Error  ] Unable to execute GatherDiagnostics: No diagnostic output at C:\Users\Bhaskar Shankarling\AppData\Local\Temp\69ECDF7C-4221-4181-A0B6-A4E7CA9460C4/20191105153822.zip    at Docker.Backend.Backend.GatherDiagnostics(String args, String file) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Backend\Backend.cs:line 314
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 48
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 180
[15:38:22.847][CrashReport    ][Error  ] No diagnostic output available at C:\Users\Bhaskar Shankarling\AppData\Local\Temp\69ECDF7C-4221-4181-A0B6-A4E7CA9460C4/20191105153822.zip after running : 'C:\Program Files\Docker\Docker\Resources\com.docker.diagnose.exe -path C:\Users\Bhaskar Shankarling\AppData\Local\Temp\ gather -id 69ECDF7C-4221-4181-A0B6-A4E7CA9460C4/20191105153822'
[15:38:22.873][ErrorReportWindow][Error  ] Could not gather diagnostics : No diagnostic output at C:\Users\Bhaskar Shankarling\AppData\Local\Temp\69ECDF7C-4221-4181-A0B6-A4E7CA9460C4/20191105153822.zip.
[15:40:10.671][ErrorReportWindow][Info   ] Open logs

```

### Steps to reproduce the behavior

Not sure as it was working fine a day before and suddenly started failing.

**Comment by mikeyjk** [comment]
After opening the hyper-v I realised something was wrong with it.
After disabling/enabling virtualisation in BIOS, I then uninstalled and re-installed the hyper-v additional features within Windows (with restarts between each step above, -_-).

After re-installing Hyper-V and rebooting, the Hyper-V app/interface looked better, and lo and behold after reinstalling Docker Desktop it's now working.

A very painful experience that cost me multiple hours.
Not sure if it was a Win update or a policy change at my workplace.
