### ISSUE TITLE
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Element not found.

### ISSUE THREAD

**Issue by narayask** [docker/for-win#5065]
Hi Team,
I have installed Docker Desktop 19.03.4 stable on Windows 10 Enterprise system, 
I am able to see docker running in "Docker setting", getting below error while running docker commands.
I have restarted the docker services as below and still no luck.  
net stop com.docker.service and
net start com.docker.service

C:\Windows\system32>docker -- version
Client: Docker Engine - Community                                                                                                                                                    Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

C:\Windows\system32>docker run hello-world                                                                                                                                          docker: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'docker run --help'.

Below is the Error while starting Docker desktop.
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Element not found.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

Can someone help me with this. I am a beginner.

Thanks
Sanjeev Kumar N

**Comment by narayask** [comment]
Now i am getting below error while restarting Docker Desktop.

Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Element not found.


   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
