### ISSUE TITLE
"Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled"

### ISSUE THREAD

**Issue by Daniel15** [docker/for-win#509]
### Expected behavior
Docker starts as expected

### Actual behavior
I get this error when Docker tries to start:
```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Inconsistent parameters PolicyStore PersistentStore and Dhcp Enabled

   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

 - Diagnostic ID: `CBA474E7-9602-4C9E-8530-24E26DFEF16B/2017-02-18_16-44-48`
 - System info:
   - Windows 10.0.14971 Build 14971
   - Docker version 1.13.1, build 092cba3

**Comment by Daniel15** [comment]
I uninstalled Docker, restarted, reinstalled Docker, restarted again, and it seems to be working fine now. Feel free to close this issue if my crash report doesn't have any useful information.
