### ISSUE TITLE
Docker fails to start after initial installation

### ISSUE THREAD

**Issue by gmcraff-f5** [docker/for-win#5130]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A6704DC0-525F-4FBB-8A89-EDCB4FBBD16E/20191113191519

### Expected behavior

Docker will start so initial hello world can be attempted

### Actual behavior

Error and stack trace immediately after starting Docker Desktop

### Information

  - Windows Version: Windows 10 Enterprise 1709 build 16299.15
  - Docker Desktop Version: 2.1.0.4 (39773) stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Docker fails to start after initial installation.  Same error occurs after deinstalling and reinstalling

Unable to stop - Cannot invoke method. Method invocation is supported only on core types in this language mode.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext() in C:\workspaces\stable-19.03.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-19.03.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 39
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup) in C:\workspaces\stable-19.03.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Actions.cs:line 123
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0() in C:\workspaces\stable-19.03.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Actions.cs:line 100
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1() in C:\workspaces\stable-19.03.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\TaskQueuing\TaskQueue.cs:line 45

Diagnostic ID A6704DC0-525F-4FBB-8A89-EDCB4FBBD16E/20191113191519

  2. Docker desktop also fails to close after the error, apparently hung at the point of trying to stop something that won't stop or doesn't exist

**Comment by gmcraff-f5** [comment]
Turns out the problem was Constrained Language mode for Powershell, enforced by my corporate IT department.  I can resolve this by requesting an exception from them.
