### ISSUE TITLE
Docker carsh on Windows 10 Enter

### ISSUE THREAD

**Issue by IshwarChincholkar** [docker/for-win#5133]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version: 10 enterprise (64bit) -i5 7th gen
  - Docker Desktop Version: 2.1.0.4 - 39773 build 64bit
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: on HyperV

### Steps to reproduce the behavior

  1. ... Crash on laptop restart
  2. ...

Log:

Unable to stop - Cannot invoke method. Method invocation is supported only on core types in this language mode.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

----------------------------log.txt---------------------------------

[12:13:48.010][PowerShell        ][Info   ] Run script with parameters: -Stop True -Verbose True -ErrorAction Stop
[12:13:48.160][HyperV            ][Error  ] Unable to stop: System.Management.Automation.CmdletInvocationException: Cannot invoke method. Method invocation is supported only on core types in this language mode. ---> System.Management.Automation.RuntimeException: Cannot invoke method. Method invocation is supported only on core types in this language mode.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunAsync>d__6.MoveNext()
[12:13:48.160][Moby              ][Info   ] Stop
[12:13:48.175][Linux             ][Error  ] Failed to start: Unable to stop - Cannot invoke method. Method invocation is supported only on core types in this language mode.. Let's retry
[12:13:48.175][Linux             ][Info   ] Setting container engine status to Starting
[12:13:48.274][Installer         ][Info   ] Checking for features: *Hyper-V*, Containers
[12:13:48.275][PowerShell        ][Info   ] Run script...
[12:13:52.387][PowerShell        ][Info   ] Run script...
[12:13:55.982][PowerShell        ][Info   ] Run script...
[12:13:59.297][PowerShell        ][Info   ] Run script...
[12:14:02.645][Installer         ][Info   ] Features installed
[12:14:02.674][HyperV            ][Info   ] Hyper-V is running
[12:14:02.674][PowerMode         ][Info   ] Stop
[12:14:02.674][HyperV            ][Info   ] Stop
[12:14:02.675][PowerShell        ][Info   ] Run script with parameters: -Stop True -Verbose True -ErrorAction Stop
[12:14:02.746][HyperV            ][Error  ] Unable to stop: System.Management.Automation.CmdletInvocationException: Cannot invoke method. Method invocation is supported only on core types in this language mode. ---> System.Management.Automation.RuntimeException: Cannot invoke method. Method invocation is supported only on core types in this language mode.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
   --- End of inner exception stack trace ---
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunAsync>d__6.MoveNext()
[12:14:02.746][Moby              ][Info   ] Stop
[12:14:02.762][Linux             ][Info   ] Setting container engine status to FailedToStart
[12:14:02.764][NamedPipeServer   ][Error  ] Unable to execute engine/start: Unable to stop - Cannot invoke method. Method invocation is supported only on core types in this language mode.    at Docker.Backend.HyperV.HandleException(String action, Exception ex)
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
   at Docker.Backend.ContainerEngine.Linux.DoStop()
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
[12:14:02.904][NamedPipeClient   ][Error  ] Unable to send engine/start: Unable to stop - Cannot invoke method. Method invocation is supported only on core types in this language mode.
[12:14:02.913][Notifications     ][Error  ] Unable to stop - Cannot invoke method. Method invocation is supported only on core types in this language mode.
[12:14:34.977][NamedPipeClient   ][Info   ] Sending app/version()...
[12:14:34.985][NamedPipeClient   ][Info   ] Received response for app/version
[12:14:34.985][NamedPipeClient   ][Info   ] Sending diagnostics/gather()...
[12:14:34.984][NamedPipeServer   ][Info   ] app/version()
[12:14:34.984][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[12:14:34.987][NamedPipeServer   ][Info   ] diagnostics/gather()

**Comment by rem-aj** [comment]
Hi team I'm experiencing this issue also, looking forward to updates.

**Comment by IshwarChincholkar** [comment]
@rem-aj 
Issue is resolved , due to powershell security policy docker was getting crash on my Win-10 laptop.

**Comment by shimpikk** [comment]
> @rem-aj
> Issue is resolved , due to powershell security policy docker was getting crash on my Win-10 laptop.

What exactly you did? Did you change any PowerShell settings or System-wide change? Can you provide the commands/ steps you run to solve the issue? Thank you in advance.

**Comment by jeffgriffith** [comment]
hi @IshwarChincholkar  any luck with this? i started getting this yesterday and haven't recovered from it yet. my language mode is restricted but it's also the case for some of my colleages without the problem. i'm trying to revert to an older docker version now to match my still-functioning colleague.

**Comment by jeffgriffith** [comment]
i don't have the power in enterprise environment to change my execution policy. is there some other workaround? trying now to revert to an older version since i have colleagues functioning with the same execution policy without errors.

**Comment by IshwarChincholkar** [comment]
I just set `Get-ExecutionPolicy ` to `RemoteSigned `
`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine`
