### ISSUE TITLE
Docker crashes on login

### ISSUE THREAD

**Issue by yooakim** [docker/for-win#5154]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D1DD6790-FD31-4D95-AC1F-6A07B084A328/20191116072548

### Expected behavior

Docker should start

### Actual behavior

```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.


   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning)
   at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

```

### Information

Not a new issue. I logged in to my system and Docker crashed

  - Windows Version: 1903 (19013.1122)
  - Docker Desktop Version: 2.1.5.0 (40323)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

Using the WSL 2 subsystem

### Steps to reproduce the behavior
  1. Log in to Windows when Docker is set to auto-start

**Comment by simonferquel** [comment]
Should be fixed with 2.1.6.0
