### ISSUE TITLE
I am not able to start the docker for windows with liux containers after the update.

### ISSUE THREAD

**Issue by Arjun-R-Dev** [docker/for-win#5252]
Unable to stop - The file or directory is corrupted and unreadable. (Exception from HRESULT: 0x80070570)

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by mikeparker** [comment]
Please fill in the issue template
