### ISSUE TITLE
Docker fails on startup using WSL 2 based engine

### ISSUE THREAD

**Issue by borysvorona** [docker/for-win#5260]
### Error
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker

   at Docker.Backend.LifecycleClient.WaitForServerUp(TimeSpan pingTimeout)
   at Docker.Backend.ContainerEngine.WslEngine.DoStart(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential, Boolean retry)
   at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential, Boolean retry)
   at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  - [ + ] I have tried with the latest version of my channel Edge
  - [ + ] I have uploaded Diagnostics
  - Diagnostics ID: 98B72FDD-EA52-4775-B2CB-2BCE8E58E93A/20191202212505

### Expected behavior
Docker Gracefully Starts on Startup

### Actual behavior
Docker Fails on Startup

### Information

  - Windows Version: 10.0.19033 Build 19033
  - WLS 2: Ubuntu image
  - Docker Desktop Version: 2.1.6.1 40900

### Steps to reproduce the behavior
  1. Setup Docker for WSL 2
  2. Docker start on login

**Comment by simonferquel** [comment]
as with https://github.com/docker/for-win/issues/5256, can you try https://github.com/docker/for-win/issues/5256 and report the detailed error here ?

**Comment by borysvorona** [comment]
Fixed by restoring Docker to default settings and re-setup for WSL2.
