### ISSUE TITLE
Please help with Docker issue, stuck in a loop! 

### ISSUE THREAD

**Issue by lukeh99** [docker/for-win#5323]
I'm stuck in a loop where I can't get docker to run in linux containers, on a windows 10 machine. 
I keep getting the error below and none of the previously mentioned tips have worked. I'm new to docker and could really use some help! 

Unable to destroy - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The data is invalid. 

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass27_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by lukeh99** [comment]
Here is my troubleshoot ID
B3BDCA78-5EB1-4731-80DC-055E9C94C465/20191213120351

**Comment by mat007** [comment]
You’re running 2.0.0.3 which was released 10 months ago, could you try with the latest version?
You might want to also try the Edge channel i.e. https://docs.docker.com/docker-for-windows/edge-release-notes/

**Comment by lukeh99** [comment]
Ok let me try that version, I was purposely using an old version because I was told only that version would work for purposes; webodm. 
Let me attempt the edge channel. Will report back.

**Comment by lukeh99** [comment]
Tried new version and edge version, getting the error below. 
Diag ID....

B3BDCA78-5EB1-4731-80DC-055E9C94C465/20191213193738



Unable to destroy - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The data is invalid. 

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
