### ISSUE TITLE
Docker running on VM crashes on start up. New installation.

### ISSUE THREAD

**Issue by napsa-4805** [docker/for-win#5337]
Running the latest stable build of Docker on a VM and it crashes on start up.

Unable to start - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'DockerDesktopVM' failed to start.

Failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running.

'DockerDesktopVM' failed to start. (Virtual machine ID 0F87C050-4757-4982-8B78-DC3CEDF9F6CC)

The Virtual Machine Management Service failed to start the virtual machine 'DockerDesktopVM' because one of the Hyper-V components is not running (Virtual machine ID 0F87C050-4757-4982-8B78-DC3CEDF9F6CC).

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass27_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by cah-sandip-bhoi** [comment]
I am facing the same error. Did we find anything?

**Comment by pustian** [comment]
The same error.

**Comment by napsa-4805** [comment]
Nothing from the team yet. I suppose I will attempt to tweak some settings in my VM and see what happens.
