### ISSUE TITLE
Receiving Virtualization Error on Initial Startup

### ISSUE THREAD

**Issue by roshanr10** [docker/for-win#5362]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 0A572683-3353-4803-B8B3-A8CF1039CEB0/20191221163746

### Expected behavior
I'm able to use a fresh install of Docker Desktop out of the box.

### Actual behavior
I receive the error:
```
An error occurred:
Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled
```

### Information

  - Windows Version: Windows 10 Pro - 1909 (18363.535)
  - Docker Desktop Version: 2.1.0.5(40693)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

I have VT on in the Bios, which is reflected in task manager, and I have DEP enabled in control panel. I follow the steps on the link to no avail. I tried a few other CLI commands to enable Hyper-V runner based on the other issues in GH, but no luck. Any help would be greatly appreciated.

Log Snippet:
```
[21:34:01.345][HyperV            ][Error  ] Unable to start: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'DockerDesktopVM' failed to start.

Virtual machine 'DockerDesktopVM' could not be started because the hypervisor is not running.

'DockerDesktopVM' failed to start. (Virtual machine ID 67583F81-8CF7-4BF5-B886-83676D716152)

Virtual machine 'DockerDesktopVM' could not be started because the hypervisor is not running (Virtual machine ID 67583F81-8CF7-4BF5-B886-83676D716152).

The following actions may help you resolve the problem:

1) Verify that the processor of the physical computer has a supported version of hardware-assisted virtualization.

2) Verify that hardware-assisted virtualization and hardware-assisted data execution protection are enabled in the BIOS of the physical computer.  (If you edit the BIOS to enable either setting, you must turn off the power to the physical computer and then turn it back on.  Resetting the physical computer is not sufficient.)

3) If you have made changes to the Boot Configuration Data store, review these changes to ensure that the hypervisor is configured to launch automatically.


   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunAsync>d__6.MoveNext()
[21:34:01.345][Linux             ][Error  ] Failed to start: Unable to start - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'DockerDesktopVM' failed to start.

Virtual machine 'DockerDesktopVM' could not be started because the hypervisor is not running.

'DockerDesktopVM' failed to start. (Virtual machine ID 67583F81-8CF7-4BF5-B886-83676D716152)

Virtual machine 'DockerDesktopVM' could not be started because the hypervisor is not running (Virtual machine ID 67583F81-8CF7-4BF5-B886-83676D716152).

The following actions may help you resolve the problem:

1) Verify that the processor of the physical computer has a supported version of hardware-assisted virtualization.

2) Verify that hardware-assisted virtualization and hardware-assisted data execution protection are enabled in the BIOS of the physical computer.  (If you edit the BIOS to enable either setting, you must turn off the power to the physical computer and then turn it back on.  Resetting the physical computer is not sufficient.)

3) If you have made changes to the Boot Configuration Data store, review these changes to ensure that the hypervisor is configured to launch automatically.

. Let's retry
[21:34:01.345][Linux             ][Info   ] Setting container engine status to Starting
[21:34:01.376][Linux             ][Info   ] Setting container engine status to Quitting
[21:34:01.376][NamedPipeClient   ][Error  ] Unable to send engine/start: Hardware assisted virtualization and data execution protection must be enabled in the BIOS. See https://docs.docker.com/docker-for-windows/troubleshoot/#virtualization-must-be-enabled
[21:34:07.220][Moby              ][Error  ] Failed to read Moby's logs: The operation has timed out.
```

### Steps to reproduce the behavior

  1. Uninstall Docker & Hyper-V
  2. Install Docker (which installs Hyper-V)
  3. Start Docker

**Comment by roshanr10** [comment]
Found the issue, documented here: https://github.com/docker/docker.github.io/issues/6381

Wasn't clear at first, but the machine I was trying to get working was upgraded from Win7 to Win10 which broke Hyper-V, which in turn broke Docker. Hopefully this helps the next person to come across this issue.
