### ISSUE TITLE
Unable to launch process: 1260

### ISSUE THREAD

**Issue by itcrowd** [docker/for-win#5425]
Hi

I've got this error here when trying to start Docker Desktop:

**Unable to launch process: 1260**

>    at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
>    at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
>    at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
>    at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

  [Y] I have tried with the latest version of my channel (Stable or Edge)
  [Y] I have uploaded Diagnostics
  [Y] Diagnostics ID: 6D581805-B47C-4764-B6B5-A8057DA19FD7/20200106122220

### Expected behavior

Docker should start as expected

### Actual behavior

Docker fails to start with error - Unable to launch process: 1260

### Information

  - Windows Version: Pro 10.0.18363 Build 18363
  - Docker Desktop Version: Docker Desktop Version: 2.1.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
  - Hyper-V is enabled

**Log File:**
[060120_log.txt](https://github.com/docker/for-win/files/4027258/060120_log.txt)

This is the first error - might be relevant:

> [12:20:36.116][VpnKit            ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
> [12:20:36.116][VpnKit            ][Error  ] vpnkit.exe: While watching C:\Users\BILL\AppData\Roaming\Docker\resolv.conf: ENOENT
> [12:20:36.116][VpnKit            ][Error  ] vpnkit.exe: Failed to read DNS configuration file C:\Users\BILL\AppData\Roaming\Docker\resolv.conf: reading C:\Users\BILL\AppData\Roaming\Docker\resolv.conf: No such file or directory. Disabling current configuration.
> 

**More errors here:**

> [12:20:36.116][VpnKit            ][Error  ] vpnkit.exe: While watching C:\Users\BILL\AppData\Roaming\Docker\gateway_forwards.json: ENOENT
> [12:20:36.116][VpnKit            ][Error  ] vpnkit.exe: Failed to read gateway forwards from C:\Users\BILL\AppData\Roaming\Docker\gateway_forwards.json: reading C:\Users\BILL\AppData\Roaming\Docker\gateway_forwards.json: No such file or directory.
> 

**And this one:**

> [Error  ] Failed to read Moby's logs: The operation has timed out.

**And then fail**

> 
[Error  ] Failed to start: Unable to launch process: 1260. Let's retry

### Steps to reproduce the behavior
Reboot windows and attempt to start Docker Desktop

Thanks in advance for any help and if I did not supply enough information please let me know.

**For interest:**

  1. ... I originally installed Docker Toolbox 3 years ago and its folders and files remain
  2. ... I cannot see any way to remove the old Docker Toolbox either with Windows Uninstall or using Revo Uninstaller.

**Comment by itcrowd** [comment]
Lots of warnings about vpnkit.exe - I have NordVPN installed.

> [12:20:36.116][VpnKit            ][Warning] vpnkit.exe: There is no database: using hardcoded network configuration values
> 
> [12:22:12.768][VpnKit            ][Warning] vpnkit.exe: There is no database: using hardcoded network configuration values
> [12:25:33.342][VpnKit            ][Warning] vpnkit.exe: fb40 Query:0 na:c:r:rn 0 <qs:www.docker.com. <A|IN>> <an:> <au:> <ad:> lookup failed: no servers configured
> 
> [12:25:33.342][VpnKit            ][Warning] vpnkit.exe: 0694 Query:0 na:c:r:rn 0 <qs:www.docker.com. <AAAA|IN>> <an:> <au:> <ad:> lookup failed: no servers configured
> 
> [12:25:35.843][VpnKit            ][Warning] vpnkit.exe: fb40 Query:0 na:c:r:rn 0 <qs:www.docker.com. <A|IN>> <an:> <au:> <ad:> lookup failed: no servers configured
> 
> [12:25:35.843][VpnKit            ][Warning] vpnkit.exe: 0694 Query:0 na:c:r:rn 0 <qs:www.docker.com. <AAAA|IN>> <an:> <au:> <ad:> lookup failed: no servers configured
> 
> [12:25:38.268][VpnKit            ][Warning] vpnkit.exe: ef4c Query:0 na:c:r:rn 0 <qs:8.8.8.8.in-addr.arpa. <PTR|IN>> <an:> <au:> <ad:> lookup failed: no servers configured
> 
> [12:25:40.771][VpnKit            ][Warning] vpnkit.exe: ef4c Query:0 na:c:r:rn 0 <qs:8.8.8.8.in-addr.arpa. <PTR|IN>> <an:> <au:> <ad:> lookup failed: no servers configured
> 
> [12:25:43.270][VpnKit            ][Warning] vpnkit.exe: 2274 Query:0 na:c:r:rn 0 <qs:www.docker.com. <AAAA|IN>> <an:> <au:> <ad:> lookup failed: no servers configured
> 
> [12:25:43.270][VpnKit            ][Warning] vpnkit.exe: e0c5 Query:0 na:c:r:rn 0 <qs:www.docker.com. <A|IN>> <an:> <au:> <ad:> lookup failed: no servers configured

Maybe I should uninstall NordVPN and Docker, reboot, an try installing Docker again.

**Comment by itcrowd** [comment]
Uninstalled NordVPN, cleaned gthe Registry, and tried again:

> 
> [15:40:11.811][VpnKit            ][Info   ] vpnkit.exe: Configuration server_macaddr = f6:16:36:bc:f9:c6; max_connection = None; dns_path = C:\Users\BILL\AppData\Roaming\Docker\resolv.conf; dns = ; resolver = Upstream; domain = None; allowed_bind_addresses = 0.0.0.0; gateway_ip = 192.168.65.1; host_ip = 192.168.65.2; lowest_ip = 192.168.65.3; highest_ip = 192.168.65.14; dhcp_json_path = None; dhcp_configuration = None; mtu = 1500; http_intercept = None; http_intercept_path = C:\Users\BILL\AppData\Roaming\Docker\http_proxy.json; port_max_idle_time = 300; host_names = host.docker.internal, docker.for.win.host.internal, docker.for.win.localhost; gateway_names = gateway.docker.internal, docker.for.win.gateway.internal, docker.for.win.http.internal; vm_names = vm.internal; udpv4_forwards = []; tcpv4_forwards = []; gateway_forwards_path = C:\Users\BILL\AppData\Roaming\Docker\gateway_forwards.json; pcap_snaplen = 128
> 
> [15:40:11.811][VpnKit            ][Info   ] vpnkit.exe: Listening on AF_HYPERV { vmid = 00000000-0000-0000-0000-000000000000; serviceid = 30D48B34-FACB-11E6-BD58-64006A7986D3 }
> 
> [15:40:11.811][VpnKit            ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
> 
> [15:40:11.811][VpnKit            ][Error  ] vpnkit.exe: While watching C:\Users\BILL\AppData\Roaming\Docker\resolv.conf: ENOENT
> 
> [15:40:11.811][VpnKit            ][Error  ] vpnkit.exe: Failed to read DNS configuration file C:\Users\BILL\AppData\Roaming\Docker\resolv.conf: reading C:\Users\BILL\AppData\Roaming\Docker\resolv.conf: No such file or directory. Disabling current configuration.

[070120_log.txt](https://github.com/docker/for-win/files/4031424/070120_log.txt)

Looks like a problem with /etc/resolve.conf - but that might not be as important as this:

> 
> [15:42:05.881][NamedPipeServer   ][Error  ] Unable to execute engine/start: Unable to launch process: 1260    at Docker.Win32Helpers.NativeImpersonatedProcess.Start(NativeImpersonatedProcess* , basic_string<wchar_t\,std::char_traits<wchar_t>\,std::allocator<wchar_t> >* watchguardPath) in c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.16.27023\include\xstring:line 1825
>    at Docker.Win32Helpers.ImpersonatedProcess.Start(String watchguardPath) in c:\workspaces\stable-19.03.x\src\github.com\docker\pinata\win\src\docker.win32helpers\impersonatedprocess.cpp:line 250
>    at Docker.Backend.Processes.ExternalProcess.StartImpersonatedProcess(String fileName, String arguments, String currentDirectory, IDictionary`2 envVariables, WindowsIdentityRecorder identity, CancellationToken stopToken)
>    at Docker.Backend.Processes.ExternalProcess.Start(String arguments, String currentDirectory, IDictionary`2 envVariables, WindowsIdentityRecorder identity)
>    at Docker.Backend.Processes.ApiProxy.StartWithVm(Settings settings, String vmId)
>    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
>    at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)

Is this critical:

> [15:42:05.881][NamedPipeServer   ][Error  ] Unable to execute engine/start: Unable to launch process: 1260    at Docker.Win32Helpers.NativeImpersonatedProcess.Start(NativeImpersonatedProcess* , basic_string<wchar_t\,std::char_traits<wchar_t>\,std::allocator<wchar_t> >* watchguardPath) in c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.16.27023\include\xstring:line 1825
>    at Docker.Win32Helpers.ImpersonatedProcess.Start(String watchguardPath) in c:\workspaces\stable-19.03.x\src\github.com\docker\pinata\win\src\docker.win32helpers\impersonatedprocess.cpp:line 250
> 

**Am I missing Visual Studio 2017?**
