### ISSUE TITLE
Error running Docker over Windows

### ISSUE THREAD

**Issue by TestAppsGlo** [docker/for-win#5441]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

This is the error:

Unable to destroy - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Invalid class 

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by mohamadnorouzi20** [comment]
yep fresh after install i'm getting this

**Comment by ulrich** [comment]
Can you send a diagnostic? Via the System Tray > Troubleshoot > Run diagnostic button.

Thank you.
