### ISSUE TITLE
Creating Switch: DockerNAT

### ISSUE THREAD

**Issue by domelz** [docker/for-win#5496]
- [ x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x ] I have uploaded Diagnostics
  - Diagnostics ID: A3443031-04DC-4E3B-9F84-E46B895C2BDB/20200117122253

### Expected behavior
Docker starts.

### Actual behavior

Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

### Information

  - Windows Version: 10.0.16299 Build 16299
  - Docker Desktop Version: 2.1.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. Attempt to start Docker

**Comment by domelz** [comment]
I resolved the issue of Docker Desktop failing to start on my Windows 10 version 1709 PC by installing the Windows 10 Upgrade to get the “Fall Creators Update” which is in Windows 10 version 1909. 

This fixed the problem of the Windows Hyper-V Manager failing to create a virtual machine for Docker. 
It also adds a Hyper-V Quick Create desktop application.

https://www.techradar.com/how-to/how-to-download-and-install-the-windows-10-fall-creators-update-right-now
