### ISSUE TITLE
Failed to execute script docker-compose

### ISSUE THREAD

**Issue by YoChecho** [docker/for-win#5501]
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 124, in perform_command
  File "compose\cli\command.py", line 39, in project_from_options
  File "compose\cli\docker_client.py", line 84, in tls_config_from_options
  File "site-packages\docker\tls.py", line 81, in __init__
docker.errors.TLSParameterError: Path to a certificate and key files must be provided through the client_config param. TLS configurations should map the Docke
r CLI client configurations. See https://docs.docker.com/engine/articles/https/ for API details.
[11504] Failed to execute script docker-compose

**Comment by mat007** [comment]
Can you tell us which Docker Desktop version you’re running and some reproduction steps?

**Comment by marktinsley** [comment]
Same here.

1. `docker-compose up -d`
1. `docker-compose exec name ls -l`

Before, this would list the contents of the default dir. 

Now, I get this:

```
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 491, in exec_command
  File "compose\cli\main.py", line 1469, in call_docker
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
TypeError: environment can only contain strings
[12824] Failed to execute script docker-compose
```

I can attach a bash session via the new dashboard's CLI button. But, cannot via `docker-compose exec name bash` anymore.
