### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by potray** [docker/for-win#5512]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E6E10FC4-3B92-4BB3-BE11-CEDECB05D187/20200121115342

### Expected behavior
Docker Desktop should be able to run.

### Actual behavior
It shows the following error:
```
Unable to stop - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: A positional parameter cannot be found that accepts argument 'gip'.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
```

### Information
I didn't run Docker for 1 week, so potentially a Windows update might be doing some shenanigans. I wish I could help more, but sadly I wasn't using the computer those days, so I can't know what happened.

I've tried reinstalling, but no success.

I've also tried some solutions for some `Unable to stop - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop` like errors, but no success either.

Docker Desktop version: 2.1.0.5 (40693)
Channel: stable
Windows version: Windows 10 pro, build 18363.592.

**Update**

I was just prompted to update to version 2.2.0.0 (42247). The error still exists but now there's more information:
``` 
Unable to stop Hyper-V VM: A positional parameter cannot be found that accepts argument 'gip'.
at <ScriptBlock>, C:\Windows\system32\WindowsPowerShell\v1.0\Modules\NetTCPIP\NetIPConfiguration.psm1: line 299
at <ScriptBlock>, <No file>: line 92

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
```

I submitted the new crash report with the diagnostic ID E6E10FC4-3B92-4BB3-BE11-CEDECB05D187/20200121151951

### Steps to reproduce the behavior
I just run Docker Desktop and I get this result.

**Comment by DD-UX** [comment]
Having the same issue. Attempted to use both stable/edge versions and simply can't run Docker desktop. Did any came by with a workaround?

**Comment by potray** [comment]
After many hours of trying to know what's going on, it appears it's a problem with Powershell. I tried to use Vagrant today and a very similar error occurred, and running something super simple like `Write-Output $PSVersionTable.PSVersion.Major` also throws a very similar error:
```
Write-Output : A positional parameter cannot be found that accepts argument '5'.
```
I'll keep you posted with any updates.

**Comment by potray** [comment]
I fixed this by simply reinstalling Windows. Closing!
