### ISSUE TITLE
Bug report for Docker on Windows

### ISSUE THREAD

**Issue by pansardinicolas** [docker/for-win#5547]
https://hub.docker.com/editions/community/docker-ce-desktop-windows -->
  - [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID:
00989EF4-2613-4002-819F-E53B3B931E76/20200122180002
### Expected behavior
Start docker for windows
### Actual behavior
Error right after starting
### Information

  - Windows Version: Windows 10 Enterprise version 1903 build 18362.535
  - Docker Desktop Version: 2.1.0.5 (40693) stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No
### Steps to reproduce the behavior

  1. Click on docker icon

Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V encountered an error trying to access an object on computer 'ZCURL-BX99K03' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

**Comment by pansardinicolas** [comment]
I managed to make it work by waiting it send all the reports (mandatory) and restarting. Then, it says "Docker is running" but the PowerShell, cmd or MINGW don't recognize it, so I took this advice: https://github.com/docker/for-win/issues/2367#issuecomment-568666233 
cd "C:\Program Files\Docker\Docker"
./DockerCli.exe -SwitchDaemon

try this

And it worked as a charm

**Comment by pansardinicolas** [comment]
it doesn't work with Linux containers

**Comment by pansardinicolas** [comment]
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.


   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning)
   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions)
   at Docker.Backend.ContainerEngine.Windows.Restart(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_5(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by denilolopes** [comment]
its works....grate....tanks
