### ISSUE TITLE
Cant start docker after update to 2.2.0.0

### ISSUE THREAD

**Issue by dzedzey** [docker/for-win#5562]
- [v ] I have tried with the latest version of my channel (Stable or Edge)
  - [ v] I have uploaded Diagnostics
  - Diagnostics ID: 12F353B9-AC88-4357-9C4F-922E3B5D43D4/20200123093126

### Actual behavior
docker doesn't start
got error:

One or more errors occurred.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

**Comment by dzedzey** [comment]
Can't fix it. 
I tried:
1. To disable Hyper-V and reboot, 
2. Uninstall Docker then possible(works), because it doesn't have a problem with removing VMs an images step
3. Reboot and enable Hyper-V
4. Reboot and install Docker
5, Reboot

Still same exact error

**Comment by dzedzey** [comment]
Error from Hyper-V-VMMS : Checkpoint operation for 'DockerDesktopVM' failed. (Virtual machine ID B630B537-9E97-48D7-918C-43CCA1E44636)

**Comment by benjaminbws** [comment]
Same problem with 2.2.0.0 and Edge 2.1.7.0..

Here is the log from the edge version
[log.txt](https://github.com/docker/for-win/files/4121668/log.txt)

**Comment by kgrinsven** [comment]
I am also getting the same error:

One or more errors occurred.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

Running stable version 2.2.0.0

[log.txt](https://github.com/docker/for-win/files/4156145/log.txt)

**Comment by dzedzey** [comment]
upgraded to 2.0.0.3 and it still doesn't work. Crash report: 
7E4816CE-6175-415F-ADFB-C54B2CFCEA9A/20200217104328

The  message is:
**Docker.Core.Backend.BackendDestroyException:
One or more errors occurred.
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass30_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.AggregateException:
  One or more errors occurred.
     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
     at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
     at Docker.Backend.LifecycleClient.DockerStart()
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Docker.Core.HttpBadResponseException:
     unable to fetch daemon.json: Get http://unix/engine/daemon.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
        at Docker.Backend.HttpClientExtensions.<ParseResponseBodyAsJsonAsync>d__2`1.MoveNext()
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Docker.Backend.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext()**

**Comment by dzedzey** [comment]
7E4816CE-6175-415F-ADFB-C54B2CFCEA9A/20200224155323
report from release 2.0.0.3

**Comment by dzedzey** [comment]
Was somebody able to solve this problem?

**Comment by kgrinsven** [comment]
> Was somebody able to solve this problem?
> I had to uninstall Docker for Windows and now run Ubuntu virtual machine o Hyper-V with Linux Docker inside

I ended up doing the exact same thing.

**Comment by benjaminbws** [comment]
Would be nice if Docker would do something. Even like respond to this or any of the other threads.

**Comment by dzedzey** [comment]
We found the issue! And it's not obvious. This was Windows feature 
![image](https://user-images.githubusercontent.com/8134137/76215736-a5910e80-620f-11ea-9f88-32cc3595213d.png)

**Comment by thomasdane** [comment]
Disabling WSL is not a good fix - docker and WSL should work together.

**Comment by dzedzey** [comment]
Could be related to Windows version 1709

**Comment by kgrinsven** [comment]
> We found the issue! And it's not obvious. This was Windows feature
> ![image](https://user-images.githubusercontent.com/8134137/76215736-a5910e80-620f-11ea-9f88-32cc3595213d.png)
> It must be disabled in order to start Docker!
> Please fix this

Thank You!

Disabling WSL finally got Docker working for me.

I know it's not a good fix but at least I have it running locally instead of through an Ubuntu virtualbox.

**Comment by dzedzey** [comment]
Any news on this? Can I help somehow?
