### ISSUE TITLE
Cannot add file share in Docker for Windows (2.2.0.0) on Windows 10

### ISSUE THREAD

**Issue by lokisisland** [docker/for-win#5581]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics (cannot generate Diagnostics, see below)
  - Diagnostics ID: n/a

Since upgrading to Docker for Windows 2.2.0.0, I cannot access shared volumes. When I attempt to add the share through the settings UI, I receive a credentials prompt but any attempt at providing (valid) credentials results in the credentials prompt closing and re-opening. 

Steps to reproduce:
1. Open Docker for Windows Settings.
2. Click Resources.
3. Click File Sharing.
4. Tick "C" drive check box.
5. Enter valid administrator credentials for the local machine.
6. Click Save.

At this point, the credentials prompt disappears and then reappears asking for credentials again (within around half a second). Invalid credentials result in an error message on the credentials popup windows. 

Is there anyway around this? I cannot use Docker at the moment as most of my containers rely on volume mounts. I have attempted to install the previous version of Docker but it just tells me I have the most up to date version. I would rather not remove Docker completely to reinstall the previous version as it will mean backing up and restoring many containers. 

When I attempt to run the Diagnostics, I receive an error (after several minutes):

"Error while gathering diagnostics : Failed to run 'C:\Program Files\Docker\Docker\resources"

Below is (what I believe to be) the relevant section of the log file:

[10:02:02.956][VpnKit            ][Info   ] vpnkit.exe: Hostnet_icmp 192.168.65.3 id=15973 -> 172.217.20.131 id=1: expiring ICMP NAT rule
[10:02:06.886][VpnKit            ][Info   ] vpnkit.exe: Connected Ethernet interface f6:16:36:bc:f9:c6
[10:02:06.886][VpnKit            ][Info   ] vpnkit.exe: UDP interface connected on 172.217.169.35
[10:02:08.997][APIRequestLogger  ][Info   ] [1fe1ff9b] <Server start> POST http://localhost/mount-credentials
[10:02:09.000][MountCredentialAsker][Info   ] Storing credentials: DESKTOP-92EKF7V\docker-admin:***********
[10:02:09.002][APIRequestLogger  ][Info   ] [1fe1ff9b] <Server end> POST http://localhost/mount-credentials -> 200 OK (took 4ms)
[10:02:09.020][APIRequestLogger  ][Info   ] [5407ad9f] <Server start> GET http://localhost/settings
[10:02:09.026][APIRequestLogger  ][Info   ] [5407ad9f] <Server end> GET http://localhost/settings -> 200 OK (took 5ms)
[10:02:09.050][APIRequestLogger  ][Info   ] [7affd40c] <Server start> POST http://localhost/settings
[10:02:09.051][APIRequestLogger  ][Info   ] [0b856f31] <NotificationsClient start> POST http://localhost/engine/state
[10:02:09.054][NamedPipeClient   ][Info   ] Sending app/version()...
[10:02:09.055][NamedPipeClient   ][Info   ] Received response for app/version
[10:02:09.055][NamedPipeClient   ][Info   ] Sending filesharing/get-protocol()...
[10:02:09.055][NamedPipeServer   ][Info   ] app/version()
[10:02:09.055][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[10:02:09.058][APIRequestLogger  ][Info   ] [0b856f31] <NotificationsClient end> POST http://localhost/engine/state -> 200 OK (took 7ms)
[10:02:09.058][NamedPipeClient   ][Info   ] Received response for filesharing/get-protocol
[10:02:09.055][NamedPipeServer   ][Info   ] filesharing/get-protocol()
[10:02:09.059][NamedPipeClient   ][Info   ] Sending app/version()...
[10:02:09.060][NamedPipeClient   ][Info   ] Received response for app/version
[10:02:09.060][NamedPipeClient   ][Info   ] Sending filesharing/mount(All, C, , Docker.Core.Settings)...
[10:02:09.055][APIRequestLogger  ][Info   ] [f85c5064] <GoBackendClient start> GET http://localhost/features
[10:02:09.056][GoBackendProcess  ][Info   ] time="2020-01-24T10:02:09Z" msg="external: GET /features 200 \"\" \"\""
[10:02:09.058][APIRequestLogger  ][Info   ] [f85c5064] <GoBackendClient end> GET http://localhost/features -> 200 OK (took 2ms)
[10:02:09.058][NamedPipeServer   ][Info   ] filesharing/get-protocol done in 00:00:00.0029983.
[10:02:09.059][NamedPipeServer   ][Info   ] app/version()
[10:02:09.066][NamedPipeClient   ][Info   ] Received response for filesharing/mount
[10:02:09.067][APIRequestLogger  ][Info   ] [ef80c1a0] <NotificationsClient start> POST http://localhost/engine/state
[10:02:09.059][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[10:02:09.060][NamedPipeServer   ][Info   ] filesharing/mount(All, C, , Docker.Core.Settings)
[10:02:09.070][APIRequestLogger  ][Info   ] [7affd40c] <Server end> POST http://localhost/settings -> 401 Unauthorized (took 20ms)
[10:02:09.060][GrpcFuse          ][Info   ] Mount C
[10:02:09.060][APIRequestLogger  ][Info   ] [b96e6837] <LifecycleClient start> POST http://localhost/mount
[10:02:09.066][APIRequestLogger  ][Info   ] [b96e6837] <LifecycleClient end> POST http://localhost/mount -> 500 InternalServerError (took 5ms)
[10:02:09.074][APIRequestLogger  ][Info   ] [ef80c1a0] <NotificationsClient end> POST http://localhost/engine/state -> 200 OK (took 6ms)
[10:02:09.066][GrpcFuse          ][Error  ] Unable to mount C drive: unexpected error: System.AggregateException: One or more errors occurred. ---> Docker.Backend.HttpBadResponseException: Exception of type 'Docker.Backend.HttpBadResponseException' was thrown.
   at Docker.Backend.HttpClientExtensions.<ParseResponseBodyAsJsonAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Docker.Backend.LifecycleClient.Mount(MountRequest req)
   at Docker.Backend.FileSharing.GrpcFuse.MountInMoby(String drive)
---> (Inner Exception #0) Docker.Backend.HttpBadResponseException: Exception of type 'Docker.Backend.HttpBadResponseException' was thrown.
   at Docker.Backend.HttpClientExtensions.<ParseResponseBodyAsJsonAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext()<---
[10:02:09.066][NamedPipeServer   ][Info   ] filesharing/mount done in 00:00:00.0060001.
[10:02:09.081][GoBackendProcess  ][Info   ] time="2020-01-24T10:02:09Z" msg="external: GET /features 200 \"axios/0.19.0\" \"\""
[10:02:09.110][ApiProxy          ][Info   ] time="2020-01-24T10:02:09Z" msg="proxy >> GET /containers/json?all=true\n"
[10:02:09.119][APIRequestLogger  ][Info   ] [7cfbf454] <Server start> GET http://localhost/mount-credentials
[10:02:09.119][APIRequestLogger  ][Info   ] [7cfbf454] <Server end> GET http://localhost/mount-credentials -> 200 OK (took 0ms)

**Comment by stephen-turner** [comment]
Thanks for the report. This is the same as #5567, so I'll close this copy as a dupe.

**Comment by lokisisland** [comment]
Sorry, I missed the original report; thanks :)
