### ISSUE TITLE
Installer died

### ISSUE THREAD

**Issue by sixcorners** [docker/for-win#5598]
Luckily it gives a stack trace:
```
An error occurred while sending the request.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.DownloadStep.<DoAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__23.MoveNext()
```

If it's not can you either change the installer to give a better error message or increase the amount of stuff in the stack trace?

**Comment by sixcorners** [comment]
When I check for updates now it says that docker is updated so I don't really know what failed.
I mostly made this to say that I think there should be a better error message or more error info here.
