### ISSUE TITLE
Docker Desktop not running after updating to 2.2.0.0(42247)

### ISSUE THREAD

**Issue by imranasadmd** [docker/for-win#5615]
Diagnostics were uploaded with id: 0A7DE742-609B-4873-B31F-FA4C1BF76DC3/20200127204403

**Comment by imranasadmd** [comment]
When switching from windows to Linux containers an error occurred with the below message
One or more errors occurred.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.<>c__DisplayClass39_0.<SwitchDaemon>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

[log_01282020.txt](https://github.com/docker/for-win/files/4123102/log_01282020.txt)
