### ISSUE TITLE
docker-compose exec error --version 2.2.0.0 

### ISSUE THREAD

**Issue by godhelpjun** [docker/for-win#5618]
- [x] I have tried with the latest version of my channel (Stable)
  - [] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:windows 10 pro
  - Docker Desktop Version:2.2.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

F:\prj\php\dock>docker-compose exec mysql bash
Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 72, in main
  File "compose\cli\main.py", line 128, in perform_command
  File "compose\cli\main.py", line 491, in exec_command
  File "compose\cli\main.py", line 1469, in call_docker
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 644, in _execute_child
TypeError: environment can only contain strings
[10352] Failed to execute script docker-compose

F:\prj\php\dock>python --version
Python 3.8.0

**Comment by mat007** [comment]
Duplicates of https://github.com/docker/compose/issues/7170
