### ISSUE TITLE
Docker Crash after updating from 2.1.0.5 to the new version 2.2.0.0

### ISSUE THREAD

**Issue by shishjoshi** [docker/for-win#5627]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

**### Expected behavior**
Docker desktop should be running with any versions
**### Actual behavior**
Docker desktop is crashing.
 Detailed logs are attached at the end with this issue.

**Error message while loading Docker is :**

Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass27_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()

### Information
   - Yes it is  reproducible.
  - Is the problem new? - Yes
  - Did the problem appear with an update? - Yes appear after we migrated to the new version
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
-->
  - Windows Version: 1809
Servicing stack update for Windows 10, version 1809: November 12, 2019
  - Docker Desktop Version: 2.1.0.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Windows OS machine
diagnostic id - C4221B06-8C32-47EA-B636-FE49313333E5/20200129002921

### Steps to reproduce the behavior

  1. ...Install docker version 2.1.0.5
  2. ...Upgrade the docker version 2.2.0.0
  3 ... Try to open latest version or Reinstall the docker version 2.1.05 and try in both of the cases it is crashing

Logs detailes below.

Version: 2.1.0.5 (40693)
Channel: stable
Sha1: 6fd76f1ada686b4e692d9cb9ec5bd7a9e74e275f
Started on: 2020/01/29 09:43:02.170
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1809
Build: 17763
BuildLabName: 17763.1.amd64fre.rs5_release.180914-1434
File: C:\Users\joshia6\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:43:02.755][GUI               ][Info   ] Starting...
[09:43:02.863][ComponentVersions ][Info   ] Edition community
[09:43:03.221][ComponentVersions ][Info   ] Edition community
[09:43:04.707][AppMigrator       ][Info   ] Current version: 5. Latest version: 5
[09:43:05.323][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[09:43:05.340][SegmentApi        ][Info   ] Usage statistic: Identify
[09:43:05.875][SegmentApi        ][Info   ] Usage statistic: appLaunched
[09:43:05.918][SegmentApi        ][Error  ] Failed to Identify: An error occurred while sending the request.
[09:43:05.936][SegmentApi        ][Error  ] Failed to track event appLaunched: An error occurred while sending the request.
[09:43:09.726][ApplicationTemplatesTracking][Info   ] Cannot list templates
[09:43:09.729][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[09:43:09.733][SegmentApi        ][Info   ] Usage statistic: heartbeat
[09:43:09.749][SegmentApi        ][Error  ] Failed to track event eventTemplatesInfo: An error occurred while sending the request.
[09:43:09.757][SegmentApi        ][Error  ] Failed to track event heartbeat: An error occurred while sending the request.
[09:43:09.940][NamedPipeClient   ][Info   ] Sending app/version()...
[09:43:09.979][NamedPipeClient   ][Info   ] Received response for app/version
[09:43:09.981][NamedPipeClient   ][Info   ] Sending app/migrate()...
[09:43:09.985][NamedPipeClient   ][Info   ] Received response for app/migrate
[09:42:06.091][ComponentVersions ][Info   ] Edition community
[09:42:06.637][Linux             ][Info   ] Setting container engine status to Stopped
[09:42:06.719][BackendNamedPipeServer][Info   ] Started
[09:43:09.976][NamedPipeServer   ][Info   ] app/version()
[09:43:09.977][NamedPipeServer   ][Info   ] app/version done in 00:00:00.0010011.
[09:43:09.982][NamedPipeServer   ][Info   ] app/migrate()
[09:43:10.005][NamedPipeClient   ][Info   ] Sending app/version()...
[09:43:10.009][NamedPipeClient   ][Info   ] Received response for app/version
[09:43:10.009][NamedPipeClient   ][Info   ] Sending version-packs/enable(community, Docker.Core.Settings)...
[09:43:09.985][NamedPipeServer   ][Info   ] app/migrate done in 00:00:00.0013268.
[09:43:10.008][NamedPipeServer   ][Info   ] app/version()
[09:43:10.008][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[09:43:10.028][NamedPipeClient   ][Info   ] Received response for version-packs/enable
[09:43:10.019][NamedPipeServer   ][Info   ] version-packs/enable(community, Docker.Core.Settings)
[09:43:10.028][NamedPipeServer   ][Info   ] version-packs/enable done in 00:00:00.0090028.
[09:43:10.073][NamedPipeClient   ][Info   ] Sending app/version()...
[09:43:10.074][NamedPipeClient   ][Info   ] Received response for app/version
[09:43:10.075][NamedPipeClient   ][Info   ] Sending engine/start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions, GLOBAL\joshia6:**********)...
[09:43:10.074][NamedPipeServer   ][Info   ] app/version()
[09:43:10.074][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[09:43:10.080][NamedPipeServer   ][Info   ] engine/start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions, GLOBAL\joshia6:**********)
[09:43:10.131][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\Resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[09:43:10.938][GoBackendProcess  ][Info   ] Started
[09:43:10.940][Linux             ][Info   ] Setting container engine status to Starting
[09:43:10.953][PowerShell        ][Info   ] Creating a Runspace Pool...
[09:43:11.069][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[09:43:11.069][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[09:43:11.069][GoBackendProcess  ][Info   ] time="2020-01-29T09:43:11+11:00" msg="started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl"
[09:43:11.070][GoBackendProcess  ][Debug  ] time="2020-01-29T09:43:11+11:00" msg="socket.ListenVsock: 4098"
[09:43:11.077][GoBackendProcess  ][Info   ] listening on 62372 for data connection
[09:43:11.077][GoBackendProcess  ][Info   ] ⇨ http server started on 00000000-0000-0000-0000-000000000000:00001002-facb-11e6-bd58-64006a7986d3
[09:43:11.235][PowerShell        ][Info   ] Runspace Pool created (Min=1, Max=2)
[09:43:11.715][PowerMode         ][Info   ] Stop
[09:43:11.717][HyperV            ][Info   ] Stop
[09:43:11.733][PowerShell        ][Info   ] Run script with parameters: -Stop True -Verbose True -ErrorAction Stop
[09:43:13.397][HyperV            ][Info   ] Exporting function 'Get-NetAdapter'.
[09:43:13.398][HyperV            ][Info   ] Exporting function 'Enable-NetAdapter'.
[09:43:13.399][HyperV            ][Info   ] Exporting function 'Disable-NetAdapter'.
[09:43:13.400][HyperV            ][Info   ] Exporting function 'Restart-NetAdapter'.
[09:43:13.401][HyperV            ][Info   ] Exporting function 'Rename-NetAdapter'.
[09:43:13.401][HyperV            ][Info   ] Exporting function 'Set-NetAdapter'.
[09:43:13.499][HyperV            ][Info   ] Exporting function 'New-NetAdapterAdvancedProperty'.
[09:43:13.500][HyperV            ][Info   ] Exporting function 'Get-NetAdapterAdvancedProperty'.
[09:43:13.500][HyperV            ][Info   ] Exporting function 'Set-NetAdapterAdvancedProperty'.
[09:43:13.501][HyperV            ][Info   ] Exporting function 'Remove-NetAdapterAdvancedProperty'.
[09:43:13.502][HyperV            ][Info   ] Exporting function 'Reset-NetAdapterAdvancedProperty'.
[09:43:13.555][HyperV            ][Info   ] Exporting function 'Get-NetAdapterBinding'.
[09:43:13.556][HyperV            ][Info   ] Exporting function 'Set-NetAdapterBinding'.
[09:43:13.556][HyperV            ][Info   ] Exporting function 'Enable-NetAdapterBinding'.
[09:43:13.557][HyperV            ][Info   ] Exporting function 'Disable-NetAdapterBinding'.
[09:43:13.621][HyperV            ][Info   ] Exporting function 'Get-NetAdapterChecksumOffload'.
[09:43:13.621][HyperV            ][Info   ] Exporting function 'Set-NetAdapterChecksumOffload'.
[09:43:13.622][HyperV            ][Info   ] Exporting function 'Enable-NetAdapterChecksumOffload'.
[09:43:13.623][HyperV            ][Info   ] Exporting function 'Disable-NetAdapterChecksumOffload'.
[09:43:13.694][HyperV            ][Info   ] Exporting function 'Get-NetAdapterEncapsulatedPacketTaskOffload'.
[09:43:13.695][HyperV            ][Info   ] Exporting function 'Set-NetAdapterEncapsulatedPacketTaskOffload'.
[09:43:13.698][HyperV            ][Info   ] Exporting function 'Enable-NetAdapterEncapsulatedPacketTaskOffload'.
[09:43:13.699][HyperV            ][Info   ] Exporting function 'Disable-NetAdapterEncapsulatedPacketTaskOffload'.
[09:43:13.739][HyperV            ][Info   ] Exporting function 'Get-NetAdapterHardwareInfo'.
[09:43:13.787][HyperV            ][Info   ] Exporting function 'Get-NetAdapterIPsecOffload'.
[09:43:13.787][HyperV            ][Info   ] Exporting function 'Set-NetAdapterIPsecOffload'.
[09:43:13.788][HyperV            ][Info   ] Exporting function 'Enable-NetAdapterIPsecOffload'.
[09:43:13.788][HyperV            ][Info   ] Exporting function 'Disable-NetAdapterIPsecOffload'.
[09:43:13.835][HyperV            ][Info   ] Exporting function 'Get-NetAdapterLso'.
[09:43:13.835][HyperV            ][Info   ] Exporting function 'Set-NetAdapterLso'.
[09:43:13.836][HyperV            ][Info   ] Exporting function 'Enable-NetAdapterLso'.
[09:43:13.836][HyperV            ][Info   ] Exporting function 'Disable-NetAdapterLso'.
[09:43:13.886][HyperV            ][Info   ] Exporting function 'Get-NetAdapterPowerManagement'.
[09:43:13.887][HyperV            ][Info   ] Exporting function 'Set-NetAdapterPowerManagement'.
[09:43:13.888][HyperV            ][Info   ] Exporting function 'Enable-NetAdapterPowerManagement'.
[09:43:13.888][HyperV            ][Info   ] Exporting function 'Disable-NetAdapterPowerManagement'.
[09:43:13.924][HyperV            ][Info   ] Exporting function 'Get-NetAdapterQos'.
[09:43:13.925][HyperV            ][Info   ] Exporting function 'Set-NetAdapterQos'.
[09:43:13.927][HyperV            ][Info   ] Exporting function 'Enable-NetAdapterQos'.
[09:43:13.929][HyperV            ][Info   ] Exporting function 'Disable-NetAdapterQos'.
[09:43:13.974][HyperV            ][Info   ] Exporting function 'Get-NetAdapterRdma'.
[09:43:13.975][HyperV            ][Info   ] Exporting function 'Set-NetAdapterRdma'.
[09:43:13.975][HyperV            ][Info   ] Exporting function 'Enable-NetAdapterRdma'.
[09:43:13.976][HyperV            ][Info   ] Exporting function 'Disable-NetAdapterRdma'.
[09:43:14.040][HyperV            ][Info   ] Exporting function 'Get-NetAdapterRsc'.
[09:43:14.041][HyperV            ][Info   ] Exporting function 'Set-NetAdapterRsc'.
[09:43:14.043][HyperV            ][Info   ] Exporting function 'Enable-NetAdapterRsc'.
[09:43:14.044][HyperV            ][Info   ] Exporting function 'Disable-NetAdapterRsc'.
[09:43:14.079][HyperV            ][Info   ] Exporting function 'Get-NetAdapterRss'.
[09:43:14.080][HyperV            ][Info   ] Exporting function 'Set-NetAdapterRss'.
[09:43:14.080][HyperV            ][Info   ] Exporting function 'Enable-NetAdapterRss'.
[09:43:14.080][HyperV            ][Info   ] Exporting function 'Disable-NetAdapterRss'.
[09:43:14.136][HyperV            ][Info   ] Exporting function 'Get-NetAdapterSriov'.
[09:43:14.136][HyperV            ][Info   ] Exporting function 'Set-NetAdapterSriov'.
[09:43:14.137][HyperV            ][Info   ] Exporting function 'Enable-NetAdapterSriov'.
[09:43:14.137][HyperV            ][Info   ] Exporting function 'Disable-NetAdapterSriov'.
[09:43:14.181][HyperV            ][Info   ] Exporting function 'Get-NetAdapterSriovVf'.
[09:43:14.215][HyperV            ][Info   ] Exporting function 'Get-NetAdapterStatistics'.
[09:43:14.272][HyperV            ][Info   ] Exporting function 'Get-NetAdapterVmq'.
[09:43:14.273][HyperV            ][Info   ] Exporting function 'Set-NetAdapterVmq'.
[09:43:14.274][HyperV            ][Info   ] Exporting function 'Enable-NetAdapterVmq'.
[09:43:14.277][HyperV            ][Info   ] Exporting function 'Disable-NetAdapterVmq'.
[09:43:14.306][HyperV            ][Info   ] Exporting function 'Get-NetAdapterVmqQueue'.
[09:43:14.334][HyperV            ][Info   ] Exporting function 'Get-NetAdapterVPort'.
[09:43:14.380][HyperV            ][Info   ] Exporting function 'Get-NetAdapterPacketDirect'.
[09:43:14.381][HyperV            ][Info   ] Exporting function 'Set-NetAdapterPacketDirect'.
[09:43:14.382][HyperV            ][Info   ] Exporting function 'Enable-NetAdapterPacketDirect'.
[09:43:14.382][HyperV            ][Info   ] Exporting function 'Disable-NetAdapterPacketDirect'.
[09:43:15.623][HyperV            ][Info   ] Exporting function 'Get-NetCompartment'.
[09:43:15.713][HyperV            ][Info   ] Exporting function 'New-NetIPAddress'.
[09:43:15.713][HyperV            ][Info   ] Exporting function 'Get-NetIPAddress'.
[09:43:15.713][HyperV            ][Info   ] Exporting function 'Set-NetIPAddress'.
[09:43:15.713][HyperV            ][Info   ] Exporting function 'Remove-NetIPAddress'.
[09:43:15.852][HyperV            ][Info   ] Exporting function 'Get-NetIPInterface'.
[09:43:15.854][HyperV            ][Info   ] Exporting function 'Set-NetIPInterface'.
[09:43:15.919][HyperV            ][Info   ] Exporting function 'Get-NetIPv4Protocol'.
[09:43:15.919][HyperV            ][Info   ] Exporting function 'Set-NetIPv4Protocol'.
[09:43:16.006][HyperV            ][Info   ] Exporting function 'Get-NetIPv6Protocol'.
[09:43:16.006][HyperV            ][Info   ] Exporting function 'Set-NetIPv6Protocol'.
[09:43:16.072][HyperV            ][Info   ] Exporting function 'New-NetNeighbor'.
[09:43:16.073][HyperV            ][Info   ] Exporting function 'Get-NetNeighbor'.
[09:43:16.073][HyperV            ][Info   ] Exporting function 'Set-NetNeighbor'.
[09:43:16.073][HyperV            ][Info   ] Exporting function 'Remove-NetNeighbor'.
[09:43:16.131][HyperV            ][Info   ] Exporting function 'Get-NetOffloadGlobalSetting'.
[09:43:16.132][HyperV            ][Info   ] Exporting function 'Set-NetOffloadGlobalSetting'.
[09:43:16.173][HyperV            ][Info   ] Exporting function 'Get-NetPrefixPolicy'.
[09:43:16.261][HyperV            ][Info   ] Exporting function 'New-NetRoute'.
[09:43:16.261][HyperV            ][Info   ] Exporting function 'Find-NetRoute'.
[09:43:16.261][HyperV            ][Info   ] Exporting function 'Get-NetRoute'.
[09:43:16.265][HyperV            ][Info   ] Exporting function 'Set-NetRoute'.
[09:43:16.265][HyperV            ][Info   ] Exporting function 'Remove-NetRoute'.
[09:43:16.313][HyperV            ][Info   ] Exporting function 'Get-NetTCPConnection'.
[09:43:16.384][HyperV            ][Info   ] Exporting function 'Get-NetTCPSetting'.
[09:43:16.384][HyperV            ][Info   ] Exporting function 'Set-NetTCPSetting'.
[09:43:16.437][HyperV            ][Info   ] Exporting function 'New-NetTransportFilter'.
[09:43:16.437][HyperV            ][Info   ] Exporting function 'Get-NetTransportFilter'.
[09:43:16.437][HyperV            ][Info   ] Exporting function 'Remove-NetTransportFilter'.
[09:43:16.474][HyperV            ][Info   ] Exporting function 'Get-NetUDPEndpoint'.
[09:43:16.523][HyperV            ][Info   ] Exporting function 'Get-NetUDPSetting'.
[09:43:16.523][HyperV            ][Info   ] Exporting function 'Set-NetUDPSetting'.
[09:43:16.604][HyperV            ][Info   ] Exporting function 'Get-NetIPConfiguration'.
[09:43:16.604][HyperV            ][Info   ] Exporting alias 'gip'.
[09:43:16.756][HyperV            ][Info   ] Exporting function 'Test-NetConnection'.
[09:43:16.756][HyperV            ][Info   ] Exporting alias 'TNC'.
[09:43:17.221][HyperV            ][Info   ] VM DockerDesktopVM does not exist
[09:43:17.221][HyperV            ][Debug  ] [stop] took 00:00:05.5014263 to run
[09:43:17.225][OptimizeDisk      ][Info   ] Optimize
[09:43:17.225][PowerShell        ][Info   ] Run script...
[09:43:17.250][Moby              ][Info   ] Stop
[09:43:17.290][HyperVGuids       ][Info   ] Installing GUIDs...
[09:43:17.290][PowerMode         ][Info   ] Start
[09:43:17.301][Firewall          ][Info   ] Removing all existing rules...
[09:43:17.301][HyperV            ][Info   ] Create
[09:43:17.301][HyperVGuids       ][Info   ] GUIDs installed
[09:43:17.356][PowerShell        ][Info   ] Run script with parameters: -Create True -VhdPathOverride C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx -VhdSize 17179869184 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 28 -PreferredIPAddress  -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-desktop.iso -Verbose True -ErrorAction Stop
[09:43:17.394][Firewall          ][Info   ] All existing rules are removed.
[09:43:17.394][Firewall          ][Info   ] Opening ports for SMB...
[09:43:17.477][Firewall          ][Info   ] Ports are opened
[09:43:19.892][HyperV            ][Info   ] Creating Switch: DockerNAT...
[09:43:44.148][HyperV            ][Error  ] Unable to create: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunAsync>d__6.MoveNext()
[09:43:44.148][Linux             ][Error  ] Failed to start: Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure . Let's retry
[09:43:44.148][Linux             ][Info   ] Setting container engine status to Starting
[09:43:44.249][Installer         ][Info   ] Checking for features: *Hyper-V*, Containers
[09:43:44.250][PowerShell        ][Info   ] Run script...
[09:43:51.938][PowerShell        ][Info   ] Run script...
[09:43:55.854][PowerShell        ][Info   ] Run script...
[09:43:59.955][PowerShell        ][Info   ] Run script...
[09:44:04.044][Installer         ][Info   ] Features installed
[09:44:04.120][HyperV            ][Info   ] Hyper-V is running
[09:44:04.120][PowerMode         ][Info   ] Stop
[09:44:04.120][HyperV            ][Info   ] Stop
[09:44:04.120][PowerShell        ][Info   ] Run script with parameters: -Stop True -Verbose True -ErrorAction Stop
[09:44:04.243][HyperV            ][Info   ] VM DockerDesktopVM does not exist
[09:44:04.244][HyperV            ][Debug  ] [stop] took 00:00:00.1238165 to run
[09:44:04.244][OptimizeDisk      ][Info   ] Optimize
[09:44:04.244][PowerShell        ][Info   ] Run script...
[09:44:04.258][Moby              ][Info   ] Stop
[09:44:04.303][HyperV            ][Info   ] Destroy
[09:44:04.303][PowerShell        ][Info   ] Run script with parameters: -KeepVolume True -Destroy True -Verbose True -ErrorAction Stop
[09:44:04.359][HyperV            ][Info   ] VM DockerDesktopVM does not exist
[09:44:04.366][HyperV            ][Info   ] Destroying Switch DockerNAT...
[09:44:06.359][HyperV            ][Info   ] Removing VM DockerDesktopVM...
[09:44:06.392][HyperV            ][Debug  ] [destroy] took 00:00:02.0884865 to run
[09:44:06.393][Firewall          ][Info   ] Closing ports...
[09:44:06.393][Firewall          ][Info   ] Removing all existing rules...
[09:44:06.454][Firewall          ][Info   ] All existing rules are removed.
[09:44:06.454][Firewall          ][Info   ] Ports are closed
[09:44:06.454][HyperVGuids       ][Info   ] Removing GUIDs...
[09:44:06.459][HyperVGuids       ][Info   ] GUIDs removed
[09:44:06.459][HyperV            ][Info   ] Create
[09:44:06.460][PowerShell        ][Info   ] Run script with parameters: -Create True -VhdPathOverride C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx -VhdSize 17179869184 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 28 -PreferredIPAddress  -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\docker-desktop.iso -Verbose True -ErrorAction Stop
[09:44:08.258][HyperV            ][Info   ] Creating Switch: DockerNAT...
[09:44:11.692][HyperV            ][Error  ] Unable to create: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.EndInvoke(IAsyncResult asyncResult)
   at Docker.Core.PowerShell.<>c__DisplayClass13_0.<InvokeAsync>b__0(IAsyncResult asyncResult)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<InvokeAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.PowerShell.<RunAsync>d__6.MoveNext()
[09:44:11.692][Linux             ][Info   ] Setting container engine status to FailedToStart
[09:44:11.695][NamedPipeServer   ][Error  ] Unable to execute engine/start: Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
   at Docker.Backend.HyperV.Create(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
[09:44:11.854][NamedPipeClient   ][Error  ] Unable to send engine/start: Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
[09:44:11.855][Notifications     ][Error  ] Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Generic failure 
[09:44:11.907][NamedPipeClient   ][Info   ] Sending app/version()...
[09:44:11.908][NamedPipeClient   ][Info   ] Received response for app/version
[09:44:11.908][NamedPipeClient   ][Info   ] Sending diagnostics/gather()...
[09:44:11.908][NamedPipeServer   ][Info   ] app/version()
[09:44:11.908][NamedPipeServer   ][Info   ] app/version done in 00:00:00.0009957.
[09:44:11.909][NamedPipeServer   ][Info   ] diagnostics/gather()
[09:44:23.295][SegmentApi        ][Info   ] Usage statistic: actionMenuCloudLogin
[09:44:33.683][SegmentApi        ][Info   ] Usage statistic: actionLoginSucceded
[09:44:36.576][DockerHub         ][Info   ] Login successfull
[09:44:39.709][SegmentApi        ][Info   ] Usage statistic: actionMenuSettings
[09:44:40.303][NamedPipeClient   ][Info   ] Sending app/version()...
[09:44:40.306][NamedPipeClient   ][Info   ] Received response for app/version
[09:44:40.306][NamedPipeClient   ][Info   ] Sending app/version()...
[09:44:40.306][NamedPipeClient   ][Info   ] Sending disk/get-size()...
[09:44:40.308][NamedPipeClient   ][Info   ] Received response for app/version
[09:44:40.308][NamedPipeClient   ][Info   ] Sending disk/get-size()...
[09:44:40.305][NamedPipeServer   ][Info   ] app/version()
[09:44:40.314][NamedPipeClient   ][Info   ] Received response for disk/get-size
[09:44:40.314][NamedPipeClient   ][Info   ] Received response for disk/get-size
[09:44:40.305][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[09:44:40.319][NamedPipeClient   ][Info   ] Sending app/version()...
[09:44:40.319][NamedPipeClient   ][Info   ] Sending app/version()...
[09:44:40.321][NamedPipeClient   ][Info   ] Received response for app/version
[09:44:40.321][NamedPipeClient   ][Info   ] Sending disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)...
[09:44:40.321][NamedPipeClient   ][Info   ] Received response for app/version
[09:44:40.321][NamedPipeClient   ][Info   ] Sending disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)...
[09:44:40.323][NamedPipeClient   ][Info   ] Received response for disk/get-size
[09:44:40.323][NamedPipeClient   ][Info   ] Received response for disk/get-size
[09:44:40.307][NamedPipeServer   ][Info   ] app/version()
[09:44:40.307][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[09:44:40.308][NamedPipeServer   ][Info   ] disk/get-size()
[09:44:40.310][NamedPipeServer   ][Info   ] disk/get-size()
[09:44:40.313][NamedPipeServer   ][Info   ] disk/get-size done in 00:00:00.0041990.
[09:44:40.313][NamedPipeServer   ][Info   ] disk/get-size done in 00:00:00.0021849.
[09:44:40.321][NamedPipeServer   ][Info   ] app/version()
[09:44:40.321][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[09:44:40.321][NamedPipeServer   ][Info   ] app/version()
[09:44:40.321][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[09:44:40.322][NamedPipeServer   ][Info   ] disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)
[09:44:40.323][NamedPipeServer   ][Info   ] disk/get-size done in 00:00:00.0010437.
[09:44:40.323][NamedPipeServer   ][Info   ] disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)
[09:44:40.323][NamedPipeServer   ][Info   ] disk/get-size done in 00:00:00.
[09:44:40.518][NamedPipeClient   ][Info   ] Sending app/version()...
[09:44:40.520][NamedPipeClient   ][Info   ] Received response for app/version
[09:44:40.520][NamedPipeClient   ][Info   ] Sending disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)...
[09:44:40.522][NamedPipeClient   ][Info   ] Received response for disk/get-size
[09:44:40.519][NamedPipeServer   ][Info   ] app/version()
[09:44:40.520][NamedPipeServer   ][Info   ] app/version done in 00:00:00.0009995.
[09:44:40.521][NamedPipeServer   ][Info   ] disk/get-size(C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx)
[09:44:40.522][NamedPipeServer   ][Info   ] disk/get-size done in 00:00:00.0010003.
[09:46:52.495][NamedPipeClient   ][Info   ] Received response for diagnostics/gather
[09:46:52.494][NamedPipeServer   ][Info   ] diagnostics/gather done in 00:02:40.5845499.
[09:51:37.650][SegmentApi        ][Info   ] Usage statistic: actionMenuAbout
[10:43:08.915][SegmentApi        ][Info   ] Usage statistic: heartbeat
[11:05:06.800][ErrorReportWindow ][Info   ] Open logs
[11:06:07.078][ErrorReportWindow ][Info   ] Open diagnostics
[11:13:22.231][ErrorReportWindow ][Info   ] Open logs

**Comment by UTHjarthur** [comment]
same issue here. also unable to remove at all
