### ISSUE TITLE
Docker Desktop Windows fails to start

### ISSUE THREAD

**Issue by rubygoldbergmachineinc** [docker/for-win#5655]
- [ X] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker Desktop Windows fails to start
### Actual behavior
Docker Desktop Windows 10 should start
### Information

  - Windows Version: 10
  - Docker Desktop Version:19.03.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
Launch Docker desktop engine and it fails with following error:

Unable to start Hyper-V VM: 'DockerDesktopVM' failed to start.
at Start-MobyLinuxVM, <No file>: line 688
at <ScriptBlock>, <No file>: line 811

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

---See logs here---------

Version: 2.2.0.0 (42247)
Channel: stable
Sha1: 2e3b4c91994e99da6458fe2291f2efbb3d5d80fe
Started on: 2020/01/30 19:01:48.493
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1709
Build: 16299
BuildLabName: 16299.637.amd64fre.rs3_release_svc.180808-1748
File: C:\Users\someuser.000\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[19:01:48.595][GUI               ][Info   ] Starting...
[19:01:48.616][ComponentVersions ][Info   ] Edition community
[19:01:48.684][ComponentVersions ][Info   ] Edition community
[19:01:49.737][AppMigrator       ][Info   ] Current version: 5. Latest version: 5
[19:01:49.739][GUI               ][Error  ] An instance is already running. Exiting.
[19:02:40.678][SegmentApi        ][Info   ] Usage statistic: actionMenuRestart
[19:02:40.697][App               ][Info   ] User clicked on restart
[19:02:40.699][Notifications     ][Info   ] Docker Desktop is restarting...
[19:02:40.717][SegmentApi        ][Info   ] Usage statistic: actionRestart
[19:02:40.737][NamedPipeClient   ][Info   ] Sending app/version()...
[19:02:40.738][NamedPipeClient   ][Info   ] Received response for app/version
[19:02:40.739][NamedPipeClient   ][Info   ] Sending engine/restart(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions, )...
[19:02:40.738][NamedPipeServer   ][Info   ] app/version()
[19:02:40.738][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[19:02:40.739][NamedPipeServer   ][Info   ] engine/restart(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions, )
[19:02:40.741][Linux             ][Info   ] Setting container engine status to Stopping
[19:02:40.741][PowerMode         ][Info   ] Stop
[19:02:40.741][HyperV            ][Info   ] Stop
[19:02:40.741][PowerShell        ][Info   ] Run script with parameters: -Stop True -VmName DockerDesktopVM -SwitchName DockerNAT -Verbose True -ErrorAction Stop
[19:02:40.843][HyperV            ][Info   ] VM DockerDesktopVM is stopped
[19:02:40.844][HyperV            ][Debug  ] [stop] took 00:00:00.1025350 to run
[19:02:40.844][OptimizeDisk      ][Info   ] Optimize
[19:02:40.844][PowerShell        ][Info   ] Run script...
[19:02:42.296][VpnKit            ][Info   ] Killing existing vpnkit with PID 5844
[19:02:42.304][VpnKitBridge      ][Info   ] Killing existing vpnkit-bridge with PID 16340
[19:02:42.312][Linux             ][Info   ] Setting container engine status to Stopped
[19:02:42.312][Linux             ][Info   ] Setting container engine status to Starting
[19:02:42.359][PowerMode         ][Info   ] Stop
[19:02:42.359][HyperV            ][Info   ] Stop
[19:02:42.360][PowerShell        ][Info   ] Run script with parameters: -Stop True -VmName DockerDesktopVM -SwitchName DockerNAT -Verbose True -ErrorAction Stop
[19:02:42.420][HyperV            ][Info   ] VM DockerDesktopVM is stopped
[19:02:42.420][HyperV            ][Debug  ] [stop] took 00:00:00.0609815 to run
[19:02:42.420][OptimizeDisk      ][Info   ] Optimize
[19:02:42.420][PowerShell        ][Info   ] Run script...
[19:02:43.491][APIRequestLogger  ][Info   ] [d93b2b57] <GoBackendClient start> GET http://localhost/features
[19:02:43.492][GoBackendProcess  ][Info   ] time="2020-01-30T19:02:43Z" msg="external: GET /features 200 \"\" \"\""
[19:02:43.496][APIRequestLogger  ][Info   ] [d93b2b57] <GoBackendClient end> GET http://localhost/features -> 200 OK (took 4ms)
[19:02:43.501][VpnKitBridge      ][Info   ] Starting C:\Program Files\Docker\Docker\resources\vpnkit-bridge.exe --addr listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3 host
[19:02:43.514][VpnKitBridge      ][Info   ] Started
[19:02:43.515][HyperV            ][Info   ] Create
[19:02:43.515][HyperVGuids       ][Info   ] Installing GUIDs...
[19:02:43.515][PowerMode         ][Info   ] Start
[19:02:43.515][HyperV            ][Info   ] filesharing does not need a Hyper-V NIC so omitting it
[19:02:43.515][HyperVGuids       ][Info   ] GUIDs installed
[19:02:43.515][Firewall          ][Info   ] Removing all existing rules...
[19:02:43.519][PowerShell        ][Info   ] Run script with parameters: -Create True -VmName DockerDesktopVM -VhdPathOverride C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx -VhdSize 68719476736 -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 28 -PreferredIPAddress  -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\resources\docker-desktop.iso -SwitchName  -Verbose True -ErrorAction Stop
[19:02:43.551][Firewall          ][Info   ] All existing rules are removed.
[19:02:43.551][Firewall          ][Info   ] Opening ports for SMB...
[19:02:43.567][Firewall          ][Info   ] Ports are opened
[19:02:43.587][HyperV            ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[19:02:43.608][VpnKitBridge      ][Info   ] time="2020-01-30T19:02:43Z" msg="listening on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3..."
[19:02:43.612][VpnKitBridge      ][Info   ] time="2020-01-30T19:02:43Z" msg="waiting for connection on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3..."
[19:02:43.767][HyperV            ][Info   ] Remove existing DVDs
[19:02:44.893][HyperV            ][Info   ] Attach DVD C:\Program Files\Docker\Docker\resources\docker-desktop.iso
[19:02:45.455][HyperV            ][Info   ] Disabled Guest Service Interface
[19:02:45.476][HyperV            ][Info   ] Enabled Heartbeat
[19:02:45.496][HyperV            ][Info   ] Disabled Key-Value Pair Exchange
[19:02:45.513][HyperV            ][Info   ] Enabled Shutdown
[19:02:45.532][HyperV            ][Info   ] Enabled Time Synchronization
[19:02:45.549][HyperV            ][Info   ] Disabled VSS
[19:02:45.657][HyperV            ][Info   ] VM created.
[19:02:45.657][HyperV            ][Debug  ] [create] took 00:00:02.1422643 to run
[19:02:45.657][PowerShell        ][Info   ] Run script '(Hyper-V\Get-VM DockerDesktopVM).Id.Guid'...
[19:02:45.673][IsoConfig         ][Info   ] Generating CA Cert Bundle
[19:02:45.704][IsoConfig         ][Info   ] CA Cert Bundle Generated
[19:02:45.841][HyperV            ][Info   ] Start
[19:02:45.841][PowerShell        ][Info   ] Run script with parameters: -Start True -VmName DockerDesktopVM -IsoFile C:\Program Files\Docker\Docker\resources\docker-desktop.iso -confIsoFile C:\ProgramData\DockerDesktop\tmp-d4w\config.iso -VhdPathOverride C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx -DockerIsoFile C:\Program Files\Docker\Docker\resources\docker.iso -Verbose True -ErrorAction Stop
[19:02:45.883][HyperV            ][Info   ] Starting VM DockerDesktopVM...
[19:02:45.993][VpnKit            ][Info   ] vpnkit.exe: Setting handler to ignore all SIGPIPE signals
[19:02:45.993][VpnKit            ][Info   ] vpnkit.exe: Version is 218f01482560cba2fa863f9ad872ad51d1e717fc
[19:02:45.993][VpnKit            ][Info   ] vpnkit.exe: System SOMAXCONN is 2147483647
[19:02:45.993][VpnKit            ][Info   ] vpnkit.exe: Will use a listen backlog of 32
[19:02:45.993][VpnKit            ][Info   ] vpnkit.exe: No periodic Gc.compact enabled
[19:02:45.993][VpnKit            ][Error  ] vpnkit.exe: Starting to watch : EINVAL
[19:02:45.993][VpnKit            ][Error  ] vpnkit.exe: Failed to watch hosts file : invalid argument
[19:02:45.993][VpnKit            ][Warning] vpnkit.exe: There is no database: using hardcoded network configuration values
[19:02:45.993][VpnKit            ][Info   ] vpnkit.exe: DNS server configured with no builtin DNS names; everything will be forwarded
[19:02:45.993][VpnKit            ][Info   ] vpnkit.exe: 2 upstream DNS servers are configured
[19:02:45.993][VpnKit            ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
[19:02:45.993][VpnKit            ][Info   ] vpnkit.exe: Disabling transparent HTTP redirection
[19:02:45.993][VpnKit            ][Info   ] vpnkit.exe: Updating resolvers to use host resolver
[19:02:45.993][VpnKit            ][Info   ] vpnkit.exe: Secure random number generator is available
[19:02:45.993][VpnKit            ][Info   ] vpnkit.exe: Add(3): DNS configuration changed to: use host resolver
[19:02:45.993][VpnKit            ][Info   ] vpnkit.exe: DNS server configured with builtin DNS names [ gateway.docker.internal -> 192.168.65.1, docker.for.win.gateway.internal -> 192.168.65.1, docker.for.win.http.internal -> 192.168.65.1, host.docker.internal -> 192.168.65.2, docker.for.win.host.internal -> 192.168.65.2, docker.for.win.localhost -> 192.168.65.2, vm.internal -> 192.168.65.3 ]
[19:02:45.994][VpnKit            ][Info   ] vpnkit.exe: Will use the host's DNS resolver
[19:02:45.994][VpnKit            ][Info   ] vpnkit.exe: Transparent HTTP redirection configuration file C:\Users\someuser.000\AppData\Roaming\Docker\http_proxy.json has changed
[19:02:45.994][VpnKit            ][Info   ] vpnkit.exe: Reading transparent HTTP redirection from C:\Users\someuser.000\AppData\Roaming\Docker\http_proxy.json
[19:02:45.994][VpnKit            ][Info   ] vpnkit.exe: Watching transparent HTTP redirection configuration file C:\Users\someuser.000\AppData\Roaming\Docker\http_proxy.json for changes
[19:02:45.994][VpnKit            ][Info   ] vpnkit.exe: New Gateway forward configuration: []
[19:02:45.994][VpnKit            ][Info   ] vpnkit.exe: Gateway forwards file C:\Users\someuser.000\AppData\Roaming\Docker\gateway_forwards.json has changed
[19:02:45.994][VpnKit            ][Info   ] vpnkit.exe: Reading gateway forwards file from C:\Users\someuser.000\AppData\Roaming\Docker\gateway_forwards.json
[19:02:45.994][VpnKit            ][Info   ] vpnkit.exe: Watching gateway forwards file C:\Users\someuser.000\AppData\Roaming\Docker\gateway_forwards.json for changes
[19:02:45.994][VpnKit            ][Info   ] vpnkit.exe: Configuration server_macaddr = f6:16:36:bc:f9:c6; max_connection = None; dns_path = None; dns = ; resolver = Host; domain = None; allowed_bind_addresses = 0.0.0.0; gateway_ip = 192.168.65.1; host_ip = 192.168.65.2; lowest_ip = 192.168.65.3; highest_ip = 192.168.65.14; dhcp_json_path = None; dhcp_configuration = None; mtu = 1500; http_intercept = None; http_intercept_path = C:\Users\someuser.000\AppData\Roaming\Docker\http_proxy.json; port_max_idle_time = 300; host_names = host.docker.internal, docker.for.win.host.internal, docker.for.win.localhost; gateway_names = gateway.docker.internal, docker.for.win.gateway.internal, docker.for.win.http.internal; vm_names = vm.internal; udpv4_forwards = []; tcpv4_forwards = []; gateway_forwards_path = C:\Users\someuser.000\AppData\Roaming\Docker\gateway_forwards.json; pcap_snaplen = 128
[19:02:45.994][VpnKit            ][Error  ] vpnkit.exe: While watching C:\Users\someuser.000\AppData\Roaming\Docker\gateway_forwards.json: ENOENT
[19:02:45.994][VpnKit            ][Error  ] vpnkit.exe: Failed to read gateway forwards from C:\Users\someuser.000\AppData\Roaming\Docker\gateway_forwards.json: reading C:\Users\someuser.000\AppData\Roaming\Docker\gateway_forwards.json: No such file or directory.
[19:02:45.994][VpnKit            ][Info   ] vpnkit.exe: New Gateway forward configuration: []
[19:02:45.994][VpnKit            ][Info   ] vpnkit.exe: Updating transparent HTTP redirection: {
[19:02:45.994][VpnKit            ][Info   ]   "exclude": "",
[19:02:45.994][VpnKit            ][Info   ]   "transparent_http_ports": [
[19:02:45.994][VpnKit            ][Info   ]     80
[19:02:45.994][VpnKit            ][Info   ]   ],
[19:02:45.994][VpnKit            ][Info   ]   "transparent_https_ports": [
[19:02:45.994][VpnKit            ][Info   ]     443
[19:02:45.994][VpnKit            ][Info   ]   ]
[19:02:45.994][VpnKit            ][Info   ] }
[19:02:45.998][HyperV            ][Info   ] Remove existing DVDs
[19:02:46.354][HyperV            ][Info   ] Attach DVD C:\Program Files\Docker\Docker\resources\docker-desktop.iso
[19:02:46.592][HyperV            ][Info   ] Attach Config ISO C:\ProgramData\DockerDesktop\tmp-d4w\config.iso
[19:02:47.000][HyperV            ][Info   ] Attach Docker ISO C:\Program Files\Docker\Docker\resources\docker.iso
[19:02:49.955][NamedPipeClient   ][Error  ] Unable to send engine/restart: Unable to start Hyper-V VM: 'DockerDesktopVM' failed to start.
at Start-MobyLinuxVM, <No file>: line 688
at <ScriptBlock>, <No file>: line 811
[19:02:49.955][Notifications     ][Error  ] Unable to start Hyper-V VM: 'DockerDesktopVM' failed to start.
at Start-MobyLinuxVM, <No file>: line 688
at <ScriptBlock>, <No file>: line 811
[19:02:49.953][HyperV            ][Error  ] Unable to start Hyper-V VM: Microsoft.HyperV.PowerShell.VirtualizationException: 'DockerDesktopVM' failed to start. ---> Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException: 'DockerDesktopVM' failed to start.
   at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
   at Microsoft.Virtualization.Client.Management.VMComputerSystemBaseView.EndSetState(IVMTask setStateTask)
   at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.<>c__DisplayClass4_0`1.<ConvertActionToFunction>b__0(T x)
   at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
   at Microsoft.HyperV.PowerShell.VirtualMachine.ChangeState(VirtualMachineAction action, IOperationWatcher operationWatcher)
   at Microsoft.HyperV.PowerShell.Commands.StartVM.ProcessOneOperand(VirtualMachine vm, IOperationWatcher operationWatcher)
   at Microsoft.HyperV.PowerShell.Commands.VirtualizationCmdlet`1.ProcessOperands(IList`1 operands, IOperationWatcher operationWatcher)
   --- End of inner exception stack trace ---
at Start-MobyLinuxVM, <No file>: line 688
at <ScriptBlock>, <No file>: line 811
[19:02:49.953][Linux             ][Info   ] Setting container engine status to FailedToStart
[19:02:49.959][GUI               ][Info   ] Sending Bugsnag report 3befe3e5-0e57-495a-a12e-13f206b20908...
[19:02:49.954][NamedPipeServer   ][Error  ] Unable to execute engine/restart: Unable to start Hyper-V VM: 'DockerDesktopVM' failed to start.
at Start-MobyLinuxVM, <No file>: line 688
at <ScriptBlock>, <No file>: line 811    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_3(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[19:02:50.177][GUI               ][Info   ] Bugsnag report 3befe3e5-0e57-495a-a12e-13f206b20908 sent
[19:02:50.178][SegmentApi        ][Info   ] Usage statistic: eventCrash
[19:02:50.198][NamedPipeClient   ][Info   ] Sending app/version()...
[19:02:50.199][NamedPipeClient   ][Info   ] Received response for app/version
[19:02:50.199][NamedPipeClient   ][Info   ] Sending diagnostics/gather()...
[19:02:50.198][NamedPipeServer   ][Info   ] app/version()
[19:02:50.198][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[19:02:50.204][NamedPipeServer   ][Info   ] diagnostics/gather()
[19:02:52.643][ErrorReportWindow ][Info   ] Open logs

**Comment by ircaxn** [comment]
Facing the same issue in my environment as well. any solutions?

**Comment by rprashantsingh** [comment]
Same issues here as well. 
Could it be a network/security setting (from the OS) that is blocking something on hyper-V, and hence the VM does not start? I also manually tried starting the DockerDesktopVM from the Hyper-V manager, which also fails with an error `DockerDesktop VM failed to start`. Any help on this would be appreciated..
