### ISSUE TITLE
Docker Desktop crashes after Windows 10 update

### ISSUE THREAD

**Issue by plleg** [docker/for-win#5663]
- [X ] I have tried with the latest version of my channel (Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: 2F4E65B5-BC26-4EAB-94A4-E8AFD65D5F42/20200131152021

### Expected behavior
Docker Desktop starts up

### Actual behavior
Docker Desktop crashes when trying to start up

### Information

  - Is it reproducible?  yes. it happens every time now.
  - Is the problem new? yes. just started happening after Windows 10 update
  - Did the problem appear with an update? yes
  - Windows Version: Windows 10 Pro insider preview. 10.0.19555
  - Docker Desktop Version: 2.1.7.0 (41436) Edge
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior
  1. reboot computer
  2. ( Docker Desktop is set to startup with Windows 10 )

**Comment by sc0ttwad3** [comment]
Same here!

**Comment by gabrewer** [comment]
I have a similar issue where docker is hanging after upgrading to 10.0.19555

**Comment by rmja** [comment]
Same here,

<details>
<summary>Content of %LOCALAPPDATA%\Docker\log.txt</summary>

```
Version: 2.1.7.0 (41536)
Channel: edge
Sha1: 5137ea9e944f83afdcd9dea9815fd0e2fd1d43d6
Started on: 2020/02/03 09:31:53.559
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 2004
Build: 19555
BuildLabName: 19555.1001.amd64fre.rs_prerelease.200127-0900
File: C:\Users\Rasmus\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:31:53.668][GUI               ][Info   ] Starting...
[09:31:53.699][ComponentVersions ][Info   ] Edition community
[09:31:53.746][ComponentVersions ][Info   ] Edition community
[09:31:53.996][AppMigrator       ][Info   ] Current version: 5. Latest version: 5
[09:31:54.155][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[09:31:54.158][SegmentApi        ][Info   ] Usage statistic: Identify
[09:31:54.232][SegmentApi        ][Info   ] Usage statistic: appLaunched
[09:31:54.575][ApplicationTemplatesTracking][Info   ] Cannot list templates
[09:31:54.575][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[09:31:54.606][SegmentApi        ][Info   ] Usage statistic: heartbeat
[09:31:54.716][NamedPipeClient   ][Info   ] Sending app/version()...
[09:31:54.716][NamedPipeClient   ][Info   ] Received response for app/version
[09:31:54.716][NamedPipeClient   ][Info   ] Sending app/migrate()...
[09:31:54.716][NamedPipeClient   ][Info   ] Received response for app/migrate
[09:31:52.415][WslEngine         ][Info   ] Setting container engine status to Stopped
[09:31:52.415][GoBackendProcess  ][Info   ] Killing existing com.docker.backend with PID 13744
[09:31:52.431][NamedPipeServer   ][Info   ] engine/stop done in 00:00:10.2124469.
[09:31:52.431][NamedPipeServer   ][Error  ] Pipe failure: Pipe is broken.    at System.IO.Pipes.PipeStream.WinIOError(Int32 errorCode)
   at System.IO.Pipes.PipeStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at Docker.Core.Pipe.NamedPipeServer.<HandleRequestAsync>d__13.MoveNext()
[09:31:54.716][NamedPipeServer   ][Info   ] app/version()
[09:31:54.716][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[09:31:54.716][NamedPipeServer   ][Info   ] app/migrate()
[09:31:54.716][NamedPipeServer   ][Info   ] app/migrate done in 00:00:00.
[09:31:54.764][NamedPipeClient   ][Info   ] Sending app/version()...
[09:31:54.764][NamedPipeClient   ][Info   ] Received response for app/version
[09:31:54.764][NamedPipeClient   ][Info   ] Sending version-packs/enable(community, Docker.Core.Settings)...
[09:31:54.764][NamedPipeClient   ][Info   ] Received response for version-packs/enable
[09:31:54.764][NamedPipeServer   ][Info   ] app/version()
[09:31:54.764][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[09:31:54.764][NamedPipeServer   ][Info   ] version-packs/enable(community, Docker.Core.Settings)
[09:31:54.764][NamedPipeServer   ][Info   ] version-packs/enable done in 00:00:00.
[09:31:54.780][NamedPipeClient   ][Info   ] Sending app/version()...
[09:31:54.780][NamedPipeClient   ][Info   ] Received response for app/version
[09:31:54.780][NamedPipeClient   ][Info   ] Sending engine/start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions, DESKTOP-5VE6KMP\Rasmus:**********)...
[09:31:54.780][NamedPipeServer   ][Info   ] app/version()
[09:31:54.780][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[09:31:54.780][NamedPipeServer   ][Info   ] engine/start(Linux, Docker.Core.Settings, Docker.Core.DaemonOptions, DESKTOP-5VE6KMP\Rasmus:**********)
[09:31:54.811][WslEngine         ][Info   ] Setting container engine status to Starting
[09:31:54.811][WslEngine         ][Info   ] Checking pre-conditions
[09:31:54.811][Installer         ][Info   ] Checking for features: VirtualMachinePlatform, Microsoft-Windows-Subsystem-Linux
[09:31:55.372][Installer         ][Info   ] Features installed
[09:31:55.384][APIRequestLogger  ][Info   ] [35025026] <Server start> GET http://unix/versions
[09:31:55.431][WslEngine         ][Info   ] Starting engine
[09:31:55.464][APIRequestLogger  ][Info   ] [35025026] <Server end> GET http://unix/versions -> 200 OK (took 90ms)
[09:31:55.519][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[09:31:55.529][APIRequestLogger  ][Info   ] [d8aff9aa] <Server start> GET http://unix/settings
[09:31:55.519][GoBackendProcess  ][Info   ] time="2020-02-03T09:31:55+01:00" msg="started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl"
[09:31:55.521][GoBackendProcess  ][Info   ] time="2020-02-03T09:31:55+01:00" msg="listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection"
[09:31:55.521][GoBackendProcess  ][Info   ] time="2020-02-03T09:31:55+01:00" msg="grpcfuseV2 feature-flag set so enabling FUSE cache invalidation"
[09:31:55.525][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[09:31:55.525][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[09:31:55.621][APIRequestLogger  ][Info   ] [d8aff9aa] <Server end> GET http://unix/settings -> 200 OK (took 107ms)
[09:31:55.664][GoBackendProcess  ][Info   ] time="2020-02-03T09:31:55+01:00" msg="Adding filesystem export C:\\"
[09:31:55.664][GoBackendProcess  ][Info   ] time="2020-02-03T09:31:55+01:00" msg="Adding filesystem export D:\\"
[09:31:55.664][GoBackendProcess  ][Info   ] time="2020-02-03T09:31:55+01:00" msg="Adding filesystem export G:\\"
[09:31:55.664][GoBackendProcess  ][Info   ] time="2020-02-03T09:31:55+01:00" msg="filesystem exports are: C:\\ (2),D:\\ (3),G:\\ (4)"
[09:31:55.664][GoBackendProcess  ][Info   ] time="2020-02-03T09:31:55+01:00" msg="grpcfuseInotifyEventsV0 feature-flag set so enabling inotify event injection"
[09:31:55.664][GoBackendProcess  ][Info   ] time="2020-02-03T09:31:55+01:00" msg="volume control server listening on \\\\.\\pipe\\dockerVolume"
[09:31:55.667][GoBackendProcess  ][Info   ] time="2020-02-03T09:31:55+01:00" msg="filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3"
[09:31:55.667][GoBackendProcess  ][Info   ] time="2020-02-03T09:31:55+01:00" msg="file ownership will be determined by the calling user (\"fake owner\" mode)"
[09:31:55.667][GoBackendProcess  ][Info   ] time="2020-02-03T09:31:55+01:00" msg="using mfsymlinks"
[09:31:56.277][DockerHub         ][Info   ] Login successfull
[09:32:05.625][WslEngine         ][Error  ] Failed to check wsl-bootstrap version: exit code: 1
 stdout(utf8): 
 stdout(unicode): 
  stderr (utf8): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

  stderr (unicode): ???????????????????????????????4?????????????????????????????????????????????????????????????
[09:32:05.625][WslEngine         ][Error  ] Failed to start: Failed to check wsl-bootstrap version: exit code: 1
 stdout(utf8): 
 stdout(unicode): 
  stderr (utf8): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

  stderr (unicode): ???????????????????????????????4?????????????????????????????????????????????????????????????. Let's retry
[09:32:05.625][WslEngine         ][Info   ] Setting container engine status to FailedToStart
[09:32:05.625][WslEngine         ][Info   ] Setting container engine status to Starting
[09:32:05.625][WslEngine         ][Info   ] Checking pre-conditions
[09:32:05.625][Installer         ][Info   ] Checking for features: VirtualMachinePlatform, Microsoft-Windows-Subsystem-Linux
[09:32:06.116][Installer         ][Info   ] Features installed
[09:32:06.179][WslEngine         ][Info   ] Starting engine
[09:32:16.347][NamedPipeClient   ][Error  ] Unable to send engine/start: Failed to check wsl-bootstrap version: exit code: 1
 stdout(utf8): 
 stdout(unicode): 
  stderr (utf8): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

  stderr (unicode): ???????????????????????????????4?????????????????????????????????????????????????????????????
[09:32:16.347][Notifications     ][Error  ] Failed to check wsl-bootstrap version: exit code: 1
 stdout(utf8): 
 stdout(unicode): 
  stderr (utf8): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

  stderr (unicode): ???????????????????????????????4?????????????????????????????????????????????????????????????
[09:32:16.347][WslEngine         ][Error  ] Failed to check wsl-bootstrap version: exit code: 1
 stdout(utf8): 
 stdout(unicode): 
  stderr (utf8): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

  stderr (unicode): ???????????????????????????????4?????????????????????????????????????????????????????????????
[09:32:16.347][WslEngine         ][Error  ] Failed to start: Failed to check wsl-bootstrap version: exit code: 1
 stdout(utf8): 
 stdout(unicode): 
  stderr (utf8): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

  stderr (unicode): ???????????????????????????????4?????????????????????????????????????????????????????????????. Let's retry
[09:32:16.347][WslEngine         ][Info   ] Setting container engine status to FailedToStart
[09:32:16.347][NamedPipeServer   ][Error  ] Unable to execute engine/start: Failed to check wsl-bootstrap version: exit code: 1
 stdout(utf8): 
 stdout(unicode): 
  stderr (utf8): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

  stderr (unicode): ???????????????????????????????4?????????????????????????????????????????????????????????????    at Docker.Backend.ContainerEngine.WslEngine.WslOneShotResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode)
   at Docker.Backend.ContainerEngine.WslEngine.get_IsDistroDeployed()
   at Docker.Backend.ContainerEngine.WslEngine.DoStart(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential, Boolean retry)
   at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential, Boolean retry)
   at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[09:32:16.363][GUI               ][Info   ] Sending Bugsnag report 4f8acd35-0edd-4582-9ccd-57505d121ead...
[09:32:18.287][GUI               ][Info   ] Bugsnag report 4f8acd35-0edd-4582-9ccd-57505d121ead sent
[09:32:18.302][SegmentApi        ][Info   ] Usage statistic: eventCrash
[09:32:18.334][NamedPipeClient   ][Info   ] Sending app/version()...
[09:32:18.334][NamedPipeClient   ][Info   ] Received response for app/version
[09:32:18.334][NamedPipeClient   ][Info   ] Sending diagnostics/gather()...
[09:32:18.334][NamedPipeServer   ][Info   ] app/version()
[09:32:18.334][NamedPipeServer   ][Info   ] app/version done in 00:00:00.
[09:32:18.349][NamedPipeServer   ][Info   ] diagnostics/gather()
```

</details>

**Comment by silashansen** [comment]
Same here.
My log is identical to @rmja

**Comment by rmja** [comment]
I think this is related to https://github.com/microsoft/WSL/issues/4860

**Comment by jmar5439** [comment]
same here

**Comment by tim-pluralgroup** [comment]
I am having same issues - same environment - and 
Failed to check wsl-bootstrap version: exit code: 1

**Comment by tim-pluralgroup** [comment]
reported several days ago- no response as yet

**Comment by mat007** [comment]
This looks a lot like microsoft/WSL#4726

**Comment by jmar5439** [comment]
I disabled automatic init mode for all Docker services and my problems have disappeared. 
In order to init WLS2 and docker with no problems was init "docker desktop" after Windows 10 boot.
Even thought a new docker version  was released yesterday  and  it looks that kind of problems with WLS2 seems solved. ( anyways I keep Docker disabled on boot)

**Comment by koppor** [comment]
I followed @jmar5439's recommendation: Stop "Docker Desktop Serce" (in `services.msc`). Start "Docker Desktop" (version 2.2.0.5 with engine 19.03.8). It works perfectly.

    Microsoft Windows [Version 10.0.19587.1000]

My error log report has strange German, English, Chinese language mixture:

```
Docker.Core.Backend.BackendException:
Failed to check wsl-bootstrap version: exit code: 1
 stdout(utf8): 
 stdout(unicode): 
  stderr (utf8): Der Remoteprozeduraufruf ist fehlgeschlagen und wurde nicht ausgef�hrt.

  stderr (unicode): 敄⁲敒潭整牰穯摥牵畡牦晵椠瑳映桥杬獥档慬敧⁮湵⁤畷摲⁥楮档⁴畡杳晥棼瑲മ਍
   bei Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   bei Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   bei Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   bei Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.InvalidOperationException:
  Failed to check wsl-bootstrap version: exit code: 1
 stdout(utf8): 
 stdout(unicode): 
  stderr (utf8): Der Remoteprozeduraufruf ist fehlgeschlagen und wurde nicht ausgef�hrt.

    stderr (unicode): 敄⁲敒潭整牰穯摥牵畡牦晵椠瑳映桥杬獥档慬敧⁮湵⁤畷摲⁥楮档⁴畡杳晥棼瑲മ਍
     bei Docker.Backend.ContainerEngine.WslEngine.WslOneShotResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode)
     bei Docker.Backend.ContainerEngine.WslEngine.get_IsDistroDeployed()
     bei Docker.Backend.ContainerEngine.WslEngine.DoStart(Settings settings, String daemonOptions, Credential credential)
     bei Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential, Boolean retry)
     bei Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential, Boolean retry)
     bei Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential)
     bei Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
     bei Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
     bei Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
  
```

**Comment by bascisco** [comment]
Installed docker for desktop Windows 10  2.3.0.4 latest stable on Windows 10 
![image](https://user-images.githubusercontent.com/43781523/92137318-48b49080-ee0d-11ea-9217-509079c3f713.png)

I am running this in VMworkstation as a VM. 

Starting docker and it crashed.
[log.0.txt](https://github.com/docker/for-win/files/5169719/log.0.txt)
[log.1.txt](https://github.com/docker/for-win/files/5169720/log.1.txt)

Brgds, 
Bas
