### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by abrown** [docker/for-win#568]
### Expected behavior

Should start and run

### Actual behavior

```
Docker hv-sock proxy (vsudd) is not reachable at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource1 vmId)
at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.b__0(Object[] parameters)
at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu: crash log C479241E-0BA7-4AC8-B2F3-ED2E2E6128F3/2017-03-09_15-26-01
  - host distribution and version: Windows 10, Version 1511 (OS Build 10586.753)

### Steps to reproduce the behavior

  1. Updated Docker... unfortunately
  2. Attempt to run

**Comment by abrown** [comment]
I should say that the solutions #406 and #447 (i.e. update Windows) will not work for me because I am in an enterprise environment where updates are disabled. Is there a way to roll back the update?

**Comment by ankursaini2006** [comment]
I had the same issue on my windows 10 laptop. I have been trying to resolve it for 4 days and finally I am able to resolve it.

Since my laptop is enterprise one so Docker on windows was not running on startup with Admin rights. Then I tried to open Docker for Windows.exe with "Run as Admin" and then it worked correctly.

I hope this would help others also who are facing the similar issue.

**Comment by patrick-mota** [comment]
I'm like @ankursaini2006 but no success here... still having the same problem.

**Comment by abrown** [comment]
The only thing that worked for me was finally convincing my enterprise IT department to allow me update to Windows 10, Version 1607. This does solve the issue.

**Comment by patrick-mota** [comment]
I'm already on 1607 (14393.0) sadly :(

**Comment by bailey189** [comment]
I had success fixing this issue in Windows 2016 [10.0.14393] by disabling the firewall

**Comment by w9n** [comment]
same problem with windows 1703 as a qemu guest, other hyper v guest in windows work. Disabling firewall does not fix it.

**Comment by Crazee** [comment]
Still happening with windows 10 1703. It's "easily reproducible" for me.
 Diagnostic ID: B21A5BD4-A481-421A-AA4C-E29E132F289A/2017-05-15_07-10-41

Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by Crazee** [comment]
Tried "Run as Administrator".  Same result.

**Comment by Crazee** [comment]
Though it looks from the logs things had not gone well before it got to the vsudd failure:

```
[08:18:40.304][Moby           ][Info   ] Hierarchical RCU implementation.
[08:18:40.319][Moby           ][Info   ] 	Build-time adjustment of leaf fanout to 64.
[08:18:40.336][Moby           ][Info   ] Using NULL legacy PIC
[08:18:40.351][Moby           ][Info   ] NR_IRQS:8448 nr_irqs:1448 0
[08:18:40.382][Moby           ][Info   ] Console: colour dummy device 80x25
[08:18:40.398][Moby           ][Info   ] console [ttyS0] enabled
[08:18:40.413][Moby           ][Info   ] console [ttyS0] enabled
[08:18:40.429][Moby           ][Info   ] bootconsole [earlyser0] disabled
[08:18:40.444][Moby           ][Info   ] bootconsole [earlyser0] disabled
[08:18:42.429][Moby           ][Info   ] tsc: Fast TSC calibration failed
[08:18:42.444][Moby           ][Info   ] tsc: Unable to calibrate against PIT
[08:18:42.460][Moby           ][Info   ] tsc: HPET/PMTIMER calibration failed
[08:19:32.086][PowerMode      ][Info   ] Stop
[08:19:32.086][HyperV         ][Info   ] Stop
[08:19:32.086][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[08:19:32.133][HyperV         ][Info   ] Script started at 08:19:32.133
[08:19:32.195][HyperV         ][Info   ] Module loaded at 08:19:32.195
[08:19:32.414][HyperV         ][Info   ] Stopping VM MobyLinuxVM...
[08:19:46.008][Moby           ][Info   ] Calibrating delay loop... 
[08:19:46.008][Moby           ][Error  ] Failed to read Moby's logs: The operation has timed out.
[08:19:47.336][HyperV         ][Info   ] Turn Off VM ...
[08:19:47.383][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[08:19:47.383][HyperV         ][Debug  ] [stop] took 00:00:15.2966004 to run
[08:19:47.383][OptimizeDisk   ][Info   ] Optimize
[08:19:47.383][PowerShell     ][Info   ] Run script...
[08:19:49.899][Moby           ][Info   ] Stop
[08:19:49.914][VpnKit         ][Info   ] Killing existing com.docker.slirp with PID 6560
[08:19:49.930][DataKit        ][Info   ] Killing existing com.docker.db with PID 3552
[08:19:49.945][HyperV         ][Info   ] Destroy
[08:19:49.945][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[08:19:49.976][HyperV         ][Info   ] Script started at 08:19:49.976
[08:19:50.023][HyperV         ][Info   ] Module loaded at 08:19:50.023
[08:19:50.086][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[08:19:50.086][HyperV         ][Info   ] Destroying Switch DockerNAT...
[08:19:52.758][HyperV         ][Info   ] Removing VM MobyLinuxVM...
```

**Comment by sardesh** [comment]
I am also facing the same issue. A diagnostic was uploaded with id: 12F57557-BA42-43CD-89CC-D765E48A5CAC/2017-05-27_18-40-21

**Comment by stephan7878** [comment]
Also getting this issue with latest stable version of Docker.

Version: 17.06.0-rc2-ce-win14 (12510)
Channel: edge
Sha1: e4067577a34951ceb09b9e7d029cbdff2ca0ffb4
Started on: 2017/06/09 13:50:01.181
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.206.amd64fre.rs1_release.160915-0644
File: C:\Users\Bob\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 

[omitted]

[13:53:08.088][NamedPipeServer][Error  ] Unable to execute Start: Docker hv-sock proxy (vsudd) is not reachable    at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by stephan7878** [comment]
Managed to resolve the issues after installing:
- kb4013418
- kb4019472

**Comment by the1rainmaker** [comment]
Yep - KB890830, KB4019472, KB4013418 - definitely did the trick for me - thanks stephan7878!

**Comment by abrown** [comment]
I'm closing this since there seems to be a working update path.
