### ISSUE TITLE
Failed to start Docker Desktop 2.2.0.0 on Windows 10

### ISSUE THREAD

**Issue by JabbaTek** [docker/for-win#5704]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 4FA5571C-0B2C-4210-8669-E2BFBD111058/20200205181439

### Expected behavior
Docker Desktop starts successfully and runs in the background

### Actual behavior
Docker Desktop fails to start with the following message:

One or more errors occurred.

   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

### Information

  - Windows Version: 10 (Version 1709, OS Build 16299.1625)
  - Docker Desktop Version: 2.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Try to 
[log.txt](https://github.com/docker/for-win/files/4161364/log.txt)
start Docker Desktop

**Comment by marcselis** [comment]
I've experienced that Docker Desktop 2.2+ won't run on Windows version 1709. Docker Desktop version 2.1.0.5 is the last one that does.
