### ISSUE TITLE
Docker will not start with error. logs attached

### ISSUE THREAD

**Issue by rogue-bryan** [docker/for-win#5751]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID : CC1DC8F6-2D93-4269-9604-C0F175999C15/20200212172358

### Information

  - Windows Version: 10.0.16299 Build 16299
  - Docker Desktop Version: latest 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Windows 10 Pro desktop

### Steps to reproduce the behavior

  1. I updated to the newest version today, and now it will not start. Logs attached.

**Comment by naourass** [comment]
Check this solution : https://github.com/docker/for-win/issues/5811

**Comment by rogue-bryan** [comment]
@naourass thanks for looking into my issue. I finally had a chance to try the solution out (sorry it took me this long, I need to get work done so I reverted to the previous version). I happen to have updated to the newest build that just went out. My error is still similar/same as the previous issue:

```
Docker.Core.Backend.BackendDestroyException:
One or more errors occurred.
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass30_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.AggregateException:
  One or more errors occurred.
     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
     at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
     at Docker.Backend.LifecycleClient.DockerStart()
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Docker.Core.HttpBadResponseException:
     unable to fetch daemon.json: Get http://unix/engine/daemon.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
        at Docker.Backend.HttpClientExtensions.<ParseResponseBodyAsJsonAsync>d__2`1.MoveNext()
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Docker.Backend.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext()
     
```

**Comment by rogue-bryan** [comment]
This comment lead me to the solution! https://github.com/docker/for-win/issues/5562#issuecomment-596514232

Just needed to disable WSL (not using right now anyway).

I know there's an edge version that's coming soon that integrates with WSL, so this probably isn't a huge issue, but hopefully this comment helps others.
