### ISSUE TITLE
Unable to create Hyper-V VM: Hyper-V encountered an error trying to access an object on computer 'HOST-NAME' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.

### ISSUE THREAD

**Issue by jwang5237** [docker/for-win#5800]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
     I have tried latest version of Stable
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 70F85E28-C3F9-49E9-9B61-F1B81691956E/20200217125816

### Expected behavior
Docker should start successfully. With latest windows updates.

### Actual behavior
Docker failed to start with latest Windows 10 updates. 
```
Unable to create Hyper-V VM: Hyper-V encountered an error trying to access an object on computer 'MM247562-PC' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-MobyLinuxVM, <No file>: line 388
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```
### Information
- Reproducible, error occur every time docker desktop tries to start
- Windows Version:
```
Edition     Windows 10 Enterprise
Version     1809 
OS Build   17763.1039
```
- Docker Desktop Version:
```
Version 2.2.0.3(42716)
Channel stable
Engine: 19.03.5
Compose: 1.25.4
Kubernetes: v1.15.5
Notary: 0.6.1
Credential Helper: 0.6.3
```
- Symantec Endpoint Protection:
```
Version 14 (14.2) build 1031 (14.2.1031.0100)
```

### Steps to reproduce the behavior
  1. Windows 10 with latest updates
  2. Docker latest version 2.2.0.3

**Comment by jwang5237** [comment]
I ran the following in PowerShell as Administrator:
```
MOFCOMP %SYSTEMROOT%\System32\WindowsVirtualization.V2.mof
```
Docker Desktop started up correctly
