### ISSUE TITLE
Docker install fails with 'Access is denied: at System.Diagnostics.ProcessManager.OpenProcess'

### ISSUE THREAD

**Issue by bsolomon1124** [docker/for-win#5802]
Running `Docker Desktop Installer.exe` as Administrator fails with the following error:

![docker-fail-install](https://user-images.githubusercontent.com/25164676/74684713-91229e80-519a-11ea-8b22-0e57c850a332.JPG)

Text of traceback:

```
Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModuleInfos(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModuleInfo(Int32 processId)
   at System.Diagnostics.Process.get_MainModule()
   at CommunityInstaller.RegisterProductStep.Register(String basePath, Manifest manifest, String manifestJson)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()
```

- Windows 10 Enterprise Version 1809 OS build 17763.973 64-bit x64.
- Docker 2.2.0.3

**Comment by bsolomon1124** [comment]
I was able to get the installation to succeed by running Git Bash as Administrator and issuing `./Docker\ Desktop\ Installer.exe`

```bash
$ ./Docker\ Desktop\ Installer.exe
[15:37:42.891] [InstallHandler] No installation found
[15:37:42.898] [InstallHandler] Using embedded package
[15:37:43.090] [InstallWorkflow] Using package: res:CommunityInstaller.DockerDesktop.d4w
[15:37:43.092] [InstallWorkflow] Downloading
[15:37:44.499] [InstallWorkflow] Extracting manifest
[15:37:44.551] [InstallWorkflow] Checking prerequisites
[15:37:45.782] [InstallWorkflow] Prompting for optional features
[15:37:58.205] [InstallWorkflow] Unpacking artifacts
[15:38:24.911] [InstallWorkflow] Deploying component CommunityInstaller.CreateGroupAction
[15:38:36.720] [InstallWorkflow] Deploying component CommunityInstaller.AddToGroupAction
[15:38:36.732] [InstallWorkflow] Deploying component CommunityInstaller.EnableFeaturesAction
[15:38:37.424] [InstallWorkflow-EnableFeaturesAction] Enable Windows Feature *Hyper-V*
[15:38:37.425] [InstallWorkflow-EnableFeaturesAction] Enable Windows Feature Containers
[15:39:28.930] [InstallWorkflow] Deploying component CommunityInstaller.ServiceAction
[15:39:28.943] [InstallWorkflow-ServiceAction] Creating service
[15:39:30.302] [InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
[15:39:30.321] [InstallWorkflow-ShortcutAction] Creating shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Docker Desktop.lnk/Docker Desktop
[15:39:30.328] [InstallWorkflow] Deploying component CommunityInstaller.AutoStartAction
[15:39:30.330] [InstallWorkflow] Deploying component CommunityInstaller.PathAction
[15:39:30.572] [InstallWorkflow] Deploying component CommunityInstaller.PathAction
[15:39:30.835] [InstallWorkflow] Deploying component CommunityInstaller.ExecAction
[15:39:31.443] [InstallWorkflow] Registering product
[15:39:31.825] [InstallWorkflow] Installation succeeded
```

Hell if I know the difference, but the installation succeeded.

**Comment by bsolomon1124** [comment]
Additional info:

```
C:\Users\brsolomon>docker info
Client:
 Debug Mode: false

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.92GiB
 Name: docker-desktop
 ID: 7XYT:MHV4:5YIV:3SR2:7AVF:5C5S:SXSE:NIX3:UBB2:GASQ:FKK3:DBSD
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 34
  Goroutines: 51
  System Time: 2020-02-17T22:49:26.945426294Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by Quilding** [comment]
No idea why, but that worked for me too.

**Comment by mat007** [comment]
@Quilding is there any error in one of the `install-log*.txt` files in `%LOCALAPPDATA%\Docker` that could explain why it failed previously?

**Comment by Quilding** [comment]
@mat007 Same as @bsolomon1124, Access denied at ...CommunityInstaller.RegisterProductStep.Register… We are not allowed to Run as Administrator but some elevated permission stuff through Company Policies something. Still it worked using Git Bash with the same permissions.

**Comment by adi007me** [comment]
Excellent @bsolomon1124. It worked for me too.

**Comment by RevathiPilli02** [comment]
I am facing the same issue but will the Git Bash solution work for windows setup too ?

**Comment by rmcondori** [comment]
Hello I installed docker using this solution but that causes problems with virtualbox and I am experiencing blue screens :(

How can I uninstall it ? I did it by using control panel but still having problems. I have the feeling that what ever was preventing the installation at the beginning it has not been reverted back.

Does anybody have any idea?
