### ISSUE TITLE
Docker Desktop Cannot Switch to Linux Containers

### ISSUE THREAD

**Issue by rwgridstone** [docker/for-win#5827]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: EE282695-9595-4D80-8FB9-3752588310E5/20200220072502

I understand this seems to be a common issue but the information I could find was very vague or extremely specific to an individual user's circumstances.

This installation is on a clean install of Windows Pro 10. Hyper-V is installed and enabled in BIOS.

### Expected behavior

- Docker should switch to using Linux Containers

### Actual behavior

Receive error message:

```
Docker.Core.DockerException:
Docker.Core.Backend.BackendDestroyException:
Unable to create Hyper-V VM: Failed to create a new virtual machine.

'DockerDesktopVM' failed to realize. (Virtual machine ID C0B93F9B-5049-43E4-AAC9-E5777F36FF85)

Failed to access configuration store: The system cannot find the path specified. (0x80070003).
at New-MobyLinuxVM, <No file>: line 397
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  System.Management.Automation.RuntimeException:
  Unable to create Hyper-V VM: Failed to create a new virtual machine.

'DockerDesktopVM' failed to realize. (Virtual machine ID C0B93F9B-5049-43E4-AAC9-E5777F36FF85)

Failed to access configuration store: The system cannot find the path specified. (0x80070003).
  at New-MobyLinuxVM, <No file>: line 397
  at New-MobyLinux, <No file>: line 182
  at <ScriptBlock>, <No file>: line 810
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.HyperV.Create(Settings settings)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     Failed to create a new virtual machine.

'DockerDesktopVM' failed to realize. (Virtual machine ID C0B93F9B-5049-43E4-AAC9-E5777F36FF85)

Failed to access configuration store: The system cannot find the path specified. (0x80070003).
     
         Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException:
         Failed to create a new virtual machine.

'DockerDesktopVM' failed to realize.
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation, Boolean throwIfAffectedElementNotFound)
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation)
            at Microsoft.Virtualization.Client.Management.VMServiceView.EndCreateVirtualSystem[T](IVMTask task)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
            at Microsoft.HyperV.PowerShell.VirtualMachine.Create(Server server, String name, String location, Int32 generation, Version version, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateVirtualMachine(Server server, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateObjects(IOperationWatcher operationWatcher)
         
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.<>c__DisplayClass39_0.<SwitchDaemon>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
```

### Information

  - Windows Version: Windows Pro 10 1903 with all updates applied
  - Docker Desktop Version: 2.2.0.3 (42716) stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

- Enable Hyper-V as per guidelines
- Install latest Docker Desktop
- Verify installation by running a Windows container
- Select "Switch to Linux Containers..." in the Docker Desktop tray icon

**Comment by ratuka** [comment]
Another diagnostic id: 90BEB425-B939-414A-9DBA-232E4F811B25/20200224094439

**Comment by jginternational** [comment]
Same here:

Diagnostic id: 9338AB6A-F671-42CC-BF22-07875F009138/20200224144014

- Windows 10 Enterprise 1909
- Docker desktop 2.2.0.3 (42716)

**Comment by aaglawe** [comment]
Same here

Diagnostic Id: 4FD7ED37-B662-4C73-91C0-1AE75A655F88/20200224165003

* Windows 10 Enterprise build 18362
* Docker desktop 2.2.0.3 (42716)

**Comment by rwgridstone** [comment]
(sad face)

**Comment by ratuka** [comment]
> 
> 
> Same error here.
> 
> Diagnostic id: 90BEB425-B939-414A-9DBA-232E4F811B25/20200224094439
> 
>     * Windows 10 Enterprise v1809, build 17763.973,
> 
>     * Docker Desktop 2.2.0.3 (42716)

After some boot, magically start working with the exact same version.
