### ISSUE TITLE
docker desktop hangs for a long time during startup but then works correctly

### ISSUE THREAD

**Issue by mwoodpatrick** [docker/for-win#5848]
I'm seeing an issue where docker desktop is hanging for a long period of time but eventually does start working correctly. 

Diagnostics were uploaded with id: 5B81673D-4614-408D-AAD6-6CBB9BBBE6B5/20200223032128

Looking at the docker log at the time of the issue showed a long hang from 17:25:48.496 to 18:13:12.736. 

Questions:

1. Is there a way to enable more detail in the logs so we can see what is happening at time of startup?

2. Is there an automatic way of preserving older log files sees like the log was overwritten rather than being extended

3, Anything I should be checking to help resolve this issue. Apart from the uploaded diagnostics what other information should I be providing?

The docker log at the time of the issue showed:

		Started on: 2020/02/22 17:25:44.825
		Resources: C:\Program Files\Docker\Docker\resources
		OS: Windows 10 Pro
		Edition: Professional
		Id: 2004
		Build: 19569
		BuildLabName: 19569.1000.amd64fre.rs_prerelease.200214-1419
		File: C:\Users\mlwp\AppData\Local\Docker\log.txt
		CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
		You can send feedback, including this log file, at https://github.com/docker/for-win/issues
		[17:25:45.622][GUI               ][Info   ] Starting...
		[17:25:45.746][ComponentVersions ][Info   ] Edition community
		[17:25:46.117][ComponentVersions ][Info   ] Edition community
		[**17:25:48.496**][AppMigrator       ][Info   ] Current version: 5. Latest version: 5
		[**18:13:12.736**][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
                [18:13:12.738][SegmentApi        ][Info   ] Usage statistic: Identify

**Comment by mwoodpatrick** [comment]
System crashed today, again on reboot docker is hanging on startup log shows

Version: 2.2.1.0 (42746)
Channel: edge
Sha1: b31b7ff13590598979c57262028abaa146de56ef
Started on: 2020/02/26 18:29:52.080
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2004
Build: 19569
BuildLabName: 19569.1000.amd64fre.rs_prerelease.200214-1419
File: C:\Users\mlwp\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[18:29:52.393][GUI               ][Info   ] Starting...
[18:29:52.451][ComponentVersions ][Info   ] Edition community
[18:29:52.635][ComponentVersions ][Info   ] Edition community
[18:29:54.270][AppMigrator       ][Info   ] Current version: 5. Latest version: 5

**Comment by mwoodpatrick** [comment]
Finally started looks like a 40 minute delay again!

[18:29:54.270][AppMigrator       ][Info   ] Current version: 5. Latest version: 5
[19:12:05.885][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[19:12:05.885][SegmentApi        ][Info   ] Usage statistic: Identify
[19:12:05.948][SegmentApi        ][Info   ] Usage statistic: appLaunched

**Comment by mwoodpatrick** [comment]
Failed on startup today reports timeout waiting for the life cycle server to start

**Comment by mwoodpatrick** [comment]
crash report 5B81673D-4614-408D-AAD6-6CBB9BBBE6B5/20200312123800

Docker.Core.Backend.BackendException:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.TimeoutException:
  Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
     at Docker.Backend.LifecycleClient.WaitForServerUp(TimeSpan pingTimeout)
     at Docker.Backend.ContainerEngine.WslEngine.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential, Boolean retry)
     at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential, Boolean retry)
     at Docker.Backend.ContainerEngine.WslEngine.Start(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
     at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
     at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by mwoodpatrick** [comment]
Not sure why I'm not getting any support? I reinstalled the app today and it hung for about 48 minutes and then started! How do we figure out what the app is hanging on, how do I fix this issue

 Version: 2.2.0.4 (43472)
Channel: stable
Sha1: d67a59ce3380b41601dad861688117986ca79a52
Started on: 2020/03/15 17:30:11.668
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2004
Build: 19577
BuildLabName: 19577.1000.amd64fre.rs_prerelease.200228-1439
File: C:\Users\mlwp\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[17:30:11.969][GUI               ][Info   ] Starting...
[17:30:12.016][ComponentVersions ][Info   ] Edition community
[17:30:12.232][ComponentVersions ][Info   ] Edition community
[18:18:06.112][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[18:18:06.133][SegmentApi        ][Info   ] Usage statistic: Identify
[18:18:06.191][SegmentApi        ][Info   ] Usage statistic: appLaunched
[18:18:07.337][ApplicationTemplatesTracking][Info   ] Cannot list templates
[log.txt](https://github.com/docker/for-win/files/4335637/log.txt)
