### ISSUE TITLE
Docker for Windows crashes at startup

### ISSUE THREAD

**Issue by yodar101** [docker/for-win#5857]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5C1F8F6A-CE82-4FAC-9732-64032D08AEA0/20200224124527

### Information

  - Windows Version: Windows 10 Education Windows Insider Preview evaluation copy 19555. rs_prerelease.200127-0900
  - Docker Desktop Version: 2.2.0.3 (42716)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by titusjoyson** [comment]
I'm also facing the same issue, I installed docker for windows in my windows 10 pro system. And Hyper-V is installed and Virtualisation is also Enabled.

Crash report id `3A0E9CA3-2692-444F-9F49-51654CE8B433/20200225030120`

docker  version:
```
Docker version 19.03.5, build 633a0ea
```
Crash:
```
Docker.Core.Backend.BackendException:
Time out has expired and the operation has not been completed.
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.ServiceProcess.TimeoutException:
  Time out has expired and the operation has not been completed.
     at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
     at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env)
     at Docker.Backend.Processes.WindowsDockerDaemon.Start(Settings settings, String daemonOptions, Boolean useProtectedNamedPipe)
     at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions)
     at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
     at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
     at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
  
```
