### ISSUE TITLE
No answer from VM, aborting

### ISSUE THREAD

**Issue by JoshHubanks** [docker/for-win#5859]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 458B111D-E8FA-4BDD-8459-60AA76959F16/20200224150409

### Information

  - Windows Version: Microsoft Windows [Version 10.0.18363.592]
  - Docker Desktop Version: 2.2.0.3 (42716)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by tigerinus** [comment]
Just encountered the same issue. Can't really do a factory reset since I have a whole bunch of setup. Waiting for a fix.

**Comment by tigerinus** [comment]
Diagnostic ID: 852EA2B1-1CC8-4FEC-BB87-19898D072918/20200301044609

**Comment by ettingshausen** [comment]
Same problem here.

**Comment by ettingshausen** [comment]
> Same problem here.
> Diagnostic ID: `DE386C62-7C44-4C0E-AE46-7A337754E2E1/20200414092704`

I upgraded docker to edge version error message changed 
```shell
System.TimeoutException:
Timed out while wait for Docker service to be ready
   at Docker.LinuxkitDaemonStartup.<StartAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext()
```
Diagnostic ID: `DE386C62-7C44-4C0E-AE46-7A337754E2E1/20200414181354`

**Comment by ettingshausen** [comment]
I made a full backup of `DockerDesktop.vhdx`. Is there a way to restore ? 
I tried to `Reset to factory default` and replace the vhdx file, but still not work.

**Comment by Lagicrus** [comment]
Same issue here: F5A5897E-075F-4C71-A02F-12C0F69C426C/20200502074149
V 2.2.0.5 on Stable
Windows 10.0.19613

**Comment by Lagicrus** [comment]
> Same issue here: F5A5897E-075F-4C71-A02F-12C0F69C426C/20200502074149
> V 2.2.0.5 on Stable
> Windows 10.0.19613

I "fixed" by swapping to edge, WSL2 enabled and disabling the insecure TLS in port 2375. I believe it was just the setting that fixed it but 🤷‍♂️ might as well give all my steps

**Comment by dermoritz** [comment]
I have the same issue right after patching windows.
How to disable TLS port if i am not able to start docker? Setting are disabled until docker is started?
