### ISSUE TITLE
Unable to switch to build/run Windows containers using Docker Desktop on Windows 10 1803 

### ISSUE THREAD

**Issue by seandockery** [docker/for-win#5891]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 04D0B61B-EF9D-4714-B1CE-3FFB3590FB72/20200226211505

### Information

  - Windows Version: Windows Desktop 10 1803
  - Docker Desktop Version: 2.2.0.3 (42716)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No. Physical desktop.

### Steps to reproduce the behavior

  1. Right-click on Docker Desktop
  2. Click Switch to Windows Containers...
  3. Click Switch on the dialog that appears.

When I first installed Docker Desktop, switching to Windows Containers worked fine.  Somewhere along the lines between Windows updates and Docker Desktop updates, I can no longer switch.

Running Docker Desktop in Linux containers mode works fine.

**Comment by seandockery** [comment]
I tried fully uninstalling Docker Desktop, and disabling the Hyper-V and Containers features.  Restarted.  Installed Docker Desktop.  Restarted.  Clicked Switch to Windows Containers...  Encountered a different crash.

Diagnostic ID: 04D0B61B-EF9D-4714-B1CE-3FFB3590FB72/20200528002348

```
Docker.Core.HttpBadResponseException:
Unhandled exception: Cannot start service docker on computer '.'.
   at Docker.Core.Logging.ClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\ClientExceptionInterceptor.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<StartWindowsContainersAsync>d__6.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WindowsContainersEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WindowsContainersEngine.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
Original stacktrace:
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 211
   at Docker.Backend.HttpAPI.WindowsContainersController.Start(WindowsContainerStartRequest request) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\WindowsContainersController.cs:line 42
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

**Comment by seandockery** [comment]
Docker Desktop Version: 2.3.0.3 (45519)

**Comment by mat007** [comment]
Thanks for the report, do you have any error in the Windows Event Viewer?
What’s the status of the Docker Desktop service in the service list?

**Comment by seandockery** [comment]
Hi @mat007 , Thanks for responding.

Nothing in the Windows Event Viewer jumps out at me.  I only see events indicating that the service failed to start at 30 seconds.

Since my previous post, I've updated to Windows 10 2004, but the behaviour remains the same.  I received the same HttpBadResponseException exception that I reported in my earlier comment.

Docker Desktop indicates that it is running when I hover the mouse over the notification area icon.  When I look in the Services control panel application, Docker Desktop Service is in the status of Running.

When I open the Dashboard, the bottom of the Dashboard window has a grey bubble next to the Docker text, and it is followed by "failed to start" in italic.

I've tried running "docker version" in both a standard and elevated PowerShell console:

```
PS C:\WINDOWS\system32> docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
PS C:\WINDOWS\system32>
```

Is there more information that I can get from any of the processes in order to diagnose the problem?

This is so strange because Linux Containers mode works just fine -- both with Hyper-V and WSL2.  Only Windows Containers mode is giving trouble.

**Comment by mat007** [comment]
Anything in `C:\ProgramData\Docker\panic.log`? Do you have a `dockerd.exe` process running?
Assuming you don’t have container or images you want to keep, you can try to quit Docker Desktop then delete `C:\ProgramData\Docker` and restart Docker Desktop.

**Comment by seandockery** [comment]
I am using a different machine now and this issue no longer affects me.
