### ISSUE TITLE
'An error occured' while starting docker. Uninstalled and re-installed git. still same error.

### ISSUE THREAD

**Issue by sigiridh** [docker/for-win#5910]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
When docker desktop icon is clicked, Docker starts and changes to status: 'running'
### Actual behavior
Docker does not start.
### Information
It was working fine after the first download for 5-6 times. And then stopped working.
I uninstalled re-installed the docker, still it does not work (it does not start).

### Steps to reproduce the behavior
  1. Start the Docker desktop
  2. 'Starting' process runs for few mins and below error appears:
Docker.Core.Backend.BackendDestroyException:
No answer from VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  Docker.Core.DockerException:
  No answer from VM, aborting
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)

**Comment by tigerinus** [comment]
Facing the same problem here. Looks like the same issue as https://github.com/docker/for-win/issues/5859

**Comment by byronsanchez** [comment]
Just had the same issue. Docker for Windows was failing to start and I was getting the "No answer from VM, aborting" error message. I can confirm that I was able to resolve the issue by running the steps in #3546.
