### ISSUE TITLE
Docker cannot be allocated 1TB 

### ISSUE THREAD

**Issue by tomone-hata** [docker/for-win#5915]
Docker for Windows 2.0.0.3 cannot be allocated more than 1TB in my enviroment.
When I try to allocate Docker image size in setting, Docker output below errors.

[12:13:34.984][NamedPipeServer][Info   ] TryGetVhdxSize done in 00:00:00.1835007.
[12:13:35.704][NamedPipeClient][Info   ] Sending Version()...
[12:13:36.242][GUI            ][Error  ] Index was outside the bounds of the array.

My PC has the capacity 4TB of SSD.
Would you tell me the solution?

**Comment by tomone-hata** [comment]
Does someone know the solution? I would like to know just ideas.

**Comment by mat007** [comment]
You can try to edit `%APPDATA%\Docker\settings.json` directly, or even change the disk size in the Hyper-V Manager in Windows.
Be sure to shutdown and restart Docker Desktop afterwands.

**Comment by tomone-hata** [comment]
Thanks. 
I try to edit settings.json. But, setting was not reflected. And it is difficult to modify the Hyper-V manager soon because I don't have the authority. 
I tried to change disk size in the Hyper-V before(about 1month ago). Setting display could not be execute the output the error.
I wonder if it is caused by other settings and bug.

**Comment by tomone-hata** [comment]
Does someone know any solution?

**Comment by mat007** [comment]
Due to the bug in Docker Desktop any solution at the moment requires admin rights, e.g. in an admin powershell:
```powershell
Resize-VHD -Path 'C:\ProgramData\DockerDesktop\vm-data\DockerDesktop.vhdx' -SizeBytes 1tb
```

**Comment by tomone-hata** [comment]
Thanks.
I could execute your command. But, `the below error output when open setting display after the command.`
Did it succeed the disk size extention inspite of output the error?
By the way, I tried to this solution.
https://github.com/docker/for-win/issues/2778 
But the same error continue output when I modify the disk size more than 1TB.

```
Index was outside the bounds of the array.
   at Docker.WPF.AdvancedSettings.ReadableByteCount(Double bytes) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\Settings\AdvancedSettings.xaml.cs:line 146
   at Docker.WPF.AdvancedSettings.RefreshDiskMaxSizeLabel() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\Settings\AdvancedSettings.xaml.cs:line 255
   at Docker.WPF.AdvancedSettings.<InitDiskFields>d__15.MoveNext() in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.WPF\Settings\AdvancedSettings.xaml.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\stable-18.09.x\src\github.com\docker\pinata\win\src\Docker.Windows\Program.cs:line 216
```

**Comment by mat007** [comment]
You really need to update Docker Desktop, the code from this stacktrace has been deleted a long time ago…

**Comment by tomone-hata** [comment]
Thanks a lot.
I will upgrade the new version Docker Desktop.
