### ISSUE TITLE
Unable to start Hyper-V VM: 'DockerDesktopVM' failed to change state.

### ISSUE THREAD

**Issue by Seram22** [docker/for-win#5945]
- [ yes] I have tried with the latest version of my channel (Stable or Edge)
  - [ yes] I have uploaded Diagnostics
  - Diagnostics ID: 716F00EA-66DD-4821-BA74-DA3AAFABD768/20200304184742

### Actual behavior
Docker.Core.DockerException:
Docker.Core.Backend.BackendDestroyException:
Unable to start Hyper-V VM: 'DockerDesktopVM' failed to change state.

The operation failed with error code '32788'.
at Start-MobyLinuxVM, <No file>: line 688
at <ScriptBlock>, <No file>: line 811
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  System.Management.Automation.RuntimeException:
  Unable to start Hyper-V VM: 'DockerDesktopVM' failed to change state.
  
  The operation failed with error code '32788'.
  at Start-MobyLinuxVM, <No file>: line 688
  at <ScriptBlock>, <No file>: line 811
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     'DockerDesktopVM' failed to change state.
     
     The operation failed with error code '32788'.
     
         Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException:
         'DockerDesktopVM' failed to change state.
         
         The operation failed with error code '32788'.
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
            at Microsoft.Virtualization.Client.Management.VMComputerSystemBaseView.EndSetState(IVMTask setStateTask)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.<>c__DisplayClass4_0`1.<ConvertActionToFunction>b__0(T x)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
            at Microsoft.HyperV.PowerShell.VirtualMachine.ChangeState(VirtualMachineAction action, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.StartVM.ProcessOneOperand(VirtualMachine vm, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.VirtualizationCmdlet`1.ProcessOperands(IList`1 operands, IOperationWatcher operationWatcher)
         
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by Seram22** [comment]
Version: 2.2.0.3 (42716)
Channel: stable
Sha1: e11f25edf9f955239c922a0251699b23aaf37984
Started on: 2020/03/05 00:17:11.613
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 1809
Build: 17763
BuildLabName: 17763.1.amd64fre.rs5_release.180914-1434

**Comment by Seram22** [comment]
[log.txt](https://github.com/docker/for-win/files/4289251/log.txt)

**Comment by joaoserpaD** [comment]
same issue here. found any solution?

**Comment by Pedersen175** [comment]
Seems to be duplicate of mine: #5966 
Do any of you have installed either of the updates mentioned in my bug report?

**Comment by guperez** [comment]
I have the same issue after change the memory limit from 2.00 GO to 8.00 GO. If I "Reset to factory defaults" I don't have the crash but the memory limit is reset to 2.00 GO.

Crash Report ID = 0F4E496F-EF25-4BFA-976B-F46766BF798C/20200311144153

Logs:
```
Docker.Core.DockerException:
Docker.Core.Backend.BackendException:
Unable to start Hyper-V VM: « DockerDesktopVM » n’a pas pu changer d’état.

Échec de l’opération avec le code d’erreur « 32788 ».
à Start-MobyLinuxVM, <Aucun fichier> : ligne 688
à <ScriptBlock>, <Aucun fichier> : ligne 811

  System.Management.Automation.RuntimeException:
  Unable to start Hyper-V VM: « DockerDesktopVM » n’a pas pu changer d’état.
  
  Échec de l’opération avec le code d’erreur « 32788 ».
  à Start-MobyLinuxVM, <Aucun fichier> : ligne 688
  à <ScriptBlock>, <Aucun fichier> : ligne 811
     à Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     à Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions, Credential credential)
     à Docker.Backend.BackendNamedPipeServer.<Run>b__8_3(Object[] args)
     à Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
     à Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     « DockerDesktopVM » n’a pas pu changer d’état.
     
     Échec de l’opération avec le code d’erreur « 32788 ».
     
         Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException:
         « DockerDesktopVM » n’a pas pu changer d’état.
         
         Échec de l’opération avec le code d’erreur « 32788 ».
            à Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
            à Microsoft.Virtualization.Client.Management.VMComputerSystemBaseView.EndSetState(IVMTask setStateTask)
            à Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.<>c__DisplayClass4_0`1.<ConvertActionToFunction>b__0(T x)
            à Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
            à Microsoft.HyperV.PowerShell.VirtualMachine.ChangeState(VirtualMachineAction action, IOperationWatcher operationWatcher)
            à Microsoft.HyperV.PowerShell.Commands.StartVM.ProcessOneOperand(VirtualMachine vm, IOperationWatcher operationWatcher)
            à Microsoft.HyperV.PowerShell.Commands.VirtualizationCmdlet`1.ProcessOperands(IList`1 operands, IOperationWatcher operationWatcher)
         
   à Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   à Docker.Actions.DoRestartVM(Settings previousSettings)
   à Docker.Actions.<>c__DisplayClass34_0.<RestartVM>b__0()
   à Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
```

Docker Version: 2.2.0.3 (42716)
OS: Windows 10 Entreprise
OS Version: 10.0.17134

**Comment by mfyuce** [comment]
Please check following url for the possible resolution;
In a nutshell it is about an inconsistency in VM settings. Mine was a bout the RAM size. When I decreesed the RAM size it started OK. Or closing some apps to be able to give more room for Docker desktop.


-https://www.sysprobs.com/fixed-failed-to-change-state-error-code-32788-on-hyper-v-while-attempting-to-start
