### ISSUE TITLE
error installing windows 10

### ISSUE THREAD

**Issue by soydepr** [docker/for-win#5949]
when starting docker on windows 10 getting this error 

Docker.Core.DockerException:
Docker.Core.Backend.BackendDestroyException:
Unable to create Hyper-V VM: Creating the virtual machine failed.
at New-MobyLinuxVM, <No file>: line 397
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  System.Management.Automation.RuntimeException:
  Unable to create Hyper-V VM: Creating the virtual machine failed.
  at New-MobyLinuxVM, <No file>: line 397
  at New-MobyLinux, <No file>: line 182
  at <ScriptBlock>, <No file>: line 810
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.HyperV.Create(Settings settings)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     Creating the virtual machine failed.
     
         Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException:
         Creating the virtual machine failed.
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation, Boolean throwIfAffectedElementNotFound)
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation)
            at Microsoft.Virtualization.Client.Management.VMServiceView.EndCreateVirtualSystem[T](IVMTask task)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
            at Microsoft.HyperV.PowerShell.VirtualMachine.Create(Server server, String name, String location, Int32 generation, Version version, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateVirtualMachine(Server server, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateObjects(IOperationWatcher operationWatcher)
         
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__

**Comment by guillemdj** [comment]
Same error message here. Did a first Reset to Factory two days ago and issue came up just with first usages. 

The only thing that made me suspicious is that last night while shutting down Windows it complained that was waiting for Docker process to finish.

The next morning my fears confirmed.

**Comment by guillemdj** [comment]
Another crash on Monday, reverted to previous version with Choco as I don't see how to download and old package.

`choco install docker-desktop --version=2.1.0.5`

Hopefully this works as it used to
