### ISSUE TITLE
An error ocurred: Unable to create Hyper-V VM

### ISSUE THREAD

**Issue by yogeshnagarro** [docker/for-win#5957]
Diagnostic ID: BF9B6E42-8412-4E43-988B-E8DFE5DCBF73/20200307194250

Docker.Core.DockerException:
Docker.Core.Backend.BackendDestroyException:
Unable to create Hyper-V VM: Hyper-V encountered an error trying to access an object on computer 'COMPUTER01' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
at New-MobyLinuxVM, <No file>: line 397
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  System.Management.Automation.RuntimeException:
  Unable to create Hyper-V VM: Hyper-V encountered an error trying to access an object on computer 'COMPUTER01' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
  at New-MobyLinuxVM, <No file>: line 397
  at New-MobyLinux, <No file>: line 182
  at <ScriptBlock>, <No file>: line 810
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.HyperV.Create(Settings settings)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     Hyper-V encountered an error trying to access an object on computer 'COMPUTER01' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
     
         Microsoft.Virtualization.Client.Management.ObjectNotFoundException:
         Hyper-V encountered an error trying to access an object on computer 'COMPUTER01' because the object was not found. The object might have been deleted, or you might not have permission to perform the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
            at Microsoft.Virtualization.Client.Management.HostComputerSystemView.GetPrimordialResourcePool(VMDeviceSettingType deviceType)
            at Microsoft.Virtualization.Client.Management.HostComputerSystemView.GetSettingCapabilities(VMDeviceSettingType deviceType, SettingsDefineCapabilities capability)
            at Microsoft.HyperV.PowerShell.VMScsiController.CreateTemplateScsiController(VirtualMachine parentVirtualMachine)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.ConfigureVirtualMachine(VirtualMachine vm, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateObjects(IOperationWatcher operationWatcher)
         
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

**Comment by kristof12345** [comment]
Same for me.

**Comment by AliAkhtari78** [comment]
same 4 me too.

**Comment by mberastau** [comment]
have the same issue

**Comment by hellokatili** [comment]
Uploaded crash report with diagnostic ID: `38CC4EAC-5F03-4A00-A0BD-A3A9AB8B9894/20200508130050`

**Comment by yogeshnagarro** [comment]
This issue can only be fixed by reinstalling windows as there is a problem with windows virtual network drivers.
