### ISSUE TITLE
Docker windows stopped working after windows update

### ISSUE THREAD

**Issue by Pedersen175** [docker/for-win#5966]
Failed to start docker after restart with error below. Seems to be related to one of these 2 updates
- Update for Skype Business 2016 (KB4484245) 32-Bit Edition 
- Update for Microsoft Office 2016 (KB4484247) 32-Bit Edition

**Diagnostic report:** 6D0A2C0A-284D-4BEB-B2DD-BC8C258058FD/20200309114544

**Error:**
```
Docker.Core.DockerException:
Docker.Core.Backend.BackendDestroyException:
Unable to start Hyper-V VM: 'DockerDesktopVM' failed to start. (Virtual machine ID D856A1B6-67F0-43AB-9789-B02AFCCE45BA)
at Start-MobyLinuxVM, <No file>: line 688
at <ScriptBlock>, <No file>: line 811
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  System.Management.Automation.RuntimeException:
  Unable to start Hyper-V VM: 'DockerDesktopVM' failed to start. (Virtual machine ID D856A1B6-67F0-43AB-9789-B02AFCCE45BA)
  at Start-MobyLinuxVM, <No file>: line 688
  at <ScriptBlock>, <No file>: line 811
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     'DockerDesktopVM' failed to start. (Virtual machine ID D856A1B6-67F0-43AB-9789-B02AFCCE45BA)
     
         Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException:
         'DockerDesktopVM' failed to start.
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
            at Microsoft.Virtualization.Client.Management.VMComputerSystemBaseView.EndSetState(IVMTask setStateTask)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.<>c__DisplayClass4_0`1.<ConvertActionToFunction>b__0(T x)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
            at Microsoft.HyperV.PowerShell.VirtualMachine.ChangeState(VirtualMachineAction action, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.StartVM.ProcessOneOperand(VirtualMachine vm, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.VirtualizationCmdlet`1.ProcessOperands(IList`1 operands, IOperationWatcher operationWatcher)
         
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
```

Feel free to ask for information if needed.

**Comment by Pedersen175** [comment]
Reinstall docker version 2.0.3 did not work. Same error

**Comment by DanielHJacobsen** [comment]
Experiencing the same issue. 

Win version: 1809
Win build: 17763.1039

Not the same error log (possible due to windows pro vs window enterprise), but I believe that it might be connected to the same issue as this recently open case. 

https://github.com/docker/for-win/issues/5975

The behaviour of both scenarioes are very similar.

**Comment by Pedersen175** [comment]
Exact copy of error at: #5993

Seems a lot of recent reports are related to this.

**Comment by guillemdj** [comment]
Similar here as in #5949. I have other colleagues at work with same issue. All with Windows in enterprise environment which means some updates are delayed.

After several crashes in my machine only thing that seems to be working is installing an older version

`choco install docker-desktop --version=2.1.0.5`

**Comment by Pedersen175** [comment]
Thanks for suggesting temporary solution. Might try it out if not resolved sometime soon :)

**Comment by erlfos** [comment]
I also had this error and I can confirm that downgrade (had to uninstall Docker dektop and download and install version 2.1.0.5 manually) resolves the issue.

**Comment by mattandreas** [comment]
For what it's worth, this is the same exact error message I get when I try to start docker inside a Hyper-V VM without exposing the CPU's VirtualizaitionExtension to the guest OS.

Once I run "Set-VMProcessor -VMName <Target VM's Name> -ExposeVirtualizationExtensions $true", everything works fine.

Docker 2.2.0.4, Windows 1909 build 18363.720 (fully upgraded, on a hyper-v vm)

**Comment by ii64** [comment]
> For what it's worth, this is the same exact error message I get when I try to start docker inside a Hyper-V VM without exposing the CPU's VirtualizaitionExtension to the guest OS.
> 
> Once I run "Set-VMProcessor -VMName <Target VM's Name> -ExposeVirtualizationExtensions $true", everything works fine.
> 
> Docker 2.2.0.4, Windows 1909 build 18363.720 (fully upgraded, on a hyper-v vm)

Could you explain more i got error with my Docker 2.2.0.4 the same issue like this one, what <Target VM's name> for Docker?

**Comment by Pedersen175** [comment]
Windows update and Docker update to v 2.2.0.4 (2.2.0.43472) have not fixed the problem

**Comment by Pedersen175** [comment]
> Set-VMProcessor -VMName <Target VM's Name> -ExposeVirtualizationExtensions $true



> For what it's worth, this is the same exact error message I get when I try to start docker inside a Hyper-V VM without exposing the CPU's VirtualizaitionExtension to the guest OS.
> 
> Once I run "Set-VMProcessor -VMName <Target VM's Name> -ExposeVirtualizationExtensions $true", everything works fine.
> 
> Docker 2.2.0.4, Windows 1909 build 18363.720 (fully upgraded, on a hyper-v vm)

Hmm, I can see why you need this as you are running a hosted VM (A VM in a VM) situation which does require the CPU to be available (VM in a VM is always tricky due to hardware virtualization). Dont think it will solve my problem however, as I am running directly from installed OS. 

Thanks for the suggestion though! 

Now docker team, seems a lot of people have this problem. Can we get any support or are you closed down due to Corona?

**Comment by mat007** [comment]
Hi, thanks for the report.
Have you tried with the latest Edge 2.2.2.0? We have removed the whole Powershell script since the latest Stable and the code is now different (although the underlying Hyper-V component is still the same).
https://download.docker.com/win/edge/Docker%20Desktop%20Installer.exe
If it’s still failing, can you upload fresh diagnostics, please?

**Comment by tinoviena** [comment]
fwiw: I had exactly the same problem on Win 10 (1809) and Docker Desktop 2.2.0.4.
I've uninstalled it a few days ago, and today installed Docker 2.2.0.5 - and everything works like a charm.
Note: While it was broken, I tried to start the Docker Desktop VM manuallly from the Hyper-V console and got the same "failed to change state" error.

**Comment by ncarrut** [comment]
I had the same error.  Instructions in the link below solved it for me:
https://www.reddit.com/r/HyperV/comments/9thubc/create_virtual_machine_returns_not_found_error/

**Comment by tinoviena** [comment]
I had the same error again with a completely different VM, unrelated to Docker. I've got the feeling it's what Hyper-V says when there's enough memory to start the VM.
