### ISSUE TITLE
Install failing: System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode) ..

### ISSUE THREAD

**Issue by answerquest** [docker/for-win#5967]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: (didn't even install so never got to this stage)

### Expected behavior
Docker for Windows should install

### Actual behavior
Installation fails. Failure message:
```
Not found 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObject.Initialize(Boolean getObject)
   at System.Management.ManagementBaseObject.get_ClassName()
   at System.Management.ManagementClass.GetInstances(EnumerationOptions options)
   at CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   at CommunityInstaller.EnableFeaturesAction.<DoAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()
```

### Information
  - Fresh installation on a windows laptop which belongs to a company and has some restrictions (but where admin rights are granted)
  - Windows Version: Windows 10 Enterprise v1809
  - Docker Desktop Version: 2.2.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
- Get a standard corporate laptop which has Microsoft Outlook, Office 365, Skype for Business installed, where you have admin privileges
- Try to install latest docker for windows

**Comment by nakhanha** [comment]
Were you able to fix this ?

**Comment by andrewjsaid** [comment]
@nakhanha  I ran into a similar problem today. I managed to install it after unticking the checkbox which says something like `Enable windows hyper-v features`

**Comment by answerquest** [comment]
Hi, I tried this approach - checked off hyper-v and installed... and on running it said it's trying to do hype-v then gave me an error message saying the computer doesn't have hyper-v enabled and so docker cannot run.  
I do not understand why docker gave me that checkbox to untick if it was going to try running hyper-v anyway.
