### ISSUE TITLE
Docker Desktop cannot run Linux containers

### ISSUE THREAD

**Issue by rplante** [docker/for-win#5972]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 940301BB-6A96-4970-A791-E90691093060/20200309175706

### Expected behavior
Docker Desktop launches and reports status "Docker Desktop is running" when running in Linux container mode

### Actual behavior
Docker Desktop crashes upon launch when running in Linux container mode 

### Information

  - Windows Version: Windows 10 Enterprise, Version 1809, OS Build 17763.1039
  - Docker Desktop Version: 2.2.0.3 (42716) stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install Docker Desktop for Windows 
  2. Launch Docker Desktop after installation
  3. Docker Desktop crashes with the following stack trace:

```
Docker.Core.DockerException:
Docker.Core.Backend.BackendDestroyException:
Unable to create Hyper-V VM: Hyper-V encountered an error trying to access an object on computer 'DT13132' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-MobyLinuxVM, <No file>: line 388
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  System.Management.Automation.RuntimeException:
  Unable to create Hyper-V VM: Hyper-V encountered an error trying to access an object on computer 'DT13132' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
  at New-MobyLinuxVM, <No file>: line 388
  at New-MobyLinux, <No file>: line 182
  at <ScriptBlock>, <No file>: line 810
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.HyperV.Create(Settings settings)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     Hyper-V encountered an error trying to access an object on computer 'DT13132' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
     
         Microsoft.Virtualization.Client.Management.ServerObjectDeletedException:
         Hyper-V encountered an error trying to access an object on computer 'DT13132' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
            at Microsoft.Virtualization.Client.Management.Server.LoadOSInfo()
            at Microsoft.HyperV.PowerShell.VirtualizationObjectLocator.PrepareServerConnections(Server server, Boolean allowDownlevelServers)
            at Microsoft.HyperV.PowerShell.VirtualizationObjectLocator.GetServer(String computerName)
            at Microsoft.HyperV.PowerShell.ExceptionHelper.TryWithLogging[TInput,TOutput](Func`2 function, TInput input, IOperationWatcher operationWatcher)
         
              Microsoft.Management.Infrastructure.CimException:
              Not found 
                 at Microsoft.Management.Infrastructure.Internal.Operations.CimSyncEnumeratorBase`1.MoveNext()
                 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
                 at Microsoft.Virtualization.Client.Management.Server.LoadOSInfo()
              
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.<>c__DisplayClass39_0.<SwitchDaemon>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
```
4. Verify that Virtual Machine Management Service is running 
![image](https://user-images.githubusercontent.com/9146456/76245141-bf335580-6211-11ea-8291-7603c13a0f0c.png)
5. Re-launch Docker Desktop and receive the same crash report on startup.
6. Switch to Windows Containers and observe "Docker Desktop is running" status

**Comment by luismachaner** [comment]
I had the same situation, very similar versions:
- Windows 10 Enterprise, Version 1809, OS Build 17763.1158
- Docker Desktop Version: 2.2.0.5 (43884) stable

What worked for me (probably, some steps are not needed): 
1. Switch to Windows containers --> docker is running, as you reported
1. Activate the Windows Subsystem for Linux (and reboot)
1. Switch to Linux containers --> docker is running!
1. Deactivate the Windows Subsystem for Linux (and reboot) --> docker is running
