### ISSUE TITLE
docker wont start on windows 10

### ISSUE THREAD

**Issue by cryptofool13** [docker/for-win#5975]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5F815D61-5F60-4AD5-867B-30367E72FFF9/20200310022329

### Expected behavior
opening Docker Desktop should start docker
### Actual behavior
error occurs:

> Docker.Core.Backend.BackendDestroyException:
Unable to stop Hyper-V VM: Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.
at Enable-MobyLinuxRequiredService, <No file>: line 103
at <ScriptBlock>, <No file>: line 804
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
System.Management.Automation.RuntimeException:
  Unable to stop Hyper-V VM: Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.
  at Enable-MobyLinuxRequiredService, <No file>: line 103
  at <ScriptBlock>, <No file>: line 804
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.ContainerEngine.Linux.DoStop()
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.PowerShell.Commands.ServiceCommandException:
     Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.
     
         System.InvalidOperationException:
         Cannot start service vmcompute on computer '.'.
            at System.ServiceProcess.ServiceController.Start(String[] args)
            at Microsoft.PowerShell.Commands.ServiceOperationBaseCommand.DoStartService(ServiceController serviceController)
         
              System.ComponentModel.Win32Exception:
              The service did not respond to the start or control request in a timely fashion

### Information

  - Windows Version: windows 10 enterprise version 1909 (build 18363.657)
  - Docker Desktop Version: 19.03.5, build 633a0ea 
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. install Docker Desktop installer
  2. install docker checking default settings in wizard
  3. open Docker Desktop

**Comment by cryptofool13** [comment]
Fixed this myself by disabling Hyper-V hypervisor. 

I ran  `Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-Hypervisor ` in powershell as administrator and restarted my computer.

**Comment by yangjiajun2014** [comment]
Hello.I get the same issue but docker says it needs Hypervisor after I close this windos feature.

**Comment by sw54321** [comment]
I have the same issue. Any idea how to fix this?
