### ISSUE TITLE
docker failed to start after window update.

### ISSUE THREAD

**Issue by Shawh1** [docker/for-win#6007]
System.InvalidOperationException:
Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.WPF.BackendClient.Version()
   at Docker.WPF.BackendClient.CheckVersion()
   at Docker.WPF.BackendClient.CheckService(String action)
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass30_0.<ResetToDefault>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

**Comment by zmej-serow** [comment]
I've got the same error and stacktrace today after installing KB4551762 cumulative update for Windows10, addressing security issues with SMB3.1.1.

After uninstalling KB4551762 my Docker Desktop is ok and running healthy. Seems like MS have broken something...

**Comment by Shawh1** [comment]
Thank you for feedback. I tried it, uninstall KB4551762 but the problem is still there.

**Comment by ssandeep53** [comment]
Hello Friends, any luck in resolving this error?

**Comment by ssandeep53** [comment]
System.InvalidOperationException:
Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.WPF.BackendClient.Version()
   at Docker.WPF.BackendClient.CheckVersion()
   at Docker.WPF.BackendClient.CheckService(String action)
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters)
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

**Comment by Shawh1** [comment]
Check Virtual Machines in your Hyper-v Manger. In my case, VM was missing.
![Hyper-V Manager](https://user-images.githubusercontent.com/31732368/76962007-b4b64180-691e-11ea-88e7-74cece339e57.png)

**Comment by ssandeep53** [comment]
Thanks Fahad. I do not have any virtual machines in my machine.

**Comment by Shawh1** [comment]
Try to create a VM by "docker-machine create --driver hyperv default". I tried this command but it didn't create a VM for me. I end up redeploying my system. Give it a try it might work for you.

**Comment by ssandeep53** [comment]
Reinstalling the application worked!!
Thanks Fahad :)
