### ISSUE TITLE
Cannot start Docker for Windows: Fails to Initialize

### ISSUE THREAD

**Issue by mitchellmaler** [docker/for-win#601]
### Expected behavior
Docker for win to start. 
### Actual behavior
Docker failed to initilize. 
### Information
Unable to create an instance of Docker.Actions: Unable to create an instance of Docker.WPF.WelcomeWindow
   at Docker.Core.di.Singletons.NewInstance(Type type, Int32 depth)
   at Docker.Core.di.Singletons.Get(Type type, Int32 depth)
   at Docker.Core.di.Singletons.Get[T]()
   at Docker.Program.Run(IReadOnlyCollection`1 args)

Version: 17.03.0-ce-win1 (10296)
Channel: stable
Sha1: e5a07a1a69a5123c71e24ca2aa9e6f875fa26d08
Started on: 2017/03/22 09:36:29.985
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.693.amd64fre.rs1_release.161220-1747
File: C:\Users\MM025313\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:36:30.099][GUI            ][Info   ] Starting...
[09:36:30.417][Tracking       ][Info   ] Crash report and usage statistics are enabled
[09:36:30.421][SegmentApi     ][Info   ] Usage statistic: appLaunched
[09:36:30.538][NamedPipeClient][Info   ] Sending Version()...
[09:36:30.541][NamedPipeClient][Info   ] Received response for Version
[09:36:30.541][SegmentApi     ][Info   ] Usage statistic: heartbeat
[09:36:30.540][NamedPipeServer][Info   ] Version done in 00:00:00.
[09:36:30.820][GUI            ][Error  ] Unable to create an instance of Docker.Actions: Unable to create an instance of Docker.WPF.WelcomeWindow
[09:38:22.990][ErrorReportWindow][Info   ] Open logs

### Steps to reproduce the behavior

Try to start the Docker for Windows program/service. I immediately get the error and it wont start.

**Comment by valorisdev** [comment]
I've the same issue too.
I try to open the desktop app.

Unable to create an instance of Docker.Actions: Unable to create an instance of Docker.WPF.WelcomeWindow
   à Docker.Core.di.Singletons.NewInstance(Type type, Int32 depth)
   à Docker.Core.di.Singletons.Get(Type type, Int32 depth)
   à Docker.Core.di.Singletons.Get[T]()
   à Docker.Program.Run(IReadOnlyCollection`1 args)

**Crash report**
[log.txt](https://github.com/docker/for-win/files/919335/log.txt)

**Comment by nvn6w** [comment]
I have same problem.
I installed Docker Toolbox, Docker worked property. But when I started Kitematic, Windows has crashed. I reboot my PC and could not start Docker again.

`Version: 17.03.1-ce-win5 (10743)
Channel: stable
Sha1: b18e2a50ccf296bcd637b330c0ca9faaab9d790c
Started on: 2017/04/17 17:16:41.919
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1703
Build: 15063
BuildLabName: 15063.0.amd64fre.rs2_release.170317-1834
File: C:\Users\user\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[17:16:42.092][GUI            ][Info   ] Starting...
[17:16:42.483][Tracking       ][Info   ] Crash report and usage statistics are enabled
[17:16:42.489][SegmentApi     ][Info   ] Usage statistic: appLaunched
[17:16:42.679][NamedPipeClient][Info   ] Sending Version()...
[17:16:42.698][NamedPipeClient][Info   ] Received response for Version
[17:16:42.700][SegmentApi     ][Info   ] Usage statistic: heartbeat
[17:16:39.271][BackendServer  ][Info   ] Started
[17:16:42.695][NamedPipeServer][Info   ] Version()
[17:16:42.696][NamedPipeServer][Info   ] Version done in 00:00:00.0005018.
[17:16:43.356][GUI            ][Error  ] Unable to create an instance of Docker.Actions: Unable to create an instance of Docker.WPF.WelcomeWindow
[17:16:49.736][ErrorReportWindow][Info   ] Open logs
`

**Comment by nvn6w** [comment]
I have same issue too.

Unable to create an instance of Docker.Actions: Unable to create an instance of Docker.WPF.WelcomeWindow
   at Docker.Core.di.Singletons.NewInstance(Type type, Int32 depth)
   at Docker.Core.di.Singletons.Get(Type type, Int32 depth)
   at Docker.Core.di.Singletons.Get[T]()
   at Docker.Program.Run(IReadOnlyCollection`1 args)
[log.txt](https://github.com/docker/for-win/files/925368/log.txt)

**Comment by mitchellmaler** [comment]
I just ran the installer again and I can see com.docker.service is running in the background. I tried to run powershell (Admin) and run docker commands and I get 
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.27/containers/json?all=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

When I click the desktop icon either normally or as admin for Docker for Windows I get presented with a error page that says: 
Unable to create an instance of Docker.Actions: Unable to create an instance of Docker.WPF.WelcomeWindow
   at Docker.Core.di.Singletons.NewInstance(Type type, Int32 depth)
   at Docker.Core.di.Singletons.Get(Type type, Int32 depth)
   at Docker.Core.di.Singletons.Get[T]()
   at Docker.Program.Run(IReadOnlyCollection`1 args)

I check the logs and here is what It says: 
Version: 17.03.1-ce-win12 (12058)
Channel: stable
Sha1: d1db12684b33b778cfc3012e92959e50eb486fcd
Started on: 2017/05/17 08:24:39.162
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.1198.amd64fre.rs1_release_sec.170427-1353
File: C:\Users\MM025313\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[08:24:39.283][GUI            ][Info   ] Starting...
[08:24:39.613][Tracking       ][Info   ] Crash report and usage statistics are enabled
[08:24:39.617][SegmentApi     ][Info   ] Usage statistic: appLaunched
[08:24:39.731][NamedPipeClient][Info   ] Sending Version()...
[08:24:39.734][NamedPipeClient][Info   ] Received response for Version
[08:24:39.734][SegmentApi     ][Info   ] Usage statistic: heartbeat
[08:24:39.733][NamedPipeServer][Info   ] Version done in 00:00:00.
[08:24:40.010][GUI            ][Error  ] Unable to create an instance of Docker.Actions: Unable to create an instance of Docker.WPF.WelcomeWindow
[08:24:46.510][ErrorReportWindow][Info   ] Open logs

**Comment by friism** [comment]
Can you try the latest 17.05 edge installer?

It would also be good to have more details on your environment, eg. whether you're running Docker for Windows in a VM or such.

**Comment by mitchellmaler** [comment]
I installed  Version: 17.05.0-ce-win11 (12053) and I am still getting the same error when it starts up. 

Version: 17.05.0-ce-win11 (12053)
Channel: edge
Sha1: ffbc5f5871f44611dfb2bbf49e8312332531c112
Started on: 2017/05/17 10:17:45.746
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.1198.amd64fre.rs1_release_sec.170427-1353
File: C:\Users\MM025313\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[10:17:45.859][GUI            ][Info   ] Starting...
[10:17:46.228][Tracking       ][Info   ] Crash report and usage statistics are enabled
[10:17:46.233][SegmentApi     ][Info   ] Usage statistic: appLaunched
[10:17:46.371][NamedPipeClient][Info   ] Sending Version()...
[10:17:46.375][NamedPipeClient][Info   ] Received response for Version
[10:17:46.375][SegmentApi     ][Info   ] Usage statistic: heartbeat
[10:17:46.373][NamedPipeServer][Info   ] Version done in 00:00:00.
[10:17:46.645][GUI            ][Error  ] Unable to create an instance of Docker.Actions: Unable to create an instance of Docker.WPF.WelcomeWindow
[10:17:46.657][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[10:17:46.661][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\MM025313\AppData\Local\Temp\vkgxrwpw.avw\pcap.tar)...
[10:17:46.661][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\MM025313\AppData\Local\Temp\vkgxrwpw.avw\mobyLogs.tar)...
[10:17:46.661][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\MM025313\AppData\Local\Temp\vkgxrwpw.avw\win_containers)...
[10:17:46.662][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[10:17:46.662][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\MM025313\AppData\Local\Temp\vkgxrwpw.avw\pcap.tar)
[10:17:46.662][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\MM025313\AppData\Local\Temp\vkgxrwpw.avw\win_containers)
[10:17:46.671][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[10:17:46.663][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[10:17:46.685][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[10:17:46.663][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0009998.
[10:17:46.664][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\MM025313\AppData\Local\Temp\vkgxrwpw.avw\mobyLogs.tar)
[10:17:46.664][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[10:17:46.669][NamedPipeServer][Info   ] GetDebugInfo()
[10:17:46.685][HyperV         ][Warning] Unable to download logs: Unrecognized Guid format.
[10:17:46.685][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.0210094.
[10:17:48.208][ErrorReportWindow][Info   ] Open logs
[10:17:57.675][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[10:17:57.675][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:11.0131989.
[10:18:16.489][NamedPipeServer][Info   ] GetDebugInfo done in 00:00:29.8203262.
[10:18:16.497][NamedPipeClient][Info   ] Received response for GetDebugInfo
[10:18:17.352][CrashReport    ][Info   ] Uploading diagnostics...
[10:18:18.664][CrashReport    ][Info   ] Diagnostics successfully uploaded (8B19227C-B3B8-48C8-898A-F7C45E6F228E/2017-05-17_10-17-46)
[10:18:18.676][GUI            ][Info   ] Sending Bugsnag report 71b1f766-9edf-404c-beba-fc835e34e7ad...
[10:18:19.642][GUI            ][Info   ] Bugsnag report 71b1f766-9edf-404c-beba-fc835e34e7ad sent

My host OS is Windows 10 Enterprise and I am trying to run docker on that so no virtual machine. I made sure Hyper-V is enabled in the features. 
Windows version: 1607
OS Build: 14393.1198
Dell Precision 5510
Processor: i7-6820HQ CPU @ 2.70GHz
RAM: 32GB.

The installer doesn't fail but when I run Docker for Windows I am getting that error. I can run the CLI in powershell but it cannot connect to the daemon since it wont start up. 

PS: docker ps -a
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.29/containers/json?all=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

**Comment by valorisdev** [comment]
I have exactly the same problem

**Shell client error**

PS > docker ps -a

`error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.29/containers/json?all=1: open //./pipe/docker_engine: The system cannot find the file specified.  In the default daemon configuration on Windows, the docker client must be run elevted to connect. This error may also indicate that the docker daemon is not running.`

**Logs File**

[log.txt](https://github.com/docker/for-win/files/1018228/log.txt)

**Comment by mitchellmaler** [comment]
Is there any help for this?

**Comment by friism** [comment]
@jeanlaurent @simonferquel can you take a look?

**Comment by mitchellmaler** [comment]
I installed the newest Edge on my windows laptop and now the Docker daemon is starting in the background which is allowing me to run containers and commands in the console. However I am still getting a .NET exception a different way that doesn't crash the daemon but doesn't allow the welcome window to show. I have pasted the error details: 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Docker.Core.ExperimentalFeatures.Fixup(String name, String trackingId, ExperimentalFeature feature) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\ExperimentalFeatures.cs:line 252
   at Docker.Core.ExperimentalFeatures.Get(String name) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\ExperimentalFeatures.cs:line 234
   at Docker.WPF.WelcomeWindow..ctor(CredentialManager credManager, ISettingsLoader settingsLoader, IExperimentalFeatures features, IAnalytics analytics, IVersion version) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\WelcomeWindow.xaml.cs:line 99
   at Docker.WPF.WelcomeWindowShower.Show(ISettings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.WPF\WelcomeWindow.xaml.cs:line 48
   at Docker.Actions.<>c__DisplayClass17_0.<DoStart>b__0() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Windows\Actions.cs:line 104


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1648.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Docker for Windows
    Assembly Version: 17.6.0.12433
    Win32 Version: 17.6.0.12433
    CodeBase: file:///C:/Program%20Files/Docker/Docker/Docker%20for%20Windows.exe
----------------------------------------
Docker.Core
    Assembly Version: 17.6.0.12433
    Win32 Version: 17.6.0.12433
    CodeBase: file:///C:/Program%20Files/Docker/Docker/Docker.Core.DLL
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1647.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1647.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1647.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1647.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1647.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1647.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Docker.WPF
    Assembly Version: 17.6.0.12433
    Win32 Version: 17.6.0.12433
    CodeBase: file:///C:/Program%20Files/Docker/Docker/Docker.WPF.DLL
----------------------------------------
Docker.Backend
    Assembly Version: 17.6.0.12433
    Win32 Version: 17.6.0.12433
    CodeBase: file:///C:/Program%20Files/Docker/Docker/Docker.Backend.DLL
----------------------------------------
NLog
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Program%20Files/Docker/Docker/NLog.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1636.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1637.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1637.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
Microsoft.Toolkit.Uwp.Notifications
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1.0
    CodeBase: file:///C:/Program%20Files/Docker/Docker/Microsoft.Toolkit.Uwp.Notifications.DLL
----------------------------------------
Windows.UI
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/windows/system32/WinMetadata/Windows.UI.winmd
----------------------------------------
System.Runtime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll
----------------------------------------
Windows.Data
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/windows/system32/WinMetadata/Windows.Data.winmd
----------------------------------------
Windows.Foundation
    Assembly Version: 255.255.255.255
    Win32 Version: 10.0.10011.16384
    CodeBase: file:///C:/windows/system32/WinMetadata/Windows.Foundation.winmd
----------------------------------------
System.Runtime.InteropServices.WindowsRuntime
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.WindowsRuntime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.WindowsRuntime.dll
----------------------------------------
Docker.Win32Helpers
    Assembly Version: 1.0.6360.9119
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files/Docker/Docker/Docker.Win32Helpers.DLL
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.1.19813
    CodeBase: file:///C:/Program%20Files/Docker/Docker/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.ServiceProcess
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceProcess/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.ServiceProcess.dll
----------------------------------------
System.Management.Automation
    Assembly Version: 3.0.0.0
    Win32 Version: 10.0.14393.1198
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Management.Automation/v4.0_3.0.0.0__31bf3856ad364e35/System.Management.Automation.dll
----------------------------------------
WindowsFormsIntegration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
    CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by jasonbivins** [comment]
Hi @mitchellmaler 
Are you running any apps linked in with the experimental features in the GUI? It looks like there's a path missing - but it's not a default installation path.  C:\gopath\src\github.com\docker\pinata\win\src\

System.NullReferenceException: Object reference not set to an instance of an object.
at Docker.Core.ExperimentalFeatures.Fixup(String name, String trackingId, ExperimentalFeature feature) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\ExperimentalFeatures.cs

**Comment by mitchellmaler** [comment]
@jasonbivins I do not. I just ran the edge installer (Version 17.06.0-rc1-ce-win13 (12433)) and that is what happened from the get go.

**Comment by valorisdev** [comment]
@jasonbivins **Problem solved**

I've updated Windows 10
Version 10.0.15063 Numéro 15063

**Comment by jasonbivins** [comment]
Hi @valorisdev thanks for letting me know - You were on the minimum windows version for D4W Build 10586, but there have been recent updates, especially to networking.  We might need to double check our system requirements.

**Comment by jasonbivins** [comment]
@mitchellmaler   I'm sorry you've had such an adventure getting docker running.

Can you try looking for a Docker registry key here - then delete it and reinstall? Please be sure to make a quick registry backup before deleting any keys.
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall

This will trick the installer into doing a new fresh install - there might be missing folders or a path leftover from one of the previous tries.

**Comment by mitchellmaler** [comment]
@jasonbivins After clearing the  registry and reinstalling the edge release I am not getting the .NET exception error. The service is running and I am able to run docker cli commands to create an image and run a container.  However I am still unable to get the the Docker for Windows GUI. I right click the task icon and it just waits for a bit and then just shows "About". Really the only reason I need the GUI is to mount a shared drive where I can increase the memory from the hyper-v console. Is there a way to mound a drive without the GUI and also what logging can I give you to help out with the GUI issue.

**Comment by bluebaroncanada** [comment]
Same issue here, @mitchellmaler

**Comment by bluebaroncanada** [comment]
Bump

**Comment by amosyuen** [comment]
same issue with the mounting here

**Comment by bluebaroncanada** [comment]
Why is this not high priority, yet?  This is a severe issue, and I'm being pressured to move our company away from Docker.

**Comment by jasonbivins** [comment]
Hi @mitchellmaler 
what are the contents of your daemon.json file ?  It's located at C:\ProgramData\Docker\Config

If it's empty, add {} and restart docker.

**Comment by mitchellmaler** [comment]
@jasonbivins both of the config files had something in it.

**Comment by bluebaroncanada** [comment]
Our team abandoned Docker on Friday because of this issue.

**Comment by mitchellmaler** [comment]
@jasonbivins So I ended up uninstalling, going through and removing all docker files I can find. Installing the stable version and now it is working. I am able to get to the GUI and also was able to mount my C drive.

**Comment by friism** [comment]
@bluebaroncanada I'm sorry Docker didn't work out for you. If you want to help improve Docker for others, please provide details on where you were trying to install Docker for Windows, and what version.
