### ISSUE TITLE
Docker Desktop Fails to start

### ISSUE THREAD

**Issue by Mwiedmeyer** [docker/for-win#6012]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID:
7BE1388C-B543-4D95-AE76-94A796202AB8/20200313142614
### Expected behavior
Docker Desktop starts
### Actual behavior
Docker Desktop produces an error
### Information

  - Windows Version: Win 10 Enterprise version 1909 (OS Build 18363.657)
  - Docker Desktop Version: 2.2.0.4 (43472)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
### Steps to reproduce the behavior

  1. Docker Desktop fails to start every time with:
Docker.Core.Backend.BackendException:
fatal: failed to start daemon: Error initializing network controller: Error creating default network: failed during hnsCallRawResponse: hnsCall failed in Win32: Element not found. (0x490)
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  Docker.Core.DockerException:
  fatal: failed to start daemon: Error initializing network controller: Error creating default network: failed during hnsCallRawResponse: hnsCall failed in Win32: Element not found. (0x490)
     at Docker.Backend.Processes.WindowsDockerDaemon.WaitForDaemonToBeReady()
     at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions)
     at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
     at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
     at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by zmej-serow** [comment]
I've got the same error and stacktrace today after installing KB4551762 cumulative update for Windows10, addressing security issues with SMB3.1.1.

After uninstalling KB4551762 my Docker Desktop is ok and running healthy.
