### ISSUE TITLE
Docker for Windows Starting crashed

### ISSUE THREAD

**Issue by umarriswanap** [docker/for-win#6028]
Docker.Core.Backend.BackendDestroyException:
job failed with message: Failed to create a new virtual machine.

'DockerDesktopVM' failed to realize. (Virtual machine ID 622141C1-A6BB-4985-95CE-F77C7480784E)

Failed to access configuration store: A virtual disk support provider for the specified file was not found. (0xC03A0014).
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.InvalidOperationException:
  job failed with message: Failed to create a new virtual machine.

'DockerDesktopVM' failed to realize. (Virtual machine ID 622141C1-A6BB-4985-95CE-F77C7480784E)

Failed to access configuration store: A virtual disk support provider for the specified file was not found. (0xC03A0014).
     at Docker.Backend.HyperVInfrastructure.HandleUpdatedJob(CIMConcreteJob updatedJob)
     at Docker.Backend.HyperVInfrastructure.<HandleMaybeAsyncJob>d__36.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Docker.Backend.HyperVInfrastructure.<CreateDefaultVMAsync>d__11.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Docker.Backend.HyperVInfrastructure.<CreateOrConfigureDockerVMAsync>d__9.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Docker.Backend.HyperV.<CreateOrConfigureAsync>d__8.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Docker.Backend.ContainerEngine.Linux.<>c__DisplayClass38_0.<DoStartTask>b__0()
     at System.Threading.Tasks.Task.Execute()

**Comment by zmej-serow** [comment]
Did you just installed recent Windows updates?

I've got the same error and stacktrace today after installing [KB4551762](https://support.microsoft.com/en-us/help/4551762/windows-10-update-kb4551762) cumulative update for Windows10, addressing security issues with SMB3.1.1.

After uninstalling KB4551762 my Docker Desktop is ok and running healthy. Seems like MS have broken something...

**Comment by Laro88** [comment]
I have a machine with the KB4551762 and it is running docker fine, and another that is not fine :-(
Just saying - it might not be so simple.
