### ISSUE TITLE
Failure to start up on Win10pro

### ISSUE THREAD

**Issue by Laro88** [docker/for-win#6034]
- [ x] I have tried with the latest version of my channel Stable
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID:6B346ABE-0B0A-4B01-9ED6-46331FFEAA99/20200316075819

### Actual behavior
Docker simply won't start for some reason, the DockerDesktopVM fails with the basic error: DockerDesktopVM failed to start.

**Comment by zidad** [comment]
I seem to have a similar issue, not sure if it's the same:
 
Docker.Core.Backend.BackendException:
No answer from VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoRestartVM(Settings previousSettings)
   at Docker.Actions.<>c__DisplayClass34_0.<RestartVM>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  Docker.Core.DockerException:
  No answer from VM, aborting
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.BackendNamedPipeServer.<Run>b__8_3(Object[] args)
     at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
     at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Comment by Siron777** [comment]
I have the exact same error with the version 2.2.0.5, 2.2.0.4, 2.2.0.3.

**Comment by Siron777** [comment]
For my case it is an issue with the port 2375 reserved by windows. I did what was referenced in the issue #3546 and now it is working.

**Comment by byronsanchez** [comment]
Docker for Windows was not starting for me, and I was getting this message as well- "No answer from VM, aborting". #3546 resolved it in my case.

Thanks for the pointer @Siron777!
