### ISSUE TITLE
Unable to create Hyper-V VM

### ISSUE THREAD

**Issue by PandomaOes** [docker/for-win#6050]
- [ /] I have tried with the latest version of my channel (Stable or Edge)
  - [ /] I have uploaded Diagnostics
  - Diagnostics ID:
55A5471F-DEFF-4D43-968C-78A641B0AA97/20200316205439 (when it was installing)
55A5471F-DEFF-4D43-968C-78A641B0AA97/20200317021556 (troubleshoot again within the application)

### Actual behavior
The Docker Windows keeps on saying its starting at the bottom left of the dashboard and shows this error every time it crashes.

`Docker.Core.DockerException:
Docker.Core.Backend.BackendDestroyException:
Unable to create Hyper-V VM: Hyper-V encountered an error trying to access an object on computer 'DESKTOP-MB1LNG5' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
at New-MobyLinuxVM, <No file>: line 388
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  System.Management.Automation.RuntimeException:
  Unable to create Hyper-V VM: Hyper-V encountered an error trying to access an object on computer 'DESKTOP-MB1LNG5' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
  at New-MobyLinuxVM, <No file>: line 388
  at New-MobyLinux, <No file>: line 182
  at <ScriptBlock>, <No file>: line 810
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.HyperV.Create(Settings settings)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     Hyper-V encountered an error trying to access an object on computer 'DESKTOP-MB1LNG5' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
     
         Microsoft.Virtualization.Client.Management.ServerObjectDeletedException:
         Hyper-V encountered an error trying to access an object on computer 'DESKTOP-MB1LNG5' because the object was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
            at Microsoft.Virtualization.Client.Management.Server.LoadOSInfo()
            at Microsoft.HyperV.PowerShell.VirtualizationObjectLocator.PrepareServerConnections(Server server, Boolean allowDownlevelServers)
            at Microsoft.HyperV.PowerShell.VirtualizationObjectLocator.GetServer(String computerName)
            at Microsoft.HyperV.PowerShell.ExceptionHelper.TryWithLogging[TInput,TOutput](Func`2 function, TInput input, IOperationWatcher operationWatcher)
         
              Microsoft.Management.Infrastructure.CimException:
              Not found 
                 at Microsoft.Management.Infrastructure.Internal.Operations.CimSyncEnumeratorBase`1.MoveNext()
                 at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
                 at Microsoft.Virtualization.Client.Management.CimSessionWrapper.GetInstance(String namespaceName, ICimInstance instanceId, CimOperationOptions options)
                 at Microsoft.Virtualization.Client.Management.Server.GetInstance(WmiObjectPath wmiObjectPath, CimOperationOptions options)
                 at Microsoft.Virtualization.Client.Management.Server.LoadOSInfo()
              
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()`

### Expected behavior
No idea, have never used docker Desktop prior to this.

### Information

  - Windows Version: 1903
  - Docker Desktop Version: newest (16/3/2020 vers.)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no, main.

**Comment by PandomaOes** [comment]
I have also tried to factory reset the docker as advised by the error report area but it still does not work.

**Comment by PandomaOes** [comment]
Updated windows to 1909 and its solved.
