### ISSUE TITLE
Docker Desktop won't start

### ISSUE THREAD

**Issue by dmarinnmmaorg** [docker/for-win#6068]
Expected behavior
Docker Desktop will start

Actual behavior
Docker Desktop won't start

Information
- Is the problem new?
Yes. It had worked in the past

- Did the problem appear with an update?
I had some windows updates, but can't say if it is related

- Windows Version:
Windows 10 pro
version: 1903
OS buikd 18362.720

- Docker Desktop Version:
2.2.0.4(43472)

- Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No

Error:
Docker.Core.DockerException:
Docker.Core.Backend.BackendDestroyException:
Unable to create Hyper-V VM: The operation failed.

An unexpected error occurred: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).

The operation failed.

The Hyper-V Virtual Machine Management service encountered an unexpected error: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).
at New-MobyLinuxVM, <No file>: line 397
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  System.Management.Automation.RuntimeException:
  Unable to create Hyper-V VM: The operation failed.

An unexpected error occurred: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).
  
  The operation failed.

The Hyper-V Virtual Machine Management service encountered an unexpected error: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).
  at New-MobyLinuxVM, <No file>: line 397
  at New-MobyLinux, <No file>: line 182
  at <ScriptBlock>, <No file>: line 810
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.HyperV.Create(Settings settings)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     The operation failed.

An unexpected error occurred: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).
     
     The operation failed.

The Hyper-V Virtual Machine Management service encountered an unexpected error: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).
     
         Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException:
         The operation failed.

An unexpected error occurred: Logon failure: the user has not been granted the requested logon type at this computer. (0x80070569).
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation, Boolean throwIfAffectedElementNotFound)
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation)
            at Microsoft.Virtualization.Client.Management.VMServiceView.EndCreateVirtualSystem[T](IVMTask task)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
            at Microsoft.HyperV.PowerShell.VirtualMachine.Create(Server server, String name, String location, Int32 generation, Version version, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateVirtualMachine(Server server, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateObjects(IOperationWatcher operationWatcher)
         
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

**Comment by jagretz** [comment]
I have experienced this error in many versions of docker-desktop for windows. You can "resolve" this by quitting docker-desktop and running (in powershell -- elevated mode):

```powershell
net stop vmms
# wait
net start vmms
```

This is only temporarily. It only fixes the problem for the time being. Next time you run into this error, just run the same commands. I haven't narrowed it down completely, but I will mention a couple of things:
- I update my Windows machine often
- I am running a machine managed by my organization. I am not aware of all of the administration and security software they have running on that could be initiating this problem (potentially)
- This error occurs when I use hibernate, and also when I restart. I am not sure if this same problem exists when shutting down completely.
