### ISSUE TITLE
Docker windows 10

### ISSUE THREAD

**Issue by matodrobec** [docker/for-win#607]
Hello, Could not start docker under windows 10

Unable to stop: Couldn't stop VM MobyLinuxVM
at Fatal, <No file>: line 372
at Stop-VM-Force, <No file>: line 368
at Stop-MobyLinuxVM, <No file>: line 298
at <ScriptBlock>, <No file>: line 379
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStop()
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

Log:

Version: 17.03.1-ce-rc1-win3 (10625)
Channel: edge
Sha1: 1795b358d57a91b5de5abac91fe6360420deb704
Started on: 2017/03/29 07:21:32.807
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.953.amd64fre.rs1_release_inmarket.170303-1614
File: C:\Users\Martin\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[07:21:33.619][GUI            ][Info   ] Starting...
[07:21:34.614][Tracking       ][Info   ] Crash report and usage statistics are enabled
[07:21:34.626][SegmentApi     ][Info   ] Usage statistic: appLaunched
[07:21:34.955][NamedPipeClient][Info   ] Sending Version()...
[07:21:34.980][NamedPipeClient][Info   ] Received response for Version
[07:21:34.982][SegmentApi     ][Info   ] Usage statistic: heartbeat
[07:21:24.181][BackendServer  ][Info   ] Started
[07:21:34.977][NamedPipeServer][Info   ] Version()
[07:21:34.978][NamedPipeServer][Info   ] Version done in 00:00:00.0009999.
[07:21:35.458][SegmentApi     ][Info   ] Usage statistic: eventElectedForFeature
[07:21:35.460][SegmentApi     ][Info   ] Usage statistic: stateFeatureEnabled
[07:21:35.705][Updater        ][Info   ] Checking for updates on channel edge...
[07:21:35.705][Notifications  ][Info   ] Docker is starting...
[07:21:35.729][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[07:21:35.733][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[07:21:35.743][PowerMode      ][Info   ] Stop
[07:21:35.746][HyperV         ][Info   ] Stop
[07:21:35.761][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[07:21:35.764][PowerShell     ][Info   ] Creating a Runspace Pool...
[07:21:35.797][Updater        ][Info   ] Local build 10625 is as good as the remote 10625 on channel edge
[07:21:36.202][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[07:21:36.337][HyperV         ][Info   ] Script started at 07:21:36.326
[07:21:38.735][HyperV         ][Info   ] Module loaded at 07:21:38.735
[07:21:39.647][HyperV         ][Info   ] Stopping VM MobyLinuxVM...
[07:21:42.475][HyperV         ][Info   ] Turn Off VM ...
[07:21:42.770][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:21:43.877][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:21:45.016][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:21:46.078][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:21:47.155][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:21:48.218][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:21:49.287][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:21:50.364][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:21:51.417][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:21:52.474][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:21:53.518][Moby           ][Info   ] Stop
[07:21:53.559][Linux          ][Error  ] Failed to start: Unable to stop: Couldn't stop VM MobyLinuxVM
at Fatal, <No file>: line 372
at Stop-VM-Force, <No file>: line 368
at Stop-MobyLinuxVM, <No file>: line 298
at <ScriptBlock>, <No file>: line 379. Let's retry
[07:21:53.577][PowerShell     ][Info   ] Run script...
[07:22:00.973][HyperV         ][Info   ] Hyper-V is running
[07:22:00.973][PowerMode      ][Info   ] Stop
[07:22:00.973][HyperV         ][Info   ] Stop
[07:22:00.976][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[07:22:01.013][HyperV         ][Info   ] Script started at 07:22:01.012
[07:22:01.078][HyperV         ][Info   ] Module loaded at 07:22:01.078
[07:22:01.295][HyperV         ][Info   ] Stopping VM MobyLinuxVM...
[07:22:02.947][HyperV         ][Info   ] Turn Off VM ...
[07:22:02.981][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:04.054][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:05.151][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:06.214][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:07.309][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:08.365][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:09.433][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:10.512][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:11.569][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:12.693][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:13.723][Moby           ][Info   ] Stop
[07:22:13.755][PowerMode      ][Info   ] Stop
[07:22:13.755][HyperV         ][Info   ] Stop
[07:22:13.757][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[07:22:13.792][HyperV         ][Info   ] Script started at 07:22:13.791
[07:22:13.862][HyperV         ][Info   ] Module loaded at 07:22:13.861
[07:22:13.971][HyperV         ][Info   ] Stopping VM MobyLinuxVM...
[07:22:16.277][HyperV         ][Info   ] Turn Off VM ...
[07:22:16.335][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:17.406][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:18.495][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:19.554][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:20.625][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:21.713][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:22.803][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:23.900][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:24.955][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:26.053][HyperV         ][Info   ] Kill VM MobyLinuxVM process...
[07:22:27.079][Moby           ][Info   ] Stop
[07:22:27.115][NamedPipeServer][Error  ] Unable to execute Start: Unable to stop: Couldn't stop VM MobyLinuxVM
at Fatal, <No file>: line 372
at Stop-VM-Force, <No file>: line 368
at Stop-MobyLinuxVM, <No file>: line 298
at <ScriptBlock>, <No file>: line 379    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStop()
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[07:22:27.153][NamedPipeClient][Error  ] Unable to send Start: Unable to stop: Couldn't stop VM MobyLinuxVM
at Fatal, <No file>: line 372
at Stop-VM-Force, <No file>: line 368
at Stop-MobyLinuxVM, <No file>: line 298
at <ScriptBlock>, <No file>: line 379
[07:22:27.158][Notifications  ][Error  ] Unable to stop: Couldn't stop VM MobyLinuxVM
at Fatal, <No file>: line 372
at Stop-VM-Force, <No file>: line 368
at Stop-MobyLinuxVM, <No file>: line 298
at <ScriptBlock>, <No file>: line 379
[07:22:27.201][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[07:22:27.207][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\Martin\AppData\Local\Temp\gbouj5kw.x2y\pcap.tar)...
[07:22:27.210][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[07:22:27.217][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\Martin\AppData\Local\Temp\gbouj5kw.x2y\mobyLogs.tar)...
[07:22:27.276][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\Martin\AppData\Local\Temp\gbouj5kw.x2y\win_containers)...
[07:22:27.360][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[07:22:27.281][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\Martin\AppData\Local\Temp\gbouj5kw.x2y\pcap.tar)
[07:22:27.266][NamedPipeServer][Info   ] GetDebugInfo()
[07:22:27.880][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[07:22:27.265][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\Martin\AppData\Local\Temp\gbouj5kw.x2y\mobyLogs.tar)
[07:22:27.344][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[07:22:27.344][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0630180.
[07:22:27.511][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[07:22:27.874][HyperV         ][Warning] Unable to download logs: Connection failed
[07:22:27.874][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.6090207.
[07:22:27.882][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\Martin\AppData\Local\Temp\gbouj5kw.x2y\win_containers)
[07:22:42.095][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[07:22:42.093][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:14.2113883.
[07:23:22.309][NamedPipeServer][Info   ] GetDebugInfo done in 00:00:55.0427061.
[07:23:22.313][NamedPipeClient][Info   ] Received response for GetDebugInfo
[07:23:24.030][CrashReport    ][Info   ] Uploading diagnostics...
[07:23:27.075][CrashReport    ][Info   ] Diagnostics successfully uploaded (409A39CC-0E36-4420-8A88-418EF4CA3356/2017-03-29_07-22-27)
[07:23:27.174][GUI            ][Info   ] Sending Bugsnag report 5cf6878a-6e29-40b5-bc84-8eae03c72c98...
[07:23:28.469][GUI            ][Info   ] Bugsnag report 5cf6878a-6e29-40b5-bc84-8eae03c72c98 sent
[07:23:45.774][ErrorReportWindow][Info   ] Open logs

**Comment by friism** [comment]
can you please add a diagnostic id?
