### ISSUE TITLE
Unable to stop Hyper-V VM: Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'. at Enable-MobyLinuxRequiredService

### ISSUE THREAD

**Issue by bjornwall** [docker/for-win#6074]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [x ] I have uploaded Diagnostics
  - Diagnostics ID: 51A7162D-C39B-4C62-94A2-3016F034151E/20200319082333

### Expected behavior
Docker Desktop starts.
### Actual behavior
Docker Desktop doesn't start.
### Information

  - Windows Version: 10 Pro, version 1809, OS build 17763.1039
  - Docker Desktop Version: 2.2.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Enable Windows features "Hyper-V" and "Containers"
  2. Hard re-boot windows (pressing power button 15 seconds)
3. Press F1 to get to BIOS setup.
4. In BIOS settings, enable "Intel (R) Virtualization Technology" and "Intel (R) VT-d feature"
5. Save and let windows start
6. Download Docker Desktop for Windows (stable) and install.
7. Start Docker Desktop for Windows.
8. Error message appears before anything else starts:
Docker.Core.Backend.BackendDestroyException:
Unable to stop Hyper-V VM: Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.
at Enable-MobyLinuxRequiredService, <No file>: line 103
at <ScriptBlock>, <No file>: line 804
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.Management.Automation.RuntimeException:
  Unable to stop Hyper-V VM: Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.
  at Enable-MobyLinuxRequiredService, <No file>: line 103
  at <ScriptBlock>, <No file>: line 804
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.ContainerEngine.Linux.DoStop()
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.PowerShell.Commands.ServiceCommandException:
     Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.
     
         System.InvalidOperationException:
         Cannot start service vmcompute on computer '.'.
            at System.ServiceProcess.ServiceController.Start(String[] args)
            at Microsoft.PowerShell.Commands.ServiceOperationBaseCommand.DoStartService(ServiceController serviceController)
         
              System.ComponentModel.Win32Exception:
              The service did not respond to the start or control request in a timely fashion

**Comment by arseniybanayev** [comment]
I have something similar

```
Docker.Core.DockerException:
Docker.Core.Backend.BackendException:
Unable to create Hyper-V VM: The computer '.' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at New-MobyLinuxVM, <No file>: line 388
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810

  System.Management.Automation.RuntimeException:
  Unable to create Hyper-V VM: The computer '.' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
  at New-MobyLinuxVM, <No file>: line 388
  at New-MobyLinux, <No file>: line 182
  at <ScriptBlock>, <No file>: line 810
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.BackendNamedPipeServer.<Run>b__8_3(Object[] args)
     at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
     at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     The computer '.' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
     
         Microsoft.Virtualization.Client.Management.ServerConnectionException:
         The computer '.' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
            at Microsoft.Virtualization.Client.Management.ServerNames.Resolve(String nameToResolve, IUserPassCredential credential)
            at Microsoft.Virtualization.Client.Management.Server.GetServer(String name, IUserPassCredential credential)
            at Microsoft.HyperV.PowerShell.VirtualizationObjectLocator.GetServer(String computerName)
            at Microsoft.HyperV.PowerShell.ExceptionHelper.TryWithLogging[TInput,TOutput](Func`2 function, TInput input, IOperationWatcher operationWatcher)
         
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoRestartVM(Settings previousSettings)
   at Docker.Actions.<>c__DisplayClass34_0.<RestartVM>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
```
