### ISSUE TITLE
issue with docker instalation

### ISSUE THREAD

**Issue by kanth1222** [docker/for-win#6079]
Docker.Core.Backend.BackendDestroyException:
Unable to stop Hyper-V VM: Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.
at Enable-MobyLinuxRequiredService, <No file>: line 103
at <ScriptBlock>, <No file>: line 804
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.Management.Automation.RuntimeException:
  Unable to stop Hyper-V VM: Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.
  at Enable-MobyLinuxRequiredService, <No file>: line 103
  at <ScriptBlock>, <No file>: line 804
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.ContainerEngine.Linux.DoStop()
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.PowerShell.Commands.ServiceCommandException:
     Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.
     
         System.InvalidOperationException:
         Cannot start service vmcompute on computer '.'.
            at System.ServiceProcess.ServiceController.Start(String[] args)
            at Microsoft.PowerShell.Commands.ServiceOperationBaseCommand.DoStartService(ServiceController serviceController)
         
              System.ComponentModel.Win32Exception:
              The service did not respond to the start or control request in a timely fashion

**Comment by Hamsterman** [comment]
I have used Docker Desktop for easy installation.
