### ISSUE TITLE
Unable to start Docker Desktops service exception

### ISSUE THREAD

**Issue by 8ctopus** [docker/for-win#6106]
- [NOT TESTED] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F6FACDFC-D90A-40E8-8A1A-FC5A6D749036/20200324044003

### Information

If Docker Desktop service is disabled on Docker for Windows start it will ask:

"Docker Desktop service is not running, would you like to start it? Windows will ask you for elevated access. [Start] [Quit]"

Select [Start] which is followed by the exception:

Docker.Core.DockerException:
Unable to start Docker Desktops service: 2
   at Docker.WPF.BackendClient.CheckService(String action)
   at Docker.WPF.BackendClient.SendMessage(String action, Object[] parameters)
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

- Windows Version: Windows 10 Pro 1909
- Docker Desktop Version: 2.2.0.4 (43472)
- Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Expected behavior

Docker Desktop should check for service status before trying to start it and therefore avoid the exception. Potentially you may want to get the service out of the disabled state.

### Actual behavior

see above.

### Steps to reproduce the behavior

1. close Docker Desktop
2. disable Docker Desktop service in services.msc
3. start Docker Desktop

**Comment by 8ctopus** [comment]
tested in version 2.3.0.4 (46911), it still crashes Docker and this time without any visible messages.
