### ISSUE TITLE
Unable to create Hyper-V VM because of a weird computer name '.'

### ISSUE THREAD

**Issue by arseniybanayev** [docker/for-win#6112]
### Expected behavior
Docker Desktop for Windows restarts successfully.
### Actual behavior
A window pops up with the title "An error occurred" and the following exception details:
```Docker.Core.DockerException:
Docker.Core.Backend.BackendException:
Unable to create Hyper-V VM: The computer '.' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at New-MobyLinuxVM, <No file>: line 388
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810

  System.Management.Automation.RuntimeException:
  Unable to create Hyper-V VM: The computer '.' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
  at New-MobyLinuxVM, <No file>: line 388
  at New-MobyLinux, <No file>: line 182
  at <ScriptBlock>, <No file>: line 810
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.BackendNamedPipeServer.<Run>b__8_3(Object[] args)
     at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
     at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     The computer '.' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
     
         Microsoft.Virtualization.Client.Management.ServerConnectionException:
         The computer '.' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
            at Microsoft.Virtualization.Client.Management.ServerNames.Resolve(String nameToResolve, IUserPassCredential credential)
            at Microsoft.Virtualization.Client.Management.Server.GetServer(String name, IUserPassCredential credential)
            at Microsoft.HyperV.PowerShell.VirtualizationObjectLocator.GetServer(String computerName)
            at Microsoft.HyperV.PowerShell.ExceptionHelper.TryWithLogging[TInput,TOutput](Func`2 function, TInput input, IOperationWatcher operationWatcher)
         
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoRestartVM(Settings previousSettings)
   at Docker.Actions.<>c__DisplayClass34_0.<RestartVM>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
```

### Information
  - Windows Version: **10.0.18363 Build 18363**
  - Docker Desktop Version: **same behavior with stable 2.2.0.4 and this prototype build https://github.com/docker/for-win/issues/6016#issuecomment-600285551**
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: **No, I'm working on a Microsoft Surface Laptop with the above Windows OS version installed**

I can privately upload Diagnostics to someone if necessary.

### Steps to reproduce the behavior
  1. Restart Docker Desktop for Windows

Unfortunately, I can't remember any changes to my system or updates to Docker that may have coincided with the start of this behavior.

Trying with Edge version now...

**Comment by arseniybanayev** [comment]
Edge 2.2.2.0 solves this problem.
