### ISSUE TITLE
Docker V17.03.1-ce-win5(10743)  doesn't start after installation on Windows 10 VM

### ISSUE THREAD

**Issue by whgao** [docker/for-win#613]
### Expected behavior
Docker should start after installation
### Actual behavior
"An error occured" dialog shows following errors:

The operation has timed out.
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

### Information
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
AE69FA84-9993-495C-ACBA-28D18601D0A9/2017-03-31_10-05-51

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows 10 Enterprise Version 1607 (OS Build 14393.969)

### Steps to reproduce the behavior

  1. install Docker for Windows
  2. Start Docker for Windows

**Comment by friism** [comment]
@jeanlaurent can someone look into this?

**Comment by julioms87** [comment]
I am having exactly the same issue

@whgao try to switch for Windows containers, with me, it's requested me to reboot my system and then worked perfectly but if I switch back to Linux containers... I got the same error message again.

there is any other issue like this been treated right now?

**Comment by mryusazeeme** [comment]
Im facing the same issue here. Anybody can help on this?

**Comment by bitops** [comment]
Same issue.

**Comment by s-jeyaram** [comment]
Duplicate of #1038

**Comment by matoy** [comment]
Hi guys,
Seems i have exact same behavior here.
Cheers.

**Comment by relnah** [comment]
Still an issue after updates.
Disgnostic id: 18D5608F-3086-460D-BD15-84F84F2C55D6/2017-10-26_08-42-13
Docker version:
Version 17.09.0-ce-win33 (13620)
Channel: stable
8c56a3b
Win version:
Win 10 info:
Edition: Windows 10 Enterprise x64
Version: 1709
OS Build: 16299.19
CPU: Inter Core i7-6600U 2.6GHz
RAM: 16 GB

**Comment by abarke** [comment]
Yep, linux containers was working before I tried to switch to Windows Containers. It rebooted and now when I switch back I cant start the linux containers anymore.

Version: 17.09.1-ce-win42 (14687)
Channel: stable
Sha1: 3176a6af014bdb1346ed31371a717e87e656e2b7
Started on: 2017/12/21 15:56:56.837
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.1794.amd64fre.rs1_release.171008-1615
File: C:\Users\abarker\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 

The operation has timed out.
at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 245
at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 122
at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

**Comment by jszoja** [comment]
Same here. It stopped working since I attempted to switch to windows containers. I canceled it as I didn't want to reboot.
At the same time I was updating docker, so it is hard to say what was the cause: update or switching to windows containers.
Server Version: 17.12.0-ce
