### ISSUE TITLE
Unable to start Docker on Windows

### ISSUE THREAD

**Issue by Abdullah2993** [docker/for-win#623]
Log File:
```
Version: 17.03.1-ce-win5 (10743)
Channel: stable
Sha1: b18e2a50ccf296bcd637b330c0ca9faaab9d790c
Started on: 2017/04/07 11:53:38.364
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.953.amd64fre.rs1_release_inmarket.170303-1614
File: C:\Users\Abdullah Saleem\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:53:40.856][GUI            ][Info   ] Starting...
[11:53:46.965][Tracking       ][Info   ] Crash report and usage statistics are enabled
[11:53:47.215][SegmentApi     ][Info   ] Usage statistic: appLaunched
[11:53:48.480][NamedPipeClient][Info   ] Sending Version()...
[11:53:48.637][NamedPipeClient][Info   ] Received response for Version
[11:53:48.637][SegmentApi     ][Info   ] Usage statistic: heartbeat
[11:45:59.289][PowerShell     ][Info   ] Run script...
[11:53:48.480][NamedPipeServer][Info   ] Version()
[11:53:48.480][NamedPipeServer][Info   ] Version done in 00:00:00.
[11:53:56.621][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[11:53:56.621][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[11:53:56.621][PowerMode      ][Info   ] Stop
[11:53:56.621][HyperV         ][Info   ] Stop
[11:53:56.652][Updater        ][Info   ] Checking for updates on channel stable...
[11:53:57.043][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:53:57.043][HyperV         ][Info   ] Script started at 11:53:57.043
[11:53:57.527][HyperV         ][Info   ] Module loaded at 11:53:57.527
[11:53:57.558][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:53:57.558][HyperV         ][Debug  ] [stop] took 00:00:00.9375010 to run
[11:53:57.558][OptimizeDisk   ][Info   ] Optimize
[11:53:57.558][PowerShell     ][Info   ] Run script...
[11:53:57.574][Moby           ][Info   ] Stop
[11:53:57.574][HyperV         ][Info   ] Create
[11:53:57.574][PowerMode      ][Info   ] Start
[11:53:57.574][HyperVGuids    ][Info   ] Installing GUIDs...
[11:53:57.574][Firewall       ][Info   ] Removing all existing rules...
[11:53:57.574][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[11:53:57.574][HyperVGuids    ][Info   ] GUIDs installed
[11:53:57.574][HyperV         ][Info   ] Script started at 11:53:57.574
[11:53:57.668][HyperV         ][Info   ] Module loaded at 11:53:57.668
[11:53:57.668][Firewall       ][Info   ] All existing rules are removed.
[11:53:57.668][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[11:53:57.683][Firewall       ][Info   ] Opening ports for SMB...
[11:53:57.683][Firewall       ][Info   ] Ports are opened
[11:53:57.808][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:53:57.965][Updater        ][Info   ] Local build 10743 is as good as the remote 10743 on channel stable
[11:54:11.340][HyperV         ][Info   ] Switch created.
[11:54:15.777][HyperV         ][Info   ] Set IP address on switch
[11:54:15.793][Linux          ][Error  ] Failed to start: Unable to create: ISO file at C:\Program Files\Docker\Docker\Resources\mobylinux.iso does not exist
at Fatal, <No file>: line 372
at New-MobyLinuxVM, <No file>: line 185
at <ScriptBlock>, <No file>: line 381. Let's retry
[11:54:15.793][PowerShell     ][Info   ] Run script...
[11:54:38.588][HyperV         ][Info   ] Hyper-V is running
[11:54:38.588][PowerMode      ][Info   ] Stop
[11:54:38.588][HyperV         ][Info   ] Stop
[11:54:38.588][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:54:38.588][HyperV         ][Info   ] Script started at 11:54:38.588
[11:54:38.603][HyperV         ][Info   ] Module loaded at 11:54:38.603
[11:54:38.619][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:54:38.619][HyperV         ][Debug  ] [stop] took 00:00:00.0312478 to run
[11:54:38.619][OptimizeDisk   ][Info   ] Optimize
[11:54:38.619][PowerShell     ][Info   ] Run script...
[11:54:38.635][Moby           ][Info   ] Stop
[11:54:38.650][HyperV         ][Info   ] Destroy
[11:54:38.650][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[11:54:38.650][HyperV         ][Info   ] Script started at 11:54:38.650
[11:54:38.666][HyperV         ][Info   ] Module loaded at 11:54:38.666
[11:54:38.681][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:54:38.681][HyperV         ][Info   ] Destroying Switch DockerNAT...
[11:54:41.619][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[11:54:41.635][HyperV         ][Debug  ] [destroy] took 00:00:02.9843729 to run
[11:54:41.635][Firewall       ][Info   ] Closing ports...
[11:54:41.635][Firewall       ][Info   ] Removing all existing rules...
[11:54:41.697][Firewall       ][Info   ] All existing rules are removed.
[11:54:41.697][Firewall       ][Info   ] Ports are closed
[11:54:41.697][HyperVGuids    ][Info   ] Removing GUIDs...
[11:54:41.697][HyperVGuids    ][Info   ] GUIDs removed
[11:54:41.697][HyperV         ][Info   ] Create
[11:54:41.697][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[11:54:41.713][HyperV         ][Info   ] Script started at 11:54:41.713
[11:54:41.728][HyperV         ][Info   ] Module loaded at 11:54:41.728
[11:54:41.775][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:54:45.463][HyperV         ][Info   ] Switch created.
[11:54:45.713][HyperV         ][Info   ] Set IP address on switch
[11:54:45.713][PowerMode      ][Info   ] Stop
[11:54:45.713][HyperV         ][Info   ] Stop
[11:54:45.713][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:54:45.728][HyperV         ][Info   ] Script started at 11:54:45.728
[11:54:45.744][HyperV         ][Info   ] Module loaded at 11:54:45.744
[11:54:45.775][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:54:45.775][HyperV         ][Debug  ] [stop] took 00:00:00.0625007 to run
[11:54:45.775][OptimizeDisk   ][Info   ] Optimize
[11:54:45.775][PowerShell     ][Info   ] Run script...
[11:54:45.791][Moby           ][Info   ] Stop
[11:54:45.791][HyperV         ][Info   ] Destroy
[11:54:45.791][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[11:54:45.791][HyperV         ][Info   ] Script started at 11:54:45.791
[11:54:45.822][HyperV         ][Info   ] Module loaded at 11:54:45.822
[11:54:45.838][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:54:45.838][HyperV         ][Info   ] Destroying Switch DockerNAT...
[11:54:48.291][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[11:54:48.306][HyperV         ][Debug  ] [destroy] took 00:00:02.5156339 to run
[11:54:48.306][Firewall       ][Info   ] Closing ports...
[11:54:48.306][Firewall       ][Info   ] Removing all existing rules...
[11:54:48.322][Firewall       ][Info   ] All existing rules are removed.
[11:54:48.322][NamedPipeClient][Error  ] Unable to send Start: Unable to create: ISO file at C:\Program Files\Docker\Docker\Resources\mobylinux.iso does not exist
at Fatal, <No file>: line 372
at New-MobyLinuxVM, <No file>: line 185
at <ScriptBlock>, <No file>: line 381
[11:54:48.322][Firewall       ][Info   ] Ports are closed
[11:54:48.322][Notifications  ][Error  ] Unable to create: ISO file at C:\Program Files\Docker\Docker\Resources\mobylinux.iso does not exist
at Fatal, <No file>: line 372
at New-MobyLinuxVM, <No file>: line 185
at <ScriptBlock>, <No file>: line 381
[11:54:48.322][HyperVGuids    ][Info   ] Removing GUIDs...
[11:54:48.322][HyperVGuids    ][Info   ] GUIDs removed
[11:54:48.322][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: ISO file at C:\Program Files\Docker\Docker\Resources\mobylinux.iso does not exist
at Fatal, <No file>: line 372
at New-MobyLinuxVM, <No file>: line 185
at <ScriptBlock>, <No file>: line 381    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[11:55:13.600][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[11:55:13.644][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\Abdullah Saleem\AppData\Local\Temp\zoudaie2.vnr\pcap.tar)...
[11:55:13.648][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[11:55:13.662][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\Abdullah Saleem\AppData\Local\Temp\zoudaie2.vnr\mobyLogs.tar)...
[11:55:13.662][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\Abdullah Saleem\AppData\Local\Temp\zoudaie2.vnr\win_containers)...
[11:55:13.662][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\Abdullah Saleem\AppData\Local\Temp\zoudaie2.vnr\pcap.tar)
[11:55:13.701][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[11:55:13.701][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0390545.
[11:55:14.527][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[11:55:14.529][NamedPipeServer][Info   ] GetDebugInfo()
[11:55:14.530][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\Abdullah Saleem\AppData\Local\Temp\zoudaie2.vnr\win_containers)
[11:55:14.541][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\Abdullah Saleem\AppData\Local\Temp\zoudaie2.vnr\mobyLogs.tar)
[11:55:14.685][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[11:55:14.910][HyperV         ][Warning] Unable to download logs: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual machine with name "MobyLinuxVM".
[11:55:14.912][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[11:55:14.910][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.3683342.
[11:56:22.117][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[11:56:22.117][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:01:07.5863364.
[11:57:03.022][NamedPipeServer][Info   ] GetDebugInfo done in 00:01:48.4930420.
[11:57:03.025][NamedPipeClient][Info   ] Received response for GetDebugInfo
[11:57:04.095][CrashReport    ][Info   ] Uploading diagnostics...
[11:57:20.820][CrashReport    ][Info   ] Diagnostics successfully uploaded (A61A7E92-22C5-41E9-8F7B-9672E7A2DAD6/2017-04-07_11-55-13)
[11:57:20.831][GUI            ][Info   ] Sending Bugsnag report a9330630-3c3a-4ff6-a4ff-a1e864efe799...
[11:57:22.648][GUI            ][Info   ] Bugsnag report a9330630-3c3a-4ff6-a4ff-a1e864efe799 sent
[11:58:00.346][ErrorReportWindow][Info   ] Open logs
[11:58:30.900][ErrorReportWindow][Info   ] Open logs
```

**Comment by KenWatts** [comment]
I finally solved this by completely uninstalling and reinstalling docker.  I'm using Kalabox, so I reinstalled that, as well. Good luck!

**Comment by friism** [comment]
@Abdullah2993 can you check if uninstalling and re-installing solves the problem for you?

**Comment by Abdullah2993** [comment]
@friism works after a reinstall
