### ISSUE TITLE
I can not install Docker 2.2.0.5 in windows 10 - same for Docker 2.2.0.3

### ISSUE THREAD

**Issue by horatiucherebetiu** [docker/for-win#6243]
I uploaded the crash report and got next id: E9746E32-08DF-4663-9A23-CB73C2E270DA/20200406080447

Exception:
Docker.Core.Backend.BackendDestroyException:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.TimeoutException:
  Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
     at Docker.Backend.LifecycleClient.WaitForServerUp(TimeSpan pingTimeout)
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)

**Comment by ebriney** [comment]
Hi @horatiucherebetiu I see  `"VirtualizationFirmwareEnabled":  false` in your diagnostics did you enable virtualization in your BIOS?
(see https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/reference/hyper-v-requirements)

**Comment by horatiucherebetiu** [comment]
Short update, I don't know if it helps or not, I managed to install an older version, I don't know exact name but was before 2.2.0.3.
Only since I tried to upgrade from that older version to 2.2.0.3 and later I get this problem.
In this case is still related to that setting? Was this added since 2.2.X.X?

**Comment by horatiucherebetiu** [comment]
Previous version is: 18.06.0-ce-win72.
![image](https://user-images.githubusercontent.com/7371221/78566030-58f91d00-7827-11ea-8f72-f7d47894c642.png)

**Comment by horatiucherebetiu** [comment]
After unistalling 2.2.0.5 I tried to install the previous version but it could not start.
I disabled the Hyper-V option from Windows features -> restart -> enable back Hyper-V option and after, I could run docker again.

**Comment by horatiucherebetiu** [comment]
Any suggestions?
