### ISSUE TITLE
Docker Edge doesn't start with WSLv2 feature enabled

### ISSUE THREAD

**Issue by riverar** [docker/for-win#6250]
Diagnostics not available for privacy reasons.

*Fresh install* of Windows 10 19041. WSLv2 verified working, defaults set.

```
Version: 2.2.3.0 (43965)
Channel: edge
Sha1: c2444c4f79da816f420c4d36885afb5b22efcbda
Started on: 2020/04/06 12:33:17.576
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2004
Build: 19041
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\Rafael\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
```

Skimming the logs for errors, here's `vpnkit` acting up:
```
[12:33:20.515][LinuxWSL2Engine   ][Info   ] 2020/04/06 19:33:20 resolving /mnt/host/c/Program Files/Docker/Docker/resources/wsl/docker-wsl-cli.iso...
[12:33:20.518][LinuxWSL2Engine   ][Info   ] 2020/04/06 19:33:20 copying...
[12:33:20.532][APIRequestLogger  ][Info   ] [4223f58c] <Server start> GET http://unix/versions
[12:33:20.535][VpnKit            ][Info   ] vpnkit.exe: Setting handler to ignore all SIGPIPE signals
[12:33:20.535][VpnKit            ][Info   ] vpnkit.exe: Version is 218f01482560cba2fa863f9ad872ad51d1e717fc
[12:33:20.535][VpnKit            ][Info   ] vpnkit.exe: System SOMAXCONN is 2147483647
[12:33:20.535][VpnKit            ][Info   ] vpnkit.exe: Will use a listen backlog of 32
[12:33:20.535][VpnKit            ][Info   ] vpnkit.exe: No periodic Gc.compact enabled
[12:33:20.535][VpnKit            ][Error  ] vpnkit.exe: Starting to watch : EINVAL
[12:33:20.535][VpnKit            ][Error  ] vpnkit.exe: Failed to watch hosts file : invalid argument
[12:33:20.535][VpnKit            ][Warning] vpnkit.exe: There is no database: using hardcoded network configuration values
[12:33:20.535][VpnKit            ][Info   ] vpnkit.exe: DNS server configured with no builtin DNS names; everything will be forwarded
[12:33:20.535][VpnKit            ][Info   ] vpnkit.exe: 2 upstream DNS servers are configured
[12:33:20.535][VpnKit            ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
[12:33:20.535][VpnKit            ][Info   ] vpnkit.exe: Disabling transparent HTTP redirection
[12:33:20.535][VpnKit            ][Info   ] vpnkit.exe: Updating resolvers to use host resolver
[12:33:20.536][VpnKit            ][Info   ] vpnkit.exe: Secure random number generator is available
[12:33:20.536][VpnKit            ][Info   ] vpnkit.exe: Add(3): DNS configuration changed to: use host resolver
```

```
[12:33:20.567][VpnKitBridge      ][Info   ] Proxy mutagen: waiting for remote service to be available
[12:33:20.567][VpnKitBridge      ][Info   ] Proxy docker: waiting for remote service to be available
[12:33:20.567][VpnKitBridge      ][Info   ] Proxy log: waiting for remote service to be available
[12:33:20.567][VpnKitBridge      ][Info   ] Proxy diagnosticd: waiting for remote service to be available
[12:33:20.567][VpnKit            ][Error  ] vpnkit.exe: Pipe.listen: caught (Failure "Failed to connect vmnet device")
[12:33:20.568][VpnKitBridge      ][Info   ] received ack for service vpnkit, publishing locally
[12:33:20.568][VpnKitBridge      ][Info   ] received ack for service gui, publishing locally
[12:33:20.569][VpnKitBridge      ][Info   ] cannot find service ssh-auth
```

```
[12:33:34.939][VpnKitBridge      ][Info   ] error copying: The pipe has been ended.
[12:33:34.944][APIRequestLogger  ][Info   ] [a0e1aec6] <Server start> POST http://unix/docker
[12:33:34.946][LinuxkitDaemonStartup][Info   ] Received status FailedToStart
[12:33:34.951][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[12:33:35.072][APIRequestLogger  ][Info   ] [a0e1aec6] <Server end> POST http://unix/docker -> 204 NoContent (took 128ms)
[12:33:35.073][GoBackendProcess  ][Info   ] internal: POST /events 200 \"Go-http-client/1.1\" \"\
[12:33:35.110][VpnKitBridge      ][Info   ] disconnected data connection: multiplexer is offline
[12:33:35.110][VpnKit            ][Error  ] vpnkit.exe: Vmnet.Server.listen: read EOF so closing connection
[12:33:35.110][VpnKitBridge      ][Info   ] error CloseWrite to: file has already been closed
[12:33:35.110][GoBackendProcess  ][Info   ] disconnected data connection: multiplexer is offline
[12:33:35.110][VpnKit            ][Info   ] vpnkit.exe: Vmnet.Server.disconnect
[12:33:35.110][VpnKit            ][Info   ] vpnkit.exe: Vmnet.Server.listen returning Ok()
[12:33:35.110][VpnKitBridge      ][Info   ] error copying: file has already been closed
[12:33:35.110][VpnKit            ][Info   ] vpnkit.exe: TCP/IP stack disconnected
[12:33:35.110][VpnKitBridge      ][Info   ] error copying: file has already been closed
[12:33:35.110][GoBackendProcess  ][Error  ] error accepting subconnection: accept: multiplexer is not running
[12:33:35.110][VpnKitBridge      ][Info   ] error copying: file has already been closed
[12:33:35.110][GoBackendProcess  ][Info   ] established connection to vpnkit-forwarder
[12:33:35.110][VpnKitBridge      ][Info   ] error copying: file has already been closed
[12:33:35.110][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[12:33:35.117][VpnKitBridge      ][Fatal  ] remote vpnkit bridge exited. error is: exit status 9
[12:33:35.121][VpnKitBridge      ][Error  ] Process died
[12:33:35.162][VpnKit            ][Info   ] Killing existing vpnkit with PID 2548
[12:33:35.172][ApiProxy          ][Info   ] Killing existing com.docker.proxy with PID 5992
[12:33:35.177][LinuxWSL2Engine   ][Info   ] Stopping engine
```

After a few attempts, Docker eventually bombs out:
```
[12:33:58.990][LinuxWSL2Engine   ][Warning] Distro stopped with exit code 0
[12:33:59.087][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[12:33:59.087][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[12:33:59.087][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxWSL2
[12:33:59.088][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1586201639}
[12:33:59.088][SystrayNotifications][Error  ] Failed to start
[12:33:59.090][APIRequestLogger  ][Info   ] [dbb2a75c] <NotificationsClient start> POST http://localhost/engine/state
[12:33:59.103][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[12:33:59.140][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[12:33:59.141][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[12:33:59.141][GoBackendProcess  ][Info   ] mutagen sync list --output json
[12:33:59.147][APIRequestLogger  ][Info   ] [dbb2a75c] <NotificationsClient end> POST http://localhost/engine/state -> 200 OK (took 56ms)
[12:33:59.171][Engines           ][Error  ] Start failed with Failed to start
   at Docker.LinuxkitDaemonStartup.<StartAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__24.MoveNext())
```

**Comment by simonferquel** [comment]
Those vpnkit errors are expected. Can you send a diagnostic ?

**Comment by riverar** [comment]
@simonferquel Sorry, no, for reasons stated earlier. But digging through `dockerd.log` I found:
```
2020-04-06T22:08:50Z dockerd time="2020-04-06T22:08:50.732895600Z" level=warning msg="Running experimental build"
2020-04-06T22:08:50Z dockerd failed to create API server: Could not load X509 key pair (cert: "C:\\Users\\Rafael\\.docker\\certs\\xxxs.crt", key: "C:\\Users\\Rafael\\.docker\\certs\\xxx.pem"): open C:\Users\Rafael\.docker\certs\xxx.crt: no such file or directory
```

But the file exists on disk. Removal of explicit TLS configuration in daemon.conf resolved the issue. (It's my understanding this is a Docker-EE only feature.)

**Comment by PavelSosin-320** [comment]
@simonferquel  I had exactly the same problem with a similar log but now, with the recent WSL2 version the problem became more serious. Check and uncheck "allow access ... via TCP 2375 checkbox does nothing for me. To expose HTTP interface I added 0.0.0.0 2375 host to the daemon configuration. VpnKit tries to use sockets which are not created in the GuestSrvices folder by the daemon any more:.dial unix /run/guest-services/docker.sock: connect: connection refused. But VpnKit succeeds to use TCP connection:: vpnkit.exe: TCP/IP ready & vpnkit.exe: TCP/IP stack connected.
There is no /run/guest-services/docker.sock in my docker desktop distro because all interop sockets are moved to /run/WSL. 
Maybe, addition /run/guest-services/docker.sock to the Hosts list can solve the issue but VPNKit has numerous options but Docker Desktop has no configuration for them. All these options are relevant in the Enterprise environment and have no value in Home, Small office, and Cloud environment.  If I say "no TLS I trust in my Infra and socat with IPtables + Istio are OK for me. Could you give a hint about the neutralization of VpnKit test via Unix sockets during Docker Desktop bootstrap?
P.S. Since my DNS configuration is managed in my Router and connects me to the fastest available public DNS via Router firewall also port 53 mapping contradicts with my Router configuration.
