### ISSUE TITLE
Unable to run docker desktop in Windows container mode.

### ISSUE THREAD

**Issue by Jen-Pearson** [docker/for-win#6254]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 22AAA726-2BAB-47D5-8D74-C1DEDE4D29B4/20200407025258

### Expected behavior
Switch to Windows containers should complete without error
### Actual behavior
An error occurs consistently.
Docker.Core.Backend.BackendException:
Time out has expired and the operation has not been completed.
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.ServiceProcess.TimeoutException:
  Time out has expired and the operation has not been completed.
     at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
     at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env)
     at Docker.Backend.Processes.WindowsDockerDaemon.Start(Settings settings, String daemonOptions, Boolean useProtectedNamedPipe)
     at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions)
     at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
     at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
     at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
   
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

I installed Docker Desktop with the Linux option yesterday, and today I tried switching to windows containers to build some Sitecore images.  However switching failed.  I tried rebooting and it still errored.  I tried uninstalling and reinstalling this time selecting the install as windows containers checkbox (all 3 checkboxes ticked) - and now I cannot get it to start up successfully. 

Using Windows 10 laptop running docker desktop 2.2.05 (43884). Not virtualised.

### Steps to reproduce the behavior

Initially observed using the Switch to Windows containers and then after uninstalling and reinstalling with the Windows container option selected.

**Comment by Jen-Pearson** [comment]
Running Windows 10 Enterprise.  Edit doesn't seem to be doing anything - so am adding a comment.

**Comment by Jen-Pearson** [comment]
Looks like I have Windows 10 version 1709 - and as it's a work laptop I can't change this. Does this mean I can't run windows containers ?
