### ISSUE TITLE
Unable to start services after upgrading to 2.2.0.5

### ISSUE THREAD

**Issue by scaytrase** [docker/for-win#6267]
After system startup docker-compose is unable to run services

```
C:\Work\Projects\lamoda\b2b\nike_connector>docker-compose up -d
nike_connector_wiremock_1 is up-to-date
nike_connector_sftp_1 is up-to-date
nike_connector_db_1 is up-to-date
Recreating nike_connector_connector_1 ... error

ERROR: for nike_connector_connector_1  Cannot start service connector: Ports are not available: unable to list exposed ports: Get http://unix/forwards/list: open \\.\pipe\dockerBackendApiServer: The system cannot find the file specified.

ERROR: for connector  Cannot start service connector: Ports are not available: unable to list exposed ports: Get http://unix/forwards/list: open \\.\pipe\dockerBackendApiServer: The system cannot find the file specified.
ERROR: Encountered errors while bringing up the project.
```

Restarting docker in this case leads to following error after timeout

```
Docker.Core.Backend.BackendException:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoRestartVM(Settings previousSettings)
   at Docker.Actions.<>c__DisplayClass34_0.<RestartVM>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.TimeoutException:
  Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
     at Docker.Backend.LifecycleClient.WaitForServerUp(TimeSpan pingTimeout)
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.BackendNamedPipeServer.<Run>b__8_3(Object[] args)
     at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
     at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

Hard reset docker helps until next system restart

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FF6A4741-7501-4366-A874-ECEEDE7B956B/20200408135607

2.2.0.5 stable

**Comment by lawxen** [comment]
I have the same issue  
![image](https://user-images.githubusercontent.com/20714821/81317455-7425a980-90bf-11ea-9ccd-8b278f629b6a.png)

**Comment by jemini12** [comment]
I have same issue too.

The main point is that docker backend service is holding the port though the container has been killed.

Port is still alive after container remove.

```
>netstat -a -n -o | findstr :5001
  TCP    0.0.0.0:5001           0.0.0.0:0              LISTENING       12596
  TCP    [::]:5001              [::]:0                 LISTENING       12596
```

If you exit com.docker.backend process by task manager, docker works fine.
But this is not smart solution...

My version info.

![image](https://user-images.githubusercontent.com/7028307/84978874-fdbda200-b168-11ea-8069-0630b163ae12.png)
