### ISSUE TITLE
on win10 startup docker threw below error

### ISSUE THREAD

**Issue by liquidboy** [docker/for-win#6273]
**Expected behavior**
Startup works as it should.

**Actual behavior**
Docker wont start.

**Information**

win 10 19592.rs_prerelease 200321-1791 

win 10 startup docker failed to start and the below error was thrown.

I wanted to raise this error incase for history sake .. 

Feel free to close it

**Exception**

Docker.Core.DockerException:
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.

   at Docker.Engines.DockerDaemonChecker.<CheckAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.LinuxkitDaemonStartup.<StartAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext()

**Comment by pr1metine** [comment]
I'm having similar problems. Could you resolve this issue?

**Comment by pr1metine** [comment]
I actually just needed to restart Docker Desktop.
