### ISSUE TITLE
Update failed and docker stuck

### ISSUE THREAD

**Issue by cdalexndr** [docker/for-win#6318]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Update success.

### Actual behavior
Installation failed:
```
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<ReadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.DownloadStep.<DoAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()
```

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
After installation failed, the **About** windows doesn't show any info:
![info](https://user-images.githubusercontent.com/22418250/79123643-4a6cb180-7da3-11ea-9bd3-64d1394b81c3.png)
Also, the bottom icon is animating just like when it's starting, but hovering mouse over shows "Docker Desktop is running".
Opening the troublehoot window shows at the bottom: "Docker updating". Seems like it's stuck in updating mode even if it failed...
![troubl](https://user-images.githubusercontent.com/22418250/79123821-a5060d80-7da3-11ea-8d75-60c14ffcf8a6.png)
Clicking "Run Diagnostics" does nothing, seems like the whole docker is stuck now. Docker should auto recover from a failed update...

### Steps to reproduce the behavior

  1. Update popup when starting docker or "Check for updates"
  2. Try to install update

**Comment by cdalexndr** [comment]
Trying to restart docker shows "Waiting for running jobs to complete", I guess it's the hanged failed update that will never complete... Quit worked instead.

**Comment by ejepsen** [comment]
I have the same issue.

**Comment by YoungElPaso** [comment]
Mac users seem to have encountered this behaviour as well:
https://github.com/docker/for-mac/issues/4375

The solution there and what worked for me was starting Docker Desktop from the command line, not from the Start Menu (and on the Mac side, the same sort of issue, launching from the Dock didn't work, command line did).

**Comment by kuhlaid** [comment]
I had Docker Desktop (DD) pinned in my Windows taskbar. After changing the storage location in the DD settings I was no longer able to load DD from the Windows taskbar without DD being stuck in 'updating' state, and the DD whale in the taskbar would not load. If I loaded DD from the Windows start menu the whale appeared again in the taskbar and the DD update window appeared (which I had ignored earlier). This time instead of ignoring the update I opted to install the update (v2.2.0.3). Unfortunately the DD .vhdx file was being used by another process (OneDrive) during the update, which caused the update to fail and completely remove DD from my computer. So, I had to reinstall.

**Comment by rathga** [comment]
I had the same error and problem for 2.3.0.2 (45183).  This happened when initialising the update from the automatic update reminder that pops up.  However, starting the update manually from right clicking the quick-icon and selecting 'check for updates...' made it work ok.

**Comment by cdalexndr** [comment]
Downloading and running the new version installer worked for update.

**Comment by rwaltenberg** [comment]
Still happening until today

**Comment by getanujain** [comment]
I am also facing the same issue and Docker Desktop is still stuck in updating state. Tried below versions and none working for me. 
Docker Desktop Community 2.4.0.0
Docker Desktop Community 2.3.0.5
Docker Desktop Community 2.3.0.4

**Comment by yangzhuq** [comment]
2.4.0.0 更新也出现了类似的问题
