### ISSUE TITLE
Docker Desktop 2.2.0.5 (43884) does not start 

### ISSUE THREAD

**Issue by wosteven** [docker/for-win#6335]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C6BEEF77-CD45-4FF1-8B63-BDCA53379773/20200415114315

### Information

  - Windows Version: Windows 10 Enterprise 19.09 OS build 18363.720
  - Docker Desktop Version: 2.2.0.5 (43884)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior
- Install like Docker Desktop just like described on docker.io
- After starting Docker Desktop (or after rebooting) Docker Desktop stays in state "starting", after ~20min it crashes with a Popup:

Docker.Core.Backend.BackendDestroyException:
No answer from VM, aborting
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  Docker.Core.DockerException:
  No answer from VM, aborting
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)

**Comment by nerjamartin** [comment]
Disabling and re-enabling Hyper V again solved the problem in my case. I hope it helps you.
