### ISSUE TITLE
 Installed Docker for Windows 10 and started docker not starting

### ISSUE THREAD

**Issue by rkarthi91** [docker/for-win#6372]
- [ yes] I have tried with the latest version of my channel (Stable or Edge)
  - [ yes] I have uploaded Diagnostics
  - Diagnostics ID: 4FCACEBA-A07E-4D05-87EB-303A9BCBE8B4/20200418122422

### Expected behavior
Docker should be running

### Actual behavior
Docker is still starting

`Docker.Core.Backend.BackendDestroyException:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext() in C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters) in C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeClient.cs:line 39
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications) in C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Actions.cs:line 132
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0() in C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Actions.cs:line 104
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1() in C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\TaskQueuing\TaskQueue.cs:line 46

  System.TimeoutException:
  Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
     at Docker.Backend.LifecycleClient.WaitForServerUp(TimeSpan pingTimeout) in C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Backend\LifecycleClient\LifecycleClient.cs:line 123
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential) in C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 290
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential) in C:\workspaces\stable-2.2.x\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 139
  `

### Information

  - Windows Version: OS: Windows 10 Pro Professional 1709
  - Docker Desktop Version: 2.2.0.5 (43884) stable , 16299.15.amd64fre.rs3_release.170928-1534
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Installed Window 10 newly, 
  2. Installed Docker for Windows 10 and started docker not working

Attached log files

**Comment by rkarthi91** [comment]
Unable to attach files

**Comment by mathisgag** [comment]
Same problem
