### ISSUE TITLE
Switch to Linux containers

### ISSUE THREAD

**Issue by rpateld** [docker/for-win#6376]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by rpateld** [comment]
25B230B5-9EB5-4430-96B3-0F3AB39A91A1/20200418202056

**Comment by rpateld** [comment]
Docker.Core.Backend.BackendException:
Timed out while waiting for Docker daemon to be ready
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.<>c__DisplayClass39_0.<SwitchDaemon>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  Docker.Core.DockerException:
  Timed out while waiting for Docker daemon to be ready
     at Docker.Backend.Processes.WindowsDockerDaemon.WaitForDaemonToBeReady()
     at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings, String daemonOptions)
     at Docker.Backend.ContainerEngine.Windows.Start(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
     at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
     at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
