### ISSUE TITLE
Random Crash on Laptop Boot

### ISSUE THREAD

**Issue by KyL0R3Nz0** [docker/for-win#6402]
Upon booting my laptop and logging in, I auto-connect to our company VPN.  Could this crash of Docker be due to the network changing while Docker is launching?

I do not seem to have this issue when in the office,

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
619031A3-ACDF-4304-B054-37B4FAD2AD77/20200420195600
### Information

  - Windows Version:
```
[System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0
```

  - Docker Desktop Version:
```docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```
Yes, I am running PowerShell elevated.

  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No

### Steps to reproduce the behavior

  1. Boot laptop
  2. Log into laptop
  3. Auto-login to VPN.
  4. Docker crashes.

**Comment by KyL0R3Nz0** [comment]
```Access to the path 'C:\WINDOWS\System32\drivers\etc\hosts' is denied.```

Our company policy will never allow access to the hosts file, even when elevated.

**Comment by mat007** [comment]
Here is what Docker Desktop needs to add to the host file in case you wanted to have it added manually to unblock you:
```
# Added by Docker Desktop
192.168.1.12 host.docker.internal
192.168.1.12 gateway.docker.internal
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

**Comment by KyL0R3Nz0** [comment]
That’s great information. However, GPO for my company prevents ANY modifications to the hosts file. So, this will not work.

________________________________

**Comment by mat007** [comment]
I’ve created an internal ticket so that we can take a look at what that would imply in terms of feature limitation to not add these entries in the hosts file.

**Comment by KyL0R3Nz0** [comment]
This issue being unable to write to the hosts file actually causes Docker Desktop to crash.  I am unable to run it at all unless I reinstall (resetting to "factory defaults" doesn't even work).  For some reason, reinstalling allows me to run Docker for a short period of time, or until I reboot my laptop.  Then, I get this same error again:
```
Docker.Core.DockerException:
Docker.Core.Backend.BackendDestroyException:
Unable to create Hyper-V VM: Creating the virtual machine failed.
at New-MobyLinuxVM, <No file>: line 397
at New-MobyLinux, <No file>: line 182
at <ScriptBlock>, <No file>: line 810
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  System.Management.Automation.RuntimeException:
  Unable to create Hyper-V VM: Creating the virtual machine failed.
  at New-MobyLinuxVM, <No file>: line 397
  at New-MobyLinux, <No file>: line 182
  at <ScriptBlock>, <No file>: line 810
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.HyperV.Create(Settings settings)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     Creating the virtual machine failed.
     
         Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException:
         Creating the virtual machine failed.
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation, Boolean throwIfAffectedElementNotFound)
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturn[AffectedElementType](IVMTask task, VirtualizationOperation operation)
            at Microsoft.Virtualization.Client.Management.VMServiceView.EndCreateVirtualSystem[T](IVMTask task)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
            at Microsoft.HyperV.PowerShell.VirtualMachine.Create(Server server, String name, String location, Int32 generation, Version version, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateVirtualMachine(Server server, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.NewVM.CreateObjects(IOperationWatcher operationWatcher)
         
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
```
