### ISSUE TITLE
Can't start docker

### ISSUE THREAD

**Issue by walkonthemarz** [docker/for-win#648]
I have just installed the latest docker for windows and it can't start.
it showed the info:
`
Unable to write to the database. Exit code: 1
   在 Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:行号 243
   在 Docker.Backend.ContainerEngine.Linux.Start(Settings settings) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:行号 120
   在 Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:行号 44
   在 Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) 位置 C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:行号 140
`
diagnostic id: 31D0BD16-6AF7-4572-B7BC-E501BD86CB78/2017-04-16_17-38-59

**Comment by simonferquel** [comment]
Hi @samoht, can you check this one ? it seems that datakit fails to start with named pipe related errors

**Comment by seals55** [comment]
This may be related...I just installed the latest version of Windows Go.

```
C:\Users\name>go version
go version go1.8.1 windows/amd64

```
I rebooted and the Docker service failed to start...I now see gopath conflicts.

```
C:\Users\name>go env GOPATH
C:\Users\name\go
```

There is no C:\gopath on my machine


```
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 263
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 247
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 179
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 44
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 140
```
Diagnostic: 890EC609-BF7E-4D07-92E6-F031FFCC14F7/2017-04-22_10-54-19

**Comment by walkonthemarz** [comment]
Yes,I just installed the latest go(go version go1.8.1 windows/amd64) and got the same error message. 
What should i do to fix this?
Diagnostic: 31D0BD16-6AF7-4572-B7BC-E501BD86CB78/2017-04-23_16-14-31

**Comment by fuyunliu** [comment]
@walkonthemarz reinstall your OS

**Comment by seals55** [comment]
Mine fixed itself when i upgraded to Windows 10 version 1703.

**Comment by walkonthemarz** [comment]
Mine fixed itself too when i upgraded my Windows 10.
