### ISSUE TITLE
Ensure that the destination when changing disk image location has NTFS compression disabled

### ISSUE THREAD

**Issue by Neurrone** [docker/for-win#6515]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

Changing the disk image location to a destination with NTFS compression enabled should prompt the user to disable NTFS compression for that folder. 

### Actual behavior

When docker restarts, the VM crashes with the stack trace below when trying to boot:

<details>
<summary>crash logs</summary>
```
Docker.Core.DockerException:
Docker.Core.Backend.BackendDestroyException:
Unable to start Hyper-V VM: 'DockerDesktopVM' failed to start.

Synthetic SCSI Controller (Instance ID 07BD9889-C8BE-4930-BB7E-93285727A689): Failed to Power on with Error 'The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.'.

	Attachment 'D:\documents\docker\vm-data\DockerDesktop\DockerDesktop.vhdx' failed to open because of error: 'The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.'.

'DockerDesktopVM' failed to start. (Virtual machine ID 11DCDFC0-2BA6-47B6-BE1F-26110B3A8000)

'DockerDesktopVM' Synthetic SCSI Controller (Instance ID 07BD9889-C8BE-4930-BB7E-93285727A689): Failed to Power on with Error 'The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.' (0xC03A001A). (Virtual machine ID 11DCDFC0-2BA6-47B6-BE1F-26110B3A8000)

'DockerDesktopVM': Attachment 'D:\documents\docker\vm-data\DockerDesktop\DockerDesktop.vhdx' failed to open because of error: 'The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.' (0xC03A001A). (Virtual machine ID 11DCDFC0-2BA6-47B6-BE1F-26110B3A8000)
at Start-MobyLinuxVM, <No file>: line 688
at <ScriptBlock>, <No file>: line 811
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
   at Docker.Backend.BackendNamedPipeServer.<Run>b__8_2(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

  System.Management.Automation.RuntimeException:
  Unable to start Hyper-V VM: 'DockerDesktopVM' failed to start.

Synthetic SCSI Controller (Instance ID 07BD9889-C8BE-4930-BB7E-93285727A689): Failed to Power on with Error 'The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.'.

Attachment 'D:\documents\docker\vm-data\DockerDesktop\DockerDesktop.vhdx' failed to open because of error: 'The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.'.
  
  'DockerDesktopVM' failed to start. (Virtual machine ID 11DCDFC0-2BA6-47B6-BE1F-26110B3A8000)

'DockerDesktopVM' Synthetic SCSI Controller (Instance ID 07BD9889-C8BE-4930-BB7E-93285727A689): Failed to Power on with Error 'The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.' (0xC03A001A). (Virtual machine ID 11DCDFC0-2BA6-47B6-BE1F-26110B3A8000)

'DockerDesktopVM': Attachment 'D:\documents\docker\vm-data\DockerDesktop\DockerDesktop.vhdx' failed to open because of error: 'The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.' (0xC03A001A). (Virtual machine ID 11DCDFC0-2BA6-47B6-BE1F-26110B3A8000)
  at Start-MobyLinuxVM, <No file>: line 688
  at <ScriptBlock>, <No file>: line 811
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.HyperV.PowerShell.VirtualizationException:
     'DockerDesktopVM' failed to start.

Synthetic SCSI Controller (Instance ID 07BD9889-C8BE-4930-BB7E-93285727A689): Failed to Power on with Error 'The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.'.

Attachment 'D:\documents\docker\vm-data\DockerDesktop\DockerDesktop.vhdx' failed to open because of error: 'The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.'.
     
     'DockerDesktopVM' failed to start. (Virtual machine ID 11DCDFC0-2BA6-47B6-BE1F-26110B3A8000)

'DockerDesktopVM' Synthetic SCSI Controller (Instance ID 07BD9889-C8BE-4930-BB7E-93285727A689): Failed to Power on with Error 'The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.' (0xC03A001A). (Virtual machine ID 11DCDFC0-2BA6-47B6-BE1F-26110B3A8000)

'DockerDesktopVM': Attachment 'D:\documents\docker\vm-data\DockerDesktop\DockerDesktop.vhdx' failed to open because of error: 'The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.' (0xC03A001A). (Virtual machine ID 11DCDFC0-2BA6-47B6-BE1F-26110B3A8000)
     
         Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException:
         'DockerDesktopVM' failed to start.

Synthetic SCSI Controller (Instance ID 07BD9889-C8BE-4930-BB7E-93285727A689): Failed to Power on with Error 'The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.'.

Attachment 'D:\documents\docker\vm-data\DockerDesktop\DockerDesktop.vhdx' failed to open because of error: 'The requested operation could not be completed due to a virtual disk system limitation.  Virtual hard disk files must be uncompressed and unencrypted and must not be sparse.'.
            at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
            at Microsoft.Virtualization.Client.Management.VMComputerSystemBaseView.EndSetState(IVMTask setStateTask)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.<>c__DisplayClass4_0`1.<ConvertActionToFunction>b__0(T x)
            at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
            at Microsoft.HyperV.PowerShell.VirtualMachine.ChangeState(VirtualMachineAction action, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.StartVM.ProcessOneOperand(VirtualMachine vm, IOperationWatcher operationWatcher)
            at Microsoft.HyperV.PowerShell.Commands.VirtualizationCmdlet`1.ProcessOperands(IList`1 operands, IOperationWatcher operationWatcher)
         
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()
```
</details>

### Information
  - Windows Version: windows 10 1909
  - Docker Desktop Version: 2.20.5
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

### Steps to reproduce the behavior

  1. ... Go to settings -> resources and change the location of the disk image to a folder with NTFS compression enabled.
  2. ... Click on apply and restart.

**Comment by shiroinekotfs** [comment]
![image](https://github.com/docker/for-win/assets/115929530/1b04fe9a-1c3c-4d44-ae01-19c66f1b4f18)

Try to untick this on your `D:\` drive.

Make sure that you have permission **AND** `docker` is not running.
