### ISSUE TITLE
Intsalled Docker on Windows 10 and get the following error when starting: Unable to stop Hyper-V VM: Service 'Hyper-V Host Compute Service

### ISSUE THREAD

**Issue by pradeepramadasan** [docker/for-win#6519]
Docker.Core.Backend.BackendDestroyException:
Unable to stop Hyper-V VM: Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.
at Enable-MobyLinuxRequiredService, <No file>: line 103
at <ScriptBlock>, <No file>: line 804
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.Management.Automation.RuntimeException:
  Unable to stop Hyper-V VM: Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.
  at Enable-MobyLinuxRequiredService, <No file>: line 103
  at <ScriptBlock>, <No file>: line 804
     at Docker.Backend.HyperV.HandleException(String action, Exception ex)
     at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters, PowerShellConfiguration config)
     at Docker.Backend.ContainerEngine.Linux.DoStop()
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
  
     Microsoft.PowerShell.Commands.ServiceCommandException:
     Service 'Hyper-V Host Compute Service (vmcompute)' cannot be started due to the following error: Cannot start service vmcompute on computer '.'.
     
         System.InvalidOperationException:
         Cannot start service vmcompute on computer '.'.
            at System.ServiceProcess.ServiceController.Start(String[] args)
            at Microsoft.PowerShell.Commands.ServiceOperationBaseCommand.DoStartService(ServiceController serviceController)
         
              System.ComponentModel.Win32Exception:
              The service did not respond to the start or control request in a timely fashion

**Comment by Richard-Barrett** [comment]
Try this:

Try this, I had the same issue:
So I was actually able to solve it by doing the following:

Enter The following commands within an elevated command prompt:
```
Enable Hyper V - You can do this by running the following command as administrator. - dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All

Enable Hypervisor with following command - bcdedit /set hypervisorlaunchtype auto
```
Research: https://dotnetthoughts.net/hardware-assisted-virtualization-and-data-execution-protection-must-be-enabled/

Then Restart and prompt asks to download the Linux Kernel

Apparently Docker Desktop is forgetting this in their initial set-up for the updates and installation for anybody using Hyper-V and the Linux Containers requiring the WSL2 Linux Kernel Backend to initialize Containers. provided by Microsoft.

Microsoft Link: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

Download the above ^^

Stackoverflow Link: https://stackoverflow.com/questions/59413071/error-message-for-hyper-v-and-data-execution-for-docker-desktop-on-windows-10-fa/59653039#59653039

You need to Download wsl2-kernel. 
Similar Github Issue: https://github.com/docker/for-win/issues/6689
