### ISSUE TITLE
Docker Desktop failed to start after upgrading to 2.3.0.1

### ISSUE THREAD

**Issue by jbod** [docker/for-win#6521]
- [ X ] I have tried with the latest version of my channel (Stable or Edge)
  - [ X ] I have uploaded Diagnostics
  - Diagnostics ID: 6CFF6EB5-4D5C-4050-BA19-CE82CF449077/20200501152840

### Expected behavior

The Docker Desktop application is up and running.

### Actual behavior

The service remains in the "Starting" state for a couple of minutes, then fails with this error:

```System.TimeoutException:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
   at Docker.ApiServices.LifecycleClient.<WaitForServerUpAsync>d__8.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\LifecycleClient.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

### Information
- Windows Version: 10, 2004 build 19041.208
- Docker Desktop version: 2.3.0.1 (44875)

Using Docker Desktop to run containers with a WSL2 Debian instance.

This was working fine with the 2.3.0.0, but upgrading to 2.3.0.1 made it to break. I did not tried to reinstall the 2.3.0.0 yet, I will do this and push my results here.

Note that I also tried to disable my antivirus (BitDefender) with no success.

**Comment by jbod** [comment]
Just downgraded to version 2.3.0.0 and it now works like a charm!

Something in the 2.3.0.1 release is causing this issue. I'll stick with the 2.3.0.0 meanwhile.

**Comment by simonferquel** [comment]
Hmm, one of the things that retrograding to 2.3.0.0 did, was actually reset everything to default settings, and remove existing data. Have you tried to reset settings to factory defaults with 2.3.0.1 ?

**Comment by jbod** [comment]
@simonferquel You're right, reinstalling the 2.3.0.1 and resetting settings did the trick! Now all is working fine, thank you!
