### ISSUE TITLE
Failed to start Docker on Window 10 Pro with Docker Desktop

### ISSUE THREAD

**Issue by TheRealSpaceShip** [docker/for-win#6558]
- [x] I have tried with the latest version of my channel (Stable)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 107E88B0-2CB8-4EA6-821B-3B6B7F5D71DA/20200505085332

### Expected behavior
Docker is started successfully

### Actual behavior
Docker is failed to start

### Information

  - **Is it reproducible?:** Reproduced each time on Windows startup
  - **Is the problem new?:** For me - yes
  - **Did the problem appear with an update?:** No. I have installed latest stable version download from official website
  - **Windows Version:** Windows 10 Pro Build: 18363
  - **Docker Desktop Version:** 2.2.0.5 (43884) channel stable
  - **Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:** NO

[Logs file](https://github.com/docker/for-win/files/4579908/log.txt)

Error message:
```
Docker.Core.Backend.BackendDestroyException:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean withNotifications)
   at Docker.Actions.<>c__DisplayClass26_0.<StartAsync>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass18_0.<.ctor>b__1()

  System.TimeoutException:
  Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
     at Docker.Backend.LifecycleClient.WaitForServerUp(TimeSpan pingTimeout)
     at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions, Credential credential)
     at Docker.Backend.ContainerEngine.Linux.Start(Settings settings, String daemonOptions, Credential credential)
```

### Steps to reproduce the behavior

  1. Install Docker Desktop on Windows 10 Pro build 18363
  2. Enable start Docker Desktop on Windows startup
  3. Restart Windows

**Comment by relyafi** [comment]
I'm observing a similar issue. Information that is different from the above:

- **Diagnostics Id:** 98FD128B-2906-4277-9376-1A409E5924A9/20200505131816
- **Did the problem appear with an update?:** Possibly - I believe both the Docker Desktop version and the WSL Ubuntu version may have updated since last use.
- **Windows Version:** Windows 10 Pro Build: 19041
- **Docker Desktop Version:** 19.03.8 channel edge
- **Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:** No, but using WSL2 containers

`System.TimeoutException:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
   at Docker.ApiServices.LifecycleClient.<WaitForServerUpAsync>d__8.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\LifecycleClient.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92`
