### ISSUE TITLE
Failed to run service: System.ArgumentException

### ISSUE THREAD

**Issue by thomasrosted** [docker/for-win#6566]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 8D9E5AA9-E277-4B83-B7C7-3AC9111937AC/20200506120232

### Expected behavior
That the Docker Desktop Service starts without errors.

### Actual behavior
The service starts, but in C:\ProgramData\DockerDesktop\service.txt it list errors, and afterwards trying to start Docker Desktop also fails (with a different error).

```
System.InvalidOperationException:
Sequence contains no matching element
```

### Information
The problems happens consistently when starting the service. It's a newly installed machine.

C:\ProgramData\DockerDesktop\service.txt contains the following error, but the service keeps running:

```
Version: 2.2.0.5 (43884)
Channel: stable
Sha1: 758e889f2c543b35d0bdfa51e811744f686d81b3
Started on: 2020/05/06 13:45:22.223
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1909
Build: 18363
BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
File: C:\ProgramData\DockerDesktop\service.txt
CommandLine: "C:\Program Files\Docker\Docker\com.docker.service"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[13:45:22.303][DockerService     ][Info   ] Starting service
[13:45:22.311][ComponentVersions ][Info   ] Edition community
[13:45:22.335][ComponentVersions ][Info   ] Edition community
[13:45:22.346][DockerService     ][Error  ] Failed to run service: System.ArgumentException: Unable to create an instance of Docker.Backend.BackendService: Unable to create an instance of Docker.Backend.ContainerEngine.Linux: Unable to create an instance of Docker.Backend.HyperV: Unable to create an instance of Docker.Core.SettingsLoader: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Unable to create an instance of Docker.Backend.ContainerEngine.Linux: Unable to create an instance of Docker.Backend.HyperV: Unable to create an instance of Docker.Core.SettingsLoader: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Unable to create an instance of Docker.Backend.HyperV: Unable to create an instance of Docker.Core.SettingsLoader: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Unable to create an instance of Docker.Core.SettingsLoader: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Absolute path information is required.
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.Environment.InternalGetFolderPath(SpecialFolder folder, SpecialFolderOption option, Boolean suppressSecurityChecks)
   at Docker.Core.Paths.get_LocalRoamingApplicationData()
   at Docker.Core.Paths.get_SettingsJson()
   at Docker.Core.SettingsLoader..ctor(IEnterpriseConfigurationFileLoader configurationFileLoader, IChannel channel, ISettingsRegistry settingsRegistry)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth)
   --- End of inner exception stack trace ---
   at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth)
   at Docker.Core.Di.Singletons.Get(Type type, Int32 depth)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth)
   --- End of inner exception stack trace ---
   at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth)
   at Docker.Core.Di.Singletons.Get(Type type, Int32 depth)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth)
   --- End of inner exception stack trace ---
   at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth)
   at Docker.Core.Di.Singletons.Get(Type type, Int32 depth)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth)
   --- End of inner exception stack trace ---
   at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth)
   at Docker.Core.Di.Singletons.Get(Type type, Int32 depth)
   at Docker.Core.Di.Singletons.Get[T]()
   at Docker.Service.DockerService.DoRun()
```

  - Windows Version: Windows 10 Enterprise 18363.778. 
  - Docker Desktop Version: 2.2.0.5 (43884)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by thomasrosted** [comment]
It turned out that the `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\User Shell Folders\AppData key` for my `Local System/SYSTEM` user which is used to run the Docker Desktop Service was not set. Why that was, I have no idea, but adding a value of `%USERPROFILE%\AppData\Roaming` to that key (required elevating/impersonating via `nircmd.exe`) fixed the problem, and it is not possible to run the Docker Desktop application.
