### ISSUE TITLE
Docker Desktop is not running with linux containers

### ISSUE THREAD

**Issue by anisghossain** [docker/for-win#6573]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: C89EE6FD-D81B-4C33-ACFB-58932D55FF60/20200506223157

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by btulasiramreddy** [comment]
Here is the error msg for this

Error  ] Unable to start Hyper-V VM: Microsoft.HyperV.PowerShell.VirtualizationException: 'DockerDesktopVM' failed to start. (Virtual machine ID 008F9A5E-2338-4F08-966A-27AA5DC03B11) ---> Microsoft.Virtualization.Client.Management.VirtualizationOperationFailedException: 'DockerDesktopVM' failed to start.
   at Microsoft.Virtualization.Client.Management.View.EndMethodReturnInternal(IVMTask task, VirtualizationOperation operation, Boolean affectedElementExpected)
   at Microsoft.Virtualization.Client.Management.VMComputerSystemBaseView.EndSetState(IVMTask setStateTask)
   at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.<>c__DisplayClass4_0`1.<ConvertActionToFunction>b__0(T x)
   at Microsoft.HyperV.PowerShell.ExtensionMethods.OperationWatcherExtensions.PerformOperationWithReturn[T](IOperationWatcher watcher, Func`1 startTaskMethod, Func`2 endTaskMethod, String taskDescription, VirtualizationObject targetObject)
   at Microsoft.HyperV.PowerShell.VirtualMachine.ChangeState(VirtualMachineAction action, IOperationWatcher operationWatcher)
   at Microsoft.HyperV.PowerShell.Commands.StartVM.ProcessOneOperand(VirtualMachine vm, IOperationWatcher operationWatcher)
   at Microsoft.HyperV.PowerShell.Commands.VirtualizationCmdlet`1.ProcessOperands(IList`1 operands, IOperationWatcher operationWatcher)
   --- End of inner exception stack trace ---
at Start-MobyLinuxVM, <No file>: line 688
at <ScriptBlock>, <No file>: line 811
[13:37:14.744][Linux             ][Error  ] Failed to start: Unable to start Hyper-V VM: 'DockerDesktopVM' failed to start. (Virtual machine ID 008F9A5E-2338-4F08-966A-27AA5DC03B11)
at Start-MobyLinuxVM, <No file>: line 688
at <ScriptBlock>, <No file>: line 811.
