### ISSUE TITLE
New edge installer fails with fileNotFound

### ISSUE THREAD

**Issue by willseward** [docker/for-win#663]
### Expected behavior

Installs new version

### Actual behavior

```
Could not find file 'C:\Program Files\Docker\Docker\installationmanifest.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at LightweightInstaller.UninstallWorkflow.<ProcessAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<HandleD4WPackage>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LightweightInstaller.InstallWorkflow.<ProcessAsync>d__18.MoveNext()
```

### Information

* Diagnostic Id: 43973942-FC86-4407-9BB3-DB80E6CB436C/2017-04-21_09-03-19
* Windows: 15042.0

**Comment by wiktor-k** [comment]
I had the same issue when docker started. This was a clean installation (as update failed for some other reason). Restarting it manually (no reset) worked... but for how long?!

I've observed that usually there is 80-90% chance of breaking something when I update Docker using the automatic updates (Docker cannot start, this error, Hyper-V error, volumes are not working), so I'm disabling automatic updates as managing Docker now takes more time than I save by actually using Docker...

**Comment by LarsWH** [comment]
I was also unable to reinstall Docker. I tried a number of PowerShell clean up scripts suggested by others, but without success. Finally I solved it through this registry fix:
https://success.docker.com/KBase/Docker.For.Win_-_Install_fails_on_installationmanifest.json

**Comment by rn** [comment]
closing old issues
