### ISSUE TITLE
System.InvalidOperationException: Failed to deploy distro docker-desktop 

### ISSUE THREAD

**Issue by rsdmike** [docker/for-win#6640]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E707C486-C1D9-47D8-9EB8-D285CDEA4902/20200512030235

### Expected behavior
Docker Desktop boots on startup
### Actual behavior
Docker fails to start with:
```
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\Mike\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0xffffffff


 stderr: 
   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__16.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```
### Information

  - Windows Version:  Version (2004)10.0.19041 Build 19041.208
  - Docker Desktop Version: 2.3.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Unsure if the following will reproduce..

  1. Ensure WSL2 is enabled
  2. Install Docker-Desktop - say yes to using WSL2 when prompted
  3. Reboot

Other info  - I have Ubuntu 20.04 LTS installed from the windows store, i use Windows Sandbox as well.

**Comment by simonferquel** [comment]
@benhillis the 0xffffffff error on deploying a distro is still the wsl service crash related to HNS and port 43 right ?

@rsdmike By any chance, have you run Docker Desktop in Windows containers previously ?

**Comment by Kilsgaard** [comment]
I have joust updated my 3 developer computers to Win10(2004) and WSL2
And is now getting the exact same error on all 3 computers.
two have been set to Windows containers but the last have only had linux containers enabled..

**Comment by simonferquel** [comment]
do you see this when trying to upgrade a wsl1 distro to wsl2 as well ? (like `wsl --set-version Ubuntu 2`)

**Comment by Kilsgaard** [comment]
Yes I do
PS C:\Users\GKi> wsl -l -v
  NAME      STATE           VERSION
* WLinux    Stopped         1
  Ubuntu    Running         1
PS C:\Users\GKi> wsl --set-version Ubuntu 2
Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
Error: 0xffffffff

**Comment by simonferquel** [comment]
Ok so the good news (for me) is that the issue does not come from Docker Desktop!
I think the issue is related to processes listening on port 53 (dns). Can you check if some process does that, then restart lxss service and try again?

**Comment by benhillis** [comment]
Correct, the -1 error indicates an issue creating the virtual network.

**Comment by Kilsgaard** [comment]
Yes netstat says that I have a listening service on port 53, proberly the company antivirus..
is there a way to get arround this?

**Comment by rsdmike** [comment]
@simonferquel Only Linux containers have been configured on this machine, haven't used Windows Containers. This problem seems intermittent, sometimes a reboot fixes it, other times it doesnt. I don't see anything listening on port 53 for me. I upgraded to distro wsl2, and will keep ya posted if it happens again.

**Comment by Kilsgaard** [comment]
I have found the problem, got permission to remove our corporate antivirus from one of my developer machines, and now I can run WSL 2
It looks like (heimdalsecurity.com) is capturing port 53 when it is installed :-(

**Comment by rsdmike** [comment]
@simonferquel I am still seeing this for the WSL2 upgraded distro of Ubuntu 20.04 LTS :(

**Comment by simonferquel** [comment]
@rsdmike what about port 53 ? can you check with netstat ?

**Comment by rsdmike** [comment]
![image](https://user-images.githubusercontent.com/22204562/82474227-9506db00-9a7f-11ea-9944-c0bd44bca510.png)

**Comment by NickHeap2** [comment]
I had the same problem with jhi_service.exe
![image](https://user-images.githubusercontent.com/42422453/87163447-44fa0700-c2bf-11ea-97a2-3f57e5b5c1b2.png)
This was the Intel(R) Dynamic Application Loader Host Interface service.
Everything worked once I stopped that service.

**Comment by daserge** [comment]
For me it was Hyper-V - everything is working fine after disabling it.

**Comment by sapinder** [comment]
Disabling Hyper-V also helped me.

**Comment by pn141** [comment]
I had a dns proxy called "Acrylic" that was listening on port 53. Docker-desktop started fine after I removed Acrylic

**Comment by KiLLeRRaT** [comment]
I don't understand all the people that are 'okay' with disabling Hyper-V.  I think it's a desparate and very poor solution to the problem.  What about the people using Hyper-V?

Any tips... I do a `netstat -aon | findstr ":53"` and see that there is a couple of hits:

```
  TCP    192.168.64.1:53        0.0.0.0:0              LISTENING       45392
  UDP    0.0.0.0:53             *:*                                    31272
  UDP    0.0.0.0:53             *:*                                    31272
  UDP    192.168.64.1:53        *:*                                    45392
```

I tried killing these suckers, but doesn't help me. It looks like it's the UDP Port 53 on on PID 31272, which for me is Internet Connection Sharing.  This service is running for some reason.  I don't explicitely use ICS, but it's getting enabled because of _something_.  I tried stopping it, access denied.  I tried setting startup to disabled, but in the Windows Event Viewer it is noted that it was automatically set back to _Manual (triggered)_ again.

Any other ideas?

**Futher findings:**
After messing a LOT with killing and stopping/starting services (WITHOUT REBOOTING) suddenly docker now started and is running.  No idea what I did or how it suddenly started.

**Comment by b1kjsh** [comment]
I had the same issue and after switching back and forth from windows containers to linux containers and rebooting it magically started working. My guess is that it's an issue with other app's using that port before docker can use it during the login sequence. but so far it has been unreliable on win 2004.

**Comment by semenmiroshnichenko** [comment]
I had the same issue on my Win 10 machine. Yesterday I switched to windows containers and then back to linux containers, then I shut down my pc for the night, and today I faced this problem. Killing dockerd.exe solves the problem.

**Comment by JanOonk** [comment]
I keep reading above people disabling Hyper-V, how is it possible then to have Docker Desktop for Windows running without Hyper-V?? When I disable it in the BIOS I get an error when starting Docker Desktop.
![image](https://user-images.githubusercontent.com/13236774/92246185-b15f4400-eec5-11ea-9582-d79a2f56885b.png)

**Comment by Bacon-Fixation** [comment]
i believe they are referring to Hyper-V as in the windows feature  type "windows features in start and look for Hyper -V

**Comment by Bacon-Fixation** [comment]
but for me https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel  updating WSL 2 Linux kernal solved my issue

**Comment by briandesousa** [comment]
> but for me https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel updating WSL 2 Linux kernal solved my issue
> mine started with a windows preview update

This worked for me as well. Before installing the WSL2 Linux Kernel update, I had tried purging all Docker data, uninstalling and reinstalling Docker, disabling and re-enabling the WSL feature but nothing resolved the error. After installing the WSL update, Docker Desktop starts up just like before. 

I can't be certain but I believe this also started happening after a Windows preview update on the Dev channel... potentially version 2004, OS build 20206.1000

**Comment by delta1186** [comment]
> I had a dns proxy called "Acrylic" that was listening on port 53. Docker-desktop started fine after I removed Acrylic

I this my issue too.  However, Acrylic is being used by my web dev tool to self host web apps for testing.  I am going to play around with Acrylic config and see if I can get something working.

**Comment by FWest98** [comment]
> 
> 
> I don't understand all the people that are 'okay' with disabling Hyper-V. I think it's a desparate and very poor solution to the problem. What about the people using Hyper-V?
>  [.....]
> I tried killing these suckers, but doesn't help me. It looks like it's the UDP Port 53 on on PID 31272, which for me is Internet Connection Sharing. This service is running for some reason. I don't explicitely use ICS, but it's getting enabled because of _something_. I tried stopping it, access denied. I tried setting startup to disabled, but in the Windows Event Viewer it is noted that it was automatically set back to _Manual (triggered)_ again.
> 

I experienced exactly this problem just now, and I rely on Hyper-V for other stuff in my setup so disabling was not an option for me. I looked through my event log and saw specific error messages that led me to [this post](https://borncity.com/win/2019/06/18/windows-10-v1903-ip-resolution-bug-in-hyper-v-switch/) where the suggestion was to enable the "Windows Sandbox" feature. After a reboot, I could finally use Docker again.

**Comment by RaulRG** [comment]
I am having the same problem too. After installation docker didn't work due to a corrupted config file (directly after the installation!). I deleted the file, it got recreated and worked for some days. Then it started failing with the same callstack (error in Docker.Engines.WSL2.WSL2Provisioning). My experience with the WSL2-based docker desktop is horrible. I think it worked 3 out of 14 days :-(

**Comment by asforza** [comment]
disconnected the ethernet cable, instantly the process dnscrypt-proxy.exe (Cisco) got killed and I could  and install Docker (having previously installed wsl 2).
Plugged ethernet back-in and could stop and start docker w/o problem.
It must have free port 53.

**Comment by lesmo** [comment]
I've faced this problem too in an almost-new Windows 10 Pro install, just switched "back" from macOS. In the past (years ago), I used to use [Acrylic DNS](https://sourceforge.net/projects/acrylic/) which is a DNS Proxy that will naturally listen on port 53 to do fancy things like serving my localhost projects on `myproject.local` just like dnsmasq does on *nix systems. **Uninstalling it fixed it for me**.

This means that using WSL2 is incompatible with using any kind of DNS Server, which is something you may want to keep in mind and perhaps may need to be included in the documentation while Microsoft addresses this problem in WSL. This is not a Docker issue, it's more of a problem from WSL. [There is an issue](https://github.com/microsoft/WSL/issues/5092) discussing the problem.

**Comment by ronrat** [comment]
I was encountering the `0xffffffff` error both during Docker startup and when running `wsl --set-version Ubuntu 2`. Running `netstat -aon | findstr ":53"` returned the following:

```
  TCP    127.0.0.1:53           0.0.0.0:0              LISTENING       23820
  TCP    127.0.0.1:53           127.0.0.1:58060        TIME_WAIT       0
  TCP    127.0.0.1:53           127.0.0.1:60175        TIME_WAIT       0
  UDP    0.0.0.0:53             *:*                                    12976
  UDP    127.0.0.1:53           *:*                                    23820
```

I disconnected from my VPN and then disconnected completely from the local network (pulled CAT5 from NIC and disabled WiFi). I tried the WSL conversion at that point and it still didn't work. I plugged the network cable back in and that time the WSL conversion worked. Started up Docker for Window successfully.

**Comment by BasixKOR** [comment]
Tried killing a process using :53 port and it seems like it's working. Have no idea why this works tho.

**Comment by Jim-Johnson-Programmer** [comment]
Windows 10 took WSL2 upgrade.  Docker worked after reinstalling.  Rebooted machine...docker crashes on startup.  Trying to learn from you guys on what to do.

I noticed that I had to click to have my Kali Linux prompt up from my start menu.  Once I had this, docker didn't crash anymore.  This makes sense since I am not set for Windows containers right now.

**Comment by Mary1910** [comment]
Hello, 
this worked for me 
https://mariateresamatulli.medium.com/system-invalidoperationexception-failed-to-deploy-distro-docker-desktop-to-c-users-appdata-loc-8d976e3755d9

note. This is my first comment on Git. If the link above somehow violates the rules of the community, I'll remove it :)

**Comment by BeniKovac** [comment]
Turining off my antivirus worked for me on Windows 10 Home.

**Comment by markusjohnsson** [comment]
I'm running Windows in Parallels on macos and I had to "Enable nested virtualization" in the Windows vm Configuration > Hardware >  CPU & Memory > Advanced Settings.

**Comment by artempogosian** [comment]
I had the same issue and was able to solve it by:

- enabling Intel Virtualization Technology in my BIOS
- allowing NUMA spanning in Hyper-V settings
- reinstalling Docker with WSL-2 option ticked and installing WSL2 Linux kernel update package for x64 machines

**Comment by Juni4567** [comment]
in my case, I just uninstalled the WSL subsystem for linux from control panel and docker started working.

**Comment by JakubKoralewski** [comment]
Turning off a VPN while Docker is starting worked for me.

**Comment by jonorozcoc** [comment]
For everyone using Acrylic DNS proxy or related software will have this error. The solution is uninstalling it

**Comment by dvasdekis** [comment]
Private Internet Access VPN was the problem for me. I quit it, and Docker worked again.

**Comment by chenmin201** [comment]
I was having this exact problem. After killing a DNS proxy (Acrylic DNS Proxy) Docker starts to work! I think Docker WSL2 backend runs on port 53. If that port is used by any other process Docker won't run.

**Comment by sivasunken** [comment]
> Private Internet Access VPN was the problem for me. I quit it, and Docker worked again.

Thanks so much... I have been struggling with this issue and didnt realize that if docker started before PIA it would work

**Comment by vvnc** [comment]
restart the machine helped me

**Comment by parvex** [comment]
If other methods didn't work I believe it could be due to some broken network settings from vmware or other software. For me this method worked:

1. switching off windows subsystem for linux feature and virtual machine platform
2. restart
3. clean registry with CCleaner
4. switch on subsystem and platform
5. restart

**Comment by MonsieurPatate** [comment]
Only deleting `%USERPROFILE%/.wslconfig` solved the problem for me
