### ISSUE TITLE
Cannot create Docker container from fresh install on Windows (Error: Unable to start terminal process: CreateProcess failed)

### ISSUE THREAD

**Issue by markusgiesen** [docker/for-win#6643]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 82B0AC70-398D-4C0C-98C2-2815626C1E44/20200512065553

### Expected behavior
Fresh Docker install on a Win10 machine, never ran Docker on it.
When using Visual Studio Code and trying to open a repo in a new remote container I should just see the Docker container open and running

### Actual behavior
When using Visual Studio Code and trying to open a repo in a new remote container I am getting an error message "Error: Unable to start terminal process: CreateProcess failed"

### Information

  - Windows Version: 10 Pro, 10.0.17763 Build 17763 - updated and retried with Version 10.0.18363 Build 18363
  - Docker Desktop Version: 2020-05-11 2.3.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: nope, a brick of a machine on my desk

### Steps to reproduce the behavior

  1. Install a fresh Docker onto Win 10 Pro
  2. Install fresh VS Code
 3. git clone a repo with a working linux Ubuntu 18.04 & Git container
4. Try and open repo in container
5. Watch it burn :(

Full error message
```
Error: Unable to start terminal process: CreateProcess failed
        at new WindowsPtyAgent (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsPtyAgent.js:77:36)
        at new WindowsTerminal (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\windowsTerminal.js:50:24)
        at Object.spawn (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\node-pty\lib\index.js:28:12)
        at c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:5211
        at async Object.t.runCommand (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:8512)
        at async c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:118726
        at async Object.D [as cloneAndBuildRepository] (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:118585)
        at async Object.t.openDockerfileRepoDevContainer (c:\Users\user\.vscode\extensions\ms-vscode-remote.remote-containers-0.117.0\dist\extension.js:1:165567)
```
>

**Comment by cwaespi** [comment]
I am experiencing the same issue after a fresh installation of Docker Desktop 2.3.0.2. Previous working Version Docker Desktop 2.2.0.5.

**Comment by mat007** [comment]
Should this not be reported to VS Code?

**Comment by markusgiesen** [comment]
Nope, this is a Docker Desktop issue. I found a duplicate issue here:
https://github.com/microsoft/vscode-remote-release/issues/2975

Apparently the latest build has a bug. Removing Docker and installing an earlier version worked for me but there also seems to be another fix suggested in the thread above that users report resolved the issue for them.

**Comment by stephen-turner** [comment]
The comments by user @chrmarti in microsoft/vscode-remote-release#2975 show that the fix is on the Visual Studio side, and indeed they've already fixed it.

**Comment by monsdar** [comment]
And [this comment](https://github.com/microsoft/vscode-remote-release/issues/2975#issuecomment-627456260) contains a workaround for everyone who's still affected
