### ISSUE TITLE
Update to Docker Desktop Community 2.3.0.2 breaks docker-compose

### ISSUE THREAD

**Issue by Smasherr** [docker/for-win#6652]
I use docker-desktop with WSL2. After the latest update I cannot use docker-compose anymore. It throws the following exception:

```
$ docker-compose up -d
Pulling vault (vault:)...
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1077, in up
  File "compose/cli/main.py", line 1073, in up
  File "compose/project.py", line 548, in up
  File "compose/service.py", line 361, in ensure_image_exists
  File "compose/service.py", line 1250, in pull
  File "compose/progress_stream.py", line 102, in get_digest_from_pull
  File "compose/service.py", line 1215, in _do_pull
  File "site-packages/docker/api/image.py", line 396, in pull
  File "site-packages/docker/auth.py", line 48, in get_config_header
  File "site-packages/docker/auth.py", line 324, in resolve_authconfig
  File "site-packages/docker/auth.py", line 235, in resolve_authconfig
  File "site-packages/docker/auth.py", line 262, in _resolve_authconfig_credstore
  File "site-packages/docker/auth.py", line 287, in _get_store_instance
  File "site-packages/docker/credentials/store.py", line 25, in __init__
docker.credentials.errors.InitializationError: docker-credential-desktop.exe not installed or not available in PATH
[23260] Failed to execute script docker-compose
```

I deliberately don't have any windows paths on my `PATH` and that worked with the previous version of docker-desktop.

**Comment by simonferquel** [comment]
Hmm yes, we added support for universal `docker login` (login from windows and you can push/pull from your wsl distros). This requires the windows credential helper that we ship with docker desktop to be in you wsl distro PATH.
If you don't want to add a windows path to your wsl env, you can just copy (or symlink) it into a wsl directory

**Comment by Smasherr** [comment]
Thanks for your quick response, @simonferquel! I think this information might be useful to be found in the documentation.

**Comment by fvoncina** [comment]
For those, like me, that doesn't have the windows path in wsl2 here is the line for creating the symlink:
```bash
sudo  ln -s /mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-credential-desktop.exe /usr/bin/docker-credential-desktop.exe
```

**Comment by mbuffa** [comment]
It's not really helpful, but I'm encountering this exact error using the Ubuntu image available on the Windows Store. docker-credential-desktop.exe is in the path, .docker/config.json is there correctly set, and I haven't made huge changes to my distro apart from setting up development tools.

I just booted a Alpine through WSL and it worked immediately with the same settings. Will try to investigate.

**Comment by uxoof** [comment]
just try restart.

**Comment by matheussouza9** [comment]
After I tried the @fvoncina solution, I got the following error

```
Building app
Traceback (most recent call last):
  File "site-packages/docker/credentials/store.py", line 80, in _execute
  File "subprocess.py", line 411, in check_output
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['/usr/bin/docker-credential-desktop.exe', 'list']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 72, in main
  File "compose/cli/main.py", line 128, in perform_command
  File "compose/cli/main.py", line 1077, in up
  File "compose/cli/main.py", line 1073, in up
  File "compose/project.py", line 548, in up
  File "compose/service.py", line 367, in ensure_image_exists
  File "compose/service.py", line 1106, in build
  File "site-packages/docker/api/build.py", line 261, in build
  File "site-packages/docker/api/build.py", line 308, in _set_auth_headers
  File "site-packages/docker/auth.py", line 302, in get_all_credentials
  File "site-packages/docker/credentials/store.py", line 71, in list
  File "site-packages/docker/credentials/store.py", line 93, in _execute
docker.credentials.errors.StoreError: Credentials store docker-credential-desktop.exe exited with "error listing credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ''".
[17672] Failed to execute script docker-compose
```

But, I've added the `docker-credential-wincred.exe` to my `/usr/bin` as a symbolic link too.

`lrwxrwxrwx 1 root root 78 Jun 18 15:15 /usr/bin/docker-credential-wincred.exe -> '/mnt/c/Program Files/Docker/Docker/resources/bin/docker-credential-wincred.exe'*`

I can execute it normally.
```
$ docker-credential-wincred.exe version
0.6.3
```

**Comment by realmgic** [comment]
This still doesn't work for me - even after adding symlinks:

```
zohar@DESKTOP-B73HQJT:/tmp$ /usr/bin/docker-credential-desktop.exe list
error listing credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``
zohar@DESKTOP-B73HQJT:/tmp$ "docker-credential-wincred.exe" version
0.6.3
zohar@DESKTOP-B73HQJT:/tmp$ ls /usr/bin/do* -l
-rwxr-xr-x 1 root root      9017 Jun 19  2019 /usr/bin/do-release-upgrade
-rwxr-xr-x 1 root root  89221056 Mar 11 03:24 /usr/bin/docker
lrwxrwxrwx 1 root root        52 Jun 19 18:13 /usr/bin/docker-compose -> /wsl/docker-desktop/cli-tools/usr/bin/docker-compose
lrwxrwxrwx 1 root root        74 Jun 23 09:41 /usr/bin/docker-credential-desktop.exe -> '/c/Program Files/Docker/Docker/resources/bin/docker-credential-desktop.exe'
lrwxrwxrwx 1 root root        74 Jun 23 09:43 /usr/bin/docker-credential-wincred.exe -> '/c/Program Files/Docker/Docker/resources/bin/docker-credential-wincred.exe'
-rwxr-xr-x 1 root root    804408 Mar 11 03:24 /usr/bin/docker-init
-rwxr-xr-x 1 root root   3593848 Mar 11 03:24 /usr/bin/docker-proxy
-rwxr-xr-x 1 root root 104999776 Mar 11 03:24 /usr/bin/dockerd
```

**Comment by icetee** [comment]
I logged in Docker Desktop, and works.

**Comment by villasv** [comment]
I also disable Windows path as it makes the shell much slower. It think the Docker Desktop WSL2 integration should take care of adding docker-credential-desktop.exe the PATH instead of assuming it's there.

**Comment by mp051998** [comment]
> For those, like me, that doesn't have the windows path in wsl2 here is the line for creating the symlink:
> 
> ```shell
> sudo  ln -s /mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-credential-desktop.exe /usr/bin/docker-credential-desktop.exe
> ```

Thanks! This worked for me!

**Comment by PhilipSchmid** [comment]
Thanks @fvoncina and @matheussouza9! Your workarounds in combination with https://github.com/docker/compose/issues/7495#issuecomment-640301591 worked for me 👍.

**Comment by Hebilicious** [comment]
I had this issue on windows + wsl2 backend while trying to use `docker-compose: up -d`: 
` docker-credential-desktop.exe not installed or not available in PATH`

I did those 2 things : 
`sudo  ln -s /mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-credential-desktop.exe /usr/bin/docker-credential-desktop.exe`

In ~/.docker/config.json, change
{"credsStore":"desktop.exe"} to {"_credsStore":"desktop.exe"}

Then it started working
