### ISSUE TITLE
Can not switch to linux containers

### ISSUE THREAD

**Issue by Setkias** [docker/for-win#6711]
[20200514105005.zip](https://github.com/docker/for-win/files/4627868/20200514105005.zip)

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A18473E0-DF63-4FDF-91B1-773A9CB2969A/20200514110555

### Expected behavior
No error message when selecting "switch to linux containers..."

### Actual behavior
An error message when selecting "switch to linux containers..."

### Information

  - Windows Version: Windows 10 (build 1909)
  - Docker Desktop Version: 2.3.0.1 (44875)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No.

### Steps to reproduce the behavior

This is a fresh install on my windows system.

The error message is:

```
Docker.Core.HttpBadResponseException:
Unhandled exception: job failed with message: Kan DockerDesktopVM niet starten. (Virtuelemachine-id FF1B8676-66E0-46BF-9011-AE9DA3EB4A0C)
   at Docker.Core.Logging.ClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\ClientExceptionInterceptor.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<StartHyperVVMAsync>d__11.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
Original stacktrace:
   bij Docker.Backend.HyperVInfrastructure.HandleUpdatedJob(CIMConcreteJob updatedJob) in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:regel 800
   bij Docker.Backend.HyperVInfrastructure.<HandleMaybeAsyncJob>d__37.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:regel 740
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij Docker.Backend.HyperVInfrastructure.<StartVMAsync>d__29.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:regel 588
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Docker.Backend.HyperV.<StartAsync>d__7.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperV.cs:regel 101
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Docker.Backend.HttpAPI.HyperVAPIController.<StartAsync>d__8.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\HyperVAPIController.cs:regel 44
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

**Comment by Richard-Barrett** [comment]
Hi you need to have the WSL 2 Downloaded. 
https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

Occasionally you might even encounter this issue:

# Windows
Here is what worked for me:
If you want to do it on Windows I would do the following:
1. Uninstall Everything Related to Docker-Desktop in Control Panel and disable Hyper-V
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
2. If you are using Chocolatey you can uninstall all of that there too with `choco uninstall package` and disable Hyper-V https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
3. Restart your Machine and Enter BIOS Menu and Make sure you have Virtualization and/or Hyperthreading Enabled. 

Use this link to see how to get into BIOS: https://support.lenovo.com/us/en/solutions/ht500006
You may need to reset your BIOS to default (Note not all Machines Support Virtualization) 
4. Allow for normal boot to occur
5. Enable Hyper-V for Windows 10 
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
6. Run through the following in an elevated command prompt and allowing for administrative access by right-clicking on command prompt:
```
dism.exe /Online /Enable-Feature:Microsoft-Hyper-V /All
bcdedit /set hypervisorlaunchtype auto
```

7. Restart Your Computer One More Time
8. Boot up
9. You can go to Docker-Desktop or you can install it with Chocolatey
If you want to install it via website, I assume you know where to go. Get the Stable Version. 
10 (Option A). Install as normal via https://www.docker.com/products/docker-desktop
10 (Option B). Use Chocolatey: 
Open up powershell in elevated admin console and install chocolatey
```
Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
```
https://chocolatey.org/install

Then after you install it run:
```
choco install docker-desktop
```
Chocolatey Link: https://chocolatey.org/packages/docker-desktop#releasenotes
Docker Release Notes: https://docs.docker.com/docker-for-windows/release-notes/

Whatever you decide, you need to make sure 
1. Your System Supports Virtualization
2. You have that enabled in System BIOS
3. Makes sure you have downloaded the WSL 2 background: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

Hope this helps, I too have had so many problems with Docker-Desktop as of late.

**Comment by Setkias** [comment]
The WSL 2 route worked. Thanks.
