### ISSUE TITLE
docker prompted to switch to WSL2, then crashed

### ISSUE THREAD

**Issue by cjisndenial** [docker/for-win#6716]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Docker starts.
### Actual behavior
Docker crashes.
### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. Docker told me my version of windows supports WSL2 now and asked to switch, I said OK.  Note I am running Windows 10 Version 2004 (19041.264)
  2. Installed WSL2 per provided PS command
  3. Installed WSL2 latest kernel per provided link.
  4. Docker restarted and crashed.  Further attempts to restart result in same crash.

**Comment by cjisndenial** [comment]
Killed all docker services running in background.  Restarted docker again.  All is well.

**Comment by mat007** [comment]
Thanks for the report, did you happen to capture and upload diagnostics (Troubleshot window from the systray menu)?

**Comment by cjisndenial** [comment]
I submitted the diagnostics via the crash window docker popped up when it crashed.  That was Docker’s own crash report window.

On May 14, 2020, at 9:58 AM, Mathieu Champlon <notifications@github.com<mailto:notifications@github.com>> wrote:



Thanks for the report, did you happen to capture and upload diagnostics (Troubleshot window from the systray menu)?

**Comment by AntonLapounov** [comment]
I have also hit the issue with Docker failing to start with WSL2 on Windows 10 Version 2004. In my case the `docker-desktop` distro was stuck in the `Installing` state:
```
C:\>wsl -l -v
  NAME              STATE           VERSION
* Ubuntu            Running         2
  docker-desktop    Installing      2
```
That caused the following errors reported in the log file:
```
[17:49:53.845][SystrayNotifications][Info   ] Docker is starting
[17:49:53.849][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[17:49:53.852][LoggingMessageHandler][Info   ] [e49313de] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[17:49:54.036][WSL2Provisioning  ][Error  ] Failed to terminate distro: exit code: -1
 stdout: There is no distribution with the supplied name.


 stderr: 
[17:49:54.042][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[17:49:54.135][LinuxWSL2Engine   ][Info   ] Stopping engine
[17:49:54.232][MutagenProcess    ][Info   ] [forwarding] Looking for existing sessions
[17:49:54.232][MutagenProcess    ][Info   ] [forwarding] Session manager initialized
[17:49:54.232][MutagenProcess    ][Info   ] [sync] Looking for existing sessions
[17:49:54.232][MutagenProcess    ][Info   ] [sync] Session manager initialized
[17:49:54.262][LinuxWSL2Engine   ][Warning] Failed to send stop message to distro, will terminate abrubtly: 
[17:49:54.383][WSL2Provisioning  ][Error  ] Failed to terminate distro: exit code: -1
 stdout: There is no distribution with the supplied name.


 stderr: 
[17:49:54.384][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.UnstableState to state change sink
[17:49:54.384][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.UnstableState sent to state change sink
[17:49:54.384][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.UnstableState from LinuxWSL2
[17:49:54.385][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1589503794}
[17:49:54.385][SystrayNotifications][Info   ] Docker Desktop failed to stop
[17:49:54.392][LoggingMessageHandler][Info   ] [e49313de] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 539ms)
[17:49:54.406][Engines           ][Error  ] Start failed with Failed to terminate distro: exit code: -1
 stdout: There is no distribution with the supplied name.


 stderr: 
   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<TerminateDistroAsync>d__13.MoveNext() in C:\workspaces\edge-2.2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 119
```
The `wsl --unregister docker-desktop` command fixed the issue for me.
Diagnostics ID: C8CB4AE0-0A37-47AD-BEC4-BEEAC139DE8C/20200515005040

**Comment by simonferquel** [comment]
@AntonLapounov thanks for reporting this case. It might be very hard to reproduce though, but there are certainly things we can try to improve the experience.

**Comment by simonferquel** [comment]
In the logs I see Error: wslpath wslCLIDest: wslpath failed; stderr is "wslpath: C:\\Program Files\\Docker\\Docker\\resources\\wsl\\docker-wsl-cli.iso\n": exit status 1.
We have a fix for this one coming shortly, in the mean time, can you close docker desktop and try to run `wsl --shutdown` ? We have seen cases where for some reason wslpath utility is unreliable.
