### ISSUE TITLE
Docker for windows 2.3.0.2 fails to install / failed to install with Windows hyper-v feature on

### ISSUE THREAD

**Issue by Mierpo** [docker/for-win#6802]
Docker for windows 2.3.0.2 fails to install / failed to install. All previous versions have worked without issues.

Thrown error:

`
Call cancelled 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   at CommunityInstaller.EnableFeaturesAction.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()
`

### Expected behavior

Docker for windows should install correctly, when choosing "Windows hyper-v features ON"

### Actual behavior

Installation fails.

### Information

Windows version info: Windows 10 Pro, build 18362.
Installation fails only when attempting to install Windows Hyper-V feature. In this case the Windows feature is precisely what I want to install and I don't even need the Linux feature.

I've had multiple different versions of Docker-for-Windows installed without issues in my laptop before. The problems began after a recent windows update. First, docker no longer started, so I figured I could reset to factory defaults. Did not help. Then, I uninstalled docker and tried to install the latest version, but now the installation fails.

I also tried to install an older version, 2.2.0.5, but this also fails. As does an even older version, 2.2.0.3.

### Steps to reproduce the behavior

Try to install the latest Docker-for-Windows (2.3.0.2) through installer. Windows 10 Pro build 18362, BitLocker enabled.

**Comment by daqieq** [comment]
Having the same issue with Windows 10 Pro:
Version: 1903
Build: 18362.778

**Comment by jonathanccfeng** [comment]
Also experiencing this issue installing.

Win 10 Enterprise 1709
build 16299.1508

**Comment by marcosgouvea** [comment]
Same here
Win 10 Pro
build 19041.329

**Comment by pldiguanaman** [comment]
Same issue.
Win 10 Enterprise
1903 Build 18632.778

**Comment by alejandro5042** [comment]
Same issue. Win 10 Enterprise 20175.1000

**Comment by neoned** [comment]
Same issue
```
Edition	Windows 10 Pro Insider Preview
Version	2004
Installed on	‎7/‎30/‎2020
OS build	20180.1000
Experience	Windows Feature Experience Pack 120.19101.0.0
```
`Docker 2.3.0.4`

Can't install docker after its attempt to upgrade

**Comment by sabrsorensen** [comment]
Same issue. Win 10 Enterprise Insider Ver 2004 Build 20175.1000.

**Comment by linssendane** [comment]
Same issue, Win 10 Pro Insider Ver 2004 Build 20180.1000

**Comment by rahmatyanuar** [comment]
Same issue, Win 10 Pro Insider 2004 Build 20175

**Comment by Zac-dot** [comment]
Same issue, Win 10 Education Insider 2004 Build 20180

**Comment by linssendane** [comment]
I fixed it!

Spent hours trying to fix this, but I think the following did it for me:

I went to `Start > Windows Update Settings` then clicked `View optional updates`. There were a bunch of optional drivers from Intel available that I installed.

After rebooting, I opened the Docker 2.3.0.4 installer and *un-selected* `Enable WSL 2 Windows features`. This was already the case as I did have a working installation of docker before all this.

Extra notes:
The installation fails for me with the `Enable WSL 2 Windows features` option enabled. Also, this option didn't appear for me before updating my drivers.

**Comment by Zac-dot** [comment]
@linssendane Yeah, for some reason the installer attempts to enable WSL 2 Windows Features even though they are enabled (so it fails). Got it working once more.

**Comment by pldiguanaman** [comment]
I could install by unchecking that option but then when I try to switch from Linux to Windows containers it throws an error.

**Comment by aminnaggar** [comment]
exact same as @pldiguanaman . And I'm not able to `docker pull mongo:2.3` or any other image for that matter.

This is what I get when I try to install with WSL2 enabled

```
  at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   at CommunityInstaller.EnableFeaturesAction.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__27.MoveNext()
```

**Comment by rosensama** [comment]
Getting the same trying to install Docker Desktop 2.4.0.0.  No prior Docker installation.  WSL 2 is enabled.

**Installation Failed**
```
Call cancelled 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   at CommunityInstaller.EnableFeaturesAction.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__27.MoveNext()
```
