### ISSUE TITLE
Unable to switch to Docker Desktop Linux Containers from Windows 10 machine. Timeout happens.

### ISSUE THREAD

**Issue by somnath1000** [docker/for-win#6821]
My Issue : 
**I have installed docker Desktop in my Win-10 machine.
Docker failed to start with Linux containers.
Switched to Windows container.
Docker starts fine and running fine. Able to run hello-world image.
Switching back to Linux Containers from Windows 10 machine. 
Timeput happens.
Docker fails to start.**

  - [ ] I have tried with the latest version of my channel = Stable
  - [ ] I have uploaded Diagnostics : YES
  - Diagnostics ID: `A023D8AA-F040-4D77-A6CB-7B4EBD41519E/20200521100050`

### Information
```
  - Is it reproducible?  : Yes everytime
  - Is the problem new? : No
  - Did the problem appear with an update? : Installed latest version of docker desktop from docker hub.
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
  - Windows Version:  Windows 10 Enterprise -1909 - 
  - Docker Desktop Version: 2.3.0.2 (45183)
  - Docker engine : 19.03.8
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:  No
```

On windows container everything is running fine. Able to run hello-world image successfully.

**docker version :** 

```
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.24)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:37:20 2020
  OS/Arch:          windows/amd64
  Experimental:     false
```

**After switching to Linux container it crashes.
Docker version shows this :**

```
PS C:\WINDOWS\system32> docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
PS C:\WINDOWS\system32>
```

**I have hyper-v enabled.
I have windows hypervisor platform enabled.**

### Steps to reproduce the behavior
```
Install Docker Desktop.
Docker service fails to start.
Switch to windows containers.
Docker starts.
Switch back to Linux containers, it fails. 
Docker crashes.
```

**Crash Log :**

```
Timed out while wait for Docker service to be ready
   at Docker.LinuxkitDaemonStartup.<StartAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\LinuxkitDaemonStartup.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

**Docker Logs last few lines :**

```
[15:30:49.367][ApiProxy          ][Info   ] Killing existing com.docker.proxy with PID 8856
[15:30:49.393][VpnKit            ][Info   ] Killing existing vpnkit with PID 11828
[15:30:49.407][VpnKitBridge      ][Info   ] Killing existing vpnkit-bridge with PID 14904
[15:30:49.416][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[15:30:49.416][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[15:30:49.416][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxHyperV
[15:30:49.427][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1590055249}
[15:30:49.427][SystrayNotifications][Error  ] Timed out while wait for Docker service to be ready
```

**Comment by somnath1000** [comment]
For the first time itself after installing docker desktop with Linux container is not able to run the docker.
Somehow I can manage to switch to Windows Container.  But again switching back to Linux container the same issue pops up.

**Comment by somnath1000** [comment]
Okk, I am able to resolve it.

Here are the steps I have taken :

```
1. I have windows hypervisor platform disabled.
2. I uninstalled other minikube and google cloud sdk which were present in my machine with multiple kubectl service, though they were not pointed in enviornment variables.
3. Uninstalled docker desktop.
4. Removed docker folders from Program Files, App Data, and Program data.
5. Restarted my machine
6. Installed docker for desktop.
7. Docker services started fine with Linux containers and I am able to run containers.
```

Only thing I did not do yet is to check the switch to Windows containers and  again switch back to Linux. As I have much work left to be done. I will test this later on and share my experience.
