### ISSUE TITLE
Docker restart resulted in crash

### ISSUE THREAD

**Issue by ankitbko** [docker/for-win#6873]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D6B43B7E-DD21-4810-8C30-2E9F20A12946/20200526043636

### Expected behavior
Docker should restart

### Actual behavior
Docker Crashed.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Not able to reproduce. Quitting docker and starting again worked.
  - Is the problem new? Faced it first time
  - Did the problem appear with an update? No idea

  - Windows Version: 10.0.19041 N/A Build 19041.264
  - Docker Desktop Version: 2.3.0.2 (45183)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Faced with issue #4526 after host machine slept for the night. To solve it, right clicked on docker icon in task bar -> restart
  2. Docker crashed
```csharp
Docker.Core.DockerException:
Failed to start
   at Docker.LinuxkitDaemonStartup.<StartAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\LinuxkitDaemonStartup.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<RestartAsync>d__29.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 274

```

**Comment by oad-sindhoo** [comment]
I am also facing the exact issue.

`Version: 2.3.2.1 (46329)
Channel: edge
Sha1: 7c29be886de7f844af3095cf3799b442d4e48c39
Started on: 2020/07/08 20:00:03.845
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 1803
Build: 17134
BuildLabName: 17134.1.amd64fre.rs4_release.180410-1804
File: C:\Users\Sindho Oad\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[20:00:04.118][GUI               ][Info   ] Starting...
[20:00:04.309][ComponentVersions ][Info   ] Edition community
[20:00:04.321][ComponentVersions ][Info   ] Edition community
[20:00:05.283][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[20:00:05.322][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[20:00:05.326][SegmentApi        ][Info   ] Usage statistic: Identify
[20:00:05.626][SegmentApi        ][Info   ] Usage statistic: appLaunched
[20:00:08.523][ApplicationTemplatesTracking][Info   ] Cannot list templates
[20:00:08.525][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[20:00:08.527][SegmentApi        ][Info   ] Usage statistic: heartbeat
[20:00:08.657][LoggingMessageHandler][Info   ] [e51aa514] <BackendAPIClient start> GET http://backend/version
[20:00:08.712][LoggingMessageHandler][Info   ] [e51aa514] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 52ms)
[20:00:09.509][LoggingMessageHandler][Info   ] [9f2e125a] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[20:00:09.941][LoggingMessageHandler][Info   ] [9f2e125a] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 432ms)
[20:00:09.955][LoggingMessageHandler][Info   ] [497868d5] <BackendAPIClient start> POST http://backend/migrate/app
[20:00:09.959][LoggingMessageHandler][Info   ] [497868d5] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 4ms)
[20:00:09.974][Engines           ][Debug  ] Starting
[20:00:10.081][LoggingMessageHandler][Info   ] [a63c298e] <BackendAPIClient start> POST http://backend/versionpack/enable
[20:00:10.248][LoggingMessageHandler][Info   ] [a63c298e] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 166ms)
[20:00:10.616][LoggingMessageHandler][Info   ] [5d3ee903] <BackendAPIClient start> POST http://backend/cloudcli/toggle
[20:00:10.625][LoggingMessageHandler][Info   ] [5d3ee903] <BackendAPIClient end> POST http://backend/cloudcli/toggle -> 204 NoContent (took 9ms)
[20:00:10.715][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[20:00:10.783][GoBackendProcess  ][Info   ] Started
[20:00:10.809][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[20:00:10.809][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[20:00:10.824][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxHyperV
[20:00:10.839][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1594220410}
[20:00:10.842][SystrayNotifications][Info   ] Docker is starting
[20:00:10.852][LoggingMessageHandler][Info   ] [b2133527] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[20:00:11.185][LoggingMessageHandler][Info   ] [b2133527] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 332ms)
[20:00:11.191][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[20:00:11.197][LoggingMessageHandler][Info   ] [3e1d2fe7] <BackendAPIClient start> POST http://backend/hyperv/stop
[20:00:11.932][Updater           ][Info   ] Check for update process exited with 4294967295
[20:00:13.846][LoggingMessageHandler][Info   ] [3e1d2fe7] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 2648ms)
[20:00:13.930][VpnKitBridge      ][Info   ] Starting C:\Program Files\Docker\Docker\resources\vpnkit-bridge.exe --addr listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3 host
[20:00:14.040][VpnKitBridge      ][Info   ] Started
[20:00:14.596][LoggingMessageHandler][Info   ] [65157e33] <Server start> GET http://unix/versions
[20:00:14.883][LoggingMessageHandler][Info   ] [65157e33] <Server end> GET http://unix/versions -> 200 OK (took 287ms)
[20:00:16.896][VpnKitBridge      ][Info   ] listening on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[20:00:16.896][VpnKitBridge      ][Info   ] waiting for connection on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[20:00:17.869][IsoConfig         ][Info   ] Generating CA Cert Bundle
[20:00:18.004][IsoConfig         ][Info   ] CA Cert Bundle Generated
[20:00:18.008][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[20:00:18.011][GoBackendProcess  ][Info   ] started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl
[20:00:18.020][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[20:00:18.024][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[20:00:18.024][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[20:00:18.024][GoBackendProcess  ][Info   ] enabling filesystem caching
[20:00:18.024][GoBackendProcess  ][Info   ] filesystem exports are:  (2)
[20:00:18.027][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\docker_cli
[20:00:18.027][GoBackendProcess  ][Info   ] volume control server listening on \\\\.\\pipe\\dockerVolume
[20:00:18.037][GoBackendProcess  ][Info   ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[20:00:18.037][GoBackendProcess  ][Info   ] file ownership will be determined by the calling user (\"fake owner\" mode)
[20:00:18.037][GoBackendProcess  ][Info   ] using mfsymlinks
[20:00:24.198][LoggingMessageHandler][Info   ] [ddefdee9] <BackendAPIClient start> POST http://backend/hyperv/create
[20:00:30.478][LoggingMessageHandler][Info   ] [ddefdee9] <BackendAPIClient end> POST http://backend/hyperv/create -> 204 NoContent (took 6280ms)
[20:00:30.493][VpnKit            ][Info   ] Starting C:\Program Files\Docker\Docker\resources\vpnkit.exe --ethernet \\.\pipe\dockerVpnkit --hosts "" --http "C:\Users\Sindho Oad\AppData\Roaming\Docker\http_proxy.json" --gateway-forwards "C:\Users\Sindho Oad\AppData\Roaming\Docker\gateway_forwards.json" --diagnostics \\.\pipe\dockerVpnKitDiagnostics --host-names host.docker.internal,docker.for.win.host.internal,docker.for.win.localhost --gateway-names gateway.docker.internal,docker.for.win.gateway.internal,docker.for.win.http.internal --listen-backlog 32 --gateway-ip 192.168.65.1 --host-ip 192.168.65.2 --lowest-ip 192.168.65.3 --highest-ip 192.168.65.14
[20:00:30.552][VpnKit            ][Info   ] Started
[20:00:30.558][DockerCliAPIServer][Info   ] Starting C:\Program Files\Docker\Docker\resources\docker.exe serve --address npipe:////./pipe/dockerCliApi
[20:00:30.603][DockerCliAPIServer][Info   ] Started
[20:00:30.626][LoggingMessageHandler][Info   ] [23b0df23] <BackendAPIClient start> POST http://backend/hyperv/start
[20:00:30.907][VpnKit            ][Info   ] vpnkit.exe: Setting handler to ignore all SIGPIPE signals
[20:00:30.907][VpnKit            ][Info   ] vpnkit.exe: Version is 218f01482560cba2fa863f9ad872ad51d1e717fc
[20:00:30.908][VpnKit            ][Info   ] vpnkit.exe: System SOMAXCONN is 2147483647
[20:00:30.908][VpnKit            ][Info   ] vpnkit.exe: Will use a listen backlog of 32
[20:00:30.908][VpnKit            ][Info   ] vpnkit.exe: No periodic Gc.compact enabled
[20:00:30.908][VpnKit            ][Error  ] vpnkit.exe: Starting to watch : EINVAL
[20:00:30.908][VpnKit            ][Error  ] vpnkit.exe: Failed to watch hosts file : invalid argument
[20:00:30.908][VpnKit            ][Warning] vpnkit.exe: There is no database: using hardcoded network configuration values
[20:00:30.908][VpnKit            ][Info   ] vpnkit.exe: DNS server configured with no builtin DNS names; everything will be forwarded
[20:00:30.908][VpnKit            ][Info   ] vpnkit.exe: 2 upstream DNS servers are configured
[20:00:30.908][VpnKit            ][Error  ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
[20:00:30.909][VpnKit            ][Info   ] vpnkit.exe: Disabling transparent HTTP redirection
[20:00:30.909][VpnKit            ][Info   ] vpnkit.exe: Updating resolvers to use host resolver
[20:00:30.909][VpnKit            ][Info   ] vpnkit.exe: Secure random number generator is available
[20:00:30.909][VpnKit            ][Info   ] vpnkit.exe: Add(3): DNS configuration changed to: use host resolver
[20:00:30.909][VpnKit            ][Info   ] vpnkit.exe: DNS server configured with builtin DNS names [ gateway.docker.internal -> 192.168.65.1, docker.for.win.gateway.internal -> 192.168.65.1, docker.for.win.http.internal -> 192.168.65.1, host.docker.internal -> 192.168.65.2, docker.for.win.host.internal -> 192.168.65.2, docker.for.win.localhost -> 192.168.65.2, vm.internal -> 192.168.65.3 ]
[20:00:30.909][VpnKit            ][Info   ] vpnkit.exe: Will use the host's DNS resolver
[20:00:30.910][VpnKit            ][Info   ] vpnkit.exe: Transparent HTTP redirection configuration file C:\Users\Sindho Oad\AppData\Roaming\Docker\http_proxy.json has changed
[20:00:30.910][VpnKit            ][Info   ] vpnkit.exe: Reading transparent HTTP redirection from C:\Users\Sindho Oad\AppData\Roaming\Docker\http_proxy.json
[20:00:30.910][VpnKit            ][Info   ] vpnkit.exe: Watching transparent HTTP redirection configuration file C:\Users\Sindho Oad\AppData\Roaming\Docker\http_proxy.json for changes
[20:00:30.910][VpnKit            ][Info   ] vpnkit.exe: New Gateway forward configuration: []
[20:00:30.910][VpnKit            ][Info   ] vpnkit.exe: Gateway forwards file C:\Users\Sindho Oad\AppData\Roaming\Docker\gateway_forwards.json has changed
[20:00:30.910][VpnKit            ][Info   ] vpnkit.exe: Reading gateway forwards file from C:\Users\Sindho Oad\AppData\Roaming\Docker\gateway_forwards.json
[20:00:30.910][VpnKit            ][Info   ] vpnkit.exe: Watching gateway forwards file C:\Users\Sindho Oad\AppData\Roaming\Docker\gateway_forwards.json for changes
[20:00:30.910][VpnKit            ][Info   ] vpnkit.exe: Configuration server_macaddr = f6:16:36:bc:f9:c6; max_connection = None; dns_path = None; dns = ; resolver = Host; domain = None; allowed_bind_addresses = 0.0.0.0; gateway_ip = 192.168.65.1; host_ip = 192.168.65.2; lowest_ip = 192.168.65.3; highest_ip = 192.168.65.14; dhcp_json_path = None; dhcp_configuration = None; mtu = 1500; http_intercept = None; http_intercept_path = C:\Users\Sindho Oad\AppData\Roaming\Docker\http_proxy.json; port_max_idle_time = 300; host_names = host.docker.internal, docker.for.win.host.internal, docker.for.win.localhost; gateway_names = gateway.docker.internal, docker.for.win.gateway.internal, docker.for.win.http.internal; vm_names = vm.internal; udpv4_forwards = []; tcpv4_forwards = []; gateway_forwards_path = C:\Users\Sindho Oad\AppData\Roaming\Docker\gateway_forwards.json; pcap_snaplen = 128
[20:00:30.910][VpnKit            ][Error  ] vpnkit.exe: While watching C:\Users\Sindho Oad\AppData\Roaming\Docker\gateway_forwards.json: ENOENT
[20:00:30.910][VpnKit            ][Error  ] vpnkit.exe: Failed to read gateway forwards from C:\Users\Sindho Oad\AppData\Roaming\Docker\gateway_forwards.json: reading C:\Users\Sindho Oad\AppData\Roaming\Docker\gateway_forwards.json: No such file or directory.
[20:00:30.910][VpnKit            ][Info   ] vpnkit.exe: New Gateway forward configuration: []
[20:00:30.911][VpnKit            ][Info   ] vpnkit.exe: Updating transparent HTTP redirection: {
[20:00:30.911][VpnKit            ][Info   ]   "exclude": "",
[20:00:30.911][VpnKit            ][Info   ]   "transparent_http_ports": [
[20:00:30.911][VpnKit            ][Info   ]     80
[20:00:30.911][VpnKit            ][Info   ]   ],
[20:00:30.911][VpnKit            ][Info   ]   "transparent_https_ports": [
[20:00:30.911][VpnKit            ][Info   ]     443
[20:00:30.911][VpnKit            ][Info   ]   ]
[20:00:30.911][VpnKit            ][Info   ] }
[20:00:33.480][DockerCliAPIServer][Info   ] serving daemon API" address="npipe:////./pipe/dockerCliApi
[20:00:34.484][LoggingMessageHandler][Info   ] [12063758] <Server start> POST http://unix/usage/cli
[20:00:34.641][LoggingMessageHandler][Info   ] [12063758] <Server end> POST http://unix/usage/cli -> 200 OK (took 157ms)
[20:00:34.644][GoBackendProcess  ][Info   ] cli: POST /usage 200 \"Go-http-client/1.1\" \"\
[20:00:35.112][LoggingMessageHandler][Info   ] [23b0df23] <BackendAPIClient end> POST http://backend/hyperv/start -> 500 InternalServerError (took 4485ms)
[20:00:35.149][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[20:00:35.150][LoggingMessageHandler][Info   ] [9b54daf6] <BackendAPIClient start> POST http://backend/hyperv/stop
[20:00:37.063][LoggingMessageHandler][Info   ] [9b54daf6] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 1912ms)
[20:00:37.076][DockerCliAPIServer][Info   ] Killing existing docker with PID 20000
[20:00:37.093][VpnKit            ][Info   ] Killing existing vpnkit with PID 19992
[20:00:37.120][VpnKitBridge      ][Info   ] Killing existing vpnkit-bridge with PID 4652
[20:00:37.175][LoggingMessageHandler][Info   ] [5603f756] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[20:00:41.310][LoggingMessageHandler][Info   ] [5603f756] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 500 InternalServerError (took 4135ms)
[20:00:41.354][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[20:00:41.354][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[20:00:41.354][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxHyperV
[20:00:41.355][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1594220441}
[20:00:41.357][SystrayNotifications][Error  ] Microsoft.Management.Infrastructure.CimException: Catastrophic failure 
   at Microsoft.Management.Infrastructure.Internal.Operations.CimSyncEnumeratorBase`1.MoveNext()
   at SimCim.Core.SimCimScope.<EnumerateInstances>d__10`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Docker.Backend.Features.Installer.GetFeatureInfoMaps(Feature[] features) in C:\workspaces\edge-2.3.2.1\src\github.com\docker\pinata\win\src\Docker.Backend\Features\Installer.cs:line 46
   at Docker.Backend.Features.Installer.GetFeatureReport(Feature[] features) in C:\workspaces\edge-2.3.2.1\src\github.com\docker\pinata\win\src\Docker.Backend\Features\Installer.cs:line 32
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
[20:00:41.390][GUI               ][Info   ] Sending Bugsnag report 36ed112f-74e9-4336-87c5-0c7f037db63d...
[20:00:41.880][GUI               ][Info   ] Bugsnag report 36ed112f-74e9-4336-87c5-0c7f037db63d sent
[20:00:41.882][SegmentApi        ][Info   ] Usage statistic: eventCrash
[20:00:41.887][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[20:00:42.231][Engines           ][Error  ] Start failed with Catastrophic failure 
   at Docker.Core.Logging.HttpClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() in C:\workspaces\edge-2.3.2.1\src\github.com\docker\pinata\win\src\Docker.Core\Logging\HttpClientExceptionInterceptor.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\edge-2.3.2.1\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext() in C:\workspaces\edge-2.3.2.1\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<CheckFeaturesAsync>d__4.MoveNext() in C:\workspaces\edge-2.3.2.1\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoCheckPreconditionsAsync>d__18.MoveNext() in C:\workspaces\edge-2.3.2.1\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 110
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\edge-2.3.2.1\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\edge-2.3.2.1\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\edge-2.3.2.1\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__23.MoveNext() in C:\workspaces\edge-2.3.2.1\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 108)
[20:00:42.624][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[20:00:42.649][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[20:03:40.326][ErrorReportWindow ][Info   ] Open diagnostics
[20:03:57.290][ErrorReportWindow ][Info   ] Open logs
`
