### ISSUE TITLE
Unable to start Docker after installing 2.3.0.2

### ISSUE THREAD

**Issue by SeNarak** [docker/for-win#6877]
The VM is also deleted in Hyper V Manager - We use SCCM to update Docker Desktop.
![image](https://user-images.githubusercontent.com/65959218/82904723-2506c200-9f63-11ea-9dd4-b80614e36024.png)

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 21DB1441-17E0-452D-99BE-4B7C0FF8FDBA/20200526125843

### Information

  - Windows Version: 1909
  - Docker Desktop Version: 2.3.0.2
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

1. Install 2.2.0.5 then update to 2.3.0.2. Installation completed, but docker ist unable to start. no failure. it only stuck on starting docker
2. uninstalled docker and all appdata files. Installed only the new version without update. same problem. docker stucks on starting docker.
3. repeat number 1, with another installer file of docker. also same problem

in the old version of docker i see a hyper v virtual machine, in the new version i dont have any docker vm. only my test win 10 vm

**Comment by cybernetics** [comment]
same here. not able to start docker for desktop. using win 10 Pro (v 2004) with WSL2. during the installation I did not select the checkbox to enable WSL2 backend, still, it seems like it's trying to use WSL2 backend.

also submitted docker diagnostic with id: 96DD888D-3B30-4F40-A5F5-BC139A7300EB/20200629051046

getting the following error during startup:

System.InvalidOperationException:
Failed to deploy distro docker-desktop to %localappdata%\Docker\wsl\distro: exit code: -1
 stdout: Error: 0xffffffff


 stderr: 
   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__16.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
