### ISSUE TITLE
Reset to Factory Default crashes.

### ISSUE THREAD

**Issue by jimmy927** [docker/for-win#6887]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID from crash: FC536F7E-E7F5-437E-940C-10A3D084FA01/20200526194804
  - Diagnostics ID: FC536F7E-E7F5-437E-940C-10A3D084FA01/20200526195339

### Expected behavior

Docker resets to factory defaults.

### Actual behavior

Docker crashes.

```
System.InvalidOperationException:
Failed to terminate distro: exit code: -1
 stdout: There is no distribution with the supplied name.


 stderr: 
   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<TerminateDistroAsync>d__13.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<TerminateDistrosAsync>d__9.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<UnprovisionAsync>d__7.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoDestroyAsync>d__28.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 263
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.DestroyTransition.<DoRunAsync>d__6.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\DestroyTransition.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<DestroyAsync>d__16.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<ResetToDefaultAsync>d__25.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 163

```

### Information

  - Windows Version: Windows 10 Home Build: 19041
  - Docker Desktop Version:   2.3.1.0 (45408)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: **no**

### Steps to reproduce the behavior

  1. Click on factory reset

**Comment by jimmy927** [comment]
Problem went way after fixing the following issue:

https://github.com/docker/for-win/issues/6849
