### ISSUE TITLE
Docker does not start on windows 10 : 35C603B8-574C-4D3C-B91C-EB2C59710955/2017-05-01_20-52-59

### ISSUE THREAD

**Issue by nagkumar** [docker/for-win#691]
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 3FB20427-AE7A-4732-BBD8-0DC17334B75B)
at Start-MobyLinuxVM, <No file>: line 287
at <ScriptBlock>, <No file>: line 382
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 243
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 120
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 44
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 140

**Comment by friism** [comment]
Please include more details on your environment and a diagnosticid if possible. Also what version of Docker you're trying to install.

**Comment by nagkumar** [comment]
Diagnostic ID : 35C603B8-574C-4D3C-B91C-EB2C59710955/2017-05-01_20-52-59

**Comment by nagkumar** [comment]
Any update on this please..even a good workaround would do

See the latest Diagnostic ID, based on today's install
35C603B8-574C-4D3C-B91C-EB2C59710955/2017-05-15_17-17-36

**Comment by nagkumar** [comment]
I think issue is with some permisstions, ran 

net localgroup administrators LOCAL /delete
net localgroup administrators SERVICE /delete﻿

as said at https://community.spiceworks.com/topic/379549-hyper-v-2012-vm-s-wont-initialize-no-other-error-msg?page=1 comments section

and also made sure virtual network switch is configured properly as said at

https://blogs.technet.microsoft.com/canitpro/2015/09/08/step-by-step-enabling-hyper-v-for-use-on-windows-10/

last part of the URL

In all issue was more to do with Hyper-V issue than docker

Best way to see them isolated is create any default vm in hyper-v from hyper-v manager and see if you are able to start the created virtual machine. if that is happening, then no issue with hyper-v, else fix the hyper-v, before thinking it is a issue with docker.

In all it took me more than a week of trial and error to know the cause
