### ISSUE TITLE
Docker desktop failed to stop, have uninstalled and reinstalled several times

### ISSUE THREAD

**Issue by liampeng1** [docker/for-win#6917]
- [X ] I have tried with the latest version of my channel (Stable or Edge)
  - [X ] I have uploaded Diagnostics
  - Diagnostics ID: 5B04A2B5-42CA-4DAB-9B9A-19DC8A73C591/20200528034333

### Expected Behavior
Docker desktop starts.

### Actual behavior
Docker Desktop does not start. Get error that docker desktop failed to stop.

From logfile:

Version: 2.3.0.3 (45519)
Channel: stable
Sha1: 0356a6f23f086a8134d83ee38d99ffe55a121f02
Started on: 2020/05/28 09:28:07.514
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Home
Edition: Core
Id: 2004
Build: 19041
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\17576\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:28:07.593][GUI               ][Info   ] Starting...
[09:28:07.608][ComponentVersions ][Info   ] Edition community
[09:28:07.612][ComponentVersions ][Info   ] Edition community
[09:28:07.782][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[09:28:07.784][GUI               ][Error  ] An instance is already running. Exiting.
[09:28:07.757][SegmentApi        ][Info   ] Usage statistic: appLaunched
[09:28:08.024][ApplicationTemplatesTracking][Info   ] Cannot list templates
[09:28:08.025][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[09:28:08.027][SegmentApi        ][Info   ] Usage statistic: heartbeat
[09:28:08.081][LoggingMessageHandler][Info   ] [ca4299f9] <BackendAPIClient start> GET http://backend/version
[09:28:08.113][LoggingMessageHandler][Info   ] [ca4299f9] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 30ms)
[09:28:08.194][LoggingMessageHandler][Info   ] [398a363c] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[09:28:08.204][LoggingMessageHandler][Info   ] [398a363c] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 9ms)
[09:28:08.215][LoggingMessageHandler][Info   ] [79a66c94] <BackendAPIClient start> POST http://backend/migrate/app
[09:28:08.219][LoggingMessageHandler][Info   ] [79a66c94] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 3ms)
[09:28:08.224][Engines           ][Debug  ] Starting
[09:28:08.239][LoggingMessageHandler][Info   ] [3feaff3c] <BackendAPIClient start> POST http://backend/versionpack/enable
[09:28:08.274][LoggingMessageHandler][Info   ] [3feaff3c] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 34ms)
[09:28:08.333][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[09:28:08.335][GoBackendProcess  ][Info   ] Started
[09:28:08.338][MutagenProcess    ][Info   ] Starting C:\ProgramData\Docker\cli-plugins\docker-mutagen.exe mutagen daemon run
[09:28:08.340][MutagenProcess    ][Info   ] Started
[09:28:08.347][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[09:28:08.348][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[09:28:08.351][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxWSL2
[09:28:08.358][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1590676088}
[09:28:08.358][SystrayNotifications][Info   ] Docker is starting
[09:28:08.360][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[09:28:08.362][LoggingMessageHandler][Info   ] [3847d71f] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[09:28:08.386][MutagenProcess    ][Info   ] [forwarding] Looking for existing sessions
[09:28:08.386][MutagenProcess    ][Info   ] [forwarding] Session manager initialized
[09:28:08.386][MutagenProcess    ][Info   ] [sync] Looking for existing sessions
[09:28:08.386][MutagenProcess    ][Info   ] [sync] Session manager initialized
[09:28:08.422][LoggingMessageHandler][Info   ] [3847d71f] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 59ms)
[09:28:08.462][WSL2Provisioning  ][Error  ] Failed to terminate distro: exit code: -1
 stdout: There is no distribution with the supplied name.

 stderr: 
[09:28:08.466][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[09:28:08.520][LinuxWSL2Engine   ][Info   ] Stopping engine
[09:28:08.586][LinuxWSL2Engine   ][Warning] Failed to send stop message to distro, will terminate abrubtly: 
[09:28:08.655][WSL2Provisioning  ][Error  ] Failed to terminate distro: exit code: -1
 stdout: There is no distribution with the supplied name.

 stderr: 
[09:28:08.656][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.UnstableState to state change sink
[09:28:08.656][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.UnstableState sent to state change sink
[09:28:08.656][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.UnstableState from LinuxWSL2
[09:28:08.657][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1590676088}
[09:28:08.657][SystrayNotifications][Info   ] Docker Desktop failed to stop
[09:28:08.669][Engines           ][Error  ] Start failed with Failed to terminate distro: exit code: -1
 stdout: There is no distribution with the supplied name.

 stderr: 
   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<TerminateDistroAsync>d__13.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__24.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 109)
[09:28:08.814][LoggingMessageHandler][Info   ] [29b5e7ad] <Server start> GET http://unix/versions
[09:28:08.875][LoggingMessageHandler][Info   ] [29b5e7ad] <Server end> GET http://unix/versions -> 200 OK (took 60ms)
[09:28:08.904][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[09:28:08.905][GoBackendProcess  ][Info   ] started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl
[09:28:08.906][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[09:28:08.906][GoBackendProcess  ][Info   ] enabling filesystem caching
[09:28:08.906][GoBackendProcess  ][Info   ] filesystem exports are:  (2)
[09:28:08.907][GoBackendProcess  ][Info   ] volume control server listening on \\\\.\\pipe\\dockerVolume
[09:28:08.908][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[09:28:08.908][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[09:28:08.910][GoBackendProcess  ][Info   ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[09:28:08.910][GoBackendProcess  ][Info   ] file ownership will be determined by the calling user (\"fake owner\" mode)
[09:28:08.910][GoBackendProcess  ][Info   ] using mfsymlinks
[09:28:14.337][SegmentApi        ][Info   ] Usage statistic: actionMenuFeedback
[09:28:14.688][LoggingMessageHandler][Info   ] [39da5d4e] <Server start> POST http://localhost/notifications/subscriptions
[09:28:14.742][LoggingMessageHandler][Info   ] [4f2c8d37] <NotificationsClient start> GET http://localhost/ping
[09:28:14.757][LoggingMessageHandler][Info   ] [4f2c8d37] <NotificationsClient end> GET http://localhost/ping -> 200 OK (took 15ms)
[09:28:14.759][LoggingMessageHandler][Info   ] [39da5d4e] <Server end> POST http://localhost/notifications/subscriptions -> 200 OK (took 70ms)
[09:28:15.816][LoggingMessageHandler][Info   ] [6a6c3923] <Server start> GET http://localhost/registry/user
[09:28:15.818][LoggingMessageHandler][Info   ] [54e72bce] <Server start> GET http://localhost/docker
[09:28:15.818][LoggingMessageHandler][Info   ] [6a6c3923] <Server end> GET http://localhost/registry/user -> 404 NotFound (took 1ms)
[09:28:15.820][LoggingMessageHandler][Info   ] [60f77f15] <Server start> GET http://localhost/kubernetes
[09:28:15.824][LoggingMessageHandler][Info   ] [f95d730b] <Server start> GET http://localhost/license/details
[09:28:15.826][LoggingMessageHandler][Info   ] [fd099005] <Server start> GET http://localhost/versions
[09:28:15.829][LoggingMessageHandler][Info   ] [f95d730b] <Server end> GET http://localhost/license/details -> 200 OK (took 5ms)
[09:28:15.829][LoggingMessageHandler][Info   ] [fd099005] <Server end> GET http://localhost/versions -> 200 OK (took 3ms)
[09:28:15.829][LoggingMessageHandler][Info   ] [60f77f15] <Server end> GET http://localhost/kubernetes -> 200 OK (took 9ms)
[09:28:15.830][LoggingMessageHandler][Info   ] [54e72bce] <Server end> GET http://localhost/docker -> 200 OK (took 11ms)
[09:28:15.867][GoBackendProcess  ][Info   ] external: GET /system/editor 200 \"axios/0.19.0\" \"\
[09:28:21.196][LoggingMessageHandler][Info   ] [75b7627a] <Server start> GET http://localhost/desktop/diagnose
[09:28:21.286][LoggingMessageHandler][Info   ] [75b7627a] <Server end> GET http://localhost/desktop/diagnose -> 204 NoContent (took 89ms)
[09:28:21.286][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[09:28:21.323][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[09:28:21.324][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[09:28:21.325][GoBackendProcess  ][Info   ] mutagen sync list --output json
[09:28:21.351][GoBackendProcess  ][Info   ] mutagen C:\\ProgramData\\Docker\\cli-plugins\\docker-mutagen.exe mutagen sync list --output json: null\n
[09:28:21.351][GoBackendProcess  ][Info   ] external: GET /sync 200 \"Go-http-client/1.1\" \"\
[09:28:24.070][FeedbackWindow    ][Info   ] Open logs

### Information

  - Windows Version: 10 2004
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
Happens every time I try to to start docker desktop
<!--
A reproducible case, Dockerfiles with reproduction inside is best.

**Comment by hcabnettek** [comment]
Same I am unable to run Docker Desktop. Whale icon turns red and says Docker Desktop fails to stop. It happened right after Windows 10 2004 was released for me.

**Comment by dalean5** [comment]
I am having the same issue, but it is very weird. Everything was working fine with the Insider Preview of version 2004. However, when I upgrade to the stable release, everything broke. I am still investigating the issue to see if I can resolve it.

**Comment by dalean5** [comment]
@liampeng1 and @hcabnettek I resolved the issue by reading and following the instructions here https://github.com/docker/for-win/issues/6971
