### ISSUE TITLE
Only Linux containers doesn't work: Unable to write to the database. Exit code: 1

### ISSUE THREAD

**Issue by julioms87** [docker/for-win#692]
### Expected behavior
Start Docker with Linux containers
### Actual behavior
Crash
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
8F3292C0-B2FA-45C7-AED8-B9D6A57DEC38/2017-05-01_16-34-16

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows 10 Enterprise Version	10.0.14393 Build 14393

### Steps to reproduce the behavior

  1. Launch Docker with Linux containers,
  2. Await until the crash report.

### Error

Unable to write to the database. Exit code: 1
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 243
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 179
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 44
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 140

### Additional Info

I had an fresh Windows install, then I installed Docker, which ran nice for one time only with Linux containers, put Windows to update and rebooted the system, then the issue started.

I am still able to use with Windows containers.

Thanks!

**Comment by friism** [comment]
Not enough details, closing.

**Comment by julioms87** [comment]
@friism Sorry mate, as soon I opened the issue gave a hit at the enter key. Does it need any other information?

**Comment by friism** [comment]
@julioms87 you're good - thanks!

**Comment by friism** [comment]
What happens if you do factory reset in Docker for Windows or alternatively re-install Docker for Windows?

**Comment by julioms87** [comment]
@friism thanks for your reply. The same issue, tried both version, restart, reset to factory and uninstall, then reboot and re-install.

All those ways lead me to the same issue.

**Comment by julioms87** [comment]
@friism resolved, actually I had to reinstall the OS. Thanks.

**Comment by iceweird** [comment]
5136A7F1-3053-436D-8C41-87318833CDD7/2017-08-16_10-16-36 same problem here, not going to reinstall OS tho :( can u help @friism pls?
