### ISSUE TITLE
Docker Desktop failed to start after updating Win10 to 2004

### ISSUE THREAD

**Issue by davidmz** [docker/for-win#6927]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: F8D4656A-2008-4238-8399-697C2AC780B9/20200528131158

### Expected behavior

Docker Desktop should start

### Actual behavior

Error occured:

```
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\David\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0xffffffff


 stderr: 
   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__16.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

### Information
  - Windows Version: Windows 10 Pro, v 2004, build 19041
  - Docker Desktop Version: 2.3.1.0 (45408)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

**Comment by davidmz** [comment]
In my case, the cause was dnscrypt-proxy.exe that took occupied port 53. It somehow prevented the WSL 2 from working.

This seems to be a common problem (I have seen other similar messages with port 53 busy).

**Comment by mat007** [comment]
> This seems to be a common problem (I have seen other similar messages with port 53 busy).

I agree, @simonferquel do you believe we could could test the port and pop a nice error message box if it’s already bound?

**Comment by damienvanrobaeys** [comment]
I have the same issue, after migrating from 2.2.0.5 to 2.3.0.3
![image](https://user-images.githubusercontent.com/8832278/86455518-009bc380-bd21-11ea-9d3c-ac130c8a7c8a.png)

**Comment by damienvanrobaeys** [comment]
I also noticed one thing.
I have migrated manually my distros to wsl 2 using: wsl --set-version distro 2 before upgrading to 2.3.0.3
When I launch Docker I have the error.
Now I have migrated my distos back to wsl 1.
When I launch docker I don't have any issue.

**Comment by adinata-id** [comment]
> I have the same issue, after migrating from 2.2.0.5 to 2.3.0.3
> ![image](https://user-images.githubusercontent.com/8832278/86455518-009bc380-bd21-11ea-9d3c-ac130c8a7c8a.png)

this is bugs version 2.3.0.3 ?

**Comment by nevmerzhitsky** [comment]
The same problem.

Hello @docker the issue is still there.

**Comment by devedse** [comment]
Hey all,

I'm also running into this problem. Sadly the policies from my employer force me to use a tool that forces my DNS to go through a DNS server hosted at my local machine.

The way this works is by running an instance of dnscrypt-proxy.exe. Since there's probably more people that host a DNS server on their own machines (for various reasons), I think this issue should be solved by not depending on port 53 being available rather then writing a better error message.

**Comment by simonferquel** [comment]
Hi, unfortunately, there is nothing we can do on our side for this bug.
Although, Microsoft has acknowledged it, and even has a fix (current dev-preview insider build has it), and they are working on backporting it to official Windows 10 builds (trough a future Windows update). In the mean time, you can revert to using Hyper-V backend.
