### ISSUE TITLE
sam build --use-container not able to clear out .aws-sam folder until restart

### ISSUE THREAD

**Issue by rupe120** [docker/for-win#6938]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 72B0EE3F-FB45-455E-AAEC-0C09939470E1/20200529013539

### Expected behavior

AWS `sam build --use-container` should be able to be used without running into access denied errors.

### Actual behavior

The `.aws-sam` folder is locked by Docker and prevents the contents from being refreshed. A restart of Docker Desktop fixes the problem every time. 

I will randomly, though frequently receive the following errors. The `OSError` happens once, and then I receive the `PermissionError` every time until I restart Docker Desktop

```
> sam build --use-container
Starting Build inside a container
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 129, in cli
    mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 179, in do_cli
    mode=mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 69, in __enter__
    self._build_dir = self._setup_build_dir(self._build_dir, self._clean)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 91, in _setup_build_dir
    shutil.rmtree(build_dir)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 516, in rmtree
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 404, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 402, in _rmtree_unsafe
OSError: [WinError 145] The directory is not empty: '.aws-sam\\build'
```

```
> sam build --use-container --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Starting Build inside a container
No Parameters detected in the template
2 resources found in the template
Found Serverless function with name='CustomMetricDeliveryCloudwatchFunction' and CodeUri='cloudwatch_metric_delivery/'
No Parameters detected in the template
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 82, 'exitReason': 'PermissionError', 'exitCode': 255, 'requestId': '45bd311d-8076-44b1-bff8-25b15bda4642', 'installationId': '70ce78ee-79f5-4ef9-867e-02893e68d012', 'sessionId': 'e404098b-88c9-4f95-ba3c-e65ec6a99505', 'executionEnvironment': 'CLI', 'pyversion': '3.7.6', 'samcliVersion': '0.52.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 129, in cli
    mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 179, in do_cli
    mode=mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 69, in __enter__
    self._build_dir = self._setup_build_dir(self._build_dir, self._clean)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 91, in _setup_build_dir
    shutil.rmtree(build_dir)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 516, in rmtree
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 395, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 377, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 374, in _rmtree_unsafe
PermissionError: [WinError 5] Access is denied: '.aws-sam\\build\\CustomMetricDeliveryCloudwatchFunction'
```

### Information

  - Windows Version: Windows 10 - Version 10.0.18363 Build 18363
  - Docker Desktop Version: 2.3.1.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

  - The problem is not reliable, though It happened to me at least 5 or 6 times in the last 1:30
  - Docker Desktop did recently update, though I just today started working on a SAM project and I have not used SAM in many months
 

### Steps to reproduce the behavior
 ? Run `sam build --use-container` until it happens?

**Comment by rupe120** [comment]
This is no longer random. It happens every time

**Comment by mpeckdsd** [comment]
I'm running into the exact same problem. Have you found a workaround besides bouncing docker?

**Comment by rupe120** [comment]
Ya, don't use Docker with Windows. Everything works great under Linux

**Comment by rupe120** [comment]
It turns out that this is still inconsistent, though it does seem to happen more often than not. It's also not just the `sam build --use-container` that will hold file locks on the .aws-sam folder, `sam local invoke` can also cause the container to not release file system resources in that folder.

**Comment by mpeckdsd** [comment]
Yeah, unfortunately work constraints force me to use windows. I kinda found a workaround, but it involves using wsl.

**Comment by rupe120** [comment]
I haven't had luck with Docker in WSL. How are you using it?

**Comment by mpeckdsd** [comment]
I followed the instructions here: https://nickjanetakis.com/blog/setting-up-docker-for-windows-and-wsl-to-work-flawlessly

**Comment by rupe120** [comment]
Thank you @mpeckdsd 

I had to do this first 

https://github.com/microsoft/WSL/issues/5125#issuecomment-619350931

But after that I was able to complete the steps in from the blog you posted

**Comment by dstrohl** [comment]
For me the problem seems to be after running a sam local invoke command.  After the build I can run another build, delete the directory, etc... but after I run the local invoke command, I cant even delete the directory using the command line.

**Comment by owaiskazi19** [comment]
Any work around for this problem? 
Every time I have to restart the docker before running `sam build`.

**Comment by paulschwarz** [comment]
I'm experiencing exactly the same and verified that restarting Docker solves the issue, but obviously that's slow.

However, I've made an interesting observation. The issue isn't actually resolved by restarting Docker, that's overkill; all you have to do is "refresh" Docker Desktop. I don't know how to describe this better, but here's an example of how to do it:

1. Get your same build to fail.
2. In Docker Desktop, go to the "Command Line" tab and enable experimental features. 
3. Press "Apply & Restart".
4. Immediately disable experimental features.
5. Press "Apply & Restart".

The actual steps above have no special meaning or method. The key is that Docker Desktop sort of "refreshes" itself and it's very fast (no need to reboot the whole Docker VM). But somehow in this "refresh" it gives up the reference to the ghost mounted volume.

At this point, you can immediately run your `$ sam build` again and it will work.

My hope is that this finding helps to clarify that perhaps the issue isn't with Docker or Windows, but rather with Docker Desktop on Windows. I hope this leads to narrowing down the problem and releasing a fix.

**Comment by mpeckdsd** [comment]
Hey guys, I was able to get it working more consistently by right clicking on the docker desktop icon in the taskbar, going to settings, and clicking the 'troubleshoot' bug at the top. Then, 'clean/purge data'. Not a permanent fix, but seems to help substantially. 
![image](https://user-images.githubusercontent.com/57722081/88303894-8df58680-ccd5-11ea-85a9-a2dfc869bcd6.png)

**Comment by paulschwarz** [comment]
@mpeckdsd what's the minimal selection needed in the "Clean/Purge data" dialog?

- [ ] Hyper-V
- [ ] WSL 2
- [ ] Windows Containers

Which do you select?

**Comment by mpeckdsd** [comment]
I'm only running containers in hyper-v so that's all I selected.

**Comment by paulschwarz** [comment]
> @mpeckdsd what's the minimal selection needed in the "Clean/Purge data" dialog?
> 
> * [ ]  Hyper-V
> * [ ]  WSL 2
> * [ ]  Windows Containers
> 
> Which do you select?

I was able to get away with just selecting "WSL 2" and then "Delete". It purges pretty quickly and works every time.

I'm curious about the timeline of when we can stop doing this workaround.

**Comment by ltoshev** [comment]
I have same issue, supper annoying to do dev work this way. Cleaning purging data is also slow and it also restarts docker. It also deleted all my images, which means fetching them again is pretty slow. So dont do purge! At least for me is not an option.

**Comment by ltoshev** [comment]
The only solution I've found is you download Process Explorer -> run it in Adm mode, go to the Docker Desktop.exe sort - by the name column and find the files in your ./aws-sam folder -> right click Close Handle. Then you can run again the sam build --use-container and it will succeed. You have to do this every time, but its a lot faster.

**Comment by nealonhager** [comment]
Having the same issue, really makes development sluggish sadly.

**Comment by dgrove153** [comment]
> 
> 
> > @mpeckdsd what's the minimal selection needed in the "Clean/Purge data" dialog?
> > 
> > * [ ]   Hyper-V
> > * [x]   WSL 2
> > * [ ]   Windows Containers
> > 
> > Which do you select?
> 
> I was able to get away with just selecting "WSL 2" and then "Delete". It purges pretty quickly and works every time.
> 
> I'm curious about the timeline of when we can stop doing this workaround.

Of all the solutions, this worked for me as well and was the fastest. Still annoying though.

**Comment by nealonhager** [comment]
> > > @mpeckdsd what's the minimal selection needed in the "Clean/Purge data" dialog?
> > > 
> > > * [ ]    Hyper-V
> > > * [x]    WSL 2
> > > * [ ]    Windows Containers
> > > 
> > > Which do you select?
> > 
> > 
> > I was able to get away with just selecting "WSL 2" and then "Delete". It purges pretty quickly and works every time.
> > I'm curious about the timeline of when we can stop doing this workaround.
> 
> Of all the solutions, this worked for me as well and was the fastest. Still annoying though.

This works _most_ of the time. Sometimes I will need to do a full restart.

**Comment by researchdeveloping** [comment]
Do you have any idea how to fix such a problem in Docker on Windows?
