### ISSUE TITLE
Docker for Windows - Not starting and failing with error message"Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start"

### ISSUE THREAD

**Issue by udaycern** [docker/for-win#696]
### Expected behavior
Downloaded docker CE version, verified Virtualization is enabled and Hyper-V feature is turned on. Expected docker to start running after installation
### Actual behavior
Docker failing with error message"Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start"
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
E0EE74AD-59E6-4E35-A140-E57B8B6E453E/2017-05-02_11-13-23

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)
Windows 10 Enterprise edition (Updated with all latest patches)

Docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      windows/amd64

### Steps to reproduce the behavior

  1. ... 
  2. ...
Log file:
Version: 17.03.1-ce-win5 (10743)
Channel: stable
Sha1: b18e2a50ccf296bcd637b330c0ca9faaab9d790c
Started on: 2017/05/02 11:09:01.111
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1607
Build: 14393
BuildLabName: 14393.1066.amd64fre.rs1_release_sec.170327-1835
File: C:\Users\C15637\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:09:01.214][GUI            ][Info   ] Starting...
[11:09:01.462][Tracking       ][Info   ] Crash report and usage statistics are enabled
[11:09:01.466][SegmentApi     ][Info   ] Usage statistic: appLaunched
[11:09:01.560][NamedPipeClient][Info   ] Sending Version()...
[11:09:01.562][NamedPipeClient][Info   ] Received response for Version
[11:09:01.563][SegmentApi     ][Info   ] Usage statistic: heartbeat
[11:09:01.562][NamedPipeServer][Info   ] Version done in 00:00:00.
[11:09:02.055][Updater        ][Info   ] Checking for updates on channel stable...
[11:09:02.056][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[11:09:02.057][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[11:09:02.057][PowerMode      ][Info   ] Stop
[11:09:02.057][HyperV         ][Info   ] Stop
[11:09:02.057][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:09:02.062][HyperV         ][Info   ] Script started at 11:09:02.062
[11:09:02.072][HyperV         ][Info   ] Module loaded at 11:09:02.072
[11:09:02.083][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:09:02.083][HyperV         ][Debug  ] [stop] took 00:00:00.0259947 to run
[11:09:02.083][OptimizeDisk   ][Info   ] Optimize
[11:09:02.083][PowerShell     ][Info   ] Run script...
[11:09:02.090][Moby           ][Info   ] Stop
[11:09:02.098][HyperV         ][Info   ] Create
[11:09:02.098][HyperVGuids    ][Info   ] Installing GUIDs...
[11:09:02.098][PowerMode      ][Info   ] Start
[11:09:02.098][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[11:09:02.099][Firewall       ][Info   ] Removing all existing rules...
[11:09:02.101][HyperVGuids    ][Info   ] GUIDs installed
[11:09:02.104][HyperV         ][Info   ] Script started at 11:09:02.104
[11:09:02.115][HyperV         ][Info   ] Module loaded at 11:09:02.114
[11:09:02.121][Firewall       ][Info   ] All existing rules are removed.
[11:09:02.121][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[11:09:02.130][Firewall       ][Info   ] Opening ports for SMB...
[11:09:02.136][Updater        ][Info   ] Local build 10743 is as good as the remote 10743 on channel stable
[11:09:02.138][Firewall       ][Info   ] Ports are opened
[11:09:02.797][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:09:04.964][HyperV         ][Info   ] Switch created.
[11:09:05.242][HyperV         ][Info   ] Set IP address on switch
[11:09:05.268][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[11:09:05.920][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[11:09:06.141][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[11:09:06.513][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[11:09:06.642][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\mobylinux.iso
[11:09:07.070][HyperV         ][Info   ] Disabled Guest Service Interface
[11:09:07.083][HyperV         ][Info   ] Enabled Heartbeat
[11:09:07.109][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[11:09:07.121][HyperV         ][Info   ] Enabled Shutdown
[11:09:07.134][HyperV         ][Info   ] Enabled Time Synchronization
[11:09:07.152][HyperV         ][Info   ] Disabled VSS
[11:09:07.458][HyperV         ][Info   ] VM created.
[11:09:07.458][HyperV         ][Debug  ] [create] took 00:00:05.3597675 to run
[11:09:07.458][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[11:09:07.488][DataKit        ][Info   ] Starting C:\Program Files\Docker\Docker\Resources\com.docker.db.exe --url hyperv-connect://4026c82e-6adf-4111-823f-832505cd548d,\\.\pipe\dockerDataBase --color never
[11:09:07.492][DataKit        ][Info   ] Started
[11:09:07.492][Database       ][Info   ] Generating CA Cert Bundle
[11:09:07.524][DataKit        ][Info   ] Starting com.docker.db.exe 0.7.0-34-g6f04213 ...
[11:09:07.534][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[11:09:07.534][DataKit        ][Info   ] com.docker.db.exe: accepted a new connection on \\.\pipe\dockerDataBase
[11:09:07.534][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[11:09:07.534][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[11:09:07.534][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[11:09:07.534][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[11:09:07.534][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[]}
[11:09:07.534][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[11:09:07.534][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[11:09:07.576][DataKit        ][Info   ] com.docker.db.exe: accepted a new connection on \\.\pipe\dockerDataBase
[11:09:07.577][DataKit        ][Info   ] com.docker.db.exe: Using protocol TwoThousand msize 16384
[11:09:07.742][Database       ][Info   ] CA Cert Bundle Generated
[11:09:08.034][Database       ][Info   ] Successfully wrote 8 value(s)
[11:09:08.034][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/ssl/certs/ca-certificates.crt=C:\windows\TEMP\tmp1C33.tmp
[11:09:08.072][DataKit        ][Info   ] com.docker.db.exe: accepted a new connection on \\.\pipe\dockerDataBase
[11:09:08.073][DataKit        ][Info   ] com.docker.db.exe: Using protocol TwoThousand msize 16384
[11:09:08.234][Database       ][Info   ] Successfully wrote value
[11:09:08.234][Moby           ][Info   ] Connecting...
[11:09:08.235][Moby           ][Error  ] Failed to read Moby's logs: The operation has timed out.
[11:09:08.235][HyperV         ][Info   ] Start
[11:09:08.235][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[11:09:08.235][PowerShell     ][Info   ] Run script with parameters: -Start True...
[11:09:08.869][HyperV         ][Info   ] Script started at 11:09:08.869
[11:09:08.928][Database       ][Info   ] Writing com.docker.driver.amd64-linux/slirp/dns=nameserver 10.128.10.17
nameserver 10.128.8.17
search XXXX.com
search northamerica.XXXX.net
[11:09:08.974][DataKit        ][Info   ] com.docker.db.exe: accepted a new connection on \\.\pipe\dockerDataBase
[11:09:08.975][DataKit        ][Info   ] com.docker.db.exe: Using protocol TwoThousand msize 16384
[11:09:09.070][Database       ][Info   ] Successfully wrote 1 value(s)
[11:09:09.145][VpnKit         ][Info   ] Starting C:\Program Files\Docker\Docker\Resources\com.docker.slirp.exe --ethernet hyperv-connect://4026c82e-6adf-4111-823f-832505cd548d --port hyperv-connect://4026c82e-6adf-4111-823f-832505cd548d --db \\.\pipe\dockerDataBase --debug --diagnostics \\.\pipe\dockerVpnKitDiagnostics
[11:09:09.149][VpnKit         ][Info   ] Started
[11:09:09.181][VpnKit         ][Info   ] com.docker.slirp.exe: Logging to stdout (stdout:true DEBUG:false)
[11:09:09.181][VpnKit         ][Info   ] com.docker.slirp.exe: Setting handler to ignore all SIGPIPE signals
[11:09:09.182][VpnKit         ][Info   ] com.docker.slirp.exe: vpnkit version c41f7c8589352c95b14de636c895e8fbd72222e5 with hostnet version   uwt version 0.0.3 hvsock version 0.13.0 
[11:09:09.182][VpnKit         ][Info   ] com.docker.slirp.exe: starting port forwarding server on port_control_url:hyperv-connect://4026c82e-6adf-4111-823f-832505cd548d vsock_path:
[11:09:09.182][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to 4026c82e-6adf-4111-823f-832505cd548d:0B95756A-9985-48AD-9470-78E060895BE7
[11:09:09.186][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to 4026c82e-6adf-4111-823f-832505cd548d:30D48B34-7D27-4B0B-AAAF-BBBED334DD59
[11:09:09.186][VpnKit         ][Error  ] com.docker.slirp.exe: While watching /etc/resolv.conf: ENOENT
[11:09:09.186][VpnKit         ][Info   ] com.docker.slirp.exe: hosts file has bindings for 
[11:09:09.463][HyperV         ][Info   ] Module loaded at 11:09:09.463
[11:09:09.465][HyperV         ][Info   ] Starting VM MobyLinuxVM...
[11:09:09.620][Linux          ][Error  ] Failed to start: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID 4026C82E-6ADF-4111-823F-832505CD548D)

'MobyLinuxVM' failed to start worker process: An invalid HANDLE was specified. (0xC0000008). (Virtual machine ID 4026C82E-6ADF-4111-823F-832505CD548D)
at Start-MobyLinuxVM, <No file>: line 287
at <ScriptBlock>, <No file>: line 382. Let's retry
[11:09:09.620][PowerShell     ][Info   ] Run script...
[11:09:12.819][HyperV         ][Info   ] Hyper-V is running
[11:09:12.819][PowerMode      ][Info   ] Stop
[11:09:12.820][HyperV         ][Info   ] Stop
[11:09:12.820][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:09:12.827][HyperV         ][Info   ] Script started at 11:09:12.827
[11:09:12.837][HyperV         ][Info   ] Module loaded at 11:09:12.837
[11:09:12.867][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[11:09:12.867][HyperV         ][Debug  ] [stop] took 00:00:00.0469963 to run
[11:09:12.867][OptimizeDisk   ][Info   ] Optimize
[11:09:12.867][PowerShell     ][Info   ] Run script...
[11:09:14.169][Moby           ][Info   ] Stop
[11:09:14.176][VpnKit         ][Info   ] Killing existing com.docker.slirp with PID 4412
[11:09:14.182][DataKit        ][Info   ] Killing existing com.docker.db with PID 3112
[11:09:14.187][HyperV         ][Info   ] Destroy
[11:09:14.188][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[11:09:14.195][HyperV         ][Info   ] Script started at 11:09:14.195
[11:09:14.204][HyperV         ][Info   ] Module loaded at 11:09:14.204
[11:09:14.220][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[11:09:14.220][HyperV         ][Info   ] Destroying Switch DockerNAT...
[11:09:15.650][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[11:09:15.702][HyperV         ][Debug  ] [destroy] took 00:00:01.5148766 to run
[11:09:15.702][Firewall       ][Info   ] Closing ports...
[11:09:15.702][Firewall       ][Info   ] Removing all existing rules...
[11:09:15.775][Firewall       ][Info   ] All existing rules are removed.
[11:09:15.775][Firewall       ][Info   ] Ports are closed
[11:09:15.775][HyperVGuids    ][Info   ] Removing GUIDs...
[11:09:15.777][HyperVGuids    ][Info   ] GUIDs removed
[11:09:15.777][HyperV         ][Info   ] Create
[11:09:15.778][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[11:09:15.786][HyperV         ][Info   ] Script started at 11:09:15.785
[11:09:15.810][HyperV         ][Info   ] Module loaded at 11:09:15.810
[11:09:15.864][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:09:17.954][HyperV         ][Info   ] Switch created.
[11:09:18.089][HyperV         ][Info   ] Set IP address on switch
[11:09:18.111][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[11:09:18.768][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[11:09:18.949][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[11:09:19.275][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[11:09:19.396][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\mobylinux.iso
[11:09:19.862][HyperV         ][Info   ] Disabled Guest Service Interface
[11:09:19.877][HyperV         ][Info   ] Enabled Heartbeat
[11:09:19.899][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[11:09:19.916][HyperV         ][Info   ] Enabled Shutdown
[11:09:19.928][HyperV         ][Info   ] Enabled Time Synchronization
[11:09:19.946][HyperV         ][Info   ] Disabled VSS
[11:09:20.237][HyperV         ][Info   ] VM created.
[11:09:20.238][HyperV         ][Debug  ] [create] took 00:00:04.4608362 to run
[11:09:20.238][PowerMode      ][Info   ] Stop
[11:09:20.238][HyperV         ][Info   ] Stop
[11:09:20.238][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:09:20.245][HyperV         ][Info   ] Script started at 11:09:20.245
[11:09:20.258][HyperV         ][Info   ] Module loaded at 11:09:20.258
[11:09:20.286][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[11:09:20.286][HyperV         ][Debug  ] [stop] took 00:00:00.0479902 to run
[11:09:20.286][OptimizeDisk   ][Info   ] Optimize
[11:09:20.286][PowerShell     ][Info   ] Run script...
[11:09:21.594][Moby           ][Info   ] Stop
[11:09:21.602][HyperV         ][Info   ] Create
[11:09:21.603][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[11:09:21.605][HyperVGuids    ][Info   ] Installing GUIDs...
[11:09:21.605][PowerMode      ][Info   ] Start
[11:09:21.605][Firewall       ][Info   ] Removing all existing rules...
[11:09:21.609][HyperVGuids    ][Info   ] GUIDs installed
[11:09:21.613][HyperV         ][Info   ] Script started at 11:09:21.613
[11:09:21.629][HyperV         ][Info   ] Module loaded at 11:09:21.628
[11:09:21.658][Firewall       ][Info   ] All existing rules are removed.
[11:09:21.658][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[11:09:21.703][Firewall       ][Info   ] Opening ports for SMB...
[11:09:21.720][Firewall       ][Info   ] Ports are opened
[11:09:22.048][HyperV         ][Info   ] Using existing Switch: DockerNAT
[11:09:22.100][HyperV         ][Info   ] Using existing Switch IP address
[11:09:22.118][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[11:09:22.218][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[11:09:22.334][HyperV         ][Info   ] Disabled Guest Service Interface
[11:09:22.347][HyperV         ][Info   ] Enabled Heartbeat
[11:09:22.361][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[11:09:22.374][HyperV         ][Info   ] Enabled Shutdown
[11:09:22.388][HyperV         ][Info   ] Enabled Time Synchronization
[11:09:22.402][HyperV         ][Info   ] Disabled VSS
[11:09:22.496][HyperV         ][Info   ] VM created.
[11:09:22.496][HyperV         ][Debug  ] [create] took 00:00:00.8942218 to run
[11:09:22.496][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[11:09:22.516][DataKit        ][Info   ] Starting C:\Program Files\Docker\Docker\Resources\com.docker.db.exe --url hyperv-connect://b668b918-98f6-4bc5-ba5c-927c70429d8e,\\.\pipe\dockerDataBase --color never
[11:09:22.519][DataKit        ][Info   ] Started
[11:09:22.519][Database       ][Info   ] Generating CA Cert Bundle
[11:09:22.548][DataKit        ][Info   ] Starting com.docker.db.exe 0.7.0-34-g6f04213 ...
[11:09:22.561][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[11:09:22.561][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[11:09:22.561][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[11:09:22.561][DataKit        ][Info   ] com.docker.db.exe: accepted a new connection on \\.\pipe\dockerDataBase
[11:09:22.561][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[11:09:22.561][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[11:09:22.561][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[]}
[11:09:22.561][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[11:09:22.561][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[11:09:22.602][DataKit        ][Info   ] com.docker.db.exe: accepted a new connection on \\.\pipe\dockerDataBase
[11:09:22.603][DataKit        ][Info   ] com.docker.db.exe: Using protocol TwoThousand msize 16384
[11:09:22.782][Database       ][Info   ] CA Cert Bundle Generated
[11:09:22.984][Database       ][Info   ] Successfully wrote 8 value(s)
[11:09:22.984][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/ssl/certs/ca-certificates.crt=C:\windows\TEMP\tmp56EB.tmp
[11:09:23.048][DataKit        ][Info   ] com.docker.db.exe: accepted a new connection on \\.\pipe\dockerDataBase
[11:09:23.049][DataKit        ][Info   ] com.docker.db.exe: Using protocol TwoThousand msize 16384
[11:09:23.253][Database       ][Info   ] Successfully wrote value
[11:09:23.254][Moby           ][Info   ] Connecting...
[11:09:23.254][Moby           ][Error  ] Failed to read Moby's logs: The operation has timed out.
[11:09:23.254][HyperV         ][Info   ] Start
[11:09:23.254][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...
[11:09:23.256][PowerShell     ][Info   ] Run script with parameters: -Start True...
[11:09:23.260][HyperV         ][Info   ] Script started at 11:09:23.260
[11:09:23.273][HyperV         ][Info   ] Module loaded at 11:09:23.273
[11:09:23.276][HyperV         ][Info   ] Starting VM MobyLinuxVM...
[11:09:23.337][Database       ][Info   ] Writing com.docker.driver.amd64-linux/slirp/dns=nameserver 10.128.10.17
nameserver 10.128.8.17
search XXXX.com
search northamerica.XXXX.net
[11:09:23.375][DataKit        ][Info   ] com.docker.db.exe: accepted a new connection on \\.\pipe\dockerDataBase
[11:09:23.376][DataKit        ][Info   ] com.docker.db.exe: Using protocol TwoThousand msize 16384
[11:09:23.459][Database       ][Info   ] Successfully wrote 1 value(s)
[11:09:23.519][VpnKit         ][Info   ] Starting C:\Program Files\Docker\Docker\Resources\com.docker.slirp.exe --ethernet hyperv-connect://b668b918-98f6-4bc5-ba5c-927c70429d8e --port hyperv-connect://b668b918-98f6-4bc5-ba5c-927c70429d8e --db \\.\pipe\dockerDataBase --debug --diagnostics \\.\pipe\dockerVpnKitDiagnostics
[11:09:23.523][VpnKit         ][Info   ] Started
[11:09:23.523][PowerMode      ][Info   ] Stop
[11:09:23.523][HyperV         ][Info   ] Stop
[11:09:23.524][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:09:23.529][HyperV         ][Info   ] Script started at 11:09:23.529
[11:09:23.543][HyperV         ][Info   ] Module loaded at 11:09:23.543
[11:09:23.554][VpnKit         ][Info   ] com.docker.slirp.exe: Logging to stdout (stdout:true DEBUG:false)
[11:09:23.554][VpnKit         ][Info   ] com.docker.slirp.exe: Setting handler to ignore all SIGPIPE signals
[11:09:23.554][VpnKit         ][Info   ] com.docker.slirp.exe: vpnkit version c41f7c8589352c95b14de636c895e8fbd72222e5 with hostnet version   uwt version 0.0.3 hvsock version 0.13.0 
[11:09:23.554][VpnKit         ][Info   ] com.docker.slirp.exe: starting port forwarding server on port_control_url:hyperv-connect://b668b918-98f6-4bc5-ba5c-927c70429d8e vsock_path:
[11:09:23.554][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to b668b918-98f6-4bc5-ba5c-927c70429d8e:0B95756A-9985-48AD-9470-78E060895BE7
[11:09:23.558][VpnKit         ][Info   ] com.docker.slirp.exe: connecting to b668b918-98f6-4bc5-ba5c-927c70429d8e:30D48B34-7D27-4B0B-AAAF-BBBED334DD59
[11:09:23.559][VpnKit         ][Error  ] com.docker.slirp.exe: While watching /etc/resolv.conf: ENOENT
[11:09:23.559][VpnKit         ][Info   ] com.docker.slirp.exe: hosts file has bindings for 
[11:09:23.565][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[11:09:23.565][HyperV         ][Debug  ] [stop] took 00:00:00.0419930 to run
[11:09:23.565][OptimizeDisk   ][Info   ] Optimize
[11:09:23.565][PowerShell     ][Info   ] Run script...
[11:09:24.656][Moby           ][Info   ] Stop
[11:09:24.663][VpnKit         ][Info   ] Killing existing com.docker.slirp with PID 1984
[11:09:24.669][DataKit        ][Info   ] Killing existing com.docker.db with PID 1844
[11:09:24.672][HyperV         ][Info   ] Destroy
[11:09:24.673][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[11:09:24.678][HyperV         ][Info   ] Script started at 11:09:24.678
[11:09:24.690][HyperV         ][Info   ] Module loaded at 11:09:24.690
[11:09:24.706][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[11:09:24.706][HyperV         ][Info   ] Destroying Switch DockerNAT...
[11:09:25.797][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[11:09:25.852][HyperV         ][Debug  ] [destroy] took 00:00:01.1799022 to run
[11:09:25.852][Firewall       ][Info   ] Closing ports...
[11:09:25.852][Firewall       ][Info   ] Removing all existing rules...
[11:09:25.923][Firewall       ][Info   ] All existing rules are removed.
[11:09:25.923][Firewall       ][Info   ] Ports are closed
[11:09:25.923][HyperVGuids    ][Info   ] Removing GUIDs...
[11:09:25.925][HyperVGuids    ][Info   ] GUIDs removed
[11:09:25.925][NamedPipeServer][Error  ] Unable to execute Start: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID B668B918-98F6-4BC5-BA5C-927C70429D8E)

'MobyLinuxVM' failed to start worker process: An invalid HANDLE was specified. (0xC0000008). (Virtual machine ID B668B918-98F6-4BC5-BA5C-927C70429D8E)
at Start-MobyLinuxVM, <No file>: line 287
at <ScriptBlock>, <No file>: line 382    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[11:09:26.049][NamedPipeClient][Error  ] Unable to send Start: Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID B668B918-98F6-4BC5-BA5C-927C70429D8E)

'MobyLinuxVM' failed to start worker process: An invalid HANDLE was specified. (0xC0000008). (Virtual machine ID B668B918-98F6-4BC5-BA5C-927C70429D8E)
at Start-MobyLinuxVM, <No file>: line 287
at <ScriptBlock>, <No file>: line 382
[11:09:26.050][Notifications  ][Error  ] Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID B668B918-98F6-4BC5-BA5C-927C70429D8E)

'MobyLinuxVM' failed to start worker process: An invalid HANDLE was specified. (0xC0000008). (Virtual machine ID B668B918-98F6-4BC5-BA5C-927C70429D8E)
at Start-MobyLinuxVM, <No file>: line 287
at <ScriptBlock>, <No file>: line 382

**Comment by friism** [comment]
Can you try the Edge version to see if a later version addresses your problem? Also, do you have Comodo installed? https://superuser.com/questions/1110408/hyper-v-fail-to-start-any-virtual-machine-an-invalid-handler-was-specified

**Comment by Mohamed3on** [comment]
Same problem. Tried uninstalling/reinstalling, disabling/enabling HyperV with no luck.
