### ISSUE TITLE
Problem switching from Linux Container to Windows Container.  

### ISSUE THREAD

**Issue by patware** [docker/for-win#6964]
- [X] I have tried with the latest version of my channel (Stable or Edge)
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: 
    - 41B04787-9E9F-4DCD-B38C-77BD576F5EA0/20200530032637
    - 41B04787-9E9F-4DCD-B38C-77BD576F5EA0/20200530033828

### Expected behavior
I should switch from linux to windows containers and back without exception.

### Actual behavior
Popup Dialog : An Error occured

Docker.Core.HttpBadResponseException:
Unhandled exception: Time out has expired and the operation has not been completed.
   at Docker.Core.Logging.ClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\ClientExceptionInterceptor.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<StartWindowsContainersAsync>d__6.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WindowsContainersEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WindowsContainersEngine.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
Original stacktrace:
   at System.ServiceProcess.ServiceController.WaitForStatus(ServiceControllerStatus desiredStatus, TimeSpan timeout)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 211
   at Docker.Backend.HttpAPI.WindowsContainersController.Start(WindowsContainerStartRequest request) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\WindowsContainersController.cs:line 42
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

### Information

  - Is it reproducible? yes.  I tried uninstalling Docker for Windows, Hyper-V/container features and started over, following [MS docs](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/configure-docker-daemon#how-to-uninstall-docker)
  - Is the problem new?  Yes, I've been able to switch before without a problem.  
  - Did the problem appear with an update?  I don't think so.  The only thing I can think of is that I created an Hyper-V virtual machine and created a new External Switch, it's about that time it started to fail miserably on many instances.

  - Windows Version: 2004 (OS Build 19041.264)
  - Docker Desktop Version: Version 2.3.0.3 (45519) Engine 19.03.8
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
    - Real Windows 10 PC

### Steps to reproduce the behavior
  1. Start docker for windows (linux container)
  2. Switch to Windows Containers...  working, working, working, boom.

Ho, I also tried deleted the AppData\Roaming\Docker\* files.  Same.  

Last hint... in the logs: I saw this.

[23:38:27.142][LoggingMessageHandler][Info   ] [6169a243] <BackendAPIClient end> POST http://backend/windowscontainers/start -> 500 InternalServerError (took 30345ms)
[23:38:27.149][LoggingMessageHandler][Info   ] [9013dd82] <BackendAPIClient start> POST http://backend/windowscontainers/stop
[23:38:28.258][LoggingMessageHandler][Info   ] [9013dd82] <BackendAPIClient end> POST http://backend/windowscontainers/stop -> 204 NoContent (took 1109ms)
[23:38:28.258][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[23:38:28.258][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[23:38:28.259][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from WindowsContainers
[23:38:28.259][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"windows","date":1590809908}
[23:38:28.260][SystrayNotifications][Error  ] Unhandled exception: Time out has expired and the operation has not been completed.

Pat

**Comment by patware** [comment]
I found out about another MS [troubleshooting guide](https://docs.microsoft.com/en-us/virtualization/windowscontainers/troubleshooting) 

I have many errors in the Network validation portion:

Describing Container network is created
 [+] At least one local container network is available 1.1s
 [-] At least one NAT, Transparent, or L2Bridge Network exists 22ms
   Expected {0} to be greater than {0}
   218:       $totalnets | Should BeGreaterThan 0
   at <ScriptBlock>, <No file>: line 218
 [-] NAT Network's vSwitch is internal 18ms
   Expected: {Internal}
   But was:  {}
   223:       $switchType | Should Be "Internal"
   at <ScriptBlock>, <No file>: line 223
 [+] A Windows NAT is configured if a Docker NAT network exists 266ms
 [-] Specified Network Gateway IP for NAT network is assigned to Host vNIC 12ms
   Expected: value to not be empty
   237:       $natGatewayIP | Should Not BeNullOrEmpty
   at <ScriptBlock>, <No file>: line 237
 [-] NAT Network's internal prefix does not overlap with external IP' 20ms
   Expected {0} to be greater than {0}
   264:         $hostips.Count | Should BeGreaterThan 0
   at <ScriptBlock>, <No file>: line 264

I've slept 3.5 hours in the last two days, I'll put this on hold and check back tomorrow ;)
