### ISSUE TITLE
After enabling wsl 2, Start failed with Failed to check distro: exit code: -1

### ISSUE THREAD

**Issue by melaniejones731** [docker/for-win#6967]
- [x ] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
On start, docker desktop will achieve started state

### Actual behavior
Docker failed to start, and docker failed to stop.

### Information

  - Windows Version: Version 2004 (OS Build 19041.264)
  - Docker Desktop Version: 2.3.0.3 (45519) stable
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: both...somewhat
[diagnostics.log](https://github.com/docker/for-win/files/4705391/diagnostics.log)

### Steps to reproduce the behavior

  1. I encountered proxy issues trying to build a project using an older version of docker for windows. The entire project built via docker-compose up, but I couldn't access the UI on localhost. It was very close to working.
  2. A co-worker was using wsl and windows terminal, and I thought that might be a good solution. So I downloaded all the required windows updates and docker desktop for wsl.
3. After installing, the docker desktop no longer starts. There is an access denied error in the logfiles: 
[02:48:40.086][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1590828520}
[02:48:40.087][SystrayNotifications][Info   ] Docker is starting
[02:48:40.091][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[02:48:40.095][LoggingMessageHandler][Info   ] [4a6d1996] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[02:48:40.419][WSL2Provisioning  ][Error  ] Failed to check distro: exit code: -1
 stdout: Access is denied.

 stderr: 
[02:48:40.452][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[02:48:40.599][LinuxWSL2Engine   ][Info   ] Stopping engine
[02:48:40.722][WSL2Provisioning  ][Error  ] Failed to check distro: exit code: -1
 stdout: Access is denied.

 stderr: 
[02:48:40.723][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.UnstableState to state change sink
[02:48:40.723][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.UnstableState sent to state change sink
[02:48:40.723][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.UnstableState from LinuxWSL2
[02:48:40.725][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1590828520}
[02:48:40.726][SystrayNotifications][Info   ] Docker Desktop failed to stop
[02:48:40.755][Engines           ][Error  ] Start failed with Failed to check distro: exit code: -1
 stdout: Access is denied.

I have tried restarting, and uninstalling and reinstalling as well as this script to completely remove docker, and then reinstall docker desktop. https://success.docker.com/article/how-to-completely-remove-docker-in-windows-10

I don't know what to do at this point.

**Comment by melaniejones731** [comment]
A further symptom of the issue - if I switch to windows containers, then docker will start. However, after switching to windows containers I cannot switch back to Linux containers now, and I also cannot reset to factory settings due to error access is denied.

![image](https://user-images.githubusercontent.com/28410534/83324936-b73ded00-a225-11ea-91d1-f5ec2af4a2f9.png)

**Comment by melaniejones731** [comment]
Crash report: D12C03F2-86E2-4EE6-8A23-3DCC241ACC99/20200530092830

**Comment by StefanScherer** [comment]
This looks like an issue with WSL 2. Could you run the following command in a PowerShell terminal?

```
wsl -l -v
```

This should list the installed WSL distros and the version of it. Something similar is called from Docker Desktop before we log "Failed to check distro".

I couldn't find a good matching issue at https://github.com/microsoft/WSL repo, but https://github.com/microsoft/WSL/issues/4141 may be related. There is also a link to gather more information.

What you could try to do is to check if WSL 2 works itself. Set the version of WSL to version 2:

```
wsl --set-default-version 2
```

Then install a WSL distro from Microsoft Store, eg. an Ubuntu distro.

**Comment by melaniejones731** [comment]
Hi Stefan, thank you for your response. Interestingly, when I run this command from the Windows Terminal Power Shell instance, I see my Ubuntu instances and they claim to be version 2 WSL. 

![terminalpic](https://user-images.githubusercontent.com/28410534/83337626-7a501580-a27a-11ea-9705-8420456b957b.png)

However, when I run the same commands from Windows PowerShell (as admin), I get an Access denied message similar to what is shown in Docker for Windows.

![powershellpic](https://user-images.githubusercontent.com/28410534/83337625-791ee880-a27a-11ea-95eb-2e1f7ce13d32.png)

Do you think resolving this WSL issue will also resolve the problem where I am unable to switch back from windows containers to linux containers? 

I will add this response on the ticket you referenced as well.

**Comment by StefanScherer** [comment]
Yes, I think this "Access denied" error is related to the problem switching back to Linux containers.
I don't know a solution for that.
In the meantime what you could do is to turn off the WSL 2 backend in the Docker Desktop settings and then try to switch to Linux container mode. This starts Docker Desktop with the Hyper-V backend as in previous Windows versions.

**Comment by melaniejones731** [comment]
I have attempted to do that, but unchecking the WSL 2 option results in a crash:

D12C03F2-86E2-4EE6-8A23-3DCC241ACC99/20200531163906

**Comment by StefanScherer** [comment]
Oh dear. What I see in the diagnostics Hyper-V has problems to get  2GB of RAM: 

"Start failed with Unhandled exception: job failed with message: 'DockerDesktopVM' failed to start. (Virtual machine ID 40CAA6D8-18FE-49DB-8CB1-967AEDC268B6)
'DockerDesktopVM' is unable to allocate 2048 MB of RAM: Insufficient system resources exist to complete the requested service."

You could try to shutdown WSL 2 to give back memory with `wsl --shutdown` or after a reboot.

**Comment by melaniejones731** [comment]
I did a reboot, and that got me back pretty much to where I started, which is here:

D12C03F2-86E2-4EE6-8A23-3DCC241ACC99/20200601034844

When I try to open localhost, I get error: 

This site can’t provide a secure connectionlocalhost sent an invalid response.
Try running Windows Network Diagnostics.
ERR_SSL_PROTOCOL_ERROR


That isn't related to this particular problem, but was what inspired me to try the wsl2 option.

I'm trying to bind to port 81 because 80 was listening to something else.

**Comment by StefanScherer** [comment]
But Docker Desktop itself starts up?
Port 80 seems to be used by IIS webserver.

**Comment by cybernetics** [comment]
same here. not able to start docker for desktop. using win 10 Pro (v 2004) with WSL2. during the installation I did not select the checkbox to enable WSL2 backend, still, it seems like it's trying to use WSL2 backend.

also submitted docker diagnostic with id: 96DD888D-3B30-4F40-A5F5-BC139A7300EB/20200629051046

getting the following error during startup:

System.InvalidOperationException:
Failed to deploy distro docker-desktop to %localappdata%\Docker\wsl\distro: exit code: -1
 stdout: Error: 0xffffffff


 stderr: 
   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__16.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

**Comment by melaniejones731** [comment]
Hi @StefanScherer - I still have this issue, and think it has something to do with the way Ubuntu is installed - I was wondering if you have seen anything else like this since May/June? I would really like to try to use Docker for Windows with WSL2.

**Comment by StefanScherer** [comment]
Hi @melaniejones731 - oh that's sad that you still have trouble. I'm not aware we had this issue reported by other users.
I've read the ticket again, but I don't have any recommendations. 
It seems like a WSL 2 problem. So I only have general suggestions like getting all Windows updates, try latest Docker Desktop, remove the WSL features - reboot and install WSL again, or at last start with a more clean Windows installation. 😬
