### ISSUE TITLE
In-app upgrade to 2.3.0.3 (45519) fails

### ISSUE THREAD

**Issue by spock-yh** [docker/for-win#6982]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 48959770-AECB-46D8-9A3F-F2151342B8E5/20200531213647

### Expected behavior
Clicking "Install Update" on the "new version is available" dialog should successfully install docker

### Actual behavior
Clicking "Install Update" seems to:
* stop the Hyper-V backend
* then asks for elevated privileges
* shows a "downloading package" window shows up
*  When the download is done, an "installation failed" window opens, with the following message:
```
Process InstallerCli.exe exited with code 1
   at CommunityInstaller.ExecAction.<DoAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<HandlePrePackagedExeAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()
```
* Once the dialog is closed, docker starts agian

### Information

  - Windows Version: 10 Pro (1903)
  - Docker Desktop Version:  2.3.0.2 (45183)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no

  - The update notification re-appears every time docker checks for the update
  - The installation fails consistently
  - attaching the install-log
[install-log.1.txt](https://github.com/docker/for-win/files/4708548/install-log.1.txt)

### Steps to reproduce the behavior

  1. Check for updates
  2. Click "Install Update"

**Comment by tfogdal** [comment]
Same issue here:
* Windows 10 Enterprise (1909)
* Docker Desktop Version 2.3.0.3 (45519)

Install log:
-------------------------------------------------
Process InstallerCli.exe exited with code 1
   at CommunityInstaller.ExecAction.<DoAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<HandlePrePackagedExeAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()
------------------------------------
