### ISSUE TITLE
Docker Issue- Crash

### ISSUE THREAD

**Issue by AshishMG** [docker/for-win#7009]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by AshishMG** [comment]
Log File Information

Version: 2.3.0.3 (45519)
Channel: stable
Sha1: 0356a6f23f086a8134d83ee38d99ffe55a121f02
Started on: 2020/06/02 13:48:03.120
Resources: c:\program files\docker\docker\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1909
Build: 18363
BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
File: C:\Users\ashish.m.g\AppData\Local\Docker\log.txt
CommandLine: "c:\program files\docker\docker\docker desktop.exe"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[13:48:03.274][GUI               ][Info   ] Starting...
[13:48:03.321][ComponentVersions ][Info   ] Edition community
[13:48:03.326][ComponentVersions ][Info   ] Edition community
[13:48:03.711][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[13:48:03.737][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[13:48:03.747][SegmentApi        ][Info   ] Usage statistic: Identify
[13:48:04.058][SegmentApi        ][Info   ] Usage statistic: appLaunched
[13:48:27.878][ApplicationTemplatesTracking][Info   ] Cannot list templates
[13:48:27.880][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[13:48:27.882][SegmentApi        ][Info   ] Usage statistic: heartbeat
[13:48:28.094][LoggingMessageHandler][Info   ] [914de3b4] <BackendAPIClient start> GET http://backend/version
[13:48:29.476][LoggingMessageHandler][Info   ] [914de3b4] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 1381ms)
[13:48:32.659][LoggingMessageHandler][Info   ] [b87bc3d6] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[13:48:32.777][LoggingMessageHandler][Info   ] [b87bc3d6] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 117ms)
[13:48:32.786][LoggingMessageHandler][Info   ] [2f7b1174] <BackendAPIClient start> POST http://backend/migrate/app
[13:48:32.791][LoggingMessageHandler][Info   ] [2f7b1174] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 5ms)
[13:48:32.797][Engines           ][Debug  ] Starting
[13:48:32.819][LoggingMessageHandler][Info   ] [08f85ca5] <BackendAPIClient start> POST http://backend/versionpack/enable
[13:48:33.015][LoggingMessageHandler][Info   ] [08f85ca5] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 196ms)
[13:48:33.026][GoBackendProcess  ][Info   ] Starting c:\program files\docker\docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[13:48:35.016][GoBackendProcess  ][Info   ] Started
[13:48:35.024][MutagenProcess    ][Info   ] Starting C:\ProgramData\Docker\cli-plugins\docker-mutagen.exe mutagen daemon run
[13:48:36.496][MutagenProcess    ][Info   ] Started
[13:48:36.510][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[13:48:36.512][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[13:48:36.516][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxHyperV
[13:48:36.526][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1591085916}
[13:48:36.527][SystrayNotifications][Info   ] Docker is starting
[13:48:40.045][LoggingMessageHandler][Info   ] [5d8a678f] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[13:48:40.508][LoggingMessageHandler][Info   ] [5d8a678f] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 462ms)
[13:48:40.512][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[13:48:40.517][LoggingMessageHandler][Info   ] [a5801571] <BackendAPIClient start> POST http://backend/hyperv/stop
[13:48:40.678][LoggingMessageHandler][Info   ] [a5801571] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 161ms)
[13:48:40.696][MutagenProcess    ][Info   ] [forwarding] Looking for existing sessions
[13:48:40.700][MutagenProcess    ][Info   ] [forwarding] Session manager initialized
[13:48:40.700][MutagenProcess    ][Info   ] [sync] Looking for existing sessions
[13:48:40.702][MutagenProcess    ][Info   ] [sync] Session manager initialized
[13:48:40.703][VpnKitBridge      ][Info   ] Starting c:\program files\docker\docker\resources\vpnkit-bridge.exe --addr listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3 host
[13:48:41.198][LoggingMessageHandler][Info   ] [dc7acef3] <Server start> GET http://unix/versions
[13:48:41.328][LoggingMessageHandler][Info   ] [dc7acef3] <Server end> GET http://unix/versions -> 200 OK (took 130ms)
[13:48:41.386][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[13:48:41.387][GoBackendProcess  ][Info   ] started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl
[13:48:41.394][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[13:48:41.398][GoBackendProcess  ][Info   ] enabling filesystem caching
[13:48:41.398][GoBackendProcess  ][Info   ] filesystem exports are:  (2)
[13:48:41.398][GoBackendProcess  ][Info   ] volume control server listening on \\\\.\\pipe\\dockerVolume
[13:48:41.400][GoBackendProcess  ][Info   ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[13:48:41.400][GoBackendProcess  ][Info   ] file ownership will be determined by the calling user (\"fake owner\" mode)
[13:48:41.400][GoBackendProcess  ][Info   ] using mfsymlinks
[13:48:41.412][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[13:48:41.413][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[13:48:42.282][VpnKitBridge      ][Info   ] Started
[13:48:47.523][VpnKitBridge      ][Info   ] listening on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[13:48:47.523][VpnKitBridge      ][Info   ] waiting for connection on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[13:48:48.527][IsoConfig         ][Info   ] Generating CA Cert Bundle
[13:48:48.577][IsoConfig         ][Info   ] CA Cert Bundle Generated
[13:48:55.611][LoggingMessageHandler][Info   ] [13707e15] <BackendAPIClient start> POST http://backend/hyperv/create
[13:48:56.407][LoggingMessageHandler][Info   ] [13707e15] <BackendAPIClient end> POST http://backend/hyperv/create -> 500 InternalServerError (took 796ms)
[13:48:56.429][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[13:48:56.429][LoggingMessageHandler][Info   ] [7fd02abe] <BackendAPIClient start> POST http://backend/hyperv/stop
[13:48:56.831][LoggingMessageHandler][Info   ] [7fd02abe] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 401ms)
[13:48:56.841][VpnKitBridge      ][Info   ] Killing existing vpnkit-bridge with PID 15376
[13:48:56.870][LoggingMessageHandler][Info   ] [d8086ff6] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[13:48:57.979][LoggingMessageHandler][Info   ] [d8086ff6] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 1109ms)
[13:48:57.987][LoggingMessageHandler][Info   ] [41d23c7b] <BackendAPIClient start> GET http://backend/hyperv/check-virtualization
[13:48:58.020][LoggingMessageHandler][Info   ] [41d23c7b] <BackendAPIClient end> GET http://backend/hyperv/check-virtualization -> 204 NoContent (took 32ms)
[13:48:58.021][LoggingMessageHandler][Info   ] [e4f92428] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[13:48:58.117][LoggingMessageHandler][Info   ] [e4f92428] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 96ms)
[13:48:58.117][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[13:48:58.117][LoggingMessageHandler][Info   ] [d23aee8c] <BackendAPIClient start> POST http://backend/hyperv/stop
[13:48:58.473][LoggingMessageHandler][Info   ] [d23aee8c] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 355ms)
[13:48:58.492][VpnKitBridge      ][Info   ] Starting c:\program files\docker\docker\resources\vpnkit-bridge.exe --addr listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3 host
[13:48:59.498][VpnKitBridge      ][Info   ] Started
[13:48:59.498][IsoConfig         ][Info   ] Generating CA Cert Bundle
[13:48:59.538][IsoConfig         ][Info   ] CA Cert Bundle Generated
[13:49:00.985][VpnKitBridge      ][Info   ] listening on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[13:49:00.987][VpnKitBridge      ][Info   ] waiting for connection on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[13:49:05.309][LoggingMessageHandler][Info   ] [636dc265] <BackendAPIClient start> POST http://backend/hyperv/create
[13:49:06.211][LoggingMessageHandler][Info   ] [636dc265] <BackendAPIClient end> POST http://backend/hyperv/create -> 500 InternalServerError (took 902ms)
[13:49:06.212][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[13:49:06.212][LoggingMessageHandler][Info   ] [316edaea] <BackendAPIClient start> POST http://backend/hyperv/stop
[13:49:06.556][LoggingMessageHandler][Info   ] [316edaea] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 343ms)
[13:49:06.567][VpnKitBridge      ][Info   ] Killing existing vpnkit-bridge with PID 7180
[13:49:06.579][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[13:49:06.579][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[13:49:06.579][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxHyperV
[13:49:06.582][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1591085946}
[13:49:06.583][SystrayNotifications][Error  ] Unhandled exception: Sequence contains no elements.
[13:49:06.646][GUI               ][Info   ] Sending Bugsnag report b3b08322-4ec8-4300-8258-bc333fbc4d52...
[13:49:06.784][GUI               ][Info   ] Bugsnag report b3b08322-4ec8-4300-8258-bc333fbc4d52 sent
[13:49:06.786][SegmentApi        ][Info   ] Usage statistic: eventCrash
[13:49:06.788][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'c:\program files\docker\docker\resources\com.docker.diagnose.exe' gather.
[13:49:06.978][Engines           ][Error  ] Start failed with Unhandled exception: Sequence contains no elements.
   at Docker.Core.Logging.ClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\ClientExceptionInterceptor.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<CreateHyperVVMAsync>d__10.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__24.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 109)
[13:49:09.344][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[13:49:09.345][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[13:49:09.346][GoBackendProcess  ][Info   ] mutagen sync list --output json
[13:49:13.519][GoBackendProcess  ][Info   ] mutagen C:\\ProgramData\\Docker\\cli-plugins\\docker-mutagen.exe mutagen sync list --output json: null\n
[13:49:13.519][GoBackendProcess  ][Info   ] external: GET /sync 200 \"Go-http-client/1.1\" \"\
[13:49:55.825][ErrorReportWindow ][Info   ] Open logs
[13:50:59.001][ErrorReportWindow ][Info   ] Open logs
[13:54:05.555][Diagnostics       ][Info   ] Diagnostics cancelled by user
