### ISSUE TITLE
Docker for Windows Installation Error - Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

### ISSUE THREAD

**Issue by seanius007** [docker/for-win#706]
### Expected behavior
Install Hyper-V; enable virtualisation in BIOS; Install Docker for Windows 
Docker for Windows starts without errors

### Actual behavior
Fails to start with the following error - Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

### Information

  - Diagnostic ID - 98AEC4B0-C706-4B0E-AB83-07B445D834D8/2017-05-05_11-31-13

  - Log file:

Version: 17.05.0-ce-rc1-win8 (11189)
Channel: edge
Sha1: 73d01bb48e39db1d7d76f279a68f7fadc46b15a1
Started on: 2017/05/05 11:28:42.450
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1511
Build: 10586
BuildLabName: 10586.839.amd64fre.th2_release.170303-1605
CommandLine: "C:\Program Files\Docker\Docker\Docker for windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:28:42.681][GUI            ][Info   ] Starting...
[11:28:43.350][Tracking       ][Info   ] Crash report and usage statistics are enabled
[11:28:43.358][SegmentApi     ][Info   ] Usage statistic: appLaunched
[11:28:43.579][NamedPipeClient][Info   ] Sending Version()...
[11:28:43.597][NamedPipeClient][Info   ] Received response for Version
[11:28:43.600][SegmentApi     ][Info   ] Usage statistic: heartbeat
[11:22:45.834][BackendServer  ][Info   ] Started
[11:28:43.596][NamedPipeServer][Info   ] Version()
[11:28:43.596][NamedPipeServer][Info   ] Version done in 00:00:00.
[11:28:44.216][SegmentApi     ][Info   ] Usage statistic: eventElectedForFeature
[11:28:44.218][SegmentApi     ][Info   ] Usage statistic: stateFeatureEnabled
[11:28:44.580][Notifications  ][Info   ] Docker is starting...
[11:28:44.638][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[11:28:44.642][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[11:28:44.649][PowerMode      ][Info   ] Stop
[11:28:44.655][HyperV         ][Info   ] Stop
[11:28:44.673][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:28:44.677][PowerShell     ][Info   ] Creating a Runspace Pool...
[11:28:45.803][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[11:28:45.887][HyperV         ][Info   ] Script started at 11:28:45.878
[11:28:50.328][HyperV         ][Info   ] Module loaded at 11:28:50.328
[11:28:50.665][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:28:50.666][HyperV         ][Debug  ] [stop] took 00:00:06.0082205 to run
[11:28:50.667][OptimizeDisk   ][Info   ] Optimize
[11:28:50.668][PowerShell     ][Info   ] Run script...
[11:28:50.697][Moby           ][Info   ] Stop
[11:28:50.726][PowerMode      ][Info   ] Start
[11:28:50.727][HyperV         ][Info   ] Create
[11:28:50.728][HyperVGuids    ][Info   ] Installing GUIDs...
[11:28:50.729][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[11:28:50.733][Firewall       ][Info   ] Removing all existing rules...
[11:28:50.741][HyperVGuids    ][Info   ] GUIDs installed
[11:28:50.742][HyperV         ][Info   ] Script started at 11:28:50.742
[11:28:50.823][Firewall       ][Info   ] All existing rules are removed.
[11:28:50.824][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[11:28:50.845][Firewall       ][Info   ] Opening ports for SMB...
[11:28:50.870][Firewall       ][Info   ] Ports are opened
[11:28:50.898][HyperV         ][Info   ] Module loaded at 11:28:50.898
[11:28:51.191][HyperV         ][Info   ] Enabled workaround for Build 10586 VMSwitch issue
[11:29:09.524][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:29:22.518][HyperV         ][Info   ] Switch created.
[11:29:24.895][Linux          ][Error  ] Failed to start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

. Let's retry
[11:29:24.898][PowerShell     ][Info   ] Run script...
[11:29:40.095][HyperV         ][Info   ] Hyper-V is running
[11:29:40.095][PowerMode      ][Info   ] Stop
[11:29:40.095][HyperV         ][Info   ] Stop
[11:29:40.096][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:29:40.112][HyperV         ][Info   ] Script started at 11:29:40.112
[11:29:40.264][HyperV         ][Info   ] Module loaded at 11:29:40.264
[11:29:40.292][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:29:40.292][HyperV         ][Debug  ] [stop] took 00:00:00.1970080 to run
[11:29:40.293][OptimizeDisk   ][Info   ] Optimize
[11:29:40.293][PowerShell     ][Info   ] Run script...
[11:29:40.316][Moby           ][Info   ] Stop
[11:29:40.344][HyperV         ][Info   ] Destroy
[11:29:40.345][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[11:29:40.379][HyperV         ][Info   ] Script started at 11:29:40.378
[11:29:40.518][HyperV         ][Info   ] Module loaded at 11:29:40.518
[11:29:40.544][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:29:40.547][HyperV         ][Info   ] Destroying Switch DockerNAT...
[11:29:58.793][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[11:29:58.863][HyperV         ][Debug  ] [destroy] took 00:00:18.5190529 to run
[11:29:58.864][Firewall       ][Info   ] Closing ports...
[11:29:58.865][Firewall       ][Info   ] Removing all existing rules...
[11:29:59.113][Firewall       ][Info   ] All existing rules are removed.
[11:29:59.115][Firewall       ][Info   ] Ports are closed
[11:29:59.115][HyperVGuids    ][Info   ] Removing GUIDs...
[11:29:59.125][HyperVGuids    ][Info   ] GUIDs removed
[11:29:59.125][HyperV         ][Info   ] Create
[11:29:59.130][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[11:29:59.151][HyperV         ][Info   ] Script started at 11:29:59.151
[11:29:59.389][HyperV         ][Info   ] Module loaded at 11:29:59.389
[11:29:59.634][HyperV         ][Info   ] Enabled workaround for Build 10586 VMSwitch issue
[11:30:18.742][HyperV         ][Info   ] Creating Switch: DockerNAT...
[11:30:37.284][HyperV         ][Info   ] Switch created.
[11:30:39.129][PowerMode      ][Info   ] Stop
[11:30:39.129][HyperV         ][Info   ] Stop
[11:30:39.130][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[11:30:39.152][HyperV         ][Info   ] Script started at 11:30:39.150
[11:30:39.485][HyperV         ][Info   ] Module loaded at 11:30:39.485
[11:30:39.689][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:30:39.690][HyperV         ][Debug  ] [stop] took 00:00:00.5610309 to run
[11:30:39.690][OptimizeDisk   ][Info   ] Optimize
[11:30:39.690][PowerShell     ][Info   ] Run script...
[11:30:39.916][Moby           ][Info   ] Stop
[11:30:39.951][HyperV         ][Info   ] Destroy
[11:30:39.952][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[11:30:39.973][HyperV         ][Info   ] Script started at 11:30:39.973
[11:30:40.402][HyperV         ][Info   ] Module loaded at 11:30:40.401
[11:30:40.590][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[11:30:40.592][HyperV         ][Info   ] Destroying Switch DockerNAT...
[11:31:12.955][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[11:31:12.997][HyperV         ][Debug  ] [destroy] took 00:00:33.0465750 to run
[11:31:12.998][Firewall       ][Info   ] Closing ports...
[11:31:12.998][Firewall       ][Info   ] Removing all existing rules...
[11:31:13.097][Firewall       ][Info   ] All existing rules are removed.
[11:31:13.097][Firewall       ][Info   ] Ports are closed
[11:31:13.097][HyperVGuids    ][Info   ] Removing GUIDs...
[11:31:13.098][HyperVGuids    ][Info   ] GUIDs removed
[11:31:13.222][NamedPipeServer][Error  ] Unable to execute Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 120
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 44
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 140
[11:31:13.465][NamedPipeClient][Error  ] Unable to send Start: Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

[11:31:13.469][Notifications  ][Error  ] Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The object already exists.

[11:31:13.558][CrashReport    ][Info   ] Preparing package to send with the diagnostics
[11:31:13.570][NamedPipeClient][Info   ] Sending GetDebugInfo()...
[11:31:13.572][NamedPipeClient][Info   ] Sending DownloadVpnKitLogs(C:\Users\sargents\AppData\Local\Temp\zd4xddwe.ueh\pcap.tar)...
[11:31:13.579][NamedPipeClient][Info   ] Sending DownloadVmLogs(C:\Users\sargents\AppData\Local\Temp\zd4xddwe.ueh\mobyLogs.tar)...
[11:31:13.776][NamedPipeClient][Info   ] Sending DownloadWinContainersDebugInfo(C:\Users\sargents\AppData\Local\Temp\zd4xddwe.ueh\win_containers)...
[11:31:15.473][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo(C:\Users\sargents\AppData\Local\Temp\zd4xddwe.ueh\win_containers)
[11:31:15.512][NamedPipeClient][Info   ] Received response for DownloadVpnKitLogs
[11:31:15.478][NamedPipeServer][Info   ] GetDebugInfo()
[11:31:15.479][NamedPipeServer][Info   ] DownloadVmLogs(C:\Users\sargents\AppData\Local\Temp\zd4xddwe.ueh\mobyLogs.tar)
[11:31:15.482][NamedPipeServer][Info   ] DownloadVpnKitLogs(C:\Users\sargents\AppData\Local\Temp\zd4xddwe.ueh\pcap.tar)
[11:31:15.501][VpnKit         ][Warning] Unable to download logs: The operation has timed out.
[11:31:15.501][NamedPipeServer][Info   ] DownloadVpnKitLogs done in 00:00:00.0195744.
[11:31:15.546][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[11:31:15.696][NamedPipeClient][Info   ] Received response for DownloadVmLogs
[11:31:15.695][HyperV         ][Warning] Unable to download logs: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Hyper-V was unable to find a virtual machine with name "MobyLinuxVM".
[11:31:15.695][NamedPipeServer][Info   ] DownloadVmLogs done in 00:00:00.2160856.
[11:32:09.298][NamedPipeClient][Info   ] Received response for DownloadWinContainersDebugInfo
[11:32:09.296][NamedPipeServer][Info   ] DownloadWinContainersDebugInfo done in 00:00:53.8232542.
[11:32:31.611][NamedPipeServer][Info   ] GetDebugInfo done in 00:01:16.1329369.
[11:32:31.621][NamedPipeClient][Info   ] Received response for GetDebugInfo
[11:32:33.991][CrashReport    ][Info   ] Uploading diagnostics...
[11:32:41.064][CrashReport    ][Info   ] Diagnostics successfully uploaded (98AEC4B0-C706-4B0E-AB83-07B445D834D8/2017-05-05_11-31-13)
[11:32:41.119][GUI            ][Info   ] Sending Bugsnag report a982f636-5133-42a1-b02d-a395038f44fb...
[11:32:43.866][GUI            ][Info   ] Bugsnag report a982f636-5133-42a1-b02d-a395038f44fb sent
[11:33:55.829][ErrorReportWindow][Info   ] Open logs
[11:47:02.888][ErrorReportWindow][Info   ] Open logs

### Steps to reproduce the behavior
Install Hyper-V; enable virtualisation in BIOS; Install Docker for Windows

**Comment by seanius007** [comment]
I have reviewed Issue #599 and the tactical work around works.  A permanent fix is still needed.  Closing issue.
