### ISSUE TITLE
Docker for windows fails to start

### ISSUE THREAD

**Issue by NovaLogicDev** [docker/for-win#7110]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:23B4FDFD-EDAA-44BF-B513-231C2627515C/20200607232427

### Expected behavior
Docker desktop for windows starts after system restart
### Actual behavior
Docker desktop for windows fails to start

```
 Docker.Core.DockerException:
Failed to start
   at Docker.LinuxkitDaemonStartup.<StartAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\LinuxkitDaemonStartup.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

### Information
  - Windows Version: Windows 10 Enterrpise, version 2004, OS build 19041.264
  - Docker Desktop Version: v2.3.0.3

Problem occurred after system restart, no windows updates, they are disabled this system has not been updated since it was installed from a fresh image 3 weeks ago. No updates of any kind have occurred nor did I make any changes to DD configuration.

### Steps to reproduce the behavior

  1. Restarted windows after stopping all containers
  2. Start DD

Logfile:
[log.txt](https://github.com/docker/for-win/files/4743289/log.txt)

**Comment by beeka** [comment]
Look similar to the issue I am having starting docker desktop, but with Windows 10 Pro 1909 build 18363.836

```
Docker.Core.DockerException:
Failed to start
   at Docker.LinuxkitDaemonStartup.<StartAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\LinuxkitDaemonStartup.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

Uploaded diagnostics ID 7CA390EB-1EB3-404C-8674-53EBB539AFB9/20200609130656

Factory reset got it working again... but no idea what has been lost.

**Comment by NovaLogicDev** [comment]
Looks like your issue was related to Hyper-V Linux backends. This one has to do with WSL2 backends.

**Comment by beeka** [comment]
They are indeed different... a cursory comparison of the stack trace felt similar at the time. Blame it on the frustration at "Failed to start" not helping me help myself:  I am using Hyper-V and could see the docker vm start, but closed without showing help... the log essentially tells me "failed to start" and not much else (the log should include something useful to google for). Looking at the number of recent issues that are equally nondescript I'll have to hope the reset fixed it for good.

**Comment by Moschti** [comment]
@NovaLogicDev I have exactly the same issue.

The only difference: I use Win10 Professional, version 2004 (OS build 19041.264). 
As WSL2 distro I use the default Ubuntu 18.04.4 LTS from the windows store without any customization.

[log.txt](https://github.com/docker/for-win/files/4891158/log.txt)

**Comment by instantsc** [comment]
Removing C:\ProgramData\DockerDesktop\vm-data seems to have fixed the issue for me. You'll lose your local containers/images, of course.

**Comment by PavelSosin-320** [comment]
Exactly the same with
OS: Windows 10 Pro
Edition: Professional
Id: 2004
Build: 20170
BuildLabName: 20170.1000.amd64fre.rs_prerelease.200710-1419
The problem started early with Build 20160.100
C:\ProgramData\DockerDesktop\vm-data is already empty

**Comment by PavelSosin-320** [comment]
The issue is obviously arround vpnkit
vpnkit.exe: Pipe.listen: caught (Failure "Failed to connect vmnet device")
But vmnet is something about vmware, not about hyper-v
I use WSL 2.0 based on lightweight Hyper-V  machine, so vmnet device is a fantom.

**Comment by grobacz** [comment]
I have a suspicion that you need to have WSL (Windows Subsystem for Linux) Windows feature enabled to start Docker. Could any of you confirm this?

**Comment by kimchunhe** [comment]
1. download [NoLsp.exe](www.proxifier.com/tmp/Test20200228/NoLsp.exe)
2. run **CMD** with administrator
3. execute command: 
`NoLsp.exe C:\windows\system32\wsl.exe`
