### ISSUE TITLE
After update to Winver 19645.1 I get stderr WSL 2 requires an update to its kernel component

### ISSUE THREAD

**Issue by rnwolf** [docker/for-win#7193]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0627D9A5-F188-464C-9800-511273C03C1B/20200611190615

### Expected behavior

Docker starts after power up.

### Actual behavior

Docker Desktop error screen.

Re-occurs after reboot.

```
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\rnwol\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: 
 stderr: WSL 2 requires an update to its kernel component. For information please visit https://aka.ms/wsl2kernel


   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__16.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92


```

### Information

  - Is the problem new? Yes
  - Did the problem appear with an update? Yes
  - Windows Version: Winver 
19645.1
  - Docker Desktop Version:  docker --version
Docker version 19.03.8, build afacb8b
  
### Steps to reproduce the behavior

Turn computer off/on

**Comment by rnwolf** [comment]
Downloaded the WSL2 kernel and reinstalled it from https://docs.microsoft.com/en-gb/windows/wsl/wsl2-kernel
again and now Docker is able to start without error.

**Comment by metcalfc** [comment]
Thanks rnwolf. That is the expected behavior for this release. It is a rough edge that for new installs of WSL2 won't be present. Microsoft wanted to separate the Linux portion into its own MSI so they can update it outside of the Windows OS patch cycle. So for this release (and hopefully this release only) you have to install the MSI separately. Effectively the Windows update removed it. Then you reinstall it via the MSI so it can be managed separately.

Thats what the stderr message was directing you to by pointing to: https://aka.ms/wsl2kernel

**Comment by rnwolf** [comment]
I still needed to run the following to get docker to startup again.

```
 wsl --unregister docker-desktop
 wsl --unregister docker-desktop-data
```

**Comment by gagneet** [comment]
As a workaround to get Docker working on a Windows Insider build.
- Uninstall Docker and WSL 2 kernel.
- Go to the Control Panel -> Programs -> Turn Windows features on or off
- Uncheck the following: Containers, Hyper-V, Windows Subsystem for Linux
- Restart the system
- Install Docker without the WSL2 enabled/checked in the first screen
- Go to the Control Panel -> Programs -> Turn Windows features on or off
- Turn on/check the Windows Subsystem for Linux
- Restart the system.

Do not install the WSL2 Kernel.

Docker should be up and running :-)

**Comment by nebuk89** [comment]
@simonferquel FYI 👀

**Comment by simonferquel** [comment]
Yes, for some reason, installing the Kernel package on current insider fast seem to break WSL 2. @benhillis are you aware of this ?
