### ISSUE TITLE
WSL2 backend always crash System.InvalidOperationException: Failed to deploy distro docker-desktop 

### ISSUE THREAD

**Issue by wdrdres3qew5ts21** [docker/for-win#7208]
My window 10 Enterprise with WSL2 backend integrated always crash like the logs below had any way to fix this ? I want to recover my important data inside WSL2 or how to make docker run again ?

  - [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 759D0CB8-4722-49F0-A635-EA83A7868FDD/20200612114453
````
Version: 2.3.0.3 (45519)
Channel: stable
Sha1: 0356a6f23f086a8134d83ee38d99ffe55a121f02
Started on: 2020/06/12 18:43:43.539
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 2004
Build: 19041
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\s.trakulmaiphol\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[18:43:43.797][GUI               ][Info   ] Starting...
[18:43:43.875][ComponentVersions ][Info   ] Edition community
[18:43:43.882][ComponentVersions ][Info   ] Edition community
[18:43:47.814][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[18:43:47.900][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[18:43:47.912][SegmentApi        ][Info   ] Usage statistic: Identify
[18:43:48.333][SegmentApi        ][Info   ] Usage statistic: appLaunched
[18:43:51.255][ApplicationTemplatesTracking][Info   ] Cannot list templates
[18:43:51.257][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[18:43:51.261][SegmentApi        ][Info   ] Usage statistic: heartbeat
[18:43:51.847][LoggingMessageHandler][Info   ] [38b79bb3] <BackendAPIClient start> GET http://backend/version
[18:43:53.776][LoggingMessageHandler][Info   ] [38b79bb3] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 1926ms)
[18:43:54.434][LoggingMessageHandler][Info   ] [966f1f3b] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[18:43:54.709][LoggingMessageHandler][Info   ] [966f1f3b] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 271ms)
[18:43:54.724][LoggingMessageHandler][Info   ] [29fdff6c] <BackendAPIClient start> POST http://backend/migrate/app
[18:43:54.734][LoggingMessageHandler][Info   ] [29fdff6c] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 10ms)
[18:43:54.748][Engines           ][Debug  ] Starting
[18:43:54.790][LoggingMessageHandler][Info   ] [9ccd2fa3] <BackendAPIClient start> POST http://backend/versionpack/enable
[18:43:55.167][LoggingMessageHandler][Info   ] [9ccd2fa3] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 376ms)
[18:43:55.415][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[18:43:55.423][GoBackendProcess  ][Info   ] Started
[18:43:55.427][MutagenProcess    ][Info   ] Starting C:\ProgramData\Docker\cli-plugins\docker-mutagen.exe mutagen daemon run
[18:43:55.431][MutagenProcess    ][Info   ] Started
[18:43:55.449][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[18:43:55.451][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[18:43:55.460][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxWSL2
[18:43:55.472][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1591962235}
[18:43:55.476][SystrayNotifications][Info   ] Docker is starting
[18:43:55.486][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[18:43:55.506][LoggingMessageHandler][Info   ] [5b7fb4b0] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[18:43:55.594][MutagenProcess    ][Info   ] [forwarding] Looking for existing sessions
[18:43:55.594][MutagenProcess    ][Info   ] [forwarding] Session manager initialized
[18:43:55.594][MutagenProcess    ][Info   ] [sync] Looking for existing sessions
[18:43:55.594][MutagenProcess    ][Info   ] [sync] Session manager initialized
[18:43:55.767][WSL2Provisioning  ][Info   ] Checking docker-desktop
[18:43:55.778][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\s.trakulmaiphol\AppData\Local\Docker\wsl\distro
[18:43:57.120][LoggingMessageHandler][Info   ] [5b7fb4b0] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 1613ms)
[18:43:57.748][DockerHub         ][Info   ] Login successfull
[18:43:58.222][LoggingMessageHandler][Info   ] [8e4f9a56] <Server start> GET http://unix/versions
[18:43:58.582][LoggingMessageHandler][Info   ] [8e4f9a56] <Server end> GET http://unix/versions -> 200 OK (took 360ms)
[18:43:59.002][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[18:43:59.005][GoBackendProcess  ][Info   ] started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl
[18:43:59.006][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[18:43:59.011][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[18:43:59.012][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[18:43:59.016][GoBackendProcess  ][Info   ] enabling filesystem caching
[18:43:59.017][GoBackendProcess  ][Info   ] filesystem exports are:  (2)
[18:43:59.021][GoBackendProcess  ][Info   ] volume control server listening on \\\\.\\pipe\\dockerVolume
[18:43:59.030][GoBackendProcess  ][Info   ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[18:43:59.030][GoBackendProcess  ][Info   ] file ownership will be determined by the calling user (\"fake owner\" mode)
[18:43:59.031][GoBackendProcess  ][Info   ] using mfsymlinks
[18:44:00.097][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\s.trakulmaiphol\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0xffffffff


 stderr: 
[18:44:00.110][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[18:44:00.531][LinuxWSL2Engine   ][Info   ] Stopping engine
[18:44:00.683][LoggingMessageHandler][Info   ] [71e63c50] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[18:44:02.953][LoggingMessageHandler][Info   ] [71e63c50] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 2270ms)
[18:44:03.386][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[18:44:03.386][LoggingMessageHandler][Info   ] [48f34a28] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[18:44:03.473][WSL2Provisioning  ][Info   ] Checking docker-desktop
[18:44:03.474][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\s.trakulmaiphol\AppData\Local\Docker\wsl\distro
[18:44:03.475][LoggingMessageHandler][Info   ] [48f34a28] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 88ms)
[18:44:06.296][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\s.trakulmaiphol\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0xffffffff


 stderr: 
[18:44:06.296][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[18:44:06.497][LinuxWSL2Engine   ][Info   ] Stopping engine
[18:44:06.542][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[18:44:06.542][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[18:44:06.542][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxWSL2
[18:44:06.544][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1591962246}
[18:44:06.544][SystrayNotifications][Error  ] Failed to deploy distro docker-desktop to C:\Users\s.trakulmaiphol\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0xffffffff


 stderr: 
[18:44:06.614][GUI               ][Info   ] Sending Bugsnag report 4c1648dc-fde7-4976-9261-9fa1deeb3ba6...
[18:44:06.753][GUI               ][Info   ] Bugsnag report 4c1648dc-fde7-4976-9261-9fa1deeb3ba6 sent
[18:44:06.757][SegmentApi        ][Info   ] Usage statistic: eventCrash
[18:44:06.762][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[18:44:07.148][Engines           ][Error  ] Start failed with Failed to deploy distro docker-desktop to C:\Users\s.trakulmaiphol\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0xffffffff


 stderr: 
   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__16.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__24.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 109)
[18:44:07.756][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[18:44:07.759][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[18:44:07.760][GoBackendProcess  ][Info   ] mutagen sync list --output json
[18:44:10.090][GoBackendProcess  ][Info   ] mutagen C:\\ProgramData\\Docker\\cli-plugins\\docker-mutagen.exe mutagen sync list --output json: null\n
[18:44:10.091][GoBackendProcess  ][Info   ] external: GET /sync 200 \"Go-http-client/1.1\" \"\
[18:44:47.735][SegmentApi        ][Info   ] Usage statistic: actionResetToDefault
[18:44:47.735][SystrayNotifications][Info   ] Docker Desktop is resetting to default...
[18:44:47.751][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.DestroyTransition to state change sink
[18:44:47.751][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.DestroyTransition sent to state change sink
[18:44:47.767][LoggingMessageHandler][Info   ] [540d4908] <BackendAPIClient start> POST http://backend/hyperv/destroy
[18:44:47.852][Diagnostics       ][Info   ] Diagnostics cancelled by user
[18:44:47.869][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.DestroyTransition from LinuxHyperV
[18:44:47.873][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"updating","Mode":"linux","date":1591962287}
[18:44:47.873][SystrayNotifications][Info   ] Docker Desktop is destroying...
[18:44:47.877][ErrorReportWindow ][Error  ] Could not gather diagnostics : User cancelled diagnostics..
[18:44:48.357][LoggingMessageHandler][Info   ] [540d4908] <BackendAPIClient end> POST http://backend/hyperv/destroy -> 204 NoContent (took 587ms)
[18:44:48.357][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StoppedState to state change sink
[18:44:48.357][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StoppedState sent to state change sink
[18:44:48.357][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.DestroyTransition to state change sink
[18:44:48.357][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.DestroyTransition sent to state change sink
[18:44:48.357][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StoppedState from LinuxHyperV
[18:44:48.357][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"stopped","Mode":"linux","date":1591962288}
[18:44:48.357][SystrayNotifications][Info   ] Docker has stopped
[18:44:48.357][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.DestroyTransition from WindowsContainers
[18:44:48.357][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"updating","Mode":"linux","date":1591962288}
[18:44:48.357][SystrayNotifications][Info   ] Docker Desktop is destroying...
[18:44:48.361][LoggingMessageHandler][Info   ] [930540be] <BackendAPIClient start> POST http://backend/windowscontainers/destroy
[18:44:48.451][LoggingMessageHandler][Info   ] [930540be] <BackendAPIClient end> POST http://backend/windowscontainers/destroy -> 204 NoContent (took 88ms)
[18:44:48.451][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StoppedState to state change sink
[18:44:48.451][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StoppedState sent to state change sink
[18:44:48.451][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.DestroyTransition to state change sink
[18:44:48.451][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.DestroyTransition sent to state change sink
[18:44:48.451][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StoppedState from WindowsContainers
[18:44:48.451][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"stopped","Mode":"linux","date":1591962288}
[18:44:48.451][SystrayNotifications][Info   ] Docker has stopped
[18:44:48.451][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.DestroyTransition from LinuxWSL2
[18:44:48.451][LinuxWSL2Engine   ][Info   ] Destroying distro
[18:44:48.451][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"updating","Mode":"linux","date":1591962288}
[18:44:48.451][SystrayNotifications][Info   ] Docker Desktop is destroying...
[18:44:48.524][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StoppedState to state change sink
[18:44:48.524][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StoppedState sent to state change sink
[18:44:48.536][Engines           ][Debug  ] Starting
[18:44:48.536][LoggingMessageHandler][Info   ] [be2cc619] <BackendAPIClient start> POST http://backend/versionpack/enable
[18:44:48.536][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StoppedState from LinuxWSL2
[18:44:48.536][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"stopped","Mode":"linux","date":1591962288}
[18:44:48.536][SystrayNotifications][Info   ] Docker has stopped
[18:44:48.565][LoggingMessageHandler][Info   ] [be2cc619] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 29ms)
[18:44:48.569][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[18:44:48.569][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[18:44:48.569][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxWSL2
[18:44:48.569][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[18:44:48.569][LoggingMessageHandler][Info   ] [ab789000] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[18:44:48.569][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1591962288}
[18:44:48.569][SystrayNotifications][Info   ] Docker is starting
[18:44:48.617][WSL2Provisioning  ][Info   ] Checking docker-desktop
[18:44:48.617][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\s.trakulmaiphol\AppData\Local\Docker\wsl\distro
[18:44:48.617][LoggingMessageHandler][Info   ] [ab789000] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 49ms)
[18:44:50.687][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\s.trakulmaiphol\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0xffffffff


 stderr: 
[18:44:50.687][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[18:44:50.813][LinuxWSL2Engine   ][Info   ] Stopping engine
[18:44:50.841][LoggingMessageHandler][Info   ] [b5ad43cc] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[18:44:51.120][LoggingMessageHandler][Info   ] [b5ad43cc] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 277ms)
[18:44:51.238][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[18:44:51.238][LoggingMessageHandler][Info   ] [a1653b11] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[18:44:51.283][WSL2Provisioning  ][Info   ] Checking docker-desktop
[18:44:51.283][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\s.trakulmaiphol\AppData\Local\Docker\wsl\distro
[18:44:51.287][LoggingMessageHandler][Info   ] [a1653b11] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 47ms)
[18:44:53.236][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\s.trakulmaiphol\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0xffffffff


 stderr: 
[18:44:53.236][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[18:44:53.411][LinuxWSL2Engine   ][Info   ] Stopping engine
[18:44:53.450][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[18:44:53.450][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[18:44:53.450][Engines           ][Error  ] Start failed with Failed to deploy distro docker-desktop to C:\Users\s.trakulmaiphol\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0xffffffff


 stderr: 
   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__16.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__24.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 109)
[18:44:53.450][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxWSL2
[18:44:53.450][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1591962293}
[18:44:53.450][SystrayNotifications][Error  ] Failed to deploy distro docker-desktop to C:\Users\s.trakulmaiphol\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Error: 0xffffffff


 stderr: 
[18:44:53.450][GUI               ][Info   ] Sending Bugsnag report 0e51b0a1-0993-47c6-9575-030b0574aab3...
[18:44:53.511][GUI               ][Info   ] Bugsnag report 0e51b0a1-0993-47c6-9575-030b0574aab3 sent
[18:44:53.511][SegmentApi        ][Info   ] Usage statistic: eventCrash
[18:44:53.511][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[18:44:53.583][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[18:44:53.584][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[18:44:53.585][GoBackendProcess  ][Info   ] mutagen sync list --output json
[18:44:55.912][GoBackendProcess  ][Info   ] mutagen C:\\ProgramData\\Docker\\cli-plugins\\docker-mutagen.exe mutagen sync list --output json: null\n
[18:44:55.912][GoBackendProcess  ][Info   ] external: GET /sync 200 \"Go-http-client/1.1\" \"\
[18:47:22.688][Diagnostics       ][Info   ] Uploading diagnostics 759D0CB8-4722-49F0-A635-EA83A7868FDD/20200612114453
[18:47:25.850][ErrorReportWindow ][Info   ] Open diagnostics
[18:47:38.419][ErrorReportWindow ][Info   ] Open diagnostics
[18:47:45.711][Diagnostics       ][Info   ] Uploaded succesfully diagnostics 759D0CB8-4722-49F0-A635-EA83A7868FDD/20200612114453
[18:49:59.055][ErrorReportWindow ][Info   ] Open logs
````
### Expected behavior
using wsl command and running docker with WSL2 integrated like normally
### Actual behavior
Crash with 0xffffffff
### Information

  - Windows Version: Window 10 Enterpeise, Id 2004, Build 19041
  - Docker Desktop Version: Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ... Ubuntu 18.04 from Microsoft Store
  2. ... Window10 Enterprise
  3. .. I got failed message all the time
![Alt Text](https://i.imgur.com/ha6AP96.png)

**Comment by gagneet** [comment]
As a workaround to get Docker working on a Windows Insider build.
- Uninstall Docker and WSL 2 kernel.
- Go to the Control Panel -> Programs -> Turn Windows features on or off
- Uncheck the following: Containers, Hyper-V, Windows Subsystem for Linux
- Restart the system
- Install Docker without the WSL2 enabled/checked in the first screen
- Go to the Control Panel -> Programs -> Turn Windows features on or off
- Turn on/check the Windows Subsystem for Linux
- Restart the system.

Do not install the WSL2 Kernel.

Docker should be up and running :-)

**Comment by wdrdres3qew5ts21** [comment]
Thank you very much I absolutely appreciate your help I can confirm that your methods can fix this error problem ヾ(≧▽≦*)o
I already found that I had ever open "Container for window/ Switched to Window Container" for once also with Hyper-V enabled. The ways to fix is you must **"Disabled Hyper-V/ Container for window"**
Close issues !!!!

**Comment by TeacherBiz** [comment]
Thank you! This worked for me too.
