### ISSUE TITLE
Docker Desktop 2.3.0.3 for windows 10 Does not start after installation

### ISSUE THREAD

**Issue by pathikreet** [docker/for-win#7250]
- [ Y] I have tried with the latest version of my channel (Stable or Edge)
  - [Y ] I have uploaded Diagnostics
  - Diagnostics ID: F352FC6E-93D1-478B-86CA-0FB2B1459109/20200615094546

### Expected behavior
Docker Desktop should start up normally
### Actual behavior
Docker Desktop does not start at all.
### Information

  - Windows Version: 10
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install latest stable release of Docker Desktop
  2. HyperV enabled
  3. Restart System.
  4. Run Docker Desktop as an Administrator.
  5. Docker tries to start the Linux HyperV backend.
  6. Docker desktop stops.
PFB the logs from the logfile:
Version: 2.3.0.3 (45519)
Channel: stable
Sha1: 0356a6f23f086a8134d83ee38d99ffe55a121f02
Started on: 2020/06/15 15:09:58.555
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1809
Build: 17763
BuildLabName: 17763.1.amd64fre.rs5_release.180914-1434
File: C:\Users\801876\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[15:10:05.813][GUI               ][Info   ] Starting...
[15:10:11.234][ComponentVersions ][Info   ] Edition community
[15:10:11.370][ComponentVersions ][Info   ] Edition community
[15:10:28.488][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[15:10:29.922][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[15:10:30.192][SegmentApi        ][Info   ] Usage statistic: Identify
[15:10:33.351][SegmentApi        ][Info   ] Usage statistic: appLaunched
[15:11:25.845][ApplicationTemplatesTracking][Info   ] Cannot list templates
[15:11:25.848][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[15:11:25.849][SegmentApi        ][Info   ] Usage statistic: heartbeat
[15:13:22.007][LoggingMessageHandler][Info   ] [21e9406e] <BackendAPIClient start> GET http://backend/version
[15:13:25.815][LoggingMessageHandler][Info   ] [21e9406e] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 3805ms)
[15:13:26.189][LoggingMessageHandler][Info   ] [399561fa] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[15:13:29.242][LoggingMessageHandler][Info   ] [399561fa] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 3051ms)
[15:13:29.255][LoggingMessageHandler][Info   ] [7a151c68] <BackendAPIClient start> POST http://backend/migrate/app
[15:13:29.269][LoggingMessageHandler][Info   ] [7a151c68] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 14ms)
[15:13:29.280][Engines           ][Debug  ] Starting
[15:13:29.353][LoggingMessageHandler][Info   ] [2c4cc9ab] <BackendAPIClient start> POST http://backend/versionpack/enable
[15:13:29.998][LoggingMessageHandler][Info   ] [2c4cc9ab] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 645ms)
[15:13:30.866][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[15:13:36.306][GoBackendProcess  ][Info   ] Started
[15:13:36.309][MutagenProcess    ][Info   ] Starting C:\ProgramData\Docker\cli-plugins\docker-mutagen.exe mutagen daemon run
[15:13:36.488][MutagenProcess    ][Info   ] Started
[15:13:36.496][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[15:13:36.696][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[15:13:36.702][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxHyperV
[15:13:36.719][MutagenProcess    ][Info   ] [forwarding] Looking for existing sessions
[15:13:36.758][MutagenProcess    ][Info   ] [forwarding] Session manager initialized
[15:13:36.758][MutagenProcess    ][Info   ] [sync] Looking for existing sessions
[15:13:36.762][MutagenProcess    ][Info   ] [sync] Session manager initialized
[15:13:36.837][LoggingMessageHandler][Info   ] [76bbfee3] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[15:13:37.035][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1592214216}
[15:13:37.269][SystrayNotifications][Info   ] Docker is starting
[15:13:40.595][LoggingMessageHandler][Info   ] [76bbfee3] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 3757ms)
[15:13:40.601][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[15:13:40.607][LoggingMessageHandler][Info   ] [6c2b62d4] <BackendAPIClient start> POST http://backend/hyperv/stop
[15:13:48.975][LoggingMessageHandler][Info   ] [0e8ec687] <Server start> GET http://unix/versions
[15:13:49.147][LoggingMessageHandler][Info   ] [0e8ec687] <Server end> GET http://unix/versions -> 200 OK (took 171ms)
[15:13:49.234][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[15:13:49.239][GoBackendProcess  ][Info   ] started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl
[15:13:49.241][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[15:13:49.247][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[15:13:49.262][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[15:13:49.264][GoBackendProcess  ][Info   ] enabling filesystem caching
[15:13:49.264][GoBackendProcess  ][Info   ] filesystem exports are:  (2)
[15:13:49.265][GoBackendProcess  ][Info   ] volume control server listening on \\\\.\\pipe\\dockerVolume
[15:13:49.268][GoBackendProcess  ][Info   ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[15:13:49.268][GoBackendProcess  ][Info   ] file ownership will be determined by the calling user (\"fake owner\" mode)
[15:13:49.268][GoBackendProcess  ][Info   ] using mfsymlinks
[15:13:49.888][LoggingMessageHandler][Info   ] [6c2b62d4] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 9280ms)
[15:13:49.921][VpnKitBridge      ][Info   ] Starting C:\Program Files\Docker\Docker\resources\vpnkit-bridge.exe --addr listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3 host
[15:13:50.833][VpnKitBridge      ][Info   ] Started
[15:13:50.895][IsoConfig         ][Info   ] Generating CA Cert Bundle
[15:13:51.412][VpnKitBridge      ][Info   ] listening on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[15:13:51.413][VpnKitBridge      ][Info   ] waiting for connection on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[15:13:51.736][IsoConfig         ][Info   ] CA Cert Bundle Generated
[15:13:58.682][LoggingMessageHandler][Info   ] [967b271e] <BackendAPIClient start> POST http://backend/hyperv/create
[15:15:28.016][SegmentApi        ][Info   ] Usage statistic: actionMenuFeedback
[15:15:31.603][LoggingMessageHandler][Info   ] [9a389d8e] <Server start> POST http://localhost/notifications/subscriptions
[15:15:31.776][LoggingMessageHandler][Info   ] [fefda3c5] <NotificationsClient start> GET http://localhost/ping
[15:15:31.802][LoggingMessageHandler][Info   ] [fefda3c5] <NotificationsClient end> GET http://localhost/ping -> 200 OK (took 25ms)
[15:15:31.803][LoggingMessageHandler][Info   ] [9a389d8e] <Server end> POST http://localhost/notifications/subscriptions -> 200 OK (took 201ms)
[15:15:38.388][LoggingMessageHandler][Info   ] [dd627a11] <Server start> GET http://localhost/registry/user
[15:15:38.392][LoggingMessageHandler][Info   ] [338f38d6] <Server start> GET http://localhost/docker
[15:15:38.392][LoggingMessageHandler][Info   ] [dd627a11] <Server end> GET http://localhost/registry/user -> 404 NotFound (took 3ms)
[15:15:38.393][LoggingMessageHandler][Info   ] [a6984606] <Server start> GET http://localhost/kubernetes
[15:15:38.395][LoggingMessageHandler][Info   ] [59ff539e] <Server start> GET http://localhost/license/details
[15:15:38.397][LoggingMessageHandler][Info   ] [721ea2c8] <Server start> GET http://localhost/versions
[15:15:38.403][LoggingMessageHandler][Info   ] [721ea2c8] <Server end> GET http://localhost/versions -> 200 OK (took 5ms)
[15:15:38.403][LoggingMessageHandler][Info   ] [338f38d6] <Server end> GET http://localhost/docker -> 200 OK (took 10ms)
[15:15:38.403][LoggingMessageHandler][Info   ] [59ff539e] <Server end> GET http://localhost/license/details -> 200 OK (took 8ms)
[15:15:38.403][LoggingMessageHandler][Info   ] [a6984606] <Server end> GET http://localhost/kubernetes -> 200 OK (took 10ms)
[15:15:38.717][GoBackendProcess  ][Info   ] external: GET /system/editor 404 \"axios/0.19.0\" \"\
[15:15:39.041][BackendAPIClient  ][Error  ] HttpOS Client: Exception:Cancellation token triggered before we finished reading from the stream.
[15:15:39.046][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StopTransition to state change sink
[15:15:39.046][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StopTransition sent to state change sink
[15:15:39.046][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StopTransition from LinuxHyperV
[15:15:39.047][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"updating","Mode":"linux","date":1592214339}
[15:15:39.048][SystrayNotifications][Info   ] Docker Desktop is stopping...
[15:15:39.051][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[15:15:39.051][LoggingMessageHandler][Info   ] [b105aebb] <BackendAPIClient start> POST http://backend/hyperv/stop
[15:15:39.056][LoggingMessageHandler][Info   ] [4f792439] <NotificationsClient start> POST http://localhost/engine/state
[15:15:39.196][LoggingMessageHandler][Info   ] [4f792439] <NotificationsClient end> POST http://localhost/engine/state -> 200 OK (took 140ms)
[15:15:40.950][LoggingMessageHandler][Info   ] [b105aebb] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 1899ms)
[15:15:40.960][VpnKitBridge      ][Info   ] Killing existing vpnkit-bridge with PID 5800
[15:15:40.968][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StoppedState to state change sink
[15:15:40.968][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StoppedState sent to state change sink
[15:15:40.968][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[15:15:40.968][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[15:15:40.968][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StoppedState from LinuxHyperV
[15:15:40.968][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"stopped","Mode":"linux","date":1592214340}
[15:15:40.968][SystrayNotifications][Info   ] Docker has stopped
[15:15:40.968][LoggingMessageHandler][Info   ] [dab9739a] <NotificationsClient start> POST http://localhost/engine/state
[15:15:40.981][LoggingMessageHandler][Info   ] [dab9739a] <NotificationsClient end> POST http://localhost/engine/state -> 200 OK (took 12ms)
[15:15:41.026][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxHyperV
[15:15:41.028][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1592214341}
[15:15:41.028][LoggingMessageHandler][Info   ] [96419cee] <NotificationsClient start> POST http://localhost/engine/state
[15:15:41.095][LoggingMessageHandler][Info   ] [96419cee] <NotificationsClient end> POST http://localhost/engine/state -> 200 OK (took 66ms)
[15:15:41.479][Engines           ][Error  ] Start failed with Cancellation token triggered before we finished reading from the stream.
   at HttpOverStream.ByLineReader.<ReadLineAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.Client.DialMessageHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<CreateHyperVVMAsync>d__10.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__24.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 109)
[15:15:43.753][LoggingMessageHandler][Info   ] [fba6cbc0] <Server start> GET http://localhost/desktop/diagnose
[15:15:44.738][LoggingMessageHandler][Info   ] [fba6cbc0] <Server end> GET http://localhost/desktop/diagnose -> 204 NoContent (took 985ms)
[15:15:44.738][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[15:15:46.635][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[15:15:46.640][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[15:15:46.644][GoBackendProcess  ][Info   ] mutagen sync list --output json
[15:15:47.122][FeedbackWindow    ][Info   ] Open logs
[15:15:49.153][GoBackendProcess  ][Info   ] mutagen C:\\ProgramData\\Docker\\cli-plugins\\docker-mutagen.exe mutagen sync list --output json: null\n
[15:15:49.153][GoBackendProcess  ][Info   ] external: GET /sync 200 \"Go-http-client/1.1\" \"\

**Comment by kaybs28** [comment]
Hi, I am experiencing this issue from past 1 week with version 2.3.0.3. Please help

**Comment by kaybs28** [comment]
Responded how I resolved the issue under the thread https://github.com/docker/for-win/issues/7105
