### ISSUE TITLE
Docker Desktop For Windows does not run

### ISSUE THREAD

**Issue by Nosterx** [docker/for-win#7254]
- [+] I have tried with the latest version of my channel (Stable or Edge)
  - [+] I have uploaded Diagnostics 
  - Diagnostics ID: 14CA1412-6728-4532-803F-73EBA799607E/20200615131553

### Expected behavior
Docker starts
### Actual behavior
Docker failed to start
### Information
  - Windows Version: Windows 10 Pro Build 19041.329
  - Docker Desktop Version:  2.3.0.3 (first installation on this machine)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No
  - WSL2 status:
$# wsl -l -v
  NAME              STATE           VERSION
* Ubuntu            Running        2
  docker-desktop    Installing      2

**Comment by Faldo** [comment]
Same problem here, works fine in Hyper-V mode, switching to WSL 2, chrashes at startup, tried re-installing, tried setting wsl 2 when installing, also tried installing without wsl 2 , enabling it in settings after installation.
Docker Desktop Community 2.3.0.3 (45519)
Windows 10 Pro 19041.264
running wsl -l -v gives
 NAME              STATE           VERSION
* Ubuntu-20.04      Stopped         2
  docker-desktop    Installing      2

**Comment by Faldo** [comment]
Found how to solve it with in issue  "Unable to start docker. #6849"

**Comment by Nosterx** [comment]
Solved with https://github.com/docker/for-win/issues/5256#issuecomment-645917731

**Comment by cybernetics** [comment]
same here. not able to start docker for desktop. using win 10 Pro (v 2004) with WSL2. during the installation I did not select the checkbox to enable WSL2 backend, still, it seems like it's trying to use WSL2 backend.

also submitted docker diagnostic with id: 96DD888D-3B30-4F40-A5F5-BC139A7300EB/20200629051046

getting the following error during startup:

System.InvalidOperationException:
Failed to deploy distro docker-desktop to %localappdata%\Docker\wsl\distro: exit code: -1
 stdout: Error: 0xffffffff


 stderr: 
   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__16.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 142
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
