### ISSUE TITLE
System.IO.IOException on config.iso after switching to WSL 2 engine

### ISSUE THREAD

**Issue by DominikPalo** [docker/for-win#7320]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 0AD921EA-BC52-4F23-8B86-900481FE31DF/20200619064356

### Expected behavior
I'm able to start Docker after switching to WSL 2 engine.

### Actual behavior
I'm not able to start Docker - it always fails with a `System.IO.IOException` error

### Information
I installed the latest big Windows update (2004), installed the WSL 2 (using the PowerShell command recommended by Docker), downloaded and installed WSL 2 kernel, restarted the computer and since then I'm not able to start Docker anymore (I tried multiple computer restarts). It always fails with:

```
System.IO.IOException:
The process cannot access the file 'C:\Users\Dominik\AppData\Local\Docker\vm-config\config.iso' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at Docker.Engines.IsoConfig.DeleteIso() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\IsoConfig.cs:line 220
   at Docker.Engines.IsoConfig.CreateIso(Settings settings, JObject jsonConfig, Boolean rawJson) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\IsoConfig.cs:line 112
   at Docker.Engines.WSL2.WSL2Configurator.PrepareConfiguration(Settings settings) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Configurator.cs:line 19
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<RestartAsync>d__29.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 274

```

**Comment by llbarbosas** [comment]
I don't know why, but I fixed it by shutting down the DockerDesktopVM in the Hyper-V Manager.

**Comment by karakal** [comment]
Thank you a lot!!!! That fixed the problem for me too....

**Comment by gabrielgt3k** [comment]
Thank you! Work for me

**Comment by khalid-s** [comment]
Resetting to factory defaults from the error window solved mine
