### ISSUE TITLE
 Docker desktop may conflict with proxifier ?

### ISSUE THREAD

**Issue by Itoktsnhc** [docker/for-win#7420]
### Expected behavior
 Docker desktop can run normally after proxifier installed
### Actual behavior
Docker desktop can not start normally when proxifier is installed. After uninstall proxifier, docker desktop back to normal

### Information

> System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

> stderr: 
   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<RestartAsync>d__29.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 274

logs:
>  Version: 2.3.0.3 (45519)
Channel: stable
Sha1: 0356a6f23f086a8134d83ee38d99ffe55a121f02
Started on: 2020/06/25 09:59:19.473
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2004
Build: 19041
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\Itokt\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:59:19.535][GUI               ][Info   ] Starting...
[09:59:19.535][ComponentVersions ][Info   ] Edition community
[09:59:19.551][ComponentVersions ][Info   ] Edition community
[09:59:19.646][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[09:59:19.661][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[09:59:19.661][SegmentApi        ][Info   ] Usage statistic: Identify
[09:59:19.724][SegmentApi        ][Info   ] Usage statistic: appLaunched
[09:59:19.903][ApplicationTemplatesTracking][Info   ] Cannot list templates
[09:59:19.904][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[09:59:19.904][SegmentApi        ][Info   ] Usage statistic: heartbeat
[09:59:19.944][LoggingMessageHandler][Info   ] [b4a577da] <BackendAPIClient start> GET http://backend/version
[09:59:19.961][LoggingMessageHandler][Info   ] [b4a577da] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 21ms)
[09:59:20.018][LoggingMessageHandler][Info   ] [4671170c] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[09:59:20.113][LoggingMessageHandler][Info   ] [4671170c] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 90ms)
[09:59:20.113][LoggingMessageHandler][Info   ] [0451ec74] <BackendAPIClient start> POST http://backend/migrate/app
[09:59:20.113][LoggingMessageHandler][Info   ] [0451ec74] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 1ms)
[09:59:20.128][Engines           ][Debug  ] Starting
[09:59:20.128][LoggingMessageHandler][Info   ] [6b66deb2] <BackendAPIClient start> POST http://backend/versionpack/enable
[09:59:20.159][LoggingMessageHandler][Info   ] [6b66deb2] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 25ms)
[09:59:20.211][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[09:59:20.212][GoBackendProcess  ][Info   ] Started
[09:59:20.217][MutagenProcess    ][Info   ] Starting C:\ProgramData\Docker\cli-plugins\docker-mutagen.exe mutagen daemon run
[09:59:20.217][MutagenProcess    ][Info   ] Started
[09:59:20.223][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[09:59:20.223][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[09:59:20.226][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxWSL2
[09:59:20.230][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1593050360}
[09:59:20.231][SystrayNotifications][Info   ] Docker is starting
[09:59:20.233][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[09:59:20.235][LoggingMessageHandler][Info   ] [b5e78ed2] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[09:59:20.248][MutagenProcess    ][Info   ] [forwarding] Looking for existing sessions
[09:59:20.248][MutagenProcess    ][Info   ] [forwarding] Session manager initialized
[09:59:20.248][MutagenProcess    ][Info   ] [sync] Looking for existing sessions
[09:59:20.248][MutagenProcess    ][Info   ] [sync] Session manager initialized
[09:59:20.295][LoggingMessageHandler][Info   ] [b5e78ed2] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 59ms)
[09:59:20.609][LoggingMessageHandler][Info   ] [32fd2aed] <Server start> GET http://unix/versions
[09:59:20.656][LoggingMessageHandler][Info   ] [32fd2aed] <Server end> GET http://unix/versions -> 200 OK (took 46ms)
[09:59:20.673][GoBackendProcess  ][Info   ] 鈬?http server started on \\.\pipe\dockerVpnKitControl
[09:59:20.674][GoBackendProcess  ][Info   ] started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl
[09:59:20.674][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[09:59:20.675][GoBackendProcess  ][Info   ] enabling filesystem caching
[09:59:20.675][GoBackendProcess  ][Info   ] filesystem exports are:  (2)
[09:59:20.675][GoBackendProcess  ][Info   ] volume control server listening on \\\\.\\pipe\\dockerVolume
[09:59:20.675][GoBackendProcess  ][Info   ] 鈬?http server started on \\.\pipe\dockerBackendApiServerForGuest
[09:59:20.675][GoBackendProcess  ][Info   ] 鈬?http server started on \\.\pipe\dockerBackendApiServer
[09:59:20.676][GoBackendProcess  ][Info   ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[09:59:20.676][GoBackendProcess  ][Info   ] file ownership will be determined by the calling user (\"fake owner\" mode)
[09:59:20.676][GoBackendProcess  ][Info   ] using mfsymlinks
[09:59:22.773][WSL2Provisioning  ][Info   ] Checking docker-desktop
[09:59:22.878][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\Itokt\AppData\Local\Docker\wsl\distro
[09:59:23.385][WSL2Provisioning  ][Error  ] Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

> stderr: 
[09:59:23.401][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[09:59:23.433][LinuxWSL2Engine   ][Info   ] Stopping engine
[09:59:23.464][LinuxWSL2Engine   ][Warning] Failed to send stop message to distro, will terminate abrubtly: 
[09:59:23.533][LoggingMessageHandler][Info   ] [f8a9ce97] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[09:59:23.982][LoggingMessageHandler][Info   ] [f8a9ce97] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 441ms)
[09:59:24.089][DockerHub         ][Info   ] Login successfull
[09:59:24.334][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[09:59:24.334][LoggingMessageHandler][Info   ] [95dfa85b] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[09:59:24.374][LoggingMessageHandler][Info   ] [95dfa85b] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 36ms)
[09:59:24.385][WSL2Provisioning  ][Info   ] Checking docker-desktop
[09:59:24.385][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\Itokt\AppData\Local\Docker\wsl\distro
[09:59:24.897][WSL2Provisioning  ][Error  ] Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

> stderr: 
[09:59:24.897][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[09:59:24.929][LinuxWSL2Engine   ][Info   ] Stopping engine
[09:59:24.973][LinuxWSL2Engine   ][Warning] Failed to send stop message to distro, will terminate abrubtly: 
[09:59:25.036][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change > sink
[09:59:25.036][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[09:59:25.036][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxWSL2
[09:59:25.037][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1593050365}
[09:59:25.037][SystrayNotifications][Error  ] Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

> stderr: 
[09:59:25.050][GUI               ][Info   ] Sending Bugsnag report 9abaaef2-d74a-45ce-8f68-64638992929f...
[09:59:25.115][GUI               ][Info   ] Bugsnag report 9abaaef2-d74a-45ce-8f68-64638992929f sent
[09:59:25.115][SegmentApi        ][Info   ] Usage statistic: eventCrash
[09:59:25.117][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[09:59:25.199][Engines           ][Error  ] Start failed with Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

> stderr: 
   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__24.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 109)
[09:59:25.977][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[09:59:25.978][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[09:59:25.978][GoBackendProcess  ][Info   ] mutagen sync list --output json
[09:59:25.996][GoBackendProcess  ][Info   ] mutagen C:\\ProgramData\\Docker\\cli-plugins\\docker-mutagen.exe mutagen sync list --output json: null\n
[09:59:25.996][GoBackendProcess  ][Info   ] external: GET /sync 200 \"Go-http-client/1.1\" \"\

proxifier at https://www.proxifier.com/

  - Windows Version: version 2004 build 19041.329
  - Docker Desktop Version: 2.3.0.3 (45519) stable

### Steps to reproduce the behavior
Install proxifier at https://www.proxifier.com/ then start docker desktop

**Comment by Itoktsnhc** [comment]
> Right now we have a tool that solves the problem:
www.proxifier.com/tmp/Test20200228/NoLsp.exe

> Please just run as admin with the full path to wsl.exe as the parameter:
NoLsp.exe c:\windows\system32\wsl.exe

> This should fix the problem with WSL2.

By proxifer team
