### ISSUE TITLE
Docker crashes frequently on startup

### ISSUE THREAD

**Issue by andersnordmann** [docker/for-win#7577]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 79D4CF1B-1AEE-4698-918E-F10CEDDAE632/20200707073334

### Expected behavior
Docker Desktop should start up with windows

### Actual behavior
Docker desktop frequently crashes on start up with the message "An error occurred" and this crash report:
Docker.Core.HttpBadResponseException:
Unhandled exception: Cannot start service docker on computer '.'.
   ved Docker.Core.Logging.ClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\ClientExceptionInterceptor.cs:linje 17
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:linje 37
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Docker.Core.BackendAPI.BackendAPIClient.<StartWindowsContainersAsync>d__6.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:linje 53
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Docker.Engines.WindowsContainersEngine.<DoStartAsync>d__12.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WindowsContainersEngine.cs:linje 50
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:linje 29
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:linje 67
--- Afslutningen på staksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:linje 92
Original stacktrace:
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at Docker.Backend.Processes.WindowsDockerDaemon.TryToStartService(Settings settings, String args, Dictionary`2 env) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 211
   at Docker.Backend.HttpAPI.WindowsContainersController.Start(WindowsContainerStartRequest request) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\WindowsContainersController.cs:line 42
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__0(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()

### Information

  - Windows Version: Windows 10 Enterprise version 1809, build 17763.1282
  - Docker Desktop Version: 2.3.0.3 (45519)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by andersnordmann** [comment]
From the log file:
LogFile: C:\Users\akn\AppData\Local\Docker\log.txt
Version: 2.3.0.3 (45519)
Channel: stable
Sha1: 0356a6f23f086a8134d83ee38d99ffe55a121f02
Started on: 2020/07/07 09:33:27.563
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1809
Build: 17763
BuildLabName: 17763.1.amd64fre.rs5_release.180914-1434
File: C:\Users\akn\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:33:27.671][GUI               ][Info   ] Starting...
[09:33:27.696][ComponentVersions ][Info   ] Edition community
[09:33:27.696][ComponentVersions ][Info   ] Edition community
[09:33:27.952][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[09:33:27.974][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[09:33:27.978][SegmentApi        ][Info   ] Usage statistic: Identify
[09:33:28.143][SegmentApi        ][Info   ] Usage statistic: appLaunched
[09:33:29.277][ApplicationTemplatesTracking][Info   ] Cannot list templates
[09:33:29.277][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[09:33:29.277][SegmentApi        ][Info   ] Usage statistic: heartbeat
[09:33:29.413][LoggingMessageHandler][Info   ] [f5ae395a] <BackendAPIClient start> GET http://backend/version
[09:33:29.446][LoggingMessageHandler][Info   ] [f5ae395a] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 38ms)
[09:33:29.578][LoggingMessageHandler][Info   ] [720de5cb] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[09:33:29.589][LoggingMessageHandler][Info   ] [720de5cb] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 11ms)
[09:33:29.598][LoggingMessageHandler][Info   ] [0efabb04] <BackendAPIClient start> POST http://backend/migrate/app
[09:33:29.603][LoggingMessageHandler][Info   ] [0efabb04] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 4ms)
[09:33:29.603][Engines           ][Debug  ] Starting
[09:33:29.629][LoggingMessageHandler][Info   ] [bd033f01] <BackendAPIClient start> POST http://backend/versionpack/enable
[09:33:29.679][LoggingMessageHandler][Info   ] [bd033f01] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 50ms)
[09:33:29.813][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[09:33:29.816][GoBackendProcess  ][Info   ] Started
[09:33:29.820][MutagenProcess    ][Info   ] Starting C:\ProgramData\Docker\cli-plugins\docker-mutagen.exe mutagen daemon run
[09:33:29.822][MutagenProcess    ][Info   ] Started
[09:33:29.835][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[09:33:29.836][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[09:33:29.842][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from WindowsContainers
[09:33:29.851][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"windows","date":1594107209}
[09:33:29.852][SystrayNotifications][Info   ] Docker is starting
[09:33:30.546][MutagenProcess    ][Info   ] [forwarding] Looking for existing sessions
[09:33:30.546][MutagenProcess    ][Info   ] [forwarding] Session manager initialized
[09:33:30.546][MutagenProcess    ][Info   ] [sync] Looking for existing sessions
[09:33:30.546][MutagenProcess    ][Info   ] [sync] Session manager initialized
[09:33:31.279][LoggingMessageHandler][Info   ] [6f583dca] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[09:33:31.812][LoggingMessageHandler][Info   ] [6f583dca] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 532ms)
[09:33:31.832][LoggingMessageHandler][Info   ] [de1ca61a] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[09:33:31.846][LoggingMessageHandler][Info   ] [62f99af1] <BackendAPIClient start> POST http://backend/windowscontainers/start
[09:33:31.852][LoggingMessageHandler][Info   ] [abc96228] <Server start> GET http://unix/versions
[09:33:31.913][DockerHub         ][Info   ] Login successfull
[09:33:31.972][LoggingMessageHandler][Info   ] [abc96228] <Server end> GET http://unix/versions -> 200 OK (took 123ms)
[09:33:32.009][LoggingMessageHandler][Info   ] [de1ca61a] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 177ms)
[09:33:32.092][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[09:33:32.122][GoBackendProcess  ][Info   ] started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl
[09:33:32.124][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[09:33:32.125][GoBackendProcess  ][Info   ] enabling filesystem caching
[09:33:32.125][GoBackendProcess  ][Info   ] filesystem exports are:  (2)
[09:33:32.126][GoBackendProcess  ][Info   ] volume control server listening on \\\\.\\pipe\\dockerVolume
[09:33:32.127][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[09:33:32.128][GoBackendProcess  ][Info   ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[09:33:32.128][GoBackendProcess  ][Info   ] file ownership will be determined by the calling user (\"fake owner\" mode)
[09:33:32.128][GoBackendProcess  ][Info   ] using mfsymlinks
[09:33:32.130][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[09:33:32.752][LoggingMessageHandler][Info   ] [62f99af1] <BackendAPIClient end> POST http://backend/windowscontainers/start -> 500 InternalServerError (took 905ms)
[09:33:32.765][LoggingMessageHandler][Info   ] [c5c42cf1] <BackendAPIClient start> POST http://backend/windowscontainers/stop
[09:33:32.776][LoggingMessageHandler][Info   ] [c5c42cf1] <BackendAPIClient end> POST http://backend/windowscontainers/stop -> 204 NoContent (took 10ms)
[09:33:32.776][LoggingMessageHandler][Info   ] [2b61db3a] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[09:33:33.179][LoggingMessageHandler][Info   ] [2b61db3a] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 403ms)
[09:33:33.180][LoggingMessageHandler][Info   ] [99b5a4f2] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[09:33:33.579][LoggingMessageHandler][Info   ] [99b5a4f2] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 401ms)
[09:33:33.579][LoggingMessageHandler][Info   ] [b9aba241] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[09:33:33.579][LoggingMessageHandler][Info   ] [2d5035aa] <BackendAPIClient start> POST http://backend/windowscontainers/start
[09:33:33.671][LoggingMessageHandler][Info   ] [b9aba241] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 81ms)
[09:33:33.762][LoggingMessageHandler][Info   ] [2d5035aa] <BackendAPIClient end> POST http://backend/windowscontainers/start -> 500 InternalServerError (took 180ms)
[09:33:33.762][LoggingMessageHandler][Info   ] [d04de12f] <BackendAPIClient start> POST http://backend/windowscontainers/stop
[09:33:33.779][LoggingMessageHandler][Info   ] [d04de12f] <BackendAPIClient end> POST http://backend/windowscontainers/stop -> 204 NoContent (took 14ms)
[09:33:33.779][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[09:33:33.779][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[09:33:33.779][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from WindowsContainers
[09:33:33.779][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"windows","date":1594107213}
[09:33:33.779][SystrayNotifications][Error  ] Unhandled exception: Cannot start service docker on computer '.'.
[09:33:33.812][GUI               ][Info   ] Sending Bugsnag report d3aaf10b-3509-4270-b446-8b6c538cb527...
[09:33:34.196][GUI               ][Info   ] Bugsnag report d3aaf10b-3509-4270-b446-8b6c538cb527 sent
[09:33:34.196][SegmentApi        ][Info   ] Usage statistic: eventCrash
[09:33:34.213][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[09:33:34.315][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[09:33:34.317][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[09:33:34.318][GoBackendProcess  ][Info   ] mutagen sync list --output json
[09:33:34.402][Engines           ][Error  ] Start failed with Unhandled exception: Cannot start service docker on computer '.'.
   ved Docker.Core.Logging.ClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\ClientExceptionInterceptor.cs:linje 17
--- Afslutningen p堳taksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:linje 37
--- Afslutningen p堳taksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- Afslutningen p堳taksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Docker.Core.BackendAPI.BackendAPIClient.<StartWindowsContainersAsync>d__6.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:linje 53
--- Afslutningen p堳taksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Docker.Engines.WindowsContainersEngine.<DoStartAsync>d__12.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WindowsContainersEngine.cs:linje 50
--- Afslutningen p堳taksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:linje 29
--- Afslutningen p堳taksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:linje 67
--- Afslutningen p堳taksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:linje 92
--- Afslutningen p堳taksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:linje 72
--- Afslutningen p堳taksporingen fra den tidligere placering, hvor undtagelsen blev udløst ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Docker.Engines.Engines.<StartAsync>d__24.MoveNext() i C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:linje 109)
[09:33:34.590][GoBackendProcess  ][Info   ] mutagen C:\\ProgramData\\Docker\\cli-plugins\\docker-mutagen.exe mutagen sync list --output json: null\n
[09:33:34.590][GoBackendProcess  ][Info   ] external: GET /sync 200 \"Go-http-client/1.1\" \"\

**Comment by smell-well** [comment]
same with you...
