### ISSUE TITLE
System.TimeoutException: Timed out while wait for Docker service to be ready    at Docker.LinuxkitDaemonStartup

### ISSUE THREAD

**Issue by savar566** [docker/for-win#7588]
Getting below error while switching from Windows to Linux container...by default windows container is loading
.<StartAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\LinuxkitDaemonStartup.cs:line 43
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

  - [ ] I have tried with the latest version of my channel (Stable or Edge) Stable
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 66A28D14-0F8D-4D4F-BDE8-26B857E587CA/20200708031053

### Expected behavior
Docker should switch from windows to Linux
### Actual behavior
Switching failed
### Information

  - Windows Version: Windows 10 
  - Docker Desktop Version:  19.03.8
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Running on windows

### Steps to reproduce the behavior

  1. ... From settings,switch to Linux contatiner

**Comment by mollychen12** [comment]
I got the same question as the docker desktop engine is 19.03.12.I was stucked with the problem for several days .
