### ISSUE TITLE
Docker desktop community version 2.3.0.3 is not starting the docker on windows 10 Pro Version: 1803

### ISSUE THREAD

**Issue by muqtharali** [docker/for-win#7618]
I have installed Docker desktop community 2.3.0.3 on windows 10 Pro and installation was successful but while launching the docker, getting the below issue and not getting started.

I have tried with stable and edge version also.

### Expected behavior
Docker has to be started with Linux containers by default.

### Actual behavior
Getting the error
Docker.Core.HttpBadResponseException:
Unhandled exception: job failed with message: 'DockerDesktopVM' failed to start. (Virtual machine ID B06524EB-17E6-4032-AA22-F526D04C78C9)
   at Docker.Core.Logging.ClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\ClientExceptionInterceptor.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.HttpClientExtensions.<PostJsonWithJsonResponseAsync>d__1`1.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 22
--- End of stack trace from previous location where exception was thrown ---

### Information

  - Is it reproducible? Yes
  - Is the problem new? Yes
  - Did the problem appear with an update? No

  - Windows Version: Windows 10 Pro for workstatations - 1803
  - Docker Desktop Version: 2.3.0.3
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

1. Download the docker 2.3.0.3
2. Install the docker
3. Launch the docker
4. You can see the error

**Comment by anupwarke** [comment]
Refer #7353 if this helps you

**Comment by muqtharali** [comment]
> Refer #7353 if this helps you

Thanks for your reply.

I tried the solution given in #7353 but I don't see Everyone or Service as part of the list of administrators.

I am getting the same error while starting the VM from Powershell as Administrator

Error:

Start-VM : 'DockerDesktopVM' failed to start. (Virtual machine ID DD129BD6-7761-4FCD-8FE2-480B11881EF7)
At line:1 char:1
+ Start-VM -Name DockerDesktopVM
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : AccessDenied,Microsoft.HyperV.PowerShell.Commands.StartVM

**Comment by muqtharali** [comment]
> Refer #7353 if this helps you

I have analysed all the groups in the list of administrators and I removed common groups from the list.

Restart the system and docker. It is working and am able to start the docker engine successfully.

Thanks **anupwarke** for your help.

**Comment by anupwarke** [comment]
Glad to hear @muqtharali

**Comment by muqtharali** [comment]
Issue has been resolved so I am closing this issue.
