### ISSUE TITLE
Fresh stable Docker crashes in Windows 10 in vm

### ISSUE THREAD

**Issue by Superlokkus** [docker/for-win#763]
### Expected behavior
Docker should start
### Actual behavior
Docker crashes
### Information

  - 9D0CF86C-1EEA-4FA0-8579-5EC58F28931D/2017-05-23_16-53-23
  - Fresh install of stable docker, 17.03.1-ce-win12 (12058)
  - Windows 10 Pro 1607, on virtual machine VMWare Fusion Professional Version 8.5.7, on OSX host

### Steps to reproduce the behavior

  1. Install docker (incl. reboots for hyper-v installation)
  2. Wait for crash report due automatic docker startup

**Comment by wikrie** [comment]
sound like the same issue as #748

**Comment by Superlokkus** [comment]
Maybe not, looks like I don't have a problem starting the VM but write a database (but about the start dough): 

> Unable to write to the database. Exit code: 1
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)


Log:
```
Version: 17.03.1-ce-win12 (12058)
Channel: stable
Sha1: d1db12684b33b778cfc3012e92959e50eb486fcd
Started on: 2017-05-24 09:30:00.288
Resources: C:\Program Files\Docker\Docker\Resources
OS: Windows 10 Pro
Edition: Professional
Id: 1607
Build: 14393
BuildLabName: 14393.1198.amd64fre.rs1_release_sec.170427-1353
File: C:\Users\markus\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker for Windows.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:30:00.538][GUI            ][Info   ] Starting...
[09:30:01.319][Tracking       ][Info   ] Crash report and usage statistics are enabled
[09:30:01.335][SegmentApi     ][Info   ] Usage statistic: appLaunched
[09:30:01.507][NamedPipeClient][Info   ] Sending Version()...
[09:30:01.523][NamedPipeClient][Info   ] Received response for Version
[09:30:01.538][SegmentApi     ][Info   ] Usage statistic: heartbeat
[09:29:37.148][BackendServer  ][Info   ] Started
[09:30:01.523][NamedPipeServer][Info   ] Version()
[09:30:01.523][NamedPipeServer][Info   ] Version done in 00:00:00.
[09:30:02.788][NamedPipeClient][Info   ] Sending Start(Docker.Core.Settings)...
[09:30:02.788][Updater        ][Info   ] Checking for updates on channel stable...
[09:30:02.819][NamedPipeServer][Info   ] Start(Docker.Core.Settings)
[09:30:02.835][PowerMode      ][Info   ] Stop
[09:30:02.866][HyperV         ][Info   ] Stop
[09:30:02.976][Updater        ][Info   ] Local build 12058 is as good as the remote 12058 on channel stable
[09:30:02.992][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[09:30:03.054][PowerShell     ][Info   ] Creating a Runspace Pool...
[09:30:04.351][PowerShell     ][Info   ] Runspace Pool created (Min=1, Max=2)
[09:30:04.632][HyperV         ][Info   ] Script started at 09:30:04.616
[09:30:07.382][HyperV         ][Info   ] Module loaded at 09:30:07.382
[09:30:07.851][HyperV         ][Info   ] VM MobyLinuxVM does not exist
[09:30:07.851][HyperV         ][Debug  ] [stop] took 00:00:04.9531309 to run
[09:30:07.851][OptimizeDisk   ][Info   ] Optimize
[09:30:07.851][PowerShell     ][Info   ] Run script...
[09:30:07.882][Moby           ][Info   ] Stop
[09:30:07.882][HyperV         ][Info   ] Create
[09:30:07.882][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[09:30:07.898][HyperVGuids    ][Info   ] Installing GUIDs...
[09:30:07.898][HyperVGuids    ][Info   ] GUIDs installed
[09:30:07.898][PowerMode      ][Info   ] Start
[09:30:07.898][Firewall       ][Info   ] Removing all existing rules...
[09:30:07.913][HyperV         ][Info   ] Script started at 09:30:07.913
[09:30:07.960][HyperV         ][Info   ] Module loaded at 09:30:07.960
[09:30:08.038][Firewall       ][Info   ] All existing rules are removed.
[09:30:08.054][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[09:30:08.069][Firewall       ][Info   ] Opening ports for SMB...
[09:30:08.085][Firewall       ][Info   ] Ports are opened
[09:30:08.304][HyperV         ][Info   ] Creating Switch: DockerNAT...
[09:30:11.507][HyperV         ][Info   ] Switch created.
[09:30:12.710][HyperV         ][Info   ] Set IP address on switch
[09:30:14.319][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[09:30:15.632][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[09:30:16.226][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[09:30:16.835][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[09:30:17.257][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\mobylinux.iso
[09:30:17.804][HyperV         ][Info   ] Disabled Guest Service Interface
[09:30:17.820][HyperV         ][Info   ] Enabled Heartbeat
[09:30:17.835][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[09:30:17.851][HyperV         ][Info   ] Enabled Shutdown
[09:30:17.866][HyperV         ][Info   ] Enabled Time Synchronization
[09:30:17.882][HyperV         ][Info   ] Disabled VSS
[09:30:18.069][HyperV         ][Info   ] VM created.
[09:30:18.069][HyperV         ][Debug  ] [create] took 00:00:10.1875011 to run
[09:30:18.069][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[09:30:18.116][DataKit        ][Info   ] Starting C:\Program Files\Docker\Docker\Resources\com.docker.db.exe --url hyperv-connect://9dee84be-3cd2-4b0f-8c97-5e6ed5a5aa52,\\.\pipe\dockerDataBase --color never
[09:30:18.163][DataKit        ][Info   ] Started
[09:30:18.179][Database       ][Info   ] Generating CA Cert Bundle
[09:30:18.210][Database       ][Info   ] CA Cert Bundle Generated
[09:30:18.226][DataKit        ][Info   ] Starting com.docker.db.exe 0.7.0-34-g6f04213 ...
[09:30:18.226][DataKit        ][Error  ] com.docker.db.exe: Failed to set up server socket listening on hyperv-connect://9dee84be-3cd2-4b0f-8c97-5e6ed5a5aa52: Unix.Unix_error(Unix.ENETDOWN, "socket", "")
[09:30:18.226][DataKit        ][Info   ] com.docker.db.exe: internal error, uncaught exception:
[09:30:18.226][DataKit        ][Info   ]                    (Failure accept_forever)
[09:30:18.226][DataKit        ][Info   ]                    
[09:30:18.226][DataKit        ][Error  ] Process died
[09:30:23.179][Linux          ][Error  ] Failed to start: The operation has timed out.. Let's retry
[09:30:23.179][PowerShell     ][Info   ] Run script...
[09:30:25.913][HyperV         ][Info   ] Hyper-V is running
[09:30:25.913][PowerMode      ][Info   ] Stop
[09:30:25.913][HyperV         ][Info   ] Stop
[09:30:25.913][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[09:30:25.929][HyperV         ][Info   ] Script started at 09:30:25.929
[09:30:25.929][HyperV         ][Info   ] Module loaded at 09:30:25.929
[09:30:25.991][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[09:30:25.991][HyperV         ][Debug  ] [stop] took 00:00:00.0781178 to run
[09:30:25.991][OptimizeDisk   ][Info   ] Optimize
[09:30:25.991][PowerShell     ][Info   ] Run script...
[09:30:27.445][Moby           ][Info   ] Stop
[09:30:27.445][HyperV         ][Info   ] Destroy
[09:30:27.445][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[09:30:27.460][HyperV         ][Info   ] Script started at 09:30:27.460
[09:30:27.491][HyperV         ][Info   ] Module loaded at 09:30:27.491
[09:30:27.507][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[09:30:27.507][HyperV         ][Info   ] Destroying Switch DockerNAT...
[09:30:28.163][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[09:30:28.241][HyperV         ][Debug  ] [destroy] took 00:00:00.7965957 to run
[09:30:28.241][Firewall       ][Info   ] Closing ports...
[09:30:28.241][Firewall       ][Info   ] Removing all existing rules...
[09:30:28.366][Firewall       ][Info   ] All existing rules are removed.
[09:30:28.366][Firewall       ][Info   ] Ports are closed
[09:30:28.366][HyperVGuids    ][Info   ] Removing GUIDs...
[09:30:28.366][HyperVGuids    ][Info   ] GUIDs removed
[09:30:28.366][HyperV         ][Info   ] Create
[09:30:28.366][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[09:30:28.382][HyperV         ][Info   ] Script started at 09:30:28.382
[09:30:28.382][HyperV         ][Info   ] Module loaded at 09:30:28.382
[09:30:28.444][HyperV         ][Info   ] Creating Switch: DockerNAT...
[09:30:30.319][HyperV         ][Info   ] Switch created.
[09:30:30.585][HyperV         ][Info   ] Set IP address on switch
[09:30:30.632][HyperV         ][Info   ] Creating VM MobyLinuxVM...
[09:30:31.726][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[09:30:32.038][HyperV         ][Info   ] Attach VHD C:\Users\Public\Documents\Hyper-V\Virtual Hard Disks\MobyLinuxVM.vhdx
[09:30:32.554][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[09:30:32.757][HyperV         ][Info   ] Attach DVD C:\Program Files\Docker\Docker\Resources\mobylinux.iso
[09:30:33.179][HyperV         ][Info   ] Disabled Guest Service Interface
[09:30:33.194][HyperV         ][Info   ] Enabled Heartbeat
[09:30:33.226][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[09:30:33.241][HyperV         ][Info   ] Enabled Shutdown
[09:30:33.257][HyperV         ][Info   ] Enabled Time Synchronization
[09:30:33.273][HyperV         ][Info   ] Disabled VSS
[09:30:33.523][HyperV         ][Info   ] VM created.
[09:30:33.523][HyperV         ][Debug  ] [create] took 00:00:05.1562465 to run
[09:30:33.523][PowerMode      ][Info   ] Stop
[09:30:33.523][HyperV         ][Info   ] Stop
[09:30:33.523][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[09:30:33.523][HyperV         ][Info   ] Script started at 09:30:33.523
[09:30:33.538][HyperV         ][Info   ] Module loaded at 09:30:33.538
[09:30:33.569][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[09:30:33.569][HyperV         ][Debug  ] [stop] took 00:00:00.0468731 to run
[09:30:33.569][OptimizeDisk   ][Info   ] Optimize
[09:30:33.569][PowerShell     ][Info   ] Run script...
[09:30:35.039][Moby           ][Info   ] Stop
[09:30:35.039][HyperV         ][Info   ] Create
[09:30:35.039][PowerShell     ][Info   ] Run script with parameters: -Create True -VhdPathOverride  -SwitchSubnetAddress 10.0.75.0 -SwitchSubnetMaskSize 24 -CPUs 2 -Memory 2048 -IsoFile C:\Program Files\Docker\Docker\Resources\mobylinux.iso...
[09:30:35.039][HyperVGuids    ][Info   ] Installing GUIDs...
[09:30:35.039][HyperVGuids    ][Info   ] GUIDs installed
[09:30:35.039][PowerMode      ][Info   ] Start
[09:30:35.039][Firewall       ][Info   ] Removing all existing rules...
[09:30:35.069][Firewall       ][Info   ] All existing rules are removed.
[09:30:35.069][Firewall       ][Info   ] Opening ports for C:\Program Files\Docker\Docker\Resources\com.docker.proxy.exe...
[09:30:35.069][HyperV         ][Info   ] Script started at 09:30:35.069
[09:30:35.101][HyperV         ][Info   ] Module loaded at 09:30:35.101
[09:30:35.101][Firewall       ][Info   ] Opening ports for SMB...
[09:30:35.116][Firewall       ][Info   ] Ports are opened
[09:30:35.382][HyperV         ][Info   ] Using existing Switch: DockerNAT
[09:30:35.429][HyperV         ][Info   ] Using existing Switch IP address
[09:30:35.460][HyperV         ][Info   ] Setting CPUs to 2 and Memory to 2048 MB
[09:30:35.538][HyperV         ][Info   ] Connect Internal Switch DockerNAT
[09:30:35.648][HyperV         ][Info   ] Disabled Guest Service Interface
[09:30:35.663][HyperV         ][Info   ] Enabled Heartbeat
[09:30:35.679][HyperV         ][Info   ] Disabled Key-Value Pair Exchange
[09:30:35.694][HyperV         ][Info   ] Enabled Shutdown
[09:30:35.710][HyperV         ][Info   ] Enabled Time Synchronization
[09:30:35.726][HyperV         ][Info   ] Disabled VSS
[09:30:35.819][HyperV         ][Info   ] VM created.
[09:30:35.819][HyperV         ][Debug  ] [create] took 00:00:00.7800879 to run
[09:30:35.819][PowerShell     ][Info   ] Run script '(Get-VM MobyLinuxVM).Id.Guid'...
[09:30:35.835][DataKit        ][Info   ] Starting C:\Program Files\Docker\Docker\Resources\com.docker.db.exe --url hyperv-connect://f696b56c-22f0-4c20-8d9a-2acfd8f61f9e,\\.\pipe\dockerDataBase --color never
[09:30:35.835][DataKit        ][Info   ] Started
[09:30:35.835][Database       ][Info   ] Generating CA Cert Bundle
[09:30:35.851][Database       ][Info   ] CA Cert Bundle Generated
[09:30:35.851][DataKit        ][Info   ] Starting com.docker.db.exe 0.7.0-34-g6f04213 ...
[09:30:35.851][DataKit        ][Error  ] com.docker.db.exe: Failed to set up server socket listening on hyperv-connect://f696b56c-22f0-4c20-8d9a-2acfd8f61f9e: Unix.Unix_error(Unix.ENETDOWN, "socket", "")
[09:30:35.851][DataKit        ][Info   ] com.docker.db.exe: internal error, uncaught exception:
[09:30:35.851][DataKit        ][Info   ]                    (Failure accept_forever)
[09:30:35.851][DataKit        ][Info   ]                    
[09:30:35.866][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[09:30:35.866][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[09:30:35.866][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[09:30:35.866][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[09:30:35.866][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[09:30:35.866][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[]}
[09:30:35.866][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[09:30:35.866][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[09:30:35.866][DataKit        ][Error  ] Process died
[09:30:36.964][Database       ][Error  ] 2017/05/24 09:30:35 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:36 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:36 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:36 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:36 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:36 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:36 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:36 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:36 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:36 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:36 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

[09:30:36.964][Database       ][Error  ] Unable to modify database: Unable to write to the database. Exit code: 1. Let's retry in 1s
[09:30:37.994][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[09:30:37.994][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[09:30:37.994][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[09:30:37.994][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[09:30:37.994][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[09:30:37.994][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[]}
[09:30:37.994][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[09:30:37.994][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[09:30:39.026][Database       ][Error  ] 2017/05/24 09:30:38 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:38 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:38 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:38 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:38 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:38 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:38 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:38 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:38 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:38 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:39 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

[09:30:39.026][Database       ][Error  ] Unable to modify database: Unable to write to the database. Exit code: 1. Let's retry in 1s
[09:30:40.042][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[09:30:40.042][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[09:30:40.042][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[09:30:40.042][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[09:30:40.042][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[09:30:40.042][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[]}
[09:30:40.042][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[09:30:40.042][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[09:30:41.091][Database       ][Error  ] 2017/05/24 09:30:40 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:40 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:40 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:40 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:40 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:40 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:40 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:40 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:40 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:40 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:41 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

[09:30:41.091][Database       ][Error  ] Unable to modify database: Unable to write to the database. Exit code: 1. Let's retry in 1s
[09:30:42.107][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[09:30:42.107][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[09:30:42.107][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[09:30:42.107][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[09:30:42.107][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[09:30:42.107][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[]}
[09:30:42.107][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[09:30:42.107][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[09:30:43.142][Database       ][Error  ] 2017/05/24 09:30:42 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:42 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:42 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:42 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:42 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:42 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:42 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:42 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:42 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:43 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:43 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

[09:30:43.142][Database       ][Error  ] Unable to modify database: Unable to write to the database. Exit code: 1. Let's retry in 1s
[09:30:44.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/config=static
[09:30:44.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/address=10.0.75.2
[09:30:44.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/netmask=255.255.255.0
[09:30:44.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/net/gateway=10.0.75.1
[09:30:44.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/network=hybrid
[09:30:44.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/docker/daemon.json={"registry-mirrors":[],"insecure-registries":[]}
[09:30:44.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/etc/sysctl.conf=
[09:30:44.173][Database       ][Info   ] Writing com.docker.driver.amd64-linux/native/port-forwarding=true
[09:30:45.209][Database       ][Error  ] 2017/05/24 09:30:44 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:44 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:44 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:44 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:44 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:44 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:44 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:44 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:45 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:45 Retry dialing \\.\pipe\dockerDataBase in 100ms
2017/05/24 09:30:45 Failed to contact the database on \\.\pipe\dockerDataBase: open \\.\pipe\dockerDataBase: The system cannot find the file specified.

[09:30:45.209][PowerMode      ][Info   ] Stop
[09:30:45.209][HyperV         ][Info   ] Stop
[09:30:45.209][PowerShell     ][Info   ] Run script with parameters: -Stop True...
[09:30:45.209][HyperV         ][Info   ] Script started at 09:30:45.209
[09:30:45.224][HyperV         ][Info   ] Module loaded at 09:30:45.224
[09:30:45.255][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[09:30:45.255][HyperV         ][Debug  ] [stop] took 00:00:00.0463601 to run
[09:30:45.255][OptimizeDisk   ][Info   ] Optimize
[09:30:45.255][PowerShell     ][Info   ] Run script...
[09:30:46.552][Moby           ][Info   ] Stop
[09:30:46.552][HyperV         ][Info   ] Destroy
[09:30:46.552][PowerShell     ][Info   ] Run script with parameters: -Destroy True -KeepVolume True...
[09:30:46.568][HyperV         ][Info   ] Script started at 09:30:46.568
[09:30:46.568][HyperV         ][Info   ] Module loaded at 09:30:46.568
[09:30:46.583][HyperV         ][Info   ] VM MobyLinuxVM is stopped
[09:30:46.583][HyperV         ][Info   ] Destroying Switch DockerNAT...
[09:30:47.193][HyperV         ][Info   ] Removing VM MobyLinuxVM...
[09:30:47.255][HyperV         ][Debug  ] [destroy] took 00:00:00.7025759 to run
[09:30:47.255][Firewall       ][Info   ] Closing ports...
[09:30:47.255][Firewall       ][Info   ] Removing all existing rules...
[09:30:47.318][Firewall       ][Info   ] All existing rules are removed.
[09:30:47.318][Firewall       ][Info   ] Ports are closed
[09:30:47.318][HyperVGuids    ][Info   ] Removing GUIDs...
[09:30:47.318][HyperVGuids    ][Info   ] GUIDs removed
[09:30:47.349][NamedPipeServer][Error  ] Unable to execute Start: Unable to write to the database. Exit code: 1    at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[09:30:47.349][NamedPipeClient][Error  ] Unable to send Start: Unable to write to the database. Exit code: 1
[09:30:47.349][Notifications  ][Error  ] Unable to write to the database. Exit code: 1
[09:41:02.975][ErrorReportWindow][Info   ] Open logs
```

**Comment by Superlokkus** [comment]
I was able to fix that issue for me, as some people suggested on #748 I had to enable virtualisation in my VM, for VMWare Fusion I attached a screenshot
![bildschirmfoto 2017-05-24 um 09 55 18 2](https://cloud.githubusercontent.com/assets/226051/26392610/894855a2-4067-11e7-9fa0-13334aec196b.png)
