### ISSUE TITLE
Container stops responding

### ISSUE THREAD

**Issue by tberne** [docker/for-win#765]
### Expected behavior
Docker containers keeps running.

### Actual behavior
Docker containers stop responding after a while.
Explaining a little more: 
In my local dev environment, I have a docker-compose (see DC.zip) that start a few services for me.
One of them (the database -- `mysql:5.7`), stops responding after a while.
In my application, the following error occurs:

    2017-05-24 13:08:41,796 ERROR      [Page Cache Generator Global_default-1] lumis.portal.page.cache.PageCacheGenerator - Error in PageCacheGenerator.run of 'Global_default-1'
    javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Cannot open connection
    	at org.hibernate.ejb.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:614)
    	at org.hibernate.ejb.TransactionImpl.begin(TransactionImpl.java:41)
    	at lumis.portal.dao.hibernate.TransactionHibernate.getEntityManager(TransactionHibernate.java:255)
    	at lumis.portal.dao.hibernate.TransactionHibernate.getEntityManager(TransactionHibernate.java:236)
    	at lumis.portal.dao.hibernate.TransactionHibernate.getSession(TransactionHibernate.java:264)
    	at lumis.portal.page.cache.PageCacheDaoHib.searchPageCacheForGeneration(PageCacheDaoHib.java:160)
    	at lumis.portal.page.cache.PageCacheDaoHib.getNextPageForGeneration(PageCacheDaoHib.java:89)
    	at lumis.portal.page.cache.PageCacheManager.getNextPageForGeneration(PageCacheManager.java:1301)
    	at lumis.portal.page.cache.PageCacheManager.generateNextPage(PageCacheManager.java:765)
    	at lumis.portal.page.cache.PageCacheGenerator.run(PageCacheGenerator.java:54)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: org.hibernate.exception.JDBCConnectionException: Cannot open connection
    	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:97)
    	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
    	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:52)
    	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:449)
    	at org.hibernate.jdbc.ConnectionManager.getConnection(ConnectionManager.java:167)
    	at org.hibernate.jdbc.JDBCContext.connection(JDBCContext.java:142)
    	at org.hibernate.transaction.JDBCTransaction.begin(JDBCTransaction.java:85)
    	at org.hibernate.impl.SessionImpl.beginTransaction(SessionImpl.java:1354)
    	at org.hibernate.ejb.TransactionImpl.begin(TransactionImpl.java:38)
    	... 9 more
    Caused by: java.sql.SQLTransientConnectionException: HikariPool-2 - Connection is not available, request timed out after 10000ms.
    	at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:591)
    	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:194)
    	at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:146)
    	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:85)
    	at lumis.portal.dao.hibernate.HikariConnectionProvider.getConnection(HikariConnectionProvider.java:74)
    	at org.hibernate.jdbc.ConnectionManager.openConnection(ConnectionManager.java:446)
    	... 14 more
    Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
    
    The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
    	at sun.reflect.GeneratedConstructorAccessor274.newInstance(Unknown Source)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
    	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
    	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
    	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2251)
    	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2284)
    	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2083)
    	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:806)
    	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
    	at sun.reflect.GeneratedConstructorAccessor53.newInstance(Unknown Source)
    	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
    	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:410)
    	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:328)
    	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:95)
    	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:101)
    	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:346)
    	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:196)
    	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:442)
    	at com.zaxxer.hikari.pool.HikariPool.access$200(HikariPool.java:73)
    	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:620)
    	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:606)
    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	... 1 more
    Caused by: java.net.ConnectException: Connection refused: connect
    	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
    	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
    	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
    	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
    	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    	at java.net.Socket.connect(Socket.java:589)
    	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:211)
    	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:300)
    	... 23 more

It's a communication problem between my (Java) application and the database server started by docker-compose.

After that happens, if I try to restart the docker-compose services, the following error occur:

    Starting elasticsearch ... error
    Starting selenium ... error
    Starting kibana ... error
    Starting webserver ... error
    Starting database ... error
    
    ERROR: for elasticsearch  Cannot start service elasticsearch: driver failed programming external connectivity on endpoint trnkdesenv_elasticsearch_1 (93be7f0ce586c8050953dc14f6691ec5857846acd45155981432f32c08c0795f): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:9300:tcp:172.18.0.4:9300: input/output error
    
    ERROR: for selenium  Cannot start service selenium: driver failed programming external connectivity on endpoint trnkdesenv_selenium_1 (bf35d69f6d8d91b19a3e10633cec05ebd5a28bb55ae7b85389d9add3c4b871d6): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:5900:tcp:172.18.0.2:5900: input/output error
    
    ERROR: for database  Cannot start service database: driver failed programming external connectivity on endpoint trnkdesenv_database_1 (0ea7cc70908c8f5c8574478caf118bfc4c0f9a9e1a40bae613462ad8aedea55c): Error starting userland proxy: mkdir /port/tcp:0.0.0.0:3306:tcp:172.18.0.3:3306: input/output error
    ERROR: No containers to start
    Error starting environment

With the following error entries:

    [13:12:38.383][ApiProxy       ][Info   ] proxy >> GET /v1.22/containers/json?all=1&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtrnkdesenv%22%2C+%22com.docker.compose.service%3Ddatabase%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0
    [13:12:38.383][ApiProxy       ][Info   ] Dial Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:38.383][ApiProxy       ][Info   ] proxy >> GET /v1.22/containers/json?all=1&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtrnkdesenv%22%2C+%22com.docker.compose.service%3Delasticsearch%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0
    [13:12:38.383][ApiProxy       ][Info   ] Dial Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:38.384][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:38.384][ApiProxy       ][Info   ] proxy >> GET /v1.22/containers/json?all=1&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtrnkdesenv%22%2C+%22com.docker.compose.service%3Dselenium%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0
    [13:12:38.384][ApiProxy       ][Info   ] Dial Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:38.386][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:38.387][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:38.387][ApiProxy       ][Info   ] proxy << GET /v1.22/containers/json?all=1&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtrnkdesenv%22%2C+%22com.docker.compose.service%3Ddatabase%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0
    [13:12:38.391][ApiProxy       ][Info   ] proxy >> GET /v1.22/containers/c54f0efde2201c02c743502917191c4f3a146514848a7b334ddb5669a5aa3769/json
    [13:12:38.391][ApiProxy       ][Info   ] Dial Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:38.393][ApiProxy       ][Info   ] proxy << GET /v1.22/containers/json?all=1&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtrnkdesenv%22%2C+%22com.docker.compose.service%3Delasticsearch%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0
    [13:12:38.393][ApiProxy       ][Info   ] proxy << GET /v1.22/containers/json?all=1&limit=-1&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dtrnkdesenv%22%2C+%22com.docker.compose.service%3Dselenium%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D&trunc_cmd=0&size=0
    [13:12:38.399][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:38.402][ApiProxy       ][Info   ] proxy >> GET /v1.22/containers/4fb73169d56690068e52180ffc9e782b256fff09e553817a1a3fa92da2d8a835/json
    [13:12:38.402][ApiProxy       ][Info   ] Dial Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:38.402][ApiProxy       ][Info   ] proxy >> GET /v1.22/containers/fc2823c6b589d23b32292adac05c53203cead108d8a2b7fbd18619d83dff7e2e/json
    [13:12:38.402][ApiProxy       ][Info   ] Dial Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:38.404][ApiProxy       ][Info   ] proxy << GET /v1.22/containers/c54f0efde2201c02c743502917191c4f3a146514848a7b334ddb5669a5aa3769/json
    [13:12:38.406][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:38.408][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:38.408][ApiProxy       ][Info   ] proxy << GET /v1.22/containers/4fb73169d56690068e52180ffc9e782b256fff09e553817a1a3fa92da2d8a835/json
    [13:12:38.411][ApiProxy       ][Info   ] proxy << GET /v1.22/containers/fc2823c6b589d23b32292adac05c53203cead108d8a2b7fbd18619d83dff7e2e/json
    [13:12:38.415][ApiProxy       ][Info   ] proxy >> POST /v1.22/containers/c54f0efde2201c02c743502917191c4f3a146514848a7b334ddb5669a5aa3769/start [start]
    [13:12:38.415][ApiProxy       ][Info   ] proxy >> POST /v1.22/containers/c54f0efde2201c02c743502917191c4f3a146514848a7b334ddb5669a5aa3769/start
    [13:12:38.415][ApiProxy       ][Info   ] Dial Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:38.415][ApiProxy       ][Info   ] proxy >> POST /v1.22/containers/4fb73169d56690068e52180ffc9e782b256fff09e553817a1a3fa92da2d8a835/start [start]
    [13:12:38.415][ApiProxy       ][Info   ] proxy >> POST /v1.22/containers/4fb73169d56690068e52180ffc9e782b256fff09e553817a1a3fa92da2d8a835/start
    [13:12:38.415][ApiProxy       ][Info   ] Dial Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:38.423][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:38.424][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:39.388][ApiProxy       ][Info   ] proxy >> POST /v1.22/containers/fc2823c6b589d23b32292adac05c53203cead108d8a2b7fbd18619d83dff7e2e/start [start]
    [13:12:39.388][ApiProxy       ][Info   ] proxy >> POST /v1.22/containers/fc2823c6b589d23b32292adac05c53203cead108d8a2b7fbd18619d83dff7e2e/start
    [13:12:39.388][ApiProxy       ][Info   ] Dial Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:39.388][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 7604db34-4edc-4865-a640-402dbae61807:23a432c2-537a-4291-bcb5-d62504644739
    [13:12:39.388][ApiProxy       ][Info   ] proxy << POST /v1.22/containers/c54f0efde2201c02c743502917191c4f3a146514848a7b334ddb5669a5aa3769/start
    [13:12:39.388][ApiProxy       ][Info   ] proxy << POST /v1.22/containers/4fb73169d56690068e52180ffc9e782b256fff09e553817a1a3fa92da2d8a835/start
    [13:12:39.388][ApiProxy       ][Info   ] proxy << POST /v1.22/containers/fc2823c6b589d23b32292adac05c53203cead108d8a2b7fbd18619d83dff7e2e/start

I've noticed that if after that I restart Docker, the environment can be started again with no errors. And again, after a while, it stops responding.

### Information

  - Diagnostic ID: 06456465-406D-414C-8716-1CC9D40EC4C8/2017-05-24_13-13-03.
  - [DC.zip](https://github.com/docker/for-win/files/1026255/DC.zip)
  - Windows 10 PRO x64

### Steps to reproduce the behavior

  1. Start the attached docker-compose.
  2. Waits a while (last time, it took about four hours to the symptom to happen).

**Comment by retog** [comment]
I'm wondering if this is the same as https://superuser.com/questions/1222620/network-connection-to-docker-container-interrupts-and-the-container-cant-be-res#_=_

**Comment by tberne** [comment]
Seems to be the same.

**Comment by tberne** [comment]
Hey guys, do you have any news on this?
