### ISSUE TITLE
Docker not lauching on Windows 10 Home - Failed to set version to docker-desktop: exit code: -1

### ISSUE THREAD

**Issue by satyadevshetty** [docker/for-win#7727]
This is the error i am getting:
"System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: The Windows Subsystem for Linux instance has terminated."

Diagnostic ID:
1A4EBD75-4267-4A94-9CF0-E26791F1B99D/20200719055643

Windows 10 Home
WSL 2 - Ubuntu 20.04 LTS
Docker Desktop

Below is the complete Error:
"
System.InvalidOperationException:
Failed to set version to docker-desktop: exit code: -1
 stdout: The Windows Subsystem for Linux instance has terminated.
stderr: 
   at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__6.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__23.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
"

  - [ Yes] I have tried with the latest version of my channel (Stable or Edge)
  - [Yes  ] I have uploaded Diagnostics
  - Diagnostics ID: 1A4EBD75-4267-4A94-9CF0-E26791F1B99D/20200719055643

### Expected behavior
Should Lauch

### Actual behavior
Not lauching 
### Information

  - Windows Version: Windows 10 HOme  Version 2004(OS Build 19041.388
  - Docker Desktop Version: 
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No on my Windows 10 Home Laptop

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by santanaguy** [comment]
Same problem here, same configuration.

Diagnostic ID: 22D4B1CD-43C8-4B2A-9770-D094DE58B176/20200720130040

**Comment by santanaguy** [comment]
It seems the problem disappeared after updating Windows and restarting. Everything seems normal now...
