### ISSUE TITLE
Failed to upgrade Docker to 2.3.0.4

### ISSUE THREAD

**Issue by andyli** [docker/for-win#7849]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics

Docker Desktop just prompted me to update, but it failed with error:

```
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   at CommunityInstaller.EnableFeaturesAction.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__29.MoveNext()
```

My Windows version:
```
OS Name:                   Microsoft Windows 10 Pro Insider Preview
OS Version:                10.0.20175 N/A Build 20175
```

Tried running the installers (stable channel 2.3.0.4 and edge channel 2.3.3.2) manually after the failure, got the same error.

**Comment by zyazhb** [comment]
**Same issue**

**Comment by alejandro5042** [comment]
I also fail the upgrade. Tried both stable and edge, same as OP. Same Windows version, except mine is Enterprise.

**Comment by alejandro5042** [comment]
Here is my `install-log.txt`:

```
[21:35:04.107] [InstallHandler] No installation found
[21:35:04.367] [InstallWorkflow] Using package: res:DockerDesktop
[21:35:04.373] [InstallWorkflow] Downloading
[21:35:05.247] [InstallWorkflow] Extracting manifest
[21:35:10.494] [InstallWorkflow] Checking prerequisites
[21:35:10.623] [InstallWorkflow] Prompting for optional features
[21:35:37.615] [InstallWorkflow] Unpacking artifacts
[21:37:57.780] [InstallWorkflow] Deploying component CommunityInstaller.CreateGroupAction
[21:38:02.860] [InstallWorkflow] Deploying component CommunityInstaller.AddToGroupAction
[21:38:02.874] [InstallWorkflow] Deploying component CommunityInstaller.EnableFeaturesAction
[21:38:04.640] [InstallWorkflow] Component CommunityInstaller.EnableFeaturesAction failed
Exception type: System.Runtime.InteropServices.COMException, Exception message: , StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   at CommunityInstaller.EnableFeaturesAction.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__32.MoveNext()
[21:38:04.642] [InstallWorkflow] Installation failed
Exception type: System.Runtime.InteropServices.COMException, Exception message: , StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   at CommunityInstaller.EnableFeaturesAction.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__27.MoveNext()
[21:38:04.646] [InstallWorkflow] Rollbacking component CommunityInstaller.AddToGroupAction
[21:38:04.649] [InstallWorkflow] Rollbacking component CommunityInstaller.CreateGroupAction
[21:38:04.651] [InstallWorkflow] Rollbacking component CommunityInstaller.UnpackArtifactsStep
[21:38:04.670] [FileSystem] Deleting C:\Program Files\Docker\Docker
[21:38:05.056] [FileSystem] Deleted C:\Program Files\Docker\Docker successfully
[21:38:05.057] [InstallWorkflow] Rollbacking component CommunityInstaller.ExtractManifestStep
[21:38:05.058] [InstallWorkflow] Rollbacking component CommunityInstaller.DownloadStep
```

**Comment by rbakersmith** [comment]
I'm having the same issue (on Win10 Pro 20175):

```
[13:38:20.660] [InstallHandler] No installation found
[13:38:20.665] [InstallHandler] Using embedded package
[13:38:21.012] [InstallWorkflow] Using package: res:CommunityInstaller.DockerDesktop.d4w
[13:38:21.015] [InstallWorkflow] Downloading
[13:38:23.436] [InstallWorkflow] Extracting manifest
[13:38:25.667] [InstallWorkflow] Checking prerequisites
[13:38:25.782] [InstallWorkflow] Unpacking artifacts
[13:39:44.901] [InstallWorkflow] Deploying component CommunityInstaller.CreateGroupAction
[13:39:56.437] [InstallWorkflow] Deploying component CommunityInstaller.AddToGroupAction
[13:40:07.815] [InstallWorkflow] Deploying component CommunityInstaller.EnableFeaturesAction
[13:40:08.476] [InstallWorkflow] Component CommunityInstaller.EnableFeaturesAction failed
Exception type: System.Runtime.InteropServices.COMException, Exception message: , StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   at CommunityInstaller.EnableFeaturesAction.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__34.MoveNext()
[13:40:08.479] [InstallWorkflow] Installation failed
Exception type: System.Runtime.InteropServices.COMException, Exception message: , StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__97`1.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at CommunityInstaller.EnableFeaturesAction.GetFeaturesToEnable()
   at CommunityInstaller.EnableFeaturesAction.<DoAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__29.MoveNext()
[13:40:08.482] [InstallWorkflow] Rollbacking component CommunityInstaller.AddToGroupAction
[13:40:08.485] [InstallWorkflow] Rollbacking component CommunityInstaller.CreateGroupAction
[13:40:08.487] [InstallWorkflow] Rollbacking component CommunityInstaller.UnpackArtifactsStep
[13:40:08.495] [FileSystem] Deleting C:\Program Files\Docker\Docker
[13:40:08.756] [FileSystem] Deleted C:\Program Files\Docker\Docker successfully
[13:40:08.758] [InstallWorkflow] Rollbacking component CommunityInstaller.ExtractManifestStep
[13:40:08.760] [InstallWorkflow] Rollbacking component CommunityInstaller.DownloadStep
```

I also can't return to 2.3.0.3 - the installation fails with the same error.

**Comment by StarNamer** [comment]
I have the same issue. Same Docker version on same version of Windows Insider Preview (20175). It seemed to be running fine until it tried to update.  These are the installation logs of my various attempts.

[install-log.1.txt](https://github.com/docker/for-win/files/4986647/install-log.1.txt)
[install-log.2.txt](https://github.com/docker/for-win/files/4986648/install-log.2.txt)
[install-log.3.txt](https://github.com/docker/for-win/files/4986649/install-log.3.txt)
[install-log.4.txt](https://github.com/docker/for-win/files/4986650/install-log.4.txt)
[install-log.5.txt](https://github.com/docker/for-win/files/4986651/install-log.5.txt)
[install-log.6.txt](https://github.com/docker/for-win/files/4986652/install-log.6.txt)
[install-log.7.txt](https://github.com/docker/for-win/files/4986653/install-log.7.txt)
[install-log.txt](https://github.com/docker/for-win/files/4986654/install-log.txt)

**Comment by SR-Lut3t1um** [comment]
I also have the same Issue

**Comment by stephen-turner** [comment]
There's a bug in the latest Insiders build that stops Docker Desktop from working. See #7808.

**Comment by alejandro5042** [comment]
@stephen-turner It seems like the other issue is a runtime issue with `docker pull`. This one is an install issue: we can't even install Docker. It appears the install issue even affects Win 10 build 18363. See #6928.

**Comment by stephen-turner** [comment]
I suspect #6928 is a different issue. It's become far more common with Windows build 20175.

**Comment by mrsombre** [comment]
I can't install on 2004 build

```
Version: 2.3.0.3 (45519)
Channel: stable
Sha1: 0356a6f23f086a8134d83ee38d99ffe55a121f02
Started on: 2020/07/29 15:50:25.161
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2004
Build: 19041
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\dbarsukov\AppData\Local\Docker\install-log.txt
CommandLine: "C:\Program Files\Docker\Docker\InstallerCli.exe" -k -p
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[15:50:25.300][ComponentVersions ][Info   ] Edition community
[15:50:25.329][Installer         ][Info   ] Killing processes...
[15:50:25.355][Installer         ][Error  ] Access is denied
[15:50:25.463] [UninstallWorkflow] Action CommunityInstaller.ExecAction failed
Exception type: System.InvalidOperationException, Exception message: Process InstallerCli.exe exited with code 1, StackTrace:
   at CommunityInstaller.ExecAction.<DoAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__12.MoveNext()
[15:50:25.467] [InstallWorkflow] Installation failed
Exception type: System.InvalidOperationException, Exception message: Process InstallerCli.exe exited with code 1, StackTrace:
   at CommunityInstaller.ExecAction.<DoAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__29.MoveNext()
[15:50:25.469] [InstallWorkflow] Rollbacking component CommunityInstaller.ExtractManifestStep
[15:50:25.470] [InstallWorkflow] Rollbacking component CommunityInstaller.DownloadStep
```

**Comment by metcalfc** [comment]
This WSL2 bug https://github.com/microsoft/WSL/issues/5648 does effect Docker, it is not an issue with Docker. We are hopeful for a fix soon. Right now Windows 20175 and 20180 have this issue. You can disable the WSL2 backend in your Docker settings for now. You won't find docker in your WSL2 path anymore but you can work around this temporarily with:

```
alias docker=docker.exe
```
Docker on the Windows side (powershell, cmd, etc) will behave normally.

**Comment by rbakersmith** [comment]
2.3.0.4 installs for me now (with WSL2 enabled) after upgrading to Windows build 20180.
