### ISSUE TITLE
Unable to run Docker for Windows using TLS with Linux Containers

### ISSUE THREAD

**Issue by northcoder-repo** [docker/for-win#7939]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 5CEBE6D0-2CCF-43E9-82A1-F32E743E3984/20200802201037

### Steps Taken

Go to Docker Desktop > Settings > Docker Engine and replace the default docker daemon config file with this:
```
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "debug": true,
  "experimental": false,
  "tlsverify": true,
  "tlscacert": "C:/Users/atant/OneDrive/Documents/home-projects/docker/dockercerts/ca.pem",
  "tlscert": "C:/Users/atant/OneDrive/Documents/home-projects/docker/dockercerts/server-cert.pem",
  "tlskey": "C:/Users/atant/OneDrive/Documents/home-projects/docker/dockercerts/server-key.pem",
  "hosts": [
    "tcp://0.0.0.0:2376",
    "npipe://"
  ]
}
```
Then apply & restart.

### Expected behavior

Docker Desktop should have restarted and I should have been able to run the following command, to verify the new settings:

```
docker --tlsverify ^
  --tlscacert=C:/Users/atant/OneDrive/Documents/home-projects/docker/dockercerts/ca.pem ^
  --tlscert=C:/Users/atant/OneDrive/Documents/home-projects/docker/dockercerts/cert.pem ^
  --tlskey=C:/Users/atant/OneDrive/Documents/home-projects/docker/dockercerts/key.pem ^
  -H=localhost:2376 version
```

### Actual behavior

At the "apply & restart" step mentioned above, Docker Desktop fails to restart. The following message is displayed in the error window:
```
Docker.Core.DockerException:
Failed to start
   at Docker.LinuxkitDaemonStartup.<StartAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\LinuxkitDaemonStartup.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__24.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 152
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<RestartAsync>d__29.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 274
```
A crash log is generated - see attached.

### Crash log attachment:

[20200802201037.zip](https://github.com/docker/for-win/files/5012860/20200802201037.zip)

### Information

Please note that everything mentioned above works exactly as expected, if I use Windows containers, instead of Linux containers. That is, the daemon config file changes are accepted, Docker Desktop restarts correctly, and I can run my `docker version` command using `tlsverify` and the related certificates.

The crash happens regardless of whether I actually have any Linux docker containers or images, by the way.

  - Windows Version: Windows 10, version 2004, OS build 19041.388
  - Docker Desktop Version: 2.3.0.4 (46911) - stable channel
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

The problem was happening the same as described here, using Hyper-V, prior to my upgrade to using WSL 2. So, it's not a new problem.

### Steps to reproduce the crash

  1. Install Docker Desktop latest stable version (2.3.0.4, in my case).
  2. Choose to use Linux containers.
  3. Set up the required certs, to support TLS connectivity.
  4. Change the docker daemon config file, as described above.
  5. Apply and restart.

**Comment by mstiles92** [comment]
Same exact issue here. Windows 10 Pro, version 2004, OS build 19041.450. Same Docker Desktop version, same daemon config file except for different paths to the location of my certs. I also had the same issue on Hyper-V as well before switching to the WSL 2 backend.

**Comment by Kage-Yami** [comment]
It would appear I'm experiencing the same issue, using the WSL2 backend

Diagnostic ID: `2B75234E-3FDD-4D5F-825E-0464EDE4C4E7/20201029101007`
Docker Engine: `v19.03.13`
Windows 10: Pro 2004 Build `19041.572` / Experience Pack `120.2212.31.0`

**Comment by kphilly1** [comment]
Hello.  Is there any update on this issue?  We're also experiencing a similar issue whereby the Docker Daemon fails to restart if the TLS settings are applied.  We saw this issue on 2.3.0.4, but upgraded to 3.2.2 and still seeing the issue.  The log files don't really produce any output that gives any clear indicator of the root cause.  Please advise.  Thanks.

**Comment by matthew-kenny** [comment]
Same exact issue Windows Server 2022 with wsl2 backend

**Comment by AxelGuignard** [comment]
Any update on this?
I'm having the same issue, I followed the guide from docker website to protect the daemon with TLS and everything is fine until I try to restart docker desktop with the new daemon configuration.
On another subject, I also tried to set the log-driver setting to "windows" in the daemon configuration, and it also failed.
The documentation don't mention that these settings are unsupported, and they shouldn't be.

**Comment by AxelGuignard** [comment]
For future reference, I was able to configure TLS for the docker daemon with Docker Desktop for windows by generating a self-signed certificate using openSSL and registering it in Trusted Root Certification Authorities. Then you just have to restart Docker engine and it works.
**DO NOT** try to edit the engine configuration in the settings of Docker Desktop. It's a trap.
[Link to the related documentation](https://docs.docker.com/registry/insecure/#use-self-signed-certificates)

**Comment by northcoder-repo** [comment]
> For future reference, I was able to configure TLS for the docker daemon with Docker Desktop for windows by generating a self-signed certificate using openSSL and registering it in Trusted Root Certification Authorities.

Thank you @AxelGuignard for mentioning this - much appreciated. I did try this approach, but I guess I'm not doing it correctly... I hit 2 issues: 

(1) Following the details in your link, I see documentation [here](https://docs.docker.com/desktop/faqs/windowsfaqs/#how-do-i-add-custom-ca-certificates) stating that this is to "_verify registry server certificates, and client certificates, to authenticate to registries._" - but I don't have a registry. I just want to use the Docker API (the REST services) over HTTPS rather than HTTP, which seems to be a different thing.

(2) I see [here](https://docs.docker.com/engine/security/certificates/) that the directory I need to use to store my certs is of the form `hostname:port` - so, for example, `localhost:5000` - but Windows does not support using a colon in a directory name. (This documentation is for Linux, of course.) Just using something like `localhhost5000` as my directory name did not appear to have any effect. 

Point (2) probably means I should be placing my key and self-signed cert somewhere else, for Docker to pick up. But it stopped me being able to check point (1) more closely.

At this point, my original issue is no longer a high priority for me (time has passed; I have moved on). But I would still be interested in confirming a solution.

**Comment by AxelGuignard** [comment]
@northcoder-repo Yes, I celebrated a bit early.

When I posted my previous comment (on April 28), I was also just trying to use Docker API. In the latter, I wanted to create a private docker registry that would be accessible from the (internal) network, which also requires to secure the daemon with TLS.

I thought I had win because after doing what I explained, I was able to push an image on my registry from the machine that hosts the registry. However, I failed to push or pull from the registry with another machine on the same network.

So, to answer your questions:
(1) The link is indeed for registry configuration. Some of it still applies I think though. From what I understood, docker desktop for windows uses the certificates registered in "Trusted Root Certification Authorities", so if you have a certificate issued by a CA or a self-signed certificate, you should be able to use it with docker desktop by registering it on windows.

(2) This seems to be the configuration for linux. I don't understand why it is so hard to find documentation for windows.
Well, I do understand, most servers runs on linux, but still... I think it doesn't really matter where you store your certificates on windows, you should just import it in windows configuration as stated in (1).

If you feel like trying a bit on your side, even by simple curiosity, and you happen to get some results, do not hesitate to share your discoveries!

**Comment by HuangFuSL** [comment]
I think [this repo](https://github.com/kekru/docker-remote-api-tls) may provide an alternative approach. I've tested on Docker Desktop 4.21.1 and it worked properly.

Just follow the [instructions](https://github.com/kekru/docker-remote-api-tls#remote-api-with-auto-generating-ca-certificates-and-keys) and download the client certificate from the container, then you can connect to the host using the following command.

```
docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem -H="<your-domain-name>:2376" version
```

The output is

```
Client:
 Cloud integration: v1.0.35
 Version:           24.0.2
 API version:       1.43
 Go version:        go1.20.4
 Git commit:        cb74dfc
 Built:             Thu May 25 21:53:15 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.21.1 (114176)
 Engine:
  Version:          24.0.2
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.4
  Git commit:       659604f
  Built:            Thu May 25 21:52:17 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by AxelGuignard** [comment]
Thanks @HuangFuSL for the suggestion.

I ended up installing docker directly in wsl on an Ubuntu distro. It makes things a lot simpler because you're in linux, so you can actually follow the documentation. You just need to [forward your ports](https://woshub.com/port-forwarding-in-windows/) (at least 2376 to connect to docker with HTTPS, I also did 80 to reach my apache container and 2375 just in case). Then follow the [documentation](https://docs.docker.com/engine/security/protect-access/).

**Comment by TanqiZhou** [comment]
win11 at wsl2;
  "tlscacert": "C:/Users/Administrator/.docker/certs/ca.pem",
  "tlscert": "C:/Users/Administrator/.docker/certs/server-cert.pem",
  "tlskey": "C:/Users/Administrator/.docker/certs/server-key.pem",
  "tlsverify": true
log: 
invalid TLS configuration: could not load X509 key pair ...no such file or directory
EOF
**Developing AI but leaving a bunch of bugs unfixed?**
