### ISSUE TITLE
Unable to start the Docker Daemon

### ISSUE THREAD

**Issue by Legorooj** [docker/for-win#7997]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E579FAEC-58FF-411D-BB0C-90C1670EE907/20200808014739

### Expected behavior

Docker Daemon starting normally.

### Actual behavior

Crashes out with the following error:
<details>
<summary>Stack Trace</summary>

```
Docker.Core.HttpBadResponseException:
Unhandled exception: job failed with message: Failed to create a new virtual machine.

'DockerDesktopVM' failed to realize. (Virtual machine ID 9AE0AB48-9747-489D-9676-7674D2A6F1D4)

Failed to access configuration store: The system cannot find the path specified. (0x80070003).
   at Docker.Core.Logging.ClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\ClientExceptionInterceptor.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<CreateHyperVVMAsync>d__10.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
Original stacktrace:
   at Docker.Backend.HyperVInfrastructure.HandleUpdatedJob(CIMConcreteJob updatedJob) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:line 800
   at Docker.Backend.HyperVInfrastructure.<HandleMaybeAsyncJob>d__37.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:line 740
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HyperVInfrastructure.<CreateDefaultVMAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:line 126
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HyperVInfrastructure.<CreateOrConfigureDockerVMAsync>d__10.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperVInfrastructure.cs:line 97
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HyperV.<CreateOrConfigureAsync>d__8.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV\HyperV.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Backend.HttpAPI.HyperVAPIController.<CreateVMAsync>d__7.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Backend\HttpAPI\HyperVAPIController.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```
</details>

### Information
  - Windows Version: 1909
  - Docker Desktop Version: 2.3.0.4
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No - running Windows 10 Pro on a laptop

### Steps to reproduce the behavior

  1. Install Docker Desktop
  2. Start Docker Desktop

### Additional Information

<details>
<summary>Docker logfile</summary>

```
Version: 2.3.0.4 (46911)
Channel: stable
Sha1: d4f5fcf98140180eeef00e02c1c8bb0ad69e35d3
Started on: 2020/08/08 11:47:27.908
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 1909
Build: 18363
BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
File: C:\Users\legor\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[11:47:28.049][GUI               ][Info   ] Starting...
[11:47:28.209][ComponentVersions ][Info   ] Edition community
[11:47:28.224][ComponentVersions ][Info   ] Edition community
[11:47:30.127][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[11:47:30.215][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[11:47:30.231][SegmentApi        ][Info   ] Usage statistic: Identify
[11:47:30.642][SegmentApi        ][Info   ] Usage statistic: appLaunched
[11:47:31.292][ApplicationTemplatesTracking][Info   ] Cannot list templates
[11:47:31.292][SegmentApi        ][Info   ] Usage statistic: eventTemplatesInfo
[11:47:31.292][SegmentApi        ][Info   ] Usage statistic: heartbeat
[11:47:31.809][LoggingMessageHandler][Info   ] [7689b8f9] <BackendAPIClient start> GET http://backend/version
[11:47:31.875][LoggingMessageHandler][Info   ] [7689b8f9] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 59ms)
[11:47:32.117][LoggingMessageHandler][Info   ] [2669d1e5] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[11:47:32.133][LoggingMessageHandler][Info   ] [2669d1e5] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 6ms)
[11:47:32.133][LoggingMessageHandler][Info   ] [f895d3c8] <BackendAPIClient start> POST http://backend/migrate/app
[11:47:32.133][LoggingMessageHandler][Info   ] [f895d3c8] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 3ms)
[11:47:32.148][Engines           ][Debug  ] Starting
[11:47:32.189][LoggingMessageHandler][Info   ] [4f1d4275] <BackendAPIClient start> POST http://backend/versionpack/enable
[11:47:32.240][LoggingMessageHandler][Info   ] [4f1d4275] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 51ms)
[11:47:32.459][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[11:47:32.475][GoBackendProcess  ][Info   ] Started
[11:47:32.490][MutagenProcess    ][Info   ] Starting C:\ProgramData\Docker\cli-plugins\docker-mutagen.exe mutagen daemon run
[11:47:32.490][MutagenProcess    ][Info   ] Started
[11:47:32.506][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[11:47:32.506][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[11:47:32.506][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxHyperV
[11:47:32.522][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1596851252}
[11:47:32.522][SystrayNotifications][Info   ] Docker is starting
[11:47:33.787][MutagenProcess    ][Info   ] [forwarding] Looking for existing sessions
[11:47:33.787][MutagenProcess    ][Info   ] [forwarding] Session manager initialized
[11:47:33.787][MutagenProcess    ][Info   ] [sync] Looking for existing sessions
[11:47:33.787][MutagenProcess    ][Info   ] [sync] Session manager initialized
[11:47:34.767][LoggingMessageHandler][Info   ] [5f8422ae] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[11:47:34.857][LoggingMessageHandler][Info   ] [5f8422ae] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 91ms)
[11:47:34.862][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[11:47:34.862][LoggingMessageHandler][Info   ] [1bd054b2] <BackendAPIClient start> POST http://backend/hyperv/stop
[11:47:34.892][LoggingMessageHandler][Info   ] [1bd054b2] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 26ms)
[11:47:34.917][VpnKitBridge      ][Info   ] Starting C:\Program Files\Docker\Docker\resources\vpnkit-bridge.exe --addr listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3 host
[11:47:34.917][VpnKitBridge      ][Info   ] Started
[11:47:36.232][VpnKitBridge      ][Info   ] listening on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[11:47:36.232][VpnKitBridge      ][Info   ] waiting for connection on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[11:47:36.281][LoggingMessageHandler][Info   ] [ec59fa01] <Server start> GET http://unix/versions
[11:47:36.447][LoggingMessageHandler][Info   ] [ec59fa01] <Server end> GET http://unix/versions -> 200 OK (took 167ms)
[11:47:37.235][IsoConfig         ][Info   ] Generating CA Cert Bundle
[11:47:37.272][IsoConfig         ][Info   ] CA Cert Bundle Generated
[11:47:37.289][GoBackendProcess  ][Info   ] started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl
[11:47:37.289][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[11:47:37.290][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[11:47:37.291][GoBackendProcess  ][Info   ] enabling filesystem caching
[11:47:37.291][GoBackendProcess  ][Info   ] filesystem exports are:  (2)
[11:47:37.293][GoBackendProcess  ][Info   ] volume control server listening on \\\\.\\pipe\\dockerVolume
[11:47:37.295][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[11:47:37.296][GoBackendProcess  ][Info   ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[11:47:37.296][GoBackendProcess  ][Info   ] file ownership will be determined by the calling user (\"fake owner\" mode)
[11:47:37.296][GoBackendProcess  ][Info   ] using mfsymlinks
[11:47:37.297][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[11:47:37.395][LoggingMessageHandler][Info   ] [ac2b9271] <BackendAPIClient start> POST http://backend/hyperv/create
[11:47:37.761][LoggingMessageHandler][Info   ] [ac2b9271] <BackendAPIClient end> POST http://backend/hyperv/create -> 500 InternalServerError (took 365ms)
[11:47:37.787][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[11:47:37.787][LoggingMessageHandler][Info   ] [fa768aea] <BackendAPIClient start> POST http://backend/hyperv/stop
[11:47:37.806][LoggingMessageHandler][Info   ] [fa768aea] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 18ms)
[11:47:37.818][VpnKitBridge      ][Info   ] Killing existing vpnkit-bridge with PID 18228
[11:47:37.846][LoggingMessageHandler][Info   ] [24bc3fa3] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[11:47:38.636][LoggingMessageHandler][Info   ] [24bc3fa3] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 800ms)
[11:47:38.651][LoggingMessageHandler][Info   ] [36415c96] <BackendAPIClient start> GET http://backend/hyperv/check-virtualization
[11:47:38.667][LoggingMessageHandler][Info   ] [36415c96] <BackendAPIClient end> GET http://backend/hyperv/check-virtualization -> 204 NoContent (took 17ms)
[11:47:38.667][LoggingMessageHandler][Info   ] [3888d951] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[11:47:38.736][LoggingMessageHandler][Info   ] [3888d951] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 63ms)
[11:47:38.736][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[11:47:38.736][LoggingMessageHandler][Info   ] [4d237150] <BackendAPIClient start> POST http://backend/hyperv/stop
[11:47:38.754][LoggingMessageHandler][Info   ] [4d237150] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 18ms)
[11:47:38.772][VpnKitBridge      ][Info   ] Starting C:\Program Files\Docker\Docker\resources\vpnkit-bridge.exe --addr listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3 host
[11:47:38.775][VpnKitBridge      ][Info   ] Started
[11:47:38.775][IsoConfig         ][Info   ] Generating CA Cert Bundle
[11:47:38.835][VpnKitBridge      ][Info   ] listening on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[11:47:38.837][VpnKitBridge      ][Info   ] waiting for connection on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[11:47:38.847][IsoConfig         ][Info   ] CA Cert Bundle Generated
[11:47:38.955][LoggingMessageHandler][Info   ] [304526f5] <BackendAPIClient start> POST http://backend/hyperv/create
[11:47:39.174][LoggingMessageHandler][Info   ] [304526f5] <BackendAPIClient end> POST http://backend/hyperv/create -> 500 InternalServerError (took 220ms)
[11:47:39.174][LinuxHyperVEngine ][Info   ] Stopping watching for host power events
[11:47:39.174][LoggingMessageHandler][Info   ] [2c0af118] <BackendAPIClient start> POST http://backend/hyperv/stop
[11:47:39.190][LoggingMessageHandler][Info   ] [2c0af118] <BackendAPIClient end> POST http://backend/hyperv/stop -> 204 NoContent (took 18ms)
[11:47:39.190][VpnKitBridge      ][Info   ] Killing existing vpnkit-bridge with PID 1808
[11:47:39.205][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[11:47:39.205][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[11:47:39.205][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxHyperV
[11:47:39.205][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1596851259}
[11:47:39.205][SystrayNotifications][Error  ] Unhandled exception: job failed with message: Failed to create a new virtual machine.

'DockerDesktopVM' failed to realize. (Virtual machine ID 9AE0AB48-9747-489D-9676-7674D2A6F1D4)

Failed to access configuration store: The system cannot find the path specified. (0x80070003).
[11:47:39.237][GUI               ][Info   ] Sending Bugsnag report 20fb6d73-f05e-44fa-bb57-8d7a8c00ecb6...
[11:47:39.391][GUI               ][Info   ] Bugsnag report 20fb6d73-f05e-44fa-bb57-8d7a8c00ecb6 sent
[11:47:39.391][SegmentApi        ][Info   ] Usage statistic: eventCrash
[11:47:39.391][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[11:47:39.492][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[11:47:39.493][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[11:47:39.493][GoBackendProcess  ][Info   ] mutagen sync list --output json
[11:47:39.519][GoBackendProcess  ][Info   ] mutagen C:\\ProgramData\\Docker\\cli-plugins\\docker-mutagen.exe mutagen sync list --output json: null\n
[11:47:39.519][GoBackendProcess  ][Info   ] external: GET /sync 200 \"Go-http-client/1.1\" \"\
[11:47:41.422][Engines           ][Error  ] Start failed with Unhandled exception: job failed with message: Failed to create a new virtual machine.

'DockerDesktopVM' failed to realize. (Virtual machine ID 9AE0AB48-9747-489D-9676-7674D2A6F1D4)

Failed to access configuration store: The system cannot find the path specified. (0x80070003).
   at Docker.Core.Logging.ClientExceptionInterceptor.<InterceptResponseAsync>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\ClientExceptionInterceptor.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.BackendAPI.BackendAPIClient.<CreateHyperVVMAsync>d__10.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__24.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 109)
```
</details>

## I've tracked down the exact cause of this issue - I think

Opening Event Viewer straight after opening docker desktop will show the following error:
```
The machine-default permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{C2F03A33-21F5-47FA-B4BB-156362A2F239}
 and APPID 
{316CDED5-E4AE-4B15-9113-7055D84DCC97}
 to the user LEGOROOJ\legor SID (S-1-5-21-1794809802-1247634186-4025354365-1001) from address LocalHost (Using LRPC) running in the application container Microsoft.Windows.ShellExperienceHost_10.0.18362.449_neutral_neutral_cw5n1h2txyewy SID (S-1-15-2-155514346-2573954481-755741238-1654018636-1233331829-3075935687-2861478708). This security permission can be modified using the Component Services administrative tool.
```
The exact Event ID is `10016`.

Opening `regedit` and tracking down that AppID took me to `HKEY_CLASSES_ROOT\CLSID\{c2f03a33-21f5-47fa-b4bb-156362a2f239}.`. 

If you go into Component Services, and try to modify `Immersive Shell`, I find that all of the options are greyed out. I can't edit the launch permissions. I also tried setting the Global Activation Permissions for DCOM services through right-clicking on `My Computer` in the sidebar of Component Services, going into properties, `COM Security`, `Launch and Activation Permission`, and giving my user account full control.

Nothing has worked. I've reinstall docker, restarted and updated Windows. I'm quite stuck with this issue.

Let me know if there is any other information I can give.

**Comment by Legorooj** [comment]
Update: Managed to get it working with the WSL2 backend. Using Hyper-V is still and issue though.
