### ISSUE TITLE
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Element not found. 

### ISSUE THREAD

**Issue by mukeshkagarwal** [docker/for-win#817]
### Expected behavior
It should work properly
### Actual behavior
Crashes with Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Element not found.

   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
DB7A80BB-531B-4A71-9590-4851C998135C/2017-06-13_10-52-29
  - a reproducible case if this is a bug, Dockerfiles FTW
Install Docker and run
  - page URL if this is a docs issue or the name of a man page
No
  - host distribution and version (Windows version, build number, etc)
OS Name	 Microsoft Windows 10 Enterprise
Version	10.0.14393 Build 14393
Processor	Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz, 2701 Mhz, 2 Core(s), 4 Logical Processor(s)

### Steps to reproduce the behavior

  1. Install Docker
  2. Run Docker

**Comment by jasonbivins** [comment]
Hi @mukeshkagarwal    Which build were you using?  Stable or Edge?

**Comment by narayask** [comment]
Do we have any solution for this error. 
Unable to create - The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Element not found.


   at Docker.Core.Pipe.NamedPipeClient.<TrySendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.Core.Pipe.NamedPipeClient.Send(String action, Object[] parameters)
   at Docker.Actions.DoStart(SynchronizationContext syncCtx, Boolean showWelcomeWindow, Boolean executeAfterStartCleanup)
   at Docker.Actions.<>c__DisplayClass24_0.<Start>b__0()
   at Docker.ApiServices.TaskQueuing.TaskQueue.<>c__DisplayClass17_0.<.ctor>b__1()
