### ISSUE TITLE
Cannot start docker service on Win 10 Pro

### ISSUE THREAD

**Issue by vincekovacs** [docker/for-win#819]
### Expected behavior

After login start docker service.

### Actual behavior

After login cannot start docker service

### Information

Diagnostic ID: 2945C7BF-945B-49EF-8B30-7077DD1731D8/2017-06-13_16-10-46
Operating system: Windows 10 Pro

I got following error:
```
The operation has timed out.
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

**Comment by jasonbivins** [comment]
Hi @vincekovacs 

What version of Docker for Windows are you using?  Can try rebooting the machine and starting docker again?

**Comment by vincekovacs** [comment]
Hi,

I'm using `17.03.1-ce-win12 (12058)` from `stable` channel.

Thank you
