### ISSUE TITLE
Windows hns service is running but dockerd fails with - hnsCall failed in Win32: The service has not been started.

### ISSUE THREAD

**Issue by gakera** [docker/for-win#8226]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: FC2D0E6A-B052-4774-9782-768A8F60F9E1/20200825162412

### Expected behavior

Switching to Windows containers should work. 

### Actual behavior

It don't work. 

```
Docker.Core.DockerException:
Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified.

   at Docker.Engines.DockerDaemonChecker.<CheckAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\DockerDaemonChecker.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WindowsContainersEngine.<DoStartAsync>d__12.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WindowsContainersEngine.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

### Information

Please, help us understand the problem.  For instance:
  - Is it reproducible?
Yes, happens every time I switch to Windows containers
  - Is the problem new?
No, I reported this on SO like 9 months ago, and it's still a problem. https://stackoverflow.com/questions/58642314/docker-daemon-on-windows-10-crashing-when-started-hnscall-failed-in-win32-t
  - Did the problem appear with an update?
Maybe, there's like, an update every month...
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.
Can I ship you my computer?
  - Windows Version: (now, no idea what it was when this first started). 
λ systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
  - Docker Desktop Version: (now, but like this started way back last year).
λ docker -v
Docker version 19.03.12, build 48a66213fe
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:
No... just my desktop machine at work. 

### Steps to reproduce the behavior

  1. Have docker installed
  2. Switch to Windows Containers
  3. Crash / error
  4. Upload crash report
  5. Uninstall / Reinstall
  6. Repeat 100x steps 1-5
  7. Nothing happens for months
  8. Try again today
  9. "Reset factory settings", same results
 10. Upload crash report FC2D0E6A-B052-4774-9782-768A8F60F9E1/20200825162412
 11. Notice for the first time a "report issue" option
 12. Report issue
 13. Prepare for disappointment, and non-functioning Windows Containers forever.

**Comment by gakera** [comment]
Trying again what I did on the SO thread, I get similar error, dockerd fails with output: 

```
C:\Program Files\Docker\Docker\resources
λ dockerd
time="2020-08-25T16:38:04.906205700Z" level=info msg="Starting up"
time="2020-08-25T16:38:04.909177500Z" level=debug msg="Listener created for HTTP on npipe (//./pipe/docker_engine)"
time="2020-08-25T16:38:04.913175600Z" level=debug msg="Stackdump - waiting signal at Global\\stackdump-25192"
time="2020-08-25T16:38:04.913175600Z" level=info msg="Windows default isolation mode: hyperv"
time="2020-08-25T16:38:04.914176700Z" level=debug msg="Using default logging driver json-file"
time="2020-08-25T16:38:04.914176700Z" level=debug msg="[graphdriver] trying provided driver: windowsfilter"
time="2020-08-25T16:38:04.915175700Z" level=debug msg="WindowsGraphDriver InitFilter at C:\\ProgramData\\Docker\\windowsfilter"
time="2020-08-25T16:38:04.915175700Z" level=debug msg="Initialized graph driver windowsfilter"
time="2020-08-25T16:38:04.924177400Z" level=debug msg="Max Concurrent Downloads: 3"
time="2020-08-25T16:38:04.924177400Z" level=debug msg="Max Concurrent Uploads: 5"
time="2020-08-25T16:38:04.925175700Z" level=info msg="Loading containers: start."
time="2020-08-25T16:38:04.925175700Z" level=debug msg="Option Experimental: false"
time="2020-08-25T16:38:04.925175700Z" level=debug msg="Option DefaultDriver: nat"
time="2020-08-25T16:38:04.926190500Z" level=debug msg="Option DefaultNetwork: nat"
time="2020-08-25T16:38:04.926190500Z" level=debug msg="Network Control Plane MTU: 1500"
time="2020-08-25T16:38:04.927191300Z" level=info msg="Restoring existing overlay networks from HNS into docker"
time="2020-08-25T16:38:04.927191300Z" level=debug msg="[GET]=>[/networks/] Request : "
time="2020-08-25T16:38:04.934175500Z" level=debug msg="Network Response : [{\"ActivityId\":\"9A83FF02-21EB-49F0-879B-559444E6EC70\",\"AdditionalParams\":{},\"CurrentEndpointCount\":0,\"Extensions\":[{\"Id\":\"E7C3B2F0-F3C5-48DF-AF2B-10FED6D72E7A\",\"IsEnabled\":false,\"Name\":\"Microsoft Windows Filtering Platform\"},{\"Id\":\"E9B59CFA-2BE1-4B21-828F-B6FBDBDDC017\",\"IsEnabled\":false,\"Name\":\"Microsoft Azure VFP Switch Extension\"},{\"Id\":\"EA24CD6C-D17A-4348-9190-09F0D5BE83DD\",\"IsEnabled\":false,\"Name\":\"Microsoft NDIS Capture\"}],\"Flags\":0,\"Health\":{\"LastErrorCode\":0,\"LastUpdateTime\":132427441207010283},\"ID\":\"D63871DB-DF27-4EE6-80FB-6986CA4FDD2A\",\"IPv6\":false,\"LayeredOn\":\"7B01AE19-872A-416D-BA15-AF5CECD5F9E6\",\"MacPools\":[{\"EndMacAddress\":\"00-15-5D-74-AF-FF\",\"StartMacAddress\":\"00-15-5D-74-A0-00\"}],\"MaxConcurrentEndpoints\":0,\"Name\":\"My New Virtual Switch\",\"Policies\":[],\"State\":1,\"TotalEndpoints\":0,\"Type\":\"Transparent\",\"Version\":42949672963,\"Resources\":{\"AdditionalParams\":{},\"AllocationOrder\":0,\"CompartmentOperationTime\":0,\"Flags\":0,\"Health\":{\"LastErrorCode\":0,\"LastUpdateTime\":132427441206541563},\"ID\":\"9A83FF02-21EB-49F0-879B-559444E6EC70\",\"PortOperationTime\":0,\"State\":1,\"SwitchOperationTime\":0,\"VfpOperationTime\":0,\"parentId\":\"18DF5BED-03C6-4825-88D8-90F4DCB5473E\"}}]"
time="2020-08-25T16:38:04.937177500Z" level=debug msg="Network  transparent (263a832) restored"
time="2020-08-25T16:38:04.943176300Z" level=debug msg="[GET]=>[/networks/] Request : "
time="2020-08-25T16:38:04.947185100Z" level=debug msg="Network Response : [{\"ActivityId\":\"9A83FF02-21EB-49F0-879B-559444E6EC70\",\"AdditionalParams\":{},\"CurrentEndpointCount\":0,\"Extensions\":[{\"Id\":\"E7C3B2F0-F3C5-48DF-AF2B-10FED6D72E7A\",\"IsEnabled\":false,\"Name\":\"Microsoft Windows Filtering Platform\"},{\"Id\":\"E9B59CFA-2BE1-4B21-828F-B6FBDBDDC017\",\"IsEnabled\":false,\"Name\":\"Microsoft Azure VFP Switch Extension\"},{\"Id\":\"EA24CD6C-D17A-4348-9190-09F0D5BE83DD\",\"IsEnabled\":false,\"Name\":\"Microsoft NDIS Capture\"}],\"Flags\":0,\"Health\":{\"LastErrorCode\":0,\"LastUpdateTime\":132427441207010283},\"ID\":\"D63871DB-DF27-4EE6-80FB-6986CA4FDD2A\",\"IPv6\":false,\"LayeredOn\":\"7B01AE19-872A-416D-BA15-AF5CECD5F9E6\",\"MacPools\":[{\"EndMacAddress\":\"00-15-5D-74-AF-FF\",\"StartMacAddress\":\"00-15-5D-74-A0-00\"}],\"MaxConcurrentEndpoints\":0,\"Name\":\"My New Virtual Switch\",\"Policies\":[],\"State\":1,\"TotalEndpoints\":0,\"Type\":\"Transparent\",\"Version\":42949672963,\"Resources\":{\"AdditionalParams\":{},\"AllocationOrder\":0,\"CompartmentOperationTime\":0,\"Flags\":0,\"Health\":{\"LastErrorCode\":0,\"LastUpdateTime\":132427441206541563},\"ID\":\"9A83FF02-21EB-49F0-879B-559444E6EC70\",\"PortOperationTime\":0,\"State\":1,\"SwitchOperationTime\":0,\"VfpOperationTime\":0,\"parentId\":\"18DF5BED-03C6-4825-88D8-90F4DCB5473E\"}}]"
time="2020-08-25T16:38:04.951176000Z" level=debug msg="Launching DNS server for network \"none\""
time="2020-08-25T16:38:04.961178900Z" level=debug msg="releasing IPv4 pools from network My New Virtual Switch (263a83221a96f93de6d4244514dc5067bbbe3e6ddb4746b20a502a7e17b0f363)"
time="2020-08-25T16:38:04.962177400Z" level=debug msg="ReleasePool(0.0.0.0/0)"
time="2020-08-25T16:38:04.965176500Z" level=debug msg="cleanupServiceDiscovery for network:263a83221a96f93de6d4244514dc5067bbbe3e6ddb4746b20a502a7e17b0f363"
time="2020-08-25T16:38:04.966175800Z" level=debug msg="cleanupServiceBindings for 263a83221a96f93de6d4244514dc5067bbbe3e6ddb4746b20a502a7e17b0f363"
time="2020-08-25T16:38:04.972176000Z" level=debug msg="Allocating IPv4 pools for network My New Virtual Switch (263a83221a96f93de6d4244514dc5067bbbe3e6ddb4746b20a502a7e17b0f363)"
time="2020-08-25T16:38:04.972176000Z" level=debug msg="RequestPool(LocalDefault, , , map[], false)"
time="2020-08-25T16:38:04.972176000Z" level=debug msg="RequestAddress(0.0.0.0/0, <nil>, map[RequestAddressType:com.docker.network.gateway])"
time="2020-08-25T16:38:04.973176200Z" level=debug msg="[GET]=>[/endpoints/] Request : "
time="2020-08-25T16:38:04.981175700Z" level=debug msg="Launching DNS server for network \"My New Virtual Switch\""
time="2020-08-25T16:38:04.981175700Z" level=debug msg="[GET]=>[/networks/D63871DB-DF27-4EE6-80FB-6986CA4FDD2A] Request : "
time="2020-08-25T16:38:04.986179000Z" level=debug msg="Network Response : {\"ActivityId\":\"9A83FF02-21EB-49F0-879B-559444E6EC70\",\"AdditionalParams\":{},\"CurrentEndpointCount\":0,\"Extensions\":[{\"Id\":\"E7C3B2F0-F3C5-48DF-AF2B-10FED6D72E7A\",\"IsEnabled\":false,\"Name\":\"Microsoft Windows Filtering Platform\"},{\"Id\":\"E9B59CFA-2BE1-4B21-828F-B6FBDBDDC017\",\"IsEnabled\":false,\"Name\":\"Microsoft Azure VFP Switch Extension\"},{\"Id\":\"EA24CD6C-D17A-4348-9190-09F0D5BE83DD\",\"IsEnabled\":false,\"Name\":\"Microsoft NDIS Capture\"}],\"Flags\":0,\"Health\":{\"LastErrorCode\":0,\"LastUpdateTime\":132427441207010283},\"ID\":\"D63871DB-DF27-4EE6-80FB-6986CA4FDD2A\",\"IPv6\":false,\"LayeredOn\":\"7B01AE19-872A-416D-BA15-AF5CECD5F9E6\",\"MacPools\":[{\"EndMacAddress\":\"00-15-5D-74-AF-FF\",\"StartMacAddress\":\"00-15-5D-74-A0-00\"}],\"MaxConcurrentEndpoints\":0,\"Name\":\"My New Virtual Switch\",\"Policies\":[],\"State\":1,\"TotalEndpoints\":0,\"Type\":\"Transparent\",\"Version\":42949672963,\"Resources\":{\"AdditionalParams\":{},\"AllocationOrder\":0,\"CompartmentOperationTime\":0,\"Flags\":0,\"Health\":{\"LastErrorCode\":0,\"LastUpdateTime\":132427441206541563},\"ID\":\"9A83FF02-21EB-49F0-879B-559444E6EC70\",\"PortOperationTime\":0,\"State\":1,\"SwitchOperationTime\":0,\"VfpOperationTime\":0,\"parentId\":\"18DF5BED-03C6-4825-88D8-90F4DCB5473E\"}}"
time="2020-08-25T16:38:04.995175500Z" level=debug msg="Allocating IPv4 pools for network nat (ef32fad53ab7cf92318dd8965a0a3b5a2332c84d72d51dba81f496d0547ee529)"
time="2020-08-25T16:38:04.995175500Z" level=debug msg="RequestPool(LocalDefault, , , map[], false)"
time="2020-08-25T16:38:04.995175500Z" level=debug msg="RequestAddress(0.0.0.0/0, <nil>, map[RequestAddressType:com.docker.network.gateway])"
time="2020-08-25T16:38:04.996176100Z" level=debug msg="HNSNetwork Request ={\"Name\":\"nat\",\"Type\":\"nat\",\"Subnets\":[{\"AddressPrefix\":\"0.0.0.0/0\"}]} Address Space=[{0.0.0.0/0  []}]"
time="2020-08-25T16:38:04.996176100Z" level=debug msg="[POST]=>[/networks/] Request : {\"Name\":\"nat\",\"Type\":\"nat\",\"Subnets\":[{\"AddressPrefix\":\"0.0.0.0/0\"}]}"
time="2020-08-25T16:38:05.779818700Z" level=debug msg="releasing IPv4 pools from network nat (ef32fad53ab7cf92318dd8965a0a3b5a2332c84d72d51dba81f496d0547ee529)"
time="2020-08-25T16:38:05.779818700Z" level=debug msg="ReleasePool(0.0.0.0/0)"
time="2020-08-25T16:38:05.779818700Z" level=debug msg="daemon configured with a 15 seconds minimum shutdown timeout" time="2020-08-25T16:38:05.779818700Z" level=debug msg="start clean shutdown of all containers with a 15 seconds timeout..."
failed to start daemon: Error initializing network controller: Error creating default network: failed during hnsCallRawResponse: hnsCall failed in Win32: The service has not been started. (0x426)
```

**Comment by stephen-turner** [comment]
Thanks for the report. If it's an error in the hns interface, then the bug is in the Windows container code in the engine, which is just an upstream component to us. So I suggest you report it in the moby/moby project. (Sorry, I would just move the ticket, but I can't because the engine is not in the docker org).

**Comment by gakera** [comment]
Allrite... let's get shut down over there, too https://github.com/moby/moby/issues/41423

**Comment by gakera** [comment]
@stephen-turner this was an interesting find, over at the moby issue: https://github.com/moby/moby/issues/41423#issuecomment-693329460

"The question is, why is the docker.exe command opening up a docker_engine named pipe instead of a docker_engine_windows named pipe. And how do I tell it to not do that?"
