### ISSUE TITLE
Docker for Windows fails to start on Windows 10 with VMware PowerCLI installed

### ISSUE THREAD

**Issue by jsonofcourse** [docker/for-win#825]
### Expected behavior
Docker for Windows starts at boot or in response to restart command
### Actual behavior
DFW does not start.
### Information
  - Windows 10.0.15063
  - Docker for Windows Version 17.03.1-ce-win12 (12058) Channel: stable d1db126

```
[23:03:37.931][NamedPipeServer][Error  ] Unable to execute Restart: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 6/14/2017 11:03:37 PM	Get-VM		You are not currently connected to any servers. Please connect first using a Connect cmdlet.	
at <ScriptBlock>, <No file>: line 4    at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters)
   at Docker.Backend.ContainerEngine.Linux.DoStop()
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
[23:03:38.601][NamedPipeClient][Error  ] Unable to send Restart: Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 6/14/2017 11:03:37 PM	Get-VM		You are not currently connected to any servers. Please connect first using a Connect cmdlet.	
at <ScriptBlock>, <No file>: line 4
[23:03:38.601][Notifications  ][Error  ] Unable to stop: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 6/14/2017 11:03:37 PM	Get-VM		You are not currently connected to any servers. Please connect first using a Connect cmdlet.	
at <ScriptBlock>, <No file>: line 4
```

Issue is caused by conflicting cmdlet names within Hyper-V and PowerCLI modules. I was able to correct the error by fully qualifying the Hyper-V cmdlets called in "C:\Program Files\Docker\Docker\resources\MobyLinux.ps1"

Example:
Hyper-V\Get-VM
Hyper-V\Get-VMHost

### Steps to reproduce the behavior

  1. Install and configure Docker for Windows
  2. Install PowerCLI

**Comment by jasonbivins** [comment]
Hi @jsonofcourse 
I put together a quick KB around this, and entered an enhancement request so that we can hopefully handle that a little better.
Do you mind if I go ahead and close this issue out?

**Comment by jsonofcourse** [comment]
Not at all

**Comment by jasonbivins** [comment]
Thanks!

**Comment by jasonbivins** [comment]
@jsonofcourse   Dev has closed out the issue - and looks like the change has been made.  Please check it out in the next release and open up a new issue if you have any problems.
