### ISSUE TITLE
Edge channel latest 17.06.0-rc4-ce-win15 (12573) crashes on start

### ISSUE THREAD

**Issue by JanneRantala** [docker/for-win#830]
### Expected behavior

Docker would start.

### Actual behavior

It doesn't. Fails with exception:

Docker daemon failed with message:

   at Docker.Backend.ContainerEngine.Windows.DoStart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 198
   at Docker.Backend.ContainerEngine.Windows.Restart(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 135
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

### Information

  - Diagnostic ID 7143158E-5CC1-4EAC-B0B4-591C12A47682/2017-06-19_11-04-45
  - Windows 10 Enterprise 1607, Docker latest from edge channel 17.06.0-rc4-ce-win15 (12573)

### Steps to reproduce the behavior

  1. Install latest from edge channel
  2. start Docker

**Comment by jasonbivins** [comment]
Hi @JanneRantala  
Can you try again using the latest Edge build we released today?

I'm really only seeing two errors in the logs - there are quite a few I/O timeouts and I saw this one as well when the service tried to start.

[09:09:27.173][NamedPipeClient][Error  ] Unable to send Start: Windows policy Deny write access to fixed drives not protected by Bitlocker is conflicting with current operation
[09:10:26.352][Notifications  ][Info   ] Docker failed

**Comment by JanneRantala** [comment]
Hi @jasonbivins 

I was able to start with latest from Edge build, thanks!

**Comment by aroder** [comment]
@jasonbivins I see the same error you mention when I try to run the docker daemon. Version 17.06.2-ce. When you mention the latest Edge build, where can I find that, and when is this fix targeted for general release?

**Comment by jasonbivins** [comment]
Hi @aroder 
You can find the latest builds here:  https://docs.docker.com/docker-for-windows/install/

I don't have an eta for a fix yet though
