### ISSUE TITLE
Unable to start docker - Exception 0xc0000005 when running docker version

### ISSUE THREAD

**Issue by esiauwid** [docker/for-win#839]
### Expected behavior
typing docker version should provide the version details of the docker, instead of exception error.

### Actual behavior
PS C:\WINDOWS\system32> docker version
Exception 0xc0000005 0x0 0x7ffb 0x18000890b
PC=0x18000890b
-- see below for full error message.

### Information
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
A diagnostic was uploaded with id: A172C01B-A02D-4CFB-9440-35CF410DD1A6/2017-06-21_10-17-42

  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

Windows 10 Pro
Version 1703
OS Build 15063.413
Intel i7-6700HQ 2.6GHz
32G Ram
64-bit, x64 based processor
Docker is up-to-date to the latest version
### Steps to reproduce the behavior

  1. .Installed Docker on Windows 10 Pro
  2. Open PowerShell in Admin Mode and type "docker version"
- Same error even after uninstall and reinstall.

### Full Error Message and Log

PS C:\WINDOWS\system32> docker version
Exception 0xc0000005 0x0 0x7ffb 0x18000890b
PC=0x18000890b

syscall.Syscall(0x7ffba839bfd0, 0x2, 0x29c, 0x3, 0x0, 0x0, 0x0, 0x2a8)
        /usr/local/go/src/runtime/syscall_windows.go:163 +0x6b
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.setFileCompletionNotificationModes(0x29c, 0x203, 0x0, 0xff
ffffff)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:88 +0x6f
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.makeWin32File(0x29c, 0xc0423c9890, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/file.go:78 +0xd8
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.DialPipe(0xc0420cf0e8, 0x16, 0xc0423c9980, 0x0, 0x12a0920,
 0xc041fe16ff, 0xc0423c99f8)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/pipe.go:188 +0x537
github.com/docker/docker/vendor/github.com/docker/go-connections/sockets.DialPipe(0xc0420cf0e8, 0x16, 0x773594000, 0xc04
2038001, 0x1000000000010, 0x100, 0x100)
        /go/src/github.com/docker/docker/vendor/github.com/docker/go-connections/sockets/sockets_windows.go:26 +0x46
github.com/docker/docker/vendor/github.com/docker/go-connections/sockets.configureNpipeTransport.func1(0xba710f, 0x3, 0x
c0423a36e0, 0x19, 0x60, 0x0, 0xc0423d0001, 0xc0423cc180)
        /go/src/github.com/docker/docker/vendor/github.com/docker/go-connections/sockets/sockets_windows.go:19 +0x49
net/http.(*Transport).dial(0xc0420d0960, 0xf13040, 0xc0420401e0, 0xba710f, 0x3, 0xc0423a36e0, 0x19, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/net/http/transport.go:829 +0x82
net/http.(*Transport).dialConn(0xc0420d0960, 0xf13040, 0xc0420401e0, 0x0, 0xba783f, 0x4, 0xc0423a36e0, 0x19, 0x0, 0x0, .
..)
        /usr/local/go/src/net/http/transport.go:967 +0x1a8c
net/http.(*Transport).getConn.func4(0xc0420d0960, 0xf13040, 0xc0420401e0, 0xc04239b9e0, 0xc0423b8480)
        /usr/local/go/src/net/http/transport.go:885 +0x7f
created by net/http.(*Transport).getConn
        /usr/local/go/src/net/http/transport.go:887 +0x3a8

goroutine 1 [select]:
github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp.Do(0xf13300, 0xc0420413d8, 0xc04239b980, 0xc0420d0a50,
0xc0420d0a50, 0xc0421739e0, 0x599f4c)
        /go/src/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:55 +0x40a
github.com/docker/docker/client.(*Client).doRequest(0xc0423c0000, 0xf13300, 0xc0420413d8, 0xc0420d0a50, 0x6, 0x0, 0x0, 0
x0, 0xc0420d0a50, 0x0)
        /go/src/github.com/docker/docker/client/request.go:127 +0x75
github.com/docker/docker/client.(*Client).Ping(0xc0423c0000, 0xf13300, 0xc0420413d8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/client/ping.go:17 +0x1d4
github.com/docker/docker/cli/command.(*DockerCli).Initialize(0xc0421af4a0, 0xc042308e60, 0x7, 0xc042398d80)
        /go/src/github.com/docker/docker/cli/command/cli.go:158 +0x181
main.newDockerCommand.func2(0xc042398d80, 0xf6a690, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/docker/docker/cmd/docker/docker.go:48 +0xa9
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).execute(0xc042398d80, 0xc0420463b0, 0x0, 0x0, 0xc04239
8d80, 0xc0420463b0)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:628 +0x578
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc04208d680, 0xc04208db00, 0xc042324ce0, 0xc
04206c428)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:742 +0x37e
github.com/docker/docker/vendor/github.com/spf13/cobra.(*Command).Execute(0xc04208d680, 0xc04208d680, 0xf0ad40)
        /go/src/github.com/docker/docker/vendor/github.com/spf13/cobra/command.go:695 +0x32
main.main()
        /go/src/github.com/docker/docker/cmd/docker/docker.go:104 +0xeb

goroutine 18 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:116 +0x15e
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 19 [select]:
net/http.(*Transport).getConn(0xc0420d0960, 0xc0423a36c0, 0x0, 0xba783f, 0x4, 0xc0423a36e0, 0x19, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:890 +0x9d3
net/http.(*Transport).RoundTrip(0xc0420d0960, 0xc0420d0a50, 0xc0420d0960, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:367 +0x31a
net/http.send(0xc0420d0a50, 0xf0a700, 0xc0420d0960, 0x0, 0x0, 0x0, 0x8, 0xc04206c568, 0x411d3f)
        /usr/local/go/src/net/http/client.go:256 +0x166
net/http.(*Client).send(0xc04239b980, 0xc0420d0a50, 0x0, 0x0, 0x0, 0xc04206c568, 0x0, 0x1)
        /usr/local/go/src/net/http/client.go:146 +0x109
net/http.(*Client).doFollowingRedirects(0xc04239b980, 0xc0420d0a50, 0xc2b760, 0x3, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:528 +0x5ec
net/http.(*Client).Do(0xc04239b980, 0xc0420d0a50, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:184 +0x1f1
github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp.Do.func1(0xc04239b980, 0xc0420d0a50, 0xc2b080, 0xc0423b
8420)
        /go/src/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:48 +0x40
created by github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp.Do
        /go/src/github.com/docker/docker/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go:51 +0xe4

goroutine 33 [syscall, locked to thread]:
syscall.Syscall6(0x7ffba8395530, 0x5, 0x2a8, 0xc0423c3f5c, 0xc0423c3f60, 0xc0423c3f68, 0xffffffff, 0x0, 0x7ffba3f21040,
0x1, ...)
        /usr/local/go/src/runtime/syscall_windows.go:174 +0x6b
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.getQueuedCompletionStatus(0x2a8, 0xc0423c3f5c, 0xc0423c3f6
0, 0xc0423c3f68, 0xffffffff, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/zsyscall_windows.go:76 +0xc6
github.com/docker/docker/vendor/github.com/Microsoft/go-winio.ioCompletionProcessor(0x2a8)
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/file.go:129 +0x82
created by github.com/docker/docker/vendor/github.com/Microsoft/go-winio.initIo
        /go/src/github.com/docker/docker/vendor/github.com/Microsoft/go-winio/file.go:57 +0x87
rax     0x0
rbx     0xc042038368
rcx     0x29c
rdi     0x272000
rsi     0xc0423c97a0
rbp     0xc0423c9750
rsp     0x137fda0
r8      0x1
r9      0x29c
r10     0x1f
r11     0xe9d38
r12     0x0
r13     0xd3
r14     0xc2791b
r15     0x3
rip     0x18000890b
rflags  0x10246
cs      0x33
fs      0x53
gs      0x2b

**I also checked the Log files for failed and found these 2 lines (in bold below):**

10:17:21.001][ApiProxy       ][Info   ] proxy << GET /_ping
[10:17:21.002][ApiProxy       ][Info   ] proxy >> GET /v1.27/containers/json
[10:17:21.003][ApiProxy       ][Info   ] Dial Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:21.009][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:21.012][ApiProxy       ][Info   ] proxy << GET /v1.27/containers/json
[10:17:21.033][Moby           ][Info   ] ? Docker daemon working: 17.03.1-ce
[10:17:21.046][Moby           ][Info   ] ? Diagnostics server running: /usr/bin/diagnostics-server -hvsock
[10:17:21.059][Moby           ][Info   ] ? System containerd server running: /usr/bin/containerd
[10:17:21.094][Moby           ][Info   ] ? System containerd working
[10:17:21.134][Moby           ][Info   ]  * Starting Hyper-V daemon: hv_kvp_daemon ... [ ok ]
[10:17:21.161][Moby           ][Info   ]  * Starting Hyper-V daemon: hv_vss_daemon ... [ ok ]
[10:17:21.192][Moby           ][Info   ]  * Adjusting oom killer settings ... [ ok ]
[10:17:21.210][Moby           ][Info   ] 
[10:17:21.214][Moby           ][Info   ] Welcome to Moby
[10:17:21.217][NamedPipeClient][Info   ] Received response for Start
[10:17:21.217][DockerDaemonChecker][Info   ] Docker daemon is running
[10:17:21.217][NamedPipeServer][Info   ] Start done in 00:00:16.6931876.
[10:17:21.222][Moby           ][Info   ] 
[10:17:21.226][NamedPipeClient][Info   ] Sending Mount(C, appuser,:**********, Docker.Core.Settings)...
[10:17:21.227][NamedPipeServer][Info   ] Mount(C, appuser:**********, Docker.Core.Settings)
[10:17:21.227][SambaShare     ][Info   ] Mount C
[10:17:21.239][Moby           ][Info   ]                         ##         .
[10:17:21.254][Cmd            ][Info   ] Share name        C
[10:17:21.254][Cmd            ][Info   ] Path              C:\
[10:17:21.254][Cmd            ][Info   ] Remark            
[10:17:21.254][Cmd            ][Info   ] Maximum users     No limit
[10:17:21.254][Cmd            ][Info   ] Users             appuser     
[10:17:21.254][Cmd            ][Info   ] Caching           Caching disabled
[10:17:21.255][Cmd            ][Info   ] Permission        DESKTOP-R6NF26G\appuser, FULL
[10:17:21.255][Cmd            ][Info   ] 
[10:17:21.255][Cmd            ][Info   ] The command completed successfully.
[10:17:21.255][Cmd            ][Info   ] 
[10:17:21.258][SambaShare     ][Info   ] "C" is shared
[10:17:21.260][Moby           ][Info   ]                   ## ## ##        ==
[10:17:21.273][Moby           ][Info   ]                ## ## ## ## ##    ===
[10:17:21.281][Moby           ][Info   ]            /"""""""""""""""""\___/ ===
[10:17:21.292][Moby           ][Info   ]       ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
[10:17:21.299][Moby           ][Info   ]            \______ o           __/
[10:17:21.307][Moby           ][Info   ]              \    \         __/
[10:17:21.319][Moby           ][Info   ]               \____\_______/
[10:17:21.321][Moby           ][Info   ] 
[10:17:21.325][Moby           ][Info   ] 
[10:17:21.382][SambaShare     ][Info   ] Username: appuser
[10:17:21.382][SambaShare     ][Info   ] Host IP: 10.0.75.1
[10:17:21.382][SambaShare     ][Info   ] Cifs options: noperm,iocharset=utf8,nobrl,mfsymlinks,vers=3.02,domain=DESKTOP-R6NF26G
[10:17:21.437][ApiProxy       ][Info   ] proxy >> GET /_ping
[10:17:21.438][ApiProxy       ][Info   ] Dial Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:21.438][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:21.439][ApiProxy       ][Info   ] proxy << GET /_ping
[10:17:21.444][ApiProxy       ][Info   ] proxy >> POST /v1.27/images/load?quiet=1
[10:17:21.444][ApiProxy       ][Info   ] Dial Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:21.450][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:21.585][ApiProxy       ][Info   ] proxy << POST /v1.27/images/load?quiet=1
[10:17:21.882][ApiProxy       ][Info   ] proxy >> GET /_ping
[10:17:21.882][ApiProxy       ][Info   ] Dial Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:21.883][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:21.884][ApiProxy       ][Info   ] proxy << GET /_ping
[10:17:21.887][ApiProxy       ][Info   ] proxy >> POST /v1.27/containers/create [rewriteBinds]
[10:17:21.888][DataKit        ][Info   ] com.docker.db.exe: accepted a new connection on \\.\pipe\dockerDataBase
[10:17:21.888][DataKit        ][Info   ] com.docker.db.exe: Using protocol TwoThousand msize 16384
**[10:17:21.896][ApiProxy       ][Info   ] Failed to Walk to [snapshots bab850d6e8c208c0042d0a9e077c10553c1ed3c7 ro com.docker.driver.amd64-linux proxy http] 9p: No such file or directory
[10:17:21.897][ApiProxy       ][Info   ] Failed to read proxies/http from snaphshot p9p.MessageRerror{Ename:"No such file or directory"}**
[10:17:21.897][ApiProxy       ][Info   ] proxy >> POST /v1.27/containers/create
[10:17:21.897][ApiProxy       ][Info   ] Dial Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:21.898][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:22.053][ApiProxy       ][Info   ] proxy << POST /v1.27/containers/create
[10:17:22.062][ApiProxy       ][Info   ] proxy >> POST /v1.27/containers/6fb71c309064355480ce1d46af779f300604ec6b33a2984fa47b27fbbdbb072d/attach?stderr=1&stdin=1&stdout=1&stream=1
[10:17:22.062][ApiProxy       ][Info   ] Dial Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:22.063][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:22.064][ApiProxy       ][Info   ] Upgrading to raw stream
[10:17:22.064][ApiProxy       ][Info   ] proxy >> GET /v1.27/events?filters=%7B%22container%22%3A%7B%226fb71c309064355480ce1d46af779f300604ec6b33a2984fa47b27fbbdbb072d%22%3Atrue%7D%2C%22type%22%3A%7B%22container%22%3Atrue%7D%7D
[10:17:22.064][ApiProxy       ][Info   ] Dial Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:22.064][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:22.067][ApiProxy       ][Info   ] proxy >> POST /v1.27/containers/6fb71c309064355480ce1d46af779f300604ec6b33a2984fa47b27fbbdbb072d/start [start]
[10:17:22.067][ApiProxy       ][Info   ] proxy >> POST /v1.27/containers/6fb71c309064355480ce1d46af779f300604ec6b33a2984fa47b27fbbdbb072d/start
[10:17:22.067][ApiProxy       ][Info   ] Dial Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:22.069][ApiProxy       ][Info   ] Successfully dialed Hyper-V socket 56bb1e63-bc30-490e-bcff-dc816d564dec:23a432c2-537a-4291-bcb5-d62504644739
[10:17:22.348][ApiProxy       ][Info   ] proxy << POST /v1.27/containers/6fb71c309064355480ce1d46af779f300604ec6b33a2984fa47b27fbbdbb072d/start
[10:17:22.469][ApiProxy       ][Info   ] proxy << POST /v1.27/containers/6fb71c309064355480ce1d46af779f300604ec6b33a2984fa47b27fbbdbb072d/attach?stderr=1&stdin=1&stdout=1&stream=1
[10:17:23.099][ApiProxy       ][Info   ] Cancel connection...
[10:17:23.101][NamedPipeClient][Info   ] Received response for Mount
[10:17:23.102][Actions        ][Debug  ] Start took 00:00:18.5772595
[10:17:23.102][Notifications  ][Info   ] Docker is running
[10:17:23.102][SegmentApi     ][Info   ] Usage statistic: appRunning
[10:17:23.101][NamedPipeServer][Info   ] Mount done in 00:00:01.8745525.
[10:17:23.101][ApiProxy       ][Info   ] proxy << GET /v1.27/events?filters=%7B%22container%22%3A%7B%226fb71c309064355480ce1d46af779f300604ec6b33a2984fa47b27fbbdbb072d%22%3Atrue%7D%2C%22type%22%3A%7B%22container%22%3Atrue%7D%7D
[10:17:23.132][NamedPipeClient][Info   ] Sending GetDefaultVhdxPath()...
[10:17:23.132][NamedPipeServer][Info   ] GetDefaultVhdxPath()
[10:17:23.134][NamedPipeClient][Info   ] Received response for GetDefaultVhdxPath
[10:17:23.134][NamedPipeServer][Info   ] GetDefaultVhdxPath done in 00:00:00.0020002.
[10:17:25.100][DnsUpdater     ][Info   ] Network configuration change detected
[10:17:25.100][PowerShell     ][Info   ] Run script '$(Find-NetRoute -RemoteIPAddress 8.8.8.8).InterfaceIndex[0]'...

**Comment by jasonbivins** [comment]
Hi @esiauwid    
Is windows running on a virtual or physical box?

Can you run the Debug-ContainerHost.ps1  script posted here and let me know what you get?
   https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/Debug-ContainerHost

**Comment by jasonbivins** [comment]
Hi @esiauwid 
I looked through the log again, and don't see any obvious errors there - can you please send me the resutls of the debug script?
