### ISSUE TITLE
Docker Build causes panic

### ISSUE THREAD

**Issue by kryton** [docker/for-win#84]
running Docker4Win (Beta) -  9C3411FC-B7F8-492E-9A8E-087E63AD674E/2016-09-15_18-18-08

set REPO=docker-registry-v2.XXXXXXXXXXX.com
docker build --rm=true -t %REPO%/dr_offline .

time="2016-09-15T18:14:36-05:00" level=error msg="Can't add file \\\\?\\C:\\GD\\work\\src\\offline\\.git\\hooks\\prepare-commit-msg.sample to tar: io: read/write on closed pipe"
An ertime="2016-09-15T18:14:36-05:00" level=error msg="Can't add file \\\\?\\C:\\GD\\work\\src\\offline\\.git\\hooks\\prepare-commit-msg.sample to tar: io: read/write on closed pipe"
An error occurred trying to connect: Post http://192.168.211.128:2375/v1.24/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&rm=1&shmsize=0&t=docker-registry-v2.digitalriver-external.com%2Fdr_offline&ulimits=null: dial tcp 192.168.211.128:2375: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
panic: bytes.Buffer: truncation out of range

goroutine 1 [running]:
panic(0xaaf580, 0xc0822cad40)
        /usr/local/go/src/runtime/panic.go:481 +0x3f4
bytes.(*Buffer).Truncate(0xc0820db6d0, 0x0)
        /usr/local/go/src/bytes/buffer.go:71 +0xc6
bytes.(*Buffer).WriteTo(0xc0820db6d0, 0x14c41c0, 0xc082026018, 0x2d1, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:225 +0x1b6
github.com/Azure/go-ansiterm/winterm.(*windowsAnsiEventHandler).Flush(0xc0820db6b0, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/Azure/go-ansiterm/winterm/win_event_handler.go:674 +0x216
github.com/Azure/go-ansiterm.(*AnsiParser).Parse(0xc0820aa780, 0xc08237a000, 0x21e, 0x240, 0x1, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/Azure/go-ansiterm/parser.go:89 +0x123
github.com/docker/docker/pkg/term/windows.(*ansiWriter).Write(0xc0821eb1a0, 0xc08237a000, 0x21e, 0x240, 0x410101, 0x0, 0x0)
        /go/src/github.com/docker/docker/pkg/term/windows/ansi_writer.go:63 +0x2bf
fmt.Fprintln(0x14c8f60, 0xc0821eb1a0, 0xc082447e18, 0x1, 0x1, 0xc0822ca8e0, 0x0, 0x0)
        /usr/local/go/src/fmt/print.go:255 +0xac
main.main()
        /go/src/github.com/docker/docker/cmd/docker/docker.go:84 +0x746

C:\GD\work\src\offline>

### Information

  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by kryton** [comment]
please close. I had my docker host environment variable set, and this is probably why it was happening.
it's more an issue with the docker client I'd guess
