### ISSUE TITLE
Cannot create MobyLinux VM-Host is shorter than computer name so can't be resolved

### ISSUE THREAD

**Issue by novaterata** [docker/for-win#846]
### Expected behavior
Docker for Window starts with no error
### Actual behavior
Docker can't start, has a red icon, and gives the following error:
```
Unable to create: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The computer 'XXXX-XXXXXXXX-1' could not be resolved. Make sure you typed the machine name correctly and that you have network access.
at New-MobyLinuxVM, <No file>: line 222
at <ScriptBlock>, <No file>: line 385
   at Docker.Backend.HyperV.RunScript(String action, Dictionary`2 parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\HyperV.cs:line 177
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 123
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145

```

### Information
My computer is named XXXX-XXXXXXXX-10
The result of `Get-VMHost -ComputerName localhost` is XXXX-XXXXXXXX-1

### Steps to reproduce the behavior
  1. Give your computer a long enough name, at least 16 characters (might not be necessary)
  1. Enable Hyper-V
  1. Restart
  1. Disable Containers if enabled
  1. Install Docker for Windows
  1. Start Docker for Windows

UPDATE:
Uninstalling Hyper-V and Docker for Windows, then reinstalling Hyper-V, Containers, and Docker for Windows solved the problem, so the real issue is that there is no warning or helpful error that Containers must be enabled before installing Docker for Windows.

**Comment by novaterata** [comment]
Ok, that's weird, I manually ran the command `New-VM -Name Foo -Generation 2 -NoVHD` and it worked. I then deleted that VM and ran `MobyLinux.ps1 -Create` again and it worked this time. I don't have a clue now, but it happens frequently.

**Comment by novaterata** [comment]
https://github.com/docker/for-win/issues/587  This was the issue that looks to the be the same, but was Closed. Maybe I'm confused, but I thought this would be in Edge by now. I'll try doing a complete uninstall of Docker and then reinstall Edge

**Comment by jasonbivins** [comment]
Hi @novaterata 
It looks like the virtual adapter in Hyper-V might not be getting created correctly, or getting connected every time.  
Can you run the debug script located here and let me know what you get?
https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/Debug-ContainerHost

**Comment by novaterata** [comment]
@jasonbivins 

```
Checking for common problems
Describing Windows Version and Prerequisites
 [+] Is Windows 10 Anniversary Update or Windows Server 2016 702ms
 [+] Has KB3192366, KB3194496, or later installed if running Windows build 14393 131ms
 [+] Is not a build with blocking issues 22ms
 [-] Has 'Containers' feature installed 41.96s
   Expected: {Enabled}
   But was:  {Disabled}
   23:             (Get-WindowsOptionalFeature -Online -FeatureName Containers).State | Should Be "Enabled"
   at <ScriptBlock>, C:\Program Files\Docker\Docker\resources\Debug-ContainerHost.ps1: line 23
Describing Docker is installed
 [+] A Docker service is installed - 'Docker' or 'com.Docker.Service'  76ms
 [+] Service is running 22ms
 [+] Docker.exe is in path 2.17s
 [+] Docker is registered in the EventLog service 105ms
Describing User has permissions to use Docker daemon
 [+] docker.exe should not return access denied 43ms
Describing Windows container settings are correct
 [+] Do not have DisableVSmbOplock set to 1 25ms
 [+] Do not have zz values set 23ms
 [+] Do not have FDVDenyWriteAccess set to 1 21ms
Describing The right container base images are installed
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/images/json: open //./pipe/docker_engine: The syst                                                                                                                                                       em cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevate                                                                                                                                                       d to connect. This error may also indicate that the docker daemon is not running.
 [-] At least one of 'microsoft/windowsservercore' or 'microsoft/nanoserver' should be installed 224ms
   ValidationMetadataException: The argument is null or empty. Provide an argument that is not null or empty, and then t                                                                                                                                                       ry the command again.
   ParameterBindingValidationException: Cannot validate argument on parameter 'Property'. The argument is null or empty.                                                                                                                                                        Provide an argument that is not null or empty, and then try the command again.
   at <ScriptBlock>, C:\Program Files\Docker\Docker\resources\Debug-ContainerHost.ps1: line 115
Describing Container network is created
 [+] At least one local container network is available 1.09s
 [-] At least one NAT, Transparent, or L2Bridge Network exists 57ms
   Expected {0} to be greater than {0}
   206:       $totalnets | Should BeGreaterThan 0
   at <ScriptBlock>, C:\Program Files\Docker\Docker\resources\Debug-ContainerHost.ps1: line 206
 [-] NAT Network's vSwitch is internal 29ms
   Expected: {Internal}
   But was:  {}
   211:       $switchType | Should Be "Internal"
   at <ScriptBlock>, C:\Program Files\Docker\Docker\resources\Debug-ContainerHost.ps1: line 211
 [+] A Windows NAT is configured if a Docker NAT network exists 340ms
 [-] Specified Network Gateway IP for NAT network is assigned to Host vNIC 29ms
   Expected: value to not be empty
   225:       $natGatewayIP | Should Not BeNullOrEmpty
   at <ScriptBlock>, C:\Program Files\Docker\Docker\resources\Debug-ContainerHost.ps1: line 225
 [-] NAT Network's internal prefix does not overlap with external IP' 29ms
   Expected {0} to be greater than {0}
   252:         $hostips.Count | Should BeGreaterThan 0
   at <ScriptBlock>, C:\Program Files\Docker\Docker\resources\Debug-ContainerHost.ps1: line 252
Showing output from: docker info

Showing output from: docker version
Client:
 Version:      17.06.0-ce-rc5
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   b7e4173
 Built:        Tue Jun 20 07:13:29 2017
 OS/Arch:      windows/amd64

Showing output from: docker network ls

Getting Warnings & errors in the Windows event logs from the last 24 hours
Logs saved to C:\Program Files\Docker\Docker\resources\logs_20170623-150957.csv


Getting Docker for Windows daemon logs from the last execution
    Note: More logs are available at C:\Users\critchea\AppData\Local\Docker. Only showing the latest.
```

**Comment by jasonbivins** [comment]
Hi @novaterata  It does look like a couple of the features got missed during the install.
Please try the below steps:

Warning - You will lose any docker containers or images. As always, please run a full backup before making any changes.
These steps can be done through the Windows control panel, or using the below Powershell commands with elevated privileges.

- Uninstall Docker, Hyper-V, and if installed - the Windows containers feature. Then reboot.
- Enable Hyper-V
-      Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
- Reboot, then enable the containers feature. 
-      Enable-WindowsOptionalFeature -Online -FeatureName Containers -All
- Install Docker

**Comment by novaterata** [comment]
@jasonbivins That solved it. I thought only Hyper-V was a requirement as I only use Linux containers. So still seems likea bug to me. I'll update the description

**Comment by jasonbivins** [comment]
Hi @novaterata 
We actually use a small Linux image in the Hyper-V to perform some of the translations - but Windows has recently announced that they are working on supporting Linux Containers on Windows (LCOW)  so this may change in the future, but I don't have a time frame yet.  
Do you mind if I go ahead and close this issue?

**Comment by novaterata** [comment]
Sure

**Comment by novaterata** [comment]
I mean, go ahead and close it. Thanks for your help

**Comment by jasonbivins** [comment]
You're welcome @novaterata !

**Comment by savbace** [comment]
Workaround: **stop/start Hyper-V service** helped me - after doing this Docker has started successfully.

![Image of Yaktocat](https://cdn.pbrd.co/images/HTF6XSj.png)
