### ISSUE TITLE
Docker edge failed again and again and finally killed my WSL

### ISSUE THREAD

**Issue by smallst** [docker/for-win#8463]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:
533EEDEC-5C97-40E7-B295-4E31D9D4531B/20200913083006
### Expected behavior
expect docker desktop to work normally, i mean, can connect docker from both windows and wsl.
### Actual behavior
cann't connect docker from wsl (wsl2 arch).
`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

 from https://github.com/docker/for-win/issues/8183#issuecomment-689400672 i see it may be something related to glibc.
i'm not very urgent to see `docker ps` worked but after a while i found docker killed my WSL distro. that's really trouble me.
since https://github.com/docker/for-win/issues/8183 is closed i open this one to wait a solution. thanks!
### Information

  - Windows Version: 2004(19041.508)
  - Docker Desktop Version: edge 2.3.6.2(47842)
  - WSL version: Linux 4.19.104-microsoft-standard, glibc 2.32-4 
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No, it is a normal pc.

i have the log repeat again and again and finally killed my WSL then got another log.: 
```
[10:33:40.583][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:33:40 Proxy error: exit status 2
[10:33:48.957][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:33:48 Existing cli api socket file /home/smallst/.docker/run/docker-cli-api.sock, trying to clean it
[10:33:49.104][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:33:49 Starting distro cli api server on /home/smallst/.docker/run/docker-cli-api.sock
[10:33:49.110][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:33:49 Starting WSL Distro proxy
[10:33:49.351][WslIntegrationAgent-Arch][Info   ] fatal error: unexpected signal during runtime execution
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] [signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7fd108c09e84]
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] runtime stack:
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] runtime.throw(0xb4f25b, 0x2a)
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/runtime/panic.go:1116 +0x74
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] runtime.sigpanic()
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/runtime/signal_unix.go:679 +0x46e
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] goroutine 1 [syscall]:
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] runtime.cgocall(0xa8dac0, 0xc000277aa0, 0xc000132830)
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/runtime/cgocall.go:133 +0x5d fp=0xc000277a70 sp=0xc000277a38 pc=0x404fed
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] os/user._Cfunc_mygetgrnam_r(0xc0003f6490, 0xc0003f2900, 0x319a080, 0x400, 0xc000132830, 0x0)
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] 	_cgo_gotypes.go:123 +0x4f fp=0xc000277aa0 sp=0xc000277a70 pc=0x51c63f
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] os/user.lookupGroup.func1.1(0xc0003f6490, 0x7, 0x7, 0xc0003f2900, 0xc00038eed0, 0xc000132830, 0x7fd132b0fe98)
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/os/user/cgo_lookup_unix.go:146 +0xf5 fp=0xc000277af0 sp=0xc000277aa0 pc=0x51e7e5
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] os/user.lookupGroup.func1(0xd69340)
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/os/user/cgo_lookup_unix.go:146 +0x59 fp=0xc000277b38 sp=0xc000277af0 pc=0x51e869
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] os/user.retryWithBuffer(0xc00038eed0, 0xc000277c28, 0x6, 0xc0003f6490)
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/os/user/cgo_lookup_unix.go:247 +0x3d fp=0xc000277b90 sp=0xc000277b38 pc=0x51dc3d
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] os/user.lookupGroup(0xb34755, 0x6, 0x0, 0x0, 0x0)
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/os/user/cgo_lookup_unix.go:141 +0x1a1 fp=0xc000277c80 sp=0xc000277b90 pc=0x51d321
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] os/user.LookupGroup(...)
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/os/user/lookup.go:51
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] main.main()
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] 	/go/src/github.com/docker/pinata/docker-desktop-proxy/main.go:105 +0x774 fp=0xc000277f88 sp=0xc000277c80 pc=0xa8a164
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] runtime.main()
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/runtime/proc.go:203 +0x202 fp=0xc000277fe0 sp=0xc000277f88 pc=0x4379d2
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] runtime.goexit()
[10:33:49.353][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000277fe8 sp=0xc000277fe0 pc=0x464d31
[10:33:49.451][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:33:49 Proxy error: exit status 2
[10:33:56.368][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:33:56 Existing cli api socket file /home/smallst/.docker/run/docker-cli-api.sock, trying to clean it
[10:33:56.514][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:33:56 Starting distro cli api server on /home/smallst/.docker/run/docker-cli-api.sock
[10:33:56.520][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:33:56 Starting WSL Distro proxy
[10:33:56.778][WslIntegrationAgent-Arch][Info   ] fatal error: unexpected signal during runtime execution
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] [signal SIGSEGV: segmentation violation code=0x1 addr=0xe5 pc=0x7fdcb9a6fe84]
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] runtime stack:
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] runtime.throw(0xb4f25b, 0x2a)
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/runtime/panic.go:1116 +0x74
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] runtime.sigpanic()
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/runtime/signal_unix.go:679 +0x46e
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] goroutine 1 [syscall]:
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] runtime.cgocall(0xa8dac0, 0xc00025faa0, 0xc0000da818)
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/runtime/cgocall.go:133 +0x5d fp=0xc00025fa70 sp=0xc00025fa38 pc=0x404fed
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] os/user._Cfunc_mygetgrnam_r(0xc0003a4490, 0xc0003948a0, 0x2e34080, 0x400, 0xc0000da818, 0x0)
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] 	_cgo_gotypes.go:123 +0x4f fp=0xc00025faa0 sp=0xc00025fa70 pc=0x51c63f
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] os/user.lookupGroup.func1.1(0xc0003a4490, 0x7, 0x7, 0xc0003948a0, 0xc00032eed0, 0xc0000da818, 0x7fdce31347d0)
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/os/user/cgo_lookup_unix.go:146 +0xf5 fp=0xc00025faf0 sp=0xc00025faa0 pc=0x51e7e5
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] os/user.lookupGroup.func1(0xd69340)
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/os/user/cgo_lookup_unix.go:146 +0x59 fp=0xc00025fb38 sp=0xc00025faf0 pc=0x51e869
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] os/user.retryWithBuffer(0xc00032eed0, 0xc00025fc28, 0x6, 0xc0003a4490)
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/os/user/cgo_lookup_unix.go:247 +0x3d fp=0xc00025fb90 sp=0xc00025fb38 pc=0x51dc3d
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] os/user.lookupGroup(0xb34755, 0x6, 0x0, 0x0, 0x0)
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/os/user/cgo_lookup_unix.go:141 +0x1a1 fp=0xc00025fc80 sp=0xc00025fb90 pc=0x51d321
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] os/user.LookupGroup(...)
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/os/user/lookup.go:51
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] main.main()
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] 	/go/src/github.com/docker/pinata/docker-desktop-proxy/main.go:105 +0x774 fp=0xc00025ff88 sp=0xc00025fc80 pc=0xa8a164
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] runtime.main()
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/runtime/proc.go:203 +0x202 fp=0xc00025ffe0 sp=0xc00025ff88 pc=0x4379d2
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] runtime.goexit()
[10:33:56.780][WslIntegrationAgent-Arch][Info   ] 	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00025ffe8 sp=0xc00025ffe0 pc=0x464d31
[10:33:56.881][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:33:56 Proxy error: exit status 2
[10:34:02.193][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:34:02 Existing cli api socket file /home/smallst/.docker/run/docker-cli-api.sock, trying to clean it
[10:34:02.399][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:34:02 Starting distro cli api server on /home/smallst/.docker/run/docker-cli-api.sock
[10:34:02.405][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:34:02 Starting WSL Distro proxy
[10:34:02.677][WslIntegrationAgent-Arch][Info   ] fatal error: unexpected signal during runtime execution
...
...
[10:39:15.382][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:39:15 Proxy error: exit status 2
[10:39:19.135][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:39:19 Error while syncing ~/.aws: subdir .aws not synced: exit status 4294967295
[10:40:19.290][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:40:19 Error while syncing ~/.azure: subdir .azure not synced: exit status 4294967295
[10:40:49.350][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:40:49 Unable to start cli api server: unable to get distro home folder: exit status 4294967295
[10:40:49.350][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:40:49 Starting WSL Distro proxy
[10:41:49.476][WslIntegrationAgent-Arch][Info   ] ?(u?N  L i n u x   ?v  W i n d o w s   P[?|?~?[?O?]?~bk0
 
 
[10:41:49.485][WslIntegrationAgent-Arch][Info   ]  2020/09/13 10:41:49 Proxy error: exit status 4294967295
[10:42:23.573][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:42:23 unable to create ~/.docker/run directory: exit status 4294967295
[10:42:55.017][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:42:55 unable to create ~/.docker/run directory: exit status 4294967295
[10:43:28.967][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:43:28 unable to create ~/.docker/run directory: exit status 4294967295
[10:44:01.929][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:44:01 unable to create ~/.docker/run directory: exit status 4294967295
[10:44:36.650][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:44:36 unable to create ~/.docker/run directory: exit status 4294967295
[10:45:10.591][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:45:10 unable to create ~/.docker/run directory: exit status 4294967295
[10:45:46.274][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:45:46 unable to create ~/.docker/run directory: exit status 4294967295
[10:46:20.629][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:46:20 unable to create ~/.docker/run directory: exit status 4294967295
[10:46:53.691][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:46:53 unable to create ~/.docker/run directory: exit status 4294967295
[10:47:27.327][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:47:27 unable to create ~/.docker/run directory: exit status 4294967295
[10:48:01.881][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:48:01 unable to create ~/.docker/run directory: exit status 4294967295
[10:48:35.320][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:48:35 unable to create ~/.docker/run directory: exit status 4294967295
[10:49:11.359][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:49:11 unable to create ~/.docker/run directory: exit status 4294967295
[10:49:44.872][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:49:44 unable to create ~/.docker/run directory: exit status 4294967295
[10:50:20.677][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:50:20 unable to create ~/.docker/run directory: exit status 4294967295
[10:50:36.740][SegmentApi        ][Info   ] Usage statistic: heartbeat
[10:50:54.264][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:50:54 unable to create ~/.docker/run directory: exit status 4294967295
[10:51:26.447][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:51:26 unable to create ~/.docker/run directory: exit status 4294967295
[10:52:02.559][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:52:02 unable to create ~/.docker/run directory: exit status 4294967295
[10:52:36.280][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:52:36 unable to create ~/.docker/run directory: exit status 4294967295
[10:53:11.452][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:53:11 unable to create ~/.docker/run directory: exit status 4294967295
[10:53:43.415][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:53:43 unable to create ~/.docker/run directory: exit status 4294967295
[10:54:17.576][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:54:17 unable to create ~/.docker/run directory: exit status 4294967295
[10:54:53.114][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:54:53 unable to create ~/.docker/run directory: exit status 4294967295
[10:55:29.061][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:55:29 unable to create ~/.docker/run directory: exit status 4294967295
[10:56:00.910][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:56:00 unable to create ~/.docker/run directory: exit status 4294967295
[10:56:32.597][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:56:32 unable to create ~/.docker/run directory: exit status 4294967295
[10:57:07.815][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:57:07 unable to create ~/.docker/run directory: exit status 4294967295
[10:57:43.060][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:57:43 unable to create ~/.docker/run directory: exit status 4294967295
[10:58:17.248][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:58:17 unable to create ~/.docker/run directory: exit status 4294967295
[10:58:48.549][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:58:48 unable to create ~/.docker/run directory: exit status 4294967295
[10:59:20.474][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:59:20 unable to create ~/.docker/run directory: exit status 4294967295
[10:59:52.181][WslIntegrationAgent-Arch][Info   ] 2020/09/13 10:59:52 unable to create ~/.docker/run directory: exit status 4294967295
[11:00:27.623][WslIntegrationAgent-Arch][Info   ] 2020/09/13 11:00:27 unable to create ~/.docker/run directory: exit status 4294967295
[11:01:01.772][WslIntegrationAgent-Arch][Info   ] 2020/09/13 11:01:01 unable to create ~/.docker/run directory: exit status 4294967295
[11:01:33.568][WslIntegrationAgent-Arch][Info   ] 2020/09/13 11:01:33 unable to create ~/.docker/run directory: exit status 4294967295
[11:02:09.623][WslIntegrationAgent-Arch][Info   ] 2020/09/13 11:02:09 unable to create ~/.docker/run directory: exit status 4294967295
```
### Steps to reproduce the behavior

just start docker desktop and wait... from my log the issue comes about 40 minutes later ..

**Comment by smallst** [comment]
fix by 2.3.7.0
