### ISSUE TITLE
Docker Desktop update 2.3.0.5 fails to install

### ISSUE THREAD

**Issue by rmorrise** [docker/for-win#8491]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - I am unable to run Diagnostics, because nothing happens when I click "Diagnostics" from the Troubleshoot menu. It looks like Docker Desktop is stuck in an updating state.

### Expected behavior
- Docker Desktop should install updates normally
- Diagnostics should run when I click on Diagnostics

### Actual behavior
1) It says Docker Desktop Installation Failed with the following exception:
```
Response status code does not indicate success: 403 (Forbidden).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at CommunityInstaller.DownloadStep.<DoAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__29.MoveNext()
```
2) When I go to Troubleshoot and click the Diagnostics button, nothing happens at all. In the bottom left it says Docker updating.

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior
  1. Right-click on system tray > Check for Updates
  2. Install Update
  3. Accept windows UAC prompt

**Comment by rmorrise** [comment]
I am running windows 10, Version	10.0.18363 Build 18363
When I go to "About Docker Desktop", the version and channel information come up blank on the about dialog, and are not populated.

Let me know if there is any other information I can provide.

**Comment by mat007** [comment]
Do you have any log files like `%LOCALAPPDATA%\Docker\install-log*.txt`? Any error in one of them with a time stamp around the time when you had the issue?

**Comment by mat007** [comment]
This looks like the download failed, it probably didn’t install anything, you can try to download from https://www.docker.com/products/docker-desktop and install it by running the installer.

**Comment by rmorrise** [comment]
Thanks for your reply!

Here is the latest install log. I will try downloading a fresh installer and let you know what happens.

```
[12:31:13.301] [CheckForUpdateHandler] Install found: version=46911, displayVersion=2.3.0.4, basePath=C:\Program Files\Docker\Docker, channel=stable, channelUrl=https://desktop.docker.com/win/stable/appcast.xml
[12:31:13.872] [CheckForUpdateHandler] Appcast found: version=48029, displayVersion=2.3.0.5, installerUrl=https://desktop.docker.com/win/stable/48029/Docker%20Desktop%20Installer.exe
[12:31:32.994] [NewVersionFoundDialog] Executing: C:\Program Files\Docker\Docker\Docker Desktop Installer.exe install -package "https://desktop.docker.com/win/stable/48029/Docker%20Desktop%20Installer.exe" --confirm --append-logs --log-output-file="C:\Users\rmorrise\AppData\Local\Docker\install-log.txt"
[12:31:36.154] [InstallHandler] Existing installation found: version=46911, displayVersion=2.3.0.4, basePath=C:\Program Files\Docker\Docker, channel=stable, channelUrl=https://desktop.docker.com/win/stable/appcast.xml
[12:31:36.161] [ProcessEnvironmentDetector] Not run as admin, relaunching with UAC prompt
[12:31:39.874] [InstallHandler] Existing installation found: version=46911, displayVersion=2.3.0.4, basePath=C:\Program Files\Docker\Docker, channel=stable, channelUrl=https://desktop.docker.com/win/stable/appcast.xml
[12:31:39.876] [InstallHandler] using package https://desktop.docker.com/win/stable/48029/Docker%20Desktop%20Installer.exe
[12:31:40.001] [InstallWorkflow] Using package: https://desktop.docker.com/win/stable/48029/Docker%20Desktop%20Installer.exe
[12:31:40.004] [InstallWorkflow] Downloading
[12:31:42.198] [InstallWorkflow] Download failed.
Exception type: System.Net.Http.HttpRequestException, Exception message: Response status code does not indicate success: 403 (Forbidden)., StackTrace:
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at CommunityInstaller.DownloadStep.<DoAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__29.MoveNext()
[12:31:42.199] [InstallWorkflow] Installation failed
Exception type: System.Net.Http.HttpRequestException, Exception message: Response status code does not indicate success: 403 (Forbidden)., StackTrace:
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at CommunityInstaller.DownloadStep.<DoAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__29.MoveNext()
```

**Comment by mlag** [comment]
I had the same issue after updating to 2.3.0.5.
I had to reinstall version 2.3.0.4, reinstalling 2.3.0.5 did not fix the issue.

For uninstalling I had remove docker from the registry, as the uninstaller crashed. 

["The was a key in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall called “Docker Desktop.” I deleted it and all of its sub-keys and the Docker installation then went to completion."](https://stackoverflow.com/questions/42161471/how-to-uninstall-docker-machine-under-windows-10/51167323#comment107826621_51167323)

**Comment by rmorrise** [comment]
In my case, running the latest Docker Desktop installer seemed to get Docker Desktop working again. I didn't have to do anything to the registry.

When I click "Check for Update" nothing seems to happen, but it seems able to run diagnostics.

**Comment by rmorrise** [comment]
I'll leave this issue open so that the root cause of the download failure can be investigated. I was able to work around the problem for my purposes. Thank you for your help!
