### ISSUE TITLE
Failed to restart Docker Desktop error

### ISSUE THREAD

**Issue by aaroncompaniados26** [docker/for-win#8525]
- [x] I have tried with the latest version of my channel (Stable or Edge)
- [x] I have uploaded Diagnostics
- Diagnostics ID: BBCF3F57-872A-4736-9119-F6BD9547A95C/20200916232426

## Expected behavior

No errors found!

#### Failed to restart

System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\Aaron\AppData\Local\Docker\wsl\distro: exit code: -1
stdout: Insufficient system resources exist to complete the requested service.

stderr:
at Docker.Core.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\WslCommand.cs:line 119
at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d**17.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d**8.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d**25.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d**0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d**5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d**5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d**14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.Engines.Engines.<RestartAsync>d**29.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 275

### Information

- Windows Version: Windows 10 Home Single Language (version 2004)
- Docker Desktop Version: 2.3.0.5 (48029)
- Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: A virtualized Windows on a cloud server

### Steps to reproduce the behavior

1. ...
2. ...

**Comment by EtharAlali** [comment]
+1 on this sadly! 

Docker desktop worked fine last week. This week, I got round to enabling the 2004 update and there were three installations:

1. https://support.microsoft.com/en-gb/help/4571756/windows-10-update-kb4571756 (targeting 19041.508)
2. https://support.microsoft.com/en-gb/help/4576478/kb4576478-cumulative-update-for-net-framework
3. https://support.microsoft.com/en-gb/help/4484530/security-update-for-office-2010-september-8-2020

I don't have Office 2010. Does Docker desktop use RemoteFX in any way? Since they finally switched that off. 

"We no longer support the RemoteFX 3D video adapter. If you are still using this adapter, you may become vulnerable to security risk. Learn more (https://go.microsoft.com/fwlink/?linkid=2131976)”

**Comment by aaroncompaniados26** [comment]
> +1 on this sadly!
> 
> Docker desktop worked fine last week. This week, I got the latest docker desktop installation and also got round to enabling updated to Win 10 build 2004 and there were three installations:
> 
> 1. https://support.microsoft.com/en-gb/help/4571756/windows-10-update-kb4571756 (targeting 19041.508)
> 2. https://support.microsoft.com/en-gb/help/4576478/kb4576478-cumulative-update-for-net-framework
> 3. https://support.microsoft.com/en-gb/help/4484530/security-update-for-office-2010-september-8-2020
> 
> I don't have Office 2010.
> 
> Does Docker desktop use RemoteFX in any way? Since they finally switched that off in Hyper-V.
> 
> "We no longer support the RemoteFX 3D video adapter. If you are still using this adapter, you may become vulnerable to security risk. Learn more ([https://go.microsoft.com/fwlink/?linkid=2131976)”](https://go.microsoft.com/fwlink/?linkid=2131976)%E2%80%9D)
> 
> **EDIT:**
> 
> A simple reboot appears to have fixed this for me. Not at all sure why.

Thank you for your suggestion on how to fix these kinds of minor bugs and to make it more efficient. It is apparent that you have thought a lot about implementing such a system, and I would like to talk with you about it. It really helped me a lot, and Docker Desktop seems to be running quite smoothly.

Thanks again for your message. The ideas and suggestions of innovative, thinking people are always welcome. 😄 👍 💯
