### ISSUE TITLE
Docker failed to initialize

### ISSUE THREAD

**Issue by PabloLigeroJDS** [docker/for-win#8618]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 09308469-E60C-4778-A18E-152CAC0B625D/20200922075507

### Expected behavior
Run Dockers for desktop. I expected the aplication to open, but an Error window of Docke appears.

### Actual behavior
An Error window appear with information about the error. In the logs ( attached below ) it can be appreciated that is a problem related with the configuration.... but Im not sure.

### Information

  - Windows version: 10.0.17134 Build 17134
  - Docker Desktop Version: 2.3.0.5 (48029)
  - Running in windows.

### Log File:
Version: 2.3.0.5 (48029)
Channel: stable
Sha1: c2bacb43a7aec4c9d7ed0bdc73106464c0861e18
Started on: 2020/09/22 09:55:07.013
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1803
Build: 17134
BuildLabName: 17134.1.amd64fre.rs4_release.180410-1804
File: C:\Users\xxxxxxxx\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[09:55:07.097][GUI               ][Info   ] Starting...
[09:55:07.113][ComponentVersions ][Info   ] Edition community
[09:55:07.113][ComponentVersions ][Info   ] Edition community
[09:55:07.298][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[09:55:07.314][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[09:55:07.314][SegmentApi        ][Info   ] Usage statistic: Identify
[09:55:07.403][SegmentApi        ][Warning] Failed to Identify: Configuration system failed to initialize
[09:55:07.405][SegmentApi        ][Info   ] Usage statistic: appLaunched
[09:55:07.410][SegmentApi        ][Warning] Failed to track event appLaunched: Configuration system failed to initialize
[09:55:07.412][ApplicationTemplatesTracking][Info   ] Docker template not found, skipping analytics.
[09:55:07.412][SegmentApi        ][Info   ] Usage statistic: heartbeat
[09:55:07.412][SegmentApi        ][Warning] Failed to track event heartbeat: Configuration system failed to initialize
[09:55:07.412][GUI               ][Error  ] System.ArgumentException:
Unable to create an instance of Docker.App: Unable to create an instance of Docker.WPF.Nps.NPS: Unable to create an instance of Docker.WPF.Nps.WootricService: Exception has been thrown by the target of an invocation.
   at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
   at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
   at Docker.Core.Di.Singletons.Get[T]() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 28
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 320

  System.ArgumentException:
  Unable to create an instance of Docker.WPF.Nps.NPS: Unable to create an instance of Docker.WPF.Nps.WootricService: Exception has been thrown by the target of an invocation.
     at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
     at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
     at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
  
     System.ArgumentException:
     Unable to create an instance of Docker.WPF.Nps.WootricService: Exception has been thrown by the target of an invocation.
        at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 93
        at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
        at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
        at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
        at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
        at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
     
         System.Reflection.TargetInvocationException:
         Exception has been thrown by the target of an invocation.
            at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
            at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
            at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
         
              System.Configuration.ConfigurationErrorsException:
              Configuration system failed to initialize
                 at System.Configuration.ConfigurationManager.PrepareConfigSystem()
                 at System.Configuration.ConfigurationManager.GetSection(String sectionName)
                 at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
                 at System.Net.Configuration.SettingsSectionInternal.get_Section()
                 at System.Net.Http.HttpClientHandler..ctor()
                 at Docker.WPF.Nps.WootricService..ctor(IChannel channel, IVersion version) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.WPF\Nps\WootricService.cs:line 29
              
                    System.Configuration.ConfigurationErrorsException:
                    Unrecognized configuration section runtime. (C:\Program Files\Docker\Docker\Docker Desktop.exe.Config line 3)
                       at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
                       at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
                       at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
                    
[09:55:07.427][GUI               ][Info   ] Sending Bugsnag report bfef7bac-2967-4be5-833e-57b03d1828fe...
[09:55:07.514][GUI               ][Info   ] Bugsnag report bfef7bac-2967-4be5-833e-57b03d1828fe sent
[09:55:07.514][SegmentApi        ][Info   ] Usage statistic: eventCrash
[09:55:07.514][SegmentApi        ][Warning] Failed to track event eventCrash: Configuration system failed to initialize
[09:55:07.514][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[09:55:35.303][ErrorReportWindow ][Info   ] Open logs
[10:13:41.507][Diagnostics       ][Info   ] Uploading diagnostics 09308469-E60C-4778-A18E-152CAC0B625D/20200922075507
[10:13:42.780][Diagnostics       ][Info   ] Uploaded succesfully diagnostics 09308469-E60C-4778-A18E-152CAC0B625D/20200922075507
[10:24:56.719][ErrorReportWindow ][Info   ] Open logs

I tried to install several times docker but I was never able to lunch it. Is the first time I install and use Dockers for windows. 

### Steps to reproduce the behavior

Install Dockers Desktop and lunch the program.

**Comment by antonioborondo** [comment]
Same problem here 👎

**Comment by mat007** [comment]
This seems to be the root cause
```
                    System.Configuration.ConfigurationErrorsException:
                    Unrecognized configuration section runtime. (C:\Program Files\Docker\Docker\Docker Desktop.exe.Config line 3)
                       at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
                       at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
                       at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
```
This [https://stackoverflow.com/questions/197834/what-is-wrong-when-you-get-an-unrecognized-configuration-section-runtime-confi](Stackoverflow question) implies there might be something wrong with the .NET framework installed on the machine.

Can you for a `C:\windows\microsoft.net\framework\v4.0.30319\Config\machine.config` file and check that there is a `runtime` sub-element somewhere at the top of the `configSections` element?

**Comment by antonioborondo** [comment]
@mat007 The element is there:
```
<configuration>
    <configSections>
...
        <section name="runtime" .../>
...
```

**Comment by mat007** [comment]
Can you post the output of the following command (to check the .NET framework version)?
```
(Get-ItemProperty "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full").Release
```

**Comment by antonioborondo** [comment]
@mat007 0x00080eb1 (528049)

**Comment by mat007** [comment]
Does `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\machine.config` have the proper element as well (`Framework64` instead of `Framework`)?

Does it make a difference if you run Docker Desktop as administrator?

Can you try to copy the whole `configSections` part from the `configuration` element of `machine.config` at the top of the `configuration` element of `C:\Program Files\Docker\Docker\Docker Desktop.exe.config`, i.e.
```
<configuration>
  <configSections>
    …
  </configSections>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      …
```
to see if that helps, or at least makes it fail differently?

**Comment by PabloLigeroJDS** [comment]
Runing docker desktop as an administrator doesn't make any diference. The same error appears. 
Regarding the config file you coment ( machine.config) does not exist in the specified directory. Instead I have **machine.config.default** and "mmachine.config.comments".

**Comment by mat007** [comment]
Here is the full content of that folder on my machine:

![image](https://user-images.githubusercontent.com/2386884/94808230-18064d80-03f1-11eb-8ab2-baedd60b7af4.png)

Is `machine.config` the only missing one for you in there?

**Comment by PabloLigeroJDS** [comment]
Yes, machine.config is the only file that is missing

**Comment by mat007** [comment]
The two files are identical on my machine, can you copy `C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\machine.config` to `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config` to see if that helps?
