### ISSUE TITLE
Docker Desktop for Windows does not start after install

### ISSUE THREAD

**Issue by antonioborondo** [docker/for-win#8662]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3F88A3D6-0ED3-4173-9814-05EFD956F30D/20200925110444

### Expected behavior
Docker Desktop for Windows starts.

### Actual behavior
Docker Desktop for Windows crashes with the following exception:

```
System.ArgumentException:
Unable to create an instance of Docker.App: Unable to create an instance of Docker.WPF.Nps.NPS: Unable to create an instance of Docker.WPF.Nps.WootricService: Exception has been thrown by the target of an invocation.
   at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
   at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
   at Docker.Core.Di.Singletons.Get[T]() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 28
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 320

  System.ArgumentException:
  Unable to create an instance of Docker.WPF.Nps.NPS: Unable to create an instance of Docker.WPF.Nps.WootricService: Exception has been thrown by the target of an invocation.
     at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 89
     at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
     at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
     at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
     at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
     at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
  
     System.ArgumentException:
     Unable to create an instance of Docker.WPF.Nps.WootricService: Exception has been thrown by the target of an invocation.
        at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 93
        at Docker.Core.Di.Singletons.Get(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 51
        at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
        at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
        at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
        at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
     
         System.Reflection.TargetInvocationException:
         Exception has been thrown by the target of an invocation.
            at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
            at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
            at Docker.Core.Di.Singletons.NewInstance(Type type, Int32 depth) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\di\Singletons.cs:line 83
         
              System.Configuration.ConfigurationErrorsException:
              Configuration system failed to initialize
                 at System.Configuration.ConfigurationManager.PrepareConfigSystem()
                 at System.Configuration.ConfigurationManager.GetSection(String sectionName)
                 at System.Configuration.PrivilegedConfigurationManager.GetSection(String sectionName)
                 at System.Net.Configuration.SettingsSectionInternal.get_Section()
                 at System.Net.Http.HttpClientHandler..ctor()
                 at Docker.WPF.Nps.WootricService..ctor(IChannel channel, IVersion version) in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.WPF\Nps\WootricService.cs:line 29
              
                    System.Configuration.ConfigurationErrorsException:
                    Unrecognized configuration section runtime. (C:\Program Files\Docker\Docker\Docker Desktop.exe.Config line 3)
                       at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
                       at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
                       at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
```
                    
### Information

  - Windows Version: Windows 10 Enterprise 1809
  - Docker Desktop Version: 2.3.0.5 (48029)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

  1. Install Docker Desktop for Windows
  2. Start Docker Desktop for Windows

**Comment by antonioborondo** [comment]
Same issue as https://github.com/docker/for-win/issues/8618

**Comment by stephen-turner** [comment]
Thanks for the report. Weird that we haven't ever had this one before and then suddenly two reports in three days. I'll close this copy as a duplicate, but we'll take a look.

**Comment by antonioborondo** [comment]
@stephen-turner Thanks!
