### ISSUE TITLE
Windows (2004) - Docker Desktop (2.1.0) stops working randomly during use.

### ISSUE THREAD

**Issue by Malunke** [docker/for-win#8675]
Dear all,

I have the same problem, statet here (https://github.com/docker/for-win/issues/4383) - but this issue is locked.

It is the newest Windows 10 Pro as well as the newest Docker-Engine.

The behavior started round aboud 11.09.2020.

It is a VirtualMachine (VMWare ESXi) with only Windows 10 Pro and Docker installed (as well as one docker image (bitwarden) - no other software is installed.

Suddenly bitwarden stops working (it can be reactivated when restarting docker or restarting windows - but it will stuck between 5 minutes to 60 minutes after reboot/restart docker).

`PS C:\users\admin> .\bitwarden.ps1 -restart
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2020, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 19.03.12, build 48a66213fe
docker-compose version 1.27.2, build 18f557f9

Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 259, in _raise_for_status
  File "site-packages\requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\api\client.py", line 265, in _result
  File "site-packages\docker\api\client.py", line 261, in _raise_for_status
  File "site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'open \\\\.\\pipe\\docker_engine_linux: Das System kann die angegebene Datei nicht finden.'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error ("b'open \\\\.\\pipe\\docker_engine_linux: Das System kann die angegebene Datei nicht finden.'")
[9060] Failed to execute script docker-compose
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 259, in _raise_for_status
  File "site-packages\requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\api\client.py", line 265, in _result
  File "site-packages\docker\api\client.py", line 261, in _raise_for_status
  File "site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'open \\\\.\\pipe\\docker_engine_linux: Das System kann die angegebene Datei nicht finden.'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error ("b'open \\\\.\\pipe\\docker_engine_linux: Das System kann die angegebene Datei nicht finden.'")
[5512] Failed to execute script docker-compose
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 259, in _raise_for_status
  File "site-packages\requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\api\client.py", line 265, in _result
  File "site-packages\docker\api\client.py", line 261, in _raise_for_status
  File "site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'open \\\\.\\pipe\\docker_engine_linux: Das System kann die angegebene Datei nicht finden.'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error ("b'open \\\\.\\pipe\\docker_engine_linux: Das System kann die angegebene Datei nicht finden.'")
[2556] Failed to execute script docker-compose
Error response from daemon: open \\.\pipe\docker_engine_linux: Das System kann die angegebene Datei nicht finden.
docker: Error response from daemon: open \\.\pipe\docker_engine_linux: Das System kann die angegebene Datei nicht finden.
See 'docker run --help'.`

**Comment by Malunke** [comment]
After a lot of reading and testing it seems to be caused by VMWare Tools

I have installed MVWareTools 11.0.5

After disabling (VMwareToolboxCmd.exe config set appinfo disabled true) appinfo docker seems to work stable. (It doesn't hung up for 12 hours until now)

**Comment by franktank128** [comment]
I Had the same problem where Docker with Linux containers on Windows Server 2019 (1908) would freeze randomly after 10-15 minutes. VMWare Tools v. 11265 (11.0.1) seems to be the culprit. After uninstalling VMware Tools entirely from the VM the problem is gone. Docker is stable for 48+ hours now.
