### ISSUE TITLE
Docker stable version 2.3.0.5 not working in windows 10 after security update KB4571741

### ISSUE THREAD

**Issue by lashok** [docker/for-win#8709]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:0E553890-348A-4448-A059-992AD8C3A42F/20200929164125

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by lashok** [comment]
Version: 2.3.0.5 (48029)
Channel: stable
Sha1: c2bacb43a7aec4c9d7ed0bdc73106464c0861e18
Started on: 2020/09/29 22:04:35.244
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 1709
Build: 16299
BuildLabName: 16299.637.amd64fre.rs3_release_svc.180808-1748
File: C:\Users\296115\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe"
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[22:04:35.837][GUI ][Info ] Starting...
[22:04:37.009][ComponentVersions ][Info ] Edition community
[22:04:37.009][ComponentVersions ][Info ] Edition community
[22:04:45.478][AppMigrator ][Info ] Current version: 6. Latest version: 6
[22:04:45.541][TrackingSettings ][Info ] Crash report and usage statistics are enabled
[22:04:45.634][SegmentApi ][Info ] Usage statistic: Identify
[22:04:46.322][SegmentApi ][Info ] Usage statistic: appLaunched
[22:04:46.353][ApplicationTemplatesTracking][Info ] Docker template not found, skipping analytics.
[22:04:46.353][SegmentApi ][Info ] Usage statistic: heartbeat
[22:04:56.525][LoggingMessageHandler][Info ] [a49e5203] GET http://backend/version
[22:05:20.132][LoggingMessageHandler][Info ] [a49e5203] GET http://backend/version -> 200 OK (took 23600ms)
[22:05:28.402][LoggingMessageHandler][Info ] [cfed6399] GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[22:05:34.028][LoggingMessageHandler][Info ] [cfed6399] GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 5625ms)
[22:05:34.059][LoggingMessageHandler][Info ] [47ef2d4f] POST http://backend/migrate/app
[22:05:34.103][LoggingMessageHandler][Info ] [47ef2d4f] POST http://backend/migrate/app -> 204 NoContent (took 44ms)
[22:05:34.115][Engines ][Debug ] Starting
[22:05:35.698][LoggingMessageHandler][Info ] [4803a339] POST http://backend/versionpack/enable
[22:05:36.177][LoggingMessageHandler][Info ] [4803a339] POST http://backend/versionpack/enable -> 204 NoContent (took 479ms)
[22:05:40.963][LoggingMessageHandler][Info ] [3b4086b5] POST http://backend/cloudcli/toggle
[22:05:42.602][LoggingMessageHandler][Info ] [3b4086b5] POST http://backend/cloudcli/toggle -> 204 NoContent (took 1638ms)
[22:05:42.769][GoBackendProcess ][Info ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\.\pipe\dockerBackendApiServer
[22:06:06.320][GoBackendProcess ][Info ] Started
[22:06:06.798][MutagenProcess ][Info ] Starting C:\ProgramData\Docker\cli-plugins\docker-mutagen.exe mutagen daemon run
[22:06:33.705][MutagenProcess ][Info ] Started
[22:06:33.846][EngineStateMachine][Debug ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[22:06:33.847][EngineStateMachine][Debug ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[22:06:33.852][EngineStateListener][Debug ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxHyperV
[22:06:33.999][EngineStateNotificationRecorder][Debug ] Registered state {"State":"starting","Mode":"linux","date":1601397393}
[22:06:34.000][SystrayNotifications][Info ] Docker is starting
[22:06:36.853][LoggingMessageHandler][Info ] [9e30bb2c] POST http://backend/dns/refresh-hosts
[22:06:41.673][MutagenProcess ][Info ] [forwarding] Looking for existing sessions
[22:06:41.674][MutagenProcess ][Info ] [forwarding] Session manager initialized
[22:06:41.674][MutagenProcess ][Info ] [sync] Looking for existing sessions
[22:06:41.674][MutagenProcess ][Info ] [sync] Session manager initialized
[22:06:43.786][LoggingMessageHandler][Info ] [9e30bb2c] POST http://backend/dns/refresh-hosts -> 204 NoContent (took 6933ms)
[22:06:43.789][LinuxHyperVEngine ][Info ] Stopping watching for host power events
[22:06:43.792][LoggingMessageHandler][Info ] [51da6928] POST http://backend/hyperv/stop
[22:06:44.715][LoggingMessageHandler][Info ] [51da6928] POST http://backend/hyperv/stop -> 204 NoContent (took 921ms)
[22:06:44.933][VpnKitBridge ][Info ] Starting C:\Program Files\Docker\Docker\resources\vpnkit-bridge.exe --addr listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3 host
[22:06:52.018][LoggingMessageHandler][Info ] [bcfe577a] GET http://unix/versions
[22:06:52.195][LoggingMessageHandler][Info ] [bcfe577a] GET http://unix/versions -> 200 OK (took 176ms)
[22:06:53.185][GoBackendProcess ][Info ] ⇨ http server started on \.\pipe\dockerVpnKitControl
[22:06:53.187][GoBackendProcess ][Info ] started port-forwarding control server on \\.\pipe\dockerVpnKitControl
[22:06:53.188][GoBackendProcess ][Info ] listening on unix:\\.\pipe\dockerVpnkitData for data connection
[22:06:53.192][GoBackendProcess ][Info ] ⇨ http server started on \.\pipe\dockerBackendApiServerForGuest
[22:06:53.192][GoBackendProcess ][Info ] ⇨ http server started on \.\pipe\docker_cli
[22:06:53.192][GoBackendProcess ][Info ] enabling filesystem caching
[22:06:53.192][GoBackendProcess ][Info ] filesystem exports are: (2)
[22:06:53.194][GoBackendProcess ][Info ] volume control server listening on \\.\pipe\dockerVolume
[22:06:53.195][GoBackendProcess ][Info ] ⇨ http server started on \.\pipe\dockerBackendApiServer
[22:06:53.605][GoBackendProcess ][Info ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[22:06:53.605][GoBackendProcess ][Info ] file ownership will be determined by the calling user ("fake owner" mode)
[22:06:53.605][GoBackendProcess ][Info ] using mfsymlinks
[22:06:55.481][VpnKitBridge ][Info ] Started
[22:06:56.189][VpnKitBridge ][Info ] listening on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[22:06:56.190][VpnKitBridge ][Info ] waiting for connection on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[22:06:57.112][IsoConfig ][Info ] Generating CA Cert Bundle
[22:06:57.146][IsoConfig ][Info ] CA Cert Bundle Generated
[22:07:38.157][LoggingMessageHandler][Info ] [9a3f9326] POST http://backend/hyperv/create
[22:08:02.579][LoggingMessageHandler][Info ] [9a3f9326] POST http://backend/hyperv/create -> 204 NoContent (took 24422ms)
[22:08:02.647][VpnKit ][Info ] Starting C:\Program Files\Docker\Docker\resources\vpnkit.exe --ethernet \.\pipe\dockerVpnkit --hosts "" --http "C:\Users\296115\AppData\Roaming\Docker\http_proxy.json" --gateway-forwards "C:\Users\296115\AppData\Roaming\Docker\gateway_forwards.json" --diagnostics \.\pipe\dockerVpnKitDiagnostics --host-names host.docker.internal,docker.for.win.host.internal,docker.for.win.localhost --gateway-names gateway.docker.internal,docker.for.win.gateway.internal,docker.for.win.http.internal --listen-backlog 32 --gateway-ip 192.168.65.1 --host-ip 192.168.65.2 --lowest-ip 192.168.65.3 --highest-ip 192.168.65.14
[22:08:17.000][VpnKit ][Info ] Started
[22:08:17.009][DockerCliAPIServer][Info ] Starting C:\Program Files\Docker\Docker\resources\docker.exe serve --address npipe:////./pipe/dockerCliApi
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: Setting handler to ignore all SIGPIPE signals
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: Version is 218f01482560cba2fa863f9ad872ad51d1e717fc
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: System SOMAXCONN is 2147483647
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: Will use a listen backlog of 32
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: No periodic Gc.compact enabled
[22:08:19.065][VpnKit ][Error ] vpnkit.exe: Starting to watch : EINVAL
[22:08:19.065][VpnKit ][Error ] vpnkit.exe: Failed to watch hosts file : invalid argument
[22:08:19.065][VpnKit ][Warning] vpnkit.exe: There is no database: using hardcoded network configuration values
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: DNS server configured with no builtin DNS names; everything will be forwarded
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: 2 upstream DNS servers are configured
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: Disabling transparent HTTP redirection
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: Updating resolvers to use host resolver
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: Secure random number generator is available
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: Add(3): DNS configuration changed to: use host resolver
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: DNS server configured with builtin DNS names [ gateway.docker.internal -> 192.168.65.1, docker.for.win.gateway.internal -> 192.168.65.1, docker.for.win.http.internal -> 192.168.65.1, host.docker.internal -> 192.168.65.2, docker.for.win.host.internal -> 192.168.65.2, docker.for.win.localhost -> 192.168.65.2, vm.internal -> 192.168.65.3 ]
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: Will use the host's DNS resolver
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: Transparent HTTP redirection configuration file C:\Users\296115\AppData\Roaming\Docker\http_proxy.json has changed
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: Reading transparent HTTP redirection from C:\Users\296115\AppData\Roaming\Docker\http_proxy.json
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: Watching transparent HTTP redirection configuration file C:\Users\296115\AppData\Roaming\Docker\http_proxy.json for changes
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: New Gateway forward configuration: []
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: Gateway forwards file C:\Users\296115\AppData\Roaming\Docker\gateway_forwards.json has changed
[22:08:19.065][VpnKit ][Info ] vpnkit.exe: Reading gateway forwards file from C:\Users\296115\AppData\Roaming\Docker\gateway_forwards.json
[22:08:19.066][VpnKit ][Info ] vpnkit.exe: Watching gateway forwards file C:\Users\296115\AppData\Roaming\Docker\gateway_forwards.json for changes
[22:08:19.066][VpnKit ][Info ] vpnkit.exe: Configuration server_macaddr = f6:16:36:bc:f9:c6; max_connection = None; dns_path = None; dns = ; resolver = Host; domain = None; allowed_bind_addresses = 0.0.0.0; gateway_ip = 192.168.65.1; host_ip = 192.168.65.2; lowest_ip = 192.168.65.3; highest_ip = 192.168.65.14; dhcp_json_path = None; dhcp_configuration = None; mtu = 1500; http_intercept = None; http_intercept_path = C:\Users\296115\AppData\Roaming\Docker\http_proxy.json; port_max_idle_time = 300; host_names = host.docker.internal, docker.for.win.host.internal, docker.for.win.localhost; gateway_names = gateway.docker.internal, docker.for.win.gateway.internal, docker.for.win.http.internal; vm_names = vm.internal; udpv4_forwards = []; tcpv4_forwards = []; gateway_forwards_path = C:\Users\296115\AppData\Roaming\Docker\gateway_forwards.json; pcap_snaplen = 128
[22:08:19.066][VpnKit ][Error ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
[22:08:19.066][VpnKit ][Info ] vpnkit.exe: Updating transparent HTTP redirection: {
[22:08:19.066][VpnKit ][Info ] "exclude": "",
[22:08:19.066][VpnKit ][Info ] "transparent_http_ports": [
[22:08:19.066][VpnKit ][Info ] 80
[22:08:19.066][VpnKit ][Info ] ],
[22:08:19.066][VpnKit ][Info ] "transparent_https_ports": [
[22:08:19.066][VpnKit ][Info ] 443
[22:08:19.066][VpnKit ][Info ] ]
[22:08:19.066][VpnKit ][Info ] }
[22:08:19.066][VpnKit ][Info ] vpnkit.exe: New Gateway forward configuration: [{"protocol":"udp","external_port":53,"internal_ip":"127.0.0.1","internal_port":65092},{"protocol":"tcp","external_port":53,"internal_ip":"127.0.0.1","internal_port":50083}]
[22:08:23.759][DockerCliAPIServer][Info ] Started
[22:08:23.768][LoggingMessageHandler][Info ] [67d0eaf5] POST http://backend/hyperv/start
[22:08:40.773][LoggingMessageHandler][Info ] [9f8a8241] POST http://unix/usage/cli
[22:08:40.788][DockerCliAPIServer][Info ] serving daemon API" address="npipe:////./pipe/dockerCliApi
[22:08:40.914][LoggingMessageHandler][Info ] [9f8a8241] POST http://unix/usage/cli -> 200 OK (took 140ms)
[22:08:40.915][GoBackendProcess ][Info ] cli: POST /usage 200 "Go-http-client/1.1" "
[22:10:03.369][LoggingMessageHandler][Info ] [67d0eaf5] POST http://backend/hyperv/start -> 500 InternalServerError (took 99601ms)
[22:10:03.377][LinuxHyperVEngine ][Info ] Stopping watching for host power events
[22:10:03.377][LoggingMessageHandler][Info ] [4de195f1] POST http://backend/hyperv/stop
[22:10:06.684][LoggingMessageHandler][Info ] [4de195f1] POST http://backend/hyperv/stop -> 204 NoContent (took 3306ms)
[22:10:06.691][DockerCliAPIServer][Info ] Killing existing docker with PID 15416
[22:10:07.539][VpnKit ][Info ] Killing existing vpnkit with PID 15844
[22:10:07.549][VpnKitBridge ][Info ] Killing existing vpnkit-bridge with PID 11228
[22:10:07.567][LoggingMessageHandler][Info ] [2c1a1419] POST http://backend/windowsfeatures/check
[22:10:33.122][LoggingMessageHandler][Info ] [2c1a1419] POST http://backend/windowsfeatures/check -> 200 OK (took 25554ms)
[22:10:33.130][LoggingMessageHandler][Info ] [1e95c29c] GET http://backend/hyperv/check-virtualization
[22:10:34.144][LoggingMessageHandler][Info ] [1e95c29c] GET http://backend/hyperv/check-virtualization -> 204 NoContent (took 1014ms)
[22:10:34.147][LoggingMessageHandler][Info ] [7358456e] POST http://backend/dns/refresh-hosts
[22:10:34.210][LoggingMessageHandler][Info ] [7358456e] POST http://backend/dns/refresh-hosts -> 204 NoContent (took 63ms)
[22:10:34.210][LinuxHyperVEngine ][Info ] Stopping watching for host power events
[22:10:34.210][LoggingMessageHandler][Info ] [a9bf7803] POST http://backend/hyperv/stop
[22:10:36.138][LoggingMessageHandler][Info ] [a9bf7803] POST http://backend/hyperv/stop -> 204 NoContent (took 1927ms)
[22:10:36.155][VpnKitBridge ][Info ] Starting C:\Program Files\Docker\Docker\resources\vpnkit-bridge.exe --addr listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3 host
[22:10:36.256][VpnKitBridge ][Info ] Started
[22:10:37.241][VpnKitBridge ][Info ] listening on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[22:10:37.241][VpnKitBridge ][Info ] waiting for connection on listen://00000000-0000-0000-0000-000000000000/000007CF-FACB-11E6-BD58-64006A7986D3...
[22:10:38.242][IsoConfig ][Info ] Generating CA Cert Bundle
[22:10:38.560][IsoConfig ][Info ] CA Cert Bundle Generated
[22:10:55.813][LoggingMessageHandler][Info ] [6cac6e1b] POST http://backend/hyperv/create
[22:10:58.469][LoggingMessageHandler][Info ] [6cac6e1b] POST http://backend/hyperv/create -> 204 NoContent (took 2655ms)
[22:10:58.476][VpnKit ][Info ] Starting C:\Program Files\Docker\Docker\resources\vpnkit.exe --ethernet \.\pipe\dockerVpnkit --hosts "" --http "C:\Users\296115\AppData\Roaming\Docker\http_proxy.json" --gateway-forwards "C:\Users\296115\AppData\Roaming\Docker\gateway_forwards.json" --diagnostics \.\pipe\dockerVpnKitDiagnostics --host-names host.docker.internal,docker.for.win.host.internal,docker.for.win.localhost --gateway-names gateway.docker.internal,docker.for.win.gateway.internal,docker.for.win.http.internal --listen-backlog 32 --gateway-ip 192.168.65.1 --host-ip 192.168.65.2 --lowest-ip 192.168.65.3 --highest-ip 192.168.65.14
[22:10:58.735][VpnKit ][Info ] Started
[22:10:58.738][DockerCliAPIServer][Info ] Starting C:\Program Files\Docker\Docker\resources\docker.exe serve --address npipe:////./pipe/dockerCliApi
[22:10:58.841][VpnKit ][Info ] vpnkit.exe: Setting handler to ignore all SIGPIPE signals
[22:10:58.841][VpnKit ][Info ] vpnkit.exe: Version is 218f01482560cba2fa863f9ad872ad51d1e717fc
[22:10:58.841][VpnKit ][Info ] vpnkit.exe: System SOMAXCONN is 2147483647
[22:10:58.841][VpnKit ][Info ] vpnkit.exe: Will use a listen backlog of 32
[22:10:58.841][VpnKit ][Info ] vpnkit.exe: No periodic Gc.compact enabled
[22:10:58.841][VpnKit ][Error ] vpnkit.exe: Starting to watch : EINVAL
[22:10:58.841][VpnKit ][Error ] vpnkit.exe: Failed to watch hosts file : invalid argument
[22:10:58.841][VpnKit ][Warning] vpnkit.exe: There is no database: using hardcoded network configuration values
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: DNS server configured with no builtin DNS names; everything will be forwarded
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: 2 upstream DNS servers are configured
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: Disabling transparent HTTP redirection
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: Updating resolvers to use host resolver
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: Secure random number generator is available
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: Add(3): DNS configuration changed to: use host resolver
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: DNS server configured with builtin DNS names [ gateway.docker.internal -> 192.168.65.1, docker.for.win.gateway.internal -> 192.168.65.1, docker.for.win.http.internal -> 192.168.65.1, host.docker.internal -> 192.168.65.2, docker.for.win.host.internal -> 192.168.65.2, docker.for.win.localhost -> 192.168.65.2, vm.internal -> 192.168.65.3 ]
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: Will use the host's DNS resolver
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: Transparent HTTP redirection configuration file C:\Users\296115\AppData\Roaming\Docker\http_proxy.json has changed
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: Reading transparent HTTP redirection from C:\Users\296115\AppData\Roaming\Docker\http_proxy.json
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: Watching transparent HTTP redirection configuration file C:\Users\296115\AppData\Roaming\Docker\http_proxy.json for changes
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: New Gateway forward configuration: []
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: Gateway forwards file C:\Users\296115\AppData\Roaming\Docker\gateway_forwards.json has changed
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: Reading gateway forwards file from C:\Users\296115\AppData\Roaming\Docker\gateway_forwards.json
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: Watching gateway forwards file C:\Users\296115\AppData\Roaming\Docker\gateway_forwards.json for changes
[22:10:58.842][VpnKit ][Info ] vpnkit.exe: Configuration server_macaddr = f6:16:36:bc:f9:c6; max_connection = None; dns_path = None; dns = ; resolver = Host; domain = None; allowed_bind_addresses = 0.0.0.0; gateway_ip = 192.168.65.1; host_ip = 192.168.65.2; lowest_ip = 192.168.65.3; highest_ip = 192.168.65.14; dhcp_json_path = None; dhcp_configuration = None; mtu = 1500; http_intercept = None; http_intercept_path = C:\Users\296115\AppData\Roaming\Docker\http_proxy.json; port_max_idle_time = 300; host_names = host.docker.internal, docker.for.win.host.internal, docker.for.win.localhost; gateway_names = gateway.docker.internal, docker.for.win.gateway.internal, docker.for.win.http.internal; vm_names = vm.internal; udpv4_forwards = []; tcpv4_forwards = []; gateway_forwards_path = C:\Users\296115\AppData\Roaming\Docker\gateway_forwards.json; pcap_snaplen = 128
[22:10:58.843][VpnKit ][Error ] vpnkit.exe: While watching /etc/resolv.conf: ENOENT
[22:10:58.844][VpnKit ][Info ] vpnkit.exe: Updating transparent HTTP redirection: {
[22:10:58.844][VpnKit ][Info ] "exclude": "",
[22:10:58.844][VpnKit ][Info ] "transparent_http_ports": [
[22:10:58.844][VpnKit ][Info ] 80
[22:10:58.844][VpnKit ][Info ] ],
[22:10:58.844][VpnKit ][Info ] "transparent_https_ports": [
[22:10:58.844][VpnKit ][Info ] 443
[22:10:58.844][VpnKit ][Info ] ]
[22:10:58.844][VpnKit ][Info ] }
[22:10:58.845][VpnKit ][Info ] vpnkit.exe: New Gateway forward configuration: [{"protocol":"udp","external_port":53,"internal_ip":"127.0.0.1","internal_port":65092},{"protocol":"tcp","external_port":53,"internal_ip":"127.0.0.1","internal_port":50083}]
[22:10:59.170][DockerCliAPIServer][Info ] Started
[22:10:59.170][LoggingMessageHandler][Info ] [3f3c27fb] POST http://backend/hyperv/start
[22:11:00.741][DockerCliAPIServer][Info ] serving daemon API" address="npipe:////./pipe/dockerCliApi
[22:11:01.475][LoggingMessageHandler][Info ] [b31f6d22] POST http://unix/usage/cli
[22:11:01.476][LoggingMessageHandler][Info ] [b31f6d22] POST http://unix/usage/cli -> 200 OK (took 0ms)
[22:11:01.478][GoBackendProcess ][Info ] cli: POST /usage 200 "Go-http-client/1.1" "
[22:11:17.200][LoggingMessageHandler][Info ] [3f3c27fb] POST http://backend/hyperv/start -> 500 InternalServerError (took 18030ms)
[22:11:17.201][LinuxHyperVEngine ][Info ] Stopping watching for host power events
[22:11:17.201][LoggingMessageHandler][Info ] [4e85c6ef] POST http://backend/hyperv/stop
[22:11:18.962][LoggingMessageHandler][Info ] [4e85c6ef] POST http://backend/hyperv/stop -> 204 NoContent (took 1760ms)
[22:11:18.969][DockerCliAPIServer][Info ] Killing existing docker with PID 888
[22:11:18.980][VpnKit ][Info ] Killing existing vpnkit with PID 16168
[22:11:18.993][VpnKitBridge ][Info ] Killing existing vpnkit-bridge with PID 12280
[22:11:19.002][EngineStateMachine][Debug ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[22:11:19.002][EngineStateMachine][Debug ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[22:11:19.002][EngineStateListener][Debug ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxHyperV
[22:11:19.005][EngineStateNotificationRecorder][Debug ] Registered state {"State":"failed to start","Mode":"linux","date":1601397679}
[22:11:19.006][SystrayNotifications][Error ] Unhandled exception: job failed with message: 'DockerDesktopVM' failed to start. (Virtual machine ID CC92E7E0-93EA-4E7D-BDC1-FABFFBB9038B)
[22:11:19.738][GUI ][Info ] Sending Bugsnag report a8213344-35ee-40c9-a797-902ffd8a9524...
[22:11:21.273][GUI ][Info ] Bugsnag report a8213344-35ee-40c9-a797-902ffd8a9524 sent
[22:11:21.274][SegmentApi ][Info ] Usage statistic: eventCrash
[22:11:21.280][Diagnostics ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[22:11:22.426][Engines ][Error ] Start failed with Unhandled exception: job failed with message: 'DockerDesktopVM' failed to start. (Virtual machine ID CC92E7E0-93EA-4E7D-BDC1-FABFFBB9038B)
at Docker.Core.Logging.ClientExceptionInterceptor.d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\ClientExceptionInterceptor.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.Core.Logging.LoggingMessageHandler.d__4.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Net.Http.HttpClient.d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.Core.HttpClientExtensions.d__1`1.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 22
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.Core.BackendAPI.BackendAPIClient.d__11.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Core\BackendAPI\BackendAPIClient.cs:line 102
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.Engines.LinuxHyperVEngine.d__13.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.ApiServices.StateMachines.TaskExtensions.d__0.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.ApiServices.StateMachines.StartTransition.d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at Docker.ApiServices.StateMachines.StartTransition.d__5.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.ApiServices.StateMachines.EngineStateMachine.d__14.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Docker.Engines.Engines.d__24.MoveNext() in C:\workspaces\stable-2.3.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 110)
[22:11:25.161][GoBackendProcess ][Info ] external: GET /events 200 "Go-http-client/1.1" "
[22:11:25.163][GoBackendProcess ][Info ] external: GET /forwards/list 200 "Go-http-client/1.1" "
[22:11:25.167][GoBackendProcess ][Info ] mutagen sync list --output json
[22:11:25.751][GoBackendProcess ][Info ] mutagen C:\ProgramData\Docker\cli-plugins\docker-mutagen.exe mutagen sync list --output json: null\n
[22:11:25.751][GoBackendProcess ][Info ] external: GET /sync 200 "Go-http-client/1.1" "
[22:11:57.325][ErrorReportWindow ][Info ] Open logs
