### ISSUE TITLE
Unable to start or run Docker

### ISSUE THREAD

**Issue by rjmholt** [docker/for-win#8722]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 5C7D1889-64F8-4F26-8A73-439F1B6AD557/20200930144816

### Expected behavior

```
> docker ps
<probably no output, since I would have no docker processes running>
```

### Actual behavior

```
> docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

### Information

  - Windows Version: 10.0.20226
  - Docker Desktop Version: 2.4.0.0 (this wasn't very easy to find -- no CLI, no about menu, had to inspect the exe metadata)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: no, desktop machine

### Steps to reproduce the behavior

  1. Try to start docker by running Docker Desktop
  2. Get error occurred popup:

```
     System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\roholt\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: The parameter is incorrect.


 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 142
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

Happy to provide any extra info required!

**Comment by simonferquel** [comment]
I am on dev channel but only get build 20221. Where 20226 comes from ?

**Comment by simonferquel** [comment]
I see that you are from Microsoft. You may have access to non-public builds. Maybe warning someone in the WSL team (@benhillis maybe?) would make sense.

**Comment by rjmholt** [comment]
FWIW I've had this error for a little while now and only updated the machine recently. Totally willing to accept that it might be due to being on an insider build though.

**Comment by simonferquel** [comment]
If you have a distro working in wsl 2 mode, can you try to do the following:
`wsl --export <distro-name> backup.tar`
`mkdir ~\backup-distro`
`wsl --import backup ~\backup-distro backup.tar --version 2` ?
(this is basically what docker desktop does)

**Comment by DaleyKD** [comment]
I don't mean to derail, but I, too, cannot get Docker for Windows 2.4.0.0 to start. It is stuck in "Starting..."

**Comment by rjmholt** [comment]
> I don't mean to derail, but I, too, cannot get Docker for Windows 2.4.0.0 to start. It is stuck in "Starting..."

I suspect you're facing a different problem and may need to open a new issue. I had this issue in 2.3.x as well

**Comment by rjmholt** [comment]
> If you have a distro working in wsl 2 mode, can you try to do the following:

I've solved my initial problem on another machine and currently can't rdp into the original repro instance, but will follow up later

**Comment by major-mayer** [comment]
I am also affected of this issue. IIRC Docker-Desktop asked me to upgrade to 2.4.0.0  a few days ago.
When I try to access the docker container inside the WSL 2 shell i.e. `docker ps` it just outputs:
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

Sounds not good to me, especially since in the Docker Desktop window it says Docker "running".
I've uploaded the diagnostics with the id "4526D823-371B-4649-862A-9F77FF90B27E/20201001125016"

**Comment by simonferquel** [comment]
Your logs indicate that at some point you had wsl2 integration working with 2.4.0.0 (it shows docker api calls from the CLI running in ubuntu, including creating containers with mounts).
By any chance, did you change your default WSL distro ? (I see that "enableIntegrationWithDefaultWslDistro" is true, and no explicit distro integration).
You can check that with `wsl -l -v`

**Comment by major-mayer** [comment]
No i didnt' change my default WSL distro. At least not that i've known. I always use the Ubuntu image from the Microsoft store.
But it could indeed be that the WSL2 integration was working at some point, i think the update was a few days ago and Docker stopped working just today, so maybe i was able to start a container yesterday or something like that.

For me resetting all docker containers/ images to factory defaults and reinstalling Docker for Windows did the trick.
I don't know if this was really necessary and resetting all containers is really a pain, but at least it helped.

**Comment by simonferquel** [comment]
Hmm can't really debug the issue without having the machine in the broken state.
Something that can happen though, is mount tracking data to be stale, but it did not show up in the logs.

**Comment by rjmholt** [comment]
@simonferquel your suspicion is correct that wsl is rejecting the particular wsl call:

```
> wsl --export Ubuntu backup.tar

> mkdir backup-distro

> wsl --import backup backup-distro backup.tar --version 2
The parameter is incorrect.
```

Looking up the possible errors, I haven't found anything that looks really like my situation

**Comment by simonferquel** [comment]
You should probably submit the issue on https://github.com/microsoft/WSL. (and if you can include me in the discussion as I am genuinely interested of where it may come from and what possible workaround there might be)
