### ISSUE TITLE
Docker windows not starting after update to 2.4.0

### ISSUE THREAD

**Issue by enricotimisela** [docker/for-win#8739]
I have tried with the latest version of my channel (Stable or Edge)
 I have uploaded Diagnostics
Diagnostics ID: E0F4AE85-AABC-4F82-AF2C-39ED7A69E6B6/20201001074613
Expected behavior
Docker should be running

Actual behavior
Docker not starting
`System.NullReferenceException:
Object reference not set to an instance of an object.
   at Docker.Engines.IsoConfig.Meta(Object value) in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\IsoConfig.cs:line 146
   at Docker.Engines.IsoConfig.GenerateConfig(Settings settings) in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\IsoConfig.cs:line 82
   at Docker.Engines.IsoConfig.Write(Settings settings) in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\IsoConfig.cs:line 40
   at Docker.Engines.LinuxHyperVEngine.<DoStartAsync>d__14.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\LinuxHyperVEngine.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
`

Information
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18363 N/A Build 18363
Docker Desktop Version: 2.4.0
Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: NO
Steps to reproduce the behavior
Update Docker windows to version 2.4.0

**Comment by jimmymain** [comment]
anyone know of a workaround for this.

**Comment by ericminio** [comment]
https://github.com/docker/for-win/issues/464#issuecomment-475886822

**Comment by adrianmenegatti** [comment]
Same issue here. Any fix or workaround?
