### ISSUE TITLE
Can't upgrade to 2.4.0.0

### ISSUE THREAD

**Issue by kmadsen** [docker/for-win#8783]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID:  29D62A05-1560-466F-94FF-95800DCF13D2/20201001223141

### Expected behavior
Successful upgrade
### Actual behavior
Can't upgrade
### Information

**Windows Version**
Microsoft Windows 10 Pro
10.0.19041 Build 19041
 
**Docker Desktop Version**
Failed to install from 2.3.0.5 (48029) to 2.4.0.0 (48506)

**Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:**
No, running on a PC

### Steps to reproduce the behavior
 

1. Click "Install Update" in update windw
2. Watch progress of download for a few minutes
3. Notice Installation failed message with stack trace below

```
The decryption operation failed, see inner exception.
   at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.<ReadAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CommunityInstaller.DownloadStep.<DoAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__29.MoveNext()
```

**Comment by kmadsen** [comment]
Restarted computer and it worked. I'm also using Remote Desktop, restarting might have disconnected it.

Feel free to close if this is not actionable
