### ISSUE TITLE
docker.errors.DockerException: Credentials store error: StoreError('Unexpected OS error "Access is denied", errno=13')

### ISSUE THREAD

**Issue by KRDMTech** [docker/for-win#8787]
When I run docker-compose inside of Visual Studio 2019. I get this error.

Severity	Code	Description	Project	File	Line	Suppression State
Error	DT1001	docker.errors.DockerException: Credentials store error: StoreError('Unexpected OS error "Access is denied", errno=13')
If the error persists, try restarting Docker Desktop.	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	385	

  - [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by stephen-turner** [comment]
Does it work outside Visual Studio?

**Comment by KRDMTech** [comment]
I opened a command prompt, went into the project folder and ran docker-compose up. These are the results (same error)

Creating network "blah" with driver "bridge"
Building fakeproject
Traceback (most recent call last):
  File "site-packages\docker\credentials\store.py", line 80, in _execute
  File "subprocess.py", line 395, in check_output
  File "subprocess.py", line 472, in run
  File "subprocess.py", line 775, in __init__
  File "subprocess.py", line 1178, in _execute_child
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 126, in perform_command
  File "compose\cli\main.py", line 1070, in up
  File "compose\cli\main.py", line 1066, in up
  File "compose\project.py", line 615, in up
  File "compose\service.py", line 362, in ensure_image_exists
  File "compose\service.py", line 1125, in build
  File "site-packages\docker\api\build.py", line 261, in build
  File "site-packages\docker\api\build.py", line 308, in _set_auth_headers
  File "site-packages\docker\auth.py", line 302, in get_all_credentials
  File "site-packages\docker\credentials\store.py", line 71, in list
  File "site-packages\docker\credentials\store.py", line 104, in _execute
docker.credentials.errors.StoreError: Unexpected OS error "Access is denied", errno=13
[212420] Failed to execute script docker-compose

**Comment by stephen-turner** [comment]
Thanks. The stack trace shows that this is a docker compose error, so I'm going to move this ticket into the compose repository.
