### ISSUE TITLE
Docker Desktop failing to launch in Window 10  

### ISSUE THREAD

**Issue by mananaya** [docker/for-win#8794]
- [ x] I have tried with the latest version of my channel (Stable or Edge)
  - [ x] I have uploaded Diagnostics
  - Diagnostics ID: 3A63CCCD-56AF-46AE-AEB6-8FCBEE8CAB54/20201003095003

### Expected behavior
Docker should launch
### Actual behavior
Docker failed to launch
### Information

  - Windows Version: Windows 10 Enterprise, Id: 2004, Build: 19041
  - Docker Desktop Version: 2.4.0.0 (48506)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Error log below;
Version: 2.4.0.0 (48506)
Channel: stable
Sha1: b18c8c862baf6c395898f15dd01857d96ddca564
Started on: 2020/10/03 15:19:47.533
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Enterprise
Edition: Enterprise
Id: 2004
Build: 19041
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\MANASNAYAK\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[15:19:47.637][GUI               ][Info   ] Starting...
[15:19:47.661][ComponentVersions ][Info   ] Edition community
[15:19:47.668][ComponentVersions ][Info   ] Edition community
[15:19:48.285][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[15:19:48.346][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[15:19:48.353][SegmentApi        ][Info   ] Usage statistic: Identify
[15:19:48.667][SegmentApi        ][Info   ] Usage statistic: appLaunched
[15:19:48.676][SegmentApi        ][Info   ] Usage statistic: heartbeat
[15:19:48.842][LoggingMessageHandler][Info   ] [d06edc75] <BackendAPIClient start> GET http://backend/version
[15:19:50.418][LoggingMessageHandler][Info   ] [d06edc75] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 1572ms)
[15:19:52.410][LoggingMessageHandler][Info   ] [4483b265] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[15:19:52.579][LoggingMessageHandler][Info   ] [4483b265] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 169ms)
[15:19:52.598][LoggingMessageHandler][Info   ] [1ae29f79] <BackendAPIClient start> POST http://backend/migrate/app
[15:19:52.614][LoggingMessageHandler][Info   ] [1ae29f79] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 16ms)
[15:19:52.627][Engines           ][Debug  ] Starting
[15:19:52.656][LoggingMessageHandler][Info   ] [292d61b1] <BackendAPIClient start> POST http://backend/versionpack/enable
[15:19:52.829][LoggingMessageHandler][Info   ] [292d61b1] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 173ms)
[15:19:52.862][LoggingMessageHandler][Info   ] [7ecd4954] <BackendAPIClient start> POST http://backend/cloudcli/toggle
[15:19:52.874][LoggingMessageHandler][Info   ] [7ecd4954] <BackendAPIClient end> POST http://backend/cloudcli/toggle -> 204 NoContent (took 11ms)
[15:19:52.882][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[15:19:53.735][Updater           ][Info   ] Launcher process exited with 4294967295
[15:19:54.268][GoBackendProcess  ][Info   ] Started
[15:19:54.285][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[15:19:54.286][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[15:19:54.295][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxWSL2
[15:19:54.306][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1601718594}
[15:19:54.309][SystrayNotifications][Info   ] Docker is starting
[15:19:54.314][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[15:19:54.318][LoggingMessageHandler][Info   ] [764ea257] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[15:19:54.486][WSL2Provisioning  ][Info   ] Checking docker-desktop
[15:19:54.512][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\MANASNAYAK\AppData\Local\Docker\wsl\distro
[15:19:55.211][LoggingMessageHandler][Info   ] [764ea257] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 892ms)
[15:19:57.027][WSL2Provisioning  ][Error  ] Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

 stderr: 
[15:19:57.051][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[15:19:57.336][LinuxWSL2Engine   ][Info   ] Stopping engine
[15:19:57.688][LinuxWSL2Engine   ][Warning] Failed to send stop message to distro, will terminate abrubtly: 
[15:19:58.014][LoggingMessageHandler][Info   ] [ffa036bc] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[15:19:58.715][LoggingMessageHandler][Info   ] [190bd0e1] <Server start> GET http://unix/versions
[15:19:58.816][LoggingMessageHandler][Info   ] [190bd0e1] <Server end> GET http://unix/versions -> 200 OK (took 101ms)
[15:19:58.878][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[15:19:58.878][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\docker_cli
[15:19:58.878][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[15:19:58.879][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[15:19:58.879][GoBackendProcess  ][Info   ] started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl
[15:19:58.879][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[15:19:58.879][GoBackendProcess  ][Info   ] enabling filesystem caching
[15:19:58.879][GoBackendProcess  ][Info   ] filesystem exports are:  (2)
[15:19:58.879][GoBackendProcess  ][Info   ] volume control server listening on \\\\.\\pipe\\dockerVolume
[15:19:58.892][GoBackendProcess  ][Info   ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[15:19:58.892][GoBackendProcess  ][Info   ] file ownership will be determined by the calling user (\"fake owner\" mode)
[15:19:58.892][GoBackendProcess  ][Info   ] using mfsymlinks
[15:19:59.338][LoggingMessageHandler][Info   ] [ffa036bc] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 1322ms)
[15:20:00.377][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[15:20:00.377][LoggingMessageHandler][Info   ] [7fee27a3] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[15:20:00.536][WSL2Provisioning  ][Info   ] Checking docker-desktop
[15:20:00.537][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\MANASNAYAK\AppData\Local\Docker\wsl\distro
[15:20:00.553][LoggingMessageHandler][Info   ] [7fee27a3] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 176ms)
[15:20:01.506][WSL2Provisioning  ][Error  ] Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

 stderr: 
[15:20:01.507][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[15:20:01.676][LinuxWSL2Engine   ][Info   ] Stopping engine
[15:20:01.932][LinuxWSL2Engine   ][Warning] Failed to send stop message to distro, will terminate abrubtly: 
[15:20:02.175][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[15:20:02.175][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[15:20:02.175][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxWSL2
[15:20:02.177][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1601718602}
[15:20:02.278][SystrayNotifications][Error  ] System.InvalidOperationException: Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 142
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
[15:20:02.324][GUI               ][Info   ] Sending Bugsnag report 99975372-4258-43ad-8bbc-af71f5e5acb9...
[15:20:02.488][GUI               ][Info   ] Bugsnag report 99975372-4258-43ad-8bbc-af71f5e5acb9 sent
[15:20:02.489][SegmentApi        ][Info   ] Usage statistic: eventCrash
[15:20:02.492][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[15:20:02.761][Engines           ][Error  ] Start failed with Failed to set version to docker-desktop: exit code: -1
 stdout: The attempted operation is not supported for the type of object referenced.

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 142
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__23.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 108)
[15:20:03.734][GoBackendProcess  ][Info   ] external: GET /events 200 \"Go-http-client/1.1\" \"\
[15:20:03.735][GoBackendProcess  ][Info   ] external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\
[15:22:04.737][ErrorReportWindow ][Info   ] Open diagnostics
[15:22:10.191][Diagnostics       ][Info   ] Uploading diagnostics 3A63CCCD-56AF-46AE-AEB6-8FCBEE8CAB54/20201003095003
[15:22:17.127][Diagnostics       ][Info   ] Uploaded succesfully diagnostics 3A63CCCD-56AF-46AE-AEB6-8FCBEE8CAB54/20201003095003
[15:28:56.774][ErrorReportWindow ][Info   ] Open logs

**Comment by vctls** [comment]
Not sure if I should make my own issue about this, since there are already so many.
Same Windows version 19041, tried 2.4.0, and 2.4.1, stable and edge channels but Docker just won't start.
I am _not_ using WSL2 back-end and don't want to, although I see the latest installer tries to enable that by default.
On my last try, the dashboard and taskbar icon were not in sync:
![image](https://user-images.githubusercontent.com/18054077/95012259-83d9f780-0637-11eb-97db-0e2810646c32.png)
But Docker was indeed stopped.
