### ISSUE TITLE
One more bug

### ISSUE THREAD

**Issue by hakuno** [docker/for-win#8837]
Hey!

Everytime I update the Docker For Windows I get some bad surprise.

The beta channel is buggy. And I guess some bug came to the stable channel recently.

The last message error after I updated:

```
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 259, in _raise_for_status
  File "site-packages\requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\api\client.py", line 265, in _result
  File "site-packages\docker\api\client.py", line 261, in _raise_for_status
  File "site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'i/o timeout'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: 500 Server Error: Internal Server Error ("b'i/o timeout'")
[32872] Failed to execute script docker-compose
```

The version is `2.4.0.0` from `2020-09-28`. Channel: stable.

BTW can I downgrade? 😢

**Comment by hakuno** [comment]
`8BFC29AA-1721-4D50-9945-D7B0966BDAA1/20201005160416`

**Comment by stephen-turner** [comment]
Thanks for the report. This seems to be a compose bug, so I'm moving the ticket to the compose repository.
