### ISSUE TITLE
Docker not working in windiws 10 

### ISSUE THREAD

**Issue by apurv-18** [docker/for-win#8925]
Version: 2.4.1.0 (48583)
Channel: edge
Sha1: 460b75aa6ad60eeb476c9cfb70f4794a81daa741
Started on: 2020/10/09 13:03:28.364
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Home Single Language
Edition: CoreSingleLanguage
Id: 1909
Build: 18363
BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
File: C:\Users\Apurv Prasad\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[13:03:28.520][GUI               ][Info   ] Starting...
[13:03:28.553][ComponentVersions ][Info   ] Edition community
[13:03:28.559][ComponentVersions ][Info   ] Edition community
[13:03:28.864][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[13:03:28.893][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[13:03:28.897][SegmentApi        ][Info   ] Usage statistic: Identify
[13:03:29.052][SegmentApi        ][Info   ] Usage statistic: appLaunched
[13:03:29.063][SegmentApi        ][Info   ] Usage statistic: heartbeat
[13:03:29.176][LoggingMessageHandler][Info   ] [6efd46ba] <BackendAPIClient start> GET http://backend/version
[13:03:29.217][GUI               ][Error  ] System.NullReferenceException:
Object reference not set to an instance of an object.
   at Docker.Core.Cli.CliOptionsLoader.Get() in C:\workspaces\edge-2.4.1.x\src\github.com\docker\pinata\win\src\Docker.Core\cli\CliOptionsLoader.cs:line 33
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\edge-2.4.1.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 340
[13:03:29.237][GUI               ][Info   ] Sending Bugsnag report bdd69328-6342-4d14-932c-411770c14e4b...
[13:03:29.367][LoggingMessageHandler][Info   ] [6efd46ba] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 189ms)
[13:03:29.450][GUI               ][Info   ] Bugsnag report bdd69328-6342-4d14-932c-411770c14e4b sent
[13:03:29.451][SegmentApi        ][Info   ] Usage statistic: eventCrash
[13:03:29.455][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[13:03:29.644][LoggingMessageHandler][Info   ] [e1ec3dc8] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[13:03:29.666][LoggingMessageHandler][Info   ] [e1ec3dc8] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 21ms)
[13:03:29.708][LoggingMessageHandler][Info   ] [e848e184] <BackendAPIClient start> POST http://backend/migrate/app
[13:03:29.717][LoggingMessageHandler][Info   ] [e848e184] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 8ms)
[13:03:29.732][Engines           ][Debug  ] Starting
[13:03:29.772][LoggingMessageHandler][Info   ] [efafd815] <BackendAPIClient start> POST http://backend/versionpack/enable
[13:03:29.878][LoggingMessageHandler][Info   ] [efafd815] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 105ms)
[13:03:30.052][LoggingMessageHandler][Info   ] [9b49624e] <BackendAPIClient start> POST http://backend/cloudcli/toggle
[13:03:30.068][LoggingMessageHandler][Info   ] [9b49624e] <BackendAPIClient end> POST http://backend/cloudcli/toggle -> 204 NoContent (took 16ms)
[13:03:30.088][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[13:03:30.105][GoBackendProcess  ][Info   ] Started
[13:03:30.123][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[13:03:30.124][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[13:03:30.133][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxWSL2
[13:03:30.142][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1602228810}
[13:03:30.143][SystrayNotifications][Info   ] Docker is starting
[13:03:31.446][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[13:03:31.450][LoggingMessageHandler][Info   ] [0197f753] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[13:03:32.246][LoggingMessageHandler][Info   ] [0197f753] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 796ms)
[13:03:32.671][Updater           ][Info   ] Launcher process exited with 4294967295
[13:03:33.051][LoggingMessageHandler][Info   ] [61fb6009] <Server start> GET http://unix/versions
[13:03:33.161][LoggingMessageHandler][Info   ] [61fb6009] <Server end> GET http://unix/versions -> 200 OK (took 109ms)
[13:03:34.589][Diagnostics       ][Info   ] Uploading diagnostics AD387B12-CDEB-44A4-95BF-802AB49C3404/20201009073329
[13:03:34.608][GoBackendProcess  ][Info   ] started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl
[13:03:34.608][GoBackendProcess  ][Info   ] enabling filesystem caching
[13:03:34.608][GoBackendProcess  ][Info   ] filesystem exports are:  (2)
[13:03:34.608][GoBackendProcess  ][Info   ] volume control server listening on \\\\.\\pipe\\dockerVolume
[13:03:34.608][GoBackendProcess  ][Info   ] listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection
[13:03:34.609][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[13:03:34.617][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[13:03:34.620][GoBackendProcess  ][Info   ] filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3
[13:03:34.620][GoBackendProcess  ][Info   ] file ownership will be determined by the calling user (\"fake owner\" mode)
[13:03:34.621][GoBackendProcess  ][Info   ] using mfsymlinks
[13:03:34.627][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[13:03:34.627][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\docker_cli
[13:03:38.603][Diagnostics       ][Info   ] Uploaded succesfully diagnostics AD387B12-CDEB-44A4-95BF-802AB49C3404/20201009073329
[13:04:07.758][ErrorReportWindow ][Info   ] Open logs

![docker issue](https://user-images.githubusercontent.com/65449097/95556014-3fcc6580-0a30-11eb-8d9d-dd944f420e8e.PNG)

**Comment by natnaov8** [comment]
$docker logout
