### ISSUE TITLE
Startup failure

### ISSUE THREAD

**Issue by LostKatana** [docker/for-win#893]
**### Expected behavior**
After starting the PC I want to see _Docker is running_ message.

**### Actual behavior**
Docker throws an error and is not started

**### Information**
  - CA370BA2-3323-4876-AC18-E426A0FBFEBB/2017-07-04_23-06-44
  - Windows 10 Pro Version 1703 Systembuild 15063.413
  - Docker Community Edition Version 17.06.0-ce-win18 (12627)

**### Steps to reproduce the behavior**

  1. I try to reproduce that the next days as it seems to appear when switching network from our corporate network to my local network at home.
  2. This is the stacktrace shown:
```
[22:46:09.843][NamedPipeServer][Error  ] Unable to execute Mount: The process cannot access the file 'C:\WINDOWS\TEMP\m2ibdlg0.nu5' because it is being used by another process.    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at Docker.Backend.MobyCommand.RunDocker(String arguments, IDictionary`2 envVariables, String stdin, Int32 timeoutMs, String cidFile)
   at Docker.Backend.MobyCommand.Run(String commandLine, IDictionary`2 envVariables, Boolean load, String stdin, Int32 timeoutMs)
   at Docker.Backend.SambaShare.MountInMoby(String mount, String drive, Credential cred, CredentialInfo credInfo, String options, String ip)
   at Docker.Backend.SambaShare.MountInMoby(String drive, Credential credential, Settings settings)
   at Docker.Backend.SambaShare.Mount(String drive, Credential credential, Settings settings)
   at Docker.Backend.BackendServer.<Run>b__5_11(Object[] args)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```
**###Temporary solution**
Restart Docker and it works,

**Comment by b-mille** [comment]
Same here !

**Comment by minkbear** [comment]
Same too.

**Comment by vvasilenok** [comment]
+1

**Comment by bericoberin** [comment]
This bug still comes back often.  Restarting is simply a work around.

I've reset Docker to it's default configuration, but after I apply necessary changes:

- Share my C: drive
- Expose deamon on port 2375 to make it compatible with docker build

I get the crash on startup after one or two days.  I've done this dance a half dozen times and it's a half dozen too many.  I have no confidence in this product on Windows, even if it's only being used as a dev tool.

**Comment by AndrewCritchley** [comment]
I'm having this exact same issue since updating to the latest version. As with @bericoberin I'm able to use it for a short while if i do a factory reset, but after a day or so docker just stops working.

This is just using Linux containers.

Windows 10 Pro, build 14393.1358.

**Comment by konrad-ha** [comment]
We have a bunch of developers affected by this, I sure hope a fix is coming along soon.

**Comment by friism** [comment]
@konrad-ha can you run diagnostics and post diagnostic-id here?

**Comment by bericoberin** [comment]
Is the "send diagnostic" dialog for show?  I've submitted quite a few

**Comment by ebriney** [comment]
It's must be fixed in the next release.
(see https://github.com/docker/for-win/issues/874)

**Comment by LostKatana** [comment]
Also see #818

**Comment by Dargmuesli** [comment]
The new version is available for download. Try it and tell us if this problem is fixed.

**Comment by bericoberin** [comment]
I've had it for a few days and so far so good.  I need to get some
instances loaded to really test it out.

**Comment by LostKatana** [comment]
I've also tested a few days now and didn't had this issue.
But now I have another popping up when I first start.
Will upload a new ticket for that.
