### ISSUE TITLE
Error Starting Docker in Windows 10 Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by csanthosh13** [docker/for-win#904]
### Expected behavior
Docker Should Start
### Actual behavior
Docker is not starting. Below is the error generated
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

Diagnostic-id: 686EA43D-3A49-493C-8D6A-3D86667DF3F9/2017-07-09_10-57-27
### Information
  - Diagnostic ID: 686EA43D-3A49-493C-8D6A-3D86667DF3F9/2017-07-09_10-57-27
  - Attached log for more information
[log.txt](https://github.com/docker/for-win/files/1133566/log.txt)

**Comment by csanthosh13** [comment]
Manually tried to start MobyLinuxVM in Hyper V Manager but it failed to start. Below is the attached log information when trying to start Docker

Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start.

'MobyLinuxVM' failed to initialize.

'MobyLinuxVM' failed to start. (Virtual machine ID 9725E735-F20F-4FE9-A43B-E537E64EFE23)

'MobyLinuxVM' failed to initialize. (Virtual machine ID 9725E735-F20F-4FE9-A43B-E537E64EFE23)
at Start-MobyLinuxVM, <No file>: line 291
at <ScriptBlock>, <No file>: line 386
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

[log.txt](https://github.com/docker/for-win/files/1133615/log.txt)

**Comment by csanthosh13** [comment]
I was able to start Docker by manually starting MobyLinuxVM. After that restarted Docker and it started working. Below is Diagnostic ID: 686EA43D-3A49-493C-8D6A-3D86667DF3F9/2017-07-09_14-15-46
Can you please check what caused the issues in previous comments

**Comment by jamesmbourne** [comment]
I wasn't able to see the MobyLinuxVM in Hyper-V manager, but by deleting `MobyLinuxVM.vhdx` (found in `C:\Users\Public\Documents\Hyper-V\Virtual hard disks` for me) and restarting the Docker service, it was able to start without the error.

**Comment by samarkumar1** [comment]
I tried deleting but it didn't work, any suggestions will be helpful..

**Comment by EdGreen21** [comment]
didn't work for me either

**Comment by nareshnagpal06** [comment]
I am also facing the same issue. When I start docker  it gives following error - 


**Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 297
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 265
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings, String daemonOptions) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Linux.cs:line 190
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 47
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145**


Things I have tried so far
1. Reinstalled Docker 
2. Ran docker as Admin
3. Tried with Edge version

but none of above steps helped. Was anyone able to find the solution for this issue?

**Comment by samarkumar1** [comment]
I think this issue is related with system cpu% or memory% current utilization, where docker is not able to get allocated memory. 

I closed the application which is taking more system resource and restart the docker it worked. 

Hope it help.

**Comment by nareshnagpal06** [comment]
Thanks but I can see CPU and memory utilisation is quite moderate. I just tried increasing the allocated RAM and CPU  to docker but still no luck. It takes some time and gave same error .

**Comment by nareshnagpal06** [comment]
I was able to finally run docker on windows 10 running with boot camp on mac. I am not sure why it did not work with Parallel Desktop . May be one for Parallels support.

**Comment by lilasquared** [comment]
@nareshnagpal06 I was having this issue on parallels as well.  I dug through some of the settings for my VM and on the Security tab I checked "Isolate Windows from Mac".  When I turned the VM on the next time docker started successfully in linux mode.

**Comment by csandanov** [comment]
@lilasquared I tried your suggestion but it didn't help, my setup:
* Parallels 13.2 Pro edition (macos high sierra)
* Docker for win 17.09.1-ce
* Windows 10 Pro (all updates installed)
* Nested virtualization enabled
* Win 10: virtualization and Hyper-V enabled

When switching to Windows containers, it works fine. Tried different workarounds (refs #971) like:
* Restarting Docker and Hyper-V services
* Switching to Win containers then back to Linux containers
* Running docker as administrator

None of those helped. Checked that moby VM created successfully via Hyper-V manager.

Did I miss something?

**Comment by arthurdn** [comment]
**Removing or changing** of priority for third party software with **high CPU consumption** fixed everything.

**Comment by ctmcisco** [comment]
For anyone following this ticket:

Try the following:

1. Switch or stay on Windows Containers.
2. Disable the "Start when Windows starts" setting.


![image](https://user-images.githubusercontent.com/14852041/37053107-e9a96bd8-2140-11e8-9bdf-b264980b6127.png)

3. Exit Docker application
4. restart docker services via PowerShell

get-service *docker* | Restart-Service -Force -Verbose

5. Launch Docker , Run as Admin
6. Swtich to Linux Containers.

TEST:

Reboot Windows 10
Launch Docker 
Does it work?

You can also parse the docker log in PowerShell for troubleshooting:

cat C:\Users\USERPROFILE\AppData\Local\Docker\log.txt -tail 10 -wait
