### ISSUE TITLE
Update to 2.4.0.0: docker login from WSL2 distro fails with .../docker-credential-desktop.exe: Invalid argument

### ISSUE THREAD

**Issue by Him90** [docker/for-win#9061]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: D277A93A-1E25-4716-AE7A-56BBB29CD950/20201015094317

### Expected behavior

Docker login, docker-compose work as before

### Actual behavior

Docker login, docker-compose fail from WSL2 distro

### Information

  - Windows Version: 19041
  - Docker Desktop Version:  2.4.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

(from powsershell)
  1. docker login -> works
  2. relogin works with existing credentials

(from wsl2 distro) 
   1. docker login -> fails 
     /c/Program Files/Docker/Docker/resources/bin/docker-credential-desktop.exe: Invalid argument
     Error saving credentials: error storing credentials - err: exit status 1, out: `

   2. docker-compose up (only hello-world as service) -> fails

/c/Program Files/Docker/Docker/resources/bin/docker-credential-desktop.exe: Invalid argument
Traceback (most recent call last):
  File "docker/credentials/store.py", line 80, in _execute
  File "subprocess.py", line 411, in check_output
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '['/c/Program Files/Docker/Docker/resources/bin/docker-credential-desktop.exe', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/auth.py", line 264, in _resolve_authconfig_credstore
  File "docker/credentials/store.py", line 35, in get
  File "docker/credentials/store.py", line 93, in _execute
docker.credentials.errors.StoreError: Credentials store docker-credential-desktop.exe exited with "".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 126, in perform_command
  File "compose/cli/main.py", line 1070, in up
  File "compose/cli/main.py", line 1066, in up
  File "compose/project.py", line 615, in up
  File "compose/service.py", line 356, in ensure_image_exists
  File "compose/service.py", line 1267, in pull
  File "compose/progress_stream.py", line 99, in get_digest_from_pull
  File "compose/service.py", line 1234, in _do_pull
  File "docker/api/image.py", line 396, in pull
  File "docker/auth.py", line 48, in get_config_header
  File "docker/auth.py", line 324, in resolve_authconfig
  File "docker/auth.py", line 235, in resolve_authconfig
  File "docker/auth.py", line 281, in _resolve_authconfig_credstore
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-desktop.exe exited with "".')
[3279] Failed to execute script docker-compose

   3. docker run hello-world -> pulls latest but with warning
     /c/Program Files/Docker/Docker/resources/bin/docker-credential-desktop.exe: Invalid argument

**Comment by covertxd** [comment]
I have this issue as well. I was able to get it to work by setting `appendWindowsPath = true` in `/etc/wsl.conf`.

```conf
[automount]
enabled = true

[interop]
appendWindowsPath = true
```

I prefer to have `appendWindowsPath` disabled.

**Comment by DuboisS** [comment]
For me, have this in my **~/.docker/config.json** fixed docker-credentials errors.

```json
{
  "_credSstore": "desktop",
  "experimental": "enabled"
}
```

**Note the underscore**, without the underscore I can't `run build` ("docker-credential-desktop": executable file not found in $PATH).
If I remove the underscore, it only fixes `docker-compose`, not `docker build`

Warning, the file seems to update itself... (after docker update ? wsl --shutdown ?)

No related to my **/etc/wsl.conf** configuration where I have disable some options...
```conf
[interop]
enabled=false # enable launch of Windows binaries; default is true
appendWindowsPath=false # append Windows path to $PATH variable; default is true
```

![image](https://user-images.githubusercontent.com/29716703/99153891-eb11af80-26ab-11eb-8a66-30d8a2972e34.png)
The login is ok!

But is not normal to have to change this config.json manually...

**Comment by thgeorgiou** [comment]
Anyone knows which executables from the Windows-side are necessary for authentication to work? Enabling `appendWindowsPath` causes tab-completion on the shell to be very slow but adding some specific folder Docker needs would be no problem.

I tried adding
* `C:\Program Files\Docker\Docker\resources\bin`
* `C:\ProgramData\DockerDesktop\version-bin`

unfortunately without success.

**Comment by rlabrecque** [comment]
/remove-lifecycle stale

Remains an issue

**Comment by olivierchatry** [comment]
@thaylongs thanks ! but it did not help. Just running the command give me the same results :

**Comment by olivierchatry** [comment]
So, turn out, I installed WSl using the new app store from windows 11, and this seems to not work correctly with docker desktop. Uninstalled it ( it work alongside the normal "add remove feature" way of installing ), and then everything working find and dandy.

**Comment by bwmeier** [comment]
I was able to get it to work via changing the symlink for docker-credential-desktop.exe in the wsl /usr/bin:

``sudo ln -sf /mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-credential-desktop.exe /usr/bin``

The existing symlink pointed to a different executable that was broken:

``/usr/bin/docker-credential-desktop.exe -> /mnt/wsl/docker-desktop/cli-tools/usr/bin/docker-credential-desktop.exe``

**Comment by pys-arhs** [comment]
/remove-lifecycle stale
Still an issue.

**Comment by tlgDJPorv** [comment]
I am getting a similar error message when doing `docker pull` from WSL.  
My IT org has enabled AppLocker on Windows, and it is blocking `/usr/bin/docker-credential-desktop.exe`.

**WSL2**
```shell
$ docker pull ubuntu
Using default tag: latest
/usr/bin/docker-credential-desktop.exe: Invalid argument
latest: Pulling from library/ubuntu
Digest: sha256:26c68657ccce2cb0a31b330cb0be2b5e108d467f641c62e13ab40cbec258c68d
Status: Image is up to date for ubuntu:latest
docker.io/library/ubuntu:latest
```

**Windows Powershell**
```pwsh
Get-WinEvent 'Microsoft-Windows-AppLocker/*' -MaxEvents 100000 | Where LevelDisplayName -eq 'Error' | Format-Table -Wrap

   ProviderName: Microsoft-Windows-AppLocker

TimeCreated                     Id LevelDisplayName Message
-----------                     -- ---------------- -------
11-05-2022 12:53:36           8004 Error            \\WSL$\UBUNTU\MNT\WSL\DOCKER-DESKTOP\CLI-TOOLS\USR\BIN\DOCKER-CREDENTIAL-DESKTOP.EXE was prevented from running.
11-05-2022 12:45:17           8004 Error            \\WSL$\UBUNTU\MNT\WSL\DOCKER-DESKTOP\CLI-TOOLS\USR\BIN\DOCKER-CREDENTIAL-DESKTOP.EXE was prevented from running.
11-05-2022 11:03:33           8004 Error            \\WSL$\UBUNTU\MNT\WSL\DOCKER-DESKTOP\CLI-TOOLS\USR\BIN\DOCKER-CREDENTIAL-DESKTOP.EXE was prevented from running.
```

**Comment by PetrMc** [comment]
this solved my problem - https://forums.docker.com/t/docker-credential-desktop-exe-executable-file-not-found-in-path-using-wsl2/100225/5

```
Solution:
In ~/.docker/config.json change credsStore to credStore
```

**Comment by sliekens** [comment]
> this solved my problem - https://forums.docker.com/t/docker-credential-desktop-exe-executable-file-not-found-in-path-using-wsl2/100225/5
> 
> ```
> Solution:
> In ~/.docker/config.json change credsStore to credStore
> ```

It's not a solution. It only _appears_ to work because `"credStore"` is not a valid config key so it is ignored, docker defaults to not using a store (i.e. store credentials in plaintext). If you check the contents of your `~/.docker/config.json` again, you will find your password in readable text.

**Comment by puellanivis** [comment]
Hm… I just randomly started hitting this as well, but it’s not just `docker-credential-desktop.exe` it seems _all_ of my windows executables are dying with `Invalid argument`.

```
$ /mnt/c/Windows/System32/findstr.exe
/mnt/c/Windows/System32/findstr.exe: Invalid argument
```

**Comment by puellanivis** [comment]
FYI came across this: https://github.com/microsoft/WSL/issues/6170 seems a common problem with docker at times, but sometimes also git? 🤷‍♀️

**Comment by JustusNBB** [comment]
I just ran into this after onboarding to another project and switching IDEs. For some reason VSCode sets up the PS into WSL env without this issue, while I have to try workarounds posted here, to get it to work within IntelliJ!

**Comment by rmoreas** [comment]
> ```powershell
> Get-WinEvent 'Microsoft-Windows-AppLocker/*' -MaxEvents 100000 | Where LevelDisplayName -eq 'Error' | Format-Table -Wrap
> ```

Thanks for sharing. AppLocker was also the problem in our case!

**Comment by rmoreas** [comment]
> I am getting a similar error message when doing `docker pull` from WSL. My IT org has enabled AppLocker on Windows, and it is blocking `/usr/bin/docker-credential-desktop.exe`.
> 
> **WSL2**
> 
> ```shell
> $ docker pull ubuntu
> Using default tag: latest
> /usr/bin/docker-credential-desktop.exe: Invalid argument
> latest: Pulling from library/ubuntu
> Digest: sha256:26c68657ccce2cb0a31b330cb0be2b5e108d467f641c62e13ab40cbec258c68d
> Status: Image is up to date for ubuntu:latest
> docker.io/library/ubuntu:latest
> ```
> 
> **Windows Powershell**
> 
> ```powershell
> Get-WinEvent 'Microsoft-Windows-AppLocker/*' -MaxEvents 100000 | Where LevelDisplayName -eq 'Error' | Format-Table -Wrap
> 
>    ProviderName: Microsoft-Windows-AppLocker
> 
> TimeCreated                     Id LevelDisplayName Message
> -----------                     -- ---------------- -------
> 11-05-2022 12:53:36           8004 Error            \\WSL$\UBUNTU\MNT\WSL\DOCKER-DESKTOP\CLI-TOOLS\USR\BIN\DOCKER-CREDENTIAL-DESKTOP.EXE was prevented from running.
> 11-05-2022 12:45:17           8004 Error            \\WSL$\UBUNTU\MNT\WSL\DOCKER-DESKTOP\CLI-TOOLS\USR\BIN\DOCKER-CREDENTIAL-DESKTOP.EXE was prevented from running.
> 11-05-2022 11:03:33           8004 Error            \\WSL$\UBUNTU\MNT\WSL\DOCKER-DESKTOP\CLI-TOOLS\USR\BIN\DOCKER-CREDENTIAL-DESKTOP.EXE was prevented from running.
> ```

@tlgDJPorv thanks for sharing. AppLocker was also the problem in our case!

**Comment by masoud-maghsoudi** [comment]
> /remove-lifecycle stale

**Comment by masoud-maghsoudi** [comment]
Windows 11, Version 22H2 (OS Build 22621.1105)
Ubuntu 22.04 under WSL2
Docker version 20.10.22, build 3a2c30b

I am still having this issue

/remove-lifecycle stale

**Comment by parzydlo** [comment]
@sliekens's suggestion finally fixed the problem for me where all previously mentioned fixes failed

**Comment by mtjrider** [comment]
I am not sure if this helps anyone, but none of the recommended fixes or workarounds solved this issue for me.
I am on Windows 11 using Docker Desktop 4.25.0 with the following version printed from Ubuntu WSL.
```
$ docker --version
Docker version 24.0.6, build ed223bc
```

To fix the `invalid argument` error, I did the following:
1. Opened Docker Desktop
2. Navigated to **Settings** (upper right cog wheel)
3. Under the **Resources** menu, select _WSL Integration_
4. Check _**Enable integration with my default WSL distro**_ **and** _**Ubuntu**_
5. Shutdown WSL at the command-line with `wsl --shutdown`
6. Quit Docker Desktop

After restarting Docker Desktop and the WSL distribution, the credential-store errors vanished. See the image below for what my configuration looks like in the Docker Desktop GUI.

It seems odd to me that I would have to explicitly enable Ubuntu when the default WSL distro was enabled.

![image](https://github.com/docker/for-win/assets/13078940/7050935f-9803-4bc5-8d0b-59823cc009b6)
