### ISSUE TITLE
Docker desktop with WSL 2 on Windows 10 fails to initialize every time for me.

### ISSUE THREAD

**Issue by ajdavids** [docker/for-win#9076]
See title. I always get this error:

```log
[01:24:58.726][DailyHeartbeat    ][Warning] Failed to send heartbeat: System.NullReferenceException: Object reference not set to an instance of an object.
   at Docker.Core.Cli.CliOptionsLoader.Get() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Core\cli\CliOptionsLoader.cs:line 33
   at Docker.ApiServices.Analytics.DailyHeartbeat.<GenerateMetadataAndResetAsync>d__43.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\Analytics\DailyHeartbeat.cs:line 250
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.Analytics.DailyHeartbeat.<DoSendHeartbeatAsync>d__42.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\Analytics\DailyHeartbeat.cs:line 217
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.Analytics.DailyHeartbeat.<<TriggerHeartBeatSend>b__40_0>d.MoveNext() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\Analytics\DailyHeartbeat.cs:line 188
```

**Comment by blackmore466** [comment]
Same issue. I guess it related with WSL2
