### ISSUE TITLE
Docker Desktop crashing on startup, yet also working until I quit the crash dialogue

### ISSUE THREAD

**Issue by danwhitston** [docker/for-win#9124]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: CA4F0817-F4D3-4891-91FD-65E6D26E8765/20201019152331

### Expected behavior

Docker starts on Windows start, after default install, without throwing errors.

### Actual behavior

```
System.NullReferenceException:
Object reference not set to an instance of an object.
   at Docker.Core.Cli.CliOptionsLoader.Get() in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Core\cli\CliOptionsLoader.cs:line 33
   at Docker.Program.Run(IReadOnlyCollection`1 args) in C:\workspaces\stable-2.4.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 327
```

This error gets thrown. Strangely, the UI and services appear to load successfully despite this. However, clicking the Quit button to close the dialogue quits the Docker UI and attempting to re-open it causes the same error to be thrown again.

I've tried uninstalling and reinstalling, and that hasn't changed the behaviour. 

### Information

  - Windows Version: 10, build 19041
  - Docker Desktop Version: 2.4.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

I'm running a default WSL 2 and Docker install on a fresh Dell XPS 15 with Windows 10 Home, and oodles of memory and disk space.

### Steps to reproduce the behavior

The problem lies some distance before this. To reproduce, install WSL 2, Docker desktop, and any necessary integrations for those two, then turn on the computer.

**Comment by danwhitston** [comment]
Unsure how but I've fixed it. I think picking the option to reset the defaults may have been the thing that did the trick.
