### ISSUE TITLE
netcfg -d results in docker error of 

### ISSUE THREAD

**Issue by wanfuse123** [docker/for-win#9221]
netcfg -d results in the error. How do I fix?

System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\hiken\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: There are no more endpoints available from the endpoint mapper.

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

**Comment by wanfuse123** [comment]
Version: 2.4.2.0 (48975)
Channel: edge
Sha1: d7fa31b7c7697a2d8efe9c009f4446ad40ab6336
Started on: 2020/10/24 19:50:40.353
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2004
Build: 20241
BuildLabName: 20241.1000.amd64fre.rs_prerelease.201016-1450
File: C:\Users\mememe\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[19:50:40.519][GUI               ][Info   ] Starting...
[19:50:40.580][GUI               ][Warning] Failed to configure docker scan: Newtonsoft.Json.JsonSerializationException: No JSON content found. Path '', line 1, position 72.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target, JsonSerializerSettings settings)
   at Docker.Core.Cli.ScanOptionsLoader.Configure(String snykPath) in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Core\cli\ScanOptionsLoader.cs:line 18
   at Docker.Program.CheckDockerScanConfigFile(Logger logger) in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Program.cs:line 166
[19:50:40.603][ComponentVersions ][Info   ] Edition community
[19:50:40.611][ComponentVersions ][Info   ] Edition community
[19:50:40.701][LoggingMessageHandler][Info   ] [65c9ed79] <GoBackendClient start> GET http://localhost/ping
[19:50:40.768][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[19:50:41.076][LoggingMessageHandler][Info   ] [3aa48392] <GoBackendClient start> GET http://localhost/ping
[19:50:41.076][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[19:50:41.193][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[19:50:41.255][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[19:50:41.378][LoggingMessageHandler][Info   ] [6fbbe9a8] <GoBackendClient start> GET http://localhost/ping
[19:50:41.431][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[19:50:41.445][GoBackendProcess  ][Info   ] Started
[19:50:41.447][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[19:50:41.452][SegmentApi        ][Info   ] Usage statistic: Identify
[19:50:41.596][GoBackendProcess  ][Info   ] msg="starting backend server"
[19:50:41.597][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[19:50:41.597][GoBackendProcess  ][Info   ] msg="started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl"
[19:50:41.603][GoBackendProcess  ][Error  ] msg="unable to query WslEngineEnabled state after 0s. Last error was Get \"http://unix/settings\": open \\\\.\\pipe\\dockerWebApiServer: The system cannot find the file specified."
[19:50:41.604][GoBackendProcess  ][Info   ] msg="listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection"
[19:50:41.604][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\docker_cli
[19:50:41.605][GoBackendProcess  ][Info   ] msg="adding routes for /docker.tar"
[19:50:41.605][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[19:50:41.605][GoBackendProcess  ][Info   ] msg="adding routes for /kube-images.tar"
[19:50:41.608][GoBackendProcess  ][Info   ] msg="adding routes for /docker.tar"
[19:50:41.608][GoBackendProcess  ][Info   ] msg="adding routes for /kube-images.tar"
[19:50:41.610][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[19:50:41.732][LoggingMessageHandler][Info   ] [428c45a3] <GoBackendClient start> GET http://localhost/ping
[19:50:41.773][GoBackendProcess  ][Info   ] msg="external: GET /ping 200 \"\" \"\""
[19:50:41.804][LoggingMessageHandler][Info   ] [428c45a3] <GoBackendClient end> GET http://localhost/ping -> 200 OK (took 71ms)
[19:50:41.824][GoBackendClient   ][Info   ] backend API ready
[19:50:41.825][LoggingMessageHandler][Info   ] [aa9de651] <GoBackendClient start> GET http://localhost/features
[19:50:41.829][GoBackendProcess  ][Info   ] msg="external: GET /features 200 \"\" \"\""
[19:50:41.832][LoggingMessageHandler][Info   ] [aa9de651] <GoBackendClient end> GET http://localhost/features -> 200 OK (took 7ms)
[19:50:42.072][SegmentApi        ][Info   ] Usage statistic: appLaunched
[19:50:42.088][SegmentApi        ][Info   ] Usage statistic: heartbeat
[19:50:42.524][LoggingMessageHandler][Info   ] [82464607] <BackendAPIClient start> GET http://backend/version
[19:50:42.539][LoggingMessageHandler][Info   ] [82464607] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 14ms)
[19:50:42.561][LoggingMessageHandler][Info   ] [91c359d1] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[19:50:42.569][LoggingMessageHandler][Info   ] [91c359d1] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 7ms)
[19:50:42.581][LoggingMessageHandler][Info   ] [9d3099e9] <BackendAPIClient start> POST http://backend/migrate/app
[19:50:42.586][LoggingMessageHandler][Info   ] [9d3099e9] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 4ms)
[19:50:42.596][Engines           ][Debug  ] Starting
[19:50:42.616][LoggingMessageHandler][Info   ] [125a506f] <BackendAPIClient start> POST http://backend/versionpack/enable
[19:50:42.680][LoggingMessageHandler][Info   ] [125a506f] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 63ms)
[19:50:42.686][LoggingMessageHandler][Info   ] [f17ccf43] <BackendAPIClient start> POST http://backend/cloudcli/toggle
[19:50:42.700][LoggingMessageHandler][Info   ] [f17ccf43] <BackendAPIClient end> POST http://backend/cloudcli/toggle -> 204 NoContent (took 14ms)
[19:50:42.716][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[19:50:42.718][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[19:50:42.726][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxWSL2
[19:50:42.735][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1603583442}
[19:50:42.736][SystrayNotifications][Info   ] Docker is starting
[19:50:42.749][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[19:50:42.759][LoggingMessageHandler][Info   ] [604bab22] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[19:50:43.614][LoggingMessageHandler][Info   ] [89e42e40] <Server start> GET http://unix/settings
[19:50:43.666][WSL2Provisioning  ][Info   ] Checking docker-desktop
[19:50:43.674][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\mememe\AppData\Local\Docker\wsl\distro
[19:50:43.674][Updater           ][Info   ] Launcher process exited with 4294967295
[19:50:43.760][LoggingMessageHandler][Info   ] [604bab22] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 1001ms)
[19:50:43.841][LoggingMessageHandler][Info   ] [89e42e40] <Server end> GET http://unix/settings -> 200 OK (took 226ms)
[19:50:46.408][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\mememe\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: There are no more endpoints available from the endpoint mapper.


 stderr: 
[19:50:46.419][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[19:50:46.431][GoBackendProcess  ][Info   ] msg="NewSharer: WSL2 engine is enabled so no file sharer is required."
[19:50:46.431][GoBackendProcess  ][Info   ] msg="enabling filesystem caching"
[19:50:46.431][GoBackendProcess  ][Info   ] msg="filesystem exports are:  (2)"
[19:50:46.432][GoBackendProcess  ][Info   ] msg="volume control server listening on \\\\.\\pipe\\dockerVolume"
[19:50:46.435][GoBackendProcess  ][Info   ] msg="filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3"
[19:50:46.435][GoBackendProcess  ][Info   ] msg="file ownership will be determined by the calling user (\"fake owner\" mode)"
[19:50:46.435][GoBackendProcess  ][Info   ] msg="using mfsymlinks"
[19:50:46.756][LinuxWSL2Engine   ][Info   ] Stopping engine
[19:50:46.903][LoggingMessageHandler][Info   ] [bb8b8aa2] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[19:50:48.630][LoggingMessageHandler][Info   ] [bb8b8aa2] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 1726ms)
[19:50:49.428][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[19:50:49.428][LoggingMessageHandler][Info   ] [58f9969d] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[19:50:49.694][LoggingMessageHandler][Info   ] [58f9969d] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 266ms)
[19:50:49.944][WSL2Provisioning  ][Info   ] Checking docker-desktop
[19:50:49.944][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\mememe\AppData\Local\Docker\wsl\distro
[19:50:55.469][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\mememe\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: There are no more endpoints available from the endpoint mapper.


 stderr: 
[19:50:55.470][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[19:50:56.014][GUI               ][Info   ] Bugsnag report d7426998-cc21-4f35-90b9-0638a40bca09 sent
[19:50:56.016][SegmentApi        ][Info   ] Usage statistic: eventCrash
[19:50:56.038][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[19:50:56.295][Engines           ][Error  ] Start failed with Failed to deploy distro docker-desktop to C:\Users\mememe\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: There are no more endpoints available from the endpoint mapper.


 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__21.MoveNext() in C:\workspaces\master\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 102)
[19:50:56.408][GoBackendProcess  ][Info   ] msg="external: GET /events 200 \"Go-http-client/1.1\" \"\""
[19:50:56.410][GoBackendProcess  ][Info   ] msg="external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\""
[19:50:56.418][GoBackendProcess  ][Info   ] msg="external: GET /ping 200 \"Go-http-client/1.1\" \"\""
[19:53:34.671][ErrorReportWindow ][Info   ] Open logs

**Comment by wanfuse123** [comment]
4CDD3BA5-A32F-4128-9561-6ADD93D1A1FD/20201027001651


Note: I issued netdfg -d because Internet Connection Sharing Service seemed to be putting a stop to docker working on port 53
