### ISSUE TITLE
Docker Desktop 2.4.2.0 installation failed

### ISSUE THREAD

**Issue by cjus** [docker/for-win#9274]
```
Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The module was expected to contain an assembly manifest.
   at CommunityInstaller.EnableFeaturesAction.DoAsync(CancellationToken cancelToken)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__25.MoveNext()
```

  - [x] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Flawless installation

### Actual behavior
Installation failed.

### Information
Please, help us understand the problem.  For instance:
  - Is it reproducible? Absolutely
  - Is the problem new? Yes
  - Did the problem appear with an update? Yes
  - A reproducible case if this is a bug, Dockerfiles with reproduction inside is best.

  - Windows Version: Windows 10 Pro
  - Docker Desktop Version: 2.4.2.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior
A reproducible case, Dockerfiles with reproduction inside is best.

  1. run installer

**Comment by Riiiiika** [comment]
Met the same issue with even the very similar env, powershell version is 7, any comments?

**Comment by cng00** [comment]
I have the same problem when installing on Windows 10 Enterprise.

Component CommunityInstaller.EnableFeaturesAction failed
Exception type: System.IO.FileLoadException, Exception message: Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Access is denied., StackTrace:
   at CommunityInstaller.EnableFeaturesAction.DoAsync(CancellationToken cancelToken)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__32.MoveNext()
[11:19:43.431][InstallWorkflow] Installation failed
Exception type: System.IO.FileLoadException, Exception message: Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Access is denied., StackTrace:
   at CommunityInstaller.EnableFeaturesAction.DoAsync(CancellationToken cancelToken)
   at CommunityInstaller.InstallWorkflow.<HandleD4WPackageAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__27.MoveNext()

**Comment by cjus** [comment]
I waited a week and retried the download and install. Perhaps there was an update. All good now.

**Comment by swhkn** [comment]
I encountered same problem. Fixed it by manually Install WSL 2 first before installing Docker. And then on Docker Installation I unchecked the "Install WSL 2 feature on Windows" option
