### ISSUE TITLE
Unable to update Docker

### ISSUE THREAD

**Issue by casufi** [docker/for-win#9382]
### Information

  - Windows Version: 18363
  - Docker Desktop Version: 2.3.0.2 (45183)

> `Version: 2.3.0.2 (45183)
> Channel: stable
> Sha1: e9b671cd3cb844cb63ad6fd7c79a4d15424233c4
> Started on: 2020/11/03 14:41:31.772
> Resources: C:\Program Files\Docker\Docker\resources
> OS: Windows 10 Enterprise
> Edition: Enterprise
> Id: 1909
> Build: 18363
> BuildLabName: 18362.1.amd64fre.19h1_release.190318-1202
> File: C:\Users\vkotulskyi\AppData\Local\Docker\install-log.txt
> CommandLine: "C:\Program Files\Docker\Docker\InstallerCli.exe" -k -p
> You can send feedback, including this log file, at https://github.com/docker/for-win/issues
> [14:41:32.166][ComponentVersions ][Info   ] Edition community
> [14:41:32.199][Installer         ][Info   ] Killing processes...
> [14:41:32.215][Installer         ][Info   ] Killing existing Docker Desktop process with PID 10404
> [14:41:32.315][Installer         ][Error  ] Access is denied
> [14:41:32.775] [UninstallWorkflow] Action CommunityInstaller.ExecAction failed
> Exception type: System.InvalidOperationException, Exception message: Process InstallerCli.exe exited with code 1, StackTrace:
>    at CommunityInstaller.ExecAction.<DoAsync>d__28.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__12.MoveNext()
> [14:41:32.791] [InstallWorkflow] Installation failed
> Exception type: System.InvalidOperationException, Exception message: Process InstallerCli.exe exited with code 1, StackTrace:
>    at CommunityInstaller.ExecAction.<DoAsync>d__28.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at CommunityInstaller.UninstallWorkflow.<ProcessAsync>d__12.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at CommunityInstaller.InstallWorkflow.<PerformUninstall>d__28.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at CommunityInstaller.InstallWorkflow.<HandlePrePackagedExeAsync>d__26.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at CommunityInstaller.InstallWorkflow.<ProcessAsync>d__24.MoveNext()
> [14:41:32.795] [InstallWorkflow] Rollbacking component CommunityInstaller.DownloadStep
>

**Comment by casufi** [comment]
Why it was closed?
