### ISSUE TITLE
Docker Desktop is failing to load after latest update

### ISSUE THREAD

**Issue by adi-mohan** [docker/for-win#9442]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 3A162DB3-82F2-4F32-BC47-EAE3A470D600/20201109060821

### Expected behavior
Error-less startup
### Actual behavior
Startup is failing due to some issue in LinuxWSL2 integration
### Information

  - Windows Version: 2004, OS Build 19041.572
  - Docker Desktop Version: 2.5.0.0 (49427)
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: Windows on a laptop, natively. Also for WSL2 Ubuntu

### Steps to reproduce the behavior

  1. ...
  2. ...

Logs:
Docker.Engines.WSL2.WSL2ErrorFoundInLogsException:
Error found in logs indicating startup will most likely fail: Error creating 000-metadata: exit status 1
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

**Comment by adi-mohan** [comment]
With the latest Windows feature update 20H2, the Docker Desktop is working fine.
