### ISSUE TITLE
Docker Not Starting Error OS:Windows 10 Home FeaturesEnabled: Hyper V WSL 2 

### ISSUE THREAD

**Issue by Leontking** [docker/for-win#9644]
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\abhia\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: {Application Error}

The exception s (0x
 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92

**Comment by Leontking** [comment]
pLEAse Help

**Comment by Litvinovis** [comment]
You cannot install Docker for Windows on Windows 10 Home according to the documentation.
System Requirements:

> Windows 10 64bit: Pro, Enterprise or Education (1607 Anniversary Update, Build 14393 or later).
> 
> Note: If your system does not meet the requirements to run Docker for Windows, you can install Docker Toolbox, which uses Oracle Virtual Box instead of Hyper-V.

**Comment by Leontking** [comment]
> You cannot install Docker for Windows on Windows 10 Home according to the documentation.
> System Requirements:
> 
> > Windows 10 64bit: Pro, Enterprise or Education (1607 Anniversary Update, Build 14393 or later).
> > Note: If your system does not meet the requirements to run Docker for Windows, you can install Docker Toolbox, which uses Oracle Virtual Box instead of Hyper-V.
> 
> You can either upgrade your Windows 10 version or follow [recipe](https://medium.com/@mbyfieldcameron/docker-on-windows-10-home-edition-c186c538dff3)

What!!!!!!!!!!!!!!!!!!

**Comment by Leontking** [comment]
> > You cannot install Docker for Windows on Windows 10 Home according to the documentation.
> > System Requirements:
> > > Windows 10 64bit: Pro, Enterprise or Education (1607 Anniversary Update, Build 14393 or later).
> > > Note: If your system does not meet the requirements to run Docker for Windows, you can install Docker Toolbox, which uses Oracle Virtual Box instead of Hyper-V.
> > 
> > 
> > You can either upgrade your Windows 10 version or follow [recipe](https://medium.com/@mbyfieldcameron/docker-on-windows-10-home-edition-c186c538dff3)
> 
> What!!!!!!!!!!!!!!!!!!

There is a windows 10 home versison In docker Hub I installed It it is giving Me error

**Comment by Leontking** [comment]
Windows toolbox is not available It is deprecated Where and how to download it @Litvinovis

**Comment by Leontking** [comment]
Please Tell Me a way To download Docker_toolbox?

**Comment by Leontking** [comment]
Closest 
Duplicate of #9643

**Comment by Leontking** [comment]
I Even see that there is no such folder called c:/resources

**Comment by Leontking** [comment]
Ok

**Comment by Leontking** [comment]
I got Link For it

**Comment by Leontking** [comment]
I will reply and close this if it works

**Comment by Leontking** [comment]
No it say Hyper-V Installed Error

**Comment by Leontking** [comment]
I restarted My computer 10000 Times Today

**Comment by stephen-turner** [comment]
@Litvinovis Where did you find this documentation? Docker Desktop has worked on Windows 10 Home for some time now. If we still have documentation contradicting that, please let us know where and we will remove it.

@Leontking I suspect WSL 2 isn't installed properly, which is a prerequisite. What does `wsl -l` or `wsl -d Ubuntu` do? If you need help installing WSL 2, try this page from Microsoft: https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by andrewpalumbo** [comment]
I'm having the same issues after following the instructions on  https://docs.microsoft.com/en-us/windows/wsl/install-win10 to install  `WSL 2`:

It doesnt seem that the `WSL2` installed correctly.  

After :`wsl --set-default Ubuntu` 

`Ubuntu` is my Default:
```PS C:\windows\system32> wsl -l -v                                                                                         NAME          STATE           VERSION
* Ubuntu        Stopped         1
  kali-linux    Stopped         1
  ```

When setting `Ubuntu` to version 2:
```
PS C:\windows\system32> wsl --set-version Ubuntu 2                                                                      Conversion in progress, this may take a few minutes...
For information on key differences with WSL 2 please visit https://aka.ms/wsl2
{Application Error}
The exception s (0x
PS C:\windows\system32>
```
Possible that the WSL2 distro was not fully installed?


The error i get Starting `docker-desktop`:

```
System.InvalidOperationException:
Failed to deploy distro docker-desktop to C:\Users\andy\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: {Application Error}

The exception s (0x
 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15138\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
```

No Hypervisor running:
```
PS C:\windows\system32> Get-WindowsOptionalFeature -Online | ? State -eq Enabled


FeatureName : Printing-PrintToPDFServices-Features
State       : Enabled

FeatureName : Printing-XPSServices-Features
State       : Enabled

FeatureName : TelnetClient
State       : Enabled

FeatureName : TFTP
State       : Enabled

FeatureName : NetFx3
State       : Enabled

FeatureName : WCF-Services45
State       : Enabled

FeatureName : WCF-TCP-PortSharing45
State       : Enabled

FeatureName : MediaPlayback
State       : Enabled

FeatureName : WindowsMediaPlayer
State       : Enabled

FeatureName : SmbDirect
State       : Enabled

FeatureName : Internet-Explorer-Optional-amd64
State       : Enabled

FeatureName : MicrosoftWindowsPowerShellV2Root
State       : Enabled

FeatureName : MicrosoftWindowsPowerShellV2
State       : Enabled

FeatureName : SearchEngine-Client-Package
State       : Enabled

FeatureName : MSRDC-Infrastructure
State       : Enabled

FeatureName : WorkFolders-Client
State       : Enabled

FeatureName : Printing-Foundation-Features
State       : Enabled

FeatureName : FaxServicesClientPackage
State       : Enabled

FeatureName : Printing-Foundation-InternetPrinting-Client
State       : Enabled

FeatureName : Microsoft-Windows-Subsystem-Linux
State       : Enabled

FeatureName : VirtualMachinePlatform
State       : Enabled

FeatureName : Microsoft-Windows-NetFx3-OC-Package
State       : Enabled

FeatureName : Microsoft-Windows-NetFx4-US-OC-Package
State       : Enabled

FeatureName : Microsoft-Windows-Client-EmbeddedExp-Package
State       : Enabled

FeatureName : Microsoft-Windows-NetFx3-WCF-OC-Package
State       : Enabled

FeatureName : Microsoft-Windows-NetFx4-WCF-US-OC-Package
State       : Enabled

FeatureName : Windows-Defender-ApplicationGuard
State       : Enabled

FeatureName : NetFx4-AdvSrvs
State       : Enabled

FeatureName : NetFx4Extended-ASPNET45
State       : Enabled

FeatureName : Containers
State       : Enabled



PS C:\windows\system32>                                              
```

**Comment by stephen-turner** [comment]
Yes, it looks like there are problems with your WSL 2 installation, independent of Docker.

**Comment by digitalave** [comment]
I also experiencing the same issue. and done everything. So, disappointed. Docker being buggy with WSL2
![image](https://user-images.githubusercontent.com/48489828/114754976-c44cc780-9d76-11eb-8760-1216c83324b7.png)
