### ISSUE TITLE
Switch to Windows Containers fails with error 'Object reference not set to an instance of an object'

### ISSUE THREAD

**Issue by vikaspal71** [docker/for-win#967]
### Expected behavior
Switch to Windows Containers setting should switch the container to Windows one from Linux container
### Actual behavior
Switch to Windows Containers fails with error 'Object reference not set to an instance of an object'
### Information
226D6E43-EA3B-464D-8EFF-F2FE31E45C26/2017-08-01_14-14-38 is uploaded
  - Diagnostic ID from "Diagnose & Feedback" in the menu.
  - a reproducible case if this is a bug, Dockerfiles FTW
  - page URL if this is a docs issue or the name of a man page
  - host distribution and version (Windows version, build number, etc)

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by c2TheOlin** [comment]
[14:25:06.064][NamedPipeServer][Error  ] Unable to execute Start: Object reference not set to an instance of an object.    at Docker.Backend.Processes.WindowsDockerDaemon.StopLogging() in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\Processes\WindowsDockerDaemon.cs:line 82
   at Docker.Backend.ContainerEngine.Windows.Start(Settings settings) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Backend\ContainerEngine\Windows.cs:line 77
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass9_0.<Register>b__0(Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 46
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters) in C:\gopath\src\github.com\docker\pinata\win\src\Docker.Core\pipe\NamedPipeServer.cs:line 145
[14:25:06.079][NamedPipeClient][Error  ] Unable to send Start: Object reference not set to an instance of an object.
