### ISSUE TITLE
Network connectivity in container breaks and docker can't restart

### ISSUE THREAD

**Issue by beckermarc** [docker/for-win#9740]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: E0B966CF-3984-4F14-831D-6CFC657754D1/20201209123146

### Expected behavior

I would expect the network access to remain stable and docker desktop to restart without running into timeouts.

### Actual behavior

Since a few days I am experiencing issues with Docker Desktop on Windows. After some time the network connection in my container suddenly breaks and I am not able to access other servers in my network. I am connected to my company's VPN and can neither access resources on the internet, nor in our corporate network from my container anymore.

I have also observed, that sometimes after the connectivity breaks, the vpnkit-bridge.exe process is consuming a lot of CPU time.
Also in these cases commands like `docker run -it ubuntu:20.04 /bin/bash` start to hang indefinitely.
If there are additional log files I can gather in these situations, please let me know where to find them.

After restarting docker everything usually works again and breaks again after an hour or so.
Sometimes however restarting docker crashes with the diagnostics information attached to this incident (E0B966CF-3984-4F14-831D-6CFC657754D1/20201209123146). A subsequent startup usually works without problems.

```
System.TimeoutException:
Timed out waiting for the lifecycle-server to start.
This may be the result of a slow environment or there may be a real problem.
This timeout can be increased by editing settings.json, value 'lifecycleTimeoutSeconds'.
This file is usually in C:\Users\(your username)\AppData\Roaming\Docker
   at Docker.ApiServices.LifecycleClient.<WaitForServerUpAsync>d__8.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\LifecycleClient.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<RestartAsync>d__26.MoveNext() in C:\workspaces\stable-2.5.x\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 266
```

### Information

  - Windows Version: 1909 (18363.1198)
  - Docker Desktop Version: 2.5.0.1
  - I am using the WSL2 environment

The problem did not appear after an update of Docker. My assumption is that a change in Windows, our VPN or my corporate firewall might be the cause of this issue. Therefore I hope to get some additional details, what is going wrong inside Docker, to further understand the problem. Although those assumptions don't really explain, that it works for some time and then breaks suddenly...

### Steps to reproduce the behavior

n/a

**Comment by adnoh** [comment]
same symtoms here but without wsml. I could'nt connect to the internet from within containers suddently, and after trying to update docker it doesn't start anymore... totally doomed :( I guess some "nice" windows update - again?

**Comment by beckermarc** [comment]
For future reference: In my case the issue was caused by McAfee's MVISION EDR Client. They also document the incompatibility with docker here: https://kb.mcafee.com/corporate/index?page=content&id=KB90041
