### ISSUE TITLE
Docker for windows: Update hangs and dies

### ISSUE THREAD

**Issue by Madpeterz** [docker/for-win#9762]
### Expected behavior
Update to work correctly 

### Actual behavior
```
exit code 1
   at CommunityInstaller.InstallWorkflow.<>c__DisplayClass25_0.<HandlePrePackagedExeAsync>b__0()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<HandlePrePackagedExeAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

a popup asking if I want to update,
I hit accept and it hangs and dies with a stuck process scroller at the bottom

### Info
Unable to give version details as the install is now broken.

**Comment by mat007** [comment]
Hi, thanks for the report. Can you take a look at `%LOCALAPPDATA%\Docker\install-log.txt` (or `.2`, …) to see if there is an error inside?
