### ISSUE TITLE
Docker Desktop 3.0.0 failed under Windows 10

### ISSUE THREAD

**Issue by dputerity** [docker/for-win#9772]
Failed to register product: The operation being requested was not performed because the user has not logged on to the network. The specified service does not exist. (Exception from HRESULT: 0x800704DD)
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()

**Comment by chuoke** [comment]
Same issue. I can't start it too after updated to v3.

**Comment by elpluto** [comment]
Same issue for me, any ideas.

**Comment by croudet** [comment]
Same issue when upgrading from 3.0.0 to 3.0.4

**Comment by infacc** [comment]
Same after upgrading to 3.0.4. Reinstalling or [downgrading](https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-300) doesn't work either.

After the update to 3.0.4 I couldn't start Docker, only the whale would appear for a second in the system tray. 
Further the Windows search didn't seem to find Docker.
The corresponding log (`%USERPROFILE%\AppData\Local\Docker\log.txt`):
```
Version: 3.0.4 (51218)
Sha1: abd615e73fd8667bab468026e72bac31c59c14de
Started on: 2021/01/12 10:29:07.071
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2009
Build: 19042
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\user\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[10:29:07.140][GUI               ][Info   ] Starting...
[10:29:07.194][ComponentVersions ][Info   ] Edition community
[10:29:07.194][ComponentVersions ][Info   ] Edition community
[10:29:07.240][LoggingMessageHandler][Info   ] [fdb4bad1] <GoBackendClient start> GET http://localhost/ping
[10:29:07.256][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[10:29:07.356][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[10:29:07.372][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[10:29:07.394][GoBackendProcess  ][Info   ] Started
[10:29:07.394][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[10:29:07.394][SegmentApi        ][Info   ] Usage statistic: Identify
[10:29:07.456][GoBackendProcess  ][Info   ] msg="starting backend server"
[10:29:07.456][GoBackendProcess  ][Info   ] msg="started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl"
[10:29:07.456][GoBackendProcess  ][Info   ] msg="listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection"
[10:29:07.456][GoBackendProcess  ][Error  ] msg="unable to query WslEngineEnabled state after 0s. Last error was Get \"http://unix/settings\": open \\\\.\\pipe\\dockerWebApiServer: The system cannot find the file specified."
[10:29:07.456][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[10:29:07.456][GoBackendProcess  ][Info   ] msg="adding routes for /docker.tar"
[10:29:07.456][GoBackendProcess  ][Info   ] msg="adding routes for /kube-images.tar"
[10:29:07.456][GoBackendProcess  ][Info   ] msg="adding routes for /docker.tar"
[10:29:07.456][GoBackendProcess  ][Info   ] msg="adding routes for /kube-images.tar"
[10:29:07.456][GoBackendProcess  ][Info   ] msg="adding routes for /services.tar -> C:\\Program Files\\Docker\\Docker\\resources\\services.tar"
[10:29:07.456][GoBackendProcess  ][Info   ] msg="adding routes for /services.tar -> C:\\Program Files\\Docker\\Docker\\resources\\services.tar"
[10:29:07.456][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\docker_cli
[10:29:07.456][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[10:29:07.456][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[10:29:07.580][LoggingMessageHandler][Info   ] [4e83bafe] <GoBackendClient start> GET http://localhost/ping
[10:29:07.592][GoBackendProcess  ][Info   ] msg="external: GET /ping 200 \"DockerDesktopCSharp\" \"\""
[10:29:07.602][LoggingMessageHandler][Info   ] [4e83bafe] <GoBackendClient end> GET http://localhost/ping -> 200 OK (took 21ms)
[10:29:07.608][GoBackendClient   ][Info   ] backend API ready
[10:29:07.608][LoggingMessageHandler][Info   ] [16ba1e04] <GoBackendClient start> GET http://localhost/features
[10:29:07.609][GoBackendProcess  ][Info   ] msg="external: GET /features 200 \"DockerDesktopCSharp\" \"\""
[10:29:07.610][LoggingMessageHandler][Info   ] [16ba1e04] <GoBackendClient end> GET http://localhost/features -> 200 OK (took 2ms)
[10:29:07.663][SegmentApi        ][Info   ] Usage statistic: appLaunched
[10:29:07.668][SegmentApi        ][Warning] Failed to Identify: An error occurred while sending the request.
[10:29:07.668][SegmentApi        ][Warning] Failed to track event appLaunched: An error occurred while sending the request.
[10:29:07.668][SegmentApi        ][Info   ] Usage statistic: heartbeat
[10:29:07.669][SegmentApi        ][Warning] Failed to track event heartbeat: An error occurred while sending the request.
[10:29:07.836][GUI               ][Error  ] Error getting credentials: error getting credentials - err: exec: "docker-credential-wincred.exe": executable file not found in %PATH%, out: ``
```

When reinstalling the following error message is shown:

```
Failed to register product: The operation being requested was not performed because the user has not logged on to the network. The specified service does not exist. (Exception from HRESULT: 0x800704DD)
   at CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
```

`%USERPROFILE%\AppData\Local\Docker\install-log.txt`:
```
Started on: 2021/01/12 10:50:47.739
File: C:\Users\user\AppData\Local\Docker\install-log.txt
CommandLine: "C:\Users\user\Downloads\Docker Desktop Installer.exe" 
[10:50:47.739][ManifestAndExistingInstallationLoader] No install path specified, looking for default installation registry key
[10:50:47.739][Program] No installation found
[10:50:47.749][ProcessEnvironmentDetector] Not run as admin, relaunching with UAC prompt
```

For every reinstall I need to uninstall Docker via the Control Panel with a warning:

![warning screenshot](https://i.imgur.com/3h2nIT4.png)

**Comment by LandOfToz** [comment]
Still getting this issue after trying to install v3.2.2 as Administrator.  Has anyone found a resolution yet?

**Comment by aeabijl** [comment]
Same here, I get the same issue as well. Doesn't matter if I'm installing through Chocolatey or use the installer.

**Comment by jeffrson** [comment]
Same here. This is the log I got when installing from an elevated command prompt:
```
[10:05:48.599] [Program] No installation found
[10:05:48.770] [InstallWorkflow] Using package: res:DockerDesktop
[10:05:48.772] [InstallWorkflow] Downloading
[10:05:49.650] [InstallWorkflow] Extracting manifest
Failed to track the installer started event, caused by: Fehler beim Senden der Anforderung.[10:05:50.310] [InstallWorkflow] Manifest found: version=61853, displayVersion=3.2.2, channelUrl=https://desktop.docker.com/win/stable/amd64/appcast.xml
[10:05:50.311] [InstallWorkflow] Checking prerequisites
[10:05:50.640] [InstallWorkflow] Unpacking artifacts
[10:07:27.142] [InstallWorkflow] Deploying component CommunityInstaller.CreateGroupAction
[10:07:27.439] [InstallWorkflow] Deploying component CommunityInstaller.AddToGroupAction
[10:07:27.454] [InstallWorkflow] Deploying component CommunityInstaller.EnableFeaturesAction
[10:07:27.946] [InstallWorkflow] Deploying component CommunityInstaller.ServiceAction
[10:07:27.950] [InstallWorkflow-ServiceAction] Removing service
[10:07:27.953] [InstallWorkflow-ServiceAction] Creating service
[10:07:29.555] [InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
[10:07:29.590] [InstallWorkflow-ShortcutAction] Creating shortcut: C:\ProgramData\Microsoft\Windows\Start Menu\Docker Desktop.lnk/Docker Desktop
[10:07:29.658] [InstallWorkflow] Deploying component CommunityInstaller.ShortcutAction
[10:07:29.660] [InstallWorkflow-ShortcutAction] Creating shortcut: C:\Users\user\Desktop\Docker Desktop.lnk/Docker Desktop
[10:07:29.663] [InstallWorkflow] Deploying component CommunityInstaller.AutoStartAction
[10:07:29.665] [InstallWorkflow] Deploying component CommunityInstaller.PathAction
[10:07:30.135] [InstallWorkflow] Deploying component CommunityInstaller.PathAction
[10:07:30.674] [InstallWorkflow] Deploying component CommunityInstaller.ExecAction
[10:07:32.754] [InstallWorkflow] Registering product
[10:07:32.761] [InstallWorkflow] Cancel pending background download
[10:07:32.786] [InstallWorkflow] Installation failed
Exception type: System.Exception, Exception message: Failed to register product: Der angeforderte Vorgang konnte nicht ausgeführt werden, da der Benutzer nicht am Netzwerk angemeldet ist. Der angegebene Dienst ist nicht vorhanden. (Ausnahme von HRESULT: 0x800704DD), StackTrace:
   bei CommunityInstaller.InstallWorkflow.<DoHandleD4WPackageAsync>d__29.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei CommunityInstaller.InstallWorkflow.<DoProcessAsync>d__23.MoveNext()
[10:07:32.797] [InstallWorkflow] Rollbacking component CommunityInstaller.ExecAction
[10:07:32.798] [InstallWorkflow] Rollbacking component CommunityInstaller.PathAction
[10:07:33.261] [InstallWorkflow] Rollbacking component CommunityInstaller.PathAction
[10:07:33.693] [InstallWorkflow] Rollbacking component CommunityInstaller.AutoStartAction
[10:07:33.694] [InstallWorkflow] Rollbacking component CommunityInstaller.ShortcutAction
[10:07:33.696] [InstallWorkflow] Rollbacking component CommunityInstaller.ShortcutAction
[10:07:33.700] [InstallWorkflow] Rollbacking component CommunityInstaller.ServiceAction
[10:07:34.708] [InstallWorkflow] Rollbacking component CommunityInstaller.EnableFeaturesAction
[10:07:34.710] [InstallWorkflow] Rollbacking component CommunityInstaller.AddToGroupAction
[10:07:34.712] [InstallWorkflow] Rollbacking component CommunityInstaller.CreateGroupAction
[10:07:34.716] [InstallWorkflow] Rollbacking component CommunityInstaller.UnpackArtifactsStep
[10:07:34.726] [FileSystem] Deleting C:\Program Files\Docker\Docker
[10:07:35.014] [FileSystem] Deleted C:\Program Files\Docker\Docker successfully
[10:07:35.015] [InstallWorkflow] Rollbacking component CommunityInstaller.ExtractManifestStep
[10:07:35.017] [InstallWorkflow] Rollbacking component CommunityInstaller.DownloadStep
```

Unfortunately I decided to do the announced update for 3.2.2 yesterday. Now I cannot run Docker for Desktop anymore.

BTW, I'm a bit "worried" about the lack of an "official" response since december...

**Comment by by-Exist** [comment]
I'm having the same problem. Hope this will be resolved soon.
