### ISSUE TITLE
Microsoft.DotNet.Docker.CommandLineClientException: Creating network "dockercompose_default" with the default driver {"message":"HNS failed with error : The parameter is incorrect.

### ISSUE THREAD

**Issue by Softwaremaker** [docker/for-win#978]
### Information

docker version:
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.2-ee-5
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   fa09039
 Built:        Wed Jul 19 23:56:45 2017
 OS/Arch:      windows/amd64

docker-compose version 1.9.0dev, build 466ebb6
docker-py version: 1.10.6
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2h  3 May 2016

Windows Server 2016 DC on a VM in Azure
HyperV (nested virtualization) and Containers enbabled
Visual Studio 2017 ver 15.2 installed
.NET Core Tooling/SDK installed

docker images - a
microsoft/aspnetcore          1.1                 bff3f324b4c7        20 hours ago        1.221 GB
microsoft/aspnetcore          <none>              bff3f324b4c7        20 hours ago        1.221 GB
microsoft/windowsservercore   latest              2c42a1b4dea8        3 weeks ago         10.24 GB
microsoft/windowsservercore   <none>              2c42a1b4dea8        3 weeks ago         10.24 GB

### Steps to reproduce the behavior

  1. Created a simple default .NET Core ASPNET Web Application (Docker support)
  2. Solution builds successfully.
  3. Run it on Docker from Visual Studio will get build error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "PrepareForLaunch" task failed unexpectedly.
Microsoft.DotNet.Docker.CommandLineClientException: Creating network "dockercompose1364920800_default" with the default driver
{"message":"HNS failed with error : The parameter is incorrect. "}.

For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting ---> Microsoft.DotNet.Docker.CommandLineClientException: Creating network "dockercompose1364920800_default" with the default driver
{"message":"HNS failed with error : The parameter is incorrect. "}
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.DockerComposeClient.<ExecuteAsync>d__18.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DotNet.Docker.DockerComposeClient.<ExecuteAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.DockerWorkspace.<PrepareForLaunchAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DotNet.Docker.BuildTasks.DockerBaseTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\Docker\Microsoft.VisualStudio.Docker.Compose.targets	192	

I have checked from so many threads in forums on this error but nothing proposed can successfully build this simple ASPNET Core on VS2017/WS2016/Auzre.

What am I missing ? Thanks !

**Comment by jamesmbourne** [comment]
Looking at the version information of the Docker client and server, it appears your client is a few versions behind the server.

I'm not well versed in the compatibility between versions of the API but I would suggest updating your client to match or supersede the server version as a first step.
