### ISSUE TITLE
Docker Desktop cannot start on Windows 10 on ARM

### ISSUE THREAD

**Issue by mannok** [docker/for-win#9955]
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: A22E3255-3A41-4312-A6BF-5E7D37E0669F/20201229160839

### Expected behavior
Docker Desktop will be shown successfully.

### Actual behavior
Crashed when starting WSL2. An Error dialog prompted up and here is the exception stacktrace:
```
System.BadImageFormatException:
Could not load file or assembly 'Microsoft.Management.Infrastructure.Native, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. An attempt was made to load a program with an incorrect format.
   at Microsoft.Management.Infrastructure.CimSession.Create(String computerName, CimSessionOptions sessionOptions)
   at Docker.Core.InfrastructureObjectScopeProvider.CreateRootCimV2() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Core\InfrastructureObjectScopeProvider.cs:line 18
   at Docker.Backend.Features.Installer.GetFeatureInfoMaps(Feature[] features) in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Backend\Features\Installer.cs:line 44
   at Docker.Backend.Features.Installer.GetFeatureReport(Feature[] features) in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Backend\Features\Installer.cs:line 32
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

### Information

  - Windows Version: Windows 10 on ARM Home Insider Preview Version 2004 (OS Build 21277.1000) -> x64 emulation enabled
  - Docker Desktop Version: 3.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

**Comment by stephen-turner** [comment]
Correct, it doesn't run on Windows on Arm. It's not just work we would have to do, there are also lots of our dependencies missing. I was going to direct you to the roadmap issue, docker/roadmap#91, but I see you've already found it.
