### ISSUE TITLE
Docker desktop stops during startup

### ISSUE THREAD

**Issue by dagalb** [docker/for-win#9968]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 912B020F-11E1-4E3B-A479-43D86D30DED5/20201230133913

### Expected behavior

Docker Desktop should start normally

### Actual behavior

Docker Desktop startup hangs for a couple of minutes and then the process stops by itself. 
Log snippet:

[14:35:18.084][LifecycleClient   ][Info   ] Lifecycle-server is responding.
[14:35:18.134][LinuxWSL2Engine   ][Info   ] Starting Docker service...
[14:35:18.134][LoggingMessageHandler][Info   ] [08de68ca] <LifecycleClient start> GET http://localhost/docker/start
[14:35:18.158][LoggingMessageHandler][Info   ] [ccb5ed59] <Server start> GET http://unix/settings/linux-daemon
[14:35:18.160][LoggingMessageHandler][Info   ] [ccb5ed59] <Server end> GET http://unix/settings/linux-daemon -> 200 OK (took 1ms)
[14:35:18.161][GoBackendProcess  ][Info   ] msg="internal: GET /engine/daemon.json 200 \"Go-http-client/1.1\" \"\""
[14:35:23.218][VpnKit            ][Info   ] vpnkit.exe: Connected Ethernet interface f6:16:36:bc:f9:c6
[14:35:23.218][VpnKit            ][Info   ] vpnkit.exe: UDP interface connected on 192.168.65.1
[14:35:23.233][LoggingMessageHandler][Info   ] [dc84ea93] <Server start> GET http://unix/settings
[14:35:23.237][LoggingMessageHandler][Info   ] [dc84ea93] <Server end> GET http://unix/settings -> 200 OK (took 4ms)
[14:35:23.238][GoBackendProcess  ][Info   ] msg="internal: GET /vm/gatewayip 200 \"DockerDesktopGo\" \"\""
[14:35:23.704][VpnKitBridge      ][Info   ] msg="received ack for service docker, publishing locally"
[14:36:59.166][LifecycleClient   ][Error  ] HttpOS Client: Exception:Cancellation token triggered before we finished reading from the stream.
[14:36:59.167][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StopTransition to state change sink
[14:36:59.167][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StopTransition sent to state change sink
[14:36:59.167][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StopTransition from LinuxWSL2
[14:36:59.167][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"updating","Mode":"linux","date":1609335419}
[14:36:59.167][SystrayNotifications][Info   ] Docker Desktop is stopping...

if i try to restart, i get this:

System.Threading.Tasks.TaskCanceledException:
Cancellation token triggered before we finished reading from the stream.
   at HttpOverStream.ByLineReader.<ReadLineAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HttpOverStream.Client.DialMessageHandler.<SendAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.Logging.LoggingMessageHandler.<SendAsync>d__4.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Core\Logging\LoggingMessageHandler.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Core.HttpClientExtensions.<GetJsonAsync>d__0`1.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Core\HttpClientExtensions.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.LifecycleClient.<DockerStartAsync>d__10.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\LifecycleClient.cs:line 122
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.LinuxkitDaemonStartup.<StartAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\LinuxkitDaemonStartup.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<RestartAsync>d__26.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 266

### Information

It's the third time it happens in the last 3 weeks. One day it starts and works fine, next day this happens without any conceivable reason. Only workaround so far, if it can be called a workaround, is resetting factory defaults and reinstalling all images and containers, which takes hours in my specific case.
I am using WSL 2

  - Windows Version: Windows 10 Home
  - Docker Desktop Version: 3.0.0
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM: No

### Steps to reproduce the behavior

Unfortunately, it seems totally random.

**Comment by dagalb** [comment]
this workaround worked for me 👍 

https://github.com/docker/for-win/issues/9755#issuecomment-748539590
