### ISSUE TITLE
Docker desktop not running

### ISSUE THREAD

**Issue by surumi2020** [docker/for-win#9986]
Version: 3.0.0 (50684)
Sha1: b7108cdfefccc66549bd6b9ee3373e8dd40b8ac1
Started on: 2021/01/03 16:06:36.147
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2004
Build: 19041
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\surum\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[16:06:36.225][GUI               ][Info   ] Starting...
[16:06:36.256][ComponentVersions ][Info   ] Edition community
[16:06:36.272][ComponentVersions ][Info   ] Edition community
[16:06:36.303][LoggingMessageHandler][Info   ] [92eb67ff] <GoBackendClient start> GET http://localhost/ping
[16:06:36.345][LoggingMessageHandler][Info   ] [92eb67ff] <GoBackendClient end> GET http://localhost/ping -> 200 OK (took 45ms)
[16:06:36.345][GoBackendClient   ][Info   ] backend API ready
[16:06:36.408][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[16:06:36.408][GUI               ][Info   ] An instance is already running. Launching the container view.
[16:06:37.049][LoggingMessageHandler][Info   ] [d9d665c1] <Server end> POST http://localhost/electron/containers -> 200 OK (took 633ms)
[16:06:37.395][LoggingMessageHandler][Info   ] [bcb1180a] <Server start> POST http://localhost/notifications/subscriptions
[16:06:37.441][LoggingMessageHandler][Info   ] [bdcb79a0] <NotificationsClient start> GET http://localhost/ping
[16:06:37.457][LoggingMessageHandler][Info   ] [bdcb79a0] <NotificationsClient end> GET http://localhost/ping -> 200 OK (took 8ms)
[16:06:37.457][LoggingMessageHandler][Info   ] [bcb1180a] <Server end> POST http://localhost/notifications/subscriptions -> 200 OK (took 58ms)
[16:06:40.117][GoBackendProcess  ][Info   ] msg="external: GET /features 200 \"axios/0.20.0\" \"\""
[16:06:40.122][LoggingMessageHandler][Info   ] [a263d881] <Server start> GET http://localhost/versions
[16:06:40.126][LoggingMessageHandler][Info   ] [88736dcf] <Server start> GET http://localhost/license/details
[16:06:40.138][LoggingMessageHandler][Info   ] [14fc3d34] <Server start> GET http://localhost/kubernetes
[16:06:40.139][LoggingMessageHandler][Info   ] [39a7740b] <Server start> GET http://localhost/registry/user
[16:06:40.141][LoggingMessageHandler][Info   ] [39a7740b] <Server end> GET http://localhost/registry/user -> 500 InternalServerError (took 1ms)
[16:06:40.142][LoggingMessageHandler][Info   ] [a263d881] <Server end> GET http://localhost/versions -> 200 OK (took 19ms)
[16:06:40.142][LoggingMessageHandler][Info   ] [14fc3d34] <Server end> GET http://localhost/kubernetes -> 200 OK (took 3ms)
[16:06:40.142][LoggingMessageHandler][Info   ] [88736dcf] <Server end> GET http://localhost/license/details -> 200 OK (took 16ms)
[16:06:40.143][GoBackendProcess  ][Info   ] msg="external: GET /system/editor 200 \"axios/0.20.0\" \"\""
[16:06:40.147][LoggingMessageHandler][Info   ] [c08f93f5] <Server start> GET http://localhost/docker
[16:06:40.148][LoggingMessageHandler][Info   ] [c08f93f5] <Server end> GET http://localhost/docker -> 200 OK (took 1ms)
[16:06:40.171][GoBackendProcess  ][Info   ] msg="external: GET /features 200 \"axios/0.20.0\" \"\""
[16:07:06.797][GoBackendProcess  ][Info   ] msg="received new cli usage: {Command:run Context:moby}"
[16:07:06.800][LoggingMessageHandler][Info   ] [bd285526] <Server start> POST http://unix/usage/cli
[16:07:06.803][LoggingMessageHandler][Info   ] [bd285526] <Server end> POST http://unix/usage/cli -> 200 OK (took 2ms)
[16:07:06.804][GoBackendProcess  ][Info   ] msg="cli: POST /usage 200 \"Go-http-client/1.1\" \"\""
[16:09:01.836][SegmentApi        ][Info   ] Usage statistic: actionMenuRestart
[16:09:01.836][App               ][Info   ] User clicked on restart
[16:09:01.840][SystrayNotifications][Info   ] Docker Desktop is restarting...
[16:09:01.848][SegmentApi        ][Info   ] Usage statistic: actionRestart
[16:09:01.848][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StoppedState to state change sink
[16:09:01.848][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StoppedState sent to state change sink
[16:09:01.848][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[16:09:01.848][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[16:09:01.848][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[16:09:01.848][LoggingMessageHandler][Info   ] [ee464605] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[16:09:01.848][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StoppedState from LinuxWSL2
[16:09:01.848][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"stopped","Mode":"linux","date":1609679341}
[16:09:01.848][SystrayNotifications][Info   ] Docker has stopped
[16:09:01.848][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxWSL2
[16:09:01.848][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1609679341}
[16:09:01.848][SystrayNotifications][Info   ] Docker is starting
[16:09:01.848][LoggingMessageHandler][Info   ] [f75c4214] <NotificationsClient start> POST http://localhost/engine/state
[16:09:01.864][LoggingMessageHandler][Info   ] [f75c4214] <NotificationsClient end> POST http://localhost/engine/state -> 200 OK (took 22ms)
[16:09:01.864][LoggingMessageHandler][Info   ] [17118ffb] <NotificationsClient start> POST http://localhost/engine/state
[16:09:01.879][LoggingMessageHandler][Info   ] [17118ffb] <NotificationsClient end> POST http://localhost/engine/state -> 200 OK (took 9ms)
[16:09:01.895][WSL2Provisioning  ][Info   ] Checking docker-desktop
[16:09:01.895][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\surum\AppData\Local\Docker\wsl\distro
[16:09:01.942][LoggingMessageHandler][Info   ] [ee464605] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 90ms)
[16:09:02.037][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\surum\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

For information please visit https://aka.ms/wsl2-install

 stderr: 
[16:09:02.037][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[16:09:02.084][LinuxWSL2Engine   ][Info   ] Stopping engine
[16:09:02.119][LoggingMessageHandler][Info   ] [477338b9] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[16:09:02.510][LoggingMessageHandler][Info   ] [477338b9] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 390ms)
[16:09:02.616][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[16:09:02.616][LoggingMessageHandler][Info   ] [cc1df814] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[16:09:02.656][WSL2Provisioning  ][Info   ] Checking docker-desktop
[16:09:02.656][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\surum\AppData\Local\Docker\wsl\distro
[16:09:02.656][LoggingMessageHandler][Info   ] [cc1df814] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 41ms)
[16:09:02.796][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\surum\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

For information please visit https://aka.ms/wsl2-install

 stderr: 
[16:09:02.796][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[16:09:02.836][LinuxWSL2Engine   ][Info   ] Stopping engine
[16:09:02.856][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[16:09:02.856][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[16:09:02.856][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxWSL2
[16:09:02.866][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1609679342}
[16:09:02.866][LoggingMessageHandler][Info   ] [b2f85f85] <NotificationsClient start> POST http://localhost/engine/state
[16:09:02.866][SystrayNotifications][Error  ] System.InvalidOperationException: Failed to deploy distro docker-desktop to C:\Users\surum\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

For information please visit https://aka.ms/wsl2-install

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
[16:09:02.866][GUI               ][Info   ] Sending Bugsnag report 1547d2fe-d8e1-4424-94bb-1ce628ebafba...
[16:09:02.866][LoggingMessageHandler][Info   ] [b2f85f85] <NotificationsClient end> POST http://localhost/engine/state -> 200 OK (took 7ms)
[16:09:02.907][GUI               ][Info   ] Bugsnag report 1547d2fe-d8e1-4424-94bb-1ce628ebafba sent
[16:09:02.907][SegmentApi        ][Info   ] Usage statistic: eventCrash
[16:09:02.907][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[16:09:02.924][SystrayNotifications][Error  ] System.InvalidOperationException: Failed to deploy distro docker-desktop to C:\Users\surum\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

For information please visit https://aka.ms/wsl2-install

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<RestartAsync>d__26.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 266
[16:09:02.996][GUI               ][Info   ] Sending Bugsnag report 63616fc8-cc2e-4eff-b9dc-bfe1444b14e1...
[16:09:03.016][GUI               ][Info   ] Bugsnag report 63616fc8-cc2e-4eff-b9dc-bfe1444b14e1 sent
[16:09:03.016][SegmentApi        ][Info   ] Usage statistic: eventCrash
[16:09:03.016][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[16:09:03.076][GoBackendProcess  ][Info   ] msg="external: GET /diagnostics/goroutines 200 \"Go-http-client/1.1\" \"\""
[16:09:03.076][GoBackendProcess  ][Info   ] msg="external: GET /events 200 \"DockerDesktopGo\" \"\""
[16:09:03.077][GoBackendProcess  ][Info   ] msg="external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\""
[16:09:03.084][GoBackendProcess  ][Info   ] msg="external: GET /ping 200 \"DockerDesktopGo\" \"\""
[16:09:03.193][GoBackendProcess  ][Info   ] msg="external: GET /diagnostics/goroutines 200 \"Go-http-client/1.1\" \"\""
[16:09:03.194][GoBackendProcess  ][Info   ] msg="external: GET /events 200 \"DockerDesktopGo\" \"\""
[16:09:03.195][GoBackendProcess  ][Info   ] msg="external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\""
[16:09:03.203][GoBackendProcess  ][Info   ] msg="external: GET /ping 200 \"DockerDesktopGo\" \"\""

**Comment by surumi2020** [comment]
Docker desktop is not running in windows 10 pro. above is the log file
