### ISSUE TITLE
crashing while starting

### ISSUE THREAD

**Issue by SameerC87** [docker/for-win#9987]
- [ ] I have tried with the latest version of my channel (Stable or Edge)
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID: 2004

### Actual behavior
Version: 3.0.0 (50684)
Sha1: b7108cdfefccc66549bd6b9ee3373e8dd40b8ac1
Started on: 2021/01/03 14:42:05.945
Resources: C:\Program Files\Docker\Docker\resources
OS: Windows 10 Pro
Edition: Professional
Id: 2004
Build: 19041
BuildLabName: 19041.1.amd64fre.vb_release.191206-1406
File: C:\Users\surum\AppData\Local\Docker\log.txt
CommandLine: "C:\Program Files\Docker\Docker\Docker Desktop.exe" 
You can send feedback, including this log file, at https://github.com/docker/for-win/issues
[14:42:06.007][GUI               ][Info   ] Starting...
[14:42:06.054][ComponentVersions ][Info   ] Edition community
[14:42:06.054][ComponentVersions ][Info   ] Edition community
[14:42:06.101][LoggingMessageHandler][Info   ] [e7d4f1e3] <GoBackendClient start> GET http://localhost/ping
[14:42:06.117][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[14:42:06.226][AppMigrator       ][Info   ] Current version: 6. Latest version: 6
[14:42:06.242][GoBackendProcess  ][Info   ] Starting C:\Program Files\Docker\Docker\resources\com.docker.backend.exe -addr unix:\\.\pipe\dockerBackendApiServer
[14:42:06.429][LoggingMessageHandler][Info   ] [b67f0e3c] <GoBackendClient start> GET http://localhost/ping
[14:42:06.429][GoBackendClient   ][Warning] HttpOS Client: connection timed out.
[14:42:06.476][GoBackendProcess  ][Info   ] Started
[14:42:06.476][TrackingSettings  ][Info   ] Crash report and usage statistics are enabled
[14:42:06.476][SegmentApi        ][Info   ] Usage statistic: Identify
[14:42:06.575][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerVpnKitControl
[14:42:06.575][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\docker_cli
[14:42:06.575][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServerForGuest
[14:42:06.575][GoBackendProcess  ][Info   ] ⇨ http server started on \\.\pipe\dockerBackendApiServer
[14:42:06.576][GoBackendProcess  ][Info   ] msg="starting backend server"
[14:42:06.577][GoBackendProcess  ][Info   ] msg="started port-forwarding control server on \\\\.\\pipe\\dockerVpnKitControl"
[14:42:06.577][GoBackendProcess  ][Info   ] msg="listening on unix:\\\\.\\pipe\\dockerVpnkitData for data connection"
[14:42:06.577][GoBackendProcess  ][Error  ] msg="unable to query WslEngineEnabled state after 0s. Last error was Get \"http://unix/settings\": open \\\\.\\pipe\\dockerWebApiServer: The system cannot find the file specified."
[14:42:06.577][GoBackendProcess  ][Info   ] msg="adding routes for /docker.tar"
[14:42:06.577][GoBackendProcess  ][Info   ] msg="adding routes for /kube-images.tar"
[14:42:06.577][GoBackendProcess  ][Info   ] msg="adding routes for /services.tar -> C:\\Program Files\\Docker\\Docker\\resources\\services.tar"
[14:42:06.577][GoBackendProcess  ][Info   ] msg="adding routes for /docker.tar"
[14:42:06.577][GoBackendProcess  ][Info   ] msg="adding routes for /kube-images.tar"
[14:42:06.577][GoBackendProcess  ][Info   ] msg="adding routes for /services.tar -> C:\\Program Files\\Docker\\Docker\\resources\\services.tar"
[14:42:06.741][LoggingMessageHandler][Info   ] [ecdd7eb9] <GoBackendClient start> GET http://localhost/ping
[14:42:06.753][GoBackendProcess  ][Info   ] msg="external: GET /ping 200 \"DockerDesktopCSharp\" \"\""
[14:42:06.768][LoggingMessageHandler][Info   ] [ecdd7eb9] <GoBackendClient end> GET http://localhost/ping -> 200 OK (took 25ms)
[14:42:06.775][GoBackendClient   ][Info   ] backend API ready
[14:42:06.775][LoggingMessageHandler][Info   ] [afc1162d] <GoBackendClient start> GET http://localhost/features
[14:42:06.776][GoBackendProcess  ][Info   ] msg="external: GET /features 200 \"DockerDesktopCSharp\" \"\""
[14:42:06.779][LoggingMessageHandler][Info   ] [afc1162d] <GoBackendClient end> GET http://localhost/features -> 200 OK (took 3ms)
[14:42:06.859][SegmentApi        ][Info   ] Usage statistic: appLaunched
[14:42:06.864][SegmentApi        ][Info   ] Usage statistic: heartbeat
[14:42:12.110][LoggingMessageHandler][Info   ] [9c6b295a] <BackendAPIClient start> GET http://backend/version
[14:42:12.172][LoggingMessageHandler][Info   ] [786547fa] <Server start> GET http://unix/settings
[14:42:12.485][LoggingMessageHandler][Info   ] [9c6b295a] <BackendAPIClient end> GET http://backend/version -> 200 OK (took 369ms)
[14:42:12.583][LoggingMessageHandler][Info   ] [a9112d9e] <BackendAPIClient start> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx
[14:42:12.650][LoggingMessageHandler][Info   ] [a9112d9e] <BackendAPIClient end> GET http://backend/hyperv/vhdx-size?path=C:%5CProgramData%5CDockerDesktop%5Cvm-data%5CDockerDesktop.vhdx -> 200 OK (took 71ms)
[14:42:12.650][LoggingMessageHandler][Info   ] [0cab1e60] <BackendAPIClient start> POST http://backend/migrate/app
[14:42:12.666][LoggingMessageHandler][Info   ] [0cab1e60] <BackendAPIClient end> POST http://backend/migrate/app -> 204 NoContent (took 7ms)
[14:42:12.744][LoggingMessageHandler][Info   ] [786547fa] <Server end> GET http://unix/settings -> 200 OK (took 568ms)
[14:42:12.799][GoBackendProcess  ][Info   ] msg="NewSharer: WSL2 engine is enabled so no file sharer is required."
[14:42:12.799][GoBackendProcess  ][Info   ] msg="enabling filesystem caching"
[14:42:12.799][GoBackendProcess  ][Info   ] msg="filesystem exports are:  (2)"
[14:42:12.799][GoBackendProcess  ][Info   ] msg="volume control server listening on \\\\.\\pipe\\dockerVolume"
[14:42:12.801][GoBackendProcess  ][Info   ] msg="filesystem server listening on 00000000-0000-0000-0000-000000000000:00001003-facb-11e6-bd58-64006a7986d3"
[14:42:12.801][GoBackendProcess  ][Info   ] msg="file ownership will be determined by the calling user (\"fake owner\" mode)"
[14:42:12.801][GoBackendProcess  ][Info   ] msg="using mfsymlinks"
[14:42:14.205][Updater           ][Info   ] Launcher process exited with 4294967295
[14:42:14.205][Engines           ][Debug  ] Starting
[14:42:14.221][LoggingMessageHandler][Info   ] [48df99d0] <BackendAPIClient start> POST http://backend/versionpack/enable
[14:42:14.299][LoggingMessageHandler][Info   ] [48df99d0] <BackendAPIClient end> POST http://backend/versionpack/enable -> 204 NoContent (took 85ms)
[14:42:14.299][LoggingMessageHandler][Info   ] [70d82749] <BackendAPIClient start> POST http://backend/cloudcli/toggle
[14:42:14.315][LoggingMessageHandler][Info   ] [70d82749] <BackendAPIClient end> POST http://backend/cloudcli/toggle -> 204 NoContent (took 7ms)
[14:42:14.315][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.StartTransition to state change sink
[14:42:14.315][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.StartTransition sent to state change sink
[14:42:14.315][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.StartTransition from LinuxWSL2
[14:42:14.330][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"starting","Mode":"linux","date":1609674134}
[14:42:14.330][SystrayNotifications][Info   ] Docker is starting
[14:42:14.330][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[14:42:14.330][LoggingMessageHandler][Info   ] [6d852dfb] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[14:42:14.440][WSL2Provisioning  ][Info   ] Checking docker-desktop
[14:42:14.440][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\surum\AppData\Local\Docker\wsl\distro
[14:42:14.549][LoggingMessageHandler][Info   ] [6d852dfb] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 217ms)
[14:42:15.569][Updater           ][Info   ] Launcher process exited with 4294967295
[14:42:18.376][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\surum\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

For information please visit https://aka.ms/wsl2-install

 stderr: 
[14:42:18.392][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[14:42:18.423][LinuxWSL2Engine   ][Info   ] Stopping engine
[14:42:18.477][LoggingMessageHandler][Info   ] [0eb3ef27] <BackendAPIClient start> POST http://backend/windowsfeatures/check
[14:42:18.777][LoggingMessageHandler][Info   ] [0eb3ef27] <BackendAPIClient end> POST http://backend/windowsfeatures/check -> 200 OK (took 299ms)
[14:42:19.009][LinuxWSL2Engine   ][Info   ] Terminating lingering processes and wsl distros and patching host file
[14:42:19.009][LoggingMessageHandler][Info   ] [29bda57d] <BackendAPIClient start> POST http://backend/dns/refresh-hosts
[14:42:19.040][LoggingMessageHandler][Info   ] [29bda57d] <BackendAPIClient end> POST http://backend/dns/refresh-hosts -> 204 NoContent (took 29ms)
[14:42:19.056][WSL2Provisioning  ][Info   ] Checking docker-desktop
[14:42:19.056][WSL2Provisioning  ][Info   ] deploying WSL distro docker-desktop to C:\Users\surum\AppData\Local\Docker\wsl\distro
[14:42:19.209][WSL2Provisioning  ][Error  ] Failed to deploy distro docker-desktop to C:\Users\surum\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

For information please visit https://aka.ms/wsl2-install

 stderr: 
[14:42:19.209][LinuxWSL2Engine   ][Info   ] Stopping windows side processes
[14:42:19.256][LinuxWSL2Engine   ][Info   ] Stopping engine
[14:42:19.278][EngineStateMachine][Debug  ] sending state Docker.ApiServices.StateMachines.FailedToStartState to state change sink
[14:42:19.278][EngineStateMachine][Debug  ] State Docker.ApiServices.StateMachines.FailedToStartState sent to state change sink
[14:42:19.278][EngineStateListener][Debug  ] received state Docker.ApiServices.StateMachines.FailedToStartState from LinuxWSL2
[14:42:19.278][EngineStateNotificationRecorder][Debug  ] Registered state {"State":"failed to start","Mode":"linux","date":1609674139}
[14:42:19.325][SystrayNotifications][Error  ] System.InvalidOperationException: Failed to deploy distro docker-desktop to C:\Users\surum\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

For information please visit https://aka.ms/wsl2-install

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
[14:42:19.341][GUI               ][Info   ] Sending Bugsnag report 7d405b71-5424-46ba-bb13-3a3801074ba5...
[14:42:19.426][GUI               ][Info   ] Bugsnag report 7d405b71-5424-46ba-bb13-3a3801074ba5 sent
[14:42:19.426][SegmentApi        ][Info   ] Usage statistic: eventCrash
[14:42:19.426][Diagnostics       ][Warning] Starting to gather diagnostics as User : 'C:\Program Files\Docker\Docker\resources\com.docker.diagnose.exe' gather.
[14:42:19.672][GoBackendProcess  ][Info   ] msg="external: GET /diagnostics/goroutines 200 \"Go-http-client/1.1\" \"\""
[14:42:19.673][GoBackendProcess  ][Info   ] msg="external: GET /events 200 \"DockerDesktopGo\" \"\""
[14:42:19.674][GoBackendProcess  ][Info   ] msg="external: GET /forwards/list 200 \"Go-http-client/1.1\" \"\""
[14:42:19.682][GoBackendProcess  ][Info   ] msg="external: GET /ping 200 \"DockerDesktopGo\" \"\""
[14:42:19.708][Engines           ][Error  ] Start failed with Failed to deploy distro docker-desktop to C:\Users\surum\AppData\Local\Docker\wsl\distro: exit code: -1
 stdout: Please enable the Virtual Machine Platform Windows feature and ensure virtualization is enabled in the BIOS.

For information please visit https://aka.ms/wsl2-install

 stderr: 
   at Docker.ApiServices.WSL2.WslShortLivedCommandResult.LogAndThrowIfUnexpectedExitCode(String prefix, ILogger log, Int32 expectedExitCode) in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\WSL2\WslCommand.cs:line 146
   at Docker.Engines.WSL2.WSL2Provisioning.<DeployDistroAsync>d__17.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.WSL2Provisioning.<ProvisionAsync>d__8.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\WSL2Provisioning.cs:line 78
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.WSL2.LinuxWSL2Engine.<DoStartAsync>d__25.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\WSL2\LinuxWSL2Engine.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.TaskExtensions.<WrapAsyncInCancellationException>d__0.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\TaskExtensions.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Docker.ApiServices.StateMachines.StartTransition.<DoRunAsync>d__5.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\StartTransition.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.ApiServices.StateMachines.EngineStateMachine.<StartAsync>d__14.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.ApiServices\StateMachines\EngineStateMachine.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Docker.Engines.Engines.<StartAsync>d__21.MoveNext() in C:\workspaces\PR-15077\src\github.com\docker\pinata\win\src\Docker.Desktop\Engines\Engines.cs:line 102)
[14:42:29.552][SegmentApi        ][Info   ] Usage statistic: actionMenuQuickStartGuide
[14:42:30.552][LoggingMessageHandler][Info   ] [568ce991] <Server start> POST http://localhost/notifications/subscriptions
[14:42:30.598][LoggingMessageHandler][Info   ] [9d6d7fe9] <NotificationsClient start> GET http://localhost/ping
[14:42:30.598][LoggingMessageHandler][Info   ] [9d6d7fe9] <NotificationsClient end> GET http://localhost/ping -> 200 OK (took 11ms)
[14:42:30.614][LoggingMessageHandler][Info   ] [568ce991] <Server end> POST http://localhost/notifications/subscriptions -> 200 OK (took 62ms)
[14:42:33.682][GoBackendProcess  ][Info   ] msg="external: GET /features 200 \"axios/0.20.0\" \"\""
[14:42:33.686][LoggingMessageHandler][Info   ] [f25c3fb2] <Server start> GET http://localhost/versions
[14:42:33.691][LoggingMessageHandler][Info   ] [3430a94d] <Server start> GET http://localhost/license/details
[14:42:33.693][LoggingMessageHandler][Info   ] [0fa72fa4] <Server start> GET http://localhost/kubernetes
[14:42:33.694][LoggingMessageHandler][Info   ] [15dedc2c] <Server start> GET http://localhost/registry/user
[14:42:33.694][LoggingMessageHandler][Info   ] [3430a94d] <Server end> GET http://localhost/license/details -> 200 OK (took 3ms)
[14:42:33.694][LoggingMessageHandler][Info   ] [f25c3fb2] <Server end> GET http://localhost/versions -> 200 OK (took 8ms)
[14:42:33.695][LoggingMessageHandler][Info   ] [15dedc2c] <Server end> GET http://localhost/registry/user -> 500 InternalServerError (took 1ms)
[14:42:33.696][LoggingMessageHandler][Info   ] [e10d4818] <Server start> GET http://localhost/docker
[14:42:33.699][LoggingMessageHandler][Info   ] [e10d4818] <Server end> GET http://localhost/docker -> 200 OK (took 2ms)
[14:42:33.699][LoggingMessageHandler][Info   ] [0fa72fa4] <Server end> GET http://localhost/kubernetes -> 200 OK (took 6ms)
[14:42:33.706][GoBackendProcess  ][Info   ] msg="external: GET /system/editor 200 \"axios/0.20.0\" \"\""
[14:42:33.708][GoBackendProcess  ][Info   ] msg="external: GET /features 200 \"axios/0.20.0\" \"\""
[14:43:00.896][LoggingMessageHandler][Info   ] [03ffc75d] <Server start> POST http://localhost/analytics/track
[14:43:00.896][LoggingMessageHandler][Info   ] [6185259b] <Server start> POST http://localhost/analytics/track
[14:43:00.896][LoggingMessageHandler][Info   ] [fe8b5403] <Server start> POST http://localhost/analytics/track
[14:43:00.897][LoggingMessageHandler][Info   ] [733d42bd] <Server start> POST http://localhost/analytics/track
[14:43:00.902][LoggingMessageHandler][Info   ] [a0d561c5] <Server start> POST http://localhost/analytics/track
[14:43:00.906][SegmentApi        ][Info   ] Usage statistic: actionFinishTutorial
[14:43:00.906][SegmentApi        ][Info   ] Usage statistic: actionFinishTutorial
[14:43:00.906][SegmentApi        ][Info   ] Usage statistic: actionFinishTutorial
[14:43:00.907][SegmentApi        ][Info   ] Usage statistic: actionFinishTutorial
[14:43:00.907][LoggingMessageHandler][Info   ] [03ffc75d] <Server end> POST http://localhost/analytics/track -> 200 OK (took 11ms)
[14:43:00.907][SegmentApi        ][Info   ] Usage statistic: actionFinishTutorial
[14:43:00.907][LoggingMessageHandler][Info   ] [6185259b] <Server end> POST http://localhost/analytics/track -> 200 OK (took 10ms)
[14:43:00.907][LoggingMessageHandler][Info   ] [a0d561c5] <Server end> POST http://localhost/analytics/track -> 200 OK (took 5ms)
[14:43:00.907][LoggingMessageHandler][Info   ] [733d42bd] <Server end> POST http://localhost/analytics/track -> 200 OK (took 10ms)
[14:43:00.907][LoggingMessageHandler][Info   ] [fe8b5403] <Server end> POST http://localhost/analytics/track -> 200 OK (took 10ms)
[14:43:31.324][LoggingMessageHandler][Info   ] [a31fbd8f] <Server start> POST http://localhost/registry/login
[14:43:31.329][LoggingMessageHandler][Info   ] [a31fbd8f] <Server end> POST http://localhost/registry/login -> 200 OK (took 4ms)
[14:43:44.422][ErrorReportWindow ][Info   ] Open logs

### Information

  - Windows Version:
  - Docker Desktop Version:
  - Are you running inside a virtualized Windows e.g. on a cloud server or on a mac VM:

### Steps to reproduce the behavior

  1. ...
  2. ...

**Comment by SoulSeekkor** [comment]
Also having a crash on startup, after updating to this new 3.0.0 version it is completely unusable on Windows 10.

**Comment by frederic-meyrou** [comment]
SAme issue here, I have latest vresion of docker for windows desktop, I start it as a task when my server boot, but this doesn't work anymore where it used to.
[GoBackendProcess  ][Error  ] msg="unable to query WslEngineEnabled state after 0s. Last error was Get \"http://unix/settings\": open \\\\.\\pipe\\dockerWebApiServer: The system cannot find the file specified."
